### ISSUE TITLE
Can't download flutterflow project

### ISSUE THREAD

**Issue by LeeSingChanYau** [FlutterFlow/flutterflow-issues#29] opened 2022-10-07 21:11 UTC
We need a solution asap. Please call me at (650)835-3525

## Expected behavior (required)
Downloading the source code of the entire project.

## Current behavior (required)
Our application has no bugs, but when we try to download the code, firebase config errors showed up (only shows when we try to download the code), and even after we reconfigured the files, it threw another error of package name miss match, and then it says fail to build and fail to download. We tried it several times and it was the same problem.
I know our application is 100% bug free, but whether there is error or not, we want to download the code immediately.
## To Reproduce (required)
1. Download source code, application has no errors
2. Firebase config errors showed up
3. Reconfigure the files
4. Firebase config errors disappear
5. Package name mismatch showed up
6. Reconfigure the files
7. Package name mismatch disppear
8. Build failed (download failed)
9. No errors in custom code
## Context (required)
We need the source code to test and deploy the app locally and on actual devices.
## Your environment
* Version of FlutterFlow used: V3.0
* Platform (e.g. Web, MacOS Desktop): MacOS
* Browser name and version: Chrome
* Operating system and version (desktop or mobile):Desktop

**Comment by bulgariamitko** [comment] 2022-10-07 21:27
Sometimes the custom code can be the reason why you can't download the project. Can you create a duplicate of this project delete all the custom code and disconnect FB and tell me if you can download the project.

**Comment by Pepino-GR** [comment] 2022-10-07 23:05
We can't work on the same issue with different id's. Can you please generate a Bug Report Code which you can get by right clicking any widget from the widget tree

**Closed** 2022-10-07 23:31 UTC
Labels: status: duplicate, status: can't reproduce
