### ISSUE TITLE
Un-setting the Update Delay (ms) field does not remove the 'Duration' statement in the source code

### ISSUE THREAD

**Issue by PieterHartog** [FlutterFlow/flutterflow-issues#2164] opened 2024-01-13 10:24 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

On TextFields, we have the property 'Update Delay (ms)'. When set, this creates a Duration(milliseconds: 2000) statement in the source code.
The problem is when I don't want a delay anymore. I delete the value in FF from the 'Update Delay' field from say 2000 ms to an empty value. However, this does not remove the Duration(milliseconds: 2000) statement from the code.

### Expected Behavior

When removing the value from the Update Delay (ms) field, it should also remove the Duration() statement in the source code.

### Steps to Reproduce

1. pick a TextField where the Update Delay (ms) field is not set yet.
2. view the source code and double check that the Duration() statement does not exist for this field.
3. for the same TextField, set the Update Delay (ms) to a value, say 1000
4. view the source code and see the Duration() statement for this field
5. now delete the value in the Update Delay (ms), so the field is empty
6. view the source code again and the Duration statement is still there.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ki87huM9NseFF7s71bfoxlmAvHGIkTL03t9VxSUgrIrbyPJkUac7BfhFBZ9+qTEFPKEWGkn4F0dbvid7xKcc3BzuBfql8zKt2cgvwXj6/aoSgDJaOZ38mM8dYCn6H06u7kB1QPvJtLWdn116leu+yY3TdHpP7Zwh9f6PHaOI=

### Context

Trying to remove the input delay on a TextField widget.

Workaround for now is to set the Delay to 0 ms.

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/37ce189a-b36f-4df5-9bc4-74a6b3ff8bfe/e6ad71ed-ee8d-4945-9701-baf26cdecfb1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zN2NlMTg5YS1iMzZmLTRkZjUtOWJjNC03NGE2YjNmZjhiZmUvZTZhZDcxZWQtZWU4ZC00OTQ1LTk3MDEtYmFmMjZjZGVjZmIxIiwiaWF0IjoxNzA3MTc4MTUyLCJleHAiOjMzMjc3NzM4MTUyfQ.0C2dx6LM7nac0PWakk8lD_uIWg8PhmZfteW5AuN4Jrk)

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: V4.0
- Platform: all
- Browser name and version: Chrome
- Operating system and version affected: Windows 11
```

**Comment by rzambroni** [comment] 2024-04-09 18:39
Hi @PieterHartog, apologies for the delay in the response. I was trying to reproduce this issue on a blank project and seems to be working fine on my end. The code is being removed after the "Update Page on Text Change" toggle is set to off. Are you still experiencing this? If not, please feel free to close this issue.

Thanks a lot!

**Closed** 2024-04-12 17:02 UTC
Labels: status: can't reproduce
