### ISSUE TITLE
FlutterFlow Portal Stucks(Blacks Out) after when trying to add custom widgets/components

### ISSUE THREAD

**Issue by narayanzzz** [FlutterFlow/flutterflow-issues#1356] opened 2023-08-25 17:15 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am facing a weird problem in Flutterflow, the problem is the screen blacks out when click on the option to add custom component or widget in the existing widget tree, because of this i am not able to use any custom widgets and components

I have tried below things

1)Duplicating the project ->Still the issue persists

2)Created fresh blank project -> I am able to add custom widgets and components

![FlutterFlow_Portal_Blackout](https://github.com/FlutterFlow/flutterflow-issues/assets/42004228/9599f5a9-2a56-429b-887e-4f44c3441c50)

### Expected Behavior

As the problem is specific to project could be some bug which is not allowing me to do so .Expected behaviour is that Flutterflow portal should not black out ,and should allow to add custom widgets and component

### Steps to Reproduce

1)Create Blank Page with Only Scaffold and Column Widget
2)In column widget try to add custom component/custom widget

Screen blacks out need to refresh to get it working again

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40l8iBx5NItbwA15D+c8Iwmik5JmIiapEe1u5RaCgofePtOol3evWlYkppZ8+4TWxle0SmmmMD+d7yjd/9Je0CFwuVf6U+/qV6dg7zfDqQa5OBPIe8fEB8L8ZVC0fD5sKG2hNNJsBidFIEwGGIJu+sSh/vK6b7IlFISq/LZO4=

### Context

Not able to add any custom code to the project
I am trying to do add custom component/widget which is the basic feature of Flutterflow

### Visual documentation

![FlutterFlow_Portal_Blackout](https://github.com/FlutterFlow/flutterflow-issues/assets/42004228/94ba49c5-c92c-4c53-8dce-660172aa470f)

### Environment

```markdown
- FlutterFlow version:v3.1
- Platform : Flutterflow Web
- Browser name and version: Microsoft Edge and Chrome 116.0.5845.111 (64-bit)
- Operating system and version affected: Windows
```

**Comment by narayanzzz** [comment] 2023-08-25 19:19
Can we pls check on this not able to proceed because of this
Have tried creating fresh project

Observation on New project:

1)Added 15 Pages
2)In all 15 pages i have added Pages from the template stored from original project
3)After 15 pages, tried adding custom component ,the screen black outs and need to restart the flutterflow

**Comment by kevintonb** [comment] 2023-09-01 06:45
Hey @narayanzzz , thank you for getting in touch with us. I am unable to reproduce this issue on my end, however this seems to be an issue that would arise due to a couple of reasons, primarily being device specific. I will provide some troubleshooting steps that might help you resolve the issue. 

1. Please check if you have sufficient speed on your internet connection and try switching to a different network if the current one is slower. 
2. Try opening your project in SAFE_MODE to identify if you have any UI that is crashing within your canvas. You can open safe mode by appending "?SAFE_MODE" at the end of the project url and loading it.
3. Please ensure that you're using the latest version on Google Chrome, as this would be the best recommended browser to develop on Flutterflow without any issues.
4. Do a hard refresh on your Google Chrome tab. You can do this by clicking on "Cmd + Shift + R", and then try to reload the project once again. Also, try to log out of your project before doing this and retry again.

As this is a device specific issue and is not reproducible, I am closing this issue for now. The github issue tracker is meant to report bugs that are evident and reproducible within the platform. However if you still keep facing the issue after following all the steps that are mentioned, please feel free to get in touch with our support team to get further assistance at support@flutterflow.io.

**Closed by kevintonb** 2023-09-01 06:45 UTC
Labels: status: needs triage

**Comment by ks233ever** [comment] 2024-02-12 18:24
Hi Guys,

I am facing the issue and am completely blocked from development. When I click on certain pages, the entire screen turns black. There were no issues the last time we were developing, and we haven't made any code updates since that version. What ended up being the solution here? Updating chrome and launching in safe mode did nothing.
