### ISSUE TITLE
Done button on the top right of the keyboard for ios

### ISSUE THREAD

**Issue by ibm777p2** [FlutterFlow/flutterflow-issues#5166] opened 2024-12-22 18:22 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

FlutterFlow does not natively provide a way to add a “Done” button at the top of the keyboard for iOS text fields. Instead, developers must manually modify the generated code (for example, using keyboard_actions or a custom accessory view) to achieve this functionality. On Android, the system’s back button or the default UI can already dismiss the keyboard, so this issue is specifically impacting iOS users.

### Expected Behavior

A built-in FlutterFlow keyboard selection  for the text field to have a “Done” button (or similar toolbar) at the top of the iOS keyboard that can hide the keyboard when tapping or to trigger an action from the button—without requiring manual edits in the exported code. This would let iOS users easily dismiss the keyboard, matching common iOS design patterns and eliminating the need for manual workarounds.

### Steps to Reproduce

1.Create a New FlutterFlow Project

2.Start a fresh project in FlutterFlow and add a page or screen.
Add a Text Field

3.On the page, add a TextFormField in FlutterFlow’s UI builder.
Attempt to select a keyboard type with the done button on the top of the keyboard for the textfield

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEez8jc34VItbwG1s/ide1aiQMwHVgjbJ0vpe5+dwsjCeOoE4Y2PuLeYVtoWOqHYX1ifFmkgl4C0trUj87DLe5fGxerc5xFzagAUxDgYF+labKOOrqKbX9BBcZQG2KM3ImjkQpAPfViLl4W3U6QPNm+b3qCf9qOYwx5e6fDbOY=

### Visual documentation

We want this
![image](https://github.com/user-attachments/assets/70884db8-6f3e-4211-b578-d9fd83f5e1ed)

We can't select this keyboard type with the done button on the top. here is the documentation
https://docs.flutterflow.io/resources/forms/textfield/

### Environment

```markdown
- FlutterFlow version: v5.0.0+
- Platform: Mobile iphone  
- Browser name and version: 131.0.6778.205
- Operating system and version affected: Mac OS Sequoia
```

**Comment by Alezanello** [comment] 2024-12-23 20:17
Hello!

You can change the **Submit Type** of the text field to options like "Done," "Next," or "Search," depending on your needs. Additionally, you can enable the **"Hide Keyboard on Tap"** feature. This ensures that the keyboard will hide when the user taps anywhere outside of the text field within the app.

Let me know if you need further assistance with this!

**Comment by ibm777p2** [comment] 2024-12-24 02:06
@Alezanello I don't think you understand what I'm requesting here, all the keyboard type doesn't  any done button on the top as shown in the picture, we need that done button because in bottom sheet doesn't hide the keyboard when you tap outside of the keyboard and in numeric keyboard doesn't have the done button neither. Please double check the requirements.

**Comment by Alezanello** [comment] 2024-12-24 14:51
Apologies for misunderstanding the issue earlier! This appears to be a duplicate of the following: [Issue #5160](https://github.com/FlutterFlow/flutterflow-issues/issues/5160).

The original issue has already been reviewed and forwarded to the engineering team for investigation and a fix.

I'll close this issue as a duplicate. Any updates will be provided on the main issue. Thank you for your understanding!

**Closed as not planned** 2024-12-24 14:52 UTC
Labels: closed: duplicate
