### ISSUE TITLE
Page State and Page Parameters issue

### ISSUE THREAD

**Issue by pascal-ferrere** [FlutterFlow/flutterflow-issues#3700] opened 2024-08-28 07:53 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The user is supposed to click on a button called "Add task" which navigates to another page where the user can select one task among a list of tasks (the data is coming from Supabase). Once the task is selected, the user is being redirected to the previous page where the selected task is being displayed. This is done by passing the Supabase Row through Page Parameters. From here two issues appear: 
1. The navigation bar simply disappears from the page for no reason. 
2. The data being passed through the Page Parameter works well the first time, but if the same action is being repeated, then the data doesn't show up. 

### Expected Behavior

The user should be able to click on a button called "Add task", which brings him to another page in order to select one task among a list of tasks. Once the task is selected, the user is being redirected to the previous page where the selected task is being displayed. The user should be able to delete the selected task and repeat the same operation to select another task. 
The navigation bar should remain on the page and the data should be passed from one page to another without any bugs. 

### Steps to Reproduce

1. Create a page with a Page Parameter expecting a Supabase Row
2. Add a another page containing a list of dynamic children with the data coming from a Supabase Query
3. Pick one item in the list and pass the data while navigating back to the first page 
4. Display the data you selected on the previous page 
5. Clear the data 
6. Repeat the operation by selecting a new item 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfz8mA24lgoctH176JKMcxjmY7JWkcTeU30+thcw4bI+LkPLAhePfsYhNDWOqHelFEHUyGpFgB/vTxuN7tCfICNTmAc4A4yJNtUxDgJXqXMZDTBs3hZXBtEf1gGG6H1runsyRBALdfLFIN2V+Uet6+b3qCf9qOYwx5e6fDbOY=

### Visual documentation

https://github.com/user-attachments/assets/82104955-d3b4-4a6b-b027-c6a3a4ed4c9d

### Environment

```markdown
- FlutterFlow version: v4.1.83
- Platform: iOS
- Browser name and version: iOS Simulator v17.4
- Operating system and version affected: macOS Sonoma 14.6.1
```

**Comment by paulperez-dev** [comment] 2024-08-28 19:17
Hi @pascal-ferrere! I noticed that you added a navigation to the tracker inside the `checkboxSelect` callback. Instead, [go back ](https://docs.flutterflow.io/concepts/navigation/page-navigation/)to the previous screen. This should solve both of the behaviors you are facing.

This is not a bug, I'm closing this ticket.

**Comment by pascal-ferrere** [comment] 2024-08-28 19:26
Hi @paulperez-dev, 

Thanks for looking into this, however I completely changed my logic and used the App State to pass the data. So what you've seen is different from the issue I was talking about. 

I cannot pass the data through the Page Parameters if I use "Go back".

**Comment by paulperez-dev** [comment] 2024-08-28 20:32
Yes, and that was the solution, to use the App State! Glad to hear it is working!

**Closed as not planned by paulperez-dev** 2024-08-28 20:32 UTC
Labels: closed: not a bug
