### ISSUE TITLE
Flutterflow doesn't recognize the type "list" supabase string array

### ISSUE THREAD

**Issue by Alde19** [FlutterFlow/flutterflow-issues#461] opened 2023-02-09 12:45 UTC
A supabase table with a column "listofinterest" type : String - Define as array : 

![image](https://user-images.githubusercontent.com/76486126/217816083-b9c67e12-b053-42fd-bf94-cb5fbeee3b00.png)

But flutterflow doesn't recognize this row as a list :

![image](https://user-images.githubusercontent.com/76486126/217816182-ee4ab4fb-6626-4f3d-b3d5-bccfb9057838.png)

**Comment by hariprasadms** [comment] 2023-02-09 18:14
Hi @Alde19 - Thanks for posting this issue. This fix coming shortly in next updates. Thanks

**Comment by hariprasadms** [comment] 2023-02-09 23:51
Hi @Alde19 - It should be fixed now. Because of supa-base limitation, array datatype wouldn't automatically select in FF while fetching schema details.. However, there is an option to select datatype now.

See this video. Thanks
https://user-images.githubusercontent.com/17435678/217964472-659486f6-6c12-48ad-96f5-bb62a9f5ce08.mp4

**Comment by Alde19** [comment] 2023-02-10 08:03
I @hariprasadms thank you for your answer. I know for this select option on FF. Before I could choose but now FF defaults to "null"

https://user-images.githubusercontent.com/76486126/218035783-b99cee25-143a-4a85-a4de-d6ce7d8bbc37.mp4

**Comment by polenvinagre** [comment] 2023-02-10 13:17
Hi! I have the same problem.
![supabase_erro_array_1](https://user-images.githubusercontent.com/50787371/218101391-c5347157-f81f-495b-a903-786352fba237.jpg)

**Comment by ramyakantd** [comment] 2023-02-11 08:31
@hariprasadms ,
Can you please share the timeline for the release? This bug is a blocker for me.

**Comment by agreaves** [comment] 2023-02-11 08:57
Sorry for this issue, we'll fix it within 24hrs.

**Comment by agreaves** [comment] 2023-02-11 09:01
Apologies, I may have spoken too soon. There is certainly a bug here but I haven't been able to reproduce it. Could anyone in this thread please share their Bug Report Code? It's necessary for me to reproduce and fix.

**Comment by Alde19** [comment] 2023-02-11 10:43
![Capture d’écran du 2023-02-11 11-39-42](https://user-images.githubusercontent.com/76486126/218253809-17c3890c-d939-41cb-b7d6-c245bea23ffd.png)

I don' know if it could help you.
Or say me how i can find bug code ?

**Comment by agreaves** [comment] 2023-02-11 17:54
To generate the Bug Report Code, please go to the widget tree, right click on one of the widgets, and click "Get Bug Report Code".

**Comment by Alde19** [comment] 2023-02-11 18:04
It generated this: IT4kivHq7ZJOvt9c187pbe14jik7NjsgTLJEoOxhYzsgF5D4BKQlPMylVBRCZ9yzaH9MClqkilkDp87UiPPfJOwpBzquGoROybVIW1yjEA8=

**Comment by ramyakantd** [comment] 2023-02-12 06:02
IT4Kl8jfx5BOxLhc0L6JbsExhmAvHDM8aIJFlu5ueE0dfZSoG7YAW/SkQE9WZ7yhdH03OWaZuDgxw/DJvczIN/I5BymCUbpm/7hMdwzvUnihMIy3CsyVdnF8FpYGSSDy

My bug report code. @agreaves

**Comment by agreaves** [comment] 2023-02-14 20:23
This should now be fixed!

**Closed by agreaves** 2023-02-14 20:23 UTC
Labels: type: bug, status: confirmed

**Comment by Alde19** [comment] 2023-02-14 21:36
Yes it's fixed. Thank you !

**Comment by polenvinagre** [comment] 2023-02-15 02:32
It is fixed. Thanks!

**Comment by ptoxxxxx** [comment] 2023-03-22 14:29
Is it supposed to be like that? There are all data types as a choice but none of them is an array/list. Therefore it's not possible to add value to the array in backend call because an arrray is not recognized.

![array data type supabase FF](https://user-images.githubusercontent.com/102899487/226936140-b7d6c03a-c6d6-4a4e-96e8-dea6d95f482a.png)

**Comment by agreaves** [comment] 2023-03-22 23:36
Hi @ptoxxxxx, can you elaborate and also include a bug report code? Thanks.
