### ISSUE TITLE
Error code 400 with Private API

### ISSUE THREAD

**Issue by sl985** [FlutterFlow/flutterflow-issues#350] opened 2023-01-13 14:07 UTC
## Expected behavior (required)
I have a problem with the Call API. When I use without the Make Private API option everything works.

## Current behavior (required)
Switching API Call to Make Private it doesn't work in the app. In the console logs I have the following error: 
`statusCode: 400, error: "ReferenceError: body is not defined`

## To Reproduce (required)
It seems to me that the problem is caused by using Body x-www-form-urlencoded. I have second API in my project, where I use in Body JSON - everything works fine with the Private API option. 

1. Register on Deepl.com (free)
2. Add new API Calls with parameters:
**Headers**
Authorization: DeepL-Auth-Key YOUR KEY

**Body**
Body: x-www-form-urlencoded
Parameters: (I use variables)
text string hello world!
source_lang string EN
target_lang string DE

### Bug Report Code (required, generate from Widget Tree)
IT4wkfLqw5R2oblE1qr+bPpVqDwWGDsmRK8klesaZCs9f5CvOpYUec/6PlpoOebgYFVAOU2Mp14zpOjnkfLlUsddPQSdb4hC/7tuZDzMeziVV8jfU/HUACkbeacOQSj6

## Context (required)
I would like the API requests to DeepL to use the private API Call, because I am storing the authorization key.

## Screenshots / recordings
I posted the screenshots on the community forum:
https://community.flutterflow.io/c/bugs/error-with-private-api

## Your environment

* Version of FlutterFlow used: 3.3.4, January 12, 2023
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version:  Chrome
* Operating system and version (desktop or mobile): Desktop

**Comment by cleanspacedev** [comment] 2023-01-13 20:43
Yeah, I have gotten the same thing since they released private API calls through the Firebase functions.  Have not been able to use it or make it work.

**Comment by Pepino-GR** [comment] 2023-01-15 11:26
@shelpert,

can you please verify?

**Comment by hariprasadms** [comment] 2023-03-02 16:09
Hi @cleanspacedev - I hope this issue is fixed in latest FF builds. We are closing this issue. Let us know if issue persists again we can re-open the issue and start investigating. Thanks

**Closed** 2023-03-02 16:09 UTC
Labels: status: needs triage

**Comment by waminos** [comment] 2023-03-09 14:25
hi @hariprasadms  @shelpert ! 
Similar issu, in my case the problem is with:
Parameters: (I use variables)
a string --> OK
b int --> OK
c  JSON --> PROBLEM  = should be like this : [{"role":"user1","content":"hi"},{"role":"user2","content":"hey you"}] , when inspecting network its:  "[{\"role\":\"user1\",\"content\":\"hi\"},{\"role\":\"user2\",\"content\":\"hey you\"}]"

need help
