### ISSUE TITLE
Paged infinite scroll with Stream sometimes only returns partial data

### ISSUE THREAD

**Issue by TemplarDesign** [FlutterFlow/flutterflow-issues#520] opened 2023-02-22 15:51 UTC
I want to have a list of users on my "admin dashboard > Manage users" section. 

## Expected behavior (required)

When an admin accesses this page and taps on the "users" section, it is supposed to load the list of all users.

## Current behavior (required)

When first loading the page, only the current user loads in the list. The admin must click back and then click the users tab again to load the list of all users.

## To Reproduce (required)
1. Login as an admin 
2. Navigate to the adminDashboard screen
3. Tap "Users". Only the current user will display
4. Tap the back icon on the top left of the app bar
5. Tap "Users" again and you'll see the full list of users.

## Context (required)

Since February 9th, I have had many conversations with Sam from FlutterFlow support chat about the issue. After almost 2 weeks of chatting with Sam about this issue, Sam recommended that I submit a bug report here. Sam stated that he has been unable to reproduce the issue.

## Screenshots / recordings

https://komododecks.com/recordings/EKVPeoMtfavYgqP6OdXN

## Your environment

* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

I have tested this across multiple and I have been able to reproduce the issue across all of these devices, internet service providers, and browsers:

- iMac, MacOS Moneterey v12.5, Xfinity internet, Chrome, Safari, and Brave browsers.
- Samsung Note20 Ultra, Android, Google Fi internet, Chrome and Internet browsers.
- iPhone 12, iOS, T-Mobile internet, Safari and Chrome browsers.
- Dell PC, Windows 10, Century link internet, Chrome and Edge browsers.

**Comment by TemplarDesign** [comment] 2023-02-27 13:45
Any update?

**Comment by TemplarDesign** [comment] 2023-03-01 14:36
@yoheisoito @katherineqian ?

**Comment by katherineqian** [comment] 2023-03-01 22:21
Hi @TemplarDesign, 

Would you mind providing us with a bug report code the user widget in your admin dashboard page to help me assess your issue? Thanks!

**Comment by TemplarDesign** [comment] 2023-03-01 23:15
IT4Cz8r13ItPsfVY0LrUbMdV/CQWNkx8RYEnmsF+VkwYHZPMCpkqdcnQXFJWUuG0THxpMU2ZjnIx/vvemvL1Kew6PRWrfKF8z6pAegrNcD6WRYyUCajpY25/Df1MCEiEy8HYsRV4GNRuLF4C6lOQGu6/dAHDGI+2C3oRLf+KC5OK2SrDX1iXc2URm05KZDPz

**Comment by TemplarDesign** [comment] 2023-03-03 13:16
?

**Comment by TemplarDesign** [comment] 2023-03-06 10:27
@katherineqian ???

**Comment by katherineqian** [comment] 2023-03-07 04:54
Hi @TemplarDesign. Unfortunately, I have tried to reproduce this in your project, but as far as I can tell the users list is loading properly on the first navigation. I understand this must be frustrating, but on my end I cannot proceed with triaging or fixing this as a bug if I cannot reproduce it at all. 

My suggestion would be to try to create reproducible steps for this bug which start as close as possible from a blank project. In other words, if you could recreate the situation you described where navigating to a page only shows 1 record, but navigating back to the page shows a full list of records. We can't give individual support through the GitHub issue tracker, so I wouldn't be able to help you further diagnose your specific problem in your project, but if you can reproduce this and provide some steps to doing so, we can re-assess this as a reproducible bug on the platform.

**Comment by TemplarDesign** [comment] 2023-03-09 19:06
<img width="639" alt="Screen Shot 2023-03-09 at 12 05 38 PM" src="https://user-images.githubusercontent.com/116034778/224128895-b83c8e14-7115-444b-bd62-a3013edd5689.png">

I hired another FlutterFlow expert to look into the issue. Neil with Protorix. He is experiencing the same problem.

**Comment by TemplarDesign** [comment] 2023-03-17 02:14
Still unresolved.

**Comment by katherineqian** [comment] 2023-03-17 20:47
Hi @TemplarDesign, I'll try again to reproduce this issue on a new project.

**Comment by katherineqian** [comment] 2023-03-21 06:35
Hi @TemplarDesign - I was able to reproduce your issue and will work on a fix for this. In the meantime, if you turn off "Listen for Changes" in your users query on the ListView, it should successfully load the full users list. I will follow up with an update on unblocking your ability to use Stream in this scenario. Thanks for your patience in the matter.

**Comment by TemplarDesign** [comment] 2023-03-22 08:25
Ok @katherineqian

**Comment by TemplarDesign** [comment] 2023-03-23 08:50
Still unresolved @katherineqian @agreaves

**Comment by katherineqian** [comment] 2023-03-25 06:38
Hi @TemplarDesign  - to confirm, did turning off Stream fix your issue?

**Comment by aemelyanovff** [comment] 2023-04-05 14:17
This bug is rather difficult to fix, unfortunately. We are not planning to work on it in the near future.

For now, I just recommend not enabling "Listen for Changes" when using infinite scroll with Firestore.

**Comment by agreaves** [comment] 2023-07-09 23:19
Closing this issue as it is stale, however this issue very well may be fixed in the upcoming release! We were not able to reproduce so it's difficult to confirm however we have updates coming to Infinite Scroll which have fixed some related issues.

**Closed by agreaves** 2023-07-09 23:19 UTC
Labels: type: bug, status: confirmed, priority: low
