### ISSUE TITLE
Unable To Signin Or Signup In Windows Desktop App

### ISSUE THREAD

**Issue by amirceo** [FlutterFlow/flutterflow-issues#2937] opened 2024-05-19 17:28 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I enter my email and password on the website it signs in but when I enter the same email and password in the desktop app it says my email or password is wrong. my accounts email is verified.

### Expected Behavior

I expect to sign in or at least signup in Windows desktop app.

### Steps to Reproduce

1. Try to sign in to windows desktop app in windows 10 I don't know how to reproduce.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

fff

### Context

I want to just sign in, why this page makes things too complicated?

### Visual documentation

![Capture](https://github.com/FlutterFlow/flutterflow-issues/assets/139783468/10ad6518-fca4-4fd0-b276-ef55fb129925)

### Environment

```markdown
- FlutterFlow version: Newest (Strangely It Dont Have Version Name!!!)
- Platform: Windows 10
- Browser name and version: Windows 10
- Operating system and version affected: windows 10 (What A Mess!!!)
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by amirceo** [comment] 2024-05-19 17:28
What a messy company!!!

**Comment by leighajarett** [comment] 2024-05-21 00:58
Oh no, sorry you're running into this! This isn't good - we're taking a look

**Comment by leighajarett** [comment] 2024-05-21 00:59
Can you please provide your email address?

**Comment by paulperez-dev** [comment] 2024-05-21 13:46
Hi @amirceo! Can you also share the version you are in? Usually, the version can be seen inside a project, but because you can't sign in, you will need to look into the settings of w10:<br><br>Settings>Apps>Installed apps

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/e583b790-d1e5-4996-962e-bddc70f6b0b3/23e5f738-946a-4bdf-a039-c7cdee2561ab?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lNTgzYjc5MC1kMWU1LTQ5OTYtOTYyZS1iZGRjNzBmNmIwYjMvMjNlNWY3MzgtOTQ2YS00YmRmLWEwMzktYzdjZGVlMjU2MWFiIiwiaWF0IjoxNzE2Mjk5MTcxLCJleHAiOjMzMjg2ODU5MTcxfQ.-0raxErYEtvCybOfI3CncnUOF00lApNF-hP4u14e5fE " alt="image.png" width="1004" height="66" />

**Comment by amirceo** [comment] 2024-05-21 14:23
It's the newest version I downloaded it yesterday from Flutterflow official
website.

**Comment by paulperez-dev** [comment] 2024-05-21 23:41
@amirceo when sign into the web, do you use a password manager to autocomplete the credentials?<br><br>In the desktop app, are you copy/pasting the password?

**Comment by amirceo** [comment] 2024-05-22 07:50
No I know my password, and copied it too.

**Comment by paulperez-dev** [comment] 2024-05-31 17:09
Hi @amirceo! Can you please verify if the issue persists in the latest release?

**Comment by amirceo** [comment] 2024-05-31 18:23
I will check it out tomorrow and let you know

**Comment by paulperez-dev** [comment] 2024-06-05 14:11
Hi @amirceo! I will close this issue by the end of the day if there is no update.

**Comment by amirceo** [comment] 2024-06-05 14:40
It don't sign in 🫤

**Comment by paulperez-dev** [comment] 2024-06-12 05:17
Hi @amirceo. Can you please try to sing in from another device?

**Comment by amirceo** [comment] 2024-06-12 08:20
No I only have access to one device

**Comment by leighajarett** [comment] 2024-06-12 20:37
Can you try and reset your password? <br><br>We unfortunately aren't able to reproduce anything or see any errors related to the sign in on your account 🙁

**Comment by amirceo** [comment] 2024-06-12 20:51
It doesn't give me errors on the website it only gives me errors on the
desktop and my Windows is Windows 10

**Comment by paulperez-dev** [comment] 2024-07-03 21:14
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Closed by paulperez-dev** 2024-07-03 21:14 UTC
Labels: status: needs triage, waiting for user response
