### ISSUE TITLE
Timer not updated with CountController value

### ISSUE THREAD

**Issue by centifanto** [FlutterFlow/flutterflow-issues#1545] opened 2023-09-28 05:36 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have Timer whose value is derived from a app state var. I also have the CountController set the value of that app state var upon tap and then rebuild the page  However, the Timer does not change value.

### Expected Behavior

Timer gets value from var set by CountController

### Steps to Reproduce

1. App state var
2. Timer widget gets value from var
3. CountController updates app state var, rebuilds page
4. Timer value does not change

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gz8rluJNPn7wA7qX2Ke9WliI4Qm1+R4c0rdluTQwjF5D4BKQUfOD4UxZoZMCzaH9cOGaWrFg0wtruvdnDUPI3BwqqQItyz5F+TRPPbECRRLanDc3pQ3Z7BeZXN3Ku4KSRhSJ+OvRZc14a31OUGOesST6Cf9qOYwx5e6fDbOY=

### Context

A timer that a user can set to check in, and upon ending it makes backend calls to delete records of them checked in

### Visual documentation

I have a small public test project that will illustrate this well. It has 3 pages:

1. One that illustrates the issue
2. One that includes my "hack", that uses a `Reset Timer` call. This works, but not ideal, as I don't want a user to accidently reset the timer
3. One that shows what I think the Timer widget should look like. I believe the current implementation of the Timer widget is useless, as there is not clean/native way for a user to update the values, and also, the ability to set the time should not be a separate widget, aka CountController

Here's the link to the public test project:
https://app.flutterflow.io/project/timer-test-6k3x55

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: Web
- Browser name and version: Brave Chromium 117.0.5938.92
- Operating system and version affected: Windows 11
```

**Comment by SameerShahzad99** [comment] 2023-09-28 19:54
@centifanto Thank you for submitting this issue, i was able to reproduce this on my end!

**Comment by joshua-ffio** [comment] 2023-10-10 19:23
Duplicate of #223 

---

Hi @centifanto !

Thank you for filing this issue, however, this is the intended behavior of the timer widget. Mainly, this is because adding the functionality to implicitly update the timer value when the page is updated could have adverse effects when the timer has already been started. Because of this, we want to give full control over the setting of the timer value and controlling the state of the timer to the user. 

Regarding the UX, it's currently set to a minimal design in order to give the most flexibility for users to build timers to their desired specs. If you think there is more that should be added to the widget, we definitely would like to hear it; so please submit your suggestion as a feature request through the FlutterFlow menu so we can correctly prioritize our feature planning.

Thanks again!

**Closed** 2023-10-10 19:24 UTC
Labels: status: duplicate, closed: not a bug
