### ISSUE TITLE
Application force quits on iPad and potentially other platforms when branching menu is clicked in specific project in account but not others

### ISSUE THREAD

**Issue by piershare** [FlutterFlow/flutterflow-issues#3902] opened 2024-09-25 17:29 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Clicking on branching menu force quits application on iPad on latest 5.0 stable.

unfortunately this behavior happens only on specific projects, most importantly, piersharedev, on my account and not others. 

### Expected Behavior

Application doesn’t crash

### Steps to Reproduce

Click on branching menu, witness crash.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kiMrl34ZPxOVY15Dtbe5sjjg4G1B7TL07ttYbZxUjIuPtBJh/Z+PsalJvTtemYENhHGaJjjk1w6HpheLpMvVdAyWCRqp4zs1qdwzxRXq8RpuYELuodHxtJ5tPGn6e5LbUuCRAKfVtSXNh11ymA9+RThXvCZ+/Zwh9f6PHaOI=

### Visual documentation

N/A

### Environment

```markdown
- FlutterFlow version: 5.0
- Platform: iPad
- Browser name and version: iOS app
- Operating system and version affected: 17.6.1
```

**Comment by paulperez-dev** [comment] 2024-09-25 20:41
Hi @piershare,

I'm really sorry you're experiencing this issue. I wasn’t able to reproduce it on a blank project, but I was able to replicate it in your project. This leads me to believe it could be project-specific, and our support team will be best suited to help resolve it.

Would you mind reaching out to them? You can contact them either by email at [support@flutterflow.io](mailto:support@flutterflow.io) or via the in-app chat in FlutterFlow.

I'll go ahead and close this issue, as our tracker is intended for bugs reproducible from blank projects. However, if you're able to replicate this in a blank project as well, please let us know and share the bug code for that project.

Thank you so much for your understanding!

**Comment by piershare** [comment] 2024-09-25 20:53
Thank you, I will do that.

**Comment by MartinLockheart** [comment] 2024-09-26 00:09
I'm also running into the same issue on the Windows Desktop version. I'll reach out to support about it, but it's not just @piershare

**Comment by piershare** [comment] 2024-10-02 01:26
This is now fixed for me

**Comment by paulperez-dev** [comment] 2024-10-02 14:39
Hi @MartinLockheart,

Are you still encountering this error? If so, could you please file a new issue with all the details?

**Closed as completed by paulperez-dev** 2024-10-02 14:39 UTC
Labels: closed: support request
