### ISSUE TITLE
Text on any button using a Custom Theme Widget is overridden after style is changed.

### ISSUE THREAD

**Issue by dominikmucklow** [FlutterFlow/flutterflow-issues#1723] opened 2023-10-27 08:21 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If you update the style on a Custom Theme Button, any buttons that have that style applied will display the incorrect button text. The correct text will display in the editor and preview mode, but not in test mode and not in production.

This is the same issue as https://github.com/FlutterFlow/flutterflow-issues/issues/791, which is not fixed despite being closed.

This is NOT due to the 'link' option being set under the 'Button Text' of the Custom Theme Button.

### Expected Behavior

Buttons should display the correct text.

You should be able to adjust the style of custom theme widget button without is breaking all the button texts.

### Steps to Reproduce

1. Create a custom theme button, ensure that the 'link' option is not set under the 'Button Text'.
2. Apply the custom theme to any number of buttons, give those buttons different Button Texts.
3. Go to the Translations section under Settings, add at least 2 languages, and press 'Translate All'.
4. Return to the custom theme button and change some of the style settings, such as applying a disabled state.
5. Now, when running the app in production or test, the buttons will display the incorrect Button Text.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kysmB34ZgocdG1s/Lbe0xgj07C1ggTLJEoetxc0gbfe/4P7AMYcneXBJWXcizaH9YClWWrFw03PzJhof9FfcpHEmZUYs+1c9uERPPbFu5MI+YCc+8end5GtxXC0fG0cGJkQolNrZtZV0uw2C6GuiXEj+Cf9qOYwx5e6fDbOY=

### Context

This bug, which was supposed to be fix according to the previous thread, has already caused once to delete all buttons and custom theme widgets and all buttons and start again. Now that it has recurred, I am loathe to repeat that process until it is actually fixed.

Until then, custom theme buttons are useless unless you set them up once and never touch them again.

### Visual documentation

![Screen Shot 2023-10-27 at 4 11 37 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/149148630/6ce3c815-5517-47e9-87b7-5afc30a05481)

![Screen Shot 2023-10-27 at 4 11 07 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/149148630/bb9010a0-cabe-4f16-93d9-981e35ee54cd)

### Environment

```markdown
- FlutterFlow version: v4.0 released October 26
- Platform: Web
- Browser name and version: Chrome 118.0.5993.88
- Operating system and version affected: macOS Monterey 12.7
```

**Comment by hariprasadms** [comment] 2023-10-27 11:03
Hi @dominikmucklow - Thanks for submitting the issue. I have tested above steps but not able to reproduce the issue. 
Setup a blank project with issue steps details and share the bug report code of the same. Also a quick video would be more useful. Thanks

**Comment by dominikmucklow** [comment] 2023-10-27 13:03
Hi @hariprasadms,

Thanks for getting back to me, I have set up a new project "widget_style_bug" with bug report code: IT4CzMrl25F2rtxE187qLMFFmSQsH1whRYEvmMJtdwkbHZPOD7AQP8nRP1dUcOG7TXNmeE60in0X/MqPv/HtLsACAwusfapRwaVTWAvJTl+gV66DBpS3b3FtO9lPfECY58O73wpTLtp1Wi077V+MCNi8RT7DCZzPOUY/AuaeXdeK2SrDX1iXc2URm05KZDPz

**Comment by hariprasadms** [comment] 2023-10-27 14:31
@dominikmucklow - Thanks for the details. This is the best way to submit issues with a blank project setup and video snippet. So that we can quickly decide the issue is bug or not.

**Comment by GuzSantos** [comment] 2023-10-30 15:34
Experience the same behavior with buttons. All texts are reflecting the custom widegt

**Comment by wenkaifan0720** [comment] 2023-11-03 06:10
This should be fixed in our next update. Thanks for the feedback!

**Closed by wenkaifan0720** 2023-11-03 06:10 UTC
Labels: type: bug, status: confirmed, closed: fixed
