### ISSUE TITLE
CanvasKit do not display images with Hash

### ISSUE THREAD

**Issue by khomya** [FlutterFlow/flutterflow-issues#1313] opened 2023-08-20 19:29 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In Web all images with Hash are not displayed. Only Hashes are visible.

### Expected Behavior

First you see Hash, after that you see image.

### Steps to Reproduce

1. I just switched to CanvasKit and find out this problem.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wkfHlsIZ2xOFY+KXqdcFv+SAWCDp/aJ0/lu4aRis9JLbqB4kiY/WkZVpoQsu8d29EIUSmmkE03NqLv4b1UfkDIQ+ZRtll1aVUawriXmeQQZOBOqWKXHFfGppRGWKX37SzvwokHMttWCET1F6qfPKuf3fUNO/6IlFISq/LZO4=

### Context

website is unusable

### Visual documentation

<img width="468" alt="Screenshot 2023-08-20 at 23 25 33" src="https://github.com/FlutterFlow/flutterflow-issues/assets/2369704/557c3845-b0b9-436b-99a6-d8ae698e93e7">

### Environment

```markdown
- FlutterFlow version: 3.1 aug17
- Platform: Web
- Browser name and version: Chrome 115.0.5790.170, Safari 16.5.2 (18615.2.9.11.10)
- Operating system and version affected: MacOS 13.4.1
```

**Comment by khomya** [comment] 2023-08-20 20:00
And also completly not displaying images from Assets
<img width="401" alt="Screenshot 2023-08-20 at 23 57 19" src="https://github.com/FlutterFlow/flutterflow-issues/assets/2369704/3ef21c32-66e5-4fa7-a73e-d20a59a145d7">
<img width="289" alt="Screenshot 2023-08-20 at 23 58 40" src="https://github.com/FlutterFlow/flutterflow-issues/assets/2369704/42221aa1-6e0e-4991-b06c-ff84d30fb792">

result
<img width="483" alt="Screenshot 2023-08-20 at 23 58 22" src="https://github.com/FlutterFlow/flutterflow-issues/assets/2369704/43df216e-717d-435c-8956-2fba2d34b0c4">

**Comment by hariprasadms** [comment] 2023-08-20 20:09
Hi @khomya - Thanks for posting the issue. I looked at your project and when i see in browser console while accessing your web app. I see below errors. The images are displaying because of cors policy error. 

Can you confirm below points please?

1. How it works when you deploy without CanvasKit ? - CanvasKit feature is in beta state at the moment. You can expect bugs around it. If it is not working in your project, you can disable it in. 

2. How are you storing the images in backend? - Share us a quick video or images which can show us how images are stored.

<img width="1511" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/d7995d1e-bf27-4f32-b03c-fa5e3b7d29ae">

**Comment by khomya** [comment] 2023-08-21 06:43
Hi!

1. Without CanvasKit - all images are displayed! With and without hash! (but website is very slow and often not working in safari, thats why I want to try CanvasKit option).
2. Nothing fancy with image storage.
Its either Assets (shown before) or just as displayed in Documentation.
<img width="1176" alt="Screenshot 2023-08-21 at 10 40 29" src="https://github.com/FlutterFlow/flutterflow-issues/assets/2369704/dbf431d2-68bb-4f75-bfce-57cb4d3e1fae">
<img width="616" alt="Screenshot 2023-08-21 at 10 42 21" src="https://github.com/FlutterFlow/flutterflow-issues/assets/2369704/dea053de-d48e-451d-aa36-5a41259fc76e">
<img width="627" alt="Screenshot 2023-08-21 at 10 42 37" src="https://github.com/FlutterFlow/flutterflow-issues/assets/2369704/6dd13602-e0c6-48cd-a762-56de830a5a78">

**Comment by wenkaifan0720** [comment] 2023-08-23 16:16
Looks like a duplicate of this issue: https://github.com/FlutterFlow/flutterflow-issues/issues/1228

**Closed** 2023-08-24 22:12 UTC
Labels: type: bug, status: confirmed, closed: duplicate
