### ISSUE TITLE
Custom Domain Server (web server) does not response with gzip encoding ... :(

### ISSUE THREAD

**Issue by thruthesky** [FlutterFlow/flutterflow-issues#94] opened 2022-11-04 13:44 UTC
After I publish the app with Custom Domain, I found it is very slow.
And I checked the size of main.dart.js and surprisingly, I knew it is not gzipped.

It took 12 seconds to load the main.dart.js and the size is 6.9MB.
<img width="992" alt="image" src="https://user-images.githubusercontent.com/5080329/199986538-6cb84a8a-2138-47e0-aac4-b1d38998fc9b.png">

Below is the comparison on custom-domain and non-custom-domain. With gzip, it's only 1.7MB.
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/5080329/199986047-077cf957-4b0a-43cb-aa36-91d7b5549639.png">

Please, add encoding on the web server of custom domain.
Thank you.

**Comment by Pepino-GR** [comment] 2022-11-06 12:42
Hello thruthesky,
I declare it as a feature request, because it is not a bug.

**Comment by thruthesky** [comment] 2022-11-06 14:21
@Pepino-GR Yes, Thank you.

**Comment by wenkaifan0720** [comment] 2022-11-07 08:38
Since this is a feature request, I will close this issue for now.

**Closed by wenkaifan0720** 2022-11-07 08:38 UTC
Labels: type: feature request
