### ISSUE TITLE
Enter Key doesn't delete a page

### ISSUE THREAD

**Issue by coach1990** [FlutterFlow/flutterflow-issues#3632] opened 2024-08-16 02:09 UTC
### Can we access your project?

- [x] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

i have over 25 pages in a project that i want to detele quickly, however, Click is the only method we can do it. Enter Key doesnt work on Pages section. I have made a video that explains this behavior, hope it helps. happy to add more inputs when needed.

### Expected Behavior

Enter key should also delete the page

### Steps to Reproduce

create a page
rigth click and select Delete Page
press Enter key -page wont delete
right click again and select Delete Page
This time, click on the Delete Red Button- page will be deleted

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sls/l6otPvsdG1ZDuc8dB/TsvHEwgap0kscp/bxIgGIDzPOw+ZPXsalFoYMjgT1V+I0SmmmQx/srqidmWL/ACFw2afb5awc1UZgvvTlite5OBDqiOdEdBM9tUC2GM5pjZkxZ5HLFucl4s7U6yG+/KUXTrHu/AIndISq/LZO4=

### Visual documentation

https://github.com/user-attachments/assets/9d7ac80c-c182-4e5c-a677-4c2dfe28ca14

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.82+ released August 7, 2024 Flutter version is 3.22.2
- Platform: Desktop App Windows
- Browser name and version: Microsoft Edge Version 127.0.2651.74 (Official build) (64-bit)
- Operating system and version affected: Windows 11 Home Single Language , 23H2
```

**Comment by paulperez-dev** [comment] 2024-08-16 12:39
Hi @coach1990! Because this is a risky operation, the default focus is on the NO option. If you press TAB and then ENTER, the page will be deleted. 

Because this is not a bug, I will close this issue.

**Closed as not planned** 2024-08-16 12:39 UTC
Labels: closed: not a bug
