### ISSUE TITLE
No matter where I set the Request Permissions for Notification, it shows up when the app starts.

### ISSUE THREAD

**Issue by DMTProtocol** [FlutterFlow/flutterflow-issues#1269] opened 2023-08-15 03:11 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

No matter where I set the Request Permissions for Notification, it shows up when the app starts.

### Expected Behavior

Displayed at the location where Request Permissions for Notification is set

### Steps to Reproduce

1. Please set Request Permissions for Notification in a place other than the startup page
2. Please check if it is displayed in Strartup page such as Homepage when you start the application

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4glPLq249Om+5E+c76be9apCg4NW4mbb00st5Hd0gdCOPrBuwue+D7VEpDXfbgaVNcEVf+pzgBzNWMhd7lD/EEZAusQJRMwYd6bzrOe2iVM7HREZOWekd7P+NRIGKC4KS3vSJBNu5pdU4121yQNuyQdC3DFOu/Zwh9f6PHaOI=

### Context

I want permission to be notified at a specified location.

### Visual documentation

![IMG_5646](https://github.com/FlutterFlow/flutterflow-issues/assets/106588916/3087e8c5-0bcb-4ecd-9af1-d78ca14bda49)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: iOS
- Browser name and version: iPhone11
- Operating system and version affected: iOS 16.3.1
```

**Comment by kevintonb** [comment] 2023-08-17 15:48
Hey @DMTProtocol , thank you for getting in touch and for taking the time to prepare the bug report. We noticed in your project that you're using an external dependency called 'awesome_notifications' in a custom action and it is set in a page that's accessible from a bottom navigation item. This could've initialised the dependency and caused a permission request from the user before the permission request from the actions was triggered. So far, I could not replicate the same behaviour in a new project. But if you're able to, please reproduce this behaviour in a new project without any external dependency intervention and share it here in the thread as a bug report so that we can isolate this issue if found within Flutterflow.

**Comment by kium-one** [comment] 2023-09-22 20:04
@kevintonb I'm having a similar issue. I'm trying to check first if permissions were requested already, so I don't request them again (I think it's bad practice?). 
My flow is 
1. Login screen (launches this custom action on load).
2. Show permissions screen (after login) - shown if permissions not already requested, by checking app variable set on step 1)
3. Button on that page triggers the FF action to ask for permissions.
When testing, the permissions get asked when the Permission screen loads, rather than when the button is pressed.
Any idea what might be happening?
Widget code: IT4ghc/lvJdOm99J1aX2de9VvCkQJmU1a5c0sNobbxAjIoDoPJkUac/RdlduXtfnTAlXKEWKgkw0wN7yk+LLF+0DPQSqR6JJ1ZZIcQ3ycEe/aoubOpeWOn8nMJlPf0yi0ra3nQolKbdaSiVm7XGqF9++RXbUQeb7Zwh9f6PHaOI=
<img width="493" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/12573714/6d1f6b7f-c2fc-424f-8826-6ebf34d2faf4">

**Comment by kium-one** [comment] 2023-09-25 19:02
@kevintonb This doesn't seem to work at all. I removed all code related to notifications and only trigger permissions on the click of a button, but the permissions get asked on page load.

Bug report code
IT4ghc/lvJdOm99J1aX2de9VvCkQJmU1a5c0sNobbxAjIoDoPJkUac/RdlduXtfnTAlXKEWJ/WABw+DpkvLPIe0FBw6bfKU71s0JazzLRmC/aoubOpeWOn8nMJlPf0yi0ra3nQolKbdaSiVm7XGqF9++RXbUQeb7Zwh9f6PHaOI=

**Comment by kium-one** [comment] 2023-09-27 11:42
ChatGPT's take on this:

Your `main.dart` does subscribe to `fcmTokenUserStream`:

```dart
final fcmTokenSub = fcmTokenUserStream.listen((_) {});
```

This line of code subscribes to the `fcmTokenUserStream`, which in turn triggers the `getFcmTokenStream` function and the associated permission request.

The reason it might be triggering only on a certain page could be due to the following:

1. The `authenticatedUserStream` might be emitting a new user only when you navigate to that specific page.
2. Some other condition in your app might be causing the Stream to emit a new value only on that specific page.

The `fcmTokenUserStream.listen((_) {});` is initialized in the `initState` of your `_MyAppState` class, which means it starts listening as soon as your app starts. However, the actual permission request will only happen when `authenticatedUserStream` emits a new user that is not null.

If you want to control when the permission request appears, you could conditionally subscribe to `fcmTokenUserStream` based on some app state or user action. Would you like to proceed with that approach? If so, I can provide a full code example.

**Comment by kium-one** [comment] 2023-09-27 11:50
Crossing my fingers that Apple will not decline the release because permissions are asked right when the user is created 😬

**Comment by kium-one** [comment] 2023-09-30 18:35
Thank you for checking in. I'm still getting the issue in my project. There's no custom code regarding checking permissions. What did you mean by external dependencies?
Unfortunately, I won't be able to test on a blank project right now because it means creating a new firebase project and iOS build to test on a real device, etc. If you have one set up already, I'd love to know if it works for you. The configuration is firebase authentication + push notifications enabled, then a button that requests permissions (the FF action).

**Comment by katherineqian** [comment] 2023-10-01 20:59
Hi @kium-one, by external dependencies I was referring to @kevintonb 's response: 

> We noticed in your project that you're using an external dependency called 'awesome_notifications' in a custom action and it is set in a page that's accessible from a bottom navigation item. This could've initialised the dependency and caused a permission request from the user before the permission request from the actions was triggered. 

Would it be possible for you to provide a bug report code for the project where you experience this? Since @kevintonb had already triaged the issue for the original author who included a bug report code, and suggested that it was likely based on the external dependency + that he could not replicate in a new project, it would aid me in being able to help you find out what's causing this behavior.

**Comment by kium-one** [comment] 2023-10-01 21:04
Ah yes absolutely. Here's the bug report code for my permissions page/button.
IT4ghc/lvJdOm99J1aX2de9VvCkQJmU1a5c0st5Hd0gdCOPrBuw+deDeSEtVcOnjaVNcAWG0pF8z+Nb6iIT9DPFcGzmub7Y6/qVTEjzOe2i5bJOYOpC8Tmt9O8RXfEyw56evqwhCAMxfcVlg2Dm1fPOtQjPDFOu/Zwh9f6PHaOI=

**Comment by katherineqian** [comment] 2023-10-01 21:39
Thank you! I appreciate you providing that info. After investigating, it looks like this would have to be a feature request rather than a bug. When push notifications are enabled, we currently simply default to always requesting permissions for each user and then subscribing to the FCM token stream (like you described in your explanation above). This would be a request to allow you to customize when the permissions notification shows up, since I requesting notification permissions on each new user is the standard behavior for when push notifications are enabled now. We would detect whether you have a request notification permission action in your project and it would require some changes to the current setup of getting the FCM token, since not everyone using push notifications would add their own request permissions action. I'll put in the request internally. 

Are there any restrictions from Apple that I should know about, where it would be grounds for denying an app if you ask for permissions when users are created?

**Comment by kium-one** [comment] 2023-10-02 05:26
Thank you Kathy. Maybe I misunderstood something but how is the request permissions action supposed to work normally? Does it ever request permissions when you click on it?In terms of Apple, I know their guidelines are to have a screen explaining what notifications we send and also for the buttons to not say “yes” “no” but rather just continue, and then the native permissions are shown, so that the user can make a free choice. Most apps have a screen like this, but some have none, so maybe it’s fine without.On Oct 1, 2023, at 11:39 PM, Kathy Qian ***@***.***> wrote:﻿
Thank you! I appreciate you providing that info. After investigating, it looks like this would have to be a feature request rather than a bug. When push notifications are enabled, we currently simply default to always requesting permissions for each user and then subscribing to the FCM token stream (like you described in your explanation above). This would be a request to allow you to customize when the permissions notification shows up, since I requesting notification permissions on each new user is the standard behavior for when push notifications are enabled now. We would detect whether you have a request notification permission action in your project and it would require some changes to the current setup of getting the FCM token, since not everyone using push notifications would add their own request permissions action. I'll put in the request internally.
Are there any restrictions from Apple that I should know about, where it would be grounds for denying an app if you ask for permissions when users are created?

**Comment by nickpicciri** [comment] 2023-10-05 20:41
> Thank you! I appreciate you providing that info. After investigating, it looks like this would have to be a feature request rather than a bug. When push notifications are enabled, we currently simply default to always requesting permissions for each user and then subscribing to the FCM token stream (like you described in your explanation above). This would be a request to allow you to customize when the permissions notification shows up, since I requesting notification permissions on each new user is the standard behavior for when push notifications are enabled now. We would detect whether you have a request notification permission action in your project and it would require some changes to the current setup of getting the FCM token, since not everyone using push notifications would add their own request permissions action. I'll put in the request internally.
> 
> Are there any restrictions from Apple that I should know about, where it would be grounds for denying an app if you ask for permissions when users are created?

Hi just wanted to chime in to emphasize that this is a huge issue for other projects as well. My app has the auth -> the onboarding flow, and the user gets asked if they'd like to enable notifications before understanding why they're used or how often they will get them.

**Comment by kium-one** [comment] 2023-10-06 05:54
Addition: I tried setting up permissions action *before* the user is logged in, but the action doesn't work there either, the permissions still get asked as soon as the authentication is done.

**Comment by metysj** [comment] 2023-11-01 03:20
Same feedback as other commenters. It may be "working as designed" but doesn't seem like it's "working as users expected".

**Comment by nickpicciri** [comment] 2023-12-06 06:09
Hi is a fix coming any time soon?

**Comment by taggxyz** [comment] 2024-01-13 11:44
Still have this problem, it completely breaks my onboarding because if any of the permissions are denied on launch - I can't then trigger the permission action during onboarding...

**Comment by victoriahuang1** [comment] 2024-01-23 23:42
Hi all, thanks for bringing this to our attention. This is for sure something that we should support.

However as Kathy has previously stated, this is a feature request. As such, I will be closing this issue and moving this to our board for prioritization, so that it can get reviewed and worked on.

**Closed by victoriahuang1** 2024-01-23 23:42 UTC
Labels: type: bug, status: confirmed, Permissions

**Comment by taggxyz** [comment] 2024-01-23 23:52
@victoriahuang1 Originally, FlutterFlow did not prompt for permissions when the app started. In the past, if your app had permission request actions on _any_ of its pages, it **wouldn’t** trigger the permission alert at the start of the app. 

This is why we believe it to be a bug.

**Comment by victoriahuang1** [comment] 2024-01-24 01:04
@taggxyz I have already talked with the eng team, and the conclusion is that we will work on this as a feature request. This is certainly something that we plan on addressing. We will just be tracking this task along with our other features, rather than here.

**Comment by Nic61** [comment] 2024-04-20 14:41
@victoriahuang1 Thanks for labelling this as a feature request, it sure is. Just wanted to ping here again as it's something quite important for us. Not only does it show up on user auth creation but every now and then it comes back up after the app has been closed for awhile.
All the best to the FF team.
I hope with the recent round closed you've got some more engineers working on this.

**Comment by bdonovan858** [comment] 2024-06-06 17:54
Hi @victoriahuang1, checking in to see if you or the FF team had a general timeline for this feature? Thanks so much!

**Comment by solkennedy** [comment] 2024-06-13 13:43
When will this be released?

**Comment by victoriahuang1** [comment] 2024-06-14 19:30
We currently don't have a timeline for this feature but have noted it for future updates. We appreciate your understanding, thanks!

**Comment by sanjayelate** [comment] 2024-06-29 15:50
> We currently don't have a timeline for this feature but have noted it for future updates. We appreciate your understanding, thanks!

Is it something we can do ourselves by editing the main.dart file?

**Comment by WellDunDun** [comment] 2024-08-20 08:28
Has anyone figured out a workaround? This is causing me, my clients, and their users a huge headache @leighajarett @bulgariamitko

**Comment by sanjayelate** [comment] 2024-08-24 14:25
This is ridiculous, how has this not been sorted yet? It's completely pointless having a 'request permission' action for push if it's going to be triggered automatically as soon as they're authenticated. It's also really bad practise, especially for iOS apps.

**Comment by Nic61** [comment] 2024-08-24 14:28
Why is ti closed btw? I don't think this is solved, right?

**Comment by sanjayelate** [comment] 2024-08-24 14:31
It's because they deem it to be a feature request, not a bug. 

They purposely put the request in as part of the 'backend/push_notifications/push_notifications_util.dart'; import in the main.dart file.

This in turn triggers the the getFcmTokenStream function, which is called by fcmTokenUserStream.

This stream is only activated for authenticated users (authenticatedUserStream.where((user) => user != null)) but is triggered as soon as authentication happens.

[victoriahuang1](https://github.com/victoriahuang1) commented [on Jan 24](https://github.com/FlutterFlow/flutterflow-issues/issues/1269#issuecomment-1907176553)
> @taggxyz I have already talked with the eng team, and the conclusion is that we will work on this as a feature request. This is certainly something that we plan on addressing. We will just be tracking this task along with our other features, rather than here.

**Comment by leighajarett** [comment] 2024-11-22 12:37
Hi all, I wanted to give you a heads up that we have addressed this feature request and it will be available in the next release!

**Comment by bdonovan858** [comment] 2024-11-22 16:41
Thanks @leighajarett. This is will be a great addition!

**Comment by solkennedy** [comment] 2024-12-05 20:17
@leighajarett Thanks for the update. Still seeing this issue in the latest release - any idea the version code to look out for?

**Comment by Diallol** [comment] 2024-12-27 15:10
Not solved my apps accepted on appStore and Play Store. her the pattern with a google login .you click , a notification permissions pop up .You accept the permission but you not redirect to the next page . You need to reclick for the location permission and then it will navigate to the next one.
