### ISSUE TITLE
Google Authentication pop-up is blocked by the browser because the 'allow-popups' request header is missing

### ISSUE THREAD

**Issue by Asiyil-K-Alaswad** [FlutterFlow/flutterflow-issues#3142] opened 2024-06-15 14:46 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

- during Run mode
- When Trying to Sign up / Sign in using google authentication (through firebase of course) 
- the google sign in pop-up does not show 
- an informaitonal message pops up from the bottom side of the app. Which reads : "Error: Unable to establish a connection with the popup. It may have been blocked by the browser"
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/150237420/b39d3ba7-6184-4c3a-8403-1c765d8a6cfd)

### Expected Behavior

-  pop-ups are allowed for all sites in the browser's settings
- the debugging, Run mode and other related urls are all added to the autherized domain in the firebase authentication settings
- an error message is printed in the console. It reads : " locked opening \***Request Url\*** in a new window because the request was made in a sandboxed frame whose 'allow-popups' permission is not set. "
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/150237420/87db7972-7aec-4348-90ce-016818c67dd3)

### Steps to Reproduce

1. Create Blank Project
2. follow the Firebase connection steps provided by Flutterflow
3. setup and enable authentication in firebase and flutterflow
4. create a button
5. add the 'create account' or 'log in' authentication action to the button
6. run program and click the button

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEelsn1z4pNj7xZ1ZP6Y/lFgQMxQUB+bZ0vlO1FGE0YNb2uBJoteMnuaXddUt+kelZHMFSJhmUGpsLuhobDJ8E6OTStY6V607tTFj3weD2iVbaRELuKY3FRHdpMBUy0yruFnxQnGOpYWHdn73GLcq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/150237420/87fb6a5a-364b-44c4-8238-7156fe6fea0f)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/150237420/16b0d7aa-0090-466b-9694-268bb0f05d1b)

### Environment

```markdown
- FlutterFlow version: v4.1.60+ released June 14, 2024
- Flutter version is 3.19.1
- Platform: Web
- Browser name and version: Google Chrome Version 126.0.6478.62
- Operating system and version affected: Windows 10 64 bit version 22H2 (OS Build 19045.4529)
```

### Additional Information

additional triage I have done :
- tried on different browsers on the same machine : chrome , opera and firefox
- tried on a different machine ( windows 11 )

**Comment by Sejal-svg** [comment] 2024-06-17 07:03
I am also facing similar issue . Did you find any solution ?

**Comment by Asiyil-K-Alaswad** [comment] 2024-06-17 09:09
> I am also facing similar issue . Did you find any solution ?

No. it is still persistant.

**Comment by mlagus** [comment] 2024-06-17 18:30
I have the same issue
Already added all urls to allow in the browser and it still persists

**Comment by paulperez-dev** [comment] 2024-06-17 18:30
Hi @Sejal-svg @Asiyil-K-Alaswad. Can you please share a capture of how these settings looks like? 

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/6c83c7a2-06f5-4d23-8732-9c5fe903f4c8/f1cb624c-c37c-48f2-9fce-64d0170467b0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82YzgzYzdhMi0wNmY1LTRkMjMtODczMi05YzVmZTkwM2Y0YzgvZjFjYjYyNGMtYzM3Yy00OGYyLTlmY2UtNjRkMDE3MDQ2N2IwIiwiaWF0IjoxNzE4NjQ5MDU3LCJleHAiOjMzMjg5MjA5MDU3fQ.EgN5Jg3R5aV03YLBz0f3-MF_C06dmdk7e26KBmugSkQ " alt="image.png" width="409" height="493" />

**Comment by mlagus** [comment] 2024-06-17 18:32
<img width="421" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/2507079/c6fa45e8-09d8-4d6f-afc8-abccc2150e65">

**Comment by mlagus** [comment] 2024-06-17 18:32
<img width="353" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/2507079/4dc0675b-ea5d-454a-b616-1fb9d96bcaba">

**Comment by paulperez-dev** [comment] 2024-06-17 18:34
@mlagus which browser are you using?

**Comment by mlagus** [comment] 2024-06-17 18:39
@paulperez-dev  which browser are you using?

Chrome Version 125.0.6422.142 (Official Build) (arm64)

**Comment by paulperez-dev** [comment] 2024-06-17 18:46
@mlagus please click on 'Site settings', and share a capture of the configuration.

**Comment by mlagus** [comment] 2024-06-17 19:28
@paulperez-dev  why? what u wanna see? The list is long in there

**Comment by paulperez-dev** [comment] 2024-06-17 20:14
@mlagus the popup permissions specifically for the FF site.

**Comment by mlagus** [comment] 2024-06-18 06:08
@paulperez-dev  the popups and redirects are allowed

**Comment by mlagus** [comment] 2024-06-18 06:14
<img width="120" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/2507079/c3c06eeb-8a7f-49e6-9632-09e71669c55e">
In run mode i get this wierd icons generated. In test mode ther look correct with apple and google logo. Dont know if its connecting to the same problem

**Comment by Asiyil-K-Alaswad** [comment] 2024-06-18 08:37
> Hi @Sejal-svg @Asiyil-K-Alaswad. Can you please share a capture of how these settings looks like?
> 
> <img alt="image.png" width="409" height="493" src="https://camo.githubusercontent.com/3718a1e5d1a18f1a30e439251b046a81e373df80f8091262a734e3eb4ea12938/68747470733a2f2f75706c6f6164732e6c696e6561722e6170702f33323431303839642d373336612d343432322d393030622d3035316537326163636462652f36633833633761322d303666352d346432332d383733322d3963356665393033663463382f66316362363234632d633337632d343866322d396663652d3634643031373034363762303f7369676e61747572653d65794a68624763694f694a49557a49314e694973496e523563434936496b705856434a392e65794a775958526f496a6f694c7a4d794e4445774f446c6b4c54637a4e6d45744e4451794d6930354d4442694c5441314d5755334d6d466a593252695a533832597a677a597a64684d6930774e6d59314c54526b4d6a4d744f44637a4d693035597a566d5a546b774d325930597a67765a6a466a596a59794e474d74597a4d33597930304f4759794c546c6d593255744e6a526b4d4445334d4451324e3249774969776961574630496a6f784e7a45344e6a51354d4455334c434a6c654841694f6a4d7a4d6a67354d6a41354d44553366512e45674e354a6733523561563033594c427a3066332d4d465f433036646d646b376532364b426d7567536b5120">


![image](https://github.com/FlutterFlow/flutterflow-issues/assets/150237420/84138112-1afb-4f14-9b53-06780074c378)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/150237420/947a4adb-ebd4-4640-882e-de9e5987454f)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/150237420/34f5a35a-e0b8-4704-9fec-fe8e69ec8b31)

**Comment by mlagus** [comment] 2024-06-18 13:02
I rebooted computer, tried to access flutter flow. it was just black!
I emptied cashe and reloaded and got this in console
"Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox."
I found this thread:
https://stackoverflow.com/questions/78011724/warning-third-party-cookie-will-be-blocked-learn-more-in-the-issues-tab
Could it be belonging to that problem?

**Comment by mlagus** [comment] 2024-06-18 18:36
I got this from google console:
"
```
The error "Blocked opening ... in a new window because the request was made in a sandboxed frame whose 'allow-popups' permission is not set" indicates that your web application is trying to open a popup window (likely for authentication with Firebase) from within an iframe or a context that has sandbox restrictions. Browsers enforce these restrictions to prevent potentially malicious behavior from embedded content.
Here's a breakdown of the issue and how to fix it:
Understanding the Error
Sandboxed Frames: When you embed content in an iframe, you can apply the sandbox attribute with various restrictions. One of these restrictions is allow-popups, which controls whether the iframe is allowed to open new windows.
Security Measure: This is a security feature to prevent embedded content from opening unwanted popups, which could be used for phishing or other malicious purposes.
Solutions
Adjust Sandbox Attribute: If you control the iframe where your code is running, modify the sandbox attribute to include allow-popups:

<iframe src="your_app_url" sandbox="allow-scripts allow-same-origin allow-popups"></iframe>

Open Popup from Top-Level Window: If you can't modify the sandbox attribute, restructure your code to initiate the popup opening from the top-level window (the main browser window, not within an iframe). This might involve using postMessage communication between the iframe and the parent window.
Alternative Authentication Methods: Consider using authentication methods that don't rely on popups, such as:
Redirect-based flow: Firebase Authentication supports redirect-based flows where the user is redirected to a login page and then back to your application after authentication.
In-page authentication: Implement a login form directly within your application's page.
Code Analysis
Looking at your provided code snippet, the issue likely stems from the window.open call. If this code is executed within a sandboxed iframe without the allow-popups permission, the browser will block the popup.
Debugging Tips
Check Console: Open your browser's developer console to see if there are any additional error messages or warnings related to the popup blocking.
Inspect Sandbox Attribute: If your code is within an iframe, inspect the iframe element in the developer tools to see if the sandbox attribute is present and what restrictions are applied.
Important Considerations
User Experience: Popups can be disruptive to the user experience. Consider whether alternative authentication methods might provide a smoother flow.
Security: Always prioritize security when implementing authentication. Carefully evaluate the risks and benefits of different approaches.
If you can provide more context about how your application is structured (e.g., whether it's embedded in an iframe, how the authentication flow is initiated), I can give more specific guidance.
Data used to understand this message

```

**Comment by mlagus** [comment] 2024-06-18 18:43
Jump in here and upvote this problem
https://community.flutterflow.io/ask-the-community/post/unable-to-authenticate-using-google-hYFpowS2i2LRDzx

**Comment by mlagus** [comment] 2024-06-20 06:52
@Asiyil-K-Alaswad  Have you been able to fix it?

**Comment by Asiyil-K-Alaswad** [comment] 2024-06-20 08:53
> @Asiyil-K-Alaswad Have you been able to fix it?

No luck. The only other thing I haven't tried is running it on a safari browser to see if the problem is solely from chrome, but I don't have access to a Mac/IOS device.

**Comment by paulperez-dev** [comment] 2024-06-22 12:30
Hi @Asiyil-K-Alaswad! Can you please share a capture of the domains added to Firebase Auth?

**Comment by Asiyil-K-Alaswad** [comment] 2024-06-23 10:46
@paulperez-dev  
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/150237420/742229d8-b578-4162-99dc-6baafa1645e5)

**Comment by mlagus** [comment] 2024-06-23 17:47
@paulperez-dev  i have the same settings as @Asiyil-K-Alaswad  its all set according to instructions.
Why does FF test mode work but not run mode?

**Comment by mlagus** [comment] 2024-06-24 19:23
Its work fine with testing it here, so it must be specific to flutter flow or firebase settings
https://gal-demo.withgoogle.com/

**Comment by karolpaw85** [comment] 2024-06-25 20:40
I also have the same issue but in RUN mode. When I use desctop Flutterflow it works. A bit frustrating... BTW, it was working before and one day it stopped... I do not recall any changes I made to my system, browser or project.

**Comment by Tyg-g** [comment] 2024-06-26 07:18
This issue probably has to do with that the permissions in an `<iframe>` has to be explicitly allowed in HTML using the attribute `allow='...' `. The site settings alone are not enough. The same thing why the camera and microphone don't work in debug mode.

**Comment by Asiyil-K-Alaswad** [comment] 2024-06-27 08:43
@Tyg-g  Yeah it's definitely that. The issue is controlling an elements attribute in FlutterFlows UI is not really something the developer could do.

**Comment by abhibalani** [comment] 2024-06-28 12:35
Having the same issue. Google auth pop up not showing up. 

In test mode it says, this url is not added as authorized domains which it is. 
And in run mode it says unable to establish connection with pop up, browser may have blocked the pop up. 

Any work around for this? 

I want to use razorpay. For razorpay FF required firebase auth.

**Comment by abhibalani** [comment] 2024-06-28 12:35
Having the same issue. Google auth pop up not showing up. 

In test mode it says, this url is not added as authorized domains which it is. 
And in run mode it says unable to establish connection with pop up, browser may have blocked the pop up. 

Any work around for this? 

I want to use razorpay. For razorpay FF required firebase auth.  
![Screenshot 2024-06-28 180317](https://github.com/FlutterFlow/flutterflow-issues/assets/9943941/9be7866e-fbe5-4690-a5a4-d0463541fd37)

**Comment by karolpaw85** [comment] 2024-06-28 21:16
Well. the problem is that for the last 4 months i was using RUN mode about 200 times to test my app, and it was working. and one day it stopped. I did not change anything in login page at all... Although there was a new flutter update...
So concluding, is there anything I can do solve it or shall we wait for FF people to fix it?

**Comment by Tyg-g** [comment] 2024-06-29 05:45
> In test mode it says, this url is not added as authorized domains which it is. And in run mode it says unable to establish connection with pop up, browser may have blocked the pop up.
> 
> Any work around for this?

Test mode: you have to add the URL from the <iframe> of the app preview to Google Auth. I think it is 'your-project-id.run.app', I can't check it right now. 

Run mode: Click the [Wiew Full Screen] button.

**Comment by abhibalani** [comment] 2024-06-29 08:00
I solved it. 

In test mode, when you see error in snack bar like this 
![Screenshot 2024-06-28 180317](https://github.com/FlutterFlow/flutterflow-issues/assets/9943941/3f660e55-59dd-4b9a-bfc4-c7e551f3d0ac)

Open developer console on google chrome and there will be a URL printed within an error from firebase auth which you can add to authorized domains in firebase. Wait for a minute, it should work then.

**Comment by mlagus** [comment] 2024-07-01 06:04
@abhibalani  do you mean the url from this error?
<img width="474" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/2507079/97fe7405-13b5-4d0c-9f70-d14b88259788">

**Comment by abhibalani** [comment] 2024-07-01 08:25
@mlagus 
![Screenshot 2024-07-01 1353311](https://github.com/FlutterFlow/flutterflow-issues/assets/9943941/9a8af76e-13fd-4284-a8f8-6cd2655af69d)

This message is what I am referring to. 

Hope it helps.

**Comment by abhibalani** [comment] 2024-07-01 15:02
@mlagus I am getting the same error on run mode.

![Screenshot 2024-07-01 203129](https://github.com/FlutterFlow/flutterflow-issues/assets/9943941/a0a4a28b-dec6-4d10-b6a2-8b233471348f)

But this working in local environment setup with FF desktop app for windows.

**Comment by mlagus** [comment] 2024-07-01 18:22
@abhibalani 
Yes as said before, i only have the problem in run mode

**Comment by karolpaw85** [comment] 2024-07-02 08:11
I have this message from support: Yes, Seems google auth recently changed something in their end that requires a header to be added to the launcher, i notified the team responsible for our bug triage to make it a priority and identify the issue, seems they assume it's happening in the test mode not run mode
They will triage it and will prioritise the fix to roll out in next releases. 
So I guess I will be fixed.

**Comment by abhibalani** [comment] 2024-07-02 08:45
> I have this message from support: Yes, Seems google auth recently changed something in their end that requires a header to be added to the launcher, i notified the team responsible for our bug triage to make it a priority and identify the issue, seems they assume it's happening in the test mode not run mode They will triage it and will prioritise the fix to roll out in next releases. So I guess I will be fixed.

Thanks for the info. This issue was raised 2 weeks ago. 

I am not very sure now if it was right choosing FF for frontend development. 

I haven't received any response on my ticket and my email that I sent 3-4 days ago. 

I am finally taking a manual API route to integrate razorpay in my app.

**Comment by itsstevenliu** [comment] 2024-07-08 09:31
Any update? This is happening in run mode for me - test mode and publish mode works fine.

**Comment by tomkrata** [comment] 2024-07-11 16:31
I had the same problem.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/17932938/f23ab9c1-b3aa-4b9e-b701-cf329f014918)
Enabled the Windows (alpha) checkbox in platforms tab settings. Works for me.

**Comment by paulperez-dev** [comment] 2024-07-11 18:55
Hi @Asiyil-K-Alaswad, can you please try disabling this option?

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/a4bd9974-8f18-4b37-a0bd-2a2c8f55d911/9cd48ad6-79cf-4d51-a87f-c1c9c680ab6b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hNGJkOTk3NC04ZjE4LTRiMzctYTBiZC0yYTJjOGY1NWQ5MTEvOWNkNDhhZDYtNzljZi00ZDUxLWE4N2YtYzFjOWM2ODBhYjZiIiwiaWF0IjoxNzIwNzI0MTE3LCJleHAiOjMzMjkxMjg0MTE3fQ.0RdeRSNEE8pg--IEQGLoBDD2dTJtOLtkxR-Xi0oXJfw " alt="image.png" width="1407" height="706" />

If this does not work, can you please reach out to [support@flutterflow.io](mailto:support@flutterflow.io)? They can better assist you with ensuring your project is configured correctly!

**Comment by mlagus** [comment] 2024-07-15 07:25
@paulperez-dev  I did disable that option and i still have the same error (run mode)
Ive already reached out to support

**Closed as completed** 2024-07-17 13:42 UTC
Labels: status: needs triage

**Comment by mlagus** [comment] 2024-07-18 08:28
@Asiyil-K-Alaswad  and all!
Ive talked to FF support and they will have a fix for this in production next week! This week its in beta! Yay!

**Comment by reed-hub** [comment] 2024-09-13 14:27
did the fix come yet? I am seeing this when attempting to login with my PWA published on custom domain and using the google authentication...
