### ISSUE TITLE
Update with supabase not working for updating array of texts.

### ISSUE THREAD

**Issue by pireslopesvinicius** [FlutterFlow/flutterflow-issues#3292] opened 2024-07-01 16:23 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have defined in the supabase a table, in which I have a column that is of type array of texts, however, when trying to execute the action update from supabase in that column, specifying a list of strings it just doesnt update it, no aparent reason.

### Expected Behavior

It should update the array of texts normally.

### Steps to Reproduce

1. Create a supabase table that has a column of type array of texts (non-nullable)
2. Try to do a update in flutterflow with a page state (list of strings) in it

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hcrqx892obxY+KXqYMJVniA5KU97bJIVie5raCsofePrOpkAf8/7UFtUOMPiSlVEJGaWimYX/Mrov/PLFfkEPU+bfaJE/6hcZRfgQkmlMs2tPIS3b3EnI/FbGkik1MO3ogkkHNtvLnMt22WmAd+tYBfBJp/1C0UdOeaoXdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

![1](https://github.com/FlutterFlow/flutterflow-issues/assets/122576344/536a0e2d-48cb-4e17-9b9e-956fe2a06bb5)

### Environment

```markdown
- FlutterFlow version: v4.1.65+
- Platform: Desktop
- Browser name and version: Desktop version actually
- Operating system and version affected: Windows 10 64 bits
```

**Comment by pireslopesvinicius** [comment] 2024-07-02 12:58
I have changed the workflows logic in my project, I have done it by code with custom action (updateItemArtes). But It was not working before by the native way of doing it.

**Comment by Alezanello** [comment] 2024-07-02 13:05
Hello!

I'm glad you found an alternative solution. Currently, I am attempting to replicate the main issue but have not had any success so far. Could you please replicate the issue in a blank project and share the Bug Report Code with me for further investigation?

Thank you for your cooperation!

Best regards,<br>Azanello

**Comment by pireslopesvinicius** [comment] 2024-07-02 13:13
Bug Report Code: IT40hcrqx892obxY+KXqYMJVniA5KU97bJIVie5raCsofePrOpkAf8/7UFtUOMPiSlVEJGaWimYX/MnIhuDpJ/U4Ik+uGZhC1aoBaAqVeFKuSrnXBb63b3EnI/FbGkik1MO3ogkkHNtvLnMt22WmAd+tYBfBJp/1C0UdOeaoXdeK2SrDX1iXc2URm05KZDPz

I have put it the past action in the on long press so you can test it, it's in the CardItensArtes component at button Adicionar mais artes

**Comment by Alezanello** [comment] 2024-07-02 14:10
Thank you for your report. I'm sorry you're experiencing this issue. While I was unable to reproduce it on a blank project, it is replicable on your specific project. This leads me to believe it's a project-specific issue.

Our support team is best equipped to help resolve this. Could you please follow up with them either via email at [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside FlutterFlow?

I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects.

If you manage to reproduce this issue on a blank project as well, please let us know and provide the bug report code for that project.

Thank you so much!

Best regards, Azanello

**Closed as not planned** 2024-07-02 14:10 UTC
Labels: closed : project specific

**Comment by pireslopesvinicius** [comment] 2024-07-02 14:14
Okay, thanks anyway, it seems to be specific to my project, but I've done a workaround
