### ISSUE TITLE
Web App "Entry Page" page does not load Navbar

### ISSUE THREAD

**Issue by EJS00102** [FlutterFlow/flutterflow-issues#867] opened 2023-05-09 13:30 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When the entry page of the web app is loaded, the navbar is not loaded or does not display. If I manually add the route onto the URL then the navbar loads.

### Expected Behavior

It is expected that the Navbar should load when the entry page is loaded. Otherwise it makes it very difficult to use the navbar.

### Steps to Reproduce

1. Create blank app
2. Add 2 pages
3. Display both on Navbar
4. Put 1 page as "Entry Page" and the other page as "Logged in"
5. Publish to web
6. It will automatically open on "Entry Page" without" Navbar
7. Manually add route to url
8. Reload page
9. Navbar appears

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89gocNc187qdcFAhQIgQ0QnU7gnlO1ucx4afLbwEO0IfOPsYUNKQu2FfAliM1CJnjk10ejmjofLKfJdGwuVY7Y60JVAVDyUZGW5MsmsCJOoTn9PHZ5MIFCA0LWzpCMlGLFZWmw76lz6Nq3qNleeY8aSfxBlZ7vfcPo=

### Context

This is a major problem, because if the navbar is not consistent, then it renders my app useless on web.

### Visual documentation

![Screenshot 2023-05-09 at 15 23 06](https://github.com/FlutterFlow/flutterflow-issues/assets/52255287/7d28b27f-af8d-472c-8b2a-f970f6a0e833)
![Screenshot 2023-05-09 at 15 23 48](https://github.com/FlutterFlow/flutterflow-issues/assets/52255287/7d5e58e9-7f95-439e-a74d-7be6977a8053)

### Environment

```markdown
- FlutterFlow version: Version 1.1.65 (1.1.65)
- Platform: Web App
- Browser name and version: SAfari Version 16.3 (18614.4.6.1.6) 
- Operating system and version affected: Mac 13.2.1 (22D68)
```

**Comment by EJS00102** [comment] 2023-05-09 16:36
This might help...

It seems like this only happens if your "Entry Page" is the same as the page you want to use as your "Home Page" and you want to display a Nav Bar on it. 

In other words, if you set your "Entry Page" as a onboarding page which then navigates to your "Home Page" then the Nav Bar will display.

I still think it's a bug though, because nothing prohibits you from putting a Navbar on your Entry Page.

**Comment by hariprasadms** [comment] 2023-05-09 17:51
Hi @EJS00102 - Thanks for submitting the issue. I agree with you. However, when considering web apps as in general, top or side nav bars are more frequently used than bottom nav bars. 

I can mark this as bug. Dev team can decide technically how we can fix it.

**Comment by nicmohr25** [comment] 2023-05-09 19:23
I have recognized the same behavior on IOS. The NavBar is not loading when you open the app with an user that is not authenticated. Once authenticated the navbar appears. Even when Logging out

**Comment by EJS00102** [comment] 2023-05-10 04:36
> Hi @EJS00102 - Thanks for submitting the issue. I agree with you. However, when considering web apps as in general, top or side nav bars are more frequently used than bottom nav bars. 
> 
> 
> 
> I can mark this as bug. Dev team can decide technically how we can fix it.
> 
> 
> 
> 

The thing is I am not planning to build only a web app, seeing that the premise of Flutterflow is one code base for all the platforms. 

Thanks for marking it as a bug, hopefully it can be fixed soon.

**Comment by agreaves** [comment] 2023-09-17 22:27
Hi @EJS00102, thank you for the bug report! Unfortunately this is actually the intended behavior at the moment. For authenticated apps, the Entry Page is intended to be used as a page for logging the user in or going through an onboarding flow, not as a home page in and of itself. Particularly because all of the other tabs will be able to be accessed even if they are marked as requiring authentication.

If this is absolutely necessary, I'd recommend creating a separate Entry Page and doing an On Page Load routing from that Entry page to the page with the nav bar when the app first opens.

**Closed by agreaves** 2023-09-17 22:27 UTC
Labels: type: bug, status: confirmed
