### ISSUE TITLE
Listview refresh database loses the scroll position and update page state doesn't update the list view. 

### ISSUE THREAD

**Issue by abhibalani** [FlutterFlow/flutterflow-issues#3500] opened 2024-07-29 06:50 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a posts feed on my app in a list view with pagination enabled. 

The feed API gets the feed and in each post element it has the data if the post is already liked or not.
I have the like/unlike button in a conditional builder. 
Like and unlike button calls an API and updates the liked/unliked state of the feed item. 

The api call succeeds and on "Refresh listview" the feed is updated but the track of the current post (scroll position) is lost.

Similarly I have a chat page where I am refreshing the listview every 10 seconds but on refresh it loses the scroll position. 

Video explanation: https://drive.google.com/file/d/1iuMGAAaetZ_jw4j52iojSwGu_7gsd5nC/view

### Expected Behavior

The expected functionality is that the like/unlike button should change state based on action success after re-fetching the feed but the scroll position should remain the same. 

I am able to achieve expected functionality if I keep the API call for feed outside (in a parent container) the ListView for feed and update the page state on successful like/unlike action. 

But I need to paginate the feed and for that I need to make the API call in the ListView widget.

### Steps to Reproduce

1. Create a list view
2. Bind data to it
3. add an action to refresh the list after every 5 seconds
4. scroll to the middle of list view
5. on refresh, the listview will be scrolled to top. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gz8jfz812ofpE7aX6bu9VoD0sQzN+aJc0sd4bGA0dCJzuPLMQdvXsQFNvQtznYAhIIUSmmkQF+Nr7iPzLC/UEPkmbfqI5yqVcbA2UZEWuQZOBDJeKX3QnEf9Tf2Kg56S02iZDJsdYS3ws7FyMDOTKaD3bJpC0IlFISq/LZO4=

### Visual documentation

![image](https://github.com/user-attachments/assets/83a4fee7-55d9-40ec-af5f-e63dfb1ca1ec)
![image](https://github.com/user-attachments/assets/b557f6e4-9637-4694-8fe1-f5a82db0fa29)

### Environment

```markdown
- FlutterFlow version: 4.1.78+
- Platform: Desktop
- Browser name and version: Chrome 126.0.6478.185
- Operating system and version affected: Windows 11
```

**Comment by paulperez-dev** [comment] 2024-07-30 02:42
Hi @abhibalani! This is how flutter behaves out of the box: if the screen is rebuilt, the position is reset to its default value. I'm closing this issue, this is not a bug.

**Closed as not planned** 2024-07-30 02:43 UTC
Labels: closed: not a bug

**Comment by abhibalani** [comment] 2024-07-30 05:04
@paulperez-dev Then how do you expect to build a chat message and a profile feed functionality using FlutterFlow with live updates? Or are you saying we cannot build that functionality using Flutterflow? Because that is a basic use case but cannot be built because of the limitations with Listview.

**Comment by abhibalani** [comment] 2024-07-30 16:40
cc @pooja-ff
