### ISSUE TITLE
ListView not showing Firebase records with DataTypes

### ISSUE THREAD

**Issue by orchard800** [FlutterFlow/flutterflow-issues#150] opened 2022-11-22 13:27 UTC
I'm trying to create a list of cards in a ListView from a collection in Firebase. It all works fine until I try to build the list with datatypes.

![dataType_bug](https://user-images.githubusercontent.com/84687635/203325024-7201157d-dace-4ff6-882d-b60607cc7c79.png)

Where I just use the string 'card_business_name' - that works fine. However, if I try to use my data type 'card_business: business_name' - no list shows.

I have followed all the troubleshooting steps but keep getting the same results.

Please help! This is really holding up production of our app.

**Comment by katherineqian** [comment] 2022-11-22 16:01
Hi @orchard800, 

In order to keep our issue tracker useful and maintainable for all users, please follow the bug report template while reporting bugs. We will be happy to re-assess when the necessary information is provided.

Also, it would be helpful if you could provide a Bug Report Code. This can be generated by going to the widget tree, right clicking on the affected widget, and selecting “Get Bug Report Code”. If the bug is not specific to a widget, selecting any widget will work.

Thank you!

**Comment by orchard800** [comment] 2022-11-24 01:22
Ah apologies for that! It's my first time posting on here.

I've managed to narrow down the actual issue and it's much easier to explain now:

I have a Listview returning a document collection from Firebase. All works great until I populate the document reference field in my dataType (business_ref). It works fine with all other field types, just not references. Check out the attached screenshots from FF content manager.

![image](https://user-images.githubusercontent.com/84687635/203672993-6f596e83-ccb3-4111-936d-7c2a20240c22.png)
![image](https://user-images.githubusercontent.com/84687635/203673009-4e5a72ec-6684-4a59-9a4c-3c73d5d5c3d6.png)
![image](https://user-images.githubusercontent.com/84687635/203673026-7d0d4ef5-2e69-4a41-ba84-be70f9a79c82.png)
![image](https://user-images.githubusercontent.com/84687635/203673035-7f45d3fb-3fb6-4c52-b590-cd5881327b49.png)

My bug report code (from the ListView) is: IT4ghc/1z4tPtbxa7aXycu9ahjgvG0AhU5c0sNtuTQIdCYDuBIYiaff8VEtVZ9O5T3NtKEWIgmYJp/THitrXCO5fHyqrRapk+KoJSjnMUnjkEuzyT+3IHDUHZbsSXTTm

**Comment by agreaves** [comment] 2022-11-29 04:04
Hi @orchard800, thanks for the info! I've taken a look but I'm not able to reproduce the issue at the moment in any other project. Would you mind if I ran your project, and tested this out to see if I can reproduce the behavior? All I'd need from you is to add the document references and confirm that the issue is happening. This would be super helpful, thanks!

**Comment by orchard800** [comment] 2022-11-30 11:28
Thanks for this @agreaves! Happy for you access whatever you need.

I recorded a loom video here:
https://www.loom.com/share/30bb632411154bfbbabd8183154510ea

The record in the example is: 
/cards/pJsVcE8BSYo4pFmJrBHs

**Comment by agreaves** [comment] 2022-12-18 21:52
Hey! Thanks for all the info, I'm now able to see what happened. Our CMS had a bug where Document References inside of Data Types are being added as Strings instead. This caused the document to fail to load since it tried to parse a String as a Document Reference, and so it does not show up.

This bug in the CMS will be fixed upon our next release, but for now you can fix the issue by making sure all Doc References are not Strings in your data.

**Closed by agreaves** 2022-12-18 21:52 UTC
Labels: status: needs information
