### ISSUE TITLE
Support GitHub Sign In for the FlutterFlow Windows desktop app

### ISSUE THREAD

**Issue by gagansuie** [FlutterFlow/flutterflow-issues#4013] opened 2024-10-09 05:48 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

GitHub sign-in is missing in the Windows desktop application 

### Expected Behavior

GitHub sign-in will be available on the Windows desktop application

### Steps to Reproduce

1. Download and install and try to login via GitHub

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

NA

### Visual documentation

![Screenshot 2024-10-09 004612](https://github.com/user-attachments/assets/448eb2d4-9a78-4d07-b2f7-f033e3d1a180)

### Environment

```markdown
- FlutterFlow version: Latest
- Platform: Windows
- Operating system and version affected: Windows
```

**Comment by Alezanello** [comment] 2024-10-09 12:39
Hi there!

Thank you for your feedback! I'll go ahead and create an internal feature request so the team is aware of this. However, since this is currently expected behavior, I'll close this issue to keep the tracking system focused on bugs rather than feature requests.

Feel free to reach out if you have any other questions or concerns!

**Closed as not planned** 2024-10-09 12:40 UTC
Labels: closed: feature / enhancement request

**Comment by gagansuie** [comment] 2024-10-29 02:15
https://www.flutterflow.io/desktop

I am unable to test my app on desktop because I cannot sign in using my github login.

**Comment by Alezanello** [comment] 2024-10-29 18:58
Hello!

To log in using your email and password, please try resetting your password through the web. Once you've set a new password, you'll be able to log in with your email and password without losing the option to log in via GitHub on the web.

Let us know if you need any further assistance!
