### ISSUE TITLE
Textfield read only bad styling

### ISSUE THREAD

**Issue by tiago-sales-packercrew** [FlutterFlow/flutterflow-issues#3468] opened 2024-07-24 09:31 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

A text field when read only we able to click on it, to see hover effects and the cursor even changes.

### Expected Behavior

The text field when the read only property is true there should be no hover effect, not clickable and the cursor should stay the same.

### Steps to Reproduce

1. insert text field in a page
2. set the read only to true
3. publish
4. hover and click

6. adding some label text also helps to preview the click action

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oz/Hqx89grs9J1s/IdfoxnSQRQnp+ULhJ0spBay0jF7KuDLMqY8/RVERoYOGhYW9XMWeKiWoW0+jUiOLxOMEqZBeZQNV7/qliTQLNUmGXeJStFJWgWH9AL+lVCnai3MG32xJSFNJtR3wOwDv7IeqQcAXrJ4zGNXoeDa/LZO4=

### Visual documentation

![image](https://github.com/user-attachments/assets/5b7aabc9-5820-492f-8210-a1afe755f0e4)

Read only set to true:
With out hovering
![image](https://github.com/user-attachments/assets/7e9a656d-c575-4835-840e-6b06c818a5b6)

Hovering
![image](https://github.com/user-attachments/assets/1210d269-793a-487a-bb79-e960b51fb745)

Clicked highlights the textfield
![image](https://github.com/user-attachments/assets/67400e0f-7a7b-4ae1-86ba-8d86a7d98e12)

### Environment

```markdown
- FlutterFlow version: v4.1.75+ released July 23, 2024
- Platform: Test mode, and local run-in web, also in android, couldn't test in IOS but I believe will do the same
- Browser name and version: edge, chrome, all.
- Operating system and version affected: couldn't test in operating system.
```

### Additional Information

project id: test-project-wzubn4

**Comment by msusviela** [comment] 2024-07-24 12:03
Hi @tiago-sales-packercrew. I've checked this and it's expected behavior. You can modify the color when it's tapped over depending if you're on readonly in this section:

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/3616a283-4998-42a8-b25e-1dfde1546f4f/55f6fa46-78e2-4bda-99af-f5b4581358a9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zNjE2YTI4My00OTk4LTQyYTgtYjI1ZS0xZGZkZTE1NDZmNGYvNTVmNmZhNDYtNzhlMi00YmRhLTk5YWYtZjViNDU4MTM1OGE5IiwiaWF0IjoxNzIxODIyNTgzLCJleHAiOjMzMjkyMzgyNTgzfQ.PXGlI33SrUgRxNCbU_jqn40oTvU2EhqWXSac9oCvzsc " alt="image.png" width="198" height="185" />

You can select the colors adding a conditional that can depend on the variable you used for enabling readonly. 

I'm closing this issue since this tracker is only for bugs. <br><br>Thanks for filling in!

**Closed as not planned** 2024-07-24 12:03 UTC
Labels: closed: not a bug

**Comment by tiago-sales-packercrew** [comment] 2024-07-24 12:15
The problem is not just the color! If the text field is empty, and the read only is true, if you click/tap you will be able to see the label text move to top as it read only text was false, which means the read only gets focused, what also means this should not be possible. 

I'm sorry to hear that you're closing without really looking into the problem. 

Readonly = true
Textfield not tapped
![image](https://github.com/user-attachments/assets/42c82b5d-da3d-4fc1-8656-e9f6bc058f5b)

Textfield tapped
![image](https://github.com/user-attachments/assets/67f11246-9fb6-4d88-b30a-96cc63bd67bb)


The read-only should disable any actions to the textfield... or at least should be an option for the dev to choose to either keep the actions or disable them.

**Comment by msusviela** [comment] 2024-07-24 12:34
I totally see your point but I have looked into the issue and I've looked into the generated code. That's expected behavior because if you use the same widget (TextFormField) in native Flutter and enable readonly, the same will happen. We are using Flutter to generate the code, so if we generate a widget with the readonly property, we expect to match the behavior that Flutter offers.

**Comment by tiago-sales-packercrew** [comment] 2024-07-24 13:45
In that case, thank you for your time, as I'm coming from JS I'm used to have this kind of behaviour.

Also in this case, more power to the feature that allows devs to choose to keep the flutter behavior or the other.


Keep up with the good work. For this time, I'll build a new component with a condition regarding a page state to either show one or the other (text field or just the value in simple text widget)!
