### ISSUE TITLE
Unable to call firebase functions in test mode

### ISSUE THREAD

**Issue by Noah765** [FlutterFlow/flutterflow-issues#26] opened 2022-10-07 08:48 UTC
Hello everyone,

I've got a custom action looking like this:
```
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_functions/cloud_functions.dart';

Future<void> callCloudFunction(
  BuildContext context,
  String name,
  dynamic parameters,
) async {
  try {
    final FirebaseAuth auth = FirebaseAuth.instance;
    final User? user = auth.currentUser;     // User is logged in, user uid is available

    final FirebaseFunctions functions = FirebaseFunctions.instance;

    await functions.httpsCallable("addTeacher").call({});        // Crashes here
  } on FirebaseFunctionsException catch (error) {
    ScaffoldMessenger.of(context).showSnackBar(SnackBar(
      content: Text(error.message!, style: const TextStyle()),
      duration: const Duration(seconds: 2),
      backgroundColor: const Color(0xFFFF0000),
    ));
  } catch (e) {
    ScaffoldMessenger.of(context).showSnackBar(SnackBar(
      content: Text(e.toString(), style: const TextStyle()),
      duration: const Duration(seconds: 2),
      backgroundColor: const Color(0xFFFF0000),
    ));
  }
}
```

When testing in debug mode I noticed the error message:
```NoSuchMethodError: tried to call a non-function such as null: 'dart.global.firebase.auth'```

After I added these lines:
```
final FirebaseAuth auth = FirebaseAuth.instance;
final User? user = auth.currentUser;     // User is logged in, user uid is available
```
the error message changed to:
```NoSuchMethodError: tried to call a non-function such as null: 'dart.global.firebase.functions'```

I have found these resources regarding these kinds of errors:
https://stackoverflow.com/questions/57114754/nosuchmethoderror-tried-to-call-a-non-function-such-as-null-dart-global-fir
https://stackoverflow.com/questions/57242045/flutter-web-tried-to-call-a-non-function-such-as-null-dart-global-firebase-s
https://stackoverflow.com/questions/73784197/nosuchmethoderror-tried-to-call-a-non-function-such-as-null-dart-global-fire

**Comment by agreaves** [comment] 2022-10-07 16:48
Hi @Noah765, this occurs because Firebase Cloud Functions require additional configuration in order to run properly (in this case it's missing a necessary `.js` file), and FlutterFlow does not know to add it if you are using it in a custom code.

For this reason, unfortunately not all custom code will work in FlutterFlow. However, in this case there is good news! There is a workaround you can do, which is to create a fake API call and mark it as private. This will use cloud functions to call it and FlutterFlow will add the files you need in this case.

Closing this issue for now since it's not a bug so much as a current limitation of the platform.

**Closed by agreaves** 2022-10-07 16:48 UTC
Labels: status: needs triage

**Comment by Noah765** [comment] 2022-10-08 07:38
It works! ... until I try to move the function to Europe, then Firebase just always returns the "internal" error
