### ISSUE TITLE
Blur widget overflows border radius

### ISSUE THREAD

**Issue by sirian-m** [FlutterFlow/flutterflow-issues#78] opened 2022-11-01 10:49 UTC
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

The blur is contained within the border radius of the child backdrop widget.

## Current behavior (required)

The blur overflows the border radius set by the child widget. The behavior also occurs when "Clip Content" is enabled on the child container or when the blur is wrapped in a container with the same border radius, also when "Clip Content" is enabled on that wrapping container.

## To Reproduce (required)

1. Add blur widget
2. Enable backdrop
3. Add container widget as a child
4. Set the border radius to something larger than 0
5. Click Run
6. Observe that the backdrop blur still has sharp corners and that the set border radius is not applied

## Context (required)

Create a nice rounded frosted glass container.

## Screenshots / recordings

Expected:

![image](https://user-images.githubusercontent.com/109159237/199216394-70ddde8e-3db0-4bad-971c-21d136374e9c.png)

Current:

![image](https://user-images.githubusercontent.com/109159237/199216435-f52c9ce7-902d-4012-8ede-8951e98ce144.png)

## Your environment

* **Bug Report Code:**
* Version of FlutterFlow used: 3.3.4
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome 106
* Operating system and version (desktop or mobile): Desktop

**Comment by hariprasadms** [comment] 2022-11-01 16:23
Hi, I can test this and looks fine in my app. 

I suggest try this in another page and see the consistency. If you could share the code snippet of this widget tree from the code view that would great.  

![image](https://user-images.githubusercontent.com/17435678/199283450-b30d02ea-049d-4c5d-b3b1-fdd2444a169b.png)

**Comment by organicnz** [comment] 2022-11-01 17:45
Hi mate,

Yeah look fine on my test page, but I see it on a published page :)

Test page
<img width="1435" alt="Screen Shot 2022-11-01 at 20 37 13" src="https://user-images.githubusercontent.com/4765090/199301378-d47884da-daa3-4717-bcda-a00940bfc21f.png">

Published page
<img width="1440" alt="Screen Shot 2022-11-01 at 20 40 47" src="https://user-images.githubusercontent.com/4765090/199301522-23ed0e66-a2f8-4929-93ef-8edb89c42707.png">

Widget tree
<img width="1439" alt="Screen Shot 2022-11-01 at 20 45 15" src="https://user-images.githubusercontent.com/4765090/199302068-c81601c1-fc49-4a9c-91f0-5853131469c9.png">

**Comment by sirian-m** [comment] 2022-11-01 20:03
> Hi, I can test this and looks fine in my app.
> 
> I suggest try this in another page and see the consistency. If you could share the code snippet of this widget tree from the code view that would great.
> 
> ![image](https://user-images.githubusercontent.com/17435678/199283450-b30d02ea-049d-4c5d-b3b1-fdd2444a169b.png)

It looks lie you don't have backdrop blur enabled, that's were I have the issue. When you enable backdrop, lower the opacity of the color of the chil container to see the backdrop. I'm not sur eif this works, bit try copying this into your widget tree:
"Cg5TdGFja181enU3YTVhORJbCg5JbWFnZV8wZ3BjY2hkNBgHIkUyQAoiaHR0cHM6Ly9waWNzdW0ucGhvdG9zL3NlZWQvMjU3LzYwMBABGAMiFgoJCQAAAAAAAPB/EgkJAAAAAAAA8H/6AwBiABLAAgoSQ29udGFpbmVyXzBjdTJjNHp6EsIBCg1CbHVyX3g2Zmh5djc1EoMBChJDb250YWluZXJfeTM3am5qbnkYASJpClAKFgoJCQAAAAAAwGJAEgkJAAAAAAAAXkASMhIkCQAAAAAAAERAEQAAAAAAAERAGQAAAAAAAERAIQAAAAAAAERAQgYIgICAwANaAGIAIgAwAHISCQAAAAAAAAAAEQAAAAAAAAAA+gMAYgAYMSIncgkJAAAAAAAAAACyAxYJAAAAAAAAOEARAAAAAAAAOEAYASAB+gMAYgAYASJhCkgKFgoJCQAAAAAAwGJAEgkJAAAAAAAAXkASKhIkCQAAAAAAAERAEQAAAAAAAERAGQAAAAAAAERAIQAAAAAAAERAWgBiACIAMAFyEgkAAAAAAAAAABEAAAAAAAAAAPoDAGIAGA8iHloJEQAAAAAAADhAggENCgsSCQkAAAAAAABpQPoDAA==" 

This is the copied data from my widget tree where the issue is present in. Notice: it will show correctly in the editor, but in run mode or in a build it won't.

The generated code:

`Padding(
  padding: EdgeInsetsDirectional.fromSTEB(0, 24, 0, 0),
  child: Container(
    height: 200,
    child: Stack(
      children: [
        Image.network(
          'https://picsum.photos/seed/257/600',
          width: double.infinity,
          height: double.infinity,
          fit: BoxFit.cover,
        ),
        Align(
          alignment: AlignmentDirectional(0, 0),
          child: ClipRRect(
            borderRadius: BorderRadius.circular(40),
            child: Container(
              width: 150,
              height: 120,
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(40),
              ),
              child: Align(
                alignment: AlignmentDirectional(0, 0),
                child: ClipRect(
                  child: BackdropFilter(
                    filter: ImageFilter.blur(
                      sigmaX: 24,
                      sigmaY: 24,
                    ),
                    child: Align(
                      alignment: AlignmentDirectional(0, 0),
                      child: Container(
                        width: 150,
                        height: 120,
                        decoration: BoxDecoration(
                          color: Color(0x38000000),
                          borderRadius: BorderRadius.circular(40),
                        ),
                      ),
                    ),
                  ),
                ),
              ),
            ),
          ),
        ),
      ],
    ),
  ),
)`

**Comment by hariprasadms** [comment] 2022-11-02 14:50
Thanks for sharing the code snippet. It helped me to reproduce the behaviour you can see. The steps you have provided initially did't include the sigmaX: 24, sigmaY: 24 properties and its values. hence it was not able to reproduce the behaviour. 
The behaviour what you can see is controlled by using sigmaX and sigmaY property values ( Look at its help tips on the editor ). At present In FF blur widget got the less properties to add more customisation and it is working as expected. to get the best out of it, you should play with its available properties and its child widget properties.

Below I have added an example which is showing blur and container widgets with colour property. If I add the border to container it can show the blur boarder around. So to hide it ,I have removed the container border property. Something like this you can try and fit few customisation.  

![image](https://user-images.githubusercontent.com/17435678/199520222-dfb76e1a-5230-4c82-9e0c-41e3bbbcfdc2.png)

However, I can pass this info to developer team and see if they can add more properties to change the share of blur widget. But it is going to be enhancement for the existing blur-widget.

**Comment by sirian-m** [comment] 2022-11-02 15:02
Thanks for your response!

But I'm not entirely sure you understand what I mean. What I want is a rounded corner container with a backdrop filter blur on it which is only limited to the rounded corner container (similar as to what Apple uses a lot). The problem is that this backdrop blur does currently not adhere to the set border radius on the child container.

I want to achieve this:
![image](https://user-images.githubusercontent.com/109159237/199524342-83905885-6909-4b27-861d-fd208b22b280.png)

But FF currently does this, it doesn't clip the backdrop blur as you can see:
![image](https://user-images.githubusercontent.com/109159237/199524448-204cae4f-e52c-466d-affc-598633c6a5f1.png)

**Comment by katherineqian** [comment] 2022-11-05 16:11
This should be fixed in the next release.

**Closed by katherineqian** 2022-11-05 16:11 UTC
Labels: type: feature request
