### ISSUE TITLE
JSON Response from GET API's cannot be stored/used in page state variables.

### ISSUE THREAD

**Issue by Aravind-Aji** [FlutterFlow/flutterflow-issues#1191] opened 2023-07-31 08:58 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After calling a GET API , I'm getting the response . I can see the response in console , but I'm not able to use/store that JSON response .

### Expected Behavior

The response of GET API calls should be able to be used properly.

### Steps to Reproduce

1. Create a new page with list of some items.
2. Call an API to get that list of items.
3. Display the list of items with response from API Call.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kivHlsYtPxc9c1pDpbe5GgigQKXo9TL07r+5xb0gvIrbyOu9/OeDBTE1VYMugTXlhHGGgmk4CwPuOjYbfIe4qJRecR7U4zbhQUQnNWXq8R4yVO8/pTnFTHdNRC0yl5KTYuCR+AMVaW3xg6mWyfeuAcCrBN5+/Zwh9f6PHaOI=

### Context

I am not able to complete my project without fixing this issue.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/70636253/4fc088a1-714d-47ff-b1c9-fa7724e6eb61)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/70636253/b92b0b44-a9e6-46b7-a4f2-d00b18c831f4)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/70636253/2d62e906-7991-486b-bd60-7c26d2b4c391)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/70636253/ba3c7322-5582-4214-9281-71380d1dec71)

### Environment

```markdown
- FlutterFlow version:  v3.1 (released Feb 27, 2023)
- Platform:Web
- Browser name and version: Chrome 107.0.5304.110
- Operating system and version affected: Microsoft Windows 11 Pro 10.0.22000 Build 22000
```

**Comment by WellDunDun** [comment] 2023-07-31 12:45
@Aravind-Aji I don't recommend using on page load for API calls where you need the data from it to be displayed on the page. The widgets that need that data will begin painting before the API call is complete and the app state is set. You have a few options:

1. Conditionally display the listview based on app state is set (so it won't show if that app state doesn't have the data yet)
2. Make the backend query on a container instead (don't make calls on columns because it will keep calling the API for every movement in the column)

Hope this helps!

**Comment by ghfsystem** [comment] 2023-07-31 14:24
I can confirm that i am not able to get any values into the UI builder.
When we use th json path to bind, it is reads it as null.

Where as the json path in the API configuration section, does actually show the correct values from the response as intended.

Test api call works.

I have 2 pages, where on page 1, on click of a button i am calling an api call and launching the url from the json response. doesn't work.

Network call response of API is correct.

**Comment by katherineqian** [comment] 2023-09-29 20:17
Hi, there have been several improvements to JSON responses (for example, https://github.com/FlutterFlow/flutterflow-issues/issues/1302#issuecomment-1727597603, #1312) in the last updates. Can you confirm whether these issues have resolved for you? I will close the issue for now, but please feel free to reopen if you continue to experience this problem.

**Closed by katherineqian** 2023-09-29 20:17 UTC
Labels: type: bug, status: confirmed
