### ISSUE TITLE
Dynamic value for switch is not working

### ISSUE THREAD

**Issue by pratimadudhewar** [FlutterFlow/flutterflow-issues#2028] opened 2023-12-19 13:56 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Need your help regarding the  switch dynamic value.
We have a preferences screen , where the user can set his preferences for Languages and channels.
On change of a dropdown menu we update the page state, which is getting updated properly but can't view this updated values for switch.
I have put the checkbox and switch both where the checkbox gets updated properly but why can't it update the Switch?
![switch3](https://github.com/FlutterFlow/flutterflow-issues/assets/154335911/00d7ee58-3800-4f83-9800-373b6b43c699)

Is there a different way of implementation for the switch, as switch is a component?
Please find the attached screenshots for more details. 
![Switch2](https://github.com/FlutterFlow/flutterflow-issues/assets/154335911/94c707f6-0462-4a55-b8a5-8d18e200351a)

### Expected Behavior

Expected behavior is  when page state value is changing , switch value should reflect latest value

### Steps to Reproduce

1)Run the Project
2) open drawer on clicking  an app  icon from Murli Screen
3) Click on Preferences from drawer.
4) Check values in listview by changing the dropdown value from the header.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kzufl+otPxd9Y0LX1be1V/TsQJkAnTLIFse0aRR4aIZzrEYYAf8/7X0NKTcuDeG5AH2H8rHoEpqnpkdjtEvQ7FySZUak+0JVAFwnxVnmmRbrSC823dnEmGZhgBWq84LSFpAl4KrJpS3AA1znyN63qNleeY8aSfxBlZ7vfcPo=

### Context

User to view the latest preferences set for particular center.

### Visual documentation

N/A
![Switch2](https://github.com/FlutterFlow/flutterflow-issues/assets/154335911/731cd9b1-50b2-4d20-bf6b-30b77a342f90)
![switch3](https://github.com/FlutterFlow/flutterflow-issues/assets/154335911/1d301256-d03e-4af4-a933-284d72d8cc77)

### Environment

```markdown
- FlutterFlow version: 
- Platform: web
- Browser name and version:Chrome
- Operating system and version affected: Windows 10
```

**Comment by hariprasadms** [comment] 2023-12-22 12:14
Hi @pratimadudhewar - Thanks for submitting the issue. I can reproduce the issue. This is issue is happening for both switch and checkbox widgets. 

**Dev note** - In the video below, you'll observe that upon triggering the click action of the buttons, the text value on the page gets modified during the rebuild. However, the same action does not result in a change in the status of the switch and checkbox widgets.

https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/8cc55f57-a714-460e-aa20-92887c41026a

**Comment by wenkaifan0720** [comment] 2023-12-25 02:25
Hi @hariprasadms. Could you share with me the test project you used?

**Comment by ignalauret** [comment] 2024-04-22 19:32
Hey @pratimadudhewar thanks for your report. I was able to verify that there is no way of changing the value of the Switch or Checkbox dynamically when it's already built. You can change its initial value dynamically, but not modify it after. Since this is a feature that is not yet implemented on FlutterFlow, I'm creating a Feature Request for our engineering team and linking this issue so you get updated when its completed.
I'm closing this issue since its not a bug, have a great day!

**Closed by ignalauret** 2024-04-22 19:32 UTC
Labels: type: bug, status: confirmed, not in linear
