### ISSUE TITLE
allowImages in Chat widget is not working as expected

### ISSUE THREAD

**Issue by KavyaDevv** [FlutterFlow/flutterflow-issues#456] opened 2023-02-08 09:52 UTC
## Expected behavior (required)
When I turn off the Allow Images in Chat widget, it should not show the camera option

## Current behavior (required)
When I turn off the Allow Images in Chat widget, it is showing the camera option

## To Reproduce (required)

1. Create new page
2. Add Chat widget
3. Set Allow Images
4. Click Run
5. Observe that page will show the camera icon

## Context (required)
I want to hide the camera icon in the Chat

## Screenshots / recordings
Test ProjectURL: https://app.flutterflow.io/project/chat-test-mvjo6t

## Your environment

* Version of FlutterFlow used: v3.0
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome Version 109.0.5414.75
* Operating system and version (desktop or mobile):

**Comment by bulgariamitko** [comment] 2023-02-09 10:13
This issue tracker is intended for general bugs that are applicable to all users. Because this error appears to be specific to your project and the steps are not reproducible, this is classified as a support request and will be closed. Please use chat support or contact support [at] flutterflow.io for further assistance.
 
 If you do find a specific reason for the issues you are encountering in your project, please don’t hesitate to open a new bug report with the relevant steps to reproduce.
 
 Thank you for your contribution!

**Comment by ibm777p2** [comment] 2023-02-10 07:30
> This issue tracker is intended for general bugs that are applicable to all users. Because this error appears to be specific to your project and the steps are not reproducible, this is classified as a support request and will be closed. Please use chat support or contact support [at] flutterflow.io for further assistance.
> 
> If you do find a specific reason for the issues you are encountering in your project, please don’t hesitate to open a new bug report with the relevant steps to reproduce.
> 
> Thank you for your contribution!

I don't think this issue isa specific to one project, it's actually happening to me too and I can't remove the camera icon in the chat even if I click on allow image to false. I have to remove the camera icon manually before submitting the code to the stores.

**Comment by foldingtable** [comment] 2023-02-10 16:47
> This issue tracker is intended for general bugs that are applicable to all users. Because this error appears to be specific to your project and the steps are not reproducible, this is classified as a support request and will be closed. Please use chat support or contact support [at] flutterflow.io for further assistance.
> 
> If you do find a specific reason for the issues you are encountering in your project, please don’t hesitate to open a new bug report with the relevant steps to reproduce.
> 
> Thank you for your contribution!

I agreed with IBM. I set up several self contained chat projects, and disabled/turn-off the Allow Images, but the camera remained and allow users to upload images.

**Comment by foldingtable** [comment] 2023-02-10 16:51
> > This issue tracker is intended for general bugs that are applicable to all users. Because this error appears to be specific to your project and the steps are not reproducible, this is classified as a support request and will be closed. Please use chat support or contact support [at] flutterflow.io for further assistance.
> > If you do find a specific reason for the issues you are encountering in your project, please don’t hesitate to open a new bug report with the relevant steps to reproduce.
> > Thank you for your contribution!
> 
> I don't think this issue isa specific to one project, it's actually happening to me too and I can't remove the camera icon in the chat even if I click on allow image to false. I have to remove the camera icon manually before submitting the code to the stores.

Hi IBM, how did you remove the camera icon manually? I'm not a programmer, if possible, can you do a step-by-step? (sorry if this is the wrong forum). Thanks in advance.

**Comment by foldingtable** [comment] 2023-02-10 17:08
> > This issue tracker is intended for general bugs that are applicable to all users. Because this error appears to be specific to your project and the steps are not reproducible, this is classified as a support request and will be closed. Please use chat support or contact support [at] flutterflow.io for further assistance.
> > If you do find a specific reason for the issues you are encountering in your project, please don’t hesitate to open a new bug report with the relevant steps to reproduce.
> > Thank you for your contribution!
> 
> I agreed with IBM. I set up several self contained chat projects, and disabled/turn-off the Allow Images, but the camera remained and allow users to upload images.

Just to clarify, the camera will disappeared on Flutterflow itself, but when run in Test, Run mode and on a real device, the camera remained and images are upload-able.

**Comment by ibm777p2** [comment] 2023-02-10 17:24
Ok, I will list out the steps the simplest way possible if you think it's too technical let me know.
(This works the same in PC or Mac, I'm using Mac though)
-Download the code in a zip file.
-Unzip the file and all your code will be in a folder.
-Drag the folder into Visual Studio Code window(you will need to download Visual studio code if you don't have it)
-Once your code is in Visual Studio Code look for this file name "flutter_flow_chat_widget.dart"
-all you have to is to remove the following code and you are all set

                  trailing: [
                      if (uploadMediaAction != null)
                        Padding(
                          padding: const EdgeInsetsDirectional.only(
                              start: 12.0, end: 6.0),
                          child: InkWell(
                            onTap: uploadMediaAction,
                            child: const Icon(
                              Icons.camera_alt_outlined,
                              color: Color(0xA1A1A1A1),
                              size: 24,
                            ),
                          ),
                        ),
                    ],

**Comment by foldingtable** [comment] 2023-02-10 18:57
> Ok, I will list out the steps the simplest way possible if you think it's too technical let me know. (This works the same in PC or Mac, I'm using Mac though) -Download the code in a zip file. -Unzip the file and all your code will be in a folder. -Drag the folder into Visual Studio Code window(you will need to download Visual studio code if you don't have it) -Once your code is in Visual Studio Code look for this file name "flutter_flow_chat_widget.dart" -all you have to is to remove the following code and you are all set
> 
> ```
>               trailing: [
>                   if (uploadMediaAction != null)
>                     Padding(
>                       padding: const EdgeInsetsDirectional.only(
>                           start: 12.0, end: 6.0),
>                       child: InkWell(
>                         onTap: uploadMediaAction,
>                         child: const Icon(
>                           Icons.camera_alt_outlined,
>                           color: Color(0xA1A1A1A1),
>                           size: 24,
>                         ),
>                       ),
>                     ),
>                 ],
> ```

Thanks so much. I'll give it a go.

**Comment by wenkaifan0720** [comment] 2023-02-19 08:42
This is indeed a bug on our end. Should be fixed in the next update. Thank you!

**Closed by wenkaifan0720** 2023-02-19 08:42 UTC
Labels: type: bug, status: confirmed, closed: fixed
