### ISSUE TITLE
FlutterFlow keeps removing specifics fields of my actions

### ISSUE THREAD

**Issue by 00davidsarago00** [FlutterFlow/flutterflow-issues#3535] opened 2024-08-01 20:47 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

# I'm having the trouble when I set a firebase query to bring certain documents related to the current Authenticated User. 
When I set the fields to relate those IDs (UserID in the firebase document and the Auth. User's ID) and save the project, just in less than a minute, the field of the Auth. UserID is blank.

---

![1](https://github.com/user-attachments/assets/4cc7eb42-22ec-4bdd-83b9-e3fce63d39e4)

## *A couple seconds later...*

![2](https://github.com/user-attachments/assets/bb5bcd39-9b42-4de1-a1f6-b2e6416ce90f)

![CleanShot 2024-08-01 at 17 15 48@2x](https://github.com/user-attachments/assets/fa57fa92-d254-4876-81d7-04e32f058ae8)

![CleanShot 2024-08-01 at 17 19 04@2x](https://github.com/user-attachments/assets/4a824171-7c9b-4844-a997-022a90da69f4)

---

### Expected Behavior

The expected behavior is to not remove the fields that I've already set.

### Steps to Reproduce

0. On Page Load Action of HomeShadow
1. Make a firebase query
2. Set the collection band
3. Set the query type to Single Document or whatsoever you want
4. Set a filter (in my case it's to relate collection's document (userUuid) to Auth. userID, both have to be equal to each other)
5. Save the project
6. Start a run test
7. Wait a couple seconds
8. See that the Auth. userID's fields are all blank.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4giPLl8ZVOj7xH1rr+LO9Wr2A7G2I3bb00sNobbxAjIoDoPJkUacjCUBJCOdTgYFZpKEWIjXEKwPuOiYf9NsY5Cw6BR4BRwboBWznMcEK/aoS6DZeWR3dAP+dnGn600aSS2yJBIvp2S14f7UOMAuSUfB3vO7H7Zwh9f6PHaOI=

### Visual documentation

![CleanShot 2024-08-01 at 17 35 19@2x](https://github.com/user-attachments/assets/98407b6d-9bc4-41fe-8748-f38778b62945)
![CleanShot 2024-08-01 at 17 35 34@2x](https://github.com/user-attachments/assets/c7955e34-9c21-45ea-8af3-bd117a4192a3)
![CleanShot 2024-08-01 at 17 37 24@2x](https://github.com/user-attachments/assets/88a14fe6-4001-4881-8b30-e95c1d67abbc)
![CleanShot 2024-08-01 at 17 38 20@2x](https://github.com/user-attachments/assets/37be8caf-3b3b-4002-98bb-2418716bb26d)
## Saving the project
![CleanShot 2024-08-01 at 17 38 25@2x](https://github.com/user-attachments/assets/63a2b7bd-bf66-46e0-a134-55ecd19f88d5)
## Running Test Mode
![CleanShot 2024-08-01 at 17 38 41@2x](https://github.com/user-attachments/assets/c2be4b61-ea3b-4fc8-939f-e8fdd2c037e6)
## The errors came back :(
![CleanShot 2024-08-01 at 17 39 00@2x](https://github.com/user-attachments/assets/399ee5c6-3edb-4417-8c42-690f0b5156e0)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.79 released August 1, 2024
- Platform: IOS, Android
- Browser name and version: (Desktop App for Mac) and (Chrome 127) 
- Operating system and version affected: OS X 10.15.7
```

### Additional Information

I don't know exactly if the Run Test Mode Step is directly related to the problem, but there it is.

**Comment by msusviela** [comment] 2024-08-02 02:17
Hi @00davidsarago00.<br>Thank you for your report.<br>I'm closing this issue since it's a duplicate of this one:<br>[https://github.com/FlutterFlow/flutterflow-issues/issues/3529](https://github.com/FlutterFlow/flutterflow-issues/issues/3529)<br>The ENG team is working on a fix for this.<br>You can follow the original issue to keep updated. Thanks!

**Closed as not planned by msusviela** 2024-08-02 02:17 UTC
Labels: closed: duplicate

**Comment by agreaves** [comment] 2024-08-04 01:01
Hi @00davidsarago00, apologies for this issue! This should now be fixed on web!
