### ISSUE TITLE
Google Login Error in Android

### ISSUE THREAD

**Issue by Jeffcyw** [FlutterFlow/flutterflow-issues#3876] opened 2024-09-23 04:58 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm using supabase auth and followed all the steps in setting up the Google log in. It works well for awhile until lately I've just deployed a new updated version (haven't changed any of the auth settings except setting up firebase for analytics) and now it's not working on my phone anymore, even on the older production version I'm not able to login with Google anymore. The list of email came out and upon select it just disappeared and nothing happens.

Checked the cloud console SHA1, it's matching with my Play Store app signing. 

Could this be because I'm not using Firebase auth but have Firebase set up and reconfig the file causing the issue?

### Expected Behavior

Google login should be working on all android device.

### Steps to Reproduce

Try logging in with Google on Android phone

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4WhsmA8YxJpbxE1s+NdcZR/WAWHEwlaOcrm8N9cw0aF5fpPaYPX/z4UBJoTbyndglIfWCGuGUz3MLGm9z1E+w3NRKVGK5O/qtQaw/KcEe7V8XWErqwQH9EGshjIEiD0JjUhxV4VdRsSXgY1FOmIdyASi/YCZewNlUnMfyaC5DXvgfuQ0SLb3kNh1JWeC/v

### Visual documentation

No response after pressing log in with Google

### Environment

```markdown
- FlutterFlow version: 
- Platform: 
- Browser name and version:
- Operating system and version affected: Android
```

**Comment by harsh-sachdev** [comment] 2024-09-23 06:40
I'm also facing the same issue after the September 21 update. When I click on the Google Sign-In button, the email ID modal appears, but after selecting the email, nothing happens. I tried debugging the code locally, and after selecting the email, I see this error in the console.

```
PerfMonitor binderTransact: time=234ms interface=com.google.android.auth.IAuthManagerService code=5
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(exception, ERROR, null, null)
```

**Comment by taken35** [comment] 2024-09-23 07:05
I am also having exactly the same issue after the September 21. Please note Google login works in other platforms of my app except my testing Android phone.

**Comment by burakbaskan** [comment] 2024-09-23 08:30
https://community.flutterflow.io/ask-the-community/post/login-issues-started-to-happen-with-android-e2nluFSgEyxvC0A

**Comment by Alezanello** [comment] 2024-09-23 13:49
Hello,

It looks like this is a duplicate of an existing issue: [FlutterFlow Issue #3872](https://github.com/FlutterFlow/flutterflow-issues/issues/3872). To streamline efforts and avoid duplication, I will be closing this ticket. Please feel free to provide any updates or follow the progress on the main issue.

Thank you for your understanding!

**Closed as not planned by Alezanello** 2024-09-23 13:49 UTC
Labels: closed: duplicate
