### ISSUE TITLE
FlutterFlow fails to launch after new update

### ISSUE THREAD

**Issue by whitedirewolf** [FlutterFlow/flutterflow-issues#2907] opened 2024-05-14 15:29 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

This morning I went ahead and downloaded  the new update for FlutterFlow, once the update was complete and I attempted to re-launch the software I received a critical error and the application failed to launch. I posted this error on the FlutterFlow community page, and was directed to post it here. 

<img width="1440" alt="Error" src="https://github.com/FlutterFlow/flutterflow-issues/assets/32909521/f8aaa2df-0f7e-4c79-bb7f-628ef416160e">

### Expected Behavior

After the update I excepted the app to work so I could continue with my work. 

### Steps to Reproduce

This was an update error that is now making it impossible for the FlutterFlow app to work as intended on my Macbook. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

This is impossible for me to get. 

### Context

It has affected me greatly and I am desperate for help. 

### Visual documentation

<img width="1440" alt="Error" src="https://github.com/FlutterFlow/flutterflow-issues/assets/32909521/309506af-8bb4-4d35-9d28-06e3919c61d2">

### Additional Info

I have deleted the app and attempted to re-download and install, this resulted in the same error. 

### Environment

```markdown
- FlutterFlow version: Version 4.1.38
- Platform: Macbook Pro
- Browser name and version: Google Chrome
- Operating system and version affected: MacOS Big Sur (I understand this is a very old OS but so is my Macbook Pro (I fear a recent update will bomb my computer; this has happened before, I time machined my laptop)
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by ignalauret** [comment] 2024-05-15 01:53
Hey @whitedirewolf thanks for your report. I'm really sad for this crash that you are experiencing, I hope you were able to maybe restart your computer and make it work again.  I will send to our technical team to see if they can figure out the root cause of this. Have a great day!

**Comment by whitedirewolf** [comment] 2024-05-15 06:26
Hey @ignalauret No luck this morning either sadly... I desperately need the app to work again so  I can continue with my work. Is it possible to backtrack the update in any way?

**Comment by clintdoriot** [comment] 2024-05-21 10:08
I'm experiencing this exact crash as well, even after updating to 4.1.53. I'm in a similar situation of having MacOS 11 Big Sur, and am unable to upgrade.

I ran into this issue a month or two ago. Seemed like everyone having the issue was on MacOS 11. But then it got resolved with a new build a few days later

**Comment by clintdoriot** [comment] 2024-05-31 15:12
The new version (4.1.54) resolves this issue for me.

**Comment by paulperez-dev** [comment] 2024-06-03 20:00
Hi @clintdoriot! Thanks for confirming! @whitedirewolf can you please verify if the issue persists after updating to the latest version?

**Comment by whitedirewolf** [comment] 2024-06-04 06:21
Hey everyone! Yes it is working now! thanks.

**Comment by paulperez-dev** [comment] 2024-06-04 12:44
Thanks! I'm closing this issue.

**Closed** 2024-06-15 17:41 UTC
Labels: Bug, macOS
