### ISSUE TITLE
Custom function that uses enum fails in compilation and test mode is unavailable - URGENT

### ISSUE THREAD

**Issue by chesskiss** [FlutterFlow/flutterflow-issues#3708] opened 2024-08-29 17:08 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

This time I'm attaching the link to the video to reproduce.

The test does not compile. See the error below.
![Screenshot 2024-08-24 at 6 34 12 PM](https://github.com/user-attachments/assets/d3a2b174-5bbd-42b7-8dee-4e3d4eb86dda)

### Expected Behavior

Should compile and run in test mode

### Steps to Reproduce

please see video

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEelPHlw852j70E0Ln+de5FlQMwGkQ5a7sviu5+FBQaI+OtE7N3Ps/7aldBYuqHf1dte1L/nk0GpdbNiNj9VsInEzqcbLZ5+M5fUxDjXj2uMKagPIe0SmhtL/pgFWa70qbUoSRAPvBqR3wC7Dn7Ft6Ab3qCf9qOYwx5e6fDbOY=

### Visual documentation

please see video to reproduce:
https://drive.google.com/file/d/1lY3o9tRpp54PxDxCpFTbPBBA6zTetVhV/view?usp=sharing

1. Create a custom function that takes a string list and returns an enum list. You can leave the function empty and return an empty enum list.
Create a widget that calls it

### Environment

```markdown
- FlutterFlow version: v4.183+ (synced)
- Platform: Web
- Browser name and version: Version 127.0.6533.89 (Official Build) (arm64)
- Operating system and version affected: MacOS Sonoma 14.5 (23F79)
```

### Additional Information

I intend to launch this app in the upcoming days, and now the project is stuck because I cannot test it properly. This is the most crucial time of my startup, so it is very urgent for me to resolve this. If I don't, I'll just copy the code to a local environment, and will, unfortunately, have to continue this project without FF (which was very convenient until now)

**Comment by Alezanello** [comment] 2024-08-29 17:15
Closed duplicate of topic: [https://github.com/FlutterFlow/flutterflow-issues/issues/3688](https://github.com/FlutterFlow/flutterflow-issues/issues/3688)

**Closed as not planned** 2024-08-29 17:14 UTC
Labels: status: needs triage
