### ISSUE TITLE
Lottie animations not rendering properly

### ISSUE THREAD

**Issue by damianfraire** [FlutterFlow/flutterflow-issues#2934] opened 2024-05-18 17:26 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Lottie animations downloaded from lottiefiles are not rendering properly in the lottieAnimation widget. 

### Expected Behavior

Lottie animations should render properly.

### Steps to Reproduce

1. Create an empty project
2. Add a lottieAnimation widget
3. Download a lottie animation from lottie files (i.e. https://lottie.host/168bb4ea-3344-43a0-904f-f058fbb23b4a/JnQjlSNG9m.json) 
4. Upload as asset or add the link to the widget

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kjc+A5ZVNxd8B15CMbccxgj0vJnp7TL0Vr+0ac0gYGIzcPLMqe/TOVFJuOLC0Twl2f1mjknkyp9HemvHUU/c6aCiWfYh+wodcSQLNUTqXVJSkCKWaTm5/DehWGHKX18OG3BBBOu9ucloh1Ey6Cu+XVibcNIyxNWs7Jf6HLZKK2SrDX1iXc2URm05KZDPz

### Context

Lottie animations has worked before but recently new downloaded files from lottiefiles are not rendering properly. Although if I used a previously saved (+1 month ago) animation, it does render properly.

### Visual documentation

Here is the lottie animation how it's supposed to show (played in any online player)
![lottieAnimationAnyOnlinePlayer](https://github.com/FlutterFlow/flutterflow-issues/assets/70819362/2ac3bc35-160f-45c6-9dd9-3cd4c44e3a4a)

Here is how it looks like in flutterflow when rendered in LottieAnimation widget
![lottieAnimationFlutterFlow](https://github.com/FlutterFlow/flutterflow-issues/assets/70819362/1f4638d0-3aa9-451d-ab45-cf37852d4a29)

### Additional Info

I have deployed this app on my phone with local run and it doesn't render properly there either. 

### Environment

```markdown
- FlutterFlow version: 4.1.53
- Platform: Android
- Browser name and version: Chrome 124.0.6367.208
- Operating system and version affected: Windows 11
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by msusviela** [comment] 2024-05-21 00:13
I was able to reproduce the issue, I will send it to the ENG team so they can work on this!

**Comment by msusviela** [comment] 2024-05-22 17:09
Hi @damianfraire. We tried to reproduce the bug it from our side and we were only able to replicate it with that particular animation. We're suspecting this is a project-specific issue.

**Comment by damianfraire** [comment] 2024-05-22 18:12
Thanks for the response @msusviela. I'm still getting the same issue in a brand new project but I just found out that if I download the json file using Google Chrome, the animation has rendering issues, but if I do it using Microsoft Edge, then it reproduces properly. Not sure if the browser is adding/removing formatting issues that is widget can't support? My specific issue is solved that I have a workaround, but may be worth to take a look. 

Also, @leighajarett I would recommend not closing the issues without giving the customer an opportunity to provide some insights, it takes time and effort from customers to step onto these issues, troubleshoot and rule out is not them, browse the issue list to validate if it has been reported and finally fill out all the fields in this form and screenshots to report it. This whole process can take days and closing this issue unilaterally after 30 minutes will probably not help to increase quality in the platform that customers are freely trying to help with.

**Comment by leighajarett** [comment] 2024-06-10 21:12
Hi there! Sorry about that. That's a great point - I appreciate you taking the time to file this issue. 

Even if an issue is closed, we try to respond to further comments and reopen as necessary~

We think this is a problem with the underlying flutter Lottie package. I noticed another user with a similar issue. Both can be recreated with using a widget directly in Flutter. I filed an issue on the package so hopefully they're able to resolve it https://github.com/xvrh/lottie-flutter/issues/359

I'm going to close this issue for now since there doesnt seem like any action we can take on our side. However, I will reopen if new information emerges!

**Comment by BenEppers** [comment] 2024-07-24 08:39
here is the solution: 

https://youtu.be/66uWvDuOUcs?si=pE-YJ3kfBE8OGKze

**Comment by leighajarett** [comment] 2024-07-24 18:46
Thanks for posting this! You should add to our community forum as well!

**Comment by BenEppers** [comment] 2024-07-24 18:50
Sure! I am new to github, can you show me where?

**Comment by leighajarett** [comment] 2024-07-25 11:21
[https://community.flutterflow.io/](https://community.flutterflow.io/) 🙂

**Comment by isegal** [comment] 2024-07-25 21:43
After a recent update of either flutter or pubspec.yaml, our iOS app is crashing on many devices due to lottie.

I've managed to catch the crash backtrace, but I am not sure how much FlutterFlow lends itself to easy rollbacks of flutter version.

```
#0	(null) in 0x101620000 ()
#1	(null) in NativeCanvas._restore$Method$FfiNative ()
#2	0x000000010a342a88 in _NativeCanvas.restore ()
#3	0x000000010a342a88 in BaseLayer.draw ()
#4	0x000000010a35a1d4 in CompositionLayer.drawLayer ()
#5	0x000000010a3425c0 in BaseLayer.draw ()
#6	0x000000010972ad90 in LottieDrawable.draw ()
#7	0x000000010972aa64 in RenderLottie.paint ()
#8	0x00000001096f9088 in RenderObject._paintWithContext ()
#9	0x00000001096f8fd4 in PaintingContext.paintChild ()
#10	0x00000001097174a8 in RenderProxyBoxMixin.paint (#2) ()
#11	0x00000001096f9088 in RenderObject._paintWithContext ()
#12	0x00000001096f96e4 in PaintingContext._repaintCompositedChild ()
#13	0x00000001098e4368 in PaintingContext.repaintCompositedChild ()
#14	0x00000001098e4368 in PipelineOwner.flushPaint ()
#15	0x00000001098e4460 in PipelineOwner.flushPaint ()
#16	0x00000001098dc810 in RendererBinding.drawFrame ()
#17	0x00000001098dc320 in WidgetsBinding.drawFrame ()
#18	0x00000001098dbce4 in RendererBinding._handlePersistentFrameCallback (#2) ()
#19	0x00000001098dbca8 in RendererBinding._handlePersistentFrameCallback ()
#20	0x00000001096046c4 in SchedulerBinding._invokeFrameCallback ()
#21	0x0000000109604468 in SchedulerBinding.handleDrawFrame ()
#22	0x000000010960430c in SchedulerBinding._handleDrawFrame (#2) ()
#23	0x00000001096041e4 in SchedulerBinding._handleDrawFrame ()
#24	0x00000001095d3c34 in invoke ()
#25	0x00000001095d6928 in PlatformDispatcher._drawFrame ()
#26	0x00000001095d68ec in drawFrame ()
#27	0x00000001095d6958 in drawFrame (#2) ()
#28	(null) in stub InvokeDartCode ()
```

**Comment by leighajarett** [comment] 2024-07-26 20:31
Thanks for reporting this - we are looking into it!

**Comment by leighajarett** [comment] 2024-07-26 20:54
@wenkai can you take a look at this?

**Comment by wenkaifan0720** [comment] 2024-07-27 00:00
Hi @isegal. Could you provide a bug report code? Thanks!

Nevermind. I see your bug report code in the other issue.

**Comment by wenkaifan0720** [comment] 2024-07-29 15:29
Closing this as the crashing issue is reported in https://github.com/FlutterFlow/flutterflow-issues/issues/3483.

**Closed by wenkaifan0720** 2024-07-29 15:29 UTC
Labels: status : project specific, needs technical triage, Bug, Unknown Issue
