### ISSUE TITLE
Can't paste or duplicate child widget from a parent widget that is not visible

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#1046] opened 2023-06-25 12:50 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I can't duplicate or paste widget when the parent widget is not show in the UI Builder

### Expected Behavior

I want to continue editing regardless of whether it is displayed in the UI Builder

### Steps to Reproduce

1. Create a column
2. Add some widgets
3. Now the column created previously set conditional visibility as false
4. And turn of the "Show in the UI Builder" option
5. Now you can't paste or duplicate child widgets from that column

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sz8mAsIxIseFH+KryKPl7/T0RH0A4apIoscsZbw4bB4zqPLJ+OvfRNlpvZ+bjSkNhHFL/klgEwfzLidnpD/U3ITqeGoB6/89+ajnJQXq8Ra7SO4eVdXxtEeBQJmqs36TUvglAGNRuZUYZ1F2tNuqRfCnACZu/Zwh9f6PHaOI=

### Context

I want to continue editing regardless of whether it is displayed in the UI Builder. I don't know if this is a bug or a feature request but it is frustrating mainly when using the new Conditional Builder.

### Visual documentation

https://schoolfy365.tinytake.com/msc/ODM3MzI0MF8yMTY0OTA1NQ

### Environment

```markdown
- FlutterFlow version: FlutterFlow v3.1 released June 25, 2023
- Platform: Web
- Browser name and version: Chrome 114.0.5735.134 (Official Build) (64-bit)
- Operating system and version affected: Windows 11
```

**Comment by wenkaifan0720** [comment] 2023-06-29 15:43
Hi @Franco98404. This is the intended behavior, same for conditional builders and the conditional visibility property for all widgets. The reason for this behavior is because if the widget is not visible in the builder, we can't detect whether it would trigger a layout crash. And you would not be able to see the UI update for those invisible widgets, which kind of defeats the purpose of a visual app builder. 

Because of these reasons, I would close this issue for now. Thank you.

**Closed by wenkaifan0720** 2023-06-29 15:43 UTC
Labels: closed: not a bug, status: not a bug
