### ISSUE TITLE
Unknown error compiling custom code. A common cause is a custom widget or action whose name in the code does not match the name provided in the editor.

### ISSUE THREAD

**Issue by MyTaxAssist** [FlutterFlow/flutterflow-issues#3399] opened 2024-07-15 06:31 UTC
### Can we access your project?

- [x] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Unable to compile Custom Widget. I am getting the following error even in blank project
Unknown error compiling custom code. A common cause is a custom widget or action whose name in the code does not match the name provided in the editor.

### Expected Behavior

It should compile

### Steps to Reproduce

Create Custom Widget
Give a name: SessionTimer
Copy the below code
`// Automatic FlutterFlow imports
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/custom_code/widgets/index.dart'; // Imports other custom widgets
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
// Begin custom widget code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

// Set your widget name, define your parameter, and then add the
// boilerplate code using the green button on the right!

import 'dart:async';

class SessionTimer extends StatefulWidget {
  const SessionTimer({
    Key? key,
    required this.width,
    required this.height,
    this.timeoutDuration = 60,
    this.minTimeoutDuration = 60,
  }) : super(key: key);

  final double width;
  final double height;
  final int timeoutDuration;
  final int minTimeoutDuration;

  @override
  _SessionTimerState createState() => _SessionTimerState();
}

class _SessionTimerState extends State<SessionTimer> {
  Timer? _timer;

  void _handleInactivity() {
    Navigator.pushReplacementNamed(context, "/");
  }

  void _initializeTimer() {
    if (_timer != null) {
      _timer!.cancel();
    }
    // Setup action after "timeoutDuration"
    _timer = Timer(
      Duration(
        seconds: widget.timeoutDuration < widget.minTimeoutDuration
            ? widget.minTimeoutDuration
            : widget.timeoutDuration,
      ),
      () => _handleInactivity(),
    );
  }

  void _handleUserInteraction([dynamic _]) {
    _initializeTimer();
    print(_);
    print("Detected! Reset timer ...\n");
  }

  @override
  void initState() {
    super.initState();
    _initializeTimer();
  }

  @override
  void dispose() {
    if (_timer != null) {
      _timer!.cancel();
    }
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      behavior: HitTestBehavior.translucent,
      onTap: () => _handleUserInteraction("onTap"),
      onPanDown: _handleUserInteraction,
      child: Container(
        width: widget.width,
        height: widget.height,
        color: Colors.transparent, // Ensure the container is transparent
      ),
    );
  }
}`
click on compile
we get error 
**Unknown error compiling custom code. A common cause is a custom widget or action whose name in the code does not match the name provided in the editor.**

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEez/Lq7othpbwC7pfcau1ohQMwGkQ5a7sviu5+FBQaI+OrPbMUds7CXxBCSOqHeVdAP1CkgkMK08qKheOXUMFcOkmbGqpJz6pbUxDhZFuWR5CMOrWKWnFSQMJTfRXA5LTQkyNSC/tsS1YZwFOILti+b3qCf9qOYwx5e6fDbOY=

### Visual documentation

![image](https://github.com/user-attachments/assets/324137cf-6ba7-4704-a5db-5e9453d6f27f)

![image](https://github.com/user-attachments/assets/fe02c880-a288-4903-8265-02665f99d07b)

### Environment

```markdown
- FlutterFlow version: 4.1.72
- Platform: Web
- Browser name and version: hrome is up to date
Version 126.0.6478.127 (Official Build) (64-bit)
- Operating system and version affected: Windows 10
```

### Additional Information

We have production system https://mytaxassist.in published using flutterflow. We are unable to implement session timeout for web users. We have 400 Active users accessing this Application and we have Government mandated due date that we complete filing the tax returns by July 31.  This is very critical Application for our company as we have 15 days left. This has to be resolved in Next 48 hours

**Comment by MyTaxAssist** [comment] 2024-07-15 06:36
Screen shot with no errors in the code. but still not compiling 
![image](https://github.com/user-attachments/assets/878ff57f-1540-47a6-8dbd-c2df9439c692)

Code for reference 
`// Automatic FlutterFlow imports
import '/backend/backend.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/custom_code/widgets/index.dart'; // Imports other custom widgets
import '/custom_code/actions/index.dart'; // Imports custom actions
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
// Begin custom widget code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

// Set your widget name, define your parameter, and then add the
// boilerplate code using the green button on the right!

import 'dart:async';

class SessionTimer extends StatefulWidget {
  const SessionTimer({
    Key? key,
    required this.width,
    required this.height,
    this.timeoutDuration = 60,
    this.minTimeoutDuration = 60,
  }) : super(key: key);

  final double width;
  final double height;
  final int timeoutDuration;
  final int minTimeoutDuration;

  @override
  _SessionTimerState createState() => _SessionTimerState();
}

class _SessionTimerState extends State<SessionTimer> {
  Timer? _timer;

  void _handleInactivity() {
    Navigator.pushReplacementNamed(context, "/");
  }

  void _initializeTimer() {
    if (_timer != null) {
      _timer!.cancel();
    }
    // Setup action after "timeoutDuration"
    _timer = Timer(
      Duration(
        seconds: widget.timeoutDuration < widget.minTimeoutDuration
            ? widget.minTimeoutDuration
            : widget.timeoutDuration,
      ),
      () => _handleInactivity(),
    );
  }

  void _handleUserInteraction([dynamic _]) {
    _initializeTimer();
    print(_);
    print("Detected! Reset timer ...\n");
  }

  @override
  void initState() {
    super.initState();
    _initializeTimer();
  }

  @override
  void dispose() {
    if (_timer != null) {
      _timer!.cancel();
    }
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      behavior: HitTestBehavior.translucent,
      onTap: () => _handleUserInteraction("onTap"),
      onPanDown: _handleUserInteraction,
      child: Container(
        width: widget.width,
        height: widget.height,
        color: Colors.transparent, // Ensure the container is transparent
      ),
    );
  }
}`

**Comment by msusviela** [comment] 2024-07-15 12:21
Hi. I copied your code and it's throwing some errors:

1. First of all, it's not recognizing the type when you set the state.<br>You should have class \_SessionTimerState extends State<SessionTimer>  instead of class \_SessionTimerState extends State.
2. You have an empty print statement, This is also throwing an error.
3. Then in the method \_handleUserInteraction, you're calling to initializeTimer method. I think you got a typo there and it should be \_initializeTimer.<br><br>I'm closing this issue since it's not a bug. If you have further questions regarding project-specific issues, our support team is our best chance to get it solved. You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow.

**Closed as not planned** 2024-07-15 12:22 UTC
Labels: status: needs triage, status: not a bug

**Comment by MyTaxAssist** [comment] 2024-07-16 10:55
I have done the changes you suggested but still getting the same error. 

`// Automatic FlutterFlow imports
import '/backend/backend.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/custom_code/widgets/index.dart'; // Imports other custom widgets
import '/custom_code/actions/index.dart'; // Imports custom actions
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
// Begin custom widget code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

// Automatic FlutterFlow importsUnknown error compiling custom code. A common cause is a custom widget or action whose name in the code does not match the name provided in the editor.

// Set your widget name, define your parameter, and then add the
// boilerplate code using the green button on the right!

import 'dart:async';

class SessionTimerState extends StatefulWidget {
  const SessionTimerState({
    Key? key,
    required this.width,
    required this.height,
    required this.timeoutDuration,
    required this.minTimeoutDuration,
  }) : super(key: key);
  final double width;
  final double height;
  final int timeoutDuration;
  final int minTimeoutDuration;

  @override
  _SessionTimerState createState() => _SessionTimerState();
}

class _SessionTimerState extends State<SessionTimerState> {
  late Timer _timer;

  @override
  void initState() {
    super.initState();
    _initializeTimer;
  }

  @override
  void dispose() {
    _timer.cancel();
    super.dispose();
  }

  void _handleInactivity() {
    Navigator.pushReplacementNamed(context, "/");
  }

  void _initializeTimer() {
    _timer.cancel();
    // setup action after "timeoutDuration"
    _timer = Timer(
        Duration(
            seconds: widget.timeoutDuration < widget.minTimeoutDuration
                ? widget.minTimeoutDuration
                : widget.timeoutDuration),
        () => _handleInactivity());
  }

  void _handleUserInteraction([_]) {
    _initializeTimer;
    print("Detected! Reset timer ...\n");
  }

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
        behavior: HitTestBehavior.translucent,
        onTap: () => _handleUserInteraction("onTap"),
        onPanDown: _handleUserInteraction,
        child: Container(
          width: widget.width,
          height: widget.height,
          color: Colors.transparent,
        ));
  }
}`


**Unknown error compiling custom code. A common cause is a custom widget or action whose name in the code does not match the name provided in the editor.**

**Comment by MyTaxAssist** [comment] 2024-07-16 10:58
When I tried your first suggestion
You should have class _SessionTimerState extends State instead of class _SessionTimerState extends State
I am getting this error when trying to save the widget

![image](https://github.com/user-attachments/assets/50aed253-366b-40fc-94f0-60ecb047c3f3)

However this one saves  **class SessionTimerState extends StatefulWidget {**

**Comment by msusviela** [comment] 2024-07-16 13:46
Sorry, my bad. I realized that my first suggestion was missing something. It must be class \_SessionTimerState extends State<SessionTimerState>. (You have to indicate which state you're extending). <br><br>Also, please correct the handleUserInteraction to look like this (it's throwing an error because of the parameter, and then I needed to add the \_ so it's recognized in the build method)<br>void \_handleUserInteraction(\[dynamic event\])   <br><br>A code like this should compile: 

```

class SessionTimerState extends StatefulWidget {
  const SessionTimerState({
    Key? key,
    required this.width,
    required this.height,
    required this.timeoutDuration,
    required this.minTimeoutDuration,
  }) : super(key: key);
  final double width;
  final double height;
  final int timeoutDuration;
  final int minTimeoutDuration;

@override
  _SessionTimerState createState() => _SessionTimerState();
}

class _SessionTimerState extends State<SessionTimerState> {
  late Timer _timer;

@override
  void initState() {
    super.initState();
    _initializeTimer;
  }

@override
  void dispose() {
    _timer.cancel();
    super.dispose();
  }

void _handleInactivity() {
    Navigator.pushReplacementNamed(context, "/");
  }

void _initializeTimer() {
    _timer.cancel();
    // setup action after "timeoutDuration"
    _timer = Timer(
        Duration(
            seconds: widget.timeoutDuration < widget.minTimeoutDuration
                ? widget.minTimeoutDuration
                : widget.timeoutDuration),
        () => _handleInactivity());
  }

void _handleUserInteraction([dynamic event]) {
    _initializeTimer;
    print("Detected! Reset timer ...\n");
  }

@override
  Widget build(BuildContext context) {
    return GestureDetector(
        behavior: HitTestBehavior.translucent,
        onTap: () => _handleUserInteraction("onTap"),
        onPanDown: _handleUserInteraction,
        child: Container(
          width: widget.width,
          height: widget.height,
          color: Colors.transparent,
        ));
  }
}
```

**Comment by MyTaxAssist** [comment] 2024-07-16 15:08
Thank you for the quick response the code compiled now. One quick question why is the Custom Code in FlutterFlow not showing these errors and showing it as **Unknown error compiling custom code. A common cause is a custom widget or action whose name in the code does not match the name provided in the editor.**. The editor should show the errors in detail. 

OR can you please suggest any other tool to check these custom code errors .

TIA.

**Comment by MyTaxAssist** [comment] 2024-07-16 15:32
Thank you for the quick reply. For the above code also I am getting the same error

**`Unknown error compiling custom code. A common cause is a custom widget or action whose name in the code does not match the name provided in the editor. `**

**Comment by msusviela** [comment] 2024-07-16 15:36
I'm not able to reproduce this from blank, can you please reach out to [support@flutterflow.io](mailto:support@flutterflow.io)? They can better assist you with ensuring your project is configured correctly

**Comment by MyTaxAssist** [comment] 2024-07-16 15:47
![image](https://github.com/user-attachments/assets/3b24f719-b55d-40ad-95e0-ea04eef58356)


 I  am getting the same error even in fresh project. pls help me to check if any mistake in the code. I am new to Flutterflow. TIA

'// Automatic FlutterFlow imports
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/custom_code/widgets/index.dart'; // Imports other custom widgets
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
// Begin custom widget code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

// Set your widget name, define your parameter, and then add the

// boilerplate code using the green button on the right!

import 'dart:async';

class SessionTimerState extends StatefulWidget {
  const SessionTimerState({
    Key? key,
    required this.width,
    required this.height,
    required this.timeoutDuration,
    required this.minTimeoutDuration,
  }) : super(key: key);
  final double width;
  final double height;
  final int timeoutDuration;
  final int minTimeoutDuration;

  @override
  _SessionTimerState createState() => _SessionTimerState();
}

class _SessionTimerState extends State<SessionTimerState> {
  late Timer _timer;

  @override
  void initState() {
    super.initState();
    _initializeTimer;
  }

  @override
  void dispose() {
    _timer.cancel();
    super.dispose();
  }

  void _handleInactivity() {
    Navigator.pushReplacementNamed(context, "/");
  }

  void _initializeTimer() {
    _timer.cancel();
    // setup action after "timeoutDuration"
    _timer = Timer(
        Duration(
            seconds: widget.timeoutDuration < widget.minTimeoutDuration
                ? widget.minTimeoutDuration
                : widget.timeoutDuration),
        () => _handleInactivity());
  }

  void _handleUserInteraction([dynamic event]) {
    _initializeTimer;
    print("Detected! Reset timer ...\n");
  }

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
        behavior: HitTestBehavior.translucent,
        onTap: () => _handleUserInteraction("onTap"),
        onPanDown: _handleUserInteraction,
        child: Container(
          width: widget.width,
          height: widget.height,
          color: Colors.transparent,
        ));
  }
}'

**Comment by msusviela** [comment] 2024-07-16 16:02
The issue is in this line:<br>class \_SessionTimerState extends State <br><br>You need it to be:<br>class \_SessionTimerState extends State<SessionTimerState>

**Comment by MyTaxAssist** [comment] 2024-07-16 17:27
![image](https://github.com/user-attachments/assets/f01825e8-960b-41ee-a100-4e124aaa48b8)

When I change the code as suggested by you, it is says 

**No widget "SessionTimerState" found.

Are you sure you want to save?**


Widget Name and class and cons name has to be same **SessionTimerState**. I cannot add **_SessionTimerState** in widget name

**Comment by msusviela** [comment] 2024-07-16 17:31
We're still unable to reproduce it from blank from out side, can you please reach out to [support@flutterflow.io](mailto:support@flutterflow.io)? They can better assist you with ensuring your project is configured correctly

**Comment by shivpratik** [comment] 2024-10-12 08:34
![Screenshot 2024-10-12 at 2 02 59 PM](https://github.com/user-attachments/assets/420dcd75-b72a-436e-ae79-bd34f0821b39)


Even I'm have the same issue. I'm just trying to save the boiler plate and I get the error.
