### ISSUE TITLE
Missing "Specific Value" option for conditional visibility

### ISSUE THREAD

**Issue by KirilOkun** [FlutterFlow/flutterflow-issues#86] opened 2022-11-02 13:42 UTC
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

When using JSON data for the first value of a single condition for conditional visibility both options "Specific Value"  and "Variable"  should be available.

## Current behavior (required)

Only "From Variable" option is available

## To Reproduce (required)

1.    Specify a JSON source for a page 
2.    Enable Conditional visibility for a widget
3.    Add a single condition
4.    For value 1 specify a JSON path 
5.    For value 2 try to set specific value
6.    Specific value option does not appear in the drop down.

## Context (required)

Impossible to use specific value comparison when using JSON data
![Dashboard-FlutterFlow](https://user-images.githubusercontent.com/1024870/199504923-098e8e71-d8c3-40c7-b8b9-4444754336e8.png)

## Your environment

* **Bug Report Code:**
* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by Pepino-GR** [comment] 2022-11-02 14:35
I can reproduce the issue.

**Comment by agreaves** [comment] 2022-11-02 21:07
Hi @KirilOkun, the trouble is that when you use a JSON path, it produces a JSON (dynamic) result, so we have no way of knowing whether this is a String, Integer, Map, etc. So in this case a Specific Value doesn't actually make sense because we have no idea what type it should be (should we treat it as a String, Double, etc?). We may down the line modify Specific Value to allow you to define type, but this is not something we're likely to do in the near future.

In the meantime, there are a few (less than ideal) workarounds:
1. Define a Local State variable with the default text that you want to match, and then use that
2. Define a Custom Function that returns the text you want to match.

Those are both less than ideal, but in the near future there will be two other workarounds as well:
3. Use **Combine Text**, with just a single text element equal to the one you want to set.
4. We're going to add the ability to define app wide constants that you can then use as a variable here.

Unfortunately these are all workarounds at the moment, but the latter two are much more convenient and will be enabled in the very near future. In the meantime, I'm closing this as a Feature Request which we can revisit later!

**Closed by agreaves** 2022-11-02 21:07 UTC
Labels: type: bug, status: confirmed

**Comment by KirilOkun** [comment] 2022-11-03 04:08
@agreaves    Makes sense.     #3 is prob the most flexible.

**Comment by bulgariamitko** [comment] 2022-11-08 15:16
> Hi @KirilOkun, the trouble is that when you use a JSON path, it produces a JSON (dynamic) result, so we have no way of knowing whether this is a String, Integer, Map, etc. So in this case a Specific Value doesn't actually make sense because we have no idea what type it should be (should we treat it as a String, Double, etc?). We may down the line modify Specific Value to allow you to define type, but this is not something we're likely to do in the near future.
> 
> In the meantime, there are a few (less than ideal) workarounds:
> 
> 1. Define a Local State variable with the default text that you want to match, and then use that
> 2. Define a Custom Function that returns the text you want to match.
> 
> Those are both less than ideal, but in the near future there will be two other workarounds as well: 3. Use **Combine Text**, with just a single text element equal to the one you want to set. 4. We're going to add the ability to define app wide constants that you can then use as a variable here.
> 
> Unfortunately these are all workarounds at the moment, but the latter two are much more convenient and will be enabled in the very near future. In the meantime, I'm closing this as a Feature Request which we can revisit later!

I totally understand and get the point and get how this can be done without any custom code, but I think this should be written in the documentary and in i icon as well so people know why this option is not there and this is not a bug/issue. This is my advice.
