### ISSUE TITLE
Upload media to local file with multiple images doesn't work

### ISSUE THREAD

**Issue by guillemgotes** [FlutterFlow/flutterflow-issues#590] opened 2023-03-09 15:23 UTC
### Has your issue been reported?

- [x] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I try to upload multiple images via local file (not firebase), just one image is sent through the API.

### Expected Behavior

The entire list of images uploaded shoult be sent through the API.

### Steps To Reproduce

A) Create an API
1. Create an API call give it a name and an API url. Select type: "POST".
2. Create a variable named "images". Select type: "uploaded file". Is list: "true".
3. In the body of the API call choose "multipart". Create a parameter named images. Select value source from variable. Select the variable created in step 2.
4. Save the API call.

B)Create the frontend
1. Create a new page
2. Create container
3. Set action on container: "upload media to local file". Just allow photos (no video). Set media to Gallery. Toggle multiple images ON.
4. Add another action following the first one: "backend call API". Select the API call created in "Step A". Add a variable. Select "images" (created in step A-2). Value source: "from variable". Choose the variable "uploaded local files" (under widget state). No further changes, Confirm. Close.

c) Reproduce error
1. Run the project.
2. Click the container
3. Click gallery, choose some pictures and upload them.
7. You will receive just one image through the API call instead of an array of images.

### Bug Report Code

ITFfl8n635F1ofVG1oSJL8ZsvCUXJW0cTL4zlO1HcxAYGO/yPbJ/Z+PsXFNvTum8YGlhHGaiml810srNj97yGscqMkiZc4h6zpBAZDvwY3q8RZTWPLuOZWtPN+ZhIUCs4Lu7uxJBB7doV3wk2jv3Oe6RdDbfCZ+/Zwh9f6PHaOI=

### Context

I want to save some images in my external backend (XANO) and I can't get them all at once.

### Environment

```markdown
- FlutterFlow version: 
- Platform: web
- Browser name and version: chrome
- Operating system and version affected:
```

**Comment by organicnz** [comment] 2023-03-15 13:17
Hi, @guillemgotes. Thanks, for adding this issue 🙂

Could you please share which API provider you are using? I couldn't upload an image or images via upload.io for some reason :)

**Comment by guillemgotes** [comment] 2023-03-21 10:16
Hi @organicnz , I use Xano.

**Comment by guillemgotes** [comment] 2023-03-29 07:27
Hi, any updates? @organicnz

**Comment by shelpert** [comment] 2023-04-13 00:20
Hello,

Can you confirm that you are still experiencing this issue? It looks like we had a bug fix addressing this issue a month ago but sometimes it takes a while to get through the pipeline, so just wondering if you've tried again lately!

**Comment by guillemgotes** [comment] 2023-04-13 06:49
Hello,

Yes, I just checked it and it still happens. You choose many pictures to upload but just one is sent through the API.

Around a month ago you solved the loading of a single picture. In fact I would say it's since that moment that it appeared this other issue.

**Comment by shelpert** [comment] 2023-04-14 22:01
Hello,

I would like to test your project to investigate this issue, but am unable to login with your current auth set up. If you could do one of these things, I can investigate further: fix your current set up so that I can use a +1 number, temporarily add email authentication, or, ideally, set up a simple project with just the page containing the issue and link it here. Thanks!

**Comment by guillemgotes** [comment] 2023-04-17 08:16
Hi @shelpert , as you would have to set up many things for the account, I directly created a user for you with all the information needed. If you give me a way to contact you, I will send you the phone number and the verification code so you have direct access.

**Comment by shelpert** [comment] 2023-04-17 17:59
Hi, 

The best way to give me that info is to make a blank Flutterflow project with the info on a page, then add the bug report code here so that I can access the project!

**Comment by guillemgotes** [comment] 2023-04-17 18:18
Hi shelpert,

Here it goes!

ITFfhcr134xPsdtJ0L6JcMcwpGYWQmUcTeUzlO1hdwwbI+OvB7M2ZMjRM1BCWOqHeAtYe1GLvzoD/tL7jvLxG/E4BE6sY4RTzqlxUxDgfD+XRKqLEaWaQUZ7EfFnBX6k0KeK3BRdBPJvLyEi3WCQPuyAb3qCf9qOYwx5e6fDbOY=

**Comment by shelpert** [comment] 2023-04-20 18:13
Hi @guillemgotes,

I've confirmed that the API request is sending multiple images to the server. Please check that your endpoint accepts multiple images in one request. It seems from the response that only one image is accepted at a time, since I can get multiple images to be returned in the response only when I make multiple requests. I'm closing this issue since it does not seem to be a bug on the Flutterflow end.

**Closed by shelpert** 2023-04-20 18:13 UTC
Labels: status: needs triage
