### ISSUE TITLE
Razorpay payments were working before, but are no longer working. No Payment ID also being generated.

### ISSUE THREAD

**Issue by duuetdev** [FlutterFlow/flutterflow-issues#4877] opened 2024-11-13 09:59 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I first integrated the Razorpay API and tested it by making a couple of payments and it was working well with all the different types of payments method. But now suddenly without making any change, the Razorpay integration isn't working. The transaction is getting failed before the payment ID is generated also. This is happening in both iOS and android apps.

### Expected Behavior

The payment should complete successfully with the payment ID being captured and stored correctly as it was before.

### Steps to Reproduce

1. Follow all the steps to the Razorpay Integration from the official documentation.
2. In testing the Razorpay payments, see that the payment is getting failed each time in all types of payment types. 
3. Notice that the payment is getting failed before the transaction id/payment id is generated.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEelM/q35NItbxb+bnQKMFGiQMxQUB+bZ0vlO1FGBE0IZivEIkAZc7EaXdYZO2RfHxiMFC0rFEEwtbWiOL1UMEDGxWYb6V607VQaTvwJXKuRrqPCc60XmtCGehhBWq5yKSs2h4kLrdsc14d20+Lcq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

https://github.com/user-attachments/assets/55d750fa-ccfe-4c51-a654-431469534aef

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.8+ 
- Platform: Web/MacOS
- Browser name and version: Safari (latest)
- Operating system and version affected: MacOS Sequoia 15.1
```

### Additional Information

Please help us resolve this issue fast! We're unable to accept payments until it's sorted. The production apps are affected.

**Comment by duuetdev** [comment] 2024-11-14 05:32
This is a high priority issue for us since we're not able to accept orders through our app, please check as soon as possible.

**Comment by leighajarett** [comment] 2024-11-14 13:30
Thanks for filing this, we are working on it!

**Comment by sbis04** [comment] 2024-11-14 17:24
@duuetdev does it also fail if you try using the Razorpay test credentials?

**Comment by sbis04** [comment] 2024-12-15 05:47
Closing since we were not able to reproduce this issue on our side.

**Closed as completed by sbis04** 2024-12-15 05:47 UTC
Labels: status: confirmed, closed: not a bug, Bug
