### ISSUE TITLE
Scan Barcode/QR code not working

### ISSUE THREAD

**Issue by daviesgeek** [FlutterFlow/flutterflow-issues#2764] opened 2024-04-19 00:52 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am trying to add a barcode scanner to a very simple app but i can't load it, it ends up throwing this error:

> Error: MissingPluginException(No implementation found for method scanBarcode on channel flutter_barcode_scanner)
> at Object.throw\_ \[as throw\] (dart_sdk.js:11914:11)

Was following the docs here: [https://docs.flutterflow.io/actions/actions/widget-ui-interactions/scan-barcode-qr-code](https://docs.flutterflow.io/actions/actions/widget-ui-interactions/scan-barcode-qr-code)

### Expected Behavior

Expect that the barcode scanner would show up

### Steps to Reproduce

Following the docs here: [https://docs.flutterflow.io/actions/actions/widget-ui-interactions/scan-barcode-qr-code](https://docs.flutterflow.io/actions/actions/widget-ui-interactions/scan-barcode-qr-code)

1. Create new project
2. Add button
3. Add tap action of "Scan Barcode/QR code"
4. Run test session
5. Click on button
6. Note that the scanner doesn't show up and the aforementioned error shows in the console

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4CksmAsJRgoeFF0JDubMdF9SkQIjo2RY0/k+xhcwgaDZPMC+wIZ/f7XFRuTde0YWNAfGaGoGU1w8HemvzLIMBdHz+dQIBy1boNVzziWkimVLbSCKqWfm5/AppmIEyi5J2z2glQG7FsWkY/2juEf+7LQgvtJZC2OkUjJOakD5OK2SrDX1iXc2URm05KZDPz

### Context

All I want to do is create a simple barcode scanner app and I'm unable to do so.

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/40d1bae7-0db4-4343-ad58-45c90f3bc01e/2aba9d9f-b52f-4be7-a22c-f9750ff25f6a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80MGQxYmFlNy0wZGI0LTQzNDMtYWQ1OC00NWM5MGYzYmMwMWUvMmFiYTlkOWYtYjUyZi00YmU3LWEyMmMtZjk3NTBmZjI1ZjZhIiwiaWF0IjoxNzEzNDg4MjIzLCJleHAiOjMzMjg0MDQ4MjIzfQ.fhAFZOe6a_ckjlrNTBA4QHU_k8MtBjWi5eXxvWclzR0)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.34+ released April 16, 2024. Flutter version is 3.19.1
- Platform: Web
- Browser name and version: Brave 1.65.114 (Chromium 124.0.6367.60), also tried Chrome 124.0.6367.60
- Operating system and version affected: macOS Sonoma 14.4
```

**Comment by paulperez-dev** [comment] 2024-04-19 15:49
Hi @daviesgeek! Thanks for your report! The package we use for barcode/QR code scanning only supports native platforms, so it is expected to see that message on the web. Please test on a real smartphone.

I'm closing this issue since this is an expected behavior.

**Closed by paulperez-dev** 2024-04-19 15:49 UTC
Labels: status: needs triage
