### ISSUE TITLE
Scrollbar does not appear on iPad

### ISSUE THREAD

**Issue by caioamoedo** [FlutterFlow/flutterflow-issues#1813] opened 2023-11-09 21:06 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

All of my app's scrollbars appear normally in the test version of Flutterflow, but they do not appear on the iPad after deploying to TestFlight.

I already made sure to enable the option to always show scrollbars in the Flutterflow settings panel. But still, they only appear in the Test Mode and the Web version, not on the iPad app.

### Expected Behavior

Scrollbars appear on the iPad, the same way they appear on the Test Mode and on the web version.

### Steps to Reproduce

1. Create an app with scrollbars.
2. Deploy it to App Store
3. Notice that the scrollbars do not appear

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gj8r634pItbwE7aqNb+9ahj8vNlw/bZc0st4bGAsdGOvrBu0idvfeVE9oXfWmaVNcJlKZvEcdwM7rjs7pL8c4AxGBfoBTyJBqQzzOe2ihaLKpC86Kf3YnAZ5WG2KA4bus3CYlNrN2clpk22eUCe6XH3fDFOu/Zwh9f6PHaOI=

### Context

IT4gj8r634pItbwE7aqNb+9ahj8vNlw/bZc0st4bGAsdGOvrBu0idvfeVE9oXfWmaVNcJmaYoGQE/9bruNnPJPYDFEybRaI4zboJVwr0e2ihaLKpC86Kf3YnAZ5WG2KA4bus3CYlNrN2clpk22eUCe6XH3fDFOu/Zwh9f6PHaOI=

### Visual documentation

![untitled](https://github.com/FlutterFlow/flutterflow-issues/assets/114263710/86265c1d-d85f-4016-9914-55c00b155240)
![Sem título](https://github.com/FlutterFlow/flutterflow-issues/assets/114263710/d4ba2591-fc18-43db-9351-98cdd36848ca)

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: Chrome 118.0.5993.120
- Browser name and version: 
- Operating system and version affected: iPadOS (20G75)
```

**Comment by sbis04** [comment] 2023-12-31 16:14
Hey @caioamoedo, currently we support the scrollbar theme only on platforms in which Flutter shows a scrollbar by default (web and desktop). So, it won't appear on mobile / tablet devices. I'm closing this since it's not a bug.

**Closed by sbis04** 2023-12-31 16:14 UTC
Labels: type: feature / enhancement request
