### ISSUE TITLE
Data types from Arrays defined in Supabase is not recognized

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#267] opened 2022-12-22 21:59 UTC
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

Data types from an Array defined in Supabase is not recognized on FlutterFlow

## Current behavior (required)

Is necessary set again in FlutterFlow

## To Reproduce (required)

1. Define as Array a column on Supabase and choose a data type
2. Get the Schema in FlutterFlow
3. Now you should see that is not recognized

### Bug Report Code

IT4ohfKA4YlOxPVd0a6IY+1omSQXOVg1R5IV0cpBZywgfZzzBLN/fPfQPltWOdfjSkFte2eMp14F09KKv4f9NPYCJS6uc75k1rlUUw7hVk6gMqnfU/HUACkbeacOQSj6

## Context (required)

I want to get the schema from supabase

## Screenshots / recordings

![image](https://user-images.githubusercontent.com/36147203/209231678-cabda13c-b066-4574-b04b-d6c8bb9b7565.png)
![image](https://user-images.githubusercontent.com/36147203/209231953-c0c9ac51-d929-4942-b9db-e67791183c5d.png)

## Your environment

* Version of FlutterFlow used: December 22 December
* Platform (e.g. Web, MacOS Desktop): Desktop
* Browser name and version: Version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (64-bit)
* Operating system and version (desktop or mobile): Windows 11 - 22H2 - Os build: 22621.963

**Comment by agreaves** [comment] 2022-12-22 22:40
Hi @Franco98404, unfortunately this is a limitation of the PostgREST API endpoint that tells us the table definitions. Because of this, we require users to set the Array types within the Supabase settings page. Sorry for the inconvenience!

Closing this for now as this is not a bug on the FlutterFlow side.

**Closed by agreaves** 2022-12-22 22:40 UTC
Labels: status: wontfix, closed: other

**Comment by Franco98404** [comment] 2022-12-23 21:59
Ok, thanks for the explanation, but when show the error it would be nice that go the specific table to set the Array types

![image](https://user-images.githubusercontent.com/36147203/209408946-76220c15-9756-43de-a172-6774fac53b91.png)
