### ISSUE TITLE
Build failed. Compilation error

### ISSUE THREAD

**Issue by emerson-almeida** [FlutterFlow/flutterflow-issues#3222] opened 2024-06-25 16:55 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

This error started to occur today. Until yesterday the system was working normally. Today I didn't make any changes.
in the constructor, there are no errors flagged. What could be happening?
the return of the compilation error is described in the field below.
My name is Emerson and my registered username is maj.almeida@hotmail.com. CapitalPIX project.
thanks

### Expected Behavior

que apenas o compilador funcionasse.

### Steps to Reproduce

não há passoa para reproduzir o erro, apenas o projeto não está sendo compilado... mesmo sem nenhum erro sinalizado no construtor
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/104561907/514f7fc9-8d07-4751-b74b-79c392ebe93b)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/104561907/34c2f4e0-cdb7-405e-964a-2cbb403aefc2)

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT88lfLqy49IsctD+Krqde9ajikvJjs/a+YwluxqEAg1F73qB4l3Z8/7VEpAXsThYGxteU22gVgBpqHKuPPhEsECBwSXGKY5/6liTjnzcHKzaq6OC5bhVXckEZlbfRXAy7er2SMmPs1fW14Sw0itLOiidDHAQ5DpCzJNDv2JEKLAp2/nABzdFyZE828URVOgCfUUTxGByM+UtpJh0eDnyw==

### Visual documentation

81 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Launching lib/main.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...      
/root/.pub-cache/hosted/pub.dev/app_links-3.4.1/lib/app_links.dart:11:38: Error: The method 'getInitialAppLink' isn't defined for the class 'AppLinksPlatform'.
 - 'AppLinksPlatform' is from 'package:app_links_platform_interface/app_links_platform_interface.dart' ('/root/.pub-cache/hosted/pub.dev/app_links_platform_interface-1.2.0/lib/app_links_platform_interface.dart').
Try correcting the name to the name of an existing method, or defining a method named 'getInitialAppLink'.
    return AppLinksPlatform.instance.getInitialAppLink();
                                     ^^^^^^^^^^^^^^^^^
/root/.pub-cache/hosted/pub.dev/app_links-3.4.1/lib/app_links.dart:16:38: Error: The method 'getInitialAppLinkString' isn't defined for the class 'AppLinksPlatform'.
 - 'AppLinksPlatform' is from 'package:app_links_platform_interface/app_links_platform_interface.dart' ('/root/.pub-cache/hosted/pub.dev/app_links_platform_interface-1.2.0/lib/app_links_platform_interface.dart').
Try correcting the name to the name of an existing method, or defining a method named 'getInitialAppLinkString'.
    return AppLinksPlatform.instance.getInitialAppLinkString();
                                     ^^^^^^^^^^^^^^^^^^^^^^^
/root/.pub-cache/hosted/pub.dev/app_links-3.4.1/lib/app_links.dart:21:38: Error: The method 'getLatestAppLink' isn't defined for the class 'AppLinksPlatform'.
 - 'AppLinksPlatform' is from 'package:app_links_platform_interface/app_links_platform_interface.dart' ('/root/.pub-cache/hosted/pub.dev/app_links_platform_interface-1.2.0/lib/app_links_platform_interface.dart').
Try correcting the name to the name of an existing method, or defining a method named 'getLatestAppLink'.
    return AppLinksPlatform.instance.getLatestAppLink();
                                     ^^^^^^^^^^^^^^^^
/root/.pub-cache/hosted/pub.dev/app_links-3.4.1/lib/app_links.dart:26:38: Error: The method 'getLatestAppLinkString' isn't defined for the class 'AppLinksPlatform'.
 - 'AppLinksPlatform' is from 'package:app_links_platform_interface/app_links_platform_interface.dart' ('/root/.pub-cache/hosted/pub.dev/app_links_platform_interface-1.2.0/lib/app_links_platform_interface.dart').
Try correcting the name to the name of an existing method, or defining a method named 'getLatestAppLinkString'.
    return AppLinksPlatform.instance.getLatestAppLinkString();
                                     ^^^^^^^^^^^^^^^^^^^^^^
/root/.pub-cache/hosted/pub.dev/app_links-3.4.1/lib/app_links.dart:41:38: Error: The getter 'allStringLinkStream' isn't defined for the class 'AppLinksPlatform'.
 - 'AppLinksPlatform' is from 'package:app_links_platform_interface/app_links_platform_interface.dart' ('/root/.pub-cache/hosted/pub.dev/app_links_platform_interface-1.2.0/lib/app_links_platform_interface.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'allStringLinkStream'.
    return AppLinksPlatform.instance.allStringLinkStream;
                                     ^^^^^^^^^^^^^^^^^^^
/root/.pub-cache/hosted/pub.dev/app_links-3.4.1/lib/app_links.dart:46:38: Error: The getter 'allUriLinkStream' isn't defined for the class 'AppLinksPlatform'.
 - 'AppLinksPlatform' is from 'package:app_links_platform_interface/app_links_platform_interface.dart' ('/root/.pub-cache/hosted/pub.dev/app_links_platform_interface-1.2.0/lib/app_links_platform_interface.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'allUriLinkStream'.
    return AppLinksPlatform.instance.allUriLinkStream;
                                     ^^^^^^^^^^^^^^^^
Waiting for connection from debug service on Web Server...         53.0s
Failed to compile application.

### Environment

```markdown
- FlutterFlow version: 4.1.61+
- Platform: Web
- Browser name and version: Chrome Versão 126.0.6478.127 (Compilação oficial) (64 bits)
- Operating system and version affected: Windows 11
```

**Comment by msusviela** [comment] 2024-06-25 16:56
Hi all. It seems to be related to a package upgrade on [pub.dev](http://pub.dev/). Our engineering team is already aware and working on a fix.

I'm closing this issue because It's a duplicate of: [https://github.com/FlutterFlow/flutterflow-issues/issues/3217](https://github.com/FlutterFlow/flutterflow-issues/issues/3217) I'll be following this from this issue.

Thanks for your reports!

**Closed as not planned** 2024-06-25 16:57 UTC
Labels: closed: duplicate
