### ISSUE TITLE
API Calls to launch URL Links do not work in Test Mode 

### ISSUE THREAD

**Issue by hughCar389** [FlutterFlow/flutterflow-issues#3276] opened 2024-06-28 17:54 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

As I try to text the api calls using Launch URL or my custom action that does the same thing it does not work. Even though both actions worked fine a few days ago.

### Expected Behavior

When the Provider/ Location Name is clicked, it launches the Link provided.

### Steps to Reproduce

Test Mode
Go to either Locations or Surgeons Page
Click the Location/Provider Name

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfkM/l7ZBgoctH176JKcJVvDgWH18cTYMvjuphcx40CIysOoYufM/RQ0NKTtSlf1Y/C1SkmlIF+fuNjeHPJPc4C0+CQblx0JVATxbLQnqWSpvSO820SHF8GeRUGUCe1renpSN5Nvh2W3gSwHGLNq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/124802801/99bef394-5707-4088-af59-c94e47af4efd)

### Environment

```markdown
- FlutterFlow version: 4.1.63+
- Platform: Web Desktop
- Browser name and version: Chrome 126.0.6478.127
- Operating system and version affected: Windows
```

### Additional Information

Even though both actions worked fine a few days ago.

**Comment by msusviela** [comment] 2024-06-28 17:57
Hi @hughCar389. <br>I already replied in the other issue that you opened: [https://github.com/FlutterFlow/flutterflow-issues/issues/3269](https://github.com/FlutterFlow/flutterflow-issues/issues/3269)<br><br>I'm closing this since it's a duplicate of that.

**Closed as not planned** 2024-06-28 17:57 UTC
Labels: closed: duplicate

**Comment by hughCar389** [comment] 2024-06-28 18:55
@msusviela The issue doesn't work in any of my projects or this ones clone. I need help fixing this issue.

**Comment by msusviela** [comment] 2024-06-28 19:17
I'm sorry but we are unable to reproduce this issue from a blank project, can you please reach out to [support@flutterflow.io](mailto:support@flutterflow.io)? They can better assist you with ensuring your project is configured correctly.
