### ISSUE TITLE
Action editor goes faint

### ISSUE THREAD

**Issue by thruthesky** [FlutterFlow/flutterflow-issues#444] opened 2023-02-03 16:52 UTC
## Expected behavior (required)

- Action editor goes faint.

## Current behavior (required)

- The Action editor should not go faint.

## To Reproduce (required)

Please watch the video.

### Bug Report Code (required, generate from Widget Tree)

N/A

## Context (required)

- The screen strangely goes faint and difficult to work.

## Screenshots / recordings

https://user-images.githubusercontent.com/5080329/216660654-2e348457-3144-41f7-8d62-b6de68c4f2d0.mp4

## Your environment

* Version of FlutterFlow used: v3.0 January 21, 2023 - Flutter 3.3.4
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome Version 109.0.5414.87 (Official Build) (arm64)
* Operating system and version (desktop or mobile): Mac, Laptop.

**Comment by hariprasadms** [comment] 2023-02-04 22:53
Hi @thruthesky - Thanks for posting this issue. 
We need more information on the reproducing steps before we look into this issue. Issue troubleshooting is tough without steps information. I appreciate that you included the video clip. However, video clip it is not clearly showing when exactly grey background showing up. Please refer issue template and add the details accordingly.

We can re-visit the issue once you have provided more information.

As per video, I think, hard refresh browser page ( Ctrl+R) can help to clear the grey background. Give a try and let us know if that can help you.

Thanks

**Comment by hariprasadms** [comment] 2023-02-06 16:50
Hi @thruthesky - Can you please update the status of this issue? If this is still persisting, can you add more step details to reproduce the issue. 
If you are not facing this problem any more, we can close the issue. Please update.

**Comment by agreaves** [comment] 2023-02-12 21:03
Closing this as a transient issue since we aren't able to reproduce. Please let us know if you are able to reproduce this issue and we can further investigate!

**Closed by agreaves** 2023-02-12 21:03 UTC
Labels: status: needs information, status: needs reproducible steps
