### ISSUE TITLE
Flutter 3.24.2 causes main crashes

### ISSUE THREAD

**Issue by TolinhoCTO** [FlutterFlow/flutterflow-issues#4750] opened 2024-10-29 07:11 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When downloading the app a lot of users experience crashes when opening the app since the upgrade to 3.24.2, it fills the cashes too quickly even when using cashes or removing them. No clear structure on this side, some works other don'ts

### Expected Behavior

Work like before flutter update

### Steps to Reproduce

1. download meerai.io on app store
2. If your iphone is concerned the app will crash

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXi/Hl34Z1oeZE1rqAK8ZsniYwGUwbUOc7j9VEGAsjCePqEIl3O+PBXFdocuqHf1FDfUyWhTgz087qv9j9F8JeBxasc5xH+LV1UxDgLUWWacm7PpC0f3QmBfNRG2aC0J6nuRQkBMZtL2QMwU+DfeyQb3qCf9qOYwx5e6fDbOY=

### Visual documentation

https://github.com/user-attachments/assets/73d04fe7-34b8-4bcb-8012-7fe2e3cb91da

### Environment

```markdown
- FlutterFlow version: 5.0.8
- Platform: IOS
- Browser name and version: Chrome
- Operating system and version affected: IOS, flutter 3.24.2
```

**Comment by Alezanello** [comment] 2024-10-29 12:22
Hello!

Could you provide a bit more information to help us investigate? Specifically:

* Do you have any crash logs you can share?
* Is this issue occurring only on iPhone, or does it happen on Android as well?
* Have you tested it in Local Run on a simulator? If so, does the issue persist there?
* Do you have any additional debugging logs?

Thank you! This will help us understand the problem more clearly.

**Comment by TolinhoCTO** [comment] 2024-10-29 13:00
I am sorry I do not have the capacities to reproduce the crash with my computer, it only happens with iphones. I do not know how to try it on local run but I myself don’t have the problem with my phone but half of my users have

**Comment by Alezanello** [comment] 2024-10-29 13:50
Are you using macOS or Windows on your computer?

You can try downloading the FlutterFlow Desktop App and using the Local Run feature to test your app. This will allow you to view logs that might explain why the app is crashing.

Please note that this GitHub Issue Tracker is intended for reporting bugs that can be reproduced on a new, blank project. Understanding the specific cause of this issue in your project will help us attempt to replicate it on our end.

Thank you!

**Comment by tarakiga** [comment] 2024-10-29 14:49
Maybe this may help, i am having the same issue with app during testing. First with Android where I was able to get stacktrace from crashlytics and same on ios as well. Find stacktrace attached:
[com.mycompany.cohorts_issue_142da408780c70d2ade1e81d52b5ad37_crash_session_672054B6027800010E1F0BBE643EE1F1_DNE_0_v2_stacktrace.txt](https://github.com/user-attachments/files/17558715/com.mycompany.cohorts_issue_142da408780c70d2ade1e81d52b5ad37_crash_session_672054B6027800010E1F0BBE643EE1F1_DNE_0_v2_stacktrace.txt)

**Comment by ghost** [comment] 2024-10-29 15:31
I’m experiencing the same issue. My app crashes immediately after opening on both Android and iOS. I raised a ticket for assistance from the FlutterFlow support team, but the problem hasn’t been resolved. The app was working perfectly before the update.

**Comment by ghost** [comment] 2024-10-29 15:43
Here is a crash report from the Google Play Store, which may help. Exception java.lang.IllegalAccessError: Field 'com.google.firebase.concurrent.ExecutorsRegistrar.a' is inaccessible to class 'L.n1' (declaration of 'L.n1' appears in /data/app/~~wDvgiQVxTU_93yqL-FW5ZQ==/com.mycompany.hulum-HkxmhC-TzDtfUKa9JFUA1Q==/base.apk)
  at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0 (ComponentRuntime.java)
  at com.google.firebase.components.Lazy.get (Lazy.java)
  at com.google.firebase.components.RestrictedComponentContainer.get (RestrictedComponentContainer.java)
  at com.google.firebase.appcheck.FirebaseAppCheckRegistrar.lambda$getComponents$0 (FirebaseAppCheckRegistrar.java)
  at com.google.firebase.tracing.ComponentMonitor.lambda$processRegistrar$0 (ComponentMonitor.java:12)
  at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0 (ComponentRuntime.java)
  at com.google.firebase.components.Lazy.get (Lazy.java)
  at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents (ComponentRuntime.java)
  at com.google.firebase.components.ComponentRuntime.initializeEagerComponents (ComponentRuntime.java)
  at com.google.firebase.FirebaseApp.initializeAllApis (FirebaseApp.java:67)
  at com.google.firebase.FirebaseApp.initializeApp (FirebaseApp.java:72)
  at com.google.firebase.FirebaseApp.initializeApp (FirebaseApp.java:38)
  at com.google.firebase.FirebaseApp.initializeApp (FirebaseApp.java:38)
  at com.google.firebase.provider.FirebaseInitProvider.onCreate (FirebaseInitProvider.java)
  at android.content.ContentProvider.attachInfo (ContentProvider.java:2451)
  at android.content.ContentProvider.attachInfo (ContentProvider.java:2421)
  at com.google.firebase.provider.FirebaseInitProvider.attachInfo (FirebaseInitProvider.java:13)
  at android.app.ActivityThread.installProvider (ActivityThread.java:7508)
  at android.app.ActivityThread.installContentProviders (ActivityThread.java:7019)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6790)
  at android.app.ActivityThread.-$$Nest$mhandleBindApplication
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2132)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:201)
  at android.os.Looper.loop (Looper.java:288)
  at android.app.ActivityThread.main (ActivityThread.java:7918)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:548)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:936)

**Comment by slvkrvnsv** [comment] 2024-10-29 18:44
In my case, it works fine with the iOS app, but Android crashes with the exception:

> io.grpc.okhttp.OkHttpChannelBuilder.<clinit> (OkHttpChannelBuilder.java:103)

I don't know how it passed the review! But now I have **0% crash-free users** on the latest release. OMFG. Achievement unlocked.

On some devices, you have 1 second of the initial page rendered but on others, it crashes completely right after launch.

If I launch the in debug mode via Android studio it's fine, but in the Release mode, I've reproduced this stuff – crash!

UPDATE. Thanks to ChatGPT I've modified the project by adding 'proguard-rules.pro' file with the necessary stuff inside of it because the 'purchases_flutter-8-1.2' dependency required it, but didn't have it in the 'android/app' directory.

I'm not sure if it's related to the main case already. But when 'main' crashes is a trouble!

**Comment by adnanmur** [comment] 2024-10-29 22:33
> Here is a crash report from the Google Play Store, which may help. Exception java.lang.IllegalAccessError: Field 'com.google.firebase.concurrent.ExecutorsRegistrar.a' is inaccessible to class 'L.n1' (declaration of 'L.n1' appears in /data/app/~~wDvgiQVxTU_93yqL-FW5ZQ==/com.mycompany.hulum-HkxmhC-TzDtfUKa9JFUA1Q==/base.apk) at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0 (ComponentRuntime.java) at com.google.firebase.components.Lazy.get (Lazy.java) at com.google.firebase.components.RestrictedComponentContainer.get (RestrictedComponentContainer.java) at com.google.firebase.appcheck.FirebaseAppCheckRegistrar.lambda$getComponents$0 (FirebaseAppCheckRegistrar.java) at com.google.firebase.tracing.ComponentMonitor.lambda$processRegistrar$0 (ComponentMonitor.java:12) at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0 (ComponentRuntime.java) at com.google.firebase.components.Lazy.get (Lazy.java) at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents (ComponentRuntime.java) at com.google.firebase.components.ComponentRuntime.initializeEagerComponents (ComponentRuntime.java) at com.google.firebase.FirebaseApp.initializeAllApis (FirebaseApp.java:67) at com.google.firebase.FirebaseApp.initializeApp (FirebaseApp.java:72) at com.google.firebase.FirebaseApp.initializeApp (FirebaseApp.java:38) at com.google.firebase.FirebaseApp.initializeApp (FirebaseApp.java:38) at com.google.firebase.provider.FirebaseInitProvider.onCreate (FirebaseInitProvider.java) at android.content.ContentProvider.attachInfo (ContentProvider.java:2451) at android.content.ContentProvider.attachInfo (ContentProvider.java:2421) at com.google.firebase.provider.FirebaseInitProvider.attachInfo (FirebaseInitProvider.java:13) at android.app.ActivityThread.installProvider (ActivityThread.java:7508) at android.app.ActivityThread.installContentProviders (ActivityThread.java:7019) at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6790) at android.app.ActivityThread.-$$Nest$mhandleBindApplication at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2132) at android.os.Handler.dispatchMessage (Handler.java:106) at android.os.Looper.loopOnce (Looper.java:201) at android.os.Looper.loop (Looper.java:288) at android.app.ActivityThread.main (ActivityThread.java:7918) at java.lang.reflect.Method.invoke at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:548) at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:936)

I have the same issue on Android. iOS works fine, let me know if you find a fix

**Comment by kamiloxl** [comment] 2024-10-29 23:40
> In my case, it works fine with the iOS app, but Android crashes with the exception:
> 
> > io.grpc.okhttp.OkHttpChannelBuilder. (OkHttpChannelBuilder.java:103)
> 
> I don't know how it passed the review! But now I have **0% crash-free users** on the latest release. OMFG. Achievement unlocked.
> 
> On some devices, you have 1 second of the initial page rendered but on others, it crashes completely right after launch.
> 
> If I launch the in debug mode via Android studio it's fine, but in the Release mode, I've reproduced this stuff – crash!
> 
> UPDATE. Thanks to ChatGPT I've modified the project by adding 'proguard-rules.pro' file with the necessary stuff inside of it because the 'purchases_flutter-8-1.2' dependency required it, but didn't have it in the 'android/app' directory.
> 
> I'm not sure if it's related to the main case already. But when 'main' crashes is a trouble!

I have evcly the same issue!!! So annoying I spend already 20h on debugging but no solution. Newest update is soooo 💩

**Comment by tarakiga** [comment] 2024-10-29 23:45
I got the progaurd recommendation too but I don't want to go through the stress of always updating source files when I want to deploy or do I have to do it just once?


 


  
  
 

 
  
 
   On Wed, Oct 30, 2024, 03:40 AM kamiloxl ***@***.***> wrote: 
   
  
  
   
   
   In my case, it works fine with the iOS app, but Android crashes with the exception: 
    
    io.grpc.okhttp.OkHttpChannelBuilder. (OkHttpChannelBuilder.java:103) 
    
   I don't know how it passed the review! But now I have 0% crash-free users on the latest release. OMFG. Achievement unlocked. 
   On some devices, you have 1 second of the initial page rendered but on others, it crashes completely right after launch. 
   If I launch the in debug mode via Android studio it's fine, but in the Release mode, I've reproduced this stuff – crash! 
   UPDATE. Thanks to ChatGPT I've modified the project by adding 'proguard-rules.pro' file with the necessary stuff inside of it because the 'purchases_flutter-8-1.2' dependency required it, but didn't have it in the 'android/app' directory. 
   I'm not sure if it's related to the main case already. But when 'main' crashes is a trouble! 
   
  I have evcly the same issue!!! So annoying I spend already 20h on debugging but no solution. Newest update is soooo 💩 
  —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***> 
  [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/FlutterFlow/flutterflow-issues/issues/4750#issuecomment-2445518497",
"url": "https://github.com/FlutterFlow/flutterflow-issues/issues/4750#issuecomment-2445518497",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ghost** [comment] 2024-10-30 00:33
> > In my case, it works fine with the iOS app, but Android crashes with the exception:
> > > io.grpc.okhttp.OkHttpChannelBuilder. (OkHttpChannelBuilder.java:103)
> > 
> > 
> > I don't know how it passed the review! But now I have **0% crash-free users** on the latest release. OMFG. Achievement unlocked.
> > On some devices, you have 1 second of the initial page rendered but on others, it crashes completely right after launch.
> > If I launch the in debug mode via Android studio it's fine, but in the Release mode, I've reproduced this stuff – crash!
> > UPDATE. Thanks to ChatGPT I've modified the project by adding 'proguard-rules.pro' file with the necessary stuff inside of it because the 'purchases_flutter-8-1.2' dependency required it, but didn't have it in the 'android/app' directory.
> > I'm not sure if it's related to the main case already. But when 'main' crashes is a trouble!
> 
> I have evcly the same issue!!! So annoying I spend already 20h on debugging but no solution. Newest update is soooo 💩


> > Here is a crash report from the Google Play Store, which may help. Exception java.lang.IllegalAccessError: Field 'com.google.firebase.concurrent.ExecutorsRegistrar.a' is inaccessible to class 'L.n1' (declaration of 'L.n1' appears in /data/app/~~wDvgiQVxTU_93yqL-FW5ZQ==/com.mycompany.hulum-HkxmhC-TzDtfUKa9JFUA1Q==/base.apk) at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0 (ComponentRuntime.java) at com.google.firebase.components.Lazy.get (Lazy.java) at com.google.firebase.components.RestrictedComponentContainer.get (RestrictedComponentContainer.java) at com.google.firebase.appcheck.FirebaseAppCheckRegistrar.lambda$getComponents$0 (FirebaseAppCheckRegistrar.java) at com.google.firebase.tracing.ComponentMonitor.lambda$processRegistrar$0 (ComponentMonitor.java:12) at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0 (ComponentRuntime.java) at com.google.firebase.components.Lazy.get (Lazy.java) at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents (ComponentRuntime.java) at com.google.firebase.components.ComponentRuntime.initializeEagerComponents (ComponentRuntime.java) at com.google.firebase.FirebaseApp.initializeAllApis (FirebaseApp.java:67) at com.google.firebase.FirebaseApp.initializeApp (FirebaseApp.java:72) at com.google.firebase.FirebaseApp.initializeApp (FirebaseApp.java:38) at com.google.firebase.FirebaseApp.initializeApp (FirebaseApp.java:38) at com.google.firebase.provider.FirebaseInitProvider.onCreate (FirebaseInitProvider.java) at android.content.ContentProvider.attachInfo (ContentProvider.java:2451) at android.content.ContentProvider.attachInfo (ContentProvider.java:2421) at com.google.firebase.provider.FirebaseInitProvider.attachInfo (FirebaseInitProvider.java:13) at android.app.ActivityThread.installProvider (ActivityThread.java:7508) at android.app.ActivityThread.installContentProviders (ActivityThread.java:7019) at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6790) at android.app.ActivityThread.-$$Nest$mhandleBindApplication at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2132) at android.os.Handler.dispatchMessage (Handler.java:106) at android.os.Looper.loopOnce (Looper.java:201) at android.os.Looper.loop (Looper.java:288) at android.app.ActivityThread.main (ActivityThread.java:7918) at java.lang.reflect.Method.invoke at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:548) at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:936)
> 
> I have the same issue on Android. iOS works fine, let me know if you find a fix

As someone without a coding background, I rely completely on FlutterFlow to build, test, and deploy my app. I didn’t anticipate encountering such difficulties—my mistake! Unfortunately, their internal support hasn’t been very helpful. Right now, I’m waiting for the FlutterFlow team to resolve the issue. I had been conducting internal tests and was just about to submit for review, this is really disappointing.

**Comment by TolinhoCTO** [comment] 2024-10-30 05:17
It got a bit crazy out here, nevertheless I runned my app on local run and had this error logs coming up which can maybe explain the crashes: 

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).

[!] The `Runner [Debug]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `Runner [Release]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `Runner [Profile]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `ImageNotification [Debug]` target overrides the `CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER` build setting defined in `Pods/Target Support Files/Pods-ImageNotification/Pods-ImageNotification.debug.xcconfig'. This can lead to problems with the CocoaPods installation
[!] The `ImageNotification [Profile]` target overrides the `CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER` build setting defined in `Pods/Target Support Files/Pods-ImageNotification/Pods-ImageNotification.profile.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
[!] The `ImageNotification [Release]` target overrides the `CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER` build setting defined in `Pods/Target Support Files/Pods-ImageNotification/Pods-ImageNotification.release.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `ImageNotification [Profile]` target overrides the `CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER` build setting defined in `Pods/Target Support Files/Pods-ImageNotification/Pods-ImageNotification.profile.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

**Comment by TolinhoCTO** [comment] 2024-10-30 05:22
I precise for anyone jumping in this issue, this issue only concern IOS crashes

**Comment by amicable-io** [comment] 2024-10-30 11:30
https://community.flutterflow.io/discussions/post/apk-crash-after-3-24-2-flutter-update-6iWn5tXbN1gpYvA

**Comment by amicable-io** [comment] 2024-10-30 11:30
@Alezanello can you take a look on it? It is breaking entire deployment to play store. Solution for it is here https://community.flutterflow.io/discussions/post/apk-crash-after-3-24-2-flutter-update-6iWn5tXbN1gpYvA

**Comment by Alezanello** [comment] 2024-10-30 12:37
Hello everyone! Thank you for sharing the link to the community post; it provides helpful context about the situation. I’ll forward this ticket to the engineering team for a fix. Thanks for your patience!

**Comment by leighajarett** [comment] 2024-10-30 12:45
We have a fix for this issue and will deploy ASAP!

**Comment by TolinhoCTO** [comment] 2024-10-31 13:54
Hi, even with the latest link shared did you investigate the issue on the ios side I shared ? Thank you for your quick response

**Comment by ghost** [comment] 2024-11-01 03:04
i am also facing the same issue.
 !] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).

[!] The `Runner [Debug]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `Runner [Release]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `Runner [Profile]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `ImageNotification [Debug]` target overrides the `CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER` build setting defined in `Pods/Target Support Files/Pods-ImageNotification/Pods-ImageNotification.debug.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `ImageNotification [Release]` target overrides the `CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER` build setting defined in `Pods/Target Support Files/Pods-ImageNotification/Pods-ImageNotification.release.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `ImageNotification [Profile]` target overrides the `CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER` build setting defined in `Pods/Target Support Files/Pods-ImageNotification/Pods-ImageNotification.profile.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
Launching lib/main.dart on iPhone 16 in debug mode...

**Comment by alfqui19** [comment] 2024-11-08 13:24
Any updates on the deployed fix? I have not been able to publish a new version of my android app since update

**Comment by leighajarett** [comment] 2024-11-08 20:41
Working on getting it deployed ASAP!

**Comment by TolinhoCTO** [comment] 2024-11-15 11:51
Not fixed still crashing on ios

**Comment by leighajarett** [comment] 2024-11-15 13:09
Sorry about that, taking another look! Please send over any additional details that could be helpful

**Comment by wenkaifan0720** [comment] 2024-11-15 16:54
Hi @TolinhoCTO. I tested on a simulator (iOS 18.0) and a real device (iOS 18.1) and couldn't reproduce a crash. I created a account and navigated through the app. Could you provide more details on which devices/iOS version your users are seeing the crash? Thank you!

**Comment by TolinhoCTO** [comment] 2024-11-15 16:56
The simulator usually use a device which is more advanced, the problem is encountered with every iphone under the 13th

**Comment by wenkaifan0720** [comment] 2024-11-15 16:57
Do you mean iPhone 13 or iOS 13?

**Comment by TolinhoCTO** [comment] 2024-11-15 16:57
Which is an important part of our userbase, also it has been reported multiple times. And in the logs on launching errors are showing up

**Comment by TolinhoCTO** [comment] 2024-11-15 16:58
Every iphone under 13 or not pro under 13

**Comment by wenkaifan0720** [comment] 2024-11-15 16:59
I tested on an iPhone 13 mini (running iOS 18.1). Let me try a simulator with lower iOS versions.

**Comment by wenkaifan0720** [comment] 2024-11-15 17:18
I still couldn't reproduce the crash on a simulator running iOS 17.4. I don't have other physical devices around. If you could reproduce the crash locally, could you send me the error log?

**Comment by wenkaifan0720** [comment] 2024-11-15 17:23
@hulum-io @tarakiga @adnanmur @kamiloxl Hi all. Just want to make sure, are you guys still experiencing crashing issues? We have pushed a bunch of fixes since the last Flutter upgrade.

**Comment by amicable-io** [comment] 2024-11-16 09:29
@wenkaifan0720 for me all is working fine (kamiloxl here) :)

**Comment by TolinhoCTO** [comment] 2024-11-16 10:29
> I still couldn't reproduce the crash on a simulator running iOS 17.4. I don't have other physical devices around. If you could reproduce the crash locally, could you send me the error log?

The crash is exactly the same as the first video opened on this issue, tested again yesterday and still happening (a new version has been deployed on our end yesterday) are the fixes live ? And maybe it has a connection with those logs https://github.com/FlutterFlow/flutterflow-issues/issues/4750#issuecomment-2451206764

**Comment by wenkaifan0720** [comment] 2024-11-18 15:15
These are cocoapods warnings, which I don't think is relevant. Since I still can't reproduce this issue, I am not sure what the issue is. This issue might be relevant: https://github.com/firebase/flutterfire/issues/13553. We will update our Firebase dependencies to the latest version. If you don't want to wait for the next update, you can manually add the Firebase dependencies as your custom dependency and use the latest versions.

**Comment by TolinhoCTO** [comment] 2024-11-21 04:04
I Searched and I think I finnaly found it:
Exception: blurhash length mismatch: length is 104 but it should be 84

I want to precise I do not give length or height to blurhash, just using the functionnality nested in flutterflow

**Comment by wenkaifan0720** [comment] 2024-11-21 13:13
Could you point to where are you using this blurhash (with a bug report code)?

**Comment by tarakiga** [comment] 2024-11-25 10:48
Here is a crash file from my iOs preflight test if it is helpful. Same thing that was fixed on iOs where app crashes on login.
        
        
          On Nov 21 2024, at 5:14 pm, Wenkai Fan ***@***.***> wrote:
          
        
        
           
Could you point to where are you using this blurhash (with a bug report code)?

**Comment by tarakiga** [comment] 2024-11-27 12:57
[crashlog.txt](https://github.com/user-attachments/files/17934525/crashlog.txt)
 This is the crash log from ios. Android is fixed and working now but iOs still crashes on login.

**Comment by tarakiga** [comment] 2024-11-30 19:20
So i did some debugging and after disabling and removing onesignal ios stopped crashing on signin so i'm guessing it was a permission issue.

**Closed as completed** 2024-12-05 03:57 UTC
Labels: status: confirmed, Bug
