### ISSUE TITLE
Unable to set fields when using datatype from a document

### ISSUE THREAD

**Issue by corpclegg27** [FlutterFlow/flutterflow-issues#236] opened 2022-12-16 11:11 UTC
<img width="380" alt="Screenshot_20221216_113022" src="https://user-images.githubusercontent.com/89472366/208086133-22e09812-6796-4432-8943-d1a06aa0437d.png">
<img width="379" alt="Screenshot_20221216_113933" src="https://user-images.githubusercontent.com/89472366/208086020-34653ad8-efbe-4fe5-800c-2672c8ffacf1.png">

**Comment by davidflutterflow** [comment] 2022-12-16 13:13
Thanks, seems we can't select data types anymore I approve this is a bug.

**Comment by davidflutterflow** [comment] 2022-12-16 13:16
Steps to reproduce:
1- You need to have a data type
2- you have a field in one of collections from the data type
3- try to set a text widget from the same document/data type filed

The issue is after select the data type field the next options is not appear to select the field

**Comment by agreaves** [comment] 2022-12-16 16:32
Thank you very much for the bug report! We have just pushed a fix, so closing this issue now.

**Closed by agreaves** 2022-12-16 16:32 UTC
Labels: status: needs triage
