### ISSUE TITLE
Reopen: problem with saving theme widgets #3367

### ISSUE THREAD

**Issue by ReflexOlivier** [FlutterFlow/flutterflow-issues#3392] opened 2024-07-13 08:41 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

the Saving issue on theme widget described in ticket #3367 is always present.
Just test it this morning on the App and on the Web (safari).
See video

Thanks.

### Expected Behavior

Widget Theme have to be saved each time

### Steps to Reproduce

1 create new theme widget
2 make changes to the widget parameters
3 save the widget
4 Issue: **sometimes** widget not saved

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

TFfkvLlx5NgochE1a6Jb+0wqCEsQz4cTeU30+thcw4bI+KqE4khP/TCVFRVYuqHYwpDM1Sbgjoy+fTnv9jxUMICA0mVGKph1KtfUxDgTlmhV4iJBaWaVkElJ8dRN2qn0Z2RuwpAKsF0S3ws7TuuAd6QY3qCf9qOYwx5e6fDbOY=

### Visual documentation

https://github.com/user-attachments/assets/35b6b9f0-0bdc-471d-b2e8-cbcc42b38ebe

### Environment

```markdown
- FlutterFlow version: 4.1.72
- Platform:App & Web
- Browser name and version:Safari 17.5
- Operating system and version affected: MacOs 13.6.7
```

### Additional Information

Quick resolution of this issue is very important as we use every time this functionality.

Thanks

**Comment by paulperez-dev** [comment] 2024-07-14 00:25
Hi @LouisTheBoss! I was able to reproduce the issue, I will send it to the ENG team so they can work on this!

**Comment by saurabhqaengineerfp** [comment] 2024-07-17 20:15
Hi, I saw the video attached above. I would like to say it is not just safari, it is present on chrome and firefox as well. Not just mac, it is reproducible 9 out of 10 times on windows as well. Please fix this as soon as possible. I cannot imagine how are clients using flutterflow without widgets working. How is this not a showstopper. This should be highest priority for flutterflow team. I was up last night for 4 hours trying to get a workaround. I thought this would have stop everything at flutterflow organisation and would have been fixed by now but to my surprise it is still the same. How is this company running?

**Comment by carlosgomesp** [comment] 2024-07-17 20:39
As a workaround, I am creating the widget directly on the page, setting the styles, and saving it as a theme widget. I am experiencing the same issue mentioned above. I am using Windows 11 and have tested it on the most common browsers (Edge, Chrome, Firefox) with the latest version. I believe it is crucial to pay full attention to this bug since our company is encountering this issue in several projects we are working on.

**Comment by saurabhqaengineerfp** [comment] 2024-07-17 22:06
Thanks @carlosgomesp , I tried your workaround of creating the theme widgets directly from the page itself, I would say it gave some relief but there is no way to bind some properties i the widget when you do it from the page. For example, height of the button will change to default, content padding of TextField, Label value of TextField, Hint value of TextField will be set to default. So Ilet us hope that flutterflow team fixes this soon. I am bit skeptical now that this company will fail or is failing, I have read too many negative comments about the customer support, that they are the worst anyone has ever experienced, they come back after 72 hours, this is for the premium customers, people like me who are using free tier are lowest in priority. But I am assuming as widget creation is such a big functionality of flutterflow, how is it not resolved yet.

**Comment by carmenchargely** [comment] 2024-07-18 16:20
I'm experiencing this bug as well. It's really frustrating. Sometimes it starts to save after I refresh the screen, but then it goes back to not saving.

**Comment by saurabhqaengineerfp** [comment] 2024-07-20 20:01
Thank you so much devs and flutterflow team for resolving the issue, I don't see it anymore.

**Closed as completed** 2024-07-23 07:40 UTC
Labels: status: confirmed, Bug
