### ISSUE TITLE
Build fails 10x more often then before

### ISSUE THREAD

**Issue by Kato-Official** [FlutterFlow/flutterflow-issues#3979] opened 2024-10-05 05:20 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I've been noticing a lot of frequent build failures when testing lately. It started happening after a previous update, but with the latest version (FlutterFlow v5.0.3, released October 4, 2024, and Flutter version 3.22.2), it's happening even more often. It's getting frustrating enough that I had to opening this report. Any suggestions on how to resolve this?
![Screenshot 2024-10-05 at 9 13 18 AM (2)](https://github.com/user-attachments/assets/6a2cb09e-d618-4c0d-a614-a8639ccbfd7f)

### Expected Behavior

Not to fail so often. I understand every now and then, but not this frequently. 

### Steps to Reproduce

1. Test on any project the "test" button and notice how frequently you see the build failed.
2. Feel free to check the logs.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTjsmAsItNm7RG+KnTKPpvoCEUGUMcWOdEl+tuZwgbIoznBu0qesj7M1tDUsDiaVNcAlqanl4J+aDHv4fDCvUrGEyZQYA/wZdUdAr0e2inRpSRPIeWQEZBGcFYf3ax0bW7swpROtNidEY+wHGECunJYBbDFOu/Zwh9f6PHaOI=

### Visual documentation

![Screenshot 2024-10-05 at 9 13 18 AM (2)](https://github.com/user-attachments/assets/96c410f5-1800-4bc8-b22e-71e8476ef86e)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.3, released October 4, 2024, and Flutter version 3.22.2
- Platform: Desktop 
- Browser name and version: Chrome
- Operating system and version affected: Mac
```

**Comment by paulperez-dev** [comment] 2024-10-07 20:22
Hi @Kato-Official,

I'm so sorry to hear you're experiencing this issue. I wasn’t able to reproduce the behavior on my end. If the issue persists, could you please reach out to our support team? You can contact them via email at [support@flutterflow.io](mailto:support@flutterflow.io) or through the in-app chat within FlutterFlow.

Since this tracker is specifically for bugs that can be reproduced from blank projects, I’ll go ahead and close this issue for now. However, if you’re able to reproduce it on a blank project, please don’t hesitate to let us know and share the bug code for that project.

Thank you so much for your understanding!

**Closed as completed** 2024-10-08 06:03 UTC
Labels: status: needs triage
