### ISSUE TITLE
Reorderable ListView Selects Old Index as actual Index and New Index as Position

### ISSUE THREAD

**Issue by Dev-Muhammad-Junaid** [FlutterFlow/flutterflow-issues#1427] opened 2023-09-08 18:46 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I just tried the new Reorderable list and couldn't update the values in the way I thought they should
So when I printed out the values old index is actual index and new index is position instead of new index

### Expected Behavior

The index should be index right? Not sure if it's by design that new index is set to position. But I doubt it.

### Steps to Reproduce

1. Drop a listview
2. Drop a text
3. Make it reorderable

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40kMmA8Y9Pxd9A7c/9bcdR/SI5KUw+RI0n0+1RaCosfZT2BLMcec/RVERtZOniYX9YIGaghWoW0NL8k+DtNvAnOTeWfLZ5+M5qTg7MbHqgbrqgFJWgeUFCJ+hgI0fG5MCzqhFACPp2Wnct7Du2Feu9YHfaQrrVOm4wDq/LZO4=

### Context

Not able to reorder effectively

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/65047962/dba9279f-40a9-4f44-99a7-e5de095e6c27

### Environment

```markdown
- FlutterFlow version:v3.1 (released September 7, 2023)
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected:  MACOS Sonoma
```

**Comment by zeymermontes** [comment] 2023-09-13 17:33
I was going to report this too. I can confirm that I have the same issue and that the expected behavior is to keep the new order on the list.

**Comment by idea-garage** [comment] 2023-09-14 02:01
Read this: [https://api.flutter.dev/flutter/material/ReorderableListView-class.html](https://api.flutter.dev/flutter/material/ReorderableListView-class.html)

`onReorder: (int oldIndex, int newIndex) {
        setState(() {
          if (oldIndex < newIndex) {
            newIndex -= 1;
          }
          final int item = _items.removeAt(oldIndex);
          _items.insert(newIndex, item);
        });
      },`

**Comment by stevey6404** [comment] 2023-09-14 02:26
I think the index numbers outputted are correct, but from a UI element perspective, it isn't...how everything is still A,B,C,D,E.

Is there a way to order it correctly after the move within FF?

**Comment by idea-garage** [comment] 2023-09-14 02:49
You may set the ListView ordering as some variable in the target Collection. Update this variable in the specific document On reorder.
I'm using Supabase, so please someone describe for Firebase.

**Comment by Dev-Muhammad-Junaid** [comment] 2023-09-14 14:00
> I think It's normal behaviour of ReorderableListView class. Read this: https://api.flutter.dev/flutter/material/ReorderableListView-class.html
> 
> Sample in Flutter code: onReorder: (int oldIndex, int newIndex) { setState(() { if (oldIndex < newIndex) { newIndex -= 1; } final int item = _items.removeAt(oldIndex); _items.insert(newIndex, item); }); },

I see, the underlying working is kind of the same, I can ofcourse implement as such, however, this should be updated for non-technicals. They are not aware of Flutter they are completely relying on FF to build this. So having one index as index and second as position will make them scream 😅

**Comment by stevey6404** [comment] 2023-09-15 02:35
> You may set the ListView ordering as some variable in the target Collection. Update this variable in the specific document On reorder.
> I'm using Supabase, so please someone describe for Firebase.

Thanks for this! I'm trying to figure this out for Firebase so happy to share when I get it. 
I'm having a bit of trouble updating the ordering for everything else (not the dragged item).

E.g. I have created a position field called 1,2,3,4,5 for A,B,C,D,E

I drag A to be after C. A now has the position of 3 but B and C still have position of 2 and 3 and D and E have position 4 and 5 (which is correct). Now thinking about it, do I need to execute a loop to -1 position for anything before the newly dragged item (e.g. A and B).

**Comment by idea-garage** [comment] 2023-09-15 08:52
Carefully read this:
[https://api.flutter.dev/flutter/dart-core/List/insert.html](https://api.flutter.dev/flutter/dart-core/List/insert.html)

**Comment by Alexandre-Lemyre** [comment] 2023-09-16 23:26
As a no-coder who have been using FF for more than a year, I have no idea what is going on here. I select the "reorderable" option in the Listview, I expect the items to be reorderable... but they keep snapping back in their original place when I try to move them. Will this be fixed?

**Comment by stevey6404** [comment] 2023-09-17 05:13
@Alexandre-Lemyre luckily FF has updated their documentation on what to do! Last time I searched it wasn't there but it's there now!!

https://docs.flutterflow.io/widgets-and-components/widgets/layout-elements/listview#reorder-list

**Comment by Alexandre-Lemyre** [comment] 2023-09-17 23:36
Hi @stevey6404. Thank you for the follow up! That looks simple enough, but I am unable to create the custom action. In fact, something prevents me from saving it (see attached images). Any cues on what I might be doing wrong?

![Custom action 1](https://github.com/FlutterFlow/flutterflow-issues/assets/120210391/8fdb0f04-402c-44a5-b37f-c4106d58f994)
![custom action 2](https://github.com/FlutterFlow/flutterflow-issues/assets/120210391/d0861ef3-e0f0-4efd-b5d0-6c42be2f976b)

**Comment by zeymermontes** [comment] 2023-09-17 23:42
@Alexandre-Lemyre 
Because on the code the name is not the same. You have on the UI "reorderItems" and on the code you have "reorderFirebaseItems"

**Comment by Alexandre-Lemyre** [comment] 2023-09-17 23:53
@zeymermontes
Thank you for pointing out this mistake. Now, when I try to save, I get this error: unable to process parameter "list"
Do you know what might be the error?

**Comment by zeymermontes** [comment] 2023-09-17 23:58
@Alexandre-Lemyre  the issue is that on the ui list is of type List<String> but on the code  is a List<PlaylistRecord>

**Comment by Alexandre-Lemyre** [comment] 2023-09-18 00:33
@zeymermontes
I'm sorry I do not quite understand the issue and how to fix it. I am using the code provided in the documentation for a list of items retrieved from Firebase:
https://docs.flutterflow.io/widgets-and-components/widgets/layout-elements/listview#reorder-list

The only indication is "Replace the custom action code with the below one".

**Comment by stevey6404** [comment] 2023-09-18 00:35
In argument 1, you haven't checked the 'Is List' checkbox.

**Comment by Alexandre-Lemyre** [comment] 2023-09-18 00:40
Oh I did try that and I am getting the same error: unable to process parameter "list"

**Comment by zeymermontes** [comment] 2023-09-18 00:40
On the provided code the list type is List<String>

// Define a function called reorderItems that returns a Future of a list of strings.
// It takes in a list of strings, an old index, and a new index as parameters.
Future<List<String>> reorderItems(
  List<String> list,
  int oldIndex,
  int newIndex,
) async {
  // If the item is being moved to a position further down the list
  // (i.e., to a higher index), decrement the newIndex by 1.
  // This adjustment is needed because removing an item from its original
  // position will shift the indices of all subsequent items.
  if (oldIndex < newIndex) {
    newIndex -= 1;
  }

  // Remove the item from its original position in the list and store
  // it in the 'item' variable.
  final item = list.removeAt(oldIndex);

  // Insert the removed item into its new position in the list.
  list.insert(newIndex, item);

  // Return the modified list.
  return list;
}

**Comment by Alexandre-Lemyre** [comment] 2023-09-18 00:45
I might be a bit slow tonight. I tried to check the 'Is List' checkbox and I get the same error when saving

![custom action 4](https://github.com/FlutterFlow/flutterflow-issues/assets/120210391/aedf8a78-dc26-414a-8f50-8e0c28ce5fcf)

**Comment by aemelyanovff** [comment] 2023-09-22 20:03
Closing the issue. To summarize:
- You need to implement an action "On Reorder" to update the data source.
- The meaning of "Old Index" and "New Index" is this: `Implementations should remove the corresponding list item at oldIndex and reinsert it at newIndex.`. It's borrowed directly from [here](https://api.flutter.dev/flutter/widgets/ReorderCallback.html). I'll include it in the tooltip.
- [This document](https://docs.flutterflow.io/widgets-and-components/widgets/layout-elements/listview#reorder-list) explains how to implement that action.

**Closed by aemelyanovff** 2023-09-22 20:03 UTC
Labels: status: needs triage
