### ISSUE TITLE
Unknown Error with Custom Widgets

### ISSUE THREAD

**Issue by jcorn925** [FlutterFlow/flutterflow-issues#3325] opened 2024-07-06 01:33 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am getting the following error: Custom Widget: Unknown error compiling custom code. A common cause is a custom widget or action whose name in the code does not match the name provided in the editor.

This error was connected to a specific function which I deleted then recreated. The error went away for that function but re-emerged for a completely separate, unrelated function.

This tells me the error could be related to the index of the custom function in my list of functions, maybe.

### Expected Behavior

There shouldn't be any error related to my functions.

### Steps to Reproduce

Simply view the error and associated custom functions.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ehvHlvM91ofpE7c/Ab8FvmSQRIjs/RYInm9V+dAw0NZjtB+wLO+j+SGhVOLynf1VYeWeJ8X4I7sKMud7+GscVHxGIQ75A+JN1FxaVXke6R7rTBZO0e2hRM9hMI0Ce56COihJ4KthtLSEm7F6yIeusVibtJJzaDlg7Pf39DKfUpUqFLibNGzhmtmNecCfn

### Visual documentation

<img width="551" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/67557245/9992a50e-55e0-4422-bf6a-5b903b8c249f">

### Environment

```markdown
- FlutterFlow version: 4.1.65
- Platform: Web
- Browser name and version: Edge
- Operating system and version affected: Windows 11 Enterprise 22H2
```

### Additional Information

I can't deploy to testflight with the error present. Significant blocker

**Comment by msusviela** [comment] 2024-07-07 15:18
Hey @jcorn925, Thanks for your report, So sorry you are experiencing this issue. I was not able to reproduce this on a blank project, that's why I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. Thanks so much!

**Closed as not planned** 2024-07-08 18:22 UTC
