### ISSUE TITLE
On Data Change generates invalid code when using single document query and attempting to access the field of that query document

### ISSUE THREAD

**Issue by isegal** [FlutterFlow/flutterflow-issues#1329] opened 2023-08-22 20:22 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Invalid code is generated:

```
	"Undefined name 'myComponentRecord'.
Try correcting the name to one that is defined, or defining the name.
```

### Expected Behavior

It should be possible to access fields in the handler of On Data Changed

### Steps to Reproduce

1. Create a container component
2. Add a firestore query to container, of type: Query Collection, Single Document query. Add any filter.
3. Add a form field inside the container
4. Add an On Data Change action to the same component. Set the form field to a field of the query document from #2.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hcnfz5Fgod9c1rrUK/lahmU5JlN9RI0Nke57aCsofePrOpkAf8/7UFtUOd+/SlVXfU6JjngX/MmKkdr1O8cEHymYfJQ/z8xcVA7hTXOnRZeYEq63b3wnO8pYJkzD5rSw3CNQXdtscmAmw2eMHvCsaBHZGYT3OUQWROaoXdeK2SrDX1iXc2URm05KZDPz

### Context

Form fields only support "initial" value. It is impossible to update form fields as a result of "On Data Changed", even though FlutterFlow allows it, the code generated is invalid because the definition of the single document is place in an incorrect relative location, causing an undefined variable error.

### Visual documentation

<img width="305" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/4561505/43ce9d9d-9f0f-4710-9e3c-5a1efb3a5b3a">

<img width="970" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/4561505/1e044034-724b-4ec5-af90-06e303e1d253">

<img width="1496" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/4561505/c2511cd8-eae3-47eb-b7b3-f684ab2f0d41">

### Environment

```markdown
- FlutterFlow version: v1.1.97
- Platform: iOS
- Browser name and version: Native FF
- Operating system and version affected: all
```

**Comment by hariprasadms** [comment] 2023-08-23 12:23
Hi @isegal - Thanks for submitting the issue. I have tested the above steps. I can confirm that _On data change_ action is working as expected. It is not a bug.

The example is shown below. In real-time scenarios, I would advise using the app/page states in conjunction with the on data change to update the widget's status on the UI. You can always get in touch with the FF technical support team if you need more help. Thanks 

https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/8194ee61-b79c-466e-9e23-f1a9ed25ff26

**Comment by isegal** [comment] 2023-08-24 18:10
@hariprasadms 

At 0:03, the Set Form Field needs to have a field that is set from the cities document itself, not the hard-coded True value.
Hard-coded values work, but "set from variable" does not work if it refers to the same collection that is the source of the On Data Change event.

**Comment by aemelyanovff** [comment] 2023-08-29 21:21
@isegal Thanks for reporting the issue. You are right, it's a bug. It'll be fixed in the next update.

**Closed** 2023-08-29 21:21 UTC
Labels: type: bug, closed: fixed
