### ISSUE TITLE
Api call without internet connection breaks action chain on mobile

### ISSUE THREAD

**Issue by TeferiHero** [FlutterFlow/flutterflow-issues#1404] opened 2023-09-05 07:45 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using Api Calls in an action chain, if there is no internet connection on a mobile device, or the connection is lost in the middle of a Call, an Exception is uncaught and the action chain doesn't continue. I cannot detect whether the Api call has failed due to a broken internet connection, or do anything after that

### Expected Behavior

I expect to detect if an API call fails, to be able to react accordingly.
At least for the action chain to continue, so that the app doesn't break.
As per Flutterflow Forum
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/118672945/ed41ac26-cc42-464c-89b8-548ba383903a)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/118672945/5f15db1e-9928-46ac-af6c-c11b9f758ea7)

### Steps to Reproduce

1. Create an API call.
2. Create a new page
3. Create a button with following actions after clicking: Execute API call, then open a dialog.
4. Build APK, and launch on mobile device.
5. With internet on, click on a button and observe dialog opening
6. With internet off, click on a button and observe dialog doesn't open

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40l8j14ot1xMtD1r6JKflagmA5KVA8a5E4letraCosfZT2BLMcec/RVERuOLyoS1Flek60hWoW0/D7vYftLe07EyiufYRT+KhMZhXKIUG6aa6XFJWge3F8M9hjGBDD0cHUuBFdOsxsSiUi2DqMNdytUjTYQIzGIVcGD6/LZO4=

### Context

My app relies on making API call to retrieve user data when starting the app. Should the connection break, I have to recover from that, at least not get stuck at the loading screen

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/118672945/9e09cb45-a9fb-460f-9b6c-7ba59737fa40)
![Screenshot_20230905-092337](https://github.com/FlutterFlow/flutterflow-issues/assets/118672945/fc599be0-ddcb-4801-8a9c-0d14606259d6)
![Screenshot_20230905-092447](https://github.com/FlutterFlow/flutterflow-issues/assets/118672945/5a5260b0-0038-4ebd-9ab8-79efdbb5361b)
From Android Studio debug session
![Zrzut ekranu (5)](https://github.com/FlutterFlow/flutterflow-issues/assets/118672945/2128101b-310f-4482-86da-4429913ed116)

### Environment

```markdown
- FlutterFlow version: v3.1 released August 28, 2023
- Platform: Android
- Browser name and version:
- Operating system and version affected: Android 9
```

**Comment by hariprasadms** [comment] 2023-09-17 18:55
Hi @TeferiHero - Thanks for submitting the issue. At present FlutterFlow does not provide inbuilt handler to check the API response contains data or not based on an active internet connection. However, you can handle it by using custom code based on your needs. It can confirm that it is not a bug.

**Comment by joshua-ffio** [comment] 2023-09-21 03:04
Sub-issue/duplicate of https://github.com/FlutterFlow/flutterflow-issues/issues/1199

**Closed by joshua-ffio** 2023-09-21 03:04 UTC
Labels: closed: not a bug
