### ISSUE TITLE
Mac App - Sidebar disappear randomly

### ISSUE THREAD

**Issue by kicsijohn** [FlutterFlow/flutterflow-issues#560] opened 2023-03-02 12:07 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.

### Current Behavior

The sidebar disappears and appears randomly
![CleanShot 2023-03-02 at 12 47 03](https://user-images.githubusercontent.com/45784821/222423096-6fa4d4c9-dad5-4609-91d0-b49f6a6c619b.jpg)

### Expected Behavior

the sidebar doesn't disappear

### Steps To Reproduce

1. Open the mac app
2. open a project
3. change something on a page
4. if nothing happens open another app (for example: Chrome) and switch back to the Flutterflow app

### Bug Report Code

IT40jM/q4c5PmOZE7rr+KcJV+T45KWJ5a7gr0MFraCosfZT2BLMcec/RVERWOL3mSlZmIVqakWoW0635iNmSA/EVCAetb7p61Ktccg/McFi6MKaqFJWgeUZTHeJQCGqa5raZhxBQG7BiLyUB11zzN+yXEnLBJpDwIjMSD6/LZO4=

### Context

I always have to navigate to the home and back to see the sidebar again - and I can't use command+Z to redo changes because I lost them if I leave the project

### Additional info

https://user-images.githubusercontent.com/45784821/222423027-3d3d68ca-8ac9-4ca1-a7f0-2240bc21112a.mp4

### Environment

```markdown
- FlutterFlow version: v1.1.47 Flutter 3.7.3
- Platform: MacOS
- Operating system and version affected: macOS Ventura 13.2.1
```

**Comment by hariprasadms** [comment] 2023-03-02 13:59
Hi @kicsijohn - Thanks for reporting the issue. I tested this issue for more than 30 min working with mac version of FF. However, I did not notice this behaviour. It looks like very much random one. Please add more details when exactly you are seeing this issue. Thanks

**Comment by kicsijohn** [comment] 2023-03-02 18:47
Hi @hariprasadms I restarted my mac and after the app worked great for hours. Now happening again after I created a custom function on the web and then clicked on the app the "Custom functions need to be checked for errors. Click here to check for errors." message in the issues section

**Comment by bulgariamitko** [comment] 2023-03-04 19:37
I can confirm this bug

**Comment by agreaves** [comment] 2023-07-10 01:24
Hi @kicsijohn, thanks for the bug report. Unfortunately, I haven't been able to reproduce this issue even on larger and larger projects. I'm hoping this is fixed by now as this issue is a few months old and there have been various updates in both Flutter and FlutterFlow.

My best guess as to what is happening is that there is an issue with something being rendered on the page and this is causing layout issues which are dragging the builder down with it. My suggestion (if this occurs again) is to open the same page and web and observe its behavior to see if there are any issues there.

Closing for now as I am not able to reproduce but please let me know if you are experiencing this issue and have any new information on what triggers it. A new bug report code would be useful as well in this case because the current project linked the above code no longer exists.

**Closed by agreaves** 2023-07-10 01:24 UTC
Labels: type: bug, status: confirmed
