### ISSUE TITLE
[URGENT] Unable to set initial value for state field of type Enum

### ISSUE THREAD

**Issue by giladresisi** [FlutterFlow/flutterflow-issues#3265] opened 2024-06-27 15:48 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I created an enum and then created a page state field of type enum and chose my new enum type, however I couldn't set the initial value for this field - the selection remained "unset" even when I chose one of the values. Also, if I didn't check the "nullable" checkbox for this field and confirmed after I supposedly chose one of the values as an initial value - I immediately got an error saying that a non-nullable field must have a default value set.
This bug doesn't allow me to finish a new version for my users, which I already should've deployed yesterday but couldn't because of this bug.

### Expected Behavior

I expected to be able to select one of the values of this enum an initial value for this field.

### Steps to Reproduce

1. Create a new enum type
2. Create several values for it
3. Create a state field of this type within a page or a component
4. Try to select one of the values as the initial value for this field

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oz8r13ItOxLhc+KrAdfpVnSQ7Qkc3argo0MpBZywgfZzzBLN/fPfQPlVoZPWnSgl+eWC2p14ywfzOvuPpOMYoZBKcGZx++rhfFxfgRmajbpeTF7qOeHJQO99gI0CFy6ungSJAH/VtR00tw12mOeyRHwrbQJTUPWo8Sq/LZO4=

### Visual documentation

![Screenshot 2024-06-27 224519](https://github.com/FlutterFlow/flutterflow-issues/assets/6623700/2c9408e8-0386-41af-9f77-5d17f6a33a75)

### Environment

```markdown
- FlutterFlow version: v4.1.63+
- Platform: Web
- Browser name and version: Chrome 126.0.6478.127
- Operating system and version affected: Windows 11 Pro
```

### Additional Information

Solving this bug is urgent for my project and my users.

**Comment by Toninomex** [comment] 2024-06-27 16:22
Hello there, I am on more or less the same.

Support told me that Flutteflow is moving to an "improved" flutter version and since Tuesday we have all been expecting problems with the "states" (app, page, component) and math.

I think we need to ask for better communication between FF and the community because it the tell us about what might happen, we can be prepared instead of thinking the problem is on our side and loose tons of hours figuring it out.

**Comment by ignalauret** [comment] 2024-06-27 18:47
Hey @giladresisi thanks for your report. I've been able to replicate the bug and I see it as critical, I will send this so our Technical team can take care of it. Have a great day!

**Closed as not planned** 2024-06-27 21:00 UTC
Labels: status: confirmed, Bug

**Comment by leighajarett** [comment] 2024-06-28 11:07
We are working on a fix for this issue and hope to have something out ASAP. We're using this issue for tracking purposes: [https://github.com/FlutterFlow/flutterflow-issues/assets/144909175/a42ca919-7db0-4664-a9c3-e05d5f26bbc7](https://github.com/FlutterFlow/flutterflow-issues/assets/144909175/a42ca919-7db0-4664-a9c3-e05d5f26bbc7)
