### ISSUE TITLE
action editor white box bug

### ISSUE THREAD

**Issue by palmdeskApp** [FlutterFlow/flutterflow-issues#158] opened 2022-11-24 11:07 UTC
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
When termination is accidentally deleted, the entire box becomes white. it becomes difficult to work in that box. 

## Current behavior (required)
image attached. 

## Screenshots / recordings
Attached

## Your environment
Window 10, crome broswer.
![action flow editor bug](https://user-images.githubusercontent.com/117246043/203769278-f2dd96b7-1628-40d1-a0b2-bc6832589606.png)

**Comment by agreaves** [comment] 2022-11-29 02:08
Hi @palmdeskApp, can you please add reproducible steps to this issue? I need a bit more information as I'm currently unable to reproduce.

**Comment by palmdeskApp** [comment] 2022-11-29 03:06
I have not found the reproduction logic of this bug. I think deleted that terminator and a such a box appeared. I deleted entire actions and rebuilt it. But It wasted my few hours in rebuilding.

**Comment by agreaves** [comment] 2022-11-30 04:05
Ok, thanks for the info. It sounds like we're not able to reproduce this issue so I'm going to close it for now, but if you (or anyone else) encounters it again please reply to this issue with the bug report code for the widget in question. From there it should be easy to fix! 🙂

**Closed by agreaves** 2022-11-30 04:05 UTC
Labels: status: needs information, status: needs reproducible steps
