### ISSUE TITLE
FF docs - can't delete user

### ISSUE THREAD

**Issue by tinrunje** [FlutterFlow/flutterflow-issues#1077] opened 2023-07-05 11:37 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I don't know where to put this as it isn't a bug but the FF docs are incorrect.

To delete a user, the FF docs state that you first must "Logout" and then use the Firebase Auth "Detete User" action, the docs are here: https://docs.flutterflow.io/actions/actions/backend-database/firebase-authentication/delete-user. However, that doesn't make sense and it doesn't work. Even just using the "Delete User" action won't work unless the user has logged in very recently (so you cannot delete a user if it logged in a week ago). The following message will pop up:
![IMG_3785](https://github.com/FlutterFlow/flutterflow-issues/assets/52575319/fe846a5b-a547-4424-82d6-6cc466ccc1f2)

Weirdly, if you login and then delete the user, it will work.

However, this isn't intuitive at all... Users want to delete their account when they feel like it and not have to logout -> login -> delete. Looking into this, I found this great community post: https://community.flutterflow.io/c/discuss-and-get-help/delete-user-account. The post says that the action setup you need is:
1. Delete the user document for the authenticated user first 
2. Then delete the user via Auth action
3. Then log out the user via Auth action

And I can confirm this works somewhat okay... it deletes the user document for sure but still doesn't really delete the user from Firebase Authentication. 

The purpose of this Git post is for FF to update their docs so new users don't experience this as well.

### Expected Behavior

FF docs are correct and up to date.

### Steps to Reproduce

1. create page
2. create login/register
3. login 
4. leave account logged in for a day
5. try delete account using the FF docs method 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wkMmAuI92mOZE0K6JY+9VmSQWGDs+bec3l+1DYCs9f5CvOpYUec/6PlpWXdCrTUFYIWKcp14y0/OMvfD1DvYrHzmZG6JH/rhIcA3KRXKubLGTF7qBPHFtEeRgfGnE36e3hCUnWdBoW3giwE2hfdm9Qg3vNKb1DEQwSq/LZO4=

### Context

Users cannot delete account and are therefore contacting our customer support to delete accounts.

### Visual documentation

In the description above.

### Environment

```markdown
- FlutterFlow version: v3.1 (released June 29, 2023)
- Platform: MacOS Desktop
- Browser name and version: 114.0.5735.198 (Official Build) (arm64)
- Operating system and version affected: macOS Ventura 13.4
```

**Comment by hariprasadms** [comment] 2023-07-05 12:39
Hi @tinrunje - Thanks for sharing this observation. I have passed this information to document team to review and update it if required. Thanks

**Comment by tinrunje** [comment] 2023-07-05 17:15
> Hi @tinrunje - Thanks for sharing this observation. I have passed this information to document team to review and update it if required. Thanks

Thanks. Also please check if the process is correct as the delete user action still isn't completely functional.

**Comment by oengmengthong** [comment] 2023-07-06 13:51
For that case you can create custom action and create endpoint API at cloud function to access firebase_admin

**Comment by hariprasadms** [comment] 2023-09-20 11:26
Hi @tinrunje - I can confirm that, delete user full feature is working as expected. When delete user action is triggered, it deletes the authenticated user from firebase authentication and also associated documents from the tagged collection (Refer step 5 in the user doc).  I presume the issue is resolved to you. 

Let us know if this is the case,  i'll close the issue. Thanks

**Comment by hariprasadms** [comment] 2023-09-25 15:07
Hi, No recent activities in the issue. We presume you have resolved the issue. Hence closing the issue. Thanks

**Closed by hariprasadms** 2023-09-25 15:07 UTC
Labels: type: documentation, closed: not a bug, waiting for user response
