### ISSUE TITLE
URL change -> app not working 

### ISSUE THREAD

**Issue by valeriodipalo** [FlutterFlow/flutterflow-issues#3596] opened 2024-08-09 23:19 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am having troubles in changing the app url. I've tried doing it but it has led to problems in production. In particular, the url used is the right one when the page opens, but after the login goes to the url which was used before. To try to solve the problem I've unplublished and re-published the app and that has led to the whole app not functioning after the login. I'll need to change the url name and I would need some additional support to perform this task 

### Expected Behavior

Once i change the url, this stays the same troughout all the app pages 

### Steps to Reproduce

1. change url 
2. try the app in prod 
3. perform login 
4. receive error 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT9XiuflxIt1pbxY1872acAxnjgXH1s7auYrldZ+axAafY/qP5kqdcnRP1tpWbS/T2w7IWGN+XgK+ezLkc7+MeY5HxeWfLZm+c9ASQCVXTmXWpDUEs+CdGJ/J95XfGK45JmnkCJ+Os5aWF4s2GCMe97KYz/vMLnhOms/D+akCLzA+kqbAR7dFS9Z2RwNHkeMPdg2Sw6whaX/+a4QlI/S/ol8qBVXzoPSwtX1TBKTWVk=

### Visual documentation

The error is to notice looking at the url 

### Environment

```markdown
- FlutterFlow version: 4.1.81
- Platform:Web 
- Browser name and version: Chrome 127.0.6533.100
- Operating system and version affected: macOS Sonoma 14.4.1 (23E224)
```

### Additional Information

I'm trying just to change the url of my app. I have changed the domain name of the landing page and the whole branding, so it would be necessary to change the flutterflow domain name too.

**Comment by msusviela** [comment] 2024-08-10 00:53
Hi @valeriodipalo. I wasn't able to replicate from blank. <br>I entered your project, used the url that's on AppSettings -> Web publishing (I'm not putting here the URL because I don't know if you want to make it public). I see that you don't have a custom domain so the url is the one that finishes with .flutterflow.app. Then I created an account, navigated to the home, then I signed out and signed in again. The url for all those cases were the same. Tell me if i'm missing something.<br>Sometimes it can take a little time to deploy. 

Is it working properly for you now? If not, please let me know.

**Comment by valeriodipalo** [comment] 2024-08-10 01:46
Hi Micaela,

Thank you for your support. I'm experiencing an issue with the application
I'm developing. The problem occurs during the sign-in process. Here's a
step-by-step explanation:

   1. I've reproduced the error by changing the URL as shown in screenshot
   (1).
   2. When users attempt to log in from casewiz.flutterflow.app, using the
   Google sign-in button, they are redirected to prepwiz.flutterflow.app.
   3. I've attached screenshots to illustrate the issue:
      - Screenshot 2: The sign-in page with the original URL
      - Screenshot 3: The Google access page
      - Screenshot 4: The home page shown after Google sign-in (with
      different url).

As you can see, there's an unexpected change in the base URL during this
process. The application starts at casewiz.flutterflow.app but ends up at
prepwiz.flutterflow.app after sign-in.

Can you please help me understand why this URL change is happening and how
to prevent it?

P.S. I've removed the screenshot from the message as it doesn't allow me to
send it with them inside, if these are needed, can you let me know of a
better procedure to share?

Il giorno sab 10 ago 2024 alle ore 02:54 Micaela ***@***.***>
ha scritto:

**Comment by msusviela** [comment] 2024-08-10 02:16
@valeriodipalo, thanks for the quick response. I'm not seeing the screenshots, can you please upload them again? (I think it's because you probably responded by mail and maybe they were not recognized by the github thread).

From the bug report code you provided, the URL configured at web deploy is prepwiz.flutterflow.app. Can you confirm which one is the new URL? If the new is casewiz, I'll advice to put it again and redeploy. 

Please let me know which one is the new URL so I can send it to our internal team. They have the right tools to configure manually this.

**Comment by valeriodipalo** [comment] 2024-08-10 13:22
![1](https://github.com/user-attachments/assets/5c6ca204-f5a6-4bf0-b2c8-8472a6dc4782)
<img width="1792" alt="2" src="https://github.com/user-attachments/assets/9ba41db1-b268-46b3-8533-ca95b7d1f88f">
<img width="1792" alt="3" src="https://github.com/user-attachments/assets/86123d0d-f3dc-4bcf-9e8b-80bcd224e094">
<img width="1792" alt="4" src="https://github.com/user-attachments/assets/26ed54b7-e7c7-4e92-94c2-6bd41f533c68">
Here the screenshots I was metioning

**Comment by msusviela** [comment] 2024-08-10 14:55
Thanks! As for now It's redirecting me correctly:

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/cdf757f8-56d7-4a25-8d66-a3dd9e495336/035f58d7-6096-4873-82ba-5d2fa0fdd15f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jZGY3NTdmOC01NmQ3LTRhMjUtOGQ2Ni1hM2RkOWU0OTUzMzYvMDM1ZjU4ZDctNjA5Ni00ODczLTgyYmEtNWQyZmEwZmRkMTVmIiwiaWF0IjoxNzIzMzAxNzIwLCJleHAiOjMzMjkzODYxNzIwfQ.V-2vCLm-EWFPnPmZxjdZj90G32sznWPP7P1sKhRo65Q " alt="image.png" width="1032" height="611" />

I also entered your project though the bug report code and now the correct url is showing to me (before i was shown the prepwiz one).<br><br>Can you check if it's working for you? I mentioned this to the team so they can fix it manually, but please let me know if it's working for you now

**Comment by valeriodipalo** [comment] 2024-08-11 11:02
I'm still having the problem on my end. We can isolate the problem to the Google Sign-in button and functionality. When I sign-in with google from my laptop using different browsers (Chrome and Safari) or when I access to it through my phone (using Safari) as soon as the google log-in is completed i get redirected to the old url (prepwiz.flutterflow.app) instead of the desired one (casewiz.flutterflow.app). 

This represents a major problem as with new updates the users who will access trough Google, will be redirected to a previous version of the app. 

I'd like your support to solve the problem for the Google Sign-In use case. 
Thank you !

**Comment by msusviela** [comment] 2024-08-12 10:52
I tested now and could replicate the issue. I sent it to the team so they can check your case, I'll let you know as soon as I have an answer

**Comment by valeriodipalo** [comment] 2024-08-12 10:54
thank you very much Michaela, I'll wait for updates

Il giorno lun 12 ago 2024 alle ore 12:52 Micaela ***@***.***>
ha scritto:

**Comment by valeriodipalo** [comment] 2024-08-13 12:55
Hi Micaela, any update on the problem resolution ? I'm planning to launch
soon and this represents a major problem

Il giorno lun 12 ago 2024 alle ore 12:53 Valerio Di Palo <
***@***.***> ha scritto:

**Comment by msusviela** [comment] 2024-08-13 13:19
Hi @valeriodipalo. Our team is looking into it

**Comment by valeriodipalo** [comment] 2024-08-17 21:37
Hi Micaela, It is more than 4 days since your last message. I'm really
looking forward to launch my app and not working sign in represents a huge
blocker for it. Could you please update me with the current status to solve
this issue?
Thanks, Valerio

Il giorno mar 13 ago 2024 alle ore 15:19 Micaela ***@***.***>
ha scritto:

**Comment by valeriodipalo** [comment] 2024-08-19 18:46
Is there any update on the issue?

Il giorno sab 17 ago 2024 alle ore 23:37 Valerio Di Palo <
***@***.***> ha scritto:

**Comment by rzambroni** [comment] 2024-11-01 18:45
Hello,

Apologies for the delayed response! Our team attempted to replicate this issue on blank projects but couldn't reproduce it. This suggests it's unlikely to be a bug within FlutterFlow itself; it may be more related to configuration specifics in your project.

For help in resolving this type of issue, reaching out to our support team might be the best route. You can contact them either by email at [support@flutterflow.io](mailto:support@flutterflow.io) or via the in-app chat for direct guidance.

Thank you!

**Closed as not planned** 2024-11-07 15:48 UTC
Labels: status: can't reproduce
