### ISSUE TITLE
App Details Fields Missing Variable Selector

### ISSUE THREAD

**Issue by kiptoomm** [FlutterFlow/flutterflow-issues#5125] opened 2024-12-17 13:22 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The [Mobile Deployment docs](https://docs.flutterflow.io/deployment/deploy-for-environments#mobile-deployment) state that we can: 
> create [environment values](https://docs.flutterflow.io/testing/dev-environments#use-environment-values) for the package name and set it into Settings & Integrations > General > App Details > Package Name. This ensures that when you switch environments, the package name changes and you can submit separate builds to the App Store and Play Store.

However, FlutterFlow's App Details field for setting the Package Name currently seems to only accept a hard-coded value. There should be a way to select the value dynamically from the variable selector, no?

The same issue affects the "URL Scheme" option under App Settings -> App Details -> Routing & Deep Linking. I wold like to use slightly different schemes for my various app 'flavors' e.g. `myapp-dev://myapp.com`, `myapp-stg://myapp.com` and `myapp://myapp.com` for dev, staging and production builds, respectively. 

### Expected Behavior

It should be possible to set the package name and URL Scheme dynamically using the "Set Variable" selector/wizard, like this:

<img width="491" alt="Screenshot 2024-12-17 at 16 08 49" src="https://github.com/user-attachments/assets/587b3521-d007-4e1f-a313-3947d1b73568" />

### Steps to Reproduce

1. Create an environment value for Production, Staging and Development to represent package names e.g. com.myapp, com.myapp.stg and com.myapp.dev
2. Go to App Settings -> App Details. Set the Package Name value.

It is not possible to set the desired package name to an environment value defined in App Settings -> Dev Environments

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kz/Hqx89godtF0JP1be5aiWQ7Jkx+TLJEpu0bWUkbGO/4OpkAeM7OQElCTtyzaHxiB1X/inEfzM7Rkt/XOsY5EzmZfqpTz6tcaBPPbFOhboyKCrW0Z0EkL+VUJ26z36TYuh1CA/phclIf2HGIB/C9QT+Cf9qOYwx5e6fDbOY=

### Visual documentation

<img width="491" alt="Screenshot 2024-12-17 at 16 08 49" src="https://github.com/user-attachments/assets/ee9c6eca-9aa2-466d-8d65-92d7065318df" />
<img width="825" alt="Screenshot 2024-12-17 at 16 14 24" src="https://github.com/user-attachments/assets/074b9ff6-08b2-45ea-b441-afd38512c5a9" />
<img width="579" alt="Screenshot 2024-12-17 at 16 14 13" src="https://github.com/user-attachments/assets/50e66fce-7a24-4696-8d40-fc4f3445221b" />

### Environment

```markdown
- FlutterFlow version: v5.0.0+ released December 16, 2024
- Platform: Web
- Browser name and version: Google Chrome Version 131.0.6778.140 (Official Build) (arm64)
- Operating system and version affected: macOS 15.0
```

### Additional Information

I would like to publish dev, staging and production builds to their respective Alpha, Beta and Production tracks on the Google Play Store

**Comment by Alezanello** [comment] 2024-12-17 15:46
Thank you so much for bringing this to our attention! I’ll share this with our engineering team right away so they can work on a fix. We appreciate your patience and support!

**Comment by leighajarett** [comment] 2024-12-17 20:52
Sorry you're so right! We actually just pushed the feature a few hours ago to change the package name by deployment, and we made it a dropdown instead of the original plan with variable binding. <br><br>You can see the updated documentation with details! Let me know if you run into any issues. <br><br>The URL scheme is not something we current support but I can see how that would be valuable so I will add it to our backlog. Closing this out since it is not a bug. Thanks so much for reporting!

**Closed as not planned by leighajarett** 2024-12-17 20:52 UTC
Labels: status: confirmed, Bug

**Comment by kiptoomm** [comment] 2024-12-19 10:00
> Sorry you're so right! We actually just pushed the feature a few hours ago to change the package name by deployment, and we made it a dropdown instead of the original plan with variable binding. You can see the updated documentation with details! Let me know if you run into any issues. The URL scheme is not something we current support but I can see how that would be valuable so I will add it to our backlog. Closing this out since it is not a bug. Thanks so much for reporting!

All sounds good, thank you @leighajarett! Look forward to the URL scheme solution when you get to it
