### ISSUE TITLE
Query Filtering is not working

### ISSUE THREAD

**Issue by ganadevprajapathy** [FlutterFlow/flutterflow-issues#3560] opened 2024-08-05 23:12 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Query filtering using authenticated user record or any other parameter is not filtering anything. The entire list is available without any filter.

### Expected Behavior

Query filtering to work as its supposed to!

### Steps to Reproduce

Create a new client record under a user.
Try to filter the client records for that user.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTjPHl7ZdOsfVG+KXyccBKjiYXM0MdXOczitVEew4bCIj4ELMLds/7SBNtTdCzaHx+AleYiT4F0Pz6vd/XG/kCAwWBQaFz1pBcaxPPbEe5R4iNPKueQ0ZfEeRUGnKj17eNoQhQJstfLVIN3V2MIe6/cz2Cf9qOYwx5e6fDbOY=

### Visual documentation

This is the query
![image](https://github.com/user-attachments/assets/2fdb6774-3afc-416a-88c1-8a2365439b7a)
This is the result
![image](https://github.com/user-attachments/assets/dcef45d4-50d3-4cc4-88f7-4f8e140231f8)

Only clientname with value "insider" should be visible. But every single record is visible.

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.79+ released August 3, 2024
- Platform: 3.22.2
- Browser name and version: Chrome, 127.0.6533.72
- Operating system and version affected: Windows 10
```

### Additional Information

Please help resolve the issue asap.

**Comment by msusviela** [comment] 2024-08-06 13:25
Hey @ganadevprajapathy, Thanks for your report, So sorry you are experiencing this issue. I was not able to reproduce this on a blank project, but if it is replicable on yours,  I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. Thanks so much!

**Closed as not planned** 2024-08-09 22:21 UTC
Labels: closed: support request
