### ISSUE TITLE
White space between SliverAppBar and the body of the application.

### ISSUE THREAD

**Issue by irfan-ahmed-1982** [FlutterFlow/flutterflow-issues#695] opened 2023-03-31 07:48 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

There is a white space between the  SliverAppBar and the body of the app. This white space can be seen only in the real devices, Test and Run Modes works fine.
![cigwvx2cagoscn96kzbn22a7gvvk](https://user-images.githubusercontent.com/118018023/229055082-bf24100b-b988-428a-a8d2-4da727e98576.jpg)

![image](https://user-images.githubusercontent.com/118018023/229055221-27b1a634-a3d6-4659-8fcf-448daf37ae09.png)

### Expected Behavior

It is expected that there is no gap between the app bar and the body of the app.

![image](https://user-images.githubusercontent.com/118018023/229055599-5d2b2bb4-5cf9-4594-911b-2e8ba6624137.png)

### Steps To Reproduce

1. Create a new Page.
2. Activate the SliverAppBar.
3. Use default settings.
4. Turn Off Pinned.
5. Turn On Floating and Snap.
6. Leave Expanded Height and Collapsed Height blank
7.  Toolbar Height and Add Bottom Section shall be 56 each.
8. Leave others unchanged as shown in the image below:
![image](https://user-images.githubusercontent.com/118018023/229056905-78243dca-4cb4-49c8-ad0f-3ed048197a97.png)

### Bug Report Code

IT4OivHq6ot1mNtA1rrqdcBsgSQvQkA/U5ZM0+5DSUg0CK3NGu4AeM7TTEpvZr2qS29UMWeGgn0x/Pfqjc7+U8ErHwSeQKJ6z6VySg/JVjuuV7KsDqi7fW1SL99MIECj4Lu7nxNDCMxqR1I+2WauHfPJTgnbQ7G3DWsBO8+LJdeK2SrDX1iXc2URm05KZDPz

### Context

Looking a way to remove the white space between the SliverAppBar and the body of the application.

### Additional info

![image](https://user-images.githubusercontent.com/118018023/229057326-5c148bb2-1349-44a9-ae3a-bdbd79a62815.png)
![image](https://user-images.githubusercontent.com/118018023/229055599-5d2b2bb4-5cf9-4594-911b-2e8ba6624137.png)
![cigwvx2cagoscn96kzbn22a7gvvk](https://user-images.githubusercontent.com/118018023/229055082-bf24100b-b988-428a-a8d2-4da727e98576.jpg)

### Environment

```markdown
- FlutterFlow version: 3.7.3
- Platform: Windows 
- Browser name and version: Google Chrome Version 111.0.5563.146 (Official Build) (64-bit)
- Operating system and version affected: Windows 11
```

**Comment by hariprasadms** [comment] 2023-03-31 09:22
Hi @irfan-ahmed-1982 - I can't reproduce the issue. I have checked your project and I can't see the issue where it is exactly.  
However, FF editor is not altering the basic feature of Sliver AppBar widget. I suggest double check the page layout design and see if there is any hidden padding for widgets causing the issue. Otherwise, it should working fine. 

A quick video can be more helpful to see the issue.Pleas share the details.

**Comment by irfan-ahmed-1982** [comment] 2023-03-31 09:24
@hariprasadms Have you checked with real device? As this has no problem in Test Mode and Run Modes I have also mentioned in my original Post.

**Comment by hariprasadms** [comment] 2023-03-31 09:34
@irfan-ahmed-1982 - Can you share a quick video of the issue in real device please?

**Comment by irfan-ahmed-1982** [comment] 2023-03-31 09:40
Please have a look here:

https://user-images.githubusercontent.com/118018023/229085068-32e26305-931d-48e5-8451-5bea12286c59.mp4

**Comment by hariprasadms** [comment] 2023-03-31 09:40
@irfan-ahmed-1982 - Is this the gap you are talking about in the issue. 

https://user-images.githubusercontent.com/17435678/229085204-f2a56236-4cf0-4465-8b5b-26539a2771d3.mov

**Comment by irfan-ahmed-1982** [comment] 2023-03-31 09:42
@hariprasadms I think yes.

I have a screenshot from my run mode which is perfectly fine: I need my app to look like below screenshot from Run Mode:

![image](https://user-images.githubusercontent.com/118018023/229085759-e1778474-0ec7-42b5-be19-b7bccc1632b6.png)

**Comment by hariprasadms** [comment] 2023-03-31 09:45
Thanks for sharing the details. I will investigate the issue and decide the status accordingly.

**Comment by hariprasadms** [comment] 2023-03-31 10:27
Hi @irfan-ahmed-1982 - I think I found a solution for the issue. The page where you have sliver app-bar, disable the safe-area from scaffold widget and build the app. It should fix the space issue what you are seeing. See below. 

I have tested it in iOS but not sure how it looks in Android. Give a try and let me know. Thanks

https://user-images.githubusercontent.com/17435678/229095764-ade749d7-7b42-4d14-ac80-584313e80744.MP4

**Comment by irfan-ahmed-1982** [comment] 2023-03-31 10:37
Disabling the safe area might not be the best solution for solving the white gap issue between a SliverAppBar and a non-sliver widget in the body.

The safe area is a margin around the edges of the screen that ensures content is not obscured by system user interfaces such as the status bar, navigation bar, or the home indicator. Disabling the safe area may cause the content to be partially obscured by these system UI elements, which is not a good user experience.

If you notice your 2 videos, the first one with Safe Area enabled, the Home indicator is just below the content of the Body, whilst the second video you can see the home indicator is overlapping the Body content.

**Comment by hariprasadms** [comment] 2023-03-31 10:58
For now, you can take this solution as a work-round for the issue. We look into the issue in detail and see what fix we can do keeping safe area enabled. Thanks

**Comment by irfan-ahmed-1982** [comment] 2023-03-31 12:17
**Option 1:** Per the flutter documentations, it is required to add the sliver-widget in the body, you have 2 options for adding that:

[https://docs.flutter.dev/cookbook/lists/floating-app-bar](url)

![image](https://user-images.githubusercontent.com/118018023/229116913-516e82da-6431-4a5d-8ec6-ffc3ca79e834.png)

**Option 2:** Alternatively you can add "SliverToBoxAdapter".

Wrapping the Column widget inside a SliverToBoxAdapter widget will make it a sliver that can be used in a CustomScrollView. This should eliminate the white gap between the SliverAppBar and the Column.

**Option 3:** "NestedScrollView" widget can be used instead of a CustomScrollView. The NestedScrollView widget allows to have both a SliverAppBar and a non-sliver widget in the body, without any white gap issue.

**Comment by jakepalancalpp** [comment] 2023-04-27 21:25
I turned off safe-area and created this custom action to check if device has option for safe area (I'm only releasing on iOS so just used custom action bool to toggle a 34pi container. My project doesn't call for top padding so I didn't include):

`bool hasBottomPadding(BuildContext context) {
  final EdgeInsets padding = MediaQuery.of(context).padding;
  return padding.bottom > 0.0;
}`

**Comment by wenkaifan0720** [comment] 2023-05-15 15:40
Hi all. This issue will be fixed in the next update. Basically, we need to turn off the top safe area of the Scaffold's body if a sliver app bar is set.

**Closed by wenkaifan0720** 2023-05-15 15:40 UTC
Labels: type: bug, status: confirmed, closed: fixed
