### ISSUE TITLE
Rebuild Containing Page not working

### ISSUE THREAD

**Issue by lcoppa** [FlutterFlow/flutterflow-issues#3509] opened 2024-07-29 21:59 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a custom weekly calendar. Clicking to the next/prev week buttons changes parts of the page (first level component) but not the subcomponents within that. I set the "Rebuild Containing Page" in the button actions, when updating the week number stored in an appstate variable.
When going to adifferent page (tab) and back to this one, the calendar is correctly rebuilt

### Expected Behavior

All components in the page should update when clicking on the week navigations buttons, including the second-level components

### Steps to Reproduce

In my project lov-eat-l34bs3, go to CalendarWeekView page and click on previous/current/next week buttons above the week view

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTjMmB0It2ocsA+KrPY+1Fhio4CUMcWOdEl+tuZwgbIoznBuw2e/elblVtZMOraVNfeU7+vEwxzN7sj9/xF+05BxKtfqJ9+s5UEw70e2iWbpibPIe8fnZBJ+xQfH6C3Im0kSJTOsVhR3gE2FyuJN6WbAjDFOu/Zwh9f6PHaOI=

### Visual documentation

https://github.com/user-attachments/assets/55d8bdea-0137-46dc-8edd-67c7b58bb974

### Environment

```markdown
- FlutterFlow v4.1.78+ released July 26, 2024
Flutter version is 3.22.2
- Platform: web
- Browser name and version: chrome 126.0.6478.185
- Operating system and version affected: macos sonoma 14.5
```

### Additional Information

This is not good from a UX point of view. It's not terrible for the mvp state my app is in, but it's not acceptable as release version. It's also a bit worrying that, unless I'm doing something wrong, a basic need like refreshing a page does not work.
Thank you very much team, keep up the amazing work you are doing!

**Comment by Alezanello** [comment] 2024-07-31 13:59
Hello!

I wasn't able to reproduce the issue. Could you create a new blank project with just this widget to see if the behavior is different? This will help us determine if the problem is project-specific.

Best regards,<br>Azanello

**Comment by lcoppa** [comment] 2024-07-31 15:53
Hi, I can try but it's a pretty complex page. Did you try directly from my project and it works as expected?
thank youLuca 
    Il mercoledì 31 luglio 2024 alle ore 15:59:43 CEST, Alezanello ***@***.***> ha scritto:  
 
 


Hello!

I wasn't able to reproduce the issue. Could you create a new blank project with just this widget to see if the behavior is different? This will help us determine if the problem is project-specific.

Best regards,
Azanello

**Comment by Alezanello** [comment] 2024-08-06 13:47
Hello!<br><br>Sorry for the late response, did you tried to set the Rebuild to "All Pages"?

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/7a4c122e-4d88-44dd-a84e-e5da7460db87/bd9273ed-ea87-4fc7-8d27-c0d0e1111fee?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83YTRjMTIyZS00ZDg4LTQ0ZGQtYTg0ZS1lNWRhNzQ2MGRiODcvYmQ5MjczZWQtZWE4Ny00ZmM3LThkMjctYzBkMGUxMTExZmVlIiwiaWF0IjoxNzIyOTUyMDY4LCJleHAiOjMzMjkzNTEyMDY4fQ.2Xpx_cmFhx9Hxpa8aa8FhuWt0KirR7_Q9ObGPkKud5k " alt="image.png" width="336" height="364" />

**Comment by eavendano** [comment] 2024-08-10 05:31
Hello Team!

I have the very same issue, but here is my version.

I have a modal, when I open the modal, I update a record in Supabase and then Update App State so I can see the record reflected. I tried both Rebuild All Pages and Rebuild Current Page and I cannot get the update to trigger. No error on the console either, and in the network tab, I cannot see any new API calls to "refresh" the state.

Here are the Steps:

Step #1
Slide my list item
![support1](https://github.com/user-attachments/assets/cc53f0da-78b8-48de-850d-29de4b375094)

Step #2
Select Edit [Editar]
![support2](https://github.com/user-attachments/assets/1cd3599e-0ccf-4ac1-ba25-f1a1f7f5a417)

Step #3
Update from 50 to 90
![support3](https://github.com/user-attachments/assets/aa1b2f25-fe49-47be-b791-5230890da7fc)

Step #4
The list item still says 50 (Trust me it is a different screenshot)
![support4](https://github.com/user-attachments/assets/73107f20-2441-40f6-ab25-519e0301dc28)

**Comment by eavendano** [comment] 2024-08-11 00:04
I fogot to add that my Flutterflow version is:
`FlutterFlow v4.1.81+ released August 6, 2024
Flutter version is 3.22.2`

**Comment by Alezanello** [comment] 2024-09-03 12:55
Hello,

I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by eavendano** [comment] 2024-09-03 13:38
It still persists, I tried it this weekend and it still not rebuilds my containing page

**Comment by tmpsantos** [comment] 2024-09-09 13:22
It was not fixed, I can confirm on v4.1.84. In the generated code, the callbacks called for updating the page apparently are empty, which makes this action a no-op in this case.

**Comment by tmpsantos** [comment] 2024-09-09 13:50
The root cause is because the dynamically generated component is not being created with `wrapWithModel` where `updateCallback: () => setState(() {})` is set with a reference to the current page. This issue should not affect a components used outside a dynamically generated list.

**Comment by Franco98404** [comment] 2024-09-09 15:28
Hello, I'm facing with the same problem

**Comment by lcoppa** [comment] 2024-09-09 15:49
I also confirm the issue still persist as of today

**Comment by tmpsantos** [comment] 2024-09-09 16:04
There is a workaround for this issue that was mentioned before. You can add to your action chain an "Update App State" that doesn't even update anything, but triggers a "Rebuild All Pages". This will work at the cost of a performance impact if you have many pages open.

![image](https://github.com/user-attachments/assets/42bf5150-a090-4621-8bcf-4bb50006517a)

**Comment by Franco98404** [comment] 2024-09-09 17:50
> There is a workaround for this issue that was mentioned before. You can add to your action chain an "Update App State" that doesn't even update anything, but triggers a "Rebuild All Pages". This will work at the cost of a performance impact if you have many pages open.

Unfortunately, in my case doesn't work :(

**Comment by eavendano** [comment] 2024-09-09 19:23
Rebuild All Pages doesn't work for me neither

**Comment by lcoppa** [comment] 2024-09-10 07:38
Neither it does fo me

**Comment by Alezanello** [comment] 2024-09-10 18:18
Hello everyone,

Thanks to tmpsantos' feedback, I was able to replicate the issue, and using the "Rebuild All Pages" option seems to fix it. However, could you please share a short video explaining the logic behind your rebuild process or how it is being triggered?

Alternatively, if you could share the Bug Report Code and specify the exact page and component that isn’t working, that would be really helpful. This would allow us to identify any patterns or potential issues. It seems like the bug might not be limited to the "Rebuild Containing Page" function being empty; it could also be related to the generated code. This information would greatly assist in identifying similar bugs or multiple issues across different scenarios.

Thank you!

**Comment by eavendano** [comment] 2024-09-14 04:54
https://github.com/user-attachments/assets/c4e7d2d8-b8cc-4406-8582-2e40d868c431

Modals may also be part of the problem.

**Comment by eavendano** [comment] 2024-09-14 04:56
@Alezanello ⬆️
Bug Report Code: IT4si/Lqw5FNoblE7rruY8J7/Sk6Nn44R40wscp/bxIgGIDzPOw+ZPXsSE1vXt+mTAl+fUSmmnwe09GOvtrlNew6aA2aGqpn/5FqVQ3hXnKmUZOBBbmZOXZCEcFQIW7C0KbYrREmPulfSU4k61+mCtm8ShTcNb7GIndISq/LZO4=

**Comment by Alezanello** [comment] 2024-09-19 19:17
Hello everyone!

With the help of @tmpsantos, I've been able to replicate the issue. I'll be forwarding this ticket to the engineering team for further investigation and a possible fix.

Thank you for your patience!

**Comment by mackaby** [comment] 2024-09-27 06:19
I'm having the same problem when using the new widget builder as parameter if I pass in components that has state changes. In this case not even rebuilding all pages work.

**Closed as completed** 2024-09-27 18:25 UTC
Labels: status: confirmed, Bug

**Comment by rubenmeerman** [comment] 2025-01-16 08:22
I'm having this issue also as of January 2025. Neither Rebuild Containing Page nor Rebuild All Pages will rebuild the page the component is in. This seems like bug. Does anybody have a fix? You can Navigate to the same page but that is super clunky and jarring to the eye.

**Comment by finnalli27** [comment] 2025-03-10 17:20
Also having this same problem as of March 2025. Specifying 'Rebuild current page' for a component doesn't seem to trigger the 'On page load' action of the page it's being used.

**Comment by lcoppa** [comment] 2025-03-10 17:50
@victoriahuang1 I'm not sure why you closed the issue, it was never resolved. I still have the problem, and it looks like I'm not the only one.
Could you please reopen it?

thank you
Luca

**Comment by lcoppa** [comment] 2025-05-31 15:04
Hi @wenkaifan0720, did you have a chance to look into this? I was hoping the fix would have bene one of the "little things" fixed in v6, but the issue persists.
Any idea on the timescale to get it fixed? Currently, the components are not re-initialized when using "reuild current page", i.e. the OnInitialization trigger actions in the component are not re-executed; so, the component state is not updated correctly 

thank you
Luca

**Comment by Amit-Dagan** [comment] 2025-10-24 09:30
@Alezanello  
I experience the same issue 
it a shame that a small bug like this completely ruins flutterflow for me 

i wil try to have a work around but its just annoying
