### ISSUE TITLE
Supabase View schema in FF built incorrectly

### ISSUE THREAD

**Issue by dhurbhat** [FlutterFlow/flutterflow-issues#574] opened 2023-03-04 14:07 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.

### Current Behavior

The dart code generated for a Supabase View incorrectly makes the Primary key column nullable.  This causes build failures.

### Expected Behavior

Primary key fields in Supabase are NON NULLABLE... therefore, I expect the FF dart file to not make it nullable.

Example: if `id` is a primary key then, FF generates 
`  String? get id => getField<String>('id')!;
`
This is wrong and as noted, causes BUILD FAILURES.

### Steps To Reproduce

1. Create a Supabase View on table that has a non-null primary key
2. Generate FF schema
3. Look at the code generated and see if dart field for Primary key is nullable

### Bug Report Code

NONE

### Context

BUILD FAILS in FF

Exporting the code to Github, fixing the table file and then compiling in Android Studio is only way to deploy.

### Additional info

NOTE - This along with exact project, page, errant line of code and fix was reported to support over a week ago.  **NOTHING** got done.

### Environment

```markdown
- FlutterFlow version: v3.1 Flutter 3.7.3
- Platform: MacOS
- Browser name and version: Chrome N/A
- Operating system and version affected: N/A
```

**Comment by Pepino-GR** [comment] 2023-03-06 16:06
Hi dhurbhat,

if I try this, I get the code "String get id => getField<String>('id')!;" and it seems to be o.k.

So, I cannot reproduce the issue. Can you give me more information?

**Comment by dhurbhat** [comment] 2023-03-06 17:24
@Pepino-GR 

- Did you use a Supabase view created from a JOIN ?

I have a view that looks like this:
`create view MyView as
select "TableA".*, 
"Places".address, "Places".bedrooms, "Places".baths, "Places".city, 
"Places".state, "Places".on_campus, "Places".zip
from "TableA" left outer join "Places" on "TableA".place = "Places".id;
alter view MyView owner to authenticated;`

Then try it in FF - 

Also - note this was working through Jan and most of Feb - then something changed couple of weeks ago and it started to fail.

You may also want to check which browser... I am using Chrome... Safari has another blocking issue (previously reported).

**Comment by Pepino-GR** [comment] 2023-03-07 09:49
Thank you for your information. With this configuration, I can reproduce the issue. Thanks for reporting.

**Comment by dhurbhat** [comment] 2023-03-09 04:02
Any ETA on a fix?
I cannot build :( in FF

**Comment by agreaves** [comment] 2023-03-15 22:59
Hi @dhurbhat, could you please include a Bug Report Code? It's required for all issues and is incredibly helpful to debugging issues. You can generate it by right clicking anywhere in the widget tree.

**Comment by dhurbhat** [comment] 2023-03-16 02:52
IT4shc/qy5dgocNG1brUK/lR/CoQJlg/bb8wscp/bxIgGIDzPOw+ZPWkVFFtYN/mdGxUfESmmlMG0PDJkYTLA/kqG06abLZawZABUQvgfH2lUZOBCsyOYXAlM/FjG0eO37WjmBF+CLBoWVEs2l2qOt+Xf3LZN5u3IndISq/LZO4=

This is what was generated.

**Comment by dhurbhat** [comment] 2023-03-23 02:32
Hello? @agreaves / @Pepino-GR any updates?

It's been weeks (3 weeks on Github and more than 3 weeks with FF Support prior to that) that I'm not able to build from within FF :(

**Comment by aemelyanovff** [comment] 2023-04-04 22:24
@dhurbhat Sorry for the slow turnaround on this.

Fields being nullable in generated code is not a bug - FlutterFlow doesn't know which view fields are nullable because Supabase API that we use doesn't return this information. On its own it should not cause build errors.

Builds are failing for your project because of a bug in `ToggleIcon`. The fix will be released in the next update.

**Closed by aemelyanovff** 2023-04-04 22:24 UTC
Labels: type: bug, status: confirmed

**Comment by dhurbhat** [comment] 2023-04-11 11:14
@aemelyanovff - thanks for the update.
AND your notes don't make sense to me.

- you mention nullable in generated code is not a bug - maybe.  **BUT** the point was that this SHOULD NOT be nullable as this field is a primary key in the DB Table.
- you also state that Supabase generated code was not the cause for build failure - but `ToggleIcon` was... **STRANGE** that making the field in Supabase record nullable does not cause build failures in Android Studio but does in FlutterFlow.
