### ISSUE TITLE
Chat Flow causes error

### ISSUE THREAD

**Issue by heloWelo** [FlutterFlow/flutterflow-issues#2708] opened 2024-04-12 13:08 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I've imported the Chat & Group Chat flow. Set the rules and permissions etc. but I get the error message: Run mode-only notification: Firestore Security Rules Error on ListView: Missing or insufficient permissions.

In the console, I get: Uncaught TypeError: J.cy(...).af is not a function
    at Object.ep (main.dart.js:201:24)
    at Object.dn (main.dart.js:5423:3)
    at bbT.$1 (main.dart.js:110523:19)
ep @ main.dart.js:201
dn @ main.dart.js:5423
$1 @ main.dart.js:110523

### Expected Behavior

Start chatting

### Steps to Reproduce

1. Add flow
2. Select Chat & Group Chat Bubble
3. Set permissions
4. Run
5. Go to Chat page, try to add a Chat with the plus symbol Top right (there are none)
6. Error appears after loading the page

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Oz8r634p2sdtJ+Kryb8FKnSQWH1w6RLxM1NYbEE0bCO7NG4gIZfTBXE9uOP25dghqOU6koDkx09aMm9z1U+1fIT+tbqI++IdiVBbjQnOVM5/QOpG8RkRUGshhCEi+57W3ughNNrFoWEY912byNe+sTjLZK5zPDDEzMf2JIrLXrgfuQ0SLb3kNh1JWeC/v

### Context

Project cannot be rolled out. I want to use the Chat flow.

### Visual documentation

<img width="260" alt="tbrun_error" src="https://github.com/FlutterFlow/flutterflow-issues/assets/4135681/3e1e656f-29d9-4d82-8134-5a6251801080">

### Environment

```markdown
- FlutterFlow version: 3.19.1
- Platform: Web
- Browser name and version: Edge Version 123.0.2420.81 (Official build) (64-bit) & Chrome Version 123.0.6312.122 (Official Build) (64-bit)
- Operating system and version affected: Windows 11 22631.3447
```

**Comment by paulperez-dev** [comment] 2024-04-12 19:36
Hi @heloWelo, thank you for your report! The error you are getting is related to the Firebase rules that are set. How they should be configured varies from project to project, so I suggest you to go one by one, taking your time to understand and refine each rule.

Here is a post from our community that may help you: [https://community.flutterflow.io/ask-the-community/post/run-mode-only-notification-firestore-security-rules-error-on-home-z9FoNYTuCSs1XUe](https://community.flutterflow.io/ask-the-community/post/run-mode-only-notification-firestore-security-rules-error-on-home-z9FoNYTuCSs1XUe) (hope it helps you!)

I'm going to close this issue since this tracker is for reproducible bugs.

**Comment by heloWelo** [comment] 2024-04-13 03:29
I've given every permission possible. I don't fully trust FlutterFlow documents or 'tutorials'. They are so often incomplete or just plain wrong. I've done as you've suggested and think this is a bug, despite your comments.

**Closed** 2024-04-17 11:30 UTC
Labels: closed: not a bug
