### ISSUE TITLE
Translation/i18n broken: translation keys duplicated, random fields filled or overwritten. SHOWSTOPPER!

### ISSUE THREAD

**Issue by HeikoKanzler** [FlutterFlow/flutterflow-issues#720] opened 2023-04-04 10:10 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Since the last update, the localization seems to be broken: on Buttons, the key for the translation is the same on all buttons. It looks like that with introducing the themes, always the last key in inserted on all buttons on code generation:

```
text: FFLocalizations.of(context)
    .getText(
  'omtra9ed' /* LOGIN */,
),

text: FFLocalizations.of(context)
    .getText(
  'omtra9ed' /* REGISTRATION */,
),
```

**Update: appears to be a problem with drop downs as-well**

Clearing the theme etc. doesn't help.

Example: the last added button text is applied to the logon and registration buttons
![CleanShot 2023-04-04 at 11 42 48](https://user-images.githubusercontent.com/5279575/229758698-4094cda3-c82a-4dd2-a0f4-59f6a65b300b.jpg)

Example: random buttons added on a separate page, the LAST button text is applied to (not all exported buttons). I believe only "themed buttons" are affected, however: removing the theme from the button doesn't help, even deleting and adding the buttons in doesn't help:
![CleanShot 2023-04-04 at 11 51 43](https://user-images.githubusercontent.com/5279575/229758734-ccb79bcf-7a6c-4ccd-9457-46bf17e53126.jpg)

Drop Downs are affected as well, in this example the drop down says country (there's another country selector below), but should say "role":
![CleanShot 2023-04-04 at 13 19 20](https://user-images.githubusercontent.com/5279575/229776298-910c59b1-676d-415e-a5ca-ebc2418cb9d9.jpg)

### Expected Behavior

All buttons have their own text / translations.

### Steps To Reproduce (updated)
1. Create new project
2. Add two languages (english, german...)
3. Add two buttons to the project, name them clearly different, don't bother to translate them
4. Create a new themed widget (Button, just change the color)
5. Assign the theme to both buttons
6. Rename them again (that's already a bug, the button text should stay), again, don't bother to translate them
7. Run the project: both buttons have the same text from the last button.

### Bug Report Code

ITFXjPHlvIVIrsBE0KrPK8BFliowFnIca+YZhOsbbw4aF4CsEZoDbuvRPhNDXf26T25UI2eJ/To03M7yjoTMUfpeNQiEQ5Q7/pNqaArJVTmiRKq2CJa8PXZ5P9tgf266yJ2rnRB+Iup0S3cuig/GSw==

### Context

I want my button texts back ;-)

### Environment

```markdown
- FlutterFlow version: v1.1.57
- Platform: Mac
- Operating system and version affected: macOS Ventura 13.2 (22D49)
```

**Comment by hariprasadms** [comment] 2023-04-04 21:58
Hi @HeikoKanzler - In run mode, to see the language changes on widget texts, language selector widget should be added ( See below video showing when button text is same but different for different languages). 

https://user-images.githubusercontent.com/17435678/229930819-fe9c8c4a-7cd0-4ec7-a302-111d9ff70a90.mp4

Below video showing, buttons with different text and it changes according to language selection. 

https://user-images.githubusercontent.com/17435678/229931516-36bab720-7f14-4914-bd23-dc8fa3749276.mp4

How re you trying to control the language display in run mode ? If you do not have language control widget to change the language, button texts displays same for all buttons as per primary language selected in the Languages settings page.

**Comment by HeikoKanzler** [comment] 2023-04-05 06:32
1. I am using the language widget provided 
2. It was working as expected and the bug was introduced with the last update (i believe it has something to do with the new Themed Widgets)
3. I can see the bug in the exported code: the translation key is simply wrong, it's the same across widgets, see my examples taken from my splash screen. (See "current behaviour").

**Comment by hariprasadms** [comment] 2023-04-05 12:48
I still not able to reproduce with above details. It looks like specific to project issue. However I can mark this as bug. Developer can confirm the status. 

Developers note - I did try the steps with both default and themed widgets. Not able to re-produce the issue. It sounds more like a project specific issue. Please have a look.

**Comment by HeikoKanzler** [comment] 2023-04-05 13:25
Hi Hari, I just tried it again, and its easy to reproduce:
1. create new project
2. add two buttons to the project, name them clearly different
3. create a new themed widget (Button, just change the color)
4. assign theme two both buttons
5. rename them again (that's already a bug, the button text should stay)
6. run the project: both buttons have the same text from the last button.

![CleanShot 2023-04-05 at 15 21 16](https://user-images.githubusercontent.com/5279575/230093939-5812cdbe-93d1-45af-8d1e-33f69383b825.jpg)

**Comment by hariprasadms** [comment] 2023-04-05 13:27
Thanks for the details @HeikoKanzler. Defiantly it helps to fix the issue. Thanks

**Comment by HeikoKanzler** [comment] 2023-04-05 16:33
The whole feature is broken, even the language editor doesn't work properly now, if you change the values of one field, the value of another field is changed, too:
https://user-images.githubusercontent.com/5279575/230145351-7bc8f2e3-1b55-45d5-a43c-e63f668e0797.mp4

**Comment by HeikoKanzler** [comment] 2023-04-07 12:16
Question: how can I get my existing project running again? I used the previously created test project to remove the extra languages to have at least one working language in the project, but this results into a compile error and makes the app unusable. I am obviously not going to try that now on my main project.

![CleanShot 2023-04-07 at 13 53 05](https://user-images.githubusercontent.com/5279575/230607129-14f6ea39-b49e-4c15-8eba-b8ac0b0e295c.jpg)

**Comment by wenkaifan0720** [comment] 2023-04-07 14:45
Hi @HeikoKanzler. I believe this will be fixed in our next update. You will still need to refill the text after you've selected a theme widget style, but the translation should be working again. I understand this is not the ideal flow, we are still looking into how we can improve the flow (see this related issue: https://github.com/FlutterFlow/flutterflow-issues/issues/708).

As for your compilation error, it looks like your project is missing the `primaryBtnText` color. If you define it in the color settings page, the project should compile. This custom color was added by default previously, but we have removed it since it does not follow our naming convention. But existing project should still keep this color. Are you trying to use it in custom code? If not there might be some issue. If you don't mind, could you share with me the bug report code?

**Comment by HeikoKanzler** [comment] 2023-04-07 19:26
Thanks for replying.
I haven't added anything manually to the project, it's the simple one used to demo the bug.

After the last update today, I now took a copy of the app, deleted the additional languages and keep working on a single language version to get the already finished stuff working again.

Hopefully the translation will work again soon and then I have unfortunately to translate the whole app again.

/heiko

**Comment by wenkaifan0720** [comment] 2023-04-10 13:56
In our next update, we also allow you to specify whether you would want to sync the text in a theme button/text/textfield style with the actual widget, so you don't need to redo the translation. 

I'll close this issue for now as it should be fixed in our next update.

**Closed by wenkaifan0720** 2023-04-10 13:56 UTC
Labels: type: bug, status: confirmed, closed: fixed

**Comment by benjaminathlan** [comment] 2023-05-14 13:37
This error is still appearing in my project
