### ISSUE TITLE
api call charset=utf8

### ISSUE THREAD

**Issue by salvanin** [FlutterFlow/flutterflow-issues#3431] opened 2024-07-18 15:14 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm making an API call and everything works fine in the test API call, but when I switch to test mode, it shows an error 'invalid media type expected "/" - charset=utf8.
![Captura de tela 2024-07-18 104012](https://github.com/user-attachments/assets/3ce21ed4-021a-498e-a05d-946635db8c46)

### Expected Behavior

The response as per the image below

![image](https://github.com/user-attachments/assets/13a650c5-8781-469c-a288-cb6ce4229219)

### Steps to Reproduce

The rest of the project works fine, only in the api call that presents the error

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Kl8nfz4xNrsNc+Krqde9VgikvJlg/bZJFlup+EBYjIojxG7YAQszOSBJaZ+m+Sgo3f2GkpHEx0NnIuMzIN8cqOSWeGK46yKh2SDv/Tj2XVabROrqsOnd6HtpKChDC4Z2znxBdHPFoSVI77Dn7Pu+9EnPvHabqDDAnJcmYFILIs3PuQ0SLb3kNh1JWeC/v

### Visual documentation

![image](https://github.com/user-attachments/assets/67ccea4e-37c1-4455-87bf-6df0a90a37cb)
![image](https://github.com/user-attachments/assets/e7e50d35-d592-4cc5-829d-aa3e911d4121)

### Environment

```markdown
- FlutterFlow version: 4.1.73
- Platform:web
- Browser name and version: Chrome  126.0.6478.127
- Operating system and version affected: w11
```

**Comment by msusviela** [comment] 2024-07-19 11:04
Hey @salvanin, Thanks for your report, So sorry you are experiencing this issue. I was not able to reproduce this on a blank project, but if it is replicable on yours, I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. Thanks so much!

**Closed as not planned** 2024-07-19 11:04 UTC
Labels: status: needs triage, closed: support request
