### ISSUE TITLE
Custom domains instructions not working correctly

### ISSUE THREAD

**Issue by joziasmartini** [FlutterFlow/flutterflow-issues#1535] opened 2023-09-26 16:10 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The domain instructions for DNS configuration are not working correctly. 

It's probably because of the string split algorithm implemented in the background.

### Expected Behavior

I expect that when I type www.website.com.br it gives me the correct instructions for DNS configuration.

### Steps to Reproduce

1. Go to settings and integrations
2. Enter in web publishing
3. Inside custom domain, type any compound tld
4. For example, www.website.com.br or www.website.co.cc
5. The instructions for the www subdomain are wrong
6. The instructions for the dns configuration are wrong

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40ivLq25NPm8BE1a6Jcfpajic5JWk4argZm8F7aCsofePrOpkAf8/7UFtUOOmkSmxEIFr8mmcX/MnHkvPTIfY3IT6dUaE/zc9AcALgJWSnMp/SPpS3b0RSDedmGhGhy7ugkxN+XdBoR3w66lOIJeeRVjHaCYDsIlcBGOaoXdeK2SrDX1iXc2URm05KZDPz

### Context

Connect a custom domain. I was able to figure it out, but it was really confusing.

### Visual documentation

I can't provide an image because I have only one custom domain disponible in my account.

The domain is being used in a production project.

Also, maintainers, please don't change the domain these days in my personal project.

We will do a presentation in a university and it needs to be working in the next days.

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Web
- Browser name and version: Chrome 108.0.5359.124 (Official Build) (64-bit)
- Operating system and version affected: Ubuntu 22
```

**Comment by staceyeloff** [comment] 2023-10-06 11:57
I have the same issue. 

Domain is Ideationtostartup.co.za and flutterflow recognizes it as a subdomain.

The configuration settings don't work either.I have also tried using @ instead of the name given by flutterflow and it still does not work. 

See below

![Screenshot 2023-10-05 212121](https://github.com/FlutterFlow/flutterflow-issues/assets/147159227/d9d631db-0a19-4191-9490-7cf9b07215bd)

![Screenshot 2023-10-05 212052](https://github.com/FlutterFlow/flutterflow-issues/assets/147159227/19a1815c-b122-4200-8cd7-629b00280b2f)
![Screenshot 2023-10-05 212121](https://github.com/FlutterFlow/flutterflow-issues/assets/147159227/fe428944-8c4e-4199-bf5e-865619bd134d)

**Comment by davidflutterflow** [comment] 2023-10-06 12:16
@hariprasadms We troubleshoot this in support and seems there is an issue on our end with domains like .xx.yy
Could you please prioritize this

**Comment by aemelyanovff** [comment] 2023-10-10 16:33
@joziasmartini Do you mean that instead of `www.website` the name should be `www`? If no, please elaborate what you mean by "The instructions for the www subdomain are wrong".

@staceyeloff If `@` doesn't work, can you try leaving the name blank? The exact way to configure it depends on your registrar. After that, check if the A record shows in an [online DNS checker](https://www.nslookup.io/domains/ideationtostartup.co.za/dns-records/). Note that DNS changes take time to propagate, sometimes several hours.

**Comment by joziasmartini** [comment] 2023-10-10 16:52
> @joziasmartini Do you mean that instead of `www.website` the name should be `www`? If no, please elaborate what you mean by "The instructions for the www subdomain are wrong".

No, I mean that when I type www.website.com.br, the www subdomain configuration message right below the input goes into an error too. It's a string split error.

**Comment by joziasmartini** [comment] 2023-10-10 17:22
> @joziasmartini What do you mean "goes into an error too"? I don't see errors when I type this.
> 
> <img width="1139" alt="Screenshot 2023-10-10 at 2 01 17 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/92294640/aa14d1ad-4f2f-4f4d-92b0-80dc755c1a4d">
> 
> BTW if you only want `www.website.com.br`, uncheck "Also `www.www.website.com.br`".

I thought it was strange to give an user the option to www.www... but that's ok if you do not feel there is a problem.

**Comment by staceyeloff** [comment] 2023-10-10 18:22
@aemelyanovff I have tried leaving it blank, using "@" and also the name flutterflow gave me and left each for 12 to 24 hours and it still does not find the dns records. I have even used another empty domain with the .co.za extension at the end and it also did not find the dns records. The configuration works fine when using a straight extension but has a problem with extended extensions

**Comment by aemelyanovff** [comment] 2023-10-10 19:08
> > @joziasmartini What do you mean "goes into an error too"? I don't see errors when I type this.
> > <img alt="Screenshot 2023-10-10 at 2 01 17 PM" width="1139" src="https://user-images.githubusercontent.com/92294640/274001707-aa14d1ad-4f2f-4f4d-92b0-80dc755c1a4d.png">
> > BTW if you only want `www.website.com.br`, uncheck "Also `www.www.website.com.br`".
> 
> I thought it was strange to give an user the option to [www.www](http://www.www)... but that's ok if you do not feel there is a problem.

Got it. We can consider hiding this option for domains starting with `www.` but I wouldn't call it a bug though.

**Comment by aemelyanovff** [comment] 2023-10-10 19:12
> @aemelyanovff I have tried leaving it blank, using "@" and also the name flutterflow gave me and left each for 12 to 24 hours and it still does not find the dns records. I have even used another empty domain with the .co.za extension at the end and it also did not find the dns records. The configuration works fine when using a straight extension but has a problem with extended extensions

I see... Then I suggest reaching out to the support of your registrar.

Long story short, there must be an `A` record mapping `ideationtostartup.co.za` to `34.136.28.237`. The details of how to do it depend on your registrar. You can use [this link](https://www.nslookup.io/domains/ideationtostartup.co.za/dns-records/) to check if the record exists. If nslookup can't find it, then FlutterFlow won't be able to find it either.

**Comment by aemelyanovff** [comment] 2023-11-22 21:27
Closing as not a bug.

Additionally, in the next update we'll change the way we display instructions for connecting domains like `.co.za`.

**Closed by aemelyanovff** 2023-11-22 21:27 UTC
Labels: type: bug, status: confirmed
