### ISSUE TITLE
Dismiss Dialog not closing corectly

### ISSUE THREAD

**Issue by youdjin2** [FlutterFlow/flutterflow-issues#2696] opened 2024-04-10 14:24 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

it started in the last two days out of the blue. when i try to dismiss a Custom alert dialog by clicking outside the dialog box, the page navigates back by itself either to the previous page or to homepage. No navigation actions are present, just a simple dismiss action. its very frustrating because it does it each time a record is added or edited to a list from a custom dialog window with a form in it.

### Expected Behavior

Zxpected behavior is to just close the dialog. 

### Steps to Reproduce

Add a new record to list.
save the record.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXlsmAz4Z2ssRE15DUdsB4gWIwGUALa+dI0tZ+TQ0jF5D4BJkLO+P7VxdoUsSzaHxEJWH/kk8G0fT5hdmeIccFBy6tUbo9zqt5ExPPbH6XaJeYCqq8e3MnDZ5VGWaX4cPY3BNRPfVaW3hk11yYeeqvHj6Cf9qOYwx5e6fDbOY=

### Context

Its frustrating that the dialog doesn;t behave as normal. Just close and thats it.

### Visual documentation

no

### Environment

```markdown
- FlutterFlow version: latest
- Platform: Web
- Browser name and version: Edge
- Operating system and version affected: Windows
```

**Comment by paulperez-dev** [comment] 2024-04-10 20:19
Hi @youdjin2, thanks for your report! I noticed that you are closing the dialog using an action. Dialogs automatically have the dismiss behavior, if you add it again it will end closing two times (first it closes the dialog, the second 'closes' the page and navigates back).<br><br>Can you please remove the closing action and let me know if it works as expected?

**Comment by youdjin2** [comment] 2024-04-10 20:50
Hi, thanks for checking, however my situation is this: when i hit the 3 dots menu of a row, i open a custom menu with Edit and Delete buttons. Now if choose Edit, the normal behavior of this dialog would be to self close, right? and open another custom dialog with the edit Form. well according to what you saying its not selfclosing, so this is why i put an Action to Close it. I put another Action to Close the form after submit, otherwise how would the dialog know that it needs to close? So Close Action on the Dialog with Form, and close Action on dialog with Menu. Anyway i already tried everything, removing the action on both, adding one by one, and behavior is the same. So please elaborate what is the correct action to close both of these dialogs correctly without navigating to another page.

**Comment by youdjin2** [comment] 2024-04-10 20:59
ok, i found the culprit, it was the close Action on the actual 3 dots that was causing this behavior, however the Menu dialog is still not closing(even if it has the close action) after opening the form dialog.

**Comment by paulperez-dev** [comment] 2024-04-10 22:04
@youdjin2 Glad to hear that! In that case, you can try to manually close the Menu Dialog before showing the Form Dialog. Let me know how it goes.

**Comment by youdjin2** [comment] 2024-04-10 22:11
it doesn't close, i see it in the background of the form. i tried enabling Non blocking, however it made the edit button non functional, i mean when i click it it does nothin. Doesn;t open the form dialog.

**Comment by paulperez-dev** [comment] 2024-04-10 23:15
@youdjin2 I was no longer able to reproduce the issue on your project. Were you able to close the first dialog before showing the second?

**Comment by youdjin2** [comment] 2024-04-10 23:35
still not

**Comment by paulperez-dev** [comment] 2024-04-19 01:47
Hi @youdjin2, can you please replicate the issue on a blank project and share the bug report code?

**Comment by paulperez-dev** [comment] 2024-04-23 22:19
Closing this issue since we haven't heard back from you, thanks!

**Closed** 2024-04-23 22:19 UTC
Labels: closed: other
