### ISSUE TITLE
Notification message pops up with the message; Flutterflow version out of date (description; You are on an older version of flutterflow than one of your collaborators. Please refresh the page to use the latest version.)

### ISSUE THREAD

**Issue by Danjeey** [FlutterFlow/flutterflow-issues#346] opened 2023-01-11 18:23 UTC
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
No notification message should pop up even after refreshing the tab

## Current behavior (required)
Notification message pops up even after refreshing the page which stops me from accessing anything on the platform

## To Reproduce (required)
After refreshing the tab and working for approximately 3 minutes the notification pops up
.

### Bug Report Code (required, generate from Widget Tree)
Not applicable

## Context (required)
I can't work on the platform at all

## Screenshots / recordings
![flutterflow bug](https://user-images.githubusercontent.com/122471296/211885782-90b9d306-3965-4278-9c8b-e2cfe622ce26.JPG)

## Your environment

* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome
* Operating system and version (desktop or mobile): Windows 10

**Comment by hariprasadms** [comment] 2023-01-24 10:39
Hi @Danjeey - Thanks for sharing the issue details. Could you please confirm, you still facing this issue. 
I suggest try to use incognito mode of your browser and see if this issue still can persist. And also while refreshing try to do a hard refresh ( Ctrl, Shift and the 'R' key ) and if this can help. Let me know how it goes. Thanks

**Comment by hariprasadms** [comment] 2023-02-07 16:55
Hi @Danjeey - Thanks for posting this issue.
I'm just looking at this issue and found that it is a quite old one. Sorry for not picking the issue for debugging on time. However, as we got few latest updates on FF since this issue raised and no follow up on the issue, I believe the issue is resolved for you. Hence I am closing the issue for now. If the problem persists yet we can re-open the issue and start investigating. Thanks

**Closed by hariprasadms** 2023-02-07 16:55 UTC
Labels: status: needs triage
