### ISSUE TITLE
Logged in users cant use any textfiled in app

### ISSUE THREAD

**Issue by khomya** [FlutterFlow/flutterflow-issues#1164] opened 2023-07-25 17:05 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I didnt change anything in project, but now users cant use any textfield! 
Now users cant use any fileds - phones, emails, names, comments...

in Androin and in iOS - the same. Fields not working!
on web version - the same!

### Expected Behavior

users should be able to use textfields

### Steps to Reproduce

I dont know what happened

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wkfHlsIZ2xOFY+KXqdcFv+SAWCDp/aJ0/lu4aRis8I4jyO5YUSMzBUFFWTLzgYH9DPk6WoDgKxvfqiuHhVPUqZE6afLpP1ZFUaA7NUXKiM5SLPLm7fW1fGZtWfVzAy6aKkRB4PultS1o13U2QOu+XcA7qCb2wIUcnAcibJdeK2SrDX1iXc2URm05KZDPz

### Context

Users cant use App

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/2369704/eb655395-0e53-4a0a-aef6-85b59f69c283

### Additional Info

https://github.com/FlutterFlow/flutterflow-issues/assets/2369704/8485e2a3-cfe1-4a42-87b1-3487aeed7fb2

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: MacOS
- Browser name and version: Chrome Version 115.0.5790.102 (Official Build) (arm64)
- Operating system and version affected: MacOS 13.4.1
```

**Comment by khomya** [comment] 2023-07-26 11:52
I checked a lot of situations - the problem only appears for logged users.
i tested on pages with stack and every other widgets... if page is accessible by not logged user - then he can use TextField.
Logged Users - cant use textfields

In my video it is recorded: before user logged in - textfields are working.
After login - textfields not working/

**Comment by khomya** [comment] 2023-07-26 14:28
let me add you to TestFlight group - and you will use it and check.

**Comment by khomya** [comment] 2023-07-26 14:34
Or you can try website https://georgiatennis.ge from Android or iOS device.
And see the authorization goes OK, but once you logged in - you cant use textfields.

I tested on several iOS and Android devices.
My users write to me and they say that they cant use textfields.

**Comment by khomya** [comment] 2023-07-26 14:46
>>>Can you please confirm how it is working in Android and also if you could try to test in one or two latest iOS devices would be great.
I uploaded first video - its Android.
And I tested on iPhone 12 (2nd video), ipad mini 6, iphone 14

**Comment by khomya** [comment] 2023-07-26 14:48
you should get an invitation to testflight! I added you.

**Comment by khomya** [comment] 2023-07-26 15:34
in Google console in IAM & Admin I found this:
<img width="1090" alt="Screenshot 2023-07-26 at 19 32 31" src="https://github.com/FlutterFlow/flutterflow-issues/assets/2369704/e0a01419-820a-48c4-9842-bf4175d147d9">
Refreshed 3 days ago.
At that time i encountered this problem with logged users!

**Comment by khomya** [comment] 2023-07-26 15:37
<img width="1365" alt="Screenshot 2023-07-26 at 19 35 52" src="https://github.com/FlutterFlow/flutterflow-issues/assets/2369704/97366fa9-49a2-498c-b647-265cc22603f0">
And I have a lot of "bulbs"

"There are no permissions being used for Firebase Authentication Admin for firebase-adminsdk-alltn@georgia-tennis*** Remove this role to clean up your policy. Analysis is based off of the last 90 days."

**Comment by khomya** [comment] 2023-07-31 09:37
https://github.com/FlutterFlow/flutterflow-issues/assets/2369704/1afd555b-910b-4418-a56b-dad03f459f70

I also cant use the Dropdown search.

**Comment by khomya** [comment] 2023-07-31 09:42
And BTW the week passed since this bug!
I didnt get any response.
And now I get letter that the day of payment is near.
I couldnt use my APP or the FLUTTERFLOW for this week. I dont want to pay for this. I want a refund!

**Comment by sbis04** [comment] 2023-08-03 04:49
Hey @khomya, so sorry for this huge delay! But this issue was very project specific, and was really hard for us to reproduce. I think it's happening specifically because of the way the custom nav bar is being used (more on this as follows).

There can be two ways to fix this issue:

1. The reason why this issue is happening in the first place is the combination of custom nav bar + checking for keyboard visibility on every page. The easiest fix would be to just **remove** the keyboard visibility check on the nav bar in **every page** (and this should definitely work, I've already tested it):

<img width="2046" alt="Screenshot 2023-08-03 at 9 51 23 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/43280874/08d2921d-7196-451a-9e65-f8f27a99d4e0">

2. The second way is to enable **Replace Route** inside the navigate action that's set on each of the Nav Bar IconButtons. 

<img width="2045" alt="Screenshot 2023-08-03 at 10 08 56 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/43280874/3c05d206-a913-4db7-a075-76b0236a849c">

(But one thing to note here, by having this enabled users won't be able to just back and go to the previous nav bar selected page, they need to use the nav bar buttons to switch pages.

We will definitely dig into this issue deeper, in case there is a better solution so that you can use your app the same way it was actually configured. But while we look into that, these are the two options that you can try.

> **A more technical explanation of this issue (in case someone with technical knowledge of Flutter wants to understand the issue):** Flutter navigation works like a Stack, so whenever to navigate to a new page it just adds the page as a stack (doesn't remove the previous page). Only when you go back from a page it actually gets removed. This issue was occurring because they was a keyboard visibility checker stream running in the background, which was active even you you navigate to a new page. And, this was causing conflict with the new keyboard visibility stream created on the new page -- eventually resulting in this huge issue!

**Comment by khomya** [comment] 2023-08-08 14:58
Well!!!!!
The first method helped!!!
sbis04 - thank you very much!

**Comment by sbis04** [comment] 2023-08-12 03:30
No problem! I will close this issue for now.

**Closed by sbis04** 2023-08-12 03:30 UTC
Labels: type: bug, status : project specific
