### ISSUE TITLE
Order by optional field causes the documents without this field to be filtered out

### ISSUE THREAD

**Issue by halvorot** [FlutterFlow/flutterflow-issues#386] opened 2023-01-22 13:57 UTC
## Expected behavior (required)
I would expect that if I add "order by" to a backend document query that it would have no effect on which elements are filtered out and not. I would expect that the items that do not have the field I order by would end up at the bottom of the list. Or ideally that I could choose if the elements should appear before or after the values that have the value set.

## Current behavior (required)
The current implementation filters out elements that do not have this field set. My use case is that I have a collection of documents that have an optional field event_date. Which means some documents have this field and others don't (i.e. null value). When i do a backend query and order by this event_date, only the documents with the event_date set appear and the others are filtered out.

## To Reproduce (required)
1. Create a collection of documents with one of the fields being a datetime/timestamp
2. create some documents with this datetime field set and some without 
3. add a backend query for the collection and list the documents ordered by the datetime field
4. observe that the documents that do not have the datetime field set will not appear

### Bug Report Code (required, generate from Widget Tree)
IT4ozMrqx5BOseFK0L6JccBKjSQ4Ql9+bZIalcpBZzUYF5SuCLMqY8mnPhBuTdeoY29Ef2KMp14xwdaOiPPxN+4oHz6CG75T+roJdgGXJVGmRpvfU/HUACkbeacOQSj6

## Your environment

* Version of FlutterFlow used: v3.0 January 20
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by yoheisoito** [comment] 2023-01-31 14:46
Hi @halvorot,

Thanks for raising this issue.
Current behavior is the expected behavior as also described in firebase documents.
To quote: "An orderBy() clause also filters for existence of the given field. The result set will not include documents that do not contain the given field."

I am closing the issue now as it is not a bug, but please feel free to reopen to ask further questions on this.


https://firebase.google.com/docs/firestore/query-data/order-limit-data?hl=en

<img width="793" alt="Screen Shot 2023-01-31 at 23 45 54" src="https://user-images.githubusercontent.com/115172813/215792259-4b64e515-5865-43c1-853d-c75e356ab1af.png">

**Closed by yoheisoito** 2023-01-31 14:46 UTC
Labels: status: needs triage
