### ISSUE TITLE
Custom function string comparisons are not working correctly

### ISSUE THREAD

**Issue by wednesdei** [FlutterFlow/flutterflow-issues#598] opened 2023-03-13 06:19 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I've written a custom function to parse out a code, and a state value from a URL. The state value is equal to the userID. When I try to compare the UserID to the State value, FF is saying that they don't match; however, they do match, so I'm not sure what's up. 

I thought I might be comparing the wrong types; however, I've tested the code on dartpad.dev and it works perfectly. You can checkout the code here: 

https://dartpad.dev/?id=82b41deac5f9ec34da9428afdc466f08

Here is my code in FF. 

When I use the values: 

 String tokenCode =
      'https://www.myurl.com/return?state=JvAdZxJquIQLvQFatAg0mpWbo5S2&code=7-Dwzv6fXqVsG3JSgvi-NQjdm9gpRw';
  String uid = 'JvAdZxJquIQLvQFatAg0mpWbo5S2';

the function returns 'fail' :/ 

Any ideas? 

````
import 'dart:convert';
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:timeago/timeago.dart' as timeago;
import '../../flutter_flow/lat_lng.dart';
import '../../flutter_flow/place.dart';
import '../../flutter_flow/custom_functions.dart';
import '../../backend/backend.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../../auth/auth_util.dart';

String getCode(
  String tokenCode,
  String uid,
) {
  /// MODIFY CODE ONLY BELOW THIS LINE

  // parse variable length URL string for value after the text 'code='
  Uri uri = Uri.parse(tokenCode);
  String state = uri.queryParameters['state']!;
  String code = uri.queryParameters['code']!;

  if (state == uid) {
    return '$state and $code';
  }

  return 'fail';

  /// MODIFY CODE ONLY ABOVE THIS LINE
}
````

### Expected Behavior

The string comparison between uid and state should be true, and return the code value as it does in dartpad.dev here: 

https://dartpad.dev/?id=82b41deac5f9ec34da9428afdc466f08

### Steps To Reproduce

1. Create new custom function.
2. Create two string arguments:

- tokenCode
- uid
3. Pase the code provided above into the custom function. 
4. Test the code using the values here: 
 String tokenCode =
      'https://www.myurl.com/return?state=JvAdZxJquIQLvQFatAg0mpWbo5S2&code=7-Dwzv6fXqVsG3JSgvi-NQjdm9gpRw';
  String uid = 'JvAdZxJquIQLvQFatAg0mpWbo5S2';
5. FlutterFlow says that state and uid don't match, but they do.

### Bug Report Code

There are no bug codes in Custom Code section.

### Context

I can't do a comparison.

### Additional info

I don't think its needed, but let me know.

### Environment

```markdown
- FlutterFlow version: latest
- Platform: web
- Browser name and version: chrome latest
- Operating system and version affected: windows 11 latest
```

**Comment by ParentPass** [comment] 2023-03-15 01:33
![ffbug2](https://user-images.githubusercontent.com/127899451/225180906-79d056ba-1c08-4653-8989-b8c05d2e60b6.png)

I'm facing a similar issue. I think the problem is in the functions parameters, after testing with simple functions like this in the screenshot

**Comment by visan-marius** [comment] 2023-03-15 12:56
Yup same. getting the famous Hello World.

**Comment by organicnz** [comment] 2023-03-17 10:33
Hi @wednesdei. Thank you Chris for submitting the issue :)

Hm, I'm running into this problem right now. Could you if you are on the same version of FF? :)
As far as I know, there shouldn't be a problem :)

![image](https://user-images.githubusercontent.com/4765090/225879941-94801c9a-808c-4a33-9c26-9ec77edef37a.png)

**Comment by agreaves** [comment] 2023-03-22 02:05
Hey @wednesdei and all! Thanks for the bug report. Apologies for forgetting to update this thread, it should have been fixed as of last Thursday's deploy. Closing this for now but please let me know if anyone is still experiencing this issue!

**Closed by agreaves** 2023-03-22 02:05 UTC
Labels: status: needs information, status: can't reproduce
