### ISSUE TITLE
Regex bug

### ISSUE THREAD

**Issue by vinivilhegasdev** [FlutterFlow/flutterflow-issues#1376] opened 2023-08-29 02:42 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm trying to apply a regex expression to allow (#.## or ##.## or ###.##) as an input. This is the regex: ^\d{1,3}(\.\d{1,2})?$ But it's not working..

### Expected Behavior

Allowing #.## or ##.## or ###.## as an input.

### Steps to Reproduce

1. Create a text field
2. Try to implement a custom regex
3. Put ^\d{1,3}(\.\d{1,2})?$ or another one you want.
4. Test.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Ok/Lqx8pgod9c1rrUK/lahmU5KW4jULxMjut+SUsYNZfNGu4Iec/eUFZuZry6dGxcemajpGYK/Pfqv9jmUcEnAwysf7pBzcxIUgrxZHytM7avOrqVfW1fN9lMBWKM15iN3yZ7PupuSXwD71ymJt+XHzTsQ5DPPVYFJs6LJdeK2SrDX1iXc2URm05KZDPz

### Context

I've tried to implement regex express in my app and after be in contact with the support they confirmed it's a bug. In the 'valorPedidoMontarEntrega' field under 'Valor total do pedido' section in the page CriarPedido. I'm trying to apply a regex expression to allow (#.## or ##.## or ###.##) as an input. This is the regex: ^\d{1,3}(\.\d{1,2})?$ But it's not working..

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/143469975/4582d2a3-2e3c-43e1-a76a-3335693ef6ed

### Environment

```markdown
- FlutterFlow version: v1
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: Windows
```

**Comment by hariprasadms** [comment] 2023-08-29 08:49
Hi @vinivilhegasdev - Thanks for reporting the issue. This issue is related to #1308. This issue should be fixed once it is fixed.

**Comment by vinivilhegasdev** [comment] 2023-09-08 16:43
any updates?

**Comment by agreaves** [comment] 2023-09-16 23:59
Hi @vinivilhegasdev, closing this as a duplicate of #1308, which I have just resolved. This is due to the incorrect trailing `$` in the Regex (please see the original issue for more details). Thanks!

**Closed by agreaves** 2023-09-16 23:59 UTC
Labels: type: bug, status: confirmed
