### ISSUE TITLE
Bugs for number of document in Firebase Data Manager

### ISSUE THREAD

**Issue by sangkyy94** [FlutterFlow/flutterflow-issues#313] opened 2023-01-03 01:46 UTC
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

number of document in Firebase data manager must be correct.

## Current behavior (required)

 Firebase Datta Manager shows only 1,000 documents even though I have 5600 document in Firebase. 
App shows exact number but only Firebase data manager show I have only 1,000 document 

## To Reproduce (required)

1.
2.
3.
4.

## Screenshots / recordings

<img width="546" alt="스크린샷 2023-01-03 오전 10 45 26" src="https://user-images.githubusercontent.com/82285956/210290543-1fc9778f-cf02-4e54-ae49-d77eac050525.png">

## Your environment

* Version of FlutterFlow used: 3.3.4
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome version 108.0.5359.124
* Operating system and version (desktop or mobile): Mac OS Monterey 12.6

**Comment by bulgariamitko** [comment] 2023-01-03 16:01
I can't reproduce this as I don't have 1k documents. I will change that with a status of confirm and let FF team decide if it is a bug or limitation of the platform.

**Comment by shelpert** [comment] 2023-04-06 23:23
Hello,

We consider this issue to be more of a limitation of our CMS and might fix it sometime in the future, but for now I'm closing it as wontfix. We only query and read 1000 documents at a time in CMS, because otherwise it would be really slow and users would be charged more for the extra reads on their database.

**Closed by shelpert** 2023-04-06 23:23 UTC
Labels: type: bug, status: wontfix
