### ISSUE TITLE
Setting ENUM fields from the FlutterFlow Firestore CMS stores a wrong value

### ISSUE THREAD

**Issue by marinosabijan** [FlutterFlow/flutterflow-issues#2546] opened 2024-03-17 20:29 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When setting the enum value using the firestore CMS from flutterflow,

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/a05cb474-6c51-4680-9648-e51a26dc38a1/88129032-0efb-4186-9579-f939876a96b9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hMDVjYjQ3NC02YzUxLTQ2ODAtOTY0OC1lNTFhMjZkYzM4YTEvODgxMjkwMzItMGVmYi00MTg2LTk1NzktZjkzOTg3NmE5NmI5IiwiaWF0IjoxNzEyMzM5MDM4LCJleHAiOjMzMjgyODk5MDM4fQ.Ex8Dr5UZDDS8obyPEAmWe-GSHCl_N9mLH-Pl_2rgt6Q)

the value is set wrong as such:

![Screenshot 2024-03-17 at 21 23 08](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f1b99f41-8d01-4cb7-b031-105faa38903b/99165b24-918b-4707-98bb-a71b2f5bbc97?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mMWI5OWY0MS04ZDAxLTRjYjctYjAzMS0xMDVmYWEzODkwM2IvOTkxNjViMjQtOTE4Yi00NzA3LTk4YmItYTcxYjJmNWJiYzk3IiwiaWF0IjoxNzEyMzM5MDM4LCJleHAiOjMzMjgyODk5MDM4fQ.ZPSuoy92AkP3Oqj3VqR4IqFkcER-PzNNSWwVKXZw43I)

### Expected Behavior

It is expected to store the value as it should with the name of the enum:

![Screenshot 2024-03-17 at 21 23 11](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/21615d96-1dd2-4d12-81b8-2e14c030138d/9e3ed8ca-b3ff-419b-8b5f-edbe76746f01?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yMTYxNWQ5Ni0xZGQyLTRkMTItODFiOC0yZTE0YzAzMDEzOGQvOWUzZWQ4Y2EtYjNmZi00MTliLThiNWYtZWRiZTc2NzQ2ZjAxIiwiaWF0IjoxNzEyMzM5MDM4LCJleHAiOjMzMjgyODk5MDM4fQ.97HQNuEbPbxAe5YEYWAW3qWxjuNyFt4zpyCvef0IC60)

It only sets the value of the enum correctly when setting it from the app itself, not when setting it from flutterflow CMS. So it's expected that works as well.

### Steps to Reproduce

1. Create an enum type in your app
2. add the enum as a filed in one of your collections/ documents
3. use the flutterflow firestore CMS to set the value of the enum and verify the wrong value being set in firestore

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTi8mAvJN2xcdY+KnhKu1FlWA4I0MdXOczitVEew4bCIj4PaQuZvSkYlZoQsyzaHxAJU6b/X8f3MrJk+LpUPoEAymtb6Zayc1uSxPPbGamV4SwOrqWQH9DM+BYGGqf0bensyRQGLBaSiEB2173Pe6Qbz2Cf9qOYwx5e6fDbOY=

### Context

I am trying to use the flutteflow firestore CMS to set enum field values for the locale types. I don't want to use string for it, because I want my CMS users to not produce errors by misstyping the strings of the locale codes.

### Visual documentation

![Screenshot 2024-03-17 at 21 23 11](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/90794e5f-d8e0-4f9a-a741-284522d0dbb3/a87486f2-7ebc-4f3e-aca5-d5eed3c0e800?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85MDc5NGU1Zi1kOGUwLTRmOWEtYTc0MS0yODQ1MjJkMGRiYjMvYTg3NDg2ZjItN2ViYy00ZjNlLWFjYTUtZDVlZWQzYzBlODAwIiwiaWF0IjoxNzEyMzM5MDM4LCJleHAiOjMzMjgyODk5MDM4fQ.b_oqCE7UHbxk8FYnINxMKEybyP-YLsNuZwy1S6ZOm5E)

![Screenshot 2024-03-17 at 21 23 08](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/98a52d04-5509-4e65-ab59-eb2064535713/b6948ef2-415d-482e-9320-c2c8b2f5ce5b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85OGE1MmQwNC01NTA5LTRlNjUtYWI1OS1lYjIwNjQ1MzU3MTMvYjY5NDhlZjItNDE1ZC00ODJlLTkzMjAtYzJjOGIyZjVjZTViIiwiaWF0IjoxNzEyMzM5MDM4LCJleHAiOjMzMjgyODk5MDM4fQ.C-wPzZaVL4e_JQ9o14qI0-hB0zwa_xkEw4G00q4Gu0U)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/1055f553-5737-44d8-a04a-26d74a9243aa/755caecf-3fa1-46bc-a794-6721d8ece5d8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xMDU1ZjU1My01NzM3LTQ0ZDgtYTA0YS0yNmQ3NGE5MjQzYWEvNzU1Y2FlY2YtM2ZhMS00NmJjLWE3OTQtNjcyMWQ4ZWNlNWQ4IiwiaWF0IjoxNzEyMzM5MDM4LCJleHAiOjMzMjgyODk5MDM4fQ.r48zKCX7nKBl0usyQlNzHi9P_U5LcxEYbtmizSPzY7g)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1.33
- Platform: Mobile, Web and CMS
- Browser name and version: Chrome, Version 122.0.6261.129 (Official Build) (x86_64)
- Operating system and version affected: MacOS, N/A
```

**Comment by marinosabijan** [comment] 2024-03-25 09:18
Any updates?

**Comment by davidflutterflow** [comment] 2024-03-25 09:27
@hariprasadms I also replicated this issue, It's a bug in our CMS

**Comment by marinosabijan** [comment] 2024-04-02 01:34
@davood-flutterflow is it fixed?

**Comment by ignalauret** [comment] 2024-04-11 21:41
Hey @marinosabijan thanks for your report. I was able to replicate your problem, I'm sending a ticket to the Engineering team to fix it. They will keep you updated on this thread. <br>Have a good day!

**Comment by Perlo34** [comment] 2024-05-02 16:52
Any update ? the issue was submitted since more than a month , many update but not fix

**Comment by Perlo34** [comment] 2024-05-02 17:09
Sorry , it work now from action create document but the issue perssist when create document from content manager

**Comment by AnushaFF** [comment] 2024-05-15 16:15
Hi @StormKiller the fix is not yet released. You would have to wait until the next release to verify the fix. Please let us know if the issue persists after the release. Thanks!

**Comment by StormKiller** [comment] 2024-05-16 04:14
Thank you so much @AnushaFF 
Appreciate your quick response :)

**Comment by StormKiller** [comment] 2024-05-25 05:45
Does any know which release this fix will be released with?

My version
FlutterFlow v4.1.53+ released May 17, 2024
Flutter version is 3.19.1

**Comment by PeninPab** [comment] 2024-06-01 15:45
> Does anyone know which release will include this fix?
> 
> My version FlutterFlow v4.1.53+ released May 17, 2024 Flutter version is 3.19.1

This recent release has fixed the Enums, it's now properly storing the value to what has been typed for the value. However I am experiencing an issue where when editing the enum field in the firebase data manager provided by Flutterflow, it shows up as unset when I edit a document. Requires me to reset the values of the enums once more before applying the update to the document.

**Comment by anuragggg** [comment] 2024-06-19 14:33
> > Does anyone know which release will include this fix?
> > My version FlutterFlow v4.1.53+ released May 17, 2024 Flutter version is 3.19.1
> 
> This recent release has fixed the Enums, it's now properly storing the value to what has been typed for the value. However I am experiencing an issue where when editing the enum field in the firebase data manager provided by Flutterflow, it shows up as unset when I edit a document. Requires me to reset the values of the enums once more before applying the update to the document.

facing the same issue, any updates ??

**Comment by StormKiller** [comment] 2024-06-20 16:48
@PeninPab @anuragggg 
I have the same issue. Although this is a regression bug, we need to open a new issue for this. I'm a bit tied up with my work at the moment. Could anyone help open a new issue (with screen and reproduce steps)?

**Comment by leighajarett** [comment] 2024-06-24 17:08
So sorry about this! We're taking another look and will have an update soon

**Comment by StormKiller** [comment] 2024-06-25 04:44
Thank you so much for your attention @leighajarett :)

**Comment by vieiraes** [comment] 2024-06-27 00:18
following

**Closed** 2024-06-28 05:10 UTC
Labels: status: confirmed, Bug, Firebase CMS

**Comment by leighajarett** [comment] 2024-06-28 10:46
We've resolved this in our codebase and will have a fix out ASAP

**Comment by StormKiller** [comment] 2024-06-28 15:18
Thank you again @leighajarett !! Appreciate your attention :)
