### ISSUE TITLE
Unable to add an action to toogle icon widget

### ISSUE THREAD

**Issue by plannedlivingjournal** [FlutterFlow/flutterflow-issues#3813] opened 2024-09-12 16:04 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hi! I am creating an app wherein if someone likes a post/test, it should get added to their 'Favorites' folder. If someone clicks on the 'Toggle button', it should get added to another page.

![image](https://github.com/user-attachments/assets/27f68b71-8e22-42ce-91ec-8a06c535c2aa)

### Expected Behavior

1) Click on Toggle/Heart button 
2) Should get added to another page/should get collected.

### Steps to Reproduce

Unable to create the scenario

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4olsn15YVPj7xE7q6JccBKjSQWOUAlbLgO0cpBZzAaIrb1CLMqY8mnPltBZ+mkS3xUOmGcp14E0/DWj/zhG8YEZC2aRtlGyM8BaBXjTliWMZeTF7qWPnB5M+5gfUix07aruBVTAPNpc3AB70+YHN+8dAXBO4DJDWo8Sq/LZO4=

### Visual documentation

![image](https://github.com/user-attachments/assets/9a0a90a2-6187-4b20-9f08-c610560fc275)

### Environment

```markdown
- FlutterFlow version: 3.22.2
- Platform: Web
- Browser name and version: Chrome 1.28
- Operating system and version affected: Windows
```

**Comment by paulperez-dev** [comment] 2024-09-13 04:40
Hi @plannedlivingjournal,

Thanks for reporting the issue! However, I’m having a bit of trouble understanding the exact nature of the bug. Could you please provide more context and details, such as the steps you’re following, the platform you’re using, and any specific behavior you're noticing? This will help us investigate the issue more effectively.

I appreciate your help!

**Comment by plannedlivingjournal** [comment] 2024-09-14 16:34
Hi @paulperez-dev, I am not clear on the steps of how to add an action to toggle icon. So, I want to provide a feature just like Instagram, wherein if you like a post it also goes into 'Likes' section in activity folder. Similarly, here if someone clicks on the heart icon, it should get added in some other folder so that user can directly go to that folder and view his liked affirmations.

**Comment by paulperez-dev** [comment] 2024-09-19 04:18
Hi @plannedlivingjournal,

You can achieve that feature by using an AppState to save the liked element and creating a page that reads/loads the data from the state. For further assistance, feel free to reach out to the community: [https://community.flutterflow.io/ask-the-community](https://community.flutterflow.io/ask-the-community).

I’ll be closing this issue as it’s not a bug.

**Closed as not planned** 2024-09-27 17:50 UTC
Labels: closed: not a bug
