### ISSUE TITLE
'Hide Keyboard on Tap' isn't working

### ISSUE THREAD

**Issue by iGrits** [FlutterFlow/flutterflow-issues#1325] opened 2023-08-21 22:41 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In the page scaffold properties, I have 'Hide Keyboard on Tap'  DISABLED.  Even with this disabled, my keyboard disappears whenever I tap anywhere on the page.

Initially raised in community:
https://community.flutterflow.io/troubleshooting/post/how-do-i-disable-hide-keyboard-on-tap-Tbi3xZ2PxgiJyFO

### Expected Behavior

With the 'Hide Keyboard on Tap' DISABLED, I would expect tapping on the screen to do nothing.  e.g if keyboard is displaying, and you tap on the screen, the keyboard remains displayed.

### Steps to Reproduce

1. Create a new page
2. Add a TextField widget
3. Disable 'Hide Keyboard on Tap'
4. Test in Test Mode.  Click on textfield widget to bring up keyboard, and then click anywhere outside of the screen.  Keyboard should disspear even with 'Hide Keyboard on Tap' disabled.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ekMrl25Ngoflc0aryb/pahjs5KVs7U4ZMmMNxcAwbNZTwB7MMO+j+THdWUu3ifFZiJWGJmm0f3PTRuePpV8AnEByJb4s4zroMWAryfHuRVqqsDJGKe3FtP9JnGUi7zpuZohRTA7JvLHth6jiAJOu8ThDdQ4zyNXowQvL/BLD4nAOQFhzCGX0Jg1ZSfCvr

### Context

I have a messaging app, that every time someone hits a button to send a message, their keyboard disappears.  Typically, your keyboard remains open to type any additional messages.

### Visual documentation

https://community.flutterflow.io/troubleshooting/post/how-do-i-disable-hide-keyboard-on-tap-Tbi3xZ2PxgiJyFO

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform:Android FlutterFlow Preview App
- Browser name and version:n/a
- Operating system and version affected: Android
```

**Comment by hariprasadms** [comment] 2023-08-23 14:16
Hi @iGrits - Thanks for submitting the issue. I can reproduce the issue. However it is inconsistent. 

Dev note - On iOS it works fine ( however, clicking on edge of the screen at left side, it closes the keypad ). On Android it is not working.

**Comment by wenkaifan0720** [comment] 2023-08-23 18:26
Hi @hariprasadms. I tried on an Android emulator and a real Android device but the keyboard wouldn't be dismissed.

**Comment by wenkaifan0720** [comment] 2023-09-24 01:17
Since I can't reproduce this issue from the test project, I will close it for now.

**Closed** 2023-09-24 01:16 UTC
Labels: status: can't reproduce, closed: not a bug, status: not a bug

**Comment by gentleVirus** [comment] 2024-02-20 18:38
Is there a chance to reopen this issue? I am experiencing the same bug on PWAs at several Android and iOS devices.

**Comment by betatechnologiesuk** [comment] 2024-04-14 21:09
I am also experiencing this issue across iOS

**Comment by banksAcc** [comment] 2024-05-06 07:52
hi, yes I notice the problem too, it's a flutterfow bug, which is quite serious in my point of view...we're waiting for a resolution from the FF team. In the meantime, does anyone have any ideas on how to get around this problem?

**Comment by deepakkano** [comment] 2025-05-14 07:41
On some devices, there's an issue where the keyboard does not open even when tapping on a `TextField`.

**Device name:** OnePlus 7 Pro.
