### ISSUE TITLE
Entire project not working due to webview widget

### ISSUE THREAD

**Issue by ValetCEO** [FlutterFlow/flutterflow-issues#3259] opened 2024-06-27 11:47 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

My whole project is crashing - when I deploy to web I now just get a blank screen. On further investigation, it appears to be Flutterflows own WebView widget causing this. This is reproducible in a blank project

### Expected Behavior

The page should load and show the content

### Steps to Reproduce

1. start a new project
2. put webview on the page
3. try running in test mode or deploy to web

![365d231a-8b24-4c16-90c3-070cc2752b19](https://github.com/FlutterFlow/flutterflow-issues/assets/155745989/3160102b-e00d-445b-9979-a6f914ff9a73)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Clcrqw5VOsdhE7c+BbPowoDwWHG4jRYEn1usbGAk0N5PQCJkQO8nQPhBWZPXmYFZcMGK2p14Ep9rKuezhKPY5AAeqf7pnys12SzyXZDuWabmTF7u8WHxPP9xXCHKh5MOJgiJdIfhZSmAhwEOlN++idDHtHbLIDmowSq/LZO4=

### Visual documentation

![365d231a-8b24-4c16-90c3-070cc2752b19](https://github.com/FlutterFlow/flutterflow-issues/assets/155745989/72a32fdd-1527-4461-9974-cc04c557048c)
<img width="1680" alt="Screenshot 2024-06-26 at 15 27 35" src="https://github.com/FlutterFlow/flutterflow-issues/assets/155745989/9751fa1b-5021-4414-9737-71821633a8e8">

### Environment

```markdown
- FlutterFlow version: 4.1.63
- Platform: All
- Browser name and version: Chrkme
- Operating system and version affected: All
```

**Comment by rzambroni** [comment] 2024-06-27 14:28
Hello, i attempted to replicate this issue but i was unable to do so, it is working fine on a blank project. I tested both running it on test mode and web publish.<br>You mentioned this is replicable on a blank project, can you share that blank project bug-report-code so we can take a look?

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/782b20b4-6024-469b-8bcf-2b6c18551f2f/2188ef1b-4776-4f48-934a-47af08ce8fff?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83ODJiMjBiNC02MDI0LTQ2OWItOGJjZi0yYjZjMTg1NTFmMmYvMjE4OGVmMWItNDc3Ni00ZjQ4LTkzNGEtNDdhZjA4Y2U4ZmZmIiwiaWF0IjoxNzE5NDk4NTIwLCJleHAiOjMzMjkwMDU4NTIwfQ.TLR0eiZV3XcSY1pBYGjzy94c1fowPUwC72kXYDz2jDE " alt="image.png" width="1073" height="970" />

**Comment by ValetCEO** [comment] 2024-06-27 14:53
I'm waiting for the developer to respond with the link. Can you please ask the support team to respond to messages, it's been 16 hours since the last message and so far no help at all fixing these issues!

**Comment by rzambroni** [comment] 2024-06-27 21:12
Hey there, it seems like in most cases the issue is related to the usage of this dependency on your custom code: `html_editor_enhanced` It is very likely that this package is not yet compatible with the latest flutter stable version 3.22.2.

**Comment by rzambroni** [comment] 2024-06-27 21:14
I'll mark this ticket as a duplicate of the original report. [https://github.com/FlutterFlow/flutterflow-issues/issues/3229](https://github.com/FlutterFlow/flutterflow-issues/issues/3229)

**Closed as not planned by rzambroni** 2024-06-27 21:14 UTC
Labels: closed: duplicate
