### ISSUE TITLE
A screen with Algolia search always asks for the user's location

### ISSUE THREAD

**Issue by cheggy** [FlutterFlow/flutterflow-issues#39] opened 2022-10-15 22:24 UTC
Any time I have a screen that uses Algolia search, code is added to the screen to get the user's location,
Even if I select Location == None from the editor.
The result is when going to the screen:
1. It loads a black screen while it tries to get the user's location
2. The user is prompted to give access to device location when it's not needed.

## Expected behavior (required)

If I add Algolia to a screen and select Location == None,
No code is added to the screen to get the user's location.

## Current behavior (required)
If I create a screen, and run a backend query of Query Type = Algolia Search
And select Location == None,
Code is added to the screen to get the user's location.
The results is the screen loads black while it get's the users location
And the user is prompted to provide access to their device location, which is a poor user experience, as it's unclear why the app should be prompting for this information.

## To Reproduce (required)
1. Create a new screen
2. On a ListView, add a backend query of type Algolia Search
3. Set the Location to 'None'
4. Use the query to build the listView
5. Build/run the app and go to the screen created.

## Context (required)
It creates a poor user experience
I have to comment it out every time I build the app manually

## Screenshots / recordings
![image](https://user-images.githubusercontent.com/3022867/196009646-725a4842-1d41-4a8b-b444-5294ebfd2111.png)
![image](https://user-images.githubusercontent.com/3022867/196009672-aeecb623-b563-4010-81a4-0625c55208c8.png)

## Your environment

Been happening since day 1
FlutterFlow v3.0 Oct 6 2022
Windows Chrome current version, web editor, Edge current version
Windows 11

**Comment by bulgariamitko** [comment] 2022-10-18 11:34
I can't reproduce it because I think there is other issue. When you create a new project and you don't collect FB and just create a new collection inside FF you can't select a Collection even if you have one in FF from the dropdown menu in Algolia Search. Can someone confirm that as other issue?

**Comment by cheggy** [comment] 2022-10-18 21:53
@hariprasadms are you after my Project Link?  Is it safe to put a project link in here, or can I DM you somehow?

**Comment by bulgariamitko** [comment] 2022-10-18 22:06
You can create a new project reproduce it. Make it public and share the link here.

**Comment by katherineqian** [comment] 2022-10-22 06:03
@cheggy You can go to your project, right click anywhere in the widget tree on the screen that was affected, and select "Generate Bug Report Code". You can share the generated code here, which will help the team privately get more information about your project.

**Comment by cheggy** [comment] 2022-10-23 08:42
ITFTzMmAsYtIxLRG+KqJdO0wmiYWM0MdXZIRmOtvewgjF774P+0uZ+DBdRJpQsCzaH1ID2H9o3wCpujSi9/DMfkqHE6bGKJhzroBZ1yjEA8=

**Comment by agreaves** [comment] 2022-11-11 23:07
Thanks @cheggy for providing this bug report and that info, this proved extremely useful! This issue will be fixed upon our next release 🙂

**Closed by agreaves** 2022-11-11 23:07 UTC
Labels: status: can't reproduce
