### ISSUE TITLE
Checkbox not clickable in List View generated from variable

### ISSUE THREAD

**Issue by hannahjkn23** [FlutterFlow/flutterflow-issues#3709] opened 2024-08-29 18:09 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a List View that is not set from a query but a variable because it holds two queries. I added a checkbox to the first row as usual to select multiple List Items, but the checkboxes are not clickable, only the grey circle around them is shown. 

### Expected Behavior

The expected behaviour would be that I can click on the checkbox and since the initial value is unchecked the clicked checkbox changes it value to checked.

### Steps to Reproduce

1. Create a Page or component and add an List View to it
2. Set up an (app state) variable that holds a List of either document references or a custom data type
3. In the List View add widgets as you want to style it and add a checkbox to it (wrapped in row) with the initial value "unchecked"
4. Choose the (app state) variable as the variable to generate the List views data items from 
5. Open test or run mode, navigate to the page/component and try to select the items 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFflvHl3It2ocsG0a6JKO0wvyk7OWEcTIAzjdV+bwogIuOqBuwxO/SlZRNvTf2qaVNcBFajpFEC+aH7jdr2G/o6NgqWfKI7/6hfEwvee2i5RaXXDM60Q2t6BdpVGn6f1sOvrhEnOsRuW15g1FOPNuq9XhPDFOu/Zwh9f6PHaOI=

### Visual documentation

![4de6daa6-8af4-495a-b0c4-605d450848b6](https://github.com/user-attachments/assets/4eb24772-9af0-414a-b39e-4230dbb8e073)

### Environment

```markdown
- FlutterFlow version: 3.22.2
- Platform: Web 
- Browser name and version: Microsoft edge, Safari
- Operating system and version affected: macOS, Windows 11
```

**Comment by Alezanello** [comment] 2024-08-30 19:42
Hi there!

I wasn’t able to reproduce the issue following your steps:

1. Created an AppState list of references.
2. Created a ListView.
3. Added a Checkbox inside a Row within the list.
4. Generated dynamic children for the list from the AppState.

Everything worked as expected on my end.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/7eafb9eb-fa78-4667-9dcd-ce70f65755b9/ea9499c7-1b21-4a2b-a636-9f5e8e7da748?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83ZWFmYjllYi1mYTc4LTQ2NjctOWRjZC1jZTcwZjY1NzU1YjkvZWE5NDk5YzctMWIyMS00YTJiLWE2MzYtOWY1ZThlN2RhNzQ4IiwiaWF0IjoxNzI1MDQ2OTM2LCJleHAiOjMzMjk1NjA2OTM2fQ.wVUGzHZk2NoqUGaqlddd5CjdstnvaLNh7TU8bmVPtTs " alt="asExpected.gif" width="1575" height="884" />

Public Project: [https://app.flutterflow.io/project/qa-1845-p9fn7j](https://app.flutterflow.io/project/qa-1845-p9fn7j)

**Comment by hannahjkn23** [comment] 2024-08-31 12:19
Hi, it seems to be a problem in test mode, in reality it seem to work, as shown in the videos

https://github.com/user-attachments/assets/fb40b7b3-2b5d-4da2-8a78-ea72a59685df


https://github.com/user-attachments/assets/faa5e60e-fb11-4089-812f-b877276591da

**Comment by Alezanello** [comment] 2024-09-18 22:12
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by Alezanello** [comment] 2024-09-30 14:25
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Closed as not planned by Alezanello** 2024-09-30 14:25 UTC
Labels: status: can't reproduce, waiting for user response
