### ISSUE TITLE
checkbox on toggle off action not calling

### ISSUE THREAD

**Issue by staplKody** [FlutterFlow/flutterflow-issues#2956] opened 2024-05-21 14:41 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I toggle off my checkbox, none of the actions are performed. 

### Expected Behavior

The action's would be performed under the on toggle off tab. 

### Steps to Reproduce

1. create a page
2. add a check box
3. add an action under the on toggle off of that checkbox
4. observe that the action is not called

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kkcjfsMx2rsdY17X5be5Fv2UUQlAgTLIFse0aRR4cF4yrB+wMesz4Q0NKTu3iTH9MHmK0rD4d+fD7vvDDGvYpMgSYbZw50JVATQ2XLXy5M7qwEquCe3NfJ8FMJmKu4baNhRZ/LvN0S3xh2UzyNq3qNleeY8aSfxBlZ7vfcPo=

### Context

I am using a check box in a bottom sheet to select all items (handled in backend via some logic). When I toggle the check box on it performs all of the actions. However, when I toggle it off it does not perform any actions. I did attempt opening a snack bar or just displaying the state it is manipulating in a text widget to verify that nothing is happening when it is toggle off. 

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/137829936/1f24c563-a101-47af-9d97-e71b34bf97e1)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/137829936/b326a27c-8bec-4584-9b86-95bb7d3d05f4)

### Environment

```markdown
- FlutterFlow version: 4.1.53+
- Platform:Windows App
- Browser name and version: N/A
- Operating system and version affected:  Windows 11 version 23H2
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by msusviela** [comment] 2024-05-22 01:13
Hey @staplKody, Thanks for your report, So sorry you are experiencing this issue. I was not able to reproduce this on a blank project, but it is replicable on yours. That's why I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. Thanks so much!

**Comment by staplKody** [comment] 2024-05-22 13:03
@msusviela ok thank you, I will follow up with the support team.

**Closed** 2024-05-28 19:55 UTC
Labels: waiting for user response
