### ISSUE TITLE
AI component gen

### ISSUE THREAD

**Issue by joekman990** [FlutterFlow/flutterflow-issues#2550] opened 2024-03-18 17:29 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When trying to add a component with AI gen i get an error saying that i reach my limit for the day and it failed to insert

### Expected Behavior

i expect the ai to generate the component i am on the paid plan and it will generate a page if i ask for one just the components are giving me this issue

### Steps to Reproduce

1. click the green icon on the top left of your canvas
2. select component
3. input a prompt to generate a component
4. when a component is generated select insert

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTl8rl34ZPm7RJ+Kn1KflFoCE7M0MfWOdEket+EA0hfamsPe0hduPsQ1VLYteFSmNiHmegp3EJ+Pz1v9nPF8ErCwiafLY4yJRXQTrMLUymR5PQO7isXkBREeVQIW7A0MOrmyRDPtRZWi0X7GeAevCdG3qCf9qOYwx5e6fDbOY=

### Context

i was trying to generate a simple component and ended up spending a lot of time trying to make sure this was a bug it is more to help the amazing FlutterFlow team be aware of a bug

### Visual documentation

[https://github.com/FlutterFlow/flutterflow-issues/assets/72816439/44fa4915-a654-4d15-8d71-ee5e7152663a](https://github.com/FlutterFlow/flutterflow-issues/assets/72816439/44fa4915-a654-4d15-8d71-ee5e7152663a)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1.33
- Platform:macOS
- Browser name and version: chrome and macOS app
- Operating system and version affected:
```

**Comment by hariprasadms** [comment] 2024-03-22 18:55
Hey @joekman990 - Are you still encountering the issue? I've just verified it, and I can confirm that no error is appearing on my end. If the issue is not present at your end, please consider closing it. Thanks

**Comment by joekman990** [comment] 2024-03-27 15:18
this is still an issue for me 

Uploading Screen Recording 2024-03-27 at 11.15.58 AM.mov…

**Comment by joekman990** [comment] 2024-03-27 15:19
https://github.com/FlutterFlow/flutterflow-issues/assets/72816439/09f7559b-18a5-4f53-8f4d-6abd2b244a00

**Comment by joekman990** [comment] 2024-03-27 18:33
i am still finding this issue persisting i uploaded a video showing the
issue

**Comment by joekman990** [comment] 2024-04-02 18:09
> Hey @joekman990 - Are you still encountering the issue? I've just verified it, and I can confirm that no error is appearing on my end. If the issue is not present at your end, please consider closing it. Thanks

any update do you see what the issue is i am still experiencing it

**Comment by leighajarett** [comment] 2024-04-05 18:20
Thanks for flagging this as an issue. We're working on it!

**Comment by joekman990** [comment] 2024-04-05 20:46
🙏🙏

**Closed** 2024-04-05 22:28 UTC
Labels: status: confirmed

**Comment by leighajarett** [comment] 2024-04-06 11:34
This has been fixed and should be resolved in next week's release. Thank you!
