### ISSUE TITLE
Firestore Functions not working

### ISSUE THREAD

**Issue by DTOP1102** [FlutterFlow/flutterflow-issues#3438] opened 2024-07-19 04:08 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello, I m working on my project and i need to use cloud functions in custome function to display points from documents but it showing me this error. 

i tried to move it to custom actions and refreshing firebase , changing rules but none of them works for me

### Expected Behavior

it should calculate 'runs' field from 'batters' list.

### Steps to Reproduce

i simply using cloud functions in my 'teamScore' custom function it showing the package before but no more but before its not working either.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFflcr1z4tPvsBI+a6JdvpViiU7OVMcTIMziNZ+exUbfaL1Buw+euClREpvZ/25aVNcfWaZhlMJw8rVk+PfF/UoHyiZbbk41bt6UDrke2igVYSYCZOKPHNCM55Qf2HG36SvqghDOsdqdE4s312TfO+/QnHDIuu/Zwh9f6PHaOI=

### Visual documentation

![Screenshot_12](https://github.com/user-attachments/assets/a386f303-a7f2-4f81-a5f6-eef3cb401d0d)
![Untitled](https://github.com/user-attachments/assets/329a6f2b-0dbd-41eb-bbd6-176130325c87)

### Environment

```markdown
- FlutterFlow version: v4.174
- Platform: Web
- Browser name and version: Chrome v126.0.6478.182
- Operating system and version affected: Windows 10 Pro
```

**Comment by msusviela** [comment] 2024-07-19 10:26
Hey @DTOP1102, This is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. Thanks so much!

**Closed as not planned by msusviela** 2024-07-19 10:26 UTC
Labels: closed: support request
