### ISSUE TITLE
Unable to use the "action with parameter" return value inside action.

### ISSUE THREAD

**Issue by woiq** [FlutterFlow/flutterflow-issues#2249] opened 2024-01-26 15:47 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Im attempting to use the new action with paramter callback, but seem to be getting stuck without reason. I attempted to use it in a normal component where it succeeded. But when trying to use it in a custom widget it seemed to fail. I can correctly create the paramter inside my custom widget and call with a passed paramter, but then when trying to use this return value in the passing action, when selecting the callback paramters. the only visual change that happens is the trashcan, but no actual value is set inside the field, or am i able to select one of the values inside the data type. See pictures below.
I added the callback with paramter and im calling it inside a test button to return a simple test value.

### Expected Behavior

To be able to use the callback paramater just like (for example) page parameters.

### Steps to Reproduce

1. Create a new custom widget.
2. Add a 'action with parameter' parameter for the custom widget.
3. Add this custom widget inside a flutterflow page.
3. Inspect the custom widgets properties and define an action for the callback.
Final. 4. Attempt to use the callback's parameter value without succes.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40jPzc5bZ/xrx3+rXIb/cwoCAjJHI3RIAo0NhBaCsofePrOpkAf8/7UFtUOeGoY1Z6J2GZkXMX/MmOv9nxUfcEBxWdY4hy1pd+dzngJTimb8mlCZS3b0QlGdJMI0OB5rSRowhTAPZZV0YN1FOAFt6scD3dQ+PLPDEkROa4XdeK2SrDX1iXc2URm05KZDPz

### Context

Im experiecing the same issue in a different widget where im attempting to return a data type, i cant select any values inside that datatype nor can i pass the datatype itself either, ive tried with other normal values, int, strings etc. I just want to return a value to its parent after modifying it.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/91980736/3afdccc7-b64c-4925-97a5-2818a8783cbb)
![1](https://github.com/FlutterFlow/flutterflow-issues/assets/91980736/db448070-505e-4764-8137-39000dd02bc2)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/91980736/7f9b9710-a798-4f83-bd32-35aaa7475792)

### Environment

```markdown
- FlutterFlow version: v4.1
- Platform: Web
- Browser name and version: Chrome 120.0.6099.227
- Operating system and version affected: Windows 10 Pro 22H2
```

**Comment by hariprasadms** [comment] 2024-01-26 17:59
Hi @woiq - Please share a blank project with the issue set up in it. I'm unable to identify the issue point in the provided project.

**Comment by sbis04** [comment] 2024-01-29 03:14
@woiq I tried reproducing this on a fresh project but wasn't able to. Can you try deleting the `TestWidget` once, and then save and compile? Now, test if you can use the callback action parameters.

Also, I just noticed in the above example, instead of:

```dart
onPressed: (() {
  widget.number.call(10);
}),
```

I believe you wanted to do this:

```dart
onPressed: (() async {
  await widget.testAction?.call(10);
}),
```

**Comment by woiq** [comment] 2024-01-29 15:31
So after some more analysize I realized the issue is there but only if i dont the paramter in correct locations, for example: 
Integer callback, used on integer base, correct usage.
Integer callback, used inside alert dialog message, error.

This behavior does not apply to page paramter where it convert and uses the integer in a string or the ability to use it inside a combine text formation.
I also had trouble returning a data type and using one of its children as values inside the callback function. Where it would not give me the option to open the data structure field.

So conclusion, for me the issue still lies unless the callback return value, is the exact same as the use case in the project.

**Comment by woiq** [comment] 2024-01-29 15:46
> Hi @woiq - Please share a blank project with the issue set up in it. I'm unable to identify the issue point in the provided project.

I made a simple project recreating the issue.
https://app.flutterflow.io/project/test-oapt4w

To see the issue follow the visual steps below:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/91980736/d470a6a7-1869-4bc6-8075-c5410a60a8fe)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/91980736/78409326-e13b-43aa-991a-7609ecbe39e3)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/91980736/c2bb4e39-46a9-4462-8836-7d96884e0e2d)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/91980736/c02fa96a-b6e8-4827-b81a-66d70daa0aff)

**Comment by hariprasadms** [comment] 2024-01-30 12:55
Hi @woiq - Thanks for the details. Yes, i can reproduce the bug.  

Dev note - It mostly happens when call back action parameter is data type.

**Comment by dmslabsbr** [comment] 2024-02-02 20:26
I'm having the same problem in FlutterFlow.

![b](https://github.com/FlutterFlow/flutterflow-issues/assets/3632067/de9b9dfe-e44b-4ba6-81c4-3f853f3fd0b4)

I already tried to compile the code in Flutter using VS Code, and I didn't receive any compilation errors.

**Comment by sbis04** [comment] 2024-02-04 06:52
The issue with the Data Type inside callback action parameter should be fixed in the new update!

@dmslabsbr though this might be related to callback action parameter this looks like a different issue, can you please create a separate issue with all the information?

**Closed by sbis04** 2024-02-04 06:52 UTC
Labels: type: bug, status: confirmed
