### ISSUE TITLE
Copy to Clipboard fails in Test Mode

### ISSUE THREAD

**Issue by Dev-Muhammad-Junaid** [FlutterFlow/flutterflow-issues#1418] opened 2023-09-07 15:15 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Copy to clipboard action doesn't work. 
Works fine in local IDE but not in Web or Testmode
Chrome Error provided.

### Expected Behavior

To be able to copy anything using copy to clipboard action

### Steps to Reproduce

1. Add Action Copy to Clipboard

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40kMmA8Y9Pxd9A7c/9bcdR/SI5KUw+RI0n0+1RaCgofePtOol3evWlUFZvUuHhd0FMM0SmmlkDzOjIuNrhU+0ENRGVGIBD+qhqFjngXk6mUZOBPZOOSXR6QJhMClDG1J+3oSRBLsp2ci0Y2V2QJ9m/Hx3YH5z6ImdISq/LZO4=

### Context

I am trying to copy some text from action "copy to clipboard"

### Additional Info

.

### Environment

```markdown
- FlutterFlow version: v3.1 released August 28, 2023
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected:  MacOS Sonoma 14.0
```

**Comment by Dev-Muhammad-Junaid** [comment] 2023-09-07 15:16
<img width="1314" alt="Screenshot 2023-09-07 at 8 04 38 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/65047962/ab560865-0e17-45e0-a195-9e824c9f3152">

**Comment by Dev-Muhammad-Junaid** [comment] 2023-09-07 15:30
Just tested this with the newly released flutterflow update. Same issue

- FlutterFlow version: v3.1 released September 07, 2023
-

**Comment by SameerShahzad99** [comment] 2023-09-08 18:51
@Dev-Muhammad-Junaid Thank you for submitting this bug, you have not attached a blank project, but I was able to reproduce this on my project!

**Comment by Dev-Muhammad-Junaid** [comment] 2023-09-09 07:59
Thanks. Glad to be of service :D ✌️

**Comment by wenkaifan0720** [comment] 2023-09-19 05:01
Hi @Dev-Muhammad-Junaid. Unfortunately the webview package we use has `clipboard-read` enabled but it doesn't seem to work. Since this is not something we can fix on our end, and you can test it with web publishing, I will close this issue for now.

**Closed by wenkaifan0720** 2023-09-19 05:01 UTC
Labels: type: bug, status: wontfix, status: confirmed, priority: low, closed: other

**Comment by Dev-Muhammad-Junaid** [comment] 2023-09-19 11:54
Thanks for the update...@wenkaifan0720.  I see it's not worth digging deeper into this atm. Of course, it works fine in other places. So we are good to go. Maybe for the non-technicals we can add "Clipboard may not work in test mode " in Test mode sessions for now. ✌️
