### ISSUE TITLE
"Non-blocking" firestore writes are waited when using batch write

### ISSUE THREAD

**Issue by ryutosh** [FlutterFlow/flutterflow-issues#3701] opened 2024-08-28 09:05 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Even if all firestore write actions are setted to "Non-blocking", the procedure waited when using batch write.

# Case1. **Withou**t batch write -> not waited (**As Expected**).
![image](https://github.com/user-attachments/assets/242b50d9-627a-4a81-8bbb-2be285139059)

Generated code
```
                          onPressed: () async {
                            unawaited(.      👈
                              () async {
                                await EquipmentsRecord.createDoc(
                                        currentUserReference!)
                                    .set(createEquipmentsRecordData(
                                  ownerId: currentUserUid,
                                  name: 'create1withoutBatch',
                                ));
                              }(),
                            );
                            unawaited(.      👈
                              () async {
                                await EquipmentsRecord.createDoc(
                                        currentUserReference!)
                                    .set(createEquipmentsRecordData(
                                  ownerId: currentUserUid,
                                  name: 'create2withoutBatch',
                                ));
                              }(),
                            );
                          },
```

# Case2. **With** batch write -> waited (**Not Expected**).
Enabling "Batch Firestore Writes".
![image](https://github.com/user-attachments/assets/1d0eb584-4992-4b79-8524-0c81bc5bb5d0)
Generated code
```
                          onPressed: () async {
                            final firestoreBatch =
                                FirebaseFirestore.instance.batch();
                            try {
                              unawaited(.      👈
                                () async {
                                  firestoreBatch.set(
                                      EquipmentsRecord.createDoc(
                                          currentUserReference!),
                                      createEquipmentsRecordData(
                                        ownerId: currentUserUid,
                                        name: 'create1witBatch',
                                      ));
                                }(),
                              );
                              unawaited(.      👈
                                () async {
                                  firestoreBatch.set(
                                      EquipmentsRecord.createDoc(
                                          currentUserReference!),
                                      createEquipmentsRecordData(
                                        ownerId: currentUserUid,
                                        name: 'create2withBatch',
                                      ));
                                }(),
                              );
                            } finally {
                              await firestoreBatch.commit();.      😭
                            }
                          },
```

### Expected Behavior

Don't wait if all firestore related actions are unwaited(Non-blocking).

### Steps to Reproduce

1. Create Actions to write firestore
2. Check "Non-blocking" to them
3. Enable "Batch write"

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEehfKB35ZJpbwG1c7qcsJWiQMxN0A5beRE09UbURcbNZ+rELYpWsjDbhBvXtOAS39EPk6koFg0zM7skvLLOMJdHAyHbr1xyqluFA3KIUahbq6PCKqKdGt8AelYFUik15+RnxNQItNpdV1pig/GSw==

### Visual documentation

In current behavior section.

### Environment

```markdown
- FlutterFlow version: 4.1.85
- Platform: Mac
- Browser name and version: Chrome
- Operating system and version affected: MacOS Sonoma
```

### Additional Information

Batch write can be unwaited and works offline app.
https://firebase.google.com/docs/firestore/manage-data/transactions#batched-writes

**Comment by Alezanello** [comment] 2024-08-28 11:46
Hi there!

I understand your concern, but this behavior is currently expected. The non-blocking option only affects singular actions, not batch writes. I believe this would be more appropriate as a feature/enhancement request to allow "Non-blocking" in Batch Writes as well. I’ll generate a request ticket for the engineering team and close this issue for now since it’s an expected behavior, not a bug.

**Closed as not planned** 2024-08-28 11:47 UTC
Labels: closed: feature / enhancement request

**Comment by ryutosh** [comment] 2024-08-28 12:09
Hi, @Alezanello 
Thanks for your answer.
I also searched the official documentation before reporting this issue and could not find any mention of this being the intended specification.
Your explanation helped me understand that this was the intent. Thank you.
