### ISSUE TITLE
Can not open a page other than Home when deploying in my own server.

### ISSUE THREAD

**Issue by hyperloop9** [FlutterFlow/flutterflow-issues#1791] opened 2023-11-06 14:51 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If I deploy my project in flutterflow servers, I can get into a custom page. for example sanify.flutterflow.app/configuracion
But if I deploy the project in my own server, I can not get into any page other than home, trying to get into another page, gets me to 404 error page.

### Expected Behavior

I should be able to get infot app.sanify.site/configuracion

### Steps to Reproduce

1. Write in the browser url: https://app.sanify.site/configuracion
2. See that it takes me to an error page

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Does not apply

### Context

I am trying to make payments and I need the return URL and Error URL to get my project live

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/145791340/3bab42f3-8cae-4f92-a95d-f421f9c89626)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/145791340/ecbec42a-4b15-4efb-83e5-cd3356eea88b)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Web
- Browser name and version: Google chrome
- Operating system and version affected: Windows 10
```

**Comment by hariprasadms** [comment] 2023-11-06 21:57
Hi @hyperloop9 - This issue should go to FlutterFlow support team. We can't consider this for investigation as it is not a bug of any features.

**Comment by hyperloop9** [comment] 2023-11-06 22:03
Hi! I talk to flutterflow support team and the told me to create a ticket here.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/145791340/f9a4fae1-eb54-457f-afd6-702a1ad2cf74)

**Comment by hariprasadms** [comment] 2023-11-06 22:18
Ok. Please update issue with project bug report code and add images and video snippets to give more details about the issue you are facing. Thanks

**Comment by AndresPaul** [comment] 2023-11-18 15:09
@hyperloop9 enfrente lo mismo. El problema es que estas usando seguramente un CPANEL. Las aplicaciones SPA, como las creadas con Flutter para web, funcionan de tal manera que no recargan la página completa al navegar entre sus rutas internas. Y cuando un usuario intenta acceder directamente a una ruta específica a través de la URL. En este caso, el servidor web, por defecto, busca un archivo físico que corresponda a esa ruta. Como en una SPA no existen archivos físicos para cada ruta (ya que se manejan internamente por la aplicación), esto resulta en un error 404. Esto es algo importante que tienes que tener en cuenta al alojar en hosting.

LA SOLUCION:
En la raíz de tu aplicación Web en el CPANEL Modifica o Crea el archivo ".htaccess" con lo siguiente:

````
# Activa el motor de reescritura
RewriteEngine On

# Verifica si la solicitud no corresponde a un directorio existente
RewriteCond %{REQUEST_FILENAME} !-d

# Verifica si la solicitud no corresponde a un archivo existente
RewriteCond %{REQUEST_FILENAME} !-f

# Redirige todas las solicitudes que no son archivos o directorios a index.html
# QSA: Añade los parámetros de la consulta original a la nueva URL
# L: No aplica más reglas después de esta si se cumple
RewriteRule ^ index.html [QSA,L]
````
Los comentarios los puedes borrar. Espero te sirva.

**Comment by hyperloop9** [comment] 2023-11-21 00:24
@AndresPaul muchas gracias! Eso era justo lo que buscaba

**Comment by victoriahuang1** [comment] 2023-11-21 23:37
Closing as this was an issue with the non-flutterflow server.

**Closed by victoriahuang1** 2023-11-21 23:37 UTC
Labels: closed: not a bug, status : project specific
