### ISSUE TITLE
Progressbar in PageView causing caching?

### ISSUE THREAD

**Issue by horecdev** [FlutterFlow/flutterflow-issues#3169] opened 2024-06-18 23:56 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

So I have a Pageview which dynamically generates questions from a variable, which consists of couple containers that change color based on if selected value is correct. What I want to do is to cache it, so that when user swipes couple pages forward, but wants to check what he did wrong and swipe back, he could see what he had chosen. I thought I had it because it kind of worked, but when I removed the progressbar from my pageview child, it stopped. Ill add videos below

https://github.com/FlutterFlow/flutterflow-issues/assets/171154385/13e3cadb-4ac8-443a-b206-af39ca1ea6f1
https://github.com/FlutterFlow/flutterflow-issues/assets/171154385/d205b58f-b62a-449e-bc2b-0587a77bfde3

### Expected Behavior

I expected the progressbar to be removed and chosen things to still be visible when swiping back

### Steps to Reproduce

1. Create a new page
2. put a pageview there
3. create a component with some state variables that affect it and are changeable on-click (on my video its those question components where you submit your choice)
4. design a dynamic pageview that generates a progressbar (it doesnt even have to have any value or whatever, just basic progressbar) and the component
5. after choosing and swiping you can go back and see that the changes you made are somehow saved and the user can check what he did and what he had chosen on previous swipes
6. remove the progressbar
7. check once again and after every swipe the changes made on the child swipe before no longer exist and are generated once again from the variable (such as if state variables went initial/null and the component was just generated once again)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40i/Lq25BgrulA18/tbfpajic5Jml9RJINksB7aCosCJzwBIgcf/fOYkRvXfW/YH9EImD9kWoW3M74j9jlLMdcAySVfoRM+LVUUwndfEm5VY/QFJWge2h5O8pMGm3G1pjQrB4nPbF0SXghw2CQHueiRXbfGYz3OWssDa/LZO4=

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/171154385/3517fe04-378b-45d1-85d7-5b057c695607
Uploading WithoutProgressbar.mp4…

### Environment

```markdown
- FlutterFlow version: 4.1.61
- Platform: Web
- Browser name and version: Opera GX
- Operating system and version affected: Windows 11
```

### Additional Information

Im trying to make my pageview cache the chosen answers, so that the user can check what he did correctly. I dont want to persist them through log-ins but just for the time of use

**Comment by msusviela** [comment] 2024-06-21 10:25
Hey @ozehownik, Thanks for your report, So sorry you are experiencing this issue. I was not able to reproduce this on a blank project, but it is replicable on yours. That's why I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. Thanks so much!

**Closed as not planned** 2024-07-02 19:55 UTC
Labels: status: can't reproduce
