### ISSUE TITLE
Welsh Language not selectable on translation page

### ISSUE THREAD

**Issue by j-mcq** [FlutterFlow/flutterflow-issues#3581] opened 2024-08-07 21:25 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I would like to add Welsh as an app language on the Language Settings page. Welsh is supported by google translate so seems like an omission as there are lots of other languages in there with smaller number of speakers.

### Expected Behavior

Welsh to be selectable as a language on the Languages Settings page.

### Steps to Reproduce

1. go to the language settings page
2. click add language
3. try and find Welsh (or Cymraeg (Welsh for Welsh)) in the list

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ghcnf5ZJ2n7wA7qX2Ke9WlScQNWl9aq00sd4bGA0dCJzuPLMQdvWkfhRuXsPiT39qOUSmmnM03NbqufOeGO0qAAWVfN1xyZZuVAzKTkm7QZOBC8+sVnBCP5tRBUeO57Ww2xJDItR1Wmdk33GYFuu/TT3dGYTxIlFISq/LZO4=

### Visual documentation

<img width="992" alt="image" src="https://github.com/user-attachments/assets/c3c2f2df-7782-4355-9546-1ed42806357c">
![image](https://github.com/user-attachments/assets/74177c01-05f8-4d7a-b079-6934023b69c4)

### Environment

```markdown
- FlutterFlow version: v4.182+
- Platform: Web
- Browser name and version: Chrome 127.0.6533.90 
- Operating system and version affected: Windows
```

**Comment by Alezanello** [comment] 2024-08-07 21:52
Hello!

This GitHub Issue Tracker is meant for bugs that can be replicated from a new blank project. It looks like this is more of a feature/enhancement request. I will send this request to the engineering team's backlog and close this issue as it is not a bug. If you encounter any issues, please don't hesitate to create a new ticket!

Best regards,<br>Azanello

**Closed as not planned** 2024-08-07 21:52 UTC
Labels: closed: feature / enhancement request
