### ISSUE TITLE
Updating App State Breaks Json Lists? Update: ImagePath bugged when coming from JSON String

### ISSUE THREAD

**Issue by Josefpa** [FlutterFlow/flutterflow-issues#1352] opened 2023-08-25 04:06 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Add a tier in the add tier button, which will update the json and then that json will not render a list correctly, but if its being set from app launch the json works?

### Expected Behavior

For it to update

### Steps to Reproduce

Update a JSOn

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfhefqwItIn7wG15SIY+xWgmU4C1McTeU30+thcw4bI+KsPLQce+PSbVpuWOqHY1V+G1aKoEc1wfTpiYTPLcc7HwubRoBezJF9UxDvTmSgM7XRPc2KS3MmN/1RIFOM0LbYuSVAVfRaL1I91GCmJfO+b3qCf9qOYwx5e6fDbOY=

### Context

Cant add tiers :)

### Visual documentation

Dont have Just scroll and add Tier

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by Josefpa** [comment] 2023-08-25 04:07
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/67612575/3f3b1cab-2230-4d98-a3a0-8df81ad6a542)

**Comment by kevintonb** [comment] 2023-09-01 06:35
Hey @Josefpa , thank you for getting in touch. The current bug report code that you created does not have much information about the issue. Kindly add detailed explanation with more information about the issue that you're facing, and provide detailed steps to reproduce this issue in a new project. Please also include a new blank project with the issue setup as it would be helpful for us to isolate and troubleshoot the issue more effectively.

**Comment by Josefpa** [comment] 2023-09-12 04:04
Hey Hey, Sorry about the delayed response, have been working on different features and forgot about this one.. when ever I update json locally and have a JSON generator from that it seems to glitch out... I will look into it and try reporting a better bug report :)

**Comment by Josefpa** [comment] 2023-09-12 17:59
Yep getting this bug in other JSON list areas:

These areas worked before with no issues

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/67612575/7bed1b24-3a04-4fc4-842b-d899c8c7af1c)

**Comment by Josefpa** [comment] 2023-09-18 06:33
@kevintonb There has to be something wrong since when I update the code within the FF env itself like manually and reload it it works... with the generated JSON... but when the code does it I get the toList error.. copying that json and adding it again works?

Seems to be something to do with JSON generating children that gets updated

**Comment by Josefpa** [comment] 2023-09-18 15:29
Found it... Passing Image Paths as JSONs String breaks the To List

**Comment by Josefpa** [comment] 2023-09-18 15:32
Ex I have : https://i.ibb.co/hFbCn6Y/exampleImage.png

under $.image

which is being passed as a ImagePath

**Comment by Josefpa** [comment] 2023-09-18 15:54
Fixed with a simple Custom Function that converts the string to a image path string :)

`import 'dart:convert';
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:timeago/timeago.dart' as timeago;
import '../../flutter_flow/lat_lng.dart';
import '../../flutter_flow/place.dart';
import '../../flutter_flow/uploaded_file.dart';
import '../../flutter_flow/custom_functions.dart';
import '/backend/backend.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '/backend/schema/structs/index.dart';
import '/auth/firebase_auth/auth_util.dart';

String convertStringtoImagePath(String tehstring) {
  /// MODIFY CODE ONLY BELOW THIS LINE

  return tehstring;

  /// MODIFY CODE ONLY ABOVE THIS LINE
}
`

**Comment by Josefpa** [comment] 2023-09-18 16:58
Sorry closed it as for me but may be want to be fixed for the team still :)

**Comment by agreaves** [comment] 2023-09-22 22:55
Hey @Josefpa! Closing this for now as we still don't have enough information to really investigate (can't reproduce this from a blank project), and it sounds like the problem is already fixed on your end 🙂

**Closed by agreaves** 2023-09-22 22:55 UTC
Labels: status: needs triage, status: needs information, status: needs reproducible steps, needs a blank project with issue setup
