### ISSUE TITLE
FlutterFlow 5.0.1 (& 5.0) unable to compile custom action code

### ISSUE THREAD

**Issue by Supertecnoboff** [FlutterFlow/flutterflow-issues#3926] opened 2024-09-28 16:27 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Whenever I try to compile custom action code in FlutterFlow, it does NOT work and also does not state what the code specific errors are. I get the following (general) error:

> Unknown error compiling custom code. A common cause is a custom widget or action whose name in the code does not match the name provided in the editor.

Here is my code:

`// Automatic FlutterFlow imports
import '/backend/backend.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/custom_code/actions/index.dart'; // Imports other custom actions
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
// Begin custom action code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

Future<String> getFirstString(String text) async {
  // split string by empty spaces and get first string

  List<String> words = text.split(" ");
  if (words.isNotEmpty) {
    return words[0];
  } else {
    return "";
  }
}`

![Screenshot 2024-09-28 at 17 09 27](https://github.com/user-attachments/assets/069b46be-e489-4ea3-a9a1-9238a3cd99a5)

When pressing the Red Cross button, I get an empty list of code errors:

![Screenshot 2024-09-28 at 17 12 39](https://github.com/user-attachments/assets/8235689e-8110-443e-b683-27920d133ed0)

### Expected Behavior

1. Create custom action.
2. Write and save custom code.
3. Compile with no errors (or if there are errors, provide me with a list of actual code errors).

### Steps to Reproduce

1. Open custom code editor section.
2. Select "+ Add" button and select "Action".
3. Write custom code and set name, return value and parameters.
4. Save custom action.
5. Compile custom action.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48i87huJVNrsda1rrtbfpVniQUJj47bb8s1upuVUo8J5zKB+wAYvf7P1FWTL3id29AJU38knIz/Pfqv/DLE/oDAy6BG4c7yJNTFwrKWkGlVYTRO5GzfW1fJ+dRFVSj08OFqiUkLuhpZU4R3GaMe9yAfA/qK5jIDUcNLv21KdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

https://github.com/user-attachments/assets/9fca0be4-2640-4174-a2b6-bf076981eb39

### Environment

```markdown
- FlutterFlow version: 5.0.1
- Platform: macOS Sequoia 15.0
- Browser name and version: FlutterFlow desktop app for macOS
- Operating system and version affected: macOS Sequoia 15.0
```

### Additional Information

I am unable to compile any custom action code, it doesn't matter how simple or complex the code is, nothing complies.

**Comment by rzambroni** [comment] 2024-09-30 15:27
Hi @Supertecnoboff,

Thank you for bringing this to our attention. I tried replicating the same action on my end, and interestingly, it compiled correctly.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/1ebd86cf-f624-4eb9-ab87-7a835e5a03ec/55110e50-65fe-4fda-a034-16c3163171e3?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xZWJkODZjZi1mNjI0LTRlYjktYWI4Ny03YTgzNWU1YTAzZWMvNTUxMTBlNTAtNjVmZS00ZmRhLWEwMzQtMTZjMzE2MzE3MWUzIiwiaWF0IjoxNzI3NzEwMDQ2LCJleHAiOjMzMjk4MjcwMDQ2fQ.5AOLaa95Km5ligHGPjbiPWklrdb0sXABeE_pMhcc-m4 " alt="image.png" width="1437" height="903" />

<br>However, we're currently investigating this further as we've received a few similar reports. An engineer is already looking into it, and we'll keep you posted with any updates.

Thanks again for your patience and for reporting this!

**Comment by fsc-ethan** [comment] 2024-09-30 16:07
I am seeing a similar behavior with the custom code error.
When I try to build from my local machine (after cloning the GitHub repo) I get the following error. Not sure if they are related.

```bash
Launching lib/main.dart on Chrome in debug mode...
../../../../.pub-cache/hosted/pub.dev/image_picker_platform_interface-2.9.1/lib/src/types/picked_file/html.dart:30:38: Error: The method 'UnmodifiableUint8ListView' isn't defined for the class 'PickedFile'.
 - 'PickedFile' is from 'package:image_picker_platform_interface/src/types/picked_file/html.dart' ('../../../../.pub-cache/hosted/pub.dev/image_picker_platform_interface-2.9.1/lib/src/types/picked_file/html.dart').
Try correcting the name to the name of an existing method, or defining a method named 'UnmodifiableUint8ListView'.
      return Future<Uint8List>.value(UnmodifiableUint8ListView(_initBytes!));
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^
Failed to compile application.
```

**Comment by Supertecnoboff** [comment] 2024-09-30 16:14
@rzambroni Thanks very much for your swift reply, much appreciated. So is this only an issue with FlutterFlow desktop app? (As I have not used the FlutterFlow website in a long time, as the desktop app is much faster to work with). Thanks for your time.

**Comment by ShaneVC01** [comment] 2024-09-30 21:10
I get the same issue since yesterday. I have custom actions that was not modified and was working for weeks, and now I get this:

"Unknown error compiling custom code. A common cause is a custom widget or action whose name in the code does not match the name provided in the editor."

I am unable to deploy my latest update. 

This is a critical issue, please look into this ASAP.

Thanks

**Comment by ShaneVC01** [comment] 2024-10-01 01:53
I can confirm this started working again @mmearly , thank you!

**Comment by Supertecnoboff** [comment] 2024-10-01 14:52
@mmearly It's still not working for me, both in the FlutterFlow web app and the desktop app.

**Comment by Supertecnoboff** [comment] 2024-10-01 15:51
Just updated to FlutterFlow 5.0.2 and it's working perfectly! Thanks so much to the FlutterFlow team for fixing the issue.

**Comment by mmearly** [comment] 2024-10-01 23:28
Hey all! Sorry for the automatic closing/reopening. We have identified two things that can cause this issue; one has been fixed and merged in and the other is still in progress. Glad to hear that things are working again for some of you!

**Closed as completed** 2024-10-02 23:24 UTC
Labels: Bug, watched by support, Cherry Pick, Enterprise Cherry-Picked

**Comment by mmearly** [comment] 2024-10-02 23:27
The second fix has been merged in and will be available in the next release! 🥳
