### ISSUE TITLE
Checkbox Group Text Wrap Issue

### ISSUE THREAD

**Issue by syedabdullah90** [FlutterFlow/flutterflow-issues#2096] opened 2024-01-03 19:43 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a checkbox group which gets populated based on API Call results.
The text is overflowing in it and I have tried to remove the width of the container, hard code the width, looked at the community and could not find a good answer on how to wrap the overflowing text. Is this a bug in a widget?

### Expected Behavior

Wrap the text because the text is dynamic and text length is unknown. There should be a property called Wrap Text in the widget to solve this issue or it should be default behaviour.

### Steps to Reproduce

1. Create CheckboxGroup Widget wrapped in a container
2. Get dynamic results from an API or database
3. It will overflow the text out of the popup width.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wl/H1uI9On7xH7aqNdcFB/Cc4Ijt/U+cFisJEeCs/JJTxBIkIffT7PxZeOc+kSmNML2KjuHox+fDWhvzMA+UpOQ+tR4Ry1LtpWw7iJUmuSq2VDZGofUZQI+5JJVOP0J7UmRIlCNFZV1oQ12GMf+itVg7fGb7FO2w3BOSIOqXJ+lWrQ0SLb3kNh1JWeC/v

### Context

My client will click on an AI Icon, it will open a popup, they can get response from openAI API based on their input which I want to present them in a checkbox group so they can select multiple options.

### Visual documentation

![err](https://github.com/FlutterFlow/flutterflow-issues/assets/35668531/9a7d25a6-c3f4-4343-a39c-9cf7370da23f)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/35668531/072b9a45-5313-40c9-8c3e-ab2c1f6dac5c)

### Additional Info

Nothing

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: Desktop
- Browser name and version: Chrome latest version
- Operating system and version affected: Windows 10
```

**Comment by John-DreamLabs** [comment] 2024-01-03 20:11
following. This issue has been brought up a few times.

**Comment by wenkaifan0720** [comment] 2024-01-04 01:24
Hi all. This seems to be a duplicate of https://github.com/FlutterFlow/flutterflow-issues/issues/1378, which should be fixed in our next update. Thanks!

**Closed** 2024-01-04 01:26 UTC
Labels: type: bug, closed: fixed

**Comment by syedabdullah90** [comment] 2024-01-04 03:41
How soon can we expect the next push coz I need to deliver project to my client and it sucks to say him that I cant do anything.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by wenkaifan0720** [comment] 2024-01-05 00:01
@syedabdullah90. I can't give you an exact estimate. But it should be within a week.
