### ISSUE TITLE
Conditional checking API success/response is not working properly

### ISSUE THREAD

**Issue by aaahariri** [FlutterFlow/flutterflow-issues#1558] opened 2023-09-30 11:40 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have an action workflow triggered on a page load. The action contains:

**- API Call 1**
- Conditional for API 1 (Set to Succeeded directly)
- Code if True & False
**- API Call 2**
- Conditional for API 2
- Code if True & False

The problem is that the conditional for API1 is working fine and logic is executing. However, the conditional for API2, doesn't work at all. To make sure, I was able to successfully fire logic before conditional 2 but not within it. Yet, the API 2 is working fine because I am using it directly in a listview within the page!

For Conditional for API2, I tried the following:
- Succeeded (directly)
- Status = 200
- ItemsReceived >= 0
All without success and the conditional is not working!

### Expected Behavior

Conditional 2 should work and the logic within its true branch should work.

### Steps to Reproduce

1. Create a page with 2 API calls loading on page load.
2. Do conditional for API 1 and below it conditional for API2.
3. Check if conditional for API2 is working correctly.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4khc/1z4ZIvttH+rntbe1KjjkUKW48TL07ttYbZxUjIuPtBJh/evfsYVpCZ+7idGlhHGeL+UwD0t76huHPN+46Bw6sfItzyIdydgHxUXq8RbqtEbmeSHd7EtxVGW6j16Ss2h4lKfhYS0Y/312De9mUaBLYN5+/Zwh9f6PHaOI=

### Context

I am trying pass API 2 response when successful to a custom function so that I can set App state values based on a pre-defined custom data type.

### Visual documentation
[Video Explaining the Issue](https://www.dropbox.com/s/azvzwi9ftqpfh6v/FlutterFlow-ConditionalAPI2Bug.mov?dl=0)

[1](https://www.dropbox.com/scl/fi/ikar6jru2vwx9eu0w8gqs/Screenshot-2023-09-30-at-2.26.46-PM.png?rlkey=2pzjh6u50g1a1o8scpcznfm88&dl=0)

[2](https://www.dropbox.com/scl/fi/0y09kjsp40qcxgzeatlqj/Screenshot-2023-09-30-at-2.27.12-PM.png?rlkey=o29fwzyw0tw1ay75hd92b2a7l&dl=0)

### Environment

```markdown
- FlutterFlow version: V4.0.2
- Platform: MacOS FlutterFlow app
- Browser name and version:  Chrome 117
- Operating system and version affected: macOS Monterey
```

**Comment by aaahariri** [comment] 2023-09-30 11:58
I have added a snack bar to both sides of the conditional action, non are being triggered.
[Both branches of the conditional action are not working](https://www.dropbox.com/scl/fi/0oowpqjvpt3qmmwvtut70/Screenshot-2023-09-30-at-2.56.28-PM.png?rlkey=lkip9a0b15cdzx56mxax4d6s4&dl=0)

**Comment by aaahariri** [comment] 2023-09-30 21:51
I previously ran into some issues where I noticed that the Mac app might be causing some inconsistencies.
I just tested this for this issue, I edited the conditional for API2 from the FlutterFlow web app (Chrome) and it worked directly.

I guess I should rely less on the Mac app from now on...

**Comment by aaahariri** [comment] 2023-09-30 21:56
Another update, another possibility could be a custom action I am running within the true path, causing a blocker somehow?! The code is compiled without any errors though 🤔

**Comment by hariprasadms** [comment] 2023-10-01 13:51
Hi @aaahariri - Thanks for submitting the issue. We need a blank project setup with issue reproducible step details to investigate the issue. Please update the issue with the required details. Thanks

**Comment by hariprasadms** [comment] 2023-10-04 15:12
Hi @aaahariri - Any updates about blank project to show case the issue?. Let us know if issue is resolved for you, we can close the issue. Thanks

**Comment by hariprasadms** [comment] 2023-10-07 20:04
Hi, As there is no response, I presume the issue is resolved for you.  Hence closing the issue. Let us know if issue still persists and provide required details. Thanks

**Closed** 2023-10-07 20:04 UTC
Labels: status: needs triage, needs a blank project with issue setup, waiting for user response
