### ISSUE TITLE
Library database follow on bug... can't use library value defaults to pull schema

### ISSUE THREAD

**Issue by chuggmuffinReturns** [FlutterFlow/flutterflow-issues#4954] opened 2024-11-22 14:14 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

https://www.loom.com/share/3cc0d408868e44a3afcd65b3169bd8a0

Cant use library value defaults for Supabase schema download

### Expected Behavior

If we are going to be able to use libraries to extend database functionality then we need to be able to pull database schema from the library value defaults...

(I mean...... we could just do a whole delete - add - pull - delete - revert loop but that seems terrible)

### Steps to Reproduce

create library
create library values supaURL and supaAuth
enable supabase
set url and auth dynamically from library values
...nada

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wi87huIhgrsBE1rrUcMBviikQIjs6bZIw0u0bUis8GZT0B4kcYs+kfklUOe2+S2xie2CagnsX/MqKj4X9JMIoYAybG6Z/z81tWA7yZziXVbK6C5S3b2tTM8RTI3Kj0JmJuSVQWcB0WlIs2k+UHem+fDLfHqbQCzM4AOa4XdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

https://www.loom.com/share/3cc0d408868e44a3afcd65b3169bd8a0

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by Alezanello** [comment] 2024-11-22 22:17
**Hello!**

As mentioned in the related issue regarding Supabase and Libraries ([https://github.com/FlutterFlow/flutterflow-issues/issues/4953](https://github.com/FlutterFlow/flutterflow-issues/issues/4953)), this feature is not currently intended to be supported. The team is working on a fix to properly disable all Supabase features within Libraries.

I’ll go ahead and mark this issue as a duplicate of the one mentioned above for internal tracking and linking purposes. Thank you for your understanding!

**Closed as not planned by Alezanello** 2024-11-22 22:17 UTC
Labels: closed: duplicate
