### ISSUE TITLE
Dynamic property "Password Field" on Text Fields widget is not working

### ISSUE THREAD

**Issue by GersonFuentes** [FlutterFlow/flutterflow-issues#4372] opened 2024-10-22 00:49 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue..

### Current Behavior

Text Field > Additional Properties > Password Field:
If I choose to set this property dinamically, it doesn't work at all. Tried to set the value stored in an App State, Component State, Page State, depending from Conditions, even passing the value as a constant "True" or "False". Nothing worked. 

![image](https://github.com/user-attachments/assets/8c34ace2-48f5-4da1-b2cb-59de2d93f957)
![image](https://github.com/user-attachments/assets/d7036656-098b-4353-84f0-f988ffda9a96)
![image](https://github.com/user-attachments/assets/92b52544-d892-473d-bfad-39932a5e356c)
![image](https://github.com/user-attachments/assets/4707ee72-deb1-4e6e-a2c7-335f1160bba1)

The only way to set this property's value is through the classic switch (non-dynamic)

### Expected Behavior

Text Field Password Field property (boolean) should be set dinamically, but it is not taking this value. The property is always set by the value of the classic switch.

### Steps to Reproduce

1. Create new page
2. Create Text Field
3. Set dynamically the value on Text Field > Additional Properties > Password Field
4. Click Run
5. Observe the dynamic value is not taken for this property.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4elc/l34t1mOZE7c/Ab8dVnSQWNnInbZInlOxEEQwjF7bpPbM+ZOj+THdWUu3ifFZiJWGJmm01zPuNuOOWUME3HByJb4Rz+atuewnzVj6jWqqRBaqrP3QmP/JjGGKEzpuZqx0nOtpoWF0s7zu6HujKFyvDJ5yyITEROeWYKoLIjmiGHXnWGn0Jg1ZSfCvr

### Visual documentation

![image](https://github.com/user-attachments/assets/8c34ace2-48f5-4da1-b2cb-59de2d93f957)
![image](https://github.com/user-attachments/assets/d7036656-098b-4353-84f0-f988ffda9a96)
![image](https://github.com/user-attachments/assets/92b52544-d892-473d-bfad-39932a5e356c)
![image](https://github.com/user-attachments/assets/4707ee72-deb1-4e6e-a2c7-335f1160bba1)

### Environment

```markdown
- FlutterFlow version: Version 5.0.7 (5.0.7)
- Platform: MacOS Sequoia 15.0.1 and Windows 11.
- Browser name and version: Chrome 
- Operating system and version affected: Versión 130.0.6723.58 (Build oficial) (arm64) on MacOS
```

### Additional Information

I need to set this property dynamically, the same way I set other widgets and form fields in my project.

**Comment by Alezanello** [comment] 2024-10-22 12:17
Hello!

Thank you for bringing this up. It looks like this issue is a duplicate of the following: [GitHub issue #3663](https://github.com/FlutterFlow/flutterflow-issues/issues/3663). I'll link both tickets internally to ensure all the information is connected. However, I’ll be closing this ticket as a duplicate so we can focus on the original issue.

If you have any further questions or updates, please feel free to add them to the original ticket.

Thank you for your understanding!

**Closed as not planned** 2024-10-22 12:17 UTC
Labels: closed: duplicate

**Comment by GersonFuentes** [comment] 2024-10-22 12:22
@Alezanello GitHub issue #3663 is labeled as "waiting for user response" 3 weeks ago, opened 2 months ago, and is not having any progress at all, even other users have contributed to the issue.

**Comment by GersonFuentes** [comment] 2024-10-30 14:48
Why do you close it? How can it be "duplicated" if the #3663 is closed too? The original and the duplicate never got any solution. The bug exists already, and the 2 issues about it was closed with any valid reason. Why can't you fix it? @Alezanello

**Comment by GersonFuentes** [comment] 2024-10-30 14:49
> Hello!
> 
> Thank you for bringing this up. It looks like this issue is a duplicate of the following: [GitHub issue #3663](https://github.com/FlutterFlow/flutterflow-issues/issues/3663). I'll link both tickets internally to ensure all the information is connected. However, I’ll be closing this ticket as a duplicate so we can focus on the original issue.
> 
> If you have any further questions or updates, please feel free to add them to the original ticket.
> 
> Thank you for your understanding!

Why do you close it? How can it be "duplicated" if the #3663  is closed too? The original and the duplicate never got any solution. The bug exists already, and the 2 issues about it was closed with any valid reason. Why can't you fix it? @Alezanello
