### ISSUE TITLE
There is no error. But it shows an error and refuse to compile. How to re-produce the error.

### ISSUE THREAD

**Issue by thruthesky** [FlutterFlow/flutterflow-issues#242] opened 2022-12-19 06:02 UTC
I am spending like 4 hours to remove this error no - (1).

There is no error actually. I can run debug mode with this error indication. And I download the source code and it's running on locally.
I have 3 team members and all of them has no error indication. It appears on my end only. I have tried many things repeatedly like closing browser and signing again, changing web browser, etc.

Wish it gives a hint how I could get rid of it.

<img width="594" alt="image" src="https://user-images.githubusercontent.com/5080329/208357950-7642b532-44e2-41ff-9956-cb63e93d2c14.png">

---

After the struggling of 12 hours yesterday, and 6 hours today, ... I suddenly thought, It all happened with recent update.... and what I did on recent update?

Supabase.

I removed Supabase and the error `Custom Code error (1)` has gone now !! But I see different error.

---

After hours of struggling, we found that it's really Supabase that's causing the problem (in our case).
We have tested on many projects and found that every time we work with Supabase, the problem appears.

I have a video recording to re-produce the error and fix the error. We finally fixed and able to run the project after removing Supabase.
See the video below.

** How to Reproduce **

1. Add a custom action.
2. Set up Supabase.
3. Edit the custom action.

And you will see the `unknown error` or `custom action error`...

** How to Fix **

- To remove the Unknown error, simply disabling Supabase will NOT solve the problem.

1. Go to settings -> Supabase
2. Clear Schema
3. Disable Supabase
4. Compile again.

https://user-images.githubusercontent.com/5080329/208668021-6a908276-19a9-467b-a45e-32e1ec889e23.mp4

**Comment by Franco98404** [comment] 2022-12-19 21:45
I have the same problem, looks like a new bug from the last update, but in my case, I can compile and build the app

**Comment by agreaves** [comment] 2022-12-19 23:01
Hi @thruthesky and @Franco98404, this is a known error where users on Web vs Desktop currently cause the other to see this issue. Is someone on your team using Desktop and the rest Web or vice-versa? If so, we're working to fix this issue in the near future.

**Comment by thruthesky** [comment] 2022-12-20 01:07
> Hi @thruthesky and @Franco98404, this is a known error where users on Web vs Desktop currently cause the other to see this issue. Is someone on your team using Desktop and the rest Web or vice-versa? If so, we're working to fix this issue in the near future.

Since we found out that we cannot use the Web and the Desktop together, we only use Web. And When this error appears, we only use Web.

**Comment by thruthesky** [comment] 2022-12-20 01:10
Now, all of our team members see the error message.

<img width="470" alt="image" src="https://user-images.githubusercontent.com/5080329/208557950-add06de1-d767-409f-8512-752d09c4612e.png">

I will try to use the Desktop version.

**Comment by Franco98404** [comment] 2022-12-20 01:13
> Hi @thruthesky and @Franco98404, this is a known error where users on Web vs Desktop currently cause the other to see this issue. Is someone on your team using Desktop and the rest Web or vice-versa? If so, we're working to fix this issue in the near future.

All the team always use web browser

PD: Is the desktop version only available to Mac users?

**Comment by thruthesky** [comment] 2022-12-20 01:38
The symptom is that, After I edit the custom action or widget, I can run without compiling. ( I cannot compile anyway ).


https://user-images.githubusercontent.com/5080329/208560920-cf03d655-196f-4f0f-8aa5-48bc452bf45c.mp4

**Comment by thruthesky** [comment] 2022-12-20 08:28
After the struggling of 12 hours yesterday, and 6 hours today, ... I suddenly thought, It all happened recent update.... and what I did on recent update?

Supabase.

I removed Supabase and the error `Custom Code error (1)` has gone now !!

**Comment by jamie-syon** [comment] 2022-12-20 10:20
Also had the same issues yesterday when trying out Supabase with an existing project.   
 Thought it was the "supbaseSignUp" custom action I created so deleted it, no luck.  Turned off Supabase but still has the issue until about 10am (UK time) this morning when after a few goes it finally worked.

Then added Supabase back and created a new custom action "supabaseSignUp" I am back to an "unknown error" when compiling.  I should also add that even though I get this unknown error I can still compile locally.

**Comment by thruthesky** [comment] 2022-12-20 11:32
I am still struggling. It's not getting worse.

I cloned and set up a copy project.

I deleted the custom widgets and the custom actions one by one to find which causes the error.

I deleted from the last and compile, and delete the last again and compile, and do it again until I delete all the custom actions and widgets. It really took me hours and I got rid of errors when I delete the last one.

So, I cloned and set it up again and delete the first one and see if the error goes away.
But after I delete the first one, the error still appears.

So, I deleted the custom widget and actions one-by-one again from the first to last.
And when I deleted the last custom action, the error goes away.

And I add a simple action. And the error appears. When there is no error, it gives error and refuse to run.

It's not running debug run mode anymore.

See the video that I recorded. Me and my team spend lots of time on it. :(

Again, we only use Web UI Builder at this moment.

https://user-images.githubusercontent.com/5080329/208657140-498e6c0a-674c-4044-94d4-201b7f3ce4a4.mp4

**Comment by jamie-syon** [comment] 2022-12-20 11:37
I don't think its your code, I think its a problem with FlutterFlow.

My custom actions have been the same since last week and I still get the "Unknown error" when trying to compile.  I can also download the code and compile locally without a problem.

I'm speaking with Flutterflow at the moment, will and an update here as soon as I know more.

**Comment by thruthesky** [comment] 2022-12-20 12:32
I have a video recording to re-produce the error and fix the error.

** How to Reproduce **

https://user-images.githubusercontent.com/5080329/208668021-6a908276-19a9-467b-a45e-32e1ec889e23.mp4



1. Add a custom action.
2. Set up Supabase.
3. Edit the custom action.

And you will see the `unknown error` or `custom action error`...


** How to Fix **

- To remove the Unknown error, simply disabling Supabase will NOT solve the problem.

1. Go to settings -> Supabase
2. Clear Schema
3. Disable Supabase
4. Compile again.

**Comment by jamie-syon** [comment] 2022-12-20 12:54
Confirmed.  Clearing the schema before disabling Supabase worked for me, just disabling Supabase did not.

So Supabase is a no-no for now then which is sad as I was excited to try it

**Comment by thruthesky** [comment] 2022-12-20 12:56
@jamie-syon Hope there is a way to debug/find problems easily. :)

**Comment by jamie-syon** [comment] 2022-12-20 12:58
@thruthesky I have just spent an hour on live chat with Flutterflow, I have given them this issue as a reference and confirmed that your "fix" does work in that the Supabase integration is causing the problem.

Will have to leave it with them....

**Comment by agreaves** [comment] 2022-12-21 01:42
Hi @thruthesky and @jamie-syon, thanks for the information. I believe I know the issue, but as I'm not able to reproduce I need some help. Would one or both of you mind adding Supabase back to recreate the issue, and then generating a Bug Report Code and responding with it? This info helps us debug issues much more easily.

Of course, after generating this feel free to remove Supabase again in the meantime, but I'd need the bug report code with it on. Thank you very much!

**Comment by thruthesky** [comment] 2022-12-21 02:23
Hi, @agreaves I am not sure what to do to generate `a Bug Report Code`.

I just have created a new project and reproduced the same error.
I made the project public.
You may clone the project: https://app.flutterflow.io/project/test-zucn5p

**Comment by thruthesky** [comment] 2022-12-21 07:10
Hi, @agreaves Bug Report Code
ITESz/Hqx89grv0B7c+MKMBAhQIgQ0QnU7gnlO1ucx43IZOsP5Y2Pc7BcUNKTt+5TwhmAlGanlED/vzKvfHiFew3HASYb6JEk/UwKlCvHAM=

**Comment by jamie-syon** [comment] 2022-12-21 09:50
Hi @agreaves 

Here you go:

ITFXz8jfz5R1rsRE+7X+L+xVgjowGUQFUOdEl95Hd0gdCOPrBuwlO+OkQFhBZO7haVNcBWClkT8J+PD0kuPxK8I6KTueUaJFz6gBawvmKTbkEuzyT+3IHDUHZbsSXTTm

Cleared the Supabase schema and disabled Supabase and can now compile again.

**Comment by Franco98404** [comment] 2022-12-22 06:22
![image](https://user-images.githubusercontent.com/36147203/209070071-f3f9d3a4-e7c6-4529-93de-8700622ff557.png)

With this update I have this error and I can't compile. Please fix it as soon as possible because we can't develop our app properly

Bug Report Code:
IT4ohfKA4YlOxPVd0a6IY+1omSQXOVg1R5IV0cpBZywgfZzzBLN/fPfQPltWOdfjSkFte2eMp14ep9r5vobTCe5eCxSdGapJ/5YMVT3gRnulb6XfU/HUACkbeacOQSj6

**Comment by agreaves** [comment] 2022-12-23 07:49
Thank you all for the Bug Report Codes!! They were all super helpful and I've identified the issue. This will be fixed upon our next deploy!

**Closed by agreaves** 2022-12-23 07:49 UTC
Labels: status: needs triage

**Comment by Franco98404** [comment] 2022-12-23 08:00
Meanwhile I share a workaround that my coworker found to generate a test or build!

[2022-12-23 00_43_47.zip](https://github.com/FlutterFlow/flutterflow-issues/files/10293433/2022-12-23.00_43_47.zip)

**Comment by gasserwshalaby** [comment] 2023-05-20 02:25
the issue is still here, and. here is the bug report code

IT4Chcr1sM9Pj7xe7arUbPlVnSQWCDsmRYIWmNZDdw4jDZPMC+wIZ/f7XFRuTde0SglDMVmGp3Ee0P/emvHfN8IqIUmbGK4/1bhcZDvMWTuiMLqJO7WeOG5/DZ9NCmqa57eF3SV5JtdhSFI622D7GvDIFxfDNO/RIjE7JPyaOZCK2SrDX1iXc2URm05KZDPz

**Comment by MainStreetTech** [comment] 2023-06-05 00:54
Yep, locked up trying to complete this app, might have to switch back to firebase? hopefully this is a fast turn around! :)  I am using Supabase Auth as well fyi

Bug Report: 
IT4si/Ll5YpgrsMA15DudcdB/T4RHFh9ap0kscpCbw4bIYj2P4lzY876P0htcOGoYFVIM1qmp14Dpc3HuOzlJPYECwWbR65/zKVcEw7MQmG7V5eTF7ioYH9AO9pWCBWX0LTYvCRQBPd2WkFm32GEPu6XcHPYJ5DsIlQ8Sq/LZO4=

**Comment by amiel-danao** [comment] 2023-07-10 15:43
> Meanwhile I share a workaround that my coworker found to generate a test or build!
> 
> [2022-12-23 00_43_47.zip](https://github.com/FlutterFlow/flutterflow-issues/files/10293433/2022-12-23.00_43_47.zip)

what work around?
The video shows only the bug?

**Comment by amiel-danao** [comment] 2023-07-10 15:44
> Thank you all for the Bug Report Codes!! They were all super helpful and I've identified the issue. This will be fixed upon our next deploy!

Obviously this still not fixed yet, almost half a year later

**Comment by mamadouramadan723** [comment] 2023-07-24 19:21
This is very helpful
https://stackoverflow.com/questions/75564859/flutterflow-unknown-error-compiling-custom-code
