### ISSUE TITLE
Beautiful Crash every time when removing a row

### ISSUE THREAD

**Issue by ivantodorov78** [FlutterFlow/flutterflow-issues#2705] opened 2024-04-11 20:11 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Removing a row widget incorrectly puts input text field at the bottom of the tree inside a container instead of as a child of parent component. Attempt to remove the grey container crashes the entire app every time

### Expected Behavior

Remove row and text input field remains in column widget. 

### Steps to Reproduce

see video, you have permission to look at the project. https://us06web.zoom.us/clips/share/Cqu-eAuqdV-y8miFTY1cb2DhuXx65rG-eDIRBwqWAmig7AfgSJpuZ2FT9-xbrw92eoM4nUE8pW1CBs8vqOL1Rdk0.ZqLohC3BLTz_0C04

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wjM/luJNOm7RK1aXqLO9ViicWMjp6ROY00O5uRis9CZDoOu9/ZeCkfhNVOdOmYWlhHFr9rE0Fw6DGheHqGMc4MgWcftlm1c9UeAvyTXq8SpvXPpOWQmhfGfpVGGqs352rhApCIsRZS04F6lOYANnLaBLXCZ+/Zwh9f6PHaOI=

### Context

i was optimizing my UI by simplifying the widget tree 

### Visual documentation

https://us06web.zoom.us/clips/share/Cqu-eAuqdV-y8miFTY1cb2DhuXx65rG-eDIRBwqWAmig7AfgSJpuZ2FT9-xbrw92eoM4nUE8pW1CBs8vqOL1Rdk0.ZqLohC3BLTz_0C04

### Environment

```markdown
- FlutterFlow version: 4.1.39
- Platform: macOS
- Browser name and version:Safari 
- Operating system and version affected: mac
```

**Comment by rzambroni** [comment] 2024-04-11 22:44
Hey @ivantodorov78, i'm taking a look at the issue but i could't find the Row you are referring too in the vid. 😅 (see screenshot)<br><br>Where you able delete it?

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/c5361c4a-0dfb-4716-a930-b9912e2cb973/38e5d22f-3841-431c-b402-5d7d557157f9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jNTM2MWM0YS0wZGZiLTQ3MTYtYTkzMC1iOTkxMmUyY2I5NzMvMzhlNWQyMmYtMzg0MS00MzFjLWI0MDItNWQ3ZDU1NzE1N2Y5IiwiaWF0IjoxNzEyODc1NDcwLCJleHAiOjMzMjgzNDM1NDcwfQ.IzQFGaMelKX5RQXKgqo7JgRCgfORMLiPvGXi7_zZOTU " alt="image.png" width="2544" height="1331" />

**Comment by ivantodorov78** [comment] 2024-04-11 22:51
Yeah I had to work around it by adding a container above the column and it let me properly delete them.

___

*Ivan Todorov* | (310) 266-7533 | Calendar ( https://app.hubspot.com/meetings/ivantodorov/30m-1h-2h ) | LinkedIn ( https://www.linkedin.com/in/ivantodorov/ )

**Comment by rzambroni** [comment] 2024-04-11 22:54
That was an odd one for sure. Could you please let us know if you happen to run into it again? will close this for now as we will not be able to replicate it.

Thanks.

**Comment by ivantodorov78** [comment] 2024-04-11 23:07
this happens often to me, seems the page widget gets corrupted with certain action patterns or states. I’ve lost half pages worth of widget tree and had to rebuild multiple times. We can reproduce it by going back to that time snapshot, happy to do it on zoom if you are unable to go back in time without me

___

*Ivan Todorov* | (310) 266-7533 | Calendar ( https://app.hubspot.com/meetings/ivantodorov/30m-1h-2h ) | LinkedIn ( https://www.linkedin.com/in/ivantodorov/ )

**Comment by rzambroni** [comment] 2024-04-11 23:09
Ideally, it would be great if you could replicate this in a blank project so we can isolate it from project-specific issues. And we can send that bug report code over to the team to verify it.

**Comment by ivantodorov78** [comment] 2024-04-12 02:38
Hey there,

I found another place this is taking place, I haven't fixed it yet so you guys can take a look at the live project:

Page:

https://app.flutterflow.io/project/lumenosity-app-93r6hh?tab=widgetTree&component=TaskItem

Crashbug Code:

IT4wjM/luJNOm7RK1aXqLO9ViicWMjp6ROY00O5uRis9CZDoOu9+PMykXExvTdO8T0NhHFSjgmMH3Pz9i97mG8A4PSibQIB/yM9idgzNf3q8SpvXPpOWQmhfGfpVGGqs352rhApCIsRZS04F6lOYANnLaBLXCZ+/Zwh9f6PHaOI=

Please keep me posted on what you find, as I mentioned earlier this bug has corrupted my "file" in the past and would be great to eliminate.

___

*Ivan Todorov* | (310) 266-7533 | Calendar ( https://app.hubspot.com/meetings/ivantodorov/30m-1h-2h ) | LinkedIn ( https://www.linkedin.com/in/ivantodorov/ )

**Comment by ivantodorov78** [comment] 2024-04-12 03:50
Please also take a look at this as it may be related to the issue we're discussing:

https://us06web.zoom.us/clips/share/dycJjUw4UkqkUs-IqjC_4cfFzZWHifE7c__tMrE2F3hK3setaK19MmLGAHW2CxS2oc0eSVylm4Yk1WxvsZ7lfRk-.aaL4zfvWjNhYcY9y

___

*Ivan Todorov* | (310) 266-7533 | Calendar ( https://app.hubspot.com/meetings/ivantodorov/30m-1h-2h ) | LinkedIn ( https://www.linkedin.com/in/ivantodorov/ )

**Comment by rzambroni** [comment] 2024-04-12 13:09
Hey @ivantodorov78, thanks for the details, 

> Page:
>
> [https://app.flutterflow.io/project/lumenosity-app-93r6hh?tab=widgetTree&component=TaskItem](https://app.flutterflow.io/project/lumenosity-app-93r6hh?tab=widgetTree&component=TaskItem)<br><br>Crashbug Code:
>
> IT4wjM/luJNOm7RK1aXqLO9ViicWMjp6ROY00O5uRis9CZDoOu9+PMykXExvTdO8T0NhHFSjgmMH3Pz9i97mG8A4PSibQIB/yM9idgzNf3q8SpvXPpOWQmhfGfpVGGqs352rhApCIsRZS04F6lOYANnLaBLXCZ+/Zwh9f6PHaOI=

The link and bug-code are redirecting me to the login and i could not find a component called TaskItem, were you referring to TaskItemDetail?<br><br>If that's the case i was able to delete the DetailsRowRow inside the Expanded column, it didn't an error.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/294a8f38-8b53-44c7-958f-39d05a82ad37/6752f5b5-822b-40d4-af1c-9ddafcb59ea5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yOTRhOGYzOC04YjUzLTQ0YzctOTU4Zi0zOWQwNWE4MmFkMzcvNjc1MmY1YjUtODIyYi00MGQ0LWFmMWMtOWRkYWZjYjU5ZWE1IiwiaWF0IjoxNzEyOTI3MzU5LCJleHAiOjMzMjgzNDg3MzU5fQ.-RGYuFNrGENFuAnANMQM14JI8C8gzU_dI58ZXkRbIDA " alt="image.png" width="1637" height="1373" />

**Comment by ivantodorov78** [comment] 2024-04-12 14:15
Hi there, after the issue persisted I ended up rolling back a bit and re-building/cleaning up the widget tree. I think what I'll do next time is clone the component and see if I can preserve a broken tree that way, the challenge has been that I have to keep building and not in a position to leave things in a non-working state, I was secretly hoping that FF has the ability to take a look at an issue from a time snapshot of the project. An you share a bit about what Crashbug code is/does?

___

*Ivan Todorov* | (310) 266-7533 | Calendar ( https://app.hubspot.com/meetings/ivantodorov/30m-1h-2h ) | LinkedIn ( https://www.linkedin.com/in/ivantodorov/ )

**Comment by ivantodorov78** [comment] 2024-04-12 23:43
Hi, me again,

Take a look at this video, when I try to wrap the TokenBalance text field in a Container, it remove my TokenBalance Text from the widget tree. It appears the removal is visual only, when I reload the app it's still there.

https://us06web.zoom.us/clips/share/jFvSCqB31LFY9kx3EJuVqh7rmu-5NlxptAmJxA6rX8jSqD5Q3w9ZVjQ6gdmHignER0dNYBs_pUHnyclbybKwDUcK.-NiRg10bwCAsWEns

Then I also found this bug, whenever I come back form a walkthrough, the FlutterFlow stage gets the grey box:

Take a look:

https://us06web.zoom.us/clips/share/vX0Iwf7H-Yc9g5o0V0SGDiX0oQ_6eQ0eBndM9oqDhfBOx_0eUgtLoYwgVzfHaTa6fm5jfF7LH6UFOX-lWz__wntq.aEnYDD6PRdqMXEl2

___

*Ivan Todorov* | (310) 266-7533 | Calendar ( https://app.hubspot.com/meetings/ivantodorov/30m-1h-2h ) | LinkedIn ( https://www.linkedin.com/in/ivantodorov/ )

**Comment by leighajarett** [comment] 2024-04-13 11:30
Hi there, sorry but we are unable to reproduce this bug from a blank project. Can you please reach out to our support team? They can help troubleshoot project-specific errors. <br><br>Thanks so much and sorry you're running into these issues!

**Closed by leighajarett** 2024-04-13 11:30 UTC
Labels: status: can't reproduce
