### ISSUE TITLE
Email authentication with Firebase is not working, deleted user can still login

### ISSUE THREAD

**Issue by jessieplaydatecare** [FlutterFlow/flutterflow-issues#1661] opened 2023-10-19 06:02 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Deleted user can still login. 

### Expected Behavior

Deleted user can not login unless a new account is created. 

### Steps to Reproduce

1: Create sign up page with email authentication action set up, and create a new user
2: Set up firebase and make sure users collection is getting data from the test mode
3: Delete user document from flutterflow and firebase, clear cache, restart the computer
4: Try to login again with the deleted user account

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KiMn1z8pgod9Y0LrtbfowiikvIjsnap08lut+Z0scGIjyG7YAW/SkQE9WZ7yhdH02fWGakj8Jp8LPv8zIN8A5OQuAfqk51sxiVhbiJTuQacm0DauKW3NTPNpKCFCC0ImskSNdNsl2cXga7Ey6AuuAZDfaGYTwCkgFR8mbIqT7nXPuQ0SLb3kNh1JWeC/v

### Context

This could be a P1 issue since deleted user can still login
Also I tried to login with one user and set the userRef/Email, the userRef seems messed up as well, it shows different value. 

### Visual documentation

N/A

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Mac Book Pro
- Browser name and version:Chrome
- Operating system and version affected: Mac 11.7.10
```

**Comment by SameerShahzad99** [comment] 2023-10-20 20:02
Hi, @jessieplaydatecare I tried reproducing this issue on my side and it appears to be working fine.

**Comment by sbis04** [comment] 2023-10-25 03:37
There seems to be an issue with the cloud function to delete the user document from Firebase. So, currently the actual user deletion from Firebase Auth is working fine but the respective user document is not getting deleted because of some issue with the cloud fn. I'll investigate more into the issue.

**Comment by jessieplaydatecare** [comment] 2023-10-25 04:14
Thank you @sbis04 @SameerShahzad99 for investigating the issue.

**Comment by katherineqian** [comment] 2023-12-08 23:19
Hi, this issue will be fixed in the next version!

**Closed by katherineqian** 2023-12-08 23:19 UTC
Labels: type: bug, status: confirmed, priority: medium
