### ISSUE TITLE
Letter spacing for text isn't working

### ISSUE THREAD

**Issue by rikark** [FlutterFlow/flutterflow-issues#1084] opened 2023-07-07 10:21 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Letter spacing for text (inside button widget or regular text widget) isn't changing when a value is added to the 'Letter spacing' field 

### Expected Behavior

Letter spacing changes depending on the value in the  'Letter spacing' field 

### Steps to Reproduce

1. Create a text widget or button widget
2. Add some text
3. Add a value to the 'Letter spacing' field 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KhvHl049Itbxa1s+NdMJVqGEWHEx/a+Y0ltVud04YF5+sG7YAW/SkQE9WZ7yhdH03IEyJrDkz+a3TvszIN/Y7NUyCfoha/pZQVgzgUlKRaaa3Ec+sdEZQQdpKC0i91KTU3CUnNrdvLUI77GWEOfK8bz/ZJbKzOFQdRv6hKqfUo3fuQ0SLb3kNh1JWeC/v

### Context

Make text pretty

### Visual documentation

<img width="1022" alt="Screenshot 2023-07-07 at 12 16 18" src="https://github.com/FlutterFlow/flutterflow-issues/assets/91953140/01d0fb8d-31c4-4890-b9d6-2e70a9a80cef">

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: MacOS web
- Browser name and version: Chrome Version 113.0.5672.126 (Official Build) (arm64)
- Operating system and version affected: 13.2.1
```

**Comment by hariprasadms** [comment] 2023-07-07 11:37
Hi @rikark - Thanks for submitting the issue. I can see the issue in your project. However, I can confirm that letter spacing in general working as expected. It appears to be an issue specific to your project.

**Comment by wenkaifan0720** [comment] 2023-07-07 14:29
Hi @rikark. This is due to the fact that the font you use does not support letter spacing on the web yet. If you run your app on mobile, the letter spacing will be shown correctly. Since this is not something we can fix. I'll close this issue for now. Thanks.

**Closed by wenkaifan0720** 2023-07-07 14:29 UTC
Labels: status: confirmed, closed : project specific, status : project specific
