### ISSUE TITLE
test mode fails

### ISSUE THREAD

**Issue by bitgandtter** [FlutterFlow/flutterflow-issues#3160] opened 2024-06-17 17:34 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

test mode does not open after debug feature relased

### Expected Behavior

to works

### Steps to Reproduce

run any project on test mode

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

NA

### Visual documentation

![Screenshot 2024-06-17 at 12 30 22 p m](https://github.com/FlutterFlow/flutterflow-issues/assets/1316125/bbd663fb-b921-41f7-9fd2-38a442fb510a)

### Environment

```markdown
- FlutterFlow version: 4.1.60
- Platform: Mac
- Browser name and version: Mac APP
- Operating system and version affected: Mac
```

**Comment by msusviela** [comment] 2024-06-17 18:50
Hey @bitgandtter, Thanks for your report, So sorry you are experiencing this issue. I was not able to reproduce this on a blank project, but it is replicable on yours. That's why I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: support@flutterflow.io or using the in-app chat inside of FlutterFlow. I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. Thanks so much!

**Closed as completed** 2024-06-17 18:50 UTC
Labels: status: can't reproduce

**Comment by bitgandtter** [comment] 2024-06-17 18:51
That's the thing. I have written support with no reply, and we are playing for the platform, holding back our developers to keep working. This is starting to get annoying.

**Comment by leighajarett** [comment] 2024-06-17 21:57
Sorry that you haven't heard back yet, we're following up and will get back ASAP!

**Comment by wenkaifan0720** [comment] 2024-06-17 22:49
Hi @bitgandtter. Could you provide a bug report code so we can look further into your project? Thank you!

**Comment by bitgandtter** [comment] 2024-06-18 02:38
sure ticket id 3367

**Comment by leighajarett** [comment] 2024-06-18 13:25
Got it, thanks! This issue has been fixed and will be deployed later today. Closing out the issue but please feel free to add a comment or reach back out if the issue persists tomorrow
