### ISSUE TITLE
Using a Supabase Row from a parameter page throw an "Unexpected null value"

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#289] opened 2022-12-27 22:54 UTC
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

I should use the data from the Supabase row along the page

## Current behavior (required)

If I use the data from the Supabase row throw an error

## To Reproduce (required)

1. Create a new page named "Page 1"
2. Create a new page named "Page 2"
3. Set as parameter a Supabase Row in the "Page 2"
4. In the "Page 1" create a button to navigate to "Page 2" and pass a Supabase Row
5. In the "Page 2" create a text widget and set as Initial Value any value from the Supabase Rom
6. See the error in the screenshot section

### Bug Report Code (required)

IT4ohfKA4YlOxPVd0a6IY+1omSQXOVg1R5IV0cpBZywgfZzzBLN/fPfQP09CTuGkSnxffWaMp141+t7Hv87xLPUnPU6ZQLpZwZFTWAvzd3O5abXfU/HUACkbeacOQSj6

## Context (required)

I want reutilize the data from a Supabase Row from a previous page

## Screenshots / recordings

![image](https://user-images.githubusercontent.com/36147203/209731510-a13c509b-ee16-4607-9b76-720f3c8cc313.png)

## Your environment

* Version of FlutterFlow used: 26 December
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (64-bit)
* Operating system and version (desktop or mobile): Windows 11 - 22H2 - Os build: 22621.963

**Comment by agreaves** [comment] 2022-12-27 23:32
Hi @Franco98404, I haven't been able to reproduce this in any of my Supabase projects. Can you add a Bug Report Code for the specific widget that you're setting from the Supabase row?

My initial guess is that when the row is not passed in (`null`) there is a null error being thrown when it tries to access a field.

**Comment by Franco98404** [comment] 2022-12-27 23:50
Hello, that is strange because I created another project and I have the same problem, here is the Bug Report Code:

IT4ohfKA4YlOxPVd0a6IY+1omSQXOVg1R5IV0cpBay0jF7KuDLMqY8/RVERuOO2kT1ZmfU6WgWoW0fvIifPtFvQDG0uuc4BFyJBQcDrKJXOnR7aJU/HUACkbeacOQSj6

Meanwhile I will create another project only with this problem and will share you another Bug Report Code

**Comment by Franco98404** [comment] 2022-12-27 23:55
Here is the Bug Report Code from another project:

ITESz/Hqx89gobUD0LXhKPlQhR4jNlx7bZNF0dVua0saF4ztEJwpWv7RblJYZ/arfwl9eVeKoDkEpNb2ud79CsAVHEDDJ+AHl/E0LlSrGAc=

**Comment by agreaves** [comment] 2022-12-28 00:31
Thanks for the test project! It looks like the issue is arising when you don't pass in the Row. This causes its value to be null and then when you try to access one of its fields it throws a null error. Typically, the fix is to add a default value so you have a fallback. However, we have a bug on our side that's making the default value still access the field using `!` which will still cause issues, but this is now fixed.

So if you use a default value for wherever you access this Row, this will be fixed in the next release!

**Closed by agreaves** 2022-12-28 00:31 UTC
Labels: status: needs triage
