### ISSUE TITLE
List is Set and Not Empty Build Error

### ISSUE THREAD

**Issue by sanchez-gonzalo94** [FlutterFlow/flutterflow-issues#1969] opened 2023-12-06 14:03 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am receiving a list (required) of a custom datatype in a component. In a conditional builder inside this component I am checking if the  list is 'List is Set and Not Empty'. When trying to build to test this component I get a build error. 

Note: This is not a custom widget where I can modify the code. 

```
Launching lib/main.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...      
lib/pages/profile/components/user_profile_earth_images/user_profile_earth_images_widget.dart:55:63: Error: Property 'isNotEmpty' cannot be accessed on 'List<EarthImagesStruct>?' because it is potentially null.
 - 'List' is from 'dart:core'.
 - 'EarthImagesStruct' is from 'package:carbon_pledge/backend/schema/structs/earth_images_struct.dart' ('lib/backend/schema/structs/earth_images_struct.dart').
Try accessing using ?. instead.
        if ((widget.earthImages != null && widget.earthImages.isNotEmpty) !=
                                                              ^^^^^^^^^^
lib/pages/profile/components/user_profile_earth_images/user_profile_earth_images_widget.dart:19:34: Context: 'earthImages' refers to a property so it couldn't be promoted.
See http://dart.dev/go/non-promo-property
  final List<EarthImagesStruct>? earthImages;
```

### Expected Behavior

I should expect to be able to build this. 

I created a custom function that did this exact same check ` earthImages != null && earthImages.isNotEmpty` and the app build successfully. 

### Steps to Reproduce

1. Create a new datatype with attributes (does not matter).
2. Create a component and set a parameter to receive a list of this custom datatype.
3. Create a Conditional Builder inside this component and set the clause "List is set and not empty" for the parameter. 
4. Add some widget inside the conditional builder.
5. Add the component to a blank screen and set the parameter.

To test the correct functionality instead of setting the conditional clause from the UI create a custom function testing (!= null and isNotEmpty) and add the custom function to the conditional clause. This will pass. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40lfLqw5ZOxLlE17rAdflFqDw5JlAma4IRl+5RaBoofePrBJkqP8zBP1dVXf2RSmxiOlmJnnIIp+jRkofLE8JcNQuIQ75E+LhUVAKWWXymaK66DbmwXXJ5Ed1gJ3a75IqOihR+Psxvc1YswDubONiRXnbvO7rUNVgZLfGJNrzL+WCKFQ7VGjhQtmNecCfn

### Context

I am trying to create a component that will conditionally build a wrapped widget of images if the a list of a custom datatype (containing image paths) is != null and not  empty. 

If its empty than set a default image. 

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/13091858/8fecdfc9-95e5-409d-8f6a-e6c0a9faec69)

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: Mobile
- Browser name and version: Chrome Version 119.0.6045.199 (Official Build) (64-bit) 
- Operating system and version affected: Linux Mint 20.1
```

**Comment by wenkaifan0720** [comment] 2023-12-07 20:03
Closed as a duplicate of https://github.com/FlutterFlow/flutterflow-issues/issues/1965

**Closed by wenkaifan0720** 2023-12-07 20:03 UTC
Labels: status: duplicate, closed: duplicate
