### ISSUE TITLE
image uploads on Windows APP do not work

### ISSUE THREAD

**Issue by gigbuilder** [FlutterFlow/flutterflow-issues#3087] opened 2024-06-09 17:35 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When trying to upload a JPG image generated by GIMP using the Windows app (current as of today) I try to drag and drop -- it gives an error of a bad file type.  I try to upload with the button and receive a notice that it is uploading but nothing happens.  If I switch to the web-app it uploads without an issue.

### Expected Behavior

should be able to drag and drop an image into a project using the windows app.

### Steps to Reproduce

Click RESOURCES from the windows app and try to upload a JPG image

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

there is no bug report code -- just an app that isn't working propery

### Visual documentation

try to drag and drop - red error message -- try to upload -- popup shows progress but nothing is uploaded -- switch to chrome and web-app, works fine.

### Environment

```markdown
Current Flutterflow Windows edition I believe was updated in May on a PC using the app downloaded from your website.
```

### Additional Information

none

**Comment by rzambroni** [comment] 2024-06-10 13:08
Hey @gigibuilder, thanks for the report, this is a known issue and it is already on the team's backlog to be fixed. You can use the web app as a workaround in the meantime.

Please note that this bug also affects other functionalities like custom icons, custom fonts, or attempting to upload a sqllite database from the windows app.

Closing this as duplicate of: [https://github.com/FlutterFlow/flutterflow-issues/issues/2728](https://github.com/FlutterFlow/flutterflow-issues/issues/2728)

**Closed as not planned** 2024-06-10 13:08 UTC
Labels: closed: duplicate
