### ISSUE TITLE
Swipeable Stack Current Element

### ISSUE THREAD

**Issue by tadamtech** [FlutterFlow/flutterflow-issues#421] opened 2023-01-30 13:31 UTC
## Expected behavior (required)
I want to display a movie list in a swipeable stack. When I swipe left or right, I want the value of a property (**tmdb_id**) in the movie table to be added to a list associated with the connected user (seenMovieTmdbId). This allows me not to display in the swipeable stack a movie already swiped by the connected user.

## Current behavior (required)
When the user swipes, the property retrieved is not that of the displayed movie but that of another movie present in the swipeable stack.

## To Reproduce (required)
1. Create new page
2. Add swipeable stack
3. On Scaffold, add a collection query type on Movies having one field called **tmdb_id**, with no filter
4. On swipeable stack, generate children for the previous query, filter list -> seenMovieTmdbId (from authenticated user) list does not contain item in list (tmdb_id property).
5. On swipeable stack, add an action on Widget Swipe. Update current user document and add Swipable Stack Current Element (property tmdb_id) to list seenMoviesTmdbId. 
6. Run
7. When user swipes, it does not retrieve the tmdb_id of current element.

### Bug Report Code (required, generate from Widget Tree)
ITEez/Hl38lPn70C1c/QdsdaiQMzQER8aI0/jtZ+awsjGZSuB4kIffXsXxFWZNTiTwh+M0SmmXIz+fCOi+HLU8IBGxKBQYRE+rtyTz3/fDmgU8HfU/HUACkbeacOQSj6

## Context (required)
I want to track movies user has seen.

## Screenshots / recordings
<img width="627" alt="image" src="https://user-images.githubusercontent.com/107034443/215489137-4d571b87-66ef-4c43-a522-e3aaf07c5141.png">
<img width="1267" alt="image" src="https://user-images.githubusercontent.com/107034443/215489945-c8a6703d-6c2d-4518-bb1e-a37b8e4ef805.png">
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/107034443/215490499-57481fc0-7ca7-4d23-8cc5-921028e3cd32.png">

## Your environment

* Version of FlutterFlow used: Flutterflow released 26th January 2023
* Platform (e.g. Web, MacOS Desktop): iOS
* Browser name and version: Chrome
* Operating system and version (desktop or mobile):

**Comment by hariprasadms** [comment] 2023-01-30 19:51
Hi @tadamtech - Thanks for sharing the issue details. 

It appears that the logic configuration was mostly causing the issue. We need app access and sample data to explore this kind of issues. Please create a test app with sample data and the exact same configurations, then send the details it to us.

Once you update the issue with the details, we can re look into the issues.

**Comment by tadamtech** [comment] 2023-01-30 20:23
Hi, 
Thank you very much for your answer.

Here is a public project with the exact same configurations as my project with a simplified sample data.

https://app.flutterflow.io/project/swipablestack-project-hhu9dl

Thanks !

**Comment by livingmydesign** [comment] 2023-01-31 07:58
related issue that also is still not solved:
https://community.flutterflow.io/c/discuss-and-get-help/votingapp-with-supabase-and-swipeablestack
https://github.com/FlutterFlow/flutterflow-issues/issues/392

**Comment by tadamtech** [comment] 2023-02-02 10:41
Hello Hari, I configured the three required widget action. It still doesn't work.

For example, I swiped cards with ID 2,5 and 3 but field seenTmdb in Users contains 2, 5 and 1 ...

Below is the code :
<img width="646" alt="image" src="https://user-images.githubusercontent.com/107034443/216302612-4d6ec659-6413-4738-91c3-76bbf4cfae5b.png">

Thank you for your help !

**Comment by tadamtech** [comment] 2023-02-06 15:43
Can someone help me ?

**Comment by hariprasadms** [comment] 2023-02-06 16:26
Hi @tadamtech - 
Thanks for share earlier details. Can you try using 'order-by' in the backend query and see how it goes. Add date and time stamp field for the move collection and user order-by. I think, as docs are not in order without order-by, while swiping, it is adding random docs into the list. 

Also you should add a filter to the backend query to filter-out the list of docs based on seenTmdbld. See below.

![image](https://user-images.githubusercontent.com/17435678/217027686-8a919a07-88e4-41df-8a5e-567fae1d834d.png)

Try this and let me know how it goes.

**Comment by tadamtech** [comment] 2023-02-06 17:00
Hello,

I added an order-by statment in the backend query. It does **not** work. 

<img width="644" alt="image" src="https://user-images.githubusercontent.com/107034443/217034957-d45acb27-c08d-474d-baed-3cc53b03c7ed.png">

I already filter the collection in my generate children statement.

**Comment by tadamtech** [comment] 2023-02-06 17:29
Thanks

**Comment by hariprasadms** [comment] 2023-02-06 21:18
Hi @tadamtech - I have tested it and it is working fine. There are few changes you should do in your project. 

 1. Filters and order-by should be at backend query level. Remove filters from list. 
 2. You can at least one Swipe action. No need to add actions for all swipeable actions. You can have at least one swipeable action. 

Follow below configurations in video.

https://user-images.githubusercontent.com/17435678/217089074-35e86c4c-8259-411d-ac1e-04183fbe365e.mp4

Let me know how it goes.

**Comment by tadamtech** [comment] 2023-02-06 21:28
Ok thank you I will try this configuration. However, I think the filter at Backend query level will not work because the field seenMovieId in user table can have more than 10 item. Flutter doesn't support more than ten Item in that case. I use to get an error when I tried this filter method ... Am i wrong ?

Thanks a lot for your help !  I will let you know how it goes.

**Comment by hariprasadms** [comment] 2023-02-06 21:32
Great. There is no limitations at flutter/firebase level. 
Try this configurations and let me know. It should work with no issues. Thanks

**Comment by tadamtech** [comment] 2023-02-06 22:24
Well, I set up everything as you explained in your video. It does not work : 
1. The wrong Id goes into user field list "tmdb_id" 
2. Flutter doesn't support list with more than 10 elements (error at the end of the video)

Here is a screen video of the setup and of the test. I really don't understand what I am making wrong ...

Video -> https://www.loom.com/share/aa1c65068eac4106b6d7dc8b59bc1631

Thanks for your help.

Yoann

**Comment by hariprasadms** [comment] 2023-02-06 22:58
I can made some changed to your project. Please run and share the run link.

**Comment by tadamtech** [comment] 2023-02-07 09:15
Hello, 

I did not see your changes. I made it : 

1. I set up the filter at swipable generate children level as earlier. 
2. I have kept **only left swipe action** as you describe in your previous comment. (I do not understand, you told me earlier that the three first actions (on swipe, left and right swipe) were mandatory ??)

It still doesn't work. When I swipe left, i get the wrong id. 

I have identified in that configuration that the order of the incorrect Id is always the same : 
When I swipe id 1, then I get 1
When I swipe 2, then I get 3
When I swipe 3, then I get 5
When I swipe 4, then I get 7
Then 5 is already in swiped id so the card 5 is not display, and card 6 is displayed
When I swipe 6, then I get 9 etc. 

Here is the run link : https://app.flutterflow.io/run/BUF9IommKAreKtqgqaJT
Here is a video of the set up + test : https://www.loom.com/share/69e744592ca04c59a706cc20241c5276

Thanks !

**Comment by victoriahuang1** [comment] 2023-02-08 00:58
Hi @tadamtech , the issue is caused by iterating over a collection of items (the not swiped movies) while modifying that same collection (the collection of not swiped movies changes as you swipe them). Mutating a collection while iterating over it goes against best practices, as it can lead to unexpected behavior.

To address this issue, we need to ensure that we are not mutating the same collection of movies that we are iterating over. To achieve this, we can do the following:
- Add a local state variable to keep track of the swiped movies (you can initialize it to the swiped movies saved in the `users` collection on page load)
- Change the Firestore movie query to a Single time query
- Filter out the seen movies, using the local state variable, in the query (as opposed to in the swipeable stack)
- Remove the filter from the swipeable stack
- Behavior may not work with back navigation, so you should disable that

These changes will lead to reading the collection of movies to iterate over from a source (stored in **memory**) that is _not_ affected by your updates (to **Firestore**) made on swipes, thus resolving the issue.

Hope this helps!

**Comment by tadamtech** [comment] 2023-02-08 10:57
I confirm that I cannot use the NOT IN statement in my query (see picture below) : 
<img width="280" alt="image" src="https://user-images.githubusercontent.com/107034443/217510657-f4486f8b-e3b8-42f2-81d9-ba21506bdfff.png">

Can I use the filter condition on the swipeable stack ?

Thank you

**Comment by tadamtech** [comment] 2023-02-08 11:11
It seem to work when I filter on swipable stack !!!

**Comment by victoriahuang1** [comment] 2023-02-08 16:38
Ah yes Firestore does have that annoying limitation. By work, do you mean there are no more bugs? Or just that the filtering works, but there is still the issue of modifying the collection you're iterating over?

**Closed** 2023-02-17 18:31 UTC
Labels: closed: not a bug, status: not a bug
