### ISSUE TITLE
LineChart X and Y values auto deleting

### ISSUE THREAD

**Issue by antoniobno1** [FlutterFlow/flutterflow-issues#3619] opened 2024-08-14 00:07 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I set the X and Y axes on my linechart from a firestore document referense they get unset or deleted after a few seconds.

Heres a video
https://drive.google.com/file/d/1FWVPQ4FXjXetTfsN51Faok9izN1b98uI/view?usp=sharing

I have managed to compile and show the graph in the app, but it does not work anymore

### Expected Behavior

X and Y axes would save as normal

### Steps to Reproduce

1. Add graph widget
2. Pull data from firestore document
3. Select X and Y

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTis/huIxNoddc+KrfKMZKgjsUCUMAWOcViuxHcx4cCO/mBO02d8mlR0NKTe6ld2w3GFSWnnECpfz6k+PpCvc6H0utGJxi0JVAExbwRT6hR82gDZbpeHAmGptmI37E1sGrkB4nB7BedU0t7WatN63qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

https://drive.google.com/file/d/1FWVPQ4FXjXetTfsN51Faok9izN1b98uI/view?usp=drive_link

### Environment

```markdown
- FlutterFlow version:  FlutterFlow v4.1.81+ released August 6, 2024
Flutter version is 3.22.2
- Platform: Chrome
- Browser name and version: Google Chrome
- Operating system and version affected: Windows 11
```

### Additional Information

I am not able to do any linecharts necessary for my project :(

**Comment by Alezanello** [comment] 2024-08-14 12:45
Hello!

This issue is a duplicate of [issue #3553](https://github.com/FlutterFlow/flutterflow-issues/issues/3553). I’ll close this thread, and you can follow any new updates directly on that ticket.

Thank you for your understanding!

**Closed as not planned by Alezanello** 2024-08-14 12:45 UTC
Labels: status: needs triage
