### ISSUE TITLE
The alpha channel from the button's fill color is not shown properly

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#1045] opened 2023-06-25 12:35 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When the button's fill color is transparent is not showed in the Test Mode and the properties is not show properly in the FF Builder, #000000 (black) instead #00000000 (transparent), the alpha channel always shown 100% 

### Expected Behavior

The button's fill color when is set as transparent should be show properly

### Steps to Reproduce

1. Add a button
2. Set the fill color with #00000000 (transparent)
3. Now open again and will appear as #000000 (black) - First Bug
4. Now open in test mode and will see the button hasn't a transparency fill color - Second Bug

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sz8mAsIxIseFH+KryKPl7/T0RH0A4apIoscsZa0kdB4joPLJ/dcjeR1VVOemrd0NhHFn8mjoJwsHGit7mGPIBG06uGKo9ybpMdj3wJHq8Ra7SO4eVdXxtEeBQJmqs36TUvglAGNRuZUYZ1F2tNuqRfCnACZu/Zwh9f6PHaOI=

### Context

I want a transparent fill color for a button. The bug is on Test Mode and Web, I didn't test in Android and iOS.

### Visual documentation

https://schoolfy365.tinytake.com/msc/ODM3MzIxNV8yMTY0OTAxNQ

### Environment

```markdown
- FlutterFlow version: FlutterFlow v3.1 released June 25, 2023
- Platform: Web
- Browser name and version: Chrome 114.0.5735.134 (Official Build) (64-bit)
- Operating system and version affected: Windows 11
```

**Comment by SameerShahzad99** [comment] 2023-06-26 19:44
Thank you for reporting this bug, it was reproducible! on my side

**Comment by wenkaifan0720** [comment] 2023-07-06 17:48
Hi @Franco98404. The color is actually set to transparent correctly. We filter the alpha channel in the color picker dialog so that you can see the color change happening, but the hex code of the color is not changed. What you see behind the button is the drop shadow of the button. You can set the elevation of the button to 0 and you will have a transparent filled button.

**Comment by wenkaifan0720** [comment] 2023-07-07 14:57
Since this is not a bug on our end. I'll close it for now.

**Closed by wenkaifan0720** 2023-07-07 14:57 UTC
Labels: closed: not a bug, status: not a bug
