### ISSUE TITLE
Can't leave a project from Dashboard

### ISSUE THREAD

**Issue by madson** [FlutterFlow/flutterflow-issues#2980] opened 2024-05-24 12:19 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

From FlutterFlow Dashboard, when you click on the tree dots menu and choose Leave Project, it shows a dialog asking: "Are you sure you want to leave project XYZ?" Then I click Leave, it presents an error stating "Not authorized" and the project keeps showing up on my Dashboard.

### Expected Behavior

It should remove the project from my Dashboard.

### Steps to Reproduce

1. Open Dashboard
2. Click on the tree dots from a project you were invited as a collaborator (Read only)
3. Select the option Leave Project from the menu
4. Confirm clicking on Leave on the dialog

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

not working

### Context

I was trying to leave a project, and I was invited as a collaborator 

### Visual documentation

N/A.

### Environment

```markdown
- FlutterFlow version: v4.1.53+
- Platform: Web
- Browser name and version: Arc Version 1.44.1 (50317)
- Operating system and version affected: macOS
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by msusviela** [comment] 2024-05-24 12:27
Hey @madson, Thanks for your report, So sorry you are experiencing this issue. I was not able to reproduce this on a blank project, but it is replicable on yours. That's why I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. Thanks so much!

**Closed as not planned** 2024-05-24 12:28 UTC
Labels: status: not a bug

**Comment by sabatage3** [comment] 2024-08-23 17:09
Hi @msusviela This is not a project-specific issue, I have the same issue, so other people as you can see here: https://community.flutterflow.io/ask-the-community/post/leaving-project-impossible-rKNmLbRIQG63Am8?highlight=XhDiXrBCuJyzEvk

I already contacted support several weeks ago, but they haven't answered the email yet.
I can't leave any of the projects that I'm invited to, it says "not authorized" even when I'm editor, and if I have read-only privileges, then, the button for leaving the project is not even displayed

**Comment by sabatage3** [comment] 2024-08-25 21:57
Any progress here? @msusviela
