### ISSUE TITLE
Conditions - Json - From value

### ISSUE THREAD

**Issue by blondie63** [FlutterFlow/flutterflow-issues#649] opened 2023-03-21 14:11 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

We now can't create a condition like this:
if $.json_field == 1

we can only write this:
if $.json_field == someStateVar

<img width="638" alt="FF-conditions-json-issue" src="https://user-images.githubusercontent.com/1261851/226632894-564d89ff-83f5-4768-b294-8f50b118f16b.png">

### Expected Behavior

I think it's logic to have a way to check a json var with any values, not only from variables

### Steps To Reproduce

It's very intuitive, no need steps

### Bug Report Code

IT4wlsmAsI1Nobhe+KqJb/pvoCMvIjo2aJ0rk8IbGSs9Grb0POxzacn8XEpWOM+8d1ZHKEWGgkAG+c3Ii+D1EcA7AxCcGKI9+rlycQ/LQme/aoSMELWWZHQnBZtRfmHC3J2N2CV/JfthdVo1217zDfKiQhLtQZ/7Zwh9f6PHaOI=

### Context

As workaround i used an App state var
<img width="345" alt="FF-conditions-json-issue-workaround" src="https://user-images.githubusercontent.com/1261851/226632623-5b16ba22-b5d8-46ac-8604-07407912e535.png">

### Environment

```markdown
- FlutterFlow version: 3.1 released March 17 2023
- Platform: Web
- Browser name and version: Chrome Version 111.0.5563.64
- Operating system and version affected: macOS Ventura 13.2.1
```

**Comment by hariprasadms** [comment] 2023-03-21 15:24
Hi @blondie63 - Thanks for posting this issue. This can be a feature request. However, from variable property gives more ability to get the value from app, page states and more. I can mark this as feature request for now.

**Comment by agreaves** [comment] 2023-07-10 01:41
Hi @blondie63, thanks for the bug report! Sorry for the delay in getting to this one, we should have updated this to let you know it is a duplicate of #86. Please see the explanation in that issue as well as the possible workarounds.

**Closed by agreaves** 2023-07-10 01:41 UTC
Labels: status: confirmed, type: feature request
