### ISSUE TITLE
DropDown widget: the Hint Text property can't be set from a variable

### ISSUE THREAD

**Issue by pierrecorbay** [FlutterFlow/flutterflow-issues#531] opened 2023-02-26 01:00 UTC
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

The Hint Text property of a DropDown widget is set to the chosen variable when using 'Set from Variable'.

## Current behavior (required)

The Hint Text property is only considering the value entered manually and doesn't update to the value of a variable when using 'Set from Variable'.
## To Reproduce (required)

1. Add a DropDown widget to a page
2. Go to the Properties Panel of this DropDown widget --> Initial Configuration --> Hint Text
3. Set from Variable
4. Choose any String variable
It sticks with the default value ("Please select...") and doesn't update to the selected variable (in the UI Builder and in the Code).

### Bug Report Code (required, generate by right clicking inside Widget Tree and clicking "Get Bug Report Code")

ITFfz8/q24lPm+FY1r6JYPkw+WA4NlscTIAvm+0aYz0bfL7rBqQMPczsahZuQtO8aVNcOVmkknse0MLNjtmSL/IEaQSCRtlMybpcTw7AKTbkEuzyT+3IHDUHZbsSXTTm

## Context (required)

I'm trying to set the Hint Text property from a variable retrieved in a Firestore document.  

## Screenshots / recordings

https://user-images.githubusercontent.com/59781996/221386658-4b17ea7f-b11d-4769-912d-1bbfdc37e3f9.mp4

## Your environment

* Version of FlutterFlow used: 3.7.3
* Platform (e.g. Web, MacOS Desktop): MacOS Desktop v1.1.45 
* Browser name and version: 
* Operating system and version (desktop or mobile): MacOS 13.2

**Comment by hariprasadms** [comment] 2023-03-01 19:59
Hi @pierrecorbay - Thanks for reporting this issue. I can re-produce the issue.

**Comment by pierrecorbay** [comment] 2023-04-04 00:54
Any update please ?

**Comment by agreaves** [comment] 2023-04-05 23:51
Hi @pierrecorbay, thank you for the bug report! This looks like it was a bug that has already been fixed. Apologies for not responding to this issue. I've confirmed that in the latest release setting a Dropdown Hint Text from variable does indeed work and is reflected in the output. One thing that may have happened is, if you set the variable and then _immediately_ switch to View Code the change may not be reflected yet as the save has not yet gone through (but will be if you either way a few seconds after making the change or subsequently refresh the View Code page).

Please see the working version in action here (please excuse the R&B background music 😅):

https://www.loom.com/share/a7a36314d6bd47588521904ea3e130e6

Closing this issue for now, as it is fixed, but if you are still experiencing issues please respond or feel free to create a new ticket.

**Closed by agreaves** 2023-04-05 23:51 UTC
Labels: type: bug, status: needs triage, status: confirmed
