### ISSUE TITLE
Webapp - Navigation issue in run mode (works fine in debug) 

### ISSUE THREAD

**Issue by Alex-vn-boulme** [FlutterFlow/flutterflow-issues#1412] opened 2023-09-06 12:43 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hi, 

I'm reaching out because I'm facing a big problem concerning the "navigate to" action. When I'm testing in debug mode everything works fine, but as soon as I switch to "run" or publish mode, the navigation is broken. Could you please do something quickly ? (it's currently prenventing us from launching)

Here is the id of my project name : IRVE-platform and link : 
https://app.flutterflow.io/project/i-r-v-e-platform-abfugx

Here is the navigation in debug mode : 
FF - IRVE Project - Navigation ok in debug mode - [Watch Video](https://www.loom.com/share/ea04dee02a2d4a99bedbb0b59c48c68c)

And broken in run mode : 
FF - IRVE-platform - navigation broken in run mode  - [Watch Video](https://www.loom.com/share/0d89484e093647998c89b7262c3fa9d3)

The navigation actions are located in the component "webNav" and are basic "navagate to" actions : 
Capture d’écran 2023-08-20 à 21.28.56.png

At first, I thought it was a temporary bug, but it's been one week with no improvement so I prefer to report it.

Thanks for your help !

### Expected Behavior

I just expect navigation in run mode to work like in debug mode. 

### Steps to Reproduce

1. Open this page in a navigator : https://app.flutterflow.io/run/Iwn6cechvBdDVOyxxGfT
2. Log inside the app with the following credentials :  
username : sompayrac.x@gmail.com
password : xs300882
3. Try to navigate just like in the video  

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Cj+fqwItIn7xc+KX6avpanj0XQkA7RYI7i9VHdxYcDZPND+x/esnRQFJuZ9OrdkFqI02krH003PfGm9z1DfE3ORyVb7pn1qh2azrdf3OWRrrXC8+OZUFUGshVGXK/y7eg3RVAAM9vWVoB33GQIuq/YDfdNJDtDGwgQ8qYENvXrgfuQ0SLb3kNh1JWeC/v

### Context

Development of the app works fine in debug mode, but I can't use the 

### Visual documentation

Here is the navigation in debug mode : 
FF - IRVE Project - Navigation ok in debug mode - [Watch Video](https://www.loom.com/share/ea04dee02a2d4a99bedbb0b59c48c68c)

And broken in run mode : 
FF - IRVE-platform - navigation broken in run mode  - [Watch Video](https://www.loom.com/share/0d89484e093647998c89b7262c3fa9d3)

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: Web
- Browser name and version: Chrome - Version 116.0.5845.179 (Build officiel) (arm64) -> issue has been reproduced on other browser
```

**Comment by sbruler** [comment] 2023-09-07 06:06
Having the same issue on mobile. TestFlight releases work fine, but the Apple App Store has rejected us while I've been working to debug this for two weeks. (We missed our launch date because of this, by the way :/). I was unable to replicate the error until I started copying .ipa files over to my device. The error (for me) only occurs on first app launch after install. IT seems that `context.pushNamed()` is not resolving. I suspect something with Go Router, but unsure.

**Comment by Alex-vn-boulme** [comment] 2023-09-15 14:24
@hariprasadms any update, more than one month we're stuck with this issue...

**Comment by wenkaifan0720** [comment] 2023-09-17 13:57
Hi @Alex-vn-boulme. I can't seem to reproduce this issue in run mode. Is it still happening to you?

https://github.com/FlutterFlow/flutterflow-issues/assets/112435854/9de3aede-d093-43fa-877c-c65e5db07abb

**Comment by wenkaifan0720** [comment] 2023-10-03 01:28
Hi! We’re closing this issue due to inactivity, as we do not have enough information currently to investigate. If this issue persists, please add the requested information so we can verify and re-open the issue. Thanks!

**Closed by wenkaifan0720** 2023-10-03 01:28 UTC
Labels: type: bug, status: confirmed, closed : project specific
