### ISSUE TITLE
Custom widgets,actions and functions showing unknown error 

### ISSUE THREAD

**Issue by zein1016** [FlutterFlow/flutterflow-issues#3622] opened 2024-08-14 08:58 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

whenever I'm creating a custom code, i'm getting unknow error 

### Expected Behavior

show me an error if there is one

### Steps to Reproduce

Create a custom action with or without dependency 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4si8rq24p2rsNK+Kr+bsBB/WUsKWIlaLgssct/cxQcB4j4PIkAPOLRTxNvQtSzaH1YGlKkkkME0s7Sk/PqG/YoIUmtG5Rj/852ERPPYzuuV4uVBZeaXUcnGfxUGB2A0cKN2hB4PsBtWUYY7FyMBOyAaz2Cf9qOYwx5e6fDbOY=

### Visual documentation

<img width="510" alt="Screenshot 2024-08-14 at 09 57 22" src="https://github.com/user-attachments/assets/2ee404cc-fbfa-4266-a99f-4b8d83859f2a">

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by Alezanello** [comment] 2024-08-14 12:23
Hello!

I noticed that your project contains multiple custom widgets and custom actions. A good way to debug the issue is to enable the "Exclude from compilation" option for all custom components. Then, you can gradually deactivate this setting for each one, testing individually to identify which custom widget or action is causing the unknown error.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/065be8f5-db45-4036-817f-98801a771051/d4897608-bffd-4f99-80c1-8c57fc932b8f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wNjViZThmNS1kYjQ1LTQwMzYtODE3Zi05ODgwMWE3NzEwNTEvZDQ4OTc2MDgtYmZmZC00Zjk5LTgwYzEtOGM1N2ZjOTMyYjhmIiwiaWF0IjoxNzIzNjM4MjA3LCJleHAiOjMzMjk0MTk4MjA3fQ.tn53o3KLaunHAVrThpGmy0OHg0_EKPFudJP9TIU6o_w " alt="image.png" width="338" height="189" />

**Comment by zein1016** [comment] 2024-08-14 12:59
Thanks for the response. When I try to load the app to test it, it is showing a package from a action I already deleted (Please see attached, I don't even have this fluttertoast-8.2.7 in any current actions. 

<img width="553" alt="Screenshot 2024-08-14 at 13 57 49" src="https://github.com/user-attachments/assets/ab272c3b-e1c7-4e07-950a-13e35004c6ce">
 . Also whenever I delete an action, the error goes to another action to state that (this new) action has an error... 
> Hello!
> 
> I noticed that your project contains multiple custom widgets and custom actions. A good way to debug the issue is to enable the "Exclude from compilation" option for all custom components. Then, you can gradually deactivate this setting for each one, testing individually to identify which custom widget or action is causing the unknown error.
> 
> <img alt="image.png" width="338" height="189" src="https://camo.githubusercontent.com/fefce88a750b835e362338c8e9e14a80641b3fa237506475c17384cf25aab8ac/68747470733a2f2f75706c6f6164732e6c696e6561722e6170702f33323431303839642d373336612d343432322d393030622d3035316537326163636462652f30363562653866352d646234352d343033362d383137662d3938383031613737313035312f64343839373630382d626666642d346639392d383063312d3863353766633933326238663f7369676e61747572653d65794a68624763694f694a49557a49314e694973496e523563434936496b705856434a392e65794a775958526f496a6f694c7a4d794e4445774f446c6b4c54637a4e6d45744e4451794d6930354d4442694c5441314d5755334d6d466a593252695a5338774e6a56695a54686d4e53316b596a51314c5451774d7a59744f4445335a6930354f4467774d5745334e7a45774e5445765a4451344f5463324d446774596d5a6d5a4330305a6a6b354c546777597a45744f474d314e325a6a4f544d79596a686d4969776961574630496a6f784e7a497a4e6a4d344d6a41334c434a6c654841694f6a4d7a4d6a6b304d546b344d6a413366512e746e35336f334b4c61756e48415672546870476d79304f4867305f454b504675644a5039544955366f5f7720">

**Comment by zein1016** [comment] 2024-08-14 14:33
I have tried the custom codes on a new project, they are working normally

**Comment by Alezanello** [comment] 2024-09-03 12:59
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by Alezanello** [comment] 2024-09-18 22:11
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Closed as not planned by Alezanello** 2024-09-18 22:11 UTC
Labels: waiting for user response
