### ISSUE TITLE
Web URL not working in iOS and iPad OS.

### ISSUE THREAD

**Issue by vairagadeharshwardhan** [FlutterFlow/flutterflow-issues#3764] opened 2024-09-06 15:36 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Web URL works in desktop browsers (chrome and Opera etc) and android browsers but not in iOS.
Android

### Expected Behavior

It should work in all browsers.

### Steps to Reproduce

https://lozy-r9t7iz.flutterflow.app this is app link.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESjMmB+cpgrsQF0LncacZqhQIgQ0QnU7gnlO1ucx42G4z0OpkiPOPBaUNKQtODYAtcEGKKoFw0puuMj/zlG+4qOQirb7o+0JVAczmXZFyjRcWoCbrhenxDL+hYBXWB0qaJqiRSJtdtcUY6wDqPNq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

NA

### Environment

```markdown
- FlutterFlow version: 4.1.87
- Platform:3.22.2
- Browser name and version: iOS safari
- Operating system and version affected: iOS, iPad OS
```

**Comment by rzambroni** [comment] 2024-09-06 17:34
Hi @vairagadeharshwardhan,

Thank you for bringing this to our attention! Could you please clarify a bit more about what you mean by "not working"?

I tested your link across multiple platforms, including Android, iOS, macOS, and Windows, and I seem to get the same consistent experience (see attached screenshot).

It would be really helpful if you could share some additional information, such as a screenshot or more detailed steps, so we can better understand the issue you're facing and provide the right support.

Thanks again!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/dfb453b3-2ec7-437e-a40e-c454dd488b9a/2e38463f-1b02-49d4-acf5-847a88cb3ca1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kZmI0NTNiMy0yZWM3LTQzN2UtYTQwZS1jNDU0ZGQ0ODhiOWEvMmUzODQ2M2YtMWIwMi00OWQ0LWFjZjUtODQ3YTg4Y2IzY2ExIiwiaWF0IjoxNzI1NjQ0MDYwLCJleHAiOjMzMjk2MjA0MDYwfQ.H39xjvZd0SlXvkL3uay5AuGJ8PM58DEgHJFjgyzwL4c " alt="image.png" width="1179" height="2556" />

**Comment by vairagadeharshwardhan** [comment] 2024-09-07 02:07
Hi,

Thank you for your reply.
The issue is that the url is not loading. It is stuck at the splash screen.
Did you observe the same?

Kind Regards,
Mr. Harshwardhan Vairagade
Contact No: +91 992229234

**Comment by rzambroni** [comment] 2024-09-07 23:37
After conducting a second test, I observed that the app successfully loads on Android (Chrome), Windows (Chrome), and MacOS (both Chrome and Safari).

However, I can confirm that it does not load on iOS, where it gets stuck on the splash screen. Based on the console errors, I suspect that these might be contributing to the issue.

It’s possible that addressing these errors could resolve the problem, as some browsers are more lenient and may allow the website to load despite these issues. This discrepancy could explain why it functions on certain platforms but not on iOS.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/374f7299-2d39-4a2a-8e2c-a6c4a052fb1d/b08ed7b9-73da-4408-b372-9f2bd7c4b0e3?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zNzRmNzI5OS0yZDM5LTRhMmEtOGUyYy1hNmM0YTA1MmZiMWQvYjA4ZWQ3YjktNzNkYS00NDA4LWIzNzItOWYyYmQ3YzRiMGUzIiwiaWF0IjoxNzI1NzUyMjQ5LCJleHAiOjMzMjk2MzEyMjQ5fQ.pca2Qs74JHk7fzz-hyvq2XGcZ1FN0-ETOS9oJhmx6c0 " alt="image.png" width="1463" height="1216" />

**Comment by vairagadeharshwardhan** [comment] 2024-09-08 06:15
Hi, 
In flutterflow what care should I take?

**Comment by vairagadeharshwardhan** [comment] 2024-09-25 14:58
Hi, any update from the FF community, I am still facing the issue! :(

**Comment by rzambroni** [comment] 2024-09-26 13:58
Hi,

I apologize for the delay in getting back to you. Unfortunately, we don’t have the bandwidth to investigate individual issues specific to customer projects. For help with specific errors, I recommend reaching out to our community at [FlutterFlow Community](https://community.flutterflow.io/) or contacting our support team. You can do so via email at support@flutterflow.io or through the in-app chat feature in FlutterFlow.

Since this tracker is specifically for bugs reproducible from blank projects, I'll be closing this issue. Thank you for your understanding!

**Closed as not planned by rzambroni** 2024-09-26 13:58 UTC
Labels: status: can't reproduce
