### ISSUE TITLE
ListView crashes on physical iOS devices when scrolling through a larger list containing images from a Firebase DB

### ISSUE THREAD

**Issue by RonGelb** [FlutterFlow/flutterflow-issues#576] opened 2023-03-04 20:18 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Scrolling through a larger list of records in a ListView containing images crashes on iOS devices. I believe because the IOS operating system kills the app because the app creates a memory issue. On Android devices or in the web, the same ListView works as expected with no errors.

### Expected Behavior

Scrolling through a larger ListView containing images without crashing the app.

### Steps To Reproduce

1. Create a page
2. Add a ListView
3. Inside that ListView add a Row containing an image which displays the image from a firebase DB
4. Add a larger number of records about 200
5. Scroll thru the ListView
6. The app will crash on IOS devices

### Bug Report Code

IT4Shcr1sIhPseFF7oSJcMdVnj4vKVs7bZIrmOtqEAAdfbKuE4kTXOn9alZVXeG+dkFmOGKZsGQK+s7Rm9z1LcE5FAeBbptz+blhVQryUl6gR6qnEpeWXXxEGshUfx2X4cC7rhBCCNBZSUY+wE+AIe+tfB/sQe/jPjInJcqHOqDXvgfuQ0SLb3kNh1JWeC/v

### Context

I reduced the number of records until the app no longer crashes on a physical IOS device. Adding more records again reproduced the crash. Or I removed the image from the ListView, the app doesn't crash anymore.

https://user-images.githubusercontent.com/96952321/222926628-d9183bac-2ecd-4fa0-b952-01804c6a93ca.mov

<img width="1246" alt="Screenshot 2023-03-04 at 21 11 04" src="https://user-images.githubusercontent.com/96952321/222926698-27a97a2f-9fd3-49ee-8628-65112cc38521.png">

### Environment

```markdown
- FlutterFlow version: 3.7.3
- Platform: IOS
- Browser name and version: -
- Operating system and version affected: IOS 15.7.1 or bigger
```

**Comment by wenkaifan0720** [comment] 2023-03-06 15:39
Hi @RonGelb. You seem to be querying the same collection in `subcollDataContainer` and `ItemContainer`. Is that necessary?

**Comment by RonGelb** [comment] 2023-03-07 21:19
I removed the backend query from the ItemContainer, but the issue (app is terminated by OS) persists on IOS devices.
<img width="1255" alt="Screenshot 2023-03-07 at 22 15 38" src="https://user-images.githubusercontent.com/96952321/223554820-0bb82300-f9fc-40ab-9a64-e4d78ab8e1d6.png">

**Comment by RonGelb** [comment] 2023-03-09 18:53
Can you please fix it. I've been working more than 6 month on the app with more than 270 versions and I can't publish it on the Apple app store. You can easily generate the memory issue. Just create a firebase db with images more than 200 images about 500 bytes per image and scroll through the list. If you use infinity scroll it's better but it is only possible to use one infinity scroll per view. But I need to sort the list by date or name.......

**Comment by wenkaifan0720** [comment] 2023-03-11 13:52
Hi @RonGelb. Sorry for the late reply. I couldn't reproduce your issue as I don't have access to the list of those 200 items. Since you are running the app yourself, could you share with me any error message that is generated when the app crashes?

**Comment by atultaz** [comment] 2023-03-12 19:12
hey I am getting the same error this is the error message
The following NetworkImageLoadException was thrown resolving an image codec:
HTTP request failed, statusCode: 500,
https://firebasestorage.googleapis.com/v0/b/notezo.appspot.com/o/users%2FtGUBhdCKvUMTn1WCB1KJx
POvjxv1%2Fuploads%2F1674672256608000.jpeg?alt=media&token=eb3a5f5e-c0cb-4551-b75c-16e6b37ccdcf

When the exception was thrown, this was the stack:
#0      NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:117:9)
<asynchronous suspension>

Image provider:
  NetworkImage("https://firebasestorage.googleapis.com/v0/b/notezo.appspot.com/o/users%2FtGUBh
  dCKvUMTn1WCB1KJxPOvjxv1%2Fuploads%2F1674672256608000.jpeg?alt=media&token=eb3a5f5e-c0cb-4551
  -b75c-16e6b37ccdcf",
  scale: 1.0)
Image key:
  NetworkImage("https://firebasestorage.googleapis.com/v0/b/notezo.appspot.com/o/users%2FtGUBh
  dCKvUMTn1WCB1KJxPOvjxv1%2Fuploads%2F1674672256608000.jpeg?alt=media&token=eb3a5f5e-c0cb-4551
  -b75c-16e6b37ccdcf",
  scale: 1.0)
══════════════════════════════════════════════════════════════════════════════════════════════
══════

Another exception was thrown: HTTP request failed, statusCode: 500,
https://firebasestorage.googleapis.com/v0/b/notezo.appspot.com/o/users%2FtGUBhdCKvUMTn1WCB1KJx
POvjxv1%2Fuploads%2F1674730002658000.jpeg?alt=media&token=2a4a683e-c703-48a8-bbe2-a6c0943f3bd5

Another exception was thrown: HTTP request failed, statusCode: 404,
https://firebasestorage.googleapis.com/v0/b/notezo.appspot.com/o/users%2FzpdKV6vzsUSGDnlo6abmx
P6rFdB3%2Fuploads%2F1667671345270000.jpeg?alt=media&token=94f9442c-2484-4877-ad19-291687209b49

Another exception was thrown: HTTP request failed, statusCode: 404,
https://firebasestorage.googleapis.com/v0/b/notezo.appspot.com/o/users%2FzpdKV6vzsUSGDnlo6abmx
P6rFdB3%2Fuploads%2F1667674977934000.jpeg?alt=media&token=b34e1a26-0475-4d92-a527-a7dc17b2c638

Another exception was thrown: HTTP request failed, statusCode: 404,
https://firebasestorage.googleapis.com/v0/b/notezo.appspot.com/o/users%2FzpdKV6vzsUSGDnlo6abmx
P6rFdB3%2Fuploads%2F1667671285246000.jpeg?alt=media&token=88ffd2bc-0901-425f-8889-94e0fcf9a45a

Another exception was thrown: HTTP request failed, statusCode: 404,
https://firebasestorage.googleapis.com/v0/b/notezo.appspot.com/o/users%2FzpdKV6vzsUSGDnlo6abmx
P6rFdB3%2Fuploads%2F1667671176003000.jpeg?alt=media&token=9cc0726c-fc32-4685-8e09-880c6cd180fa

**Comment by atultaz** [comment] 2023-03-12 19:12
> Hi @RonGelb. Sorry for the late reply. I couldn't reproduce your issue as I don't have access to the list of those 200 items. Since you are running the app yourself, could you share with me any error message that is generated when the app crashes?
hey this is the error message I am getting
The following NetworkImageLoadException was thrown resolving an image codec:
HTTP request failed, statusCode: 500,
https://firebasestorage.googleapis.com/v0/b/notezo.appspot.com/o/users%2FtGUBhdCKvUMTn1WCB1KJx
POvjxv1%2Fuploads%2F1674672256608000.jpeg?alt=media&token=eb3a5f5e-c0cb-4551-b75c-16e6b37ccdcf

When the exception was thrown, this was the stack:
#0      NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:117:9)
<asynchronous suspension>

Image provider:
  NetworkImage("https://firebasestorage.googleapis.com/v0/b/notezo.appspot.com/o/users%2FtGUBh
  dCKvUMTn1WCB1KJxPOvjxv1%2Fuploads%2F1674672256608000.jpeg?alt=media&token=eb3a5f5e-c0cb-4551
  -b75c-16e6b37ccdcf",
  scale: 1.0)
Image key:
  NetworkImage("https://firebasestorage.googleapis.com/v0/b/notezo.appspot.com/o/users%2FtGUBh
  dCKvUMTn1WCB1KJxPOvjxv1%2Fuploads%2F1674672256608000.jpeg?alt=media&token=eb3a5f5e-c0cb-4551
  -b75c-16e6b37ccdcf",
  scale: 1.0)
══════════════════════════════════════════════════════════════════════════════════════════════
══════

Another exception was thrown: HTTP request failed, statusCode: 500,
https://firebasestorage.googleapis.com/v0/b/notezo.appspot.com/o/users%2FtGUBhdCKvUMTn1WCB1KJx
POvjxv1%2Fuploads%2F1674730002658000.jpeg?alt=media&token=2a4a683e-c703-48a8-bbe2-a6c0943f3bd5

Another exception was thrown: HTTP request failed, statusCode: 404,
https://firebasestorage.googleapis.com/v0/b/notezo.appspot.com/o/users%2FzpdKV6vzsUSGDnlo6abmx
P6rFdB3%2Fuploads%2F1667671345270000.jpeg?alt=media&token=94f9442c-2484-4877-ad19-291687209b49

Another exception was thrown: HTTP request failed, statusCode: 404,
https://firebasestorage.googleapis.com/v0/b/notezo.appspot.com/o/users%2FzpdKV6vzsUSGDnlo6abmx
P6rFdB3%2Fuploads%2F1667674977934000.jpeg?alt=media&token=b34e1a26-0475-4d92-a527-a7dc17b2c638

Another exception was thrown: HTTP request failed, statusCode: 404,
https://firebasestorage.googleapis.com/v0/b/notezo.appspot.com/o/users%2FzpdKV6vzsUSGDnlo6abmx
P6rFdB3%2Fuploads%2F1667671285246000.jpeg?alt=media&token=88ffd2bc-0901-425f-8889-94e0fcf9a45a

Another exception was thrown: HTTP request failed, statusCode: 404,
https://firebasestorage.googleapis.com/v0/b/notezo.appspot.com/o/users%2FzpdKV6vzsUSGDnlo6abmx
P6rFdB3%2Fuploads%2F1667671176003000.jpeg?alt=media&token=9cc0726c-fc32-4685-8e09-880c6cd180fa

**Comment by RonGelb** [comment] 2023-03-12 20:10
I don't think 404 is the problem, seems to be handled correctly by the ImageWidget. At the moment I'm trying to get the Flutter code I exported from FlutterFlow to work inside Xcode, which is a big challenge as all the external libraries don't complete the pod load. Right now I'm thinking about not showing the images in the ListView on IOS devices as a bad workaround. If you can send me an email where I can send you the test user's credentials with all the images, it would be easier for you to reproduce the bug.

**Comment by atultaz** [comment] 2023-03-12 20:13
hey my email id is atulblogger1@gmail.com

**Comment by RonGelb** [comment] 2023-03-12 20:50
In the meantime I was able to run the Flutter code on a physical IOS device using Xcode here is the error message:

Details

The app “Runner” on iRGE quit unexpectedly.
Domain: IDEDebugSessionErrorDomain
Code: 11
Failure Reason: Message from debugger: Terminated due to memory issue
User Info: {
    DVTErrorCreationDateKey = "2023-03-12 20:46:33 +0000";
    IDERunOperationFailingWorker = DBGLLDBLauncher;
}
--

Analytics Event: com.apple.dt.IDERunOperationWorkerFinished : {
    "device_model" = "iPhone10,6";
    "device_osBuild" = "16.3.1 (20D67)";
    "device_platform" = "com.apple.platform.iphoneos";
    "launchSession_schemeCommand" = Run;
    "launchSession_state" = 2;
    "launchSession_targetArch" = arm64;
    "operation_duration_ms" = 72675;
    "operation_errorCode" = 11;
    "operation_errorDomain" = IDEDebugSessionErrorDomain;
    "operation_errorWorker" = DBGLLDBLauncher;
    "operation_name" = IDEiPhoneRunOperationWorkerGroup;
    "param_consoleMode" = 0;
    "param_debugger_attachToExtensions" = 0;
    "param_debugger_attachToXPC" = 1;
    "param_debugger_type" = 5;
    "param_destination_isProxy" = 0;
    "param_destination_platform" = "com.apple.platform.iphoneos";
    "param_diag_MainThreadChecker_stopOnIssue" = 0;
    "param_diag_MallocStackLogging_enableDuringAttach" = 0;
    "param_diag_MallocStackLogging_enableForXPC" = 1;
    "param_diag_allowLocationSimulation" = 1;
    "param_diag_checker_tpc_enable" = 1;
    "param_diag_gpu_frameCapture_enable" = 0;
    "param_diag_gpu_shaderValidation_enable" = 0;
    "param_diag_gpu_validation_enable" = 0;
    "param_diag_memoryGraphOnResourceException" = 0;
    "param_diag_queueDebugging_enable" = 1;
    "param_diag_runtimeProfile_generate" = 0;
    "param_diag_sanitizer_asan_enable" = 0;
    "param_diag_sanitizer_tsan_enable" = 0;
    "param_diag_sanitizer_tsan_stopOnIssue" = 0;
    "param_diag_sanitizer_ubsan_stopOnIssue" = 0;
    "param_diag_showNonLocalizedStrings" = 0;
    "param_diag_viewDebugging_enabled" = 1;
    "param_diag_viewDebugging_insertDylibOnLaunch" = 1;
    "param_install_style" = 0;
    "param_launcher_UID" = 2;
    "param_launcher_allowDeviceSensorReplayData" = 0;
    "param_launcher_kind" = 0;
    "param_launcher_style" = 0;
    "param_launcher_substyle" = 0;
    "param_runnable_appExtensionHostRunMode" = 0;
    "param_runnable_productType" = "com.apple.product-type.application";
    "param_runnable_type" = 2;
    "param_testing_launchedForTesting" = 0;
    "param_testing_suppressSimulatorApp" = 0;
    "param_testing_usingCLI" = 0;
    "sdk_canonicalName" = "iphoneos16.1";
    "sdk_osVersion" = "16.1";
    "sdk_variant" = iphoneos;
}
--


System Information

macOS Version 13.0.1 (Build 22A400)
Xcode 14.1 (21534.1) (Build 14B47b)
Timestamp: 2023-03-12T21:46:33+01:00

**Comment by wenkaifan0720** [comment] 2023-03-13 13:39
Hi @RonGelb. You can contact me here: wenkai@flutterflow.io. In the meantime, could you try to enable image caching and see if that helps?

**Comment by RonGelb** [comment] 2023-03-19 14:32
Please do not get me wrong. I am using Flutterflow a no/low code app. If I had the deep knowledge you asked for, I wouldn't use Flutterflow, I would use Flutter. I was hoping you could help one of your power users. In my opinion, the Flutterflow support would need a complete reorganization to take Flutterflow to the next level. Also, I've suggested many times that Flutterflow needs a real ticketing system for user requests, not that horrible intercom solution. I give up, you can close the ticket I will publish the IOS version without the image.

**Comment by wenkaifan0720** [comment] 2023-03-19 15:02
Hi @RonGelb. Sorry for the delay. Please understand that the time it took to resolve an issue depends on the complexity of the subject. Since I haven't received the credentials via email, I couldn't really test it. That's why I provided you with some suggestions that I think are related to this issue. If you still want to proceed, please send me the necessary information so that I can start testing.

**Comment by wenkaifan0720** [comment] 2023-03-26 17:00
Hi @RonGelb. I tested on a iPhone 14 with the credentials you provided, but the app didn't crash. I don't think there are as many items in this page though.

**Comment by RonGelb** [comment] 2023-03-26 18:09
Hey, did you get the login details I sent you?

**Comment by RonGelb** [comment] 2023-03-26 18:29
Thanks for testing! What IOS version does your iPhone 14 have installed and how many GB is your device's memory?

**Comment by RonGelb** [comment] 2023-03-26 18:35
**And important**: You need to to select Sort by: "NAME" otherwise you will just display 50 records and have no crash!

**Comment by wenkaifan0720** [comment] 2023-03-26 18:39
Good question! iPhone 14 has 6GB of memory. I can downgrade my simulator to older iPhone models to test. What model(iOS version) are you testing with? And are you using the same credentials you sent me and still seeing the crash?

**Comment by wenkaifan0720** [comment] 2023-03-26 18:41
> **And important**: You need to to select Sort by: "NAME" otherwise you will just display 50 records and have no crash!

I did. The app is still not crashing. 

https://user-images.githubusercontent.com/112435854/227797053-54e45196-10e6-4647-9970-2a6a18be72a8.mp4

**Comment by RonGelb** [comment] 2023-03-26 19:44
OK I understand. On the simulator iPhone 14 (IOS 16.1) and iPhone X (IOS 16.1) the app doesn't crash on my side too. If I'm using physical devices iPhoneX (IOS 16.3.1.) 32,8 GB of 64 GB used and iPhone7 (15.7.1)  12,6 GB of 32 GB used  the app crashes. Physical iPad (IOS 15.6.1) 61,8 GB of 64 GB no crash.

**Comment by wenkaifan0720** [comment] 2023-03-26 20:09
Unfortunately I don't have these physical iPhone models to test with. I'll try to test with an older simulated iPhone and see how it goes.

**Comment by wenkaifan0720** [comment] 2023-03-27 02:01
https://user-images.githubusercontent.com/112435854/227820525-73e6ead1-df1a-47c8-a547-902d5119228a.mp4

I tested with a simulated iPhone 7 with iOS 15.5, and the app still doesn't crash.

**Comment by wenkaifan0720** [comment] 2023-04-10 14:02
Hi! We’re closing this issue due to inactivity, as we do not have enough information currently to investigate further. If this issue persists, please re-open this issue. Thanks!

**Closed by wenkaifan0720** 2023-04-10 14:02 UTC
Labels: status: needs triage, closed: other
