### ISSUE TITLE
Test Mode is Blank [Gray Screen]

### ISSUE THREAD

**Issue by Dev-Muhammad-Junaid** [FlutterFlow/flutterflow-issues#3017] opened 2024-05-30 14:08 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Test mode is not showing anything.
I tested two projects. Both comeup as blank pages no errors showed up in console.

### Expected Behavior

.

### Steps to Reproduce

1 Create a new project
2 Run Test mode 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40kufl0ItIxOFb7s/uKcJV+T45KVh/a4En0dV7aCosfZT2BLMcec/RVERWcM/iS29qe0yJr2oW0c72juHDFcBcC0uafb59+LlQbA7zcHq5VYirFJWgZ3RPEd5jIUyG16uOkBInALNsSE1mw2aMJuTLcHbDQJDsOFdNDq/LZO4=

### Context

.

### Visual documentation

<img width="1512" alt="Screenshot 2024-05-30 at 7 02 43 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/65047962/3273a588-c3bc-4421-889b-5a0a12f9c5e3">
<img width="1511" alt="Screenshot 2024-05-30 at 7 02 50 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/65047962/feb455db-5940-42b1-b95f-0fd224b84abb">

### Additional Info

Community posts on the same issue

https://community.flutterflow.io/ask-the-community/post/blank-display-on-test-mode-NPBaycCR7cHM2i5

### Environment

```markdown
- FlutterFlow version: v4.1.53+ released May 16, 2024
- Flutter version is 3.19.1
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected:  Mac
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by msusviela** [comment] 2024-05-30 15:13
Hey @Dev-Muhammad-Junaid, Thanks for your report, So sorry you are experiencing this issue. I was not able to reproduce this on a blank project, but it is replicable on yours. That's why I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. Thanks so much!

**Comment by Dev-Muhammad-Junaid** [comment] 2024-05-30 15:26
Hi @msusviela, Thanks for the update. 
Yes, I found this to be happening in a few projects. Tried instant reload as well.  I'll try to get in touch with the team if that works

**Comment by CigarPandaMan** [comment] 2024-05-31 03:56
I'm having a similar issue

**Comment by JJNoCode** [comment] 2024-06-02 10:59
Hi, I've got the same problem. The problem occurs on one of my projects in production. If you have a solution, I'm interested... I try some actions to retrieve a stable version but without success.

**Comment by AnnetteIB** [comment] 2024-06-04 13:26
Exactly the same issue here

**Comment by navaidali** [comment] 2024-06-28 08:19
I am having similar issue on my project, it was working fine but suddenly it's blank in run mode. There aren't any bugs or errors in the project... Any solution?

**Comment by msusviela** [comment] 2024-07-04 20:24
Sorry for the late response. Test mode is working at the moment. Is this still an issue for you? @navaidali

**Comment by navaidali** [comment] 2024-07-04 20:34
Yes I am still facing the same issue

**Comment by msusviela** [comment] 2024-07-04 20:43
Is this happening to all the projects or just one in particular? on which platform and on which version are you working?

**Comment by msusviela** [comment] 2024-07-09 16:56
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Closed by msusviela** 2024-07-09 16:56 UTC
Labels: waiting for user response

**Comment by devaiworking** [comment] 2025-02-08 06:20
don't close. this is happening to 2-3 projects. so annoying.
