### ISSUE TITLE
Textfield Min/Max stopped working as expected this Morning

### ISSUE THREAD

**Issue by marwenmadani** [FlutterFlow/flutterflow-issues#2625] opened 2024-03-29 16:09 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Text Field widget ignores Min Line Value and defaults to Max Line value.

Example Scenario:
Min Line Value = 1
Max Line Value = 10
Text field widget initial state shows 10 line widget size

In the BUILDER

![Screenshot 2024-03-29 at 12 00 19 PM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/a45a8c68-bd98-4c8f-9566-5eeb4641304d/3a979eb2-b26e-4835-a372-919d0ccf7a3e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hNDVhOGM2OC1iZDk4LTRjOGYtOTU2Ni01ZWViNDY0MTMwNGQvM2E5NzllYjItYjI2ZS00ODM1LWEzNzItOTE5ZDBjY2Y3YTNlIiwiaWF0IjoxNzExOTc4NTcyLCJleHAiOjMzMjgyNTM4NTcyfQ.hQjGBMsNr5SAqZDCrjO4aqY3BA45uAnC2lL4P0P6Fh0 "=1072x")

In TEST MODE

![Screenshot 2024-03-29 at 12 02 28 PM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/673859e5-43d1-4e49-8ee7-c890dadc775a/bd1a92d5-939c-4781-af69-ff80a0809855?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82NzM4NTllNS00M2QxLTRlNDktOGVlNy1jODkwZGFkYzc3NWEvYmQxYTkyZDUtOTM5Yy00NzgxLWFmNjktZmY4MGEwODA5ODU1IiwiaWF0IjoxNzExOTc4NTcyLCJleHAiOjMzMjgyNTM4NTcyfQ.wXa3t28TpkEGu0h940G9-ksvrHtvRzNo5agM9hgC9M0 "=1072x")

### Expected Behavior

Text Field widget defaults to Min Line Value if defined

### Steps to Reproduce

1. Create Blank Page
2. Add Text field widget
3. Set Max line value to 2 (or higher)
4. Press Test

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT9Xk871z4tPsfVc+KX6YMEwvDwsQls7bZJFlutudwIdDOuuBIYuP+HBXFJWXf25YmxEeFm3+Xgy7t3HudnMMeYDAxGqY75M+qpuUQLhLXGXSrWaBpCodUZVGv5QI0DD352g2BFTHMlpWVIQ206YGO+AaAjsH5vzJ0QRJv+LCID7o3DlLB/rDzhs7ysLIHGsBcYEag+ukYbK6P4Curyq/ol8qBVXzoPSwtX1TBKTWVk=

### Context

I'm currently blocked from releasing my new app update as this is affecting all text fields in my App.
This is affecting all my projects

### Visual documentation

![Screenshot 2024-03-29 at 12 00 19 PM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/0a92aa07-1bff-4d80-bdfe-bd68a362fa4e/500ae85d-cf4b-4a65-9a7f-5a1065cb6b32?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wYTkyYWEwNy0xYmZmLTRkODAtYmRmZS1iZDY4YTM2MmZhNGUvNTAwYWU4NWQtY2Y0Yi00YTY1LTlhN2YtNWExMDY1Y2I2YjMyIiwiaWF0IjoxNzExOTc4NTcyLCJleHAiOjMzMjgyNTM4NTcyfQ.p9RBtw0g3oKSogT9zMCGSVe_X7CYTcQAtWK8kjAWFPo "=1072x")

![Screenshot 2024-03-29 at 12 02 28 PM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/ea80ef15-cb12-4a85-a968-ccff342dbc25/3a1eb04b-4929-4316-a9b5-18296238f9d4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lYTgwZWYxNS1jYjEyLTRhODUtYTk2OC1jY2ZmMzQyZGJjMjUvM2ExZWIwNGItNDkyOS00MzE2LWE5YjUtMTgyOTYyMzhmOWQ0IiwiaWF0IjoxNzExOTc4NTcyLCJleHAiOjMzMjgyNTM4NTcyfQ.e0qDOQtuDqrxojtQDNTxafHAKWbC-B2tlSAUqaEdwso "=1072x")

### Additional Info

*No response*

### Environment

```markdown
FlutterFlow v4.1 released March 28, 2024
Flutter version is 3.19.1
```

**Comment by kenshintani** [comment] 2024-03-29 23:49
I have the same problem.

**Comment by kaihungc1993** [comment] 2024-03-31 00:14
+1
My project used to work, but the latest test, run, and published code all have this issue.
When MaxLines is set and MinLines is set to 1, the code codesn't include MinLines. 
But if set to other values, say 2, the code includes the MinLines and works as expected.

**Really need to fix this asap.**

**Comment by Tribe77-Tech** [comment] 2024-03-31 06:38
Same here!
This was fine a few weeks back, I suspect some recent update broke this.

**Comment by bozzoleandro** [comment] 2024-04-01 14:43
Hi @marwenmadani, we were able to replicate this issue, we're looking into it. Thanks for the report

**Comment by corsaro0** [comment] 2024-04-02 08:23
+1 Same here please resolve quickly I need to launch the update

**Comment by Wittrup90** [comment] 2024-04-02 09:06
Same here - its a biggy. please fix asap.

**Comment by LucasBene** [comment] 2024-04-02 15:14
Same here! I've been talking with the support today, they have already raised the ticked internally. We need to wait for their move now and release update with bug fixes.

**Comment by szymdzie** [comment] 2024-04-03 10:32
A bug fix is needed quickly. The app is waiting to be released.

**Comment by LucasBene** [comment] 2024-04-04 16:22
Is this bug fixed? Because in our apps (all apps) same bug still there.

**Comment by marwenmadani** [comment] 2024-04-04 17:52
Hey FF Team, 
I tested this on TEST & RUN Modes and I'm still facing the same issue.
Please advise.

Tests conducted on this version:
FlutterFlow v4.1 released April 4, 2024
Flutter version is 3.19.1

**Comment by LucasBene** [comment] 2024-04-04 19:11
Same here!

**Comment by szymdzie** [comment] 2024-04-04 20:54
Same here...

**Comment by eduriftio** [comment] 2024-04-05 00:45
Yes not fix, why they closed it @takashiff

**Comment by eduriftio** [comment] 2024-04-05 00:46
@szymdzie @LucasBene @marwenmadani They mentioned it will be fixed with upcoming release today

**Comment by eduriftio** [comment] 2024-04-05 03:23
@takashiff I got the Flutterflow update, and the issue has not been fixed. Please check the screenshot. 
Flutterflow v4.1.36

![Screenshot 2024-04-05 at 1 21 20 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/145130088/e3493057-8f4c-4e37-a73c-f85fef9a16cb)

**Comment by rpock** [comment] 2024-04-05 09:30
I can confirm, that the error is still present in version 4.1.36 (tested in macOS FF app). In the FF UI it show's correctly, but the Flutter code is not generated correctly, the minLines property is still missing in the generated code. 


`// Generated code for this TextField Widget...
Padding(
  padding: EdgeInsetsDirectional.fromSTEB(8.0, 0.0, 8.0, 0.0),
  child: TextFormField(
    controller: _model.textController,
    focusNode: _model.textFieldFocusNode,
    autofocus: true,
    obscureText: false,
    decoration: InputDecoration(
      labelText: 'Label here...',
      labelStyle: FlutterFlowTheme.of(context).labelMedium.override(
            fontFamily: 'Montserrat',
            letterSpacing: 0.0,
          ),
      hintStyle: FlutterFlowTheme.of(context).labelMedium.override(
            fontFamily: 'Montserrat',
            letterSpacing: 0.0,
          ),
      enabledBorder: UnderlineInputBorder(
        borderSide: BorderSide(
          color: FlutterFlowTheme.of(context).alternate,
          width: 2.0,
        ),
        borderRadius: BorderRadius.circular(8.0),
      ),
      focusedBorder: UnderlineInputBorder(
        borderSide: BorderSide(
          color: FlutterFlowTheme.of(context).primary,
          width: 2.0,
        ),
        borderRadius: BorderRadius.circular(8.0),
      ),
      errorBorder: UnderlineInputBorder(
        borderSide: BorderSide(
          color: FlutterFlowTheme.of(context).error,
          width: 2.0,
        ),
        borderRadius: BorderRadius.circular(8.0),
      ),
      focusedErrorBorder: UnderlineInputBorder(
        borderSide: BorderSide(
          color: FlutterFlowTheme.of(context).error,
          width: 2.0,
        ),
        borderRadius: BorderRadius.circular(8.0),
      ),
    ),
    style: FlutterFlowTheme.of(context).bodyMedium.override(
          fontFamily: 'Montserrat',
          letterSpacing: 0.0,
        ),
    maxLines: 5,
    validator: _model.textControllerValidator.asValidator(context),
  ),
)`

**Comment by corsaro0** [comment] 2024-04-05 13:42
I have been waiting for the resolution of this problem for over 8 days and I am unable to launch the update of my app. Please speed this up

**Closed** 2024-04-05 16:47 UTC
Labels: status: confirmed, Bug

**Comment by eduriftio** [comment] 2024-04-06 01:37
@takashiff @rzambroni Does status "completed" mean it will be fixed soon? I just checked again, nothing has changed, the same problem.

**Comment by rzambroni** [comment] 2024-04-06 03:58
hey @eduriftio, a fix for this was made but it's not yet live on prod.

**Comment by corsaro0** [comment] 2024-04-06 08:49
hi @rzambroni When can we expect to have the update?

**Comment by rpock** [comment] 2024-04-08 09:17
Issue not solved in Version 4.1.38 @takashiff 
 
Problem: minLines Value not set when it is set to 1 in FlutterFlow. If minLines ist set to 2 or above, the value is set in the flutter code.
 
minLines have to be set also when it's 1.

**Comment by szymdzie** [comment] 2024-04-08 20:45
How long? Two weeks? Are you kidding me? This is a critical issue that is affecting many views in app, such as Chat for example. It should be implemented/updated as a priority. Please intervene promptly on this matter.

**Comment by corsaro0** [comment] 2024-04-09 07:57
@takashiff @rzambroni We have been waiting for two weeks for this bug to be resolved. Is it possible to have news regarding the release date? We haven't been able to send updates for too long

**Comment by marwenmadani** [comment] 2024-04-11 19:44
Thank you FF Team!

I can confirm everything is working as expected in the following ff version:
FlutterFlow v4.1 released April 11, 2024
Flutter version is 3.19.1

**Comment by corsaro0** [comment] 2024-04-11 20:13
Finally thank you so much!
