### ISSUE TITLE
Conditional Actions In Callbacks raising error with no reason!!

### ISSUE THREAD

**Issue by NadavTraub** [FlutterFlow/flutterflow-issues#2454] opened 2024-03-06 13:00 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When configuring a conditional action within a callback action flow editor, the FlutterFlow dashboard displays an error. Clicking on this error redirects you to the regular action flow editor (not the callback's editor) while showing an error message. Upon clicking the error again, it turns green and disappears, but the error persists on the dashboard outside this flow, preventing the app from running.

### Expected Behavior

The expected behavior is that the error will not arise since it's a valid action (as indicated by the green color in the callback action flow editor), allowing me to run my app successfully.

### Steps to Reproduce

1. create page
2. create custom component that receive a action 
3. pass action flow with conditional action 
4. try run the app

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

getting also error when trying to generate the code

### Context

trying to pass action into custom component 
and now cant run the app

### Visual documentation

<img width="1344" alt="Screenshot 2024-03-06 at 14 52 49" src="https://github.com/FlutterFlow/flutterflow-issues/assets/122477844/a8f04381-72b9-4e46-bc06-239244eb8c78">
<img width="1315" alt="Screenshot 2024-03-06 at 14 53 01" src="https://github.com/FlutterFlow/flutterflow-issues/assets/122477844/0a9a7fe5-2c53-482c-a9cb-8c9f3d952aab">
<img width="603" alt="Screenshot 2024-03-06 at 14 53 13" src="https://github.com/FlutterFlow/flutterflow-issues/assets/122477844/ee6f68ab-9ae6-4b73-9a50-9909c599c677">
<img width="1314" alt="Screenshot 2024-03-06 at 14 53 29" src="https://github.com/FlutterFlow/flutterflow-issues/assets/122477844/25ac95ea-6506-4946-a436-e44779145a37">
<img width="1158" alt="Screenshot 2024-03-06 at 14 53 37" src="https://github.com/FlutterFlow/flutterflow-issues/assets/122477844/3117cb41-9efa-4e31-b6af-03a6e570f193">
<img width="1302" alt="Screenshot 2024-03-06 at 14 53 44" src="https://github.com/FlutterFlow/flutterflow-issues/assets/122477844/d2cdeff9-e587-4d4b-aede-f86ff9126cb5">
<img width="1291" alt="Screenshot 2024-03-06 at 14 53 52" src="https://github.com/FlutterFlow/flutterflow-issues/assets/122477844/bbbc94b6-3c86-4783-a724-8b27e6114c6a">

### Additional Info

https://app.flutterflow.io/project/matchia-x17o2f

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: macOs, wed
- Browser name and version: Chrome Version 122.0.6261.94 (Official Build) (x86_64) and Safary
- Operating system and version affected: desktop macOs Sonoma 14.3.1
```

**Comment by josescgar** [comment] 2024-03-09 11:42
Maybe duplicate of https://github.com/FlutterFlow/flutterflow-issues/issues/2464 ?

**Comment by NadavTraub** [comment] 2024-03-17 10:04
@josescgar yes

**Comment by kemperflow** [comment] 2024-03-19 16:39
This has recently popped up for me as well. I am using a Drawer that contains a listView. I have actions associated with a ReOrder event. I am simply using built-in parameters of OldIndex and NewIndex. Randomly I will get this same error message, I simply open the condition, click the evaluation and save it again. I don't change anything. It clears the error long enough to send to GitHub, but it will pop an error condition again. Highly annoying.. I originally had a 3 branch multi condition, I broke it out into these individual conditions to see if it would make the error go away. It did not.

![Screenshot 2024-03-19 121824](https://github.com/FlutterFlow/flutterflow-issues/assets/63926602/af1e27af-a38c-45a3-894b-ad58b8743fd7)
![Screenshot 2024-03-19 121839](https://github.com/FlutterFlow/flutterflow-issues/assets/63926602/8ec7d6fc-8cc2-4113-9255-da4e012f883d)
![Screenshot 2024-03-19 121848](https://github.com/FlutterFlow/flutterflow-issues/assets/63926602/a3de4049-e9e9-4971-b14b-c14efb1d4ee9)

**Comment by ignalauret** [comment] 2024-04-15 23:19
Hey @NadavTraub thanks for your report. The technical team is already reviewing this errors that appear with the callbacks in conditional actions. Please follow [https://github.com/FlutterFlow/flutterflow-issues/issues/2464](https://github.com/FlutterFlow/flutterflow-issues/issues/2464) to stay updated on the fix. <br>I'm closing this issue because it's duplicated, have a great day!

**Closed** 2024-04-15 23:19 UTC
Labels: closed: duplicate
