### ISSUE TITLE
Invalid OAuth response from Apple.com

### ISSUE THREAD

**Issue by sanjayelate** [FlutterFlow/flutterflow-issues#4551] opened 2024-10-23 17:23 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Since the update, authentication has stopped working with apple. It works with previous builds before the update but now it just says Invalid OAuth response from Apple.com. I haven't touched anything to do with the authentication flow. The dependancies are all up to date

### Expected Behavior

It should log in

### Steps to Reproduce

Use Apple log in with firebase

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfk8n1z892pbwC+a6JLMJKiSkXNW0cTeU30+thcw4bI+P0BLAUeeLOblNoSOqHYFFAJFmigmcC/975v9mSDsECGwScG5he/qppUxDiQlqmVbrREpG0R3FSM/tWf0+Oy7SnhRYlOvF2ZVJi7V73BN+Qb3qCf9qOYwx5e6fDbOY=

### Visual documentation

![375966BA-02A5-48D6-A8F0-801DD2188A27](https://github.com/user-attachments/assets/a9c44a5d-1e92-4014-bb2b-35145d5815fc)

### Environment

```markdown
- FlutterFlow version: v5.0.8
- Operating system and version affected: iOS
```

**Comment by rzambroni** [comment] 2024-10-23 17:58
Hi @sanjayelate,

Thank you for bringing this up! We’re aware of this issue as it has already been reported, The team is currently investigating it. In the meantime, there’s a valid workaround that can help while we work towards a permanent solution.

I’ll close this ticket as a duplicate of the [original ticket](https://github.com/FlutterFlow/flutterflow-issues/issues/4445), please refer to it for updates.

Thanks again!

**Closed as not planned by rzambroni** 2024-10-23 17:58 UTC
Labels: closed: duplicate
