### ISSUE TITLE
data table sort does not permit ascending/descending

### ISSUE THREAD

**Issue by rcandeo** [FlutterFlow/flutterflow-issues#2869] opened 2024-05-07 22:11 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

actually I can click on my column and the toogle changes do ascending/descending. So I saved it in action to be used at Generating Children from variable, where I choose the column to sort based on the clicked one, but there is no place to select the order of this columns
I am using supabase

### Expected Behavior

I need to select the sort order of the clicked column

### Steps to Reproduce

create a data table, select generate children from variable
on action move the data sort column index to the page variable and the toogle to the other variable
coming back to generate children from variable, select the order to sort depending on the variable but there is no order to select

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

failed to copy to clipboard - i could not get

### Context

my customer needs to see in ascending/descending order

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/150471618/019a26ba-0709-4731-a190-d3c8ff407dac)

### Environment

```markdown
- FlutterFlow version: latest
- Platform:web
- Browser name and version:chrome/safari
- Operating system and version affected: all
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by msusviela** [comment] 2024-05-09 13:49
Hi @rcandeo - Thanks for submitting the issue. I've taken a look at your project, but with a lot going on, it's challenging to pinpoint the issue. Given the nature of the problem you're highlighting, we need a blank project with the issue steps set up in it. Without these details, it might be a bit challenging for us to investigate the issue. Please provide the required information. If the issue is already resolved for you, please feel free to close the issue. Thanks!

**Comment by rcandeo** [comment] 2024-05-09 23:43
hello, I just created a new app (ordenate data table) from scratch with the same issue. I still have error trying to generate the bug report code but we can establish an on-line meeting anytime
thank you so much for your attention

**Comment by rcandeo** [comment] 2024-05-10 17:38
tell me if you want me to share the project with you

**Comment by rcandeo** [comment] 2024-05-14 14:37
is there a way to report this bug that someone of flutter flow answers me?

**Comment by rcandeo** [comment] 2024-05-22 02:22
I am still waiting someone help me please

**Comment by msusviela** [comment] 2024-05-22 23:18
Hey @rcandeo, Thanks for your report, So sorry you are experiencing this issue. I was not able to reproduce this on a blank project, but it is replicable on yours. <br><br>For a blank project, I was following this documentation, please check that you're following the right steps<br>[https://docs.flutterflow.io/widgets-and-components/widgets/layout-elements/datatable-paginated](https://docs.flutterflow.io/widgets-and-components/widgets/layout-elements/datatable-paginated)

I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. 

Thanks so much!

**Comment by rcandeo** [comment] 2024-05-23 02:54
Hello @msusviela I tried with a blank project and have the same issue, and I have followed the documentation you sent to me, but I didn´t created the dart code in my project. I am thinking why there is a toogle option to move to a variable if this variable don´t have a place to be used in the generating children from variable?
If I wanted to use dart I was not asking for help in a flutter flow group. I would be in a flutter group
And even if I try to use the example it was not created to supabase, so it did not helped me

**Comment by msusviela** [comment] 2024-05-23 13:21
I wasn't able to reproduce it with the steps you provided.  I followed the mentioned documentation and could make it work from a blank project.<br><br>Please, send a more detailed step to step of what you did so I can get more insight into what's the issue. At this point, it's necessary for me to have the bug code so I can get more context into the situation.

**Comment by rcandeo** [comment] 2024-05-23 13:27
I appreciate you are trying to help, but I am not sure if this is a bug or this option that I am trying to use does not exist, cause as I told you, I couldn´t find where to use "Data Table Sorted Ascending" value
about the bug code, I have no idea but every time I try to generate I receive the attached error

![Captura de Tela 2024-05-23 às 10 26 42 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/150471618/52810024-35c4-4730-b4fe-4da5fb22a4f7)
![Captura de Tela 2024-05-23 às 10 26 27 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/150471618/c49dea71-9157-4a9d-96e1-9df4a0c71c15)

**Closed** 2024-07-09 21:38 UTC
Labels: waiting for user response
