### ISSUE TITLE
Gradient text is cut off

### ISSUE THREAD

**Issue by Franco-Cruz-Schoolfy365** [FlutterFlow/flutterflow-issues#71] opened 2022-10-31 05:55 UTC
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

Show a gradient text

## Current behavior (required)

Some time the gradient text is show correctly and others is cut off

## To Reproduce (required)

1. Create a text
2. Add a the first gradient template

Now it is complicated to reproduce because some time works and sometimes it is cut off as you can see in the video

## Context (required)

Create a gradient text

## Screenshots / recordings

https://schoolfy365.tinytake.com/msc/NzUxMTI0NV8yMDQ0NTgwMQ

## Your environment

* **Bug Report Code:** ITFTz/Hqx89grtRI+KX2du1GiigWM0MBX5Ir1utvGA4aG5yrPLMMfsz+aXdYUumYd247EWGaimoe0d7lvvDlLMBfITWYQJ82k/UwKlCvHAM=
* Version of FlutterFlow used: v3.0 - 28 October
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Brave - Version 1.45.116 Chromium: 107.0.5304.91 (Official Build) (64-bit)
* Operating system and version (desktop or mobile): Windows 11 - OS Build: 22621.674 - Version: 22H2

**Comment by hariprasadms** [comment] 2022-10-31 17:54
I can test this and see it works fine for me (in preview and run mode both). However, I noticed that sometimes on the editor after adding gradient, text get cuts off but it comes back fine after refreshing the page. This behaviour is very much inconsistent. We can keep this as non re producible for now. If it is consistence later, we can re-open. Thanks for posting the issue.

**Comment by wenkaifan0720** [comment] 2022-11-07 05:22
As we are not able to reproduce this issue, I will close this issue for now.

**Closed by wenkaifan0720** 2022-11-07 05:22 UTC
Labels: status: can't reproduce
