### ISSUE TITLE
Setting Lottie Animations from Variable is not working. 

### ISSUE THREAD

**Issue by bulgariamitko** [FlutterFlow/flutterflow-issues#308] opened 2023-01-02 09:42 UTC
## Expected behavior (required)
When you click on Path - Set from Variable and click on Run mode see the Lottie Animation.

## Current behavior (required)
Right now when you set Lottie Animation from Variable the animation is not showing. 

## To Reproduce (required)
1. Create API Call that is getting Lottie Animation from the web or try to supply the animation from custom code like custom function
2. Add LottieAnimation Widget
3. Click on Path - Set from Variable
4. Select the JSON Path from the API that is returning the LottieAnimation or select the Custom Code (Function) which is returning a String path to a web URL of a LottieAnimation. I used GitHub raw - demo link - https://raw.githubusercontent.com/bulgariamitko/flutterflowtutorials/main/Apps/Yettel/Animations/1-2-3-4-5.json

### Bug Report Code (required, generate from Widget Tree)
IT4CyvHq2892ofpE7c/QYMJagmAXJkw1RYIZ09YaUQs3HZPHCpl/P8nRak5dXbCiTGxIeWKZ8X4I7vzNhdnpG/k3PQuIQ75n/6t9EgLKTXyhR5CvPbrsP3xBO+JhN2nG1KLc1EsZYI43ExhYggfOQw==

## Context (required)
If I want to use 100 different Lottie Animations in my page I have to add 100 Widgets right now :/ 

## Your environment
* Version of FlutterFlow used: 3.3.4
* Platform (e.g. Web, MacOS Desktop): web
* Browser name and version: 108
* Operating system and version (desktop or mobile): desktop

**Comment by bulgariamitko** [comment] 2023-01-02 09:43
@organicnz , I think you said you had the same issue right?

**Comment by organicnz** [comment] 2023-01-28 10:54
> @organicnz , I think you said you had the same issue right?

Yeah, mate, I don't see the animation as well :)

**Comment by wenkaifan0720** [comment] 2023-04-04 03:41
Hi @bulgariamitko. Sorry for taking this long to respond, this issue is just assigned to me. I looked into the code and the good news is the generated code is correct when a variable path is set. The problem is with Lottie web + run mode where we have to wrap lottie inside of a webview which is causing trouble. It won't affect your app when you run it locally or publish it.

**Comment by bulgariamitko** [comment] 2023-04-04 08:54
@wenkaifan0720 , so basically in order to run Lottie animations for web you need to deploy your project for web. You can't see the lottie animations in Test Mode and run mode, right?

**Comment by wenkaifan0720** [comment] 2023-04-04 13:36
Lottie animation will always work on mobile (no matter how you setup the path). But right now on Web, it will only work if you type in the path directly. This is because Lottie doesn't fully support web right now so we had to do some custom implementation. I will try to find a solution, but it might take a while.

**Comment by wenkaifan0720** [comment] 2023-04-05 14:49
Hi @bulgariamitko. Lottie will work on the web with a variable path with the coming fix. However you still wouldn't be able to see it in run/test mode (I suspect that is because they are embedded in an iframe). If you publish to the web, then you can preview it.

**Closed by wenkaifan0720** 2023-04-05 14:49 UTC
Labels: type: bug, status: confirmed, closed: fixed

**Comment by paulVu** [comment] 2023-04-17 04:10
More issue with iPad screen, that's work on mobile. 
<img width="225" alt="Screen Shot 2023-04-17 at 11 09 45" src="https://user-images.githubusercontent.com/5320015/232375912-6a09fada-b33c-4454-9416-a1811ed9e120.png">

**Comment by bulgariamitko** [comment] 2023-04-17 06:58
@paulVu , is this related to the Lottie Animations?

**Comment by Franco98404** [comment] 2023-04-19 03:26
Hi @bulgariamitko @wenkaifan0720, I have 3 problems related to the Lottie Animations, can you check please?

https://github.com/FlutterFlow/flutterflow-issues/issues/295
https://github.com/FlutterFlow/flutterflow-issues/issues/296
https://github.com/FlutterFlow/flutterflow-issues/issues/784

**Comment by bulgariamitko** [comment] 2023-04-19 06:36
I re-open some of the issues and confirm the others. You are right there are a lot of bugs around Lottie animations, but I will provide the exact Lottie animation as maybe this is the issue?
