### ISSUE TITLE
Weird division of Japanese text

### ISSUE THREAD

**Issue by idea-garage** [FlutterFlow/flutterflow-issues#878] opened 2023-05-12 09:31 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I set these texts and publish them to the web, English texts like "Test of Japanese text" are split by spaces in "fit-span" in the HTML source.
However, the strange thing is that Japanese sentences like "日本語テキストのテスト" are divided for each character as follows.

<flt-span style="color: rgb(16, 18, 19); font-size: 14px; font-weight: normal; font-family: Poppins_regular, -apple-system, BlinkMacSystemFont, sans-serif; position: absolute; top: 0px; left: 0px; width: 14px; line-height: 21px;">日</flt-span>

<flt-span style="color: rgb(16, 18, 19); font-size: 14px; font-weight: normal; font-family: Poppins_regular, -apple-system, BlinkMacSystemFont, sans-serif; position: absolute; top: 0px; left: 14px; width: 14px; line-height: 21px;">本</flt-span>

<flt-span style="color: rgb(16, 18, 19); font-size: 14px; font-weight: normal; font-family: Poppins_regular, -apple-system, BlinkMacSystemFont, sans-serif; position: absolute; top: 0px; left: 28px; width: 14px; line-height: 21px;">語</flt-span>

This dont suite SEO optimized. In order to reduce the source size of the web, please revise so that strings with the same style are grouped together.

### Expected Behavior

I expect to these output:

<flt-span style="color: rgb(16, 18, 19); font-size: 14px; font-weight: normal; font-family: Poppins_regular, -apple-system, BlinkMacSystemFont, sans-serif; position: absolute; top: 0px; left: 0px; width: 14px; line-height: 21px;">日本語テキストのテスト</flt-span>

### Steps to Reproduce

1.Create a new page
2.Add text widget
3.set Japanese text like "日本語テキストのテスト"
4.Test mode
5.View source in Chrome devtools

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEelsn1z4pNj70B1aXuc8Iw+AMxJ1gjbJ0vhNVEewg0fLWsB+0tbuvRchZfUuHndAlEE2eankwepqHVuOzhCewnBE2EQ5Rj1qoMVQn/ZH6QRLaPCs6Sf3FRP+xgfEC00J+jsB5BIrBsS3ctig/GSw==

### Context

This dont suite SEO optimized. In order to reduce the source size of the web, please revise so that strings with the same style are grouped together.

### Visual documentation

<img width="766" alt="スクリーンショット 2023-05-12 18 30 57" src="https://github.com/FlutterFlow/flutterflow-issues/assets/35732672/a18348de-45f0-4cc3-9b28-f170288fc87b">

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform:Mac
- Browser name and version:Chrome 113.0.5672.92
- Operating system and version affected: macOS 11.7.4
```

**Comment by bulgariamitko** [comment] 2023-05-13 15:23
Can you place a picture of your widget tree as well and where are you using the text?

**Comment by idea-garage** [comment] 2023-05-14 04:36
Thanks. Below are the information. Any information is welcome.

Link to the editor:
https://app.flutterflow.io/project/blank-5iuckn

Widget tree:
<img width="270" alt="WidgetTree" src="https://github.com/FlutterFlow/flutterflow-issues/assets/35732672/dbc26ec7-b506-4e6e-a1df-e9094eea95fa">

**Comment by bulgariamitko** [comment] 2023-05-15 08:01
Sorry I do not have access to the FF projects, can you also post a screenshot where the value of the text widget it is coming from? Is it from source and if it is can you show us the value in the source as well?

**Comment by idea-garage** [comment] 2023-05-15 15:55
Thanks, sorry for inconvinience. this is the screenshot, value of the Text widget is normal value, as "日本語テキストのテスト". Is it enough information? 
<img width="310" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/35732672/685109db-53b0-4775-bbff-a6657b32e9b8">

**Comment by victoriahuang1** [comment] 2023-05-16 21:47
Hi @idea-garage , I can't reproduce the issue. I tried both the test project and published page that you provided, and this is what I see:

https://github.com/FlutterFlow/flutterflow-issues/assets/16326980/fd6449ae-0883-49c5-a037-338bc034b635

**Comment by idea-garage** [comment] 2023-05-17 00:30
Thank you and I apologize incombinience.
This is what I'm saying. Simply HTML source is weird in chrome developer tools.
<img width="1117" alt="screen" src="https://github.com/FlutterFlow/flutterflow-issues/assets/35732672/a8643271-f989-483b-a651-026544c74f78">

**Comment by victoriahuang1** [comment] 2023-05-24 06:51
Hi @idea-garage , thanks for the update. This is the expected behavior of Flutter code.

We will keep thinking of how to improve SEO with Flutter, but will be closing this as a feature request and not a bug.

**Closed by victoriahuang1** 2023-05-24 06:51 UTC
Labels: closed: feature request

**Comment by idea-garage** [comment] 2023-05-24 07:41
Thanks, I know. Hope it solves in the future.
