### ISSUE TITLE
await initFirebase(); moving after final appState = FFAppState(); issue

### ISSUE THREAD

**Issue by MahmoudIsmail88** [FlutterFlow/flutterflow-issues#4019] opened 2024-10-09 17:56 UTC
### Can we access your project?

- [ ] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

seems I am the first to report on this. in an update in the last hour or so , FF moved the initFirebase(); in the main.dart to after initializing the app state (final appState = FFAppState(); ) . this creates errors

moving the await initFirebase(); to before (final appState = FFAppState(); ) as it used to be solves the problem

### Expected Behavior

the app runs with no issue 

### Steps to Reproduce

Just start an application that is connected to Firebase 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

NA

### Visual documentation

![Capture](https://github.com/user-attachments/assets/d65e1698-6415-4ad8-a2ad-23c4622cf55b)

### Environment

```markdown
- FlutterFlow version: latest 
- Platform: windows 
- Browser name and version: NA testing on device
- Operating system and version affected:  all operating systems
```

**Comment by squirrel-o** [comment] 2024-10-09 18:01
same issue here on macOS

**Comment by Alezanello** [comment] 2024-10-09 18:17
Hello!

Could you kindly share the Bug Report Code from your project so we can test it? Thank you!

**Comment by Alezanello** [comment] 2024-10-09 18:27
I've been trying to replicate from a new blank project without success, as soon as you can please share a bug report code from your project in order to validate this bug!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/a46ea3aa-4785-4968-a828-da143f804be9/c67c8fe0-bd4b-4288-8cf5-1279f053cb08?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hNDZlYTNhYS00Nzg1LTQ5NjgtYTgyOC1kYTE0M2Y4MDRiZTkvYzY3YzhmZTAtYmQ0Yi00Mjg4LThjZjUtMTI3OWYwNTNjYjA4IiwiaWF0IjoxNzI4NDk4NDUxLCJleHAiOjMzMjk5MDU4NDUxfQ.hk3qOfsNK1eHZqI2w0tefhNf5XTlg0tEbaHjfAHicY0 " alt="Imagen de WhatsApp 2024-10-09 a las 15.25.45_3e20557e.jpg" width="1280" height="699" />

**Comment by MahmoudIsmail88** [comment] 2024-10-09 18:32
@Alezanello 

it is not related to a specific widget, but here is the code from my homepage : ITFXlPLq249Om+5E1c/ucMZKliowGUwbUOc7j9VEGAsjCeOsOrMTePTBVBRBYuqHY2NIHlekkmIG+uj5iofDA/VfZDurbt1T+YdbUxDiQkGXRarRC6jtf3N6P8JjfX3EyMKRrwldKvphSi05wV+DNemub3qCf9qOYwx5e6fDbOY=

I followed step 8 in this guide  (https://docs.flutterflow.io/misc/submit-bug-report/) to get the code

**Comment by Alezanello** [comment] 2024-10-09 18:33
This will help a lot, thanks!

**Comment by FanbaseTickets** [comment] 2024-10-09 18:57
Having the same issue here on web, macOS, and windows.

**Comment by bags307** [comment] 2024-10-09 19:03
It looks like the issue is that they moved around the first few inits in main.dart.
This is code from this morning:
```void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  GoRouter.optionURLReflectsImperativeAPIs = true;
  usePathUrlStrategy();
  await initFirebase();

  await FlutterFlowTheme.initialize();

  final appState = FFAppState(); // Initialize FFAppState
  await appState.initializePersistedState();

  if (!kIsWeb) {
    FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterFatalError;
  }

  runApp(ChangeNotifierProvider(
    create: (context) => appState,
    child: const MyApp(),
  ));
```
  
  And here is the current:

```void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  GoRouter.optionURLReflectsImperativeAPIs = true;
  usePathUrlStrategy();
  final appState = FFAppState(); // Initialize FFAppState
  await appState.initializePersistedState();
  debugLogAppState(appState);
  appState.addListener(() {
    debugLogAppState(appState);
  });

  debugLogAppConstant();

  await initFirebase();

  await FlutterFlowTheme.initialize();
```

**Comment by Alezanello** [comment] 2024-10-09 20:27
Hello everyone,

The issue has been confirmed, and a hotfix will be released shortly. Thank you for your patience!

**Comment by MartinLockheart** [comment] 2024-10-10 00:48
I'm not sure what all this affects, but I've been trying to diagnose an issue where it seems none of my document references are being registered. Is this part of that?

**Comment by nathan2580** [comment] 2024-10-10 05:52
> Hello everyone,
> 
> The issue has been confirmed, and a hotfix will be released shortly. Thank you for your patience!

Hey has this hot fix been deployed yet?

**Comment by nathan2580** [comment] 2024-10-10 08:33
Can confirm hotfix still not deployed, as per latest check - initFirebase still follows after the app state:
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  GoRouter.optionURLReflectsImperativeAPIs = true;
  usePathUrlStrategy();
  final appState = FFAppState(); // Initialize FFAppState
  await appState.initializePersistedState();

  await initFirebase();

  runApp(ChangeNotifierProvider(
    create: (context) => appState,
    child: MyApp(),
  ));
}

**Comment by MartinLockheart** [comment] 2024-10-10 08:37
Yeah, I have updates for clients delayed, unfortunately.

**Closed as not planned** 2024-10-10 16:00 UTC
Labels: status: confirmed, Bug

**Comment by MartinLockheart** [comment] 2024-10-11 06:15
Is there an ETA on the "hotfix"?

**Comment by MahmoudIsmail88** [comment] 2024-10-11 14:24
@MartinLockheart  , it is working for me now.
