### ISSUE TITLE
The project closed when i try create a action in the option Search for Field"   IF I TRY TO CLIC "ESC" in this option

### ISSUE THREAD

**Issue by GilPgm** [FlutterFlow/flutterflow-issues#2140] opened 2024-01-11 11:00 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

. The app is closed if you tap ESC in then option Update App State in then window "Search For Field"
. O aplicativo é fechado quando voce digita ESC na opção de Update App State na janela "Search For Field"

### Expected Behavior

Não fechar o aplicativo
Dont close the app

### Steps to Reproduce

----------------
I was in SCAFOLD trying to create action but if you tap ESC in SEARCH FOR FIELD 
the program to be close, see : 
----------------
Estava no SCAFOLD tentando criar uma ação, mas ao clicar em ESC ele fecha o aplicativo, assim : 
. ADD ACTION : On Page Load
. STATE Management, 
. UPDATE AppState, 
. ADD FIELD  ( attention for then problem ) 
. SEARCH FOR FIELD : <--- Aqui, se digitar ESC, o aplicativo vai FECHAR esse é o erro !
. SEARCH FOR FIELD : <--- Here if you tap ESC then app was close !

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

veja exemplo acima

### Context

veja exemplo acima

### Visual documentation

veja exemplo acima

### Additional Info

veja exemplo acima

### Environment

```markdown
- FlutterFlow version: 4 jan 2024
- Platform: windows
- Browser name and version: google chrome  
- Operating system and version affected: Windows 10 pro
```

**Comment by hariprasadms** [comment] 2024-01-11 11:50
Hi @GilPgm - Kindly update the issue details to English language, please. This is to ensure that issue details are in a general language to assist all users.

**Comment by hariprasadms** [comment] 2024-01-18 10:38
Hi @GilPgm - I'm still not able to fully understand the issue your experiencing. If you could provide more details about the issue you're facing, such as specific error messages, steps to reproduce the problem, or images, I would be better able to assist you. Additionally, if you can share a quick video clip demonstrating the issue, it would greatly help in understanding the issue.

Please close the issue if issue already been resolved to you. Thanks

**Comment by hariprasadms** [comment] 2024-02-04 20:13
Due to inactivity and no further additional details, I presume you are not experiencing the issue any more. Hence closing the issue. Thanks

**Closed by hariprasadms** 2024-02-04 20:13 UTC
Labels: status: can't reproduce
