### ISSUE TITLE
FlutterLoader.loadEntrypoint id deprecated.  Use FlutterLoader.load instead

### ISSUE THREAD

**Issue by rsstevearend** [FlutterFlow/flutterflow-issues#3250] opened 2024-06-26 21:12 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I cannot build my application for the second day now on the mac for web deployment. 
 
 
 Warning: In index.html:67: Local variable for "serviceWorkerVersion" is deprecated. Use "{{flutter_service_worker_version}}" template token instead.
Warning: In index.html:82: "FlutterLoader.loadEntrypoint" is deprecated. Use "FlutterLoader.load" instead.
Waiting for connection from debug service on Chrome...             28.2s
This app is linked to the debug service: ws://127.0.0.1:54037/rixOlEzj1ds=/ws
Debug service listening on ws://127.0.0.1:54037/rixOlEzj1ds=/ws

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

A Dart VM Service on Chrome is available at: http://127.0.0.1:54037/rixOlEzj1ds=
Rejecting promise with error: TypeError: Cannot set properties of undefined (setting 'nativeCommunication')

### Expected Behavior

For the build to not crash

### Steps to Reproduce

1) Build for web -- Chrome.
2) error occurs screen is blank.  

<script>
    window.addEventListener('load', function (ev) {
      // Download main.dart.js
      _flutter.loader.loadEntrypoint({
        entrypointUrl: 'main.dart.js',
        serviceWorker: {
          serviceWorkerUrl: 'flutter_service_worker.js?v=',
          serviceWorkerVersion: serviceWorkerVersion,
        },
        onEntrypointLoaded: async function(engineInitializer) {
          // Initialize the Flutter engine
          let appRunner = await engineInitializer.initializeEngine({});
          // Run the app
          await appRunner.runApp();
        }
      });
    });
  </script>
</body>
</html>

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ozcrlw4Z1obgA+Kr2ccAxnSQRHH02bLgelcpBZywgfZzzBLN/fPfQP0lWOcOgTHNbPmKmp14d/vSPiODtVsI7E0iAbr5B1ahQFg6XXkG6MsiTF7uCQ0QnRZtXC0DHyJinhhB7Pfh1dVYm11+IOe+9VintNYzVO2o8Sq/LZO4=

### Visual documentation

<img width="246" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/3091488/aa563c3a-d719-4fec-8763-408c0e7a27a6">

### Environment

```markdown
- FlutterFlow version: v4.1.64
- Platform: Mac
- Browser name and version: Chrome Version 122.0.6261.94 (Official Build) (arm64)
- Operating system and version affected: Sonoma 14.4.1
```

### Additional Information

I cannot build the application for the second day now since I was forced to upgrade to 3.32.2

**Comment by EnviousDetailingMarketing** [comment] 2024-06-26 21:28
I am having the same problem. I've tried numerous things!

**Comment by efenech** [comment] 2024-06-27 02:19
Same issue for me. Windows 11. FlutterFlow v4.1.64+ released June 27, 2024 Flutter version is 3.22.2

**Comment by omnibassa** [comment] 2024-06-27 08:47
We have the same issue:
Warning: In index.html:51: Local variable for "serviceWorkerVersion" is deprecated. Use "{{flutter_service_worker_version}}" template token instead.
Warning: In index.html:66: "FlutterLoader.loadEntrypoint" is deprecated. Use "FlutterLoader.load" instead.

Blank page after build and warning appears.

The whole application is booting as a blank page.

**Comment by ValetCEO** [comment] 2024-06-27 14:21
Same issue here and no response from Flutterflow !

**Comment by rzambroni** [comment] 2024-06-27 20:16
Hey there, it seems like in most cases the issue is related to the usage of this dependency on your custom code: `html_editor_enhanced` It is very likely that this package is not yet compatible with the latest flutter stable version 3.22.2.

**Comment by omnibassa** [comment] 2024-06-28 04:30
I don’t think so, duplicated the project and removing all dependencies did not help.

**Comment by mztmoraes** [comment] 2024-06-28 12:21
Same problem here. 

Since upgrading to flutter 3.22.2, I can no longer publish changes to the project.

**Comment by MaxFF1800** [comment] 2024-06-28 16:28
The issue you're experiencing is due to the custom code import of `html_editor_enhanced`, which depends on `flutter_inappwebview.` To make it work on the web, you need to make some adjustments. Specifically, you need to add a script tag, as described in the installation instructions here: [flutter_inappwebview installation guide](https://pub.dev/packages/flutter_inappwebview#installation). This will work when publishing to web but may cause errors within test mode (you may need to test your application locally) when using this package.

**Comment by EnviousDetailingMarketing** [comment] 2024-06-28 16:36
> The issue you're experiencing is due to the custom code import of `html_editor_enhanced`, which depends on `flutter_inappwebview.` To make it work on the web, you need to make some adjustments. Specifically, you need to add a script tag, as described in the installation instructions here: [flutter_inappwebview installation guide](https://pub.dev/packages/flutter_inappwebview#installation). This will work when publishing to web but may cause errors within test mode (you may need to test your application locally) when using this package.

THANK YOU. 
This solved it (testing locally).

**Comment by omnibassa** [comment] 2024-06-28 18:32
We publish from flutterflow so we have no access to the index.html. So we can’t use the flutterflow local run or cloud testing? Also we must host somewhere else?

**Comment by MaxFF1800** [comment] 2024-06-28 18:35
<img width="1710" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/161855694/aa9a7ded-1f46-48c4-8b07-a15543196f99">

You should be able to add this script within the headers tag for web deployment, and may also work within test mode 
[ScriptTxtFile](https://github.com/user-attachments/files/16034656/Script.WorkAround.txt))

**Comment by omnibassa** [comment] 2024-06-28 20:01
Thanks! And the dependency itself is already included by FlutterFlow? Or do I need to include that separately? If so, how?

**Comment by felipemontero** [comment] 2024-06-28 20:01
same here, testing was fine until 2 hours ago.... I didn’t modified any custom action, I'm guessing they are preforming several bug updates, this is happening since 2 days ago and i'm seeing several flutterflow versions updates

**Comment by MaxFF1800** [comment] 2024-06-28 20:05
Packages in general have their own dependency. The `html_editor_enhanced` package has a dependency of flutter_inappwebview and has imported it themselves. When using the html_editor_enhanced, it will automatically import the second package. However, since the second package has some setup/requirements, you need to make the changes to the header.

**Comment by felipemontero** [comment] 2024-06-28 20:26
I tried the script you provided, even deleted the custom action with external dependencies, but there's no way to launch test mode.
This is the full compilation error:

> 56 packages have newer versions incompatible with dependency constraints.
> Try `flutter pub outdated` for more information.
> Launching lib/main.dart on Web Server in debug mode...
> Waiting for connection from debug service on Web Server...      
> Warning: In index.html:641: Local variable for "serviceWorkerVersion" is deprecated. Use "{{flutter_service_worker_version}}" template token instead.
> Warning: In index.html:656: "FlutterLoader.loadEntrypoint" is deprecated. Use "FlutterLoader.load" instead.
> lib/pages/mobile/event/event_widget.dart:421:76: Error: The method 'toList' isn't defined for the class 'Map<String, dynamic>'.
>  - 'Map' is from 'dart:core'.
> Try correcting the name to the name of an existing method, or defining a method named 'toList'.
>                                                                           .toList()
>                                                                            ^^^^^^
> Waiting for connection from debug service on Web Server...         57.5s
> Failed to compile application.

**Comment by edualvesilva2** [comment] 2024-06-30 21:29
same problem for me, using win 11

**Comment by itsstevenliu** [comment] 2024-07-01 01:15
Same problem, this needs to be fixed.

**Comment by itsstevenliu** [comment] 2024-07-01 01:21
@EnviousDetailingMarketing 

> THANK YOU.
> This solved it (testing locally).


Can you show us how you did it? I copied the code

<head>
    
    <script type="application/javascript" src="/assets/packages/flutter_inappwebview_web/assets/web/web_support.js" defer></script>
    
</head>

Into the FF's web publishing > custom header but it is still experiencing the same error.

**Comment by jerperdue** [comment] 2024-07-01 15:16
@MaxFF1800 I'm running into the same issue. We need a better solution than testing locally--We need Test Mode to work. Test Mode was working until the Flutter upgrade, now it's not. Can you help this issue get more attention from Flutterflow engineering team?

**Comment by felipemontero** [comment] 2024-07-01 16:17
For what i can see this happened when FF was updated to 4.1.64, then I think several bugs appear and they decided to roll back to 4.1.63, then updated to 4.1.63+ (or something like that).
Personally I took the loss and reverted to a snapshot of 4.1.63. Save the project and keep working from there.

**Comment by omnibassa** [comment] 2024-07-02 17:50
> <img alt="image" width="1710" src="https://private-user-images.githubusercontent.com/161855694/344282052-aa9a7ded-1f46-48c4-8b07-a15543196f99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5NDI5MTMsIm5iZiI6MTcxOTk0MjYxMywicGF0aCI6Ii8xNjE4NTU2OTQvMzQ0MjgyMDUyLWFhOWE3ZGVkLTFmNDYtNDhjNC04YjA3LWExNTU0MzE5NmY5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMlQxNzUwMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MWE3ZDAyNjA3ZDVlZGFiNjk0ODAxYzA2YWNlMzAyNmMyZDAyYmUxM2UzMzY3ZWI5MjUzZTdlMWZiZmU0YjFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uUVPtem8d3wFyWlsHUhyetUKhnwJGqr-8KHPQsMblVI">
> You should be able to add this script within the headers tag for web deployment, and may also work within test mode [ScriptTxtFile](https://github.com/user-attachments/files/16034656/Script.WorkAround.txt))

The script included here worked

**Comment by jerperdue** [comment] 2024-07-03 03:27
I see. The script worked for me too. Test mode is working now. thank you

**Comment by SebyOnGitHub** [comment] 2024-07-09 18:59
When I create a new empty project, enable web and try to compile for web, I still get the warning. Is it still not fixed?

**Comment by efenech** [comment] 2024-07-10 22:29
Well, after patiently waiting for this issue to be resolved and with a new update, I'm very disappointed to see this issue is still impacting the desktop app. I want to use local run, and I should be able to build web applications without this issue disrupting my development. I'm a pro customer and I'm about a hairsbreadth away of pulling the pin on FlutterFlow, given the current priorities of the development team, which don't seem to be on fixing issues the latests Flutter update has created. For the sake of proof, here are the error messages I get:
![Screenshot 2024-07-11 081032](https://github.com/FlutterFlow/flutterflow-issues/assets/88217100/ed318003-3f42-4186-958a-51c2d110cbc0)
![Screenshot 2024-07-11 081134](https://github.com/FlutterFlow/flutterflow-issues/assets/88217100/6ffd909a-d286-4d53-8b8e-5e5a1c0eb85e)
For what it's worth, I'm currently scaffolding another framework in readiness to switch out my development. It's a shame, as I was making progress until Flutter version 3.22.2 and felt confident in its stability as a development platform. That confidence has been shaken. And, just to be clear, there is nothing in my custom functions that remotely touches the fundamental issue that this bug is reporting, so please don't skirt around the issue by suggesting otherwise. Feel free to check my project @rzambroni.

**Comment by rzambroni** [comment] 2024-07-11 13:33
Hi @efenech,

It looks like other users in the thread resolved their issues by fixing a custom code dependency. Have you checked your custom code? The usual suspect was the html_editor_enhanced package.

I understand your frustration, but if this is the case for you as well, it's not something a FlutterFlow update can fix. Please let me know if any of the solutions listed in the thread worked for you. If not, provide a bug report code so we can investigate further.

Thanks!

**Comment by efenech** [comment] 2024-07-11 21:41
> Hi @efenech,
> 
> It looks like other users in the thread resolved their issues by fixing a custom code dependency. Have you checked your custom code? The usual suspect was the html_editor_enhanced package.
> 
> I understand your frustration, but if this is the case for you as well, it's not something a FlutterFlow update can fix. Please let me know if any of the solutions listed in the thread worked for you. If not, provide a bug report code so we can investigate further.
> 
> Thanks!

Hi @rzambroni . Thanks for the reply. As I've stated, I've checked my custom code, which at this stage is lightweight and doesn't involve the use of any dependencies, particularly the html_editor_enahanced package. 

However, given the error being thrown, I opened the project in Android and on the index.html there's a script section that clearly uses what I believe is causing the error. This script is FF not mine:

 <script>
    window.addEventListener('load', function (ev) {
      // Download main.dart.js
      _flutter.loader.loadEntrypoint({
        entrypointUrl: 'main.dart.js',
        serviceWorker: {
          serviceWorkerUrl: 'flutter_service_worker.js?v=',
          serviceWorkerVersion: serviceWorkerVersion,
        },
        onEntrypointLoaded: async function(engineInitializer) {
          // Initialize the Flutter engine
          let appRunner = await engineInitializer.initializeEngine({useColorEmoji: true,});
          // Run the app
          await appRunner.runApp();
        }
      });
    });
  </script>

If you look at the console log shows the script is calling the depreciated variable:

<img width="602" alt="image" src="https://github.com/user-attachments/assets/b1ae4d78-b14a-4c71-9459-574644666980">

**Comment by efenech** [comment] 2024-07-11 21:59
Following up on my last post and diving deeper into the project code in Android, which is possibly linked to your previous comment about html_editor_enhanced, I find that even though I deleted the custom widget and related custom actions for the quill editor a few weeks ago (which likely relates to html_editor_enhanced), they still exist in my project. How? How is it that after deleting them in FlutterFlow (desktop), those actions and custom widgets persist? 

Here's the project tree and one of the files (snippet):

<img width="425" alt="image" src="https://github.com/user-attachments/assets/bd2c79ab-905f-4511-8a66-a2a9bac94e7f">
<img width="588" alt="image" src="https://github.com/user-attachments/assets/4e922ac4-f82f-46bb-b944-4e2e56439718">

Thoughts?

**Comment by SebyOnGitHub** [comment] 2024-07-12 06:20
@rzambroni 
Hi, I just wanted to tell you, created a bug report for a different breaking bug. On the other bug report, the first three steps are to reproduce this bug for this problem here. (on a new project) Without using custom code or anything like this. Plase take a look at the steps to reproduce and to the new project itself. (The last comment said completed, but the warnings are still not solved)

https://github.com/FlutterFlow/flutterflow-issues/issues/3352

**Comment by vagnerac** [comment] 2024-07-19 19:12
Same issue here.
My project does not have any custom dependency and also does not have flutter_inappwebview in its pubspec.yaml file.
I added the script in the header, but no success. I understand in my case, like others posted here, the problem is not directly related to this extension.

**Comment by rzambroni** [comment] 2024-07-19 19:23
Given the nature of the problem, it seems to be specific to your project and has proven difficult to replicate on our end. I recommend reaching out to support for a more in-depth analysis of the project. Alternatively, if you can consistently replicate this issue on a blank project, please let us know the steps so we can investigate further.

Thank you.

**Comment by efenech** [comment] 2024-07-19 22:41
> Given the nature of the problem, it seems to be specific to your project and has proven difficult to replicate on our end. I recommend reaching out to support for a more in-depth analysis of the project. Alternatively, if you can consistently replicate this issue on a blank project, please let us know the steps so we can investigate further.
> 
> Thank you.

@rzambroni to which user's post are you replying to?  Mine? @vagnerac @SebyOnGitHub ? It seems we're all getting this issue, and the best response we're getting is, "It seems to be specific to your project..." and to go and speak to "support". All good and well, but not good enough. It may not be in the grand scheme of things anything of importance to the team at FF, but for what it's worth, my impressions are that the dev team has no interest in web apps, has no interest in making sure that the local development desktop IDE is fit for purpose and is only interested in new bells and whistles rather than taking care of bugs introduced. I said in an earlier post that a response like this would result in me ditching FF for my project. Well, consider FF ditched.

**Comment by rzambroni** [comment] 2024-07-19 23:56
@efenech, i understand your frustration and we are the first ones interested in solving the issue. However, at this point, if none of the above fixes worked we are facing a similar, but distinct problem. We don't have access to your project/bug-report code so we are a bit blind trying to get this replicated, and also because of the nature of the problem, even with access to your project, we wouldn't be able to test it because we would not have permissions to build it. That's why I'm recommending anyone with a similar issue for whom the workarounds didn't work to reach out to support. While we can continue to troubleshoot here, I believe contacting support is the best course of action to achieve a resolution.<br><br>Thanks.

**Comment by Alezanello** [comment] 2024-07-22 12:10
Hello Everyone!

The main issue of this thread has been resolved. The warning "FlutterLoader.loadEntrypoint" is deprecated. Use "FlutterLoader.load" instead." does not affect your application's functionality at the moment.

Upon reviewing the logs, it appears that everyone has different issues within their projects that prevent them from running correctly. For example:

![image](https://github.com/user-attachments/assets/ac9b5d28-4e5f-47d0-a079-a05e0a332f27)

@efenech Your project error is not the FlutterLoader instead you have an issue with Supabase

I need everyone who still has issues in this thread to please share your Bug Report Code from your project. As mentioned by @rzambroni , it seems to be very project-specific, and we need to check the internal details to provide accurate assistance.

To generate the Bug Report Code, right-click on any widget inside your Widget Tree in FlutterFlow and select "Get Bug Report Code".

![image](https://github.com/user-attachments/assets/a7109270-9edd-4eab-ac4b-c7191e7c9985)



Best regards,
Azanello

**Comment by vagnerac** [comment] 2024-07-24 23:57
@Alezanello , I have created a brand new project and just ran it from local run after enabled Web in the setup:
![image](https://github.com/user-attachments/assets/974b6401-8d50-46ad-be99-44fcaf83ba42)

When click to Local Run at first time, below message is shown (same from the subject of this issue report):
![image](https://github.com/user-attachments/assets/e5716aca-061c-47c7-9cea-d77040ecf333)

Project opens in the browser:
![image](https://github.com/user-attachments/assets/693f23cc-388f-413e-9116-8c5a7ad0a15d)

After a small change in the project, just a button added, when try to do a Hot Reload, below error messages are shown:
![image](https://github.com/user-attachments/assets/11fe7e57-2f59-493c-a0c7-9ff5c24b1de3)

Follow Bug Report Code: ITFfz/Hqx89grulc7ZSJdsZapCAXNW0cTIMziNZ+exUbfaL1Buw2Zc+kfhBDTemhaVNcMWGJoFky092LiuH2UPVePS+rQYA9+rhhVTvke2ilV5PWDqigenB8GeFUGB2PyrbQuxR4Vc9tLyEWw2GMNe+vbHfDIuu/Zwh9f6PHaOI=

Just to add, I see in the previous messages there is no solution applied in FF. There is just a workaround and no solution proposed by the FF team. Alternative solution not always work for everyone and make the system not reliable, because it is necessary a workaround to make things work.

**Comment by vagnerac** [comment] 2024-07-29 17:33
Hi @Alezanello.

Please, is there any update on this subject?
All information requested was provided.

**Comment by vagnerac** [comment] 2024-08-05 22:18
@Alezanello, @rzambroni, @FlutterFlowEng is there any update on this???

**Comment by rzambroni** [comment] 2024-08-06 00:35
Hey everyone,

The issue described in the latest comments is similar but not exactly the same as the original issue on this ticket.

@vagnerac reported a separate issue, which can be found [here](https://github.com/FlutterFlow/flutterflow-issues/issues/3559). This issue has already been confirmed and sent to the ENG team for resolution.

Please refer to that other ticket as I will be closing this one for issue hygiene purposes.

**Closed as completed** 2024-08-06 00:35 UTC
Labels: waiting for user response
