### ISSUE TITLE
Flutterflow project suddenly disappeared from the dashboard

### ISSUE THREAD

**Issue by Shozoseto** [FlutterFlow/flutterflow-issues#3040] opened 2024-06-01 19:11 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Missing project. I had been working for several months and my project have suddenly disappeared unfortunately. My project name is "Worthy Words". My acccount ID is "shozo_setoguchi@yahoo.co.jp".

It just says the project link doesn't exist. 
![1](https://github.com/FlutterFlow/flutterflow-issues/assets/171447167/478ce116-3c44-42c5-9ce5-9d1aa06a6c27)

### Expected Behavior

Find and fully recover my project

### Steps to Reproduce

No steps to reproduce for this issue

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Cannot get the code as the entire project missed

### Context

Find and fully recover my project

### Visual documentation

No steps to reproduce for this issue

### Environment

```markdown
- FlutterFlow version: Latest as of June 1 2024 (Sorry I couldn't find how to confirm the exact version name)
- Platform:Web
- Browser name and version:Edge 124.0.2478.105
- Operating system and version affected:Windows 11, version 23H2
```

### General

- [X] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by msusviela** [comment] 2024-06-03 12:28
Hey @Shozoseto, Thanks for your report, So sorry you are experiencing this issue. I was not able to reproduce this on a blank project, but it is replicable on yours. That's why I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. Thanks so much!

**Closed** 2024-06-06 15:58 UTC
Labels: closed: support request
