### ISSUE TITLE
Local App State returning empty even when initial values are set

### ISSUE THREAD

**Issue by KlausGrosser** [FlutterFlow/flutterflow-issues#1056] opened 2023-06-27 22:29 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I set initial values for the variables in my Local App State and run the app (whether in test mode or run mode) everything returns empty making the app unusable until I make an action to manually update the state variables inside the running app (whats the pint of setting initial values from FF UI?)
In the example from the attached bug code, I want to display a text that comes from a variable inside a local app state variable, when I run the app, an error is thrown: Bad state: no element, even though I set the initial values so they were not empty.

### Expected Behavior

local state variables that have an initial value set from FF UI should not be empty when using them inside the app.

### Steps to Reproduce

1. Create a local state variable
2. Add an initial value to it (so its not empty)
3. Use this variable in the app

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXkvHlvIZNrsRE7arbKPlKhSgwFjsaU40V0tcaaAE0GJ+tEYkqO+r+VGFeTf2gY2NYAUybhj0dp/DHvvP9JvpeAzOCQoNozYdQWzryWnm6VKqDO6uVOHZCI8JhChG8yqS7rgl+XdZeWGwgw1r/cq3qNleeY8aSfxBlZ7vfcPo=

### Context

This basically makes my local state variables unusable.

### Visual documentation

<img width="688" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/90258185/acbca209-07b5-4403-aceb-54f34449784f">
<img width="806" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/90258185/75a959d2-aea4-41dd-ab1c-3c006e04b6bc">
<img width="628" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/90258185/ea1f2971-ab49-407d-86de-9f5ca3384acd">

### Environment

```markdown
FlutterFlow version: v3.1 (released Feb 27, 2023)
Platform (e.g. Web, MacOS Desktop): Web
Browser name and version (web): Version 114.0.5735.133 (Official Build) (arm64)
Operating system and version (desktop): macOS Ventura 13.4 (22F66)
```

**Comment by DarthBrento** [comment] 2023-06-28 10:14
Probably related to #1039  and #1050

**Comment by hariprasadms** [comment] 2023-06-28 14:18
Hi @KlausGrosser - Thanks for submitting the issue. I have tested above steps related to app state ( In general creating a app state with a value and access the same value on UI in run time). I can confirm that, it is working as expected. 

Above mentioned _steps to reproduce_ is not clear. For example, _step 1 -  create a local state variable._ When you say local state variable, is it app state or local page state?. Also a blank page with issue steps setup is not provided. The bug report code you have provided above is to the actual project. There are many pages, and I can't seem to find the one where the problem is. 

We can look into the issue once issue has been updated with the above additional information. Thanks

**Comment by KlausGrosser** [comment] 2023-06-28 20:57
Hello @hariprasadms thank you for your response. I had to delete the text widget that was causing this since I can't stop development. As @DarthBrento previously said, Im facing the same issues as the issues he mentioned.
Here is a new bug code report so you can take a look into my project:
CgxSb3dfMXk4aDBiaGcSuQEKDkltYWdlXzQ0c2FzMDEyGAciogEyZgoiaHR0cHM6Ly9waWNzdW0ucGhvdG9zL3NlZWQvMTU3LzYwMBABGAMiFgoJCQAAAAAAAFlAEgkJAAAAAAAAWUAqJAkAAAAAAABZQBEAAAAAAABZQBkAAAAAAABZQCEAAAAAAABZQJoBNAoCBgEqLggGEhFMaXN0Vmlld19wY3NseXR3OUICKgBKE5IBEAoOCgVpbWFnZRIFY2xtYmz6AwBiABKFAQoNVGV4dF83MDhqMTVwcxgCInASHwoLSGVsbG8gV29ybGQRAAAAAAAAMEA6AhAIQAioAQBaCQkAAAAAAAAkQHoCGAGaAToKAgIBKjQIBhIRTGlzdFZpZXdfcGNzbHl0dzlCAioAShmSARYKFAoLaW5zdHJ1Y3Rpb24SBTBnNmNk+gMAYgAYAyIHGgIqAPoDAGIA

**Comment by hariprasadms** [comment] 2023-06-28 21:07
Hi @KlausGrosser - Looks like above code is not correct one. It should be shorter like earlier code. Aslo, please update issue as below points. 

_Above mentioned steps to reproduce is not clear. For example, step 1 - create a local state variable. When you say local state variable, is it app state or local page state?. Also a blank page with issue steps setup is not provided. The bug report code you have provided above is to the actual project. There are many pages, and I can't seem to find the one where the problem is._

**Comment by SameerShahzad99** [comment] 2023-08-16 18:48
Closing this issue as the user have not responded with the complete details

**Closed** 2023-08-16 18:48 UTC
Labels: closed: other
