### ISSUE TITLE
Json Paths from API not fetching if the object name is numbered

### ISSUE THREAD

**Issue by Dev-Muhammad-Junaid** [FlutterFlow/flutterflow-issues#1302] opened 2023-08-18 10:20 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

This Community Post provides clear description on the issue

[](https://community.flutterflow.io/database-and-apis/post/json-path-do-not-populate-NAJj7Hil820XMYx?highlight=mu9zHnYyD0KtUGJ)a 

### Expected Behavior

I expected the JSON objects to be fetched just like on JSONPATH.com
Image provided 
<img width="1512" alt="Screenshot 2023-08-18 at 3 09 13 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/65047962/814ce4bc-bd72-49e3-81bb-a6e18557ed53">

### Steps to Reproduce

1. http://demo.splynx.com/api/2.0/admin/finance/refill-cards-series/202301
2. Set Header  Authorization: Basic MGM3MDFlYTMwM2Y3NGJlZmU4MDQzOWE0NzM5NDljZTM6MDZlNmE3ZDJkNGZmN2YzMDUwYjM4YjVlZWQ0Mzg1NDA=
3. Response and Test
4. Check Recommendation Tab [Its empty]

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gz/Hqx89NxMtE7ZD+cO9WpDs7NmZ/R700sNobbxAjIoDoPJkUaeDRcRFuZ/3kTVZfKEWIjT8K0a2KkuLIUO0DORStfqpG+ah2djrveF6/aoSXO6iKT0d5Fptjfna106aFkQpQD/tZL2AO2EyEf+nLShDbHZP7Zwh9f6PHaOI=

### Context

Set JSON path 

### Visual documentation

<img width="1512" alt="Screenshot 2023-08-18 at 3 15 57 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/65047962/f48f3ce1-4230-4aae-b0f1-f7221974589f">
<img width="1512" alt="Screenshot 2023-08-18 at 3 16 01 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/65047962/0f995fc0-cef4-4b1e-ba1a-bc7d86e5dce2">

### Additional Info

That's it

### Environment

```markdown
- FlutterFlow version: v3.1 released August 17, 2023
- Flutter version : 3.10.4
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: None
```

**Comment by YassinELY** [comment] 2023-08-26 12:12
Please do not close this, it is only "stale" because the team has not adressed the issue yet.

**Comment by kevintonb** [comment] 2023-09-01 05:46
Hey @YassinELY , thank you for taking the time to report this issue. I have tried to troubleshoot the issue with the API call information that you have provided but the response is not authorised and I'm unable to test it from my end. But I understand your concern and I have tested with a different endpoint, can you please try using the recommended json path suggestions that Flutterflow provides from the API call test response and let me know if you're facing any issue. You should be able to access any node element on the array once you have a list object from the json path expression. This is not a bug in the platform itself but an implementation issue. However I'm keeping this issue open to make sure there aren't any bugs. Kindly include a blank project with the bug / api call implementation set up so that we can take a look.

**Comment by Dev-Muhammad-Junaid** [comment] 2023-09-01 07:41
Hey @kevintonb, thanks for taking the look,  the issue wasn't that the Recommended path was not working at all. Its related to the JSON being fetched in response where the JSON Path names are numbered, which wasn't showing in recommended. I have tested it myself and provided relevant screenshots since the issue was found on another project on the community, not mine. And also provided the API headers for authorization for you to test.

**Comment by YassinELY** [comment] 2023-09-01 12:01
> Hey @YassinELY , thank you for taking the time to report this issue. I have tried to troubleshoot the issue with the API call information that you have provided but the response is not authorised and I'm unable to test it from my end. But I understand your concern and I have tested with a different endpoint, can you please try using the recommended json path suggestions that Flutterflow provides from the API call test response and let me know if you're facing any issue. You should be able to access any node element on the array once you have a list object from the json path expression. This is not a bug in the platform itself but an implementation issue. However I'm keeping this issue open to make sure there aren't any bugs. Kindly include a blank project with the bug / api call implementation set up so that we can take a look.

Hi Kevin,
How can i provide my project to you?

For me it is just weird that it worked for a long time and then 1 dag all of the sudden i have 40 error messages without changing a thing.

I would be very happy to share my project if you tell me how i can do this :)

**Comment by YassinELY** [comment] 2023-09-03 13:44
Any news? :)

**Comment by kiranetph** [comment] 2023-09-08 11:42
This should be considered as a bug. It was always working until changes in the update of August 10. 
See --> 
https://github.com/FlutterFlow/flutterflow-issues/issues/1296

**Comment by Dev-Muhammad-Junaid** [comment] 2023-09-08 12:16
Do we have an update on this? @kevintonb @wenkaifan0720

**Comment by aemelyanovff** [comment] 2023-09-19 12:44
@Dev-Muhammad-Junaid Try `$[1]` instead of `$.1`. As far as I understand, the name shorthand cannot start with a digit, see the [spec](https://www.ietf.org/archive/id/draft-ietf-jsonpath-base-20.html#section-2.5.1.1).

**Comment by Dev-Muhammad-Junaid** [comment] 2023-09-20 11:13
Thanks. I can make it work with this. However, we are able to start it with digits as we are treating them as Strings, not digits.
I have validated this before through different jsons. It was working in FF beforehand. So checking community members' responses this got changed it seems. As 
<img width="1196" alt="Screenshot 2023-09-20 at 3 46 49 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/65047962/7e7e2150-c7ab-4c77-9c72-b77d97b3a139">
<img width="1158" alt="Screenshot 2023-09-20 at 4 11 03 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/65047962/15929d3f-035c-4953-9e22-5773d0c80891">
<img width="1258" alt="Screenshot 2023-09-20 at 4 12 20 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/65047962/605a7347-f0ec-4e51-b914-7ec8da311e2f">
you can see I have valid JSON and its selectable both ways through $.4 and $[4]
in the attached files

**Comment by aemelyanovff** [comment] 2023-09-20 12:09
It did work before we upgraded our [json path parser](https://pub.dev/packages/json_path) to the latest version. But I believe its current behavior (not allowing numeric names in the shorthand notation) is correct according to the specification linked above. Please use `$[1]` or `$["1"]` instead `$.1`.

I can't speak for jsonpath.com.

Closing the issue.

**Closed by aemelyanovff** 2023-09-20 12:09 UTC
Labels: type: bug, status: confirmed

**Comment by Dev-Muhammad-Junaid** [comment] 2023-09-20 13:30
Yup, that's the case. Got it ✌️
