### ISSUE TITLE
Not able to create app state variable for type Document Reference

### ISSUE THREAD

**Issue by vikrant-p-nimap** [FlutterFlow/flutterflow-issues#3243] opened 2024-06-26 11:44 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Not able to create app state variable

### Expected Behavior

Able to create app state variable

### Steps to Reproduce

1. Go to App Values section 
2. Choose App State
3. Click on Add App State Variable
4. Inset field name, Select Document Reference, Select Reference Type
5. Create button is disabled

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

App state

### Visual documentation

<img width="1728" alt="Screenshot 2024-06-26 at 5 11 48 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/159254045/9e051b5f-2b71-4da2-a05a-e771dabef5f7">

### Environment

```markdown
- FlutterFlow version: 4.1.64
- Platform: WEb
- Browser name and version: I was using mac flutter flow application
- Operating system and version affected: Mac
```

**Comment by msusviela** [comment] 2024-06-26 12:18
I was able to reproduce the issue, I will send it to the ENG team so they can work on this!<br><br>I'm closing this issue because it's a duplicate of this issue in our internal backlog.

**Closed as not planned** 2024-06-26 12:19 UTC
Labels: closed: duplicate
