### ISSUE TITLE
Incorrect Flexible Expansion setting does not show up as error until Test/Run

### ISSUE THREAD

**Issue by jesperst67** [FlutterFlow/flutterflow-issues#905] opened 2023-05-19 23:52 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When setting the Expansion to "Flexible" in an incorrect way, Flutterflow does not show it as an error. However in Test/Run mode a white screen shows up, console showing errors correlated with column/row height/width issues.
![issue_photo01](https://github.com/FlutterFlow/flutterflow-issues/assets/31376860/5b1c8213-733e-4d13-8c64-a1316033f250)
![issue_photo02](https://github.com/FlutterFlow/flutterflow-issues/assets/31376860/b2fafa17-c22c-4179-935d-f3741cec3dd7)

### Expected Behavior

Flutterflow should show it as an error before the user starts the Test/Run mode , as currently it is difficult to identify what is causing the white screen while in the editor there are no errors showing up

### Steps to Reproduce

1. Create a Row
2. Use the Flexible setting incorrectly that should produce an error message
3. See that there is no error message in the editor
4. Run/Test the app and see the white screen (and errors in Console)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ojcrlvJROsdtC0Kr2a8F4hSQ4Jml7bYIvjspOGDwbfaKvPIlzaePRYktuTtfgSlZpKEWL+XEfwa31voSWK8cCGxCZQYRMypFQeAzwUme/aoSrEcy0PkQlBZ5UN2HH0MO03SYmNfhpZXgm1GWqety+aHPrH5v7Zwh9f6PHaOI=

### Context

I spent a few hours trying to figure out what went wrong, as the app was working in the morning and suddenly started showing a blank white screen in Run/Test mode. I tought there might be Firebase issues so I disabled Authentication and it didin;t help. I ended up copying the Console error to chatgpt and it pointed me to the right direction that this is a design related issue. After a few hours I figured I accidantely have set a row to Flexible instead of Default. When changing it to default, the App worked again. Even though Flexible setting did not show up as an error in the Editor and Flutterflow lets the users use this incorrect setting.

I try to save others from digging the issue of a white screen when it is really just an incorrect widget deisplay setting.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/31376860/30526d73-fe91-43e0-860e-8351e3177503

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: All
- Browser name and version: Chrome 113.0.5672.127
- Operating system and version affected: not related (but Windows 11 Home)
```

**Comment by hariprasadms** [comment] 2023-05-21 21:02
Hi @jesperst67 - Thanks for submitting the issue. This is not a bug. The issue you are observing is only visible in build (debug or run) mode and not in editor. 

1) The errors your see in FluterFlow editor while building UI, those are configurations errors. It will be displayed, if there are issues in widgets and data configurations.

2) The errors like blank page (mostly related to data display), errors ( red colour ) during debug and run mode, those are run time errors. To see run time errors, project code should be compiled and built. 

3) Layout errors, these errors mostly related to issues around widgets order during UI design. These errors display only during code compiling time. This can be fixed by adjusting hierarchy of your interface/ widgets.

This explanation, I think, can be useful. Thanks

**Comment by agreaves** [comment] 2023-05-21 22:14
Hi @jesperst67, thank you so much for the bug report! As Hari did, I also though this was initially a configuration issue, however after debugging your application I see that you are correct and that this is indeed a bug in the renderer.

As it turns out, Flexible issues do not cause layout problems in Release mode, so your mobile application, web mode, Run mode, etc. would not experience layout issues (similar to the UI Builder). However, it throws an assertion in Test mode which is what you saw.

We're adding a few measures to help prevent this from occurring, including adding a project error when we detect such a misconfiguration and also preventing you from making it Flexible in the first place if it would cause a layout issue. Thank you again very much for the report! This should be fixed upon our next deploy 🙂

**Closed by agreaves** 2023-05-21 22:14 UTC
Labels: closed: not a bug

**Comment by jesperst67** [comment] 2023-05-21 23:00
Hi,

No worries, always happy to help , I'm glad that i could contribute a
little. FF is a great platform, probably the best on the market, Bubble
guys should get their sh*t together 😅

please never abandon code export, that's the main reason you are winning 😊

Keep up the good stuff!
Mark
