### ISSUE TITLE
Any change made isn't being saved.

### ISSUE THREAD

**Issue by stealthyloon** [FlutterFlow/flutterflow-issues#623] opened 2023-03-17 01:52 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I try to make changes to any of my apps and save the changes. Then when I refresh the page all of the changes are gone.. Also this happens in Google Chrome and Windows Edge. It also happens in every app I have.

### Expected Behavior

When I make a change and save them I expect them to be there when I refresh the page.

### Steps To Reproduce

1. Make a change.
2. Save the page
3. Refresh the browser or open a new browser.
4. Go back to the page and you will see the data has reverted back.

### Bug Report Code

IT4WlMrqx89Nobhe0KrUY8JFmjs5Jjsna7hEm8NxSQ0jNbauO5wPX/z4UBJoTbyndgl5fGD9kTsfwNrLm9z1MOwnOTCVf6I5/8xpWjzxeF25eLqwCZeCT39uGshmC2KF5pmJhCN4GMdiSV4a6kOANtiQfAPdQLq3O0UnBP/+LpDXmAfuQ0SLb3kNh1JWeC/v

### Context

I can't move forward with my work for my clients at all.. Please fix asap.. I'm trying to make an app for one of my clients and have a deadline date of May 9th, 2023..

### Environment

```markdown
- FlutterFlow version: v3.1 - Flutter 3.7.3
- Platform: Windows 11
- Browser name and version: Google Chrome Version 111.0.5563.65 (Official Build) (64-bit)
- Operating system and version affected: Windows 11 64 Bit
```

**Comment by agreaves** [comment] 2023-03-17 02:21
Hi @stealthyloon, thanks for the report. I'm not able to see any errors or timeouts in the logs, is there any chance you could add a screen recording (especially with the developer console open if possible, Cmd + Option + J). Thanks and apologies for the inconvenience.

**Comment by stealthyloon** [comment] 2023-03-17 23:09
[steps to show that i changed data saved and refreshed and it reverted back.zip](https://github.com/FlutterFlow/flutterflow-issues/files/11006912/steps.to.show.that.i.changed.data.saved.and.refreshed.and.it.reverted.back.zip)

I'll do this again with the console open.

**Comment by stealthyloon** [comment] 2023-03-17 23:11
[steps with console open.zip](https://github.com/FlutterFlow/flutterflow-issues/files/11006917/steps.with.console.open.zip)


Steps to show it isn't saving the data. With the console open. @agreaves

**Comment by agreaves** [comment] 2023-03-17 23:43
Hi @stealthyloon, unfortunately we don't download and load zip files for security reasons. Is there any chance you could upload to Google Drive / Loom / some other web-based equivalent? Thanks, and sorry about that.

**Comment by stealthyloon** [comment] 2023-03-18 00:04
I can upload it to google drive. How would I get it to you? @agreaves

**Comment by agreaves** [comment] 2023-03-18 00:47
If you make it a sharable link you can just post it here (like you did with the zip files). Otherwise, if we want to get creative you could create an empty project with a single Text widget set to the link and then send me the bug report code 🙂

**Comment by stealthyloon** [comment] 2023-03-18 01:09
@agreaves 

https://drive.google.com/drive/folders/16Xu6h08Z36iTX2RnuHEvVu1_4NgMq0Y_?usp=sharing

**Comment by agreaves** [comment] 2023-03-18 03:59
Sorry for the back and forth here, the issue is that these are still `.zip` files, which as a general policy is not safe to download and open on our computers. Hence why I was asking if you could upload the video directly onto Google Drive (or use an alternative like Loom) so that it may be viewed there directly without needing to download a zip. If there are multiple files you can also upload those files to that same folder you shared.

Apologies for the confusion, I'm sure the back and forth must be frustrating.

**Comment by stealthyloon** [comment] 2023-03-20 17:45
https://user-images.githubusercontent.com/18235388/226423662-d2f3c84a-3ae3-4e17-b1eb-2bf42422113b.mp4

@agreaves

**Comment by agreaves** [comment] 2023-03-20 22:47
Hi @stealthyloon, thanks so much for the info! I was able to determine the issue and it will be fixed and deployed later today. This will also fix #624. Sorry for the inconvenience!

**Closed by agreaves** 2023-03-20 22:47 UTC
Labels: status: needs triage, status: needs information

**Comment by stealthyloon** [comment] 2023-03-20 23:26
@agreaves thank you!!

**Comment by Webberboy** [comment] 2023-06-09 17:50
Hello i am also having this issue 
it saying error saving this project
I have done a lot of stuffs on the app before I noticed it didn't save them
I am building my first app 
pls help

**Comment by affanminhas** [comment] 2023-09-02 14:25
> Hello i am also having this issue it saying error saving this project I have done a lot of stuffs on the app before I noticed it didn't save them I am building my first app pls help

A temporary solution is to duplicate your project and then run it. It will save the project then.

**Comment by smn-snkl** [comment] 2023-09-26 08:09
@agreaves is this fixed already because I think it still happens. I mentioned [this](https://github.com/FlutterFlow/flutterflow-issues/issues/1303#issuecomment-1727563969) last week and my team had more problems yesterday of entire API calls that were created yesterday disappearing again today.

**Comment by StoicEnso** [comment] 2023-11-03 17:35
the same things is happening to me please help

**Comment by agreaves** [comment] 2023-11-03 17:45
@StoicEnso can you describe what you're experiencing in detail please? Also please include a Bug Report Code if possible, as this helps a ton.

**Comment by StoicEnso** [comment] 2023-11-04 18:14
Hey @agreaves, here is a loom video showing the issue. I can make changes but get an error that the project does not save. Has been like this for days now. Any help will be greatly appreciated. Things I have tried, incognito, rolling back versions, saving new versions, editing other pages, nothing saves. 

https://www.loom.com/share/d62ffc0df957411eab5f9e0d0823c218?sid=c8d9712e-0347-4058-8e26-4f645a21df2b

> @StoicEnso can you describe what you're experiencing in detail, please? Also please include a Bug Report Code if possible, as this helps a ton.

**Comment by agreaves** [comment] 2023-11-05 16:28
Hi @StoicEnso, this is really strange. I'm not able to find any reason why this would be the case. Does saving new versions work even when editing the project doesn't?

Also, this is highly unlikely to be the issue, but are your local time settings (on your local device) unusual in any way?

Lastly, please try logging out and then logging back in after refreshing to see if that helps.

**Comment by TheBigOx** [comment] 2024-02-07 14:29
This has also happened to me, with writing a custom action. It reverted to a previous version and I lost all my work.
