### ISSUE TITLE
Execute Callback conditional action not set

### ISSUE THREAD

**Issue by Jakesf1** [FlutterFlow/flutterflow-issues#2303] opened 2024-02-06 08:50 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After you add a callback action in a component and add a conditional check with the newly added parameters for callbacks there are no errors as soon as you navigate to another page within the project the Issue Tracker displays an error of 'conditional execution for action is improperly set'. To solve this you can add an action in the condition, set for example an app state variable. Remove the action and all the issues/errors will go away.

### Expected Behavior

No errors should be displayed.

### Steps to Reproduce

1. Create a component
2. Add a callback action with a parameter in component parameters.
3. Add a condition based on the callback action parameter.
4. add an action to set a variable based on the condition being true.
5. Create a new page or add a widget to the current page.
6. Issue tracker will display an issue as explained above

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfz/Hqx89goctH176JdMdohmQ4KW0cTL4zlO1HcxAYGO/yPbJ/OfT7YVVBZ/2jd0NhHFCJkXM1+fT0iYSfUvkqOU+rR7o7/rhyexXzTXq8R6mYPKmdP3FDHd1YJh2cyraZoCVdPvtqcVJm6jm6OOmQYDHfCZ+/Zwh9f6PHaOI=

### Context

Cannot create a test session without steps above

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/7d48223a-f0ef-4490-b91b-e76835925f09/1342b875-19ba-4341-b27c-5b52c870f678?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83ZDQ4MjIzYS1mMGVmLTQ0OTAtYjkxYi1lNzY4MzU5MjVmMDkvMTM0MmI4NzUtMTliYS00MzQxLWIyN2MtNWI1MmM4NzBmNjc4IiwiaWF0IjoxNzA3MjI0ODE2LCJleHAiOjMzMjc3Nzg0ODE2fQ.wUvcYMlfg53AtSckFi-yVENfeArVxDOkerjsFSj53OA "=234x")

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: web
- Browser name and version: Chrome (latest
- Operating system and version affected: NA
```

**Comment by hariprasadms** [comment] 2024-02-06 13:06
Hi @Jakesf1 - Thanks for bringing up the issue. Upon reviewing your project and the reported problem, I noticed that the logic you've set up is a bit unclear. I couldn't find where the action parameter 'value' is being assigned a value to compare with '1'. However, I didn't encounter any errors when I downloaded the code, and it compiled successfully. My suggestion would be to review the logic again and ensure that a default value is assigned to the 'value' parameter before it's compared with '1'. Hopefully, this helps resolve the issue.

**Comment by Jakesf1** [comment] 2024-02-06 13:44
Hi Hari,

Thank you. Still a bit lost as you cannot set a default value for the callback action paramaters (newly introduced feature). In the actual project this might be more clear.

IT4CksmAsM9PvsdA1pPpbcFV9TkUJnIjRYE7isFxaA8dDZPND+x/esnRQFJuZ9OrdglXPmCgmTgdpvCPm9z1C/QEYBaqc6pcws1+cxXxezulMLKzO6maWnZUGshQGWqOyKeFpwhSVe9vLVlg2k6qPNmybATtK4yxDUg3OOaYWa7XrgfuQ0SLb3kNh1JWeC/v

When you add an action with update page state (no need to select a field) in the multi condition else path, you will notice the error in issue tracker disappearing.

Best Regards
Jaco

From: Hari ***@***.***>
Date: Tuesday, 06 February 2024 at 15:07
To: FlutterFlow/flutterflow-issues ***@***.***>
Cc: Jakes ***@***.***>, Mention ***@***.***>
Subject: Re: [FlutterFlow/flutterflow-issues] Execute Callback conditional action not set (Issue #2303)

Hi @Jakesf1<https://github.com/Jakesf1> - Thanks for bringing up the issue. Upon reviewing your project and the reported problem, I noticed that the logic you've set up is a bit unclear. I couldn't find where the action parameter 'value' is being assigned a value to compare with '1'. However, I didn't encounter any errors when I downloaded the code, and it compiled successfully. My suggestion would be to review the logic again and ensure that a default value is assigned to the 'value' parameter before it's compared with '1'. Hopefully, this helps resolve the issue.

**Comment by rzambroni** [comment] 2024-03-28 14:59
Hi @Jakesf1, sorry for the delay in the response. Our team attempted to reproduce this issue in a blank project but we were unable to do so. Are you still experiencing it? if that's the case, could you provide additional evidence to help us troubleshoot? A video or any other visual evidence would be great. 
If the issue no longer persists in your end, let us know so we can close the issue. Thanks.

**Comment by kevinderycke** [comment] 2024-04-04 13:13
Hi, I have the problem too. 
I have a list of ListItem with a Callback.
If I set an action and switch to another page, the Error is shown but if I cut the action and paste again, the error disappearred..

**Comment by rzambroni** [comment] 2024-04-05 02:17
Hey @kevinderycke, thanks for the context, are you able to reproduce this issue on a blank project? if so, it would be really helpful if you could provide the bug report code of the issue so we can better isolate the issue and fix it.  A video of your particular issue could also help a lot. Thanks!

**Comment by nicmohr25** [comment] 2024-04-08 19:09
I also have the same issue in my Project.
Here is the Bug Report code. I also contact the support but nobody is answering.

IT48lcmB34hNodcF+Kr2b8FajjgXH2E7aLszkOxxRUs8J5TUB+x/evz4UBJoTbyndghIIk2gimM10NLIm9z1KvpeByyYR6Jm1Kt5Ww3gYH2tbJCkOpeCX0ZuGshmIFC94aevqxV+ObBZSFoa3TqlfNzLZCnqHb7vClYRAsiYNt/XmAfuQ0SLb3kNh1JWeC/v

**Comment by timeisgolden** [comment] 2024-04-18 17:10
> Hello @rzambroni I also have the same issue in my Project. Here is the Bug Report code. I also contact the support but nobody is answering.
> 
> IT48lcmB34hNodcF+Kr2b8FajjgXH2E7aLszkOxxRUs8J5TUB+x/evz4UBJoTbyndghIIk2gimM10NLIm9z1KvpeByyYR6Jm1Kt5Ww3gYH2tbJCkOpeCX0ZuGshmIFC94aevqxV+ObBZSFoa3TqlfNzLZCnqHb7vClYRAsiYNt/XmAfuQ0SLb3kNh1JWeC/v

Hi, I am also getting the same issue in my project.
Did you resolve the issue?

**Comment by rzambroni** [comment] 2024-04-18 17:12
Hi everyone! this bug was confirmed and moved to the team so they can take a look. We will update the status here once it's fixed.

Thanks for your patience.

**Comment by sbis04** [comment] 2024-05-10 08:23
Seems like this issue is fixed in the latest release. Can anyone please confirm?

**Comment by sbis04** [comment] 2024-05-13 02:49
Closing this issue for now as it seems to be fixed!

**Closed** 2024-05-13 02:49 UTC
Labels: status: confirmed, Bug
