### ISSUE TITLE
Collaboration issue - pages disappearing when users work in parallel

### ISSUE THREAD

**Issue by danileca** [FlutterFlow/flutterflow-issues#129] opened 2022-11-15 13:14 UTC
## Expected behavior (required)
Users collaborating on the same project should be able to work in parallel on different pages and add new pages without affecting the other users' work.

## Current behavior (required)
1. When an Editor creates a new page the page that the Owner is working on disappears. In order to workaround this me (the owner) had to create a new blank page so that the Editor can work on that one.
2. Whilst working in parallel (owner on a page & editor on a different one) all of the sudden the owner's page disappeared. No warning, no error and the Editor wasn't trying to add a new page (as in the first point above).

## To Reproduce (required)
For the first behavior:
1. Create a new project
2. Add some pages
3. Add a user from collaboration settings using their email address, as an editor
4. Ask the user to create a new page

For the second behavior:
5. Whilst the owner is working on a page and the editor working on a different one the owner's page was gone. Couldn't recover from versions this time.

## Context (required)
We had to stop collaborating on the project since there is a risk of losing the work we did. In the first behavior luckily enough time passed between the version saving and the issue, so we were able to recover the deleted page from an older version. But in the second behavior we were working in parallel, so no version was saved with the page that I lost permanently.

## Your environment
* **Bug Report Code:** : N/A
* Version of FlutterFlow used: 3.0
* Platform (e.g. Web, MacOS Desktop): Web (both owner and editor)
* Browser name and version: Owner using Microsoft Edge Version 107.0.1418.35 (Official build) (64-bit); Editor using Safari 13.0.1
* Operating system and version (desktop or mobile): Owner using Win11 Enterprise 22H2; Editor using MacOS Ventura

**Comment by hariprasadms** [comment] 2023-02-07 16:52
Hi @danileca - Thanks for the issue details. 
I'm just looking at this issue and found that it is a quite old one. Sorry for not picking the issue for debugging on time.  However, as we got few latest updates on FF since this issue raised and no follow up on the issue, I believe the issue is resolved for you. Hence I am closing the issue for now. If the problem persists yet we can re-open the issue and start investigating. Thanks

**Closed** 2023-02-07 16:52 UTC
Labels: status: needs triage
