### ISSUE TITLE
Build Failed - Error loading project for test mode (package app_links)

### ISSUE THREAD

**Issue by alexandrespindola** [FlutterFlow/flutterflow-issues#3218] opened 2024-06-25 15:49 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hi guys

I'm having a test compilation error due to incompatible dependencies (apparently from the app_links package)

I didn't make any changes to the project, it just stopped working in test mode.

Has anyone experienced this problem or knows what can be tested?

What have you tried so far?
I reverted to the previous version and deleted the last widgets that were updated.

I also tested the version with code in Visual Studio Code, but the same compilation error occurs.

Did you check FlutterFlow's Documentation for this topic?

### Expected Behavior

Let the test mode build normally again.

### Steps to Reproduce

1. Run test

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

../../../.pub-cache/hosted/pub.dev/app_links-3.4.1/lib/app_links.dart:11:38: Error: The method 'getInitialAppLink' isn't defined for the class 'AppLinksPlatform'.  - 'AppLinksPlatform' is from 'package:app_links_platform_interface/app_links_platform_interface.dart' ('../../../.pub-cache/hosted/pub.dev/app_links_platform_interface-1.2.0/lib/app_links_platform_interface.dart').

### Visual documentation

![error](https://github.com/FlutterFlow/flutterflow-issues/assets/104132868/4f3cb143-4eb4-4380-82ab-d3906f2c011f)

### Environment

```markdown
- FlutterFlow version: 4.1.61+
- Platform: web
- Browser name and version: Brave, Chrome, Firefox
- Operating system and version affected: Ubuntu 24
```

**Comment by wwchiang** [comment] 2024-06-25 15:52
Just published my bug report, same issue. Someone messed up the package dependencies.

**Comment by arniigreat1** [comment] 2024-06-25 16:14
> Just published my bug report, same issue. Someone messed up the package dependencies.

yep lol

**Comment by msusviela** [comment] 2024-06-25 16:42
Hi all. It seems to be related to a package upgrade on [pub.dev](http://pub.dev/). Our engineering team is already aware and working on a fix.

I'm closing this issue because It's a duplicate of: https://github.com/FlutterFlow/flutterflow-issues/issues/3217 I'll be following this from this issue.

Thanks for your reports!

**Closed as not planned** 2024-06-25 16:53 UTC
Labels: closed: duplicate

**Comment by dbfcode** [comment] 2024-06-25 16:56
Same here in test mode:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/101150281/25e330c2-afef-4e70-aebd-9a3bcfc4d8d5)
