### ISSUE TITLE
TextField widget max line setting impacting height with no input

### ISSUE THREAD

**Issue by stevey6404** [FlutterFlow/flutterflow-issues#2658] opened 2024-04-04 02:23 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

- In the past, setting a max height to a TextField widget does not change the height of the TextField, now it does. It used to constrain the maximum expansion as the user writes.

### Expected Behavior

- The height of the widget should be based on the minimum and expands slowly to the height based on the max line. On initial load, the height should not be set to max line height. 

### Steps to Reproduce

1. Create a page
2. Add TextField widget
3. Set Min Line as 1 and Max Height as 7

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4siMn1z8pgoctJ1s7ubPlB/SEvOVM1ULgSscpFcxQcB4jZP4kQfPfQPlhWOOqoTH9AeU62p14DpcL9ivPDGMBcORWsb7lyzbVIVDvyWjiteJeTF7mwQ0FRFp9Mfm2B5J2zpyQmLbdeWlof7DmXfuiuQincHr72IFQ4Sq/LZO4=

### Context

impacts user experience as it is totally different behaivour from the past. 

### Visual documentation

<img width="890" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/25169810/82db1c02-61f0-4119-8b61-510a6b1e8a60">

### Environment

```markdown
- FlutterFlow version: 3.19.1
- Platform: Mac Web
- Browser name and version: Chrome Version 123.0.6312.105 (Official Build) (arm64)
- Operating system and version affected: Macbook Air Sonoma
```

**Comment by rzambroni** [comment] 2024-04-04 02:34
Hi @stevey, thanks for the report, our team is already aware of this issue as it is a duplicate of: [https://github.com/FlutterFlow/flutterflow-issues/issues/2625](https://github.com/FlutterFlow/flutterflow-issues/issues/2625). 

The good news is that is already fixed! 

I believe the fix will be available on tomorrow's release. 

feel free to re-file the issue if you continue to experience it after the next update.

**Closed** 2024-04-04 03:20 UTC
Labels: closed: duplicate

**Comment by eduriftio** [comment] 2024-04-05 07:40
Hey @rzambroni, unfortunately, it is not fixed, I just updated the latest FF today and checked the textfield, and it's the same issue.

![Screenshot 2024-04-05 at 1 21 20 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/145130088/04882a2c-9208-41bc-a4ab-3b4c45677564)
