### ISSUE TITLE
Merge conflicts bug - language conflict

### ISSUE THREAD

**Issue by szymonpodwyszynski** [FlutterFlow/flutterflow-issues#1540] opened 2023-09-27 14:25 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In my project after i create a branch and merge this branch into the main, there is a conflict shown as "Language" despite me not changing anything especially in a Language section. The conflict view does not show any changes made in either of branches as none were made. After clicking Resolve Conflicts and Accept this branch/Accept main - the popup is shown to accept all merge changes, and after clicking yes nothing happens - the popup closes but none changes are accepted. The only way to go through with the merge process is to click Resolve Conflicts and to click Accept manually - from there you have to click Save button on top right corner and the button "Resolve Conflict" changes to "Resolved" with a green check. From there you can accept merge and the merge comes through correctly.

### Expected Behavior

If no changes were made, no conflict should be shown.

### Steps to Reproduce

0.5 - Not on every project this error is showing (presuming it has to be somewhat complex and have two or more languages)
1 - In complex project create a new branch
2 - in this new branch merge into main

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sj+flvYtOmM9G15PqccFB/CkXKUM3bJEWscsZa0kdB4joPLJ/dsnBflJvON+/T1NhHGKKrzk1wcLvhtjIUMJeFy+BQKpFwc0JWw7df3q8RpS2CbqCQHFSDd1Uf0yky8PUghVdHNFicWQaw2CmAN+XdA/BJ5+/Zwh9f6PHaOI=

### Context

It has slowed down merging process in our team and we are worried that we are doing something wrong - thus error is showing. We dont want our progress to be destroyed and a random error should not be shown. 

### Visual documentation

[2023-09-27 15-54-23.mp4.zip](https://github.com/FlutterFlow/flutterflow-issues/files/12739669/2023-09-27.15-54-23.mp4.zip)
<img width="961" alt="Screenshot 2023-09-21 at 11 55 24" src="https://github.com/FlutterFlow/flutterflow-issues/assets/139437728/f859c3e8-c97d-4950-ad7a-c92c5e5f2334">

### Additional Info

Im adding a video of the whole process in a zip file.

### Environment

```markdown
- FlutterFlow version: Newest
- Platform: Web
- Browser name and version: Version 117.0.5938.92 (Official Build) (arm64)
- Operating system and version affected: macOS Ventura 13.6
```

**Comment by szymonpodwyszynski** [comment] 2023-10-09 06:58
Hello, i wonder if there has been any updates on this case? This error is showing up constantly and our team wonder about whats the issue - we dont know whos at fault. Let me know if i need to provide some more info, ill be more than happy to help.

**Comment by SameerShahzad99** [comment] 2023-10-30 19:34
Closing this issue as this seems to be resolved now!

**Comment by szymonpodwyszynski** [comment] 2023-10-31 09:56
Hello! This issue should not be closed as i've not received any updates on this bug. Its not a resolved issue because its still happening. Please let me know if i need to provide anymore information on this issue.

**Comment by agreaves** [comment] 2023-12-20 20:46
Hi @szymonpodwyszynski, sorry for completely missing this issue, I'm sure it was super frustrating. I did just want to check whether this issue still persists for you. We've fixed a number of branching related issues in the last couple months so it's quite possible this was fixed as well.

**Comment by agreaves** [comment] 2023-12-22 15:58
@szymonpodwyszynski We had received several bug reports about merging in the first month after it's release, which we've since fixed. I'm guessing given the age of this issue that this is one of them, but of course I can't be sure unless I'm able to reproduce it.

If you want to try it again I'm happy to keep this issue open in the meantime. But otherwise I'll close it under the assumption it's been fixed! Thanks, and once again apologies for your earlier troubles.

**Comment by hariprasadms** [comment] 2024-01-05 12:26
Hi @szymonpodwyszynski - We assume you are no longer experiencing the issue. There have been new updates released, especially around branching, since you initially raised the issue. Please give it a try and confirm if everything appears to be fine now. If you encounter any more issues, feel free to create a new issue or reopen the existing one. Thank you.

**Closed** 2024-01-05 12:26 UTC
Labels: status: needs triage, status: can't reproduce, status: not a bug
