### ISSUE TITLE
Library imports missing

### ISSUE THREAD

**Issue by nev-21** [FlutterFlow/flutterflow-issues#4695] opened 2024-10-26 22:13 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The app crashes cause it lack of some imports. This happens when using transient libraries dependencies.

### Expected Behavior

The app should not crash. The generated code must not have errors.

### Steps to Reproduce

1. create lib A,
    1.1. create apiA
    1.2. publish
2. create lib B
    2.1. import lib A
    2.2. create apiB
    2.3. create compA, add ListView (Text as Child) with apiA as backend query (infinite scroll and gen dynamic children)
    2.4. create compB, add listview (Text as Child) with apiB as backend query (infinite scroll and gen dynamic children)
    2.5. publish
3. create project X
    3.1. import lib B
    3.2. add compA and compB to homePage
    3.3 execute test mode, the app crash
4. download the code of the project X
    4.1. go dependencies/libB/.../compA you will see ApiPagingParams needs an import
    4.2. go dependencies/libB/.../compB you will see "lib_b_..._api_calls_util" which need an import
    
    

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kz/HluIhgrs9J1s/Xbfp4likvJUR7TL03pu0bFEggGLbrBIYMaeLeXFZWXbSkT1VLKEWKmmEC/sreuPHpOMApPQ6AboR8/81MSDn/cDu/aouVDpOoWnclBcFgGh2E0cCO3SMmLuh0Wngd12GYGdnJbDfrN5/4Zwh9f6PHaOI=

### Visual documentation

https://github.com/user-attachments/assets/a6e2ad47-4acb-4442-ad4e-ead53bfe0d24

### Environment

```markdown
- FlutterFlow version:  v5.0.8+ released October 25, 2024
- Platform: web
- Browser name and version: chrome 130.0.6723.70 
- Operating system and version affected: win 11
```

### Additional Information

project bug report code:
IT4kz/HluIhgrs9J1s/Xbfp4likvJUR7TL03pu0bFEggGLbrBIYMaeLeXFZWXbSkT1VLKEWKmmEC/sreuPHpOMApPQ6AboR8/81MSDn/cDu/aouVDpOoWnclBcFgGh2E0cCO3SMmLuh0Wngd12GYGdnJbDfrN5/4Zwh9f6PHaOI=

library B bug report code:
IT4gz/HluIhgofVA7ZSJcO9V+CoXOW1+bYc0sNtuTQIdCYDuBIYiaePSTFtDTb3jTVVfKEWLsDoC+tLqivPAVvU6CzKbbqp41aV+Fz3hVmW/aouVDpOoWnclBcFgGh2E0cCO3SMmLuh0Wngd12GYGdnJbDfrN5/4Zwh9f6PHaOI=

library A bug report code:
IT4gz/HluIhgofVA7ZSJce9VgmUXQlw6RJc0st4bGAsdGOvrBu0hdsnsRFBvZ+rnaVNcIWCGnngH/+vHk+zDO/pdCAWcQIg7zrlcWwHOe2i5R7bUCai8fXwlRN1jfR3AyruFnh5vBMhoWF1m2FOmNtyiQT7DBOu/Zwh9f6PHaOI=

**Comment by Alezanello** [comment] 2024-10-28 16:42
Hello!

It looks like this issue may share the same root cause as the one reported here: [GitHub Issue #4554](https://github.com/FlutterFlow/flutterflow-issues/issues/4554). I'll link this issue internally, as the other one has already been escalated to our engineering team. I will close this as a duplicate for now. If the issue is not resolved after the fix for the previous one is applied, we can reopen this ticket. Thank you for your understanding!

**Closed as not planned** 2024-10-28 16:42 UTC
Labels: closed: duplicate
