### ISSUE TITLE
copy widget style copies entire widget

### ISSUE THREAD

**Issue by padeepz** [FlutterFlow/flutterflow-issues#1726] opened 2023-10-27 14:21 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

when using copy widget style option in a text widget it copies entire text widget including the text value, no difference between copy widget and copy widget style

### Expected Behavior

only the widget style like font family, size,color (text properties) must be copied . not the text value

### Steps to Reproduce

1. create two text widget and have different text properties and values
2. now right click on one and copy widget style 
3. now paste it in another
4. the entire widget is pasted just like using copy widget

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8ol/KA4Y92rtdc1pPqL+9VijsXJmY6RYI7l9Vhaw4YGIvqB4YEeOHOVBRBXfW5S3lHGVL88Xg0w6nKhIaeU+woZQqVRt1g3JVqEA3gTlugMb6JDKmdP3R5I/NXCFS6yrSn2xB8A+FpV1ol3WeYOd/KExHaJYCzIVUdPOaIGKfInk7lKiPWGhZH0R0XAx7eTI5ODEz25eKMrop5yfj/0w==

### Context

fixing this issue will speed up my development 

### Visual documentation

this is a simple bug, easy to reproduce on any page with two text widget

### Environment

```markdown
- FlutterFlow version: 4
- Platform:web
- Browser name and version:chrome Version 118.0.5993.118 (Official Build) (64-bit)
- Operating system and version affected: win 11 pro
```

**Comment by wenkaifan0720** [comment] 2023-10-30 06:42
Hi @padeepz. This is the intended behavior but we are open to suggestions. We recommend the users to use component/theme widget if they want to reuse a certain design, both allow you to not copy the text. Copy widget style right now is basically overriding a widget, and the use case is that if the widget is already there and you just want to quickly update its style. Besides, some user might want to keep some text so it's challenging to find a clear criteria as to what text to keep. We don't want to further complicate this feature and causing confusion to the user. That's why we decide to copy everything right now.

**Comment by katherineqian** [comment] 2023-12-06 22:27
Hi @padeepz, thank you for submitting this -- since @wenkaifan0720 has mentioned this is intended behavior, I'm going to tag this as a feature request. As this issue tracker is specifically for bug reports, we kindly ask you to submit your feature requests through the in-app feature request tool. [You can find it in the “Help” menu inside of the FlutterFlow](https://docs.flutterflow.io/getting-started/ui-builder/tool-bar#2.-help). You can also vote for new features in the FlutterFlow Community by going to the Community Wishlist. This will help us keep track of and prioritize feature requests, ensuring we can continue to improve our product based on user feedback. We appreciate your understanding and look forward to hearing about your ideas! Closing this issue for now.

**Closed by katherineqian** 2023-12-06 22:27 UTC
Labels: status: needs triage
