### ISSUE TITLE
Components with semitransparent colors

### ISSUE THREAD

**Issue by ilimpapps** [FlutterFlow/flutterflow-issues#3102] opened 2024-06-12 08:52 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have component with semitransparent white color, so that in my page with dark background it looks good. But when edit my component it shows as completelly white, so I dont see my component texts. Its impossible to work like that 
![11](https://github.com/FlutterFlow/flutterflow-issues/assets/101993994/d0e5db88-2fa9-49b5-b3c1-190fb96b7574)
![22](https://github.com/FlutterFlow/flutterflow-issues/assets/101993994/a1e1411e-f1d8-444b-a718-858c64cbb61c)

### Expected Behavior

pls make possible to change bg color for component edit or make it the same bg colors as on pages where it used

### Steps to Reproduce

create component with container semitransparent white color (10% transparent)
add white text inside container
add component to page with dark color
go to edit component

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTksrq2ItOsctZ+KriLfpaij0UGUMAXOYvitYbVR42GJztPZYUfeLObUNKTNOgfAhbMGeaij0Dp97QjYfDA/leFwSZRqJF0JVAcDniLWWiaZiIDc2KYXAlBcphfGq64bWRuhJDNux2SlEu7F2bNq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

![11](https://github.com/FlutterFlow/flutterflow-issues/assets/101993994/1b485179-f03f-41e6-9d11-fd97e7889144)
![22](https://github.com/FlutterFlow/flutterflow-issues/assets/101993994/0b7210c0-682f-45e7-a09d-69f95e97e8fa)

### Environment

```markdown
FlutterFlow v4.1.54+ released June 12, 2024
Flutter version is 3.19.1
Windows desktop version
```

**Comment by msusviela** [comment] 2024-06-12 11:27
Hi @ilimpapps. I wasn't able to reproduce the issue. Would you mind sharing the RGB code for the background color of the container?

**Comment by ilimpapps** [comment] 2024-06-12 11:34
#15FFFFFF

> Hi @ilimpapps. I wasn't able to reproduce the issue. Would you mind sharing the RGB code for the background color of the container?

**Comment by msusviela** [comment] 2024-06-12 12:14
I still can't reproduce the issue. Can you share the name of the component that's giving you this issue?<br><br>Is this happening only in windows or also in the web version? From web, all the components are visible when editing.

**Comment by ilimpapps** [comment] 2024-06-12 12:18
Are you using windows desktop version?  Component name: TrainingCardClient

**Comment by ilimpapps** [comment] 2024-06-12 12:22
The issue is only for desktop windows version of FF

**Comment by paulperez-dev** [comment] 2024-07-03 22:21
Hi @ilimpapps! I tried in the latest FF Windows desktop app and can't replicate this behavior. Can you please verify in the newest version?

**Comment by ilimpapps** [comment] 2024-07-03 22:23
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/101993994/1ef910f9-6ec7-4f2e-bae2-6ef695da98c0)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/101993994/9e9ca359-4574-4a8a-9a93-b2a0ee997ce7)
FlutterFlow v4.1.65+ released July 4, 2024
Flutter version is 3.22.2

**Comment by paulperez-dev** [comment] 2024-07-12 22:31
Hi @ilimpapps! I don't understand the meaning of the latest attached images. Can you please add more context?

**Comment by ilimpapps** [comment] 2024-07-12 22:35
I use windows. So when i rightclick on pages or components  right-click-menu shows below the control panel of windows

**Comment by paulperez-dev** [comment] 2024-07-12 22:39
@ilimpapps but this is a different issue. Can you please verify if the reported issue is fixed in the latest windows version ( v4.1.72+)?

The error with the menu can be caused by the screen resolution or text scale. There is a requests to make the menu scrollable.

**Comment by ilimpapps** [comment] 2024-07-12 22:48
yes, it was fixed

**Comment by paulperez-dev** [comment] 2024-07-13 15:19
@ilimpapps thanks for the confirmation! Closing this issue since it was fixed.

**Closed as completed by paulperez-dev** 2024-07-13 15:19 UTC
Labels: closed: fixed
