### ISSUE TITLE
Custom Domain

### ISSUE THREAD

**Issue by mariasantiago27** [FlutterFlow/flutterflow-issues#3063] opened 2024-06-04 21:04 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hi, I am trying to publish a website and I want to customize the domain. I have been reviewing this video from FlutterFlow University https://www.youtube.com/watch?v=M1eNzAlacIA&t=1s but it doesn't show how to add the domain in the standard plan. I have checked FlutterFlow Docs and it says it is in my organizations https://docs.flutterflow.io/getting-started/dashboard/my-organization#add-domains but I personally don't see anything about add domains as indicated in the documentation.

I have already purchased the domain from Square Space.

Does anyone know how I can add it to be able to publish the website under a custom domain in a standard plan?

Thank you very much,

Maria Jesus Santiago

FlutterFlow University https://www.youtube.com/watch?v=M1eNzAlacIA&t=1s

FlutterFlow Docs https://docs.flutterflow.io/getting-started/dashboard/my-organization#add-domains

### Expected Behavior

Being able to add a custom domain to a web published project

### Steps to Reproduce

1. Go to setting and integrations
2. Go to app settings --> Web Publishing 
3. Click add domains (it brings me to My Account but I do not see any option to add the custom domain) 
![Imagen1](https://github.com/FlutterFlow/flutterflow-issues/assets/145969291/aba66054-bf7c-4640-9972-e48bf8f94125)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

https://app.flutterflow.io/project/carla-pau-match-on0w8j?tab=appSettings&appSettingsTab=webPublishing

### Context

To publish a project with a custom domain

### Visual documentation

![Imagen1](https://github.com/FlutterFlow/flutterflow-issues/assets/145969291/a915fc04-6b74-4061-a053-9acbaa055098)
![Imagen2](https://github.com/FlutterFlow/flutterflow-issues/assets/145969291/162b61ad-f3ae-449d-9f8e-6cb4a30c09f6)

### Environment

```markdown
- FlutterFlow version: 3.19.1
- Platform: Web
- Browser name and version: Google Chrome last version
- Operating system and version affected: Windows last version
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by msusviela** [comment] 2024-06-07 13:55
Hello @mariasantiago27.

Thanks for your report, So sorry you are experiencing this issue. I was not able to reproduce this on a blank project, but it is replicable on yours. That's why I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. Thanks so much!

**Closed** 2024-06-14 03:06 UTC
Labels: status: can't reproduce
