### ISSUE TITLE
A strange error appearing in console with the new debug panel

### ISSUE THREAD

**Issue by ubugnu** [FlutterFlow/flutterflow-issues#3108] opened 2024-06-12 19:36 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I keep seeing this error on the javascript console:
```
Error debug serializing parameter: TypeError: Instance of '() => Future<Null>': type '() => Future<Null>' is not a subtype of type 'String?'
```

### Expected Behavior

No error.

### Steps to Reproduce

1. Travel past in the time before the debug panel was deployed
2. Create a component with some form controls (text fields, dropdowns, ...)
3. Test the app, no error message on the console
4. Wait for the FF team to deploy the new debug panel (and yes, you know the future!)
5. Reamrk that this weired new error message is appearing again and again when you change some form controls, and it makes your app not working!
6. Try to travel to the past to warn the FF engineers, but sadly the new bug is also affecting your time travel capsule!

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4CivHq4Ylgrs9A0ZPIce9aniYvNjM1RYEVkOxuVQE3HZPND+x/esnRQFJuZ9OrdghEJlmagnk006HVm9z1E/YoYA+ef6pC/qVqcjzhQkOuVJDXCYeSOHxEGshPf1yB4bSRsAkkB/VaLkId216PNenKcz3dHbrqO0czPuWlJprXmAfuQ0SLb3kNh1JWeC/v

### Visual documentation

[Screencast from 2024-06-12 20-33-01.webm](https://github.com/FlutterFlow/flutterflow-issues/assets/1108370/de89c167-29a0-4b2b-960e-b5b1ca2fc305)

### Environment

```markdown
- FlutterFlow version:  v4.1.59+
- Platform: Web
- Browser name and version: Version 1.66.115 Chromium: 125.0.6422.112 (Official Build) (64-bit)
- Operating system and version affected: Ubuntu 24.04 LTS
```

**Comment by msusviela** [comment] 2024-06-12 23:57
Hey @ubugnu, Thanks for your report, So sorry you are experiencing this issue. I was not able to reproduce this on a blank project, but it is replicable on yours. That's why I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. Thanks so much!

**Closed as not planned** 2024-07-02 19:56 UTC
Labels: status: can't reproduce, closed: support request
