### ISSUE TITLE
Could not convert: Instance of 'LatLng' when uploading a LatLng to Firebase

### ISSUE THREAD

**Issue by FrancoSernaglia** [FlutterFlow/flutterflow-issues#1582] opened 2023-10-04 00:34 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I want to upload a DataType to my list in firebase document . My datatype has LatLng fields and when uploading the following error occurs:
Could not convert: Instance of 'LatLng'
This wasn't happening until I decided to add a new field (String) to my data type. Now nothing of my app can actually work.

### Expected Behavior

To upload the datatype as expected.

### Steps to Reproduce

1.Create Pasajero DataType with latlng fields
2.Create Collection on firebase with a list of Pasajero Datatype
3.Create a Document via Action to add the first element (a Pasajero datatype)
5.Observe how the latlng fields couldn't get converted to GeoPoint

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4okvLlx85grs9G1s/AacFvryQQKVgkR78ricpBazwbfe+uB4kqevfOTERtQu3jTAh+IU2Jp2oW09L3vuGeDfoECxKeQKVy+rpUSQ2Vc3ymMq6VFJWgfUBAO5hVFUij18GNmB4mAM9tSGBi7TiYFuq9TnfDJ5OwOm40D6/LZO4=

### Context

I was trying to add a passenger to a Ride document.

### Visual documentation

This is my datatype structure:
<img width="651" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/128932349/3f523520-9d43-47a4-ac71-f47ef64bb0a6">

### Additional Info

I tried uploading via Custom Action, converting the LatLng to GeoPoint and it works but my app cant allow using custom actions everytime an update of passengers is required.

This is the code that I used to try to debug the problem: (it let me upload my passenger data) (Note that I opted to upload as a Map not as a passenger structure brought the same error)
<img width="415" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/128932349/fba1f29a-6a31-42eb-9f55-13a3a71f1590">

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: Web and Android
- Browser name and version: Chrome
- Operating system and version affected:
```

**Comment by nicolas-gervais-42** [comment] 2023-10-04 11:31
Experiencing the same problem here. Was working fine before the update.

**Comment by hariprasadms** [comment] 2023-10-04 16:50
Hi @FrancoSernaglia - Thanks for submitting the issue.  When uploading a LatLng object to fire-store, you should convert the LatLng object to json formate before uploading to firestore. Try this and let us know how it goes. Thanks

**Comment by FrancoSernaglia** [comment] 2023-10-05 00:39
yes but when uploading via Action this convertion process occurs on the background. Before the update uploading a document via Action was working fine. @nicolas-gervais-42 can confirm this

**Comment by FrancoSernaglia** [comment] 2023-10-05 19:56
This is my action chain
<img width="215" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/128932349/52f1414f-44f5-4faa-81d5-c14b0ee9bc2b">
<img width="376" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/128932349/d6791f4c-163f-4ecc-b4f1-b73dc1316274">

**Comment by hariprasadms** [comment] 2023-10-07 19:40
Hi, I looked at your project. There are more page and actions. Its a bit of challenge for us to investigate with this size applications. We defiantly need a blank project with issue steps reproduced. Please add these details and let us know.

**Comment by FrancoSernaglia** [comment] 2023-10-07 22:09
I have created the blank project and the error persists! Great news
This is the bug code:v IT4gz/Hqx89goeFK187ude9WimEUC1N9U600st5Hd0gdCOPrBqQLPcmkYRNVcMOkaVNcO079mkUGpPDKhuPLOPcoHzuAfb5f+KtUUQH0e2iVbJCIO8y0OXNSEdtjIGrD0bW3myJ7IrBsWXw76k+HN/OWbDDDIuu/Zwh9f6PHaOI=

**Comment by FrancoSernaglia** [comment] 2023-10-07 22:10
<img width="752" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/128932349/cc5aa555-518e-49a6-ae88-b68331635b42">

**Comment by hariprasadms** [comment] 2023-10-08 09:43
> <img alt="image" width="752" src="https://user-images.githubusercontent.com/128932349/273415080-cc5aa555-518e-49a6-ae88-b68331635b42.png">

Thanks for the blank project details. I will have a look and confirm the status.

**Comment by hariprasadms** [comment] 2023-10-09 13:42
Hi, I can reproduce the issue.

**Comment by nicolas-gervais-42** [comment] 2023-10-30 18:46
Hi @hariprasadms , @agreaves , any updates on this one ? Thanks !

**Comment by nicolas-gervais-42** [comment] 2023-11-10 11:26
Hi @hariprasadms , hope you are well. was this resolved with the new update ? 

Best,
Nicolas

**Comment by nicmohr25** [comment] 2023-11-28 19:20
Hi @hariprasadms is there an update on this? I'm experiencing this issue as well

**Comment by bansi-patel-2805** [comment] 2023-12-05 17:39
hello,

Please resolve this issue, my whole app stopped working due to this error.

Can you please give me timeline so I can plan accordingly.

Best Regards,
Bansi Patel

**Comment by nicmohr25** [comment] 2023-12-16 20:09
Hi @hariprasadms ,is there an update on this problem? 
Thanks

**Comment by agreaves** [comment] 2023-12-20 23:26
Hi @FrancoSernaglia, @nicmohr25, and all. Sorry for the extremely delayed on this issue from the engineering side, it completely escaped my tracker. I've managed to reproduce and fix the issue (thank you @FrancoSernaglia for the really great basic example) and this will be reflected on our next release!

**Closed by agreaves** 2023-12-20 23:26 UTC
Labels: type: bug, status: confirmed, priority: medium
