### ISSUE TITLE
Loading a Document from a passed Reference is broken

### ISSUE THREAD

**Issue by atn832** [FlutterFlow/flutterflow-issues#25] opened 2022-10-07 05:05 UTC
## Expected behavior (required)
When a view passes a Document reference to another view, I expect the other view to successfully load the document from the reference.

## Current behavior (required)
I get an infinite spinner and the data never loads. No error is displayed either.

## To Reproduce (required)
1. I set up a first view with a ListView showing documents in a collection.
2. I set up a second view which will show the selected document.
3. In the first view, I set up the ListViewItem to navigate to the second view, and pass the document reference.
4. In the second view, I set up the Scaffold to load a document based on the passed document reference.
5. In the Scaffold, I have a Text widget which displays a field from the loaded document.

I am basically following the steps at:
- https://docs.flutterflow.io/data-and-backend/backend-query/document-from-reference
- https://www.youtube.com/watch?v=hkBWVwr7yXQ

## Context (required)

I am trying to load a document from a passed reference.

## Screenshots / recordings
Another user in the Discord channel was able to reproduce the bug: https://discord.com/channels/845826746582695976/845826825992929321/1027793029517545493.

To work around this issue, the solution they shared, which works for me too, is to pass the Document itself. Then in the second view, load the document again using the passed Document's reference.

I tried setting up two Text widgets, one using the passed reference, and the other reading the reference from the passed document. The first one shows an infinite spinner. The second one shows the data. I expected both to just show the same data (ie "bakeree").

<img width="367" alt="image" src="https://user-images.githubusercontent.com/3399854/194471746-e34bbaf6-fb65-47c2-ba03-16344a3a2866.png">

The resulting code is nearly identical and seems correct:
```dart
              StreamBuilder<CompaniesRecord>(
                stream: CompaniesRecord.getDocument(widget.companyRef!),
                builder: (context, snapshot) {
                  // Customize what your widget looks like when it's loading.
                  if (!snapshot.hasData) {
                    return Center(
                      child: SizedBox(
                        width: 50,
                        height: 50,
                        child: CircularProgressIndicator(
                          color: FlutterFlowTheme.of(context).primaryColor,
                        ),
                      ),
                    );
                  }
                  final textCompaniesRecord = snapshot.data!;
                  return Text(
                    textCompaniesRecord.name!,
                    style: FlutterFlowTheme.of(context).bodyText1,
                  );
                },
              ),
              StreamBuilder<CompaniesRecord>(
                stream: CompaniesRecord.getDocument(
                    widget.passedCompany!.reference),
                builder: (context, snapshot) {
                  // Customize what your widget looks like when it's loading.
                  if (!snapshot.hasData) {
                    return Center(
                      child: SizedBox(
                        width: 50,
                        height: 50,
                        child: CircularProgressIndicator(
                          color: FlutterFlowTheme.of(context).primaryColor,
                        ),
                      ),
                    );
                  }
                  final textCompaniesRecord = snapshot.data!;
                  return Text(
                    textCompaniesRecord.name!,
                    style: FlutterFlowTheme.of(context).bodyText1,
                  );
                },
              ),
```

## Your environment

* Version of FlutterFlow used: 
<img width="228" alt="image" src="https://user-images.githubusercontent.com/3399854/194471372-db90560b-869e-465d-bc10-e13cb4807d83.png">

* on a Mac Mini M1 in Chrome 105.0.5195.125 (arm64).

**Comment by hariprasadms** [comment] 2022-10-07 15:40
Hi, To load the documents from document reference you should use the query type 'document from reference'. I hope you are using the same type. I have tested this and works fine for me.  You can DM me your project link through community portal. It mostly looking like configuration issue.

**Comment by atn832** [comment] 2022-10-07 22:53
Thanks, I sent you on DM on discord.

**Comment by hariprasadms** [comment] 2022-10-08 14:26
Hi @atn832 , Thanks for sharing your project. I had a look the pages you were talking about above (home and view form). I don't see any wrong in passing parameters ( the doc and doc ref  types). it looks all right. However, in view form page I can't see the data binding from docRef. Looks like there are json data mapping. 

I have tested your use case in my local project by creating exact pages and parameters you got in your project. It is working fine with no issues. I can load the data from both Doc and Doc Ref. 

As suggest, load the data from doc reference on a page and see how it works. Let me know how it goes.

**Comment by atn832** [comment] 2022-10-09 01:04
Thanks for checking @hariprasadms. In ViewForm, the loading from doc reference is done in the Scaffold so that all children can use the data as you can see in the screenshot below:

<img width="282" alt="image" src="https://user-images.githubusercontent.com/3399854/194732626-0b6e9d71-64e6-4888-bc23-7e6172474b64.png">

In the screenshot above, I load the doc from the passed reference, and this gives me an infinite spinner. However, if I load the doc from reference using the passed doc, it works.

Just to isolate the issue, I've created a brand new page called LoadFromRefTest with two Text fields. Each one loads the doc from ref and display the Doc's name field. One of them uses the Doc parameter, the other the Doc Reference parameter. I can still reproduce the issue in this page. The one loading the doc from the reference of the Doc parameter loads fine, the one loading the doc from the reference parameter itself does not.

Load Doc from Ref using the passed Document (works fine):
<img width="571" alt="image" src="https://user-images.githubusercontent.com/3399854/194732759-d3113abd-c33a-444c-b63f-a712955cb5ef.png">

Load Doc from Ref using the passed Reference (infinite spinner):
<img width="275" alt="image" src="https://user-images.githubusercontent.com/3399854/194732711-3e227afb-3a6e-4204-a81d-ee3b1979f4b3.png">

The result:
<img width="144" alt="image" src="https://user-images.githubusercontent.com/3399854/194732664-6fcc43bf-9824-4f58-bdcf-624d4c41805f.png">

Would you mind taking another look at my settings? I saved this as snapshot v6.

**Comment by hariprasadms** [comment] 2022-10-09 18:50
Hi @atn832, I still can't reproduce the issue. However, i can see that, it works for you when you pass the doc as parameter and load the doc data in next page. I suggest continue using the way it is working for you. We will keep an eye on this issue and see if we can get the same issue from other users as well. For now, I will close the issue as we can't reproduce. Thanks

**Comment by agreaves** [comment] 2022-10-11 05:50
Hi @atn832, I also haven't been able to reproduce this, but if you could reply with the Bug Report code I'll take one last stab at it before closing. To get this, go to the Widget Tree, and right click the widget with the Navigate action (the one that navigates to the page that is having issues with Doc from Ref) and click "Get Bug Report Code". Thanks!

**Comment by atn832** [comment] 2022-10-11 09:56
Thanks for checking one last time. I used the "Copy Widget Code" on the ListViewItem that navigates to the other page, and got this code:

```dart
InkWell(
  onTap: () async {
    context.pushNamed(
      'LoadFromRefTest',
      queryParams: {
        'companyParam': serializeParam(
          listViewCompaniesRecord,
          ParamType.Document,
        ),
        'companyRefParam': serializeParam(
          listViewCompaniesRecord.reference,
          ParamType.DocumentReference,
        ),
      }.withoutNulls,
      extra: <String, dynamic>{
        'companyParam': listViewCompaniesRecord,
      },
    );
  },
  child: ListTile(
    title: Text(
      listViewCompaniesRecord.name!,
      style: FlutterFlowTheme.of(context).title3,
    ),
    subtitle: Text(
      listViewCompaniesRecord.announcementMethod!,
      style: FlutterFlowTheme.of(context).subtitle2,
    ),
    trailing: Icon(
      Icons.arrow_forward_ios,
      color: Color(0xFF303030),
      size: 20,
    ),
    tileColor: Color(0xFFF5F5F5),
    dense: false,
  ),
)
```

<img width="849" alt="image" src="https://user-images.githubusercontent.com/3399854/195058990-82b19f36-d633-4ac1-a690-fa308b7c6db4.png">

**Comment by hariprasadms** [comment] 2022-10-11 10:40
Hi @atn832 - Thanks for adding me to your project share. I just made a changes to viewform test page. I suggest run the project and see how it works. It think it should work with no issues if all correct.

**Comment by atn832** [comment] 2022-10-11 11:52
@hariprasadms Would you mind letting me know specifically what you changed in my project? I don't want to bug you the next time I run into that issue. I am looking at v8, which is the version I made and I don't see any change. I can still see ViewForms load the doc from the passed Doc instead of the passed Reference.

<img width="567" alt="image" src="https://user-images.githubusercontent.com/3399854/195082126-f81bad38-f7ff-4105-9679-93bcea1eb689.png">

Here's the list of snapshots I have made recently:
<img width="391" alt="image" src="https://user-images.githubusercontent.com/3399854/195082438-821b7fa0-b789-4a0a-9fe5-5b6aba976b32.png">

**Comment by hariprasadms** [comment] 2022-10-11 13:06
Hi @atn832, Earlier my changes not saved it seems. No worries. I just created a new page and mapped the doc ref data which is coming from home page. I suggest run this page and see how it works. Refer version 9 in the project history.

![image](https://user-images.githubusercontent.com/17435678/195098496-6756b7d9-29e1-4a56-a3e4-529ca84e7828.png)

**Comment by atn832** [comment] 2022-10-11 13:38
@hariprasadms @agreaves I think we're making some progress. I tried Hari's example form, and I get the infinite spinner issue. I am located in South Korea. Perhaps it has to do with my location? Also, someone else in the chat ran into the same issue as me, and they appear to be located in Japan:
- https://discord.com/channels/845826746582695976/845826825992929321/1027793029517545493 (was able to reproduce my issue)
- https://discord.com/channels/845826746582695976/845826825992929321/1027796273065111582 (I assume they're in Japan)

Here are two screen recordings. In the first one, I simply try Hari's form, and I get the infinite spinner. In the second one, I switch to passing a Doc, then loading from ref using that Doc, and it loads the data:
https://drive.google.com/drive/folders/17BDEXA1MAb0ivqsnUBOmK_enYsoWqqVY?usp=sharing

**Comment by agreaves** [comment] 2022-10-30 18:42
We still have not been able to reproduce this issue so I'm closing it for now unless more information / steps to reproduce come to light.

**Closed by agreaves** 2022-10-30 18:42 UTC
Labels: status: can't reproduce, closed: non-specific
