### ISSUE TITLE
Compilation error: "getter 'entryPage' isn't defined"

### ISSUE THREAD

**Issue by PGonzalvez** [FlutterFlow/flutterflow-issues#2273] opened 2024-01-31 09:00 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When trying to run the APP in test mode, I have the following error (the error is very similar in Run mode):

```
Launching lib/main.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...
lib/main.dart:191:17: Error: The getter 'entryPage' isn't defined for the class '_MyAppState'.
- '_MyAppState' is from 'package:wellness_watcher_a_p_p/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'entryPage'.
? entryPage ?? NavBarPage()
^^^^^^^^^
Waiting for connection from debug service on Web Server...         63.7s
Failed to compile application.

```

I have tried using earlier saved versions but I'm facing the same error. Those versions were working before.

I have pushed the coed to my GitHub repo to try it out locally, and adding the said getter in the main.dart file fixes the error.
However, that's something that I can't do in FlutterFlow.

I reported this in the community last Friday without a solution so far https://community.flutterflow.io/ask-the-community/post/problem-running-app-in-test-and-run-mode-V8AoSQaJBArxPko?highlight=rEJ4rirP6LGXYZo
and another user reported exactly the same issue.

I also reached out to support through the chat last Friday, but I don't have an answer either.

### Expected Behavior

The expected behavior is that the project should start up normally.

### Steps to Reproduce

Run the project in test or run mode.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

I don't have this, because it is not specific to a Widget

### Context

Suddenly since last Friday it is failing.

Before that, last time I made changes and run it, everything was working the days before.

In addition, previous versions are not working either.

### Visual documentation

<img width="1143" alt="Screenshot 2024-01-27 at 6 53 50 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/5763908/256fc822-4d1b-41a5-88de-0f3c86f21e94">

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1 released January 25, 2024 - Flutter version is 3.13.7
- Platform: Trying to run in the Web directly from FlutterFlow UI
- Browser name and version: Version 117.0.5938.149 (Official Build) (arm64)
- Operating system and version affected: Mac OS 13.2.1
```

**Comment by Robmania** [comment] 2024-01-31 09:23
At a high level, I created a sample Auth flow project, and when I ran it, it worked as expected.  I then added a Test to test the application, and I then got the same error as posted above. Only way to get it working again is reverting to the version before adding the test.

**Comment by PGonzalvez** [comment] 2024-01-31 09:34
Thank you so much!

I had added one test to actually try out the automated testing functionality and it was that. I have removed the test, and it runs again. I don't know why this was not reverted when moving to earlier versions, or maybe it was working before and the test was also in the previous versions that I tried out, I can't remember exactly when I added that test.

Anyway, I think that this is a bug from FlutterFlow, but at least I can continue with my project.

**Comment by hariprasadms** [comment] 2024-01-31 10:02
Hi @PGonzalvez - Thank you for submitting the issue. Kindly update the issue with the project bug report code. I have checked the details in my test project but was unable to reproduce the issue. Please create a new project with the issue reproducing in it and share the project bug report code. This will be useful in investigating and resolving the issue. Appreciate your cooperation. Thank you.

**Comment by PGonzalvez** [comment] 2024-01-31 14:03
I can't reproduce it from an empty project.

@Robmania you said that you could, maybe you can share it as you said you were able to reproduce it from a new project?

**Comment by aemelyanovff** [comment] 2024-01-31 19:26
Thanks for reporting the issue. It will be fixed in the next update.

**Closed by aemelyanovff** 2024-01-31 19:26 UTC
Labels: status: needs triage, needs a blank project with issue setup, waiting for user response
