### ISSUE TITLE
Mi app se queda en pantalla negra al avanzar en dos páginas

### ISSUE THREAD

**Issue by ARIELcal** [FlutterFlow/flutterflow-issues#408] opened 2023-01-25 03:51 UTC
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
 hago clic en un botón para avanzar a la siguiente página y se va a negro, me pasa solo en dos de las páginas de mi app
![Screenshot_20230125_004553](https://user-images.githubusercontent.com/122288215/214475558-2f866cd8-83b8-4f76-b076-bf2235546853.jpg)
![Screenshot_20230125_004712](https://user-images.githubusercontent.com/122288215/214475564-91b2be30-6fce-497a-b4fc-105c2ee489b0.jpg)
![Screenshot_20230125_004715](https://user-images.githubusercontent.com/122288215/214475566-a53dbec9-5f21-4561-ac7f-b7eed611d050.jpg)
@

## To Reproduce (required)

1.
2.
3.
4.

## Your environment
 en modo View la app funciona bien, en modo test y al descargar la apk me sucede lo mismo, " en la pantalla "ver mis reportes" se va a negro, apretó el botón back de mi teléfono y ahí pasa a al pantalla deseada "Mis reportes" la otra falla es al apretar el icono + "crear un nuevo reporte" la página se va a negro y no me dirige a la pantalla siguente
* Version of FlutterFlow used: 3.
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile): Android 12

**Comment by bulgariamitko** [comment] 2023-01-25 07:27
This issue tracking is intended in English only, so please edit your request and write the information in English.

**Comment by aemelyanovff** [comment] 2023-01-25 23:24
Closing the issue. @ARIELcal feel free to reopen (or better open another issue) if you rewrite the description in English and add reproducible steps.

**Closed by aemelyanovff** 2023-01-25 23:24 UTC
Labels: status: needs information, status: can't reproduce, status: needs reproducible steps
