### ISSUE TITLE
Map List Items with To Data Types doesn't work for api calls

### ISSUE THREAD

**Issue by vaital3000** [FlutterFlow/flutterflow-issues#1684] opened 2023-10-22 09:37 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I get error, when I try to use "To Data Types" in "Map List Items" for api calls

https://api-to-data-type-bug-adlgu7.flutterflow.app/
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/15158048/ccdecfca-77d9-4160-ad3b-17f0215796c8)

Also I get readable error when I run project locally in debug mode.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/15158048/710205a0-3ac0-4314-8c68-0547b1f3ff11)

Error happens here.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/15158048/ac4dc7d1-a6f7-41ce-a4cd-357604831325)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/15158048/1fbcb146-9b7a-4308-afea-ffba867e8eb6)

I found only two extensions with "withoutNulls" with signatures 
 "Map<String, dynamic> get withoutNulls"
 and 
 "Map<String, String> get withoutNulls"
 
 

### Expected Behavior

Mapping works fine

### Steps to Reproduce

1. Create new Page
2. Add Api Call (for example https://jsonplaceholder.typicode.com/posts)
3. Setup response json Path
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/15158048/7fbcbeef-b1d6-40da-bb71-8c7ee4ae258e)

4. Add ListView
5. Call Api in backend query in ListView
6. Create DataType
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/15158048/9ad278a3-e112-40d4-b9bf-22e690c4ed9a)

7. Setup map api response to Data type
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/15158048/b239449d-6922-4b4e-8e7c-e7bb973bd292)

8. Create element for display api data in listView item

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Sl8j14otIsbVE7rr+KfpR/WAQKUgjRYI309VQEBAjCKLwOoolXOjDflJvOdeFT2xYelu0qzo0wNKLheztCOQHAy6qfao41ZYNTjvNUjuWRZSDELuCRHJCL+9YNEuV15inhR1QCO52WV1k7WalNumvVi/BJ4C3Nm4zLc+HJtnUn3SkAhm6Xn0Jg1ZSfCvr

### Context

I want use mapping to data type for using typed properties from api array. 
(for example I can setup number format for typed number properties)

### Visual documentation

I attached files in previous places

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: 3.13.7
- Browser name and version: Chrome
- Operating system and version affected: Web, Android
```

**Comment by darbanhandrew** [comment] 2023-10-23 05:42
When do you think it will be solved? i have used this on a project with deadline and now i am dreadful to go for the custom code and custom action for now.

**Comment by darbanhandrew** [comment] 2023-10-29 13:16
@hariprasadms @vaital3000 
I have found a solution, you should convert the incoming json before converting to data type. i have created two custom functions  for that which i use before converting to data type and it works fine. ( found it by reading the schema structure that flutterflow generated and it had an emphasis on Map<String, dynamic> which is iconically couldn't be the output of a custom function: 
Custom function for converting list of json and converting json : 
`dynamic convertSingleMap(dynamic json) {
  /// MODIFY CODE ONLY BELOW THIS LINE

  if (json is Map) {
    Map<String, dynamic> newMap = {};
    for (var key in json.keys) {
      if (key is String) {
        newMap[key] = json[key];
      } else {
        newMap[key.toString()] = json[key];
      }
    }
    return newMap;
  } else {
    return json; // If json is not a map, return it as is
  }

  /// MODIFY CODE ONLY ABOVE THIS LINE
}`

seccond one is : 


List<dynamic> convertMap(List<dynamic> originalMap) {
  /// MODIFY CODE ONLY BELOW THIS LINE

  List<dynamic> newList = [];
  for (var item in originalMap) {
    if (item is Map) {
      Map<String, dynamic> newMap = {};
      for (var key in item.keys) {
        if (key is String) {
          newMap[key] = item[key];
        } else {
          newMap[key.toString()] = item[key];
        }
      }
      newList.add(newMap);
    } else {
      newList.add(item); // If item is not a map, add it to newList as is
    }
  }
  return newList;

  /// MODIFY CODE ONLY ABOVE THIS LINE
}

**Comment by devjones** [comment] 2023-11-02 02:53
Can confirm issues with this, which is significantly delaying.  I'm not able to have any type safety in my project which only uses API calls until this is fixed.  Currently working around by extracting API data using JSON Paths (not optimal).@darbanhandrew Will try your approach.

**Comment by devjones** [comment] 2023-11-02 03:03
It seems `fromMap` assumes that the input Map instance has values of the same type as the DataStruct, which is not true. DateTime fields for example, will be represented in the Map instance as strings, and can not be directly assigned to a DataStruct where it has type DateTime.  integers and strings so happen to match types though, so they convert fine.

**Comment by darbanhandrew** [comment] 2023-11-02 09:23
@devjones Yeah i have created another function that converts date time based on the input format ( I cover 4 types i think). I will share the code of that function later. 
the problem is on DateTime as it's critical typing. I wish this issue will be resolved and I would've like to commit to it.

**Comment by natasha-sb** [comment] 2023-11-02 15:02
I've encountered a similar issue twice (might be the same underlying issue).  Basically, if I set a JSON Path for an API response that is a List<Integer> (FF also interprets it as a List<Integer> on the API JSON Path setting screen), and then I pass that object to a function that expects List<int>, I get the error "expecting List<int> but got List<Object?>.  

I solved it by passing the entire JSON body into the function instead and parsing out the path 'from scratch'.  Not ideal and not expected, given that FF says on the Response & Test screen when hovering over the path "Type: List<Integer>  Can be used as List<Integer> or List<Double>"...

**Comment by felipeboff** [comment] 2023-11-05 04:01
It seems that a straightforward function iterating through each object and adding them to a new array is sufficient; I believe this way, we won't encounter any issues.

https://www.loom.com/share/a14921a7bff04a0ab219f8c58e694ba5?sid=fc78146f-e91a-422f-bb05-6ab32b070512

```
List<dynamic> listJSON(dynamic jsonMap) {
  /// MODIFY CODE ONLY BELOW THIS LINE

  List<dynamic> list = [];
  for (var item in jsonMap) {
    list.add(item);
  }
  return list;

  /// MODIFY CODE ONLY ABOVE THIS LINE
}
```

**Comment by hariprasadms** [comment] 2023-12-12 13:03
Hi @vaital3000 - This has been fixed and working fine in FF current version. Can you please check and confirm ?.
Thanks

**Closed** 2023-12-16 19:01 UTC
Labels: type: bug, status: confirmed, closed: fixed
