### ISSUE TITLE
Shimmer animation renders components invisible

### ISSUE THREAD

**Issue by liamcarterhawkins** [FlutterFlow/flutterflow-issues#3814] opened 2024-09-12 19:18 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I attempt to add the shimmer animation upon page load to a container or a button, the component doesn't appear.

### Expected Behavior

I expect the shimmer animation that appears in the preview to render the same when in the test environment.

### Steps to Reproduce

1. Add a container or a button with variables applied.
2. Add a shimmer animation upon page load (and set the animation to loop)
3. Preview the build in the test view.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ok8n65ZJNochE7c+BcfowqyQ7H2U2RpEzkspBazwbfe+uB4kqevfOTERBOPGmS2x5fGaJq2oW0tKOk+P9Gu0EOQyrfos/+odyeg7LcFK5R5DSFJWgQkFBP+dnBXWB5raJghBBKtphSlJn70+uIeiuRXbDCZf4OlgaD6/LZO4=

### Visual documentation

Unable to provide example as it uses sensitive information that I wouldn't want non Flutterflow devs to view.

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.89+ released September 10, 2024, Flutter version is 3.22.2
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected:
```

**Comment by rzambroni** [comment] 2024-09-13 18:58
Hi @liamcarterhawkins,

Thank you for the report! Unfortunately, this is a known Flutter issue, and there’s not much we can do from our end at the moment. You can find more details in a previous report here: [GitHub Issue](https://github.com/FlutterFlow/flutterflow-issues/issues/2857#issuecomment-2110453796).

This issue is tied to the renderer FlutterFlow uses for the web. A potential workaround would be to test using LocalRun instead.

I’ll go ahead and mark this ticket as a duplicate of the [previous report](https://github.com/FlutterFlow/flutterflow-issues/issues/2857). 

Thanks again for your understanding!

**Closed as not planned** 2024-09-13 18:58 UTC
Labels: closed: duplicate
