### ISSUE TITLE
Multiple "Arrays Contains" or "Arrays in" in FF UI

### ISSUE THREAD

**Issue by coach1990** [FlutterFlow/flutterflow-issues#3737] opened 2024-09-04 08:08 UTC
### Can we access your project?

- [ ] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

With respect to this video, Firebase has made major changes in the multiple queries: https://www.youtube.com/watch?v=qMZ_q-iHqsU

its still not showing in FF UI. Many projects are dependent on this update. Since many users are non-technical. we dont know how to write complicated queries to do such similar jobs. If you can update FF UI for this change, it would be a huge help. 

Could you please update us on this feature?

### Expected Behavior

FF UI should allow multiple arrays filters on the firestore fields

### Steps to Reproduce

Not applicable

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sjPHq2ItOodhE7rXyccd7/WYXC217beYescp/bxIgGIDzPOw+ZPXsbRBtXsviTWNMMUSmmkcF/9bTi9+eVMBfNk+cY4R7yLhqVAndeHyVe5OBDqiOdEdBM9tUC2GM5pjZkxZ5HLFucl4s7U6yG+/KUXTrHu/AIndISq/LZO4=

### Visual documentation

not applicable

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.85+ released August 27, 2024 Flutter version is 3.22.2
- Platform: Desktop App Windows
- Browser name and version: Microsoft Edge Version 127.0.2651.74 (Official build) (64-bit)
- Operating system and version affected: Windows 11 Home Single Language , 23H2

Project: letMeDraw
Project ID: let-me-draw-zo88ww
```

**Comment by Alezanello** [comment] 2024-09-04 11:50
Hello!

Thanks for bringing this up! The good news is that someone else requested this a few weeks ago, and it's already in the engineering team's backlog. Unfortunately, I don’t have an estimate for when it will be picked up or delivered.

That said, since this GitHub issue tracker is mainly for bugs that can be reproduced from a new blank project, and this seems more like a feature/enhancement request, I'll go ahead and close it here. But don’t worry—I’ll attach your request to the internal ticket so the team is aware that more people are interested in it.

Have a great day!

**Closed as not planned** 2024-09-04 11:50 UTC
Labels: closed: feature / enhancement request
