### ISSUE TITLE
Cannot upload Video/MP4 files to Project Assets

### ISSUE THREAD

**Issue by OldFred2023** [FlutterFlow/flutterflow-issues#1665] opened 2023-10-19 16:47 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Can no longer upload Video/MP4 files to project media

### Expected Behavior

to be able to upload files to project media like have been doing for on project beforehand.

### Steps to Reproduce

try uploading an .mp4 file.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

na

### Context

I cannot complete app as it is heavily media based and needs embedded video that has been fine up till this point - This is a major/critical issue for this project.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122821259/c1b99d3a-59e2-44b2-b8fc-42f95594ccfa)

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by kiwimagic** [comment] 2023-10-19 19:13
I am receiving the same error for trying to upload both .mp4 and Lottie files (.json) I created a new project from scratch and tried uploading existing Lottie files that I currently already have in my project and it fails - same message as reported above.  I can confirm I can load png and jpg files successfully.  Tested loading both via the Lottie animation Asset Animation button as well ass the general Assets area from the main menu.
<img width="1365" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/10331428/5489c3c4-72e8-41ac-8248-163e4bda1f77">
<img width="1365" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/10331428/f6b4dbfc-a896-4336-bd01-24282aaf85e7">

**Comment by kiwimagic** [comment] 2023-10-19 20:05
I saw a new build was pushed for FF so I updated and tried loading my Lottie file again.  It now works.  NOTE: the version number I see v4.0 Flutter 3.13.7 has not changed so just fyi seems to have been an incremental fix pushed and number wasn't iterated.

**Comment by kiwimagic** [comment] 2023-10-19 20:07
@OldFred2023 I just tried mp4 as well and it works for me on the new build - you may want to give it a go.

**Comment by katherineqian** [comment] 2023-10-19 20:07
Yes, the issue should be fixed now. Thanks for reporting and sorry about the inconvenience.

**Closed by katherineqian** 2023-10-19 20:07 UTC
Labels: type: bug, status: confirmed
