### ISSUE TITLE
Changes are reverted and the bug indicator keeps spinning

### ISSUE THREAD

**Issue by rikark** [FlutterFlow/flutterflow-issues#4035] opened 2024-10-11 08:05 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I make changes, they are reverted after a couple of seconds. Sometimes the changes appear again after a couple of seconds, sometimes they are permanently removed. 

It started when I was making setting conditionals in the conditionalbuilder. 

I have a screenrecording of the issue, but it's too big. 

### Expected Behavior

Not reverting changes I made

### Steps to Reproduce

Add a conditionalbuilder to a widget
Add multiple conditions
Duplicate a condition to another condition

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oksn138tPsdtJ0LX2cvlalSQWNkN9bIJN0MpBVTwbfe/1P4YUf8+kM0puT8/jT2x2IlmWgm01zPzKv87DDPldFByJb48/wZd1Ejnvc3GgaamVPLW0ekR5I+lPIBDHzpuZnhVSFMlhLEIYwU+AH+mvdC/sNLrrDDAjAuSHMr/UomCWAg/sGn0Jg1ZSfCvr

### Visual documentation

https://github.com/user-attachments/assets/a2454569-94a7-4e2a-85d5-96e4a699d3fd

See the conditional builder second to last option

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.0+ released October 9, 2024 Flutter version is 3.22.2
- Platform: Chrome
- Browser name and version: Chrome
- Operating system and version affected: Chrome OS
```

**Comment by AlexWrench** [comment] 2024-10-11 08:34
I can confirm this is also happening on the windows client.

**Comment by rikark** [comment] 2024-10-11 08:41
I have a very long screen recording reproducing this error, but I can't upload that here. 

Also the text input field for the path in the Route Settings flashes red sometimes for some pages (but not always for the same page), might by related.

**Comment by j-mcq** [comment] 2024-10-11 10:04
I can confirm this is happening for us on both the Windows client and in Chrome directly for nearly every action I try and make. Looks like this is a similar issue to another recent bug toos: https://github.com/FlutterFlow/flutterflow-issues/issues/4032

**Comment by maarrccss** [comment] 2024-10-11 10:08
Same, this is happening since a few days ago as well. Some changes are reverted instantly, as if they werent saving.

**Comment by deepanchal** [comment] 2024-10-11 15:06
I can confirm this is happening on chrome

**Comment by cecmarco** [comment] 2024-10-11 15:43
I can confirm this behavior in Chrome/Safari/Firefox and in the Mac desktop app.

**Comment by Alezanello** [comment] 2024-10-11 17:49
Hello everyone!

I wanted to let you all know that we’re aware of this issue, and we're actively working on a fix. I’ll be closing this issue as a duplicate so we can focus all efforts on the original one, which you can follow here: [https://github.com/FlutterFlow/flutterflow-issues/issues/4032](https://github.com/FlutterFlow/flutterflow-issues/issues/4032).

Thank you for your understanding!

**Closed as not planned by Alezanello** 2024-10-11 17:49 UTC
Labels: closed: duplicate
