### ISSUE TITLE
Property override: string property not properly set in text field

### ISSUE THREAD

**Issue by icarusphoenixdragon** [FlutterFlow/flutterflow-issues#3027] opened 2024-05-31 12:28 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Error appeared recently. Clicking the error does not navigate to text field widget or page. Cannot see any issues with any text fields. Cannot run test mode because of this and so it begins to look like the entire functionality of developing in FF is destroyed.
![FF bugs](https://github.com/FlutterFlow/flutterflow-issues/assets/171347014/000ef291-3e1f-4854-a8d9-573568dc9ab4)

### Expected Behavior

1) text fields work
2) clicking bugs navigates to problem widgets

### Steps to Reproduce

Not sure as I can't actually find the bug.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4slfHl8Yx1rsRE7rqBb8Br/SE7Q304bb8wscp/bxIgGIDzPOw+ZPXsRFFBZ7CmTAk7PUSmmjkdpvT3uPL1LfQqaDWtbNVh1ahMFxXdVlOiUZOBPKuCWXFPN+NQJhzG06Wrnx54OvZtLV4d3Tn7B96+d3PvJ5v4ImdISq/LZO4=

### Context

I can't continue my project. I'm litterally just trying to continue but cannot as the errors cannot be found.

### Visual documentation

![FF bugs](https://github.com/FlutterFlow/flutterflow-issues/assets/171347014/d893f357-de3a-4cbd-8991-778878fe1cfa)

### Environment

```markdown
- FlutterFlow version: 4.1.54+
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: Windows
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by msusviela** [comment] 2024-05-31 12:56
Hi @icarusphoenixdragon - Thanks for submitting the issue. I've taken a look at your project, but with a lot going on, it's challenging to pinpoint the issue. Given the nature of the problem you're highlighting, we need a blank project with the issue steps set up in it. Without these details, it might be a bit challenging for us to investigate the issue. Please provide the required information. If the issue is already resolved for you, please feel free to close the issue. Thanks!

**Comment by msusviela** [comment] 2024-06-11 16:19
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Closed** 2024-06-14 03:07 UTC
Labels: closed: other, waiting for user response
