### ISSUE TITLE
Private API call fails if it uses "params" as a variable

### ISSUE THREAD

**Issue by bloemy7** [FlutterFlow/flutterflow-issues#2085] opened 2024-01-02 08:26 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If you create an API call which has `params` as a variable, and then deploy it as a private API call, it will fail because the generate `ffPrivateApiCall` code redefines `params` as a variable, which creates a collision.

### Expected Behavior

Should be able to use `params` as a variable name in a private API call.

### Steps to Reproduce

1. Create a new API call with `params` as a variable
2. Set it to Private in the settings
3. Deploy

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

not related to widgets

### Context

I'm trying to call a third party API which uses `params` as a variable name in its call.

### Visual documentation

<img width="1167" alt="Screenshot 2024-01-02 at 9 26 41 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/1565896/7ce8bf51-a7da-4686-9b51-d9b05626b579">

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: Any
- Browser name and version: Any
- Operating system and version affected: Any
```

**Comment by hariprasadms** [comment] 2024-01-03 17:24
Hi @bloemy7 - The provided reproducible steps and screenshot lack sufficient details to understand the issue in your project. To conduct a more in-depth investigation, we require access to your project. Kindly update the issue with the project bug report code.

In my general testing of private API deployment with parameters and variables, everything appears to be functioning correctly. However, the issue might be specific to a particular endpoint. To expedite the investigation, please create a new project with detailed steps, it helps us to replicate the problem easily. Your cooperation is appreciated. Thank you.

**Comment by hariprasadms** [comment] 2024-01-05 11:44
No sufficient required details and not able to reproduce. Hence closing the issue.

**Closed by hariprasadms** 2024-01-05 11:44 UTC
Labels: status: can't reproduce

**Comment by bloemy7** [comment] 2024-05-22 07:04
Hi @hariprasadms, sorry I dropped the ball on this one.

This issue is not related to a specific endpoint. It's happening to all endpoints. I'll illustrate it better here: you will not be able to reproduce it in my project since I manually go and fix it in Google Cloud.

In every cloud function that is privately deployed to `ffPrivateCall`, the following parameter is automatically added by Flutterflow:
<img width="142" alt="Screenshot 2024-05-22 at 9 02 16 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/1565896/9f88df25-6f0f-4a4b-99a5-559c7da5244f">
it's a `params` variable, which is then used in the actual API call.

Now the problem is, if one of the parameters in an API Call in Flutterflow is _also_ called `params`, it fails, because the names collide, and this second empty one overrides the initial one!

So now every time I deploy my API I have to manually change my Google Cloud `ffPrivateCall` function as such:
<img width="262" alt="Screenshot 2024-05-22 at 9 03 47 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/1565896/7e4fe123-28bf-4d4f-b22c-b17f9aaad978">
i.e I need to rename the Flutterflow variable to `emptyParams` instead.

I hope this is clear - basically, could you use another name for this `params` instead so that it doesn't collide?
