### ISSUE TITLE
I can't check permission status on the web

### ISSUE THREAD

**Issue by maisaamadeu** [FlutterFlow/flutterflow-issues#3595] opened 2024-08-09 17:15 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When checking whether we have permission to the microphone, an exception occurs in the _permissionStatusState function with the following error message: TypedError: Failed to execute 'query' on 'Permissions': Failed to read the 'name' property from 'PermissionDescriptor': Required member é indefinite.

### Expected Behavior

The expected behavior is that when clicking on a button requesting microphone permission we can check the permission without any problems

### Steps to Reproduce

1. In the project settings, add the web platform and microphone permission.
2. Create a new page.
3. Add a button.
4. Implement a conditional check to verify microphone access.
5. Set up different alerts for both true and false cases.
6. Notice that neither alert is triggered.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTkvHbuMxOxcdb+KXuK8dGmjwsGUMfWLsr0utuGA0hfIuuELN/eOCkT1VLYteQSm1cDWajgn4z06iKv/OeL+0rMgqrRaJT/65XQRfvQn25b8WkBcywX0BBN9JRfUC/4Lu4kSJ4GPB1WVI77UylevCdG3qCf9qOYwx5e6fDbOY=

### Visual documentation

![image](https://github.com/user-attachments/assets/6d8ac7a2-3a67-461f-81bf-6efefbbc3cfd)
![image](https://github.com/user-attachments/assets/4910d84f-d67f-4ff2-9dda-8ef0373a2cc4)
![image](https://github.com/user-attachments/assets/c1e0f0cd-608b-4189-ba20-6f9254467b82)
![image](https://github.com/user-attachments/assets/c9441796-5b05-4470-b97c-15dbb54c14e5)

### Environment

```markdown
- FlutterFlow version: v4.1.82+ released August 6, 2024
- Platform: I build on Flutterflow Desktop for Web
- Browser name and version: Chrome 127.0.6533.100
- Operating system and version affected: Windows 23H2
```

**Comment by msusviela** [comment] 2024-08-09 18:05
Hi @maisaamadeu. The ENG team is already working on a fix for the microphone permission issues in web. I'm closing this issue since it's a duplicate of this:<br><br>[https://github.com/FlutterFlow/flutterflow-issues/issues/3498](https://github.com/FlutterFlow/flutterflow-issues/issues/3498)

Thanks for the report!

**Closed as not planned by msusviela** 2024-08-09 18:05 UTC
Labels: closed: duplicate
