### ISSUE TITLE
Simple condition inside Combine Conditions Bug

### ISSUE THREAD

**Issue by tothati90** [FlutterFlow/flutterflow-issues#79] opened 2022-11-01 14:29 UTC
## Expected behavior (required)
Inside Combined Conditions the simple conditions first value coming from custom function (return type: Integer) should be an Integer

## Current behavior (required)
First value is String instead of Integer
 

## To Reproduce (required)
1. Select any widget
2. Turn on the conditional visibility
3. Source: Conditions -> Combine Conditions
4. First Condition Source: Single Condition
5. First value of single condition: Custom Function --> Any function with returning type of Integer

## Context (required)
Inside Combine Conditions, when I add a Simple Condition with a first value coming from a custom function, the FlutterFlow sees it as a String value although the return type of the custom function is an Integer.

## Screenshots / recordings
https://d2y5h3osumboay.cloudfront.net/utsz3izj3k6nx047ipwds1nd5m8d

## Your environment

* Version of FlutterFlow used:  v3.0 Released on Oct. 28.
* Platform (e.g. Web, MacOS Desktop):  Web
* Browser name and version:  Chrome
* Operating system and version (desktop or mobile): Windows 11

**Comment by Pepino-GR** [comment] 2022-11-01 16:38
I cannot reproduce the issue.

**Comment by tothati90** [comment] 2022-11-02 14:05
It's weird, i just reproduced it in a completely different project.

**Comment by Pepino-GR** [comment] 2022-11-02 14:12
Can you please copy the generated code from the widget inside a comment? Like this ..
// Generated code for this Button Widget...
if ((functions.testInt() == 4) || (functions.testInt() == 5))
  FFButtonWidget(
    onPressed: () async {
      await launchUrl(Uri(
        scheme: 'tel',
        path: '',
      ));
    },...

**Comment by Pepino-GR** [comment] 2022-11-02 14:41
My Reproduction use a Button with a simple function, that returns an Int and you see in the if statement, it works

**Comment by agreaves** [comment] 2022-11-02 20:12
Hi @tothati90, my initial guess is that the custom function you have defined actually returns a type String instead of int, but it is difficult to tell without seeing the project. Please include a bug report code (you can right click the widget on the widget tree) in order for us to verify.

**Comment by tothati90** [comment] 2022-11-03 11:35
> Hi @tothati90, my initial guess is that the custom function you have defined actually returns a type String instead of int, but it is difficult to tell without seeing the project. Please include a bug report code (you can right click the widget on the widget tree) in order for us to verify.

The generated code on a Text widget:
```
if ((functions.stringtoInt('43').toString() == '') &&
    (FFAppState().latogatoId != null))
  Text(
    FFLocalizations.of(context).getText(
      'kvje2z1r' /* Color */,
    ),
    style: FlutterFlowTheme.of(context).title3,
  )
```
And this is the function I am using, but also tried different functions with integer return type.

```
import 'dart:math' as math;

int stringtoInt(String str) {
  // Add your function code here!
  return int.parse(str);
}
```

**Comment by agreaves** [comment] 2022-11-08 04:35
Hey! The issue turned out because a Number Format is being applied to the function by default. If you open the variable you'll see that this is selected. You can instead from the dropdown select "No Further Changes" and the value should now be an Integer.

I'll close this issue for the time being.

**Closed by agreaves** 2022-11-08 04:35 UTC
Labels: status: needs information, status: can't reproduce

**Comment by tothati90** [comment] 2022-11-08 11:36
@agreaves 

Ok, thank you!
