### ISSUE TITLE
Execute Callback Not Working After November 13, 2024 Update

### ISSUE THREAD

**Issue by absolutitecinfo** [FlutterFlow/flutterflow-issues#4911] opened 2024-11-16 02:26 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After the update released on November 13, 2024, the "Execute Callback" functionality stops working when used in popups. This issue occurs when trying to execute a callback to refresh a list in real-time after updating a record. The process freezes at the callback execution step.

### Expected Behavior

The callback should execute successfully after updating the record and closing the popup, allowing the list to refresh in real-time without issues.

### Steps to Reproduce

1. Create a page with a list of records.
2. Add a button or icon to open a popup.
3. Inside the popup, add a form to update the selected record.
4. Configure the save button inside the popup to:
      - Update the record,
      - Execute the callback,
      - Close the popup.
5. Save the changes and return to the list page.

Expected: The callback refreshes the list in real-time.
Actual: The process freezes when attempting to execute the callback.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40ifiCuLJ6m7hC+qiILfdFnj4hQTI2W5A3u9h7aCgoIYyuOpl/evWkNhFWZ9/hS1FMJ0Smmngy097tj/LpIcFfHxeefqpFwatqSg/LXXOja5OBBYe0f398BZ5XCBXA0p+7pBR+IsRYc0YC3FyUNvPLYHfcCZzEImdISq/LZO4=

### Visual documentation

![image](https://github.com/user-attachments/assets/580c1e41-edb1-4e22-8208-b56391ed87c3)

### Environment

```markdown
- FlutterFlow version: v5.0.11+ released November 13, 2024
- Platform: Any
- Browser name and version: Any
- Operating system and version affected: all
```

**Comment by paulperez-dev** [comment] 2024-11-18 16:07
Hi @absoluteitecinfo, I’m closing this issue as it’s a duplicate of your most recent report, which also includes this behavior.

**Closed as not planned by paulperez-dev** 2024-11-18 16:07 UTC
Labels: status: needs triage, regression
