### ISSUE TITLE
Dynamic Links always route to home page on Android App

### ISSUE THREAD

**Issue by hadronlink** [FlutterFlow/flutterflow-issues#2600] opened 2024-03-26 16:39 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I click on Dynamic Link in the IOS version it works perfectly well, but in the Android version I am always redirected to the app's home page, when I should be redirected to other pages in the app

### Expected Behavior

I believe Dynamic Links should redirect to specific app pages other than the home page

### Steps to Reproduce

1. I enabled Firebase Dynamic Links.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/121562535/6201821a-53a6-4c96-9dd6-0e589eee480c)

2. I created a "Generate Current Page Link" action and shared "Current Page Link". I tried with short and long link.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/121562535/12c3759f-a3a4-444c-848e-f4ac688005ab)

3. Clicking on the shared link works perfectly for IOS but does not work well for Android. The problem is that on Android it always redirects to the app's home page, not to the page to which the link was created. Using FlutterDevTools I got these logs when I click on the link "https://hadronlink.page.link/mqxL":

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/121562535/ff3fb898-aa70-44f4-b419-ec8b7ef5f2f7)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gkPLl24ZOxLhD1aqNa+9VlWEXC218aIc0ttx+bw4bJJCvOpYUec/6P1BuOcvjY1FPfU22p14ep8LGk+OeKfUCCzeZbphAz5BueDzMTkS6V6WTF7q3PnwnI/hgfGaF3KaFhB15APZfSUIMwFyEPequTgPUGJjzIWo4Sq/LZO4=

### Context

This issue is preventing me from redirecting app users to the correct page on the Android system.

### Visual documentation

I included images and logs in steps to reproduce.

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.33+
- Platform: Android
- Browser name and version:
- Operating system and version affected:
```

**Comment by FillipeSampaio** [comment] 2024-04-05 15:45
The issue persists and impacts our app. Any answers?

**Comment by paulperez-dev** [comment] 2024-04-26 03:19
Hi @hadronlink, sorry for the late response! Thanks for submitting the issue. I was not able to reproduce the issue from a blank project. 

I've taken a look at your project, but with a lot going on, it's challenging to pinpoint the issue. Given the nature of the problem you're highlighting, we need a blank project with the issue steps set up in it. Without these details, it might be a bit challenging for us to investigate the issue.

<br>If the issue is already resolved for you, please feel free to close the issue. Thanks!

**Comment by rzambroni** [comment] 2024-05-01 03:25
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Closed** 2024-05-01 03:24 UTC
Labels: waiting for user response
