### ISSUE TITLE
blur widget out bleeds container with clip content and rounded edges

### ISSUE THREAD

**Issue by Isxariifshe** [FlutterFlow/flutterflow-issues#122] opened 2022-11-12 17:13 UTC
when you wrap a blur widget with a backdrop in a container it should be contained in that container and never cross it, this issue is now around a week by the time I'm writing this report. the style I'm looking for (frosted glass/glassmorphism) can be sometimes observed in the UI builder but when you run the project or view the code, the issue persists, even another page that I built a month ago with a glassmorphism doesn't have that issue.

![issue jpg](https://user-images.githubusercontent.com/101445669/201486176-324ceb53-65ff-4213-8d1d-c7348e7d314d.jpg)

**Comment by hariprasadms** [comment] 2022-11-14 11:37
Hi @Isxariifshe - I can reproduce this observation. Also, I can see that other user have reported the smilier issue. Hence, i have marked this as a bug. However, at the moment, blur widget got limited properties in FF. I hope you have tried all the combinations of properties to fit your design. Let's see what FF team can suggest to handle this situation. Thanks

**Comment by wenkaifan0720** [comment] 2022-11-15 03:11
I tried to recreate the issue, as shown in this project: https://app.flutterflow.io/project/flutterflow-issue-122-e574eb. The backdrop looks normal in the UI builder and in test/run mode. However in previous mode the clip does not seem to be happening. This is quite a bizarre bug. 

Just to make sure, what I created in this project is what you intend for this issue, right? @Isxariifshe

**Comment by katherineqian** [comment] 2022-11-15 06:39
Hi @Isxariifshe, is this a duplicate of https://github.com/FlutterFlow/flutterflow-issues/issues/78? If so, it's fixed. Otherwise, can you please clarify what is different between this and the previous bug? Or is this a regression?

**Closed** 2022-11-15 06:47 UTC
Labels: type: bug, status: confirmed

**Comment by Isxariifshe** [comment] 2023-01-16 19:26
This problem still persists, in case you forget it
