### ISSUE TITLE
Execution failed for task ':package_info_plus:compileDebugJavaWithJavac'

### ISSUE THREAD

**Issue by Parth-fineapple** [FlutterFlow/flutterflow-issues#3554] opened 2024-08-05 08:01 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I trying to run local run and getting this error ->

`Launching lib/main.dart on 22111317I in debug mode...
Upgrading build.gradle
Running Gradle task 'assembleDebug'...                          

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':package_info_plus:compileDebugJavaWithJavac'.
> error: invalid source release: 17

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s
Running Gradle task 'assembleDebug'...                             20.8s
Error: Gradle task assembleDebug failed with exit code 1`

I am not able to run the app on my systems (MacBook m1 & Windows Hp Pavillion 15 gaming)

### Expected Behavior

The app should run on my local device. 
I tried using other laptop (my own, hp pavillion 15 gaming) but there also it failed.
But surprisingly it is running in other two MacBook without any issue. 
We are on a team plan and my other colleagues can run the app but I am not able to. 
I think my flutterflow account has some issue, it's not a system issue I feel?

### Steps to Reproduce

1) Install Flutterflow mac app
2) Install local run
3) Select your local device and Run 'local run'

-I once used 'package_info_plus' in custom action but later deleted it and since then I am not able to run local run.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

None

### Visual documentation

<img width="798" alt="Screenshot 2024-08-03 at 12 36 09 AM" src="https://github.com/user-attachments/assets/0ba87f78-5780-414d-aba0-908d47739908">

### Environment

```markdown
- FlutterFlow version: v4.1.79
- Platform: MacOS
- Browser name and version: -
- Operating system and version affected: MacOS Sonoma (v14.5)
```

### Additional Information

Not resolved - https://community.flutterflow.io/ask-the-community/post/execution-failed-for-task-package-info-plus-compiledebugjavawithjavac-YBGlP2xKwpLBKie

Resolved - https://community.flutterflow.io/ask-the-community/post/execution-failed-for-task-package-info-plus-compilereleasejavawithjavac-lx9rOtUbT6bNb4f

Check this out. I am facing the same issue as them.

**Comment by Alezanello** [comment] 2024-08-05 13:27
Hello!

This issue is a duplicate of [Issue #3293](https://github.com/FlutterFlow/flutterflow-issues/issues/3293).

Please refer to that issue for possible solutions or suggestions to fix this problem. <br><br>I’m going to close this issue as a duplicate.

Best regards,<br>Azanello

**Closed as not planned by Alezanello** 2024-08-05 13:27 UTC
