### ISSUE TITLE
TextField auto-focusing on back navigation despite autofocus off

### ISSUE THREAD

**Issue by max-h-silverman** [FlutterFlow/flutterflow-issues#3612] opened 2024-08-12 22:33 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If you interact with the text field before clicking on an item on the page that takes you to a details screen, when you navigate back the text field is autofocused

### Expected Behavior

Text field should not autofocus as autofocus is set to off

### Steps to Reproduce

1. Login (flutterflow/flutterflow)
2. enter "lm" in search text field
3. click the first item in the list view
4. click back arrow

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ki87lx4lgoddA1rrtbcExvCo4H245TL03t9VxSUgrIrbyPJkUacmkXExWXteodHNHKEWJ+UIDwfTzvvHxK8cVNTGabYRFz80IWgn/XnG/aoSyEs6edHFfL5pNFX6w0Z63rAolPbdaLFYS3EOYPenKVnHbNOL6Zwh9f6PHaOI=

### Visual documentation

https://github.com/user-attachments/assets/09918093-662e-4842-be87-4c691830deda

### Environment

```markdown
- FlutterFlow version: 4.1.82
- Platform: Mac
- Browser name and version: Chrome latest
- Operating system and version affected: OSX Monterrey
```

**Comment by Alezanello** [comment] 2024-08-13 21:45
Hello!

I tried to replicate the behavior you described in the project, but I wasn’t able to reproduce it. The text field doesn't seem to gain focus automatically after going back.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/d1fff4bb-32c4-4404-a24b-8f8512c7695d/f74036b8-0f49-4062-bf50-92d6cb1a7d14?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kMWZmZjRiYi0zMmM0LTQ0MDQtYTI0Yi04Zjg1MTJjNzY5NWQvZjc0MDM2YjgtMGY0OS00MDYyLWJmNTAtOTJkNmNiMWE3ZDE0IiwiaWF0IjoxNzIzNTg1NTUzLCJleHAiOjMzMjk0MTQ1NTUzfQ.e_daM0aaj_vqgGkkUgJZ5oUBwE53IfaqciRTnXuA8No " alt="autofocus.gif" width="532" height="368" />

**Comment by max-h-silverman** [comment] 2024-08-13 21:53
@Alezanello Are you testing this on web or on a device? I just replicated in another test project I just created. It's definitely an issue.

**Comment by max-h-silverman** [comment] 2024-08-13 22:48
https://app.flutterflow.io/project/print-o8d6ke

**Comment by Alezanello** [comment] 2024-08-14 11:00
I tested in on Web, i'll try in device in a few minutes!

**Comment by max-h-silverman** [comment] 2024-08-21 20:29
@Alezanello were you able to test this on a device?

**Comment by bdonovan858** [comment] 2024-08-30 21:25
I can confirm I'm experiencing the same bug on iOS and can reproduce the issue. Any status on when this may be fixed? Thank you.

**Comment by max-h-silverman** [comment] 2024-09-01 23:18
@Alezanello Please provide an update on this bug. Thanks.

**Comment by bdonovan858** [comment] 2024-09-02 00:01
To add further context that might help the dev team address this issue: I’ve noticed that when using a custom widget, I've only tested with a custom linkify text widget, the bug seems to behave differently. Specifically, if you dismiss the keyboard by tapping on the scaffold and happen to tap on a custom widget (not a native FlutterFlow widget), the issue resolves itself after navigating to another page and back, or by opening and dismissing a bottom sheet. However, if the user dismisses the keyboard by tapping on ANY other region in scaffold, the issue persists. This behavior is clearly a bug and significantly impacts the user experience. 

I hope this can be prioritized for a fix, as it was not present in FlutterFlow releases from about four weeks ago. 

Thanks!

**Comment by bdonovan858** [comment] 2024-09-13 17:33
Hi @Alezanello and @paulperez-dev - I know you folks are busy, but I wanted to check in to see if there's a timeline for this fix. It seems like a fairly reproducible bug, so hopefully, it’s just a quick tweak in the source code related to the autofocus persistence. Thanks so much for all your hard work - we really appreciate it!

**Comment by xfanwu** [comment] 2024-09-15 19:30
I had exactly the same issue and now I have to change the "navigate back" action to "navigate to" as a workaround.

**Comment by bdonovan858** [comment] 2024-09-15 20:24
> I had exactly the same issue and now I have to change the "navigate back" action to "navigate to" as a workaround. 

@xfanwu - Thanks for the suggestion! It’s helpful to know that this issue persistent across users. However, the issue with changing the navigating back action to a navigating to action is that it doesn’t solve the problem of the bottom sheet’s dismiss triggering autofocus too. Additionally, in my use case, I need the back button behavior to be dynamic, so using a fixed “navigate to” action won’t work. Hopefully, the team can address this soon!

**Comment by Alezanello** [comment] 2024-09-19 19:16
Hello everyone, and apologies for the delayed response. I've been working on a potential workaround for you while the team addresses the issue.

Could you try triggering this custom action after navigating back or closing the bottom sheets?

Make sure to enable the "Include BuildContext" option in the custom action settings.

```dart
Future triggerUnfocus(BuildContext context) async { 
  FocusScope.of(context).unfocus();
}
```

Let me know if this helps!

**Comment by max-h-silverman** [comment] 2024-09-19 19:58
@Alezanello Thanks for this. It works for back navigation, but there is one case in which it doesn't: If you navigate to a screen and then navigate from there using the 'replace route' option, the on-screen keyboard shows briefly. I tried using this custom action before that 2nd navigation but it didn't make a difference. Thanks again for getting back on this.

**Comment by max-h-silverman** [comment] 2024-09-19 20:10
@Alezanello Sorry, I was able to get it to work for this case as well. Looking forward to the permanent fix. Thanks!

**Comment by bdonovan858** [comment] 2024-09-19 21:32
Echoing @max-h-silverman - thanks @Alezanello for the workaround! Really appreciate it.

**Comment by bdonovan858** [comment] 2024-09-25 16:13
@Alezanello - do you have a workaround for this when you dismiss the bottom sheet via drag or tapping on the scrim region? The unfocus trigger doesn't fire in those scenarios. Thanks!

**Comment by max-h-silverman** [comment] 2024-10-15 01:52
@Alezanello Any update on getting a proper fix for this?

**Comment by bdonovan858** [comment] 2024-10-21 20:43
@Alezanello just checking back in on this? Thanks.

**Comment by max-h-silverman** [comment] 2024-11-11 04:09
@Alezanello Can we please get an update on whether this is being worked on/planned? Or at minimum an acknowledgement that we've been asking for updates?

**Comment by Alezanello** [comment] 2024-11-19 14:03
Hello Everyone,

Apologies for the delayed response. Over the past few weeks, we've implemented several updates that have modified certain behaviors. Personally, I can no longer reproduce the issue.

If anyone is still experiencing it, please provide either a video or a new blank project with only the necessary steps to reproduce the problem so that we can address it effectively.

Thank you for your cooperation!

**Comment by bdonovan858** [comment] 2024-11-22 21:09
@Alezanello 

This issue persists and is still reproducible. I’ve attached a video demonstrating the behavior, specifically with a bottom sheet. The issue occurs on both an emulator and a physical iPhone.

Here are the steps to reproduce the issue.

1. Add a TextField widget to a page in your app. Ensure autofocus is set to false.
2. Add a button to the same page with an action that triggers the display of a bottom sheet.
3. Navigate to the page containing the TextField and the button.
4. Tap into the TextField to give it focus.
5. Tap outside the TextField to dismiss the keyboard and remove focus.
6. Tap the button to display the bottom sheet.
7. Dismiss the bottom sheet by tapping on the scrim (outside area of the bottom sheet).

Observed Behavior:
The bottom sheet dismisses, and the TextField unexpectedly regains focus.

Expected Behavior
The TextField should not regain focus after dismissing the bottom sheet.

Note this behavior was not present prior to a release in late August 2024.

https://github.com/user-attachments/assets/d8528a7c-ba50-4b0f-910d-93e7f7c36125

**Comment by finallyfit** [comment] 2024-11-23 09:13
Thanks for providing the video @bdonovan858

Let me add that this isn't exclusive to bottom sheets — the same thing occurs with custom dialogues as well.

**Comment by nixeton** [comment] 2024-11-29 13:10
I am experiencing the same issue described by @bdonovan858. I tried the temporary solution suggested by @Alezanello, but it did not resolve the issue for me.

A temp solution that works for me is to unfocus from `FocusManager` after triggering dismiss for the Bottom Sheet and back navigation:

```dart
Future triggerUnfocus() async {
  FocusManager.instance.primaryFocus?.unfocus();
}
```

At least it works for me.

**Closed as completed** 2024-12-11 17:23 UTC
Labels: status: confirmed, Bug

**Comment by finallyfit** [comment] 2024-12-11 17:28
@nixeton I'm assuming this is a custom action? Where are you triggering it?

**Comment by MohamedNoordin** [comment] 2024-12-23 17:21
I solved this issue by unfocusing the primary focused widget in the `build` method of the `Widget` that shows up after interacting with the text field. For my case, it was the app navigation drawer. It could be also a dialog or a bottom sheet.  
```WidgetsBinding.instance.focusManager.primaryFocus?.unfocus();```  
This way, the text field gets unfocused after transitioning from a widget to another. This should be the original behavior for the text field.

**Comment by finallyfit** [comment] 2024-12-23 17:25
@MohamedNoordin did you do edit the code manually or were you able to do this through the FlutterFlow UI?

**Comment by bdonovan858** [comment] 2024-12-23 17:45
> @MohamedNoordin did you do edit the code manually or were you able to do this through the FlutterFlow UI?

Pretty sure this got patched in the most recent FF update

**Comment by finallyfit** [comment] 2024-12-23 18:18
Thanks @bdonovan858 — I just checked my latest build and you're right, this has indeed been fixed in the latest FF update. Thanks for the heads up!
