### ISSUE TITLE
Datatable does not update on rebuild component

### ISSUE THREAD

**Issue by bigbworld** [FlutterFlow/flutterflow-issues#3289] opened 2024-07-01 03:35 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

With the data table rebuilding the component or when changing the data associated(page state) to the table, it does not refresh.
I have added the last item to the title and gets updated on page update/refresh, but not the table.

### Expected Behavior

Table should update on changes.

### Steps to Reproduce

Create new datatable in a page
Create page state with a list(used supabase row list) and set the data table to generate dynamically generate children from it.
Make changes to the page state and then set refresh current page
Run the build and and trigger page state change
Table will not update/refresh (rarely gets updated, usually if the table is empty and we add item to the list the table gets updated otherwise it doesn't)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4shc7lvJVgoctH176JK+5R/GE4Njt6ULgSscgYYxAjfbbrB4YUY/fTVEpoTcOHd2xEOlmY8XMxw+zGv97pEu09Piiqbos//89QbQmXLU25MoSoPpbpYnx9M+5XGUOHzbSZkBF4CONtckIswEOUJ9mtHwHdNICwDGwvRP/9WbvOjkqRLiLCXn0Jg1ZSfCvr

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/173977991/815c25fd-80fd-4aef-9c0b-05ee244b9210)

### Environment

```markdown
- FlutterFlow version: 1.4.64
- Platform: Web/Local Run
- Browser name and version: Chrome
- Operating system and version affected: Windows 11
```

**Comment by Alezanello** [comment] 2024-07-02 12:32
Hey @bigbworld 

Thank you for your report. I'm sorry you're experiencing this issue. While I was unable to reproduce it on a blank project, it is replicable on your specific project. This leads me to believe it's a project-specific issue.

Our support team is best equipped to help resolve this. Could you please follow up with them either via email at support@flutterflow.io or using the in-app chat inside FlutterFlow?

I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects.

If you manage to reproduce this issue on a blank project as well, please let us know and provide the bug report code for that project.

Thank you so much!

Best regards,
Azanello

**Closed as not planned** 2024-07-02 12:34 UTC
Labels: closed : project specific
