### ISSUE TITLE
The Widgets falling below the expanded area of "Expandable Floating Action Button" become inaccessible

### ISSUE THREAD

**Issue by saketkrb2b** [FlutterFlow/flutterflow-issues#945] opened 2023-05-29 07:43 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I implemented an expandable floating action bar as per the tutorial https://blog.flutterflow.io/creating-an-expandable-button/
This works perfectly fine. The animations are perfect. However, even when the OptionsContainer is not expanded, if I click on the listview item in the background, it still triggers the action associated with an option in OptionsContainer. So, as a user, if I want to click on the listview item which overlaps with the expanded options, it doesn't give me the desired action. I should be able to select the listview items when the options are not visible on screen.

Whether the expandable FAB is open or closed, does not matter, the area of the options container is not accessible in the listview behind it

https://github.com/FlutterFlow/flutterflow-issues/assets/91278120/afa534c5-7a0f-4540-b425-ae3983e02099

### Expected Behavior

The elements behind the expanded area should be accessible when the the FAB is not in expanded state. 

### Steps to Reproduce

We copied the widget from the official marketplace project titled "Expandable Button".
https://app.flutterflow.io/marketplace/item/q1f1UKfYZkkHNzxAr743

<img width="887" alt="Screenshot 2023-05-29 at 1 06 17 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/91278120/d6e7bab8-4d2f-49a1-b3c7-5702906f872b">

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ShfLqw5dOtbxa1s+JbflahjovIjslRY00lu16EBcdGK2uOrQDXOmmSFRuQtOmTFc2PmGanmEz0/vHkdzIN/Y5Ok6afZxc1aVcFAKVQniQb82aELqJdnYnQdpKCnKd0LTYvyUlHOptS1o/1DmEB/OASnXDQYzzIjEjDf2kOqLNo3PuQ0SLb3kNh1JWeC/v

### Context

I want to show a list of customers added by the user on the page. For the user to be able to add new customers either from his phonebook or manually, I need an expandable floating action button. 

### Visual documentation

Attaching the video showing the FAB behavior.

https://github.com/FlutterFlow/flutterflow-issues/assets/91278120/4e1507c6-afb0-4586-a5ae-494966be2148

### Environment

```markdown
- FlutterFlow version: 3.7.12
- Platform: Android
- Browser name and version: Chrome
- Operating system and version affected: Android
```

**Comment by hariprasadms** [comment] 2023-05-30 15:28
Hi @saketkrb2b - Thanks for posting the issue. To investigate this issue, we need a blank project setup with reproduce the issue in the project. Share the project bug report code once it is ready. Thanks

**Comment by wenkaifan0720** [comment] 2023-07-05 20:46
Hi @saketkrb2b. Unfortunately the blog you saw was more for teaching people how to design and animate such a popup menu. The menu would block things behind it when its invisible. But don't worry, you can achieve your desired behavior with one of our recent feature called custom dialog. The idea is that you make the menu into a component, and when you click on the floating action button, you trigger the open custom dialog action and pass in the menu component. Let me know if you have further questions.

Since this is not a bug on our end, I would close this issue for now. Thank you.

**Closed by wenkaifan0720** 2023-07-05 20:46 UTC
Labels: closed: not a bug, status: not a bug
