### ISSUE TITLE
"Run App" fails when using custom DataType

### ISSUE THREAD

**Issue by robin-torwell** [FlutterFlow/flutterflow-issues#237] opened 2022-12-16 15:56 UTC
## Expected behavior (required)
When using a custom DataType in a widget, the Test Mode/Run App in browser feature should work.

## Current behavior (required)
The build fails.

<img width="720" alt="Screenshot 2022-12-16 at 16 44 51" src="https://user-images.githubusercontent.com/120737392/208135617-d508b855-5f92-49e8-98b0-2a7fc4af8459.png">

## To Reproduce (required)
1. Create a DataType
2. Write a Custom Action, which return a variable of that Data Type
3. Use that action in "On Page Load" of a widget
4. Use the action output of type DataType in that widget
5. Run App in Test Mode

### Bug Report Code

IT4WisrlvJNPmMBE7c/QdcFV+SAROWU7U7g7l8N+EAIgfJjsOqYPXfikSEpWZ9+kTHxcL06Znn0ew63Ik/PIA+UqCEiBRYBG+qhiZQ6UXmCXR82OCoeCZHJ6GdwGSSDy

## Context (required)

I'm eager to show the customer the app without the delay of an App Store deployment.

## Screenshots / recordings
<img width="646" alt="Screenshot 2022-12-16 at 16 52 44" src="https://user-images.githubusercontent.com/120737392/208137079-0b84ab0c-a005-4274-98ca-df32572f8d42.png">

<img width="601" alt="Screenshot 2022-12-16 at 16 53 18" src="https://user-images.githubusercontent.com/120737392/208137212-d82c446f-4fc4-48cf-97b9-472912aa3e49.png">

## Your environment

* Version of FlutterFlow used: 
<img width="262" alt="Screenshot 2022-12-16 at 16 51 51" src="https://user-images.githubusercontent.com/120737392/208136909-b47cf466-758a-492f-a91b-3ee892d4b952.png">

* Platform (e.g. Web, MacOS Desktop):  MacOS Desktop and Web
* Browser name and version: Chrome Version 108.0.5359.94 (Official Build) (x86_64)
* Operating system and version (desktop or mobile): MacBook, MacOS Ventura 13.0.1

**Comment by robin-torwell** [comment] 2022-12-21 09:46
Any news on this?

**Comment by agreaves** [comment] 2022-12-28 04:41
Closing as a duplicate of #238 which has been recently fixed.

**Closed by agreaves** 2022-12-28 04:41 UTC
Labels: status: needs triage
