### ISSUE TITLE
Gray out when set the Property of Custom widget

### ISSUE THREAD

**Issue by idea-garage** [FlutterFlow/flutterflow-issues#2082] opened 2024-01-01 14:36 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I set the Property of Custom widget, specific properties are gray out and not able to change.
And, setting one property from variable cause unexpected set another property, which have different data type.

### Expected Behavior

able to set property

### Steps to Reproduce

1. Create a simple Custom Widget
2. Set property of the custom widget

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4whvLl5Yp1m7QD+KryKMdKniYXGDskR4I7lcJxSis8JJToPLAUZ8zBM05vZrygSnx2O2GZkj4K1vfqiIX9KvVfJUirc60++pNuVhfgIHOiVYSSCrizfW1QMNNgJ2a04J7U2RJ4NtZYcmwZ22CYOevKYBTbNb7qIjMvLeW1KdeK2SrDX1iXc2URm05KZDPz

### Context

Can't set widget property

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/ac05273f-8edb-42aa-b988-79ba0c889fa6/871758ee-c95a-48f9-83dd-38615c345c10?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hYzA1MjczZi04ZWRiLTQyYWEtYjk4OC03OWJhMGM4ODlmYTYvODcxNzU4ZWUtYzk1YS00OGY5LTgzZGQtMzg2MTVjMzQ1YzEwIiwiaWF0IjoxNzA3MTgxODY3LCJleHAiOjMzMjc3NzQxODY3fQ.qN4f3zx4BWb-NyEcxa8kMBR_0UaBwRzUKUKAzUzFEy8 "=287x")

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: V4.0
- Platform:Web
- Browser name and version:Chrome 120.0.6099.129（Official Build） （arm64）
- Operating system and version affected: macOS Sonoma 14.1.2
```

**Comment by hariprasadms** [comment] 2024-01-03 16:10
Hi @idea-garage - Thank you for submitting the issue. After reviewing your project and custom widget, I couldn't identify the grey area. Additionally, the project compiled and ran successfully in both test and run modes.

https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/ca813951-234b-43fd-bf2e-11a16fff31a3

I hope the problem is resolved on your end as well. Kindly verify and confirm. Appreciate your cooperation. Thank you.

**Comment by agreaves** [comment] 2024-01-03 16:43
Hey @idea-garage! I haven't been able to reproduce this issue either, but it does look real from the screenshots. Do you have any reproducible steps? Hopefully it's just a weird edge case / one time thing, in which case if you're not able to reproduce I'll just close it for now and keep it in mind in case anyone else experiences the same thing.

**Comment by hariprasadms** [comment] 2024-01-05 11:51
Hi @idea-garage - I trust you are no longer experiencing the reported issue. There were recent updates in FF, so please try with the new updates to see if the issue has been resolved for you. I will close the issue for now, but feel free to reopen it if the same behaviour persists on your end. Thank you.

**Closed** 2024-01-05 11:52 UTC
Labels: status: can't reproduce, status: not a bug

**Comment by idea-garage** [comment] 2024-01-05 14:58
Thanks anyway. Currently the problem can't reproduce. I'll report if I see same case.
