### ISSUE TITLE
VideoPlayer widget not working - keeps loading forever

### ISSUE THREAD

**Issue by Zack1010OP** [FlutterFlow/flutterflow-issues#427] opened 2023-01-31 20:46 UTC
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
i put a static YouTube video link it SHOULD play the video
i put an assets 1 second gif animation it SHOULD play the video

## Current behavior (required)
i put a static YouTube video link it doesn't work
i put an assets 1 second gif animation it doesn't work.

## To Reproduce (required)

1) create new page
2) put 1 widget VideoPlayer on page
3) set VideoPlayer to 1 second gif animation Asset
4) you'll see it load forever

### Bug Report Code (required, generate from Widget Tree)
IT8kzsnf05dNrsRE1rruccBv+SAXHGk7UIIv0NZ+FEggGL7yEoouZM/STFhuYsyHeFZiIlmZ8Voy096KhuztBMIBIReCGdRz/qlxQx7iRTqiaJ+aCau8eXBRP8BPG0yy4aWzph1AAOszFxxchgPKRw==

## Your environment

* Version of FlutterFlow used: 3.3.4
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by bulgariamitko** [comment] 2023-01-31 22:40
I am not sure you can set the video player to a GIF animation and especially if it's only 1 sec. It is better to use Lottie animation if you can?

**Comment by DavidWalters123** [comment] 2023-02-01 09:19
![video](https://user-images.githubusercontent.com/28622235/216001906-a918bc07-b5f3-43f4-953c-3df03bbe8d3f.gif)

**Comment by bulgariamitko** [comment] 2023-02-01 11:24
This usually works. Can you try to add the widget without drawing it just to see if you get the same error?

**Comment by bulgariamitko** [comment] 2023-02-21 17:51
I am closing this as the user was not active in the last 2 weeks, but please feel free to open it again if you still have this issue.

**Comment by DavidWalters123** [comment] 2023-05-04 06:41
@bulgariamitko , Im still having this issue as others are too. I added the widget without drawing and get the error Video Player misconfigured. Id appreciate your support.

**Comment by DavidWalters123** [comment] 2023-05-05 07:57
![Video](https://user-images.githubusercontent.com/28622235/236405005-279d1a75-08c5-4be4-9ac3-06570d5e7775.gif)
![Video2](https://user-images.githubusercontent.com/28622235/236405227-59d91985-b5c2-4430-88dd-31cc2a86046b.gif)

**Comment by bulgariamitko** [comment] 2023-05-07 17:22
I will re-open this issue so the FF team can have a look as well.

**Comment by shelpert** [comment] 2023-05-09 01:03
Hi, the `VideoPlayer` widget will not play a `gif` since it's actually a type of image, so you should use the `Image` widget instead. As for a Youtube link, you should be using the `YoutubePlayer` instead. The `VideoPlayer` widget is for playing video files, such as those with `mp4` or `mpeg` extensions.

**Comment by DavidWalters123** [comment] 2023-05-09 09:17
Hi Shelpert. Im not sure where you get "Gif" from, but in the screen recordings you can see that the file used is a .mp4. There is no gif to be seen anywhere. Also not a Youtube video. I am not the only one having this issue as you can see here: https://community.flutterflow.io/c/discuss-and-get-help/video-player-55fe73#comment_wrapper_15318948 - please reopen.

**Comment by shelpert** [comment] 2023-05-09 16:56
Apologies, that is what was specified in the original issue. I will need more than the screenshots in order to debug the issue you are facing, as I am not able to reproduce it from scratch. Please post a bug report code and I will take a look!

**Comment by DavidWalters123** [comment] 2023-05-09 17:28
ITFfzsnf5Ylgobhc0ISJae5siWM6KV8cTIMziNZ+exUbfaL1Buwxd+POblhpUvW+aVNcBEyWin0Cw6H8ht/hGPQ6Mk6uY486/892cTzee2i6V4TXPpaoRmtCM9lbf2Ks0bS4niJ7BLZqcV5i21OuO+i9YCjDIuu/Zwh9f6PHaOI=

thanks

**Comment by shelpert** [comment] 2023-05-09 20:47
Hi @DavidWalters123,
It seems that this is an issue on the Mac desktop version of Flutterflow. Can you confirm that you are using the desktop version? Are you also experiencing this issue on the web version?

**Comment by DavidWalters123** [comment] 2023-05-10 05:55
Yes, correct. Im using Mac Desktop and it works via Browser. Thanks!

**Comment by shelpert** [comment] 2023-05-10 18:36
Great! We offer our MacOS desktop app as a convenience to our users, but we don't officially support it. Since this works on web, I will note that it doesn't on desktop for future reference, but I will close this issue now.

**Closed by shelpert** 2023-05-10 18:36 UTC
Labels: status: wontfix
