### ISSUE TITLE
Rebuilding page does not clear text field state

### ISSUE THREAD

**Issue by DanielEdrisian** [FlutterFlow/flutterflow-issues#833] opened 2023-05-01 18:17 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When you rebuild a page that contains a text field, the "initial value" of the text field remains the same. For example, if you are loading the initial text of a text field from a firebase document, and then you change the document, the text field still shows the old text associated with the previous document.

### Expected Behavior

It is expected that a text field should clear its state when the page state is rebuilt and update with new information.

### Steps to Reproduce

1. Make a column
2. Query a collection that includes a text property
3. Add a button in the column that sets a page state variable "selectedReference" to the selected reference of the button
4. Add a container
5. Set its query to get the document from reference "selectedReference"
6. Add a text field to the container, and set its "initial value" to be that text property in the retrieved document
7. Now run, and click on the different buttons and see that the text field value does not change

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

na

### Context

na

### Visual documentation

na

### Environment

```markdown
- FlutterFlow version: latest
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: Mac
```

**Comment by hariprasadms** [comment] 2023-05-02 12:50
Hi @DanielEdrisian - Thanks for posting the issue. I have investigate the issue and I can say that it is working as expected. As per Flutter textfields and forms default behaviour, initial value can't be updated based on re building the text form widget. Initial value is just an initial value and can't be changed. 

As a work around, I can say try to use hint text to achieve what you are expecting. I hope that works for you. 

It is not a bug. Hence, closing the issue.

**Closed by hariprasadms** 2023-05-02 12:50 UTC
Labels: status: needs triage

**Comment by DanielEdrisian** [comment] 2023-05-03 03:13
Hint text? How do I use that as a workaround?
