### ISSUE TITLE
Glitch with the controll PageView navigation action

### ISSUE THREAD

**Issue by kicsijohn** [FlutterFlow/flutterflow-issues#1129] opened 2023-07-17 10:58 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If I set a controll pageview action (swipe to next) and if I swipe back in the previous page a strange glitch happens: the action flow starts with the swipe next action

### Expected Behavior

I want that if I swipe back, the navigate next action execute the last time not the first time

### Steps to Reproduce

1. Create a pageview
2. add 5-6 pages
3. add an on page load action flow to the page: wait 2sec and control pageview - next
4. add an on pageview swipe action flow to the pageview widget: wait 2sec and control pageview - next
5. observe that is execute as planned BUT if you navigate back strange things starts to happen. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gls/l6otIsdtK0LruYO9WhiUXJW5/a5c0sNobbxAjIoDoPJkUac74YRFWON/gTX9bKEWLq3Md+vTwuN7qVvknOROVQIRR+ap+SAyVXXy/aoSXPLmwRXdSO8dhCFyY0raW2x4lXddiSCUs32b2evKvYDXDQLH6Zwh9f6PHaOI=

### Context

I want to create an user journey: open a page with pageview, play a sound then navigate to the next pageview page if the sound end then play a new sound and again and again. And I want to reset the action and start the action flow again if the user swipes back to the previous page

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/45784821/31e5a088-2db0-4b1a-ac06-49735331314f

### Environment

```markdown
- FlutterFlow version: 1.1.89 
- Platform: MacOs
- Browser name and version: Chrome
- Operating system and version affected: Mac Ventura
```

**Comment by hariprasadms** [comment] 2023-07-17 11:08
Hi @kicsijohn - Thanks for posting the issue. Please explain exact issue you are seeing at _step 5 - observe that is execute as planned BUT if you navigate back strange things starts to happen.

Answer these questions as well.

1. Is this same thing happening in iOS. If yes, provide a quick video showing the issue?
2. Is this same thing happening in Android devices. If yes, provide a quick video showing the issue?

**Comment by kicsijohn** [comment] 2023-07-17 12:17
> Hi @kicsijohn - Thanks for posting the issue. Please explain exact issue you are seeing at _step 5 - observe that is execute as planned BUT if you navigate back strange things starts to happen.

Hi @hariprasadms, I mean the action flow (wait 3 sec, then swipe to the next page) executes fine until I swipe back on the pageview. Then there is simultaneous swipe actions starts to happens at once


> 
> Answer these questions as well.
> 
> 1. Is this same thing happening in iOS. If yes, provide a quick video showing the issue?
> 2. Is this same thing happening in Android devices. If yes, provide a quick video showing the issue?

Yes its happening on both system:
Android:
https://github.com/FlutterFlow/flutterflow-issues/assets/45784821/6c679478-71da-4ab6-9b34-a4db0320e015

iOS:
https://github.com/FlutterFlow/flutterflow-issues/assets/45784821/e6ac50fd-6b7d-4c17-829e-2bcccdb6528e

**Comment by kicsijohn** [comment] 2023-07-17 21:41
If I jump to a specific page, the app executes all the swiping actions at once that were before the page I jumped to.

https://github.com/FlutterFlow/flutterflow-issues/assets/45784821/9e0e3dac-ef1a-4af9-86f6-1575c98f98a7

**Comment by hariprasadms** [comment] 2023-09-20 15:52
Hi @kicsijohn - Sorry for being late responding on the issue. I looked at your project. Pageview configuration looks fine and its intended functionally working as expected. About on click jumping to a particular page index and pages swiping till the actual index, that is expected behaviour of the widget. 

However, please let us know if the issue persists so that we can look into it. Let us know if the issue has been solved, and I'll close the ticket. Thanks

**Comment by kicsijohn** [comment] 2023-09-21 10:50
HI @hariprasadms. No problem. I believe there may have been a misunderstanding regarding the issue. During test mode on the web, the jump to page action is set to swipe until the actual index by default, which is what we expect. However, if the pageview widget has an on swipe action that swipes to the next page, the pageview will continue swiping.
![CleanShot 2023-09-21 at 12 14 45](https://github.com/FlutterFlow/flutterflow-issues/assets/45784821/27551389-d150-4aa8-831d-d4c84210e532)
**The jumpt to page action's behaviour looks like this:**
- Without on swipe - delay + swipe next action on the pageview: 
the pageview jumps to the desired index and stay there.
- with on swipe - x sec delay + swipe next action on the pageview:
the the pageview jumps to the desired index - for example the 5., then keep swiping immediately (don't wait for the delay) and continues swiping 5 times. If it jumps to the 6. index it will continue swiping 6 times. 

That's a bit of an issue for me because I'm currently using this setup in the following way:
the pageview's on swipe action starts a sound -> if the sound ends -> swipes next. But on web it behave exactly as described above: doesn't wait for the sound, it keep swiping.

Meanwhile I tested it on a real iPhone and there this looks a bit different:
I have this setup: jump to index --> start sound - wait till the sound ends --> swipe to the next page
And behave this way:
the jump to page action jumps to the desired index --> starts the sound but not wait, instead swipe to the next page immediately. 

Here is a video with this behaviour (play it with sounds, because it plays an example audio and should wait minutes before swiping):
- the read button contains jump to page --> play sound actions
- the autoplay button contains jump to page --> play sound - wait till the sound ends -> swipe to the next actions
- observe that the action flow that contains a swipe next action immediately swipes to the next page
Here is the link for the video:
https://share.cleanshot.com/pYy1L4r2

**Comment by hariprasadms** [comment] 2023-09-22 13:33
Hi @kicsijohn - Thanks for the details. Considering the way page-view widget is being configured in your project and points you added, I can mark this issue as a bug. Dev team can decide the status of it. Thanks

**Comment by agreaves** [comment] 2023-09-24 17:22
Hi @kicsijohn, thank you for the bug report! After investigating, this is actually the intended behavior of the PageView, and the issue is due to the setup of the page, which may need some additional logic to manage the timing of the sounds played and swipe action.

The PageView's `On Page Swipe` action executes any time a new page is selected. In the example you gave, this will wait 3 seconds, then swipe to the next page. If you select a page in the meantime, this will also trigger an `On Page Swipe` action, which means two such actions will be lined up. This will result in two page swipes after you've switched, each of which triggers the same "On Page Swipe" action, so you end up with a chain reaction of swipes.

This is why generally it's not advised to add `Page View -> Next` action inside of `On Page Swipe` unless you have additional logic to make sure you don't end up in a situation such as this.

I would advise gating the `PageView -> Next` action based on some logic relating to a Page or App State variable (perhaps in combination with the current PageView index) to ensure that you don't swipe more than once. Based on what you described you want to happen, the real issue is you need to distinguish between a "User Triggered" swipe and an "App Triggered" swipe.

To do this, I'd define an Action Block for the "App Triggered" swipe, which sets a variable `isAppTriggered` to `true` right before the `PaveView -> Next`, waits `100ms` and then sets `isAppTriggered` to `false`. Then, at the start of your `On Page Swipe` action, you can add a conditional on `isAppTriggered` to serve the two different use cases. That way, for a user triggered swipe you can do something different, such as set a `isUserTriggered` variable and ignore future swipe actions if this is true.

Not sure if this solution will work, but just wanted to give some ideas! However I am closing this issue now since this is expected behavior for the PageView and it's just a complex use case.

**Closed by agreaves** 2023-09-24 17:22 UTC
Labels: type: bug

**Comment by kicsijohn** [comment] 2023-09-25 18:02
Thank you @agreaves for the detailed explanation. You were correct, the swipe next action was triggered multiple times. I was able to come up with a solution for a conditional before the swipe action, and now it works perfectly.
