### ISSUE TITLE
image_downloader package gives building apk error

### ISSUE THREAD

**Issue by pippoberto** [FlutterFlow/flutterflow-issues#1074] opened 2023-07-04 13:05 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I try to download the apk of my project I get an error related to the image_downloader package

### Expected Behavior

It should download the apk with the function to download on device images with image_downloader package

### Steps to Reproduce

1. Crate a project
2. Create a custom action
3. Import package image_downloader: ^0.31.0
4. Download apk

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40z/Hq4c9grt9G+KrUbfpVqDw5Jlg/bYEzlu1raCsofePrOpkAf8/7UFtUcMildFFUfE38sH8X/MrpkfH1LfECYEuVc75T/qhITjrjfz6iM4yKDpS3b3FSGcdYCh2/yMKviB1DKrNYc3hh2mCQe97KHy3vN4DzPjIRQeaoXdeK2SrDX1iXc2URm05KZDPz

### Context

I am trying to add a function to download images on device

### Visual documentation

Error: Command failed: flutter build apk --no-pub --no-version-check
Note: /opt/.pub-cache/hosted/pub.dev/cloud_firestore-4.8.0/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestoreMessageCodec.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /opt/.pub-cache/hosted/pub.dev/cloud_firestore-4.8.0/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestoreMessageCodec.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /opt/.pub-cache/hosted/pub.dev/firebase_messaging-14.6.2/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /opt/.pub-cache/hosted/pub.dev/purchases_flutter-4.10.2/android/src/main/java/com/revenuecat/purchases_flutter/PurchasesFlutterPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
e: /opt/.pub-cache/hosted/pub.dev/image_downloader-0.31.0/android/src/main/kotlin/com/ko2ic/imagedownloader/ImageDownloaderPlugin.kt: (332, 17): 'when' expression must be exhaustive, add necessary 'is Pending', 'is Successful' branches or 'else' branch instead

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':image_downloader:compileReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m
Gradle task assembleRelease failed with exit code 1

### Additional Info

Looking on Stuck Overflow I found that many had this problem in flutter and they managed to solve it updating the kotlin version to the last one. I tried with the last three version of kotlin but I get the same results.

I tried to deploy to the stores and on the apple store it published and I tested it on testFlight and it works.
The play store deploy gives the same error as the apk build.

### Environment

```markdown
- FlutterFlow version: V.1.1.88
- Platform: Web, MacOS
- Browser name and version: 
- Operating system and version affected:
```

**Comment by bulgariamitko** [comment] 2023-07-04 13:19
Do you have any custom code in your project?

**Comment by pippoberto** [comment] 2023-07-04 20:22
> Do you have any custom code in your project?

Yes I have some custom action and custom functions and they all work well

**Comment by bulgariamitko** [comment] 2023-07-05 07:08
@pippoberto  are you using any packages in your custom code?

**Comment by pippoberto** [comment] 2023-07-05 07:46
> @pippoberto are you using any packages in your custom code?

Yes in the others custom codes I use some packages like firebase_storage and plugin_platform_interface and they all work with no problem. In the custom action which gives me problem I just use the package image_downloader and it seems to be the cause of the error.

**Comment by bulgariamitko** [comment] 2023-07-05 08:28
@pippoberto can you try to use "any" everywhere you use a package in your custom code and see if that will fix the issue?

More info you can find here 
https://www.youtube.com/watch?v=PMPP8hGAJuI

**Comment by pippoberto** [comment] 2023-07-05 13:32
> @pippoberto can you try to use "any" everywhere you use a package in your custom code and see if that will fix the issue?
> 
> More info you can find here https://www.youtube.com/watch?v=PMPP8hGAJuI

I tried adding any to every package and I got the following error:

Error: Command failed: flutter build apk --no-pub --no-version-check
Note: /opt/.pub-cache/hosted/pub.dev/cloud_firestore-4.8.0/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestoreMessageCodec.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /opt/.pub-cache/hosted/pub.dev/cloud_firestore-4.8.0/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestoreMessageCodec.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /opt/.pub-cache/hosted/pub.dev/firebase_messaging-14.6.2/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /opt/.pub-cache/hosted/pub.dev/purchases_flutter-4.10.2/android/src/main/java/com/revenuecat/purchases_flutter/PurchasesFlutterPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
e: /opt/.pub-cache/hosted/pub.dev/image_downloader-0.31.0/android/src/main/kotlin/com/ko2ic/imagedownloader/ImageDownloaderPlugin.kt: (332, 17): 'when' expression must be exhaustive, add necessary 'is Pending', 'is Successful' branches or 'else' branch instead

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':image_downloader:compileReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 26s
Gradle task assembleRelease failed with exit code 1

**Comment by bulgariamitko** [comment] 2023-07-06 05:59
@pippoberto and can you also share the custom code you are using together with the package image_downloader?

**Comment by bulgariamitko** [comment] 2023-07-06 10:53
I think this issue is related to the package image_downloader itself and not FF. Please try to use another package.

**Comment by pippoberto** [comment] 2023-07-06 12:52
@bulgariamitko Thank you. Do you know any package that works for mobile? I just need to download images to the gallery.

**Comment by wenkaifan0720** [comment] 2023-07-13 12:29
Since this is not a bug on FF side, I will close this issue for now. Thank you.

**Closed by wenkaifan0720** 2023-07-13 12:29 UTC
Labels: closed: not a bug, status: not a bug
