### ISSUE TITLE
For iOS App, generating Info.plist for UIBackgroundModes key is not proper

### ISSUE THREAD

**Issue by srinivasande** [FlutterFlow/flutterflow-issues#1444] opened 2023-09-12 12:21 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Trying to add new permission for iOS App, for key "UIBackgroundModes" and want to add value as "audio", the genrated Info.plist is not proper as this key expects the value as "Array of strings" but it is generating just String as below
**<key>UIBackgroundModes</key>
    <string>audio</string>**

INSTEAD of

**<key>UIBackgroundModes</key>
 <array>
    <string>audio</string>
 </array>**
With this there is no way that manually add/edit Info.plist in flutterflow to add permission to the audio player for playing it in background

### Expected Behavior

The generated Info.plist should be 

**<key>UIBackgroundModes</key>
 <array>
    <string>audio</string>
 </array>**

### Steps to Reproduce

1. Open Settings -> Permissions
2. Click on "+ Add Permission" to add new permission
3. Enter iOS Permission Key as "UIBackgroundModes", Permission Message as "audio" and save
4. The generated Info.plist is not proper

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Any Widget will work

### Context

In My Audio App, audio player is not functioning as expected. 
Without this permission set, iOS App player is getting stopped and playing in background.

### Visual documentation

![Screenshot 2023-09-12 at 17 43 07](https://github.com/FlutterFlow/flutterflow-issues/assets/33932492/0f19e7a5-7b1b-4433-9383-bf12062ac3e0)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: MacOS Desktop
- Browser name and version: Chrome Version 116.0.5845.179 (Official Build) (arm64)
- Operating system and version affected: iOS App
```

**Comment by hariprasadms** [comment] 2023-09-14 14:50
Hi @srinivasande - Thanks for submitting the issue. I can re produce the steps. 

Dev note - In downloaded code the permission and its string looks as below. 

<img width="912" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/31c887a3-f2aa-474f-8a3c-000603eb25d0">

Expected -
<img width="571" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/2a555e7b-7b28-49d0-b96d-8e35a3a2e658">

**Comment by wenkaifan0720** [comment] 2023-09-21 04:33
Hi @srinivasande. Right now we only support key - string pair type of custom permissions. What we might should have allowed is full input of the permission string. As for your specific need here, I believe it is a duplicate of this issue: https://github.com/FlutterFlow/flutterflow-issues/issues/1167. So I will close this one for now.

**Closed by wenkaifan0720** 2023-09-21 04:33 UTC
Labels: type: bug, status: confirmed, closed: duplicate

**Comment by sergedahdouh** [comment] 2023-11-06 03:23
and when are you planning to add the array type?

**Comment by payminty-shaun** [comment] 2023-11-14 21:10
> Hi @srinivasande. Right now we only support key - string pair type of custom permissions. What we might should have allowed is full input of the permission string. As for your specific need here, I believe it is a duplicate of this issue: #1167. So I will close this one for now.

Hi, this issue is not strictly a duplicate as there are other types of background modes that need to be supported as well. I need the following added which I am unable to do:

`<key>UIBackgroundModes</key>
<array>
	<string>bluetooth-central</string>
</array>`

Can you please re-open this issue?

**Comment by kodjima33** [comment] 2023-12-29 02:37
Hey @wenkaifan0720 
I'm [Nik](https://www.linkedin.com/in/nik-shevchenko-08565b18b/), founder of welovenocode.com (one of the biggest traffic providers for flutterflow) 

The ticket should not have been closed. This is a major issue that caused at least 2 of our devs to churn from Flutterflow. We are also paying for a Flutterflow "team" package but this issue is causing us so much pain and wasted time that we are considering to leave 

Any IOS app that requires background services on the background WILL NOT WORK, because this permission is inside an <array> of UIBackgroundmodes, there is no way to edit this permission from Flutterflow. 

I'd really ask you to look into this and fix this asap because there is no use in flutterflow's deployment feature with this bug

**Comment by kodjima33** [comment] 2023-12-29 02:40
cc @kevintonb @agreaves @aemelyanovff @sbis04 @asmengistu @bulgariamitko

**Comment by danoritic** [comment] 2024-02-02 17:25
please guys help us fix this things fast biko

**Comment by cboyaltea** [comment] 2024-02-04 23:59
Again I insist on this feature because it is not only blocking Audio background but also Bluetooth, location, stripe payment fonctionnalities.

Thanks to allow us more open way to fill the file.

**Comment by christianschoenmakers** [comment] 2024-02-21 13:03
Any solution available yet?

**Comment by fettespferd** [comment] 2024-03-30 18:50
I also really need this. Please fix!

**Comment by KiYong-Lee** [comment] 2024-05-03 01:36
Same Problem. Please fix.

**Comment by djibysensei** [comment] 2024-05-28 08:05
Hey, for those who want to add audio in the background, simply add a page with an audioPlayer widget (the one from FlutterFlow), and activate "Play in background". Even if you don't use the page, this will automatically add the audio background to the info.plist file with the "array"

**Comment by nelsonviiera** [comment] 2024-07-26 01:04
> Hey, for those who want to add audio in the background, simply add a page with an audioPlayer widget (the one from FlutterFlow), and activate "Play in background". Even if you don't use the page, this will automatically add the audio background to the info.plist file with the "array"

Nice!

**Comment by tracedaily** [comment] 2024-09-25 16:19
Same problem - but with location, not audio. No easy fix for me - that I'm aware of :(

**Comment by SMCHub** [comment] 2025-01-19 20:52
> Hey, for those who want to add audio in the background, simply add a page with an audioPlayer widget (the one from FlutterFlow), and activate "Play in background". Even if you don't use the page, this will automatically add the audio background to the info.plist file with the "array"

Is this working?I have custome code and it doesn't work.
