### ISSUE TITLE
API call successful but returns null value

### ISSUE THREAD

**Issue by icestormpure** [FlutterFlow/flutterflow-issues#4984] opened 2024-11-27 01:19 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am using ngrok to expose my local mysql server and to make api call, I am able to retrieve the values by using Postman but when it comes to Flutterflow, it returns "Status 200 (Success)" but returns null value

### Expected Behavior

Should be able to show the same result as postman does

### Steps to Reproduce

1. Set up express/node local API
2. Make sure local mysql server is running
3. Run the server js file
4. Run ngrok
5. Use the link provided by ngrok to make api call
6. Make postman call (Successful and returns the actual values)
7. Make flutterflow api call (Successful but returns null)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4giMjfsM9Oxd8F17rtKe9Wnj8vC096R5c0r9pEGEshNbmuB7QQZ8/eSxdLYteYYFVYeGG0imUewaCMhtrhIfkrMk+uG4hT1pRXQT3MJDmVWq6gEpOoYWtBIJtQGEjG356zhRQlG/tfWmQj3DmHffCdG3qCf9qOYwx5e6fDbOY=

### Visual documentation

![1](https://github.com/user-attachments/assets/50dd2120-ab6b-404d-984f-153481afc4b7)
![2](https://github.com/user-attachments/assets/e12aec4e-dfaa-4123-b928-c449c2eca4c7)

### Environment

```markdown
- FlutterFlow version: v5.0.13
- Platform: Web
- Browser name and version: Chrome 131.0.6778.86
- Operating system and version affected: It affects all platform, version, browser
```

### Additional Information

Severely affecting my project because I will need to connect with my local mysql server

**Comment by Alezanello** [comment] 2024-11-27 17:59
Hello,

Could this issue be related to not including a `userId` in your request on FlutterFlow? FF operates similarly to other API tools when making requests, so this might be a configuration issue on your local server, particularly around access control and who can retrieve specific information.

Please note that this GitHub issue tracker is intended for reporting and reproducing issues directly related to the FlutterFlow platform. If you need assistance with achieving this integration, feel free to reach out to our support team via in-app chat or at support@flutterflow.io.

**Comment by icestormpure** [comment] 2024-11-27 22:28
> Could this issue be related to not including a `userId` in your request on FlutterFlow?

No it doesn't. Just try and make an api call with the full url with no variables, it'll still return null and returns status 200. This is literally a bug how else is postman able to retrieve the values

**Comment by icestormpure** [comment] 2024-11-28 01:20
So I figured out the problem. I added header Ngrok-Skip-Browser-Warning: 'true'

Now it's able to get the data

**Comment by Alezanello** [comment] 2024-12-04 19:22
I’m glad everything is working as expected now! I’ll go ahead and close this issue, but if you encounter anything else, please don’t hesitate to open a new one!

**Closed as not planned by Alezanello** 2024-12-04 19:22 UTC
Labels: status: not a bug
