### ISSUE TITLE
I have problems opening applications on the iPad after opening it on my Windows 10 computer

### ISSUE THREAD

**Issue by Prain77** [FlutterFlow/flutterflow-issues#1605] opened 2023-10-07 03:47 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have problems opening applications on the iPad after opening it on my Windows 10 computer, there is a button that says refresh; but it doesn't do anything. Could you help me because I would like to switch between working with the iPad and the PC.

[https://punkuri.com/flutterflow/error_ipad_version.jpg](url)

### Expected Behavior

I should be able to open on my iPad and then on the PC and vice versa, so I can move forward both on the desktop and outside of my office.

### Steps to Reproduce

1. Open project https://app.flutterflow.io/project/a-f-p-consulta-9hwnth
2. Version incompatibility message appears. (see jpg)
3. The refresh button is pressed; but it doesn't do anything.
4. Forced to press Deskboard button and exit.

![errir_ipad_version](https://github.com/FlutterFlow/flutterflow-issues/assets/86490764/1d066201-2e62-4e36-8c40-b0d4812a37de)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

a-f-p-consulta-9hwnth

### Context

Could you help me because I would like to switch between working with the iPad and the PC.

### Visual documentation

![error_ipad_version](https://github.com/FlutterFlow/flutterflow-issues/assets/86490764/a9f54b21-3d04-4c92-a466-529a1ed92e58)

### Additional Info

![error_ipad_version](https://github.com/FlutterFlow/flutterflow-issues/assets/86490764/4796129c-81fc-4c69-b9bc-53f504e65647)

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: iPad / Windows 10
- Browser name and version: iPad iOS 16 / Chrome 109.0.5414.120 (Build oficial) (64 bits)
- Operating system and version affected: iOS16 / Windows 10
```

**Comment by sbis04** [comment] 2023-10-09 08:14
The issue with the iPad app should be solved in the next update, which will probably be deployed sometime this week!

**Comment by sbis04** [comment] 2023-10-09 08:18
I'm closing this issue as it's a duplicate of #1565. Please track that issue for further updates.

**Closed by sbis04** 2023-10-09 08:18 UTC
Labels: type: bug, status: confirmed
