### ISSUE TITLE
Unable to upload assets onto projects.

### ISSUE THREAD

**Issue by MishackTP** [FlutterFlow/flutterflow-issues#5065] opened 2024-12-09 13:18 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

For some time now, I’ve been unable to upload assets (e.g., GIFs, images, PDFs, etc.) to the Flutterflow projects I’m working on. While I work with a team, none of them are experiencing this issue—it seems to only affect me. When I try to upload assets, they remain stuck in an infinite loading state. As a result, I’ve had to rely on my team to upload assets for me, which is far from ideal.

<img width="1406" alt="Screenshot 2024-11-28 at 08 31 19" src="https://github.com/user-attachments/assets/3e10f9d7-376e-4fbb-8abe-a829e19e887c">

Is there a specific reason why this issue is only happening to me? And is there a solution for it?

To troubleshoot, I created a new project myself and found I could upload assets without any problems. This leaves me confused—does this mean I’m unable to upload assets to team projects created by our CEO? For context, our CEO sets up the projects for each client, and we don’t create them ourselves. As you can imagine, this issue is a significant inconvenience for both me and the team.

Any guidance or solutions would be greatly appreciated!

### Expected Behavior

The assets to upload successfully to projects instead of getting stuck in an infinite loading loop.

### Steps to Reproduce

I don't believe you will be able to reproduce this issue with your own account.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8whfLlvM92rsdF1oSJK8Janjg5KUQlUIJJltZ+cwwYGO7qPZkAevfBcVZCXu2hdG9UPkap/UEyw97RhuKeGsAoJgquGLp9+b9Xdwn/QXGhVpCLBqiCVXZ8L8JTG26ayrurpBZBD/NzWl4s6mGmGOi8cDfqNpjYPHozH/j+JpjAnGzhAR3JES8z8xIVIGreTI5ODEz25eKMrop5yfj/0w==

### Visual documentation

https://github.com/user-attachments/assets/d6b8185f-d66f-4782-a18b-49e9185da400

https://github.com/user-attachments/assets/f0490cd3-d362-4072-a972-ebaae36a7ea2

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by paulperez-dev** [comment] 2024-12-09 21:21
Hi @MishackTP,

I’m so sorry you’re experiencing this issue. I wasn’t able to reproduce it on a blank project, and since you mentioned it doesn’t occur on a new project, I suspect this might be a project-specific issue.

Our support team would be the best resource to help resolve this. Could you please reach out to them? You can contact them via email at **support@flutterflow.io** or through the in-app chat inside FlutterFlow.

I’ll close this issue here, as this tracker is specifically for bugs that can be reproduced in blank projects.

Thank you so much for your understanding, and I hope this gets resolved for you quickly!

**Comment by MishackTP** [comment] 2024-12-10 06:44
Thank you @paulperez-dev I'll follow up with the team for assistance.

**Closed as not planned** 2024-12-11 02:28 UTC
Labels: status: needs triage, status: can't reproduce, closed: support request
