### ISSUE TITLE
iOS dynamic link does not return to Flutter page from a launched URL. Android does it.

### ISSUE THREAD

**Issue by lguaman** [FlutterFlow/flutterflow-issues#842] opened 2023-05-03 03:01 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I use Firebase Dynamic Links to return to my App after pay in a web payment gateway provider using a launch URL widget. In Android it returns automatically and correctly but iOS does not.

### Expected Behavior

iOS must return automatically to the dynamic link page configured in the 303 response, as Android does.

### Steps to Reproduce

1. login with 1103756134 user and Password! as pasword. 
2. Schedule a virtual or on site appointment
3. Choose a doctor's date for appointment.
4. Go to the shopping cart
5. Tap the payment button
6. Go to payment gateway
7. Fill the fields required in the credit card. This is test enviroment, so you can use 4111111111111111; 12/29; 123
8. When payment is done, hit return to commerce
9. Android goes directly, iOS does not.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ekOfq0ItPpbxa1s+NKcJVqCY5Jmk7bYZMksJtSgw2B5DrPOwpPejxP2FoUtfiTAk7L1r9kTo13P+Pkd72A+UqAzitfYA+ws5UejrLUk6nVamaCKqoYWpCAtxJJVPH1J6k2BB4VPtac2Ri1HGMNd7IYCjfQZDINVcdPPqaCLnUpV2qQ0SLb3kNh1JWeC/v

### Context

I dont know if appointment payment is done, so I can not schedule doctors virtual meeting affecting my customers incomes.

### Visual documentation

Android video: https://drive.google.com/file/d/1Rokt5-LNPnXf9Isk_is3X4rHJBmmDlsS/view?usp=share_link
iOS video: https://drive.google.com/file/d/1Pibr0cIenlf3BmuWqKW7cCndcS92Irsy/view?usp=share_link

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform:iOS
- Browser name and version: Version 111.0.5563.110 (Official Build) (64-bit)
- Operating system and version affected: iOS
```

**Comment by hariprasadms** [comment] 2023-05-03 15:19
Hi @lguaman - Thanks for posting the issue. Can you please add what error you see in the log while redirect is blocked in iOS?. I think it could be a issue related to route which we recently seen in others project but not really sure. Please share the error details. Thanks

**Comment by almantas88** [comment] 2023-06-09 15:35
The issue still persists using FlutterFlow...

**Comment by almantas88** [comment] 2023-06-09 15:38
I even tried creating new apps and deploying them, still the issue persists.

**Comment by Kapsule-me** [comment] 2023-06-09 16:48
I'm also experiencing the same problem since the update of the go_router package from 3.1.0 to 7.1.1 on June 2, 2023.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/104095124/bae13636-cff1-4fe5-b46d-d770fd234fde)

According to [go_router migration documentation](https://docs.google.com/document/d/10Xbpifbs4E-zh6YE5akIO8raJq_m3FIXs6nUGdOspOg/edit) there are some "breaking changes" when upgrading to version 7.X.X.

I'm not sure if that helps, but wanted to relay that information just in case.

**Comment by almantas88** [comment] 2023-06-09 17:48
How much time will it take to fix this bug?

**Comment by agreaves** [comment] 2023-06-09 23:44
Hi @lguaman, thank you for this bug report and sorry for the inconvenience. I was not initially able to reproduce the issue, as from my testing it worked on both iOS and Android.

However, as of the June 2nd update in which we updated to `go_router: 7.1.1`, I can confirm there was a bug navigating to the appropriate page for Dynamic Links. I believe this is what @almantas88 and @Kapsule-me were facing, and the good news is this is fixed and now live!

However I cannot confirm that your issue will be solved as it predates the `go_router` change. It's quite possible that it was also fixed, but you'll have to please let me know if you still see a difference between Android and iOS. I will leave this issue open for the time being.

**Comment by almantas88** [comment] 2023-06-10 16:37
It seem to work! I will test this more first in monday morning.

**Comment by lguaman** [comment] 2023-06-11 01:23
Hi Alex
Let me test on monday. I'll keep you posted

**Comment by SamyKhara** [comment] 2023-06-12 02:07
> Hi @lguaman, thank you for this bug report and sorry for the inconvenience. I was not initially able to reproduce the issue, as from my testing it worked on both iOS and Android.
> 
> However, as of the June 2nd update in which we updated to `go_router: 7.1.1`, I can confirm there was a bug navigating to the appropriate page for Dynamic Links. I believe this is what @almantas88 and @Kapsule-me were facing, and the good news is this is fixed and now live!
> 
> However I cannot confirm that your issue will be solved as it predates the `go_router` change. It's quite possible that it was also fixed, but you'll have to please let me know if you still see a difference between Android and iOS. I will leave this issue open for the time being.

The bug still persists.

**Comment by Rart3001** [comment] 2023-06-15 15:34
Hi, I have the same issue on my Android device trying to open a shortened deep link. I can notice in the log that the router is trying to redirect to the destination page before the deep link is decoded: 
For example:
This is my shortened deep link:

`https://myapp.page.link/a8SW32drBxwrPrmA9
`
and the original deep link:

`https://app.myapp.ev/promotion/67890744598132371560
`
and this is the log I mentioned before:

```
[GoRouter] setting initial location /
[GoRouter] No initial matches: /a8SW32drBxwrPrmA9
[GoRouter] Using MaterialApp configuration
[GoRouter] No initial matches: /a8SW32drBxwrPrmA9
```
after that, the app opens the initial page, but the log shows this error message:


```
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
setState() called after dispose(): _StartWidgetState#e8e45(lifecycle state: defunct, not mounted)

This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.

The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().

When the exception was thrown, this was the stack: 
#0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1097:9)
#1      State.setState (package:flutter/src/widgets/framework.dart:1132:6)
#2      _StartWidgetState.initState.<anonymous closure> (/pages/new_flow/start/start_widget.dart:51:57)
#3      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#4      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227:9)
#5      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:942:7)
#9      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
(elided 3 frames from class _Timer and dart:async-patch)
```
that make reference to the "initState" method that in the end has this call:
`
    WidgetsBinding.instance.addPostFrameCallback((_) => setState(() {}));`

and after that, I can see this in the log:

```
[GoRouter] No initial matches: /a8SW32drBxwrPrmA9
[GoRouter] pushing /promotion/67890744598132371560
```
But the app stays on the main page and doesn't open the correct page.

**Comment by Rart3001** [comment] 2023-06-15 18:48
@agreaves here it is: 

`IT4klc/qw4Z2obgA1rXTbcJ4gikWQlg/TL07ttYbZxUjIuPtBJh/fuP7PltoZ/XmY0NhHFCkoFIy//yKvdjtA+4BPTmqR4B6zpYBbQHKLHq8RpSmPLi8WXBBHfJjI1S407aR2yV+HMFuc3Ae72CmA9+taD7DN5+/Zwh9f6PHaOI=`

Thank you.

**Comment by SamyKhara** [comment] 2023-06-17 21:21
Hey @agreaves - here you go
IT4kkcmAsIV2pbxY17X5bcAw9TwsJU99TLJMqNYbGA0hfL7pE5k2eMmlYlFLYteqTFdqBVr9gmE1wM71kvLhL/kpAwycbrU5wa5XQTrKQliub8WqDc2VPnEmN9NgCFy707aFviZ4BPBsSGNgwFyEOPCdG3qCf9qOYwx5e6fDbOY=

**Comment by Rart3001** [comment] 2023-06-27 14:49
Hello @agreaves, do you have some updates about this? Can you help us with this, we have a client waiting for a feature in the base of the deep link, Is something I can do to help you, do you need more information?

**Comment by agreaves** [comment] 2023-06-28 02:05
Hi @SamyKhara and @Rart3001, apologies for the lack of a status update. I've actually been unable to reproduce this issue in any project I've tested. And dynamic links do not work well on a Simulator so I can't run either of your projects locally to debug because of Apple Signing restrictions.

The only feasible way for me to reproduce and debug this issue is if either of you were able to add me to the development team (or to the particular app) so that I may sign and debug the application locally. If that sounds reasonable, please let me know and I can provide next steps for how to accomplish this.

**Comment by SamyKhara** [comment] 2023-06-28 02:35
Hi,

This issue got resolved recently for me.

I did the following- changed my share to Deep Linking, published the
project, changed my share to dynamic linking, and again published the
project.

It got solved by the change. Weird solution but it worked!

Best,
Simran

**Comment by agreaves** [comment] 2023-06-28 03:03
@Rart3001 I've tried Android as well and I'm not able to reproduce the issue there either. Can you send me a screen recording of the it on Android? Ideally on the current state of the project (locally debugged or via download APK). There did seem to be some issues on loading when I tried it.

**Comment by Rart3001** [comment] 2023-06-28 15:28
@agreaves can you give me an email address to add you to the project? and for send the video

**Comment by almantas88** [comment] 2023-08-29 10:49
I don' really know, but dynamic links works fine when the app is downloaded, I got an issue when I open the dynamic link it redirects me to app store, but doesn't redirect correctly after the installation, it only opens the app, but ignores the redirection. Works fine on Android, so this means this is a bug, and only with iOS.

Although FF documentations says "The dynamic link opens a specific page in your app. Unlike the deep link, the dynamic link survives the app install. That means if the user has not installed the app, they can be taken to the respective store to install the app. After the app is installed, users can be taken straight to the intended app page."

Main issue for me is 'users can be taken straight to the intended app page.' It doesn't do that on iOS.

**Comment by agreaves** [comment] 2023-09-22 23:06
Hi all, I will be closing this ticket shortly (in a few days), as the original issue was fixed. If you are still experiencing this same issue, please let me know. Otherwise, if you are experiencing a different dynamic linking issue, please create a new Issue with all the relevant information. Thanks!

**Closed** 2023-09-24 15:44 UTC
Labels: type: bug, status: confirmed

**Comment by almantas88** [comment] 2023-09-25 06:01
do I need to republish my app to app store and google play store?
