### ISSUE TITLE
Unable to create App State Value with Data Type 'Document Reference'

### ISSUE THREAD

**Issue by taggxyz** [FlutterFlow/flutterflow-issues#3307] opened 2024-07-03 15:21 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am unable to create an App State Value with the Data Type 'Document Reference', the 'Create' button is disabled.

### Expected Behavior

I would expect the 'Create' button to be enabled so that I can add a Document Reference to my App State.

### Steps to Reproduce

1. Create a project
2. Create a collection in the database
3. Create an App State Variable
4. Set the Data Type of the App State Variable you are creating to 'Document Reference'
5. Try to click 'Create'

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXhcj1z5V2rsBE7pPfbu0xp2EwGUwbUOc7j9VEGAsjCeOvE7N3fff7clBVWOqHd29iMFH/mkwH0ejKvYXpE/dfAz+VGIhywahLUxDvTmKXb8WbCc+oYXJ6M+VQGBWs352R2yV5Ju12clIM2GeqCN+uY3qCf9qOYwx5e6fDbOY=

### Visual documentation

<img width="485" alt="Screenshot 2024-07-03 at 16 12 30" src="https://github.com/FlutterFlow/flutterflow-issues/assets/53789605/4ee684ca-cb8b-446d-9773-62ba063ac559">

### Environment

```markdown
- FlutterFlow version: 4.1.65
- Platform: Web, MacOS Desktop
- Browser name and version: N/A
- Operating system and version affected: N/A
```

### Additional Information

I am currently unable to push our latest update which was scheduled with our users because this is such a fundamental of our new release. I have it working on other projects but since our platform is two-sided, I cannot ship as only one side works.

**Comment by Alezanello** [comment] 2024-07-03 15:50
Hi @taggxyz ,

Thank you for bringing this to our attention! 
This is a known issue, and our engineering team is already working on a fix. 
I'm closing this thread since it's a duplicate of an existing issue in our backlog.

 The fix should be deployed to production soon.

Best regards,
Azanello

**Closed as not planned** 2024-07-03 15:51 UTC
Labels: closed: duplicate

**Comment by taggxyz** [comment] 2024-07-04 20:12
@Alezanello Hey, I don't suppose you know when this will be fixed? I only ask as I have to keep pushing back our release date.

Thanks!

**Comment by Alezanello** [comment] 2024-07-04 20:21
We have fixed this issue and the fix should be live in the next product release (like Tuesday morning EST) !

**Comment by taggxyz** [comment] 2024-07-04 21:26
@Alezanello Thats great to hear, thank you!

**Comment by taggxyz** [comment] 2024-07-09 14:58
@Alezanello 👀

**Comment by Alezanello** [comment] 2024-07-09 15:00
@taggxyz I'm also anxious!!! Hahaha!

**Comment by taggxyz** [comment] 2024-07-09 15:37
@Alezanello Has today's release happened?

**Comment by Alezanello** [comment] 2024-07-09 16:06
Not at the moment, i dont have the exact time but is 99.99% that is going to be today (i hope not to use the 0.01% chance for lottery today)

**Comment by Alezanello** [comment] 2024-07-09 17:52
Released 1 hour ago!!!<br>Please confirm that your issue was beign fixed!

**Comment by Alezanello** [comment] 2024-07-09 18:13
<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/091f84a7-7ca1-4368-9a90-b202dc92ac84/e00bcebb-a80d-413e-8d0b-ed24355c4376?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wOTFmODRhNy03Y2ExLTQzNjgtOWE5MC1iMjAyZGM5MmFjODQvZTAwYmNlYmItYTgwZC00MTNlLThkMGItZWQyNDM1NWM0Mzc2IiwiaWF0IjoxNzIwNTQ4Nzk2LCJleHAiOjMzMjkxMTA4Nzk2fQ.c7VLf68nZJcWyRCU3EBCyiRKDAq3s2WAOaqSX1K0rUA " alt="image.png" width="475" height="491" />

WORKING! Everything good from your side?

**Comment by taggxyz** [comment] 2024-07-09 19:07
@Alezanello Amazing, thank you for such quick replies!!
