### ISSUE TITLE
The test session shows "Expired: -16809 minutes" and is not working

### ISSUE THREAD

**Issue by BenEppers** [FlutterFlow/flutterflow-issues#5063] opened 2024-12-09 10:09 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The test session shows "Expired: -6809 minutes" and is unavailable for use.

### Expected Behavior

The test session should start normally without showing an expiration time.

### Steps to Reproduce

Open the project
Click on Use Test Mode to initiate a test session.
Observe that the expiration time is displayed as "-6809 minutes".
The page does not load, and no error screen is displayed.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oyc/lx5BIsbxY1pD+d/lahSQ6KWY1aJEwmMpBZywgfZzzBLN/fPfQP1NoYMzmTFVmJ2emp14Jw9b1voT1UfknEyqbRbZyzZdycw/LUTuWRKWTF7uCQ0ZPN8VPfUig17WrgghRJstudH9n7zuEDNytfDDcQabBC1QwSq/LZO4=

### Visual documentation

![Screenshot 2024-12-09 110632](https://github.com/user-attachments/assets/2a8146b3-ab48-4333-8c14-a12599941fa8)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

### Additional Information

Testing is currently not possible; Need fast fix!!

**Comment by BenEppers** [comment] 2024-12-09 10:10
> ### Can we access your project?
> * [x]  I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.
> 
> ### Current Behavior
> The test session shows "Expired: -6809 minutes" and is unavailable for use.
> 
> ### Expected Behavior
> The test session should start normally without showing an expiration time.
> 
> ### Steps to Reproduce
> Open the project Click on Use Test Mode to initiate a test session. Observe that the expiration time is displayed as "-6809 minutes". The page does not load, and no error screen is displayed.
> 
> ### Reproducible from Blank
> * [ ]  The steps to reproduce above start from a blank project.
> 
> ### Bug Report Code (Required)
> IT4oyc/lx5BIsbxY1pD+d/lahSQ6KWY1aJEwmMpBZywgfZzzBLN/fPfQP1NoYMzmTFVmJ2emp14Jw9b1voT1UfknEyqbRbZyzZdycw/LUTuWRKWTF7uCQ0ZPN8VPfUig17WrgghRJstudH9n7zuEDNytfDDcQabBC1QwSq/LZO4=
> 
> ### Visual documentation
> ![Screenshot 2024-12-09 110632](https://private-user-images.githubusercontent.com/171371220/393791935-2a8146b3-ab48-4333-8c14-a12599941fa8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MzkyNzEsIm5iZiI6MTczMzczODk3MSwicGF0aCI6Ii8xNzEzNzEyMjAvMzkzNzkxOTM1LTJhODE0NmIzLWFiNDgtNDMzMy04YzE0LWExMjU5OTk0MWZhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOVQxMDA5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNGQ1YzczNzQ2YWVkOGZkMDY2OTA5ZWVhNWViMGNmODkxNzc5NWVjMWE3ZWM4MWM5YmNlMzUyMjM1YTAwZTBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nwOYrwUgdWiJxayUMzWk4wo8LuVBz9XpUoomNgV_Xto)
> 
> ### Environment
> ```
> - FlutterFlow version: 
> - Platform:
> - Browser name and version:
> - Operating system and version affected:
> ```
> 
> ### Additional Information
> Testing is currently not possible; Need fast fix!!

Instant reload is not working either, by the way

**Comment by paulperez-dev** [comment] 2024-12-09 22:07
Hi @BenEppers,

Is this issue occurring across all your projects? Could you also let me know which platform you’re using?

Thank you!

**Comment by BenEppers** [comment] 2024-12-09 23:04
Hey @paulperez-dev, Thanks for your help.
I think it's only for this project. However I am pretty sure this is not a project setup issue. There is no error or so from my side.  It happens when testing on web.

**Comment by rzambroni** [comment] 2024-12-10 15:07
Hi @BenEppers,

Thank you for reaching out! There is a known issue where the timer may sometimes display an incorrect count. However, this shouldn't be breaking your app.

It’s possible that your test session encountered a glitch. To resolve this, please try the following steps:

* Start test session
* End Session 

  <img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/8d2222ae-da83-4534-8b3a-37f450bcbf71/a9ee5d04-a52a-46e8-bfaf-1b0281dcb8a4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84ZDIyMjJhZS1kYTgzLTQ1MzQtOGIzYS0zN2Y0NTBiY2JmNzEvYTllZTVkMDQtYTUyYS00NmU4LWJmYWYtMWIwMjgxZGNiOGE0IiwiaWF0IjoxNzMzODQzMjQyLCJleHAiOjMzMzA0NDAzMjQyfQ.uvW6rFspJU9Uwhz-HZDG5g93V0F98kr_iwZ5Frir0w0 " alt="image.png" width="360" data-linear-height="160" />
* Try again.

We’ve tested it on our end, and your app appears to be loading correctly. 

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/97f9fba8-277a-4515-b6e7-fe0f2260af80/486902d4-e804-4c8e-9500-31b3e8bd27d6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85N2Y5ZmJhOC0yNzdhLTQ1MTUtYjZlNy1mZTBmMjI2MGFmODAvNDg2OTAyZDQtZTgwNC00YzhlLTk1MDAtMzFiM2U4YmQyN2Q2IiwiaWF0IjoxNzMzODQzMjQyLCJleHAiOjMzMzA0NDAzMjQyfQ.Q3N7RM8bF2gQ9cjP-mo5vsM6gGF3ls0NNj7CgPchDkk " alt="image.png" width="3600" data-linear-height="1964" />

Hope that helps.

Thanks.

**Comment by paulperez-dev** [comment] 2024-12-12 20:38
Duplicate of #5078

**Closed as not planned** 2024-12-12 20:37 UTC
Labels: status: can't reproduce, closed: duplicate
