### ISSUE TITLE
"Getter isn't defined" build error for App state list of colors initialization

### ISSUE THREAD

**Issue by BrentM** [FlutterFlow/flutterflow-issues#3130] opened 2024-06-14 00:09 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Build error preventing Test mode. This is the relevant error message:
lib/app_state.dart:92:34: Error: The getter '_TaskColors' isn't defined for the class 'Color'.
 - 'Color' is from 'dart:ui'.
Try correcting the name to the name of an existing getter, or defining a getter or field named '_TaskColors'.
        _TaskColors.map((x) => x._TaskColors.toString()).toList());

This broke today 6/13 and was working yesterday so the issue is likely very recent.

### Expected Behavior

old, working code:
  void removeFromTaskColors(Color _value) {
    _TaskColors.remove(_value);
    prefs.setStringList(
        'ff_TaskColors', _TaskColors.map((x) => x.value.toString()).toList());

new, broken code:
  void removeFromTaskColors(Color value) {
    TaskColors.remove(value);
    prefs.setStringList('ff_TaskColors',
        _TaskColors.map((x) => x._TaskColors.toString()).toList());

### Steps to Reproduce

This seems to me related to the list of colors in an app state variable. I would expect that any project that does this would be affected.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ol+fl2ItNtbxb+Kr+asFKpyQUC0wkaI0N18pOGDsdF4iuPOxzac78XEpDTe2mS2NhKEWGnkEe3PT7hvH9A8ABHy+rbLU4yc5UFg7JWlO/aoS1EpGSdHB6EdhbIEi/052juhR+CM5oWHwi3TmyN++tTXPdQI/7Zwh9f6PHaOI=

### Visual documentation

![Screenshot 2024-06-13 170721](https://github.com/FlutterFlow/flutterflow-issues/assets/952240/779a16b6-6725-465d-bc88-a6c864513ab8)

### Environment

```markdown
- FlutterFlow version: v4.1.59+
- Platform: Test Web env.
- Browser name and version: Chrome
- Operating system and version affected: Windows 11
```

**Comment by paulperez-dev** [comment] 2024-06-14 18:52
Hi @BrentM! I can't reproduce this issue in the latest version. Can you please try to replicate it in the latest version? Please share the bug report code of the new blank project if replicable.

**Comment by BrentM** [comment] 2024-06-14 19:31
I'm still getting the same error in the latest version. It looks like it is related to setting the initial values for the colors - I included a screenshot for how I initialize the color values in the project. The generated code looks incorrect and probably is worth a look at whatever is generating code for color state initialization. Without an initial value it may be exiting the .map before the mapped problem code is evaluated. 

![Screenshot 2024-06-14 122217](https://github.com/FlutterFlow/flutterflow-issues/assets/952240/73a4784d-d6da-483e-89f0-b7b5579d2f02)

I haven't created this from scratch in a blank project but hopefully the problem code snippet will help track down the responsible code. This is in "lib/app_state.dart" which I believe is completely generated by FlutterFlow.

**Comment by Layer-pj** [comment] 2024-06-15 02:18
I am also experiencing the same issue.

**Comment by BrentM** [comment] 2024-06-18 17:25
@paulperez-dev It would be great if you could escalate this. It's still happening and it's blocking my work. Thank you!

![Screenshot 2024-06-18 102308](https://github.com/FlutterFlow/flutterflow-issues/assets/952240/29eac6b4-8575-4d44-bb36-46e650b19848)

**Comment by paulperez-dev** [comment] 2024-06-19 20:29
Hi @BrentM! Can you please change all the colors and then set it back to the corresponding value?<br><br>If that doesn't work and being this a project-specific issue, our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: support@flutterflow.io or using the in-app chat inside of FlutterFlow. <br><br>I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. <br><br>If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. <br><br>Thanks so much!

**Comment by BrentM** [comment] 2024-06-20 18:57
@paulperez-dev I reproduced this in a 100% new, blank project, with an empty color list. The only change to the "Blank" starter project I made was to add a state variable of this type. It seems to affect all List Color state variables and is a project-breaking error. 

Please escalate this fix. I'd also appreciate an ETA on a fix - I've been blocked by this for more than a week and I don't want to tear my project apart to implement a workaround for this FF regression unless I absolutely have to.

Project: color-f-f-error-da2vzt
FlutterFlow v4.1.61+ released June 18, 2024

![Screenshot 2024-06-20 115146](https://github.com/FlutterFlow/flutterflow-issues/assets/952240/778aaae4-2e96-4640-a6e1-0cc867928b78)

![Screenshot 2024-06-20 114214](https://github.com/FlutterFlow/flutterflow-issues/assets/952240/9cb5deb5-2f0e-42ab-94bc-19fe0c177e5a)

**Comment by paulperez-dev** [comment] 2024-06-22 12:49
Hi @BrentM! Please share the bug report code of this new project so I can take a look.

**Comment by BrentM** [comment] 2024-06-22 16:52
@paulperez-dev Here's the bug report code for the project: IT48lcmA8YlPn7xd+KrhbflahikXQkM7U5I4m+tHUUg8KOPaPOw+Ps/BM0RvZMzjT0FXelqZ/GoW0t6PjobDEMAnAAerc4hm+s9cbjrMeH+tVrWbFJWgW2h7P9NXIECF3J6NoBF7LtFodHAY3UyqOe7IVj/cJL22PDMsDq/LZO4=

**Comment by BrentM** [comment] 2024-06-28 19:11
This seems to be resolved in the Jun 25 release

**Comment by paulperez-dev** [comment] 2024-07-03 21:20
Hi @BrentM! Thanks for the confirmation!

**Closed as not planned** 2024-07-03 21:20 UTC
Labels: closed: fixed
