### ISSUE TITLE
Issues with handling arrays of maps in Firestore documents

### ISSUE THREAD

**Issue by wednesdei** [FlutterFlow/flutterflow-issues#805] opened 2023-04-22 20:23 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The current implementation of FlutterFlow for handling Firestore documents with an array of maps does not allow updating specific key-value pairs within the array directly. The methods provided, such as "Set Individual Fields", "Set from Variable", "Clear Unspecified Values", "Add to Set", "Remove from Set", "Set Value", and "Delete" are not sufficient to update nested key-value pairs in an array of maps. These methods do not appear to be working correctly, and only allow adding data to the end of the list.

**Example data model that is not working:**

Consider a Firestore document with the following structure:

`{
  "documentId": "example_document_id",
  "arrayField": [
    {
      "key1": "value1",
      "key2": "value2"
    },
    {
      "key1": "value3",
      "key2": "value4"
    }
  ]
}`

In this example, arrayField is an array of maps containing key-value pairs.

In addition, the current implementation of BuiltValue may be causing some of the issues observed. The lack of proper support for updating specific elements in an array of maps can lead to difficulties in performing common tasks, such as adding, updating, or removing elements.

### Expected Behavior

The expected behavior for each of the mentioned methods when working with an array of maps is as follows:

**Set Individual Fields:** This method should allow users to update individual key-value pairs within a specific element of the array, without affecting other elements or key-value pairs in the array. After executing this method, the updated key-value pair in the specified element should reflect the new value.

**Set from Variable:** This method should replace the entire map at a given index in the array with the provided map variable. Other elements in the array should remain unchanged. After executing this method, the map at the specified index should contain the same key-value pairs as the provided variable.

**Clear Unspecified Values:** This method should remove all key-value pairs from the map at the given index in the array that are not included in a provided list of keys to preserve. Other elements in the array should remain unchanged. After executing this method, the map at the specified index should only contain the key-value pairs with keys specified in the preservation list.

**Add to Set:** This method should add a new key-value pair to the map at the given index in the array, without affecting other elements or key-value pairs in the array. If the key already exists, its value should be updated. After executing this method, the map at the specified index should contain the newly added key-value pair.

**Remove from Set:** This method should remove a specified key-value pair from the map at the given index in the array. Other elements and key-value pairs in the array should remain unchanged. After executing this method, the map at the specified index should no longer contain the removed key-value pair.

**Set Value:** This method should replace the entire map at the given index in the array with the provided map value. Other elements in the array should remain unchanged. After executing this method, the map at the specified index should contain the same key-value pairs as the provided value.

**Delete:** This method should remove the entire map at the given index in the array. Other elements in the array should remain unchanged, and the array length should be reduced by one. After executing this method, the array should no longer contain the deleted map.

The generated code should provide proper support for each of these methods when working with arrays of maps in Firestore documents. This would ensure users can effectively manage and manipulate their data structures as needed.

### Steps to Reproduce

1. Create a Firestore document with an array of maps data structure.
2. Try to update a specific key-value pair within the array using the methods provided by FlutterFlow.
3. Notice that there is no direct way to update specific key-value pairs within the array.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sl8nc5YhOxccA+KrUbPp7/CgRH2F8R+csscpCbw4bIYj2P4lzY876PlhBUuLjd2xhe022p14CwcLOvt7lCfA7C0uuUYRz+alQVA/MZ3KWM7mTF7m8eHAlHe5VIGKy08GJuRJRObF2WEUuwV6MGuSWShLUNL7ICkQwSq/LZO4=

### Context

This issue has significantly impacted my productivity and user experience with FlutterFlow. I am trying to accomplish a simple task of editing key-value pairs for collection documents, but the current implementation and provided methods make it challenging to achieve this goal. I have spent hours trying to figure out what is going wrong, only to learn that what I have been attempting is not even possible with the existing code.

Moreover, it is frustrating that the methods provided feel like they do not serve their intended purpose, leading to a suboptimal user experience. I am aware that other users have encountered the same issue and have been forced to implement custom action workarounds that should not be necessary.

The purpose of a tool like FlutterFlow is to streamline and simplify the development process. However, I find myself spending a considerable amount of time trying to get simple queries and operations working for common data structures, which detracts from the overall efficiency that FlutterFlow aims to provide.

I want to emphasize that my intention in raising this issue is solely to help improve the product. I believe that addressing this problem and enhancing the functionality and user experience of FlutterFlow will benefit not only me but also the entire user community. By offering constructive feedback and highlighting the challenges I have faced, I hope to contribute to the ongoing development and refinement of this valuable tool.

### Visual documentation

In my detailed bug report, I have provided a clear explanation of the issue, the data model, the methods I have tried, and the expected behavior. I believe this information should be sufficient for the developers to understand and reproduce the issue. However, if the developers feel that visuals such as images or video demonstrations would be helpful for further clarification, please do not hesitate to request them, and I will be more than happy to provide the necessary visuals to assist in resolving this issue.

### Additional Info

The solution to update a specific key-value pair within an array of maps stored in a Firestore document involves using the arrayUnion and arrayRemove methods. However, these methods might not be suitable for your use case because they do not allow updating a specific element in the array directly.

The recommended solution is to use a different data structure, such as a map of maps, where each map within the top-level map has a unique key. This will allow you to update the nested map's key-value pairs directly without affecting other maps.

Firestore arrays can be useful for storing simple lists of data or category-type data, but they have some limitations when it comes to complex data models. Arrays in Firestore are ordered, and it is not possible to directly update or delete specific elements in an array without knowing their indices. This can be a challenge when dealing with complex data models, especially when you need to update or delete elements based on their content.

Using a map data type can be a better choice for complex data models, as it allows you to store key-value pairs and perform updates and deletions based on keys directly. This makes it easier to manage and query complex data structures.

While Firestore provides custom data types, wrapping them in an array might not be the best choice for certain use cases. If the data model requires frequent updates or deletions based on the content, using a map data type or a map of maps might be more suitable.

In summary, Firestore arrays can be useful for certain scenarios, but for complex data models that require flexible querying and updating, using maps or a combination of maps might be a better choice.

Suggestions: 
1. Allow users to choose between different Firestore data types, such as "List" and "Map", when defining the document schema in the Firestore collection builder.

Here's a proposed solution:

1. Change the data structure of the Firestore document to use a map of maps instead of an array of maps. Each nested map should have a unique key.
2. To update a specific key-value pair within a nested map, use the update method on the document reference, and provide the path to the nested key-value pair using dot notation.

For example, if your document structure looks like this:

`{
  "mapOfMaps": {
    "map1": {
      "key1": "value1",
      "key2": "value2"
    },
    "map2": {
      "key1": "value3",
      "key2": "value4"
    }
  }
}
`

To update the value of **key1** within **map1**, you can use the following code:

`documentReference.update({'mapOfMaps.map1.key1': 'newValue1'});
`
This approach allows you to directly update a specific key-value pair within a nested map without affecting other maps or their key-value pairs.

### Environment

```markdown
- FlutterFlow version: v3.1 - Flutter 3.7.3
- Platform: Web, mobile, windows, mac, linux, smart watch, smart tv
- Browser name and version: chrome latest version
- Operating system and version affected: Windows 11 latest version
```

**Comment by hariprasadms** [comment] 2023-04-23 10:41
Hi @wednesdei - Thanks for the details. In general the Datatype feature is really a powerful one and it can fit for most of the app use-cases in the real-world. However, we do agree that there are still few specific nature of use cases may not be possible to achieve in direct approach, in that case we suggest to use custom code. The combination of custom code with any inbuilt in features of FlutterFlow is more powerful and users can achieve any complex use-cases. Hence we suggest to use custom code.

We can certainly look into your specific issue, if you can set up a blank project with reproducing the exact issue you are talking above. Share bug report code of the project as well. As per our recent issue tracker instructions, blank project is more important to investigate edge case issues. Please provide the details.

**Comment by wenkaifan0720** [comment] 2023-07-06 18:29
Hi @wednesdei. Thank you for the detailed suggestions and proposal. I believe handling nested map is tricky for both FlutterFlow and Firebase. The recommended workaround for now is to define custom Data Types in FF. But we will certainly look into the possibility of supporting map in the future.

Since this is more of a feature request rather than a bug report. I will close this issue for now.

**Closed by wenkaifan0720** 2023-07-06 18:29 UTC
Labels: closed: feature request, type: feature request

**Comment by frankogenrwoth** [comment] 2025-07-27 20:39
This still does not work in  my case i have a messages field that takes in an array but when i update the array from my app the changes in the data do not reflect on fire store. 

It has been over two weeks since this issue was closed if possible can it be reopened because i am not forced to update the messages over an api
