### ISSUE TITLE
Resetting stopped timer triggers "On Timer End" events

### ISSUE THREAD

**Issue by albluwi1987** [FlutterFlow/flutterflow-issues#1217] opened 2023-08-04 23:49 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

**Hi,
In my app (Home Page) there is a Timer Widget and I've added (On Page Load Action) which is ((Starting that Timer widget)) and On Timer Widget "On Timer End Action" I've put 2 actions first to reset the timer and second to start the timer again AND the issue is after the timer end its Freezes/Broken the app and I can't Scroll in it or click on any buttons and to make it work again I have to close the app and open it again**
<img width="1353" alt="‏لقطة الشاشة ١٤٤٥-٠١-٢٠ في ١٠ ٢٧ ٢٩ م" src="https://github.com/FlutterFlow/flutterflow-issues/assets/94494001/86eea514-43f5-447e-b27d-b1464b8fdb04">
<img width="1326" alt="‏لقطة الشاشة ١٤٤٥-٠١-٢٠ في ١٠ ٢٧ ٣٦ م" src="https://github.com/FlutterFlow/flutterflow-issues/assets/94494001/bdfd21d9-2115-435e-90c3-f0c3d9f04eae">

Note: I've tested the app on run mode also on real device (TestFlight)
Any Help will be appreciated, Thanks

### Expected Behavior

It supposed to work properly and start the timer again without any issues

### Steps to Reproduce

1. Create new page 
2. Add Timer Widget
3. Add action in (On Page Load) that start the Timer widget
4. On Timer widget Add 2 Actions in (On Timer End) first: Reset Timer, second: Start Timer
5. Run the App

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oz/Hqx89grs9J1s/IdfoxnSQWQkx/bbsrm8pOFC0YGOvyPbJ/duD7dhFtXemoY0NhHGGWpE8G7sGMiuHXG8E4GzeVc7V8+c1cFDvjRXq8RZiNDKudPXZ9P+VRG3Km15m3qxFSVeptWkIFwFzzPemtbAXtJ5+/Zwh9f6PHaOI=

### Context

Its a Critical Bug for me because in my app many features needs Timer to work properly and Now I've stopped my app publishing until this issue fixed

### Visual documentation

Already Uploaded in (Current Behavior) section

### Environment

```markdown
- FlutterFlow version: v3.1 (released August 3, 2023)
- Platform: web
- Browser name and version: Chrome 115.0.5790.114
- Operating system and version affected: macOS Ventura 13.4.1 (c)
```

**Comment by albluwi1987** [comment] 2023-08-05 18:20
update: I've deleted the actions at Home Page that related to location (check location enabled, request permission) But still the Freeze after several hours on real device!

**Comment by kevintonb** [comment] 2023-08-14 16:27
Hey @albluwi1987 , thank you for reporting this issue. I was able to reproduce the bug following the steps listed above.

**Comment by aemelyanovff** [comment] 2023-09-18 19:49
This seems to be a bug in a pub.dev package that we use, `stop_watch_timer`. I created a pull request there: https://github.com/hukusuke1007/stop_watch_timer/pull/37

**Comment by aemelyanovff** [comment] 2023-09-21 15:04
Fixed in the next update!

**Closed** 2023-09-21 15:04 UTC
Labels: type: bug, status: confirmed, priority: medium
