### ISSUE TITLE
Cant clear DocRef type LocalState value

### ISSUE THREAD

**Issue by tothati90** [FlutterFlow/flutterflow-issues#219] opened 2022-12-12 14:49 UTC
I've seen a similar issue here, and it's said it has been already fixed, but for me it's still not working when I try to clear the value of a docref type local state.

## Expected behavior (required)
The local state (docref type) should be set to null on clear value action. I want to be able to set a variable to null.

## Current behavior (required)
The local state value doesn't cleared

## To Reproduce (required)
1. Create a docRef type local state
2. Add it a value using an action
3. Use another action to clear it's value
4. Observe that the value still not cleared

### Bug Report Code
ITFfl8/625NOm99D15SJYMcxniE4NW0cTOURiO0bFDsdF4iuPOxzaeD8VE5pXfHgdAhDKEWKgkwdwd3Fj+GTVsYBAw+aGdl8zYd5EDvzfGHkEuzyT+3IHDUHZbsSXTTm

## Context (required)
Trying to use this field to show/hide a widget.

## Your environment

* Version of FlutterFlow used: v3.0 dec 11
* Platform (e.g. Web, MacOS Desktop):  Web
* Browser name and version:  Chrome latest
* Operating system and version (desktop or mobile): Windows 11

](https://github.com/FlutterFlow/flutterflow-issues/issues/204)

**Comment by bulgariamitko** [comment] 2022-12-12 17:07
Duplicated issue - https://github.com/FlutterFlow/flutterflow-issues/issues/204

**Comment by Pepino-GR** [comment] 2022-12-12 20:09
Hi tothati90,

in the actual versions, the issue seems to be fixed. To reproduce it, can you please share us a demo project(public) to see how it is set inside your environment?

**Comment by Pepino-GR** [comment] 2022-12-13 10:55
Hi tothati90,

I can now reproduce your issue in the current version. It is a bug and needs to be fixed. Thanks for your notification.

**Comment by tothati90** [comment] 2022-12-13 11:42
@Pepino-GR thank you!

**Comment by agreaves** [comment] 2022-12-22 22:36
Thanks for the bug report. This is now fixed and deployed!

**Closed by agreaves** 2022-12-22 22:36 UTC
Labels: status: duplicate, status: confirmed
