### ISSUE TITLE
Custom code pane does NOT show code

### ISSUE THREAD

**Issue by matmaq1** [FlutterFlow/flutterflow-issues#2066] opened 2023-12-27 12:58 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Custom code pane does NOT show code maybe 95% of the time. Rarely, from time to time it shows code correctly, but I don't know what (if anything) makes it work externally and what doesn't. The editable text window does not show up. I can click code runner and it correctly shows the errors that are underneath (if any).
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/25862703/63fe2534-8618-4951-ade1-f044bd1448ef)

### Expected Behavior

I can view, edit and save the code in custom tab.

### Steps to Reproduce

1. log in
2. open new blank project
3. go to code pane
4. no code in the code pane :(

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

rightclickdoesntworkonmywidgettree

### Context

I'm trying to debug my code

### Visual documentation

--

### Additional Info

--

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: web
- Browser name and version: edge
- Operating system and version affected: w11
```

**Comment by hariprasadms** [comment] 2023-12-27 16:02
Are you still experiencing the issue ? I have tested it recently I can confirm that custom code can load with no issues.

**Comment by matmaq1** [comment] 2023-12-27 16:33
Maybe it's something to do with Edge, I use most of the time. Chrome seems to be handling it fine, so I'll switch my tooling for now

**Comment by hariprasadms** [comment] 2023-12-28 12:09
Thank you for confirming. Since Chrome is the recommended browser for FlutterFlow, and the issue is not reproducible in Chrome, I am closing the issue. Appreciate your contributions. Thanks

**Closed** 2024-02-05 13:39 UTC
Labels: status: can't reproduce, closed: not a bug, Custom code
