### ISSUE TITLE
Inconsistent back navigation behaviour due to incorrect parsing of a String or Supabase row passed as a page parameter

### ISSUE THREAD

**Issue by wolfhoundgelert** [FlutterFlow/flutterflow-issues#2098] opened 2024-01-04 09:52 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hi guys!

I faced an issue where my web app crashed when I tapped on Android or Chrome browser back button.

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/bbd92f98-52d5-4f75-90b5-48d22fecf2a1/8660996c-f601-4d60-9717-f2608eae1d85?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iYmQ5MmY5OC01MmQ1LTRmNzUtOTBiNS00OGQyMmZlY2YyYTEvODY2MDk5NmMtZjYwMS00ZDYwLTk3MTctZjI2MDhlYWUxZDg1IiwiaWF0IjoxNzA3MTQyNzU0LCJleHAiOjMzMjc3NzAyNzU0fQ.ntrDtknoXvi6Hrzy3S0vubFYGcW-70cLxLDQAGvFkPU)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/6e129888-9693-4454-b92f-bf99b183232e/7abf7ce1-97ff-48f5-af3c-cde918704f90?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82ZTEyOTg4OC05NjkzLTQ0NTQtYjkyZi1iZjk5YjE4MzIzMmUvN2FiZjdjZTEtOTdmZi00OGY1LWFmM2MtY2RlOTE4NzA0ZjkwIiwiaWF0IjoxNzA3MTQyNzU0LCJleHAiOjMzMjc3NzAyNzU0fQ.PrL6NRZnIyf_vjAM6sJ4a6JsLQe8jSGi5-EHCWKgSSE)

Originally, I navigated between pages which receives Supabase rows as page parameters and the app died each time I used Android or Chrome browser back button.

The investigation bring me to the conclusion that the root cause is an issue with parsing JSON-s which contains "&" symbol in strings likes "Horns & Hooves". I checked the same for strings and found another issue with the ampersand: despite the fact that the navigation was ok, received values were corrupted and cut to ampersand.

I prepared a test project where 4 buttons on the Home page. These buttons navigate to 4 pages where 4 different back button's behaviours can be observed.

[https://app.flutterflow.io/run/v6pzsvIuOiXcsqjVxiR9](https://app.flutterflow.io/run/v6pzsvIuOiXcsqjVxiR9)

I performed the same simple test in the Chrome browser on each page:
click btn2 to open a new page -> click back to the prev page -> click back to the home page

The same test provides the same result on an Android device with Android back button.

The first page receives strings without ampersand and it works as good as a standard, others are not so lucky.

**Important: back button from navbar always works perfectly, the problems only with Chrome and Android back buttons.**

You can always use back button from navbar to navigate home during the tests.

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/18492fa5-e095-462a-b9bb-8791b5d42101/27c8f359-d01a-4060-a51c-9564ca474725?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xODQ5MmZhNS1lMDk1LTQ2MmEtYjliYi04NzkxYjVkNDIxMDEvMjdjOGYzNTktZDAxYS00MDYwLWE1MWMtOTU2NGNhNDc0NzI1IiwiaWF0IjoxNzA3MTQyNzU0LCJleHAiOjMzMjc3NzAyNzU0fQ.jTtuiMHnZKCdUVuKZCZIu7dY_xz9KgIphPF8Eb2ZVdI)

So, in the worse scenario, when I pass Supabase row with "&" in my real application, the app completely dies with the error:

> Error deserializing parameter: FormatException: SyntaxError: Unterminated string in JSON at position 15 (line 1 column 16)

I found this similar issue [https://github.com/flutter/flutter/issues/23365](https://github.com/flutter/flutter/issues/23365) and there was a solution to add `transform(json.decoder)`:
`return response.transform(utf8.decoder).transform(json.decoder).listen((contents) {`
Looks like it was missed for passing parameters on backward handlers.

### Expected Behavior

Navigation is consistent, values are not cut or nulled, apps don't crash.

### Steps to Reproduce

[https://app.flutterflow.io/run/v6pzsvIuOiXcsqjVxiR9](https://app.flutterflow.io/run/v6pzsvIuOiXcsqjVxiR9)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4elvLlx41gobhY0JDUd/paniAXQz47ULxM08N+QgwjCLLuP6QDOuj+QHZVOMO/dFY3OlmI8D4f3OiPhuD9CMIHPiiZfa5q1rlqFArxRkG5eLatEsyWYXJQAcdWG2GHzbe7qyNAFPZYWU4772C6H+uubCjvQZzFIVQvAv2LIq7Xon+rKxzCXn0Jg1ZSfCvr

### Context

I use Supabase rows as parameters for pages and back navigation crashes my application. I thought to use just strings as parameters but there's an issue too. For instance, I can't pass a company name "H&M" because it will be corrupted and cut to "H".

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/0b505d25-3375-4b17-9fd7-321773b087de/679c46bd-f8d8-4661-867d-27cffd8c0f67?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wYjUwNWQyNS0zMzc1LTRiMTctOWZkNy0zMjE3NzNiMDg3ZGUvNjc5YzQ2YmQtZjhkOC00NjYxLTg2N2QtMjdjZmZkOGMwZjY3IiwiaWF0IjoxNzA3MTQyNzU0LCJleHAiOjMzMjc3NzAyNzU0fQ.2CpE7WzjRl4Yj_rhpWqqjghOEcPBTtS9u8pOvUITXOA)

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: FlutterFlow v4.0 released December 29, 2023 Flutter version is 3.13.7
- Platform: Web
- Browser name and version: Chrome Version 120.0.6099.130 (Official Build) (64-bit)
- Operating system and version affected: Win10, Android 10
```

**Comment by takashiff** [comment] 2024-03-12 22:37
Hi @wolfhoundgelert, I apologize for the delayed response. Thank you for taking the time to provide a very detailed bug report, this helps our team greatly in finding and resolving the issue, and we really appreciate your support.

I've taken a look at the blank project you have provided, and I see that it is not behaving as intended. However, I am currently unable to reproduce the bug myself, which leads me to suspect it may be an issue with the Supabase setup. Here is a test table I have set up with an ampersand character, and I did not run into any issues with this. If you don't mind, could you provide a screenshot or further information on how your Supabase is configured? Thanks
<img width="416" alt="Screenshot 2024-03-12 at 3 33 34 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/134453477/91d5798f-a36d-49d2-bc37-4ed9c10cc452">

**Comment by leighajarett** [comment] 2024-04-02 16:58
I am going to close this issue since we haven't heard a response. Please open a new issue with steps to reproduce if this happens again. Thanks!

**Closed by leighajarett** 2024-04-02 16:58 UTC
Labels: waiting for user response, needs technical triage
