### ISSUE TITLE
Ghost errors being thrown left and right when trying to deploy to GitHub or download locally.

### ISSUE THREAD

**Issue by jasonNumar** [FlutterFlow/flutterflow-issues#3021] opened 2024-05-30 21:25 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Project will not deploy to GitHub or download locally. No visible errors being identified in the project issues. Tried to remove the widgets causing error from the stack trace, only to get more errors throughout. Please fix or rollback asap.

### Expected Behavior

Deploy to GitHub.

### Steps to Reproduce

Can't seem to identify the things that are causing the error, but it is preventing GitHub deployments and downloads locally, so may be something to do with that process.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

n/a

### Context

Can't deploy.

### Visual documentation

N/A

### Environment

```markdown
- FlutterFlow version:  v4.1.54
- Platform: Mac OS (Flutterflow for desktop)
- Browser name and version: n/a
- Operating system and version affected: Mac OS
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by msusviela** [comment] 2024-05-31 13:56
Hey @jasonNumar, Thanks for your report, So sorry you are experiencing this issue. I was not able to reproduce this on a blank project, but it is replicable on yours. That's why I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. Thanks so much!

**Closed** 2024-06-06 16:00 UTC
Labels: closed: support request
