### ISSUE TITLE
"Error getting Supabase schema API response" on a self-hosted Supabase instance

### ISSUE THREAD

**Issue by roba-be** [FlutterFlow/flutterflow-issues#3657] opened 2024-08-21 04:14 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When trying to connect to a self-hosted Supabase instance, I am getting the following error:
**"Error getting Supabase schema API response. Please check your connection info and try again".**
I am able to access Supabase on a subdomain with port 8000 correctly mapped
I have SSL installed.

![error-ff-supabase2](https://github.com/user-attachments/assets/f01e9622-93cb-4d36-8dcf-31c340b01709)
![error-ff-supabase1](https://github.com/user-attachments/assets/cc2e53f9-7835-4ebd-86d2-a99b29242afd)

### Expected Behavior

What's expected is that I should connect to the supabase instance.
https://www.youtube.com/watch?v=oOFYbttALP8&t=18s

### Steps to Reproduce

1. Settings
2. Integrations -> Supabase
3. Enter API URL and ANON Key
4. Get Schema

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

TERREFMCFGEFDFKZDKCMVVVSDVLSDVMDLVMSDLVSDLVLSDVL

### Visual documentation

![error-ff-supabase2](https://github.com/user-attachments/assets/2e4acd53-0620-415d-8452-5d0bff390e7c)
![error-ff-supabase1](https://github.com/user-attachments/assets/4a6178b7-db95-4965-a55f-393db1d3438f)

### Environment

```markdown
- FlutterFlow version: v4.1.83+
- Platform: Web
- Browser name and version: Chrome Version 127.0.6533.120 (Official Build) (64-bit)
- Operating system and version affected: Ubuntu 24.04, Windows 10
```

**Comment by paulperez-dev** [comment] 2024-08-21 14:07
Hi @roba-be! This is more a configuration issue than a bug, and because this tracker is only used for reproducible bugs, I am closing this issue.

You can also ask the [community ](https://community.flutterflow.io/ask-the-community)for help.

**Closed as not planned** 2024-08-26 00:02 UTC
Labels: closed: not a bug

**Comment by mythyme-app** [comment] 2024-09-11 10:07
I also have this issue, all configurations are OK! (Supabase cloud! )

I've created 3 times a new empty projects in FF and SB and "get schema" is giving an error each time
Please help

**Comment by uchemanuels** [comment] 2024-09-11 14:24
Me too. Supabase Cloud

**Comment by cpeyrusse** [comment] 2024-09-11 15:32
I also  have the exact problem. This is reproductible!

**Comment by paulperez-dev** [comment] 2024-09-27 18:44
Hi @myuthyme-app, @uchemanuels, @cpeyrusse,

Could you kindly confirm if this issue is still occurring in the latest version (5.0)? We want to ensure everything is working smoothly for you.

**Comment by bissan-sameeh** [comment] 2026-02-12 22:51
same error happens with me now

**Comment by Jiji12345** [comment] 2026-02-17 15:31
I have the same problem

**Comment by katerinechi** [comment] 2026-02-27 16:42
I have the same problem. I followed the youtube manual and the documentation, I have RLS off, and FlutterFlow is not connecting to Supabase.
Error getting Supabase schema API response.
Please check your connection info and try again.
