### ISSUE TITLE
Custom style on text component ignore properties setter 

### ISSUE THREAD

**Issue by mrbash** [FlutterFlow/flutterflow-issues#51] opened 2022-10-23 07:58 UTC
## Expected behavior (required)
I want to set text styles properties on a text component with custom style using the set feature.
<img width="306" alt="image" src="https://user-images.githubusercontent.com/2493506/197380555-afe9681e-5004-41d4-8af9-4f9b03476b5d.png">

## Current behavior (required)
The styles passed through the setter are completely ignored as you can see on below image of the code view of the componenent.
<img width="306" alt="image" src="https://user-images.githubusercontent.com/2493506/197380638-cdf5e23a-fa02-43bc-b046-6fac5ee4dcf5.png">

## To Reproduce (required)
1. Create new page
2. Add container widget
3. Add a Text Widget
4. Click on the container and convert to a component
5. Go on the edit component page
6. Add a component property "textColor" with type Color
7. Click on the Text Widget inside the component
8. Set "Custom" on "Theme Text Style"
9. Set Text Color to "textColor" parameter
10. Click on the View Code, go to the component code and see that the Text Widget doesn't set the text color using the textColor parameter

Code can be included in this section if it is relevant to reproducing the bug. 
-->

1.
2.
3.
4.

## Context (required)
I wanted to set Text Color on a Text Widget of a component passing a color by parameter. I've noticed that it also applies to other text styles properties, when Custom Theme is selected. This behaviour don't happen when a Theme style is applied, for instance when "Body Text 1" is applied.

## Your environment

* **Bug Report Code:**
* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by MizzUp** [comment] 2022-10-23 08:03
Can you try again (with chrome) and refresh your page before try again to view your code. I reproduced without any error

**Comment by mrbash** [comment] 2022-10-23 08:16
> Can you try again (with chrome) and refresh your page before try again to view your code. I reproduced without any error

Yes, no success.

I uploaded a video reproducing steps on a brand new project: https://youtu.be/E1xMG8j2U4E

**Comment by bulgariamitko** [comment] 2022-10-24 12:54
I can't reproduce this error. I just did exactly the same thing and my code in Code View is the correct one

my page code
 ```
body: SafeArea(
        child: GestureDetector(
          onTap: () => FocusScope.of(context).unfocus(),
          child: DsdcWidget(
            cdscds: Color(0xFFE62525),
          ),
        ),
      ),

```
my component
```
Widget build(BuildContext context) {
    return Container(
      width: 100,
      height: 100,
      decoration: BoxDecoration(
        color: FlutterFlowTheme.of(context).secondaryBackground,
      ),
      child: Text(
        'Hello World',
        style: TextStyle(),
      ),
    );
  }
```

**Comment by mrbash** [comment] 2022-10-24 13:29
If you set the text color of the Text widget using the `cdscds` parameter you should see somethings like this
```
      child: Text(
        'Hello World',
        style: TextStyle(
          color: widget.cdscds
        ),
      ),
```
and not this
```
      child: Text(
        'Hello World',
        style: TextStyle(),
      ),
```

**Comment by mrbash** [comment] 2022-10-26 06:07
any updates?

**Comment by agreaves** [comment] 2022-11-03 00:35
Thanks for catching this! This will be fixed upon our next release.

**Closed by agreaves** 2022-11-03 00:35 UTC
Labels: status: can't reproduce
