### ISSUE TITLE
HTMLView does not support border-radius

### ISSUE THREAD

**Issue by krkxone** [FlutterFlow/flutterflow-issues#1057] opened 2023-06-28 06:54 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Border radius does not seem to be recognized in HTMLView.

### Expected Behavior

The red border should have a radius of 10px.

### Steps to Reproduce

1. Drag HTMLView to canvas
2. Set content to `<div style='border:2px solid red;border-radius: 10px;'>container</div>`

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kjcrqx4lgocNY15DtbflFu2MWQlAiTL07ttYbZxUjIuPtBJh/Yc+lXBNBTsioSlNhHGCbpGMCpd7RiPDxIME5NTeVboRA1c9cZhbKTXq8RLKJCqqOTnclDeRnJna54auzux0mNstiSiUjwEzzPe7IThTBN5+/Zwh9f6PHaOI=

### Context

I am creating an app that loads HTML content from Firestore. Some of the content should be displayed in a rounded container. 

### Visual documentation

<img width="1268" alt="Screenshot 2023-06-28 at 08 47 40" src="https://github.com/FlutterFlow/flutterflow-issues/assets/10206775/690e9f95-2fc1-4c30-b822-88051676e61a">

<img width="1527" alt="Screenshot 2023-06-28 at 08 54 13" src="https://github.com/FlutterFlow/flutterflow-issues/assets/10206775/b496813a-ece1-4553-af27-92d5f413b600">

### Environment

```markdown
- FlutterFlow version: v1.1.87
- Platform: FlutterFlow for Mac OS
- Browser name and version: Google Chrome 114.0.5735.133
- Operating system and version affected: MacOS Ventura 13.4.1 (MacBook Pro 2021)
```

**Comment by wenkaifan0720** [comment] 2023-06-28 21:11
Hi @krkxone. This is due to the limitation of the html package (https://pub.dev/packages/flutter_html). I would suggest you try the WebView widget, with `Load content from HTML` set to true.

Since this is not a bug on our end. I would close this issue for now. Thank you.

**Closed by wenkaifan0720** 2023-06-28 21:11 UTC
Labels: closed: not a bug, status: not a bug
