### ISSUE TITLE
Enum as filter for Firestore is not working

### ISSUE THREAD

**Issue by markokosticdev** [FlutterFlow/flutterflow-issues#1840] opened 2023-11-13 14:04 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have changed a status field in a collection from String to Enum and when I try to filter it using Firestorm Query I get:
`[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument: Instance of 'RowyStatus'`
Note: RowyStatus is my Enum that has values Draft, Publish, and Archived.

This:
```
intentionsResult = await queryIntentionsRecordOnce(
      queryBuilder: (intentionsRecord) => intentionsRecord.where(
        'status',
        isEqualTo: RowyStatus.Published,
      ),
    );
```

Should be:
```
intentionsResult = await queryIntentionsRecordOnce(
      queryBuilder: (intentionsRecord) => intentionsRecord.where(
        'status',
        isEqualTo: RowyStatus.Published.name,
      ),
    );
```

### Expected Behavior

Retrieving data :)

### Steps to Reproduce

1. Create Firebase schema with enum field
2. Use Firebase Query action to get it by using the enum field as a filter

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sj8nfvJNPn7xe0KrUcvlR/SQRH2Y9ROYwscp/bxIgGIDzPOw+ZPXsXxZCQumgT2NLfESmmmYGpvDqvfDqGPcnB06Yf7ZnzrViFwziUmqua5OBPKu0Y2hSQONgCGKv1J+zghRRPrZfSXgtwGeMO+yXYA3dCZjHImdISq/LZO4=

### Context

I tried to filter Firestorm collection by Enum

### Visual documentation

`[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument: Instance of 'RowyStatus'`

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Android/iOS
- Browser name and version: Chrome 119.0.6045.105
- Operating system and version affected:
```

**Comment by davidoort** [comment] 2023-11-17 19:21
We're having the exact same issue. In our case, the code needs to go from
`.where(
    'sender_type',
    isEqualTo: SenderType.RECEIVER_USER,
  )`
  to 
  `.where(
    'sender_type',
    isEqualTo: SenderType.RECEIVER_USER.toString(),
  )`
  
  Should be an easy fix! @agreaves

**Comment by mikemcclelland** [comment] 2023-11-22 19:30
I have also verified this issue. When I try to debugPrint the enum value from my document I get null.

**Comment by trevorFields** [comment] 2023-11-29 06:51
also having issue with enums, from the code it looks like the enum functions to convert to string / back to enum arent always in the code correctly (example is when you set an enum as a firestore field, it should be converted to string).

i know yall will fix this so im using workaround getting ready for this awesome feature to be primetime!

**Comment by sanchez-gonzalo94** [comment] 2023-12-06 15:03
Same issue here

**Comment by carlosgonzalezucv** [comment] 2023-12-19 12:28
same issue here

**Comment by tadamtech** [comment] 2023-12-21 04:27
Same issue here, I cannot create document with enum fields.

**Comment by nicbyron** [comment] 2023-12-22 08:03
Same issue here. Just switched several things to enums and now I'm blocked on filtering and creating with enums

**Comment by joveptesg** [comment] 2023-12-23 06:30
Same issue

**Comment by ryanspiffy** [comment] 2023-12-27 05:19
Also ran into this issue while working with custom DataTypes that included enums as fields.  A temporary workaround I used was duplicating the field as type Integer in the DataType, then swapping over my code to use Constants (of type integer) in place of an Enum.  When the FlutterFlow team fixes this, it should be a quick swap back to Enums.  This worked fine for saving my custom DataTypes to Firebase, and I can query/filter for them based on the Constants now.

**Comment by ToddHerron** [comment] 2023-12-27 21:10
Same issue. 

- Firestore enum fields cause CREATE DOCUMENT action to hang. (Custom function required to work around.)
- Reads of enum fields from Firestore return null values instead of enum values (the casting from an String Type to enum Type when coming from Firestore seems to fail)

**Comment by agreaves** [comment] 2023-12-29 23:16
Hey folks! Thanks so much for reporting this issue and apologies for the long delay in getting to it. I've reproduce this issue and have a fix for it, which will be released shortly!

**Closed by agreaves** 2023-12-29 23:16 UTC
Labels: type: bug, status: confirmed, priority: medium

**Comment by nurzhands** [comment] 2024-01-02 19:33
Hello, thanks for fixing, is the fix released by now? Having similar issue.

**Comment by trevorFields** [comment] 2024-01-05 17:41
also wondering if anyone has tested this and if the fix is out?

**Comment by pabluez** [comment] 2024-01-09 00:09
I just tested and can't get a query filtered using an Enum field.

**Comment by fettespferd** [comment] 2024-03-13 21:40
Me neither. I tested using a Query Collection with an enum filter. One properties is a list of enums. I can not filter according to one enum.
