### ISSUE TITLE
Content sent in JSON body in API Call is not the same as entered when configuring API Call

### ISSUE THREAD

**Issue by JunkMyFunk** [FlutterFlow/flutterflow-issues#62] opened 2022-10-27 14:19 UTC
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
Creating an API Call and setting Body to JSON, I expect the body content entered to be sent when the API Call is made using Test mode.

## Current behavior (required)
The API Call body content is valid JSON and the "Test API Call" button sends the correct content to the API and receives the correct response. However when running the app in Test mode, the content sent in the API call is not identical to what was entered in the API Call settings. The problem is related to the use of escaping slashes required in order to use double-quotes inside a string value in the JSON body. The body seems to be re-parsed and stripped of slashes meaning the final body content differs from what is entered.

## To Reproduce (required)

1. Create a new API Call and set the method type to POST
2. Set the API URL to `https://en8zoqasagbcq.x.pipedream.net/` (or another API request bin of your choice)
3. Set the Body type to JSON
4. Enter the following into the body:
```
{
  "test": "The word \"work\" should be in double-quotes as they are escaped"
}
```
5. Go to Response & Test section and click Test API call.
6. Go to the [request bin](https://requestbin.com/r/en8zoqasagbcq/2Giity0iFq7gcPotqQxFQdu6KRN) and check the RAW content received matches what was entered into the API Call body (it should).
7. Save the API Call
8. Configure the app to trigger the API Call from a Backend Query on any page component
9. Run the app in Test Mode and cause the API Call to be triggered. 
10. Go to [request bin](https://requestbin.com/r/en8zoqasagbcq/2Giity0iFq7gcPotqQxFQdu6KRN) again and check the RAW content in the latest request received. You will see the double-quotes around the word "work" are no longer escaped by slashes making the JSON body invalid, so it cannot be parsed by the receiving API.

## Context (required)
The backend API we wish to use requires filter parameters to be sent in the JSON body of a POST request. Without being able to use quotes we can't query the API correctly and can only obtain an unfiltered list of all records. This effectively prevents us from being able to use FlutterFlow with our backend API.

## Screenshots / recordings
https://www.dropbox.com/s/y7r3jj4z41ax39b/Screen%20Recording%202022-10-27%20at%2014.56.45.mov?dl=0

## Your environment

* **Bug Report Code:**
* Version of FlutterFlow used: 3.3.4
* Platform (e.g. Web, MacOS Desktop): Macos Desktop 12.6
* Browser name and version: Chrome Version 106.0.5249.119 (Official Build) (arm64)
* Operating system and version (desktop or mobile):

**Comment by bulgariamitko** [comment] 2022-10-28 07:15
Two thing I suggest you to try. 
- Send this String from Local State for example instead of hard code it in the API call and see if that works

I will make this as not a bug, because this can be easily fix by using single quotes instead of doubles.

**Comment by agreaves** [comment] 2022-11-02 19:55
This will be fixed next deploy, as we will now escape backslashes for the API body to make them work the same in the API Test as when you run the app.

**Closed by agreaves** 2022-11-02 19:55 UTC
Labels: status: wontfix
