### ISSUE TITLE
tabs widgets state is not independent

### ISSUE THREAD

**Issue by coach1990** [FlutterFlow/flutterflow-issues#3633] opened 2024-08-16 02:09 UTC
### Can we access your project?

- [x] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

in Tab widget, each Tab shows a page to us where we can create a unique design.
however, the states of these design/widgets are not unique. they overlap with other widgets that are in other Tabs.
I have made a video that explains this behavior, hope it helps. happy to add more inputs when needed.

### Expected Behavior

each widget in each Tab should have a unique/independent state so we can use them differently for unique purposes.

### Steps to Reproduce

Please use my project called, 'Bug Project' and follow the steps as show in in the Video.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sls/l6otPvsdG1ZDuc8dB/TsvHEwgap0kscp/bxIgGIDzPOw+ZPXsalFoYMjgT1V+I0SmmmQx/srqidmWL/ACFw2afb5awc1UZgvvTlite5OBDqiOdEdBM9tUC2GM5pjZkxZ5HLFucl4s7U6yG+/KUXTrHu/AIndISq/LZO4=

### Visual documentation

https://drive.google.com/file/d/160mM2E6SBD0raDcQDyjjjXt4zVnNw2L3/view?usp=sharing

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.82+ released August 7, 2024 Flutter version is 3.22.2
- Platform: Desktop App Windows
- Browser name and version: Microsoft Edge Version 127.0.2651.74 (Official build) (64-bit)
- Operating system and version affected: Windows 11 Home Single Language , 23H2
```

**Comment by Alezanello** [comment] 2024-08-16 12:51
Hello!

Yes, this is a known issue, and the team is actively working on it. The problem isn't with the Tabs themselves but rather with the Create Account action.

Currently, you can only have one Create Account action across the entire project. If you edit the Create Account action in one tab, it automatically updates the other tab as well.

Even if you separate the Create Account process into different pages, it will still behave as you demonstrated in the video.

As a workaround, I suggest creating a custom action that receives the necessary information from the different tabs and then creates the user and document accordingly.

This should help until the team implements a fix.

**Comment by Alezanello** [comment] 2024-08-16 12:52
This is the original post about this issue: [https://github.com/FlutterFlow/flutterflow-issues/issues/2606](https://github.com/FlutterFlow/flutterflow-issues/issues/2606)<br><br>So I'll close this one as a Duplicate and any further information please go to that issue!

**Closed as not planned by Alezanello** 2024-08-16 12:52 UTC
Labels: status: needs triage
