### ISSUE TITLE
Dropdown options reset when associated theme widget is updated

### ISSUE THREAD

**Issue by max-h-silverman** [FlutterFlow/flutterflow-issues#1615] opened 2023-10-09 16:31 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If a dropdown is attached to a theme widget, and the theme widget is changed, the options values are reset.

### Expected Behavior

Defined option and label values should stay as is.

### Steps to Reproduce

1. create dropdown theme widget
2. create page
3. add dropdown
4. set existing theme for dropdown
5. add some values & labels
6. re-save the theme widget

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Lqx41goflY0IfudsBQhQAkQzM8bYJMl9cadwsgIr3nPbAAP+r+VGdVOrC4e31AEFGWmlIz/8KLieHIFfQEOT6dQoNoz4d2WjvybDmQVpDQDajtYHdTO+5NGlCB16az2yYlVclec1Yhw1r/cq3qNleeY8aSfxBlZ7vfcPo=

### Context

I had to re-enter dozens of pre-set options and it caused issues for some of my users!

### Visual documentation

<img width="304" alt="Screen Shot 2023-10-09 at 9 18 52 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/147427658/a526d881-bcd0-4c66-b1f9-63e691c04a14">

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: web
- Browser name and version: chrome 117.0.5938.149
- Operating system and version affected: macOS 11.7.10
```

**Comment by hariprasadms** [comment] 2023-10-10 10:22
Hi @max-h-silverman - I looked at your project and tested above steps. I can confirm that as per current design it is working as expected. 

When you create a dropdown theme with available properties in the theme wizard, those properties will be copied over when the theme is applied for a dropdown widget on the page. Technically this is the main purpose of the theme widgets. However once the theme applied, you can create options and its values in the page based on your project need.

https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/e0764265-4286-4d98-886b-396a96d7499b

**Comment by hariprasadms** [comment] 2023-10-11 10:21
> Are you saying that the expected behavior is that if you change, for example, the text color of a dropdown theme widget the existing dropdowns that use that theme are supposed to clear all of the entered option values?
> 
> As it is, the option labels are actually maintained and the option values are cleared. There's no way this is the intended behavior!

Hi, Sorry for the confusion earlier. I can confirm that I can replicate the issue. Here is a quick video.

https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/3ad0803f-8e11-46ed-8ed2-96686bf79221

**Comment by victoriahuang1** [comment] 2023-10-19 15:15
Hi @max-h-silverman , thanks for the report. I checked in with the eng team and got their confirmation that this is not a bug. This is the current expected behavior (see tooltip warning for widget styling).

However, we agree that this is not the ideal behavior. This is a feature improvement that we will keep in mind, but I will be closing this as it is not a bug.

**Closed by victoriahuang1** 2023-10-19 15:15 UTC
Labels: type: bug, status: confirmed

**Comment by lordlothar99** [comment] 2025-01-28 11:51
Hi ! any update on this ?
I definitely agree with @max-h-silverman that this would be the intended behavior. We're talking about "widget styling" feature here --> any change should only have an impact on the style ("view"), never on the underlying data ("model"). 
Plus there is a bigger problem : the options defined on a dropdown widget using a "widget style" are not saved, even though there is no change on the "widget style" itself --> to make it clear : it is currently impossible to use widget styling with a dropdown with a "widget styling" defined.
