### ISSUE TITLE
Text widgets changes using "allow translations" are affecting other widgets on the same page/component

### ISSUE THREAD

**Issue by joaocordeiro-dotted** [FlutterFlow/flutterflow-issues#3374] opened 2024-07-11 19:21 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When editing a text widget parameter using translation via "allow translations," the new text inserted is affecting the translation of other widgets on the screen or within the component. This is happening multiple times, and it is quite exhausting.

### Expected Behavior

The text I input on a certain widget (using allow translations) should affect just the widget itself not others.

### Steps to Reproduce

1. Allow translations to the project
2. Create 2 different components
3. Add a string component parameter in each component
4. Insert a text widget on each component
5. Insert both components on a page
6. Pick one component and click "allow translations" on the text parameter (on the page)
7. Insert any random text
8. Wait/refresh the page and check the translation to the other widget

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEez/Hqx892pbwB0aX+acJsqwMwGkQ5a7sviu5+FBQaI+OrB+wxdsz7VFBDSOqHSlB6EGGkhloF/6HwioXLU/QoCyiCGaZ4+ZZpUxDgJXKQVq63Bsywen9ARMNWf2K10ba3hBFTKsphLnwC7Tiqf9mQY3qCf9qOYwx5e6fDbOY=

### Visual documentation

<img width="1185" alt="Captura de Tela 2024-07-11 às 16 20 00" src="https://github.com/FlutterFlow/flutterflow-issues/assets/168860662/a320ae77-9008-476a-8035-5f8d5dfeaf03">

### Environment

```markdown
- FlutterFlow version: 4.1.70
- Platform: Web
- Browser name and version: Google chrome
- Operating system and version affected: MAC OS
```

**Comment by joaocordeiro-dotted** [comment] 2024-07-11 22:14
Guys, it's getting worse and worse...I recently updated my flutterflow to FlutterFlow v4.1.71 and the result is a mess with all my translations on text widgets. They are just changing without any action from me!!!!

**Comment by joaocordeiro-dotted** [comment] 2024-07-11 22:16
Look at this, I can't work like that really... https://www.loom.com/share/dc7483a02b9a4110a0c39c64318fe5c5?sid=875a6c5d-a4ee-4612-9171-63a21cc71a07

**Comment by Alezanello** [comment] 2024-07-11 22:19
Hello!

Let me replicate this issue to see how it is triggered. Please give me a few minutes.

Thank you!

**Comment by lleo132** [comment] 2024-07-11 22:26
I've been experiencing the same problem for months, everything gets worse when we duplicate a widget with text and use the Mac or Windows version.

**Comment by Alezanello** [comment] 2024-07-11 22:40
@joaocordeiro-dotted 
I wasn't able to replicate this issue in a new blank project. It might be more related to larger projects with many translations. Let me try it in a bigger project, and I'll get back to you with more information.

@lleo132 
Could you please share a bug report code from a project where you are currently experiencing this issue? This will help us identify any patterns.

Thank you!

**Comment by joaocordeiro-dotted** [comment] 2024-07-11 23:00
@Alezanello I just recordered a full step by step to help you reproduce. The bug is insane...I'm doing it for the second time in a blank new project, just to show you guys the pain we have in a bigger project.

I just made this:
1. Created a component with a component parameter of type string
2. Inserted a text widget on the component that receives the parameter we created
3. On a new page, I inserted the same component 2 times
4. Allowed translations on both components on "text" parameter
5. Typed different texts in both components

The result is that it mixes the text between the two components.

Bug report code: ITEez/Hqx892pbwB0aX+acJsqwMwGkQ5a7sviu5+FBQaI+LnE4kAPOD8X1htWOqHeFZAJGeIkkYC0MLWi/HpGO1eBzmtGoB/zqhfUxDgJXKQVq63Bsywen9ARMNWf2K10ba3hBFTKsphLnwC7Tiqf9mQY3qCf9qOYwx5e6fDbOY=

video: https://www.loom.com/share/aa32edfef8fb4572bb3b25f76d5ea3d0?sid=488bde95-4f45-47a2-92e8-05e4ff3f2ec4

**Comment by joaocordeiro-dotted** [comment] 2024-07-12 15:07
@Alezanello any news on reproducing the bug?

**Comment by brunoconceicao** [comment] 2024-07-16 14:28
It happened to me too, I had to delete the widget and create it again

Windows 11, both on Chrome and Flutterflow installed

**Comment by invotally** [comment] 2024-07-18 23:42
Same problem here, it's becoming unsustainable, I can't create a text or button because it 'inherits' in the text field some other text used in another button in my app, it's like they are connected, because if I modify the new button, I'm also modifying the text from where it inherited that information, which generates a mess. I never know if I'm modifying another part of my app when I create a text or button, anything that has a text field to summarize...

**Comment by joaocordeiro-dotted** [comment] 2024-07-19 00:38
@invotally mention your case on this issue [2346 ](https://github.com/FlutterFlow/flutterflow-issues/issues/2346). They are solving it there!

**Comment by Alezanello** [comment] 2024-07-22 19:37
Hello!

Just to let you know, this issue is related to [GitHub Issue #2346](https://github.com/FlutterFlow/flutterflow-issues/issues/2346). It was confirmed as fixed about 30 minutes ago and will be released tomorrow. I will mark this issue as a duplicate of that one.

Best regards,<br>Azanello

**Closed as not planned** 2024-07-22 19:38 UTC
Labels: closed: duplicate
