### ISSUE TITLE
Not fixed still crashing on ios

### ISSUE THREAD

**Issue by TolinhoCTO** [FlutterFlow/flutterflow-issues#4905] opened 2024-11-15 11:52 UTC
Not fixed still crashing on ios

_Originally posted by @TolinhoCTO in https://github.com/FlutterFlow/flutterflow-issues/issues/4750#issuecomment-2478648332_

**Comment by Alezanello** [comment] 2024-11-15 12:36
Hello!

If the issue is still causing crashes, please continue the conversation on the original post you referenced. Providing more information, such as crash logs, videos, or any other relevant evidence, would be greatly helpful in identifying and resolving the problem.

**Closed as not planned by Alezanello** 2024-11-15 12:36 UTC
Labels: closed: duplicate
