### ISSUE TITLE
Choicechips events are not fired

### ISSUE THREAD

**Issue by jan-ysebaert** [FlutterFlow/flutterflow-issues#1321] opened 2023-08-21 11:24 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

[ChoiceChipProblem.pdf](https://github.com/FlutterFlow/flutterflow-issues/files/12395383/ChoiceChipProblem.pdf)

### Expected Behavior

see the attached document in the previous step

### Steps to Reproduce

see the attached document in the previous step.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfz/Hqx89isf1Y1pSJd+14jikWH2kcT5Azje0bTRIjGpTxP4YEdfWlX1pVZMO4T1Z+JkSmmTgf0+iPhvGTUu1fPgWWc6Zz/5FqaAzhTnKQe5OBO7u0XUBROJ9hCHbD5sKz2QlvLtZtL2AR2jqpfe6WVjDYGKWyImdISq/LZO4=

### Context

I want the choicechips to behave like expected.
Some are not visible when page is loaded.

### Visual documentation

see first attached document.

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: windows
- Browser name and version: google chrome (latest)
- Operating system and version affected: windows 11 (test session)
```

**Comment by jan-ysebaert** [comment] 2023-08-21 11:38
In a nutshell : If the choicechip was not visible when the page is loaded, the events are not fired once the choicechip is visible.

**Comment by hariprasadms** [comment] 2023-08-23 16:22
Hi @jan-ysebaert - We appreciate you bringing this up. I had a look at the project you provided above. I have looked the functionality of the choice chips. I can confirm that everything is working as expected. Your attempt to update the Choice Chips widget with app status is not set up as it should be. Hence you see the issue. Refer to the FF Choice Chips User Guide and try again. Thanks

**Comment by jan-ysebaert** [comment] 2023-08-24 07:15
Hi Hari,

Your collegae Henry said it was indeed a bug. I followed the guide by the way.
Can you correct the sample project I made so that it works (and I am convinced it is not a bug).

Thank you

Jan

Van: Hari ***@***.***>
Verzonden: woensdag 23 augustus 2023 18:23
Aan: FlutterFlow/flutterflow-issues ***@***.***>
CC: Jan Ysebaert ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [FlutterFlow/flutterflow-issues] Choicechips events are not fired (Issue #1321)

EXTERNE MAIL: Open enkel attachments of hyperlinks indien u de afzender vertrouwt.


Hi @jan-ysebaert<https://github.com/jan-ysebaert> - We appreciate you bringing this up. I had a look at the project you provided above. I have looked the functionality of the choice chips. I can confirm that everything is working as expected. Your attempt to update the Choice Chips widget with app status is not set up as it should be. Hence you see the issue. Refer to the FF Choice Chips User Guide and try again. Thanks

**Comment by sbis04** [comment] 2023-08-27 15:13
Hey, I was able to reproduce the issue, and the solution for it is to assign a "Value Key" to each of the ChoiceChip widgets, it will help Flutter identify the different ChoiceChip widgets properly.

<img width="1294" alt="Screenshot 2023-08-27 at 8 34 52 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/43280874/489e6a6a-68d6-4dcf-b141-09138948da2a">

In testing, I found another bug that would cause build failure if the Value Key is specified. I have already pushed the fix, but that will be available to you in the next FlutterFlow update!

The issue was occurring in the first place because the ChoiceChips that you are showing based on the Conditionals, they contain same length of options which is being predicted by Flutter as the same widget and that was causing conflict in firing the proper actions.

**Closed by sbis04** 2023-08-27 15:13 UTC
Labels: closed: not a bug
