### ISSUE TITLE
Border Radius: Lock resets automatically

### ISSUE THREAD

**Issue by krkxone** [FlutterFlow/flutterflow-issues#1704] opened 2023-10-25 19:40 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If you set the lock of the border radius of a container to not locked, it will be set back to locked as soon as you focus the container again.

### Expected Behavior

The lock should retain the actual condition

### Steps to Reproduce

1. Create a container
2. Click on the lock to set radius values individually
3. Set border radius bottom right to 20
4. Select an other widget
5. Select the container again
6. Lock is set to locked

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sjcrqx4lgoeVc7arAKcJB/WI7NmY4beckscpCbw4bIYj2P4lzY876P0ppTu3idHxEeGemp14e0vzmk/zDC/cnGAqCf4g4yM0MWznjfz6mM5eTF7uWZ3BAI+lQf1y54JizpiNNPtBhLE4d117zOPO9FzXdQb7RIEQ8Sq/LZO4=

### Context

Seems to be a mistake. Annoys only a little

### Visual documentation

<img width="484" alt="Screenshot 2023-10-25 at 21 37 45" src="https://github.com/FlutterFlow/flutterflow-issues/assets/10206775/87ee929e-cf5e-4628-be6c-15dd8b64847b">

<img width="437" alt="Screenshot 2023-10-25 at 21 37 48" src="https://github.com/FlutterFlow/flutterflow-issues/assets/10206775/a161472b-7f0a-4a88-af77-b600975aebe2">

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: Web App
- Browser name and version: Google Chrome 118.0.5993.70
- Operating system and version affected: MacOS 14.0 (23A344)
```

**Comment by wenkaifan0720** [comment] 2023-10-26 02:28
Hi @krkxone. This is the intended behavior. We analyzed the user behavior and found that people prefer to set equal border radius so the default behavior is locked. We can certainly make every widget remember the lock/unlock settings, but that might cause other kind of confusions, as you wouldn't really remember this setting for every widget. Before we can come up with a better solution, I would mark this issue as not a bug and close it. Thank you!

**Closed by wenkaifan0720** 2023-10-26 02:28 UTC
Labels: status: needs triage
