### ISSUE TITLE
Gradient text not working properly

### ISSUE THREAD

**Issue by nathanwright17** [FlutterFlow/flutterflow-issues#1504] opened 2023-09-22 11:12 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Gradient text is showing up white on mobile view after web publish. Desktop view has some gradient text only showing the first few characters, sometimes it shows more on mouse hover/click.

### Expected Behavior

Gradient text to show in full as gradient color

### Steps to Reproduce

1. Create gradient text
2. Publish to web
3. View on mobile device (iphone 13 pro max, iOS17.0) 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8kz8jfz5VNj7wF1s7uYO9anjgXNlw6bZZM0dV+awIYF4jyEoYEe8nBQBJWYsyceHxYfWeI8WYdp9XGkobTFPkXPiiCboROzah+Fg/KbHOjVq61PrmOVWhBM+ZgN0+Hzbe7ghZ4XcxfSF481E2QFdyXVhDvQYe3NUYnGsmIDL7/jGDnHTLOXn0Jg1ZSfCvr

### Context

Gradient is a big part of my brand identity, not being able to use it in text really limits the design impact.

### Visual documentation

![IMG_2295](https://github.com/FlutterFlow/flutterflow-issues/assets/131217364/b3992713-fee2-4d3c-a08a-6386452cb383)
![IMG_2294](https://github.com/FlutterFlow/flutterflow-issues/assets/131217364/57a2c455-3a4a-4912-97d3-ec703ca4d4ae)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: iOS mobile, desktop
- Browser name and version: chrome 116.0.5845.188
- Operating system and version affected: iOS 17.0, windows 11 pro
```

**Comment by sbis04** [comment] 2023-09-22 13:36
Hey @nathanwright17, thanks for reporting the issue! The gradient text issue is because of [this](https://github.com/flutter/flutter/issues/133134) `ShaderMask` issue coming from the Flutter engine. The issue will be fixed once the Flutter engine issue is resolved (and it only happens in web HTML renderer).

In the meantime, you can use [`CanvasKit` renderer](https://docs.flutterflow.io/settings-and-integrations/app-settings/web-publishing#4.-adding-general-information) which should resolve the issue. Since the issue is not on the FlutterFlow platform I would close it for now.

**Closed by sbis04** 2023-09-22 13:36 UTC
Labels: status: needs triage
