### ISSUE TITLE
Dynamic property "Password Field" on Text Fields widget is not working.

### ISSUE THREAD

**Issue by GersonFuentes** [FlutterFlow/flutterflow-issues#4782] opened 2024-10-30 14:36 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Text Field > Additional Properties > Password Field:
If I choose to set this property dinamically, it doesn't work at all. Tried to set the value stored in an App State, Component State, Page State, depending from Conditions, even passing the value as a constant "True" or "False". Nothing worked.

The only way to set this property's value is through the classic switch (non-dynamic), even when the dynamic setting exists.

### Expected Behavior

Text Field Password Field property (boolean) should be set dinamically, but it is not taking this value. The property is always set by the value of the classic switch.

### Steps to Reproduce

1. Create new page
2. Create Text Field
3. Set dynamically the value on Text Field > Additional Properties > Password Field
4. Click Run
5. Observe the dynamic value is not taken for this property.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4elc/l34t1mOZE7c/Ab8dVnSQWNnInbZInlOxEEQwjF7bpPbM+ZOj+THdWUu3ifFZiJWGJmm01zPuNuOOWUME3HByJb4Rz+atuewnzVj6jWqqRBaqrP3QmP/JjGGKEzpuZqx0nOtpoWF0s7zu6HujKFyvDJ5yyITEROeWYKoLIjmiGHXnWGn0Jg1ZSfCvr

### Visual documentation

![image](https://github.com/user-attachments/assets/1940caa9-9ded-4d29-bec9-3efa7c044832)

![image](https://github.com/user-attachments/assets/3393238c-d74e-4c48-af32-b02d354cdb9f)

![image](https://github.com/user-attachments/assets/9d4b1257-4e50-4ef8-8425-67dfbbd7f317)

![image](https://github.com/user-attachments/assets/a406b13b-076a-4cbc-8d6e-8452ca1ba61c)

### Environment

```markdown
- FlutterFlow version: Version 5.0.7 (5.0.7)
- Platform: MacOS Sequoia 15.0.1 and Windows 11.
- Browser name and version: Chrome 
- Operating system and version affected: Versión 130.0.6723.58 (Build oficial) (arm64) on MacOS
```

### Additional Information

I need to set this property dynamically, the same way I set other widgets and form fields in my project.

**Comment by Alezanello** [comment] 2024-10-30 14:43
Hello,

This issue is a duplicate of [GitHub Issue #3663](https://github.com/FlutterFlow/flutterflow-issues/issues/3663), where you’ve already posted about the same situation. I’ll close this ticket as a duplicate to consolidate our efforts. Rest assured, the original issue remains open internally, and the engineering team is actively working on a fix.

Thank you for your patience as we address this.

**Comment by GersonFuentes** [comment] 2024-10-30 14:58
No, it is not:

![image](https://github.com/user-attachments/assets/8d110179-6fa4-4b4f-8ed1-05f21cc588fc)

@Alezanello

**Comment by Alezanello** [comment] 2024-10-30 15:20
This was marked as "Not Planned" because the engineering team already has an internal ticket for this issue. I apologize for the lack of clarity in the original post, but rest assured, it’s actively being worked on!

**Closed as not planned** 2024-10-30 19:15 UTC
Labels: closed: duplicate
