### ISSUE TITLE
ChoiceChip Initially Selected property cannot use Page State Variable

### ISSUE THREAD

**Issue by jpollone** [FlutterFlow/flutterflow-issues#1515] opened 2023-09-24 13:57 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

😊 Defining options for ChoiceChips works well when using App State and Page State Variables. 
😊 Selecting initial values using an App State Variable or added text works fine. 

😢 Selecting initial values via a Page State Variable does not work.

### Expected Behavior

The initial ChoiceChips should be able to get set from a Page State Variable. This is vital on initial page load.

![screenshot 2023-09-24 0928@2x](https://github.com/FlutterFlow/flutterflow-issues/assets/957276/e9abd1f4-7d9a-4633-890e-a44bc3e85bd2)

### Failure
1. From a new page, create a page state variables availableOptions as List<String>
2. Create an On Page Load action, Update Widget State Page, availableOptions, Set Value to List of Random Names (min 5, max 10)
3. Add ChoiceChips and Allow Multiselect
4. Set Define Options to availableOptions
5. Set Initially Selected to availableOptions, First Few Items (count 2)

### Proof
The ChoiceChips can display options via the Page State Variable ( loaded via an On Load action)
1. Repeat the same steps but set availableOptions to static values (i.e., Apple, Banana, Cantaloupe, Dates)
2. For initially selected, add Banana

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wiMjfsM1Nobhe+KrcYMExmiUvMjs/ROcO0+xDeCs8GZT0B4kcYs+kfklUcN+/YHx+fFmjvGcX/Mr2jeDyFcE4CzqtbKpmwc1qUBaWZE+iV8mbEa63b0ZSEeRQfVyP4beJhgp4KrNoS3gA2kOUHvKvRXTdNbK3DTIdLuaoXdeK2SrDX1iXc2URm05KZDPz

### Context

ChoiceChips are valuable when creating list view filters!

- Populating the initial set of ChoiceChips requires getting distinct values via a Supabase or API call.
- When the page is displayed, the appropriate ChoiceChips should be highlighted to acknowledge to the user that these are the values that filter the list

### Visual documentation

This image demonstrates the different types of tests I conducted:
1. SUCCESS! Options initially set from default values from an App State Variable, and Initially Selected using the first few items from the App State.
2. FAIL! Options initially set from default values from an App State Variable, and Initially Selected using Page State via an On Load Action.
3. FAIL!  Options and Initially Selected using Page State via an On Load Action.
4. SUCCESS! Options set using Page State via an On Load Action and Initially Selected set manually on the widget.

![screenshot 2023-09-24 0906@2x](https://github.com/FlutterFlow/flutterflow-issues/assets/957276/d263e243-cedc-44a2-8fc0-cc15f2e2ed79)

### Environment

```markdown
- FlutterFlow version: v4.0 (released Sep 19, 2023 )
- Platform: Web
- Browser name and version: Version 117.0.5938.88 (Official Build) (arm64)
Automatically update Chrome for all users Learn more
- Operating system and version affected: macOS Ventura 13.6
```

**Comment by agreaves** [comment] 2023-09-24 23:46
Hi @jpollone, thank you for the bug report! I've taken a look, and it looks like the primary issue here is not setting it from a page state variable, but setting that page state variable on page load. Strictly speaking what's going on here isn't a bug.

"On Page Load" actions are executed right after the page initially loads, so the first Initial Value that will be set for the choice chips is the unset variable, which will default to an empty list. Since it's just the initial value, this won't change after the on page load action where you're setting the page variable.

But there are workarounds to this! The easiest is to conditionally show the Choice Chips if the page variable is not initialized (or wrap it in a Conditional Builder with this same condition). For all intents and purposes it will look the same way as you're hoping for since it will only be hidden for a single frame.

Closing this issue for now as it's not a bug, but I hope this helps!

**Closed by agreaves** 2023-09-24 23:46 UTC
Labels: status: needs triage

**Comment by jpollone** [comment] 2023-09-25 00:09
Thanks, Alex. Appreciate the explanation and I wondered if it was a "sequencing" issue, but inferred differently when I saw the ChoiceChips displayed. The work-around will be unnoticeable and will be fine.

**Comment by jpollone** [comment] 2023-09-25 01:00
For those interested, this is a simple fix to use PSVs to display selected ChoiceChips with an On Load action. I merely used a widget conditional to display when the first item in the list was set. I have multiple "filter chips" for the list view and the results are what you would expect with no delay.

![choicechip-display-condition](https://github.com/FlutterFlow/flutterflow-issues/assets/957276/4d3f2427-bfc6-4b4d-8be3-966dcabc93bd)
