### ISSUE TITLE
BUG NavBar

### ISSUE THREAD

**Issue by ramerysepol** [FlutterFlow/flutterflow-issues#1441] opened 2023-09-11 20:29 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In the NavBar, when switching between pages and clicking on any empty space, the error appears:

Uncaught (in promise) Error: A FocusNode was used after being disposed.
Once you have called dispose() on a FocusNode, it can no longer be used.

This happens even if you create a project with two blank pages and activate the NavBar on both, if you switch between them and click on the empty area the error occurs

### Expected Behavior

This error prevents the process from continuing

### Steps to Reproduce

create a new project, include two blank pages and activate the navbar on both, then run the test and change from one page to another and click in the center of them, Note. activate debug mode

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfiPLl6otOodtA7a6IY+5VtCYvJjocTL4zlO1HcxAYGO/yPbJ+d+LOTEtBTeKlTVNhHGGbmlgD3PzJhvL9NsE4NQ+cf656+qlyFjuUWXq8Rq6UCc3hZkdBO95mGmKi3MGJnRMnOrFtZUY87Uz3JumWYDTBN5+/Zwh9f6PHaOI=

### Context

This problem interrupts the execution of my application when hiding some components and displaying them through a condition

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/121977425/5a584b0f-53af-40a7-b5c9-a809eded84ab

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Android/IOS
- Browser name and version: Google Chrome Version 116.0.5845.180
- Operating system and version affected: Windows 11
```

**Comment by SameerShahzad99** [comment] 2023-09-11 20:33
@ramerysepol Thank you so much for submitting this bug, i was able to reproduce this on my end!

**Comment by ramerysepol** [comment] 2023-09-12 19:26
precision for a solution? my project is on hold because of this

**Comment by wenkaifan0720** [comment] 2023-09-17 14:11
Hi @ramerysepol. I created a test project (https://app.flutterflow.io/project/flutterflow-issue-1441-9e7znt) as you described, but didn't see the error. Is it still happening to you?

**Comment by ramerysepol** [comment] 2023-09-17 14:19
Yes, create a new project, add two pages to the bar and activate the navbar on both, triple click on the tab and then on the center of the page, switch between the pages and click on the bottom of the pages, note activate debug mode on the browser to view the error in the console.

⁣Obter o BlueMail para Android ​

Em 17 de set. de 2023 11:11, em 11:11, Wenkai Fan ***@***.***> escreveu:

**Comment by wenkaifan0720** [comment] 2023-09-17 21:08
Hi @ramerysepol. I can reproduce this issue in debug mode now. However, it doesn't seem to affect the execution of the app. And it doesn't appear in run mode. Since this is likely a debug mode only issue, we will not be working on it and I close this issue for now.

**Closed by wenkaifan0720** 2023-09-17 21:08 UTC
Labels: type: bug, status: wontfix, status: confirmed, priority: low, closed: other
