### ISSUE TITLE
Translate not persist

### ISSUE THREAD

**Issue by MendesCorporation** [FlutterFlow/flutterflow-issues#3422] opened 2024-07-17 16:22 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When writing the translation and leaving the screen and returning, the translation is deleted

### Expected Behavior

Translate ok

### Steps to Reproduce

1.Select more 1 language
2.Translate

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfz8rluJNIvsdA0b6ILPponmI4JjocTeU30+thcw4bI+P0PLMqO+P7UFtvcuqHT3NmGU2lvFgd/8LwkfDLDcACKTKeGIRn+pB1UxDvTmaiSpCWPsy0ZHxCEfFPI36gy52rpSRTIrRiLngnw1yQHvOAb3qCf9qOYwx5e6fDbOY=

### Visual documentation

https://github.com/user-attachments/assets/480d4151-1fcf-4f8e-b463-cdcf2680753f

### Environment

```markdown
- FlutterFlow version: 4.1.72+
- Platform: WEB
- Browser name and version: Chrome
- Operating system and version affected:
```

**Comment by msusviela** [comment] 2024-07-17 16:37
Hi @MendesCorporation. Thanks for your report. Our team is already working on a fix for this. I'm closing this issue since it's a duplicate of one that is in our internal backlog. I will keep you updated. Thanks!

**Closed as not planned** 2024-07-17 16:37 UTC
Labels: closed: duplicate
