### ISSUE TITLE
Trigger Push Notification action

### ISSUE THREAD

**Issue by rene-getoak-app** [FlutterFlow/flutterflow-issues#3074] opened 2024-06-06 08:54 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using the build-in FF TRigger push notification action it is possible to optionally specify an image. If is dynamically set the image url value using a conditional statement as follows:

If (List is set and not empty) {
List.firstItem (url)
}
Else {
Null
}

I can only send push notifications if the Ilage url list is set and not empty.

So it seems like that the trigger push notification cannot handle dynamic setting the optional image.

### Expected Behavior

That the build in trigger push notification action can handle conditional setting the optional image url

### Steps to Reproduce

1. create a action flow with a trigger push notification
2. set a condition on the optional image

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40j+Tnz6dIsN8C0KvxbvREjhwnJW4hXIMzuNp7aCosfZT2BLMcec/RVERoTsu8dGw7eFmgo2oW0vuMiPHfO/UqCwudbpQ/+cx+aAvLWXGibpC7FJWgOmh8Ef9TIG67y7avmx0nG7BqR1lh7FyIH/KsZ3TrHoCwDW4eDq/LZO4=

### Context

Conditionally set the optional image on a push notification depending on if a chat message includes an image.

### Visual documentation

![Skærmbillede 2024-06-06 kl 10 34 52](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/c816d8c6-ceb3-4f7e-a13e-109e4fe8dc77/19d3bb90-ca9b-46e6-973f-851fc43209e0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jODE2ZDhjNi1jZWIzLTRmN2UtYTEzZS0xMDllNGZlOGRjNzcvMTlkM2JiOTAtY2E5Yi00NmU2LTk3M2YtODUxZmM0MzIwOWUwIiwiaWF0IjoxNzE3NjkwOTc5LCJleHAiOjMzMjg4MjUwOTc5fQ.UQ9E7ZIgltICY5CGfLsbnfmRalLiqWpLhcRO7QdDVro)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1.54
- Platform: Ios App
- Browser name and version: Chrome
- Operating system and version affected: macOS
```

**Comment by paulperez-dev** [comment] 2024-06-08 00:51
Hi @rene-getoak-app! I noticed that the issue is not reproduced on the version you shared. To be able to triage the bug, can you please share the code bug report code from a project with the issue reproduced on it?

**Comment by rene-getoak-app** [comment] 2024-06-11 15:02
Hi Paul

Thanks for your email.

I have recreated to action logic in a new branch with this bug report code
- IT43zMjl/ax5xLRE0M7hKO5aoGQmGkwFarkR19p7aCosfZT2BLMcec/RVERoTsu8dGw7eFmgo2oW0PTFjtjPOu1cOTadf6JJ+JYAEgHyIUe6eKazFJWgOmh8Ef9TIG67y7avmx0nG7BqR1lh7FyIH/KsZ3TrHoCwDW4eDq/LZO4=


*René Brask Birch*
Co-founder @ Oak

**Comment by paulperez-dev** [comment] 2024-06-12 05:35
Hi @rene-getoak-app! Can you please verify if the notification is sent using an asset image but keeping the same condition.

**Comment by rene-getoak-app** [comment] 2024-06-13 15:46
The message/notification is not sent and there is no error message in the
cloud function log.


*René Brask Birch*
Co-founder @ Oak

**Comment by rene-getoak-app** [comment] 2024-06-21 05:01
There is no resolution, so please don't just close it.


*René Brask Birch*
Co-founder @ Oak

**Comment by rene-getoak-app** [comment] 2024-07-05 06:13
Please find a solution instead of just stalling it


*René Brask Birch*
Co-founder @ Oak

**Comment by paulperez-dev** [comment] 2024-07-07 23:02
Hi @rene-getoak-app! Sorry for the late response. We won't close it without letting you know. I will be taking a deep look into this and let you know if I find something.

**Comment by rene-getoak-app** [comment] 2024-07-08 09:06
Thanks Paul, much apppreciated🙌


*René Brask Birch*
Co-founder @ Oak

**Comment by paulperez-dev** [comment] 2024-07-13 22:56
Hi @rene-getoak-app! I looked into the generated code and the dynamic configuration for the push notification and everything seems to be working. Can you please test again? If the issue persists, please try to reproduce it from a blank project and share the bug report code again.

**Comment by paulperez-dev** [comment] 2024-07-17 03:12
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Closed** 2024-07-17 03:12 UTC
Labels: status: needs triage
