### ISSUE TITLE
App state crashing

### ISSUE THREAD

**Issue by luilabdev** [FlutterFlow/flutterflow-issues#367] opened 2023-01-18 18:10 UTC
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
I am using a custom tab container to display a list of data per each tab. The idea is to get a list of trips from a Firestore collection and display every items that belongs to each trip.

Every trip has it own sections and every section has children components, example.

- Trip - Paris
  - Places to visit
     - Eiffel Tower
     - Louvre museum
  - Hotels
    - X hotel in paris
  - Other section
     - A child item

There are another components per each section as notes, checklist, etc. But per each place I have to make an API Call to get the place detail from Google Places and Firestore call to get the count of attached files per each place.

Another functionality is hide the entire section components and the place detail, I am using a local state list variable to store the section or component visibility and exists a text field per each place to add a note and update the Firestore collection on the event onChange.

## Current behavior (required)
The application was working, not perfect but working, one problem that I had is that I coun't found a way to keep the backend and API call alive as TabBar widget does.

But now after the new app state management features the application is crazy.

https://user-images.githubusercontent.com/19392344/213250772-64a29f01-cab5-4cd8-bbe7-89fbfb3033b8.mov

I was trying to understand what is happening, and I am using the TabBar widget instead of my custom own. But some problems are still there, for example a simple action to show/hide a Bottom Sheet reload the components state.

https://user-images.githubusercontent.com/19392344/213251670-5afc2778-4ba2-4923-af34-ee9d96de6fcd.mov

I don't know if child components are inherit the parent state or if a logic problem from my part. And if I open the application in the browser and in my android at the same time when I make a change for example in the browser the mobile app do the same behavior

## To Reproduce (required)

1.  Create a trip collection (id, name, etc)
2. Create a trip_sections collection (id, name, trip_id) every collection belongs to an specific trip
3. Create a trip_places collection (id, name, note, section_id) every place belongs to an specific section, you can add a trip_id if you want to get all places that belongs to and specific trip.
4. In the new page add a TabBar widget
5. The overview tab needs to have a Column or ListView widget to display every section
6. Into each section you need to display all places that belongs to X section
7. Into each place make a backend call to get the attached files count and an API call to get the place detail
8. Into each place you can put a TextField widget to update the note field in places collection
9. Per each section add a button to open a Bottom Sheet where you can search and add a new place to the collection

## Your environment

* Version of FlutterFlow used:  3.0
* Platform (e.g. Web, MacOS Desktop):  1.1.39
* Browser name and version:  Chrome 
* Operating system and version (desktop or mobile):

**Comment by hariprasadms** [comment] 2023-01-24 10:30
Hi @luilabdev - Thanks for sharing the issue details. First of all sorry for being late response on this one. 
Could you please confirm are you still experiencing the issues ?. 

After looking at the videos you shared, my quick thought is there could be a few logic issues around loading behaviours you see. This could because of future request data load delay and passing the data between states. At high level I can suggest try to load and store the date at page load level and later display them on the page. See if this can help you to resolve the issues what you are seeing. Thanks

**Comment by aemelyanovff** [comment] 2023-01-30 13:54
@luilabdev Thanks for reporting the issue.

This issue tracker is for bugs with a clear way to reproduce them. And I'm afraid the steps to reproduce this issue are too involved - it sounds like we'd need to rebuild a large portion of your project.

I suggest you reach out to FlutterFlow support for assistance. In the meantime, I'm closing this issue. Feel free to reopen it if you a find simpler way to reproduce it (not involving 3 interconnected collections, etc.).

**Closed by aemelyanovff** 2023-01-30 13:54 UTC
Labels: status: needs triage, status: needs information
