### ISSUE TITLE
Bug At Flutterflow Team Plan ( Branching merge )

### ISSUE THREAD

**Issue by mahmoud-talbawy** [FlutterFlow/flutterflow-issues#3449] opened 2024-07-21 20:59 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

i have created a branch to try some changes in my project and after that i needed to merge that branch to main branch and i have faced that Issue 

### Expected Behavior

make the merge like Flutterflow documentation

### Steps to Reproduce

1. create a new branch called "OfflineCartVersion"
2. made some changes on both Main and "OfflineCartVersion"
3. when merge OfflineCartVersion into main or the opposite (main into OfflineCartVersion) 
4. Flutterflow wait some time and then "Setting up merge..." then "Failed to compute merge conflicts" Message Appears 

https://github.com/user-attachments/assets/596e5865-bfa8-46c2-bc90-6a1618759251

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40iMnf0Id5o+YF15H2du5WngQvQXIYW4I7ku17aCosfZT2BLMcec/RVERCOL2odwlUJ2KJmWoW0638j4aXUO4EIQmubbpjwqhidBfzQlOQRpibFJWvP3wmO/xYfHKf1Kaw2hBAOrBtcXA57V6YGeiyQgHrH5TVO20eDq/LZO4=

### Visual documentation

https://github.com/user-attachments/assets/a05f1e02-76d3-4615-8f63-8c09443f7282

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.74 released July 21, 2024
- Platform: Macbook Pro 2020 M1
- Browser name and version: Flutterflow For Desktop 
- Operating system and version affected: MacOS Sonoma 14.5
```

### Additional Information

My entire work has been stoped due to this issue

**Comment by msusviela** [comment] 2024-07-23 11:24
Hey @mahmoud99990, Thanks for your report, So sorry you are experiencing this issue. I was not able to reproduce this on a blank project. I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. Thanks so much!

**Closed as not planned** 2024-07-26 14:51 UTC
Labels: status: can't reproduce, closed: support request

**Comment by leighajarett** [comment] 2024-07-26 20:17
Hi there - I think we have resolved this issue, can you please check and let us know if it's still happening?
