### ISSUE TITLE
'Create User Document' boolian in Auth Login and Auth Create Account actions affects both actions boolian state.

### ISSUE THREAD

**Issue by KelpME** [FlutterFlow/flutterflow-issues#871] opened 2023-05-09 21:19 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

toggle the 'Create User Document' on a button that utilizes Auth Login action and it will affect separate widgets utilizing the Auth Create Account actions 'Create User Document' state.

### Expected Behavior

I expected the 'Create User Document' boolian state of one action to not effect the state of the other.

### Steps to Reproduce

set up one click authorization with either google or apple and firebase. create two buttons on a page, one utilizes 'auth login' action (using either google or apple sign in), and the other 'auth create account' action (using same sign in provider as the previous button).

toggle the 'Create User Document' on either button and see that it affects both buttons 'Create User Document' state.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

n/a

### Context

I'm trying to present a terms and conditions agreement before collecting user information. This creates a backdoor to creating a user document through the login page.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/100400724/820c1c42-cdf1-4f20-a15f-87572848acf3)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: PC
- Browser name and version: Brave Version 1.51.110 Chromium: 113.0.5672.77 (Official Build) (64-bit)
- Operating system and version affected: Windows 10 Home 22H2
```

**Comment by bulgariamitko** [comment] 2023-05-13 12:55
Yes this is normal behavior in FF I do not think is an issue.

**Comment by wenkaifan0720** [comment] 2023-07-06 18:34
Hi @KelpME. This is a project wide setting. So they would appear to be synced across all widgets. If the user document has already been created, Firebase would not create it again. You would only want to turn if off if you are only using firebase for authentication purpose.

Since this is the expected behavior, I will close this issue for now. Thanks.

**Closed by wenkaifan0720** 2023-07-06 18:34 UTC
Labels: closed: not a bug, status: not a bug
