### ISSUE TITLE
Multi-select dropdown initial value doesn't accept a list

### ISSUE THREAD

**Issue by neian-world** [FlutterFlow/flutterflow-issues#1355] opened 2023-08-25 10:01 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When a dropdown is set to multi-select, the **initial option** value is of type String instead of List<String>.
Close this ticket if it was already addressed in https://github.com/FlutterFlow/flutterflow-issues/issues/1343

### Expected Behavior

Initial option value being of type List<String>.

### Steps to Reproduce

1. Create multi-select dropdown
2. Set option values to a variable
3. Go to select Initial Option Value
4. The type is String instead of List<String>

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ghc/lvJdOm99J1aX2de9VvCkQJmU1a5c0sN1haw4aCojoOuxzac/7dkhtTc+mT0FpKEWKjmYBwPzQhvzlM/E4aE6Ybt1azahfEhb/Xju/aoubOpeWOn8nMJlPf0yi0ra3nQolKbdaSiVm7XGqF9++RXbUQeb7Zwh9f6PHaOI=

### Context

Trying to make a multi-select work with dynamic database values.

### Visual documentation

<img width="614" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/12573714/8fe367f2-2cca-4d05-9978-b9a92c7f1dbd">

### Environment

```markdown
- FlutterFlow version: 3.1 August 24
- Platform: Chrome
- Browser name and version: Chrome  115.0.5790.170
- Operating system and version affected: Mac OS
```

**Comment by hariprasadms** [comment] 2023-08-25 14:26
Hi @neian-world - Thanks for submitting the issue. I can reproduce the issue;

**Comment by kiwisoftapp** [comment] 2023-09-13 17:09
Same issue for me

**Comment by wenkaifan0720** [comment] 2023-09-14 18:10
This is a duplicate of https://github.com/FlutterFlow/flutterflow-issues/issues/1343, so I will close this one.

**Closed by wenkaifan0720** 2023-09-14 18:10 UTC
Labels: type: bug, status: confirmed, closed: duplicate
