### ISSUE TITLE
Webview Back Navigation Failing

### ISSUE THREAD

**Issue by crossxsecure** [FlutterFlow/flutterflow-issues#3192] opened 2024-06-21 07:57 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In FlutterFlow, the 'Back' button in WebView is incorrectly navigating back to the Activity, instead of navigational within the webpage itself. This issue has been tested with multiple websites and the behavior remains consistent across all tested sites. The issue has been reproduced on multiple Android devices, indicating that it is not device-specific.

### Expected Behavior

The ‘Back’ function is expected to operate similarly to the webview.GoBack() method, which checks if there is a previous page available in the WebView’s history stack. If a previous page is available, it should navigate within the website itself. If not, only then should it navigate back to the FlutterFlow Page/Activity. The current behavior suggests that the ‘Back’ function may be mistakenly linked to the Activity’s back stack instead of the WebView’s history stack.

### Steps to Reproduce

I have created a test app for the validation, generate the apk from the test project and choose the 3 buttons to navigate to the e-commerce stores and navigate to nth page and then press the android default back button. It will loose the entire the webpages and instead of navigating from nth page - 1, it navigates you back to the home page which is totally incorrect behaviour.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40zPHlwItIm+Fc0ISJKflagmA5Jjs4R+cr1+xRaCkvfYz3CLMqY8mnPxdWZMjgSm9lfU6mp14zw+j7idjPKfk7BySWfYRczKVTETrNcEG7VY+TF7rpYmhDJ8NQIG6u4Jm3iCJ5CPVuSnAa2Fy6PeiXShfsHbX4Ino4Sq/LZO4=

### Visual documentation

.

### Environment

```markdown
- FlutterFlow version: 4.1.61+ (Latest)
- Platform: Android
- Browser name and version:
- Operating system and version affected: Android
```

### Additional Information

This issue interferes with user interactions, particularly when they are engaged in a multi-step business process within the webpage. When users tap ‘back’, instead of moving to the previous step within the process, they are unexpectedly exited from the webpage and returned to the FlutterFlow Activity.

**Comment by msusviela** [comment] 2024-06-21 12:13
Hi @crossxsecure.<br><br>Just saw that you reported this issue back then: [https://github.com/FlutterFlow/flutterflow-issues/issues/2630](https://github.com/FlutterFlow/flutterflow-issues/issues/2630)<br><br>This issue is in our backlog and the ENG team will try and solve this. I'll let you know as soon as I get an update. I'm closing this because it's a duplicate of the other issue. Thanks for your feedback.

**Closed as not planned** 2024-06-21 12:13 UTC
Labels: closed: duplicate

**Comment by crossxsecure** [comment] 2024-06-21 12:51
Hi @msusviela, it's been around 3 months and that ticket isn't addressed yet. Even basic navigations seem to be failing. Could you kindly replicate this issue? It’s essential to address this as a bug rather than a feature request.
