### ISSUE TITLE
paywall with revenueCat shows gray screen 

### ISSUE THREAD

**Issue by bustlee** [FlutterFlow/flutterflow-issues#2800] opened 2024-04-24 12:01 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The current issue is that when I log in to Google Play with account 1 to download this app, the paywall doesn't show a gray screen. However, when I log in to Google Play with diff account 2 to download the same app, the paywall does show a gray screen. By the way, I was using the same account to log in to this app, what could be the reason for this?

### Expected Behavior

Google Play account B
same app account C
![2571713959374_ pic](https://github.com/FlutterFlow/flutterflow-issues/assets/162474453/bf115939-2306-4148-8164-497936f6a861)

### Steps to Reproduce

<img width="843" alt="Screenshot 2024-04-24 at 19 51 45" src="https://github.com/FlutterFlow/flutterflow-issues/assets/162474453/67d36372-45e3-407a-90a8-282d17976143">

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4skvLqx5BNobRF+KrAcfpr/WEQJkM3bYEWscsZbw4bB4zqPLJ/ZMn8alRvUtOhTUNhHE2Gmkcd/9bLheHQFfQ7FzCBQbpiyodbFxXjWXq8Ra6LPrjtRnMlP9xmfG6a0cOSniVSOshaLWxn7DiIF/O9dHLdCZ+/Zwh9f6PHaOI=

### Context

Google Play account A
same app account C
![2581713959402_ pic](https://github.com/FlutterFlow/flutterflow-issues/assets/162474453/c90262b4-5cbe-4a29-8218-a530a1aa298a)

Google Play account B
same app account C
![2571713959374_ pic](https://github.com/FlutterFlow/flutterflow-issues/assets/162474453/bf115939-2306-4148-8164-497936f6a861)

### Visual documentation

<img width="843" alt="Screenshot 2024-04-24 at 19 51 45" src="https://github.com/FlutterFlow/flutterflow-issues/assets/162474453/bf08dee0-b3df-4e64-8988-224b997d7345">

### Environment

```markdown
- FlutterFlow version: 4.1.34
- Platform: Android
- Browser name and version: Chrome
- Operating system and version affected: Android
Furthermore, this issue has already been encountered in previous versions of FlutterFlow and has remained unresolved.
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by rzambroni** [comment] 2024-04-24 15:04
Hey @ShenmoTech, it will be hard for us to help without replicable steps, we have tested your project in a couple devices/accounts and we were not able to reproduce this issue. The revenueCat paywall shows everytime. 

If you happen to know how can we replicate this consistently we might be able to explore a bit more, otherwise i would encourage you to follow-up with our support team for further assistance.

You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. 

I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects.

**Comment by ShenmoTech** [comment] 2024-04-24 15:09
I believe this is related to the country settings of the Google Play account. When the country where the account is registered doesn't have pricing set up, it results in a null value, causing the gray screen to appear.

I think this might be the reason and hope it helps the FlutterFlow team.


I will close this issue for now. Thanks to FlutterFlow for providing a great product!
________________________________
发件人: rzambroni ***@***.***>
发送时间: 2024年4月24日 15:04
收件人: FlutterFlow/flutterflow-issues ***@***.***>
抄送: ShenmoTech ***@***.***>; Mention ***@***.***>
主题: Re: [FlutterFlow/flutterflow-issues] paywall with revenueCat shows gray screen (Issue #2800)


Hey @ShenmoTech<https://github.com/ShenmoTech>, it will be hard for us to help without replicable steps, we have tested your project in a couple devices/accounts and we were not able to reproduce this issue. The revenueCat paywall shows everytime.

If you happen to know how can we replicate this consistently we might be able to explore a bit more, otherwise i would encourage you to follow-up with our support team for further assistance.

You can do that either by email: ***@***.******@***.***> or using the in-app chat inside of FlutterFlow.

I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects.

―

**Comment by ShenmoTech** [comment] 2024-04-24 15:13
It's possible that others have encountered the same issue due to this reason, but further confirmation is needed.

**Closed as not planned** 2024-04-24 15:17 UTC
Labels: status: can't reproduce, status : project specific
