### ISSUE TITLE
Context menu (control-click) on Mac not working

### ISSUE THREAD

**Issue by goerlitz** [FlutterFlow/flutterflow-issues#2160] opened 2024-01-12 21:29 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I right click any element in the visual editor or component tree nothing happens.
However, right-clicking works on other websites, like Youtube

### Expected Behavior

The context menu for the clicked element should open.

### Steps to Reproduce

I don't know what condition leads to that issue. I'll attach a video.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

not possible because right-click does not work

### Context

I've tried it with latest Chrome and Safari on my MacBook Pro (M1). Neither does work.
I've tried it with an older Linux and Firefox - works.

I cannot properly use FlutterFlow -> deal breaker!

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/2389436/bf3e918a-6c5c-44d5-b140-946cfe6661db

### Environment

```markdown
- FlutterFlow version: v4.0 (released Jan 12, 2024)
- Platform: MacBook Pro (M1)
- Browser name and version: Chrome 120.0.6099.216 (arm64)
- Operating system and version affected: MacOS Monterey 12.4
```

**Comment by hariprasadms** [comment] 2024-01-15 08:45
Hi @goerlitz - I've looked into this issue and tested it in my projects. Right-clicking seems to work as expected. It appears to be browser-specific. Have you tested it in different projects? Can you reproduce it in other projects as well? Please confirm these details. If the issue is consistent in a specific project, kindly update the issue with the project bug report code so that we can access the project and investigate further. Thanks

**Comment by goerlitz** [comment] 2024-01-15 10:36
Hi @hariprasadms, I was able to narrow down the issue. It is not a project or browser issue - I tested with different projects on Chrome, Safari, and Firefox.

Instead, it is a Mac issue! On Mac, you use ctrl-click as right-click to open a content menu. However, ctrl-click is not working. (I updated the issue title)

I was able to find a workaround: https://support-splashtopbusiness.splashtop.com/hc/en-us/articles/4402346146701-How-to-right-click-when-connecting-from-Mac-to-Windows

1. use 2-finger tap on trackpad -> impractical when working on a keyboard
2. enable right-click for Magic Mouse in settings -> I usually have this turned off and it only works for Magic Mouse.

I'd rather not rely on workarounds but would appreciate if you could make ctrl-click work on Macs.

**Comment by hariprasadms** [comment] 2024-01-16 11:42
Thanks for the update @goerlitz. Please close the issue. Thanks

**Comment by goerlitz** [comment] 2024-01-16 17:10
@hariprasadms , I can't close the issue. The problem still exist and is quite annoying.

**Comment by hariprasadms** [comment] 2024-01-17 10:48
Hi @goerlitz - This is not a bug but it mostly sounds like a enhancement.

**Comment by goerlitz** [comment] 2024-01-17 13:57
I can't really use the context menu right now. But since the context menu is an integral UI part I'm missing a significant number of features.

Did you test control-click on a Mac?

**Closed** 2024-01-24 22:46 UTC
Labels: closed: not a bug

**Comment by SamIAmHarris** [comment] 2025-05-21 20:24
I can reproduce this on my Mac. 2 finger click on the trackpad works, but control-click does not.
