### ISSUE TITLE
Datatable does not update on rebuild component

### ISSUE THREAD

**Issue by bigbworld** [FlutterFlow/flutterflow-issues#3252] opened 2024-06-27 03:22 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

With the new data table rebuilding the component or when changing the data associated to the table, it does not refresh.

### Expected Behavior

Table should update on changes.

### Steps to Reproduce

Create new datatable in a page
Create page state with a list(used supabase row list) and set the data table to generate dynamically generate children from it.
Make changes to the page state and then set refresh current page
Run the build and and trigger page state change
Table will not update/refresh (rarely gets updated, usually if the table is empty and we add item to the list the table gets updated otherwise it doesn't)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4shc7lvJVgoctH176JK+5R/GE4Njt6ULgSscgYYxAjfbbrB4YUY/fTVEpoTcOHd2xEOlmY8XMxw+zGv97pEu09PiirY7Y7yZBTWwz/cFGhMoiKPbiJPkFPLNNMGlOHzbSZkBF4CONtckIswEOUJ9mtHwHdNICwDGwvRP/9WbvOjkqRLiLCXn0Jg1ZSfCvr

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/173977991/34f82a2a-1750-43a9-8aac-9b7af5ed043a)

### Environment

```markdown
- FlutterFlow version: 1.4.64
- Platform: Web/Local Run
- Browser name and version: Chrome
- Operating system and version affected: Windows 11
```

**Comment by paulperez-dev** [comment] 2024-06-27 21:25
Hi @bigbworld! In your project, I noticed that you are setting the app state inside the popup, so the query on the page is not called again. Consider updating the state after opening the popup (with non-blocking set to OFF).

I'm closing this issue because this is not a bug.

**Closed as not planned** 2024-07-03 21:19 UTC
Labels: closed: not a bug
