### ISSUE TITLE
FlutterFlow VSCode Extension - "FF: Pull Latest" action deletes EVERYTHING, including vscode workspace settings, .git repo, any non-FF files in the workspace

### ISSUE THREAD

**Issue by isegal** [FlutterFlow/flutterflow-issues#4022] opened 2024-10-09 23:08 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

FF: "Pull Latest" warns about "Unsynched Local Changes will be overwritten" and then proceeds to nuke not just the local changes but the entire workspace including any files that the VSCode and Fluter does not 'own'. It will nuke the entire .git history (.git directory) and any local files that you may have in the workspace such as .md files for documentation, shell scripts, tools, etc.

It even deletes and replacs .vscode and its own workspace settings (such as when we added Flutter API key in the FlutterFlow's VSCode workspace setting). This is highly destructive and is generally a major no-no for any IDE plugin to be recursively deleting and replacing the entire project root.

### Expected Behavior

We expected FF: Pull Latest to overwrite FF-owned files, but we did not expect this action to wipe EVERYTHING and replace the entire VScode (it even deleted .vscode which includes FluterFlow's own settings.json file, making any further actions impossible).

It should not delete files and directories that it actually does not own.

For example, replacing `lib/`, `assets/`, `pubspec.yaml` would be ok, but replacing the entire workspace (and nuking .git as well as the plugin's own workspace settings within .vscode in the process) is unworkable.

### Steps to Reproduce

1. Follow the steps as per FlutterFlow documentation for VSCode extension and project setup.
2. Set up the API key and other settings as a workspace setting.
3. Add any local files, eg `git init`, add custom workspace config.
4. Issue "Flutterflow: Pull Latest Changes"                          

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

N/A

### Visual documentation

N/A

### Environment

```markdown
- FlutterFlow version: current
- Platform: Mac OS
- Browser name and version: N/A
- Operating system and version affected: 14.5 (23F79)
 
VSCode About:
Version: 1.94.0
Commit: d78a74bcdfad14d5d3b1b782f87255d802b57511
Date: 2024-10-02T13:08:12.626Z (1 wk ago)
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.5.0
```

### Additional Information

Unfortunately VSCode exctensions is not usable in its current form. We need to be able to use git and local branches and also be able to have files that are not related to FF in our VSCode workspace.

**Comment by Alezanello** [comment] 2024-10-11 15:22
Hello!

This is the current expected behavior of the VSCode extension, and the extension itself explains that this will occur. However, I understand your concern, so I’ll create a feature/enhancement request to explore potential ways to prevent this from deleting everything.

Since this is the intended behavior, I’ll close this ticket as an enhancement request and create an internal ticket to ensure the engineering team is aware of your feedback.

Thank you for bringing this to our attention!

**Closed as not planned** 2024-10-11 15:22 UTC
Labels: closed: feature / enhancement request

**Comment by isegal** [comment] 2024-10-11 23:07
Please note that "FF: Pull Latest" also wipes its own settings such as FlutterFlow's API key/token. It is surprising that even that part would be considered by-design.

If this is by-design, then the action should have a more appropriate name, such as "FF Dangerzone: Reset Workspace Code and Configuration"
