### ISSUE TITLE
Flutter 3.24 + Packages Upgrade - Apple Sign In stopped working

### ISSUE THREAD

**Issue by tensoralex** [FlutterFlow/flutterflow-issues#4445] opened 2024-10-22 22:45 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After 10/22/2024 Flutter 3.24 + Packages Upgrade, Apple Sign In functionality (when IOS app built from FF local run) started to reject any Apple sign in with the following error: "Invalid OAuth response from apple.com"

### Expected Behavior

Apple sign-in should work as before FF update.

### Steps to Reproduce

1. Setup project with apple sign in
2. Download FF locally and flutter run --release on physical IOS phone.
3. Try to sign in with Apple sign in.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

N/A

### Visual documentation

N/A

### Environment

```markdown
- FlutterFlow version: 5.0.8
- Platform: IOS
- Browser name and version: N/A
- Operating system and version affected: MacOS Flutter 3.24.2
```

**Comment by tensoralex** [comment] 2024-10-22 22:49
The workaround: 
This is the confirmed issue after upgrading firebase_auth: https://github.com/firebase/flutterfire/issues/13235
Confirmed steps to fix: 
1. Update file ../lib/auth/firebase_auth/apple_auth.dart
with
```
  final oauthCredential = OAuthProvider("apple.com").credential(
    idToken: appleCredential.identityToken,
    rawNonce: rawNonce,
    accessToken: appleCredential.authorizationCode,
  );
```
Specifically add ``accessToken: appleCredential.authorizationCode,``

2. Run flutter clean and rebuild project for IOS.

This should resolve the issue.

**Comment by ajaniewiem** [comment] 2024-10-23 08:21
I experience exactly the same issue after yesterday's flutter update.

**Comment by healemdrapp** [comment] 2024-10-23 08:41
Same issue here, thanks @tensoralex for the workaround as it works

**Comment by paulperez-dev** [comment] 2024-10-23 10:16
Hi everyone,

Since a solution has been found, I’ll be closing this issue.

Thank you all for your contributions!

**Comment by healemdrapp** [comment] 2024-10-23 10:27
hold your horses @paulperez-dev... there is a difference between a solution and a workaround, a work around means that unless someone goes and edits the code manually in GitHub or otherwise, the functionality breaks!

I'd appreciate if you can open it again and assign someone to fix it, because even with the workaround, it works sometimes and not all the times so it's not totally reliable

**Comment by kubent** [comment] 2024-10-23 11:30
I build exclusively on the web ui as I don't have a mac, from what I understand I can't push this code back so that it can build with the workaround?

**Comment by amosvizer** [comment] 2024-10-23 11:44
I am experiencing the same issue. I cant believe that they think they can just close this MAJOR issue with a workaround that was found @tensoralex . @paulperez-dev if anything, this should be brought to the top of the list

**Comment by ankitStoke** [comment] 2024-10-23 11:47
Can report that I'm experiencing the same issue since yesterday's upadte. This shouldn't be closed with the fix suggested, the issue needs to be fixed in Flutterflow or else developers cannot use the automated publishing to the app store anymore.

**Comment by chf-yoshida** [comment] 2024-10-23 12:43
When will it be fixed? I would like an announcement.

**Comment by paulperez-dev** [comment] 2024-10-23 17:25
Hey everyone,

I apologize for my earlier misunderstanding of the situation. I’ll take another look at the main issue and get back to you with my findings. Thank you for bringing this to our attention!

**Comment by lottacache** [comment] 2024-10-23 20:56
Implemented apple sign in recently. Facing the same issue after following the instructions stated on https://docs.flutterflow.io/integrations/authentication/firebase/apple/ 

Apple sign in and create account works on my Native Applications not built in FlutterFlow. 


Attached is the screenshot of the Sign Up page after going through the Apple Sign in flow.
![IMG_7283](https://github.com/user-attachments/assets/1b5b5b7f-444a-477b-ab78-6e12a971030a)

**Comment by lottacache** [comment] 2024-10-23 21:34
> Implemented apple sign in recently. Facing the same issue after following the instructions stated on https://docs.flutterflow.io/integrations/authentication/firebase/apple/
> 
> Apple sign in and create account works on my Native Applications not built in FlutterFlow.

The latest push from Flutterflow to my repository shows that they have added in the line without you have to make changes yourself.
`accessToken: appleCredential.authorizationCode,` as mentioned by @tensoralex 

Apple sign in is currently working as intended.
![Screenshot 2024-10-23 at 4 32 28 PM](https://github.com/user-attachments/assets/e9671b11-4670-4029-9f29-348e8191252e)

**Comment by ahnsunnyyoung** [comment] 2024-10-24 06:53
Same issue here,, checked code has been updated, All set! Thanks.

**Comment by tensoralex** [comment] 2024-10-24 23:48
Confirming, FF code export now includes the fix for this issue.

**Closed as completed** 2024-12-05 03:57 UTC
Labels: status: confirmed, Bug
