### ISSUE TITLE
FlutterFlow break custom action names from imported plugin

### ISSUE THREAD

**Issue by regismachado** [FlutterFlow/flutterflow-issues#3952] opened 2024-10-01 22:49 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When working with custom actions from Adapty Flutter Flow plugins.

In the first time that I add an action, I can see the action names and parameters, but after that, when need to add more actions or replace parameters values, FlutterFlow stop showing the action names and don't let me use the return values from the custom actions.

### Expected Behavior

When selecting custom actions be able to:
Select the custom action
See the custom action name
Select the output result
Add and delete actions without issues.

### Steps to Reproduce

I'm following the steps in this tutorial

https://adapty.io/docs/ff-action-flow#step-11-request-adapty-paywall

Open the Actions section in the right pane.

Open the Action Flow Editor.

In the Select Action Trigger window, choose On Page Load.

In the No Actions Created window, click the Add Action button.

In the Actions Flow Editor window, search for getPaywall custom action and choose it.

In the Set Actions Arguments section, enter the real ID of the [placement you have created](https://adapty.io/docs/create-placement) in the Adapty Dashboard that includes the paywall. In this example it's example_ab_test. Be sure to use your real placement ID!

In the Action Output Variable Name, create a new variable and name it getPaywallResult. We'll use this in the next step to reference the Adapty paywall and request its products.

Step 1.2. Request Adapty paywall products
Great! We’ve retrieved the Adapty paywall. Now, let's get the products associated with this paywall:

Click the plus (+) button below, click the Add Action button to add an action to receive Adapty paywall products. For this, search and choose getPaywallProducts.

In the Set Actions Arguments section, choose getPaywallResult variable created earlier.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kk/H635V1pbxY17X5bcZGhmA4NmJ5TL07ttYbZxUjIuPtBJh/ecn4TBNWZ8vmT2lhHGe0nTkdw/DyiuL1CPoEGwWcGLk+/pd2VQrxe3q8Rq3REc6OT0RTHplPfHajyrennxQnAPBqLE4+3HGlet6/ExXrN5+/Zwh9f6PHaOI=

### Visual documentation

<img width="831" alt="Captura de Tela 2024-10-01 às 19 41 28" src="https://github.com/user-attachments/assets/a1a13199-12a1-4085-9b2e-410f5b795039">
<img width="853" alt="Captura de Tela 2024-10-01 às 19 40 08" src="https://github.com/user-attachments/assets/49aba38f-9333-4dc0-bdb0-ca54b4513cb8">
<img width="898" alt="Captura de Tela 2024-10-01 às 19 39 51" src="https://github.com/user-attachments/assets/566f2b2c-b60f-48aa-b4c8-5c295170be28">

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.2 released October 1, 2024
- Platform: Web and MacOS Desktop
- Browser name and version: Google Chrome 129.0.6668.59
- Operating system and version affected: MacOS 15 Sequoia Apple M1
```

**Comment by decoded-io** [comment] 2024-10-03 14:34
I'm running into this exact same issue. Screen recording: https://github.com/user-attachments/assets/4fff2cf3-a83e-48ac-b0be-c3e4f3f6eda0

**Comment by Alezanello** [comment] 2024-10-03 17:53
Hello!

I can confirm the issue, and it seems to be related to how imported libraries are handling custom actions. Thank you for providing the video—it made it easy to replicate the problem. I'll forward this to the engineering team for a closer look and a fix.

**Comment by AnushaFF** [comment] 2024-10-07 16:58
Thank you for reporting the issue! We have identified and fixed the issue. It will be released in 1-2 weeks!

**Closed as completed** 2024-11-18 18:49 UTC
Labels: status: confirmed, Bug
