### ISSUE TITLE
TEST MODE takes me to a deleted page that doesn't exist in the project.

### ISSUE THREAD

**Issue by ingsistempro** [FlutterFlow/flutterflow-issues#4098] opened 2024-10-17 23:16 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

TEST MODE  is not reflecting the changes; it's still showing an old version."
 **RUN MODE** button does take me to the correct page-

Another recurring anomalous behavior: each time I make a change in the project, it briefly accepts the modification but then reverts to displaying the previous information, whether it be an image, text, or a widget. This is happening consistently.

### Expected Behavior

"Test Mode is not reflecting the changes; it's still showing an old version. The Run Mode button takes me to the correct page. I need Test Mode to load the latest version of the project with the most recent development updates, as I'm encountering an error when trying to upload the local environment."

### Steps to Reproduce

1.Open the project.
2.Click the TEST MODE button.
3. is not reflecting the changes.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESifHf0IZgou4D+c/IbO16hQIgQ0QnU7gnlO1ucx4jGOOuP5YUPuDRcUNKT+GzeFZqKFaZ+Uce0M2Ni+HuGPdcHxOtY4Rb0JVAVQLiWji6Vaq4PKm0WURQFp9YCh3A4J2OkB14ALdhV3wT7EytN63qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

![image](https://github.com/user-attachments/assets/43c64ea1-0b37-4ba5-bb18-198dea106f84)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.5+ released October 9, 2024
Flutter version is 3.22.2
- Platform:windows
- Browser name and version:Buscando actualizaciones…
Versión 1.71.114 Chromium: 130.0.6723.58 (Build oficial) (64 bits)
- Operating system and version affected: icrosoft Windows 11 Pro
```

### Additional Information

Another recurring anomalous behavior: each time I make a change in the project, it briefly accepts the modification but then reverts to displaying the previous information, whether it be an image, text, or a widget. This is happening consistently.
 I have already lost about 48 hours of work.

**Comment by Alezanello** [comment] 2024-10-18 11:40
Hi there!

I'm sorry to hear you're facing this issue. I’ve tried replicating it in a new blank project but haven’t been able to reproduce it. Since this GitHub issue tracker is primarily for bugs that can be consistently replicated, I recommend reaching out to our support team directly for further assistance. You can contact them via the in-app chat or by emailing [support@flutterflow.io](mailto:support@flutterflow.io). They’ll be happy to help you resolve this!

Thank you for your understanding.

Best regards,<br>Azanello

**Comment by ingsistempro** [comment] 2024-10-18 13:45
Why does "TEST MODE" take me to a deleted page that doesn't exist in the project? How is it that, despite being deleted, the system still executes it?

**Comment by devlesorcier** [comment] 2024-10-20 09:54
Can you sir please se on the Admin folder on your screen, I'm pretty sure your page exist ;)

**Comment by ingsistempro** [comment] 2024-10-23 23:49
Every time I click the Test button in Local Run, I get the following error:

![image](https://github.com/user-attachments/assets/6e9d0218-53cb-413e-baf2-ad0cd041c8cd)

![image](https://github.com/user-attachments/assets/ca8ebf3e-71af-43e6-b1c8-4d0f2c054670)

**Comment by Alezanello** [comment] 2024-11-07 15:48
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by Alezanello** [comment] 2024-11-15 19:26
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Closed as not planned by Alezanello** 2024-11-15 19:26 UTC
Labels: status: can't reproduce

**Comment by devlesorcier** [comment] 2024-11-20 10:48
This problem is now solved. Thank you sir, please have a great day
________________________________
De : Alezanello ***@***.***>
Envoyé : vendredi 15 novembre 2024 20:27
À : FlutterFlow/flutterflow-issues ***@***.***>
Cc : devlesorcier ***@***.***>; Comment ***@***.***>
Objet : Re: [FlutterFlow/flutterflow-issues] TEST MODE takes me to a deleted page that doesn't exist in the project. (Issue #4098)


Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
