### ISSUE TITLE
Dropdown selection seems unclickeable when choose and option

### ISSUE THREAD

**Issue by wlinaresmartinez** [FlutterFlow/flutterflow-issues#2666] opened 2024-04-04 22:37 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello good afternoon, Almost 3 or 4 days ago i've create 2 dropdowns in my project to filter branCars and Models. The function is simple, if i choose one brand in the second dropdown will show the models list from the brandCard choose. I create 2 cars in testing mode and works great. Now im making a general testing of that section that was working fine and now if i choose an option form a dropdown when i try to click on the other dropdown to choose the model, it seems is unclickeable. So i cant continue with the add car process.

Also im trying to replicate the same but in other dropdown, using a category and subcategory. And the behaviour is the same. when i choose the category then i try to choose a subcategory and the other dropdown it seems inactive or unclickeable. I dont know what else i can do.

I dont know if you implement something new in dropdowns or something

![error-drop](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/974ef073-f70b-40f7-86d8-0f46cf0b5f08/feb63727-67b7-4258-aef4-e37051fdd282?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85NzRlZjA3My1mNzBiLTQwZjctODZkOC0wZjQ2Y2YwYjVmMDgvZmViNjM3MjctNjdiNy00MjU4LWFlZjQtZTM3MDUxZmRkMjgyIiwiaWF0IjoxNzEyMzMxNTA4LCJleHAiOjMzMjgyODkxNTA4fQ.imXme2RyVeslstbBzOyRI8Xmua8uABlW8ldjYCUS3nU)

![error-drop2](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/2c564f49-5e00-485a-8111-379765577e78/7b2231b7-36c6-472f-a9e9-36dcf6efbf3a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yYzU2NGY0OS01ZTAwLTQ4NWEtODExMS0zNzk3NjU1NzdlNzgvN2IyMjMxYjctMzZjNi00NzJmLWE5ZTktMzZkY2Y2ZWZiZjNhIiwiaWF0IjoxNzEyMzMxNTA4LCJleHAiOjMzMjgyODkxNTA4fQ.v0BSPlBgrR9yrV159NgiuqKMglNG352J5nd0ctXv2Fk)

![error-drop3](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/9ff3c3f3-a500-412e-8b37-9cb4d9158a66/407f9fe7-801a-44d3-89dd-33b292027596?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85ZmYzYzNmMy1hNTAwLTQxMmUtOGIzNy05Y2I0ZDkxNThhNjYvNDA3ZjlmZTctODAxYS00NGQzLTg5ZGQtMzNiMjkyMDI3NTk2IiwiaWF0IjoxNzEyMzMxNTA4LCJleHAiOjMzMjgyODkxNTA4fQ.kuUtFWzcIHqwZQtZm59jM5Xlg6cDZQNv4EeuobRLsVI)

![error-drop4](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/2d922664-19ff-46da-8f03-8fa8603a264a/55f996ca-ebc8-48f0-853b-281a1e98069c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yZDkyMjY2NC0xOWZmLTQ2ZGEtOGYwMy04ZmE4NjAzYTI2NGEvNTVmOTk2Y2EtZWJjOC00OGYwLTg1M2ItMjgxYTFlOTgwNjljIiwiaWF0IjoxNzEyMzMxNTA4LCJleHAiOjMzMjgyODkxNTA4fQ.TvDInTteYvBapb4jpW7p4_3hzN2lWp319w9LWZ0KpAQ)

### Expected Behavior

Almost 3 days ago everything was working okay because i test those dropdowns almost 10 times before continue with my develop. Now when i try to choose the second option from the other dropdown, it seems to be inactive or unclickeable, so i cant choose the other option to continue with the workflow.

### Steps to Reproduce

1. Click on Cliente Button.

![test1](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/7669de43-46ae-447e-a22f-a4df6e84b545/8ba9d976-d0e9-44c1-849b-b26fed2db1c2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83NjY5ZGU0My00NmFlLTQ0N2UtYTIyZi1hNGRmNmU4NGI1NDUvOGJhOWQ5NzYtZDBlOS00NGMxLTg0OWItYjI2ZmVkMmRiMWMyIiwiaWF0IjoxNzEyMzMxNTA4LCJleHAiOjMzMjgyODkxNTA4fQ.umPsmpBLUjAhVkrlSBQL09zLpvUjaD20HLgnX7Zviag)

1. Click on the item.

![test2](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/2db35c5f-8a8d-4f58-9836-19322e030dfe/5d681103-fe14-4ff0-b80f-dd07dba88037?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yZGIzNWM1Zi04YThkLTRmNTgtOTgzNi0xOTMyMmUwMzBkZmUvNWQ2ODExMDMtZmUxNC00ZmYwLWI4MGYtZGQwN2RiYTg4MDM3IiwiaWF0IjoxNzEyMzMxNTA4LCJleHAiOjMzMjgyODkxNTA4fQ.xDVTp4LuR9r-6c58cWrQ8LiclPJz5CMw460S7noEr-s)

1. Click on the "+" add button to show the bottom sheet and choose the options to add a car. In those dropdowns are the issue. If you choose the Brand, you wont be able to choose the model, because the second dropdown will be inactive. I dont know why. As i say, that section was already finished.

![test3](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/6fbf09b0-2b14-4b1b-8a21-1d157bb366ae/904156a1-2979-49fc-9535-56eabaeb001d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82ZmJmMDliMC0yYjE0LTRiMWItOGEyMS0xZDE1N2JiMzY2YWUvOTA0MTU2YTEtMjk3OS00OWZjLTk1MzUtNTZlYWJhZWIwMDFkIiwiaWF0IjoxNzEyMzMxNTA4LCJleHAiOjMzMjgyODkxNTA4fQ.oQujfA8IETnhyhT_NHJcC-SwVSl-MzR5BgFDuzlsBJo)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfiMjfsYtOodta7a6Jc8BKpD8WOWUcTZM3lOsYGU03IaqvPLATP8zUaXdBT+njSkFEHGGiglw0/vz0itriU8IBNSmuY6l607oNWzrvUmGWSozQC8yKYkFfJ+5nCm685rSJoSZAWfJpLl0t71+Hcq3qNleeY8aSfxBlZ7vfcPo=

### Context

this issue affect my app function because im trying to not make the users write so much in the app, only choose options, because i can keep my database safe from typdo or spelling errors.

### Visual documentation

![error-drop](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f977dd20-772b-46ca-a3ce-70a0f10db2e8/4e5642a6-be37-47e8-a40c-e3761a28f111?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mOTc3ZGQyMC03NzJiLTQ2Y2EtYTNjZS03MGEwZjEwZGIyZTgvNGU1NjQyYTYtYmUzNy00N2U4LWE0MGMtZTM3NjFhMjhmMTExIiwiaWF0IjoxNzEyMzMxNTA4LCJleHAiOjMzMjgyODkxNTA4fQ.AmcEmR_cD6mZppzPL6LlRGvc5eBVGaXpNpCb6IHlNwA)

![error-drop2](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/ec7b904a-aae6-4300-8c29-84d6af8c9575/ed7c554e-279f-4a4d-bdb9-d90ba356893b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lYzdiOTA0YS1hYWU2LTQzMDAtOGMyOS04NGQ2YWY4Yzk1NzUvZWQ3YzU1NGUtMjc5Zi00YTRkLWJkYjktZDkwYmEzNTY4OTNiIiwiaWF0IjoxNzEyMzMxNTA4LCJleHAiOjMzMjgyODkxNTA4fQ.PWqBQEemkI6sh8a4GWvmM5jsiWWZyT27ye93_2jZ6bo)

![error-drop3](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/fe9fcc63-c934-4399-b97e-d6950bad4168/2745edac-0695-4f09-91c0-ac0c80cee8d8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mZTlmY2M2My1jOTM0LTQzOTktYjk3ZS1kNjk1MGJhZDQxNjgvMjc0NWVkYWMtMDY5NS00ZjA5LTkxYzAtYWMwYzgwY2VlOGQ4IiwiaWF0IjoxNzEyMzMxNTA4LCJleHAiOjMzMjgyODkxNTA4fQ.ndgoKmaSQsy-x-X1BaInsWZqdKkQwEswNsjA_qCfUN0)

![error-drop4](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/ae16947c-9194-4336-8f5f-6d3e1a2c4458/01014c2d-d062-4945-94be-279129a37f75?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hZTE2OTQ3Yy05MTk0LTQzMzYtOGY1Zi02ZDNlMWEyYzQ0NTgvMDEwMTRjMmQtZDA2Mi00OTQ1LTk0YmUtMjc5MTI5YTM3Zjc1IiwiaWF0IjoxNzEyMzMxNTA4LCJleHAiOjMzMjgyODkxNTA4fQ.htbY8iUWSZP_h-cOFU_WMNkY72MO8ADK7Nyuz-zfYLs)

![test1](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/23ee2e85-b960-47e1-9725-a846f03470d1/c608f276-79e1-48e1-a189-539f7ff540d0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yM2VlMmU4NS1iOTYwLTQ3ZTEtOTcyNS1hODQ2ZjAzNDcwZDEvYzYwOGYyNzYtNzllMS00OGUxLWExODktNTM5ZjdmZjU0MGQwIiwiaWF0IjoxNzEyMzMxNTA4LCJleHAiOjMzMjgyODkxNTA4fQ.rsmndcgS-VZGkoWaJ1D0nSzscuaknlw_9WqF-Cuybyc)

![test2](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/dfbfb6f1-c6ac-4360-bd77-f42909476605/d09e5e99-feb4-47ac-9260-c3378b69ac58?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kZmJmYjZmMS1jNmFjLTQzNjAtYmQ3Ny1mNDI5MDk0NzY2MDUvZDA5ZTVlOTktZmViNC00N2FjLTkyNjAtYzMzNzhiNjlhYzU4IiwiaWF0IjoxNzEyMzMxNTA4LCJleHAiOjMzMjgyODkxNTA4fQ.mSR9q8Y8E2lwt5pMKN2klhZf9O7WfH5_tZE40CmHBsY)

![test3](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/66dba345-9c7c-48fb-a603-e500f03363d9/b5db0267-43f2-4e27-ad8b-adcd53c3efb4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82NmRiYTM0NS05YzdjLTQ4ZmItYTYwMy1lNTAwZjAzMzYzZDkvYjVkYjAyNjctNDNmMi00ZTI3LWFkOGItYWRjZDUzYzNlZmI0IiwiaWF0IjoxNzEyMzMxNTA4LCJleHAiOjMzMjgyODkxNTA4fQ.1SCuLJNUxGLa-g5u5bTRrKpxNgwZnG-HaEtgIN6pTuc)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: V4.1
- Platform: Mobile
- Browser name and version: Versión 123.0.6312.88 (Build oficial) (64 bits)
- Operating system and version affected: windows 11
```

**Comment by bozzoleandro** [comment] 2024-04-05 19:17
Hi @wlinaresmartinez, thanks for your report, we were able to replicate the issue. We're going to take a look at it. What you can do to select the values from the dropwdown, is clicking in the text or in the arrow, and you'll be able to change it.

**Comment by wlinaresmartinez** [comment] 2024-04-05 19:47
Hello @bozzoleandro I tried to do what you say before send this report. I make all kind the test. And it have the same behavior . When i choose the BrandCar im not able to choose the modelCar in the second dropdown.

And this worked 2 days ago when i implement that. Now is not working

**Comment by wlinaresmartinez** [comment] 2024-04-13 14:33
Im waiting for response

**Comment by leighajarett** [comment] 2024-05-08 21:43
We're working on a fix, thanks for your patience!

**Comment by paulperez-dev** [comment] 2024-05-14 06:15
Hi @wlinaresmartinez! We are no longer able to reproduce this issue, this may have been solved in one of our latest releases. Can you please verify? 

If the issue persists, please submit a new bug report code from a minimal blank project with the issue replicated.

If the issue is already resolved for you, please feel free to close the issue. Thanks!

**Closed** 2024-05-15 22:24 UTC
Labels: status: confirmed, Bug
