### ISSUE TITLE
Google Login on Android not working!

### ISSUE THREAD

**Issue by Kato-Official** [FlutterFlow/flutterflow-issues#3391] opened 2024-07-13 04:29 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When testing the Google login on real Android device does not work. The pop up appears, after touching the user account to login in with it disappears and nothing happens.

### Expected Behavior

Google Login to work on Android devices.

### Steps to Reproduce

1. Created a new project with Firebase full setup
2. Followed by the letter the entire "Initial Setup" (Including the Debug SHA1 Key and adding domains on Firebase and Google Cloud.)
3. Added the SHA1 Fingerprint to the Firebase Android Project Setting and saved
4. Regenerated configuration files in FlutterFlow
5. Added Provider on Firebase Google
6. Tested on FlutterFlow Test Mode (Working great!)
7. Tested on Web (Working great!)
8. Tested on iOS (Working great!)
9. Tested on Android (Not Working!): Pop up comes up, but when touching the account to login in with nothing happens and the pop out closes.
10. For extra measure I also tried by Linking Cloud Project to App Integrity (Same results, Android devices Google Login No Working!)
FYI: On Run mode you currently can not Test due to iFrame sandbox not approved in domain list and possibly because of the new Google update since June about third party (I believe this bug is already reported but not currently solved).

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESjfLq24lgrtsF+c72Ke5AhQIgQ0QnU7gnlO1ucx40NYjoPbQEOuD8Q0NKT+3jeHxiIGCKkj8ewNLIkeDLD8deBzWWGohD0JVAaxfgbHG5MoiaCKqWYn9SL+ZUIU+By6WjgBVSIbF2SkYE7V2DNq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

![App](https://github.com/user-attachments/assets/b7b59d3c-0025-445d-817e-3f37a9970789)
![Firebase Fingerprint](https://github.com/user-attachments/assets/ddf88614-0e2a-4093-85c1-f0d79128bedd)
![Firebase Approved Domain](https://github.com/user-attachments/assets/d5c44eb7-5c33-41ba-89a9-175c78bc1c44)
![Google Cloud Approved Domain](https://github.com/user-attachments/assets/174ab2c5-e0e5-49ce-b79b-c0ea0065f216)

### Environment

```markdown
- FlutterFlow version: v4.1.72+ released July 12, 2024 Flutter version is 3.22.2
- Platform: Android
- Browser name and version: Native App Real Device Test
- Operating system and version affected: Android
```

### Additional Information

User not able to login with Google which is the primary method used by most user, especially Android users (since they have no access to Apple login).

**Comment by greghesp** [comment] 2024-07-14 16:09
There's something buggy somewhere.  If you disable the enumeration protection under the auth settings, it throws the full error.  I was trying to sign up and it was erroring saying the user did not exist.  Something funky happened with the actions where the whole login/create flow got messed up.  

Try disabling FB auth in the project, and re-enabling it, or delete and recreate the action for login/create

**Comment by Alezanello** [comment] 2024-07-15 13:01
Hello!

This appears to be more of a Firebase Auth issue rather than a FlutterFlow bug. I couldn't replicate this issue in a new blank project. Could you please try following @greghesp's advice to see if it provides more insight?

Alternatively, you can contact support via the in-app chat or at [support@flutterflow.io](mailto:support@flutterflow.io) for assistance with your specific project situation.

Best regards,<br>Azanello

**Comment by greghesp** [comment] 2024-07-15 13:03
I'm pretty sure it's a FF bug.  My app worked fine, and then randomly broke. I had to basically delete and recreate the action exactly the same to fix it. 

By the time I figured out the cause though, I couldn't replicate it to file a bug and assumed it was just me. Seems perhaps it's not

**Comment by Alezanello** [comment] 2024-07-16 11:39
Hello again!

I've been trying to replicate the issue without success. Are you still experiencing this problem in your project?

**Comment by Kato-Official** [comment] 2024-07-16 12:31
Hi, hope you are well and thank you for your message. Yes, the only way I found to make it work was to either create a "release" key or to use the one from app signing section from the Google Console. This would all be well and good if effectively I was publishing already the app, however it is not recommended to use for internal testing track. Regardless I fixed it like so. You can start from scratch with a new project, and you'll see you'll face the same issue when testing on real Android device (Not Emulator on Android Studio). Cheers.

**Comment by Alezanello** [comment] 2024-08-06 13:09
Hello,

I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

Best regards,<br>Azanello

**Comment by Alezanello** [comment] 2024-08-09 14:36
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Closed as not planned by Alezanello** 2024-08-09 14:36 UTC
Labels: waiting for user response
