### ISSUE TITLE
Periodic action ,that update  location local state are laggy and gps icon glitching

### ISSUE THREAD

**Issue by berryvangrand** [FlutterFlow/flutterflow-issues#1280] opened 2023-08-16 10:44 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

My app working well on iOS but not on android:

I have a periodic action, that update a LatLng app state and rebuild page in every 10 ms. That is required for the realtime UI changes.

On iOS this action work well, no issue, on android the UI is laggy, like 15 fps and the gps icon is glitching.

Only appear on android.

### Expected Behavior

Need to be smooth on every platform.

### Steps to Reproduce

1. Create a page and an app state (LatLng)
2. Add an action to Scafford (at page load) and give a 10 ms periodic action
3. in side the action set the app state (LatLng) with the variable (device current location)
4, make a text and text need to be from a variable and a custom action that gives the lat or long parameter as a string.

you can see that the parameter is not smoothly change, instead laggy on android. (But you can make with a random integer as well.)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4SlsmAsJdPm9xE7oSJbu9agSQRMjs/RYIwlu5QEAs2B5TqOu0fXOj9SFRuZNe6T2w7JWCi8HMJpsHGufD2G8A9PiitfJ98z6h+bxXdWXOVVK6DC6iSbXNRGphgfEeHzbuNsxZ/C7Z1LEEs71OUHtmUVgnBNabWDTAnGPyhEJLOo3iLGgzOXn0Jg1ZSfCvr

### Context

Can publish to android, the app is done instead of this!

### Visual documentation

I send if required

### Environment

```markdown
- FlutterFlow version: latest
- Platform: Android
- Browser name and version: Sidekick 112.47.1.33931
- Operating system and version affected: macOS Monterey 12.2.1
```

**Comment by kevintonb** [comment] 2023-08-18 12:08
Hey @berryvangrand , thank you for preparing this report. But I'm finding it hard to reproduce the issue exactly as intended in the instructions that you have added in the steps to reproduce. Can you please create a sample project with the exact implementation to expose the bug? This will be very helpful for us to troubleshoot the issue that you're facing and investigate further.

**Comment by berryvangrand** [comment] 2023-08-18 12:13
This is the real app:
https://app.flutterflow.io/project/booard-g-p-s-t-i-c-k-l8smwv

and I created a sample for only this issue:
https://app.flutterflow.io/project/compasstest-38fjiw

**Comment by berryvangrand** [comment] 2023-08-24 12:10
The videos about the issue on android:
This is the App State based location value.
https://drive.google.com/file/d/1T3R6fDpw3YPL99AxYiAMtqWGJd7FmZSD/view?usp=sharing

And if I try to get this value directly from "Device Current Location" and the update action only a random integer:
https://drive.google.com/file/d/1CCzPg3BWXzcSXICfLML4F833_jwRWL6v/view?usp=sharing

**Comment by kevintonb** [comment] 2023-08-30 08:57
Hey @berryvangrand , I was not able to find the issue from the project that you have shared. But thank you for giving out a clear explanation which correctly expresses your concern. When you're setting the value from a random integer from the AppState, the computation for the random integer is done within the scope of the app itself and does not require any feedback from the device hardware / sensors explicitly. So, when you're making an update every 10ms which is 100x update per second (which is still a huge number that'll impact the app performance), the random integer is generated with ease. But when you're doing the same 100x updates with the device location, the gps is accessed for every single request which will delay your updation time quite a bit and this is an expected behaviour. I would suggest you to reduce the frequency interval and increase the duration to more than 10ms to have a smoother experience. This would ensure better performance and user experience in your application. Since this is not a bug within Flutterflow itself, I'm closing this issue for now. But thank you for supporting us and actively working on helping us improve the platform.

**Closed by kevintonb** 2023-08-30 08:57 UTC
Labels: status: needs triage, status: needs reproducible steps, needs a blank project with issue setup
