### ISSUE TITLE
Integer Variables do not return 0 in API calls

### ISSUE THREAD

**Issue by Bar343** [FlutterFlow/flutterflow-issues#875] opened 2023-05-10 21:28 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When making an API call, a JSON Syntax error is returned when integers are not set. This is not an expected behavior as integers have  default value of 0, but this does not  happen in Flutterflow when using variables.  Took me and a support member sometime to isolate this.  integer variables SHOULD be set to 0. as formatting the JSON body does not return any errors, implying that values are correctly set.
I had to manually input the default value of 0 into each variable. It should be clear that this is not a default behaviour.

### Expected Behavior

integer variables should have default value of  0, or the format button should pick up the error and let the user know.

### Steps to Reproduce

1. create a POST request that requires (optional) integer inputs.
2. create variables that correspond to the inputs.
3. place the variables in the corresponding keys in the JSON body and run the request.

### Reprodcible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Ol/LfsM5IsfVA+KrqccAwpDkXQ0w2U5ZN18J+Vk00GOLNG7UIec/4VEptXbC+TVc3OmCZhT4JzNKOv+bIN+07AzWtQL5dzLhMegGVQmGhb4+aCaqoX0YnHtpKBWKl55m3vxFdANtaSk4M3F+uOPOiYCnXQb7sCzJABOWIE9vXnXfuQ0SLb3kNh1JWeC/v

### Context

Delayed the completion of the project as the API call was critical.

### Visual documentation
![error report image 1](https://github.com/FlutterFlow/flutterflow-issues/assets/52680054/eaf6900f-8f0b-415a-a2b8-2fb7993388a8)
![error report image 2](https://github.com/FlutterFlow/flutterflow-issues/assets/52680054/7ed46ffe-9297-4d81-9266-9c8eaf158242)

Not applicable

### Environment

```markdown
- FlutterFlow version: 3.7.12
- Platform: Web 
- Browser name and version: Edge Version 113.0.1774.35 
- Operating system and version affected: Windows 10
```

**Comment by bulgariamitko** [comment] 2023-05-13 15:19
Can you provide a screenshot as well?

**Comment by Bar343** [comment] 2023-05-15 21:52
images are attached. thank you.

**Comment by bulgariamitko** [comment] 2023-05-15 22:08
@Bar343 is it possible to show the same response from Insomnia or PostMan as well to see the differences?

**Comment by Bar343** [comment] 2023-05-15 22:47
To my knowledge, in Postman, inputting 0 is what defines it as an integer (see attached), so the error does not occur. Thus, when a variable in Flutterflow is set to integer, zero should be a default as this is the expected behaviour.
![api error](https://github.com/FlutterFlow/flutterflow-issues/assets/52680054/90848994-de89-4a99-ae58-dde314d3cb07)

**Comment by bulgariamitko** [comment] 2023-05-16 07:11
@Bar343 I got what you mean, but did you try to put 0 as default value for the variables that are int and test it? 
You are right as the default value of an int should be 0 I will mark this issue as bug and let FF decide if it is as there might be some logic behind this that I do not know why it is like that.

**Comment by takashiff** [comment] 2023-09-21 19:32
Hello, thank you for your bug report. This has been confirmed as intended behavior and will now be marked as closed.

**Closed by takashiff** 2023-09-21 19:32 UTC
Labels: type: bug, status: confirmed
