### ISSUE TITLE
Error in Booleaen

### ISSUE THREAD

**Issue by wzbearb** [FlutterFlow/flutterflow-issues#3439] opened 2024-07-19 08:24 UTC
### Can we access your project?

- [x] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I made 3 page states. 
1. interger(quizScore) 
2. interger(howManyQuestiontd) 
3. boolean(lessonFinished)

I made a conditional action that if 1==2 set pagestate3 to true. 
<img width="1287" alt="스크린샷 2024-07-19 오후 5 05 50" src="https://github.com/user-attachments/assets/04f91a33-6018-4623-9c4b-f751cb527df9">

This sometimes work and sometimes doesn't work. Maybe 50%? Not touching anything else, just trying it over. 

I have copied this action from another widget, and it works perfectly there. I think it is a problem with the boolean because the debugger shows the same number at the interger section. Interger working perfectly. Just sometimes false, sometimes true. 

 
<img width="1086" alt="스크린샷 2024-07-19 오후 5 08 20" src="https://github.com/user-attachments/assets/12d5971c-a2a0-4201-b53b-d1505c7f0dc8">

The boolean endLesson is just added to check whether it's overrided with other actions. After adding it, I just added conditional action 'quizScore==howManyQuestiontd' - true - update Page State - endLesson - set Value True

### Expected Behavior

Boolean always working,

<img width="1287" alt="스크린샷 2024-07-19 오후 5 05 50" src="https://github.com/user-attachments/assets/fa5e11c0-c2b4-4350-9ff5-0157b102a876">

### Steps to Reproduce

1. create a new page
2. add 3 pagestate

1) interger(quizScore) 
2) interger(howManyQuestiontd) 
3) boolean(lessonFinished)

3. 1) and 2) is set as the same number by quering a data when the page view is scrolled.

3. make a icon button that has action

'quizScore==howManyQuestiontd' - true - update Page State - endLesson - set Value True

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFflvHlz4Z1m8tD1r6JavpVuDgXQzocTOURiO0bFDsdF4iuPOxzac7BfkhoZ7zhY2xpKEWIhk8HzNKKi9jXV8Y5OU+sRtw4yJdhVQzdTl6/aoSuPZC0bXBCM8NUIHHG052NvhUmKttvSUYH7E2qHfOtFjDAQY/7Zwh9f6PHaOI=

### Visual documentation

<img width="1287" alt="스크린샷 2024-07-19 오후 5 05 50" src="https://github.com/user-attachments/assets/b7899807-fc4d-46b4-9798-85cebaecdd6c">
<img width="1106" alt="스크린샷 2024-07-19 오후 5 08 07" src="https://github.com/user-attachments/assets/fdfd1ad8-1bba-43f6-8f89-0e562d764fc8">

### Environment

```markdown
- FlutterFlow version: 4.1.74
- Platform: ios,android
- Browser name and version:
- Operating system and version affected: 
ios 17.5.1
android 12
```

**Comment by msusviela** [comment] 2024-07-19 19:27
Hey @wzbeard, Thanks for your report, So sorry you are experiencing this issue. I was not able to reproduce this on a blank project, but if it is replicable on yours I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. Thanks so much!

**Closed as not planned** 2024-07-19 19:27 UTC
Labels: closed: support request
