### ISSUE TITLE
Compilation Error due to dependencies

### ISSUE THREAD

**Issue by drgundy37** [FlutterFlow/flutterflow-issues#3363] opened 2024-07-10 19:22 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The addition of the FlutterFlow element SwipeableStack (not custom) to any page causes the compilation to fail. Only on my specific project. If I make a new project and add one, there are no issues. 

### Expected Behavior

Compilation is without error. 

### Steps to Reproduce

1. Create new page
2. Add SwipeableStack widget
3. Run in test mode
4. Build fails

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfi/Hl389gobQB0L6JY+5KgiAXOWUcT+Qz0e5xYxQgGJDtBIgIP/TBSFBUOPHgTXxbM2GkrGIX/MqOhofxVu46JT+efNRzzqpiEALxVnuuM7q4C763b3NQGdlXC2qDy6WN2CJDC7ZYWXgG3FOXf9ivUnbcGJzzOlgzReaoXdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/68656791/4ad41526-bd7b-47a1-8f77-8f78fc3de5af)

### Environment

```markdown
- FlutterFlow version: v4.1.70+ released July 10, 2024
Flutter version is 3.22.2
- Platform: Browser and Desktop
- Browser name and version: Chrome
- Operating system and version affected:
```

**Comment by drgundy37** [comment] 2024-07-10 19:35
I restored from a snapshot from the day prior and I am able to compile with the SwipeableStack in hte platform. I have a duplicated project pre-snapshot that still won't compile.

**Comment by msusviela** [comment] 2024-07-10 21:20
Hey @grdundy37, Thanks for your report, So sorry you are experiencing this issue. I was not able to reproduce this on a blank project. That's why I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. Thanks so much!

**Closed as not planned** 2024-07-10 21:22 UTC
Labels: status: can't reproduce
