### ISSUE TITLE
Renaming items in the Widget Tree fails if mouse moves outside of input

### ISSUE THREAD

**Issue by k98kurz** [FlutterFlow/flutterflow-issues#1380] opened 2023-08-30 00:10 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I try to rename something in the widget tree, if the mouse is not hovering above the text input the entire time, it unfocuses the input. Additionally, since the widget tree view automatically scrolls, it automatically unfocused while I type even if I try to keep the mouse hovering over the input.

### Expected Behavior

The input should remain focused until the mouse clicks elsewhere, the enter button is pressed, or some other explicit unfocus event occurs. The widget tree automatic scrolling should not occur if it causes the input to unfocus.

### Steps to Reproduce

1. Create a new project.
2. On the first page, add a lot of parts in a widget tree: column > row > column > row > text; duplicate top level row several times.
3. Add another page.
4. Switch back to the first page.
5. Enable the "Stack Pages and Widget Tree Views" option.
6. Double click to rename something in the widget tree and start typing.
7. If it auto scrolls, it will unfocus automatically. Otherwise, move the mouse to hover over any other thing in the widget tree view.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Wz/Hqx89goddG15SJcMdVryQWHFw4a+Y30sNxcxE3fb7qEZwPQvj7PxFUOdSrY2NIP06Wgj8X/MnIiuDxMvcqCzSVUbU6+s1ydzuVUl+6VqbTPb63b0ZCJ5pVBWKa5qurvyVCCONicWQH7VOletzIcBDfJ7rvDlQ0AOa4XdeK2SrDX1iXc2URm05KZDPz

### Context

I rename things in the widget tree so it is easier to interact with them in actions.

### Visual documentation

Could not upload the screen capture directly, so here is a link to the video on ThemTube.

[https://youtu.be/9nUJHQ5paRk](https://youtu.be/9nUJHQ5paRk)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Vivaldi 6.1.3035.302 (JS engine: V8 11.4.183.29)
- Operating system and version affected: Ubuntu 22.04
```

**Comment by hariprasadms** [comment] 2023-08-30 12:07
Hi @k98kurz - Thanks for posting the issue. I tried the above steps you showed in the video and steps. But, not able to reproduce the issue. Looking at the procedure of steps,  I believe it may be inconsistent behaviour. I would advise trying several times to determine how persistent the issue is. If the problem is consistent and it still exists, please let us know. This issue can now be marked as _**not a bug.**_

**Comment by k98kurz** [comment] 2023-08-30 16:50
Happens consistently for me. Might be specific to my browser. I disabled all extensions and browser safety features (i.e. preventing trackers), but the issue persists.

**Comment by k98kurz** [comment] 2023-09-02 16:09
Replicated in Chromium 116.0.5845.140.

**Closed** 2023-09-04 09:58 UTC
Labels: closed: not a bug
