### ISSUE TITLE
Can't add to set (list) Firestore server timestamp

### ISSUE THREAD

**Issue by alih552** [FlutterFlow/flutterflow-issues#3505] opened 2024-07-29 13:38 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When trying to add to a list by using add to set action it doesn't allow me to add a Firestore server timestamp. but when I try to use user current device time, it works fine.
The fields data type is date time and is a list.

### Expected Behavior

It should work.

### Steps to Reproduce

1. create a field with a data type of date time and set is list to true
2. create a new page and add a button
3. add a new action (update document)
4. select the field and try add to set and select Firestore server timestamp 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kjcr1z5R1obxY0LXTbfpWoCcXJVx+TLJMt9VxSUghfeKsE+wMYM+kdhdLYtezeVBEeGKjmk0K+Nbev9jLLscCByysbqZz+ZRXQQmUd3yhMa6LPJCoWnR7O8RhClyY1rWG2wlBLsR1S1IQwDuQf/CdG3qCf9qOYwx5e6fDbOY=

### Visual documentation

<img width="286" alt="image" src="https://github.com/user-attachments/assets/d71cc2d9-6f40-4b84-ace6-7d62d242b102">
<img width="680" alt="image" src="https://github.com/user-attachments/assets/2ee74153-b73c-4c4a-abfa-c45873b37d86">

### Environment

```markdown
- FlutterFlow version:v4.1.78
- Platform: MacOS app
- Browser name and version: -
- Operating system and version affected: -
```

**Comment by paulperez-dev** [comment] 2024-07-30 03:12
The message is that `Timestamp` data type is not compatible with `DateTime` data type. Consider using a custom function to change the type before assignation. This is not a bug, I'm closing this issue.

**Closed as not planned** 2024-07-30 03:12 UTC
Labels: closed: not a bug

**Comment by alih552** [comment] 2024-07-30 14:08
@paulperez-dev but it works normally and just fine when trying to use Firestore server timestamp in a dateTime field that is not a **list**

The problem is when it's a list.

**Comment by paulperez-dev** [comment] 2024-08-27 11:41
Can you please reproduce the issue on a blank project and share the bug report code again?

**Comment by alih552** [comment] 2024-10-31 12:16
@paulperez-dev  

I've created a new blank project
Bug report code: IT48z8rluJNPxd9Y1qX5bcJagioRJl87UI0a1sJHYEw8KOPdOoYUP8+kM0RvXe6oT3x2ImKWjWoW06nuvuOWM8cBAw+tbLpA+qphVQ3yJXyXRLqDFJWgSEFtN/9mCm6P5J+3qhInBPVZWHAd2U+bfvC/c3bDJpuxPUgkDq/LZO4=



++ Also there is no way to create this custom function because FlutterFlow does not provide timestamp argument type in custom functions window.

**Comment by alih552** [comment] 2024-10-31 16:28
@Alezanello fyi

**Comment by alih552** [comment] 2024-11-06 12:48
@leighajarett
