### ISSUE TITLE
Issue in the installation process of a Web App (Flutterflow logo instead of the app logo itself).

### ISSUE THREAD

**Issue by jerodesign** [FlutterFlow/flutterflow-issues#324] opened 2023-01-06 12:25 UTC
When you install the web version on a mobile device, both the splash screen and the app icon are Flutterflow's instead of those of the app itself. All this despite having correctly configured the Favicon, the Social Share Image, the Splash of the app and the Launcher Icon.

## Expected behavior (required)

Each app's unique logo should appear throughout the installation process instead of the Flutterflow logos.

## Current behavior (required)

Both in the installation process and on the home screen of the device, the Flutterflow icon always appears.

## To Reproduce (required)

See pictures

![1](https://user-images.githubusercontent.com/40741210/211011835-9b29db09-b288-4eaa-8ef5-ba846442531a.png)
![2](https://user-images.githubusercontent.com/40741210/211011838-9489f845-b9dc-43bc-a29d-8ea64c28a5e6.png)
![3](https://user-images.githubusercontent.com/40741210/211011842-73857cdd-1c41-4783-9e59-ddceae7f0bd0.png)

**Comment by zeymermontes** [comment] 2023-01-23 07:53
This is making my projects look so un profesional.

You can replace the icons in the icon folder or you can just run the command that FF sugests for Social Share Image when deploying (publishing) the app.

**Comment by hariprasadms** [comment] 2023-01-24 10:45
Hi, I can reproduce this issue. However this is inconsistent.

**Comment by pcsk77** [comment] 2023-02-18 02:52
This is a major concern for me because it makes my app look unprofessional. When will this be fixed?

Thanks

**Comment by wenkaifan0720** [comment] 2023-03-26 16:35
Hi @pcsk77, @jerodesign. This will be worked on by our team. As this is more like a feature request, I'll close this issue for now.

**Closed by wenkaifan0720** 2023-03-26 16:35 UTC
Labels: closed: feature request, type: feature request
