### ISSUE TITLE
problems in google map widget when zooming in and out

### ISSUE THREAD

**Issue by Tito299** [FlutterFlow/flutterflow-issues#2128] opened 2024-01-10 17:15 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I zoom in the google map widget, all the streets, routes etc, become black, but when I remove the zoom they return to their original color, that didn't happen before.

### Expected Behavior

zoom in and out and keep the routes in the same color

### Steps to Reproduce

\\-create new page
\\-add google maps widget
\\-run it

* zoom to the point that the streets, routes turn black

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESiMjfsIlgoscC14fQdO5QhQMnQzM5U+cFjtt+Zw8hfZz1EYoteM/8YlBLYtemT1ZieGel+D8Gwa3sjeziVvQ5HwqdQJR9+JRXQTvhUmCXM5CXPpCwQHZAHdxYIUC75qWGkBNCKtVqLFYY32CPevCNG3qCf9qOYwx5e6fDbOY=

### Context

I am making an app that traces a route between two points and shows the route between those two points, but when zooming all the routes become black, this did not happen before.

### Visual documentation

[https://github.com/FlutterFlow/flutterflow-issues/assets/31897727/b2fce235-76a2-4887-be0a-194f3843b36b](https://github.com/FlutterFlow/flutterflow-issues/assets/31897727/b2fce235-76a2-4887-be0a-194f3843b36b)

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: 4.0
- Platform:windows 11 pro
- Browser name and version:microsoft edge 120.0.2210.121
- Operating system and version affected: windows 11 pro 23h2 (I run the project on a virtual device with android 13, with the apk)
```

**Comment by hariprasadms** [comment] 2024-02-12 12:07
Hi, Thanks for raising the issue. As it doesn't appear to be widespread and lacks a blank project with reproducible steps, it may have been overlooked. Considering its age, it's possible it has been addressed in recent FlutterFlow updates. Therefore, the issue is being closed. However, if you believe the problem persists, please reopen the issue by providing a blank project with the reproduced issue and share the project bug report code. This will facilitate a thorough investigation and prompt resolution. Thank you.

**Closed** 2024-02-12 12:08 UTC
Labels: status: can't reproduce, needs a blank project with issue setup
