### ISSUE TITLE
FlutterFlow quit unexpectedly on macOS

### ISSUE THREAD

**Issue by kiptoomm** [FlutterFlow/flutterflow-issues#2976] opened 2024-05-23 20:48 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The desktop app on macOS is crashing after installing the latest version.

I had a previous version of FlutterFlow Desktop but then ran into this somewhat related and recurrent issue: https://community.flutterflow.io/ask-the-community/post/always-says-flutterflow-version-out-of-date-inqR6pmIhXWFhVY

### Expected Behavior

The desktop app launches as before

### Steps to Reproduce

s before

1. Remove the existing app by deleting it from `/Applications` folder and clear trash, associated folders and files in `/Library`, and `~/Library` paths
2. Download the app
3. Install the new app by double-clicking on the .dmg file
4. Move the installed app to `/Applications` folder (drag)
5. Launch the app from Spotlight or double clicking from within `/Applications`

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

n/a

### Context

I want to use Local Run and I'm no longer able to do so :(

### Visual documentation

![Screen Shot 2024-05-23 at 11 32 45 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/1447912/46958485-ade8-4777-bcc8-bd4988bfcad4)

### Additional Info

"Report to Apple" crash logs: https://docs.google.com/document/d/1v9ts7vL2f3876Z4oWdvO5S9ub49-RceofhRLPDqCB58/edit?usp=sharing

### Environment

```markdown
- FlutterFlow version: latest
- Platform: MacOS Desktop
- Browser name and version: Chrome 124.0.6367.210 (Official Build) (x86_64)
- Operating system and version affected: macOS Big Sur (v11.7.10)
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by kiptoomm** [comment] 2024-05-23 20:51
Sometimes, the popup message that appears says "The application “FlutterFlow” can’t be opened. 11". See below

![Screen Shot 2024-05-23 at 11 50 30 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/1447912/3d4d5ff3-be0e-4ce9-970b-73f95f040279)

**Comment by kiptoomm** [comment] 2024-05-24 05:53
Some paths where I manually removed the old FlutterFlow-associated files in a bid to try a "clean" uninstall following [suggestions by GPT](https://chatgpt.com/share/7e76eafe-5d47-4cc2-8708-da2971cdb4e7): 

```
~/Library/Application Support/
~/Library/Preferences/
~/Library/Caches/
~/Library/Logs/
~/Library/Saved Application State
/Library/Application Support/
/Library/Preferences/
/Library/Caches/
```

The FlutterFlow files weren't always in these folders

**Comment by msusviela** [comment] 2024-05-24 16:22
Hey @kiptoomm, Thanks for your report, So sorry you are experiencing this issue. I was not able to reproduce this. This is an specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. Thanks so much!

**Closed** 2024-05-24 16:22 UTC
Labels: status: needs triage
