### ISSUE TITLE
pubspec dependencies are duplicated for every custom widget&action I have in my project

### ISSUE THREAD

**Issue by AlexP-cyber** [FlutterFlow/flutterflow-issues#3747] opened 2024-09-04 21:30 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

For every custom action&widget I have in my "tinyWins" project I see same list of pubspec dependencies and it doesn't make sence. It looks like now list of all pubspec dependencies I use in my project is assigned to each custom action&widget

### Expected Behavior

each action&widget has its own pubspec dependencies

### Steps to Reproduce

1. Open 'Custom Code' section
2. Pay attention to pubspec dependencies you have for each of your actions&widgets

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4khfLq4otIsbVE7rqAbcBFniYRNkw2TL07ttYbZxUjIuPtBJh/YM/RYlNtXbylY0NhHE6bmjoE0sr2koSTUfo4PRCsQIRdwpdcUQvye3q8RrqVOpDtfnN9J+ZTI0Ch5ruC3BN5ANdhcUYC1GCYH+eiVjHAN5+/Zwh9f6PHaOI=

### Visual documentation

even while creating new custom action from scratch I'm facing predefined pubspec dependencies

![изображение_viber_2024-09-05_00-16-10-016](https://github.com/user-attachments/assets/18e49a99-944d-449e-9297-652c4fb520ac)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.86+ released September 4, 2024
Flutter version is 3.22.2
- Platform: win desktop, web as well
- Browser name and version: google chrome, Version 128.0.6613.114 (Official Build) (64-bit)
- Operating system and version affected:  Windows 10  22H2
```

**Comment by taggxyz** [comment] 2024-09-05 13:21
I'm having the same issue - what a nightmare

**Comment by taggxyz** [comment] 2024-09-05 13:27
Also, when you remove a dependency from one custom action or widget, it removes it from everything.

**Comment by Wojtek-G** [comment] 2024-09-05 14:27
Same here (web, macOS), it seems like the dependencies from all custom actions are now grouped together.

I've noticed that most of the edits in the custom code editor now generate issues, and the only way to resolve them is to revert the whole project to the last save point. Basically, we can't use the custom code editor without risking serious issues.

**Comment by Wojtek-G** [comment] 2024-09-05 15:12
> Same here (web, macOS), it seems like the dependencies from all custom actions are now grouped together.
> 
> I've noticed that most of the edits in the custom code editor now generate issues, and the only way to resolve them is to revert the whole project to the last save point. Basically, we can't use the custom code editor without risking serious issues.

FF on macOS v4.1.87 still has this issue

**Comment by majbar-emir** [comment] 2024-09-05 15:42
Same here ! i raised a ticket but got no real help. now I see that I am not alone.

**Comment by taggxyz** [comment] 2024-09-05 15:44
@Wojtek-G Interesting you mentioned reverting to a previous version. I tried that but all my custom actions and widgets still contain all the dependencies even though they didn’t in the older version I revert to.

**Comment by Alezanello** [comment] 2024-09-05 19:15
Hello everyone,

Thank you for bringing this to our attention! Our engineering team is aware of the issue. To clarify, this is purely a visual bug and does not affect any of your custom actions or functionality. There's no need to roll back or restore anything — the bug only displays all dependencies added to your custom widgets and actions.

We're working on a hotfix that will be released soon. In the meantime, you can continue using the feature and adding dependencies as needed without any problems.

Thanks for your patience!

**Comment by majbar-emir** [comment] 2024-09-05 20:09
> Hello everyone,
> 
> Thank you for bringing this to our attention! Our engineering team is aware of the issue. To clarify, this is purely a visual bug and does not affect any of your custom actions or functionality. There's no need to roll back or restore anything — the bug only displays all dependencies added to your custom widgets and actions.
> 
> We're working on a hotfix that will be released soon. In the meantime, you can continue using the feature and adding dependencies as needed without any problems.
> 
> Thanks for your patience!

Not in my case, the custom widgets won't compile .

**Comment by majbar-emir** [comment] 2024-09-06 08:15
now the widgets compile but the visual bug is still there (I don't know if this was intended by the update so we see all dependencies added and not add them again)

**Comment by tudotubestudio** [comment] 2024-09-08 18:09
> Not in my case, the custom widgets won't compile .
Same here, custom widgets and actions won't compile, the same is valid to new projects.

**Comment by ImadBouirmane** [comment] 2024-09-09 17:08
Hi 
Recently I shared duplicated issue like this here and the problem is the custom code UI states show the same packages even you switched from one to others !
The solution as I did and its work fine now, is to set all packages you use in whole Custom Actions and Widgets and run them and keep there, it will automatically sync and compile.
Because now all custom code use same packages textfield so the compile is all at once not for every custom code !
Hope we can control every custom code as new ability and avoid those issues !

**Comment by Sergii-Shpak-072422** [comment] 2024-09-13 16:23
Faced this issue today. It completely blocked my work! It is reproducable on macOS and on the web editor.

**Comment by Sergii-Shpak-072422** [comment] 2024-09-24 10:40
@Alezanello  Is there any efficient workaround for this issue? My work is block for two weeks and it is kind of insane for keeping a critical bug open for that long.

**Comment by Alezanello** [comment] 2024-09-24 12:24
Hi everyone,

We wanted to let you know that a fix will be deployed shortly to address the issues you’ve been experiencing. Thank you for your patience and understanding as we work to resolve everything!

**Comment by Sergii-Shpak-072422** [comment] 2024-09-25 10:26
Hi @Alezanello, 
today I see the v5 is rolled out. BUT the issue is still there 🙁

**Comment by Wojtek-G** [comment] 2024-09-25 11:52
Same

> Hi @Alezanello, today I see the v5 is rolled out. BUT the issue is still there 🙁

Same here, still have this issue.

**Comment by Alezanello** [comment] 2024-10-04 17:51
Hello everyone!

The engineering team has confirmed that this behavior is now expected, where all dependencies are shown on the right. If you’re unable to compile the app for any reason, let’s start fresh. Please leave the bug reports for your project in the comments below, along with any custom code that’s causing the error.

**Comment by Phillewis63** [comment] 2024-10-07 22:09
This is a major issue. The pubspec dependencies for mixpannel custom actions are shared across all of my custom actions & custom widgets including any new ones that I try to create. If I edit the pubspec dependencies on any of these, it changes them on all of them.

**Comment by Alezanello** [comment] 2024-10-08 12:10
Hello everyone,

Just to clarify, this is the expected behavior:

Not every dependency is automatically added to all custom actions and widgets. Instead, you can now view *all* the dependencies you've added in one central place, making it easier to manage and modify them, rather than searching through individual custom actions or widgets to find and update specific dependencies.

Please note, this change does *not* impact the behavior of your Custom Actions or Custom Widgets. Everything you've added can also be viewed in the Project Dependencies section for easy reference.

**Closed as not planned by Alezanello** 2024-10-08 12:10 UTC
Labels: status: confirmed
