### ISSUE TITLE
Activity states active when user is not in the project

### ISSUE THREAD

**Issue by hughCar389** [FlutterFlow/flutterflow-issues#3182] opened 2024-06-19 18:37 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The project states another user is on when the participant has exited Flutterflow. I keep getting pop up signing me out of the project.

### Expected Behavior

The project to run smoothly and the other participants to not appear.

### Steps to Reproduce

1. Open project

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfkM/l7ZBgoctH176JKcJVvDgWH18cTIMziNZ+exUbfaL1Bu0AY/TsRxBoZNOkaVNcAlmLgkYx0sLzi+LLEvkqYBOsftVCyKhhEg7ee2iuaKa0PpCgOGtfEeFTfRG80Z+02h5AC/poLE4D7XGDeu+uRT7DFOu/Zwh9f6PHaOI=

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/124802801/13e1cc3f-9991-496d-a7bb-faa5d6d4846b)

### Environment

```markdown
- FlutterFlow version: 4.1.61+
- Platform: Windows
- Browser name and version: Chrome 
- Operating system and version affected: Windows
```

**Comment by msusviela** [comment] 2024-06-20 19:14
Hi @hughCar389. <br>I was not able to reproduce this on a blank project. That's why I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. Thanks so much!

**Closed as not planned by msusviela** 2024-06-20 19:14 UTC
Labels: status: needs triage, closed: support request
