### ISSUE TITLE
Cloud Function Error Parsing List of Custom DataType

### ISSUE THREAD

**Issue by abegehr** [FlutterFlow/flutterflow-issues#2248] opened 2024-01-26 14:06 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm returning a list of custom data type from a cloud function. There return type is specified in the cloud function and it tries to parse it in the code but I'm getting a type error:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type '_Map<Object?, Object?>' is not a subtype of type 'Map<String, dynamic>'
#0      NewContactSheet2Model.search.<anonymous closure> (package:bestes/contacts/new_contact_sheet2/new_contact_sheet2_model.dart:136:59)
#1      MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
```

This is the affected section of code:

```
final result = await FirebaseFunctions.instanceFor(region: 'europe-west3')
    .httpsCallable('searchForDoctor')
    .call({
  "query": textFieldQueryController.text,
  "place": textFieldPlaceController.text,
});
debugPrint("DEBUG result.data: ${result.data}");
cloudFunctionrc3 = SearchForDoctorCloudFunctionCallResponse(
  data: (result.data as List)
      .map((d) => ContactSearchResultStruct.fromMap(d))
      .toList(),
  succeeded: true,
  resultAsString: result.data.toString(),
  jsonBody: result.data,
);
```

Except for the `debugPrint()`, this is all generated by FF.

I've added the debug print to make sure the data is correct and it seems to be fine. A sample:

```
flutter: DEBUG result.data: [{name: test, types: [test1, test2], contactId: 12345}, … ]
```

### Expected Behavior

I'd expect it to correctly parse the custom datatype `ContactSearchResult`:

![Screenshot 2024-01-26 at 14 55 26](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/ed5c794a-c081-4c74-9922-fa5d3c6e4298/4a824958-2720-4ce1-8770-b9bff16d5e05?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lZDVjNzk0YS1jMDgxLTRjNzQtOTkyMi1mYTVkM2M2ZTQyOTgvNGE4MjQ5NTgtMjcyMC00Y2UxLTg3NzAtYjliZmYxNmQ1ZTA1IiwiaWF0IjoxNzA3MTQxMzM4LCJleHAiOjMzMjc3NzAxMzM4fQ.eofiHJgTWPjLex9Q14aQu5uFoFNyW2PXX1kC7Y3QNU8)

![Screenshot 2024-01-26 at 14 59 46](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/aab9f2ea-1b58-4a30-9dea-cf5dde5059e8/a0d1b2a9-6cef-43d2-9dd7-80e8798442b9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hYWI5ZjJlYS0xYjU4LTRhMzAtOWRlYS1jZjVkZGU1MDU5ZTgvYTBkMWIyYTktNmNlZi00M2QyLTlkZDctODBlODc5ODQ0MmI5IiwiaWF0IjoxNzA3MTQxMzM4LCJleHAiOjMzMjc3NzAxMzM4fQ.nZF2Rc-VcxwfMIDZ1HXhnKOk7zj7fi4FkVtnbDdxEbQ)

### Steps to Reproduce

1. Create the datatype from screenshot above.
2. Write function that returns the datatype with some sample data (see screenshots).
3. Call the function from FF client app.
4. Parsing error.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ContactSearchResultStruct

### Context

I can't use the cloud function without it parsing the response correctly.

### Visual documentation

Images added above.

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: Flutter 3.16.9
- Platform: Web
- Browser name and version: Chrome 121.0.6167.85
- Operating system and version affected: macOS 14.2.1
```

**Comment by abegehr** [comment] 2024-01-29 13:09
I did some experimenting and ultimately this is working now:

```dart
      cloudFunctionrc3 = SearchForDoctorCloudFunctionCallResponse(
        data: (result.data as List<dynamic>)
            .map((d) => ContactSearchResultStruct.fromMap(
                (d as Map<Object?, Object?>).map((key, value) =>
                    MapEntry(key.toString(), value as dynamic))))
            .toList(),
        succeeded: true,
        resultAsString: result.data.toString(),
        jsonBody: result.data,
      );
```

Basically it does some casting in steps: dynamic -> List<dynamic> -> List<Map<Object?, Object?> -> List<Map<String, dynamic>>

**Comment by hariprasadms** [comment] 2024-01-30 14:08
Hi @abegehr - Thanks for confirming. If the issue resolved for you. Please close the issue. Thanks

**Comment by takashiff** [comment] 2024-02-01 17:47
Hi @abegehr, could you provide the bug report code for the associated widget? This can be done by right-clicking the widget in the Widget Tree and clicking "Get Bug Report Code". Thanks

**Comment by ready4sea** [comment] 2024-02-22 14:58
I'm having the exact same issue as @abegehr. I believe the issue has not been fixed, contrary to what @hariprasadms said. Any news on this @takashiff ?

**Comment by abegehr** [comment] 2024-02-22 15:03
@takashiff, I've since changed the function to return a list of strings instead of a list of custom data types, therefore I can't provide a debug report code anymore (sorry, I notice it didn't copy&paste correctly in the OP). 
@ready4sea, if you're having the same issue, maybe you can share a debug report code (as described in @takashiff's post above)?

**Comment by takashiff** [comment] 2024-03-12 20:22
Hi @abegehr, I'm currently unable to reproduce the issue. The way FF parses lists of custom data types from cloud functions is that it expects a list of JSONs, in which each field in the data type corresponds to a key-value pair in the JSON.
For example, if we have the following Data Type:
```MyDataType
StringListField: List<String>
StringField: String```
And we have a cloud function that returns `List<MyDataType>`, the cloud function should return in the following format:
```return
[{"StringListField": ["Item 1", "Item 2"],
"StringField": "String 1"},
{"StringListField": ["Item 3", "Item 4"],
"StringField": "String2"}];```
I hope this clears things up. Please let me know if this format was followed when encountering the bug above. Thanks

**Comment by ready4sea** [comment] 2024-03-12 20:56
Thank you @takashiff  for this clarification. It was not clear anywhere that cloud functions were expected to use the JSON format. I suppose this is the case both as inputs and outputs to the cloud function ?

**Comment by takashiff** [comment] 2024-03-12 21:27
@ready4sea Yes, I will put in a request internally to update our documentation to reflect this. I apologize for the inconvenience caused.

**Closed** 2024-03-13 16:54 UTC
Labels: waiting for user response, needs technical triage
