### ISSUE TITLE
Local Run Web: Firebase App Check Run/Test Mode Debug Token not updated in project dart code

### ISSUE THREAD

**Issue by UomoCaffeLatte** [FlutterFlow/flutterflow-issues#3423] opened 2024-07-17 17:11 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using the desktop version of flutter flow, and creating a local test run using either Chrome or Edge based web devices. The firebase App Check Run/test debug token is not updated in the dart project (located in lib/flutter_flow/firebase_app_check_util.dart). Instead the reCAPTCHA v3 Site Key (For real deployment) is used. Runing a test app normally, through flutter flow, works perfectly fine. 

I have tried manually running the project code outside of the flutter flow desktop interface, and I cannot get it to work even when manually adding the debug token.

### Expected Behavior

Test app uses the debug App Check token to communicated with firebase authentication.

### Steps to Reproduce

1. Link a firebase account to your app
2. Add a reCAPTCHA v3 site key and Run/Test Mode debug token
3. Run a local run of the web application on Chrome or Edge
4. Attempt to perform any type of firebase authentication.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Cksrqw5N1m8tK7q6JY/pV+TssHDN7RYEzlup+c0kdDZPMC+wIZ/f7XFRuTde0YHw+MWCanj0zp9XemvH1U/BfFxGbbpx7wbV2VwHxQj2tVrKyOrqOZ25/AppgJ2q71Ke3nB4kItRsS3NlwEOpN9yRThDDJbLJNm4jOM+IKZOK2SrDX1iXc2URm05KZDPz

### Visual documentation

![image](https://github.com/user-attachments/assets/70867e4e-94dd-4e12-a9c0-8eb1c14b531a)

### Environment

```markdown
- FlutterFlow version: 4.1.72+
- Platform:Desktop
- Browser name and version:Chrome 126.0.6478.182 (64bit), Edge 126.0.2592.102(64-bit)
- Operating system and version affected: Web based application (Chrome and Edge)
```

### Additional Information

None

**Comment by paulperez-dev** [comment] 2024-07-22 02:36
Hi @UomoCaffeLatte! The token in the file you mentioned should not change for web. If you want to run the project out of ***FF*** you should deal with some **Flutter** configuration. Please refer to this [documentation](https://firebase.google.com/docs/app-check/flutter/debug-provider#web) on how to enable debug mode. Notice that you should add the token shown in the console in App Check and not the other way.

 I'm going to close this issue since this is not a bug.

**Comment by UomoCaffeLatte** [comment] 2024-07-22 15:57
Hi @paulperez-dev , thanks for your reply. The error occurs after I have added the Debug token in the App Check configuration in FF (desktop) and running a web app locally.

**Comment by paulperez-dev** [comment] 2024-07-23 21:50
Hi @UomoCaffeLatte! Can you please share the error you are getting? The image shared does not show any error.

**Comment by paulperez-dev** [comment] 2024-07-27 12:33
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Closed as not planned by paulperez-dev** 2024-07-27 12:33 UTC
Labels: closed: not a bug
