### ISSUE TITLE
Switch component's binding to a boolean value (from API) is broken

### ISSUE THREAD

**Issue by anttikuuskoski** [FlutterFlow/flutterflow-issues#117] opened 2022-11-10 22:23 UTC
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Setup

API call response data (array of objects) is bound to a list view. The list child template contains a switch component, which has it's initial value bound to a boolean field in the data object.

## Expected behavior (required)

1. When data is loaded and the gui rendered, each switch is expected to reflect the boolean value of the corresponding object in the REST data, i.e. be off when data field `enabled` is false and on when it's true.
2. When a switch is toggled, that switch is expected to toggle. The other switches are not expected to toggle.

## Current behavior (required)

1. When data is loaded and the gui rendered, all toggles reflect the same value which is not the data object's value.
2. When a switch is toggled, all switches toggle simultaneously

As shown in the following screen shots / caps, the enabled field is bound to both a text field and the switch. While the text field contents do change, the switches remain unbound.

As a side note, I'm also launching actions from the toggle switch component. Only one action is launched although multiple switches change state. It seems to me that all switches are simultaneously bound to a common variable somewhere instead of the list data.

## To Reproduce (required)

1. Create a list view bound to a GET API returning an array of objects containing boolean fields
2. In the list view's child template, add a switch and bind it's initial value to data field, i.e. `$.enabled`.
3. Take a preview of the app: all switches have the same value and bounce simultaneously
4. Create a test session of the app: all switches have the same value and bounce simultaneously

Example data: 
```
[
  {
    "enabled" : false,
    "name" : "ut aliquip ut",
    "id" : "nostrud occaecat aliqua labore ut"
  },
  {
    "enabled" : true,
    "name" : "in nulla",
    "id" : "ea dolore si"
  }
]
```

## Context (required)

I'm trying to display and control (enable / disable) a number of items. I am unable to do this.

## Screenshots / recordings

Switch properties

![switch_props](https://user-images.githubusercontent.com/20336930/201215432-187780c2-8119-40e6-b3fd-3bb244f7fd53.png)

List view design

![listview](https://user-images.githubusercontent.com/20336930/201215489-7c3bedcd-231c-4326-a3fd-61a4b3d22438.png)

Screencap from test session showing the effect of toggling a switch. The background color change is due to an alert.

![action](https://user-images.githubusercontent.com/20336930/201215543-bd813483-b2c4-49d2-ab7a-bd0e0fee39bd.gif)

## Your environment

* Version: Flutterflow 3.3.4
* Platform: Web
* Browser: Chrome
* OS: Windows 10

**Comment by anttikuuskoski** [comment] 2022-11-11 08:10
Party similar report in https://community.flutterflow.io/c/discuss-and-get-help/switch-widget-a5a77f.

**Comment by anttikuuskoski** [comment] 2022-11-11 09:47
Looking at the generated code (`home_page_widget.dart.js`) in test mode, it really seems that there is a single shared variable containing the state for all switches.

``` dart
class _HomePageWidgetState extends State<HomePageWidget> {
  ...
  bool? switchValue;
```
and
``` dart
                                      Switch(
                                        value: switchValue ??= getJsonField(
                                          item,
                                          r'''$.enabled''',
                                        ),
                                        onChanged: (newValue) async {
                                          setState(
                                              () => switchValue = newValue!);
```

So it might also be that it works as intended (making it a quite useless widget).

**Comment by hariprasadms** [comment] 2022-11-14 15:43
Hi, I can reproduce this issue while using firestore data as well. Hence marked this as bug.

**Comment by agreaves** [comment] 2022-12-28 01:35
Hi @anttikuuskoski, thank you for the bug report and apologies for the delay in response. This is because FlutterFlow does not currently handle stateful widgets inside dynamic generated children. We now add a project error when this is the case, and the recommended solution is to use a component for such situations.

**Closed by agreaves** 2022-12-28 01:35 UTC
Labels: type: bug, status: confirmed
