### ISSUE TITLE
Clicking on widget does not navigate to Widget Tree

### ISSUE THREAD

**Issue by dannyz61** [FlutterFlow/flutterflow-issues#3043] opened 2024-06-02 09:38 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

There are many fields in the widget tree. It is quite difficult to locate the current widget in the widget tree. Whenever I click on the widget, it scrolls to a different view.

### Expected Behavior

Whenever I click on the widget, it should scroll to the selected widget.

### Steps to Reproduce

Create multiple widgets in a scrollable widget tree. For example, if you create 10 fields, click on one to check if it navigates within the widget tree.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ClcmAvIVIvscB7c7qacEw+CQsKUg4RY0vmMB+TRUYDZP8C5kAYczBM0poTdO5fHxIeVqYmmMJ+eDThIbDUMI3HwuVb4B63JVqFjvxWj26WoyhPLiSeXNCDeNjCW6Z1MOVmxJ8A+FfV1oY2kymOti8bC/bQoTwIVdNQvyINoLMn3y7FXnoUyEy5x0XEx7eTI5ODEz25eKMrop5yfj/0w==

### Context

I'm attempting to locate the currently selected widget in the widget tree.

### Visual documentation

https://drive.google.com/file/d/1s3xosB2aoJ0AIgfHRaoUx_IOaC6JEMJz/view?usp=sharing

### Environment

```markdown
- FlutterFlow version: v4.1.54
- Platform: Browser
- Browser name and version: Chrome 125.0.6422.113
- Operating system and version affected: All
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by msusviela** [comment] 2024-06-03 12:36
Hey @dannyz61, Thanks for your report, So sorry you are experiencing this issue. I was not able to reproduce this on a blank project, but it is replicable on yours. That's why I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. Thanks so much!

**Closed** 2024-06-06 15:58 UTC
Labels: closed: support request
