### ISSUE TITLE
Build fails in test mode, and local run only publishes a rolled-back version of the app.

### ISSUE THREAD

**Issue by wwchiang** [FlutterFlow/flutterflow-issues#3219] opened 2024-06-25 15:51 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

1. The project build fails in run/test mode, even on previous versions that worked perfectly fine.
2. Attempting to run the project locally results in am older version being published (around 2 weeks old) and with none of my newer changes.

### Expected Behavior

I should be able to build and test the latest version of my app without any issues.

### Steps to Reproduce

1. Attempt to run project in test or run mode.
2. Build fails no matter which version of the project I attempt to run.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oi87huI11obhJ1a6JbvpVuyQXC0M3R5Ir18pBZywgfZzzBLN/fPfQPhZBTse+dwhEe2C2p14Ep8GOit7DJcdeNU+tfqU/z5F2SzrNf3yRRKWTF7uednNPEplUFUin5qe7uBN/PsdsdU4e706uJ++saA7bK5yxPFQ8Sq/LZO4=

### Visual documentation

![Screenshot 2024-06-25 082632](https://github.com/FlutterFlow/flutterflow-issues/assets/8504719/feb35a6c-9cff-409d-9ee3-ca8dd67a7b05)

### Environment

```markdown
- FlutterFlow version: v4.1.61
- Platform: Web
- Browser name and version: Google Chrome Version 126.0.6478.116 (Official Build) (64-bit)
- Operating system and version affected: Windows 10 Home
```

### Additional Information

Other projects that I have appear to publish just fine -- the bug is localized to this project, but I can't isolate the root cause.

**Comment by msusviela** [comment] 2024-06-25 16:42
Hi all. It seems to be related to a package upgrade on [pub.dev](http://pub.dev/). Our engineering team is already aware and working on a fix.

I'm closing this issue because It's a duplicate of: [https://github.com/FlutterFlow/flutterflow-issues/issues/3217](https://github.com/FlutterFlow/flutterflow-issues/issues/3217) I'll be following this from this issue.

Thanks for your reports!

**Closed as not planned** 2024-06-25 16:45 UTC
Labels: closed: duplicate
