### ISSUE TITLE
Line chart does not understand ff/fb timestamp field.  Requires only numbers.

### ISSUE THREAD

**Issue by KirilOkun** [FlutterFlow/flutterflow-issues#56] opened 2022-10-25 03:51 UTC
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

Line chart widget only accepts numbers as the source for data series and errors out when timestamp type is used.

## Current behavior (required)

FF crashes with an error

## To Reproduce (required)

1.  Add line chart widget
2.  Create a collection query for documents with a timestamp and number fields
3.  Use timestamp for the x axis
4.  Use number for the y axis
5.  Run application

## Context (required)

Unable to use time data on the x axis.  Workaround is to create a separate number field and convert timestamp value into the integer just to be able to plot it in a chart.   

## Your environment

* **Bug Report Code:**
* Version of FlutterFlow used:   Latest
* Platform (e.g. Web, MacOS Desktop):   Web
* Browser name and version:   Version 106.0.5249.119 (Official Build) (64-bit)
* Operating system and version (desktop or mobile):   Kubuntu  22.04

**Comment by Pepino-GR** [comment] 2022-10-25 11:07
The issue can be reproduced. The conversion of DateTime in flutter-flow-charts.dart  failed.

**Comment by abyssmaljib** [comment] 2022-12-06 02:54
Hi, I have the same issue here and hope it is fixed soon. In the meantime, is anybody has another workaround? I tried converting DateTime to epoch and collecting it in another field, but when displayed in the graph, it is very long and ugly. :(
![image](https://user-images.githubusercontent.com/119910195/205797682-da02cd3a-4960-4f46-843e-2e5f00340a53.png)

**Comment by agreaves** [comment] 2022-12-28 17:37
Hi @KirilOkun and @abyssmaljib, I'm closing this as a duplicate of #35 which we will hopefully fix soon.

**Closed by agreaves** 2022-12-28 17:37 UTC
Labels: status: confirmed
