### ISSUE TITLE
App State variable not mantaining values after being updated with an action

### ISSUE THREAD

**Issue by FrancoSernaglia** [FlutterFlow/flutterflow-issues#1136] opened 2023-07-18 19:08 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a data type app state variable which I use to store some variables so the next page can retreive that information. I have an action that using conditionals updates the app state data type. I verified that the variable is being updated during the course of the action but as soon as the action finalizes, the datatype returns to null values. Is there a bug or this behavior is intended? I just want a way to store variables between pages. 

### Expected Behavior

I want to update an app state variable with an action and the data be used in other pages.

### Steps to Reproduce

1. Create a blank page
2. Create an action button and an update action in it
3. Create an app state DataType variable with some fields in it (with null values or whatever)
4. Update fields of the datatype with an action
5. Print in some way the values of the variable and observe that: before the action the values were null, during the action were the desired values, after de action the values return to null.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4okvLlx85grs9G1s/AacFvryQQKVgkR78ricpBZz0aIuPpDJl/PM/6PltvYMelS2x+JVq2p14H0cL7j971UsFfORSsR48+wbVbWg7jfD6lWrGTF7qoOXwkEfFnG3a+5KSRgyJAFNRaLGQu6meqFtyydz/DJ4zRDEQwSq/LZO4=

### Context

I was trying to ask some questions to the user and store the answers in an app state datatype variable. I wanted to use that datatype in the next page.

### Visual documentation

before: 
<img width="195" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/128932349/23a6ca87-a043-4b6d-b56a-bd134b46b8d2">
during the action (after updating the fields):
<img width="185" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/128932349/4965f1e0-1345-45a1-94a1-d9b5d6d2f6bc">
afterwards:
<img width="185" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/128932349/2133f38f-82d4-4f95-8c55-cb2e15131be8">

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by sbis04** [comment] 2023-08-27 05:25
It seems like the issue is quite old, but wasn't looked into earlier. Does this issue still persist @FrancoSernaglia?

**Comment by sbis04** [comment] 2023-09-03 14:42
Closing this issue, assuming it's already solved!

**Closed by sbis04** 2023-09-03 14:42 UTC
Labels: closed: other
