### ISSUE TITLE
The test session shows "Expired: -6809 minutes" and is unavailable for use.

### ISSUE THREAD

**Issue by whynotIncJ** [FlutterFlow/flutterflow-issues#4799] opened 2024-11-01 00:33 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The test session shows "Expired: -6809 minutes" and is unavailable for use.

### Expected Behavior

The test session should start normally without showing an expiration time.

### Steps to Reproduce

※Only happen 1 project : timer-8g622i

1. Open the project 
2. Click on Use Test Mode to initiate a test session.
3. Observe that the expiration time is displayed as "-6809 minutes".
4. The page does not load, and no error screen is displayed.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEez8rluJNPn70E7ofhYO5vpwMwJ0QlUIInj+0bWRMhfZfmPLMuYsmkM05LYtSqY0FIPlSYpGoBwPzVvvzlGO45OTOCfa5N1b5XQTrxdzqmaZSpPquSWkZQP8FMClyi5KW7sSVvB7FpLlY422GYF/CdG3qCf9qOYwx5e6fDbOY=

### Visual documentation

[
![CleanShot 2567-11-01 at 07 08 26@2x](https://github.com/user-attachments/assets/c9d5ab1c-8ba8-4f76-aa42-edcfba31c0eb)
](url)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.8+ released October 31, 2024 / Flutter version is 3.24.2
- Platform:Web
- Browser name and version: 130.0.6723.92
- Operating system and version affected: Mac 15.0.1 (24A348)
```

### Additional Information

- Frequency of Occurrence: Every time
- The app displays correctly in Run Mode
- Currently conducting a closed alpha test on Android
- The test session works correctly in other projects (even in newly created blank projects)

**Comment by Alezanello** [comment] 2024-11-01 12:37
Hello!

I wasn’t able to replicate the issue in a new blank project as you described. In cases like this, we recommend reaching out to our support team via the in-app chat or by emailing [support@flutterflow.io](mailto:support@flutterflow.io) for further assistance.

Additionally, I compiled your app locally and didn’t find anything that indicates the issue is specific to your project. The support team will be able to help investigate this further with you.

Thank you!

**Comment by whynotIncJ** [comment] 2024-11-03 04:21
Hello Alezanello,

Thank you for your response and for looking into this. 
I also tried creating a new project and tested other projects, and it seems this issue is specific to this particular project. 

I will reach out to the support team as suggested.

Thank you again for always providing such excellent service!

**Comment by Alezanello** [comment] 2024-11-08 14:03
Thank you!<br>I’ll go ahead and close this issue, but if you encounter anything else, please don’t hesitate to open a new one!

**Closed as not planned by Alezanello** 2024-11-08 14:03 UTC
Labels: status: can't reproduce
