### ISSUE TITLE
Flags in language drop-down not displayed in web deployment

### ISSUE THREAD

**Issue by ampapplarsen** [FlutterFlow/flutterflow-issues#53] opened 2022-10-24 07:27 UTC
## Expected behavior (required)
When a language selection dropdown is presented, a flag should be displayed for each language option item.

## Current behavior (required)
Instead of a flag, a burger menu like icon (three black horizontal bars) is shown instead.

## To Reproduce (required)
1. Enable more than one language option
2. Add the language selection widget
3. Publish to web
4. Observe the above widget

## Context (required)
I want to display language selection dropdowns beautifully as I have a lot of language translations.

## Screenshots / recordings
[Screenshot](https://photos.app.goo.gl/sYSK2qVmsXoPiN5e6)
[Web deployment with the bug live. Please go to the Settings page](https://ampower.flutterflow.app/home)

**Comment by Pepino-GR** [comment] 2022-10-24 10:51
Hi ampapplarsen,

I can reproduce this issue, when I open your Webpage with the Safari Webbrowser. If I open it in Google Chrom, it works as expected.

**Comment by Pepino-GR** [comment] 2022-10-24 10:52
<img width="1362" alt="Bildschirmfoto 2022-10-24 um 12 43 48" src="https://user-images.githubusercontent.com/35230751/197510088-e47eec42-4530-4ff1-b3d4-078c76102e65.png">

**Comment by ampapplarsen** [comment] 2022-10-24 10:55
> Hi ampapplarsen,
> 
> I can reproduce this issue, when I open your Webpage with the Safari Webbrowser. If I open it in Google Chrom, it works as expected.

Still a bug, though? Safari has a substantial share of the browser market.

**Comment by bulgariamitko** [comment] 2022-10-24 12:46
Yes but this is not FF issue it should be Flutter issue. I will make this as not a bug for now and let's FF team decide.

**Comment by ampapplarsen** [comment] 2022-10-24 12:47
That's interesting. To the no-coder it's hard to discern where FF stops and F begins. 

FF has two F's so it's twice as good.

**Comment by Pepino-GR** [comment] 2022-10-24 13:01
For me it is not mainly a Flutter or FlutterFlow issue. There are two ways to fix the issue. The problem occurred because Safari handles the code different than Chrome. So one way to fix it is on Safari by Apple. The other way to fix it is on the Flutter or FlutterFlow site. 

FlutterFlow use a Flutter Package to shows the flags. And it seems, that this does not work the same way on Chrome and Safari.

**Comment by Pepino-GR** [comment] 2022-10-25 09:38
With the new Safari Version 16.1 (18614.2.9.1.12), the behavior changed.

<img width="1220" alt="Bildschirm­foto 2022-10-25 um 11 35 36" src="https://user-images.githubusercontent.com/35230751/197739706-bfd7b009-524f-4e1b-9971-de2dbd700a5b.png">

**Comment by ampapplarsen** [comment] 2022-10-25 12:23
No, this is my custom code. I just went ahead and built my own instead. I don't think these small issues will get fixed fast, so might as well steam ahead.

I'm sorry for the confusion.

Issue persists though and I am just trying to help iron out these things for those that follow.

**Comment by agreaves** [comment] 2022-11-02 19:02
Yes, unfortunately this appears to be a Flutter + Safari level issue, so we have no recourse to fix it for now. For a consistent user experience, you can switch on "Hide Flags" in the property editor to hide them for all users (although I understand this is not ideal). I'm glad you have a good solution in the meantime!

Closing for now.

**Closed by agreaves** 2022-11-02 19:02 UTC
Labels: type: bug

**Comment by davidoort** [comment] 2022-11-11 06:25
I'm unfortunately running into the same issue on chrome mobile (tested on Android and iOS). On Chrome desktop it works fine (see screenshots)
![IMG_C4D85C952C25-1](https://user-images.githubusercontent.com/21220927/201276693-0604b1d2-471e-4807-a347-586a30531f9a.jpeg)
![image](https://user-images.githubusercontent.com/21220927/201277128-d2a955f2-6fac-49e3-95c8-33e288ab6089.png)
@ampapplarsen could you maybe share the workaround you developed?

**Comment by ampapplarsen** [comment] 2022-11-11 06:29
Absolutely. I'll post it in the community tutorials. I am preparing launch of my app on iOS today, so let me square that away first - and I need to slow down a little since I had some heart problem and was ambulanced to hospital the day before, so bear with me.

**Comment by davidoort** [comment] 2022-11-11 07:23
@ampapplarsen damn good luck with the launch and take it easy, no rush! Just let me know when you've shared it and thanks in advance 🙏

**Comment by ampapplarsen** [comment] 2022-11-12 17:04
> @ampapplarsen damn good luck with the launch and take it easy, no rush! Just let me know when you've shared it and thanks in advance 🙏

Thank you!

I wrote this: https://community.flutterflow.io/c/community-tutorials/roll-your-own-persistent-language-selection - enjoy!
