### ISSUE TITLE
New datatable does not update on rebuild component

### ISSUE THREAD

**Issue by AlexandreHurbe** [FlutterFlow/flutterflow-issues#2268] opened 2024-01-30 19:13 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

With the new data table rebuilding the component or when changing the data associated to the table, it does not refresh. This has been reported in: 
https://community.flutterflow.io/ask-the-community/post/troubleshooting-flutterflow-data-table-refresh-issues-DTwE8zFD8VyZEAx?highlight=4jpeEMNjBvGVqf0
https://community.flutterflow.io/ask-the-community/post/new-data-table-issues---does-not-refresh-data-from-db-like-listview-or-EXn0SuwnBNQGgf1

### Expected Behavior

Table should update on changes similar to legacy one

### Steps to Reproduce

1. Create new datatable
2. Create component state with a list and set the data table to generate dynamically generate children from it.
3. Make changes to the component state and then set refresh current component
4. Run the build and and trigger component state change
5. Table will not update/refresh

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sj8nc25NPn7xH1aXqc8JB/GUQHDp6R+cwscpCbw4bIYj2P4lzY876PhFVOfXiSnNAMGeMp14y/vyKiuOeFMYCIRKaQJhEzapASwmWQmambpOTF7WJOUZfHtJbGnKm58OZgh1SKspZcVo411yEf9nIY3PqGOP2OkQ8Sq/LZO4=

### Context

Can't use the new datatable and new features from it. Have to use legacy table

### Visual documentation

1. Created datatable that reads from component state variable "newPlayerData"
<img width="689" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/37171772/22ad6c7e-cd03-4d6e-a547-ef80a82ae342">
2. Set drop down action to filter results and assign filtered results to "newPlayerData" and refresh component state
<img width="639" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/37171772/c42b206f-fe24-485c-b136-3135c64883e1">
3. Table will not refresh

### Environment

```markdown
- FlutterFlow version: 4.1 (released 25th January 2024)
- Platform: Web
- Browser name and version: Brave Browser v1.62.153
- Operating system and version affected: Windows 11, 22H2
```

**Comment by eduriftio** [comment] 2024-02-01 10:09
Please fix this issue, very needed!

**Comment by eduriftio** [comment] 2024-02-01 10:49
The new DataTable is great, need to fix these bugs and we can replace all custom components into a table with ease. @FlutterFlowEng please make it happen asap @hariprasadms

**Comment by hariprasadms** [comment] 2024-02-01 11:02
Hi @eduriftio - Thanks for submitting the issue. I can reproduce it. Thanks

**Comment by victoriahuang1** [comment] 2024-02-02 21:37
I am not able to reproduce this.

@eduriftio are you still experiencing this issue?
@hariprasadms if you can still reproduce this, please share the issue reproduced from blank with me.

**Comment by agreaves** [comment] 2024-02-02 22:09
Hi @AlexandreHurbe and @eduriftio, the refresh issues with the DataTable are now fixed as of yesterday's deployment!

**Closed by agreaves** 2024-02-02 22:09 UTC
Labels: type: bug, status: confirmed

**Comment by walik-walik** [comment] 2024-02-20 15:52
Hello everyone,

I am facing a similar issue as previously described, but with a slight variation: My FlutterFlow data table only updates intermittently. Sometimes, the data gets correctly updated a few times (like two or three times), but then the updates unexpectedly stop, even if the page receives a refresh. The odd part is that everything works as expected when I completely reload the page via F5.

I have tried various approaches but haven't found a consistent solution yet. The issue occurs randomly, which makes troubleshooting even more challenging. It seems like the data binding works sometimes and sometimes it doesn't, without any apparent pattern.

Has anyone else experienced this or have any ideas on how to systematically address this issue? Any help or feedback would be greatly appreciated, as this significantly impacts the user experience of my app.

Thank you in advance for your support.

**Comment by tommyhabibe** [comment] 2024-03-13 03:31
Im seeing the same issue! Please advice. My DataTable should be updating as my cart App state updates but that is not the case. It only works if pagination is on and when pagination is on the text fields in my table error out because the textField editor is being disposed of. Thanks for the help!!

**Comment by tiagosilveiransj** [comment] 2024-03-28 15:04
Hello, I'm facing the same issue, please reopen
FlutterFlow v4.1.33+
Flutter version is 3.19.1
