### ISSUE TITLE
Push Notification Action not working when app is on background

### ISSUE THREAD

**Issue by dimemacau** [FlutterFlow/flutterflow-issues#1843] opened 2023-11-14 05:06 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have implemented push notifications on my app that are working as intended when the app is fully closed. I'm opening a specific page and passing a firestore document reference as a parameter.

However, when the app is on the background, I'm receiving the push notification, but tapping on it only unpauses the app and does not open the intended page and hence does not pass the parameter either.

I want to clarify I am not doing anything different in these two scenarios, it is the same push notification, that is simply not working with the app on the background, but it is with the app fully closed.

### Expected Behavior

Tapping on the push notification while the app is on the background should open the specified page and pass a parameter.

### Steps to Reproduce

1. Create any app with a page that receives an optional parameter.
2. Create push notification action and specify page and parameter.
3. Add conditional visibility to widget that only shows when page parameter is set.
4. Run app on two devices to test.
4. Sign in with firebase authentication on both devices to send and receive PN.
5. Place receiving app on background (device 1)
5. Trigger push notification action on device 2.
6. Tap on push notification on device 1.
7. You'll see device 1's app does not show conditional widget (or if you're on a different page it doesn't open intended page).

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

n/a

### Context

I'm trying to showcase data from a document in the intended page. It is showing correctly and fully working, only if the app is closed.

### Visual documentation

n/a

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by Here-and-Now-Social** [comment] 2023-11-17 03:52
i have the same issue

**Comment by dimemacau** [comment] 2023-11-19 19:02
Hi guys, any updates on this?

**Comment by SameerShahzad99** [comment] 2024-01-23 13:07
@dimemacau I really apologize for the delay, can you please confirm if you are still experiencing this issue, also please share a blank project with the issue reproduced, so we can dig deeper to get this resolved as soon as possible.

I again apologize and appreciate your patience while we work on this resolution!

**Comment by hariprasadms** [comment] 2024-02-10 10:25
Hi, Apologies for the delayed response. Since the issue doesn't seem to be widespread and hasn't received further follow-up, it may have been inadvertently overlooked. Given the age of the issue, it's possible that it has been addressed in the latest FlutterFlow updates. Please verify if you are still encountering the problem, and if so, we can proceed with investigating it further. I've marked the issue status as _"waiting for user response"_ and will leave it open for the next 4 days before closing it. Thank you for your understanding.

**Comment by hariprasadms** [comment] 2024-02-13 09:43
If the same issue persists, kindly create a new issue with additional details. Thank you!

**Closed by hariprasadms** 2024-02-13 09:43 UTC
Labels: status: needs triage, waiting for user response
