### ISSUE TITLE
Multi-Select ChoiceChips Returns null When Nothing is Selected

### ISSUE THREAD

**Issue by KeepTrackSolutions** [FlutterFlow/flutterflow-issues#2064] opened 2023-12-26 23:27 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When storing the Widget State value of a Multiselect Choice Chips with nothing selected to an App State Variable, I am getting an Unexpected Null Value Uncaught (in promise) Error. Similarly, if this null value is stored to Firebase field and loaded as the initially Selected value, I am unable to then select any of the chips. The add function fails as the array is not initialised.

```
Uncaught (in promise) Error: Unexpected null value.
    at Object.throw_ [as throw] (dart_sdk.js:5402:11)
    at Object.nullCheck (dart_sdk.js:5752:30)
    at home_page_widget.dart:125:63
    at home_page_widget._HomePageWidgetState.new.setState (framework.dart:1138:30)
    at home_page_widget._HomePageWidgetState.new. (home_page_widget.dart:123:21)
    at Generator.next ()
    at runBody (dart_sdk.js:39921:34)
    at Object._async [as async] (dart_sdk.js:39957:7)
    at home_page_widget.dart:122:30
    at flutter_flow_widgets._FFButtonWidgetState.new. (flutter_flow_widgets.dart:110:32)
    at Generator.next ()
    at runBody (dart_sdk.js:39921:34)
    at Object._async [as async] (dart_sdk.js:39957:7)
    at flutter_flow_widgets.dart:104:15
    at ink_well._InkResponseState.new.handleTap (ink_well.dart:1154:21)
    at tap.TapGestureRecognizer.new.invokeCallback (recognizer.dart:275:24)
    at tap.TapGestureRecognizer.new.handleTapUp (tap.dart:654:11)
    at [_checkUp] (tap.dart:311:5)
    at tap.TapGestureRecognizer.new.acceptGesture (tap.dart:281:7)
    at arena.GestureArenaManager.new.sweep (arena.dart:167:12)
    at binding$5.WidgetsFlutterBinding.new.handleEvent (binding.dart:492:20)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (binding.dart:468:14)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (binding.dart:333:11)
    at [_handlePointerEventImmediately] (binding.dart:413:7)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (binding.dart:376:5)
    at [_flushPointerEventQueue] (binding.dart:323:7)
    at [_handlePointerDataPacket] (binding.dart:292:9)
    at Object.invoke1 (dart_sdk.js:193949:7)
    at _engine.EnginePlatformDispatcher.new.invokeOnPointerDataPacket (dart_sdk.js:168031:15)
    at [_onPointerData] (dart_sdk.js:169333:49)
    at dart_sdk.js:169910:30
    at dart_sdk.js:169850:9
    at loggedHandler (dart_sdk.js:169497:11)
    at Object._checkAndCall (dart_sdk.js:5625:16)
    at Object.dcall (dart_sdk.js:5630:17)
    at ret (dart_sdk.js:61495:21)
```

**Comment by hariprasadms** [comment] 2023-12-28 16:49
Hi @KeepTrackSolutions - Is the issue still persisting on your end? Upon reviewing your project, I couldn't replicate the issue; it seems to be woking as intended without any problems.

**Comment by KeepTrackSolutions** [comment] 2023-12-28 21:47
@hariprasadms, Thanks for taking a look.  Yes, this is still an issue on our end.  Please make sure that you have set the choice chips to multi-select.  
<img width="161" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/134727359/15566659-9798-4047-92c0-174a709d0cfb">


You will find that when you run with multi-select enabled, the first chip is NOT selected by default and null is returned if nothing is selected.

**Comment by hariprasadms** [comment] 2023-12-29 10:36
Hi @KeepTrackSolutions -I've tested it in your project, and I haven't seen any errors. The functionality appears to be working correctly. Please check and confirm. Thanks

**Comment by KeepTrackSolutions** [comment] 2023-12-29 16:15
Hi @hariprasadms,  I have added a Alert Dialog action after the Update App State which throws the error.  This Alert Dialog is never displayed.  I have also taken a video to hopefully make it a bit clearer to see the issue.  Please take another look.  We are still experiencing this issue.


https://github.com/FlutterFlow/flutterflow-issues/assets/134727359/bc495f42-9b83-49f7-9917-1cc45f5c1e17

**Comment by hariprasadms** [comment] 2024-01-08 12:11
Hi @KeepTrackSolutions - I am still not able to reproduce the issue. I can run your project with no configurations changes. All working fine. See below.

https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/a775e195-2b2d-4db2-b111-ec77c2f63254

**Comment by KeepTrackSolutions** [comment] 2024-01-08 19:41
@hariprasadms this is still an issue for us.   I just tried it again in my project and reproduced the issue.

When you run a test build, do not select any of the choice chips.  Your video shows your clicking the choice chips.  Just press the button.  We cannot get the Alert Dialog after the Update App State to show when the button is pressed AND no choice chips have been selected.  This doesn't work if you set a chip and then unset it, only if you haven't pressed it.

Our plan was to use this to display options to customers of which none can be selected.  The issue is, if none are selected the choice chips component Widget State value is null and a null Exception is thrown (see my previous video).

It is Very frustrating that FF Support team looked at this with me. They said it was a bug.  They asked me to log it and now you are 'unable' to reproduce it.

**Comment by hariprasadms** [comment] 2024-01-15 08:11
Hi @KeepTrackSolutions - I'm still unable to produce it. However, I'm marking it for technical triage. Meanwhile, if you've already found the solution, please feel free to close the issue. Thanks!

**Comment by takashiff** [comment] 2024-02-07 20:59
Hi @KeepTrackSolutions, thank you for your bug report. We've put in a fix for this recently, and the changes should be reflected within the next few weeks. Thanks

**Closed by takashiff** 2024-02-07 20:59 UTC
Labels: type: bug, Bug
