### ISSUE TITLE
Clicking on any project's issue listed error navigates to the right widget, but also opens "widget palette" instead of "widget tree"

### ISSUE THREAD

**Issue by elementh69** [FlutterFlow/flutterflow-issues#1830] opened 2023-11-11 14:30 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I can see some project issues (errors list) in the FF's interface.
i.e. "Property Override: Boolean property not properly set in Card"
When I click on it - it opens the right widget's settings panel on the RIGHT SIDE od the screen, but on the LEFT SIDE it opens "widget pallete" instead of "widget tree" navigated/focused on the right page or component.

### Expected Behavior

opening "widget tree" navigated/focused on the right page or component

### Steps to Reproduce

start new project
force it to have an error i.e. in visibility settings on any widget
click on the error in list
then happens what I explained above

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4klMrqy4xOj7xY17X5bcZWhiA7H181TL07ttYbZxUjIuPtBJh/eszCTxFuUvXiTFNhHFeYgToB+Mr2iIbfLu4qFw2cb7Zm1ZNuEzzhd3q8Ra7WDqWKRXAkGftRFWKl4bujnhVQGONocmQQ2zmuediyVhLqCZ+/Zwh9f6PHaOI=

### Context

i tried to be navigated to the right page by clicking on disaplyed error

### Visual documentation

no need

### Environment

```markdown
- FlutterFlow version: newest
- Platform: web
- Browser name and version: chrome
- Operating system and version affected: macOS
```

**Comment by hariprasadms** [comment] 2023-11-12 13:22
Hi @elementh69, I tested it and I can confirm that it is working as expected. See below video. As visibility property is not set, on clicking on the error details, it opens the property panel of text widget. However, left side opening widget pallet is as per current design. It can be consider as enhancement instead a bug. 

https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/77a26644-62dc-4dae-ac63-4a2e6512c030

**Comment by elementh69** [comment] 2023-11-12 14:47
Yes, exactly. The problem I am talking about is LEFT SIDE. After clicking on error the only way to know where am I is to look on the URL. I think that opening right page and widget on widget tree would be more helpful than widget palette.

**Comment by victoriahuang1** [comment] 2023-12-17 22:34
Hi @elementh69 , thanks for the report. This should be fixed now, as I can't reproduce this issue. Feel free to reopen if that is not the case.

**Closed by victoriahuang1** 2023-12-17 22:34 UTC
Labels: type: feature / enhancement request
