### ISSUE TITLE
Font Awesome Icons not showing on Run mode

### ISSUE THREAD

**Issue by juabergon** [FlutterFlow/flutterflow-issues#3236] opened 2024-06-25 23:00 UTC
### Can we access your project?

- [ ] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When running the app on run mode the icons are not showing

### Expected Behavior

Icons should show

### Steps to Reproduce

1. Set icons
2. pres Run mode
3. icons missing

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfkMmB34V2ob0E14SJL8JGhmEvH0ccTZM3lOsYGAEdfKrkE+wtP/T+aXdtQszhTG1MDValmlIJ+tbFiobDOMcBNUuZUbV607t6Zg/jTlutV6rSC7qsWEZ7O+FmJkil4KeFhQpNKsZtLF5g61+Hcq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

![Captura de pantalla 2024-06-25 214715](https://github.com/FlutterFlow/flutterflow-issues/assets/92979434/d355df02-8be3-4b70-b7ea-033178b6f513)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by msusviela** [comment] 2024-06-25 23:07
Hi. I wasn't able to reproduce the issue from a blank project using the same icons that you're using in your project. Could you please provide more information about the platform that you're using (web/desktop) and the operative system you're on?<br>Thanks.

**Comment by juabergon** [comment] 2024-06-26 11:23
@msusviela Just putting some Font Awesome icons on the app an hitting Run you can see they dont display. Im using web chrome

**Comment by msusviela** [comment] 2024-06-26 13:34
@juabergon, Thanks for your report, So sorry you are experiencing this issue. I was not able to reproduce this on a blank project. I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: support@flutterflow.io or using the in-app chat inside of FlutterFlow. I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. Thanks so much!

**Closed as not planned** 2024-07-02 20:05 UTC
Labels: closed: support request

**Comment by lucbic** [comment] 2024-07-25 20:38
I'm facing the same problem with my app in Run Mode

**Comment by ibiolm** [comment] 2024-12-17 09:31
Same problem, Font awesome icons not showing in Run Mode
