### ISSUE TITLE
Build error on web emulator, but not physical/emulator mobile device

### ISSUE THREAD

**Issue by mikedyos999** [FlutterFlow/flutterflow-issues#3220] opened 2024-06-25 15:54 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Cannot publish to Web, appears to be a dependancy issue affecting all FF users

### Expected Behavior

should publish normally, not a complex app. 

### Steps to Reproduce

just try and publish to web

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4OheflwItNpbwC+KrpbcFViiUsJm4jarxMlcBxcEwjferNG7UIec/4VEptXbC+TVc3PE2Gnn8106yMhtzIN/Q6KQ2cfapxyZBXFjzKRkStWqahPJC8WkZRLNpKBUiP37eruBV+GMxhdHAB1GeUGuiQTjbvNJDtPm4vJMiXEJP/o3/uQ0SLb3kNh1JWeC/v

### Visual documentation

Error: Command failed: flutter build web  --web-renderer html --no-pub --no-version-check --no-tree-shake-icons
Target dart2js failed: ProcessException: Process exited abnormally with exit code 1:
/opt/.pub-cache/hosted/pub.dev/app_links-3.4.1/lib/app_links.dart:11:38:
Error: The method 'getInitialAppLink' isn't defined for the class 'AppLinksPlatform'.
 - 'AppLinksPlatform' is from 'package:app_links_platform_interface/app_links_platform_interface.dart' ('/opt/.pub-cache/hosted/pub.dev/app_links_platform_interface-1.2.0/lib/app_links_platform_interface.dart').
    return AppLinksPlatform.instance.getInitialAppLink();
                                     ^^^^^^^^^^^^^^^^^
/opt/.pub-cache/hosted/pub.dev/app_links-3.4.1/lib/app_links.dart:16:38:
Error: The method 'getInitialAppLinkString' isn't defined for the class 'AppLinksPlatform'.
 - 'AppLinksPlatform' is from 'package:app_links_platform_interface/app_links_platform_interface.dart' ('/opt/.pub-cache/hosted/pub.dev/app_links_platform_interface-1.2.0/lib/app_links_platform_interface.dart').
    return AppLinksPlatform.instance.getInitialAppLinkString();
                                     ^^^^^^^^^^^^^^^^^^^^^^^
/opt/.pub-cache/hosted/pub.dev/app_links-3.4.1/lib/app_links.dart:21:38:
Error: The method 'getLatestAppLink' isn't defined for the class 'AppLinksPlatform'.
 - 'AppLinksPlatform' is from 'package:app_links_platform_interface/app_links_platform_interface.dart' ('/opt/.pub-cache/hosted/pub.dev/app_links_platform_interface-1.2.0/lib/app_links_platform_interface.dart').
    return AppLinksPlatform.instance.getLatestAppLink();
                                     ^^^^^^^^^^^^^^^^
/opt/.pub-cache/hosted/pub.dev/app_links-3.4.1/lib/app_links.dart:26:38:
Error: The method 'getLatestAppLinkString' isn't defined for the class 'AppLinksPlatform'.
 - 'AppLinksPlatform' is from 'package:app_links_platform_interface/app_links_platform_interface.dart' ('/opt/.pub-cache/hosted/pub.dev/app_links_platform_interface-1.2.0/lib/app_links_platform_interface.dart').
    return AppLinksPlatform.instance.getLatestAppLinkString();
                                     ^^^^^^^^^^^^^^^^^^^^^^
/opt/.pub-cache/hosted/pub.dev/app_links-3.4.1/lib/app_links.dart:41:38:
Error: The getter 'allStringLinkStream' isn't defined for the class 'AppLinksPlatform'.
 - 'AppLinksPlatform' is from 'package:app_links_platform_interface/app_links_platform_interface.dart' ('/opt/.pub-cache/hosted/pub.dev/app_links_platform_interface-1.2.0/lib/app_links_platform_interface.dart').
    return AppLinksPlatform.instance.allStringLinkStream;
                                     ^^^^^^^^^^^^^^^^^^^
/opt/.pub-cache/hosted/pub.dev/app_links-3.4.1/lib/app_links.dart:46:38:
Error: The getter 'allUriLinkStream' isn't defined for the class 'AppLinksPlatform'.
 - 'AppLinksPlatform' is from 'package:app_links_platform_interface/app_links_platform_interface.dart' ('/opt/.pub-cache/hosted/pub.dev/app_links_platform_interface-1.2.0/lib/app_links_platform_interface.dart').
    return AppLinksPlatform.instance.allUriLinkStream;
                                     ^^^^^^^^^^^^^^^^
Error: Compilation failed.
  Command: /sdks/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /sdks/flutter/bin/cache/dart-sdk/bin/snapshots/dart2js.dart.snapshot --platform-binaries=/sdks/flutter/bin/cache/flutter_web_sdk/kernel --invoker=flutter_tool -Ddart.vm.product=true -DFLUTTER_WEB_AUTO_DETECT=false -DFLUTTER_WEB_USE_SKIA=false -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/04817c99c9fd4956f27505204f7e344335810aed/ --native-null-assertions --no-source-maps -o /tmp/ff_service_scratch/1EdW366MuIsJ7NWSVmqN/s_b_i_v_d_manager/.dart_tool/flutter_build/97a1b05718bec35a2ce1d0104b22dca1/app.dill --packages=.dart_tool/package_config.json --cfe-only /tmp/ff_service_scratch/1EdW366MuIsJ7NWSVmqN/s_b_i_v_d_manager/.dart_tool/flutter_build/97a1b05718bec35a2ce1d0104b22dca1/main.dart
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:127:5)

Error: Failed to compile application for the Web.

### Environment

```markdown
FlutterFlow version: v4.1.61
Platform (e.g. Web, MacOS Desktop): Web
Browser name and version (web): Chrome 107.0.5304.110
Operating system and version (desktop): macOS Monterey 12.2.1
```

### Additional Information

cannot work

**Comment by pavankumar5135** [comment] 2024-06-25 15:55
@mikedyos999 same here

**Comment by MartinMadale** [comment] 2024-06-25 16:35
I am also getting this error

**Comment by msusviela** [comment] 2024-06-25 16:42
Hi all. It seems to be related to a package upgrade on [pub.dev](http://pub.dev/). Our engineering team is already aware and working on a fix.

I'm closing this issue because It's a duplicate of: [https://github.com/FlutterFlow/flutterflow-issues/issues/3217](https://github.com/FlutterFlow/flutterflow-issues/issues/3217) I'll be following this from this issue.

Thanks for your reports!

**Closed as not planned** 2024-06-25 16:50 UTC
Labels: closed: duplicate
