### ISSUE TITLE
Notification icon on android devices

### ISSUE THREAD

**Issue by staplKody** [FlutterFlow/flutterflow-issues#2901] opened 2024-05-13 16:14 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When a firebase notification arrives to my android device, a blank circle is rendered for the icon. (it was a square before adaptive icons was added and I uploaded one) 

### Expected Behavior

I would expect the notification icon to display the app icon, or an icon from the res/mipmap folders. 

### Steps to Reproduce

Send a firebase cloud messaging payload to an android device. Observe the icon does not render the app's icon.  
To see a "custom" outline, add these two lines to the AndroidManifest.xml: 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/137829936/acff75d9-7944-45df-9608-33de181d2833)
this will display an outline of the icons in the res/mipmap folders. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kkcjfsMx2rsdY17X5be5Fv2UUQlAgTLJEpu0bWUkbGO/4O7QDOvTsSEhtQsyzaH5YB2aYiTgz06HTv87tCMYDH0+AfIR4zqpIUxPPbGShMsWVEsyeXmhBL9xUBXacy5insSNQAO5qdVYlwV+qeuq9Fj6Cf9qOYwx5e6fDbOY=

### Context

This is holding up my production release of the android platform on my app. I have tried researching general android issues on this, and the best I have gotten is to add a default icon in the AndroidManifest.XML file, but that results in the same type of icon rendered, but instead outlining the logo I uploaded. I suspect the outlined circle is the app icon, but for whatever reason it is only rendering an outline of it. 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/137829936/c5eebf2b-9fa9-4add-8367-e222037e8f55)

### Visual documentation

The native icon that is rendered: ![image](https://github.com/FlutterFlow/flutterflow-issues/assets/137829936/b0078e25-9eb2-47bd-8e5f-c82fd6770975)
After setting the default icon to the ic_launcher file (the flutter logo is there by default): 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/137829936/232227b3-3bd4-4724-ba56-c540d849fc75)

After setting a default icon in the manifest and adding our logo to the mipmap folders in place of the flutter logo: 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/137829936/10f6a575-0c72-4584-9ecd-b80b675459ad)

### Additional Info

Here is my thread on the community forum regarding the issue. Others have the same problem as well. https://community.flutterflow.io/ask-the-community/post/push-notification-image-is-not-set-OVXoFkyM4uqiL1k?highlight=PXiIgrHsq0muSZS

It is noteworthy that I am not using the built in push notifications cloud function or console or anything, we have our own cloud functions written for this. you can see in the community thread the payload I am sending, I modeled it after the cloud function that flutterflow automatically deploys when enabling push notification. There are also no other issues with the notifications other than the icon only on android. 

### Environment

```markdown
- FlutterFlow version: 4.1.49+
- Platform: Windows 11
- Browser name and version: N\A
- Operating system and version affected: Windows 22631.3527
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by staplKody** [comment] 2024-05-14 14:13
I would like to add some additional context to this situation. I have resolved it, but it had to be done with custom code with no guidance to be found in any flutterflow documentation. I have also updated the community thread with my findings. 

What I had to do was generate a set of transparent png's that were in gray scale (white) and place those files into the mipmap folders in the project's source code (replacing the flutter logos that were there) and naming them ic_launcher. Then, I had to add the manifest tag for the default notification icon to point to @mipmap/ic_launcher. At that point, I began seeing the icon in the notifications. In order to color the icon, I followed this repo https://github.com/firebase/quickstart-android and saw that a colors.xml file needed to be defined with the RGB code I wanted. Then, I added a tag for the default notification color in the manifest that used @color/staplGreen (what I named my color for).  

I will keep this issue open because I suspect you guys intended for the adaptive icon to take the place of the notification icon, but it actually renders the whole adaptive icon instead which creates that outline of a square or circle since at that point it isn't a transparent image but a solid square/circle instead.

If I am mistaken and there just isn't any implementation for the notification icon to be set, can you please write some documentation guiding users on how to implement these or possibly create some way in flutterflow to add these without touching the custom code?

**Comment by paulperez-dev** [comment] 2024-05-15 19:13
Hey @staplKody! So sorry you were experiencing this issue. I will be talking with the ENG team and verify if a change needs to be made or if the documentation needs improvement.

<br>Thanks so much!

**Comment by paulperez-dev** [comment] 2024-05-16 23:32
Hi @staplKody! The source of the issue is the launcher icons package:  [https://github.com/fluttercommunity/flutter_launcher_icons/issues/537](https://github.com/fluttercommunity/flutter_launcher_icons/issues/537). We will revisit this after they solve this. I'm closing this for now.

**Closed** 2024-05-20 23:31 UTC
Labels: closed: other

**Comment by Zaaap180** [comment] 2025-04-30 15:37
> Hey [@staplKody](https://github.com/staplKody)! So sorry you were experiencing this issue. I will be talking with the ENG team and verify if a change needs to be made or if the documentation needs improvement.
> 
> Thanks so much!

Hi, @paulperez-dev 
Is FlutterFlow working on a default solution for this? I'm not a developer and I couldn't follow the solution provided in this thread. I'd like to know if there's any no-code solution of proper documentation for this issue.
Thanks

**Comment by azzar227** [comment] 2025-07-23 16:13
Adding myself to this thread as I need a fix for this bug too and I am not technical enough for the mentioned custom solution.
