### ISSUE TITLE
Dropdown stopped working since Flutterflow upgrades in Jul

### ISSUE THREAD

**Issue by bmw559** [FlutterFlow/flutterflow-issues#3118] opened 2024-06-13 12:57 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

All my dropdowns stopped working, options are displayed only when I click on the dropdown label text or icon anywhere in the box is not working.
I tested multiple devices, its the same behavior for all my dropdowns across my entire app

I did some testing and it seems the issue is only when some value is already preselected or you choose some value and you wanna try to change it.
![codeDropdowns](https://github.com/FlutterFlow/flutterflow-issues/assets/108012000/26dc3bc0-50f9-4d5b-b2f0-f13845ecd7cb)
![dropdownRealCase](https://github.com/FlutterFlow/flutterflow-issues/assets/108012000/ecd71ff6-fa28-417b-983c-24557aab95d2)
![dropdownView](https://github.com/FlutterFlow/flutterflow-issues/assets/108012000/38f1abdf-9ec4-4a84-ba36-53f38ad2b236)

### Expected Behavior

Click anywhere on the dropdown container display dropdown options

### Steps to Reproduce

1. Create new page
2. add dropdown and 2 options
3. Build real case, click on the dropdown and select one of the option, then click for example in the center of the container the options are not displayed

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oi+fl/otItbxc0KXyb8BFmSQvJnp+RLhMkcpBazwbfe+uB4kqevfOTERVZ8iqS1FmJGL8mWoW0MrwhYbPNMc4BxOeRY8+/rhyERaXUkWiMMSVFJWgeGtPGd9UFW3HyJiRghJSVehiR1Yd2E2UIfK/Yz3DQqa3DFgsDq/LZO4=

### Visual documentation

![codeDropdowns](https://github.com/FlutterFlow/flutterflow-issues/assets/108012000/7195c3e4-c059-4700-bae5-6557a67cc7ca)
![dropdownRealCase](https://github.com/FlutterFlow/flutterflow-issues/assets/108012000/62c82b47-7f97-4420-b8ae-19aaeb2a450f)
![dropdownView](https://github.com/FlutterFlow/flutterflow-issues/assets/108012000/c9da6d4a-0d9d-4ff0-bf90-7eb503ae8fc4)

### Environment

```markdown
- FlutterFlow version:  3.19.1
- Platform: Web
- Browser name and version: Chrome Verzia 125.0.6422.142
- Operating system and version affected: Windows 11
```

**Comment by bmw559** [comment] 2024-06-13 13:43
Here is recorded video and shown the not working dropdown

https://github.com/FlutterFlow/flutterflow-issues/assets/108012000/f4b1d3b8-cd58-408e-a237-f5ce037644e6

**Comment by msusviela** [comment] 2024-06-13 19:26
Hey @bmw559, Thanks for your report, So sorry you are experiencing this issue. I was not able to reproduce this on a blank project, but it is replicable on yours. That's why I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. Thanks so much!

**Comment by bmw559** [comment] 2024-06-14 11:17
Hey I was able to reproduce the issue in blank project, I found the route couse @msusviela 
Will create new issue

**Comment by rzambroni** [comment] 2024-06-17 17:28
Closing as duplicate in favor of: https://github.com/FlutterFlow/flutterflow-issues/issues/3134

**Closed as completed by rzambroni** 2024-06-17 17:28 UTC
Labels: status: can't reproduce
