### ISSUE TITLE
API call fails silently if host is unreachable

### ISSUE THREAD

**Issue by anttikuuskoski** [FlutterFlow/flutterflow-issues#640] opened 2023-03-20 11:42 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When an API call to an unresponsive host is performed, the subsequent actions in the action chain are never executed. This happens also when other types of networking errors are performed such as: nonexistent URL, url blocked by Chrome (blocked due to mixed-content).

### Expected Behavior

An API call to unresponsive host (or to a nonexistent URL or whatever the error source) should at the very least not terminate the action chain, especially as there seems to be no way to catch such errors. As the call's success state can be used directly in action conditionals, it would be natural if the call would simply be labeled as unsuccessful. 

In my opinion, having a host down or the user mistyping an URL etc. is a normal thing to happen and should be dealt as such from actions' point of view.  

### Steps To Reproduce

1. Create an API call to https://nonexistent6592831.com
2. Create an action chain with:

- State update setting a variable to known value
- backend API call
- condition testing for the API call response options to be "Succeeded"
- State updates in both branches setting a variable to known values.

3. Run the application. 
4. The app state update before the API call is triggered but actions in the conditional branches are not.

Screenshot of the action chain: ![image](https://user-images.githubusercontent.com/20336930/226326811-85246a08-063b-4115-b728-c639063b67e2.png)

### Bug Report Code

IT4Kzsncx851xMNc18/iKMFKhjwWKVwjauYsltVDb0ocIZSqG7l/TMnOVBJuOLC0dwlUf2f8jnsJ+d3emvzAUfk3EzeBUaphybVQdguWWnu6RcWrBaisf25/De1NC2Kk4KWNgBB4PfpaWV4l6jn3F/CyfBPXQZDsPVg7AeaLKZOK2SrDX1iXc2URm05KZDPz

### Context

In my application I need to poll if a certain host is available or not and this is proving very hard to do as the action chains fail to run through. This is already the second project that I'm considering scrapping due to poor networking error handling. 

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web
- Browser name and version: Chrome 111.0.5563.65 (Official Build) (64-bit)
- Operating system and version affected: Windows 10 Pro 22H2
```

**Comment by hariprasadms** [comment] 2023-03-20 15:47
Hi @anttikuuskoski - What response you get while testing this broken endpoint in api test mode?.

in FF, api response result ( succeeded step in your action) will define what to display. Based on succeeded ( You can try to use status code to check the status of api result ) you can display a message in the app. 

It is working as expected.

**Comment by anttikuuskoski** [comment] 2023-03-20 16:51
Hi @hariprasadms & thanks for your response. 

Answers below, I took the liberty to rearrange your response in order to be able respond more precisely.

> Hi @anttikuuskoski - What response you get while testing this broken endpoint in api test mode?.

"Testing call failed. Error: XMLHttpRequest Error". The same error occurs whether if the API call is timed out (nonresponsive IP address) or a nonexistent url (name cannot be resolved). Does not sound like the correct error to me in case it matters.

![image](https://user-images.githubusercontent.com/20336930/226406029-bda1fa53-b71e-4e74-a383-fd53e997322b.png)

> in FF, api response result (succeeded step in your action) will define what to display. Based on succeeded you can display a message in the app.

I'm not sure what you mean. The point of the issue here is that the action chain execution stops at backend API call step, i.e. before it gets to the point where the condition is tested.  

>  (You can try to use status code to check the status of api result ) 

Firstly, not once in my FF history (a few months) has the possibility of using status code been available for me, instead it is always disabled (red) and cannot be selected: ![image](https://user-images.githubusercontent.com/20336930/226407230-3db22423-f5b2-43fb-a641-086ce9ac631f.png). 

Secondly, even if status code was usable, I would not expect it to help since, as mentioned, the action chain execution stops at the backend call time so the condition testing would not be reached regardless of the type of condition.

> It is working as expected.

Just to be certain, I retested this by adding an intermediate status update after the API call and can so verify the problem. So the action chain is now:
1. Set variable
2. Call API (with nonexistent host name OR a nonresponsive IP address, tested both)
3. Set variable

![image](https://user-images.githubusercontent.com/20336930/226410032-5976ff09-5e13-4d19-9234-3f00efd12ead.png)

What happens is that step 3 is never executed.

It does not sound reasonable that this would be working as expected.

**Comment by hariprasadms** [comment] 2023-03-20 20:23
Hi @anttikuuskoski, Below is the way you can use api response status code. I hope it can help you to configure actions in the chain. 

As it is not a bug, I will close the issue now. Let me know if you need help. Thanks 

![image](https://user-images.githubusercontent.com/17435678/226456733-baaa67d5-d8d1-4b85-a3d7-88181c59899b.png)

**Closed** 2023-03-20 20:23 UTC
Labels: closed: not a bug

**Comment by anttikuuskoski** [comment] 2023-03-20 21:55
Hi @hariprasadms & thanks for your patience (and showing how to use the response code properly). It seems that I am unable to state the problem understandably but I'll try once more as I think this is a real matter worth fixing. 

The problem is that the action chain execution stops completely if host is unreachable. The actions after API call block are **not executed at all** including any app state updates and conditionals. Your instructions (good as they are) do not help because execution never goes that far.

**Comment by chatch** [comment] 2023-06-26 05:00
Adding to this, it's still an issue and totally agree it's a bug ... 

What happens is the api_calls.dart functions and the underlying generated code use the dart http package to make the request. that throws when there is an issue like the above but also for 401s, in my case from expired token, but presumably any non 2xx http status code is throwing exceptions. 

because there is no try catch around the request the exception is uncaught in the flutter app and this is why the action chain stops completely as described above.

so as it stands this can only be handled by writing custom action code. but why not update the api call code to catch these and let them be handled by an action chain? with action blocks now you can define reusable error handlers so it would be a very easy way to catch and handle these.
