### ISSUE TITLE
Can't save List<int> to app state

### ISSUE THREAD

**Issue by Godfrey1912** [FlutterFlow/flutterflow-issues#920] opened 2023-05-23 20:49 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

As per now-closed https://github.com/FlutterFlow/flutterflow-issues/issues/683#issue-1644551835.

A list of integers cannot be saved to an app state of type list< integer >.  The solution provided in issue 683 is incorrect, as saving as a type of list< JSON > does not resolve the issue.

### Expected Behavior

Having created an app state variable of type list< int >, I expect to be able to save a list of integers obtained from a JSON path to that variable in an "Update app state" action.  This is not possible, and produces an error as described in issue 683.

Note that manually keyed-in values into the same app state behave correctly.  In other words, it *is* possible to have a list of integers in a correctly-configured app state, but *not* possible to save them in bulk. 

### Steps to Reproduce

Create API endpoint which return a list of integers
Create JSON path of List< integer >
Create App State with type List< integer >
Create Login button or Register and use action "Update App State" and save the JSON path to App State variable
Run the Test Mode
Hit Login or Register button and check browser console for error

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Khc/1sIhgrsMA7aXyKe9ahmEXHD8jarswlsJud0kbC72qG7YAW/SkQE9WZ7yhdH03Ok20kT81+sKLvtzIN+wqF0+rRaU/yKpQbQLKfEKWbLKuOpbse39PGtpKC0zA56a32BYnHM5idCUO73GQC+i9TnLcQJT1NlUaAPyIDLP/o3/uQ0SLb3kNh1JWeC/v

### Context

I need a list of integers for populating the X and Y axes of a chart.  I also need to be able to filter these values, such as ">10" or "=50".  This not possible when the JSON path is saved to an app state variable as list< JSON >.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/99770404/9c1e9be0-b19d-4296-b9cb-c15292aa77d2)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/99770404/c6aad284-7510-4188-b68e-e7e0ab9f2596)

### Additional Info

See also my discussion at: https://community.flutterflow.io/c/discuss-and-get-help/setting-app-state-list-values#comment_wrapper_19446918

### Environment

```markdown
- FlutterFlow version: 3.7.12
- Platform:web
- Browser name and version:Chrome 113.0.5672.63
- Operating system and version affected: Linux pop_os 22.04
```

**Comment by WellDunDun** [comment] 2023-05-24 13:40
I'm having the same issue and you can find my workaround for it [here](https://youtu.be/JTDAwYdaiU8). Essentially I created a custom function to parse the list<JSON> into an list<int>. Hope this helps!

**Comment by kevintonb** [comment] 2023-05-24 21:26
Hey @Godfrey1912 the bug was reproducible, thank you for reporting.

**Comment by wenkaifan0720** [comment] 2023-05-26 01:01
Hi @Godfrey1912, @kevintonb. Care to share with me a test project that reproduces this issue? I looked into the project with the provided bug report code but couldn't find any List<int> app state variables.

**Comment by kevintonb** [comment] 2023-05-26 07:27
Hey @wenkaifan0720 , please check the page "Issue 920" in this [test project](https://app.flutterflow.io/project/triage-test-qw8syk)

**Comment by Godfrey1912** [comment] 2023-05-26 12:12
> Hi @Godfrey1912, @kevintonb. Care to share with me a test project that reproduces this issue? I looked into the project with the provided bug report code but couldn't find any List app state variables.

Apologies, I had deleted them since I wasn't using them.  I've created "testList" in my project now which you can test against too.

**Comment by wenkaifan0720** [comment] 2023-05-29 01:32
This is because once JSON is involved, Flutter doesn't know the type of the data anymore and will produce an error like this: `Unhandled Exception: type 'List<dynamic>' is not a subtype of type 'List<int>'`.

The solution is to manually cast the data to type `int`, which we will do on our side in the next update.

**Comment by Krystian95** [comment] 2023-05-30 14:57
> This is because once JSON is involved, Flutter doesn't know the type of the data anymore and will produce an error like this: `Unhandled Exception: type 'List<dynamic>' is not a subtype of type 'List<int>'`.
> 
> The solution is to manually cast the data to type `int`, which we will do on our side in the next update.

Hi @wenkaifan0720, thanks for you reply! Which could be the ETA of this fix?

**Comment by wenkaifan0720** [comment] 2023-06-04 01:02
I have pushed a fix for this in our dev channel. Should be in production in about a week.

**Closed by wenkaifan0720** 2023-06-04 01:02 UTC
Labels: type: bug, status: confirmed, closed: fixed

**Comment by Godfrey1912** [comment] 2023-06-06 10:35
> I have pushed a fix for this in our dev channel. Should be in production in about a week.

Great, thank you

**Comment by stevey6404** [comment] 2023-07-30 07:18
Hi team, I'm experiencing the same problem with type 'List<Double>'. Was this considered in the fix?

**Comment by JesJehle** [comment] 2023-08-07 09:21
Hi, I also experience the same problem:
`Expected a value of type 'List<double>?', but got one of type 'List<dynamic>'`
It seems values from an API call are not converted to type `double` but `dynamic`.

**Comment by JesJehle** [comment] 2023-08-07 09:56
Wow, thanks for the prompt reply!
I used this one:
```
List<double>? jsonToDoubleList(List<dynamic> listDynamic) {
  /// MODIFY CODE ONLY BELOW THIS LINE

// convert a JSON array containing doubles to a dart list of doubles
  return listDynamic.map((item) {
    if (item is double) {
      return item;
    } else if (item is int) {
      return item.toDouble();
    } else if (item is String) {
      return double.tryParse(item) ?? 0.0;
    } else {
      throw FormatException('Cannot convert $item to double');
    }
```
Some additional checks in case of other types. 
Thanks, a lot!

**Comment by f4cilsolucoes** [comment] 2023-09-28 13:33
I'm having the same problem, the API returns a list<int>=[1,2681,2692,2693] but has this error: 

"expected a value of type 'list<int>', but got one of type 'list<object?>' "
