### ISSUE TITLE
buttons and text styles with dimmed view

### ISSUE THREAD

**Issue by yajlan2015** [FlutterFlow/flutterflow-issues#3079] opened 2024-06-07 09:01 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I create buttons and text with the same styles but i get some buttons and texts with different view like dimmed

### Expected Behavior

views with the same styles

### Steps to Reproduce

![home2](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f8ee932e-b412-4b17-9326-5ffa94ab4bf6/61adedce-2811-41e7-93b7-d08a428dc9ab?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mOGVlOTMyZS1iNDEyLTRiMTctOTMyNi01ZmZhOTRhYjRiZjYvNjFhZGVkY2UtMjgxMS00MWU3LTkzYjctZDA4YTQyOGRjOWFiIiwiaWF0IjoxNzE3NzYyMDA3LCJleHAiOjMzMjg4MzIyMDA3fQ.4Csf2whND6Z6r6dmDoZt8Jpl4aMW9vw1EJV5HagkhDA)

this is two rows with the same styles

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

don't have bug report code

### Context

so bad affected!

### Visual documentation

![textfemmed](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/7b71eaa4-7454-4dc1-908e-c6b28142feb0/12a8afb8-ebb7-4414-a9c2-c9ce2854cd65?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83YjcxZWFhNC03NDU0LTRkYzEtOTA4ZS1jNmIyODE0MmZlYjAvMTJhOGFmYjgtZWJiNy00NDE0LWE5YzItYzljZTI4NTRjZDY1IiwiaWF0IjoxNzE3NzYyMDA3LCJleHAiOjMzMjg4MzIyMDA3fQ.Is5I3qKTHrjzYfSwdeyEUPzbSsvalADOHu5qDiuWYiI)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1.54+ released June 4, 2024
- Platform: web browser
- Browser name and version: Microsoft Edge
- Operating system and version affected: 64-bit operating system, x64-based processor
```

**Comment by msusviela** [comment] 2024-06-07 12:07
Hi @yajlan2015 - Thanks for submitting the issue. I've taken a look at your project, but with a lot going on, it's challenging to pinpoint the issue. Given the nature of the problem you're highlighting, we need a blank project with the issue steps set up in it. Without these details, it might be a bit challenging for us to investigate the issue. Please provide the required information. If the issue is already resolved for you, please feel free to close the issue. Thanks!

**Closed** 2024-06-14 03:00 UTC
Labels: status: needs triage, waiting for user response
