### ISSUE TITLE
APK Build Error

### ISSUE THREAD

**Issue by Brocoleta** [FlutterFlow/flutterflow-issues#5128] opened 2024-12-17 19:19 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Im trying to download the apk but it says APK Build Error:

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:processReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR:/tmp/ff_service_scratch/mjrIunchoJSHC5h3z8w6/subb/build/app/intermediates/incremental/release/mergeReleaseResources/merged.dir/values-v35/values-v35.xml:4: AAPT: error: style attribute 'android:attr/windowOptOutEdgeToEdgeEnforcement' not found.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:bundleReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.Aapt2ProcessResourcesRunnable
   > Android resource linking failed
     ERROR:/tmp/ff_service_scratch/mjrIunchoJSHC5h3z8w6/subb/build/app/intermediates/incremental/release/mergeReleaseResources/merged.dir/values-v35/values-v35.xml:4: AAPT: error: style attribute 'android:attr/windowOptOutEdgeToEdgeEnforcement' not found.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 11m 46s
Gradle task assembleRelease failed with exit code 1

### Expected Behavior

The APK must be downloaded successfully

### Steps to Reproduce

1. Download apk from flutterflow project

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gi/HluJZ2rsdK1brUbu9WgmEXJVB9RL00st4bGAsdGOvrBqQIPvSlUE1ucM/gaVNfeE6KknkK3MrMv+LDFO5eNTSWRrZOyYd+TTzee2i6aaqyCLmaXHN9L/NMG0y54aaVpCNAXfpiL3Ab31z6e97JTg7DBOu/Zwh9f6PHaOI=

### Visual documentation

<img width="619" alt="image" src="https://github.com/user-attachments/assets/d7e43f1c-4859-49cb-b66d-a9e4f86147b3" />

### Environment

```markdown
- FlutterFlow version: 3.24.2
- Platform: Web
- Browser name and version: Chrome Version 131.0.6778.87 (Official Build) (arm64)
- Operating system and version affected: MAC M1 Sonoma 14.5
```

**Comment by paulperez-dev** [comment] 2024-12-18 20:36
Hi @Brocoleta,

Thanks for your report, So sorry you are experiencing this issue. I was not able to reproduce this on a blank project, but it is replicable on yours. That's why I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: support@flutterflow.io or using the in-app chat inside of FlutterFlow. <br><br>I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. <br><br>If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. <br><br>Thanks so much!

**Closed as not planned** 2024-12-18 20:37 UTC
Labels: status: needs triage, status: can't reproduce

**Comment by Majorlius** [comment] 2024-12-20 12:27
I have the same problem. project-specific to multiple projects
