### ISSUE TITLE
Visiblity feature not working for a set/not component parameter

### ISSUE THREAD

**Issue by fusionstudioro** [FlutterFlow/flutterflow-issues#2259] opened 2024-01-28 08:28 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When setting up the icon to be hidden if not set, the icon is still displayed.

### Expected Behavior

When setting up the icon to be hidden if not set, the icon should not be displayed.

### Steps to Reproduce

1. Create a new component with 2 icons
2. Set up the component to have 2 parameters, iconLeft (icon) and iconRight (icon)
3. Set the first icon as variable of iconLeft, and the second as variable of iconRIght
4. Set the visibility of the icons only to be displayed if the icons are set up in the component using visibility feature (ex: iconLeft is set)
5. Add the component to a page
   Issue is described here: [https://community.flutterflow.io/ask-the-community/post/show-hide-icon-inside-a-component-based-on-component-variable-set-unset-sv2AZASWAgxIeKu?highlight=NNiEGzCEZN6QLgx](https://community.flutterflow.io/ask-the-community/post/show-hide-icon-inside-a-component-based-on-component-variable-set-unset-sv2AZASWAgxIeKu?highlight=NNiEGzCEZN6QLgx)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wz8mAvM5Pj7xH1rXuY+9ViicWMjsgbedJmOxTeCs8JJToPLAUZ8zBM05vZry9Snw3JVm0pD4e7PfqiNnPU8IqIRGCY4RfwpFhWwz/ZGOWaa2aEsyJfW1fI/pQFXa03KSR2RFRANhoV0Fn702MBd+/UhPZJoTHNUcZO/G1KdeK2SrDX1iXc2URm05KZDPz

### Context

I'm trying to create a modular button as per design system (example: [https://preline.co/figma.html](https://preline.co/figma.html))

### Visual documentation

[https://community.flutterflow.io/ask-the-community/post/show-hide-icon-inside-a-component-based-on-component-variable-set-unset-sv2AZASWAgxIeKu?highlight=NNiEGzCEZN6QLgx](https://community.flutterflow.io/ask-the-community/post/show-hide-icon-inside-a-component-based-on-component-variable-set-unset-sv2AZASWAgxIeKu?highlight=NNiEGzCEZN6QLgx)

### Additional Info

[https://community.flutterflow.io/ask-the-community/post/show-hide-icon-inside-a-component-based-on-component-variable-set-unset-sv2AZASWAgxIeKu?highlight=NNiEGzCEZN6QLgx](https://community.flutterflow.io/ask-the-community/post/show-hide-icon-inside-a-component-based-on-component-variable-set-unset-sv2AZASWAgxIeKu?highlight=NNiEGzCEZN6QLgx)

### Environment

```
- FlutterFlow version: Flutter version is 3.13.7 (FutterFlow v4.1 released January 25, 2024)
- Platform: Windows Web
- Browser name and version: Chrome Version 121.0.6167.85
- Operating system and version affected: windows 10
```

**Comment by hariprasadms** [comment] 2024-01-29 12:43
Hi @fusionstudioro - I verified your project and it seems that the configuration you made to control the display of icons based on whether they are set or not set is not correct. Therefore, I am marking this as not a bug. I can confirm that the visibility features themselves are working fine for all widgets. Thanks.

**Comment by fusionstudioro** [comment] 2024-01-29 14:04
Hi Hari, I've updated the configuration. Can you please try again? with this error widget code? IT4wz8mAvM5Pj7xH1rXuY+9ViicWMjsgbedJmOxTeCs8JJToPLAUZ8zBM05vZryrY0FiMWaGmnEe1vfqkfPfCO4DBwmqRa5N+od2FAvgYEOuMI/WDpG7fW1fI/pQFXa03KSR2RFRANhoV0Fn702MBd+/UhPZJoTHNUcZO/G1KdeK2SrDX1iXc2URm05KZDPz

Or if I'm wrong with the configuration can you please tell me what is the correct one? I've left here the component with the current settings.
![Capture](https://github.com/FlutterFlow/flutterflow-issues/assets/157949653/2242c339-ccff-4067-8732-f53437ee13cf)

**Comment by hariprasadms** [comment] 2024-01-29 14:33
You should have a true or false flag for the icon and its display status when using the component in pages. Use conditional widget in component with the true or false flag value passed from pages. This approach can help achieve the desired outcome. Keep in mind that this is just one way to accomplish it, and there might be other approaches based on your specific use case.

**Closed** 2024-02-06 01:00 UTC
Labels: closed: not a bug
