### ISSUE TITLE
Android: MissingPluginException(No implementation found for method login on channel app.meedu/flutter_facebook_auth)

### ISSUE THREAD

**Issue by suhailbilalw** [FlutterFlow/flutterflow-issues#4976] opened 2024-11-26 09:50 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Facebook login is throwing error.

### Expected Behavior

should open facebook intent to login.

### Steps to Reproduce

create a page.
place a button.
add onPressed event authentication "facebook login" from the actions.
test on android.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ghefluYtPvsdY0aruYO9ViiEQOUh7a600st5Hd0gdCOPrBqQEZfeldk5uXtCraVNcC2KJpD0FwcmMv4TTNfY6Fw2Zc6J6+s9iFBb0e2iXVc2OBbqwRHd7GexYG0yOyImJnwhQHOx2L14k3V6QfOSsQjHDFOu/Zwh9f6PHaOI=

### Visual documentation

try implementing facebook login via android.

### Environment

```markdown
- FlutterFlow version: v5.0.0
- Platform: Android
- Browser name and version: Chrome 131.0.6778.86 (Official Build) (64-bit)
- Operating system and version affected: Win 11
```

**Comment by paulperez-dev** [comment] 2024-11-26 20:06
Hi @suhailbilalw,

I tried running your project locally to test the integration, but unfortunately, I wasn’t able to. Have you been able to run the project locally on a real device?

**Comment by suhailbilalw** [comment] 2024-11-27 01:13
Hello @paulperez-dev,
Could happen because several files in the project are manually modified and app branch is the main branch. But if you will create a new fresh project, I'm sure facebook login will not work on android. flutter_facebook_auth library author has mentioned the issue in his documentation, saying it needs additional configuration. Please go through the documentation once as well.

**Comment by suhailbilalw** [comment] 2024-11-27 09:18
`E/flutter (20858): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method login on channel app.meedu/flutter_facebook_auth)`
`E/flutter (20858): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332)`
`E/flutter (20858): <asynchronous suspension>`
`E/flutter (20858): #1      FacebookAuthPlatformImplementation.login (package:flutter_facebook_auth_platform_interface/src/facebook_auth_implementation.dart:35)`
`E/flutter (20858): <asynchronous suspension>`
`E/flutter (20858): #2      facebookSignIn (package:project/auth/firebase_auth/facebook_auth.dart:20)`
`E/flutter (20858): <asynchronous suspension>`
`E/flutter (20858): #3      FirebaseAuthManager._signInOrCreateAccount (package:project/auth/firebase_auth/firebase_auth_manager.dart:311)`
`E/flutter (20858): <asynchronous suspension>`

**Comment by suhailbilalw** [comment] 2024-11-27 09:55
@paulperez-dev
Right now flutterflow is only including "facebook_app_id" in strings.xml but according to what documentation tells flutterflow should add second string "facebook_client_token" as well.
That fixes the issue probably.

**Comment by suhailbilalw** [comment] 2024-11-28 04:22
Hello @paulperez-dev,
Could happen because several files in the project are manually modified. But if you will create a new fresh project, I'm sure facebook login will not work on android. flutter_facebook_auth library author has mentioned the issue in his documentation, saying it needs additional configuration. Please go through the documentation once as well.

**Comment by paulperez-dev** [comment] 2024-11-29 02:25
Hi @suhailbilalw,

Thanks for the information. I'm looking into this.

**Comment by paulperez-dev** [comment] 2024-12-03 02:19
Hi @suhailbilalw,

After reviewing this issue, I noticed it is a duplicate of #4694. I’ll go ahead and close this as a duplicate. Please refer to that issue for any updates.

**Closed as not planned** 2024-12-03 02:20 UTC
Labels: status: needs triage, waiting for user response
