### ISSUE TITLE
flutter_flow_icon_button.dart: No name parameter 'iconColor'

### ISSUE THREAD

**Issue by anthonygoslar** [FlutterFlow/flutterflow-issues#773] opened 2023-04-17 17:55 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When building my app using flutter build ipa, the following error is thrown: 

1 warning generated.
    lib/flutter_flow/flutter_flow_icon_button.dart:91:7: Error: No named parameter with the name 'iconColor'.
          iconColor: MaterialStateProperty.resolveWith<Color?>(
          ^^^^^^^^^
    ../../development/flutter/packages/flutter/lib/src/material/button_style.dart:123:9: Context: Found this candidate, but the arguments don't match.
      const ButtonStyle({
            ^^^^^^^^^^^

This issue is fixed by commenting out lines 91-103 in the following code in flutter_flow_icon_button.dart:

### Expected Behavior

The app to build without the error

### Steps to Reproduce

When building my app using flutter build ipa, the following error is thrown: 

1 warning generated.
    lib/flutter_flow/flutter_flow_icon_button.dart:91:7: Error: No named parameter with the name 'iconColor'.
          iconColor: MaterialStateProperty.resolveWith<Color?>(
          ^^^^^^^^^
    ../../development/flutter/packages/flutter/lib/src/material/button_style.dart:123:9: Context: Found this candidate, but the arguments don't match.
      const ButtonStyle({
            ^^^^^^^^^^^

This issue is fixed by 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

It's in Android Studio

### Context

I can't build the app in Android Studio.

### Visual documentation

![image](https://user-images.githubusercontent.com/30745006/232569161-ccd5ce36-cf69-4216-add1-c9ac59c40990.png)

### Environment

```markdown
I am building the app in Android Studio on macOS Ventura 13.3.1
```

**Comment by kjoyceee** [comment] 2023-04-18 03:30
Hi, I had this exact issue. Flutter is out of date and needs to be updated. Run 'flutter upgrade' in android studios terminal.

**Comment by kjoyceee** [comment] 2023-04-18 03:32
https://github.com/FlutterFlow/flutterflow-issues/issues/710

**Comment by wenkaifan0720** [comment] 2023-04-26 01:03
Hi @anthonygoslar. As @kjoyceee has said, you'll need to update your Flutter version on your local machine. Flutterflow shows the Flutter version we currently depends on in the top nav bar. It is generally a good idea to be in sync with that version.

Since it is not a bug, we will close this issue. Thank you.

**Closed by wenkaifan0720** 2023-04-26 01:03 UTC
Labels: closed: not a bug, status: not a bug

**Comment by BrainCoreLab** [comment] 2023-04-28 11:14
Hello @anthonygoslar we have same problem...

Running "flutter pub get" in vmcapp...                           2,347ms
Launching lib/main.dart on Chrome in release mode...
Target dart2js failed: Exception: Warning: The 'dart2js' entrypoint script is deprecated, please use 'dart
compile js' instead.
lib/flutter_flow/flutter_flow_icon_button.dart:91:7:
Error: No named parameter with the name 'iconColor'.
      iconColor: MaterialStateProperty.resolveWith<Color?>(
      ^^^^^^^^^
../snap/flutter/common/flutter/packages/flutter/lib/src/material/button_style.dart:123:9:
Info: Found this candidate, but the arguments don't match.
  const ButtonStyle({
        ^^^^^^^^^^^
Error: Compilation failed.



A week from now since the update was made, it won't let me run. My application runs on the web. Any new solution?

**Comment by wenkaifan0720** [comment] 2023-04-28 13:34
Hi @BrainCoreLab, @anthonygoslar. I assume that you are compiling the app in your own machine, right? Could you check what your Flutter version is? Does the error goes away after you run 'flutter upgrade' in the terminal?
