### ISSUE TITLE
Problem with Bottom Sheet 

### ISSUE THREAD

**Issue by BRSVNukrit** [FlutterFlow/flutterflow-issues#2005] opened 2023-12-14 08:17 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

My request in Query Collection don`t display in Bottom Sheet 
![Bug report don`t screen](https://github.com/FlutterFlow/flutterflow-issues/assets/152473052/7ca77fe8-6bae-4bd5-b11f-b8175701ca92)

### Expected Behavior

I think, what my request in Query Collection will screen in Bottom Sheet.   

### Steps to Reproduce

![FireStore Settings 2](https://github.com/FlutterFlow/flutterflow-issues/assets/152473052/6968fcbc-8233-4389-861a-291c81243d9f)
I added container, ListView in Bottom Sheet. In ListView I added Query Collection with my Collection "Cars" in FireBase. 

I added text in List View. And in text dispayed field "Mark" from my collection "Cars". (Set from Variable ---- cars Document --- Mark). But these fields don`t display. I recieved empty Bottom Sheet. 

I tried to display my field "Mark" how List of Item, adding instead Container a Column. 

Bug report code of ListView:  IT4CysmB3ItIvttZ7q6JbsBv9SEvJkR/RY0ritVuRUw3N5PMCpkqdcnQXFJWUuG0YAh+P2C0rH01zNHemvD1GvpfGy6VGrZY+MxTEDriLUCmabqvDpeSQ25/DfxUGEii3JiV3B4nFM9hLU4A70+QN9y9dBbbO4TENTE3Beb/KZCK2SrDX1iXc2URm05KZDPz

Bug report code of Text:
IT4CysmB3ItIvttZ7q6JbsBv9SEvJkR/RY0ritVuRUw3N5PQCJkQO8nQPxJVOM/jSmxUMFmMp14zzN7sivDhL/krEy6ef7p4/5F6WwzzTT6uWr2TF7uCWnZBO8JRfkic57aZhx15Iu11V1I71E2AHtm/cCnbNKX4Pmo4Sq/LZO4=

![List View](https://github.com/FlutterFlow/flutterflow-issues/assets/152473052/aaef9b85-0b3d-4d6d-a6b7-24e6c16d6ee4)
![Test don`t display](https://github.com/FlutterFlow/flutterflow-issues/assets/152473052/db4dc4f0-0717-4e29-8370-db99b5565beb)
![Collection FireBase in FlutterFlow](https://github.com/FlutterFlow/flutterflow-issues/assets/152473052/a072f470-8f47-4790-9d1c-9187b41dff82)
![Collection FireBase Cars](https://github.com/FlutterFlow/flutterflow-issues/assets/152473052/f9b156f0-b6c8-4a0d-9aea-4323255fa8f6)
![FireSrore Settings 1](https://github.com/FlutterFlow/flutterflow-issues/assets/152473052/b6e5c3f8-b381-46c4-b22d-12686623c83a)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4CysmB3ItIvttZ7q6JbsBv9SEvJkR/RY0ritVuRUw3N5PQCJkQO8nQPxJVOM/jSmxUMFmMp14zzN7sivDhL/krEy6ef7p4/5F6WwzzTT6uWr2TF7uCWnZBO8JRfkic57aZhx15Iu11V1I71E2AHtm/cCnbNKX4Pmo4Sq/LZO4=

### Context

I want to display my request of field "Mark" in widget "Text" 
![what i want](https://github.com/FlutterFlow/flutterflow-issues/assets/152473052/3d96dfb2-885b-445d-a50f-28d2a9ceaa50) 

### Visual documentation

![List View](https://github.com/FlutterFlow/flutterflow-issues/assets/152473052/aaef9b85-0b3d-4d6d-a6b7-24e6c16d6ee4)
![Test don`t display](https://github.com/FlutterFlow/flutterflow-issues/assets/152473052/db4dc4f0-0717-4e29-8370-db99b5565beb)
![Collection FireBase in FlutterFlow](https://github.com/FlutterFlow/flutterflow-issues/assets/152473052/a072f470-8f47-4790-9d1c-9187b41dff82)
![Collection FireBase Cars](https://github.com/FlutterFlow/flutterflow-issues/assets/152473052/f9b156f0-b6c8-4a0d-9aea-4323255fa8f6)
![FireSrore Settings 1](https://github.com/FlutterFlow/flutterflow-issues/assets/152473052/b6e5c3f8-b381-46c4-b22d-12686623c83a)

### Additional Info

Project name: secondCourcefromIgnatEgorov
Project ID: you-tube-project-uadgx7

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.0 released December 12, 2023
Flutter version is 3.13.7
- Platform: web
- Browser name and version: Yandex Brauser 23.11.1.732 (64-bit)
- Operating system and version affected: Windows 10 Pro 1709
```

**Comment by hariprasadms** [comment] 2023-12-15 13:59
Hi, Thanks for submitting the issue. What error you see in browser console while loading query through bottom sheet ?. All these details please.

**Comment by hariprasadms** [comment] 2023-12-15 15:43
Hi @BRSVNukrit - I have verified firestore queries in bottom sheet. I can confirm that, It is working as intended.

**Comment by katherineqian** [comment] 2023-12-15 22:09
Thank you Hari! I will close this issue as project-specific for now. 

This issue tracker is intended for general bugs that are applicable to all users. Because this error appears to be specific to your project and the steps are not reproducible, this is classified as a support request and will be closed. Please use chat support or contact support [at] [flutterflow.io](http://flutterflow.io/).

**Closed by katherineqian** 2023-12-15 22:09 UTC
Labels: closed: not a bug, Firestore, Firestore query action

**Comment by BRSVNukrit** [comment] 2023-12-17 08:44
> Добавление или удаление реакций

Thank you for help, Hari! The same problem remains. Text in Bottom Sheet don`t dislay. May be I have old version of Browser? And if request from FireBase is correct, why text don`t display? I would be very grateful, if you help solve this problem. 
![dont display](https://github.com/FlutterFlow/flutterflow-issues/assets/152473052/0f259472-e86f-45a2-9717-5d662b2d9f79)
