### ISSUE TITLE
DataTable: Changing number of columns is broken

### ISSUE THREAD

**Issue by ametaplus** [FlutterFlow/flutterflow-issues#4016] opened 2024-10-09 13:54 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When changing the number of columns in a DataTable from e. g. "8" to "10" it deletes everything except the first column right after typing "1" if in reality I want to type "10".
Also typing in values like "9100" is possible, which of course breaks FF.

### Expected Behavior

I expect it to work like it did before - the field should wait until I'm ready with typing.

### Steps to Reproduce

1. Create new page
2. Add a DataTable
3. Set it to 8 columns
4. Put content into the columns
5. Try to change the amount of columns to 10

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5Xl8nl3891pbxH1rXuY+9VijsXJmY6RY0/iu1Edws1GLbpBLAHdsnuT0BZTcO8T2w7IWeJnmAC096PheL1CvoCKRGXGdk5+s9QETvNTj+zaq2bBbiKXkFTGfJWBW6jy6uJvB0mPrFYWk4bw0itLO+ASjDDQZy3PGovG/mJDJ3IkWCfFSXjViwz0TI4RBq1PvVvURGByM+UtpJh0eDnyw==

### Visual documentation

![Screenshot 2024-10-09 155158](https://github.com/user-attachments/assets/d47f5f67-65e5-4e73-af68-52222ef4ddd8)
![Screenshot 2024-10-09 155231](https://github.com/user-attachments/assets/6e2a4716-54dd-46bf-8954-84e68075a408)

### Environment

```markdown
- FlutterFlow version: 5.0.2+ 1st october 2024
- Platform: Windows
- Browser name and version: -
- Operating system and version affected: Windows 11
```

**Comment by Alezanello** [comment] 2024-10-09 14:13
Hello!

First, thank you for reaching out to us with this issue.

I was able to replicate the behavior you described. However, it's not a bug but rather the way the data table handles column changes. When you increase the number of columns from, say, 7 to 10, the process involves changing the column count from 7 to 1 first, and then to 10.

This sequence means that the data table initially interprets the input as a request for 1 column, removing the others, and then it adds columns to reach the total of 10. This behavior occurs with any change where the new number of columns is lower than the current number.

For example, if you have 6 columns and change it to 17 by first entering 1, then 7, the table will temporarily drop to 1 column before adding the additional 16, effectively removing the previous columns.

This is more about the inherent behavior of the data table rather than a hard reset.

I'm going to send this for a double check to engineering to see if it is an expected behavior or something that could be improved. Thank you very much for your time.

Best regards,<br>​Azanello

**Comment by TimothyWCTI** [comment] 2024-10-15 11:00
Hello

I'm chiming in to say I would also find issue with the current behavior deleting columns when attempting to add more.
I would grow frustrated needing to have to copy/paste in any value with more than a single digit to prevent work loss.

If this is indeed the expected behavior, I'd like to request that it be more in line with ametaplus' expectation of waiting for the typing to be complete before updating the amount of columns.

**Comment by ametaplus** [comment] 2024-10-15 11:37
That is definitely a new behaviour - I don't know since which version, but it worked already as expected (not deleting columns).

**Comment by Alezanello** [comment] 2024-10-15 12:56
This is currently the expected behavior. We’ve responded to a similar issue in this post: [GitHub Issue #3294](https://github.com/FlutterFlow/flutterflow-issues/issues/3294), explaining the same.

I didn’t close this issue as a duplicate due to the time difference between the two reports, and to allow other users who might think it's a bug to see it in the tracker for a while. However, this has already been reviewed by the engineering team.

Thank you for your understanding!

**Closed as not planned** 2024-10-15 12:57 UTC
Labels: closed: duplicate
