### ISSUE TITLE
Android App Icon with Circle Shape Not Getting Filled

### ISSUE THREAD

**Issue by Fibn007** [FlutterFlow/flutterflow-issues#1260] opened 2023-08-14 04:27 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Whenever I deploy an app to Android, the app icon (specifically the android app icon with the circle shape) does not take up the full space. It works on IOS and works on other Android app icon shapes. It only does not work on the circle shape. I submitted this via a support chat, but there has been no action on it. Resubmitting here. Pictured below:

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/43394475/81b5a09f-84f8-4934-ba89-7dcd34bbb1cb)

This is the image I'm deploying to the app launcher:

![App_Logo_Square](https://github.com/FlutterFlow/flutterflow-issues/assets/43394475/db097245-34a4-411e-856b-330fd4df842f)

### Expected Behavior

The entire circle should take the shape of the image. There should not be white space. 

### Steps to Reproduce

1. Create an app icon 
2. Submit the app icon to the launcher icon container
3. Either download the apk or deploy to the google store
4. View the app icon on a phone

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48kvLlw4tNrsdG+KXydcFFmjgWQ187aLsVi+5tTUs8KOPdOoYUP8+kM0RuUtCodwl2PmajhWoW0+znj/LxKO1dBEyaRaI7wqtIQwrJXk+nR66uFJWge3ZRM+5RCW6Yy7SJpB1+GMt1SGwb61yyDPO9QgTbJ4CzDFgsDq/LZO4=

### Context

When customers view the app icon, they don't think it looks legitimate since it doesn't match what's in the google play store. There's certainly a credibility issue with this problem.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/43394475/46741ab0-2caa-4402-84a4-53a189eb6971)

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: Windows Desktop App
- Browser name and version: Version 115.0.5790.171
- Operating system and version affected: Pixel 7, Android 13
```

**Comment by kevintonb** [comment] 2023-08-17 07:04
Hey @Fibn007 , thank you for reaching out to us. Flutterflow uses 'flutter_launcher_icons' package to generate app icons for your project. And in the default mode any icon that you use is generated as an app icon with a white space around them, so it is better to use a transparent icon. But if you would like to have a blue background with your icon I would suggest using the adaptive icon configuration to do the same. You can find documentation on how you can create an adaptive icon with a different background and foreground over here : https://pub.dev/packages/flutter_launcher_icons. Since this isn't a reproducible bug on the Flutterflow platform as such, I am closing this issue now. Please feel free to reach out to our support team at support@flutterflow.io if you need additional information :)

**Closed by kevintonb** 2023-08-17 07:04 UTC
Labels: status: needs triage

**Comment by Fibn007** [comment] 2023-08-17 19:24
Hi @kevintonb , thank you for the feedback. I understand how to fix the issue. But there is no way to upload this from FlutterFlow which is the issue that you also recognized. I'm paying for the "One Click Deployment" package using CodeMagic and I'd expect this to be part of the package. Without this feature in FF, I will have to reduce the paid version I use if I'll have to manually update this myself outside of FF.  I understand it currently isn't offered, but I'd like to argue that it definitely should be. Thank you!

**Comment by wemmick** [comment] 2023-11-10 05:13
Count me in, too. One-click submission should be just that. I'm happy to submit a round icon to make it work if that helps (this works on SAP AppGyver), but when I tried that on FF it didn't work at all. @kevintonb If you guys are just going to close issues that aren't technically broken per their original spec (whenever that was created), might I suggest a separate queue for feature requests?

**Comment by alta-atc** [comment] 2023-11-14 20:10
I am encountering the same issue. It is dissapointing that "one click deployment" is effectively broken for android without an in-app flutterflow fix for this.

**Comment by mike23333** [comment] 2023-11-27 20:41
I'm having the same issue. app icon is much smaller than all other icons. Just finished building my app too ready to launch. Now have to export and add app icon manually for each update. Crazy this is not supported. One click deployment is pointless to get now.

**Comment by mixart** [comment] 2024-01-19 16:21
Just came across this issue deploying my app. Worst case there is no documentation in flutterflow that says "if you deploy to Android your icon will look wrong and here is how you fix it". How can FF boast having millions of users and nobody has deployed to Android directly from FF.

**Comment by tadamtech** [comment] 2024-01-25 14:56
Same issue here, it would be very nice to have the ability to upload an icon for Google Play

**Comment by max-h-silverman** [comment] 2024-01-28 21:59
Ditto everything said here. This is not really an acceptable response from the FlutterFlow team. @Fibn007 can you please follow up on this?

**Comment by iGrits** [comment] 2024-02-25 22:18
I 10th this should be a feature.

**Comment by remodelai** [comment] 2024-04-04 04:24
+1 for this issue to be solved!

**Comment by Fibn007** [comment] 2024-04-26 21:08
👀 Thanks for the implementation!

**Comment by alta-atc** [comment] 2024-04-26 22:55
@Fibn007 was this resolved?

**Comment by Fibn007** [comment] 2024-04-26 23:07
@alta-atc Yes! Latest release fixes the issue. Just add a new icon under the "App Assets" -> "Android Adaptive Icon" page!

**Comment by mfatihy70** [comment] 2024-06-04 13:47
flutter_launcher_icons just f.ing wasted my 3 hours. I did it with Android Studio Asset Configurator.
