### ISSUE TITLE
Lib component "name" in consuming project is lost 

### ISSUE THREAD

**Issue by budikeohet01** [FlutterFlow/flutterflow-issues#4532] opened 2024-10-23 09:05 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When we use a lib-component in a project, we usually change its name, but on renaming the widget the original name is changed too, so we dont know anymore what is the original lib widget.
![image](https://github.com/user-attachments/assets/b66722ed-897e-4084-8f08-eb8544a693c2)

### Expected Behavior

The name of the original component (the name in the link) must be the original lib component name.
The link should redirect to the existing lib component (of the lib version that is currently used).

### Steps to Reproduce

create a lib, add a "libComp" component, publish
create project, import the lib
add the "libComp" to home page
change its name to "libComp1"
you can see the original name change, and the link doesnt work correctly.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48z8+A5ZV2pbxa1s+Jbu9ajikXQ2U7RoERk+1TRRQ8J5DaPOxzP/TBaldWUs+0TQhIO02GoGM0psHemvzLA/c5C0+dRoA7zs8JUxaVeEKhWoy3O6iSVG5/AtxTI1Sg18GRgyVCVfBvLHtg6jiAJfK/Sg7XGYzUCzM/B86LKZCK2SrDX1iXc2URm05KZDPz

### Visual documentation

IT48z8+A5ZV2pbxa1s+Jbu9ajikXQ2U7RoERk+1TRRQ8J5DaPOxzP/TBaldWUs+0TQhIO02GoGM0psHemvzLA/c5C0+dRoA7zs8JUxaVeEKhWoy3O6iSVG5/AtxTI1Sg18GRgyVCVfBvLHtg6jiAJfK/Sg7XGYzUCzM/B86LKZCK2SrDX1iXc2URm05KZDPz

Lib bug code:
IT4wz8+A5ZV2pbxa1s+Jbu9VtCAsGDt6UK8a1uwbFSs8JJToPLAUZ8zBM05vZry5TH9DemKGinMK/Pfqkd7PL8dfCwWsGdVjwZZiSznMJX+VR7aTEquVfW1TN+hnIXK+5J6vnSUnGNJedXxn7UyPe+6vTi7AH4CxDG0ZQ+alLdeK2SrDX1iXc2URm05KZDPz

### Environment

```markdown
- FlutterFlow version: 5.0.2+
- Platform: web
- Browser name and version: Chrome Versión 129.0.6668.90
- Operating system and version affected: win 11
```

**Comment by paulperez-dev** [comment] 2024-10-23 11:26
Hi @budikeohet01,

This issue was previously reported and marked as resolved in the version released yesterday. Could you please confirm which version you're experiencing this issue with?

Thank you!

**Comment by Alezanello** [comment] 2024-10-23 16:30
Hello!

This issue is a duplicate of the following ticket: [Issue #3995](https://github.com/FlutterFlow/flutterflow-issues/issues/3995). To streamline our efforts, we're centralizing all updates in that ticket, so I’ll be closing this one as a duplicate.

Thank you for your understanding!

**Closed by Alezanello** 2024-10-23 16:30 UTC
Labels: status: needs triage
