### ISSUE TITLE
Create Design Library button missing

### ISSUE THREAD

**Issue by lantolus** [FlutterFlow/flutterflow-issues#3742] opened 2024-09-04 15:05 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When on Design System page, Create Design Library button is not there

### Expected Behavior

Button Create Design Library should be visible on the top of the page

### Steps to Reproduce

Go to Theme Setting -> Design Systems. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTiPLqx4VOoctF+Kr9K+5F9TgXM0MCXLhE0dcbRkgYfLKtOpkiZur+VGFvZOGnf1VYMVClkToGwN78veDpGvY6aU2rUoNo+pNyVDzjUlKVM66ROrjpZnF8O8FhFWKH54mNoSZdNrRfSk4Sw2z/cq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

![Screenshot 2024-09-04 165138](https://github.com/user-attachments/assets/64a3e32c-79ab-42a4-afa0-7d7c5684f937)

### Environment

```markdown
- FlutterFlow version: v4.1.85+
- Platform: Web
- Browser name and version: Google Chrome 128.0.6613.114 | Microsoft Edge 128.0.2739.54
- Operating system and version affected: Windows 11
```

**Comment by Alezanello** [comment] 2024-09-04 16:00
Hi there!

It’s unusual that it’s not showing up on your end. Could you try refreshing the page or clearing your cache?

I created a new blank project, and everything displayed correctly. When I accessed your project, everything appeared fine as well. Have you tried opening it in a different browser to see if that resolves the issue?

Let me know how it goes!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/34122db4-b414-444b-a122-4fa7a4776ca8/d7d26d7e-5cf8-4e43-884a-5c45e1e63d2e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zNDEyMmRiNC1iNDE0LTQ0NGItYTEyMi00ZmE3YTQ3NzZjYTgvZDdkMjZkN2UtNWNmOC00ZTQzLTg4NGEtNWM0NWUxZTYzZDJlIiwiaWF0IjoxNzI1NDY1NjE5LCJleHAiOjMzMjk2MDI1NjE5fQ.VNGpG__Ar1YQcCaN8DsjRIgfjBNKfX85CSth3dDVP9o " alt="image.png" width="1698" height="504" />

**Comment by lantolus** [comment] 2024-09-04 16:15
I tried opening it in Chrome and Edge browsers, cleared the cache, refreshed the page, I also downloaded desktop app for Windows and it still doesn't appear. When I create new project it still doesn't show up. 
Now I tried to download Firefox to have fresh new browser but didn't help. 
I even tried different devices and button is not there. I have no idea what's the problem here.

**Comment by Alezanello** [comment] 2024-09-18 22:15
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by lantolus** [comment] 2024-09-19 20:00
Hello, 

unfortunately the issue still persist. I just updated FlutterFlow destkop app to version v4.1.89+ and I am on the same version on browser app.

**Comment by Alezanello** [comment] 2024-09-30 14:25
Hello again and sorry for the late response.<br>I was not able to reproduce this on a blank project, but it is replicable on yours. That's why I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: support@flutterflow.io or using the in-app chat inside of FlutterFlow. <br><br>I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. <br><br>If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. <br><br>Thanks so much!

**Closed as not planned by Alezanello** 2024-09-30 14:25 UTC
Labels: status: can't reproduce
