### ISSUE TITLE
Unable to download AAB or APK file, even for first deployment- It does not download- Link error

### ISSUE THREAD

**Issue by SiraEnterprises** [FlutterFlow/flutterflow-issues#434] opened 2023-02-01 23:26 UTC
{"error":"FORBIDDEN","message":"The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required."}

**Comment by bulgariamitko** [comment] 2023-02-02 07:53
In order to keep our issue tracker useful and maintainable for all users, please follow the bug report template while reporting bugs. We will be happy to re-assess when the necessary information is provided.
 
 Thank you!

**Comment by bulgariamitko** [comment] 2023-02-02 07:53
This issue tracker is intended for general bugs that are applicable to all users. Because this error appears to be specific to your project and the steps are not reproducible, this is classified as a support request and will be closed. Please use chat support or contact support [at] flutterflow.io for further assistance.
 
 If you do find a specific reason for the issues you are encountering in your project, please don’t hesitate to open a new bug report with the relevant steps to reproduce.
 
 Thank you for your contribution!

**Comment by hariprasadms** [comment] 2023-02-10 14:21
Hi, As per last comment details, looks like this issue is not re-produceable and in general it is working fine, we can close the issue.

**Closed by hariprasadms** 2023-02-10 14:21 UTC
Labels: status: not a bug
