### ISSUE TITLE
Web bug: Media upload action doesn't work more than once

### ISSUE THREAD

**Issue by ayuno** [FlutterFlow/flutterflow-issues#824] opened 2023-04-28 22:15 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a button with an "Upload media to Firebase" action. When I click it, the file upload window comes up as expected. But when the operation is cancelled without uploading anything, the button remains unresponsive (showing a loading widget) until the page is refreshed.

I have noticed the issue in two of my apps - one of them is released to mobile and I am not experiencing the issue on Android/iOS, but the issue is present in Test/Run mode. My other app is only published to the web, and the issue is very much present.

### Expected Behavior

I would expect that the user can cancel the file upload window infinite times and still be able to open it again. 

### Steps to Reproduce

1/ Create new project with Firebase
2/ Add an Upload media to Firebase action
3/ Run the project in Test/Run mode and test the above

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Wlcr1z89goe5E176JKe9ajikXQzs4bZIrm8N+RREYNZT2PJwPW/7BSFRuYc/jSnNcP2Gi8TsKpvONhd7tEvoHPiiqY6pcwZFqbz3JeDu5bq6mPrq3PnR9GeNmJleHzbenpSZ5ALJ1LXw42ly2AejIF3fbQZv4Dm1MIvqiJr/7o1mpGQzOXn0Jg1ZSfCvr

### Context

I am trying to implement a simple media picker.

### Visual documentation

It is difficult to show something _not_ working.

### Environment

```markdown
- FlutterFlow version: 3.7.12
- Platform: Web
- Browser name and version: Chrome 112.0.5615.138 (latest)
- Operating system and version affected: Windows 11
```

**Comment by hariprasadms** [comment] 2023-04-29 15:09
Hi @ayuno - Thanks for reporting the issue. We know this upload button behaviour is present in web, run and debug mode. It will be fixed in up coming updates. Thanks

**Comment by ayuno** [comment] 2023-04-29 16:46
Hi @hariprasadms! Thanks, great to hear a fix is on the roadmap already. Any chance you could share what’s causing the error? I’ll try to implement a workaround in the meantime and some clues would help me a lot.

**Comment by ouvreboite** [comment] 2023-07-17 11:26
Any update on the fix? The problem is still present at this date.

**Comment by agreaves** [comment] 2023-09-21 05:11
Hi @ayuno and all, thank you for the bug report! We were able to confirm for a while, but it was due to a Flutter bug that has [finally been fixed](https://pub.dev/packages/image_picker_for_web/changelog)! This will now be fixed on our end on our next deploy 🙂

**Closed by agreaves** 2023-09-21 05:11 UTC
Labels: type: bug, status: confirmed
