### ISSUE TITLE
SVG url images render in debug mode, but neither in Run Mode nor on actual deployed Web App

### ISSUE THREAD

**Issue by vitoras** [FlutterFlow/flutterflow-issues#2225] opened 2024-01-23 02:43 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have some SVG files stored under Google Cloud Storage, whose's URLs are stored in a Firestore document.

When setting a Container's background image from network with the URL from the Firestore document, it shows up fine in debug mode, but then it doesn't render at all when it's in run mode and neither on the actual Web App.

I tried using Dev tools with both my web app and debug mode simultaneously, and the only thing I noticed is that, in debug mode, the SVG URL is being fetched with Type "svg+xml", whereas on the web app, the very same URL in the very same page is fetched just as "xhr". I took a screenshot from both Dev Tools splited on the screen to demonstrate this, which I'll attach bellow (left is my web app and right is debug mode):

![Captura de Tela 2024-01-22 às 23 46 58](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/0f8f1b93-5574-40aa-9ac5-6ee87309f471/ef0636b8-d92e-45bb-adac-ef268422e8ed?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wZjhmMWI5My01NTc0LTQwYWEtOWFjNS02ZWU4NzMwOWY0NzEvZWYwNjM2YjgtZDkyZS00NWJiLWFkYWMtZWYyNjg0MjJlOGVkIiwiaWF0IjoxNzA2MDA2MjA5LCJleHAiOjMzMjc2NTY2MjA5fQ.kUHIRn7Q7OdvNzJmVGKeYPfm3tb8K9S-\_GqMd4gy1zw)

### Expected Behavior

SVG files are properly rendered, exactly like in Debug Mode.

### Steps to Reproduce

1. Save SVG in Google Storage
2. Store URL in Firebase document
3. Add container widget and set background image with source as Network, with URL fetching from corresponding URL field from Firestore Document stored on previous step

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTz8rqyItNvttZ+KnTYcdogSgvM0McWOdEl+tuZwgbIoznBuw2feDeVFBuZ9TgaVNcJFG0pFMF/6nwi9jXDPI6KRCVR6pq1ahyEBf0e2iRWq2bEbmCOnBCO/xVGBCP4Z2RpxFAXdZtSFIH12aqIeyQcHHDFOu/Zwh9f6PHaOI=

### Context

It affects user experience as countries flags is not shown on list.

### Visual documentation

Bellow is a side by side comparison of the actual Web App (left) and Debug Mode:

![Captura de Tela 2024-01-22 às 23 40 28](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/932f364f-1988-4020-a3f2-92e355e42ae7/2398a235-946f-4b5a-b932-4e417c30fd6c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85MzJmMzY0Zi0xOTg4LTQwMjAtYTNmMi05MmUzNTVlNDJhZTcvMjM5OGEyMzUtOTQ2Zi00YjVhLWI5MzItNGU0MTdjMzBmZDZjIiwiaWF0IjoxNzA2MDA2MjA5LCJleHAiOjMzMjc2NTY2MjA5fQ.K60y92n5-gXG6pyDUHWfJCTtr4o37jY-FS6XOctKVR0)

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: 4.1.20
- Platform: MacOS Desktop
- Browser name and version: Brave v1.61.120
- Operating system and version affected: macOS Sonoma 14.2.1
```

**Comment by hariprasadms** [comment] 2024-01-23 10:01
Hi @vitoras - What error message you see in browser console tab. Is there a CORS error ? also did you try this with Canvaskit option enabled ? Please confirm these details.

**Comment by vitoras** [comment] 2024-01-23 13:07
> Hi @vitoras - What error message you see in browser console tab. Is there a CORS error ? also did you try this with Canvaskit option enabled ? Please confirm these details. 

Hi @hariprasadms.

Actually, nothing shows in the console. It's like, because the browser loads it with xhr type, it just doesn't see it as an image.

And yes, I did deploy my web app with Canvaskit option enabled.

**Comment by vitoras** [comment] 2024-01-24 01:11
> Please share those SVG files. Compress and attached here if you can please.

Hi there, @hariprasadms.

Here's one of the Firestore link, it's public anyway and maybe it will help more since it's the actual URL that is being fetched: [https://firebasestorage.googleapis.com/v0/b/tiphub-72fce.appspot.com/o/api_logos%2Fflags%2Fbr.svg?alt=media&token=5ec8f1d8-f175-4fcf-ba17-5c7c173cb08b](https://firebasestorage.googleapis.com/v0/b/tiphub-72fce.appspot.com/o/api_logos%2Fflags%2Fbr.svg?alt=media&token=5ec8f1d8-f175-4fcf-ba17-5c7c173cb08b).

Hope that helps.

**Comment by RickAtSavveLabs** [comment] 2024-01-29 15:29
I am experiencing what seems to be the same error. When CanvasKit is not enabled, my Firebase uploaded images render fine. When CanvasKit is enabled, the images stop rendering. I also tried changing the "CORS Proxy for Images" setting from None to "Deploy with Firebase". But this created an error when I tried to publish the web app. 
I was told by FlutterFlow development to turn on CanvasKit to address an issue I was having with RatingBars. But the "fix" now prevents me from displaying uploaded images.

![Screenshot of Safari at Jan 29, 2024 at 10_00_11 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/154351161/7db463ea-8216-4a7f-935c-59bc188d3680)
![Screenshot of Safari at Jan 29, 2024 at 10_02_53 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/154351161/5f00a63d-a406-4ed4-968c-10d85f7d5041)

**Comment by RickAtSavveLabs** [comment] 2024-01-29 18:25
@wenkaifan0720 Can you tell me if I am experiencing the same issue, or if I should submit a separate bug report. Thank you.

**Comment by vitoras** [comment] 2024-01-29 18:32
> Hi @vitoras. FF actually has an error for using svg image for `Container` background. This error is suppressed in your case because the url is dynamic. If you use the `Image` widget in your use case, the image would load for both test & run mode.
> 
> ![iScreen Shoter - Google Chrome - 240130005955](https://github.com/FlutterFlow/flutterflow-issues/assets/112435854/3d96e65a-0c7e-4e72-bb65-28d0b540a916)
> 

Good afternoon, @wenkaifan0720 !

Actually, I am facing the same issue with both container and image widgets.

**Comment by wenkaifan0720** [comment] 2024-01-29 20:05
Could you reproduce this bug with this test project (https://app.flutterflow.io/project/test-8x6xit)? I can see the image loading in both run mode and web publishing.

**Comment by e5aia5** [comment] 2024-02-06 16:13
I'm experiencing the same (or similar) issue. SVG image from the web (https://api.met.no/images/weathericons/svg/partlycloudy_day.svg) shows up in the image widget in debug and preview mode but not in test/run or web publish. This happens with or without CanvasKit and with or without "Deploy with Firebase"

**Comment by vitoras** [comment] 2024-02-12 01:35
> Could you reproduce this bug with this test project (https://app.flutterflow.io/project/test-8x6xit)? I can see the image loading in both run mode and web publishing.

Hi, @wenkaifan0720! Sorry for the late response.

Not only can I not reproduce the bug with the test project, but also the bug disappeared from my actual project, after a new web publish. I think there may have been an update on FF in the meantime that solved the bug.

I appreciate the help, thanks a lot!

**Comment by wenkaifan0720** [comment] 2024-02-12 13:38
Good to know. I'll close this issue now.

**Closed by wenkaifan0720** 2024-02-12 13:38 UTC
Labels: closed: not a bug

**Comment by rossnelson111** [comment] 2024-05-29 08:45
Hi I am having this same issue:

I am storing images as SVGs on firebase and using a URL to display them in my app using an image widget. 

The images show perfectly fine on test mode but do not show on run mode and do not show on Web publish when CanvasKit is enabled. When CanvasKit is disabled they show perfectly fine.
