### ISSUE TITLE
Create account not working properly

### ISSUE THREAD

**Issue by lovestar18** [FlutterFlow/flutterflow-issues#2552] opened 2024-03-19 02:07 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When you try to create an account with an email from the 'createaccount' page, it turns black. It does create the account but it should take you to the application page.

### Expected Behavior

After you press 'createaccount' it takes you to application page

### Steps to Reproduce

1. Go to testing
2. Try to create an account with an email (not Google sign in)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hc/1z4ZPj7xG7pSJasExljw5JmF7bIIZkutRaCgofePtOol3evXsbkptZOLgSmNYMESmmjgHwsLOifOSC/o5PkmVfpxCyapydzvgIHKjUZOBPKW0OWpCEcZMCWam37W3qx1+WdNhWlon2DiEGO/KVnftO5zVImdISq/LZO4=

### Context

It's interrupting one's ability to sign into the app

### Visual documentation

[https://github.com/FlutterFlow/flutterflow-issues/assets/159853566/86f1aa01-1e5e-4a0f-8e46-4671f644e2b4](https://github.com/FlutterFlow/flutterflow-issues/assets/159853566/86f1aa01-1e5e-4a0f-8e46-4671f644e2b4)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: macOS
```

**Comment by lovestar18** [comment] 2024-03-21 12:25
@hariprasadms @takashiff - can you please assist with this one? thank you!

**Comment by lovestar18** [comment] 2024-03-26 02:11
@hariprasadms @takashiff - following up here. thank you

**Comment by lovestar18** [comment] 2024-03-28 00:55
@hariprasadms @takashiff - could you please help with this? thank you

**Comment by leighajarett** [comment] 2024-04-06 11:46
Hi there! Sorry you're dealing with this. We tried to reproduce but weren't able to do so. Can you please provide the steps to reproduce from a blank project? Not from your project specifically. 

If you need help troubleshooting your own project configurations then please reach out to support@flutterflow.io. This issue tracker is meant to house reproducible bugs 🙂

**Comment by lovestar18** [comment] 2024-04-06 17:07
Hi @leighajarett - thank you for getting back to me. I've since resolved this since the case was created. However, I'm not able to push my app live to the app store and am seeing the error below - could you please advise on this? thank you!

Codemagic Deploy Output
Failed Step: Publishing

== Gathering artifacts ==

== Publishing artifacts ==

Publishing artifact starlove.ipa
Publishing artifact App.framework.dSYM.zip
Publishing artifact ImageNotification.appex.dSYM.zip
Publishing artifact Runner.app.dSYM.zip
Publishing starlove.ipa to App Store Connect
> app-store-connect publish --path /Users/builder/clone/build/ios/ipa/starlove.ipa --key-id @env:APP_STORE_CONNECT_KEY_IDENTIFIER --issuer-id @env:APP_STORE_CONNECT_ISSUER_ID --private-key @env:APP_STORE_CONNECT_PRIVATE_KEY
/Users/builder/.pyenv/versions/3.8.13/lib/python3.8/site-packages/codemagic/models/certificate.py:123: CryptographyDeprecationWarning: Properties that return a naïve datetime object have been deprecated. Please switch to not_valid_after_utc.
  return self.certificate.not_valid_after.replace(tzinfo=timezone.utc)

Publish "/Users/builder/clone/build/ios/ipa/starlove.ipa" to App Store Connect
App name: Star Love
Bundle identifier: com.mycompany.starsoflove
Certificate expires: 2025-02-19T04:37:18.000+0000
Distribution type: App Store
Min os version: 13.0
Provisioned devices: N/A
Provisions all devices: No
Supported platforms: iPhoneOS
Version code: 15
Version: 1.1.4

Upload "/Users/builder/clone/build/ios/ipa/starlove.ipa" to App Store Connect
{
    "tool-version": "7.006.15006",
    "tool-path": "/Applications/Xcode-15.2.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Versions/A/Frameworks/AppStoreService.framework",
    "os-version": "14.2.1",
    "product-errors": [
        {
            "message": "The provided entity includes an attribute with a value that has already been used",
            "userInfo": {
                "NSUnderlyingError": "Error Domain=IrisAPI Code=-19241 \"The provided entity includes an attribute with a value that has already been used\" UserInfo={status=409, detail=The bundle version must be higher than the previously uploaded version., source={\n    pointer = \"/data/attributes/cfBundleVersion\";\n}, id=e709eb0d-cdeb-4190-bbe5-3906086328f0, code=ENTITY_ERROR.ATTRIBUTE.INVALID.DUPLICATE, title=The provided entity includes an attribute with a value that has already been used, meta={\n    previousBundleVersion = 15;\n}, NSLocalizedDescription=The provided entity includes an attribute with a value that has already been used, NSLocalizedFailureReason=The bundle version must be higher than the previously uploaded version.}",
                "NSLocalizedDescription": "The provided entity includes an attribute with a value that has already been used",
                "previousBundleVersion": "15",
                "iris-code": "ENTITY_ERROR.ATTRIBUTE.INVALID.DUPLICATE",
                "NSLocalizedFailureReason": "The bundle version must be higher than the previously uploaded version: \u201815\u2019. (ID: e709eb0d-cdeb-4190-bbe5-3906086328f0)"
            },
            "code": -19232
        }
    ]
}
Failed to upload archive at "/Users/builder/clone/build/ios/ipa/starlove.ipa"
Failed to publish /Users/builder/clone/build/ios/ipa/starlove.ipa

Failed to publish starlove.ipa to App Store Connect.

Build failed :|


Publishing failed :|
Failed to publish starlove.ipa to App Store Connect.

**Comment by rzambroni** [comment] 2024-04-06 21:02
Hey @lovestar18,

We're very glad to hear that you were able to resolve the initial problem.

Regarding the new issue you're encountering, it appears that the Build Number/Version Code wasn't incremented, leading to the publishing issue. You can try manually incrementing it in the FlutterFlow Mobile Deployment options. (16 might be the number you need, but without the full context of your project's configuration, I can't confirm.)

Since the original problem has been resolved, I'll close this issue for now. If you continue to experience difficulties with publishing, please don't hesitate to open a new issue or reach out to our support team at [support@flutterflow.io](mailto:support@flutterflow.io). They'll be more than happy to assist you further.

Thanks a lot!

**Closed** 2024-04-06 21:03 UTC
Labels: closed: not a bug

**Comment by lovestar18** [comment] 2024-04-09 11:16
Thank you @leighajarett and @rzambroni !

On a separate ticket, I asked about some of the crashes I've been running into. Is there any chance you could look into these and help me resolve them? Thank you!

<img width="625" alt="Screenshot 2024-04-09 at 7 14 47 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/159853566/b7f727cf-092f-4263-9b5c-e60eac738b97">

**Comment by leighajarett** [comment] 2024-04-09 11:29
Can you please send us a link to that ticket?

**Comment by lovestar18** [comment] 2024-04-09 11:38
@leighajarett - please see here: https://github.com/FlutterFlow/flutterflow-issues/issues/2529

thank you!

**Comment by leighajarett** [comment] 2024-04-09 11:40
Hi there! As mentioned in that issue, we were not able to recreate the problem on our side so the best path is to talk to our support team because they can help troubleshoot configurations and such. Did you reach out to them?
