### ISSUE TITLE
Validating the textfield

### ISSUE THREAD

**Issue by TanuJain2002** [FlutterFlow/flutterflow-issues#746] opened 2023-04-10 02:17 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have 2 textfields for inputing Name.
TextfieldName 1 do not allow space bewween text.
TextfieldName2 allows space but also accepts numbers

### Expected Behavior

I want to create textfield that accepts name i.e String hence I set filter to English letter in textfieldName1 but this do not allows space.
When I remove filter of English letters from textfieldName2,it allows space as well as nummbers to be entered.
I want to a textfiled that accepts first Name Middle Name LAst Name from user.English Letter filter should allow space also

### Steps to Reproduce

Drag a  form widget on screen 
Add 2 textfields
Set keyboard type of TextfieldName1 to Text and Filter properties to ENGLISH LETTERS
Set keyboard type of TextfieldName2 to Text.
Run

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code

ITESzMjfz4hgruVK1arXYMBAhQMjNlx7bZAnktV+WRMhNZ+qO4YEPvf7M0tLYtSoYFdAO2aiglsy/+jzvuzDL/Y4aUycb705+ZRXQRbLTkGnbpCRCc3oP2glEcRYGkya4Z+vkBInD/VvdEYD206If/CrG3qCf9qOYwx5e6fDbOY=

### Context

The form I want to create will not function properly

### Visual documentation

![textName2](https://user-images.githubusercontent.com/111673705/230811229-99283edf-a2f0-4d6c-85e1-3b09d5bd20b0.PNG)
![filterEnglishletter](https://user-images.githubusercontent.com/111673705/230811246-7c7a53ca-a1b1-47d0-a34f-d52fdc63f0c7.PNG)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform:Mobile
- Browser name and version: Chrome
- Operating system and version : Windows
```

**Comment by shelpert** [comment] 2023-05-10 01:42
Hello,

This is not a bug, it is working as expected so I am going to close it. If you want to include whitespace in your filter, you can use the 'Custom Regexp' option and enter `[a-zA-Z\s]` in the 'Custom Filter' section. Here is a good [resource](https://regexr.com) for writing a regexp to use as a filter.

**Closed by shelpert** 2023-05-10 01:42 UTC
Labels: closed: not a bug
