### ISSUE TITLE
LottieAnimation widget stopped seeing uploaded assets

### ISSUE THREAD

**Issue by azzar227** [FlutterFlow/flutterflow-issues#5088] opened 2024-12-12 08:06 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When 'asset' is selected as a source, all Lottie widgets present the button to upload a file but not the file selector. Even though many lottie json are uploaded as project assets. Clicking on the upload button has no effect.

![Screenshot 2024-12-12 at 8 58 50 AM](https://github.com/user-attachments/assets/390cf005-1980-48ee-ade1-b5dd92c444b4)
![Screenshot 2024-12-12 at 8 58 38 AM](https://github.com/user-attachments/assets/488ab78d-b33d-4746-b364-95b4eedfe93c)

### Expected Behavior

When 'asset' is selected as a source, all Lottie widgets present the selector to chose a json among the ones uploaded as project assets

Until yesterday, this was working great across many LottieAnimation widgets

### Steps to Reproduce

1. create page
2. add lottie widget
3. upload lottie json as project asset
4. select asset as the source of the lottie widget

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4klcr134VPj7xZ7aXxbccxlScXJnI2TL0Vr+0ac0gYGIzcPLMqe/TOVFJuOLC0YX9UIlmJgnkJp8nemvzhJcBeEEibRpw5/pBQFzrJZEyRWp/WOqWwXm5/DeZRGFzH17uFrxB4WehvL04s7TiUf+TLYCnXJJjFDW0jNf6iD5KK2SrDX1iXc2URm05KZDPz

### Visual documentation

![Screenshot 2024-12-12 at 8 58 50 AM](https://github.com/user-attachments/assets/21dbffa6-52b9-4cac-8a0b-7da047ccc4c0)
![Screenshot 2024-12-12 at 8 58 38 AM](https://github.com/user-attachments/assets/0485ccfc-ed1f-432b-87bf-17c1c08dc467)

### Environment

```markdown
- FlutterFlow version: 3.24.2
- Platform:web iOS
- Browser name and version:Chrome 131.0.6778.109
- Operating system and version affected: Sequoia 15.2
```

### Additional Information

Blocking the usage of Lottie animation

**Comment by healemdrapp** [comment] 2024-12-14 04:54
please add to this issue that the "upload file" doesn't work when trying to add a lottie asset
<img width="351" alt="Screenshot 2024-12-14 at 08 53 38" src="https://github.com/user-attachments/assets/4fe46b29-04e9-4fac-bd60-d58f93502c7b" />

**Comment by igor-lemon** [comment] 2024-12-14 11:12
Can someone from the support orientate when you will fix this issue?

**Comment by Jeffcyw** [comment] 2024-12-16 08:36
Having the same issue here. Since the bug has been confirmed, what's the status or when will this be fixed?

**Comment by PMFlis** [comment] 2024-12-16 22:15
I have the same problem. Not possible to add new lottie animation as asset or choose uploaded animation from assets. The animations that were already displayed on the screen, the paths were removed and I have error message saying Lottie path is not specified.

**Comment by azzar227** [comment] 2024-12-19 07:48
@Alezanello , when can we hope for a resolution of this issue ? (Who do we have to give love to ?)

Many thanks for your help

**Comment by healemdrapp** [comment] 2024-12-19 09:41
@azzar227 I can see that it has been resolved in the latest update, just download the latest desktop app version.

**Comment by PMFlis** [comment] 2024-12-19 10:01
Yeap it works perfectly now, all resolved.

**Comment by azzar227** [comment] 2024-12-19 13:42
It does. Amazing. Thanks!

**Closed as completed** 2024-12-26 17:43 UTC
Labels: status: confirmed, Bug, watched by support, Cherry-Picked
