### ISSUE TITLE
Switch status not updating with app state

### ISSUE THREAD

**Issue by thetechyghost** [FlutterFlow/flutterflow-issues#971] opened 2023-06-05 16:11 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When updating the app state that is tied to a switch's value, the switch state is not updating

### Expected Behavior

When an action is performed that changes the app state, a switch tied to that state should be updated

### Steps to Reproduce

1. Create a new page
2. Add a switch
3. Set the initial value of the switch to the app state
4. Change the app state via a button or other control
5.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXhc+A5c91xOpE1ZD+c+5VimAwGW4bbecR0tYbSTUYF5SuCJkqfPfAPhBBZ/GmYHxIJE2mp14B+fOPidrDCMYpHwmsbqpiyLVqdTnKJV2lM7GTF7qOPnJ8MNJXGk+B4LWRvRYnXcRiLnwC2FOmOPK/fBbvK4SxDUQwSq/LZO4=

### Context

Polling an API, when the API returns false, the switch should automatically change state

### Visual documentation

https://app.flutterflow.io/project/switch-jac1at

### Additional Info

https://app.flutterflow.io/project/switch-jac1at

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Affects all platforms
- Browser name and version:  Affects all browsers
- Operating system and version affected: Affects all os
```

**Comment by SameerShahzad99** [comment] 2023-06-05 16:22
Thank you for reporting this bug, I was able to reproduce this on my side!

**Comment by wenkaifan0720** [comment] 2023-07-05 16:11
Hi @thetechyghost. This is not a bug on the `Switch` widget, because the `Switch` is just taking the app state as the initial value. After that the internal state of the `Switch` is independent from the app state. If you want to link an app state with a `Switch` widget's internal state, the app state should only be controlled by the on Toggled on/off actions of the `Switch`. 

The UX you are trying to achieve could be confusing to the user as the `Switch` is still intractable even if you want to set it to show a fixed return status. I would suggest using the Text/Icon/custom widget to show the return status of the API.

Since this is not a bug on our side, I will close this issue for now.

**Closed by wenkaifan0720** 2023-07-05 16:11 UTC
Labels: closed: not a bug, status: not a bug

**Comment by thetechyghost** [comment] 2023-07-05 18:45
@wenkaifan0720 - the "could be confusing to the user" is subjective. Nothing relays the concept of "on / off" like a switch and if that state is potentially set outside of the app, like through another users when controlling smart switches, I would argue that the switch not behaving as expected is even more confusing. A bug is not the right term, but this should be a feature request as this obviously something that should be catered for.

**Comment by wenkaifan0720** [comment] 2023-07-05 20:19
Hi @thetechyghost. I agree that things could work if the `Switch` is completely non-interactive and its state is controlled entirely by some external state variable. But this is probably useful for a small percentage of use cases. Per Material design guidelines, a `Switch` should be interactive unless it is disabled. If you really want the `Switch` to behave like what you've described, you can use a custom widget.

**Comment by ge-king** [comment] 2024-08-09 15:46
Bumping this. This is a bug - this feature should be included. Switches should not only control, but SHOW the user the current status of a boolean.

**Comment by oskotsur** [comment] 2024-08-29 08:09
Agree with @thetechyghost, @eSebesten, @ge-king. In my case when the switch should reflect the actual app state (changed outside) and still stay interactive is quite natural. If not considering it a bug, the feature of having it would be highly appreciated
