### ISSUE TITLE
It is not possible to use a ListView in a scrollable row

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#4869] opened 2024-11-12 07:17 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

It is not possible to use a ListView in a scrollable row

### Expected Behavior

Should be possible to use a ListView in a scrollable row

### Steps to Reproduce

1. Add a row
2. Add a ListView
3. Now go to the row and enable the scroll
4. Produce a crash

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4OjMrqx89grtdA7qXbbcBKhiYsHHIja4ZNm8F9SUw0CK3NGpgMecmnPlppYM/jdFFYM1qcp14K0sL9v9rAU/UnAz+aUb56z6puFzmVTXKiRr2TF7qKPEFtONJbN0C915ivsx1CWdV1SmAC23GQAuesST7ZGIzsIXo4Sq/LZO4=

### Visual documentation

![image](https://github.com/user-attachments/assets/0e27a3db-3381-4776-ac61-deaf7fd1cc32)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.8+ released October 30, 2024 Flutter version is 3.24.2
- Platform: Web
- Browser name and version: Chrome 130.0.6723.117 (Official Build) (64-bit)
- Operating system and version affected: W11
```

### Additional Information

This user has the same problem:
https://community.flutterflow.io/ask-the-community/post/listview-inside-of-scrollable-row-26tOQoeDKUdKgAx

### Why am I trying to do this?
The reason behind this is that, on mobile devices, having many elements displayed close together makes the interface look cluttered and hard to navigate. I want to make the content scrollable only on mobile and not on desktop screens. Using data tables is not an option in this case because they don't support infinite scrolling, which is why I'm exploring this alternative approach.

My goal is to replicate the behavior of the "Min Width" property from the data table, as described in the tooltip: "The minimum width of the data table. If set and the contents exceed this width, the table will become horizontally scrollable."

If I could implement this, I would wrap a header and the list view in a container, set a minimum width (e.g., 500px). This way, on screens smaller than 500px, the horizontal scroll will be activated. On screens wider than 500px, the content would adapt to the full width of the screen without needing to scroll horizontally.

**Comment by Alezanello** [comment] 2024-11-12 18:43
Hello!

This is not a bug but rather a limitation and the current expected behavior. To enable a list view inside a row with scrolling, you will need to change the main axis of the ListView to horizontal. This adjustment allows scrolling within the row as intended.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/76340a7c-0069-438b-8cdf-fb10be825826/d4acc6bb-84e9-4fd0-ae77-374052bb813c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83NjM0MGE3Yy0wMDY5LTQzOGItOGNkZi1mYjEwYmU4MjU4MjYvZDRhY2M2YmItODRlOS00ZmQwLWFlNzctMzc0MDUyYmI4MTNjIiwiaWF0IjoxNzMxNDM2OTg4LCJleHAiOjMzMzAxOTk2OTg4fQ.-GsjLItSLPcQpaBhdG-p0mhSpj_2xyUowanuRAPEscY " alt="image.png" width="1723" height="880" />

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/1473c9a1-0124-4c0f-b46e-f4e34f608f17/48c70624-0e8a-44a4-8ee3-130574edc78c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xNDczYzlhMS0wMTI0LTRjMGYtYjQ2ZS1mNGUzNGY2MDhmMTcvNDhjNzA2MjQtMGU4YS00NGE0LThlZTMtMTMwNTc0ZWRjNzhjIiwiaWF0IjoxNzMxNDM2OTg4LCJleHAiOjMzMzAxOTk2OTg4fQ.1klKAEtXEIdfpEt-TQPD8YudCVvNQJvN4X3kwXBcacw " alt="image.png" width="1886" height="689" />

**Comment by Franco98404** [comment] 2024-11-13 22:47
But in my case, I don't want a ListView Horizontal

> My goal is to replicate the behavior of the "Min Width" property from the data table, as described in the tooltip: "The minimum width of the data table. If set and the contents exceed this width, the table will become horizontally scrollable."

The only way to do this is to have a ListView in a scrollable row

**Comment by Alezanello** [comment] 2024-11-20 17:35
Hello, and apologies for the delayed response.

Unfortunately, this is the current expected behavior in FlutterFlow. If you’re looking to achieve something similar, you might consider implementing it with a custom widget, as there isn’t a native solution available in FlutterFlow at the moment.

Thank you for your understanding

**Comment by Franco98404** [comment] 2024-11-20 22:44
Can you add this as a feature request?

**Comment by Alezanello** [comment] 2024-11-25 12:59
Of course! Apologies for the delayed response. I’ll go ahead and submit this as a feature/enhancement request. I’ll also close this issue and link it to the internal feature request ticket for tracking.

**Closed as not planned by Alezanello** 2024-11-25 12:59 UTC
Labels: closed: feature / enhancement request
