### ISSUE TITLE
Empty screen in TestMode

### ISSUE THREAD

**Issue by sachax** [FlutterFlow/flutterflow-issues#1095] opened 2023-07-10 11:28 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Running the app in TestMode, it should render the HomePage page, as it always did in all previous versions. Instead, I get an empty screen. This behavior showed up after a FlutterFlow update. My page is a really simple one: the root widget is a stack, followed by two containers. In the second container I have a column that is primary and scrollable. And it contains some content object. The only "notable" one is the news sections, notable just because it performs a backend query (an API Call). As I mentioned in the chat thread with tech support, everything worked perfectly for months: the structure hasn't changed and, anyway, there are previous versions saved.

### Expected Behavior

I should see rendered on screen the HomePage page. As it does on physical devices if I download the code and compile it.

### Steps to Reproduce

1. Create a new page
2. Add a Stack
3. Add a container
4. Nest another container
5. Add a column and make it scrollable and primary
6. add widgets (containers, rows with two containers…)
7. add a container with a ListView and populate it with a backend query (API Call to "Lista Notizie" in my project): https://www.obiettivo-magistrato.com/rest/index.php/news/lista
8. Run Test Mode

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4SifLf5ZNIvt9A0JCAbcFVij4UKUR/arg70u1QEQIdNZOqEJYPXOjASEhVXd+/TAl2Ilv9mnwx+vOKv+z2V+QHAzedGLZN/6pMVDyWZH2lV5SvOruwT2hCLJpYDkuVy7S7hBNCXfVaWV4720yqfeu/bDXvJZDxPUcRGvGkUZr5jAukAi+6Xn0Jg1ZSfCvr

### Context

I cannot run and test anymore my app on Chrome nor on Safari. I have to download the code and compile it on physical device (iOS and Android) loosing countless hours to test small things. 

### Visual documentation

<img width="1796" alt="Screenshot 2023-07-10 at 13 21 23" src="https://github.com/FlutterFlow/flutterflow-issues/assets/508564/350df4e1-8b27-466a-ac76-e2401a1aad74">
<img width="1796" alt="Screenshot 2023-07-10 at 13 21 27" src="https://github.com/FlutterFlow/flutterflow-issues/assets/508564/3ad10bcb-e1cb-4ced-b3a5-7f97d39db9b7">
<img width="1840" alt="Screenshot 2023-07-10 at 13 21 36" src="https://github.com/FlutterFlow/flutterflow-issues/assets/508564/73e9ee5d-e9df-4aab-8fc6-31a27aa25389">
<img width="1840" alt="Screenshot 2023-07-10 at 13 21 40" src="https://github.com/FlutterFlow/flutterflow-issues/assets/508564/8cc1eb0e-7d12-4e54-a183-0e8c0da0774a">
<img width="1693" alt="Screenshot 2023-07-10 at 13 21 55" src="https://github.com/FlutterFlow/flutterflow-issues/assets/508564/568dc965-8061-4bb2-b62c-17a1c014e291">
<img width="1693" alt="Screenshot 2023-07-10 at 13 22 00" src="https://github.com/FlutterFlow/flutterflow-issues/assets/508564/df6384a8-ac0e-4ed8-b1ed-a069c0c945a9">

### Additional Info

There is a chat thread with TechSupport detailing any further info.

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web
- Browser name and version: Chrome Version 114.0.5735.198 (Official Build) (arm64)
- Operating system and version affected: MacBook Pro M1 16" 2021 MacOS 14.0
```

**Comment by bulgariamitko** [comment] 2023-07-11 12:37
@sachax I think the reason is because of the data which is being returned from the API call.

**Comment by sachax** [comment] 2023-07-12 08:45
Hello @bulgariamitko and thanks for getting back to me.
Thing is, the data has worked perfectly rendering all info for more than 5 months and… it's always the same. The API Calls were setup and tested correctly and, in the homepage, they are super-simple: there is only one APICall and for some news, now limited to three just to see if there was a bug with them.
Anyway, I just made a try: I remove the ListView with the APICall and run/test the app, and the result is in the screenshot. 
<img width="1518" alt="Screenshot 2023-07-12 at 10 44 13" src="https://github.com/FlutterFlow/flutterflow-issues/assets/508564/a8442c1e-5bb9-458e-96fa-1ba3d2beeaf9">
<img width="1518" alt="Screenshot 2023-07-12 at 10 45 37" src="https://github.com/FlutterFlow/flutterflow-issues/assets/508564/a2b7f2c1-d7af-406b-99a0-21db40c9f87c">

**Comment by bulgariamitko** [comment] 2023-07-13 06:17
@sachax can you share your project link as well?

**Comment by wenkaifan0720** [comment] 2023-07-13 12:39
Hi @sachax. From the error message, it looks to be a Flutter layout issue. I can see that the issue is gone from your current project. What have you modified?

**Comment by hariprasadms** [comment] 2023-07-14 07:53
Hi @sachax - Is this issue resolved for your know? If so, please close the issue. Thanks

**Comment by sachax** [comment] 2023-07-15 12:16
HELLO! SORRY FOR LATE ANSWER! 
My project link was: https://app.flutterflow.io/project/obiettivo-magistrato-3w284r
And regarding the news: Danny from tech support asked me to switch the column with a ListView, which is a strange request but it worked. In my mind, we should be able to add a column and work as I was working for 12 releases. Using a column is so common in Flutter that having to switch to a ListView to hold column-standard elements is really strange.

**Comment by mravani2** [comment] 2023-07-15 16:09
I'm experiencing the exact same thing. After the last update, my TestMode is showing an empty screen. To make sure it wasn't something wrong with my layout, I reverted the app to a very old snapshot, and the problem persists.

Note: This only happens in TestMode or when I run on Web after downloading the code. If I export the apk and install it on my phone I can see the whole page correctly.

Btw, this is my project link: https://app.flutterflow.io/project/unit-app-4fkca6

**Comment by sachax** [comment] 2023-07-18 16:54
Here I am. Bus days and I truly apologize. 
I do totally agree. If i deploy in release mode it works perfectly on both iOS and Android. But in test mode it fails as well. 
On Chrome and Safari it fails.
(btw: your project link is restricted and I wasn't allowed to test it).
And first of all: thanks a lot.

**Comment by wenkaifan0720** [comment] 2023-07-22 17:23
Hi @sachax. I am on vacation right now so my response is a bit delayed... I still don't see the layout issue when I test run your project. It would be great if you could create a new project and reproduce the issue there. It is a strange issue from your description so I really want to see it happening in isolation so that I can understand what is going wrong. 

@mravani2. Could you change the main axis size of the main column in the home page to min? This seems to fix the issue. I believe we should have caught this issue in the builder. But let me know if this fixes your issue.

**Comment by wenkaifan0720** [comment] 2023-08-24 22:07
Hi! We’re closing this issue due to inactivity, as we do not have enough information currently to investigate. If this issue persists, please add the requested information so we can verify and re-open the issue. Thanks!

**Closed by wenkaifan0720** 2023-08-24 22:07 UTC
Labels: closed : project specific, status : project specific

**Comment by kosta0124** [comment] 2023-09-07 20:45
sachax, you are a legend! I was having the same problem white blank screen, and i had a listview nested in the column. As soon as i replaced column with listview, the issue resolved.

**Comment by casperrues1** [comment] 2025-01-14 09:59
Has anyone found a fix for the issue in FlutterFlow where custom actions don’t trigger properly when using Navigator.pushNamed, resulting in a [blank screen](https://whitescreentest.net/
)? I’m encountering the same problem and would appreciate any advice or workarounds that have worked for others.
