### ISSUE TITLE
require authentication

### ISSUE THREAD

**Issue by abdrzq16** [FlutterFlow/flutterflow-issues#825] opened 2023-04-29 11:45 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have an admin dashboard to create users accounts manually, and it should be on web. So if i made the page require authentcation FF refuses it and give me this bug (Login action is present on page that requires authentication, so it will be unreachable.)

(I think) FF logs in with the new account to make the document then log out back to my account.

If i published this on web any one can make complete profiles.

### Expected Behavior

Be able to make accounts whith enabling auth.

### Steps to Reproduce

1. make page for sign in and log in with my account as an admin.
2. make page to create a complete profile for another user> ( email,pass,name,phone..etc)
3. mkee this page require authentcation
4. getting this bug (Login action is present on page that requires authentication, so it will be unreachable.)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ol8jl34VNpbxY7rqJacFohSQUOWl/U+cv18pBazwbfe+uB4kqevfOTERoONPjdFZ9M2CZjWoW0ejsj9nDIPJcAy6cUa461LVIFAnzXXOmSqnXFJWgYHR6RMdVCE/Cy6azqxFvOvdtR0YW1FOEe+mWQi3fJZCzDnogDa/LZO4=

### Context

I can't make admin panel to make users profiles.

### Visual documentation

![image](https://user-images.githubusercontent.com/108595330/235300755-1ffc57e7-9875-4786-ade8-a12419a6aede.png)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: web, andriod , ios
- Browser name and version: chrome
- Operating system and version affected:  win 11
```

**Comment by hariprasadms** [comment] 2023-04-29 15:06
Hi @abdrzq16 - The FlutterFlow features around the logic you are trying achieve is working as expected. I would suggest you to watch the FlutterFlow YouTube tutorials and user manuals to better understand the authentication features and how to get the functionality you want. 

I'm closing the issues because this issue is not a bug. Thanks

**Closed by hariprasadms** 2023-04-29 15:06 UTC
Labels: status: needs triage
