### ISSUE TITLE
Widget configuration error

### ISSUE THREAD

**Issue by janmestek** [FlutterFlow/flutterflow-issues#141] opened 2022-11-19 18:21 UTC
## Expected behavior (required)

The page view widget was working normally. Show the uploaded images from the firebase storage.

## Current behavior (required)

The widget shows a configuration error. 
Many people experience the same problem: https://community.flutterflow.io/c/discuss-and-get-help/pageview-widget-error#comment_wrapper_13043230

## To Reproduce (required)

1. Create new page and add query from collection containing images
2. Add list view3. 
4. Add container and inside page view
5. On page view, Generate children dynamically from list of images.
6. Observe error

## Context (required)

I can't show the images from my firebase storage

## Screenshots / recordings

<img width="881" alt="Screenshot 2022-11-18 at 14 49 05" src="https://user-images.githubusercontent.com/118629165/202865757-199aee57-6ce8-47e5-972e-7f9d8b6b2f58.png">
<img width="293" alt="Screenshot 2022-11-18 at 14 48 26" src="https://user-images.githubusercontent.com/118629165/202865759-362b92cf-c7bb-47ad-b525-5bb81bddf54d.png">

## Your environment

* **Bug Report Code:**
IT4kiMjfsI52ocMA+KrTbe5GqGQvNUB8TL07s9Z+RRQvIrbyOu9/effBP1hpZMOjTWlhHFCYpDkKweyMuPDqFfcrOROsGKpEzbtpEhbgXTbkEuzyT+3IHDUHZbsSXTTm

**Comment by janmestek** [comment] 2022-11-23 13:48
Hi, 

is there any update on this topic?

**Comment by janmestek** [comment] 2022-11-28 19:59
Let me know please

**Comment by kicsijohn** [comment] 2022-12-20 22:59
> This is actually not an issue. It is how FF will work from now on. When you are using some of the Widgets in a ListView for example it is necessary to put that in a component. If you don't do that there could be some issues, so this is how FF will work now. So I will mark this as not a bug.

Hi! I have the same problem, I want to add a pageview in a SwipeableStack. If I use it as a basic element I get the same error, if I convert it to a component the error message disappears BUT I have other issues: 
- I don't have access to the widget state, and I can't pass the pageview page index as a parameter. Inside the component, I don't have access to the query on the SwipeableStack.
It is not a user-friendly solution and for me it is unusable.

**Comment by bulgariamitko** [comment] 2022-12-21 13:26
This issue tracker is intended for general bugs that are applicable to all users. Because this error appears to be specific to your project and the steps are not reproducible, this is classified as a support request and will be closed. Please use chat support or contact support [at] flutterflow.io for further assistance.
If you do find a specific reason for the issues you are encountering in your project, please don’t hesitate to open a new bug report with the relevant steps to reproduce.
Thank you for your contribution!

**Comment by agreaves** [comment] 2022-12-28 17:43
Closing this issue because as @bulgariamitko said this is simply how FlutterFlow works and using a component is the best solution in these cases.

@kicsijohn, you should be able to use the "Index in List" property to pass in the specific index, and you can pass in the document or element into the component as well. You can access the widget state inside the component by using Local State, or modify it by passing in an Action as a parameter for the component to modify the page state. I hope one of these options helps!

**Closed by agreaves** 2022-12-28 17:43 UTC
Labels: status: not a bug
