### ISSUE TITLE
JSON Paths Bugs - Filtering Expressions and paths that select elements from arrays and more

### ISSUE THREAD

**Issue by WellDunDun** [FlutterFlow/flutterflow-issues#1312] opened 2023-08-20 18:53 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have 6 new bugs that showed up today and they all relate to JSON paths. 
1. Filtering expressions that are named paths in the API tab
2. Any paths that use selecting elements from arrays
3. One more that I haven't pinpointed the source (see images - this is the one I used for the bug report code since the others can't be accessed through the widget tree to generate one)

Please note that this app is in production with users and works.

### Expected Behavior

The JSON paths should not show errors in the FlutterFlow Editor

### Steps to Reproduce

I'll try to reproduce for y'all when I have time

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ChJDb250YWluZXJfMnp6a3Y4N3QSiQIKD0NvbHVtbl82ZG9rdXBiNxKlAQoOSW1hZ2VfMDQweHJpajAYByKOATJ+Cjdwcm9qZWN0cy9teS1iYWx0by15djNvYXQvYXNzZXRzL3Q1Z3Nmc2Vhc3ZmZi9pY29uLTMucG5nEAIYAyIWCgkJAAAAAAAATEASCQkAAAAAAABMQCokCQAAAAAAACBAEQAAAAAAACBAGQAAAAAAACBAIQAAAAAAACBAaPQDWgkRAAAAAAAALkD6AwBiABJFCg1UZXh0X3NkYmJkZDNiGAIiMBIXCg5TaG9wIG15IApTdG9yZTACQAaoAQBaEhEAAAAAAAAuQCEAAAAAAAAuQPoDAGIAGAQiBSIA+gMAGAEigAEKTgoLCgkJAAAAAAAAWUASMhIkCQAAAAAAABhAEQAAAAAAABhAGQAAAAAAABhAIQAAAAAAABhAQgYI/////w9aAGIAIgBJAAAAAAAAWUBSAFobCQAAAAAAABBAEQAAAAAAADRAIQAAAAAAADRAegIYAfoDAPIFCQkAAAAAAADwP2IAigFeElgKCHhxdGFjZDN1EkwqPxI9CAxCECIOCgoKCHVzZXJEYXRhEAFKJyIlCiMkLnByaW1fdmV0X2Z1bmRyYWlzaW5nLmUtc3RvcmVfbGlua6oCCDk3cnZ3cXB0GgIIAQ==

### Context

This issue has stopped me from being able to use the platform. 

I cannot delete and try to rebuild any of this as this is a huge project with multiple devs.

Also, all the snapshots have the same issue so I can't revert.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/45949032/86fe48e1-b8bf-4696-8aac-c6231e967da6)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/45949032/4c10cb5f-c6eb-4c1c-9ae6-c679f6ecfdda)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Version 116.0.5845.97 (Official Build) (64-bit)
- Operating system and version affected: Windows 10
```

**Comment by Fibn007** [comment] 2023-08-20 22:04
Can confirm that all of the new pages I write with existing API calls fail while my old, untouched API calls are still working. Something changed recently that is breaking newly set API JSON expressions.

**Comment by WellDunDun** [comment] 2023-08-22 08:18
> Can confirm that all of the new pages I write with existing API calls fail while my old, untouched API calls are still working. Something changed recently that is breaking newly set API JSON expressions.

The weird thing is that mine are all old API Calls and it's not just API Calls, anything with JSON paths such as App State

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/45949032/f11e5b9f-37d8-44f3-b836-bf706f06e0f8)

**Comment by tomaz-dugii** [comment] 2023-08-22 23:47
Yup, something broke with JSON Path.
I always get this message: Current API endpoint is misconfigured. Details: JSON path "" is an invalid name.
And frankly I don’t know what the problem is.

**Comment by WellDunDun** [comment] 2023-08-28 07:24
Any ETA on a fix for this? I sadly can't do any testing or updates to the affected projects until it is.

**Comment by Fibn007** [comment] 2023-08-30 14:39
@kevintonb @katherineqian Hi, are there any updates on this issue. Majority of my project is API based and I've had to sit on my hands and try to find small holes to fill while I wait for this fix. Are there any updates?

**Comment by YassinELY** [comment] 2023-09-03 13:44
Any news? :)

**Comment by nparkins07** [comment] 2023-09-05 15:04
@katherineqian - Any update here? This has been an issue for over (2) weeks and we cannot update a critical feature to our app. Please advise on a fix to this asap. Thank you!

**Comment by tomaz-dugii** [comment] 2023-09-06 00:12
I change all columns names  Capitalised words, removed all whitespaces and special characters like: "-" , "_". Column names looks like this: ColumnName. Also try and do JSON path manually  by `[:].ColumnName`. This video helped me to somehow figure this out: [Subabase-FlotterFlow search tutorial](https://www.youtube.com/watch?v=jMLjyYwqJN0). Hope this help someone.

**Comment by YassinELY** [comment] 2023-09-06 19:56
Hi @katherineqian , i deploy directly from flutterflow :)
Will the solution that @tomaz-dugii gave work in my situation?

**Comment by aemelyanovff** [comment] 2023-09-18 21:19
Sorry for the late response.

@WellDunDun Try `$.prim_vet_fundraising["e_store-link"]` instead of `$.prim_vet_fundraising.e_store-link`. The JSON path parser we are currently using does not allow hyphens in property names. As far as I understand, names with hyphens are invalid in JSON path, even though some parsers allow them. See https://stackoverflow.com/questions/13869627/unable-to-access-json-property-with-dash

**Comment by YassinELY** [comment] 2023-09-19 07:38
I still have the same problem...
<img width="724" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/142539026/a3e46fd1-4434-4684-acad-8e8645621119">

**Comment by aemelyanovff** [comment] 2023-09-22 19:49
@YassinELY Please see my response [here](https://github.com/FlutterFlow/flutterflow-issues/issues/1302#issuecomment-1727597603).

Closing this issue.

**Closed by aemelyanovff** 2023-09-22 19:49 UTC
Labels: status: confirmed, priority: medium
