### ISSUE TITLE
Can t download the code after I imported the swagger file with API Calls

### ISSUE THREAD

**Issue by AlexGoncearu** [FlutterFlow/flutterflow-issues#986] opened 2023-06-12 16:49 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After importing the API definition with Swagger, (API Group) I can't download or push to repository the code. 
Error: Code Download Failed (Unexpected error). I don t implement the API Calls in my code

### Expected Behavior

Download the code for testing after importing the API Group with Swagger for testing.

### Steps to Reproduce

1. Import API Definitions with Swagger
2. Created the API Group
3. Download the Code

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Wls/qx49Om9tK14SJc8EwtCMvJkR/aIJEl8NxewEdF5DmEYwPXfikSEpWZ9+kTHxcL2CgnTo1zNqPhvzEA+UrGzuabKJGzrhxEwHJTTmuV8iVDJOoVnBQRPNJJVynyKejhiRAGONhV1ks2WauLtivRXTvQZOwDlcGQs6YUYf+s1GpQ0SLb3kNh1JWeC/v

### Context

Integrate the API Calls in my code.

### Visual documentation

![Screenshot 2023-06-12 at 19 16 01](https://github.com/FlutterFlow/flutterflow-issues/assets/127595161/c7aca44b-8106-42e9-b638-9de2b0cdcf20)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: MacOS or Web
- Browser name and version: Chrome
- Operating system and version affected: macOS Monterey 12.2.1
```

**Comment by aemelyanovff** [comment] 2023-06-12 16:59
@AlexGoncearu Thanks for reporting the issue. Can you attach the Swagger file you imported? We can't reproduce the issue and can't fix it without the swagger file.

**Comment by AlexGoncearu** [comment] 2023-06-13 16:25
[swagger (2).json.zip](https://github.com/FlutterFlow/flutterflow-issues/files/11737057/swagger.2.json.zip)

**Comment by aemelyanovff** [comment] 2023-06-13 21:38
@AlexGoncearu Thanks for the details. It'll be fixed in the next release.

**Closed by aemelyanovff** 2023-06-13 21:38 UTC
Labels: status: needs information
