### ISSUE TITLE
Dropdown shows error when API call returns empty response

### ISSUE THREAD

**Issue by ssaguadoinversiva** [FlutterFlow/flutterflow-issues#1689] opened 2023-10-23 07:35 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a Dropdown that it's populated with an API call. When this api call returns zero objects it throws this error:
<img width="387" alt="Captura de Pantalla 2023-10-23 a las 9 27 55" src="https://github.com/FlutterFlow/flutterflow-issues/assets/145776162/4cb9ebf5-8403-4297-b834-6a3c63e72507">

### Expected Behavior

The expected behavior will be just an empty dropdown

### Steps to Reproduce

1. Create a page
2. Add a dropdown
3. Use an API call to populate the Dropdown
4. Define an Option label and option value with a JSON Path

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48j8nc05NPmMNA0JD9bfpVniQUJj47apEZjextawk8J5zbPbN/eP/RPxFuZryoS39mJmCJuGEy/PfquN+WNsIVEAqBboc5yKtQWAvJfEiVVa6PCbmRfW1fL+BWClya4KuwkxF4AO9tS1YQ2nGAOtmsZD3XGJDUNjJEJuaLLdeK2SrDX1iXc2URm05KZDPz

### Context

It's a typical use case having a form with several componentes. One of them, not required, that it's populated from an API call and sometimes it's empty

### Visual documentation

<img width="387" alt="Captura de Pantalla 2023-10-23 a las 9 27 55" src="https://github.com/FlutterFlow/flutterflow-issues/assets/145776162/840cc619-f66b-4760-a9de-e86f0b497f73">

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: all
- Browser name and version: Chrome
- Operating system and version affected: Not important
```

**Comment by SameerShahzad99** [comment] 2023-10-23 17:29
Hi @ssaguadoinversiva, This issue seems to be a duplicate of an already addressed issue, please check the issue here for more details:
https://github.com/FlutterFlow/flutterflow-issues/issues/968

**Closed by SameerShahzad99** 2023-10-23 17:29 UTC
Labels: closed: not a bug, type: feature / enhancement request, closed: duplicate
