### ISSUE TITLE
Not able to edit/update/modify any custom Data Type anytime that's within a list.

### ISSUE THREAD

**Issue by Kato-Official** [FlutterFlow/flutterflow-issues#3935] opened 2024-09-30 06:01 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When trying to edit any data type within a list, you are not able to edit. Please see video: [https://dummy-1d799.kxcdn.com/videos/data_type.mp4](url)

### Expected Behavior

To be able to edit the data type. 
Is you are able to edit the data type, can you please show how. Thanks, appreciated. Cheers

### Steps to Reproduce

- Create a data type list with a single string field for testing.
- Create Collection with a single filed of this custom data type list.
- Try to edit any of this data type from the list (not add, not remove, but simply edit).

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTjsmAsItNm7RG+KnTKPpvoCEUGUMdXOczitVEew4bCIj4P6QAOvfCahNvZOKzaHNmD1qlrzkF+PzqieDuV/Q4ZEyWQIhNzrl9WhPPbEK7RYSYEs2sdHJAO8VYCH6705+KnglDLutpWFlnw16QH96sZz6Cf9qOYwx5e6fDbOY=

### Visual documentation

[https://dummy-1d799.kxcdn.com/videos/data_type.mp4](url)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.1 released September 27, 2024
Flutter version is 3.22.2
- Platform: Web & Desktop
- Browser name and version: Chorme
- Operating system and version affected: All
```

### Additional Information

Hi, hope you are well. Could you please show how to edit a data type in a list? Thanks. Cheers

**Comment by paulperez-dev** [comment] 2024-10-01 19:20
Hi @Kato-Official,

Could you please upload the video to Google Drive? The current link appears to be broken.

**Comment by Kato-Official** [comment] 2024-10-02 02:52
Hi @paulperez-dev thanks for the message. You can simply copy the link and paste it in your browser without clicking it directly. It works, I just tested it. Please check here. 

https://github.com/user-attachments/assets/9c3746dc-62cc-4649-8357-03574dea40be

**Comment by Kato-Official** [comment] 2024-10-04 03:37
Hi @paulperez-dev, any update?

**Comment by paulperez-dev** [comment] 2024-10-09 13:11
Got it, thanks! Looking into this.

**Comment by paulperez-dev** [comment] 2024-10-11 12:54
Hi @Kato-Official,

To resolve this, you'll need to update the list in the app and replace the entire list in Firebase.

Since this is expected behavior and not a bug, I'll go ahead and close this issue.

Thank you for your understanding!

**Comment by Kato-Official** [comment] 2024-10-11 13:34
@paulperez-dev please can you share a video of you doing it in FlutterFlow? Thanks.

**Comment by Kato-Official** [comment] 2024-10-14 06:10
@paulperez-dev hope you are well. Since this is expected behavior and not a bug, could you please demonstrate how to do it with a short screen recording? Thanks mate. Cheers

**Comment by paulperez-dev** [comment] 2024-10-17 13:36
One possible approach:

1. Create an app or page state to store the list.
2. Perform any operations (insert, remove, etc.) on this state list.
3. After making the changes, update Firebase using the updated state list.

**Closed as not planned by paulperez-dev** 2024-10-17 13:36 UTC
Labels: closed: not a bug
