### ISSUE TITLE
Some app state variables do not persist even when they are set to 'Persisted'

### ISSUE THREAD

**Issue by sgnaguib** [FlutterFlow/flutterflow-issues#1072] opened 2023-07-03 18:08 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

My app is used to store information about soil samples that users collect. Usually users don't have an internet connection when they collect the samples so I need to save those samples locally. Once users have access to the internet, they can upload the samples to the cloud.

I store the samples as JSON objects in a JSON list that is set to persisted. However, when a users closes the app and reopens it, all the samples (i.e. all the JSON objects in the list) are gone. For some reason, the JSON list isn't persisted properly. 

Out of curiosity, I created a string variable and set it to persisted and it does persist properly. 

### Expected Behavior

The expect behavior is that an JSON list app state variable set to persisted would keep its values when a users closes the app and reopens it.

### Steps to Reproduce

1. Create JSON List App state variable, set to 'persisted'
2. Add a default first item value (i.e. {'default': 'default'}
3. Create a text widget that displays the first item in the list ('default':'default')
4. Create a custom action that updates the first value of the list to some new JSON object (i.e. {'updated': 'updated')
5. Add an action to rebuild the page
6. Add a button to trigger the update of the json list and the rebuild of the page
7. Run the app, press the button, confirm that the first item in the json list is updated
8. Close and reopen the app (or hot reload) 
9. The new value for the item in the json list will not be persisted

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfz8/q24lPm+FY1r6Jd8ZF9CoWNmUcTIMziNZ+exUbfaL1BuxzduPsYklBTe3gaVNffU2GoEgC//T9kezpUPUVPTOZfYBe/rtyVzzke2iVbJCkPbq8YHZPBZ9bfGqZ3ImJqh1vIrF2Sk411EyIedzLRXXDFOu/Zwh9f6PHaOI=

### Context

This issue makes me app unusable. I need to be able to save samples locally and for those samples to be persisted so that if I user closes the app and reopens them later, they can still see their samples. I need to save the samples in a JSON list locally because when the information about the samples is collected, users usually don't have internet access. So I need the data to persist for a few days to give users to chance to get to a location with internet access so they can upload the samples to the cloud.

In short, I'm creating objects in this app that need to be saved locally in a list. This is critical information. However, if a users closes the app, all this critical information is lost. 

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/43552994/ce9f14de-eb8f-4124-b988-96e76b9284c4

### Additional Info

Here is the bug report code for the dummy project I created to reproduce the issue from a blank project: IT4oz/Hqx89goeJE14SJb+9V+CQ6NUQgaOY3lMpBZywgfZzzBLN/fPfQPlpCXbS6T1Y7eE22p14F0ejUvvDiVvoBNT+BfLpjyKgBERXgcDujacSTF7qoOXdADcVYGEjA4LSvvSZSIbZqcncu6nGECOqXdC7rHqLaIWo8Sq/LZO4=

Other people seem to be having this issue as well:
https://github.com/FlutterFlow/flutterflow-issues/issues/651
https://community.flutterflow.io/c/discuss-and-get-help/json-list-not-being-persisted

@victoriahuang1 said that the issue is not actually related to JSONs itself at all. However, this issue doesn't occur with string app state variables for me. 
"@darkiice the bug affecting this particular issue has been addressed. Here, the issue is not actually related to JSONs at all, but rather the JSON was used in a way that was very error prone (due to race conditions)."

@victoriahuang1 also mentioned that this issue is related to a race condition. However, I do not know what to do to avoid this race condition. 

Some responses during the month of May said that the issue had been fixed, but I'm using the latest version of the FF and I'm still encountering this issue 

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: MacOS Desktop
- Browser name and version: Chrome Version 114.0.5735.198 (Official Build) (x86_64)
- Operating system and version affected: MacOS Ventura 13.4
```

**Comment by wenkaifan0720** [comment] 2023-07-07 20:09
I think this issue is related: https://github.com/FlutterFlow/flutterflow-issues/issues/1050

**Comment by aemelyanovff** [comment] 2023-07-14 18:48
Closing as a duplicate of https://github.com/FlutterFlow/flutterflow-issues/issues/1050

**Closed by aemelyanovff** 2023-07-14 18:48 UTC
Labels: closed: duplicate
