### ISSUE TITLE
sign up/log in page

### ISSUE THREAD

**Issue by rastogipr** [FlutterFlow/flutterflow-issues#3162] opened 2024-06-17 18:21 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After pressing the "Get Started" button on the CreateAccount or the "Sign in" button on the Login page, it is not navigating to "homepage" as is defined in the action chain for the two buttons. 

### Expected Behavior

When these buttons are pressed, it should either create an account for the user or log the user in. Then, it should navigate to the "homepage". 

### Steps to Reproduce

1. Create three pages. One page to create an account for a user. One as a login page. And a third as the homepage, or the page to which the user should be directed to once logged in. 
2. On the "create an account" page, add a form with text fields, and a button at the bottom. This button should have the action chain "Auth: Create an Account" and then "Navigate to: homepage". On the "login" page, have a spot for the username and password and a button with the action chain "Auth: Log In" and then "Navigate to: homepage". 

Alternatively using the app and pages already created in my app. 
1. Begin on either the "CreateAccount" or "Login" page. Enter appropriate credentials. Click the Get Started or Sign In Button. 
2. You will notice in the Debug panel that when you hit Sign In with the right credentials, it will show that the user has been logged in, but it won't navigate to the homepage. 
3. You will also notice through the firebase database tha when you hit Get Started, a user is created but it does not navigate to the appropriate page. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

unable to get bug report

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/173090821/2d71017c-46c4-477f-be9d-f1aa15c6a5ec

### Environment

```markdown
- FlutterFlow version: v4.1.60+
- Platform: Web
- Browser name and version: safari
- Operating system and version affected: macOS Sonoma
```

**Comment by paulperez-dev** [comment] 2024-06-20 00:33
Hi @rastogipr! So sorry you are facing this issue. Can you please share a capture showing the new debug panel (auth related variables) and the browser console? This will help us identify the issue.

**Comment by rastogipr** [comment] 2024-06-21 00:01
Hi Paul,

Thank you for reaching out.

I was able to temporarily amend the issue by pushing back the date for the Firestore security rules (the one for test mode). I guess the issue is in the new rules that I had deployed. Would someone from your team be able to help me write security rules for the authentication functions in my app?

Thank you,
Pranav Rastogi
________________________________

**Comment by paulperez-dev** [comment] 2024-07-13 15:31
Hi @rastogipr! You can reach the [community ](https://community.flutterflow.io/ask-the-community)asking for help, they can help you with the rules configuration. I'm closing this issue since this is not a bug in FF.

**Closed as not planned** 2024-07-13 15:32 UTC
Labels: closed: not a bug
