### ISSUE TITLE
error lottie animation if i put it into contidiotnal builder and container

### ISSUE THREAD

**Issue by aaksa** [FlutterFlow/flutterflow-issues#3123] opened 2024-06-13 17:11 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

BuildFailed even tho there is no error

### Expected Behavior

Build Success

### Steps to Reproduce

create Container-> Conditional Builder -> Lottie Animation

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gz8jfsJZNrt9K+KXhKe9ahiIXNlB9bIc0sNobbxAjIoDoPJkUac/8SxBpZMu9YG9tKEWKmmQFwevGjvPXVO4BGAqVY6o41ZBpWDmVXke/aoSVEc+WdXF8O/tYGH6Z3Ka7nhNQCOthS3wm2kyxfvPJcAXYN5v7Zwh9f6PHaOI=

### Visual documentation

<img width="470" alt="Screenshot 2024-06-14 at 01 02 01" src="https://github.com/FlutterFlow/flutterflow-issues/assets/61930109/628ec488-dc7a-4929-9825-46bdc1eac054">

### Environment

```markdown
- FlutterFlow version: v4.1.59+ released June 13, 2024
- Platform: Web
- Browser name and version: Version 125.0.6422.114 (Official Build) (arm64)
- Operating system and version affected : Mac os Ventura 13.3.1 (22E261)
```

**Comment by msusviela** [comment] 2024-06-13 18:47
Hi @aaksa. Thanks for your report, So sorry you are experiencing this issue. I was not able to reproduce this on a blank project, but it is replicable on yours. That's why I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. Thanks so much!

**Closed as not planned** 2024-07-02 20:04 UTC
Labels: closed: support request
