### ISSUE TITLE
Unable to add an action to toogle icon widget 

### ISSUE THREAD

**Issue by plannedlivingjournal** [FlutterFlow/flutterflow-issues#3843] opened 2024-09-17 16:12 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hi! I am creating an app wherein if someone likes a post/test, it should get added to their 'Favorites' folder. If someone clicks on the 'Toggle button', it should get added to another page.

I tried getting answers on the query #3813, however, haven't been able to get any help.

![image](https://github.com/user-attachments/assets/7ea15fa1-572c-468a-a0ef-a51ee1bc87b7)

### Expected Behavior

Click on Toggle/Heart button
Should get added to another page/should get collected.

### Steps to Reproduce

Unable to create the scenario

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4olsn15YVPj7xE7q6JccBKjSQWOUAlbLgO0cpBZzAaIrb1CLMqY8mnPltBZ+mkS3xUOmGcp14E0/DWj/zhG8YEZC2aRtlGyM8BaBXjTliWMZeTF7qWPnB5M+5gfUix07aruBVTAPNpc3AB70+YHN+8dAXBO4DJDWo8Sq/LZO4=

### Visual documentation

![image](https://github.com/user-attachments/assets/8b829d0b-68bb-4097-81e1-b527122769f6)

### Environment

```markdown
- FlutterFlow version: 3.22.2
- Platform: Web
- Browser name and version: Chrome 1.28
- Operating system and version affected: Windows
```

**Comment by rzambroni** [comment] 2024-09-17 19:47
Hi @plannedlivingjournal,

Thank you for your patience, and I apologize for the delay in responding to your previous ticket. I'll go ahead and close this one as it is a a duplicate of the earlier report. We will continue to follow up on the original ticket.

If the issue is still ongoing, we kindly ask that you avoid submitting duplicate tickets, as it helps us reduce redundant efforts and respond to your concerns more efficiently.

Thank you for your understanding.

**Closed as not planned by rzambroni** 2024-09-17 19:47 UTC
Labels: status: needs triage
