### ISSUE TITLE
failed to validate firebase schema

### ISSUE THREAD

**Issue by divingjoker** [FlutterFlow/flutterflow-issues#3676] opened 2024-08-23 08:23 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

failed to validate firebase schema after add google map

### Expected Behavior

i did not expect it will failed to validate even i add google map, run test mode seems work fine

### Steps to Reproduce

create new page and add google map

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEelPHhuJRNpb0F+aqNa+xGgQMwGm45a+cZkdV8EBAaCePyOpYid+DOalVtWOqHeglUekyWiXE07vTUvtjmU/kEOTudQa0/ypZxUxDiQTu6RJjRCaWWZHEkL/JbfUzF4auG3B0nGMFYL3Ms1F2IHt+AY3qCf9qOYwx5e6fDbOY=

### Visual documentation

<img width="1203" alt="螢幕截圖 2024-08-23 16 12 41" src="https://github.com/user-attachments/assets/8126d661-52a6-4bf1-8788-31bd88612f7c">

### Environment

```markdown
- FlutterFlow version: v4.1.83
- Platform:chrome
- Browser name and version:
- Operating system and version affected: mac
```

**Comment by divingjoker** [comment] 2024-08-24 08:11
i just tried to open a blank new project with simply users collection, and still get the same message Failed to validate, what can i do ?

**Comment by turisouza** [comment] 2024-08-24 12:59
My project has the same problem. I can't validate it anymore. I've even returned to previous backups where it was validated and it's giving the same error. What can be done?

**Comment by paulperez-dev** [comment] 2024-08-26 14:19
Hi @divingjoker! I was able to reproduce the issue, I will send it to the ENG team so they can work on this!

**Comment by rzambroni** [comment] 2024-08-28 15:21
Hi everyone, I’ll mark this as a duplicate since there is already an internal ticket with a fix in place, and we want to avoid duplicating engineering efforts.

The fix will be released soon.

Thank you for the report.

**Closed as not planned by rzambroni** 2024-08-28 15:21 UTC
Labels: type: bug, status: confirmed
