### ISSUE TITLE
Passing list of docs in a component parameter to a component state on component initialization

### ISSUE THREAD

**Issue by srh98** [FlutterFlow/flutterflow-issues#1744] opened 2023-10-30 23:47 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a page state which contains a list of documents populated from a query. This page state is passed as a component parameter into a component, and then on initialization of the component the component parameter is passed into a component state which we use to dynamically populate items in a list. However, the component state does not receive the list of documents on initialization, resulting in the grid appearing empty. If we then update a different component state via a button on the page, our component state containing the list of documents gets filled with the documents from the component parameter.

To investigate what's going on I created a couple of text widgets that show the number of documents in the component parameter and the component state next to each other. On initialization we can see the component parameter has documents but the component state does not. Then clicking on the button that updates a different component state, the component state gets updated.

### Expected Behavior

The component state should receive the documents from the component parameter on initialization of the component.

### Steps to Reproduce

1. Create a new page with a page state which is a list of documents
2. Create an action flow on initialization of the page:
   i) create an action in the flow to query a collection for a list of documents that will result in a non zero number of documents returned
   ii) update the page state to contain the list of documents from the query action
3. Create a reusable component on the page with a component parameter to contain the list of documents and a component state which is a list of documents
4. On initialization of the reusable component, pass the component parameter into the component state
5. create text widgets inside the component that display the number of documents in the component parameter and component state
6. observe that the component parameter contains documents but the component state does not

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4elcmAuIhOxLhc1pPpbcAxnjgRNl87aI0zmOt+dAw0fLLvEO0tduj+TGZuOLDid2xiPFmWgm0d+cLIvYfLCcE4aRyJb6ly1ZYMEQ/jWl2RbKXQBbiCPmtPM8BhG0iezpuWkBF/OfVaR1YW7WaUIOTKExHcQozTIjIROPGbKq/Aj3CDLR3CGX0Jg1ZSfCvr

### Context

I am trying to pass a list of documents from a page state into a component so that the component can use them in its component state. There are several use cases for this within our app. 

The bug report code above is for the component I created from a blank project. The below is for the component in our app.

IT4gic/fz4VPxMhE7rruK+9WjjwvQl97bZc0sd4bGA0dCJzuPLMQdvWkUBRCUsjhd2NIP0SmmmcK0fTmkeDLCPEqBweCfN1lzcxUTAvKeHGlUZOBEpGBPWhQGdxTFW6a5LSvphFACNVuW1o62maXNu+9dBTaQefAIndISq/LZO4=

### Visual documentation

The action that sets the component state on initialization of the component:

![Screenshot 2023-10-30 at 3 28 20 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/117376796/c10a0c1d-4acf-40f0-933f-1687d616d18f)

The component we're looking at about is the one with the search bar at the top, encased by the white box. Here, you can see "120" which shows that on initialization of this component we have 12 documents in the component parameter and 0 documents in the component state:

<img width="477" alt="Screenshot 2023-10-30 at 3 30 28 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/117376796/3527ad7f-5724-429c-8852-76ba3040c340">

Then clicking on the choice chips at the top (i click "Outgoing" and then "Incoming"), you can see that the component state gets populated with the documents from the component parameter:

<img width="495" alt="Screenshot 2023-10-30 at 3 32 14 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/117376796/b820b4eb-6d0a-42d2-83c6-b4397fed24b0">

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: Mac OS, Macbook M2 Pro
- Browser name and version: Chrome 118.0.5993.117
- Operating system and version affected: MacOS Ventura 13.3.1 (a)
```

**Comment by srh98** [comment] 2023-11-02 20:49
I see there is now a non blocking option in the action editor. Would this help with this problem?

**Comment by srh98** [comment] 2023-11-07 04:24
Hi, following up on this one. Any update? Thanks!

**Comment by srh98** [comment] 2023-11-16 17:29
Hello, following up so this does not become stale

**Comment by victoriahuang1** [comment] 2023-12-21 19:38
Hi @srh98 , thanks for the report. This is actually the expected behavior due to how page loading interacts with widget rendering. The recommendation is to directly set the initial value, rather than using the "on page load" action to populate the value.

We realize this can be confusing, and will work on a better user experience -- which I can put down as a usability / feature improvement item for the team. For now though, I will be closing this ticket as it is not a bug.

#1820 #1889

**Closed by victoriahuang1** 2023-12-21 19:38 UTC
Labels: status: needs triage
