### ISSUE TITLE
Network Disconnected issue when editing Pages

### ISSUE THREAD

**Issue by pstatile** [FlutterFlow/flutterflow-issues#3671] opened 2024-08-22 12:48 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hi! I am experiencing again a very frequent issue of 'Network Disconnected'. We discussed it on Issue 3361 a while ago and it happened once in a while, but now it's again happening after a few seconds after trying to edit a Page. I checked my internet connection and it's OK. I changed it and it still happens.

### Expected Behavior

Let me edit a page without disconnecting.

### Steps to Reproduce

1. Edit a Page

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFThc/6w5N2rt9G+KniaO5aqGQ7GUMfWOdEket+EA0hfZDtBLATdczCbVVLYtfmS31DPmH+sEkfwvDpkd/1F+04YU+BUaZTzL5XQQ3jVlGhRcmpELqeW3ZBBeFmJ0yi0cHYnRFCNbBidEYk2mGuffCdG3qCf9qOYwx5e6fDbOY=

### Visual documentation

<img width="1794" alt="image" src="https://github.com/user-attachments/assets/a74cb67e-8173-4847-9035-869a13532c45">

### Environment

```markdown
- FlutterFlow version: 4.1.83+
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: iOS
```

### Additional Information

Related to: https://github.com/FlutterFlow/flutterflow-issues/issues/3361

**Comment by rzambroni** [comment] 2024-08-22 19:20
Hello, i'm going to mark this ticket as duplicate of [#3361](https://github.com/FlutterFlow/flutterflow-issues/issues/3361) as it seems to be the same issue. 

Will follow up internally to make sure we are taking into account that it is happening with more frequency recently.

Thanks.

**Closed as not planned by rzambroni** 2024-08-22 19:20 UTC
Labels: closed: duplicate
