### ISSUE TITLE
REvenueCat Paywall shows grey screen on top the paywall

### ISSUE THREAD

**Issue by pstatile** [FlutterFlow/flutterflow-issues#997] opened 2023-06-16 13:18 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I include the revenue cat paywall, on certain ocassions (might be that it is the first screen you have when opening the app), it has a grey screen on top of the paywall. BUT, if you click on a link on that page, for an instant before the transition executes the paywall is visible for a fraction of a second. If I click on any other link/button on that page, the paywall shows and works correctly.

### Expected Behavior

Show the paywall without a grey screen on top.

### Steps to Reproduce

Add a paywall. Maybe try to access that page as the initial page of the flow.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFThc/6w5N2rt9G+KniaO5aqGQ7GUMcWOdEl+tuZwgbIoznBu0AYOLeXBdtZO2naVNcG1b9ij00pN3Fhuz9E/pePQyVUY9y+s9+egzke2ihRr64CrrtR2pQM/xRG1S84ZmJvRMnVfZtSE1m12CQP+mQSnXDFOu/Zwh9f6PHaOI=

### Context

Use the paywall. If I click on any other link/button on that page, the paywall shows and works correctly.

### Visual documentation

![IMG_9815](https://github.com/FlutterFlow/flutterflow-issues/assets/50183743/680fd73f-4cee-48bb-b0ae-44f41b1d17a0)

### Additional Info

It should working like this:

![IMG_9817](https://github.com/FlutterFlow/flutterflow-issues/assets/50183743/0e05ec69-1e2b-435e-b7b0-a17950c1a8fe)

### Environment

```markdown
- FlutterFlow version: Last one.
- Platform: iPhone X
- Browser name and version:
- Operating system and version affected: iOS 15
```

**Comment by pstatile** [comment] 2023-06-16 13:25
Here is a likely stack trace info about the problem that I got from firebase crashlytics.

<img width="1313" alt="Captura de pantalla 2023-06-16 a la(s) 10 24 06" src="https://github.com/FlutterFlow/flutterflow-issues/assets/50183743/243a3382-f3f1-4830-862a-ffdcc11945dc">

**Comment by pstatile** [comment] 2023-06-16 13:29
Usually when my users open the app it asks more questions in previous pages. When I get them to the paywall page from another page, the paywall shows Ok. On my iphone that I log in to the app regularly and I have already completed my profile, when I enter since 30 mins ago, in that situation I show directly the paywall page and in that case it happens. 

There was another user reporting this same situation in the FF forum some time ago:  https://community.flutterflow.io/c/discuss-and-get-help/revenuecat-grey-screen. In that situation the user reported that it was a problem of configuration, but I am sure it is not the case because when I enter the paywall page from another page, using the same FF component with the same configuration, it works ok.

**Comment by pstatile** [comment] 2023-06-16 13:49
One thing that I think might be problematic is that inside the paywall component I have the buttons to call the revenue cat Purchase. On that action I use the revenuecat identifier, but I didn't include a default value. I am deploying that default value now in case that helps. If that is the case (yet to be tested if this solves the problem), it would mean that on some situations FF doesn't recover that package identifier from RevenueCat well. 

Here is the default I am adding now to test (that was empty before):
<img width="702" alt="Captura de pantalla 2023-06-16 a la(s) 10 43 40" src="https://github.com/FlutterFlow/flutterflow-issues/assets/50183743/c14b15c4-2b80-4acf-9f7c-a2e01bb8b6e9">


PS: I am not sure if the default is OK given that the identifier is different from iOS than from Android, right? Here is this doubt:
<img width="670" alt="Captura de pantalla 2023-06-16 a la(s) 10 47 44" src="https://github.com/FlutterFlow/flutterflow-issues/assets/50183743/e43f0ba9-93db-41fc-9c4b-30bb194aab36">

I will test this configuration in case it helps. But if indeed it does, it will only clarify that FF is not retrieving the identifier correctly. The weird situation is why if in the case I get the grey screen, if I go to another page from there, for an instant the paywall is visible and OK...

**Comment by aemelyanovff** [comment] 2023-06-22 15:11
@pstatile Thanks for reporting the issue. Can you add specific steps to reproduce, starting from a blank project? Also please add screenshots of your RevenueCat configuration (offerings, entitlements, packages).

If there's no simple way to reproduce the issue in a blank project I suggest reaching out to FlutterFlow support.

**Comment by carinnacostta** [comment] 2023-06-25 21:59
Hello. Did you manage to solve this problem? I have the same problem on iPhone.

**Comment by carinnacostta** [comment] 2023-06-25 21:59
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/34663369/0a1430d1-b599-4437-9822-78fbfcfc07cb)

**Comment by carinnacostta** [comment] 2023-06-25 22:00
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/34663369/01cec47a-30f7-40b8-a306-b0e4d9369391)

**Comment by carinnacostta** [comment] 2023-06-25 22:00
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/34663369/c83a5ef6-bee8-4f99-b651-438266f13ce2)

**Comment by carinnacostta** [comment] 2023-06-25 22:01
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/34663369/0f2f9b50-098b-44f7-8840-e8f2ffb90638)

**Comment by carinnacostta** [comment] 2023-06-25 22:01
How do I resolve the issue?

**Comment by paulVu** [comment] 2023-06-27 06:11
I got the same issue. it's null data from RevenueCat

**Comment by paulVu** [comment] 2023-06-28 01:03
<img width="1157" alt="Screenshot 2023-06-28 at 08 03 07" src="https://github.com/FlutterFlow/flutterflow-issues/assets/5320015/62ee10e5-8b8f-4c0d-9ab0-b3e9c7340f42">
I think may be problem here.

**Comment by aemelyanovff** [comment] 2023-06-30 15:17
@carinnacostta @paulVu Can you add specific steps to reproduce, starting from a blank project?

**Comment by pstatile** [comment] 2023-06-30 15:49
Hi Anton, I can only reproduce on my app since I only test it on
testFlight. What I discovered is that it only brakes (aka grey square over
the component that has the revenuecat paywall) when I access it during the
first 1-2 secs of opening the App. If I had the app already opened (on
background), it works well. For the moment I am trying to do the most
horrible but effective way: I add a Wait action of 1.5 secs and just in
case I do two previous navigation to other pages (instantly). With that, it
works well.
So, I would say that to test it, you should have the revenuecat component
(the one that is in the FF marketplace) and open the app and the homepage
page should redirect to a page where the paywall is. In that case the error
is showing a grey area over the paywall component. I assume that it should
have something to do with the App initialization and something that it is
used to connect to RevenueCat. For sure there is something that takes some
time to load on the FF side and it makes the component go grey. That is why
when you have the grey component and you then click to navigate, for an
instant it shows.
Hope it helps!
Thanks
Pablo

**Comment by carinnacostta** [comment] 2023-06-30 18:35
> <img alt="Captura de tela 28/06/2023 em 08 03 07" width="1157" src="https://user-images.githubusercontent.com/5320015/249317543-62ee10e5-8b8f-4c0d-9ab0-b3e9c7340f42.png"> Acho que pode ser problema aqui.

That was the problem. After I activated, tolerated! Thanks.

**Comment by pstatile** [comment] 2023-06-30 18:59
In my case I had everything in order, both Active in green but even then it
had the problem.

**Comment by paulVu** [comment] 2023-07-05 05:42
I was try to query pricing to display, But it's not work. So I config button to purchase like this. 
<img width="1338" alt="Screenshot 2023-07-05 at 12 42 09" src="https://github.com/FlutterFlow/flutterflow-issues/assets/5320015/fca96937-2790-480c-82ff-4eeb1d5f8a89">

**Comment by carinnacostta** [comment] 2023-07-05 09:46
@paulVu, how did you make the conditional for the restore? When the user clicks on the restore button, he will receive an alert that he does not have an active subscription or if he has, he will be redirected to the landing page. I couldn't do it.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/34663369/3f1b5f46-df66-43f6-8935-87c34d1af18f)

**Comment by paulVu** [comment] 2023-07-05 10:21
I just add the button for Restore, not do anything conditional, it's not a big deed for UX.

**Comment by carinnacostta** [comment] 2023-07-05 10:28
@paulVu What if the user doesn't have a valid signature and clicks the restore button? I wanted something like this.

![IMG_3864](https://github.com/FlutterFlow/flutterflow-issues/assets/34663369/88928525-864e-425e-9b5b-b19f90ddb5d0)

![IMG_3863](https://github.com/FlutterFlow/flutterflow-issues/assets/34663369/13b47f5d-22c9-495c-852c-65137d27d098)

**Comment by paulVu** [comment] 2023-07-06 17:32
I have update user document in firebase. Set a field as "subs" == true. After user sub. But as you say. Maybe it's not right if user cut of the flow. 
- I have created a paywall action if user go to access content of subscribers. Use conditions to check if it's not subscriber - update user document set field "subs" == false. And open the paywall screen again_
I'm going to test that on production. If it's working, will notify you

**Comment by paulVu** [comment] 2023-07-06 17:39
> @carinnacostta @paulVu Can you add specific steps to reproduce, starting from a blank project?

I'm following the blog https://blog.flutterflow.io/in-app-subscriptions-using-revenue-cat/
But can't display the packages from RevenueCat

Now I can't show the price of country. Just show the text in USD.

**Comment by aemelyanovff** [comment] 2023-07-06 20:04
@pstatile @paulVu @carinnacostta In order to troubleshoot an issue we need specific steps to reproduce it from a blank project.

By specific steps to reproduce I mean something like this:
* Create new project
* Enable RevenueCat, add PlayStore/AppStore key.
* Add button with paywall action with entitlement set to xyz.
* Export the code and run it on Android/iOS.
* Tap the button.
* Observe this error.

In addition to steps like that, please include:
* Screenshots of your entitlement/package/product configurations in RevenueCat.
* Full log.

Please create new issues - I'll be closing this one.

If there's no simple way to reproduce the issue in a blank project then I suggest reaching out to FlutterFlow support.

**Closed** 2023-07-06 20:05 UTC
Labels: status: wontfix, status: needs reproducible steps

**Comment by aemelyanovff** [comment] 2023-07-06 20:53
@pstatile @paulVu @carinnacostta Additional information: we will be upgrading RevenueCat package (`purchases_flutter`) to the latest version in the next FlutterFlow release. Maybe it'll help, but I can't say with certainty as I can't reproduce the issue.

**Comment by paulVu** [comment] 2023-07-07 06:21
Thank @aemelyanovff. I will reproduce this in new app. will take note the steps. It's not work will create new issues.

**Comment by paulVu** [comment] 2023-07-08 11:22
Hey @carinnacostta I find what is our issue, I was wrong when I setup 2 `active base plans` in a Subscription on Google Play. as image below:
<img width="736" alt="Screenshot 2023-07-08 at 18 16 58" src="https://github.com/FlutterFlow/flutterflow-issues/assets/5320015/bf516b20-760d-456c-b607-bf9c294cd79a">

It's should create 2 `subscriptions` and 1 ``active base plans` in each subscription. like below. 
<img width="728" alt="Screenshot 2023-07-08 at 18 17 28" src="https://github.com/FlutterFlow/flutterflow-issues/assets/5320015/3e1e3d5f-3e97-4aae-a8be-200d50ba955b">

I share this one. Hope everybody not get this issue.

**Comment by pstatile** [comment] 2023-07-09 13:57
Hi! I think that your logic is wrong. You might very well have 1
subscription with 2 or 3 base plans. The subscription is the concept of
category or what your app allows. Eg. "Premium" or "Gold Subscription" and
"Silver Subscription". Within one type of subscription you might have many
active base plans, eg. "gold_sub_weekly", "gold_sub_monthly" etc.
On the Play Store I have that configuration and I don't think I have a gray
screen.
Thanks! Regards

**Comment by carinnacostta** [comment] 2023-07-09 17:23
Hi @paulVu ! Managed to create conditional for restore button alert?

**Comment by afeezaziz** [comment] 2023-07-12 09:14
I am stuck with the same problem.

It seems that the page will go to grey if the page loads from revenuecat.

<img width="315" alt="Screenshot 2023-07-12 at 5 12 14 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/677026/6f2cb19a-c347-46ba-92fe-bb0f92eed9da">
<img width="942" alt="Screenshot 2023-07-12 at 5 13 31 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/677026/d998cc69-cf23-4326-97e7-c9951f2a408e">
<img width="943" alt="Screenshot 2023-07-12 at 5 13 26 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/677026/e201ff8c-717c-46f9-b1a2-4d27fc4330d6">
<img width="1040" alt="Screenshot 2023-07-12 at 5 12 40 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/677026/0fe5e9ff-9535-46fe-b24a-18c37f1ddd84">

**Comment by pstatile** [comment] 2023-07-12 19:54
I managed to avoid the problem for the moment by redirecting to another
intermediate page and wait 1.5 secs before that. It seems there is some
initial process in FF that still is not ready if you call the paywall when
the app is just opened. If the app has already been open, there is not
problem.
Hoping FF could check it.

**Comment by afeezaziz** [comment] 2023-07-13 01:26
I am still unable to go through the process, despite using your idea of redirecting the page for 1.5seconds.

I also tried with calling the function, then wait for five seconds then call it again.

<img width="444" alt="Screenshot 2023-07-13 at 9 11 02 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/677026/c94e62ef-22be-4f59-a884-16e586f0b1a4">

**Comment by pstatile** [comment] 2023-07-13 13:04
Hi! I feel you are mixing things a bit. The gray screen shows when you
enter the page where the Paywall/RevenueCat component is. When I say I add
a Wait is in my Homepage (initial page) BEFORE redirecting to the page that
has the paywall. With that, the paywall shows OK.

What you have there is the action of the purchase itself. That should work
perfectly according to all the FF documentation. I have newly subscripted
users without any problem. There is a project on the FF marketplace with
the examples to test it on a real device or testflight. Although  that
project has a few texts without default text.
Hope it helps.
Pablo

**Comment by afeezaziz** [comment] 2023-07-14 02:58
I am still unable to run Flutterflow with Revenuecat even when following exactly step by step the tutorial given. :(

I am going to run a few project on the marketplace and test whether this integration works or not. Weirdly so stripe integrations works like a charm.

**Comment by carinnacostta** [comment] 2023-07-15 20:36
Hello! I don't know which thread to put this issue in. But can you help me? I already set up my subscription on RevenueCat, I tested it and it is already working, but in the Google Play and Apple Stores, before installing the app, the user needs to pay and after he has access to the app, he has to pay the subscription too, like Do I configure it so that this initial value does not appear in stores?

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/34663369/458af00c-91a6-49ec-9d88-0b1cd0f57ae3)
