### ISSUE TITLE
Firebase says to "upload dSYM file"

### ISSUE THREAD

**Issue by lovestar18** [FlutterFlow/flutterflow-issues#3036] opened 2024-06-01 13:45 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Firebase says "This app has 3 unprocessed crashes. Upload 1 dSYM file to process them."

This is causing the app to crash very quickly

### Expected Behavior

App does not crash, this error is resolved

### Steps to Reproduce

1. Open app in app store and try navigating to different pages

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hc/1z4ZPj7xG7pSJasExljw5JmF7bIIZkutRaDUsIuOtBqQLPMjOalptXt+5aVNcfFSIgno1+fDGiuPtGsddYBeCRYhG1KgBTzzke2iXWpDXEKi8YWtTN/tYC3K035jUuB1QIvFtLFID3Duyf96ybBDDFOu/Zwh9f6PHaOI=

### Context

Preventing me from sharing my app as it crashes within 5s of opening

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/159853566/0c202857-72ed-49d2-9920-3209c52d1fde

### Environment

```markdown
- FlutterFlow version: v4.1.54
- Platform: Mobie
- Browser name and version:App
- Operating system and version affected: iPhone
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by msusviela** [comment] 2024-06-04 16:19
Hey @lovestar18, Thanks for your report, So sorry you are experiencing this issue. I was not able to reproduce this on a blank project, but it is replicable on yours. That's why I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. Thanks so much!

**Comment by lovestar18** [comment] 2024-06-04 17:25
hi @msusviela - fine to close this issue out as I've contacted support but could you and the team please help with this related issue at your earliest convenience? thank you!

https://github.com/FlutterFlow/flutterflow-issues/issues/3029

**Closed** 2024-06-14 03:09 UTC
Labels: closed: support request
