### ISSUE TITLE
Notifications - not working

### ISSUE THREAD

**Issue by lovestar18** [FlutterFlow/flutterflow-issues#2898] opened 2024-05-13 01:33 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I try to send a notification, it doesn't send to the users and says it's sent to zero devices. I am using the app in test flight and it's not coming through.

### Expected Behavior

The notifications should come through and be sent to my phone

### Steps to Reproduce

1. Open app in test mode (I can grant access)
2. Try sending notification from Flutterflow

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hc/1z4ZPj7xG7pSJasExljw5JmF7bIIZkutRaCsofePrOpkAf8/7UFtUOLS8TXxHPkyJv3IX/MqKjt7DL/YDNSuYc7Zq/qlqWw3iRl2Rb82bDq63b0ZPGZ5NGECby7ejuR1TOsBhdCEF1E6MPOvJYBDcQ6ayDEg/IOaoXdeK2SrDX1iXc2URm05KZDPz

### Context

I'd like to be able to send a daily notification to users

### Visual documentation

[notification.zip](https://github.com/FlutterFlow/flutterflow-issues/files/15288385/notification.zip)

### Environment

```markdown
- FlutterFlow version: 4.1.49
- Platform:Web
- Browser name and version:Chrome
- Operating system and version affected: MacOS
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by hariprasadms** [comment] 2024-05-13 11:04
Hey @lovestar18, Thanks for submitting the issue. I've taken a look at your project, and after testing it locally, I can confirm that it's working fine on both iOS and Android. However, the push notification configuration can be a bit tricky, and there are a few more things to consider.

Here's a link to the FlutterFlow push notification documentation: [FlutterFlow Push Notification Doc](https://docs.flutterflow.io/settings-and-integrations/app-settings/push-notifications). Follow the steps outlined there to ensure everything is set up correctly, especially for iOS.

Another way to check if it's working properly is to log into the Google Cloud Platform console and navigate to the cloud functions of your project. There, you can check the logs related to push notifications. If the settings are correct and everything is working fine, you should see logs generated for notification triggers and APNs generated for each user's login. If these logs are missing, it might indicate that something went wrong with the settings you followed.

Hope this helps!. Please check and let us know how it goes.

**Comment by lovestar18** [comment] 2024-05-13 12:18
Thank you @hariprasadms !

I went through and double checked that I followed these instructions ([FlutterFlow Push Notification Doc](https://docs.flutterflow.io/settings-and-integrations/app-settings/push-notifications)) correctly and I believe I did.

I then went to test the notifications again and got the same result (sent to zero devices). From there, I went into Google Cloud functions to check the logs and it does seem like it's set up properly according to the below - however, I might be missing something. Please let me know your thoughts?

<img width="1026" alt="Screenshot 2024-05-13 at 8 16 17 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/159853566/3a14b4a3-380b-468a-bab9-64faefc67f05">

**Comment by hariprasadms** [comment] 2024-05-15 09:09
Hi @lovestar18 - Thanks for the details. To clarify, the FCM token is generated automatically when a user installs the app and logs in. There's no need to create it manually. I can confirm that the FCM token is being generated successfully for both iOS and Android devices without any issues.

However, in your case, it still seems like there could be a configuration issue. From my end, I've noticed that notifications can be triggered successfully for Android but not for iOS. I'm currently investigating this aspect of the issue.

I would recommend that you try reconfiguring the push notification settings for iOS in a brand new project, following all the steps outlined in the documentation. This way, you can see if the FCM token can be generated without any issues.

Let me know how it goes.

**Comment by hariprasadms** [comment] 2024-05-15 12:29
@lovestar18 - I've labeled this as a bug. In the meantime, if you could update with any additional information after retrying the iOS push notification configurations, that would be greatly appreciated. Thanks.

**Comment by lovestar18** [comment] 2024-05-15 21:49
Thank you @hariprasadms ! I did try again and now it's saying it failed because _Error: Exactly one of topic, token or condition is required_

I'm not sure how but a _FF_push notifications_ collection was made in my firebase. The FCM_Tokens are under the "user collection" per instructions above.

Here's some screenshots and a video of firebase as well as testing in Flutterflow

<img width="1017" alt="Screenshot 2024-05-15 at 5 42 39 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/159853566/eb599b29-d24a-4fa1-bc00-dc622f849e0f">
<img width="834" alt="Screenshot 2024-05-15 at 5 44 54 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/159853566/fd548211-d029-457d-a614-7e8965e6d29e">

**Comment by lovestar18** [comment] 2024-05-17 13:29
Hi @hariprasadms - checking in to see if you have any updates here? thank you!

**Comment by nvimalraj** [comment] 2024-06-03 16:18
One change I had to make in all my projects to get the FCM tokens working is to grant Principal: allUsers, Role: Cloud Functions Invoker. This is because the FCM tokens are added upon the first app opening even before the user logs in, and then when the user is authenticated, the token is added into the firebase user documents. See if this helps.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/68550576/382abeab-a92a-45d0-84f2-8751ea6165b3)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/68550576/d87bfdff-dfb7-479b-b10a-927b63edee4f)

**Comment by lovestar18** [comment] 2024-06-03 16:24
Thank you very much @nvimalraj ! do you by chance have instructions or steps to perform this? Where do I find this in Firebase? Thank you!

**Comment by nvimalraj** [comment] 2024-06-03 16:45
It will be in console.cloud.google.com

Locate the cloud function

Permissions tab

Grant access

**Comment by romerodiesan** [comment] 2024-06-17 19:09
Hello. Any update on it?

**Comment by mmearly** [comment] 2024-06-27 16:22
Hi everyone!

I've taken a look at this issue, and I have come across an issue that can prevent the FCM token from generating properly. If the Firebase project associated with this FlutterFlow project was created automatically through FlutterFlow's create Firebase project feature, and if `iam.automaticIamGrantsForDefaultServiceAccounts` is false (probably because it has been set by the organization your Firebase account is under), we are unable to automatically grant permissions to the service accounts needed to get FCM tokens to generate properly. Fortunately, you are able to manually add these permissions yourself!

First, go to the Service Accounts page in Google Cloud Console. You can get here by going to your firebase project, clicking the gear icon in the top left, Project settings > Users and permissions > the link "Advanced permission settings" near the bottom right corner of the page > Service Accounts on the left.

Here, there should be an email that ends with @appspot.gserviceaccount.com and another that ends with @developer.gserviceaccount.com. Copy these email addresses and put them somewhere accessible, we will need them. 

For each of the emails listed on this page (there may be more than the two you copied), click on the email and then click on the permissions tab. From there click on Grant Access and paste in one of the emails you copied. If given a choice, choose the option ending with "App Engine default service account" or "Default compute service account". Then set the role to "Editor" (you may have to scroll up to basic). Hit Save. Repeat for the second email you copied. Here is a screenshot of what it may look like for one of these entries:

<img width="1492" alt="Screenshot 2024-06-26 at 4 50 12 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/28795229/02ac29d8-0951-4e58-9abb-b248be59be9c">

Finally, we need to add these permissions to the IAM panel. Click on IAM on the left, and follow the exact same process here -- Grant Access, and put the two emails as principal, with the same Editor role as before, save, repeat for the other email.

<img width="1497" alt="Screenshot 2024-06-26 at 4 46 48 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/28795229/cbddf32b-cc44-4720-a9b9-9636bc900688">

Users on your app should now have FCM tokens generated for them, and you should now be able to send them push notifications! If sending a push notification goes wrong after you have confirmed that the FCM tokens are being generated properly, double check that you have uploaded your APN Authentication Key (Firebase > Project Settings > Cloud Messaging > Apple app configuration > APNs Authentication Key), and that your Team ID (should be in all caps), Bundle ID, and App Store ID are all correct (in Firebase > Project Settings > General > Your apps > Apple apps)

**Closed by mmearly** 2024-06-27 16:22 UTC
Labels: status: confirmed, Bug, Notifications, watched by support, Integration Issue

**Comment by ZapeeoSheikh** [comment] 2024-07-05 14:32
@hariprasadms I am facing the same issue, But in my case the notifications generating in ff_push_notification in firebase return message success but did not receive notification. 

Let me confirm:
- ff_push_notifications are creating in firebase on notification generation.


<img width="1168" alt="as" src="https://github.com/FlutterFlow/flutterflow-issues/assets/77886136/61c4faef-5c93-497b-bcce-f60041bdc0a2">


- My FCM token is generating

<img width="1058" alt="xc" src="https://github.com/FlutterFlow/flutterflow-issues/assets/77886136/5ae043c0-1921-4dc8-ade6-3ac3579531b9">

When I am sending it through my flutterflow then it shows "Notification send to 0 user"

<img width="803" alt="dsc" src="https://github.com/FlutterFlow/flutterflow-issues/assets/77886136/092b5fb4-742b-4dfd-9ceb-3839358fb5db">

This is my cloud console below: (I think I am getting error but doesn't know why and how to fix)

<img width="1110" alt="console" src="https://github.com/FlutterFlow/flutterflow-issues/assets/77886136/5972f8a0-941d-4023-9223-acc4b80ce58a">

@mmearly Where I have to uploaded your APN Authentication Key right now I am implementing notifications only for android app. I think I have not uplaod any document of APN anywhere. Please tell me. 

Thanks

**Comment by ZapeeoSheikh** [comment] 2024-07-06 14:33
Update: Issue has been fixed, You can delete your custom function and re deploy it. Thats, all.
