### ISSUE TITLE
Incorrect spacing with Checkbox Group on device

### ISSUE THREAD

**Issue by tinrunje** [FlutterFlow/flutterflow-issues#932] opened 2023-05-25 16:19 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Checkbox Group when uploaded on-device adds "random" additional padding on top. In run/test modes and in the FF editor, it looks as expected, but when uploaded on a device, it changes. Weirdly enough, in code it does say the right amount of padding so there might be an issue with the Checkbox Group widget.

### Expected Behavior

The Checkbox Group should have top-padding equal to the one set in the FF editor/the code.

### Steps to Reproduce

1. Create new page
2. Add Text widget
3. Add Checkbox Group widget
4. Add some top padding on the Checkbox Group (aka. 12px)
5. Push to mobile device 
6. Check spacing on mobile device

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wkMmAuI92mOZE0K6JY+9VmSQWGDs+bec3l+1DYCs/JJTxBIkIffT7PxZeOc+kSmNML1m0gmQe/sLOkvziA+UpEw6cfLZZyJZ+Tg7gUjmtacyVEaqePndfEfhJJVyby7bZ2hN4VdZ1ckFl1Gb7OuivQXLsCYTaIW4nGfiYCJv5gXurQ0SLb3kNh1JWeC/v

### Context

 I am trying to create a beautiful display with evenly spaced elements.

### Visual documentation

The widget tree:
<img width="227" alt="Screenshot 2023-05-25 at 18 15 50" src="https://github.com/FlutterFlow/flutterflow-issues/assets/52575319/13126773-f016-42ba-a65c-8d1e3d7c4e06">

Text widget properties:
<img width="264" alt="Screenshot 2023-05-25 at 18 16 18" src="https://github.com/FlutterFlow/flutterflow-issues/assets/52575319/5a9d0ab0-e6b1-4165-8ea1-3262f1193aa6">

Checkbox Group widget properties:
<img width="300" alt="Screenshot 2023-05-25 at 18 16 58" src="https://github.com/FlutterFlow/flutterflow-issues/assets/52575319/d1d9d526-37a4-4dd1-8c24-ba6b017c775d">

Flutterflow editor:
<img width="553" alt="Screenshot 2023-05-25 at 18 17 13" src="https://github.com/FlutterFlow/flutterflow-issues/assets/52575319/3a38e217-06af-49b0-8bb1-bb3f07dc1582">

And then finally... on a real device:
![IMG_2690](https://github.com/FlutterFlow/flutterflow-issues/assets/52575319/13dedf3a-6d84-48ee-8dc8-61e23b6870e2)

The top-padding on device is much much larger than 12px.

### Environment

```markdown
- FlutterFlow version: 3.7.12
- Platform: MacOS
- Browser name and version: Chrome - 113.0.5672.126
- Operating system and version affected:  iOS/Android
```

**Comment by organicnz** [comment] 2023-05-30 17:27
Hi, @tinrunje. Thanks for reporting this issue, Tin 🙂

Have you tried to reproduce this issue on a web app?

**Comment by tinrunje** [comment] 2023-05-30 17:35
> Hi, @tinrunje. Thanks for reporting this issue, Tin 🙂
> 
> Have you tried to reproduce this issue on a web app?

Yeah thanks for getting back to me. I have only found this issue to be visible only on mobile devices. 
In run/test modes it seems to be fine:
![checkbox group](https://github.com/FlutterFlow/flutterflow-issues/assets/52575319/b19b20da-6030-4e69-845e-c9c8aaa4fff6)

**Comment by organicnz** [comment] 2023-05-31 10:21
> > Hi, @tinrunje. Thanks for reporting this issue, Tin 🙂
> > Have you tried to reproduce this issue on a web app?
> 
> Yeah thanks for getting back to me. I have only found this issue to be visible only on mobile devices. In run/test modes it seems to be fine: ![checkbox group](https://user-images.githubusercontent.com/52575319/242048857-b19b20da-6030-4e69-845e-c9c8aaa4fff6.jpg)

Thank you, Tin :)

Oops, because of this issue, I wasn't able to test it on the virtual mobile device. I'll try again in a few days:

```
Because hybridized depends on flutter_localizations from sdk which depends on intl 0.18.0, intl 0.18.0 is required.
So, because hybridized depends on intl 0.17.0, version solving failed.
```

**Comment by wenkaifan0720** [comment] 2023-06-14 14:53
Hi @tinrunje. This should be fixed in our next update. Thank you!

**Closed by wenkaifan0720** 2023-06-14 14:53 UTC
Labels: type: bug, status: confirmed, closed: fixed
