### ISSUE TITLE
Download code can not run in android studio

### ISSUE THREAD

**Issue by golfamigo** [FlutterFlow/flutterflow-issues#1117] opened 2023-07-14 05:57 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Download code can not run in android studio

### Expected Behavior

normal work.

### Steps to Reproduce

1. download code
2. open in android studio.
3. flutter pub get
4. got intl 0.18.0 issue "Because tool_man depends on flutter_localizations from sdk which depends on intl 0.18.1, intl 0.18.1 is required. So, because tool_man depends on intl 0.18.0, version solving failed. "
5. pubspec.yaml intl: 0.18.0 >> intl: 0.18.1
6. flutter pub get
7. error message "Running Gradle task 'assembleDebug'...
/C:/src/flutter/packages/flutter_test/lib/src/_goldens_io.dart:12:8: Error: Error when reading '../../../AppData/Local/Pub/Cache/hosted/pub.dev/test_api-0.6.0/lib/expect.dart':  No such file or directory

import 'package:test_api/expect.dart' show fail;
       ^
/C:/src/flutter/packages/flutter_test/lib/src/binding.dart:17:8: Error: Error when reading '../../../AppData/Local/Pub/Cache/hosted/pub.dev/test_api-0.6.0/lib/expect.dart':  No such file or directory

import 'package:test_api/expect.dart' show fail;
       ^
/C:/src/flutter/packages/flutter_test/lib/src/_matchers_io.dart:10:8: Error: Error when reading '../../../AppData/Local/Pub/Cache/hosted/pub.dev/test_api-0.6.0/lib/src/expect/async_matcher.dart':  No such file or directory

import 'package:test_api/src/expect/async_matcher.dart'; // ignore: implementation_imports
       ^
/C:/src/flutter/packages/flutter_test/lib/src/matchers.dart:13:8: Error: Error when reading '../../../AppData/Local/Pub/Cache/hosted/pub.dev/test_api-0.6.0/lib/src/expect/async_matcher.dart':  No such file or directory

import 'package:test_api/src/expect/async_matcher.dart'; // ignore: implementation_imports
       ^
/C:/src/flutter/packages/flutter_test/lib/src/_matchers_io.dart:44:33: Error: Type 'AsyncMatcher' not found.
class MatchesGoldenFile extends AsyncMatcher {
                                ^^^^^^^^^^^^
/C:/src/flutter/packages/flutter_test/lib/src/_matchers_io.dart:120:3: Error: Type 'Description' not found.
  Description describe(Description description) {
  ^^^^^^^^^^^
/C:/src/flutter/packages/flutter_test/lib/src/_matchers_io.dart:120:24: Error: Type 'Description' not found.
  Description describe(Description description) {
                       ^^^^^^^^^^^

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8Slcr1z89IsdtJ+Kryb8ZB/WARKVg5argRiu1qEA8gF5CuEooPe/SkP1ZvTf2+SnxbPWGZmjgyw9bMmdOeJsFdKUytfNlt/qpMFjvvXmaVRZODGbWSZnZ7INxMIG6i3KbV2iJTD/ptS3wM2mGUOPaSXibAN5zFO2onOMi1OdnM+W/hG3iyFxZszRUMLGWgEcsubQuMoIuUtpJh0eDnyw==

### Context

I need to run the code in android studio.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/30447225/e1d2b996-e0bf-44d3-a673-d50fefd4df53)

### Additional Info

[bug.txt](https://github.com/FlutterFlow/flutterflow-issues/files/12046712/bug.txt)

### Environment

```markdown
- FlutterFlow version: 
- Platform: windows 10 home
- Browser name and version: chrome 114.0.5735.199
- Operating system and version affected: Windows Feature Experience Pack 1000.19041.1000.0
```

**Comment by kevintonb** [comment] 2023-07-14 09:42
Hey @golfamigo , this issue usually occurs when the Flutter SDK version in your local machine is not compatible with the project version in your Flutterflow project. However, the Github Issue Tracker is meant to track and resolve bugs that are found within Flutterflow and are identifiable and reproducible. And since this isn't necessarily a bug within Flutterflow, I'm closing this issue for now. On another note, feel free to reach out to our support team via support@flutterflow.io if you face any other issues like this while building your app.

**Closed by kevintonb** 2023-07-14 09:42 UTC
Labels: status: needs triage
