### ISSUE TITLE
Mac Desktop App scrolling not working

### ISSUE THREAD

**Issue by John-DreamLabs** [FlutterFlow/flutterflow-issues#1455] opened 2023-09-14 17:20 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using the desktop app on the latest MacOS, the scrolling does not work, or if it does, it's very sporadic. When I select a different window, the scrolling works. See video for more details. This is true for every project I work on and has been persisting for as long as the app has been available. 

https://www.loom.com/share/a8a0341074964b699c1349c16c372a05?sid=1211864f-5b74-42f0-8c20-06ba1291ee81

### Expected Behavior

I can scroll the cavas freely (if the screen is set up for scrolling)

### Steps to Reproduce

1. create a screen with enough content to scroll
2. enable scrolling for the screen
3. try to scroll
4. click out of the window and try to scroll

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTis/qw89Irsdc+Kn6YcExhioWI0MfWOdEket+EA0hfIjuE4YXdc6lbk5LYte4enw3HGH+pFwdpKHQivz1KsFfHyqrc6Fy/75XQQ7NQjijaZCMO5GaRXBREtFhIHa94KeFviJAXftickIO1F2II/CdG3qCf9qOYwx5e6fDbOY=

### Context

I would love to use the app over the web based version

### Visual documentation

https://www.loom.com/share/a8a0341074964b699c1349c16c372a05?sid=7070196c-458f-4a45-a765-970056c0047e

### Environment

```markdown
- FlutterFlow version: v1.1.101 (desktop app)
- Platform: MacOS
- Browser name and version: n/a
- Operating system and version affected: Ventura 13.4.1 (c)
```

**Comment by victoriahuang1** [comment] 2023-09-18 22:50
@John-DreamLabs are you only experiencing this issue on the desktop app?

**Comment by John-DreamLabs** [comment] 2023-09-19 00:21
@victoriahuang1 correct, scrolling works perfectly if I'm using the browser

**Comment by victoriahuang1** [comment] 2023-09-19 23:48
@John-DreamLabs , unfortunately we are not able to reproduce the issue. As such, we will be closing this issue for now.

The one thing that I did notice was that it can take a couple of tries with trackpad for scrolling to be recognized, but the mouse's scroll is always reliable for me.

Feel free to let us know if you figure out more insights behind the sporadic scrolling behavior.

**Closed by victoriahuang1** 2023-09-19 23:48 UTC
Labels: status: needs triage

**Comment by John-DreamLabs** [comment] 2023-09-20 22:09
@victoriahuang1 I just did some additional testing. I am able to scroll when using the macbook trackpad. However, I am NOT able to scroll when using the Apple Magic Mouse.

**Comment by victoriahuang1** [comment] 2023-09-20 22:56
Thank you for looking into this! It seems like there is some issue with recognizing the magic mouse scroll, in that case.

I will keep this ticket closed for now, as there isn't an easy solution for us to support magic mouse. But we will update if Flutter comes up with a better solution!
