### ISSUE TITLE
For iOS App, bluetooth-central key is not added to UIBackgroundModes array in info.plist

### ISSUE THREAD

**Issue by Omrankabalan** [FlutterFlow/flutterflow-issues#1682] opened 2023-10-21 08:44 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I've successfully added Bluetooth permission for my app, and it's functioning well on Android. However, we've received reports of numerous crashes related to Bluetooth functionality on iOS apps, accompanied by the following error message.

Fatal Exception: NSInternalInconsistencyException
State restoration of CBCentralManager is only allowed for applications that have specified the "bluetooth-central" background mode

Upon investigating the issue, it appears that the problem because of a missing key, 'bluetooth-central,' in the UIBackgroundModes. in Info.plist file.

### Expected Behavior

The generated Info.plist should contain 

` <key>UIBackgroundModes</key>`
` <array>`
     `  <string>bluetooth-central</string>`
` </array>`

### Steps to Reproduce

1. Add Bluetooth printing functionality to your project.
2. Run IOS app.
3. App crashes when trying to use Bluetooth functionality.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXz8mBy891rsxE+rnib8AwtD8wGUwbUOc7j9VEGAsjCeKuELMcf/TOU1hWSOqHTH1AA078hXIE0/vIvuH9V/U4JSiubJxazKlhUxDhXn66VbqqBbmaOUF8HcVXfHKm0MO3vSQmOs1ZcXAW7V+Aetyub3qCf9qOYwx5e6fDbOY=

### Context

In My App, the Bluetooth functionality is not meeting expectations. Without the necessary permission set, the iOS app crashes when attempting to utilize Bluetooth for printer functionality.

### Visual documentation

![1](https://github.com/FlutterFlow/flutterflow-issues/assets/23256211/1252618d-7e23-41b6-91b6-6b6eedd63c19)

### Environment

```markdown
- FlutterFlow version: v3.1 
- Platform: Web
- Browser name and version: Chrome Version 118.0.5993.89
- Operating system and version affected: IOS App
```

**Comment by Omrankabalan** [comment] 2023-10-30 12:38
Hey @hariprasadms , any updates on this? Users still can't print due to the bug. Appreciate your help!

**Comment by Omrankabalan** [comment] 2023-11-08 11:39
Hey @hariprasadms  @sbis04 , this issue is causing crashes on IOS devices! Urgent updates needed ASAP!

**Comment by payminty-shaun** [comment] 2023-11-14 21:29
Hi team, I also need this issue resolved as I require the `bluetooth-central` permission for the package https://pub.dev/packages/mek_stripe_terminal

Thanks

**Comment by sbis04** [comment] 2024-01-22 03:12
In both cases, it looks like the `bluetooth-central` permission is required because of some external dependency. We already have a feature improvement on board to allow these permission types as "Custom Permission" on iOS. I'll mark this as a feature improvement and I'll close this as it's not a bug.

**Closed by sbis04** 2024-01-22 03:12 UTC
Labels: type: bug, status: confirmed

**Comment by tracedaily** [comment] 2024-09-25 16:16
@sbis04 - There are multiple issues that have been closed regarding this issue (https://github.com/FlutterFlow/flutterflow-issues/issues?q=uibackgroundmodes). 

If it's closed as a "feature / enhancement request" - how do we track the feature development status? Is it even being tracked? Can I submit this as a feature request somewhere else? It adds like 45 minutes to my deployment process each time because I have to manually add "<string>location</string>" to the UIBackgroundModes array in info.plist. Then build an archive with xcode, and deploy manually.
