### ISSUE TITLE
On Page Load Actions on an Initial Page Prohibit all subsequent navigation

### ISSUE THREAD

**Issue by glamourhammer** [FlutterFlow/flutterflow-issues#1252] opened 2023-08-12 05:21 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

It is impossible to navigate within a FlutterFlow app if there is an On Page Load navigation Action set on an Initial Page.

After authenticating, regardless of which widget or action is performed by the end-user, the user is always redirected to the Initial page, thus repeating the prescribed navigation flow an precluding any subsequent navigation or use within the app.

### Expected Behavior

The user should NOT be redirected back to the initial page and should be able to navigate freely within the app.

To reiterate, this behavior only occurs when there is an On Page Load action set on an Initial page.

### Steps to Reproduce

1. Create an app
2. On an Initial Page (Entry Page or Logged In Page) set an On Page Load Action to direct the user to some page within the app.
3. On the demised page, attempt any navigation.
4. Observe that the Initial Page is reloaded, thus triggering the On Page Load navigation Action back to the original page.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEelcmA7ZFJn7wE0bXXYcdsrwMwJ0QlUIInj+0bWRMhfLKuE+0UPPT8T1tLYtfkfXw/JVWghnsFzMrPiuHuGsc6NTmqc4B/zpRXQQ3MTl6lbL6RO6ieWnZ7N8dTIFCM15mzohElNttYWVYi2V+AA/CdG3qCf9qOYwx5e6fDbOY=

### Context

I cannot navigate within or otherwise use the app if there is a page load action set on the Initial Page. It is a critical error.

Within my app the bug behaves per the following:

The Initial page performs 2 actions:

1. checks to see if an authentication token is valid via an api call to a 3rd-party (Xano) backend)
2. If the token is INVALID, the user is directed to the authentication page. If VALID, the user is authenticated and redirected to a subsequent page based on conditions.

After authenticating, regardless of which widget or action is performed by the end-user, the user is always redirected to the Inital page and thus repeating the authentication flow as outlined above.

### Visual documentation

[Screen recording 2023-08-12 2.15.14 PM.webm](https://github.com/FlutterFlow/flutterflow-issues/assets/92355591/61ef3565-8ddf-4cb2-ae6c-19c1b37777b5)

### Additional Info

![Screenshot 2023-08-12 2 20 47 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/92355591/25d25d4c-4c8d-45a7-adf4-7f16bd4230e1)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Chrome Version 116.0.5845.67 
- Operating system and version affected: ChromeOS Version 116.0.5845.67
```

**Comment by schox** [comment] 2023-08-15 07:02
I think I am seeing the same problem where I get directed to the default logged in page without navigating to it. My default logged in page has page navigation as part of the on page load action. This is a new problem which I first noticed on August 9th. It is a critical error for me tii.

**Comment by kevintonb** [comment] 2023-08-16 06:55
Hey @glamourhammer , thank you for reporting this to us. As per the auth setup in Flutterflow apps, the entry page will only be accessible to users who are unauthenticated. This is to ensure that logged in users do not visibly fall back into the authentication flow. Similarly, the 'Logged in page' will only be accessible to users who are successfully authenticated. And these are the respective pages that are present in the navigation stack for the user with either of the auth states when they launch the app. Since authentication is completely managed by firebase, if you think the user needs to be sent back to the authentication page when the backend call fails, you will need to log out the user and not navigate the user to the authentication sequence. This is because, firebase preserves user auth states and the managed authentication auto-navigates the user as per the authentication state. This is an expected behaviour while using Firebase with Flutterflow and not a bug within the platform. I'm closing this issue for now as this is not a bug, but please feel free to provide any further information if you think there is a bug present and we can reopen this issue :)

**Closed by kevintonb** 2023-08-16 06:55 UTC
Labels: status: needs triage

**Comment by schox** [comment] 2023-08-16 07:56
This is most definitely a bug with respect to the default logged in page. Shall I provide more details here or open a new bug? I have got a sample project which shows it. This bug was not there before and I cannot find a workaround for it at present.

**Comment by glamourhammer** [comment] 2023-08-17 02:11
Per my previous comment, to better help the FF team identify, isolate and ultimately fix this bug, please allow me to share a new user-case example that excludes authentication.

In the OnPageLoad Action of the LoggedInPage, the user is directed to 1 of 2 pages based on a Conditional (Bool). In the supplied screen recording, kindly note that no further navigation within the app is possible because the OnPageLoad Action of the LoggedIn page is invoked before any other Action can fire.

Note that this issue is likely related to, and may be the same as issue [#1279](https://github.com/FlutterFlow/flutterflow-issues/issues/1279)   opened by @schox who previously commented on this issue.

![Screenshot 2023-08-17 10 55 32 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/92355591/5cdca2f0-eb5b-495c-aea7-14c6cc6979df)
[Screen recording 2023-08-17 10.58.40 AM.webm](https://github.com/FlutterFlow/flutterflow-issues/assets/92355591/5a036faa-a304-45b8-86f5-923818fd583e)
