### ISSUE TITLE
Error when I try create a new Branch.

### ISSUE THREAD

**Issue by ebaudson** [FlutterFlow/flutterflow-issues#3302] opened 2024-07-02 19:14 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I try to create a new branch in FlutterFlow, it shows an error message: 'Unexpected CFE, internal, null, INTERNAL.'

### Expected Behavior

It is expected that it only creates the branch.

### Steps to Reproduce

1. Open my project
2. Click on 'Branching'
3. Click on 'Create a new Branch'

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48iPHl+YlIschE7c+BbfpV+TssKUc7RoE7m+wacwo8J5zKB+wAYvf7P1FWTL2oTQhIMWCJsDsxxvfqj9r2UfYVOTubfohIz5Z2SQ/KfH2VaKquDKmzfW1QBp9NClCMyMKRvgpBOtt2dHgs6mC2AemRTjftJZDXOVQzAMmlKdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/57355847/42c84380-b453-4145-bf56-c7eb351752af

### Environment

```markdown
- FlutterFlow version: v4.1.64
- Platform: MacOS Desktop
- Browser name and version: Arc 1.49.0(51346)
- Operating system and version affected: macOS Sonoma 14.5(23F79)
```

### Additional Information

In blank project this error don't exists.

**Comment by msusviela** [comment] 2024-07-02 19:24
Hey @ebaudson, Thanks for your report, So sorry you are experiencing this issue. I was not able to reproduce this on a blank project. That's why I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. Thanks so much!

**Closed as not planned** 2024-07-02 19:24 UTC
Labels: status: can't reproduce

**Comment by grivdm** [comment] 2024-07-05 22:47
Got the same issue. By the way, branching works properly in a duplicated project.
