### ISSUE TITLE
text field/keyboard dismiss

### ISSUE THREAD

**Issue by aaronmt93** [FlutterFlow/flutterflow-issues#1543] opened 2023-09-27 18:50 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

when using the text field widget, there is a blue highlight that shows up on the last letter in the textfield that doesnt show up in test or preview mode. see video. additionally, when using with a listview to do a search, the keyboard doesnt dismiss when i click on the list view or scroll around in the widget despite having hide keyboard on tap enabled. this is happening on my phone in IOS 17. 

https://github.com/FlutterFlow/flutterflow-issues/assets/138043801/44c0c706-aa37-4812-89a7-25f133087c75

### Expected Behavior

there should be no blue highlight, just the divider. additionally, the keyboard should dismiss when interacting with the listview. 

### Steps to Reproduce

1. create a page. 
2. add a columm. 
3. add a textfield. 
4. add a listview. 
5. add components to listview. 

also hide keyboard on tap should be enabled. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gismBy4x1obhK7aX6bu9V/T04JWIhaJc0sdlud0wdCoDuBIk+ZPXsSBRBcMu6dGxpekSmmlE0pfDtkezLL/pcAAqWGIhqzpNIVAmWRTiiQZOBC5G0OURREcNTJlyA17bU3yVCWfV1SkFh2jm6F++sVnXqJoC3IlFISq/LZO4=

### Context

textfield is a core component of the project and this makes the UI unusable. additionally, dimissing the keyboard in a search context is a pretty standard feature in most apps when scrolling through searches and as of now it doesnt work. 

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/138043801/749e2993-7407-472e-a2bd-5b49cd8ec79d

### Environment

```markdown
- FlutterFlow version: 4.0 3.10.4
- Platform: Iphone, IOS 17
- Browser name and version:Chrome and IOS 17
- Operating system and version affected: IOS 17
```

**Comment by hariprasadms** [comment] 2023-10-03 11:35
Hi @aaronmt93 - Thanks for submitting the issue. I just looked at the project you provided above. It is not a blank project with issue setup. Considering the nature of the issue, we need blank project with issue setup steps. Without these details, its challenge for us to investigate and locate the issue in the project. In order to keep our issue tracker useful and maintainable for all users, please follow the bug report template while reporting bugs. 

However, I have tested above points in my projects and apps. These are working as expected. 

1. Blue highlight around cursor - It is working fine. It could be specific to your device settings. I would suggest check this in other text field widgets and see if there is same behaviour. 
2. Hide the keyboard on tap - This works when you tap on page area ( scaffold area ) but in your page design, there is no page area is exposed to take tap action. Hence it is not working. You should adjust the design accordingly. 

I hope this can help you.

**Comment by aaronmt93** [comment] 2023-10-05 16:49
right @hariprasadms it only happens on real devices. is there a path to getting it fixed on point 1?

**Comment by aemelyanovff** [comment] 2023-11-03 19:28
It's an issue in Flutter itself: https://github.com/flutter/flutter/issues/128406 It should get fixed in FF when Flutter is upgraded.

Closing the issue because it's not a bug in FlutterFlow and it's something we have no control over.

**Closed by aemelyanovff** 2023-11-03 19:28 UTC
Labels: type: bug, status: confirmed
