### ISSUE TITLE
Flutterflow for windows is not starting anymore

### ISSUE THREAD

**Issue by snowboarder** [FlutterFlow/flutterflow-issues#3322] opened 2024-07-05 18:36 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The flutterflow windows app isn't starting anymore.  I have even tried reinstalling it from scratch after redownloading it.   After logging in on google account it goes into a continuous loading state and never loads. Sometimes it even crashes when I start it up.

### Expected Behavior

Get past the loading screen and load the UI

### Steps to Reproduce

start flutterflow for windows
login if asked
never goes past loading screen

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

none because i cant open

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/1418909/eccd8268-b2fe-44e7-9747-c4d048352f5b)

### Environment

```markdown
- FlutterFlow version: latest windows version on your website as of 7/5/24
- Platform: windows 11
- Browser name and version: chrome
- Operating system and version affected: windows 11
```

### Additional Information

just started happening today

**Comment by rzambroni** [comment] 2024-07-05 18:46
Hey @snowboarder, could you try the workarounds provided on this ticket: [https://github.com/FlutterFlow/flutterflow-issues/issues/3315](https://github.com/FlutterFlow/flutterflow-issues/issues/3315)

Closing this one as duplicate of the above, please feel free to interact in that thread.

**Closed as not planned** 2024-07-05 18:45 UTC
Labels: closed: duplicate

**Comment by snowboarder** [comment] 2024-07-05 19:19
> Hey @snowboarder, could you try the workarounds provided on this ticket: #3315
> 
> Closing this one as duplicate of the above, please feel free to interact in that thread.

@rzambroni That did not resolve the issue

**Comment by rzambroni** [comment] 2024-07-05 19:22
It might be better for you to reach out to support as there is not much else we can do from here.

Sorry about that.

**Comment by snowboarder** [comment] 2024-07-05 19:24
How do I reach out to support?  Seems like FF makes that a bit difficult contact support as I have yet to find that option.

**Comment by leighajarett** [comment] 2024-07-08 09:13
Support@flutterflow.io 🙂
