### ISSUE TITLE
Android build failed due to sign_in_with_apple package on flutterflow desktop app local run

### ISSUE THREAD

**Issue by David-codes0** [FlutterFlow/flutterflow-issues#2748] opened 2024-04-16 22:00 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Launching lib/main.dart on Android SDK built for arm64 in debug mode...
Upgrading build.gradle
Running Gradle task 'assembleDebug'...                          

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sign_in_with_apple:parseDebugLocalResources'.
> Could not resolve all files for configuration ':sign_in_with_apple:androidApis'.
   > Failed to transform android.jar to match attributes {artifactType=android-platform-attr, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for PlatformAttrTransform: /Users/mac/Library/Android/sdk/platforms/android-28/android.jar.
         > /Users/mac/Library/Android/sdk/platforms/android-28/android.jar

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
Running Gradle task 'assembleDebug'...                             17.7s
Error: Gradle task assembleDebug failed with exit code 1

### Expected Behavior

to build successfully 

### Steps to Reproduce

create a project on flutterflow with firebase
test  on local run or download code and test

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

What went wrong: Execution failed for task ':sign_in_with_apple:parseDebugLocalResources'. > Could not resolve all files for configuration ':sign_in_with_apple:androidApis'.    > Failed to transform android.jar to match attributes {artifactType=android-platform-attr, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.       > Execution failed for PlatformAttrTransform: /Users/mac/Library/Android/sdk/platforms/android-28/android.jar.          > /Users/mac/Library/Android/sdk/platforms/android-28/android.jar

### Context

i wanted to run my project locally through the Flutterflow desktop app, because I normally download the code and then remove the sign-in with Apple package in order to successfully build and test on an android emulator

### Visual documentation

<img width="1440" alt="Screenshot 2024-04-16 at 9 58 54 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/99376236/be0bf27d-9d94-4dfb-a21a-5462c0160788">

### Environment

```markdown
- FlutterFlow version: v4.1.39
- Platform: macos os app
- Browser name and version:nil
- Operating system and version affected: Mac os
```

**Comment by paulperez-dev** [comment] 2024-04-17 02:25
Hi @David-codes0, thanks for your report. I need the bug report code from a blank project that replicates the issue. Can you please provide it? <br><br>Here is how you can [get the bug report code](https://docs.flutterflow.io/widgets-and-components/widgets#get-bug-report-code).

**Comment by David-codes0** [comment] 2024-04-17 23:36
https://app.flutterflow.io/project/test-app-e82t24?tab=appSettings&appSettingsTab=firebase 
this is a blank project i just create
![Uploading Screenshot 2024-04-18 at 12.36.37 AM.png…]()

**Comment by David-codes0** [comment] 2024-04-17 23:38
it still same issue while i was trying to test on an android device  
Launching lib/main.dart on Android SDK built for arm64 in debug mode...
Upgrading build.gradle
Running Gradle task 'assembleDebug'...                          

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sign_in_with_apple:parseDebugLocalResources'.
> Could not resolve all files for configuration ':sign_in_with_apple:androidApis'.
   > Failed to transform android.jar to match attributes {artifactType=android-platform-attr, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for PlatformAttrTransform: /Users/mac/Library/Android/sdk/platforms/android-28/android.jar.
         > /Users/mac/Library/Android/sdk/platforms/android-28/android.jar

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 51s
Running Gradle task 'assembleDebug'...                             52.7s
Error: Gradle task assembleDebug failed with exit code 1

**Comment by paulperez-dev** [comment] 2024-04-18 02:51
@David-codes0 Android does not support Apple sign-in, it should not throw an error on Android. Did you follow the steps described [here](https://docs.flutterflow.io/data-and-backend/firebase/authentication/apple-sign-in)?

**Comment by David-codes0** [comment] 2024-04-18 06:11
i have not integrated Apple sign-in or any sign-in method on the blank project. it is only connected with Firebase. 
Testing my project on Local run through my android shouldn't throw any error about apple sign in since it is not used in my project

**Comment by David-codes0** [comment] 2024-04-18 06:11
please confirm this at your end

**Comment by paulperez-dev** [comment] 2024-04-20 23:32
Hey @David-codes0, I was unable to reproduce this on a blank project. I suspect this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: support@flutterflow.io or using the in-app chat inside of FlutterFlow. <br><br>I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. <br><br>Thanks so much!

**Closed** 2024-04-20 23:32 UTC
Labels: closed : project specific
