### ISSUE TITLE
Activity page not working

### ISSUE THREAD

**Issue by lovestar18** [FlutterFlow/flutterflow-issues#3023] opened 2024-05-31 01:32 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I've tried troubleshooting this with support for several weeks but have had no luck. The 'activitypagecopy' isn't working

### Expected Behavior

Shows when people have liked or replied to a post

### Steps to Reproduce

1. Create a post for one user
2. Have a 2nd user like the post
3. See if it shows on the 1st user's activity page

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hc/1z4ZPj7xG7pSJasExljw5JmF7bIIZkutRaCotCLbkOpgcf/fOYkRvTeGiSmxceGGZmWoW3PvIk/DPL/QBA0+uQYh9yboJFjr/Vke6b4y1FJWgdEBPHp5Qf33GyLbYghFAKu9vc1Y/3zm6F96sfA/dHYT1DGwsDq/LZO4=

### Context

It's been preventing me from sharing my app for a few weeks

### Visual documentation

<img width="761" alt="Screenshot 2024-05-30 at 9 29 32 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/159853566/91e927f2-77c1-4c4d-8625-66682aadb975">
<img width="256" alt="Screenshot 2024-05-30 at 5 12 51 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/159853566/7e44d999-4d20-45bc-8559-62fb47c16212">

### Environment

```markdown
- FlutterFlow version: 4.1.54
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: MacOS
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by msusviela** [comment] 2024-05-31 13:41
Hi @lovestar18 - Thanks for submitting the issue. I've taken a look at your project, but with a lot going on, it's challenging to pinpoint the issue. Given the nature of the problem you're highlighting, we need a blank project with the issue steps set up in it. Without these details, it might be a bit challenging for us to investigate the issue. Please provide the required information. If the issue is already resolved for you, please feel free to close the issue. Thanks!

**Comment by lovestar18** [comment] 2024-05-31 14:09
Thank you @msusviela ! I've created a new project here (https://app.flutterflow.io/project/starsoflovenew-5dkjw4?tab=pageSelector&page=deleteaccount) that only has the "social network" aspect - does this provide what is needed?

Thank you!

**Comment by msusviela** [comment] 2024-07-04 20:46
Hi @lovestar18. So sorry for the late response. Is this still an issue for you?

**Comment by msusviela** [comment] 2024-07-09 16:56
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Closed** 2024-07-09 16:56 UTC
Labels: closed: other
