### ISSUE TITLE
Test mode silent errors in the console

### ISSUE THREAD

**Issue by AdrKacz** [FlutterFlow/flutterflow-issues#4967] opened 2024-11-25 08:26 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When running test mode in the browser, you can see an error being raised every seconds in the Console: `FormatException: SyntaxError: JSON.parse: expected property name or '}' at line 1 column 2 of the JSON data`.
This can be reproduce from a blank project so I assume it is not due to any configuration of a project but rather a problem in the Test mode itself.

The error doesn't block you from debugging **however** it makes reading the logs *very annoying* because it creates a lot of noise.

### Expected Behavior

I expect to not see unexpected error messages.

### Steps to Reproduce

1. Create a new project
2. Start test mode
3. Open your browser
4. Open the Inspector and the Console
5. See the errors after a few seconds

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Not relevant

### Visual documentation

<img width="1417" alt="Screenshot 2024-11-25 at 08 25 55" src="https://github.com/user-attachments/assets/18db7f28-7161-4d43-a536-81172aa476e9">

### Environment

```markdown
- FlutterFlow version: 5.0.13
- Platform: Desktop
- Browser name and version: Firefox, 132.0.2
- Operating system and version affected: MacOS
```

**Comment by Alezanello** [comment] 2024-11-25 12:43
Hello!

I followed the steps you mentioned, but I wasn’t able to reproduce the error in a newly created project. <br><br>Here’s the public link to the project:[ https://app.flutterflow.io/project/qa-3117-1e2d5m](https://app.flutterflow.io/project/qa-3117-1e2d5m). <br><br>You can clone it and test it yourself to see if the issue occurs on your end.

As an additional suggestion, you might want to try downloading your project’s code and running it locally to check if the error persists. This can help identify if the issue is specific to your project

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/3c699d46-cea4-4927-bc82-79e84d73c0c3/6547c7d2-3187-4c85-b003-c6c7a377425e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zYzY5OWQ0Ni1jZWE0LTQ5MjctYmM4Mi03OWU4NGQ3M2MwYzMvNjU0N2M3ZDItMzE4Ny00Yzg1LWIwMDMtYzZjN2EzNzc0MjVlIiwiaWF0IjoxNzMyNTM4NTg2LCJleHAiOjMzMzAzMDk4NTg2fQ.TKYNGnxF5qa1XJjpUAxKTZR7xZ668lKfiA4swsIK2mk " alt="image.png" width="1917" height="909" />

**Comment by AdrKacz** [comment] 2024-11-25 22:30
Thank you for investigating! Looking at your screenshot it looks you are using Chrome and not Firefox like I mentioned in my bug report, am I correct?

If you are indeed using Firefox, I will have better look at this issue and send you a more details bug report.

**Comment by Alezanello** [comment] 2024-11-27 19:19
Hello!!<br><br>Just checked in Firefox too and got 0 issues on the console, did you find anything else?

**Comment by AdrKacz** [comment] 2024-11-28 12:52
I can reproduce from the starter **Travel App** project. I created the app, didn't change anything, and select the Run button top left which opened Firefox. Here I can see the errors:

<img width="786" alt="Screenshot 2024-11-28 at 12 49 17" src="https://github.com/user-attachments/assets/e8e38dd1-6aa1-4787-a10e-3b3d009ba74d">

Then I created a completely blank project and hit run just after creation without editing anything, and once again I can see the errors:

<img width="1412" alt="Screenshot 2024-11-28 at 12 52 10" src="https://github.com/user-attachments/assets/bf96ddd3-dd83-44b0-b64e-915fde7fbdbf">

**Comment by AdrKacz** [comment] 2024-12-01 10:55
Let me know what additional information I can provide to either mitigate on my side or fix on your side *(if it has to be fixed)* 👍

**Comment by Alezanello** [comment] 2024-12-03 18:35
If this issue only occurs in test mode and on certain browsers, but does not impact the app itself, it’s likely related to Flutter DevTools or a similar environment-specific factor rather than an issue with FlutterFlow.

**Comment by AdrKacz** [comment] 2024-12-03 21:57
This is possible, but I'd rather be sure of it as it really prevents development. The console is overflowed with message making it completely unusable (there are so many error message that keeping the console open for a few seconds crashes my computer).

It is possible also that the error comes from the website used by FlutterFlow for the Test/Run mode, this website is **not** own or made by Flutter.

To be honest, I'd say it's more likely the errors comes from a parsing error from your side rather than Flutter DevTools. The errors really look like JSON parsing errors and DevTools don't have this kind of issues.

Did you manage to reproduce? If not, let me know if you need special trace to fix this issue blocking development. As of now I'm able to reproduce from any browsers from a blank project.

Out of curiosity, are you testing from Windows or MacOS ? I'm working from MacOS, if you are testing from Windows and you don't see the errors this is a good insight.

**Comment by Alezanello** [comment] 2024-12-06 14:15
Let’s try something to troubleshoot this further. Could you make the project public and share the link with me? I’ll clone it and test it directly. I’ll also screen record the process to show you the results.

I’m testing on both macOS and Windows, but that shouldn’t be an issue since the error appears to be coming from the `main.dart` file. This means it likely isn’t platform- or browser-specific.

Looking forward to your response!

**Comment by Alezanello** [comment] 2024-12-11 17:30
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Closed as not planned by Alezanello** 2024-12-11 17:30 UTC
Labels: status: can't reproduce

**Comment by AdrKacz** [comment] 2024-12-12 10:00
So sorry, I didn't see the notifications for your reply.

I'll share the public project in a new issue, thank you!
