### ISSUE TITLE
Cannot delete Action (iPad app)

### ISSUE THREAD

**Issue by ableinc** [FlutterFlow/flutterflow-issues#1742] opened 2023-10-30 19:48 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When trying to delete an Action by tapping the Action Options icon it only displays the hint of what the Action Options is and not the actual options

### Expected Behavior

1. Drag Widget onto page
2. Go to Actions in properties sidebar
3. Tap Open Actions button
4. Create any action
5. Tap Action Output button (top right corner)
6. Action Options appear

### Steps to Reproduce

1. Drag Widget onto page
2. Go to Actions in properties sidebar
3. Tap Open Actions button
4. Create any action
5. Tap Action Output button (top right corner)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4giMjfsI52ocMA+KnfLe9Wr2Q7HG18R600ttluGBYjfaLyDYkIec/6PhdCOebjY1Y7OGC2p14CwNrmjdnAGO07Mk2BfJhywZAIEQvgZD2QMKmTF7uoYn8lRJljBWqP0J23uRImJrJpdGRnwEOuN+SRExfdJO/WPXo4Sq/LZO4=

### Context

I cannot delete an action from any widget while working on the FlutterFlow iPad app

### Visual documentation

![IMG_0003](https://github.com/FlutterFlow/flutterflow-issues/assets/26948458/61dabd11-3f82-416a-b057-a6838d5d33dd)

### Environment

```markdown
- FlutterFlow version: 4.1.4
- Platform: iPad
- Browser name and version:
- Operating system and version affected: iPadOS 17.1
```

**Comment by sirian-m** [comment] 2023-10-30 23:22
Ran into this issue as well in a bunch of other places on the iPad app. Also can't copy an action, and sometimes the tooltip also blocks other taps like to got to the action editor tab.

**Comment by sbis04** [comment] 2023-10-31 02:18
There's already an issue about this open: https://github.com/FlutterFlow/flutterflow-issues/issues/1735. Closing this one as a duplicate.

**Closed by sbis04** 2023-10-31 02:18 UTC
Labels: status: needs triage

**Comment by ableinc** [comment] 2023-10-31 21:20
The duplicate was closed claiming the issue was fixed in a previous version offered the application, but the issue still persists. 

This issue should be reopened.

**Comment by sbis04** [comment] 2023-11-01 02:45
Hey @ableinc, I can't reproduce the issue on the latest version (the menu seems to open fine for me now). Can you confirm which version are you on?

![IMG_217EFABBBDF0-1](https://github.com/FlutterFlow/flutterflow-issues/assets/43280874/e0d50721-4948-4e64-a40f-c5af2e75d4e3)
