### ISSUE TITLE
Google Sign-In with Android not working

### ISSUE THREAD

**Issue by guibertjulien** [FlutterFlow/flutterflow-issues#3872] opened 2024-09-22 17:08 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Google Sign-In with Android not working

Solution:

Need to specify scope in GoogleSignIn variable (lib/auth/firebase_auth/**google_auth.dart**)

`final _googleSignIn = GoogleSignIn(
  scopes: ["profile", "email"],
);`

### Expected Behavior

Google Sign-In with Android working

### Steps to Reproduce

1. Test Google Sign-In on Android physical phone

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfz/Hqx89goelK1a6Jd8FFuCgsH2kcTeU30+thcw4bI+LkP4YEY/T7XFBCWOqHT3xEC2H8sE0f0+jTj9rPIMAVFziuGrpG/7VXUxDgUmGQR8jWPIewX2snL8FmG0+O07W3qiR7PvFvV1ouwU2yHd6uY3qCf9qOYwx5e6fDbOY=

### Visual documentation

<img width="1728" alt="Capture d’écran 2024-09-22 à 18 42 51" src="https://github.com/user-attachments/assets/98552a35-9be1-4e8b-88e5-35613a12c9b9">

### Environment

```markdown
- FlutterFlow version: 4.1.91
- Platform: Android
- Browser name and version:
- Operating system and version affected:
```

**Comment by guibertjulien** [comment] 2024-09-22 17:11
https://stackoverflow.com/questions/79009273/flutter-platformexception-when-trying-to-get-google-sign-in-access-token

**Comment by harsh-sachdev** [comment] 2024-09-23 07:05
I tried defining the scope but still facing the same issue.
When I click on the Google Sign-In button, the email ID modal appears, but after selecting the email, nothing happens. This error in the console.

```
PerfMonitor binderTransact: time=234ms interface=com.google.android.auth.IAuthManagerService code=5
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(exception, ERROR, null, null)
```

**Comment by taken35** [comment] 2024-09-23 07:09
I am having exactly the same issue as @harsh-sachdev described. It happened specifically to my test phone where I perform local tests, I can not login with google anymore but other platforms it works.

**Comment by NiklavsM** [comment] 2024-09-23 08:44
I'm having the same issue, my apps authentication is no longer working on Android 14 devices. Android 13 is fine.
App is published on Play Store and stopped working there too.
Started getting this issue 24h ago.

**Comment by Alezanello** [comment] 2024-09-23 13:46
Hello!

To enable Google Sign-In on a physical Android device, please add the SHA-1 fingerprint of your APK to Firebase. You can do this by navigating to **Firebase > Project Settings**, selecting your Android app, and then adding the SHA-1 fingerprint

Let me know if you need any further assistance!

**Comment by jeffcyw95** [comment] 2024-09-23 14:12
I'm using Supabase auth and I believe the issue is caused by a need in updating the login with Google action to match Google latest requirement. Hopefully this will be fixed by the Flutterflow team

**Comment by Alezanello** [comment] 2024-09-23 14:21
I was able to replicate the issue. Thank you so much, @guibertjulien, for providing the solution! I’ll escalate this to the team as urgent.

**Closed as completed** 2024-09-23 15:05 UTC
Labels: status: confirmed, Bug, Enterprise Cherry-Picked

**Comment by harsh-sachdev** [comment] 2024-09-23 17:00
@Alezanello adding scopes: ["profile", "email"] is not working for me, Is there anything I am missing here?

**Comment by sergedahdouh** [comment] 2024-10-02 13:46
did the issue be solved because i am facing the same issue?

**Comment by guibertjulien** [comment] 2024-10-09 20:01
Yes, it solves since FF 5.0.
