### ISSUE TITLE
Periodic action fires too frequently

### ISSUE THREAD

**Issue by schox** [FlutterFlow/flutterflow-issues#195] opened 2022-12-06 06:49 UTC
## Expected behavior (required)
A periodic action should fire as described in the Timer Interval.

## Current behavior (required)
The periodic action fires more frequently than the timer interval, and sometimes multiple times in the same second (3 [update: 7] is the most times in one second noted so far).

## To Reproduce (required)
1. Create a periodic action
2. Give it a timer interval of 30000 or 60000
3. For the next action create a firebase document, and include the current date as one field.
4. Observe the frequency of firebase document creations.

### Bug Report Code
IT4Ci87huJB2octD0LrfbcAwgikUKUh/RYIO0+t+ZxUYDZPMC+wIZ/f7XFRuTde0TUFMMFmWoHgJ+tXemvDpGPJeNRGeR7ZD1pNcdwqXXkKlV8XRPKq/PC0ffaMKRSz+

## Context (required)
I am trying to run a periodic action on a regular basis.

## Screenshots / recordings
N.A.

## Your environment

* Version of FlutterFlow used: v3.0 November 19 2022 Flutter 3.3.4
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome Version 108.0.5359.94
* Operating system and version (desktop or mobile): MacOS 13.0.1. MacBook Pro 14inch 2021

**Comment by bulgariamitko** [comment] 2022-12-11 10:58
I will mark this not a bug, because I believe this is because of the user computer and not because there is something wrong in the code. But I will let @katherineqian decide if I am right or not :)

**Comment by schox** [comment] 2022-12-11 12:47
The same problem occurs in built apps running on both Android and iOS if you mean it might be related to the computer running Flutterflow?

**Comment by bulgariamitko** [comment] 2022-12-11 18:51
Yes, because at the end of the day this process is executed from the device process/memory so I believe the problem is there, but like I said let FF decide if I am right or not.

**Comment by schox** [comment] 2022-12-21 04:07
I'm still unsure why this is listed as not a bug. The functionality exposed in this action is very simple: it is just supposed to execute an action every x milliseconds and optionally once to start with. If it doesn't do that, then it must be a bug. It doesn't behave as documented. Whether or not it is executed from a device process might provide a clue as to why it is not working, but doesn't change its behaviour.

**Comment by agreaves** [comment] 2022-12-21 05:37
Hi @schox, thanks for the report! @bulgariamitko I don't believe there was enough information about this to say whether this should be marked as a bug or not.

@schox, I was not able to reproduce the bug from the steps in your report (likely why it was marked not a bug). However, thank you for generating the bug report code because after taking a closer look I can see there is certainly an issue. The bug occurs because you have a periodic action On Page Load (for other triggers this would normally not be an issue).

So essentially, when you navigate to the page and away from it and back, we are creating a new Timer every time the page loads, but not properly disposing of it. This causes multiple Timers to stack and fire frequently like you are seeing.

This will be fixed in the next release, likely in the next two days. Thanks again for the report!

**Closed by agreaves** 2022-12-21 05:37 UTC
Labels: status: not a bug
