### ISSUE TITLE
Not able to add color variable in Content Management System

### ISSUE THREAD

**Issue by Shyam2496** [FlutterFlow/flutterflow-issues#2607] opened 2024-03-27 01:17 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

when i try to add a color value to a variable in the flutterflow content management system, it is not working

### Expected Behavior

i want to set the color value either by entering the HEX value or by picking a color from the color picker

### Steps to Reproduce

1. create new firebase collection
2. add a variable of 'Color' type
3. Click on "Manage Content"
4. Now add a document
5. Now try to add the a Color value
6. You will not be able to add

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48l+fl4ot2obxY1arPbcBFoCMXQls7a50zicJTZw08J5DaPOxzP/TBaldWUs+0TAlYMGCKiTkdpuvemvzlC/QoaDeYR6pH+rtiEQvdUl2lMbKYPLuaW25/Df5VI26C3KavrB5/OfVuZX8t21+le+SAdADvJbLzDkdEP8qKLZCK2SrDX1iXc2URm05KZDPz

### Context

i had add the values in the firebase console

### Visual documentation

![Screenshot 2024-03-27 063407](https://github.com/FlutterFlow/flutterflow-issues/assets/123336376/a39e6de5-cbaa-4b30-b2d0-023c02eb88e8)
![Screenshot 2024-03-27 063407](https://github.com/FlutterFlow/flutterflow-issues/assets/123336376/01800220-ec3d-4b15-a47e-9a4f79729934)

https://github.com/FlutterFlow/flutterflow-issues/assets/123336376/b70c9417-0188-44ce-bd85-600d79645cad

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform:Web
- Browser name and version: Chrome
- Operating system and version affected: Windows
```

**Comment by takashiff** [comment] 2024-04-02 22:31
Hi @Shyam2496, thanks for the bug report! This looks to be unintended behavior, as we currently do not have support for mapping colors to data in Firestore, as the color representation can vary from user to user. I'll go ahead and mark this as a feature request and close this issue accordingly. Thanks

**Closed by takashiff** 2024-04-02 22:31 UTC
Labels: status: needs triage
