### ISSUE TITLE
Verified e-mail check doesn't work on first click

### ISSUE THREAD

**Issue by tinrunje** [FlutterFlow/flutterflow-issues#1034] opened 2023-06-23 12:09 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When making a conditional action to check if email is verified, and it is, on the first click of the button, it will say it isn't. It will only work on the second click.

Step by step description:
Users are creating a profile with an e-mail. Once the account has been created, a verification e-mail.
<img width="223" alt="Screenshot 2023-06-23 at 14 00 18" src="https://github.com/FlutterFlow/flutterflow-issues/assets/52575319/a4dc0759-6031-4df6-8dfc-1c24d727a2b4">

On the new page that the previous page leads to users can't do anything until they verify e-mail. The new page only has a button that only allows the user to continue to the next page if the e-mail is verified as we can see below:
<img width="676" alt="Screenshot 2023-06-23 at 14 04 12" src="https://github.com/FlutterFlow/flutterflow-issues/assets/52575319/117e193f-7c90-413e-bb58-6c5335e3c789">

I, as a user, can go to my email mailbox and verify my email. The email verification process works fine. However, when I go back into the app and click on the button to go to the next page, on the first click, it will say that my email isn't verified. It will only work on the second click of the button and allow me to go to the next page.

This is bad for UX as many users do give-up at this point as they think that something isn't working and can't be bothered to move forward.

### Expected Behavior

It is expected that as soon as the e-mail is verified, the button that checks if the email is verified instantly recognises it. On the first click of the button it should allow users to move forward.

### Steps to Reproduce

1. Create 3 new pages
2.1. Page 1 - register profile with email, send email verification link when registered; lead to page 2
2.2. Page 2 - have a button that will only lead to Page 3 if email is verified. If email is not verified, display an alert dialog.
2.3. Page 3 - basic home page. can be empty. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5fkMmAuI92mOZE7YSJb+9V/CQWMjsnRYJJlu56EBQ1F5fqE5oQfcnRYk5JbbyRSmNceWH8/W0f0/zUvvDtUO0BNhyJbNVR/4dcYTngYEeQb8WPPZGSe0B7N8RMCEzCzpuZhAlQVLFvci0AwGaXfueXHzLbJrG3DXonL+WhMoTJnlKiLADGG30Jg1ZSfCvr

### Context

Many users think their email verification link didn't work as clicking on the button doesn't work. This can lead to users leaving the app before finishing the profile completion steps.

### Visual documentation

In the description above.

### Environment

```markdown
- FlutterFlow version: v3.1 (released June 23, 2023)
- Platform: MacOS Desktop
- Browser name and version: Chrome 114.0.5735.133
- Operating system and version affected: macOS Ventura 13.4
```

**Comment by hariprasadms** [comment] 2023-06-27 12:06
Hi @tinrunje - I looked at your and tested it. I can see it works for only second clicks.

**Comment by agreaves** [comment] 2023-06-28 02:06
Hi @tinrunje, thanks for the bug report! As Hari mentioned, we've reproduced this, and it should be fixed on the next release!

**Closed by agreaves** 2023-06-28 02:06 UTC
Labels: type: bug, status: confirmed

**Comment by Pedro-dwire** [comment] 2023-07-10 22:19
Hi, do you have any idea when this will be resolved? I just tested here and I'm having the same problem

**Comment by winston-lee** [comment] 2023-09-16 01:03
I concur with @Pedro-dwire , the issue is still happening?

**Comment by Exter007** [comment] 2023-11-10 12:18
Hi, did someone find a solution ?
