### ISSUE TITLE
Flutter default icon still shows when you save to deskstop

### ISSUE THREAD

**Issue by elphinehas** [FlutterFlow/flutterflow-issues#620] opened 2023-03-16 16:36 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [ ] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

![image](https://user-images.githubusercontent.com/58237353/225687750-b90949fe-c8e8-4246-b8d0-4b053d424ff4.png)

The default icon shows when saving on web/ desktop

### Expected Behavior

The uploaded icon is expected to show

### Steps To Reproduce

Publish any project to the web and try saving it to a desktop or on a mobile device

### Bug Report Code

Get Bug Report Code

### Context

Use a default icon to work as uploaded

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by bulgariamitko** [comment] 2023-03-16 21:06
Just to be sure you have uploaded a favicon in Settings, Deploy to the web, right?

**Comment by ramyakantd** [comment] 2023-03-24 13:52
Facing the same issue. Flutter icon is showing up on the browser while suggestion to download.

**Comment by aemelyanovff** [comment] 2023-04-04 17:27
Duplicate of https://github.com/FlutterFlow/flutterflow-issues/issues/324

**Closed by aemelyanovff** 2023-04-04 17:27 UTC
Labels: type: bug, status: confirmed, priority: high
