### ISSUE TITLE
API Call cannot override Content-Type header

### ISSUE THREAD

**Issue by dmk23** [FlutterFlow/flutterflow-issues#250] opened 2022-12-20 21:37 UTC
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

API Calls allow specifying headers. All headers, including `Content-Type` should be possible to set exactly, like in Postman

## Current behavior (required)

I have an API Call that accesses a resource which is very particular about how `Content-Type` header is presented

Testing via Postman I confirmed that the call works when the header is specified exactly as `Content-Type: application/json`, but fails when specified as `Content-Type: application/json; charset=utf-8`. Here is the error message with the 400 HTTP response: _"Header missing: please add content-type: application/json or application/ejson to specify payload data types"_

Unfortunately I have no control over this 3rd party resource, and FF always appends `charset=utf-8` to the header, even if I specify the correct/working header via the headers section of the API Call screen

## To Reproduce (required)

Just run my test case. Click "Test API call" for "MDB Whiffs ReplaceOne" API call in "marketwhiffs-sl6p57" project

In Chrome dev tools you will see `Content-Type: application/json; charset=utf-8` being sent, even though I have the explicit `Content-Type: application/json` header set in my test case

Screenshot shows what you would get

### Bug Report Code

N/A

## Context (required)

I cannot implement this API call which is critical for my app. I don't control the backend of this API

## Screenshots / recordings

![image](https://user-images.githubusercontent.com/1828444/208770980-71c909bc-d58e-4552-bbe1-0e398b06ddb0.png)

## Your environment

* Version of FlutterFlow used: Latest as of today
* Platform (e.g. Web, MacOS Desktop):  Test environment
* Browser name and version:  Latest Chrome
* Operating system and version (desktop or mobile): Windows 10 lateset

**Comment by bulgariamitko** [comment] 2022-12-21 13:54
What is the problem that the request is send using _charset=utf-8_?

**Comment by dmk23** [comment] 2022-12-22 07:04
> What is the problem that the request is send using _charset=utf-8_?

The problem is that some API endpoints cannot handle this correctly and cannot be changed

In my case I already found a workaround to create a custom API endpoint, but I think FF should still allow a complete customization of all headers, just like Postman in case of recurring problems like this...

**Comment by bulgariamitko** [comment] 2022-12-22 07:42
I agree, but I will mark this as feature request.

**Comment by victoriahuang1** [comment] 2022-12-23 19:56
Closing this as duplicate of #58 .
Please see solution there.

**Closed by victoriahuang1** 2022-12-23 19:56 UTC
Labels: closed: duplicate

**Comment by zboyles** [comment] 2023-11-08 22:19
> Closing this as duplicate of #58 . Please see solution there.

This is not a duplicate #58. The issue is that FF does not respect the `Content-Type` header value as is set in the Define API Call window other than what's visible in the Header preview panel. When you press `Test API Call` it will append `; charset=utf-8` which isn't supported by some 3rd party API.

**Comment by johnpreynoso** [comment] 2024-08-21 01:21
I just checked #58, and it looks irrelevant to this case. The issue is that the API call request header for "Content-Type" cannot be overridden in FlutterFlow.

Details of my experience here: https://community.flutterflow.io/ask-the-community/post/api-call----changing-request-header-content-type-not-working-Js5uwYxV8jC1eUa
