### ISSUE TITLE
Scrolling is lagging, has stutter/jank and bad performance on iOS 16.6 with Flutter 3.10.6 or below and 120hz

### ISSUE THREAD

**Issue by isegal** [FlutterFlow/flutterflow-issues#1413] opened 2023-09-07 00:57 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Scrolling on 120hz app should be smooth and not jittery

### Expected Behavior

When scrolling on any screen any Flutter app is behaving noticable jittery than native equivalents

### Steps to Reproduce

1. Create a new project that contains scrolling column or list view with some elements
2. Build it and run it in RELEASE MODE on a PHYSICAL iOS 16.6 device
3. On the device, ensure that the setting under Accessibility -> Limit Frame Rate is OFF
4. Ensure that Low Power Mode is OFF
5. Open the app and scroll around

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hcnfz5Fgod9c1rrUK/lahmU5JlN9RI0Nke57aCosfZT2BLMcec/RVERoZ7C5T39cOGGj/GoW0+j2ioaeOsY7ByiBUbZCycx+eA3yfH66MpuaFJWgZnQmBcZRBUiB37eN2RNDBONaLWct2zqDN+jLcCbANOPXIXoWDq/LZO4=

### Context

This appears to be a problem introduced in iOS 16.6 in combination with Flutter versions earlier than 3.10.7
The apps are visible jankier than native apps and customers who upgraded will see their apps visibly slower

### Visual documentation

N/A

### Additional Info

Flutter team is aware of the issue and released a hot fix for Flutter 3.10

Tracking issue on Flutter:
https://github.com/flutter/flutter/issues/131319

Hotfix:
https://github.com/flutter/flutter/wiki/Upgrading-from-3.10.6-to-3.10.7

Reddit thread:
https://www.reddit.com/r/FlutterDev/comments/15kdht7/flutter_apps_are_lagging_on_120hz_iphones_with/

### Environment

```markdown
- FlutterFlow version: v1.1.100 (Flutter 3.10.4)
- Platform: iPhone 13 Pro
- Browser name and version: N/A
- Operating system and version affected: iOS 16.6
```

**Comment by isegal** [comment] 2023-09-07 01:11
Update: I have confirmed that switching to Flutter 3.10.7 fixes the issue.

**Comment by trevorFields** [comment] 2023-09-07 04:05
I was about to submit a ticket on this. i am also experiencing this and noticed it a few weeks ago. i did some debugging and also seems to be the flutter version since i am not seeing anything on my end and all scrolling has become janky, not just one table.

**Comment by trevorFields** [comment] 2023-09-07 04:13
> Update: I have confirmed that switching to Flutter 3.10.7 fixes the issue.

@isegal  when looking at the yaml file it says sdk: ">=3.0.0 <4.0.0" is there a way to force to build to that version? even when sending to codmagic and the app store the build must still be on a lower build since i am experiencing jank even on fully compiled code running on ios.

**Comment by hariprasadms** [comment] 2023-09-12 10:06
Hi @isegal - Thanks for sharing the observation. Considering the nature of issue you have explained I think, this is no to bug in existing functionality of column or list view scrolling behaviour. This is something related to device settings compatibility with flutter version ( As you mentioned scrolling on 120hz and iOS 16.6 in combination with Flutter versions earlier than 3.10.7). Considering wider use cases, I can confirm that column and list view scrolling behaviour is working as expected with flutter version submitting version in FlutterFlow. Hence this issue is not a bug. 

I would advise sharing these specifics details as suggestions or feedback using the feedback form found in the help section. Therefore, it notifies us in the appropriate channel so that we can refine the details and come up with a supporting fix. I hope this can help you. Thanks

**Comment by aaronmt93** [comment] 2023-09-12 18:14
also having the same issue, is this not a bug that can be resolved by updating flutterflow to 3.10.7?

**Comment by isegal** [comment] 2023-09-13 00:03
@hariprasadms 

Sorry, I think I missed an important detail: Flutter versions prior to 3.10 worked smoothly on 120hz and we have confirmed that 3.10.7+ also works smoothly. Technically this is a performance regression and has been confirmed by the Flutter team.

To put it another way: our iOS builds that we made with FlutterFlow prior to FlutterFlow's upgrade to 3.10 worked smoothly on 120hz.

**Comment by trevorFields** [comment] 2023-09-13 02:59
I will second that, scrolling was smooth until a few weeks ago.

**Comment by agreaves** [comment] 2023-09-17 23:10
Hi @isegal (and others), thank you very much for this bug report! I can confirm this as due to a Flutter issue and we're aware of it and the solution. Because this is a FlutterFlow specific issue tracker (and there is already one in Flutter) I'm closing this for now.

However, we are planning to upgrade the Flutter version soon! The target date is the week after next, but unfortunately we can't upgrade much sooner than that without sufficient testing.

**Closed by agreaves** 2023-09-17 23:10 UTC
Labels: closed: feature / enhancement request, type: feature / enhancement request

**Comment by trevorFields** [comment] 2023-09-18 01:23
awesome that works for me!! thanks

**Comment by amosvizer** [comment] 2023-10-03 13:12
Any update on the update to 3.10.7? We are also getting close to release and this jittering is driving us crazy.. thanks!!

**Comment by MaggieThomann** [comment] 2023-10-11 22:51
+1, Any update on the release? 😄  I'm also having some buggy scrolling problems and hoping this will fix it. Also updated my computer to Sonoma and Xcode to 15 and now I can no longer run code locally because it [looks like](https://medium.com/flutter/whats-new-in-flutter-3-13-479d9b11df4d) only developing with Flutter 3.13 works with iOS 17 and Xcode 15.
