### ISSUE TITLE
Map List Items (current variable is not valid)

### ISSUE THREAD

**Issue by alih552** [FlutterFlow/flutterflow-issues#3245] opened 2024-06-26 13:54 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am trying to set the value of a list that should contains a users ids/references, but it's not working, an error is appearing saying that "current variable is not valid" but I don't get why and it should work.

![telegram-cloud-photo-size-2-5467537400268973441-y](https://github.com/FlutterFlow/flutterflow-issues/assets/20465950/cc55874f-8b01-4615-82c0-fa9873903bcb)

### Expected Behavior

It should work normally

### Steps to Reproduce

1. create a component
2. link & activate firestore
3. Add some users to the users collection
4. Create a new collection & set a one field for it to be a list that takes a document reference of users
5. Query users collection with some type of filter
6. Create a new action, Create document action and try to set the value for the list from the queried users collection 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kjcr1z5R1obxY0LXTbfpWoCcXJVx+TLJEoetxc0gbfe/4PZoqZvTBYVpCZ7WzaH9mC2aGkmId/9bHkfPTUscVBxyaf6phyKhMaBPPbE+QeL62O7qSdUR7I+hXf0yB57SFoBBRNbN2WkFlw16PfO+ydz6Cf9qOYwx5e6fDbOY=

### Visual documentation

![telegram-cloud-photo-size-2-5467537400268973441-y](https://github.com/FlutterFlow/flutterflow-issues/assets/20465950/eb769982-7b13-447e-9c7b-11709af52886)

### Environment

```markdown
- FlutterFlow version: v4.1.64
- Platform: MacOS
- Browser name and version: -
- Operating system and version affected: all
```

**Comment by msusviela** [comment] 2024-06-28 15:12
Hey @alih552, Thanks for your report, So sorry you are experiencing this issue. I was not able to reproduce this on a blank project, but it is replicable on yours. That's why I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. Thanks so much!

**Comment by alih552** [comment] 2024-06-28 16:08
Issue where solved by simply creating a new button instead of copying it from another page with its actions
<img width="319" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/20465950/4ba6d489-301e-4af0-8aec-f116f527606e">

I am guessing it is a bug that is related to copying and pasting the button from another page.

**Comment by nghia-filma** [comment] 2024-07-02 18:01
Hi, Im getting the same bug while trying to map rows into page state on pageLoad
<img width="693" alt="Screenshot 2567-07-03 at 00 58 54" src="https://github.com/FlutterFlow/flutterflow-issues/assets/172976388/f2759379-979a-400b-a67d-15a324ddd022">

**Closed as not planned** 2024-07-08 18:22 UTC
Labels: status: can't reproduce
