### ISSUE TITLE
Branching Problem

### ISSUE THREAD

**Issue by msedats** [FlutterFlow/flutterflow-issues#2055] opened 2023-12-25 10:53 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In order to let my team work on the project and improve the development, we wanted to start using Branching on FlutterFlow, I have created a new branch and deleted a couple of widgets. 

When i am trying to merge two different branches, FlutterFlow doesn't recognise any changes in the test branch.

### Expected Behavior

FlutterFlow doesn't recognise any changes in the test branch. 

### Steps to Reproduce

1 - Create a new Branch
2 - Delete widgets
3 - Try to merge with the main branch. 
4 - At this step, FlutterFlow doesn't recognise any changes to merge however you delete some widgets.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sl+fl4otPtbwA+Kr+bsBB/CkWQ0w+bbskscpCbw4bIYj2P4lzY876P1VvQsDgTH9AIEyMp14BpKHIv+DlCPFdYU+cbtV7yJBQWwL/ZEKiV7GTF7joPHBfFtxMCWKs5KavvxN4NsdqL1Fn1F+YP/PKVhTqQ77xIUQ8Sq/LZO4=

### Context

When you check I deleted the reported widget on the test branch however during merging the branches, FlutterFlow doesn't recognise any changes on the TestBranch. 

### Visual documentation

<img width="1661" alt="Screenshot 2023-12-25 at 13 48 06" src="https://github.com/FlutterFlow/flutterflow-issues/assets/145287693/50fc4951-bfa8-461f-8af5-f857f9379e1f">

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: Mobile
- Browser name and version: Chrome Version 120.0.6099.109 (Official Build) (arm64)
- Operating system and version affected: mac OS 14.3 Beta
```

**Comment by aemelyanovff** [comment] 2023-12-29 20:56
@msedats The page on the screenshot shows only merge conflicts; changes that can be merged without conflicts are not displayed. If you complete the merge the result should be as expected.

**Comment by msedats** [comment] 2024-01-06 13:29
Hey Anton, I expect to see what the change is on the branch. Intentionally I created 2 changes but non of them were shown on the merge screen.

**Comment by aemelyanovff** [comment] 2024-01-08 22:00
@msedats As I said, the merge screen shows only conflicts. If there are no conflicts it won't show anything. When you complete the merge you should see all your changes.

**Comment by aemelyanovff** [comment] 2024-01-12 13:47
Closing as not a bug.

**Closed** 2024-02-05 13:39 UTC
Labels: closed: not a bug, status: not a bug
