### ISSUE TITLE
Adding ORDER BY XXXX after the sqlite query statement for pageview will cause pageview to fail to load. 

### ISSUE THREAD

**Issue by 12138zhen** [FlutterFlow/flutterflow-issues#2957] opened 2024-05-21 19:13 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Setting up backend query in pageview, added sqlite query: SELECT \* FROM subtasks ORDER BY order_index;.
pageview won't load in ios simulator, but if you remove ORDER BY order_index, i.e., SELECT \* FROM subtasks; pageview loads fine.

### Expected Behavior

I expect that the pageview screen should show up

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gz/Hqx89godtJ15CBYO9V9SgQJlh6aIc0sNpuZxYjGYDuBIYiaffOXFduXt+rdHxHKEWKmnIxp/zFiODlKMIrG0ybGqZB+rtQew/yJX+/aoSDDpOKVEZ7GeRhG0i/0Z6JkyZTPrJvV0ID3UOEAvPJZB3aJrH4Zwh9f6PHaOI=

### Context

I want pageview to display in the order of my database

### Visual documentation

[https://github.com/FlutterFlow/flutterflow-issues/assets/57309340/183180df-8687-4e6d-a5e8-05f0a6d7263f](https://github.com/FlutterFlow/flutterflow-issues/assets/57309340/183180df-8687-4e6d-a5e8-05f0a6d7263f)

### Additional Info

database structure

![Screenshot 2024-05-22 at 3 09 33 AM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/09394422-3791-4121-8a18-f7c1a6396424/ba6915cc-dc57-4d98-87b8-5e59679d1db7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wOTM5NDQyMi0zNzkxLTQxMjEtOGExOC1mN2MxYTYzOTY0MjQvYmE2OTE1Y2MtZGM1Ny00ZDk4LTg3YjgtNWU1OTY3OWQxZGI3IiwiaWF0IjoxNzE2NTQ3MzE1LCJleHAiOjMzMjg3MTA3MzE1fQ.UVzJx6hVsGnBOmx4MRNxwxK03TvHz2NA38DSt0CP6wA "=648x")

### Environment

```markdown
- FlutterFlow version: v4.153
- Platform: MacOS desktop
- Browser name and version: Chrome Version 124.0.6367.208 (Official Build) (arm64)
- Operating system and version affected: MacOS Version 14.5 (23F79)
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [X] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [X] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] \~100% of the time
- [ ] \~50% of the time
- [ ] \~10% of the time
- [ ] \~1% of the time
- [X] Very rarely or only encountered once

**Comment by msusviela** [comment] 2024-05-24 10:46
Hey @12138zhen, Thanks for your report, So sorry you are experiencing this issue. I was not able to reproduce this on a blank project, but it is replicable on yours. <br>That's why I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. Thanks so much!

**Closed** 2024-05-28 19:56 UTC
Labels: waiting for user response

**Comment by 12138zhen** [comment] 2024-06-01 17:05
Hi @msusviela 

I wanted to provide an update on this issue.

After deleting the app from the iOS simulator and re-running the project, the pageview is now loading correctly without any issues. It seems that the problem has been resolved.

Thank you all for your support and suggestions.
