### ISSUE TITLE
REDE DESCONECTADA

### ISSUE THREAD

**Issue by tiagorocha4sys** [FlutterFlow/flutterflow-issues#3408] opened 2024-07-16 12:09 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Flutterflow is showing the error message "Network disconnected" for any attempt to change in project.
I've already carried out speed tests, tested on other devices, other internet links and the problem persists.

I also tested it on other projects and it works. The problem is in my project.

There is already an open ticket:
https://github.com/FlutterFlow/flutterflow-issues/issues/3361

I have already sent all the evidence.

I do not know what else to do, my demands are paralyzed!

it's definitely not a connection problem.

It seems to me that the project has reached some limit imposed by the tool.

You classify my ticket as "not a bug" and no one gives me any feedback, that's absurd.

I urgently await a solution

### Expected Behavior

I would like to go back to work and be able to edit my project

### Steps to Reproduce

1. Open the project
2. Start editing something
3. After about 2 minutes of editing, the "network disconnected" error will appear

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oksmB34ZOoctC7qXyY+9WhSQRH0M3aoEW1spBZywgfZzzBLN/fPfQPhdWZNTmd2N+Pmacp14ew6iMvobxKfYEGASCUaI/1s1cbA7KfGOiMpuTF7qWXnJSPNNYfWqn0rbQhApDLu5fWFo5wUy6ffCXcA3dQoS2IXo4Sq/LZO4=

### Visual documentation

![image](https://github.com/user-attachments/assets/25f1f80c-cb34-4e12-acc2-fa5b05ab98f0)

https://www.loom.com/share/ac4f5691be4c4f7ebae393ccae0a38b4?sid=d461e263-3dc6-443d-8ded-61d910e21e0c

![image](https://github.com/user-attachments/assets/9248c591-c122-4c41-ab4f-2f1a4c4197a8)

### Environment

```markdown
- FlutterFlow version: 4.1.72
- Platform: MAC OS
- Browser name and version: CHROME
- Operating system and version affected: SODOMA
```

**Comment by msusviela** [comment] 2024-07-16 13:11
Thanks for your report. I'm closing this because it's a duplicate of the other issue you've submitted.

**Closed as not planned** 2024-07-16 13:11 UTC
Labels: closed: duplicate
