### ISSUE TITLE
Issues when renaming widgets in the widget tree

### ISSUE THREAD

**Issue by kesioo84** [FlutterFlow/flutterflow-issues#2989] opened 2024-05-26 09:29 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

More often than not, I cannot rename widgets, at least with columns widgets is where I see it happening. Tried to replicate now on other widgets but those seem fine, and I cannot remember if before they were also experiencing the issue.

### Expected Behavior

When double-clicking on the name inside the Widget tree, as soon as you start typing a new name: 

1. The focus is lost with 1 or characters entered only (ie: instead of "contentColumn", only "co" is entered)
2. The widget tree scroll jumps and a new scroll is needed to reposition and try renaming it again.

In some cases after a few attempts, the name is registered. On others, as you see in the video, there is no chance.

### Steps to Reproduce

1. Inside a page with plenty of elements, pick a column widget of mid hirarchy
2. Double-click its name to rename
3. Try to type and enter a new name (or move the cursor with the left/right arrow or use backspace/delete, if a partial name was accepted and the focus is not lost)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89gosNY1bXubMBqhQAkQzM8bYJMl9caRQ0YNbLoPe0DeOr+VGVYZPW5Sm9iP1elsD40w63WvoThCPA4H0+reINozLlUSQvjeFGuWq6oEZGWZ0dTGe5hG0jHy6u02CNNOu5hV1Jiw2z/cq3qNleeY8aSfxBlZ7vfcPo=

### Context

Well, not being able to rename widgets in the tree prevents me from finding elements easily.

### Visual documentation

A video will help more than an image. So I uploaded one to my drive 2 videos:

On my project, the behaviour is bad
https://drive.google.com/file/d/1NnVSR57jToEOaR4d9JGIWTwmyVhDdaPS/view?usp=drive_link

On a blank project, it seems okayish but as you add more elements, it seems to start happening.

### Environment

```markdown
- FlutterFlow version: 4.1.5
- Platform: Web browser and also on MacOS Flutterflow PWA
- Browser name and version: Brave 1.66.110
- Operating system and version affected: MacOS Sonoma 14.5
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by ignalauret** [comment] 2024-05-28 02:36
Hey @kesioo84 thanks for your report. I was able to reproduce this issue trying to change the name of a Column. I will send it to our technical team so they can take a look, they will keep you updated on this thread. Have a great day!

**Comment by kesioo84** [comment] 2024-05-28 07:19
Awesome Ignacio! Gracias viejo!

**Comment by sbis04** [comment] 2024-10-02 17:08
I'm not able to reproduce this issue now, seems to be already fixed. @kesioo84 are you still facing this issue?

**Comment by sbis04** [comment] 2024-10-02 17:16
> I'm not able to reproduce this issue now, seems to be already fixed. @kesioo84 are you still facing this issue?

Nevermind, I was able to reproduce by exactly following you steps. Seems like it's pretty inconsistent (maybe it doesn't happen on all widgets), but I'll look into why it's happening.

**Comment by sbis04** [comment] 2024-10-03 18:47
It should be fixed in the upcoming release!

**Closed** 2024-10-03 18:46 UTC
Labels: status: confirmed, usability, Bug, FF Platform Issue
