### ISSUE TITLE
On Page Load Does not trigger Action that navigates to the admin panel

### ISSUE THREAD

**Issue by dannyz61** [FlutterFlow/flutterflow-issues#3035] opened 2024-06-01 11:02 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

**Full Story**
I have two panel
1. Admin Panel (access to only admin)
2. Customer Panel (access to only user)

PS: Access is maintained by the **is_admin** boolean in the User table

**Scenario**
My Default Page is: **Customer Panel**
Access Hanlded at CustomerPanel
if is_admin 
   navigate to AdminPanel 
else
   stay at CustomerPanel

**Case 1 Logged in as Admin at Admin Side**

1. Refresh the page
2. Auto-navigate to the default page CustomerPanel
3. CustomerPanel On page load, the action to navigate to the admin panel is not triggered.

**Case 2 Logged in as Admin at Customer Side**

1. When CustomerPanel OnPageLoad Failed
2. Refresh the page Again and then it works navigate to AdminPanel

**Note: sometimes it works perfectly fine sometimes it needs to be refreshed 2 times for the router to work**

### Expected Behavior

If I'm on AdminPanel and refresh the page then it should be navigate back to AdminPanel

### Steps to Reproduce

##Case 1 Logged in as Admin at Admin Side

1. Refresh the page
2. Auto-navigate to the default page CustomerPanel
3. CustomerPanel On page load, the action to navigate to the admin panel is not triggered.

##Case 2 Logged in as Admin at Customer Side

1. When CustomerPanel OnPageLoad Failed
2. Refresh the page Again and then it works navigate to AdminPanel

### Reproducible from Blank

- [x] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ClcmAvIVIvscB7c7qacEw+CQsKUg4RY0vmMB+TRUYDZPMC+wIZ/f7XFRuTde0YAk/MU6KkmM109XemvPLCvY7NU2sQLpq/qVxETzgITq5M66XDc6CPW5/DZthfVC738HU3RJ4KtZtWGdl7HGuFuetYBHbJJDsOGonJ86aKZOK2SrDX1iXc2URm05KZDPz

### Context

im trying to maintain access level According to users (admin and customer)

### Visual documentation

[https://drive.google.com/file/d/1lsN78hnpgzJmL0C9OHr_k_ni5_NUaKKx/view?usp=sharing](url)

### Environment

```markdown
- FlutterFlow version: v4.1.54+
- Platform: Browser
- Browser name and version: Chrome 125.0.6422.113
- Operating system and version affected: all
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by msusviela** [comment] 2024-06-03 20:33
Hi @dannyz61 - Thanks for submitting the issue. I've taken a look at your project, but with a lot going on, it's challenging to pinpoint the issue. Given the nature of the problem you're highlighting, we need a blank project with the issue steps set up in it. Without these details, it might be a bit challenging for us to investigate the issue. Please provide the required information. If the issue is already resolved for you, please feel free to close the issue. Thanks!

**Closed** 2024-06-06 16:34 UTC
Labels: waiting for user response

**Comment by msusviela** [comment] 2024-07-04 20:05
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
