### ISSUE TITLE
Audio Widget Doesn't Play When Device Locked

### ISSUE THREAD

**Issue by whobick** [FlutterFlow/flutterflow-issues#1284] opened 2023-08-16 18:38 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The FlutterFlow audio widget has the option to enable in background, however when enabled it turns off when a device is locked. The audio widget "play in background" option is enabled although when on a device if audio is playing the device is locked then the audio stops and can't play until unlocked again. This occurs on IOS (haven't been able to confirm on android).

### Expected Behavior

Given the audio widget says it would play in the background, the expected behavior is that the widget would work when the device is locked. It should pull the title in the audio widget as the title of the track and be accessible to play and pause on the lock screen for both IOS and Android devices.

### Steps to Reproduce

1. Create a new project
2. Drag audio widget on to page
3. Set audio widget "Play in background" to **Enabled**
4. Add any audio (network or asset)
5. Run app on IOS device
6. Lock screen (audio pauses)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48l/Hf049Pm7xY0LrUb8Fr/TgWOUs7R4INj8BtRgA8J4jcOokUf8+nRFFVUum+TVc2PlmgpDsy7srWkdzIN+1eOk+qY7ZZyahcbgnzRT6gV6qIEoeweWgkFtpKCWqD0rWFpSNQNbdoWmQ+6l2qf/OuSg/UHrrjOWonAfKhCKDJo3PuQ0SLb3kNh1JWeC/v

### Context

This limits any app with audio to only be played when the app is open. Essentially any music application or application with recorded audio has a poor experience because if the phone locks after the default time, the audio stops.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/50713619/0ba4454c-4b59-46de-b22f-886200c77080

### Environment

```markdown
- FlutterFlow version: 3.1 - August 15, 2023
- Platform: IOS
- Browser name and version: Chrome
- Operating system and version affected: MacOS
```

**Comment by wenkaifan0720** [comment] 2023-09-03 01:05
Hi @whobick. I see there are some updates for the assets_audio_player package but none seem to mention about this issue. I'll wait for a while and see if they fix it.

**Comment by agreaves** [comment] 2023-09-21 04:23
Hi @whobick, closing this one as a duplicate of #1167

**Closed by agreaves** 2023-09-21 04:23 UTC
Labels: type: bug, status: confirmed, priority: low
