### ISSUE TITLE
Terminating Actions leaves Actions hanging in no-where.

### ISSUE THREAD

**Issue by bulgariamitko** [FlutterFlow/flutterflow-issues#49] opened 2022-10-21 06:44 UTC
## Expected behavior (required)
I don't expect to be able to create Actions from no-where :)

## Current behavior (required)
You can create actions not from the chain 

## To Reproduce (required)
1. Just create the structure in the second screenshot
2. You will be able to create Actions in no-where as it is seen in the first screenshot

## Context (required)
This give me errors to the project and in overall it shouldn't be possible to do. 

## Screenshots / recordings
![Dashboard-FlutterFlow (5)](https://user-images.githubusercontent.com/7221384/197129779-c168608a-c386-4ef3-af9a-aa9a18052cc4.png)
![Dashboard-FlutterFlow (4)](https://user-images.githubusercontent.com/7221384/197129793-757d832c-9e7f-4dff-8c0c-9485ff4e1fcd.png)

## Your environment

IT40jc/l8c9IrsdF1oSJbcJR/Tw5KWYlRIEsm9VRaCssIpyuP4lzYfz7QFtUOMDgTFZUIVmZkjsX/Mr0koXAV+43NTGVGKpTypNyUQHNdzujbrbTPrzlMS0ffaMKRSz+
* Version of FlutterFlow used: 3.3.4
* Platform (e.g. Web, MacOS Desktop): web
* Browser name and version: Chrome 106
* Operating system and version (desktop or mobile): desktop

**Comment by organicnz** [comment] 2022-10-29 13:08
The issue is reproducible.

<img width="1440" alt="Screen_Shot_2022-10-29_at_15_52_51" src="https://user-images.githubusercontent.com/4765090/198833215-346e92b0-cc00-41c3-a287-a4e4369658e1.png">

**Comment by agreaves** [comment] 2022-11-02 23:41
This will be fixed in our next deploy!

**Closed by agreaves** 2022-11-02 23:41 UTC
Labels: type: bug, status: confirmed, priority: low
