### ISSUE TITLE
some fields returns null in FF getting data from Algolia

### ISSUE THREAD

**Issue by ibm777p2** [FlutterFlow/flutterflow-issues#1567] opened 2023-10-02 02:44 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have user id, Created date and currency value return null from Algolia due to how the new auto generated code.

### Expected Behavior

Return user id and created date with values and not null.

### Steps to Reproduce

Create an index from your firebase table in algolia.
in the index must contains userid, a date and a int representing a value of a price.
use a custom code to get algolia data back.
user id and the date is returned null

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4olfLluJZ1ofVY7c/QdcBv9CQWJVg2RLgZkspOWSsbfL74PKQEdc/ealJtXbWzaH1EfGeIkngF0vuNuOHpNe46NQ+VUYh51atqYBPPbH6hV6qTDqjhYXR6Ae9VGFSg1MCJqiZCIvZpc0Y86kyUevCXEj+Cf9qOYwx5e6fDbOY=

### Context

I can load any products detail in my app

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/5303536/c42ba187-fbe6-4815-93c9-1b3e8818b8b0)

### Additional Info

I solved this temporary by coping the old autogenerated code from FF to the new one, but we need FF to autogenerate the code correctly for long term solution.

Here is what I did. I replaced the new autogenerated code with the previous autogenerated code and everything works fine.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/vincentlai/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/vincentlai/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

new   autogenerated code | previous auto   generated code
-- | --
userId':   convertAlgoliaParam(                   snapshot.data['userId'],                   ParamType.DocumentReference,                 false,               ), | userId':   safeGet(                 () =>   toRef(snapshot.data['userId']),               ),
'date_created':   convertAlgoliaParam(                   snapshot.data['date_created'],                 ParamType.DateTime,                 false,               ), | 'date_created': safeGet(                 () =>   DateTime.fromMillisecondsSinceEpoch(                       snapshot.data['date_created']),               ),
'last_modified':   convertAlgoliaParam(                   snapshot.data['last_modified'],                 ParamType.DateTime,                 false,               ), | 'last_modified': safeGet(                 () =>   DateTime.fromMillisecondsSinceEpoch(                       snapshot.data['last_modified']),               ),
'price':   convertAlgoliaParam(                   snapshot.data['price'],                 ParamType.int,                 false,               ), | 'price': snapshot.data['price']?.round(),

</body>

</html>

is here how the field looks like in algolia and I think the new way FF is getting the data from algolia is wrong
{
  "promoted_priority": false,
  "promoted_discount": false,
  "images": [
    "https://firebasestorage.googleapis.com/v0/b/cambalacheros-8f081.appspot.com/o/images%2Fimage_picker_compress_f277ce5a-2300-4958-b430-eec28018ce8b.jpg?alt=media&token=8ad5d0a8-095f-487e-bea8-01c6aea3fc1e"
  ],
  "date_created": 1696093281672,
  "description": "de herreria...semi nuevos, sin detalle",
  "title": "cuadros decorativos",
  "userId": "users/0sL7KK2agqTNzQLkiONjdrnO3yZ2",
  "condition": "Usado (desgaste normal)",
  "price": 250,
  "_geoloc": {
    "lat": 32.6352981,
    "lng": -115.3816451
  },
  "cambalache_selection": "",
  "currency": "PESOS",
  "last_modified": 1696093281672,
  "product_category": "Muebles, Hogar y Jardín",
  "views": [
    "users/0sL7KK2agqTNzQLkiONjdrnO3yZ2"
  ],
  "status": "venta",
  "path": "products/wJJhLV3OW57ZiMf5oxVv",
  "lastmodified": {
    "_operation": "IncrementSet",
    "value": 1696209925163
  },
  "objectID": "wJJhLV3OW57ZiMf5oxVv"
}

### Environment

```markdown
- FlutterFlow version:  v3.1 
- Platform:mobile
- Browser name and version:107.0.5304.110
- Operating system and version affected: macOS Monterey 12.2.1
```

**Comment by ChrisLowCode** [comment] 2023-10-05 13:13
** Posting this comment to both recent Algolia-related issues found here for the community**

I have also encountered this bug with Algolia search, which started last week, possibly due to recent updates. The bug affects date and time handling in Algolia search, returning null values when using date/time from Firebase, both with standard DateTime and UNIX-converted DateTime.

This issue was noticed on my end after updating a different section of my app without modifying Algolia-related code, suggesting the bug might be on FF's end. A current temporary workaround involves using Firebase queries for text display, but this isn't viable for filtering and displaying specific Algolia documents as Firebase queries can't conditionally hide widgets referencing a query on the same widget - it would have to come from a parent widget query (which means I can't filter on the front end)

To replicate, make listviews of Algolia searches that filter without referencing any date (should work fine), Algolia searches that filter using Date to Unix tmestamp (shouldn't work), and Algolia searches referencing the date and time without formating in the filter (shouldn't work). To test the text display issue, add text referring to an Algolia-referenced DateTime field, and you'll see a null return. The text display issue confirms that this is a bug probably only related to how the data is read regarding DateTime from Algolia to FF.

Notably, the Algolia search was functioning correctly in my build earlier last week. Another community member reverted to older autogenerated code from FF, resolving the issue. This FF community member noted that this problem occurs when the newly auto-generated FF code is added to a project. Others have reported similar issues (https://github.com/FlutterFlow/flutterflow-issues/issues/1580, https://github.com/FlutterFlow/flutterflow-issues/issues/1567), with the latter providing a comparison between old and new autogenerated code.

**Comment by ibm777p2** [comment] 2023-10-05 16:34
> ** Posting this comment to both recent Algolia-related issues found here for the community**
> 
> I have also encountered this bug with Algolia search, which started last week, possibly due to recent updates. The bug affects date and time handling in Algolia search, returning null values when using date/time from Firebase, both with standard DateTime and UNIX-converted DateTime.
> 
> This issue was noticed on my end after updating a different section of my app without modifying Algolia-related code, suggesting the bug might be on FF's end. A current temporary workaround involves using Firebase queries for text display, but this isn't viable for filtering and displaying specific Algolia documents as Firebase queries can't conditionally hide widgets referencing a query on the same widget - it would have to come from a parent widget query (which means I can't filter on the front end)
> 
> To replicate, make listviews of Algolia searches that filter without referencing any date (should work fine), Algolia searches that filter using Date to Unix tmestamp (shouldn't work), and Algolia searches referencing the date and time without formating in the filter (shouldn't work). To test the text display issue, add text referring to an Algolia-referenced DateTime field, and you'll see a null return. The text display issue confirms that this is a bug probably only related to how the data is read regarding DateTime from Algolia to FF.
> 
> Notably, the Algolia search was functioning correctly in my build earlier last week. Another community member reverted to older autogenerated code from FF, resolving the issue. This FF community member noted that this problem occurs when the newly auto-generated FF code is added to a project. Others have reported similar issues (#1580, #1567), with the latter providing a comparison between old and new autogenerated code.

In a different topic we need partial data return from algolia search to gridview like the infinity scrolling feature in gridview but for algolia search. Now I'm just doing it through custom code.

**Comment by YatinBajajOP** [comment] 2023-10-07 17:11
I am facing the similar issue with my app, but instead of date, the fields containing any reference to another collection of firebase is returning me null.
I have a collection of posts which has a field of category, it is a reference to another collection called categories, when I run algolia search on the posts I get a null value returned in the field category.

**Comment by ibm777p2** [comment] 2023-10-07 18:07
> I am facing the similar issue with my app, but instead of date, the fields containing any reference to another collection of firebase is returning me null. I have a collection of posts which has a field of category, it is a reference to another collection called categories, when I run algolia search on the posts I get a null value returned in the field category.
The way I temporary solved this is to use the previous autogenerated filed in FF and put them to the current ones that returns null, check in list of fields that I replaced in my code above. This is only temp solution, FF need to autogenerate the correct code moving forward.

**Comment by ibm777p2** [comment] 2023-10-07 18:09
> > I am facing the similar issue with my app, but instead of date, the fields containing any reference to another collection of firebase is returning me null. I have a collection of posts which has a field of category, it is a reference to another collection called categories, when I run algolia search on the posts I get a null value returned in the field category.
> 
> The way I temporary solved this is to use the previous autogenerated filed in FF and put them to the current ones that returns null, check in list of fields that I replaced in my code above. This is only temp solution, FF need to autogenerate the correct code moving forward.

@agreaves and @kevintonb any updates on this?

**Comment by ChrisLowCode** [comment] 2023-10-08 08:31
I can confirm that trying to reference a document from an Algolia search also doesn't work. In my test case, this means that data can't be transferred to the next page which means the Algolia integration cannot be used. Maybe a doc references query from firebase can be the solution for that but that is a lot of unnecessary reads

**Comment by ibm777p2** [comment] 2023-10-08 15:11
> I can confirm that trying to reference a document from an Algolia search also doesn't work. In my test case, this means that data can't be transferred to the next page which means the Algolia integration cannot be used. Maybe a doc references query from firebase can be the solution for that but that is a lot of unnecessary reads

I can confirmed this need function that FF added to convert the data from algolia into FF values is making bad job most values returned null. My work around is to not use it in the auto generated code and use the old way.

This the new function that FF added for value conversion for algolia and doesn't work unless it's for latlng, anything else doesn't work.

```dart
import 'package:from_css_color/from_css_color.dart';

import '/backend/backend.dart';
import '/backend/schema/structs/index.dart';

import '../../flutter_flow/lat_lng.dart';
import '../../flutter_flow/nav/serialization_util.dart';

dynamic convertAlgoliaParam<T>(
  dynamic data,
  ParamType paramType,
  bool isList, {
  StructBuilder<T>? structBuilder,
}) {
  try {
    if (data == null) {
      return null;
    }
    if (isList) {
      if (data is! Iterable) {
        return null;
      }
      return data
          .map((p) => convertAlgoliaParam<T>(
                p,
                paramType,
                false,
                structBuilder: structBuilder,
              ))
          .where((p) => p != null)
          .map((p) => p! as T)
          .toList();
    }
    switch (paramType) {
      case ParamType.int:
        return isList
            ? (data as Iterable).map((i) => (i as num).round())
            : data?.round();
      case ParamType.double:
        return isList
            ? (data as Iterable).map((d) => (d as num).toDouble())
            : data?.toDouble();
      case ParamType.DateTime:
        isList
            ? (data as Iterable)
                .map((s) => DateTime.fromMillisecondsSinceEpoch(s))
            : safeGet(() => DateTime.fromMillisecondsSinceEpoch(data));
      case ParamType.LatLng:
        return isList
            ? null
            : safeGet(
                () => LatLng(data['_geoloc']['lat'], data['_geoloc']['lng']),
              );
      case ParamType.Color:
        return isList
            ? (data as Iterable).map((s) => fromCssColor(s))
            : safeGet(() => fromCssColor(data));
      case ParamType.DocumentReference:
        isList
            ? (data as Iterable).map((s) => toRef(s))
            : safeGet(() => toRef(data));
        break;
      case ParamType.DataStruct:
        if (structBuilder == null) {
          return null;
        }
        return isList
            ? (data as Iterable)
                .map((d) => structBuilder((d as Map).cast<String, dynamic>()))
            : structBuilder((data as Map).cast<String, dynamic>());

      default:
        return data;
    }
  } catch (e) {
    print('Error deserializing parameter: $e');
    return null;
  }
}

```

**Comment by ibm777p2** [comment] 2023-10-08 15:13
> @agreaves and @kevintonb any updates on this?

@agreaves and @kevintonb any updates on this?

**Comment by ibm777p2** [comment] 2023-10-08 19:27
> > @agreaves and @kevintonb any updates on this?
> 
> @agreaves and @kevintonb any updates on this?

@agreaves @kevintonb 
Can some body from FF explain is that new function convertAlgoliaParam to convert data from algolia into FF class values is for efficiency purpose? or what is that actually improving?

**Comment by YatinBajajOP** [comment] 2023-10-11 14:43
@agreaves @kevintonb 
Any updates on this issue?

**Comment by hariprasadms** [comment] 2023-10-11 20:27
Hi @ibm777p2 - I apologies for delay in responding for this issue. I had a quick look at your project and custom code setup. I see below warning message. Can you follow the note in the warning and revert back if any changes in the working status of this issue?

Also, did you try using algolia query option to double check you got the same issue ( May be this is not suitable for your case but just to double check. 

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/4d268613-cd12-4189-800f-c18ad81a548c)

**Comment by ibm777p2** [comment] 2023-10-12 00:53
> Hi @ibm777p2 - I apologies for delay in responding for this issue. I had a quick look at your project and custom code setup. I see below warning message. Can you follow the note in the warning and revert back if any changes in the working status of this issue?
> 
> Also, did you try using algolia query option to double check you got the same issue ( May be this is not suitable for your case but just to double check.
> 
> ![image](https://user-images.githubusercontent.com/17435678/274408977-4d268613-cd12-4189-800f->c18ad81a548c.png)

@hariprasadms  I have al ready reverted back to algolia^1.1.1, it still returning me null for date, reference and int fields.
Please review the screenshots below.

algolia^1.1.1
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/5303536/ea18ea1b-ca63-42bf-b6a7-eeb74996304b)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/5303536/9ee8b0dd-e44b-4172-8ad5-083d11fc610b)

if you review the array that algolia is directly returning here, it actually has values in date_created for position zero
from the result list.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/5303536/18b7f9b1-c1ab-4f5d-b9bd-2461afecb025)


But once it's mapped using the fromAlgolia function, the product list for position zero, the date_created value is null as shown in the image below.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/5303536/79a86645-dca6-4b07-be7e-82da1a24c135)

in the fromAlgolia mapping function use the convertAlgoliaParam method to map the value as shown in the image below and once I don't use that method convertAlgoliaParam everything return values a before no nulls. please review my previous post.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/5303536/e10d0fe4-1827-406f-b1f9-939ddcacfaf3)

**Comment by ibm777p2** [comment] 2023-10-12 00:56
> > Hi @ibm777p2 - I apologies for delay in responding for this issue. I had a quick look at your project and custom code setup. I see below warning message. Can you follow the note in the warning and revert back if any changes in the working status of this issue?
> > Also, did you try using algolia query option to double check you got the same issue ( May be this is not suitable for your case but just to double check.
> > ![image](https://user-images.githubusercontent.com/17435678/274408977-4d268613-cd12-4189-800f-%3Ec18ad81a548c.png)
> 
> @hariprasadms I have al ready reverted back to algolia^1.1.1, it still returning me null for date, reference and int fields. Please review the screenshots below.
> 
> algolia^1.1.1 ![image](https://user-images.githubusercontent.com/5303536/274449283-ea18ea1b-ca63-42bf-b6a7-eeb74996304b.png) ![image](https://user-images.githubusercontent.com/5303536/274449297-9ee8b0dd-e44b-4172-8ad5-083d11fc610b.png)
> 
> if you review the array that algolia is directly returning here, it actually has values in date_created for position zero from the result list. ![image](https://user-images.githubusercontent.com/5303536/274449541-18b7f9b1-c1ab-4f5d-b9bd-2461afecb025.png)
> 
> But once it's mapped using the fromAlgolia function, the product list for position zero, the date_created value is null as shown in the image below. ![image](https://user-images.githubusercontent.com/5303536/274449757-79a86645-dca6-4b07-be7e-82da1a24c135.png)
> 
> in the fromAlgolia mapping function use the convertAlgoliaParam method to map the value as shown in the image below and once I don't use that method convertAlgoliaParam everything return values a before no nulls. please review my previous post. ![image](https://user-images.githubusercontent.com/5303536/274450032-e10d0fe4-1827-406f-b1f9-939ddcacfaf3.png)

@hariprasadms would you please expedite the fix of this issue, it's causing many developers not able to load data from algolia and not able update their app.

**Comment by gematlas** [comment] 2023-10-12 04:42
z

**Comment by hariprasadms** [comment] 2023-10-12 12:07
Hi - I have tested and confirmed it as bug. Dev team will be looking to it shortly. Thanks for your patience.

**Comment by hariprasadms** [comment] 2023-10-13 09:35
Hello, Quick update. We have fixed this issue. It should be available in next updates.

**Comment by ibm777p2** [comment] 2023-10-13 16:22
> Hello, Quick update. We have fixed this issue. It should be available in next updates.

@hariprasadms what is the timeline to have this deployed to production?

**Comment by ibm777p2** [comment] 2023-10-19 21:06
> > > Hello, Quick update. We have fixed this issue. It should be available in next updates.
> > 
> > 
> > @hariprasadms what is the timeline to have this deployed to production? When would be next updates? this week or next week?
> 
> I see there is a new version of flutterflow now, that means the Algolia issue is fixed? @hariprasadms

I see the data coming from Algolia is working now.

**Comment by vivekraj** [comment] 2023-10-20 03:33
> > > Hello, Quick update. We have fixed this issue. It should be available in next updates.
> > 
> > 
> > @hariprasadms what is the timeline to have this deployed to production? When would be next updates? this week or next week?
> 
> I see there is a new version of flutterflow now, that means the Algolia issue is fixed? @hariprasadms

The datatype fields working for anyone? For me it is not working. Returning null. The firebase structure for the field is bookDetails (map)-> array[book(reference to book table),title(string)]. I can see the data on algolia response, but not appearing on test mode.

**Comment by ibm777p2** [comment] 2023-10-20 05:07
> > > > Hello, Quick update. We have fixed this issue. It should be available in next updates.
> > > 
> > > 
> > > @hariprasadms what is the timeline to have this deployed to production? When would be next updates? this week or next week?
> > 
> > 
> > I see there is a new version of flutterflow now, that means the Algolia issue is fixed? @hariprasadms
> 
> The datatype fields working for anyone? For me it is not working. Returning null. The firebase structure for the field is bookDetails (map)-> array[book(reference to book table),title(string)]. I can see the data on algolia response, but not appearing on test mode.

For me I'm getting all the data correctly from Algolia into my app, I haven't worked with the data you are talking about, in the mean time you can use the previous code version if you still have it. I think @hariprasadms would need to answer you on this one.

**Comment by srh98** [comment] 2023-10-25 01:21
Hi, I am also experiencing this issue. Lists of datatypes are being returned as null in Algolia results. We're using algolia for search in around 20 components in our live app so this is very frustrating as it's breaking stuff left right and center. As a workaround we're using the docref returned by algolia and then doing a document read from firestore with that reference, however that is far from ideal and not feasible in all of our components.

@hariprasadms is the development team still working on this?

**Comment by YatinBajajOP** [comment] 2023-10-25 01:29
Hi @srh98 
FF team pushed an update on last Thursday, i.e. on 19th of October and I can confirm that after that update both of the problems I was facing, were solved. 
I was getting null for the fields with reference to another collection and date time fields.

**Comment by srh98** [comment] 2023-10-25 03:24
Thanks @YatinBajajOP I see that date time fields and fields with references to other collection work. However, lists of datatypes are still returning as null.

**Comment by vivekraj** [comment] 2023-10-25 05:07
> Thanks @YatinBajajOP I see that date time fields and fields with references to other collection work. However, lists of datatypes are still returning as null.

I too confirm the same for the datatype fields. I'm also using the document reference on each item as a temporary workaround for now. Tried debugging it multiple ways, all shows that the data is null.

**Comment by ibm777p2** [comment] 2023-10-25 05:27
> > Thanks @YatinBajajOP I see that date time fields and fields with references to other collection work. However, lists of datatypes are still returning as null.
> 
> I also confirm the same for the datatype fields. I'm also using the document reference on each item as a temporary workaround for now. Tried debugging it multiple ways, all shows that the data is null.

I had that problem before so in the code I did what is shown below and you can probably use that as example to if that could your temporary work around @vivekraj 



new autogenerated code | previous auto generated code
-- | --
userId': convertAlgoliaParam(             snapshot.data['userId'],             ParamType.DocumentReference,             false,           ), | userId': safeGet(             () => toRef(snapshot.data['userId']),           ),

**Comment by srh98** [comment] 2023-10-27 04:18
hi @hariprasadms @aemelyanovff any update on this please?

**Comment by nicolas-gervais-42** [comment] 2023-10-30 18:17
Hello, also experiencing the issue regarding datatypes fields returning null

**Comment by Ortes** [comment] 2023-10-31 09:39
I think I found the bug.
I have a document named `ExercisesRecord` and a nested DataType named `ExerciseStruct` contained in the field named `fieldData`. It seems like the `ExerciseStruct` is parsed 2 times the first succeed but the second try fails because the `fieldData` is already a `ExerciseStruct` and not a `Map<String, dynamic>`.

Here is the stacktrace of where a second parsing is done.
![2023-10-31-103235_628x125_scrot](https://github.com/FlutterFlow/flutterflow-issues/assets/25187882/b10c271d-4b07-4829-b9f8-7968c8cdedff)

![2023-10-31-103407_672x199_scrot](https://github.com/FlutterFlow/flutterflow-issues/assets/25187882/a3553d26-4ce2-420a-8a1a-99903bbb9c66)

![2023-10-31-103438_529x108_scrot](https://github.com/FlutterFlow/flutterflow-issues/assets/25187882/04d3ee62-bab2-4ab2-9b4a-2f6486046939)

![2023-10-31-103500_388x147_scrot](https://github.com/FlutterFlow/flutterflow-issues/assets/25187882/4ce9cdd5-6be4-4613-889a-d6c5f6cec206)

![2023-10-31-103520_587x90_scrot](https://github.com/FlutterFlow/flutterflow-issues/assets/25187882/afbc11b8-4258-44c9-a92d-53c138726c8c)

![2023-10-31-103545_595x41_scrot](https://github.com/FlutterFlow/flutterflow-issues/assets/25187882/6a630b98-81ba-4232-ad8d-e04575bd22b6)

The code `ExerciseStruct.fromAlgoliaData(snapshot.data['fieldData'] ?? {})` is already transforming _JsonMap to `ExerciseStruct`.

Hope this help

**Comment by nathanwright17** [comment] 2023-11-02 05:00
Having issues with null returns for any search results dealing with data types. Live version still working fine so it's an issue with FF update. Can't publish any updates for the app until this is fixed!

**Comment by Ortes** [comment] 2023-11-09 09:49
Any news here ? I still cannot release my search bar because of this

**Comment by aemelyanovff** [comment] 2023-11-09 23:27
Sorry for the delay. This will be fixed in the next update.

**Closed by aemelyanovff** 2023-11-09 23:27 UTC
Labels: type: bug, status: confirmed

**Comment by srh98** [comment] 2023-11-11 07:56
As @Ortes says this is not fixed. Datatypes are still returning null.

**Comment by Ortes** [comment] 2023-11-11 15:16
I have open another issue [here](https://github.com/FlutterFlow/flutterflow-issues/issues/1827#issue-1988143533) in case it is not the same bug

**Comment by jasminder** [comment] 2023-12-21 12:17
I am also facing this bug right now. It should have been fixed by now. Only safeGet makes the data null or [] in case of list. Before safeGet, the data is working right. Like, I am trying to convert int to DateTime and a List of String to List of Document References.
