### ISSUE TITLE
Can't test my app after debug panel launch

### ISSUE THREAD

**Issue by marcelocariolato** [FlutterFlow/flutterflow-issues#3152] opened 2024-06-17 12:13 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After recent FlutterFlow updates inclunding debug panel launch, I no longer can test my app on Test mode. 

The app takes a lot of time to load Home Page when logged user has unempty list of activities that must be loaded from Firebase and then showed on the screen. 

The message "Error debug serializing parameter: Invalid argument: Maximum call stack size exceeded" is printed on the console hundreds of times as if it is on a loop. 

The app seems freezed as no action can be perfomed smoothly. Buttons actions are not perfomed. Even when I close debug panel, app behavior remains the same. Sometimes it takes the whole session trying to load debug panel informations and app's home page.

### Expected Behavior

Home page navigation should be normal.

### Steps to Reproduce

1. Login. You login with my own test user as home page content is not empty. Login: marcelo@oraco.com.br Password: 123456
2. You will land on the Home Page and the problem may be seen. Open console to see the messages.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEeiMrl8YlItb0D7rn6Le5smQMwJ0QlUIInj+0bWRMhfaLoB4YqdszRMhdLYtezfW5YIFqZsFE1wPzLiofuG/UBBzqdG9VAyYRXQTvgeDmWMM2wCqmeVnYnQOZhfHai4aTYsBV5IbBsWFoA3F6EOfCdG3qCf9qOYwx5e6fDbOY=

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/162353385/66f03bc8-cd71-4542-982b-10bd7f36b224

### Environment

```markdown
- FlutterFlow version: v4.1.60+
- Platform: Web
- Browser name and version: Microsoft Edge Version 126.0.2592.56 (64 bits)
- Operating system and version affected: Windows 11 Home Version 23H2
```

### Additional Information

If you can't reproduce the problem, please consider creating an option where I can disable debug panel. 
I feel like my business is paralyzed. My output has been reduced as I can't test new features smoothly to launch product updates. Thanks for help!

**Comment by msusviela** [comment] 2024-06-17 14:58
Hey @marcelocariolato, Thanks for your report, So sorry you are experiencing this issue. I was not able to reproduce this on a blank project, but it is replicable on yours. That's why I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. Thanks so much!

**Closed as not planned** 2024-06-17 16:38 UTC
Labels: status: can't reproduce
