### ISSUE TITLE
Build failing in test mode - package dependencies

### ISSUE THREAD

**Issue by martfo** [FlutterFlow/flutterflow-issues#3221] opened 2024-06-25 16:43 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hi team,

I've not made any changes to my app since 13/6. It compiled fine then. 
Now I'm getting a notification of build failure with a large number of dependencies failing.

### Expected Behavior

Expecting the test mode to compile the app.

### Steps to Reproduce

Click test.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4khefl3ItOn7xY17X5bcJsqCkQHDI3TL07ttYbZxUjIuPtBJh/PuClTFFtTdDhSmlhHE6buHoB+eDLkeLmUPcVEy+cRr5F/5Bibw7MTXq8SpvTPLuSVXclGcRVBXa417SRkCVNALBuL0Y/7WCIed7KFxPsJ5+/Zwh9f6PHaOI=

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/2203249/2f17994b-64b4-4e54-b2b5-f0c89518f290)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by msusviela** [comment] 2024-06-25 16:51
Hi all. It seems to be related to a package upgrade on [pub.dev](http://pub.dev/). Our engineering team is already aware and working on a fix.

I'm closing this issue because It's a duplicate of: [https://github.com/FlutterFlow/flutterflow-issues/issues/3217](https://github.com/FlutterFlow/flutterflow-issues/issues/3217) I'll be following this from this issue.

Thanks for your reports!

**Closed as not planned** 2024-06-25 16:50 UTC
Labels: closed: duplicate
