### ISSUE TITLE
Code Differences Between Downloaded Code and Pushed Code on Github

### ISSUE THREAD

**Issue by ShubhamHande99** [FlutterFlow/flutterflow-issues#2422] opened 2024-03-01 10:20 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Currently, to manage custom code, I have pushed code to the Git repository and am working on an Android studio using a local machine. For design-related changes, I continue to make them using the FlutterFlow platform. 

To quickly incorporate these changes into my local machine, I'm using the FlutterFlow CLI and specifying the same branch and destination as described in the documentation. It's working as expected, and I can see the changes in real-time on my local machine, allowing me to test everything smoothly on real devices. 

However, there are differences between the downloaded code directly from the FlutterFlow platform and the code pushed from the FlutterFlow platform. I have attached images showing the code differences. 

Some of the obvious differences include:
1. The downloaded code adds extra unused imports.
2. 'const' declarations are missing in the downloaded code.

If the project is large, I encounter a lot of GitHub conflicts every time I download the code using the FlutterFlow CLI. To address this issue, I have to resolve conflicts manually every time. Please fix this issue. It's a very important feature, and there should not be any code difference between the downloaded code and the code pushed to GitHub.

### Expected Behavior

There should not be any code difference between the downloaded code and the code pushed to GitHub.

### Steps to Reproduce

1. Let's say you are working on the FlutterFlow main branch.
2. Push the code to GitHub.
3. Git will push the code to a branch named "flutterflow."
4. Create a new feature branch in GitHub from that "flutterflow" branch to work on your local machine.
5. Now, go back to the FlutterFlow platform and make any changes to the main branch code, for example, changing the app bar name on the home screen.
6. Use the FlutterFlow CLI to download the main branch code and extract it on your local machine.
7. Observe that it downloads and extracts the code correctly, but you will notice differences in the downloaded code compared to the obvious changes I described earlier, as well as the attached images.
8. This workflow is useful for testing changes on a real device using a local machine quickly, but as the code is different, it causes a lot of Git conflict issues.
9. If I changed the Home screen in the FlutterFlow platform, then it should only show those files as changed in the Git changes when code download using CLI

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89grtsC0ZfcLMFAhQIgQ0QnU7gnlO1ucx4dC4OuBLAMZ8jCT0NKTcviS2xYEVaLoF0Kws7ej/DDOPoBE0mdGYhk0JVPERaUcH6jb7mYEcyKWnNCDd9nBX6dy5iNohQlBOx2WkIG32WDNq3qNleeY8aSfxBlZ7vfcPo=

### Context

1. The issue affecting me is that every time I download code using CLI, I have to resolve conflicts due to code differences.
2. What I'm trying to accomplish is that the code downloaded should be the same as the code pushed to GitHub, except the changes i did.

### Visual documentation

Left side code - is pushed to github from FlutterFlow and using in local machine
Right side code - is downloaded and extracted using FlutterFlow CLI from same branch it pushed to github

**1. 'const' keyword is missing from downloaded code**

<img width="1353" alt="code_difference_1" src="https://github.com/FlutterFlow/flutterflow-issues/assets/45396085/3949898b-ec0c-4742-93b6-627d1f9768fb">

**2. systemchrome related 'code' is missing in downloaded code**
<img width="1334" alt="code_difference_2" src="https://github.com/FlutterFlow/flutterflow-issues/assets/45396085/2733b0b3-dbe5-454f-8b46-eb1f08cf2f1a">

**3. adds unnecessary and unsued imports in downloaded code**
<img width="1327" alt="code_difference_3" src="https://github.com/FlutterFlow/flutterflow-issues/assets/45396085/4b51eefa-65ad-4d6e-8090-ed2834e91b60">

### Environment

```markdown
- FlutterFlow version: v4.1 and Flutter 3.13.7
- Platform:
- Browser name and version: Chrome, Safari
- Operating system and version affected:
```

**Comment by ignalauret** [comment] 2024-04-22 20:33
Hey @ShubhamHande99 thanks for you report. I can see that you have code conflicts because you have one code with "dart fix" executed and the other code without it. <br>You can go to App Settings > App Details > Download Settings, and disable Run "dart fix" for it to be downloaded without the performance enhancements. If not, you can configure your linter to perform dart fix each time you save the project, so you have all your code (GitHub and FlutterFlow) the same, given that the "dart fix" will make the exact same changes on the code.<br>Hope it was helpful, I'm closing the issue because it's not a bug. Have a great day!

**Closed** 2024-04-26 19:25 UTC
Labels: closed: not a bug
