### ISSUE TITLE
FCM token not generated

### ISSUE THREAD

**Issue by freya-hickman** [FlutterFlow/flutterflow-issues#565] opened 2023-03-02 16:23 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.

### Current Behavior

Using an Android or iOS device: 
1. Call Request Permissions - Notifications
2. FCM token is not created in Firebase database

### Expected Behavior

1. Call Request Permissions - Notifications
2. FCM token is generated for user in Firebase database

### Steps To Reproduce

With Firebase authenticated user, on Android device running OS 13 or an iOS device:
1. Have button that calls Call Request Permissions - Notifications
2. Check user document in Firebase for FCM token

### Bug Report Code

IT40hvHluI9Om9xE7aX6bu9alSg5KXo4a4Ir0u5RaCgoIYyuOpl/evWkflFvZ73jTAk/I0SmmmUep/DphYfAFcBcCxarbr56+ZYNThWUXT+Xa5OBPKq8VHx7EcZVJmKs5KS7ohV7JsxvSUIk7zuHfOvIYB7rJL6zImdISq/LZO4=

### Context

This issue means that we are unable to develop our push notifications feature. This is a critical, show-stopping feature for us.

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: ioS and Android
- Browser name and version: 
- Operating system and version affected:
```

**Comment by wenkaifan0720** [comment] 2023-03-02 16:35
Hi @freya-hickman, @agreaves. This should be related to https://github.com/FlutterFlow/flutterflow-issues/issues/329. If the user allows notification for the app, the FCM token should be generated next time the user logs in. What has changed is that Android 13 disables notification for an app by default.

**Comment by blueprin4** [comment] 2023-03-02 17:56
@freya-hickman sorry to ask but I am not sure what all steps you followed so I can help.  In FF settings that are a number of other steps to enable push notifications.  One important one is putting the description in the permissions settings under push notifications. If you have done all these can you please look at the your Xcode debug log and confirm if there is any push notifications request or communication of any kind.  I am an Xcode developer that is learning flutter/dart so I thought I would chime in when I seen your ticket.  Lastly

**Comment by freya-hickman** [comment] 2023-03-02 18:15
Hi @blueprin4 thank you for your reply. We are primarily testing on a phone on Android 13. The app's notifications are allowed in the phone's settings. When the action Request Permissions is called it does not generate the FCM token

**Comment by freya-hickman** [comment] 2023-03-02 18:16
@wenkaifan0720 I tested on a Samsung S22 on Android 13 too and it is not working

**Comment by blueprin4** [comment] 2023-03-02 18:36
> Hi @blueprin4 thank you for your reply. We are primarily testing on a phone on Android 13. The app's notifications are allowed in the phone's settings. When the action Request Permissions is called it does not generate the FCM token

No problem and sorry I am not proficient in android studios enough to offer assistance.  It does have a debug log so that will give you some clues.  The push notification system is pretty basic so it should be a solution for you soon once you double check each step for cloud messaging.  There is a lot of options that need enabled and if one is not then nothing will work correctly with it. That's why I asked what all steps where done to make sure none where missed.  You will still get the alert on the phone to allow push notifications even if steps where missed that will generate the fcm token.

**Comment by freya-hickman** [comment] 2023-03-02 18:59
@blueprin4 no problem, I really appreciate your help. There is nothing in the debug log to suggest what is going on and as far as we can tell all the things that need to be enabled are. We have been through all the guidance that FlutterFlow provides and the forum and it is still not working. Hopefully it is that there is a step missing that we currently don't know about, but it's also looking like it could be a bug.

@wenkaifan0720 When I look at the code that FF generates - it's not generating anything that looks like this that I can see. Does it for you? 

https://firebase.google.com/docs/cloud-messaging/flutter/client

**Comment by freya-hickman** [comment] 2023-03-02 20:14
It looks like the request permissions has changed for Android 13 +, is this being set correctly in the code FlutterFlow generates?

**Comment by wenkaifan0720** [comment] 2023-03-02 20:38
Hi @freya-hickman @agreaves. I just tested with my previous test project for https://github.com/FlutterFlow/flutterflow-issues/issues/329. Now the fcm token will not be generated for the user if the user registered when notification has been turned off and later enabled notification. The fcm token will still be generated when the user first enables push notification and then registers (I would imagine this route happens rarely). We definitely need to look into this issue a bit more.

**Comment by freya-hickman** [comment] 2023-03-02 20:50
The app was newly downloaded to my phone before testing and the
notifications were automatically off, so I imagine this is very common.
There are lots of people having issues with notifications and the FCM token
on the forum, maybe this is why.

Please look into it further as a matter of importance. Many thanks.

**Comment by agreaves** [comment] 2023-03-12 07:28
Closing as a duplicate of #329, which is now fixed ([link to resolution](https://github.com/FlutterFlow/flutterflow-issues/issues/329#issuecomment-1465111266))!

**Closed by agreaves** 2023-03-12 07:28 UTC
Labels: type: bug, status: confirmed

**Comment by freya-hickman** [comment] 2023-03-21 10:56
Hi, the FCM token is still not being generated. Despite permissions being granted on the phone, the app is not calling the addFCMToken Cloud function. Please help urgently.
