### ISSUE TITLE
FlutterFlow Side Dependency Error

### ISSUE THREAD

**Issue by samuellangarica** [FlutterFlow/flutterflow-issues#4446] opened 2024-10-22 23:46 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When running our app, I get the following error related to dependencies that are managed by FlutterFlow. I already have Flutter 3.24.3 properly installed

Resolving dependencies...
Note: vm_service is pinned to version 14.2.5 by flutter_test from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.

Because every version of flutter_test from sdk depends on vm_service 14.2.5 and every version of flutterflow_debug_panel from git depends on vm_service 14.2.1, flutter_test from sdk is incompatible with flutterflow_debug_panel from git.
So, because tec018_tansa depends on both flutterflow_debug_panel from git and flutter_test from sdk, version solving failed.

### Expected Behavior

I expect our app to run without any error unrelated to our development 

### Steps to Reproduce

Get Devices
Select Chrome
Test

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40lefq2ItOpbxF7aXUccBvoGA5KUAlRpEVjsFBaCgofePtOol3evWlSBJpXseoYFFMfUSmmn4GwNLzuOLxKPBfGzibRog4zLhQcT3zcGGua5OBOrjtQkBQQMFMC0iu0abUiCZDLfppSUYE1E62IN+WcHfaQ6btImdISq/LZO4=

### Visual documentation

![Screenshot 2024-10-22 at 4 23 44 p m](https://github.com/user-attachments/assets/0d73c6c9-9cb0-48f1-8260-388e88e81133)

### Environment

```markdown
- FlutterFlow version: v5.0.8
- Platform: Web
- Browser name and version: Google Chrome 130.0.6723.59 
- Operating system and version affected: macOS Sonoma 14.4
```

**Comment by paulperez-dev** [comment] 2024-10-23 10:19
Hi @samuellangarica,

Could you please try using Flutter version 3.24.2 and let us know if the issue persists?

Thank you!

**Comment by samuellangarica** [comment] 2024-10-23 13:44
Yes. I am using Flutter version 3.24.2. I previously made a typing error indicating I was using version 3.22.3

**Comment by michaelmakr** [comment] 2024-10-23 18:23
I am facing the same problem. 
```
Because every version of flutter_test from sdk depends on vm_service 14.2.5 and every version of flutterflow_debug_panel from git depends on vm_service 14.2.1, flutter_test from sdk is incompatible with flutterflow_debug_panel from git.                                                                                                                                                             
```

My environment:
Flutter version 3.24.2 on channel [user-branch]
Dart version 3.5.2
DevTools version 2.37.2
Android SDK version 35.0.0

**Comment by Serlych** [comment] 2024-10-24 19:23
Hello,

I am also encountering the same issue with version 3.24.2, and it has become a significant obstacle for our team, severely impacting our ability to meet customer commitments. Resolving this issue is critical for us, and we would greatly appreciate any efforts to address it as soon as possible.

Thank you!

**Comment by mollaie** [comment] 2024-10-28 09:43
I'm facing with the same issue and it won't let me to run any command, now I can not change the App launcher icon and it prevents app for release

**Comment by oskotsur** [comment] 2024-10-29 08:41
Having the same issue I upgraded Flutter SDK to 3.24.4 and the issue was solved.

**Comment by mollaie** [comment] 2024-10-30 11:29
@oskotsur I updated to 3.24.4 but not splash not app icon would change 
the error is gone and I'm able to generate the app launcher icon but then when I run the app either on iOS or Android the app icon is the flutter defualt and splash will appear with the white screen then move to my splash while I set different color for pre-loading color

**Comment by Alezanello** [comment] 2024-10-31 15:24
Hello everyone! It would be really helpful if each of you could share a Bug Report Code from your project in this thread. This will allow us to investigate the issue more effectively and understand why it’s occurring. Thank you!

**Comment by force-focus** [comment] 2024-11-09 03:09
The issue is not stale. This problem persists.

The issue arises after upgrading flutter

**Comment by rzambroni** [comment] 2024-11-20 14:19
Hi everyone,

If you're still running into this issue, please share a bug-report code so we can look into it further.

This situation is common when FlutterFlow upgrades to newer versions of Flutter/Dart. Custom code dependencies often need manual updates to match the new versions, as these adjustments can't be automatically handled by FlutterFlow.

* [Here](https://www.youtube.com/watch?v=8Y1uyCC_dXE) is a quick video that explains how to fix dependencies.


* If you are not being able to make it work you can also reach out to our support team directly for help (either by email at support@flutterflow.io or using the chat inside the app)

Hope that helps.

**Comment by Alezanello** [comment] 2024-11-25 20:14
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Closed as not planned by Alezanello** 2024-11-25 20:14 UTC
Labels: waiting for user response
