### ISSUE TITLE
Hover fill of IconButton differs from actual color

### ISSUE THREAD

**Issue by winthermich** [FlutterFlow/flutterflow-issues#1436] opened 2023-09-10 13:54 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When the hover-function is activated for an IconButton and a fill color is added, the color that is displayed during test + runtime differs from the defined color.

The issue is not present for the Button-control (I noticed the difference when have the two button types next to each other).

### Expected Behavior

The HoverFill of the IconButton should show the fill color provided.

### Steps to Reproduce

1. Add an IconButton and a Button to a canvas.
2. Activate "Button Hover Style", and add a hover fill color (#f1f1ff) to both controls.
3. Activate test mode, and hover above the two controls.
4. Notice that there's a difference between the hover colors displayed (if you have used #f1f1ff, then you will notice that the hover fill color of the IconButton is darker than the hoverfill color of the Button).

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXkMmAsJRNobVE+anQLcFFvCowGUQFUOdEl95Hd0gdCOPrBuwIP+CkcRZpTfW6aVNcAVmihkgF0+jlkvDlUe0pIRysb6p51pFTFxfke2ijSoyXDLWaRHEmBf1jIEfD3JivnBJ+NbZiSngX3ziqeemAcBXDFOu/Zwh9f6PHaOI=

### Context

I am trying to achieve a consistent design.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/144594075/84264a43-2275-4185-978a-5b35dad1be4d)

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: Web
- Browser name and version: Chrome 116.0.5845.180
- Operating system and version affected: Windows
```

**Comment by hariprasadms** [comment] 2023-09-10 17:18
Hi @winthermich - Thanks for submitting the issue. I can confirm that I can reproduce the behaviour. 

https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/52b0969f-1d09-49fb-b754-66be206db305

**Comment by chuggmuffin** [comment] 2023-09-18 15:29
Awesome thanks! Sorry I missed this one. I was also told it was not a bug. 

I will patiently await the fix! :D

**Comment by sbis04** [comment] 2023-09-22 13:23
Hey @winthermich, thanks for reporting the issue! It should be fixed in the next update! 😊

**Closed by sbis04** 2023-09-22 13:23 UTC
Labels: type: bug, status: confirmed

**Comment by winthermich** [comment] 2023-09-23 06:49
Hi @sbis04 
Awesome - great to hear! Thanks! :)
