### ISSUE TITLE
NoSuchMethodError when filtering in JSON path for API call

### ISSUE THREAD

**Issue by halvorot** [FlutterFlow/flutterflow-issues#336] opened 2023-01-10 17:21 UTC
## Expected behavior (required)
I expect the api to work as in the API Calls create tab in FlutterFlow. When pressing "Test API Call" I get a response and when entering JSON paths the result looks good. 

![Skjermbilde2](https://user-images.githubusercontent.com/36247551/211617891-eabe187d-e1b0-434c-bcc2-db568fb53793.PNG)

## Current behavior (required)
When testing the application I get a NoSuchMethodError: 'toList'

After searching the community for a cause/solution it seems that the problem is the use of brackets '[' in the JSON path. Brackets are necessary for filtering in the JSON path and should be supported.

![Skjermbilde](https://user-images.githubusercontent.com/36247551/211617988-a9bd3588-a78a-438d-9288-76c1d1678f43.PNG)

## To Reproduce (required)
1. Add Api call
2. Add JSON path containing filering using brackets. e.g: $.data.searchSuggestions[?(@.__typename=='SuggestedProduct')]
3. Create a page and run the api call
4. Start test mode
5. Observe the error as in the screenshot above

### Bug Report Code (required, generate from Widget Tree)
IT4ozMrqx5BOseFK0L6JccBKjSQ4Ql9+bZIalcpBZzUYF5SuCLMqY8mnP1tCZ7CnSnNmPk22p14Fp9KMiPOeO+4FExWafbpB+JBcWz3xWkKVaK3fU/HUACkbeacOQSj6

or

IT4ozMrqx5BOseFK0L6JccBKjSQ4Ql9+bZIalcpBay0jF7KuDLMqY8/RVERtZ+mid1Z5e2aZq2oW06jIjYfxFMEEJk6uf74/1cxccwv/Vn2VVK3TU/HUACkbeacOQSj6

## Context (required)
I am trying to call an API, get a resulting JSON object response, and filter the response on one of the properties using a JSON path

## Screenshots / recordings
![Skjermbilde2](https://user-images.githubusercontent.com/36247551/211617891-eabe187d-e1b0-434c-bcc2-db568fb53793.PNG)

![Skjermbilde](https://user-images.githubusercontent.com/36247551/211617988-a9bd3588-a78a-438d-9288-76c1d1678f43.PNG)

## Your environment
* Version of FlutterFlow used: v3.0 Flutter 3.3.4
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome
* Operating system and version (desktop or mobile): Windows 10

**Comment by yoheisoito** [comment] 2023-01-13 00:46
Hi @halvorot,

Thank you for submitting your issue.
I have added a JSON path containing filering using brackets on a sample site below.

https://jsonplaceholder.typicode.com/todos

with a sample query $[?(@.userId==1)]

I am able to preview my parsed results as well as use it under test and run mode on my environment.
Please see screenshots attached.

As my json queries are working fine, can you please double-check to see any errors on your query or by confirming that the above dummy api retrieval would work over a blank project?

Thanks again!

<img width="408" alt="Screen Shot 2023-01-13 at 9 40 53" src="https://user-images.githubusercontent.com/115172813/212211386-5d76c21e-cce9-48f0-a59e-02be3e86d0a6.png">

<img width="1009" alt="Screen Shot 2023-01-13 at 9 44 08" src="https://user-images.githubusercontent.com/115172813/212211375-a041ee00-20ee-4eef-803a-15ab6a493ba9.png">

**Comment by halvorot** [comment] 2023-01-14 17:24
I'm sorry, after some more debugging I found an error in my backend query configuration. Problem solved.

**Comment by halvorot** [comment] 2023-01-14 18:23
I found that the problem is in another place than the JSON path. It seems that when I set a backend API call "on change" of a seach field, then the action output til null until I start typing in the seach field. When the app then tries to generate children of a list based on the action output, we get an error.

Possible fix: Should not the app make an initial backend API call with the initial value of the search field on page load to make sure that the action output is not null?

**Comment by halvorot** [comment] 2023-01-14 18:27
Also when I try to bypass this by checking if the action output is null I get the following screen:
![image](https://user-images.githubusercontent.com/36247551/212489865-25982c96-c928-449b-959f-e1b60fcfeb79.png)

**Comment by halvorot** [comment] 2023-01-14 18:58
The API call with an empty string looks like this: 
![image](https://user-images.githubusercontent.com/36247551/212491522-cb85e9ae-c58c-4e49-8e5e-167b1bca9312.png)

I might be wrong but should not the outputs of json paths be empty lists and not null?

**Comment by Franco98404** [comment] 2023-01-19 04:23
> It seems that when I set a backend API call "on change" of a seach field, then the action output til null until I start typing in the seach field.

In mi case is very similar I have a textField when this happens, I am trying to search some value on database and when the query has results doesn't have problems, but when is empty raise the following error

![image](https://user-images.githubusercontent.com/36147203/213354292-c91b1d6e-58d6-4c65-897d-f94a49efd4f1.png)

![image](https://user-images.githubusercontent.com/36147203/213354333-1187b5a0-485d-4342-b714-455de22cdc8d.png)

Bug Report Code:
IT4ohfKA4YlOxPVd0a6IY+1omSQXOVg1R5IV0cpBazwbfe+uB4kqevfOTERocM++S2xiek2WjWoW0MLvuIXlKfQqCzGrG7pMybh2aBbdTk2taZCLU/HUACkbeacOQSj6

I found this problem in community
https://community.flutterflow.io/c/discuss-and-get-help/listviews-and-null-responses

**Comment by shelpert** [comment] 2023-03-30 01:33
Hello @halvorot @Franco98404,

Could you please update the steps to reproduce to reflect the search use case or link your project so that I can take a look? 

Thanks,
Sofia

**Comment by Franco98404** [comment] 2023-03-30 05:22
I don't have this problem right now

**Comment by shelpert** [comment] 2023-04-06 23:25
Hi,

We’re closing this issue since it seems to have been solved. If you are still having this issue, please add the requested information so we can verify and re-open the issue. Thanks!

**Closed by shelpert** 2023-04-06 23:25 UTC
Labels: status: can't reproduce

**Comment by ttjoonttkoon** [comment] 2024-04-08 02:52
same issue on my end

**Comment by itwrites** [comment] 2024-04-09 06:26
having the same issue.

**Comment by ttjoonttkoon** [comment] 2024-04-09 23:49
where you able to find a fix? sorry to re-open sort of this topic? thanks

**Comment by ttjoonttkoon** [comment] 2024-04-10 00:02
@shelpert i know this comes almost a year later but i seem to be having the same issue 

I will put down what i am doing here. 
I am trying to retrieve items from my algolia search linked to flutterflow 
the JSON is like this 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/77555167/c4066985-138b-4b4f-a414-e9da12a05e45)

in the API call detail i enabled the following: 
![APIParse](https://github.com/FlutterFlow/flutterflow-issues/assets/77555167/2c3641e6-2ab9-45fd-8c64-d9878a9d6dd8)

then i create the custom data type here: 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/77555167/348c8718-5330-4b53-8244-f754833c5202)

And i also created an appstate Variable which will be set when launching the algolia search : 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/77555167/c4b752e1-e7b2-4a76-8bcc-43b47bf01a22)
 
Up to there, i really followed the documentation on flutterflow as well as youtube video tutorials. 

Then in my code, i created a test page which has an inputText and a button to launch the search. The action is setup as follow: 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/77555167/97a8b460-1c94-4506-9310-5b67b886898c)

return is like this: 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/77555167/81825bfc-93e0-42d8-a9a1-b651aaee6e2c)


not sure what to do at this point! please help

**Comment by seckley** [comment] 2024-06-23 19:46
I am getting the same issue. It appears that the json body that is being returned starts with a variable name before the opening array braces "[" on all the api values that have list in the above messages. Same with my api call. This is what is returned from Shopify through there admin rest api.
![Screenshot 2024-06-23 154400](https://github.com/FlutterFlow/flutterflow-issues/assets/13813594/90eb19da-da81-4aab-bcdd-5f1f1036d573)
All the working api calls in your videos seem to no have the variable name and just start with the opening array brace. "["

**Comment by Hatchitss** [comment] 2024-08-08 01:01
I can confirm that the same JSON structure as in the picture above results in the error, did anyone find a workaround?

**Comment by Edigey21** [comment] 2025-05-06 13:58
aynı hatayı alıyorum api-football verileri için?
