### ISSUE TITLE
Node does not have a RichText property. New Page, Create with AI

### ISSUE THREAD

**Issue by rodseventup** [FlutterFlow/flutterflow-issues#5186] opened 2024-12-26 19:45 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

![Captura de Tela 2024-12-26 às 16 39 14](https://github.com/user-attachments/assets/b55c042e-6b07-4e97-a48d-ab1f54098720)
If I try to do it in this project or in another clone of it, I get this error. It only works if I do it in a project created completely from scratch. A new project.

### Expected Behavior

works

### Steps to Reproduce

1. Create new page
2. Create with AI

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfk8/fsYthnMxJ+r6JccdWmWMUH0ccTL4zlO1HcxAYGO/yPbJ/O/ekdRNtZ+aldHlhHE78mkAe0a3xiITDGMA3HxOdQKJE/6t2YD3gRXq8RL3TC7uafkZ6EdNWCkCf37eN2B4nOrRZLmQA2DqYCumyQXbYJ5+/Zwh9f6PHaOI=

### Visual documentation

![Captura de Tela 2024-12-26 às 16 39 14](https://github.com/user-attachments/assets/ff27ddb3-0022-45bc-a505-17b013d9eef3)

### Environment

```markdown
- FlutterFlow version: v5.0.21
- Platform:macOs
- Browser name and version:
- Operating system and version affected: macOs
```

**Comment by paulperez-dev** [comment] 2024-12-27 12:35
Hello @rodseventup,

Thank you for the report. I attempted to replicate the issue, but everything seems to be working fine on my end. Are you still experiencing this? It’s possible there was a temporary service outage that caused the issue.

Please let me know if it persists.

By the way, here is the page that was generated on my end using the prompt you shared:

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/0adf4ec6-d940-4d98-8e42-2acd74f79792/77609d15-ffa8-415f-88ee-9373816a441a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wYWRmNGVjNi1kOTQwLTRkOTgtOGU0Mi0yYWNkNzRmNzk3OTIvNzc2MDlkMTUtZmZhOC00MTVmLTg4ZWUtOTM3MzgxNmE0NDFhIiwiaWF0IjoxNzM1MzAyOTQ1LCJleHAiOjMzMzA1ODYyOTQ1fQ.8xI7ED9qTlp01siBnqURL2-SembWlCiM1LQVU39-KSE " alt="image.png" width="430" data-linear-height="627" />

**Comment by rodseventup** [comment] 2024-12-27 13:19
Yes, I can also create a page with AI like this when it’s a new project. The problem occurs when I try to create within this project of mine that I am working on at the moment. When the AI feature was launched by Flutterflow, this project already existed and always gave this problem. If you need, you can enter the project and try to create a page to check the error.

**Comment by paulperez-dev** [comment] 2024-12-29 22:16
Hey @rodseventup,

I was not able to reproduce this on a blank project, but it is replicable on yours. That's why I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: support@flutterflow.io or using the in-app chat inside of FlutterFlow. <br><br>I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. <br><br>If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. <br><br>Thanks so much!

**Closed as not planned** 2024-12-29 22:17 UTC
Labels: status: can't reproduce, closed: support request
