### ISSUE TITLE
After latest update- test on device error.

### ISSUE THREAD

**Issue by taken35** [FlutterFlow/flutterflow-issues#3225] opened 2024-06-25 18:29 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

This is what device log says: Resolving dependencies...
The current Dart SDK version is 3.3.0.

Because app depends on video_player_android >=2.4.15 which requires SDK version >=3.4.0 <4.0.0, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Try using the Flutter SDK version: 3.22.2. 

### Expected Behavior

there are no video_player_android package used in any of my custom codes. Testing was working fine a moment ago, nothing has changed to cause a possible error.

### Steps to Reproduce

Testing the app on the device. A moment ago the testing was working fine. 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

NA

### Visual documentation

NA

### Environment

```markdown
FlutterFlow v4.1.61+ released June 25, 2024
Flutter version is 3.19.1
```

**Comment by kaman1990** [comment] 2024-06-25 18:42
Also finding same issue.

**Comment by hoisel** [comment] 2024-06-25 18:45
Same error here after automatic update. After exporting code via CLI, I'm currently unable to run it:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/400244/226312db-a8a6-4771-8189-70d80f7f78e4)

**Comment by Scavuzzo** [comment] 2024-06-25 19:26
Same issue here:

Resolving dependencies...
The current Dart SDK version is 3.3.0.

Because efficast depends on video_player_android >=2.4.15 which requires SDK version >=3.4.0 <4.0.0, version solving failed.

**Comment by Psycoguana** [comment] 2024-06-25 20:00
Same here, I can confirm this happens on a blank project.

**Comment by rzambroni** [comment] 2024-06-25 20:16
hey @taken35, thanks for the report, we noticed that this happened because the macOS version was a bit behind and still running on the old version 3.19.1.

It appears to be fixed now and shows the correct version now. Please make sure to restart the app and check that the app is running: 3.22.2

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/7a9f3bc8-5843-4b14-89f2-ac9bb85b186d/4fd027e5-5d62-4374-8f9c-a01021ea9607?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83YTlmM2JjOC01ODQzLTRiMTQtODlmMi1hYzliYjg1YjE4NmQvNGZkMDI3ZTUtNWQ2Mi00Mzc0LThmOWMtYTAxMDIxZWE5NjA3IiwiaWF0IjoxNzE5MzQ2NjAxLCJleHAiOjMzMjg5OTA2NjAxfQ.Fh-I4ZV9lwsdNkNAeEAVpJzgv4wqkzhWGq30fO22EYM " alt="image.png" width="245" height="154" />

Also, please consider that:

* If you are trying to run your project locally on your machine you might also face this type of issue if you don't update your flutter version.
* This might cause a need for dependencies within custom code as well.

**Comment by andriideren** [comment] 2024-06-25 20:59
> hey @taken35, thanks for the report, we noticed that this happened because the macOS version was a bit behind and still running on the old version 3.19.1.
>
> It appears to be fixed now and shows the correct version now. Please make sure to restart the app and check that the app is running: 3.22.2
>
> ![image.png](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/bba01999-341e-4015-b524-fa22faf6f6e8/6b8cc4e8-d1f6-4b50-a312-0648c69ad45e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iYmEwMTk5OS0zNDFlLTQwMTUtYjUyNC1mYTIyZmFmNmY2ZTgvNmI4Y2M0ZTgtZDFmNi00YjUwLWEzMTItMDY0OGM2OWFkNDVlIiwiaWF0IjoxNzE5NDA5NzAyLCJleHAiOjMzMjg5OTY5NzAyfQ.e8H-YcCpaF8fDidcqIY6TtsKAh_QNCA4bg7s7leXBvU "=245x")
>
> Also, please consider that:
>
> * If you are trying to run your project locally on your machine you might also face this type of issue if you don't update your flutter version.
> * This might cause a need for dependencies within custom code as well.

Works great for me after last FlutterFlow Desktop update on Sonoma 14.5 / iOS 17.5 Emulator
Thanks for the rapid update!
Just as "nice to have" - it would be great if FlutterFlow Desktop auto-relaunch after "Local Run" setup as it remains "Inactive" and require manual restart of the app

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/df9fcc79-19fb-4652-89f8-3907c020e85f/c8a1cf44-afce-4589-af9c-e6ee739f2bd0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kZjlmY2M3OS0xOWZiLTQ2NTItODlmOC0zOTA3YzAyMGU4NWYvYzhhMWNmNDQtYWZjZS00NTg5LWFmOWMtZTZlZTczOWYyYmQwIiwiaWF0IjoxNzE5NDA5NzAyLCJleHAiOjMzMjg5OTY5NzAyfQ.DAkH0j8VELFxrdYE0vgOyGXjudoDz9nz2nAdCdQx03U)

**Comment by rsstevearend** [comment] 2024-06-26 00:18
<img width="251" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/3091488/7fbf1787-d0f1-4b87-aaaa-a50c048d6fb2">

Can't publish to the web.  I'm on Mac

**Comment by taken35** [comment] 2024-06-26 09:20
hey @rzambroni,
I am testing them through a windows desktop, now I updated it to the latest version:
<img width="194" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/28500727/a651f4a6-aaff-4541-bc31-929420fedf0a">


However, this time I got different error: Launching lib\main.dart on SM G965F in debug mode...
Upgrading build.gradle
Running Gradle task 'assembleDebug'...                          
../../../../Local/Pub/Cache/hosted/pub.dev/pdf_widget_wrapper-1.0.3/lib/src/widget_wrapper.dart:173:11: Error: No named parameter with the name 'size'.
          size: Size(
          ^^^^
../flutter/packages/flutter/lib/src/rendering/view.dart:28:9: Context: Found this candidate, but the arguments don't match.
  const ViewConfiguration({
        ^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception


I checked my custom codes and there are no pdf_widget_wrapper package used but I use pdf package from pub.dev (up to date), and pdf_widget_wrapper is depended on this pdf package. I don't know if these are related but overall I can not run and test my project on a local device right now.

**Comment by rzambroni** [comment] 2024-06-26 13:57
Hey @taken35, you might need to fix that  dependency your pdf_widget_wrapper relies on.

In case it is helpful here is a quick guide on how to fix dependency issues: [https://www.youtube.com/watch?v=8Y1uyCC_dXE](https://www.youtube.com/watch?v=8Y1uyCC_dXE)

**Comment by Psycoguana** [comment] 2024-06-26 14:11
I can build for iOS now, but not for android. I deleted the local exported project, but I keep getting the following error:
**EDIT:** I can confirm this also happens on a blank project.


...
Running Gradle task 'assembleDebug'...                          

FAILURE: Build failed with an exception.

* Where:
Settings file '/Users/username/Library/Application Support/io.flutterflow.prod.mac/projectName/android/settings.gradle' line: 22

* What went wrong:
Plugin [id: 'org.jetbrains.kotlin.android', version: '1.8.10', apply: false] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Included Builds (None of the included builds contain this plugin)
- Plugin Repositories (could not resolve plugin artifact 'org.jetbrains.kotlin.android:org.jetbrains.kotlin.android.gradle.plugin:1.8.10')
  Searched in the following repositories:
    Google
    MavenRepo
    Gradle Central Plugin Repository
....

**Comment by rzambroni** [comment] 2024-06-26 14:15
Can you please provide me with the steps to replicate in a blank project? thanks.

**Comment by Psycoguana** [comment] 2024-06-26 14:18
Sure, although there're not that many steps.

1. Create a new project.
2. Try to use Local Run with a physical android device. 

That's it, it throws that error.

I was able to build the apk online tho

**Comment by Psycoguana** [comment] 2024-06-26 17:48
I didn't change anything, but it seems to be working now

**Comment by rzambroni** [comment] 2024-06-26 18:13
ok cool, i wasn't able to replicate either

**Closed as completed by rzambroni** 2024-06-26 18:13 UTC
Labels: waiting for user response
