### ISSUE TITLE
dataTable does not show the option to create the query in the database

### ISSUE THREAD

**Issue by ingsistempro** [FlutterFlow/flutterflow-issues#2311] opened 2024-02-07 00:26 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When attempting to perform dynamic queries in a database using DataTable with Firebase, we encounter a limitation that prevents the creation of dynamic queries in the database to display the data in the table. This negatively affects the expected functionality of the application as it does not display the query creation icon

### Expected Behavior

After reviewing all FlutterFlow manuals and guides, it appears that when using the DataTable widget, database queries are required. However, despite our efforts, we have been unable to perform the query, resulting in the icon not being displayed in the framework.

### Steps to Reproduce

1. create data table
   2\\\\\\\\.generate the query

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/e2b91dbd-e6a8-4ffb-be82-46100850a177/9dbf0574-f9a9-4ee9-83d6-c37d73548fec?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lMmI5MWRiZC1lNmE4LTRmZmItYmU4Mi00NjEwMDg1MGExNzcvOWRiZjA1NzQtZjlhOS00ZWU5LTgzZDYtYzM3ZDczNTQ4ZmVjIiwiaWF0IjoxNzA3Mjk2ODk0LCJleHAiOjMzMjc3ODU2ODk0fQ.tFJSb3jGSYOoWytIlLb8gzyUNQdYwZsT9jyZEh9-CLI)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFflcmAvM91rs9H+YSJdcBKmiQ6NkccTuQ/itUbTQ0gF4jyBJsUZ8nRQHdVXc+hdG03Imejnjo0p/yNk/bIN/cqNk+BbJs//rltWD3gQlq7Wr6WC82BdXBfPNpKBWad1MCC2B1DAPp0SUY71HGqJN/JVnHrGZzvDlgZHM6KOpn7o3/uQ0SLb3kNh1JWeC/v

### Context

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/674155ae-be61-42b1-8fa6-1e5314a86882/7a49e53d-d257-452e-99db-e4659680fe56?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82NzQxNTVhZS1iZTYxLTQyYjEtOGZhNi0xZTUzMTRhODY4ODIvN2E0OWU1M2QtZDI1Ny00NTJlLTk5ZGItZTQ2NTk2ODBmZTU2IiwiaWF0IjoxNzA3Mjk2ODk0LCJleHAiOjMzMjc3ODU2ODk0fQ.6wDXrPdzdzCFIFP6gV-gWTkNJuq3Dmio6DqDr9FH-RI)

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/40f3b7de-d2c8-45ef-93c0-48af0928afe6/21891f9e-f42d-4f21-b282-56835b969b84?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80MGYzYjdkZS1kMmM4LTQ1ZWYtOTNjMC00OGFmMDkyOGFmZTYvMjE4OTFmOWUtZjQyZC00ZjIxLWIyODItNTY4MzViOTY5Yjg0IiwiaWF0IjoxNzA3Mjk2ODk0LCJleHAiOjMzMjc3ODU2ODk0fQ.I6SH7YlrffDHhOPGu25WX1ljir-VsK-SbQOemg34yvo)

### Additional Info

*No response*

### Environment

```markdown
FlutterFlow v4.1 released February 2, 2024
Flutter version is 3.13.7
crhome.
Brave Versión 1.62.156 Chromium: 121.0.6167.139 (Build oficial) (64 bits)
windows OS 64 bits, x64
```

**Comment by hariprasadms** [comment] 2024-02-09 11:23
Hi @ingsistempro - This is as per the design. This is as per recent changes to Data-Table widget. You can wrap the Data-Table with container widget to add the query and map the query output to Data-Table widget.

This is not a bug. Hence closing the issue. Thanks

**Closed** 2024-02-09 11:23 UTC
Labels: closed: not a bug
