### ISSUE TITLE
ListView unable to refresh data

### ISSUE THREAD

**Issue by adelmokhtari** [FlutterFlow/flutterflow-issues#113] opened 2022-11-09 17:00 UTC
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
In a Listview builder with an API call, both "Pull to refresh" or a triggered action "Refresh Database Request" should refresh the data.

## Current behavior (required)
Currently, on some pages, the data isn't updated. A workaround is to enable infinite scrolling on the API call.

## To Reproduce (required)
1. Create new page with app bar
2. Add ListView widget
3. Connect to an API call to get a list
4. Enable pull to refresh on ListView and on API call
5. Generate Children with variable
6. Add Column with a few Text children widgets with data 
7. Add in app bar an Icon button and add action "Refresh Database Request"
8. Try both the button and pull to refresh

Code compiled locally gave the same result.

## Context (required)
We need to refresh the ListView once the user returns from a custom edit view page. The data isn't updated on UI.

## Actual Problem
After debugging the issue it is actually in the FutureBuilder function.

**Current generated code :**

```
        builder: (context, snapshot) {
          // Customize what your widget looks like when it's loading.
          if (!snapshot.hasData) {
            return Center(
              child: SizedBox(
                width: 50,
                height: 50,
                child: SpinKitRipple(
                  color: FlutterFlowTheme.of(context).primaryColor,
                  size: 50,
                ),
              ),
            );
          }
          final filtersDrawerGetModuleFiltersResponse = snapshot.data!;
```

**Should be :**

```
        builder: (context, snapshot) {
          // Customize what your widget looks like when it's loading.
          if (!snapshot.hasData) {
            return Center(
              child: SizedBox(
                width: 50,
                height: 50,
                child: SpinKitRipple(
                  color: FlutterFlowTheme.of(context).primaryColor,
                  size: 50,
                ),
              ),
            );
          }
          if (snapshot.connectionState != ConnectionState.done) {
            return Center(
              child: SizedBox(
                width: 50,
                height: 50,
                child: SpinKitRipple(
                  color: FlutterFlowTheme.of(context).primaryColor,
                  size: 50,
                ),
              ),
            );
          }          
          final filtersDrawerGetModuleFiltersResponse = snapshot.data!;

```
More information on this issue:
[https://github.com/ddikman/flutter-rerunnable-future-builder](https://github.com/ddikman/flutter-rerunnable-future-builder)

**Comment by hariprasadms** [comment] 2022-11-09 20:18
Hi @adelmokhtari - The way it is working now as per the current design of the refresh data feature. By looking what you are asking and the examples you have given, it more sounds like feature request/ update to current implementation. 
I will pass this issue to flutter dev team to decide the status of it. 

Hi @katherineqian over to you :)

**Comment by adelmokhtari** [comment] 2022-11-10 17:58
Hi @hariprasadms, I assumed that pull to refresh and refresh database requests should always work.

**Comment by katherineqian** [comment] 2022-12-06 20:44
Hi @adelmokhtari, appreciate all the extra info you've added to this report. I agree with @hariprasadms's assessment that this is an improvement to our current implementation, so the line between bug and feature request is not super clear - but happy to mark it as confirmed and work on this. 

Thank you for your contribution!

**Comment by agreaves** [comment] 2023-04-05 04:22
Hi all, looks like this one slipped between the cracks, but as of the latest version of FlutterFlow I'm not able to reproduce this behavior. Given that and the age of the ticket I'm going to close this issue for now. If you're still experiencing the issue, please let me know and add the Bug Report Code and I can re-open the ticket.

**Closed by agreaves** 2023-04-05 04:22 UTC
Labels: status: confirmed, priority: low
