### ISSUE TITLE
Enums are not correctly deserialized when being returned on an algolia search

### ISSUE THREAD

**Issue by joekman990** [FlutterFlow/flutterflow-issues#2756] opened 2024-04-17 19:27 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

when creating a listview that shows the results of an algolia search if one of the fields is an enum it is not being deserialized and i believe it is being returned as a String causing a null value in the ui 

### Expected Behavior

i expect to have the value properly valued as an enum

### Steps to Reproduce

1. add a schema to firebase with a enum value in a field
2. add algolia to the project
3. add a listview that displays the results of an algolia search
4. add some variable that is set to the enum field of the algolia search with a default value i chose ERROR
5. run in run mode
6. search for an item and see the value in the listview

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oz/Hqx89goctD7s+BasJViSQWOUAiR7hEmMpBay0jF7KuDLMqY8/RVERCOdOnd1VAeWGJhWoW08rQjvLhDcAqCAqtf4Bl1c1ATD3gWl6QMKqbFJWgeXEnL+5RJ37G1sKn3RElXcVucWQA32a2N+u8cDTaQ5z3OkgeDq/LZO4=

### Context

i have had to use the reference that is returned from the algolia search to then call the doc from firebase instead of just using the algolia search which is a waste of resources and money

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/72816439/80268a2a-8afd-40d3-b70e-40a1a2f74627

### Environment

```markdown
- FlutterFlow version: v4.1.34+
- Platform:web/desktop
- Browser name and version:chrome
- Operating system and version affected: macos 14.4.1
```

**Comment by artemBobrov** [comment] 2024-04-17 20:51
Have a similar issue
All the enums used in the app state someway are nulled and reassigned to default value.

actually have a large number of crushes in different places after today's update..

hope would be fixed asap

**Comment by joekman990** [comment] 2024-04-22 20:55
Yes i see it in algolia it is stored as a string

**Comment by ignalauret** [comment] 2024-04-24 18:58
I was able to reproduce your issue, I'm sending it to the Technical team so they can check why the enums are not being parsed from the Algolia result. <br>They will keep you updated on this thread, have a great day!

**Closed** 2024-05-30 04:06 UTC
Labels: status: confirmed, Enums, Bug

**Comment by QuinnGunter** [comment] 2024-06-05 18:20
I am not sure if the update for this is out for the public on the latest build. 
However, when I run my app on web the results are returned as I would expect. But when I test on Android & iOS I still see this issue where the results are not being returned when there is an enum associated with the results.

**Comment by QuinnGunter** [comment] 2024-06-24 14:29
@ignalauret @leighajarett @AnushaFF  this issue is still present when on mobile. A few users have posted on the community. It seems to be the same issue as this. I didn't want to make a duplicate issue since this was been opened and closed.

@joekman990 has this fixed your issue? I've been trying for some time to get to the bottom of this issue. 


Community post about the issue 
- https://community.flutterflow.io/ask-the-community/post/algolia-search-results-are-not-populating-when-the-results-contain-an-NNenY1lbFZdjGcs?highlight=S82YsSbfEXYBtid

**Comment by fabiofcos** [comment] 2024-06-24 14:59
Same problem here!

**Comment by joekman990** [comment] 2024-06-24 15:02
@QuinnGunter  I have to check it out I'll let you know

**Comment by mohn93** [comment] 2024-07-03 16:36
This should be reopened, I'm facing the same issue here

**Comment by QuinnGunter** [comment] 2024-07-14 19:24
@mohn93 have you gotten a new issue up for this? I'll be summiting a new issue this week some time as well

**Comment by mohn93** [comment] 2024-07-15 11:06
> @mohn93 have you gotten a new issue up for this? I'll be summiting a new issue this week some time as well

Nope i haven't, yeah that would be great actually
