### ISSUE TITLE
Media in MediaDisplay widget within Container with max-width/max-height values jumps around on page load

### ISSUE THREAD

**Issue by ayuno** [FlutterFlow/flutterflow-issues#186] opened 2022-12-02 09:22 UTC
## Expected behavior (required)
I am building a chat screen with functionality to upload & show images/videos. In most chat applications, media is not shown with a fixed height or width, but rather, max-width and max-height values are determined, and the media shrinks to accommodate one of those attributes while keeping the aspect ratio.

## Current behavior (required)
I have implemented the above, and it seems that the Container is briefly unaware of the size of the image/video. Because of this, the Container first expands to its max values before taking its final shape. This results in a jumping-around action that is seen in the below video.

## To Reproduce (required)
1/ Create a Container with max-width and max-height values
2/ Add a MediaDisplay widget in the Container, do not specify height or width for either the image or the video
3/ Set MediaDisplay path from Firebase

### Bug Report Code

ITFTi/Lq25NOm+Fa+Kn2bu1oiikXI0MZXYIrie5+Zz0YF5TpPJkAOvWkNxZvZ9PnS2xEPESmmk8yzN70ht7tCPYBOTWtR4A61rlqdTnzfDuuZcHfU/HUACkbeacOQSj6

## Context (required)
I don't want any jumping-around behaviour. I would actually prefer a loading widget if the Container needs time to adjust.

## Screenshots / recordings

https://user-images.githubusercontent.com/21143928/205257678-fa7c68f6-f1bc-4a96-9a23-d9e956721cf5.mp4

## Your environment

* Version of FlutterFlow used: 3.3.4
* Platform (e.g. Web, MacOS Desktop): Web Test/Run mode and iOS 
* Browser name and version: latest Chrome
* Operating system and version (desktop or mobile): Windows 10, iOS 16

**Comment by Pepino-GR** [comment] 2022-12-02 16:48
Hi ayuno,

I cannot reproduce the issue with your methods to reproduce. The video shows a lot of more widgets inside the page. To reproduce, I need some more information about the page and the included widgets.

**Comment by ayuno** [comment] 2022-12-04 14:55
Hi @Pepino-GR! Thanks for taking a look.

I just realized that I missed one important detail - I can only reproduce the error if the Container is wrapped within a ListView widget. I think multiple images/videos slow down the page enough so that the UI shifting becomes noticeable.

I created a page called "test" in my project: https://app.flutterflow.io/project/matenic-3p61rm

This page has only the minimum required widgets to reproduce the error (ListView, Container, Image) and I'm using a Firebase db with various images/videos of my dog :)

**Comment by Pepino-GR** [comment] 2022-12-10 13:11
Hi ayuno,

I cannot reproduce this issue at all. If it is possible, please share a runtime of the project, or better, share a sample project to the public.

**Comment by ayuno** [comment] 2022-12-11 18:15
Hi @Pepino-GR - sorry, I thought you had access to my project as a developer. I created a brand new sample project, and I've managed to reproduce the error with sample images as well, not just my assets in Firebase.

I've made it public here: https://app.flutterflow.io/project/sample-error-p450bl

Whatever images you get, the screen will jump around considerably as the Container first stretches to its max size while the images load, and then it shrinks to the size of the images.

**Comment by Pepino-GR** [comment] 2022-12-12 16:22
Hi ayuno,

the system does what it should. First it draws your container 75 x 300 and then, it fits the image into it. If you set the container with a different color, you see what it does. Remove the fixed size of the container and it works as you expect.

**Comment by ayuno** [comment] 2022-12-13 21:57
Hey @Pepino-GR! I understand what it's doing - I described the same thing earlier.

But I don't understand how removing the max-width and max-height attributes (your solution) would solve my issue. If I did that, the images that the user adds to the chat would have no bounds and could take up the whole screen. 

I think the solution here would be some sort of pre-loading behavior. I accept that the Container first needs to expand and then collapse, and that this is the amount of time it takes to do that. But having this layout shift is very disorienting. I would much prefer to have a loading screen instead.

**Comment by Pepino-GR** [comment] 2022-12-14 01:05
Hi ayunu,
I didn‘t recognized, that you would like to use it in a chat. Have you tried the Chat Page Template?

**Comment by Pepino-GR** [comment] 2022-12-14 10:06
I will set a feature request and close the issue

**Comment by shelpert** [comment] 2023-01-03 17:03
Hi ayuno,

I agree that setting the Container size from a database field is a great solution! I have added your feature request to our queue and will update this thread once we have implemented the feature.

Best,
Sofia

**Closed by shelpert** 2023-01-03 17:03 UTC
Labels: closed: feature request

**Comment by ayuno** [comment] 2023-01-03 17:55
That's amazing news @shelpert, really looking forward to it!
