### ISSUE TITLE
Typo in the generated code

### ISSUE THREAD

**Issue by mvsn** [FlutterFlow/flutterflow-issues#3677] opened 2024-08-23 16:34 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Unexpected Null Value:

I'm showing/ hiding a 'verified' icon if the user is/ isn't verified. The code generated has a typo - see 'visibibility' in the code below:

// Generated code for this verified_icon Widget...
if (_model.userRecord?.verified ?? true)
  Align(
    alignment: AlignmentDirectional(1, -1),
    child: wrapWithModel(
      model: _model.verifiedIconModel,
      updateCallback: () => setState(() {}),
      child: VerifiedIconWidget(
        visibibility: FlutterFlowTheme.of(context).bORDERtextfield,
      ),
    ),
  )

### Expected Behavior

fix the typo in 'visibibility'

### Steps to Reproduce

1. Log sign up using (5107923296), code: 123456
2. Click on the 'Profile' link in the home page
3. Error

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ol+fl/otOtbxG15DUcvlagSQ7Q0A6bJIomspBazwbfe+uB4kqevfOTERWXbTjTW9IOWKkkWoW0ejNvs7DLPU6Ik2cbKE++LlucTndRTmuRJfRFJWgQnJTGeBbN2K7y8CJphJ4GLZZSV4bw06lf+fIVivXCZexOlUeDa/LZO4=

### Visual documentation

![Screenshot 2024-08-23 8 37 42 AM](https://github.com/user-attachments/assets/a0ca80b6-f42f-4c67-9135-b2137c1fb9b9)

### Environment

```markdown
- FlutterFlow version: 4.1.83
- Platform: Web
- Browser name and version: Version 126.0.6478.222
- Operating system and version affected: Chrome OS
```

### Additional Information

unable to make progress/ complete proj

**Comment by paulperez-dev** [comment] 2024-08-26 00:56
Hi @mvsn! The typo is in the widget definition (not FF): 

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/b6d113a7-3b79-450d-a0d5-3988aab324fe/59b11b58-a867-4560-a942-a85321c02f32?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iNmQxMTNhNy0zYjc5LTQ1MGQtYTBkNS0zOTg4YWFiMzI0ZmUvNTliMTFiNTgtYTg2Ny00NTYwLWE5NDItYTg1MzIxYzAyZjMyIiwiaWF0IjoxNzI0NjMzNzY2LCJleHAiOjMzMjk1MTkzNzY2fQ.P7HUllQSjdsg_FJQ0aFjZpBL8buosGXXvLKLzNuwv9c " alt="image.png" width="274" height="312" />

I'm closing this issue since this is not a bug.

**Closed as not planned** 2024-08-26 00:57 UTC
Labels: closed: not a bug

**Comment by mvsn** [comment] 2024-08-26 01:42
??
