### ISSUE TITLE
When I deploy to Google Play Store (first time) this error appears: "Build AAB with Flutter"

### ISSUE THREAD

**Issue by cherrycokes** [FlutterFlow/flutterflow-issues#1853] opened 2023-11-14 23:54 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I've been trying to deploy to Google play store for the first time, but an error message keeps coming up without the AAB files. I've followed all the tutorial steps exactly as laid out, and still I get the same error message without AAB files to download. Submitting to Apple's App Store has worked perfectly and was a breeze, but this Google Play Store seems to be a bug here. 
<img width="852" alt="Screenshot 2023-11-14 at 11 03 56 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/150866768/b89ae0bd-03b3-4fa8-967b-9b922644cef6">

### Expected Behavior

According to all the tutorials, I should get an error message BUT with the AAB files to download. Instead I get an error message and it says "Build AAB with Flutter"

### Steps to Reproduce

<img width="648" alt="Screenshot 2023-11-14 at 11 03 45 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/150866768/7296d773-be3e-4a40-b0e7-e1eefe2c22a8">

![Screenshot 2023-11-14 at 12 59 01 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/150866768/ccc38621-4731-4954-a252-28f69fedbc75)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

fgdssd

### Context

Trying to deploy, and nothing happens. Which is frustrating

### Visual documentation

<img width="648" alt="Screenshot 2023-11-14 at 11 03 45 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/150866768/232a811b-f4c9-4ecb-8ceb-3a36d58b5919">

![Screenshot 2023-11-14 at 12 59 01 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/150866768/e33a3a08-1c59-4c46-bb4a-9444a53effcc)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by natasha-sb** [comment] 2024-01-09 16:41
What is the solution to this or a workaround?  It is preventing my ability to push to Google Play....  @hariprasadms

**Comment by sbis04** [comment] 2024-01-27 05:17
@cherrycokes @natasha-sb are you still facing this issue? If you are, then please add a "Bug Report" code from your project. Since the issue is not related to any widget, just go to the Widget Tree view, right-click on any widget, and get the bug report code.

**Comment by hariprasadms** [comment] 2024-02-02 10:11
Hi @cherrycokes - Are you still experiencing the issue ? If it is resolved, please close the issue. Thanks

**Comment by sbis04** [comment] 2024-02-07 13:39
Closing this issue due to inactivity. If you are still facing the issue, feel free to re-open.

**Closed by sbis04** 2024-02-07 13:39 UTC
Labels: type: bug, status : project specific, waiting for user response
