### ISSUE TITLE
Launch url is not properly set

### ISSUE THREAD

**Issue by zeuz-it** [FlutterFlow/flutterflow-issues#3385] opened 2024-07-12 14:25 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I define a launch url action to a container's click action after a certain condition is met, I get the error "Launch URL specified in launch by openFileContainer(container name) is not properly set." The parameter I give to the launch url action is an image path type field of a firebase document that comes as a parameter to the page I am on.

### Expected Behavior

I expect it to open the incoming image path url in a new browser tab with the click action without an error and it does so. However, my project shows errors and therefore I cannot get apk and test it on the web.

### Steps to Reproduce

1. I define the click event action of a container called "openFileContainer" which contains a stack widget with an icon widget inside.
2. The action starts with a condition, the condition is the equality condition of a value that comes as a parameter to the page I am in.
3. When the condition is met, I give the value of a field of the Image Path type in the firebase document that comes as a parameter to the page I am in as a parameter to the launch url action.
4. I get the error "The initialisation URL specified by openFileContainer on initialisation is not set properly.".

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48lcmAvM9Pm8ta0LX1bcdvimEXOVs7R+cNi+pDRUs8J5DaPOxzP/TBaldWUs+0Y0FmPU2gjXM0+cnemvDlEvY4KQ6dQYh4yKVQeAqVLXymeK7XOqqdOG5/DfJWIWrF1pm0kwhNAPRtS14t3DmuGOmXfHLbH4T6DDABJ+SKB5OK2SrDX1iXc2URm05KZDPz

### Visual documentation

<img width="1274" alt="Ekran Resmi 2024-07-11 12 40 33" src="https://github.com/user-attachments/assets/aa85295a-f56e-471e-9c30-44ebc2351ab8">

### Environment

```markdown
- FlutterFlow version: 4.1.71
- Platform: IOS
- Browser name and version: Chrome 126.0.6478.127 (arm64)
- Operating system and version affected: Mac OS 14.5
```

**Comment by msusviela** [comment] 2024-07-12 20:06
Hey @zeuz-it, Thanks for your report, So sorry you are experiencing this issue. I was not able to reproduce this on a blank project, but it is replicable on yours. That's why I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. Thanks so much!

**Closed as not planned by msusviela** 2024-07-12 20:07 UTC
Labels: status: can't reproduce, closed: support request
