### ISSUE TITLE
Issue with Loading LottieFiles from URL when Set from String Value on FlutterFlow

### ISSUE THREAD

**Issue by paulVu** [FlutterFlow/flutterflow-issues#756] opened 2023-04-13 01:17 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

There appears to be an issue with loading LottieFiles from a URL when setting them from a string value on FlutterFlow. LottieFiles JSON link, when directly copied and used as a URL, works. However, when the same link is stored in Firebase and retrieved as a string value to display as a Lottie animation using FlutterFlow, it does not work. Similarly, storing the JSON file in the database also does not resolve the issue.

### Expected Behavior

Expected Result:
The Lottie animation should be displayed correctly using the retrieved JSON link as a string value in FlutterFlow, whether it is directly copied or stored in a database.

Actual Result:
The Lottie animation does not display when using the retrieved JSON link as a string value in FlutterFlow, whether it is directly copied or stored in a database. The animation appears to be broken or does not load at all.

### Steps to Reproduce

Copy a LottieFiles JSON link (e.g. https://assets5.lottiefiles.com/private_files/lf30_vvnE1w.json).
Store the copied JSON link in Firebase or any other database.
Retrieve the JSON link as a string value in FlutterFlow.
Set the retrieved string value as the LottieFiles URL in FlutterFlow to display the animation.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code

Lottie animation

### Context

This issue can be reproduced consistently by following the steps mentioned above.

### Visual documentation

![image](https://user-images.githubusercontent.com/5320015/231620125-39d1707f-421e-48cd-b9d9-afc85c7cc56d.png)
I add a text field here for check, Firestore received the URL of animation
![image](https://user-images.githubusercontent.com/5320015/231620157-7f0091e3-31d9-4353-96ed-71566073f708.png)

Issue here:
![image](https://user-images.githubusercontent.com/5320015/231620325-bb4a2cea-0377-4db9-8249-5f99d3b6274c.png)

https://app.flutterflow.io/project/lottie-from-variable-tou01r

### Additional Info

This issue seems to be specific to FlutterFlow as using the same JSON link directly in other platforms or tools like LottieFiles Player or Lottie animations in native Flutter apps works correctly.
The issue persists even when storing the JSON file in the database and retrieving it as a string value.
This issue could potentially be related to how FlutterFlow handles URL loading or string parsing for LottieFiles animations.
This issue affects the ability to dynamically load LottieFiles animations from URLs stored as string values, which could impact the functionality and user experience of FlutterFlow apps that rely on Lottie animations.
It would be helpful to investigate and resolve this issue to ensure that LottieFiles animations can be seamlessly loaded from URLs stored as string values in FlutterFlow apps.

### Environment

```markdown
lutterFlow (latest version)
Flutter (latest version)
Firebase or any other database for storing the JSON link as a string value.
```

**Comment by wenkaifan0720** [comment] 2023-04-13 20:17
Hi @paulVu. Thanks for the detailed report! This seems to be duplicate of https://github.com/FlutterFlow/flutterflow-issues/issues/308, which should be fixed in our next update.

**Closed by wenkaifan0720** 2023-04-13 20:17 UTC
Labels: status: needs triage, closed: duplicate
