### ISSUE TITLE
Current Release does not allow duplicating pages or components that contain a stack component

### ISSUE THREAD

**Issue by greghawk** [FlutterFlow/flutterflow-issues#3728] opened 2024-09-02 13:07 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Upon the most recent release when you attempt to duplicate a page or component containing a stack component no error is shown when trying to duplicate a page and nothing happens.  When trying to duplicate components/widgets via copy paste an error is thrown that there is invalid clipboard data.

### Expected Behavior

Pages/Widgets/Components can be duplicated without error.

### Steps to Reproduce

Take a page with a stack in it
try to duplicate page

Take a page with a stack and copy any container containing a stack
Try to copy paste into other page

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

if (!_model.isFileUploaded)   Align(     alignment: AlignmentDirectional(0, 0),     child: InkWell(       splashColor: Colors.transparent,       focusColor: Colors.transparent,       hoverColor: Colors.transparent,       highlightColor: Colors.transparent,       onTap: () async {         // Get Avatar         final selectedMedia = await selectMedia(           multiImage: false,         );         if (selectedMedia != null &&             selectedMedia                 .every((m) => validateFileFormat(m.storagePath, context))) {           setState(() => _model.isDataUploading2 = true);           var selectedUploadedFiles = <FFUploadedFile>[];           try {             selectedUploadedFiles = selectedMedia                 .map((m) => FFUploadedFile(                       name: m.storagePath.split('/').last,                       bytes: m.bytes,                       height: m.dimensions?.height,                       width: m.dimensions?.width,                       blurHash: m.blurHash,                     ))                 .toList();           } finally {             _model.isDataUploading2 = false;           }           if (selectedUploadedFiles.length == selectedMedia.length) {             setState(() {               _model.uploadedLocalFile2 = selectedUploadedFiles.first;             });           } else {             setState(() {});             return;           }         }         FFAppState().avatarFile =             functions.imageToBase64(_model.uploadedLocalFile2)!;         setState(() {});         _model.isFileUploaded = true;         _model.avatarUploadFile = _model.uploadedLocalFile2;         setState(() {});       },       child: Container(         width: 150,         height: 150,         clipBehavior: Clip.antiAlias,         decoration: BoxDecoration(           shape: BoxShape.circle,         ),         child: Image.asset(           'assets/images/uiAvatar@2x.png',           fit: BoxFit.cover,         ),       ),     ).animateOnPageLoad(animationsMap['circleImageOnPageLoadAnimation']!),   )

### Visual documentation

https://github.com/user-attachments/assets/2e50d326-444b-45d8-a3c8-f7eccae5f542

### Environment

```markdown
- FlutterFlow version: 4.1.85
- Platform: Web
- Browser name and version: Chrome Version 128.0.6613.113
- Operating system and version affected: OSX Sonoma
```

### Additional Information

Ignore the copy shown in the video. I got it to duplicate once i removed the stacks. I can't duplicate needed pages.

**Comment by Alezanello** [comment] 2024-09-02 14:01
Hello!

I wasn’t able to replicate the issue in a new blank project. I was able to copy and paste everything into new pages or components without any problems, which suggests that this issue might be specific to your project. Since the GitHub Issue Tracker is primarily for bugs that can be replicated in a blank project, if the issue persists, please reach out to support via in-app chat or at [support@flutterflow.io](mailto:support@flutterflow.io). They can take a closer look at your project and help determine the cause.

Thank you!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/29bbd309-05e9-4a4b-8aa4-15304eff7287/9e45cff4-3f43-4eca-9004-ea2d8f14676a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yOWJiZDMwOS0wNWU5LTRhNGItOGFhNC0xNTMwNGVmZjcyODcvOWU0NWNmZjQtM2Y0My00ZWNhLTkwMDQtZWEyZDhmMTQ2NzZhIiwiaWF0IjoxNzI1Mjg1Njk5LCJleHAiOjMzMjk1ODQ1Njk5fQ.Nitdxth52TPS_ARncJ5k00hvX0UBTFc2uCiMn4bLFTY " alt="stackCopy.gif" width="1345" height="801" />

**Comment by greghawk** [comment] 2024-09-02 14:09
I may have isolated it to a specific text field inside the stack. It will not copy. On Sep 2, 2024, at 10:02 AM, Alezanello ***@***.***> wrote:﻿
Hello!
I wasn’t able to replicate the issue in a new blank project. I was able to copy and paste everything into new pages or components without any problems, which suggests that this issue might be specific to your project. Since the GitHub Issue Tracker is primarily for bugs that can be replicated in a blank project, if the issue persists, please reach out to support via in-app chat or at ***@***.*** They can take a closer look at your project and help determine the cause.
Thank you!

**Comment by XxWillyxX** [comment] 2024-09-02 22:10
I have the same issue
Even if it's not replicable something must be wrong if many people experience it.

**Comment by greghawk** [comment] 2024-09-03 13:51
Alright with further testing it is textInputField inside the stack that stops the duplication from working.  So with this setup:
```
Stack 
    >container
       >textInputField
    >Button
```

**Comment by Alezanello** [comment] 2024-09-18 22:08
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by greghawk** [comment] 2024-09-18 23:39
I can check. On Sep 18, 2024, at 6:09 PM, Alezanello ***@***.***> wrote:﻿
Hello,I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by Alezanello** [comment] 2024-09-30 14:30
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Closed as not planned by Alezanello** 2024-09-30 14:30 UTC
Labels: status: can't reproduce
