### ISSUE TITLE
Black screen on Android app launch

### ISSUE THREAD

**Issue by JDAR-BP** [FlutterFlow/flutterflow-issues#1425] opened 2023-09-08 12:18 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

My app has been validated on Google play store, here is the link: https://play.google.com/store/apps/details?id=fr.guitarpart.flutterflow

The problem is that when I install it and launch it, I get an empty black screen like that:
![image 1](https://github.com/FlutterFlow/flutterflow-issues/assets/144033954/490f919c-851b-4b0b-b939-f8ca0cbf320d)

After that, nothing happen, even after 5 minutes staying on it.
I tried to delete the app, re-upload with changes in my app but didnt worked at all.
I'e also tried to remove Stripe extension from FlutterFlow cause it seems that it could cause some issues like that, but didnt work either.
I've also tried to download the APK directly and launch it locally on my android device but Im still getting the dark screen.

I asked several people to try to download it from different android devices but they also get this black screen.

I precise that Apple store didnt validate my app yet but it works perfectly on test flight.

### Expected Behavior

I expect my app to launch normally and make it working for our android users.

### Steps to Reproduce

1. Download the app from an android device: https://play.google.com/store/apps/details?id=fr.guitarpart.flutterflow
2. Launch it once its downloaded
3. A black screen might appear and nothing more happen

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4skc/l5c91rsRE17r+YMdB/SgWQkx7aJEsscp/bxIgGIDzPOw+ZPWlZVVpZ8OqdFZcOkSmmT4Hw87xkfHTCO03GEmAfIhzwboJUwrybHGXQZOBEsy8REF7NNxMG0yky7WRgBJDIbFpSGQl72Ghfee/cBDfQ663ImdISq/LZO4=

### Context

I'm just trying to make my app working, I can't launch my app to our users as longer as this issue is not solved.

### Visual documentation

The black screen : 
![image 1](https://github.com/FlutterFlow/flutterflow-issues/assets/144033954/03d5f6ca-d5dc-47b5-852f-bbbec5f65257)

My android version : 
![photo_2023-08-22_16-34-52 1](https://github.com/FlutterFlow/flutterflow-issues/assets/144033954/dfb839bf-7316-4380-b450-a098e47f16a0)

### Environment

```markdown
- FlutterFlow version: v3.10.4 (released 7 sept. 2023)
- Platform: Android
- Browser name and version: V12 Android
- Operating system and version affected: dont know
```

**Comment by xNizzy** [comment] 2023-09-09 09:49
I have the exact same problem.

**Comment by JDAR-BP** [comment] 2023-09-11 10:16
> I have the exact same problem.

I hope the team will be able to help

**Comment by JDAR-BP** [comment] 2023-09-15 12:30
I asked a dev to run my app in emulator.
And he found this : https://ibb.co/L51TSHY (screen of the emulator)

We can see that issue is caused by RevenueCat.
And PWA works fine because RevenueCat is not supported on web.
So its 100% the issue comes from RVC.

I hope this can help the FlutterFlow team to resolve the issue.

Thank you!

**Comment by hariprasadms** [comment] 2023-09-22 10:21
Hello @JDAR-BP - Thanks for submitting the issue. Sorry for being late responding on the issue. Are you still facing the issue or its been resolved in latest FF updates? Please confirm. 

Considering the real device side issue, I would suggest reaching customer support team would be the best approach first. They can have a closer look and advise a best solution. If they confirm its an issue related code/ current feature, you can come here, we can investigate the issue. I hope this helps you. Thanks

**Comment by JDAR-BP** [comment] 2023-09-22 12:09
> Hello @JDAR-BP - Thanks for submitting the issue. Sorry for being late responding on the issue. Are you still facing the issue or its been resolved in latest FF updates? Please confirm.
> 
> Considering the real device side issue, I would suggest reaching customer support team would be the best approach first. They can have a closer look and advise a best solution. If they confirm its an issue related code/ current feature, you can come here, we can investigate the issue. I hope this helps you. Thanks


Hi Hari,

I've already talked to KriNo from the FlutterFlow customer support, we discussed a lot about it and he passed on the message to the tech team and I've got some feedbacks from them but nothing since 2 weeks, maybe they're busy.

I don't really know what to do, I'm not dev so I struggle with Android studio and emulator to get the error messages to debug by myself, I've been forced to ask a dev to do it for me on his free time...

**Comment by Abayjafton** [comment] 2023-09-24 16:57
I have the exact same problem.

**Comment by minashawky** [comment] 2023-09-26 17:13
I have the same issue in one app... Google Play actually removed the app from the store due to this issue... It's just stuck on the splash screen

**Comment by GleisonGranado** [comment] 2023-09-27 14:38
I'm facing the same problem, from what I discovered the bug really lies in the integration with Stripe and Revenue Cat, so much so that if you remove the integration and generate an APK it will run normally, the problem is that I need Stripe for my application works and they still haven't found a solution to this problem...

I hope they make it!

**Comment by minashawky** [comment] 2023-09-27 15:27
> I'm facing the same problem, from what I discovered the bug really lies in the integration with Stripe and Revenue Cat, so much so that if you remove the integration and generate an APK it will run normally, the problem is that I need Stripe for my application works and they still haven't found a solution to this problem...
> 
> I hope they make it!

I think so too. Possibly in the upgrade to those stripe editions:

flutter_stripe: 9.4.0
flutter_stripe_web: 4.4.0

i tried manually downgrading to a working flutter_stripe package but the code broke. I’ll play around till I make it work as my app has been off the Playstore for quiet some time now.

Also, if you want to replicate the issue on a virtual device use firebase’s *Test Lab* with a *Pixel 6a, API Level 32*

**Comment by JDAR-BP** [comment] 2023-09-28 20:00
Nice guys, let us know if you find something!

**Comment by MyTechAgent** [comment] 2023-09-30 00:29
Hey team,

experiencing the same issue too. Works on ios through connect but not stripe. I wonder if we have to be an google play beta mode. i know the same issue happened with apple until I enabled the correct identifiers and certificates.

**Comment by MyTechAgent** [comment] 2023-09-30 00:48
So I have worked out what the issue was for me. It seems it was the stripe payment system, this with braintree can cause issues for some reason. If you are using these addons try to disable and redownload the apk.

**Comment by katherineqian** [comment] 2023-09-30 17:00
Hi all, I'm sorry for the extremely late response here. I was not active on maintenance and I apologize for letting this sit for so long. To get up to speed, I was wondering if @JDAR-BP you could provide an update on whether the technical support team was able to confirm that the issue was not project-specific and indeed a bug. 

In addition, it sounds like Braintree, RevenueCat, and Stripe have all been reported as sources of these issues. We recently made a large set of bug fixes, and so it would be very helpful if you could confirm whether these issues continue to persist after the updates. For example, see https://github.com/FlutterFlow/flutterflow-issues/issues/1075 where the Stripe packages were updated.

**Comment by JDAR-BP** [comment] 2023-10-01 13:11
> Hi all, I'm sorry for the extremely late response here. I was not active on maintenance and I apologize for letting this sit for so long. To get up to speed, I was wondering if @JDAR-BP you could provide an update on whether the technical support team was able to confirm that the issue was not project-specific and indeed a bug.
> 
> In addition, it sounds like Braintree, RevenueCat, and Stripe have all been reported as sources of these issues. We recently made a large set of bug fixes, and so it would be very helpful if you could confirm whether these issues continue to persist after the updates. For example, see #1075 where the Stripe packages were updated. I will also remove the closed labels in the meantime while we see if these are configuration-specific problems.

Hi @katherineqian, thanks for reaching us out!

About the "not project-specific issue", I can't be sure since I didnt ask clearly this way, but based on other feedbacks, it seems that there is a certain amount of FlutterFlow apps that got this issue.
And since it works fine without any RevenueCat and Stripe extension (based on @GleisonGranado feedback), its probably not just a project-specific issue.

By the way, the RevenueCat support said : "the error message says that its basically a bad communication between the app and Google Play Console, the device attempts to fetch products from Google and is failing."

**Comment by minashawky** [comment] 2023-10-01 14:18
Not sure of this will help but when I run a Test Lab using a Pixel 6a it shows the issue... All screenshots are blank
<img width="1120" alt="Screenshot 2023-10-01 at 6 15 46 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/6050173/59b5e982-a930-4dff-9551-4ecc226e19d2">

**Comment by MyTechAgent** [comment] 2023-10-02 05:05
> Not sure of this will help but when I run a Test Lab using a Pixel 6a it shows the issue... All screenshots are blank
> 
> <img width="1120" alt="Screenshot 2023-10-01 at 6 15 46 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/6050173/59b5e982-a930-4dff-9551-4ecc226e19d2">
> 
> 

Yep that's what happens on my end too. Making UAT painful as I deploy to apple connect and than have to save it remove stripe export apk than revert back to my backup lol

**Comment by JDAR-BP** [comment] 2023-10-02 06:34
> Not sure of this will help but when I run a Test Lab using a Pixel 6a it shows the issue... All screenshots are blank <img alt="Screenshot 2023-10-01 at 6 15 46 PM" width="1120" src="https://user-images.githubusercontent.com/6050173/271834002-59b5e982-a930-4dff-9551-4ecc226e19d2.png">

@minashawky Hey man, I've made some test myself and it seems that it shows the issue on theses devices too:
- Galaxy Z Fold3, API Level 31
- Galaxy A51, API Level 31
- Pixel 7 Pro, API Level 33

I didn't test all devices, only 9 and 4/9 shows the issue.

**Comment by Abayjafton** [comment] 2023-10-02 08:53
Guys
Remove background color and preloading color completely in splash screen in settings
Transparent or unset them
The application now starts up properly and stripe works.
That worked for me.

**Comment by JDAR-BP** [comment] 2023-10-02 16:28
> Guys Remove background color and preloading color completely in splash screen in settings Transparent or unset them The application now starts up properly and stripe works. That worked for me.

@Abayjafton Bro you right!! I've deleted splash screen set up and it works perfectly for me too!
Thank you so much for finding this man I'm struggling with that shit for a while now.

@xNizzy @minashawky @MyTechAgent @GleisonGranado 
Guys I hope it will works for you too ;)

**Comment by GleisonGranado** [comment] 2023-10-02 16:47
@Abayjafton It worked for me too! Thank you very much man, I've been suffering with this for a couple of weeks now.

I hope it works out for everyone!

Thanks guys :) Thanks @JDAR-BP for all!

**Comment by mattholdsme** [comment] 2023-10-03 05:02
> Guys Remove background color and preloading color completely in splash screen in settings Transparent or unset them The application now starts up properly and stripe works. That worked for me.

You are amazing thank you sir this fixed the issue. Now I can scrape some lost time back.

**Comment by minashawky** [comment] 2023-10-03 06:58
@JDAR-BP I wouldn't close the ticket yet as its an issue I believe that needs investigation and fixing. Why would pre-loading and splash screen background color impact having an app on android if its using Stripe or Braintree?

**Comment by xNizzy** [comment] 2023-10-03 07:19
> > Guys Remove background color and preloading color completely in splash screen in settings Transparent or unset them The application now starts up properly and stripe works. That worked for me.
> 
> 
> 
> @Abayjafton Bro you right!! I've deleted splash screen set up and it works perfectly for me too!
> 
> Thank you so much for finding this man I'm struggling with that shit for a while now.
> 
> 
> 
> @xNizzy @minashawky @MyTechAgent @GleisonGranado 
> 
> Guys I hope it will works for you too ;)

Thanks, I'll try this!

**Comment by JDAR-BP** [comment] 2023-10-03 08:22
> @JDAR-BP I wouldn't close the ticket yet as its an issue I believe that needs investigation and fixing. Why would pre-loading and splash screen background color impact having an app on android if its using Stripe or Braintree?

@minashawky Yes you're right man, I've reopened it ;)

**Comment by minashawky** [comment] 2023-10-03 09:06
Dunno if this will help, but when we removed the splash screen and pre-loading color the following pub packages were removed. Maybe one of them is conflicting with stripe 🤔 

<img width="1032" alt="Screenshot 2023-10-03 at 1 05 08 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/6050173/20003d3c-2ac1-4a74-a72f-1641fe288c3c">

Hope this helps the devs 🤞

**Closed** 2023-10-13 17:34 UTC
Labels: type: bug, status: confirmed

**Comment by iGrits** [comment] 2023-10-19 03:55
@sbis04 was this closed because it was resolved?  I am still having this issue..

**Comment by sbis04** [comment] 2023-10-19 03:58
Yes, but the update hasn't been released yet -- this issue should be fixed in the next update! (which would be sometime this week)
