### ISSUE TITLE
Project won't build/code won't download if an API call parameter is empty

### ISSUE THREAD

**Issue by aemelyanovff** [FlutterFlow/flutterflow-issues#27] opened 2022-10-07 15:14 UTC
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

If an API call parameter is left empty, FlutterFlow either should not let the user save it, or should use default values when generating  code.

## Current behavior (required)

Projects won't build and code won't download if API call parameters *with certain types* are left empty.

## To Reproduce (required)
1. Create new API call
2. Set Method Type = POST
3. Go to "Body"
4. Choose `x-www-form-urlencoded`.
5. Add new parameter. Value source: Specific Value, Type = Integer. Leave the value empty.
6. Save.
7. Trying downloading project code. Observe that it fails.

## Context (required)

I accidentally left a parameter empty, but then code download stopped working, even though there are no project errors.

## Screenshots / recordings

![Screen Shot 2022-10-07 at 11 13 39 AM](https://user-images.githubusercontent.com/92294640/194587698-8120705d-e393-4372-90fc-066f93a79d92.png)

## Your environment

* **Bug Report Code:**
* Version of FlutterFlow used: v3.0 October 5, 2022
* Platform (e.g. Web, MacOS Desktop):  Web
* Browser name and version: Chrome, 105.0.5195.125 (Official Build) (x86_64)
* Operating system and version (desktop or mobile): MacOs 12.5.1 (Monterey)

**Comment by hariprasadms** [comment] 2022-10-07 15:52
I just tested it. When api parameters are empty, project still can build and download with no issues. I think there could be errors at different part of the app. Can you please have a look at custom code and all pages for error. compile all your custom code items and see they can compile successfully with no errors.

**Comment by bulgariamitko** [comment] 2022-10-07 17:56
I was not able to reproduce this as well. Do you get any errors in the project? Do you have any custom code?

**Comment by organicnz** [comment] 2022-10-07 18:12
Couldn't push changes to the repository with the new API call as in the example :)

<img width="1440" alt="Screen Shot 2022-10-07 at 9 10 26 PM" src="https://user-images.githubusercontent.com/4765090/194622768-2ecaed6d-d380-43a2-9e23-24102557324d.png">
<img width="1440" alt="Screen Shot 2022-10-07 at 9 10 51 PM" src="https://user-images.githubusercontent.com/4765090/194622777-07c41433-8480-4343-9146-949152f9848b.png">

**Comment by organicnz** [comment] 2022-10-07 18:30
Removed the myCall API call and was able to push the changes :)

<img width="1438" alt="Screen Shot 2022-10-07 at 9 26 15 PM" src="https://user-images.githubusercontent.com/4765090/194625211-269c175b-1832-479d-88f0-0e15c47b3204.png">
<img width="1440" alt="Screen Shot 2022-10-07 at 9 26 27 PM" src="https://user-images.githubusercontent.com/4765090/194625205-eed460e9-8e6b-4b01-99d7-20e1edf47269.png">

**Comment by shelpert** [comment] 2022-10-25 17:28
This bug has been fixed and will be released in the next deploy!

**Closed by shelpert** 2022-10-25 17:28 UTC
Labels: type: bug, status: confirmed, priority: low
