### ISSUE TITLE
Action parameters disappear

### ISSUE THREAD

**Issue by ryutosh** [FlutterFlow/flutterflow-issues#3777] opened 2024-09-08 06:08 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

While entering parameters in the action editor, the already entered parameters disappear. Due to this problem, the action cannot be built.

https://github.com/user-attachments/assets/ba214629-4955-4425-a103-2c56a0714a8b

### Expected Behavior

Already entered parameters still present.

### Steps to Reproduce

1. Create action
2. Input some parameters

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEehfKB35ZJpbwG1c7qcsJWiQMwGkQ5a7sviu5+FBQaI+KvEZoieOOkUBRCYuqHY25mBGL+mmMBwaGLhtntN/UoOSScfNVayah9UxDiRXGlVqrUCpDtQXB7J8ZVGnaOy5iVqx1NANBpc2Qi2k6MHu+Qb3qCf9qOYwx5e6fDbOY=

### Visual documentation

attached in "Current Behavior"

### Environment

```markdown
- FlutterFlow version: 4.1.88
- Platform: Mac Desktop
- Browser name and version: Chrome
- Operating system and version affected: Mac Sonoma
```

**Comment by rzambroni** [comment] 2024-09-08 23:27
Hi @ryutosh,

Thanks for the report! I wasn’t able to replicate the issue you're describing. Everything seems to be working fine on my end — I tested both the web and macOS apps and noticed that the parameters in your project now appear to be configured correctly.

Are you still experiencing the issue? If so, would you mind creating a quick test in a blank project to see if the problem is replicable there as well?

Thanks again!

**Comment by ryutosh** [comment] 2024-09-09 07:29
Hi, @rzambroni 
> and noticed that the parameters in your project now appear to be configured correctly.

Yes. The input was lost, so I copied it from another action and changed it. It did not disappear.

I am trying it today with a newly created action and so far it does not seem to disappear. I will try to contact you here if I reproduce it again. Thank you for your confirmation.

**Comment by rzambroni** [comment] 2024-09-09 12:53
Sounds good, closing the issue for now, feel free to reopen it if you encounter the issue again.

Thanks.

**Closed as not planned by rzambroni** 2024-09-09 12:53 UTC
Labels: status: can't reproduce
