### ISSUE TITLE
Audio player doesn't work on iPhone on web

### ISSUE THREAD

**Issue by aemelyanovff** [FlutterFlow/flutterflow-issues#87] opened 2022-11-02 15:29 UTC
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

Audio player works on all platforms.

## Current behavior (required)

Audio player works on Desktop browsers, but not on iPhone (Safari, Chrome).

## To Reproduce (required)

1. Create new page
2. Add audio player. You can keep the default settings.
3. Publish to web.
4. Open on Desktop - observe that it shows and works.
5. Open on iPhone (I tried Safari or Chrome) - observe that the audio player doesn't show.

Link: https://audio-bug2-yy8tzn.flutterflow.app/ (project: https://app.flutterflow.io/project/audio-bug2-yy8tzn)

## Context (required)

Can't use audio player on web.

## Screenshots / recordings

N/A

## Your environment

* **Bug Report Code:**
* Version of FlutterFlow used: FlutterFlow v3.0, released October 28, 2022
* Platform (e.g. Web, MacOS Desktop):  Web
* Browser name and version: Chrome, Version 107.0.5304.87 (Official Build) (x86_64)
* Operating system and version (desktop or mobile): MacOS 12.5.1 Monterey.

**Comment by organicnz** [comment] 2022-11-12 10:57
Trying to add the audio player widget buy it no longer appears on several pages in my music app. For some reason I can only see the custom audio widget hehe 

https://hybridized.flutterflow.app/player-page-full

<img width="1434" alt="Screen Shot 2022-11-12 at 13 19 45" src="https://user-images.githubusercontent.com/4765090/201469667-cbacba1a-b067-44a2-b451-7d124a987df0.png">

**Comment by organicnz** [comment] 2022-11-12 11:24
It appeared back for a while and I was able to play the music then disappeared again on the Webapp in Chrome lmao
The opposite behaviour in the Chrome mobile browser the custom audio player works fine :)

![telegram-cloud-photo-size-2-5440542289568055421-y](https://user-images.githubusercontent.com/4765090/201471711-3ef35b09-73ba-4e04-a682-e5385862faff.jpg)

**Comment by vishalagarwal2** [comment] 2023-08-03 14:29
I tried the audio player on various devices - Chrome, Chrome mobile emulator, iOS, android, and havent been able to reproduce the error. Can I assume this is fixed or are people still facing this issue?

**Comment by aemelyanovff** [comment] 2023-08-04 18:05
@vishalagarwal2 I'm still facing this issue. Here's a new link: https://audio-bug2-1xy452.flutterflow.app/ (project - https://app.flutterflow.io/project/audio-bug2-1xy452. There's nothing in this project except the audio player).

It loads fine on my desktop and on my Android phone, but fails to load on iOS/Safari.

iPhone:
<img width="375" alt="AudioBug2" src="https://github.com/FlutterFlow/flutterflow-issues/assets/92294640/133ac00a-be68-4dac-9a94-d63bfb2310b1">

iPad:
<img width="810" alt="AudioBug2 2" src="https://github.com/FlutterFlow/flutterflow-issues/assets/92294640/c4d862cd-9f13-4524-a902-0663a56dd959">

**Comment by vishalagarwal2** [comment] 2023-08-04 20:03
<img width="409" alt="Screenshot 2023-08-04 at 4 02 56 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/63578295/1adc20e1-1945-4f81-b214-e5b30f345119">
again, it seems fine on iPhone -- iOS for me. Safari seems to be an issue tho!

**Comment by aemelyanovff** [comment] 2023-08-04 20:14
Are you running it natively on iOS? That works. Try opening the web-published links in a browser on iOS.

**Comment by vishalagarwal2** [comment] 2023-08-04 20:20
ahh gotchu! It seems to be an issue with the package itself - https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/540

Not sure how much we can do about it!

**Comment by takashiff** [comment] 2023-12-20 21:51
@fredchung I believe this is an issue with the built-in widget

**Comment by timfong888** [comment] 2024-01-12 01:14
I have the same issues, according to @vishalagarwal2 this is due to the package itself?

**Comment by Maazkhalid47** [comment] 2024-02-15 14:24
Works on the published web app and on android, doesnt work on test or run mode since these dont have microphone access but doesn't work on ios either, the audio does get recorded but doesnt get played

**Comment by ramyzeidan** [comment] 2024-03-01 23:21
anyone got any updates on this?? i even used the just_audio player from flutterflow market and it's also not working on ios ... any ideas how to fix it?

**Comment by 0xJovin** [comment] 2024-03-02 22:56
Hey FF team, any update on this? If any app uses audio as the main feature like meditation etc, this would break the experience for iOS users

**Comment by ramyzeidan** [comment] 2024-03-02 23:24
after some digging turns out for some reason ios doesn't support playing m4a audio ...

**Comment by rzambroni** [comment] 2024-04-18 19:51
Hi everyone! sorry about this report being so silent on our end, as some users already mentioned above this is a bug with the package used under the hood on flutter flow for the audio-player. 

Unfortunately, it seems that this bug will not be fixed any time soon on the package side, so we have plans to replace this feature with a better and more flexible player.

I'm closing down this thicket as this request was added to our internal backlog as a feature request and we will be tracking it there.

Thanks so much!

**Closed** 2024-04-18 20:25 UTC
Labels: priority: low, type: feature / enhancement request
