### ISSUE TITLE
Walkthrough doesn't let focusing on widgets within components (re-open #3875)

### ISSUE THREAD

**Issue by giladresisi** [FlutterFlow/flutterflow-issues#3972] opened 2024-10-03 15:55 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

See the description of #3875, what I meant to do is select a widget that RESIDES WITHIN A COMPONENT, not selecting the component itself like you guys proposed there

### Expected Behavior

I'd expect to be able to select a widget even if it resides within a component and not directly within the page

### Steps to Reproduce

See the steps described in #3875

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KzPLl8Y1IseVJ1s7ud8JB/SAWQkR+U40wlsJ9SQEbfbaoG7YMS8+kMxJVXemndGNEL2eGhn4z0+zOkuDMA+UoCxabG6pl+ZdcUQ//RmKmRrnRCpaOXH9RN5tJJVya56WJgyVCWbFZW0Is11OuA/C8cHXDGZDaDTA/J/+JLp3MnGOqQ0SLb3kNh1JWeC/v

### Visual documentation

![369738008-c76091ec-0be0-468c-b03b-4489da5cfcf0](https://github.com/user-attachments/assets/d1d289e8-7bc0-47b0-b944-d844b8aa0942)
I'd expect to be able to focus on e.g. the "List Item" header but it only allows me to focus on the MaterialListItem1 component this header resides in.

### Environment

```markdown
- FlutterFlow version: v5.0.2+
- Platform: Web
- Browser name and version: Chrome 129.0.6668.60
- Operating system and version affected: Windows 11 Pro
```

**Comment by Alezanello** [comment] 2024-10-03 18:12
Hello!<br><br>Same I sent in the other issue:<br><br>You can select the component directly from the Walkthrough menu, and if needed, you can even create a new one!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/088cf1e6-a987-4c5b-b057-09cfa2482e1e/cc94e6a6-855b-4bf2-ba4d-7294c95ddb31?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wODhjZjFlNi1hOTg3LTRjNWItYjA1Ny0wOWNmYTI0ODJlMWUvY2M5NGU2YTYtODU1Yi00YmYyLWJhNGQtNzI5NGM5NWRkYjMxIiwiaWF0IjoxNzI3OTc5MTU3LCJleHAiOjMzMjk4NTM5MTU3fQ.3qRybDKyUTKb7uEpuP-K7hl1dSZu1IiZtUbClAmrYmo " alt="chooseComponent.gif" width="1830" height="924" />

**Comment by giladresisi** [comment] 2024-10-03 18:26
So again you didn't understand my question:
I've added the MaterialListItem1 component to the page but the widget I was trying to select is specifically the "List Item" text inside it, NOT THE WHOLE COMPONENT! (as you're suggesting me to do)

**Comment by giladresisi** [comment] 2024-10-11 06:32
> So again you didn't understand my question: I've added the MaterialListItem1 component to the page but the widget I was trying to select is specifically the "List Item" text inside it, NOT THE WHOLE COMPONENT! (as you're suggesting me to do)

@Alezanello see my reply here, I wanted to select a widget which resides WITHIN a component that is inside the selected page, but as of now it only allows me to select the ENTIRE component and not a single widget inside it

**Comment by giladresisi** [comment] 2024-10-21 13:47
@Alezanello please answer regarding this issue, don't let it close again. I currently need to do very ugly stuff in my project to (partially) workaround that issue, I need that solved. Thanks

**Comment by rzambroni** [comment] 2024-11-13 15:30
Hi @giladresisi,

Apologies for the delay in getting back to you, and thank you for providing additional context. It appears that this is a limitation of the walkthrough feature. I'll check with the team to determine whether this should be classified as a bug or if we should consider it as an enhancement request moving forward.

Thank you for your patience, and I’ll keep you updated!

**Comment by rzambroni** [comment] 2024-11-13 16:44
I reached out internally and confirmed with the team that this is a known enhancement request, and it's already on the engineering backlog. Hopefully, they'll be able to prioritize it soon!

I'll go ahead and close the issue, as it's being tracked internally.

Thank you for bringing this to our attention!

**Closed as not planned** 2024-11-13 16:45 UTC
Labels: status: confirmed, Bug

**Comment by prajitlal4** [comment] 2025-02-27 13:01
I am facing the same issue here now where I am unable to create a walkthrough on a widget inside of a component. Please look at this screenshot attached: 

![Image](https://github.com/user-attachments/assets/beb61fde-4bbf-4ca0-99cd-aa1b9c5cdb88)

As you can see, I want to select the actual text inside of ScrollingComponent, however it instead selects the entire ScrollingComponent. 

I also want to be able to select the Like button and the Share button to do a walkthrough on that, but am unable to, and as far as I can see there is no workaround other than having to delete the ScrollingComponent and put those widgets in manually. I don't see how we aren't able to do this by default?

**Comment by MatthewFFerry** [comment] 2026-03-04 10:42
Hey, is there any update on this issue? I'm running into the same problem. Over a year ago, it was mentioned that this is in the engineering backlog — is there any update on when this feature request might be implemented? This would be a very useful feature for app creators. Currently, the functionality feels limited because of its absence.
