### ISSUE TITLE
assign collaborator to a single environment access only

### ISSUE THREAD

**Issue by TDKP** [FlutterFlow/flutterflow-issues#4857] opened 2024-11-09 20:23 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I can only give access to a collaborator the entire app

### Expected Behavior

I want to give a collaborator the dev environment only

### Steps to Reproduce

-Create a new FF app
-Add a collaborator to FF application.
- I can't assign the access of a collaborator for dev environment only.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfz8jc34VItbwC+a6JKMJF/WEQOUMcTYMvjuphcx43JYzkEOx3P8nCV0NKTemnYAs/OE20kmIB/8qOk/OWKccpPSirbb5b0JVAbjrdTjm6WpjRC6rhZn9AONxjCGqP5sOFmRVTANdtZXw81Ey1N63qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

<img width="1606" alt="Screen Shot 2024-11-09 at 12 22 00" src="https://github.com/user-attachments/assets/e532792b-c671-40b4-8f47-9997f330af47">
<img width="1480" alt="Screen Shot 2024-11-09 at 12 21 36" src="https://github.com/user-attachments/assets/416c7398-1c9d-4064-81e7-64a973afd5e6">

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform:Mobile
- Browser name and version: Chrome 107.0.5304.110
- Operating system and version affected: Big Sur 11.5.2
```

**Comment by Alezanello** [comment] 2024-11-11 12:33
Thank you for your feedback!

This GitHub Issue Tracker is intended specifically for reproducible bugs. It seems that your submission is a feature request. I’ll create an internal ticket so the team can add it to their backlog for consideration.

In the meantime, I’ll be closing this issue here to keep the tracker focused on reproducible bugs.

Thank you for your understanding!

**Closed as not planned** 2024-11-11 12:33 UTC
Labels: closed: feature / enhancement request
