### ISSUE TITLE
Feature Request: Add Border Color Customization on Hover for Button Widget

### ISSUE THREAD

**Issue by SauloSA** [FlutterFlow/flutterflow-issues#3157] opened 2024-06-17 14:39 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The Button widget in FlutterFlow includes various extra configurations to customize the hover state within the same widget. However, it lacks the option to customize the border color specifically when the button is hovered over. This limits the ability to fully customize the button's appearance in different states.
Add an option to customize the border color of the Button widget specifically for the hover state. This would allow users to have greater control over the button's appearance and improve the overall user interface design.

### Expected Behavior

When configuring the Button widget, users should have the ability to set a different border color that applies only when the button is hovered over. This would work similarly to other hover customization options already available in the widget.

### Steps to Reproduce

Not applicable

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Not applicable

### Visual documentation

Not applicable

### Environment

```markdown
Not applicable
```

**Comment by msusviela** [comment] 2024-06-18 15:55
Hey @SauloSA, This tracker is only used for reproducible bugs, so I am closing this issue. I've added this as a feature request in our internal backlog and we will get to it as soon as possible. Thanks for your feedback!

**Comment by msusviela** [comment] 2024-06-26 11:37
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Closed as not planned** 2024-07-02 20:06 UTC
Labels: closed: feature / enhancement request
