### ISSUE TITLE
Bug - Youtube Video Widget Layers Over Other Objects

### ISSUE THREAD

**Issue by PCDDev** [FlutterFlow/flutterflow-issues#1537] opened 2023-09-27 03:33 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

This [Login Page](https://app.flutterflow.io/project/incarts-dev-klpn58?tab=widgetTree&page=pgLogIn) has a FlutterFlow YoutubePlayer widget. When I click "Log In" and the email hasn't yet been verified, a modal pops up asking the user to verify. When that pop-up happens, if the pop-up box overlays with the YouTube video, I can't click the button on the popup (popupResendEmailVerification) or the close button on that popup. I have tested this with both a template modal and one I created from scratch and validated this appears to be an issue with the YouTubePlayer widget. 

I am testing this on a larger screen size designed for desktop.

As a workaround, I made the modal show up to the left of the video so I can interact with it. However, the informational notification that pops up after successfully requesting a new verification email cannot be closed because it overlaps with the YouTube widget.

While I can work around this issue in my project, it's not ideal, and appears to be a bug that should be fixed in FlutterFlow. Let me know if I'm missing something.

For help with troubleshooting, I've created a test account "[swimminguy121@yahoo.com](mailto:swimminguy121@yahoo.com)" and PW "Tester22$" which can be used on the login page to recreate the issue. I also set it up to use the modal which results in the error, "popupResendEmailVerificationERR". Try logging in with that account and interacting with the popup window.

### Expected Behavior

I'd expect any object visibly layered on top of the YouTube widget to receive any user interaction (button press, close window, etc.) first and not impact the YouTube widget behind the pop-up modal or message.  

### Steps to Reproduce

1. Create a new page with a YouTube widget on it
2. Create a pop-up modal or notification that is oriented to show up on top of the YouTube widget when the pop-up is activated
3. Set screen size to 1440x900
4. Try interacting with the pop-up widget, clicking a button or closing the pop-up
5. Notify FlutterFlow support about the issue
6. Oh, no! Step 5 gets us stuck in a loop! 
7. Break the loop and fix the YouTube widget. :) 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sj8nfx5dPmN9K+Krqdcdr/SIXOUg6R4Eascp/bxIgGIDzPOw+ZPXsZRdWUummd1FcekSmmloz7smLjt/xK+0qMkyrRbY7wsxtWj3/cGORUZOBDLqWOX99M+xRCWqM08GnoQpvBPRfSkYb7U62ee6ybz7bNLLGIndISq/LZO4=

### Context

I'm trying to use a pop up on a page and have the user interact with the pop-up. 

This issue prevents that from happening on pages that have a YouTube widget. The issue is not a dealbreaker for my use of FlutterFlow, but frustrating, and seems like a common enough use case that it should work and the bug should be fixed. I'm able to create a workaround (place pop-up to the side of the YouTube player), but that's not ideal. 

Somewhere around medium-low impact in the grand scheme of what you guys probably deal with. 

### Visual documentation

[Loom Video here](https://www.loom.com/share/ec233fbdb3204851bd68fd748eebb9f9?sid=b12d4c11-5603-49eb-85e7-3dcf319aa7f8) 

### Additional Info

None

### Environment

```markdown
- FlutterFlow version: v3.10.4
- Platform: Windows OS Desktop App
- Browser name and version: Chrome 116.0.5845.188 (Official Build) (64-bit)
- Operating system and version affected: Windows 10 Pro 64-bit version 22H2
```

**Comment by SameerShahzad99** [comment] 2023-09-28 19:52
@PCDDev It looks like the bug report code you shared does not belong to a blank project with the issue reproduced, can you share the correct bug report code?

**Comment by PCDDev** [comment] 2023-09-28 22:05
Hi, I shared the project where the issue is happening. I I’m not going to
rebuild one to show it. It’s pretty straightforward - Put a YT widget on a
blank screen, trigger a pop up over the widget, you won’t be able to click
any buttons on the pop up if they are on top of YT.

Feel free to try it out on the active project I linked for you or create a
blank one yourself.

Patrick

**Comment by SameerShahzad99** [comment] 2023-10-30 20:33
@PCDDev Apologies for the delayed response, i was able to reproduce this issue on my end!

**Comment by aemelyanovff** [comment] 2023-11-03 19:14
@PCDDev Thank you for reporting the issue. It was fixed in the last update.

**Closed by aemelyanovff** 2023-11-03 19:14 UTC
Labels: type: bug, status: confirmed

**Comment by aemelyanovff** [comment] 2023-11-03 19:15
Also I think it's a duplicate of https://github.com/FlutterFlow/flutterflow-issues/issues/1424
