### ISSUE TITLE
Staggeredview blocks scroll on page

### ISSUE THREAD

**Issue by sirian-m** [FlutterFlow/flutterflow-issues#418] opened 2023-01-30 00:16 UTC
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

Adding a stageredview inside a column with other content allows user to scroll through all content fluidly.

## Current behavior (required)

Once the user gets to the stageredview it behaves as a primary scroll widget, resulting in not being able to scroll back to the top of the page while touching the stageredview.

## To Reproduce (required)

1. Create new page
2. Add a column with scrolling enabled and set to primary
3. Add some content (containers, texts, whatever you want)
4. Add a stageredview with some content and set it to shrinkwrap.
5. Run the project and try to scroll the column by touch, sliding on the stageredview.

### Bug Report Code (required, generate from Widget Tree)

`return MasonryGridView.count(
          crossAxisCount: 2,
          crossAxisSpacing: 12,
          mainAxisSpacing: 12,
          itemCount: products.length,
          shrinkWrap: true,
          itemBuilder: (context, productsIndex) {
            final productsItem = products[productsIndex];
            return`

## Context (required)

I want a stageredview for products on my homepage, but this issue blocks me from scrolling through it.

## Your environment

* Version of FlutterFlow used: 3.0
* Platform (e.g. Web, MacOS Desktop): iOS simulator and Android phone
* Browser name and version: Chrome
* Operating system and version (desktop or mobile): iOS 16.2 and Android 13

## Suggestion
Add option to set the primary bool of the stageredview widget (just like on a column). When this is set to false on the stageredview (MasonryGridView) it solves the issue, tested this already.

**Comment by hariprasadms** [comment] 2023-01-30 17:35
Hi @sirian-m - Thanks for the issue details. 

I am not able to re-produce the issue. In your steps, the second point says add column and set to primary. but **'primary'** option can set to ListView widget not Column widget. However, I have added column widget with default properties and other widgets as per steps. Scrolling in stageredview works fine for me with no issues. 
Also, step 5 is bit confusing when you say "scroll the column by touch, sliding on the stageredview". 

Can you please share widget tree image and also a quick video of the issue. Once you added these details we can revisit to the issue. Thanks

**Comment by sirian-m** [comment] 2023-01-30 22:36
Hmm for me there is the primary scroll option on a column. By the touch thing I meant testing it on device/simulator and not scrolling using your mouse wheel. So the issue is that I don't want to scroll through the staggered view independently, I want to scroll through the complete page.

See screen recording of issue here:
https://user-images.githubusercontent.com/109159237/215611712-2c69d197-9b41-4625-be08-620f5f89aabb.mp4


Here is my widget stack:
![image](https://user-images.githubusercontent.com/109159237/215606366-20061873-7f93-4af2-be32-142e7d2f4c13.png)

The scrolling column settings:
![image](https://user-images.githubusercontent.com/109159237/215606476-dab6cccb-8dfd-4147-bc58-ac055a379474.png)

The stageredview settings:
![image](https://user-images.githubusercontent.com/109159237/215606824-512df07a-73e6-42b4-878f-0b8942e3b890.png)

**Comment by hariprasadms** [comment] 2023-02-01 12:47
Hi @sirian-m - Thanks for sharing the details. 

Looking at the widget tree, I think because of nested column widgets along with staggered view widgets, the property of the widgets are overlapping scrolling behaviour. 

I suggest, try to reduce column and staggered widgets and try with List-view or Grid-view widgets. I know this is theoretically suggestion but with no access to actual app / widget tree, it is difficult to debug the actual issue. Also I suggest download the code and run in visual code locally and see what error you can get while scrolling is stuck.

I am sure this is mostly related to design issue. Playing a little bit around design and widgets can solve the issue.  Let me know how it goes. Thanks

**Comment by sirian-m** [comment] 2023-02-01 12:57
Hi @hariprasadms,

Thanks for your reply. They are indeed overlapping with their current scrolling behaviour, I checked in VS Code and the parameter that's causing the issue on the staggeredview is that the "primary" boolean is not included. This means it defaults to true, causing the 2 scrolling widgets to overlap in priority meaning the parent column will not scroll when scrolling from within the staggeredview. When I manually added this to the staggered view (MasonryGridView.count) code `primary: false`, the issue was fixed. 

I don't want to replace the staggeredview with a listview in my app because the listview is only single column, and the gridview is is a single aspect ratio and the cards in the design need to be able to grow and shrink in height dynamically (not shown yet in the screen recording but that's due to it being test data).


![image](https://user-images.githubusercontent.com/109159237/216049115-2e6cf204-5eb6-4609-bc0b-29e2d54b8113.png)
So if the `primary` parameter like above would be added to the widget options of the staggered view in FF (which the column, row or listview widgets for example do have), this issue would be fixed.

**Comment by hariprasadms** [comment] 2023-02-01 17:29
@sirian-m  - It make sense for me as well. As it is not a bug with current features. we can mark this as a feature request. I will check this with Dev team for next steps. Thanks

**Comment by sirian-m** [comment] 2023-02-01 19:07
@hariprasadms Thanks! Sounds good!

**Comment by katherineqian** [comment] 2023-02-11 22:28
Hi @sirian-m,

This bug should be addressed by a recent update, as it appears to be a duplicate of https://github.com/FlutterFlow/flutterflow-issues/issues/326. I'm going to close this for now. Thank you for you contribution!

**Closed by katherineqian** 2023-02-11 22:28 UTC
Labels: type: feature request, closed: duplicate
