### ISSUE TITLE
follow up on cached image lag

### ISSUE THREAD

**Issue by aaronmt93** [FlutterFlow/flutterflow-issues#2207] opened 2024-01-20 22:05 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

relinking a bug that was marked as done but is still open. I have this issue every time I make a page view with dynamically generated items from a field. it has to be tested on a real phone, not on simulator. 

### Expected Behavior

[see link](https://github.com/FlutterFlow/flutterflow-issues/issues/1707#issuecomment-1785645666)

### Steps to Reproduce

please reopen other bug. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

na

### Context

na

### Visual documentation

na

### Additional Info

na

### Environment

```markdown
- FlutterFlow version: na
- Platform:na
- Browser name and version:na
- Operating system and version affected: na
```

**Comment by hariprasadms** [comment] 2024-01-23 18:18
Hi @aaronmt93 - During the issue resolution process, testing was conducted on both the simulator and a real device using the provided images. The issue could not be reproduced, and it was observed that the it worked correctly. Since there were no further follow-ups or reports on the issue, it was deemed resolved and subsequently closed. 
If you believe that the issue persists on your end, I recommend setting up a new blank project with the images configuration and providing the bug report code. With these specific details, it will be much easier to analyse and pinpoint the problem. This approach will assist in gaining a deeper understanding of the issue and facilitating a more effective resolution.

**Comment by aaronmt93** [comment] 2024-01-23 19:32
@hariprasadms i just ended up building my own pageview widget with gpt that preloads the images and it works fine now. so its either a feature gap or a bug on the current pageview widget if the team ever wants to look into it.

**Comment by hariprasadms** [comment] 2024-01-23 19:45
Thanks @aaronmt93 - That sounds positive. Thank you for the update. Since the issue cannot be reproduced, we will close it for now. If the problem persists in the future, feel free to reach out with a new issue, providing all the necessary details. Thanks!

**Closed** 2024-01-24 12:38 UTC
Labels: closed: not a bug
