### ISSUE TITLE
Revenue Cat purchases not working - loosing purchases

### ISSUE THREAD

**Issue by mlagus** [FlutterFlow/flutterflow-issues#3949] opened 2024-10-01 18:08 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The paywalls i have in both my apps (2), just gives a blank screen. 

<img width="381" alt="image" src="https://github.com/user-attachments/assets/6b9347c5-34a4-42b4-9531-5aea533810d3">

I can also see that me reocurring revenues has got a billing error

<img width="771" alt="image" src="https://github.com/user-attachments/assets/174612ea-959a-4fb9-90ea-74eb213fb1b4">

I have changed nothing in them and 1 days ago a successful buy was made with android.

It seems to just affect Apple users, but im not 100% sure.

### Expected Behavior

My paywalls inside FF should display data of pricing and time-period, but it just goes gray. 

### Steps to Reproduce

Any data in FF that shows Revenue cat data makes them crash. 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wic/q25ROxLRJ+KrqccdFoCUvCDsmbYJJmu5+Sis9Grb0POxzac6kYhBuTc+qYWNtKEWLsHoKw+DMi+z9FfYDHymZfLZFyJdqVQ7/RXG/aovXCcyddGtTL/tmCBG43Ku3hQolOtBfWiUW1GeXNdmtcC7sN4f7Zwh9f6PHaOI=

### Visual documentation

Pasted above. 

### Environment

```markdown
- FlutterFlow version:  v5.0.2+ released October 1, 2024
- Platform: Mac
- Browser name and version: Chrome Version 129.0.6668.60 (Official Build) (arm64)
- Operating system and version affected: Mac/ios
```

**Comment by Alezanello** [comment] 2024-10-01 20:35
Hello!

We were unable to reproduce the issue using a new blank project. Please note that the GitHub Issue tracker is intended for bugs that can be consistently reproduced. For issues like this, we recommend reaching out to our support team via the in-app chat or by emailing [support@flutterflow.io](mailto:support@flutterflow.io).

Thank you for understanding!

Best regards,<br>Azanello

**Comment by mlagus** [comment] 2024-10-01 20:39
Please reinstate the reproduction of this issue
Connect Revenue cat purchasing (subscription or in app purchasing) with an Apple account and verify that the user gets prices or information from Apple pay -> Revenue cat -> Flutter Flow run test.
Best

**Comment by mlagus** [comment] 2024-10-06 09:23
Is there any progress on this?
I have two apps using Revenue cat, and i have done No changes in the pay walls of them, and they both show the grey screen (the two apps share no components) 
Android purchases seems to work.
Can you please verify if apple has made changes to how Flutterflow can display revenue cat information like prices? Or some kind of troubleshooting. 
Im still loosing purchases

**Comment by mlagus** [comment] 2024-10-06 13:02
Issue found: 
A licens agreement in App store was not signed for Paid apps.
After signing the license agreement purchases now works.
Thank and sorry for assigning team FF to this. 
Best

**Comment by Alezanello** [comment] 2024-10-11 19:45
I’m glad everything is working as expected now! I’ll go ahead and close this issue, but if you encounter anything else, please don’t hesitate to open a new one!

**Closed as not planned by Alezanello** 2024-10-11 19:45 UTC
Labels: closed: fixed
