### ISSUE TITLE
Errors are not visible

### ISSUE THREAD

**Issue by KirilOkun** [FlutterFlow/flutterflow-issues#332] opened 2023-01-10 07:28 UTC
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

When an error occurs its details should be visible.  The error description should include the underlying framework / language / system error in its entirety.   Having to export and run the application in an IDE just to see the error text is rather wasteful.

## Current behavior (required)

The error bottom sheet appears without any visible text.  See screenshot.
![Screenshot_20230110_142145](https://user-images.githubusercontent.com/1024870/211487494-8a7cf5a2-2c93-41de-ad5d-cfc806a546dd.png)

## To Reproduce (required)

1. Add column widget
2. Try in insert ListView widget into that column
3.  This well trigger the error

## Context (required)

Without the error specifics it's very difficult to troubleshoot problems.

## Your environment

* Version of FlutterFlow used:   3.0
* Platform (e.g. Web, MacOS Desktop):  Web
* Browser name and version:   Chrome Version 108.0.5359.124 (Official Build) (64-bit)
* Operating system and version (desktop or mobile):  Kubuntu 22.04

**Comment by yoheisoito** [comment] 2023-01-10 07:43
@KirilOkun Hi, can you please elaborate on this, and kindly explain what you want to see as output?
When I for example try to insert a Expanded child to a scrollable column, I'd get an error, but I can see the errors clearly as a pop-up.

<img width="618" alt="Screen Shot 2023-01-10 at 16 40 13" src="https://user-images.githubusercontent.com/115172813/211490931-06150660-7c4a-458f-90f3-7d80c08059a2.png">

**Comment by KirilOkun** [comment] 2023-01-10 07:47
I don't get a popup.  Instead a bottom sheet slides from the bottom.  As you can see in the screen shot it's completely white without any text.   The only visible thing is the close X icon in its top right corner.

**Comment by yoheisoito** [comment] 2023-01-10 08:00
@KirilOkun  May I confirm that what you are referring is regarding the Flutterflow editor, and not the web rendering result of your webapp? I cannot seem to replicate the bottom sheet part.

**Comment by KirilOkun** [comment] 2023-01-10 09:22
Correct.  I'm in the editor  and would like to see the description of the error caused by my faulty operations.

**Comment by yoheisoito** [comment] 2023-01-10 10:02
@KirilOkun Can you try starting a blank project, and try inserting a listview onto a scrollable column? You should expect for something like the screenshot above to pop-up.

**Comment by mravani2** [comment] 2023-01-10 16:53
I've been facing the same issue here for a while. Actually, seems to be a bug related to Dark/Light mode. I'm using the Dark mode, but the errors seem to be rendered using a mix of both Light and Dark mode, making the text unreadable.

Reproducing:
[screencast-docs.google.com-2023.01.10-13_48_27.webm](https://user-images.githubusercontent.com/122111577/211613458-d335e6ce-5679-4d81-81d4-c21c366a0adb.webm)


This is the error message while I'm using the dark mode:
![image](https://user-images.githubusercontent.com/122111577/211613338-3fd1b1f5-dc47-47ed-b540-a68be4608670.png)

And this is when I'm using the Light mode:
![image](https://user-images.githubusercontent.com/122111577/211613075-5e508584-c8b9-419e-97e7-e431a8cd1613.png)

**Comment by agreaves** [comment] 2023-01-11 03:49
Hi all, this is now fixed with the latest deploy. Thanks for the report!

**Closed by agreaves** 2023-01-11 03:49 UTC
Labels: status: needs triage, status: can't reproduce

**Comment by KirilOkun** [comment] 2023-01-11 04:17
@agreaves   Thanks Alex.  FF is like fine wine.  Is getting better all the time.
