### ISSUE TITLE
Screenshot mode generating wrong sized images

### ISSUE THREAD

**Issue by nickybittencourt** [FlutterFlow/flutterflow-issues#3971] opened 2024-10-03 15:42 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When generating screenshots using the screenshot mode in the FlutterFlow preview page, the images are being generated with dimensions that are 2x2 pixels smaller than expected. This occurs for various devices. For example, the iPhone 14 Pro Max screenshot is generated at 1288x2794 pixels instead of the expected 1290x2796 pixels.

### Expected Behavior

Screenshots should match the exact screen resolution of the selected device, for example, 1290x2796 pixels for iPhone 14 Pro Max.

### Steps to Reproduce

Navigate to the preview page of the FlutterFlow app.
Enter screenshot mode.
Select iPhone 14 Pro Max as the target device.
Generate a screenshot.
Compare the resulting image dimensions to the expected device resolution.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sl/GBw4lgof1Y15DUbMdR/CoQNkw2R408scp/bxIgGIDzPOw+ZPWlSFZCQubndHxEOkSmmlsK0PD5vuHEFcEoOTCcGZxH1s9UaQzdXlOme5OBC6rpS0BQGZtQfGKD0J6nhhN4HLFvdGcs21OpNti+cAzsH731IndISq/LZO4=

### Visual documentation

![Screenshot 2024-10-03 123935](https://github.com/user-attachments/assets/a54e7f0f-9a6f-4a72-a176-324bba548045)
![image](https://github.com/user-attachments/assets/afac2754-910a-4677-bede-bdc858e8f6f1)
![image](https://github.com/user-attachments/assets/f66df5bc-1fe9-4a35-a650-000edeec3e33)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.2+ released October 1, 2024
- Platform: Web
- Browser name and version: Chrome Version 129.0.6668.72
- Operating system and version affected: Windows 11
```

**Comment by nickybittencourt** [comment] 2024-10-03 15:47
Duplicate of #3962

**Comment by Alezanello** [comment] 2024-10-03 18:31
Hello!

You’re absolutely right, this is a duplicate of [Issue #3962](https://github.com/FlutterFlow/flutterflow-issues/issues/3962).

I’ll close this issue to consolidate our efforts, and you can follow any updates on the original issue. Thank you for your understanding!

**Closed as not planned by Alezanello** 2024-10-03 18:31 UTC
Labels: closed: duplicate
