### ISSUE TITLE
Problem with UTF-8 encoding in API calls

### ISSUE THREAD

**Issue by sl985** [FlutterFlow/flutterflow-issues#133] opened 2022-11-16 16:35 UTC
Problem with UTF-8 encoding in API calls

## Expected behavior (required)
When creating international projects, I come across specific characters of the alphabet. Using an API call, I receive a response from a POST request, I expect support for UTF-8 encoding. 

## Current behavior (required)
At the moment I get a response from the API server (e.g. from OpenAI.com) encoded as UTF-8, unfortunately the international characters are displayed (processed) incorrectly. 

For example, requests in Postman display correctly.

## To Reproduce (required)

The problem probably affects all APIs.
Example: Send a simple json request to the openAI.com API (registration and many uses are free)

1. In FlutterFlow add new API Calls:

Method Type: POST
API URL: https://api.openai.com/v1/completions

Headers
`Content-Type: application/json; charset=UTF-8
Authorization: Bearer YOUR SECRET KEY`

Body json
`{
  "model": "text-davinci-002",
  "prompt": "Człowiek: Napisz mini opowiadanie o kocie",
  "temperature": 0.7,
  "max_tokens": 256,
  "top_p": 1,
  "frequency_penalty": 0,
  "presence_penalty": 0
}
`

2. Send response and test (Test api call)

3. The response is not displayed correctly despite UTF-8 encoding.

## Context (required)
Currently, integration with external services in an international environment is not possible.

## Screenshots / recordings
FlutterFlow:
[https://ibb.co/2dqJCgk](https://ibb.co/2dqJCgk)

PostMan:
[https://ibb.co/Sv8ZQbj](https://ibb.co/Sv8ZQbj)

## Your environment

* **Bug Report Code:**
* Version of FlutterFlow used: 3.3.4
* Platform (e.g. Web, MacOS Desktop): MacOS
* Browser name and version: Chrome
* Operating system and version (desktop or mobile): both

**Comment by mackaby** [comment] 2022-11-18 07:50
I experience similar issues. API calls return fine (proper character encoding) when tested in postman, but when tested in FF, swedish characters do not get properly encoded.

**Comment by benjamin-carriou** [comment] 2022-11-21 07:55
+1, i had the same comportement with Meilisearch and Stripe

**Comment by wenkaifan0720** [comment] 2022-11-23 04:56
Hi all. Could you try the solution in this [link](https://stackoverflow.com/questions/71126682/utf-8-encoding-in-api-result-dart-flutter), which is to change/add this HTTP response header? Meanwhile, I'll raise this as a feature request.

**Comment by sl985** [comment] 2022-11-23 07:56
Hi, 
Thanks for the answer :)
Adding "charset=utf-8" to the header is not possible when using third party services. (e.g. DeepL, OpenAI, etc.).

Have you changed something? Currently, international characters are displayed correctly in my running application :)

International characters are still displayed incorrectly in Test API Call. But it's not urgent :)

**Comment by wenkaifan0720** [comment] 2022-11-28 16:29
I didn't do anything on my part actually. But glad to hear that your app is running fine now! I didn't implemented this feature so I'll ask for help from our team.

**Comment by wenkaifan0720** [comment] 2022-11-28 16:31
Hi @agreaves. I think you implemented the API test page. Any ideas for solving this issue?

**Comment by mackaby** [comment] 2022-11-28 16:31
I'm still having problems on my side, so please continue to investigate it :)

**Comment by agreaves** [comment] 2022-11-29 03:14
Hi @sl985 and @mackaby, thanks for the info. Could either or both of you add a Bug Report code to this issue? It's encrypted and allows me to view the project and further investigate, and I can test out the API with the proper encoding if I have your respective permissions.

**Comment by mackaby** [comment] 2022-12-01 16:08
@agreaves not really sure what it is you want me to upload (or where to do it). I sent the project link as DM via chat for now.

**Comment by agreaves** [comment] 2022-12-18 21:35
As it turns out, I believe the issue is that the response headers of the API calls don't always add `charset=utf-8`, which is necessary for the Dart `http` library to decode the response as UTF-8 by default. For those who control the API response, you should ensure the `charset` is set in the response headers.

For everyone else, we've now aded an option in "Advances Settings" to decode the response as UTF-8. This will be released on our next deployment.

**Closed by agreaves** 2022-12-18 21:35 UTC
Labels: status: needs triage

**Comment by kckoh** [comment] 2024-05-08 20:45
If you need an answer, you can find more information at https://docs.flutterflow.io/data-and-backend/api-calls/api-calls-101#decode-responses-as-utf-8 or https://community.flutterflow.io/database-and-apis/post/help-needed-handling-special-characters-in-flutterflow-eRsDUYlymNZrJ51.
