### ISSUE TITLE
FF Windows App Crashes at Project Sign-in step

### ISSUE THREAD

**Issue by coach1990** [FlutterFlow/flutterflow-issues#3517] opened 2024-07-31 01:56 UTC
### Can we access your project?

- [ ] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have two FF apps . One (APP-1) I downloaded from: https://app.flutterflow.io/ on MS Edge Browser using this feature on the browser, like this(image attached)
![image](https://github.com/user-attachments/assets/31613aa8-6431-4e23-baf5-5f969c96c960)

and, the other(APP-2), from here: https://flutterflow.io/desktop like this (image attached)
![image](https://github.com/user-attachments/assets/ad5057c6-18a2-4c1d-9e82-e3fcc188e3a8)

(APP-2) crashes when I try to Sign-in using Google on "Create Project" page under 'Firebase'.
(APP-1) works Okay.
I have made a video explaining all steps here, size was more than 10 MB(github max limit):  https://drive.google.com/file/d/1aP2VhMWoxZORtc2NS0u_jGGgywk6N2RU/view?usp=sharing

### Expected Behavior

FF official Desktop App shouldnt crash at the mentioned step.

### Steps to Reproduce

Download FF app by following below steps (in two ways):

Open Edge Browser
Go to: https://app.flutterflow.io/ 
Click on 'install app' option showing in URL at top, like this(image attached)
![image](https://github.com/user-attachments/assets/31613aa8-6431-4e23-baf5-5f969c96c960) 

Lets say this is your APP-1

Now, go to : https://flutterflow.io/desktop and install Windows Desktop App like this (image attached)
![image](https://github.com/user-attachments/assets/ad5057c6-18a2-4c1d-9e82-e3fcc188e3a8) 

Lets say this is your APP-2

please follow the following steps on both Apps(APP-1 and, APP-2)
Settings & Integrations - Firebase (Project setup) - Create Project - Select Timezone - Sign-in using Google

Observations: APP-2 should crash and, APP-1 shouldn't.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sls/l6otPvsdG1ZDuc8dB/TkQJUw8U508scp/bxIgGIDzPOw+ZPXsUFFWTc+5dAk6e0SmmmMC0srvhdnAVvc4CzKrQaZH1rVcUgvwQkWhUZOBDqiOdEdBM9tUC2GM5pjZkxZ5HLFucl4s7U6yG+/KUXTrHu/AIndISq/LZO4=

### Visual documentation

I have made a video explaining all steps here, size was more than 10 MB(github max limit):  https://drive.google.com/file/d/1aP2VhMWoxZORtc2NS0u_jGGgywk6N2RU/view?usp=sharing

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.79+ released July 31, 2024 Flutter version is 3.22.2
- Platform: Desktop App Windows
- Browser name and version: Microsoft Edge Version 127.0.2651.74 (Official build) (64-bit)
- Operating system and version affected: Windows 11 Home Single Language , 23H2
```

**Comment by rzambroni** [comment] 2024-07-31 16:31
Hello @coach1990,

Thank you for the report. The issue you're describing is a known problem on Windows desktop app that is already on the team's backlog to be addressed. We'll close this issue as a duplicate of the [original ticket](https://github.com/FlutterFlow/flutterflow-issues/issues/2839). Feel free to check that thread for updates.

The app you referred to as "APP-1" is not the Windows desktop app; it’s essentially a browser window wrapping the web app. The issue you mentioned only affects the Windows desktop version (your "APP-2").

Thanks again for bringing this to our attention.

**Closed as not planned** 2024-07-31 16:31 UTC
Labels: closed: duplicate
