### ISSUE TITLE
API Calls to launch URL Links do not work in Test Mode

### ISSUE THREAD

**Issue by hughCar389** [FlutterFlow/flutterflow-issues#3269] opened 2024-06-27 22:52 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

As I try to text the api calls using Launch URL or my custom action that does the same thing it does not work. Even though both actions worked fine a few days ago. 

### Expected Behavior

When the Provider/ Location Name is clicked, it launches the Link provided.

### Steps to Reproduce

1. Test Mode
2. Go to either Locations or Surgeons Page
3. Click the Location/Provider Name

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfkM/l7ZBgoctH176JKcJVvDgWH18cTYMvjuphcx40CIysOoYufM/RQ0NKTtSlf1Y/C1SkmlIF+fuNjeHPJPc4C0+CQblx0JVATxbLQnqWSpvSO820SHF8GeRUGUCe1renpSN5Nvh2W3gSwHGLNq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/124802801/10d7672a-dc3d-4eac-bb5f-373ff6832252)

### Environment

```markdown
- FlutterFlow version: 4.1.63+
- Platform: Web Desktop
- Browser name and version: Chrome 126.0.6478.127
- Operating system and version affected: Windows
```

### Additional Information

Even though both actions worked fine a few days ago.

**Comment by msusviela** [comment] 2024-06-28 17:50
Hi @hughCar389.

I wasn't able to replicate this error from blank. 

This is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. 

I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project.

 Thanks so much!

**Closed as not planned** 2024-07-02 20:08 UTC
Labels: closed: support request
