### ISSUE TITLE
bug with conditional visibility and potentially animations

### ISSUE THREAD

**Issue by VmarcellusR** [FlutterFlow/flutterflow-issues#3210] opened 2024-06-24 14:20 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have 2 containers, both show categories. The first one is a list view and the user can scroll it horizontally across the page. Second one is a grid view which displays more categories at the same time.

If the user would click on 'show all' then it would change app state called 'AllCategories' to be 'true' (it's 'false' by default), then because of conditional visibility container with the list view and text 'show all' would be hidden, and container with grid view and text 'hide' would appear. After clicking on 'hide' new 'true' containers would hide and 'false' containers would appear.

The problem: I added some 'on trigger' animations to containers with lists. Both groups would have animation only while appearing. But when the page loads for the first time I can see the right container, unfortunately without visible list inside of it. after a few clicks on 'show all', 'hide' the lists with categories appear.

To be more exact, it worked before with animations, only thing that I changed was animation duration or starting point. But now even when I remove animations, the lists do not appear.

Thank you.

### Expected Behavior

I expect from the second that page loads that it is going to show list view of categories. After clicking 'show all' it's going to hide the list view and show with animation a grid view with categories. And after clicking on 'hide' it's going to hide grid view and show the list view with animation.

### Steps to Reproduce

1. Go to home pgae
2. you won't see anything under 'categories' text
3. click on the text 'show all' then 'hide' until the categories will pop up
![atest](https://github.com/FlutterFlow/flutterflow-issues/assets/157606739/67cf2731-ecf4-4c18-823e-d6f71b9a3711)
![btest](https://github.com/FlutterFlow/flutterflow-issues/assets/157606739/5bddfe4f-3328-4514-932c-00316db98e00)

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESl/Lfx5RgrsMD+s/AdMdAhQIhNmY1bZMnktVxRR4bG4DtPJoUeOPsQ0NKTdSqSlFIIFf+nkUC0/DKitrpCO0oBw6ubJhf0JVAURWVRmaVMMW0CoeWWHJSBdFYIWqO15mJvSN7LutsSlIe2zupNa3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

![atest](https://github.com/FlutterFlow/flutterflow-issues/assets/157606739/9fd05c5e-fa2a-41c3-bd14-c9e2be1dc6cc)
![btest](https://github.com/FlutterFlow/flutterflow-issues/assets/157606739/00c930ab-5a6a-41b7-baa3-c7faa5ce6509)

### Environment

```markdown
- FlutterFlow version: new one, I'm not sure
- Platform: web
- Browser name and version: brave
- Operating system and version affected: windows 10
```

### Additional Information

This issue is quite annoying because it affects developing of other features. Thank you!

**Comment by paulperez-dev** [comment] 2024-06-27 18:45
Hi @VmarcellusR! I was unable to reproduce that behavior. Can you please verify if it happens in a new project? If so, please share the bug report code so we can better identify the cause of the issue.

**Comment by VmarcellusR** [comment] 2024-06-28 14:06
I deleted the animation and then both lists started displaying containers
correctly.

**Comment by paulperez-dev** [comment] 2024-07-03 20:06
Closing this issue. If you face a similar problem please submit a new issue. Have a great day!

**Closed as not planned** 2024-07-03 20:07 UTC
Labels: closed: other
