### ISSUE TITLE
Project doesn't run! Callback parameters: Conditional execution for action is improperly set.

### ISSUE THREAD

**Issue by appach22** [FlutterFlow/flutterflow-issues#2464] opened 2024-03-07 20:42 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If I create a component (or a custom widget) that has a parameter of type callback action and that action has a parameter then I can't use this parameter in actions, executed by this callback.
Please see Steps to Reproduce for detailed description.
Until the release on the 7th of March there was a workaround: I just had to change something in the action flow editor, wait for a few seconds (not closing the editor) and the error was gone for a while letting me to run the project.
This issue was described here: [https://github.com/FlutterFlow/flutterflow-issues/issues/2303](https://github.com/FlutterFlow/flutterflow-issues/issues/2303)
But now there are no workarounds anymore (and the behaviour also changed).

### Expected Behavior

Using parameters of callback actions doesn't produce errors

### Steps to Reproduce

1. Create a custom component.
2. Add a callback with parameter:

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/29fc1719-630c-478e-ac5f-cb27032d9e75/eb736287-c3b7-4fe4-b906-f8c77c7698ca?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yOWZjMTcxOS02MzBjLTQ3OGUtYWM1Zi1jYjI3MDMyZDllNzUvZWI3MzYyODctYzNiNy00ZmU0LWI5MDYtZjhjNzdjNzY5OGNhIiwiaWF0IjoxNzExNDYwMDM2LCJleHAiOjMzMjgyMDIwMDM2fQ.cuXIfPWc7QAw1KTB9WnspprYi3Les65DwGguJCAjabw)

1. Make use of the component and assign some actions to the callback:

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/33d46410-e405-4cf5-b893-adcfc0d02dd2/a59a21a3-3abf-4047-842f-aa6bf457a9bb?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zM2Q0NjQxMC1lNDA1LTRjZjUtYjg5My1hZGNmYzBkMDJkZDIvYTU5YTIxYTMtM2FiZi00MDQ3LTg0MmYtYWE2YmY0NTdhOWJiIiwiaWF0IjoxNzExNDYwMDM2LCJleHAiOjMzMjgyMDIwMDM2fQ.aKCktfdQbLqOfAyKuZX4s1VjUI04H5PAYO3S1zA5Yqs)

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f4e7b0ae-5c6f-4d93-b9d5-cf2b0ed8e80f/885e9cf1-88a7-4516-9425-66992978d5de?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mNGU3YjBhZS01YzZmLTRkOTMtYjlkNS1jZjJiMGVkOGU4MGYvODg1ZTljZjEtODhhNy00NTE2LTk0MjUtNjY5OTI5NzhkNWRlIiwiaWF0IjoxNzExNDYwMDM2LCJleHAiOjMzMjgyMDIwMDM2fQ.JJhVE8xRjN3ZZ53hev9nxm_kvUqyykVaOvIswA6Dptk)

1. Until now everything looks fine. But...
2. Close and then open the project.
3. You'll see the error at the top right corner that doesn't let you run the project:

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/b7534213-c8fa-4b72-a052-89197b4c4002/258cb54a-920d-47fc-9d87-86f0c46e415a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iNzUzNDIxMy1jOGZhLTRiNzItYTA1Mi04OTE5N2I0YzQwMDIvMjU4Y2I1NGEtOTIwZC00N2ZjLTlkODctODZmMGM0NmU0MTVhIiwiaWF0IjoxNzExNDYwMDM2LCJleHAiOjMzMjgyMDIwMDM2fQ.X-892x9OtD8vjj-SbmPnFZVP_jK9Ks64mSRrP_5DPAM)

1. Tap on this error message. Then tap once again in the action flow editor. You'll see this:

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/04c51dac-1243-4759-8d88-a09bd31e921c/81ab0e53-4f78-4a0e-b651-debb02dee9cc?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wNGM1MWRhYy0xMjQzLTQ3NTktOGQ4OC1hMDliZDMxZTkyMWMvODFhYjBlNTMtNGY3OC00YTBlLWI2NTEtZGViYjAyZGVlOWNjIiwiaWF0IjoxNzExNDYwMDM2LCJleHAiOjMzMjgyMDIwMDM2fQ.stPpt5aHUxXlwpG6dkp11g9hUtk6gyCPu2mOdbxrCGc)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gz8jfz812ofpE7aX6bu9Vq2MRNlA5bYc0sd4bGA0dCJzuPLMQdvXsVExoZMe9S3xcfUSmmmcdw6GMi9nIV+5eMk2cQL5FypByUDvdcHu5UZOBDquNPHxBJ91QBUib17Wj3RRQWftfSEFk1F2TNfC+TizAHYTxIlFISq/LZO4=

### Context

This is totally critical because I cannot run the project anymore (unless I stop using callback parameters which is not an option because I used them a lot since they were released a month ago).

### Visual documentation

All the images were provided in "Steps to reproduce" section

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1 released March 7, 2024
- Platform: Windows 10
- Browser name and version: Google Chrome
- Operating system and version affected:
```

**Comment by appach22** [comment] 2024-03-08 07:01
It even doesn't let me download the code 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/285972/436d923c-e399-4f18-a627-aea0605b86a1)

**Comment by oliverchoy** [comment] 2024-03-08 09:14
I have the same problem on a callback since earlier today

**Comment by Vignesh-bl** [comment] 2024-03-08 17:48
I am also facing the same issue. Until yesterday, it was working absolutely fine.
Today, while opening the project. I see a lot of errors. 
When I try to fix those issues... In Callback Parameters -> parameter variables were of unknown type.
I think Flutter Flow dudes messed up a bit while addressing some other issue.
Kindly fix this bug and give us a solution ASAP.

In my scenario, I am returning a DocumentReference from a component.

**Comment by Vignesh-bl** [comment] 2024-03-08 18:24
### This was the solution I found to resolve the errors temporarily. 

Hey guys... @appach22 @oliverchoy @asmengistu @organicnz 

Don't click on the errors to navigate to the error occuring action. 
Go to each and every action manually. Reassign the value. 

> NOTE :: if you still see the parameter as undefined, Go to the component and change the parameter type to other type. Click Confirm. Again change the type to your prefered type. Click Confirm again.

Don't bother about the errors highlighted inside the action flow editor.
Only see the global error list. You can see the issues decreasing one by one.

This worked for me. This is how I resolved the errors for now.
**I hope this helps. Give a thumbs up if this worked for you.**

**Comment by josescgar** [comment] 2024-03-09 11:34
I can confirm this error is also happening to me.

Before the latest released, I got the error while the conditional check was apparently fine. Now, I get the exact same error as described in this issue. Looks like type inference is not working correctly in the action builder for callback parameters when checking for errors.

**Comment by appach22** [comment] 2024-03-11 09:34
@Vignesh-bl unfortunately this approach doesn't work well when you have a lot of such actions. It actually helps to eliminate the errors for a while and run a project, but after any changes in the project the errors appear again. It's too painful to go everytime trough the whole project modifying actions before running the project...

**Comment by appach22** [comment] 2024-03-11 10:49
@hariprasadms please pay attention to this issue: it's really blocking.

**Comment by SinneoCompany** [comment] 2024-03-12 16:14
@hariprasadms, hell, I gave the same problem, my project is ruined bcs of the bug on your side after FlutterFlow update😵🤯
So many bugs appeared, I even had to make some functions unvisitable in my app bcs it's a shame to show it someone in such a condition. 

 @hariprasadms, pleeeease, fix this bug ASAP⚠️⚠️⚠️⚠️

**Comment by Tim-nocode** [comment] 2024-03-12 19:28
Same problem (

**Comment by Artem1110** [comment] 2024-03-13 18:03
I'm facing the same issue. My project is in trouble because of a bug on your side after the FF update. Please fix it as soon as possible! Thank you

**Comment by Dbrrohof** [comment] 2024-03-16 11:25
i'm experiencing the same error

**Comment by fsc-ethan** [comment] 2024-03-19 05:58
I'm also experiencing this issue...

For those of you who are looking for a temporary solution. I used to do this before by defining an app state and using that in the action.

For example.
1. Define the AppState value `fooBool`.
2. In your custom code instead of calling the callback of the widget, assign the AppState variable. Then call the callback without any parameters. This will trigger the FF action.
```dart
FFAppState().fooBool = true;
widget.fooCallback();
```
3.  In the FF action (callback), reference your variable through the UI in the App State section.

**Comment by kemperflow** [comment] 2024-03-19 16:44
I am experiencing the same, using the built-in fields for NewIndex and OldIndex on a ListView reorder event. I randomly get condition errors. I simply open and click confirm, I change nothing.. It clears for a bit and then comes back.. Highly annoying.

![Screenshot 2024-03-19 121824](https://github.com/FlutterFlow/flutterflow-issues/assets/63926602/1a842b2b-f185-4215-996b-72da1610c5f8)
![Screenshot 2024-03-19 121839](https://github.com/FlutterFlow/flutterflow-issues/assets/63926602/bd8397b9-f9df-472f-92f4-aa79cfbb9392)
![Screenshot 2024-03-19 121848](https://github.com/FlutterFlow/flutterflow-issues/assets/63926602/902765b5-62df-4045-9f1e-68494e5662cf)

**Comment by fsc-ethan** [comment] 2024-04-02 01:40
Any update on this?

**Comment by kemperflow** [comment] 2024-04-02 16:10
Still not fixed for me.. every so often I have to open and close to make this go away.. I have found I just have to save one of them and all of the errors go away. Annoying though.

**Comment by bfosberry** [comment] 2024-04-04 03:50
Im seeing the same issue, not sure why it suddenly became a consistent problem for me on one of my callbacks

**Comment by bfosberry** [comment] 2024-04-04 04:30
This had pretty much led to a work stoppage for me (and this is a serious bug that needs to be fixed asap) but I did find a workaround

1) As soon a you trigger your callback action flow save the value you need to make a decision with to a dedicate page state (or app state) variable (no page rebuild)
2) update your conditionals to check against that value. 

Since callback parameters are no longer being check in conditionals the issue does not occur anymore.

**Comment by nicmohr25** [comment] 2024-04-08 19:11
I currently face the same issue. 
Here is a Bug Report code.

IT48lcmB34hNodcF+Kr2b8FajjgXH2E7aLszkOxxRUs8J5TUB+x/evz4UBJoTbyndghIIk2gimM10NLIm9z1KvpeByyYR6Jm1Kt5Ww3gYH2tbJCkOpeCX0ZuGshmIFC94aevqxV+ObBZSFoa3TqlfNzLZCnqHb7vClYRAsiYNt/XmAfuQ0SLb3kNh1JWeC/v

**Comment by leighajarett** [comment] 2024-04-18 10:27
This has been fixed in our codebase and will be deployed soon!

**Closed by leighajarett** 2024-04-18 10:27 UTC
Labels: status: confirmed, Bug
