### ISSUE TITLE
APK Build faild when trying to download Apk

### ISSUE THREAD

**Issue by SoLexGrowth** [FlutterFlow/flutterflow-issues#3110] opened 2024-06-12 23:45 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When i tried to download the apk file of my project I received to many errors and the last time I downloaded the app which is about 3 hours before my recent try was successful but after the recent flutterflow updates it started crashing but it's working well on test and run mode too. 

### Expected Behavior

To download successfully

### Steps to Reproduce

please the recent updates it's affecting my app I don't know where the error is coming from please🙏

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEekM/l25J2n7wC0bX2YccxqwMwJ0QlUIInj+0bWRMhNbLwO4kAes+lRxFLYteXf1ZbeGGWkmcC+aHWjc71FPI5B0mbGKZ9/r5XQTmXZD+7Vaa1DaqsVXFBGehVGkCx4auNpAlNJbZpdFpiwGGUGvCdG3qCf9qOYwx5e6fDbOY=

### Visual documentation

![IMG-20240612-WA0036](https://github.com/FlutterFlow/flutterflow-issues/assets/156712790/cb235a28-5083-46c4-8651-ca6d054b4036)
![IMG-20240612-WA0037](https://github.com/FlutterFlow/flutterflow-issues/assets/156712790/6af67259-b2ff-4a31-b53f-a0d49ca47165)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

### Additional Information

Please this is a production app and am trying to download the app and test it on a real device before this issue occur please help me out

**Comment by msusviela** [comment] 2024-06-13 00:00
Hi @SoLexGrowth - Thanks for submitting the issue. I've taken a look at your project, but with a lot going on, it's challenging to pinpoint the issue. Given the nature of the problem you're highlighting, we need a blank project with the issue steps set up in it. Without these details, it might be a bit challenging for us to investigate the issue. Please provide the required information. If the issue is already resolved for you, please feel free to close the issue. Thanks!

**Comment by msusviela** [comment] 2024-06-20 12:17
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Closed as not planned** 2024-07-02 19:57 UTC
Labels: closed: other
