### ISSUE TITLE
Language translations do not copy when duplicating a page

### ISSUE THREAD

**Issue by veduai** [FlutterFlow/flutterflow-issues#3626] opened 2024-08-15 09:07 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

It happens every time:
I have a screen with English (default) text + a German translation.
When I duplicate that page or a component, the translation gets deleted (after a minute or so). 

Next, I have to manually copy - paste the texts in the Translations settings (which btw is a very poor solution to translation management!)

### Expected Behavior

Duplicate works for translations as well.

### Steps to Reproduce

See above. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5Tz/Hqx89PvsdG1ZDuc8dKniksJj81a5I70u5+GA0aNuvuP4kUfeDBV3FIXNe+S3NcL1n9gmY03OjPhuzAA+UnAz+cfIBl+LpqEQ/gcF2VSrqODpGadUZSL9FJJVPH3KeN2CR7JvdsdE461DiAC/DLTgHYJrK3NVYdOfmKKoPNpFmqQ0SLb3kNh1JWeC/v

### Visual documentation

![image](https://github.com/user-attachments/assets/84c2697a-8a4b-4bf3-8693-da5390fd1aa6)

### Environment

```markdown
- FlutterFlow version: 4.1.81.1
- Platform: Windows10
- Browser name and version Chrome 127.0.6533.100 (Official Build) (64-bit)
- Operating system and version affected:
```

**Comment by azanello** [comment] 2024-08-15 12:11
Thanks @veduai . I'm closing this issue because it's a duplicate of this issues:
https://github.com/FlutterFlow/flutterflow-issues/issues/2346

https://github.com/FlutterFlow/flutterflow-issues/issues/3457


The ENG team is already working on a fix for all this data loss regarding translations.

You can follow the original issue to keep updated.

Thanks for filling in!

**Closed as not planned** 2024-08-15 12:12 UTC
Labels: closed: duplicate

**Comment by Alezanello** [comment] 2024-08-15 12:33
Thanks @ I'm closing this issue because it's a duplicate of this issues:
https://github.com/FlutterFlow/flutterflow-issues/issues/2346

https://github.com/FlutterFlow/flutterflow-issues/issues/3457


The ENG team is already working on a fix for all this data loss regarding translations.

You can follow the original issue to keep updated.

Thanks for filling in!
