### ISSUE TITLE
Desktop app login page is loading forever

### ISSUE THREAD

**Issue by Rrrrnnyg** [FlutterFlow/flutterflow-issues#4108] opened 2024-10-18 15:47 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I install the flutter flow desktop app on my mac, and open the app.

### Expected Behavior

I expect to see the login page and wll login succussfully using email and password.

### Steps to Reproduce

when I open it, it has 2 behaviors randomly:  
1. loading state forever, display nothing but a loading widget
2. display the login page, will start loading when I click the login button and after a few seconds it will return a failure message.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kz8+A5c9IsdtJ+KXfbe54ijsvNjs8TLJEoetxc0gbfe/4EIocZc74Yk5tOPazaH1qKFCajnIy0eDTkuzXGO4BAxKtbpR/z88JehPPYzqmMISOCc+0X0R7BZ9bG0iC4J7UhBNAKsVhWVYe2DqMHOnKbz6Cf9qOYwx5e6fDbOY=

### Visual documentation

<img width="1145" alt="image" src="https://github.com/user-attachments/assets/5517d06b-cf9a-44f5-8dae-e6b79710273b">

### Environment

```markdown
- FlutterFlow version: 5.0.6
- Platform: Macbook Pro Apple M1 8GB
- Browser name and version:
- Operating system and version affected: macOS sequoia 15.0.1
```

**Comment by paulperez-dev** [comment] 2024-10-18 19:35
Hi @Rrrrnnyg,

We’ve released a new version today. Could you please download it and verify if the issue is resolved?

**Comment by Rrrrnnyg** [comment] 2024-10-19 01:26
> Hi @Rrrrnnyg,
> 
> We’ve released a new version today. Could you please download it and verify if the issue is resolved?

Hi @paulperez-dev ,
I tried uninstalling the old version and then installing the latest version, which is 5.0.7. However, the issue still exists. When I open the app, it displays the loading state.

I use VPN on my mac.

**Comment by paulperez-dev** [comment] 2024-10-19 01:37
Hi @Rrrrnnyg,

Is the issue present when you don't use the VPN?

**Comment by Rrrrnnyg** [comment] 2024-10-19 01:41
Hi @paulperez-dev , 
I tried closing the VPN, the issue still exists.

**Comment by Rrrrnnyg** [comment] 2024-10-24 07:06
Hi @paulperez-dev , 
I want to user local run but I still cannot open the desktop app. The issue still exists.
Should I pay for something first to solve the issue? I'm in free plan now.

**Comment by paulperez-dev** [comment] 2024-10-24 18:42
Hi @Rrrrnnyg,

This has been confirmed, and the team is actively working on a fix. I’ll make sure to keep you updated on our progress.

**Comment by paulperez-dev** [comment] 2024-10-24 18:46
Hi @Rrrrnnyg,

Can you please try removing the app cache? Here are the directories:<br>/Users/<user_name>/Library/Application Support/io.flutterflow.prod.mac

/Users/<user_name>/Library/Caches/io.flutterflow.prod.mac

**Comment by Rrrrnnyg** [comment] 2024-10-25 00:55
Hi, I tried, but the issue still exists.

Paul Pérez ***@***.***> 于2024年10月25日周五 02:47写道：

**Comment by paulperez-dev** [comment] 2024-10-25 12:05
Hi @Rrrrnnyg,

This may be project-specific issue. Our support team is best equipped to help resolve this, so could you please reach out to them? You can contact them via email at [support@flutterflow.io](mailto:support@flutterflow.io) or use the in-app chat within FlutterFlow.

I’ll close this issue here since this tracker is specifically for bugs that can be reproduced on blank projects.

Thanks so much for your understanding!

**Comment by Rrrrnnyg** [comment] 2024-10-25 12:15
Thank you, I will do that.

Paul Pérez ***@***.***>于2024年10月25日 周五20:06写道：

**Closed as not planned** 2024-10-25 13:36 UTC
Labels: closed: support request
