### ISSUE TITLE
Firestore index disappears when deployed from FF

### ISSUE THREAD

**Issue by nvimalraj** [FlutterFlow/flutterflow-issues#3065] opened 2024-06-05 04:03 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have similar issue as https://github.com/FlutterFlow/flutterflow-issues/issues/2060

One particular index is deleted from Firestore everytime I deploy the index from Flutterflow. I'm able to reproduce this consistently in the project. I do see this index present in the firestore.indexes.json file but it is not getting deployed. Just this one particular index is persistently deleted.

### Expected Behavior

Flutterflow deployes index to firestore and not affect if something was created manually.

### Steps to Reproduce

Deploy index from flutterflow.

This is not possible to reproduce from blank project as I have no clue at what stage flutterflow is not able to deploy this particular index.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTlc/l3ItOm/VH+KXtY8ZsjmA7CUMfWOdEket+EA0hNZStEYkideLeTFBLYtfneX9XMGab8XMH+MLJvfL9EPVcByiYR4hPwpRXQRbjeDuQabq1EpGOOkFAEZ5RJnbC0Z273xRQBMtvcmAs712LevCNG3qCf9qOYwx5e6fDbOY=

### Context

I have to remember to manually add this index each time after deploying. Otherwise, app becomes unusable.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/68550576/3944e5a8-9093-42e2-aa52-c76bc941c18b)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/68550576/889a5be2-81c7-4c28-b799-cec70fe3eab3)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/68550576/d6448e91-6783-42b9-94bb-badb37ae11bd)

### Environment

```markdown
- FlutterFlow version: 4.1.54
- Platform: All
- Browser name and version: Google Chrome/latest
- Operating system and version affected: MacOS
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by msusviela** [comment] 2024-06-07 14:02
Hi @nvimalraj<br><br>Thanks for your report, So sorry you are experiencing this issue. I was not able to reproduce this on a blank project, but it is replicable on yours. That's why I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. Thanks so much!

**Closed** 2024-06-14 03:07 UTC
Labels: status: can't reproduce
