### ISSUE TITLE
Error: The method 'getInitialAppLink' isn't defined for the class 'AppLinksPlatform'.

### ISSUE THREAD

**Issue by raycelgraterol** [FlutterFlow/flutterflow-issues#3223] opened 2024-06-25 17:24 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

97 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Launching lib/main.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...      
/root/.pub-cache/hosted/pub.dev/app_links-3.4.1/lib/app_links.dart:11:38: Error: The method 'getInitialAppLink' isn't defined for the class 'AppLinksPlatform'.
 - 'AppLinksPlatform' is from 'package:app_links_platform_interface/app_links_platform_interface.dart' ('/root/.pub-cache/hosted/pub.dev/app_links_platform_interface-1.2.0/lib/app_links_platform_interface.dart').
Try correcting the name to the name of an existing method, or defining a method named 'getInitialAppLink'.
    return AppLinksPlatform.instance.getInitialAppLink();
                                     ^^^^^^^^^^^^^^^^^
/root/.pub-cache/hosted/pub.dev/app_links-3.4.1/lib/app_links.dart:16:38: Error: The method 'getInitialAppLinkString' isn't defined for the class 'AppLinksPlatform'.
 - 'AppLinksPlatform' is from 'package:app_links_platform_interface/app_links_platform_interface.dart' ('/root/.pub-cache/hosted/pub.dev/app_links_platform_interface-1.2.0/lib/app_links_platform_interface.dart').
Try correcting the name to the name of an existing method, or defining a method named 'getInitialAppLinkString'.
    return AppLinksPlatform.instance.getInitialAppLinkString();
                                     ^^^^^^^^^^^^^^^^^^^^^^^
/root/.pub-cache/hosted/pub.dev/app_links-3.4.1/lib/app_links.dart:21:38: Error: The method 'getLatestAppLink' isn't defined for the class 'AppLinksPlatform'.
 - 'AppLinksPlatform' is from 'package:app_links_platform_interface/app_links_platform_interface.dart' ('/root/.pub-cache/hosted/pub.dev/app_links_platform_interface-1.2.0/lib/app_links_platform_interface.dart').
Try correcting the name to the name of an existing method, or defining a method named 'getLatestAppLink'.
    return AppLinksPlatform.instance.getLatestAppLink();
                                     ^^^^^^^^^^^^^^^^
/root/.pub-cache/hosted/pub.dev/app_links-3.4.1/lib/app_links.dart:26:38: Error: The method 'getLatestAppLinkString' isn't defined for the class 'AppLinksPlatform'.
 - 'AppLinksPlatform' is from 'package:app_links_platform_interface/app_links_platform_interface.dart' ('/root/.pub-cache/hosted/pub.dev/app_links_platform_interface-1.2.0/lib/app_links_platform_interface.dart').
Try correcting the name to the name of an existing method, or defining a method named 'getLatestAppLinkString'.
    return AppLinksPlatform.instance.getLatestAppLinkString();
                                     ^^^^^^^^^^^^^^^^^^^^^^
/root/.pub-cache/hosted/pub.dev/app_links-3.4.1/lib/app_links.dart:41:38: Error: The getter 'allStringLinkStream' isn't defined for the class 'AppLinksPlatform'.
 - 'AppLinksPlatform' is from 'package:app_links_platform_interface/app_links_platform_interface.dart' ('/root/.pub-cache/hosted/pub.dev/app_links_platform_interface-1.2.0/lib/app_links_platform_interface.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'allStringLinkStream'.
    return AppLinksPlatform.instance.allStringLinkStream;
                                     ^^^^^^^^^^^^^^^^^^^
/root/.pub-cache/hosted/pub.dev/app_links-3.4.1/lib/app_links.dart:46:38: Error: The getter 'allUriLinkStream' isn't defined for the class 'AppLinksPlatform'.
 - 'AppLinksPlatform' is from 'package:app_links_platform_interface/app_links_platform_interface.dart' ('/root/.pub-cache/hosted/pub.dev/app_links_platform_interface-1.2.0/lib/app_links_platform_interface.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'allUriLinkStream'.
    return AppLinksPlatform.instance.allUriLinkStream;
                                     ^^^^^^^^^^^^^^^^
Waiting for connection from debug service on Web Server...         66.9s
Failed to compile application.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/46403855/80329e85-4d06-4c94-8ae9-03d0a720a911)

### Expected Behavior

Run test mode normally, and publish the web app normally.

### Steps to Reproduce

1.- Inside the project click in test mode.
2.- Wait for Build process and check the error

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4WleflxItOn7xe0Kr+KcJahjw5Jkwka4IRl8N9YxQYF5ztE5wPXfikSEpWZ9+kTHxcL2aZhj8KzPTKhvzuA+UrNQeVQNVSws9USwH/ZGGubJS1DbrhZXNTEflJJVyA1rW3uR4mPthqR3w82E6mF/CRHxDDGK7jOFUjMMqkUaH4p1GrQ0SLb3kNh1JWeC/v

### Visual documentation

97 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Launching lib/main.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...      
/root/.pub-cache/hosted/pub.dev/app_links-3.4.1/lib/app_links.dart:11:38: Error: The method 'getInitialAppLink' isn't defined for the class 'AppLinksPlatform'.
 - 'AppLinksPlatform' is from 'package:app_links_platform_interface/app_links_platform_interface.dart' ('/root/.pub-cache/hosted/pub.dev/app_links_platform_interface-1.2.0/lib/app_links_platform_interface.dart').
Try correcting the name to the name of an existing method, or defining a method named 'getInitialAppLink'.
    return AppLinksPlatform.instance.getInitialAppLink();
                                     ^^^^^^^^^^^^^^^^^
/root/.pub-cache/hosted/pub.dev/app_links-3.4.1/lib/app_links.dart:16:38: Error: The method 'getInitialAppLinkString' isn't defined for the class 'AppLinksPlatform'.
 - 'AppLinksPlatform' is from 'package:app_links_platform_interface/app_links_platform_interface.dart' ('/root/.pub-cache/hosted/pub.dev/app_links_platform_interface-1.2.0/lib/app_links_platform_interface.dart').
Try correcting the name to the name of an existing method, or defining a method named 'getInitialAppLinkString'.
    return AppLinksPlatform.instance.getInitialAppLinkString();
                                     ^^^^^^^^^^^^^^^^^^^^^^^
/root/.pub-cache/hosted/pub.dev/app_links-3.4.1/lib/app_links.dart:21:38: Error: The method 'getLatestAppLink' isn't defined for the class 'AppLinksPlatform'.
 - 'AppLinksPlatform' is from 'package:app_links_platform_interface/app_links_platform_interface.dart' ('/root/.pub-cache/hosted/pub.dev/app_links_platform_interface-1.2.0/lib/app_links_platform_interface.dart').
Try correcting the name to the name of an existing method, or defining a method named 'getLatestAppLink'.
    return AppLinksPlatform.instance.getLatestAppLink();
                                     ^^^^^^^^^^^^^^^^
/root/.pub-cache/hosted/pub.dev/app_links-3.4.1/lib/app_links.dart:26:38: Error: The method 'getLatestAppLinkString' isn't defined for the class 'AppLinksPlatform'.
 - 'AppLinksPlatform' is from 'package:app_links_platform_interface/app_links_platform_interface.dart' ('/root/.pub-cache/hosted/pub.dev/app_links_platform_interface-1.2.0/lib/app_links_platform_interface.dart').
Try correcting the name to the name of an existing method, or defining a method named 'getLatestAppLinkString'.
    return AppLinksPlatform.instance.getLatestAppLinkString();
                                     ^^^^^^^^^^^^^^^^^^^^^^
/root/.pub-cache/hosted/pub.dev/app_links-3.4.1/lib/app_links.dart:41:38: Error: The getter 'allStringLinkStream' isn't defined for the class 'AppLinksPlatform'.
 - 'AppLinksPlatform' is from 'package:app_links_platform_interface/app_links_platform_interface.dart' ('/root/.pub-cache/hosted/pub.dev/app_links_platform_interface-1.2.0/lib/app_links_platform_interface.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'allStringLinkStream'.
    return AppLinksPlatform.instance.allStringLinkStream;
                                     ^^^^^^^^^^^^^^^^^^^
/root/.pub-cache/hosted/pub.dev/app_links-3.4.1/lib/app_links.dart:46:38: Error: The getter 'allUriLinkStream' isn't defined for the class 'AppLinksPlatform'.
 - 'AppLinksPlatform' is from 'package:app_links_platform_interface/app_links_platform_interface.dart' ('/root/.pub-cache/hosted/pub.dev/app_links_platform_interface-1.2.0/lib/app_links_platform_interface.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'allUriLinkStream'.
    return AppLinksPlatform.instance.allUriLinkStream;
                                     ^^^^^^^^^^^^^^^^
Waiting for connection from debug service on Web Server...         66.9s
Failed to compile application.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/46403855/4ad69980-22e5-408f-b3ef-edd57759a699)

### Environment

```markdown
- FlutterFlow version: 4.1.61+
- Platform: Flutterflow
- Browser name and version: Google chrome 126.0.6478.126 
- Operating system and version affected: Windows 11 Pro 23H2
```

**Comment by msusviela** [comment] 2024-06-25 17:25
Hi all. It seems to be related to a package upgrade on [pub.dev](http://pub.dev/). Our engineering team is already aware and working on a fix.

I'm closing this issue because It's a duplicate of: [https://github.com/FlutterFlow/flutterflow-issues/issues/3217](https://github.com/FlutterFlow/flutterflow-issues/issues/3217) I'll be following this from this issue.

Thanks for your reports!

**Closed as not planned** 2024-06-25 17:26 UTC
Labels: closed: duplicate
