### ISSUE TITLE
Some Custom Functions stopped working

### ISSUE THREAD

**Issue by vladislavrushapps** [FlutterFlow/flutterflow-issues#2739] opened 2024-04-16 08:30 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

FlutterFlow v4.1 (previous versions worked without any troubles)

Some of the functions that previously worked fined stopped compiling possibly due to libraries naming conflicts. Common error is attached in screenshot

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/534e2db7-9ab6-42d2-b618-d1e001879ad5/0bafe566-fcfc-468d-a44b-e0b6a9879435?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81MzRlMmRiNy05YWI2LTQyZDItYjYxOC1kMWUwMDE4NzlhZDUvMGJhZmU1NjYtZmNmYy00NjhkLWE0NGItZTBiNmE5ODc5NDM1IiwiaWF0IjoxNzEzMjc1MzU5LCJleHAiOjMzMjgzODM1MzU5fQ.6Lonov-4cpDzB4xfu3Kqvpq5QjyfhX_1yvTAy1cARyQ)

### Expected Behavior

1. All imports that are predefined and cannot be edited work without conflicts
2. Or at least we have an ability to modify imports

### Steps to Reproduce

Try to comple following custom functions functions that use intl.dart library:

1. 

import 'dart:convert';
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:timeago/timeago.dart' as timeago;
import '/flutter_flow/lat_lng.dart';
import '/flutter_flow/place.dart';
import '/flutter_flow/uploaded_file.dart';
import '/flutter_flow/custom_functions.dart';
import '/backend/schema/structs/index.dart';
import '/backend/supabase/supabase.dart';
import '/auth/supabase_auth/auth_util.dart';

bool isNull(String? widgetState) {
  /// MODIFY CODE ONLY BELOW THIS LINE

if (widgetState == null) {
    return true;
  } else {
    return false;
  }

/// MODIFY CODE ONLY ABOVE THIS LINE
}

1. 

import 'dart:convert';
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:timeago/timeago.dart' as timeago;
import '/flutter_flow/lat_lng.dart';
import '/flutter_flow/place.dart';
import '/flutter_flow/uploaded_file.dart';
import '/flutter_flow/custom_functions.dart';
import '/backend/schema/structs/index.dart';
import '/backend/supabase/supabase.dart';
import '/auth/supabase_auth/auth_util.dart';

DateTime? stringToDatetime(String inputString) {
  /// MODIFY CODE ONLY BELOW THIS LINE

// convert string to datetime
  try {
    return DateTime.parse(inputString);
  } catch (e) {
    return null;
  }

/// MODIFY CODE ONLY ABOVE THIS LINE
}

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfl87q3ItOvuFd7q6IYcIwuCcsQkscTeU30+thcw4bI+PmPLQfP8z8QFZWYuqHY39EGVb8jk4BpqH2j+LlUPc4HyedGrpH/6hTUxDgZFyhaZS6CZaSSkZPI8dMCUy6052KkQolCPBZc1Fl7GeyDd6+Y3qCf9qOYwx5e6fDbOY=

### Context

I am using custom functions to convert strings form text fields to datetime format to insert into DB

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/ef6d7eef-c74f-42b3-97e8-9f0ad3dfe5a1/add7c1b6-c40b-421e-b239-9ae1520b7fd0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lZjZkN2VlZi1jNzRmLTQyYjMtOTdlOC05ZjBhZDNkZmU1YTEvYWRkN2MxYjYtYzQwYi00MjFlLWIyMzktOWFlMTUyMGI3ZmQwIiwiaWF0IjoxNzEzMjc1MzU5LCJleHAiOjMzMjgzODM1MzU5fQ.5iUJ4ICveKhVwYt7Om7Gf5mzqx71fSj5oSX6bt2FzM4)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform:Web
- Browser name and version: Chrome 123.0.6312.123
- Operating system and version affected: Windows
```

**Comment by AbsorbingSheath** [comment] 2024-04-18 15:04
@paulperez-dev could you please take a look?

**Comment by paulperez-dev** [comment] 2024-04-18 15:09
Hi @AbsorbingSheath, thanks for your report. Sure thing! Can you please let me know which version of FF you are using?

**Comment by vladislavrushapps** [comment] 2024-04-18 15:12
@paulperez-dev sure, it's 4.1.34

**Comment by paulperez-dev** [comment] 2024-04-19 01:37
Hi @vladislavrushapp! I validated the issue on your project but I was not able to replicate it on a blank project. Can you please try to replicate it on a blank project and share the bug report code?

**Comment by vladislavrushapps** [comment] 2024-04-20 15:18
@paulperez-dev Thanks for checking the issue on blank project. I tried to replicate the problem on blank project as well and the issue did not reproduce.
However, Issue is sill present in project (and I cannot create new custom function with the same code because it throws the same error).

Bug report does not produce the exact code of error, however it shows such statements (screen attached)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/167181093/dd025e92-a8cc-4ccd-be9f-f1b474b0c486)

**Comment by vladislavrushapps** [comment] 2024-04-21 09:45
Little Update. I replaced custom functions to custom actions and got to the compilation. basecally, I receive the same error as on screenshot above:

76 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Launching lib/main.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...      
lib/backend/supabase/database/tables/date_calendar.dart:112:15: Error: 'year' is already declared in this scope.
  String? get year => getField<String>('Year');
              ^^^^
lib/backend/supabase/database/tables/date_calendar.dart:72:11: Context: Previous declaration of 'year'.
  int get year => getField<int>('year_')!;
          ^^^^
lib/backend/supabase/database/tables/date_calendar.dart:113:7: Error: 'year' is already declared in this scope.
  set year(String? value) => setField<String>('Year', value);
      ^^^^
lib/backend/supabase/database/tables/date_calendar.dart:73:7: Context: Previous declaration of 'year'.
  set year(int value) => setField<int>('year_', value);
      ^^^^
lib/backend/supabase/database/tables/date_calendar.dart:115:15: Error: 'month' is already declared in this scope.
  String? get month => getField<String>('Month');
              ^^^^^
lib/backend/supabase/database/tables/date_calendar.dart:57:11: Context: Previous declaration of 'month'.
  int get month => getField<int>('month_')!;
          ^^^^^
lib/backend/supabase/database/tables/date_calendar.dart:116:7: Error: 'month' is already declared in this scope.
  set month(String? value) => setField<String>('Month', value);
      ^^^^^
lib/backend/supabase/database/tables/date_calendar.dart:58:7: Context: Previous declaration of 'month'.
  set month(int value) => setField<int>('month_', value);
      ^^^^^
lib/backend/supabase/database/tables/date_calendar.dart:118:15: Error: 'quarter' is already declared in this scope.
  String? get quarter => getField<String>('Quarter');
              ^^^^^^^
lib/backend/supabase/database/tables/date_calendar.dart:66:11: Context: Previous declaration of 'quarter'.
  int get quarter => getField<int>('quarter_')!;
          ^^^^^^^
lib/backend/supabase/database/tables/date_calendar.dart:119:7: Error: 'quarter' is already declared in this scope.
  set quarter(String? value) => setField<String>('Quarter', value);
      ^^^^^^^
lib/backend/supabase/database/tables/date_calendar.dart:67:7: Context: Previous declaration of 'quarter'.
  set quarter(int value) => setField<int>('quarter_', value);
      ^^^^^^^
Waiting for connection from debug service on Web Server...         57.7s
Failed to compile application.

**Comment by paulperez-dev** [comment] 2024-04-21 18:39
Hi @vladislavrushapp, this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: support@flutterflow.io or using the in-app chat inside of FlutterFlow. <br><br>I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. <br><br>Thanks so much!

**Closed** 2024-04-21 18:40 UTC
Labels: closed: support request
