### ISSUE TITLE
Local Build Version Solving Fails for Most Recent FF Update (Flutter Version 3.22.1 Upgrade)

### ISSUE THREAD

**Issue by ayjayem** [FlutterFlow/flutterflow-issues#3233] opened 2024-06-25 20:34 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

As of today, I'm getting this error when installing and building my project on a local device:

"Because <project> depends on video_player_android >=2.4.15 which requires SDK version >=3.4.0 <4.0.0, version solving failed."

This is a new error, which I suspect may have been introduced on FlutterFlow's side with a recent update. Any guidance appreciated.

### Expected Behavior

Project should continue to build locally properly as it did previously.

### Steps to Reproduce

1. Build and run project locally.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTlfLqy4ZNocNc+KXqc8cxpGU7M0MfWOdEket+EA0hfJzsBKQqZ8zeXBJLYte8dFZmIlaWhkwJpqyKvt/hCcEqJRKAfa56+JRXQTryfzqWb5+YDqiNOUF6EfJQN2a9y5+R2BJQNtBuLUIh616ECvCNG3qCf9qOYwx5e6fDbOY=

### Visual documentation

<img width="842" alt="Screenshot 2024-06-25 at 4 30 48 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/16900187/a8f19872-441b-4edb-89ec-720b0a7795df">

### Environment

```markdown
- FlutterFlow version: 4.1.61
- Platform: MacBook
- Browser name and version: N/A (Local Run)
- Operating system and version affected: macOS Sonoma 14.3.1
```

### Additional Information

Cannot build locally, so project is completely blocked for testing, which requires a device.

**Comment by rzambroni** [comment] 2024-06-25 20:38
Hey @ayjayem, sorry about that issue, it looks like it was caused by the macOS app being a bit behind. I'm marking this as a duplicate in favor of a previous ticket: [https://github.com/FlutterFlow/flutterflow-issues/issues/3225](https://github.com/FlutterFlow/flutterflow-issues/issues/3225)

Please refer to that ticket for updates.

Thanks.

**Closed as not planned** 2024-06-25 20:38 UTC
Labels: closed: duplicate

**Comment by ayjayem** [comment] 2024-06-25 20:47
Great - and the issue appears to be fixed to me now. Many thanks.
