### ISSUE TITLE
Possible Rollback

### ISSUE THREAD

**Issue by kiingor** [FlutterFlow/flutterflow-issues#3216] opened 2024-06-25 15:32 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello everything is fine?

I lost my project, or it was rolled back, I don't know. I was doing it on the web, and I downloaded the application, when I entered it it was like an old version, when I pressed F5 on the web page my project was the old one, what can I do?

### Expected Behavior

It should synchronize data from the web to the development application, not replacing the version of one or the other

### Steps to Reproduce

If you develop on the web, it is probably not synchronizing with the desktop app

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

not have

### Visual documentation

not have

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by msusviela** [comment] 2024-06-26 12:54
Hey @kiingor, Thanks for your report, So sorry you are experiencing this issue. This is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. Thanks so much!

**Closed as not planned** 2024-07-04 12:35 UTC
Labels: closed: support request
