### ISSUE TITLE
Capitalization does not work on web when using a standard keyboard via desktop

### ISSUE THREAD

**Issue by Krystian95** [FlutterFlow/flutterflow-issues#914] opened 2023-05-22 13:08 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hi, If I set the Capitalization "Words" on a Text Field, is not applied in the UI nor in the databased field as shown below.

### Expected Behavior

Text should be in capitalization as chosen, e.g. "Words" as "Hi Welcome On Board!"

### Steps to Reproduce

1. Create a new page
2. Insert a Text Field widget
3. Set capitalization "Words"

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4whvHl05dJtbxK0KX6cfpviiovIjo1R+cnmOwaTis8I4jyO5YUSMzBUFFWTL2rT2xlMFqammYd/PfqiuL9J/FdJRWdbqZ+1c9qdQvNUkGuV5izCqrsfW1SP9xmI2q00qun2RB+OuNvS3gM6mGHfO+uQjffJb7uOm0GAOaLKdeK2SrDX1iXc2URm05KZDPz

### Context

- Want to capitalize the Text Field content

### Visual documentation

![Screenshot 2023-05-22 alle 13 13 09](https://github.com/FlutterFlow/flutterflow-issues/assets/24765669/6a880c96-a000-43d4-9684-41c66c49e930)
![Screenshot 2023-05-22 alle 13 13 28](https://github.com/FlutterFlow/flutterflow-issues/assets/24765669/29922315-caea-4b18-97d7-6d61a490e500)
![Screenshot 2023-05-22 alle 13 14 01](https://github.com/FlutterFlow/flutterflow-issues/assets/24765669/488376dc-ae75-4884-b0d9-957ff9ba2d05)

### Environment

```markdown
- FlutterFlow version: 1.1.73
- Platform: Web (Mode Test, Run and Web deployment)
- Browser name and version: Chrome v. 113.0.5672.126
- Operating system and version affected: macOS Ventura 13.3.1 (a) (22E772610a)
```

**Comment by andrewjhop** [comment] 2023-05-24 22:59
Was just about to submit a bug for this.

Can confirm this is web-only behaviour, if you access the same page via a mobile device (even if it's via a browser) it works.

Please redefine bug as:

**Capitalization does not work on web when using a standard keyboard via desktop.**

**Comment by wenkaifan0720** [comment] 2023-07-05 20:04
Closed as this is a duplicate of https://github.com/FlutterFlow/flutterflow-issues/issues/935.

**Closed by wenkaifan0720** 2023-07-05 20:04 UTC
Labels: type: bug, status: confirmed, closed: duplicate
