### ISSUE TITLE
Certain Dropdowns break in IOS Testflight but not in Testmode on Browser

### ISSUE THREAD

**Issue by mitchxxmitch-code** [FlutterFlow/flutterflow-issues#3281] opened 2024-06-29 05:53 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello, 

So I have dropdowns that work and dropdowns that don't work. 

Here the category dropdown works but the body part dropdown does not:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/85580874/0a40091e-2147-4a52-8c78-d5b4c78ae83b)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/85580874/8b3d9f55-f846-4dd7-ab63-b49d84b07d70)

I have checked everything but it breaks on IOS. Also the setting is the same between those two dropdowns except of the searchability. The searchability can not be the issue since there is another dropdown in the createHabit component that also does not work on mobile - it leads the app to break.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/85580874/0425570a-3722-4802-871a-5425ecd5a8e4)

The interesting thing is that it does not break in Testmode in the browser. 

Maybe you have an idea what I can do now. 

### Expected Behavior

That it does not break as soon as you click on it on mobile.

### Steps to Reproduce

1. Open the side menue and choose exercises
2. click the floating plus button
3. Here you can add an exercise and you see the dropdowns as shown in the screenshots.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Oz8r13ItNsctZ1aXpbflFmmI5Jkw4apZN09Z+awgbJbnNG4sUds+lRGduOeGndghHeWG0kj8y+ezSm9z2GPEBISqdfIhZ/rtfWxXMWkeuR82NPKuoRnFUGshgG0ih4LSS3RZ/Ps52SEIR7U7zJem+cBXsGITqIEQvHPmIUZPXmAfuQ0SLb3kNh1JWeC/v

### Visual documentation

Already provided above (screenshots)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.65+ released June 29, 2024 / Flutter version is 3.22.2
- Platform:IOS Mobile
- Browser name and version: Chrome 126.0.6478.127 (Official Build) (arm64)
- Operating system and version affected: IOS 17.5.1
```

**Comment by msusviela** [comment] 2024-07-02 16:49
Hey @mitchxxmitch-code, Thanks for your report, So sorry you are experiencing this issue. I was not able to reproduce this on a blank project, but it is replicable on yours. That's why I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: support@flutterflow.io or using the in-app chat inside of FlutterFlow. I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. Thanks so much!

**Closed as not planned** 2024-07-05 16:46 UTC
Labels: status: can't reproduce
