### ISSUE TITLE
Support for AdaptiveIcon

### ISSUE THREAD

**Issue by corsaro0** [FlutterFlow/flutterflow-issues#2201] opened 2024-01-19 11:28 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Flutterflow does not use an adaptive icon
[https://developer.android.com/develop/ui/views/launch/icon_design_adaptive?hl=it](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive?hl=it)

On many devices the icon in the notifications is not seen, while in the smartphone home page, the image is square with a white background around it

### Expected Behavior

I expect the icon to be visible in notifications and not be surrounded by a white background
it would be sufficient to use one of these sites to upload an adaptive icon to flutterflow starting from an image [https://easyappicon.com/](https://easyappicon.com/)

### Steps to Reproduce

1. Upload an App icon
2. Publish app on play store
3. Use a device that has round icons (example Google Pixel 7)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTl8nf5ZZ1rsNc+KX1K/pvr2QQI0MdXOczitVEew4bCIj4B6QIfc/4XEpWZMizaH5IemGJpGIypcLOifzPNPZcEy6bfpw4ycxiWBPPYzimM5iMELigWn9BM9FVCB205sOKkSYmKsxtR0Y92V2Df9+yTT+Cf9qOYwx5e6fDbOY=

### Context

When I send notifications the user doesn't immediately recognize my app.

Compared to other apps, the visual impact and attention is less

### Visual documentation

![Screenshot 2024-01-19 122647](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/01171464-caa6-4cea-a6d8-a3be37c0dd66/6cdb48ba-724a-4c3a-8388-aaa3e4d54413?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wMTE3MTQ2NC1jYWE2LTRjZWEtYTZkOC1hM2JlMzdjMGRkNjYvNmNkYjQ4YmEtNzI0YS00YzNhLTgzODgtYWFhM2U0ZDU0NDEzIiwiaWF0IjoxNzA1NzQzMzI2LCJleHAiOjMzMjc2MzAzMzI2fQ.KbwrhLA_zlF7XiyP62fSuP3Ud3NQnsfgpUli1XsbaSc)

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: v4.0
- Platform: Web
- Browser name and version: Chrome 107.0.5304.110
- Operating system and version affected: Windows 11
- Mobile device: Google pixel 7
```

**Comment by mixart** [comment] 2024-01-20 03:27
Thank you for reporting, without this feature any apps published from FF look amateur and broken on Android, hindering people taking our apps seriously. I just launched my app and the first feedback I got was "hey the icon looks janky"

**Comment by wenkaifan0720** [comment] 2024-01-29 14:33
Hi @corsaro0. This is a very valid feature request. I have brought this up to our dev team. Thanks!

**Comment by leighajarett** [comment] 2024-02-06 00:46
Since this is a feature request and not a bug, we're going to close this issue. Thanks again for reporting it! We're discussing internally

**Comment by mixart** [comment] 2024-02-06 01:34
Keep in mind there are 2 issues here.

1) issue with notifications not rendering correctly

2) the app launcher icon on Android does not render correctly

For 2, if you build your app from flutterflow it will display the icon in a small square as shown below. I'm not sure how this isn't considered a bug.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/13832/41753418-61e8-443a-a9cd-10068d8adc0d)

**Comment by corsaro0** [comment] 2024-02-06 09:14
Exactly, the app has a decidedly less quality appearance, plus in the notifications since you can't see the icon the app is unrecognizable and this lowers the click rate

We need a solution for this. We have asked this many times in various posts

**Comment by leighajarett** [comment] 2024-02-07 18:14
I see. Okay I will keep it open, either way we are discussing internally. Thanks for the feedback!

**Comment by mixart** [comment] 2024-03-23 15:36
In case this helps the team...

https://community.flutterflow.io/ask-the-community/post/why-is-the-android-app-icon-small-Z3UVO3uGC0syYzf

**Comment by mixart** [comment] 2024-03-23 15:44
Here is the GitHub issue being tracked by the team...

https://github.com/FlutterFlow/flutterflow-issues/issues/2201

**Comment by mixart** [comment] 2024-03-29 03:02
Is it possible to get an update @leighajarett whether this will ever get prioritized so I can plan to get a devs help with my project. I'm unable to do any workarounds (local builds won't work for me).

**Comment by leighajarett** [comment] 2024-03-29 11:37
It's fairly high on our backlog so hoping to knock this off soon!!

**Comment by NLDylan** [comment] 2024-04-04 13:33
Can also say that this is bothering me, first thing people notice is the app icon.
I do have the option to show my icon with no background color thus maybe making it acceptable.. But this is not my preferred look. Hope flutterflow team has a fix soon before people release app to the store.

**Comment by leighajarett** [comment] 2024-04-04 14:08
Yeah I totally get it, we're hoping to get to it soon! Thanks for understanding!

**Comment by GameFailsTV** [comment] 2024-04-04 18:48
I cant deploy my app because of this bug too... "oh, you can do it downloading your app and doing this or that"! But this is not what flutterflow "Deploy to Play Store" button means

Please, fix it!

**Comment by clickqcollect** [comment] 2024-04-05 12:52
This would be so helpful. Its extremely cumbersome to adjust it and moving my project from FF to local just to fix an Icon seems counterintuitive to what the feature "Deploy to Play Store" suggest.

Hope this will make it into the next Release for 4/18/24

**Comment by leighajarett** [comment] 2024-04-17 12:17
This should be available next week :)

**Closed** 2024-04-18 01:25 UTC
Labels: type: feature / enhancement request, Feature, needs docs, needs annoucement, Estimated Release: 4/25/24

**Comment by Aging-Developer** [comment] 2024-07-29 17:37
So how do we set the background layer?
