### ISSUE TITLE
After enabling Multi Langauge option - the default language of project changed

### ISSUE THREAD

**Issue by khomya** [FlutterFlow/flutterflow-issues#678] opened 2023-03-28 05:07 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have added the MultiLangage feature to the project. After that, the default language in Test and Run modes became English, although Russian was selected in the options.

### Expected Behavior

I edit the project in the selected (Russian) language. But when I start the Test or Run mode, the language switches to English. And the Russian should remain.

### Steps To Reproduce

1. Look in Settings. Russian as main language is selected
2. Run project
3. See that project is in English

### Bug Report Code

Failure to copy to clipboard: PlatformException(copy fail, Clipboard.set Data failed, null, null) X

### Context

I need the default language to be Russian.

### Additional info

Also in Safari I dont see FLAGS in MultiLanguage Widget - as in my Settings page, as in Run or test Mode.
<img width="769" alt="Screenshot 2023-03-28 at 09 02 09" src="https://user-images.githubusercontent.com/2369704/228133215-743ab7b9-7879-46e9-bf69-a9076410339d.png">

<img width="353" alt="Screenshot 2023-03-28 at 09 03 19" src="https://user-images.githubusercontent.com/2369704/228133380-7e3d28f6-2645-4737-bb56-71bfa4f2e6a6.png">

<img width="359" alt="Screenshot 2023-03-28 at 09 04 15" src="https://user-images.githubusercontent.com/2369704/228133487-f815cbad-14cd-4e01-a8bb-dbbb06e2317f.png">

When I try to get Bug Report Code, I get this message
"Failure to copy to clipboard: PlatformException(copy fail, Clipboard.set Data failed, null, null)
X"

### Environment

```markdown
- FlutterFlow version: 3.7.3
- Platform: MacOS Desktop
- Browser name and version: Safari 16.3 (18614.4.6.1.6)
- Operating system and version affected: MasOS Ventura 13.2.1 (22D68)
```

**Comment by victoriahuang1** [comment] 2023-04-04 06:07
Hi @khomya thanks for the report. Could you share a link to your project?

**Comment by khomya** [comment] 2023-05-10 08:18
And also there is a bug with LanguageSelector Widget.

"Flag Size" and "Border Radius" - when you choose them, they remembered, but the value is not displaying.

**Comment by victoriahuang1** [comment] 2023-05-10 22:03
Hi @khomya , I was able to find the bug for the "Flag Size" and "Border Radius" properties not displaying. This should be fixed upon the next deploy.

However, I could not reproduce the other issues with my own project.

It looks like you modified the app since you reported the bug, so I don't see any English left on the Auth screen (like in your screenshot). However, I do see that some of the entries under "Russian" under languages are actually English. So it seems like you wrote the text originally in English, and then switched the primary language to Russian. This clears all English -> Russian translations, and the app assumes that the text you wrote was actually Russian. Hence when you started the app, it was all English (since the Russian translations were lost, so the default English text became labeled as "Russian"). Can you confirm this? If not, providing documentation like a screen recording of the issue would be very helpful.

Also can you upload a screen recording of what happens when you click the "Translate all" button? I could not reproduce this issue either.
> And more to this bug - autotranslate of all pages is not working.

**Comment by khomya** [comment] 2023-05-11 04:30
Hello. I think you are right, I started making the application as a copy of the Courts application and it was in English. And then I chose the language "Russian". Can all this be fixed?

**Comment by khomya** [comment] 2023-05-11 04:34
This is video of "translate" issue.

https://github.com/FlutterFlow/flutterflow-issues/assets/2369704/d65a177b-3b9a-41c2-ab8d-e5add8544bb6

**Comment by victoriahuang1** [comment] 2023-05-11 06:06
Thanks for the update @khomya . What browser are you using? Have you tried Chrome?

> Hello. I think you are right, I started making the application as a copy of the Courts application and it was in English. And then I chose the language "Russian". Can all this be fixed?

As for this, what you are seeing is the current expected behavior. However, I agree that we can make it less confusing. I will put this in as a feature request and see if it can be prioritized. It won't be handled within the scope of this issue, however, as this is a feature request.

**Comment by khomya** [comment] 2023-05-11 07:33
I use Chrome for FlutterFlow.

What about Languages? What I can do to fix my situation with Languages? Because I want to make my app with three Languages.

**Comment by victoriahuang1** [comment] 2023-05-15 01:41
I have made an update to the "translate all" function. It should fix your issue with the next deploy.

In your situation, I would recommend to write everything in Russian _only_ (because it's the primary language). And use translations for the other 2 languages.

**Closed by victoriahuang1** 2023-05-15 01:41 UTC
Labels: status: needs information

**Comment by khomya** [comment] 2023-06-11 16:53
Well. "Translate All" still not working. I push it. Several seconds pass. No errors. But no result at all.

And when I added English language - its now the default language for all.

Can you swap in database the variable for my default lang? I started project in English and then renamed landuage to Russian. But obviously in database its still English.
