### ISSUE TITLE
All assets in the project got reset to "No asset selected"

### ISSUE THREAD

**Issue by isegal** [FlutterFlow/flutterflow-issues#3568] opened 2024-08-06 18:24 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Today logged on to find that our app is not showing any asset images. It is as if some automation cleared them all out.

Looking at snapshots, every older version we look also displays "no asset selected" for images.

### Expected Behavior

Expected to have assets because we did not make any changes to those parts of the projects at all.

### Steps to Reproduce

We did not make any steps that we are aware of.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ghcnfz5Fgobhc0bXuY+9amiE7KXp8aK00rdx+EBAjfYz4O7QEfPfOQBBucO6zaH52fVGbv3MF7vzIhofDLPQ7OU6qfbZ8/pZfWhPPbGGlM4yPDLW0e39TGZtWG0yX5MGSkBIkLfpuLkI1wEz3GvOART6Cf9qOYwx5e6fDbOY=

### Visual documentation

We will submit the image in the ticket.

### Environment

```markdown
- FlutterFlow version: Latest
- Platform: Web
- Browser name and version: Chrome (latest)
- Operating system and version affected: MacOS (latest)
```

**Comment by msusviela** [comment] 2024-08-06 19:03
Hi @isegal. So sorry you're experiencing this.<br>I'm closing this issue since it's a duplicate of this:<br>[https://github.com/FlutterFlow/flutterflow-issues/issues/3565](https://github.com/FlutterFlow/flutterflow-issues/issues/3565)<br><br>You can follow the original thread for updates. Currently our ENG team is aware of this and is deploying a fix for this that will be put as soon as possible into production.<br>Thanks for filling in.

**Closed as not planned by msusviela** 2024-08-06 19:03 UTC
Labels: closed: duplicate
