### ISSUE TITLE
Call to Google Maps distancematrix API call results in empty JSON on iOS, but works fine in webapp

### ISSUE THREAD

**Issue by RickAtSavveLabs** [FlutterFlow/flutterflow-issues#3360] opened 2024-07-10 17:39 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am using the [Distance Matrix API](https://developers.google.com/maps/documentation/distance-matrix) to calculation the driving and walking time/distance between 2 locations. When the call is made, I have the results go directly to a data structure. When I deploy the project to the web and run, the call successfully works. 

In iOS when I do a local run and deploy with TestFlight, I get no results. The conditional test after the api call says that it was successful. But when I try to debugPrint the json or any returned data, it shows as null. 

Note: My other calls to Google Maps in iOS are successful.

### Expected Behavior

Making the API call should work exactly the same in iOS as it does in the web app. 

### Steps to Reproduce

1. Construct the destination and origin strings as described in the doc. Provide locations in latitude and longitude with "," and "|" deliminators as described in doc.

Example of two locations for destinations and origins
42.346788,-71.037084|42.345868,-71.039659
42.351683,-71.047126|42.349665,-71.050355

2. The only other required parameter is an apikey.
3. Make the api call
4. If done on iOS, the result will be successful but empty.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4shfLq0812pbxH1rr+bMB7/ToRHFw1bbgescpCbw4bIYj2P4lzY876P1BuOPG4YXNtfVmcp140+NWPvvD2GsI5BAqtRtlh+pNyEgnxVnynWpuTF7qKf3dABeBUIGLFyqujhSN5IbBsdGQR1E2qOOiiVjTXK7LRCkQwSq/LZO4=

### Visual documentation

![Screenshot of ScreenFloat at Jul 10, 2024 at 1_22_21 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/154351161/8082d1d2-666b-4782-b2d6-aaa106a9e1dd)
![Screenshot of FlutterFlow at Jul 10, 2024 at 1_23_32 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/154351161/bbe796cb-8f87-4749-b64a-f1bc0b307862)
![Screenshot of FlutterFlow at Jul 10, 2024 at 1_25_00 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/154351161/7cee2160-5df0-4a04-83dc-76358e5b7083)

### Environment

```markdown
- FlutterFlow version: v4.1.69
- Platform: MacOS
- Browser name and version: Safari v17.5
- Operating system and version affected: iOS v17.5.1
```

### Additional Information

In my app, users will use proximity and time to get somewhere to help determine if a place is of interest. This not working diminishes the useful functionality of the app.

**Comment by msusviela** [comment] 2024-07-11 14:39
Hey @RickAtSavveLabs, Thanks for your report, So sorry you are experiencing this issue. I was not able to reproduce this on a blank project, but if it is replicable on yours, I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. Thanks so much!

**Closed as not planned** 2024-07-12 14:56 UTC
Labels: closed: support request
