### ISSUE TITLE
"requires authentication" option page doesn't work

### ISSUE THREAD

**Issue by guibertjulien** [FlutterFlow/flutterflow-issues#3188] opened 2024-06-20 14:28 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I created a profile page with "requires authentication" option and add it in Nav bar. When I'm not logged, i can see the icon in Nav bar and I can go to the page.

### Expected Behavior

- When not logged, don't see the page in Nav bar
- When not logged, go to the login page instead of the page

### Steps to Reproduce

1. create a new page with "requires authentication"
2. add the page in Nav bar
3. run
4. log out
5. go to the page

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTk876y5Ngob1I+KrQd+1VhjksCUMdXOczitVEew4bCIj4EOwqeczSVBFDXfKzaH1UEWD/hmEKwtbFit/tEfYpIQedGYRb1od+EBPPbGOtMa6tELWVOHB9EexbfnKsyKWzvxZ7JrJZWmwu7XGqLuiiYz+Cf9qOYwx5e6fDbOY=

### Visual documentation

<img width="1024" alt="Capture d’écran 2024-06-20 à 14 52 47" src="https://github.com/FlutterFlow/flutterflow-issues/assets/3823108/f54e89ce-bfbf-46e0-8749-e91e9e8842f7">

### Environment

```markdown
- FlutterFlow version: 4.1.61
- Platform: Mac
- Browser name and version: Chrome 125.0.6422.176
- Operating system and version affected:
```

**Comment by paulperez-dev** [comment] 2024-06-21 21:36
Hi @guibertjulien! The NavBar does not use the route to navigate to the different tabs (it is more like the same page that replaces the content based on the option selected), so that configuration will only apply when you navigate from another page.<br><br>I'm closing this issue since this is not a bug.

**Closed as not planned** 2024-06-21 21:39 UTC
Labels: closed: not a bug

**Comment by hasnainadam7** [comment] 2025-01-22 10:26
i have an admin panel  in which i am deleting the users on first time deletion its forcefully logout that user but after 2nd deletion of users it's not working 

Admin Panel (MERN STACK ) controlling users to edit details or deleting users
Mobile APP FlutterFlow  for users

**Comment by hasnainadam7** [comment] 2025-01-22 10:35
@paulperez-dev not working in app
