### ISSUE TITLE
Supabase FlutterFlow Password reset flow. Url Redirect Not Working Properly

### ISSUE THREAD

**Issue by geopopos** [FlutterFlow/flutterflow-issues#2623] opened 2024-03-29 13:04 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hey all,

I've been trying to debug this issue for a few days.

I have set up supabase authentication within my flutterflow app.

I have a forgot password view that looks like this:
![Screenshot 2024-03-29 at 8 57 29 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/20918002/84acab7c-67c9-47a5-8713-edaec86fd407)

when i click the send link button i execute a resetpassword action
![Screenshot 2024-03-29 at 8 57 22 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/20918002/5efb1d1c-7ba9-4216-9970-883d7b842e85)

once that happens the email is successfully sent, but for some reason the link url is to localhost:3000
![Screenshot 2024-03-29 at 8 57 15 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/20918002/bfac0843-a7e1-4576-b73c-4d0c885b0b76)

https://tkxeyqrzqzqhxfglvyau.supabase.co/auth/v1/verify?token=2e9874ab54b6d088097123e9cedb6cc17a6041fa8199ccb83dcf9ea2&type=recovery&redirect_to=http://localhost:3000

I've set up the url config for my specific app
![Screenshot 2024-03-29 at 8 57 08 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/20918002/6056c912-818b-412e-b5e4-2f35e7c9e50b)

and i've tried multiple different configs of the confirmation url, here is my current email template

Copy
<h2>Reset Password</h2>

<p>Follow this link to reset the password for your user:</p>
<p><a href="{{ .ConfirmationURL }}resetPassword">Reset Password</a></p>
this looks to be a bug in the flutterflow set up.

as the auth reset password action only has one parameter "email field" and doesn't provide an option to change the redirect field.

### Expected Behavior

I would expect the deep link to work for the password reset link, log me in and allow me to redirect me to a url i can specify within the action

### Steps to Reproduce

Create project
Connect supabase as auth service
Create a forgot password page
create an action on button click to send a password reset link using supabase actions
cry because it's not working (but only for 2-3 minutes)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hc/qy5d1m8tK7q6Jccdanj85Jn43aJE3kO1raCgoIYyuOpl/evWkM0huXeG6dHxUf0SmmnkK0vD6ufOfGPJeORCdfKFx/892EAvLcEGna5OBPrqsW0FtHcRXCFSA15+7nxNNBOhhck4c702EJt/LbB3dNJjyImdISq/LZO4=

### Context

I am trying to set up a password reset flow, where the user can click the generated link and be 
1. logged in
2. directed to the "resetPassword" page to reset their password

### Visual documentation

https://www.loom.com/share/d52bd94927f6437893cc57b310216495

### Environment

```markdown
- FlutterFlow version: 4.1.35 
- Platform: mac os
- Browser name and version: using chrome 117.0.5938.149 (Official Build) (arm64) and local run on my iphone 12 with the latest version of ios
- Operating system and version affected: all
```

**Comment by scottwyn13** [comment] 2024-03-29 14:14
Have you confirmed your [email template](https://supabase.com/dashboard/project/tkxeyqrzqzqhxfglvyau/auth/templates) is not hard coded to localhost rather than pulling from your siteURL?

**Comment by geopopos** [comment] 2024-03-29 16:01
> Have you confirmed your [email template](https://supabase.com/dashboard/project/tkxeyqrzqzqhxfglvyau/auth/templates) is not hard coded to localhost rather than pulling from your siteURL?

yes, this is my email template
```
<h2>Reset Password</h2>

<p>Follow this link to reset the password for your user:</p>
<p><a href="{{ .ConfirmationURL }}resetPassword">Reset Password</a></p>
```

**Comment by geopopos** [comment] 2024-03-29 16:02
I've also tried
1. just the confirmationURL
2. hardcoding the url

**Comment by ignalauret** [comment] 2024-04-11 21:34
Hey @geopopos thanks for your report. I just followed your steps and I was able to get the correct URL from the reset password email. It was sending me to localhost, until I changed the SiteUrl on the Supabase console. I don't have any RedirectUrls. <br>Some things you may check:

* Are you sure you clicked on "Save" on the Supabase console?
* Are you sure you sent a **NEW** **RESET EMAIL** after you changed the configuration?
* Are you sure you are changing the correct Supabase project?

Hope this helps and that you are able to solve your problem. I'm going to close this issue because it's not a FF bug, any other help you may need please feel free to contact our Customer Support team. <br>Have a great day!

**Closed** 2024-04-17 11:29 UTC
Labels: status: not a bug
