### ISSUE TITLE
Missing null check marks for UploadedFile

### ISSUE THREAD

**Issue by treirouxel88** [FlutterFlow/flutterflow-issues#1895] opened 2023-11-22 14:34 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Application fails to build. FFUploadedFile can be null and is not accessed with a null check

### Expected Behavior

Application should build normally (APK, test mode...), the page state variable should be accessed with a null check (?.) because it can be nullable

### Steps to Reproduce

1. create new project
2. create new page
3. add a page state of UploadedFile (bytes)
4. add anything with a conditionnal action or visibility
5. test with a condition if the state of UploadedFile (bytes) "Is Set"

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40lsn1z4pNj7xH15CBaPlVgmA5JmYmbYInjOtRaDYvCIyqOph/P8z4bRZWOdO4SlNhHE7/mToC7vCLk/H1OPAqAEiZY656+qhtEzngRXq8RrbXCsyRPnQkBdJhI26j0aWFsCN4Kuxocmdm7V6LNdi/fCnvCZ+/Zwh9f6PHaOI=

### Context

Testing if there is a file stored in page state

### Visual documentation

Error got while building
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/83276347/1df1fa37-8736-4cf6-8cb5-e0cf4a8e062f)
Checking if the file is set
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/83276347/a8b31938-e582-494f-850d-09d2ec667bb6)
Variable definition in page state
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/83276347/aa73e910-2546-48ae-9d02-63924853c871)
Maybe the devs forgor that FFUploadedFile can be null
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/83276347/70eb0a9f-fd93-44ad-989d-915018352f31)
The page model
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/83276347/ba5b8d8c-80a3-4bfe-918f-270a48ae4844)

### Environment

```markdown
- FlutterFlow version: v4.0 released November 21, 2023
- Platform: Web
- Browser name and version: Edge 119.0.2151.72
- Operating system and version affected: Windows 11 22h2
```

**Comment by elementh69** [comment] 2023-11-23 13:17
I encountered the same issue about two weeks ago, and after a few hours of troubleshooting, the problem mysteriously disappeared. I believe it may not be an issue on your end, but rather with FlutterFlow.

**Comment by treirouxel88** [comment] 2023-12-08 09:55
If you have the same problem there is a workaround, just download the code and open the Flutter project in Android Studio, you go to the file that contains the error (underlined in red) and normally you will be able to see the error detected by Android Studio. The "Dart Analysis" menu also allowed me to quickly identify the problem.
Here is a screenshot of the fix proposed by Android Studio :
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/83276347/fc2adc91-6869-4b3b-8066-127ebe96625f)

**Comment by ready4sea** [comment] 2024-01-04 13:50
I am encountering the exact same issue. The steps to reproduce are identical to what was initially reported.

Indeed, there seems to be a missing null check  on the test. It is possible to correct it by downloading the code and adding the missing question mark. But it breaks the flow for development and testing, making for a lot of lost time.

It's a pity this issue is left without being treated and goes stale, because there clearly seems to be an issue.

If the FlutterFlow team wants to have a look at it, I have a blank project setup to reproduce this case, and I will leave it open for a few days. The bug report code is IT4sz/Hqx89grttH1rqBcflB/GU4NUM2ap0sscsZa0kdB4joPLJ/PcnRZRZDTf3gd1NhHFSJrGEF0976ifzlDMIBBE+tG6Y91bhxWgnMWXq8Rc2NBqiKVHd8TMJMCHKh0rWvvApTHMFeSCU97zn3JOTJYA/DCZu/Zwh9f6PHaOI=

<img width="603" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/105978018/71bfa133-543b-466f-9a7c-b0341ef8dc11">

<img width="611" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/105978018/9600cfdf-cd03-4cb9-a72c-cf338cdee057">

**Comment by takashiff** [comment] 2024-01-09 17:46
Hello @treirouxel88, thank you for your bug report. We have recently put in a fix for this issue, and the changes should be reflected within the next few weeks. Thank you for your patience!

**Closed by takashiff** 2024-01-09 17:46 UTC
Labels: type: bug, status: confirmed
