### ISSUE TITLE
SQLite integration error

### ISSUE THREAD

**Issue by tom4sz** [FlutterFlow/flutterflow-issues#3300] opened 2024-07-02 15:05 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

in my project i have SQLite database with one REAL type column, values are sometimes with fractional part equals 0 ie. 50.0 and with such values read query returns type error because value is casted as INT not as Double. When i use CAST in read query to force return type - SELECT CAST (column AS REAL) FlutterFlow read query also returns type error - this time returns NULL instead of REAL type. The same query from SQLite client works ok (with or without cast). When i use SQLite IDE to testquery i see that it works as expected from outside of FlutterFlow. 

### Expected Behavior

read query shuld return proper type od data.

### Steps to Reproduce

1. Create table with colum type REAL
2. Put example values with fractional part and without fractional part (ie. 50.0, 40.33)
3. In flutterflow Create READ Query that return type is Double
4. You get Type error

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4olfHlvM9JpbxK1ar+KcIwpyQ4G0g6ba8/l8pBZywgfZzzBLN/fPfQPxZCXc+jTAlYfU2mp14D/+jFuN/hNPcEYC+sbohg1bpqaAH/TjiQRJeTF7mCZkZ5N9hXfkiC3JmruhImOsxYSmdh1GGAF/OtfALrNoTUIno8Sq/LZO4=

### Visual documentation

Queries from sqliteonline:
![q1](https://github.com/FlutterFlow/flutterflow-issues/assets/23585218/91605bb5-895b-4cb7-9749-069c6c7918c5)
![q2](https://github.com/FlutterFlow/flutterflow-issues/assets/23585218/d675e500-202a-4f78-bc1a-5519beca85f9)
![q3](https://github.com/FlutterFlow/flutterflow-issues/assets/23585218/56d0bc30-3a75-46d4-a5df-4d4af9048a23)

### Environment

```markdown
FlutterFlow v4.1.65+ released July 1, 2024
Flutter version is 3.22.2
```

**Comment by Alezanello** [comment] 2024-07-02 20:18
Hello!

Thank you for reaching out!

After reviewing your project and testing a new blank project, I was unable to reproduce the issue. Everything seems to be working correctly.

As a result, I will close this issue as it does not appear to be a bug. It might be a project-specific situation that caused the error. If you continue to experience this problem, please contact support at support@flutterflow.io or via the chat in the app.

Best regards,<br>Azanello

**Closed as completed** 2024-07-05 20:50 UTC
Labels: status: can't reproduce, closed : project specific
