### ISSUE TITLE
Undo command in the Custom Widget editor undoes project actions, not text changes

### ISSUE THREAD

**Issue by dsabanin** [FlutterFlow/flutterflow-issues#726] opened 2023-04-05 15:11 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If you're writing code in the Custom Widget code editor and want to undo a recent change, pressing Cmd+Z instead undoes things like creating the Custom Widget, changing project settings, etc. Potentially very problematic if someone doesn't notice, as the undone changes may not be immediately obvious.

### Expected Behavior

When editing code, Cmd+Z should be confined to actions within the editor.

### Steps To Reproduce

1. Create new Custom Widget
2. Write some code
3. Do Cmd+Z and see how the Custom Widget disappears from the sidebar on the left.

### Bug Report Code

IT4si/Lqx892rsRE17rAccFr/GMsQlM2a+c0scp/bxIgGIDzPOw+ZPXsVxBDXemoS1FEIUSmmTsd+N3GheLpK/A4AxWuQbpgwbpQYQvKQmClUZOBDpDpQkBQTPFbfmqm0KWzsRUlNtNfV3AN6maYFty8dHPrNYzKImdISq/LZO4=

### Context

I freaked out because if I don't notice this behavior next time, it may undo something important, like app setting changes, widget tree changes and who knows what else.

### Environment

```markdown
- FlutterFlow version: 1.1.57
- Platform: 3.7.3
- Browser name and version: macOS desktop app
- Operating system and version affected: macOS Ventura 13.3 (22E252)
```

**Comment by HeikoKanzler** [comment] 2023-04-05 16:30
The undo function is super dangerous. It "randomly" undos actions, but certainly not the last step you made. Especially when using the code editor, it undos actions in the widget tree/app structure.

**Comment by wenkaifan0720** [comment] 2023-04-05 21:26
Hi @dsabanin. I just tried the steps you described, but the custom widget didn't disappear. Could you try to screen record the process (preferably in an empty project assuming this issue can still be reproduced)?

**Comment by HeikoKanzler** [comment] 2023-04-15 07:26
Try something different:
Create a new function, do not save it at this time, start typing and press CMD-Z.
Hard to notice, but you will see that the function will disappear Form the left function list and you can't save it any longer as it has been removed.

You have to start all over again.

**Comment by HeikoKanzler** [comment] 2023-04-23 06:55
Bump.
Yesterday i lost a whole action again because of this bug.

I would consider this as critical.

**Comment by aemelyanovff** [comment] 2023-04-26 16:47
Thanks for reporting the issue, @dsabanin!

There's no easy way to make Cmd+Z undo text changes unfortunately. But what I can do for now is disable Cmd+Z and Cmd+Shift+Z on when editing code in the desktop app. This will be included in the next update.

BTW the code editor in the web version of FlutterFlow is much more advanced. These shortcuts work there as expected.

**Comment by aemelyanovff** [comment] 2023-04-27 21:17
The fix disabling Cmd+Z and Cmd+Shift+Z in the desktop text editor has been released.

**Closed by aemelyanovff** 2023-04-27 21:17 UTC
Labels: status: confirmed, closed: fixed
