### ISSUE TITLE
JSON data with DocumentReference from Firebase not being decoded.

### ISSUE THREAD

**Issue by apppbuilder** [FlutterFlow/flutterflow-issues#2842] opened 2024-04-30 14:50 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

JSON data is not being decoded to DataType when it contains a Document Refence.

### Expected Behavior

It should decode everything and return dataType.

### Steps to Reproduce

1. Create a Custom Function.
2. Send a test data.
3. The error shows up.

Also, I tried decoding the data with the JSON to DataType and it didn't worked, that's why I got in the Custom Function to check what would be happening.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gz8rlvJR2rsRE+ZSIbu9ammYUNkN9Rpc0stluZxEoIpznBuw+e8nBdlBWTsjiaVNcfWaWhnkzptLyj9jPOuw7Ay2bG9w/+JZcTjnOe2ijabq0O5aoeEcmI+RXfHKA1sOW3QlSC/hfSGAF12eUPtmiZATDBOu/Zwh9f6PHaOI=

### Context

I'm receiving data from Cloud Function POST API, so I need to decode it and start using it. Everything is ok with the Cloud Function, it's sending data and everything, but the data is not showing properly in the app, after lots of tests, found it that it was in the DocReference item.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/160440373/f6feae80-500c-4768-a7de-466b6fbc2fc1)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/160440373/ccd70ffe-ccc8-40f5-9a3c-9d0bacafee4d)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/160440373/99d845f7-51f3-4138-ae68-5d6e2153e7b9)

### Additional Info

I created an isolated project to check if the problem would persist, and yes, it keeps up.

Also, if you all wanna see the isolated project and check everything, I'll send a bug report code below:

IT4gz8rlvJR2rsRE+ZSIbu9ammYUNkN9Rpc0stluZxEoIpznBuw+e8nBdlBWTsjiaVNcfWaWhnkzptLyj9jPOuw7Ay2bG9w/+JZcTjnOe2ijabq0O5aoeEcmI+RXfHKA1sOW3QlSC/hfSGAF12eUPtmiZATDBOu/Zwh9f6PHaOI=

(the problem isn't in the widget, but in the custom functions while decoding the data)

### Environment

```markdown
FlutterFlow v4.1.45+ released April 25, 2024
Flutter version is 3.19.1
- Platform: Web
- Browser name and version: Chrome latest
- Operating system and version affected: W11
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by apppbuilder** [comment] 2024-05-08 01:56
Do not close this issue. Thank you. @ignalauret

**Comment by ignalauret** [comment] 2024-05-10 19:56
Hey @apppbuilder thanks for your report. Our technical team has been checking your issue and they said this is not a bug. Apparently the Custom Function test mode doesn't support what you are trying to achieve. In their words: <br>"This is not a bug. It is a known limitation in custom code. Firestore calls does not work in functions test mode as it does not compile the entire app code.". <br>So sadly, you are going to have to test them on the Run modes. I will create a feature request to enable this testing, but I don't know when that can get implemented. I'm sorry for the inconvenience, have a great day!

**Comment by apppbuilder** [comment] 2024-05-12 01:47
@ignalauret Well... thank you for your reply, but to be honest it's not in the test mode... it's in the real version of the app after deployed. I'll check again and see if it's corrected or not...

Soon I'll be back with more data.

**Comment by apppbuilder** [comment] 2024-05-15 16:41
Ok, let's go to real data. @ignalauret

Here is a live app, deployed and in closed testing inside an android smartphone.

The flow is an "on page load" and after calling an API Call that triggers a Cloud Function, it returns some userData to make the app move further.

=========================
### **### Expected data:**
![expectedData](https://github.com/FlutterFlow/flutterflow-issues/assets/160440373/b0082417-f01b-40c6-a85b-5ba59ed5da7f)

=========================
### **### TheFlow**
![TestControl](https://github.com/FlutterFlow/flutterflow-issues/assets/160440373/754cd18b-e34a-4462-aa4a-963b9a57347d)
![TestControlFlowR](https://github.com/FlutterFlow/flutterflow-issues/assets/160440373/c35a420b-18ac-4b63-b12e-86d990920cb3)

> I used some "Update App State" to check when it was stopping in the live app.


=========================
### **### Test 1** — Native decoding

![Test1 - 1](https://github.com/FlutterFlow/flutterflow-issues/assets/160440373/77a3a702-33bb-44b9-bc8d-57b05364336c)
![Test1 - 2](https://github.com/FlutterFlow/flutterflow-issues/assets/160440373/8cfc1216-e6f4-4193-9816-53d0abf26584)

> Results:
> It stopped in the action before deconding data... (erroState now equals 6)

<img src="https://github.com/FlutterFlow/flutterflow-issues/assets/160440373/c6590f0f-75c6-44cd-b671-597dddfb1911" width="350">

=========================
### **### Test 2** — Custom Function decoding
![Test2 - 1](https://github.com/FlutterFlow/flutterflow-issues/assets/160440373/b7b2c985-b6d9-44cd-b92e-a2ec974122a3)

> Results: = The same...
> It stopped in the action before deconding data... (erroState now equals 6)

<img src="https://github.com/FlutterFlow/flutterflow-issues/assets/160440373/d5da1a7a-f6d8-45e1-b238-e60ad450cc7f" width="350">


=========================
### **### Test 3** — Custom Function decoding — WITHOUT DOC REFERENCE

So, to make this happen, I removed the phraseRaf field that was returning from the Cloud Function and also created a new DataType inside Flutterflow:

![Test3 - 1](https://github.com/FlutterFlow/flutterflow-issues/assets/160440373/f7160114-942c-46aa-89e2-137725fd68fe)



> Results: = Now it works perfectly.
> I printed the image when it turned "7", just to see if it really got through, the rest are simple actions to change the loading screen and it also worked...

<img src="https://github.com/FlutterFlow/flutterflow-issues/assets/160440373/50b4f14e-ed91-47d7-8815-762343e136cf" width="350">


=========================
### **### In the end...** — It's not a problem inside Test Mode or Run Mode, it's a general problem...

**Comment by apppbuilder** [comment] 2024-05-21 02:48
@ignalauret any point on this issue?

**Comment by Alezanello** [comment] 2024-07-04 15:00
Hello,

I apologize for the delayed response. First of all, have any of the recent FlutterFlow updates resolved your issue?

If not, I suggest trying to use a Custom Action instead of a Custom Function. Custom Functions might not access the `cloud_firestore` package correctly, but you can call the package properly and access the document info in a Custom Action.

Please let me know if this helps or if you need further assistance.

Best regards,<br>Azanello

**Comment by apppbuilder** [comment] 2024-07-04 15:17
Hey @Alezanello , thank you for showing up.

To be very honest, it's extremely frustrating to have a real problem within the application that prevents it from working correctly, and when talking with the support, turns out that I'm thrown aside like if it doesnt matter, and still seeing a lot of things being released as new in the platform.

FF lacks in supporting apps in the late stage of development inside the platform... all the bug reports I made here was found in the late stage of building an app, not in the early stage...

I'm not blaming you directly, but look at this, my problem was fully shown in May 15. Its July 04... So my project would be paused until now because of a bug?

=======

Now, about this issue. I solved it myself by giving the Cloud Function another step to populate a new field inside the userReference.

Instead of giving to FF App the whole list of datatypes, now only the documentReference is being passed as a list and in this case it's working good.

Can't tell you if the issue persists, and to be honest, I'll not even try to check because I already found a way to get out of the problem and there's lots of other tasks to go on with the project. But it's frustrating to pay a platform and receive this kind of treatment.

Again, thanks for showing up.

**Comment by Alezanello** [comment] 2024-07-04 15:27
Hello @apppbuilder 

Thank you for your feedback and for sharing your experience. I apologize for the frustration you’ve encountered. We are actively working on improving our response to issues and support for applications in the late stages of development.

I’m truly sorry for the delay in addressing your specific concern. We understand the importance of timely support, and we are committed to making improvements in this area.

I’m glad to hear you were able to find a workaround by giving the Cloud Function another step to populate a new field inside the userReference. It’s helpful to know that passing the documentReference as a list worked well for you.

Your feedback is invaluable, and we are taking it seriously to enhance our support and ensure such delays do not happen in the future. Please do not hesitate to reach out if you have any further concerns or need additional assistance.

Thank you again for your patience and understanding.

Best regards,
Azanello

**Closed** 2024-07-08 20:29 UTC
Labels: waiting for user response, Triage in progress
