### ISSUE TITLE
Lib component used as a widget builder parameter cannot be validated within a form validation.

### ISSUE THREAD

**Issue by nev-21** [FlutterFlow/flutterflow-issues#4075] opened 2024-10-16 23:43 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When a lib component is used as a widget builder parameter, and it has a textField widget; it can't be validated in consuming project form validation.

### Expected Behavior

When a lib component with textfield is used as widget builder param, that textfield should appear in form validation in consuming project.

### Steps to Reproduce

1. create a lib
2. create a component X with a text field "mytextfield"
3. create a component Y with a widget builder param "ywidget" and put it in widget tree
4. create a component Z, add Y and set X to "ywidget"
5. publish the lib
6. create a project, import the lib
7. add a form validation to home page
8. add component Z to form validation, you will not see "mytextfield" in the validation section

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48zMrl25F2rtxE0JD+au9ajikXQ2U7a5JNle1Dd0s8J5DaPOxzP/TBaldWUs+0d2NHMWf8oHgdw6DemvH9Je4nEwqbf7pdyZdcaQ3iWkijbL7TCqiKOm5/AtxTI1Sg18GRgyVCVfBvLHtg6jiAJfK/Sg7XGYzUCzM/B86LKZCK2SrDX1iXc2URm05KZDPz

### Visual documentation

https://github.com/user-attachments/assets/1c5291e1-3928-4273-93bf-347cc80d36c6

### Environment

```markdown
- FlutterFlow version: 5.0.6+
- Platform: web
- Browser name and version: chrome 129.0.6668.90 
- Operating system and version affected: win 11
```

### Additional Information

Project bug report code:
IT48zMrl25F2rtxE0JD+au9ajikXQ2U7a5JNle1Dd0s8J5DaPOxzP/TBaldWUs+0d2NHMWf8oHgdw6DemvH9Je4nEwqbf7pdyZdcaQ3iWkijbL7TCqiKOm5/AtxTI1Sg18GRgyVCVfBvLHtg6jiAJfK/Sg7XGYzUCzM/B86LKZCK2SrDX1iXc2URm05KZDPz

Library bug report code:
IT4wzMrl25F2rtxE0JD+au9VtCAsGDt5U5Evl+pHRis8JJToPLAUZ8zBM05vZry5Y29tfFmZrHwJxvfqktnPKfICGxObQLo7/7lucwvyQmGRVqagDZeBfW1TN+hnIXK+5J6vnSUnGNJedXxn7UyPe+6vTi7AH4CxDG0ZQ+alLdeK2SrDX1iXc2URm05KZDPz

**Comment by Alezanello** [comment] 2024-10-18 12:24
Hello Nev!!<br><br>I think is related to this issue also: [https://github.com/FlutterFlow/flutterflow-issues/issues/3976](https://github.com/FlutterFlow/flutterflow-issues/issues/3976)<br><br>In this case it will be fixed in the next production release!

**Comment by nev-21** [comment] 2024-10-22 20:58
Hi @Alezanello, #3976 was fixed but I also cheked these issues #4075 and #4074 is still happening.

**Comment by nev-21** [comment] 2024-10-30 23:30
Hello @Alezanello Wondering if there are any updates on the issue, thanks for all your work!

**Comment by Alezanello** [comment] 2024-11-01 19:41
Hello again, Nev! I apologize for the delayed response on these issues.

This particular issue relates to handling the component state within a library, whether created through the Widget Builder or not. It’s actually a duplicate of the following issues:

* [Issue #4074](https://github.com/FlutterFlow/flutterflow-issues/issues/4074)
* [Issue #4064](https://github.com/FlutterFlow/flutterflow-issues/issues/4064)

Once those two are resolved, this issue should also be addressed, so I’ll close it as a duplicate. If it persists after those fixes, please feel free to ping me here, and we’ll reopen it.

Thank you!

**Closed as not planned by Alezanello** 2024-11-01 19:41 UTC
Labels: closed: duplicate
