### ISSUE TITLE
Unable to set App State Variable with data type Document Reference

### ISSUE THREAD

**Issue by theunisdk** [FlutterFlow/flutterflow-issues#3312] opened 2024-07-04 07:01 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When adding an App State variable to a project. When you select Data Type "Document Reference" the create button is disabled for validation, but never activates again regardless of what information you put in. 

### Expected Behavior

When creating an App State Variable, you should be able to specify a name, specify Data Type "Document Reference" and select the reference type and click create.

### Steps to Reproduce

1. Create a new blank project. 
2. Create blank home page.
3. Click start building
4. Create a collection call stats from the firestore tab.
5. Create a field in stats collection called created, DateTime
6. Create a sub collection of stats called opens
7. Create a field in opens collection called created, DateTime.
8. Go to the App Values tab and click "Add App State Variable"
9. Set Name=Var1, Data Type=String and click create. Confirm that worked.
10. Click "Add App State Variable" again. 
11. Set Name=OpensRef, Data Type=Document Reference, Reference Type=Opens. 
12. Note that no matter what options you change, the create button never activates.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48l8j6y4VIscsA7q6JcsEwgikvJlM7apEs0Op9axc8J5zKB+wAYvf7P1FWTLzgY2xpe06ZmmIexvfqvtr9DfIDCzmdfbo7wc5uFBbyRkmgVpipParofW1TL59XIUy00qSNvR1NNu1oWl5g7Dn7Pd+tQnPaGb7uO20dQ+SLKdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

Video : https://www.loom.com/share/d6c1555542964f66a0b14e5e7173f5e4?sid=ae103f2d-8a7e-4262-b265-22910faea114

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/3517286/2054e7fa-684e-4863-89c3-4233b3d35a33)

You can see here that it used to work. 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/3517286/f90617ca-08cc-4a96-a0d6-9dffc5aab0a9)

### Environment

```markdown
- FlutterFlow version: 4.1.65
- Platform: Web and Windows Desktop
- Browser name and version: Chrome 126
- Operating system and version affected: Windows 10
```

**Comment by Alezanello** [comment] 2024-07-04 11:26
Hello!!,

Thank you for bringing this to our attention!

This is a known issue, and our engineering team is already working on a fix.

I'm closing this thread since it's a duplicate of an existing issue in our backlog.

The fix should be deployed to production soon.

Best regards,

Azanello

**Closed as not planned** 2024-07-04 11:26 UTC
Labels: closed: duplicate

**Comment by leighajarett** [comment] 2024-07-04 14:09
We have fixed this issue and the fix should be live in the next product release (like Tuesday morning EST)
