### ISSUE TITLE
File Upload not working 

### ISSUE THREAD

**Issue by ISHA7782** [FlutterFlow/flutterflow-issues#549] opened 2023-02-28 06:28 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.

### Current Behavior

File upload is not working to custom server. Files are considered as non-file params. 

### Expected Behavior

Files should be sent as file type as part of mutipart upload. 

### Steps To Reproduce

1. Create a ui widget 
2. Upload any media 
3. Send a media to any server using api call. 
4. Track the api call at server. The files params are sent as empty. 

### Bug Report Code

ITEek/H15c9NtbxI+qn2bsFFmQMwGkQ5a7sviu5+FBQaI+KvEYouf8zCYRZWcuqHY2xYIlWWgkEH/96LjuHLEsEFEEycR7U4/5FtH1yjEA8=

### Context

Blocker for release 

### Additional info

We have tried debugging the issue, the culprit seems to be this condition 

`    bool Function(dynamic) _isFile = (e) =>
        e is FFUploadedFile ||
        e is List<FFUploadedFile> ||
        (e is List && e.firstOrNull is FFUploadedFile);`

The files are considered as normal param. Same thing works from postman, 

<img width="747" alt="Screen Shot 2023-02-27 at 10 21 29 PM" src="https://user-images.githubusercontent.com/17334006/221771850-80a54721-f5f8-4f45-86fb-188e05222816.png">
<img width="1039" alt="Screen Shot 2023-02-27 at 10 21 37 PM" src="https://user-images.githubusercontent.com/17334006/221771857-8fa616a6-4f3f-4f46-abb0-80d9bb50bf1e.png">

### Environment

```markdown
- FlutterFlow version: 3.7.3
- Platform (e.g. Web, MacOS Desktop): MAC Version 12.5
- Browser name and version: CHROME Version 108.0.5359.124 (Official Build) (arm64)
- Operating system and version (desktop or mobile): desktop
```

**Comment by padeepz** [comment] 2023-02-28 06:37
yes same issue - in my project the uploads are working. and as soon as i pushed the latest build from the updated FF, and the file uploads are stopped working. 
so i believe the latest update of FF broke this

**Comment by hariprasadms** [comment] 2023-02-28 13:55
Hi @ISHA7782 - Thanks for reporting the issue. I can re-produce the issue. Below is the video showing uploaded file as null in a snack-bar ( Video is editor to remove local files display for security reason).

https://user-images.githubusercontent.com/17435678/221874633-01978d06-d610-45d6-99b0-e64d7effe77e.mp4

**Comment by agreaves** [comment] 2023-02-28 23:26
Hi @ISHA7782, thanks for the bug report and apologies for the inconvenience. This should be fixed now! Please let me know if you see any issues with it on your end. I'll keep this issue active for a day until you or others are able to confirm.

**Comment by ISHA7782** [comment] 2023-03-01 04:33
@agreaves  We are able to upload the files to the server, but files are getting corrupted. Have you verified that uploaded files as part of testing. 

Postman , same api works for us, but not with flutterflow.

**Comment by ISHA7782** [comment] 2023-03-01 04:35
<img width="260" alt="Screen Shot 2023-02-28 at 8 17 35 PM" src="https://user-images.githubusercontent.com/17334006/222045663-382f5fbb-11e5-4025-b5f0-3f077f8bcd2f.png">

**Comment by Shouri** [comment] 2023-03-01 10:41
Team - everytime we are trying to proceed further we are hitting a new roadblock. Request you to take it up on priority and resolve this asap.

**Comment by ISHA7782** [comment] 2023-03-03 05:52
Hi team, Can we please check on this.

**Comment by agreaves** [comment] 2023-03-06 22:12
Hi @ISHA7782 and @Shouri, I've been trying to reproduce the issue here but in all the APIs I've tested, everything seems to be working for uploading images. Now that we are no longer blocking the image parameter, everything is as it was before, so my initial question is - was this ever working for you in your project? From what I can see, the answer is most likely not but if so I can recreate a Run mode using the old version for comparison.

In the meantime, would it be possible for me to access the upload API you are using in order to test and help debug? As I said, I haven't been able to recreate the issue myself, so I'd likely only be able to debug the issue by using the API you are having issues with.

**Comment by agreaves** [comment] 2023-03-06 23:26
I believe I have found the cause of the issue, it appears that the MediaType is required by some APIs and is currently not being set. This should be fixed in the next deploy, but again because I can't access your API I'm not sure if this is the cause of the issue you're experiencing. I can build a Run mode link with the changes for you to test if you'd like.

**Comment by agreaves** [comment] 2023-03-07 01:33
Thanks @Shouri! I just need a bug report code from your project and I'll generate a Run Mode link using the updated code. Once created, it will appear as the top option in your Run Mode menu for you to test (as seen below).

![image](https://user-images.githubusercontent.com/7757399/223296214-2f16cad3-e067-4e0a-80e9-5116a62c6dae.png)

**Comment by Shouri** [comment] 2023-03-07 05:31
https://app.flutterflow.io/run/2uLLjke2gUhQV6Kpaq2P - please let me know if you need any other details.

**Comment by ISHA7782** [comment] 2023-03-07 06:10
ITEek/H15c9NtbxI+qn2bsFFmQMwGkQ5a7sviu5+FBQaI+KvEYouf8zCYRZWcuqHYG52elH+hk8F/9GKivLXNcBdBz6bbbpJ+qoAUxDgc3ygbL7SPKqOfmt5EfFmJkilyru7qiR/NrR2WWRh3TuqIOSAb3qCf9qOYwx5e6fDbOY=

**Comment by ISHA7782** [comment] 2023-03-07 06:11
@agreaves - We are able to upload the file to S3, but the s3 file is corrupted.

**Comment by agreaves** [comment] 2023-03-07 09:18
@ISHA7782 and @Shouri You should now see a Run mode link in the menu with the latest version. Please let me know if this works! If this doesn't work, please try adding a Header to the API call with `Content-Type: image/jpeg`, as this could also potentially fix the issue.

**Comment by ISHA7782** [comment] 2023-03-08 05:30
@agreaves - Still facing the same issue. Even providing the content-Type does not work. 

Is it possible to schedule a call for debugging ? We are impacted on file upload part since 17th Feb, first with https://github.com/FlutterFlow/flutterflow-issues/issues/503 , and then with this one.

**Comment by agreaves** [comment] 2023-03-08 07:11
Unfortunately we do not offer calls for debugging. As I've mentioned, this seems to be working for some other projects and on the APIs I've tested, so you may have to locally debug the issue by running Flutter locally. Are you testing via Run/Test mode or via some other method?

If you're testing only via Run/Test mode, consider turning off the setting **API Config -> Advanced Settings -> Use Proxy for Run/Test mode**. It's possible the upload is failing due to the use of the proxy.

**Comment by Shouri** [comment] 2023-03-08 08:11
We debugged even with the flutter code and can clearly see that flutterflow is not setting the right content type and instead just passing application/octet-stream. In the working projects, are you hitting backend REST end point using multipart upload? Is it possible to provide a sample app so that we can see mimicking the calls. 

We are facing issues with Video - in case of video its not uploading at all (for images at least we are getting a corrupted file). Dont know whats the best way. Request you to unblock us as we already developed 20 page app in FF.

**Comment by agreaves** [comment] 2023-03-08 18:50
Hi, here is an example project: https://app.flutterflow.io/project/upload-image-test-ji5slp. We're not doing anything particularly special outside of the box.

Note that we're not using Amazon S3, so there may be differences in the upload process that could be causing issues. Please once again try turning off **Use Proxy for Run/Test mode** if testing this way.

In addition, if you are debugging locally, please add `contentType: MediaType('image', 'jpeg'),` inside of the `http.MultipartFile.fromBytes(...)` function in `api_manager.dart`. We have made this change (and I used it to generate the earlier Run mode link) but it is not deployed yet.

**Comment by Shouri** [comment] 2023-03-09 05:35
- Sample project is not clean. Please check once. No action configured for "upload".  
- Disabled proxy but still the same issue. 
- Asking the end user to settle  the content type is not right, as we can upload images in PNG and JPEG and any other format. 

Other person reported the issue - https://github.com/FlutterFlow/flutterflow-issues/issues/273#issuecomment-1368090072. This needs thorough investigation.

**Comment by Shouri** [comment] 2023-03-09 07:44
Configuration on AWS API Gateway has resolved the issue. We are good here. 
Thanks a ton @agreaves @organicnz for all help here.

**Comment by agreaves** [comment] 2023-03-09 18:41
Awesome! Glad it's working for you now 😀

**Closed by agreaves** 2023-03-09 18:41 UTC
Labels: type: bug, status: confirmed
