### ISSUE TITLE
"Exclude current user" toggle in query collection does not work

### ISSUE THREAD

**Issue by infinixbolt** [FlutterFlow/flutterflow-issues#570] opened 2023-03-04 10:17 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.

### Current Behavior

![xCurrentUser](https://user-images.githubusercontent.com/55094860/222893552-d64479ac-38b9-4da8-91fc-303009288efe.jpg)
This toggle is supposed to exclude current user from the list of queried result but it does not.

### Expected Behavior

when the toggle is on, the current user is supposed to be excluded from the list of users.

### Steps To Reproduce

1. add a column widget
2. click on it and select backend query
3. select "query collection" as query type
4. add collection and select "list of documents" as query type
5. scroll down and toggle on "exclude current user".
6. then run the app

### Bug Report Code

IT4glsn15YVIschE7aX6bu9anmMXQ318bb00st4bGAsdGOvrBuwPO+CkN0xBOOriaVNcPmCimXEdpvzeid71Ce4pBxWufr5g+c5QZA/ke2imVLWaEpOSfWh8I9lXG2qX4buzkyUlNvpsWEYe3GGmJ+u9cArDFOu/Zwh9f6PHaOI=

### Context

i am trying to exclude the current logged in user from the list of documents in the users collection

### Environment

```markdown
- FlutterFlow version: v3.1 (released March 2, 2023)
- Platform: Web
- Browser name and version: Chrome Version 110.0.5481.96
- Operating system and version affected: Windows 11
```

**Comment by victoriahuang1** [comment] 2023-03-07 21:10
Hi @infinixbolt thanks for the report. I could not reproduce the issue with my own setup / data. Also took a look at your generated code, and it looks correct as in I see the code to exclude the current user.

When you say that the exclude filter doesn't work, what are you seeing? Is it possible that there is duplicate data in your database?

**Comment by infinixbolt** [comment] 2023-03-08 14:19
> Hi @infinixbolt thanks for the report. I could not reproduce the issue with my own setup / data. Also took a look at your generated code, and it looks correct as in I see the code to exclude the current user.
> 
> When you say that the exclude filter doesn't work, what are you seeing? Is it possible that there is duplicate data in your database?

when i say the exclude filter does not work, i still see the current user logged in after running the app

**Comment by victoriahuang1** [comment] 2023-03-08 16:31
> when i say the exclude filter does not work, i still see the current user logged in after running the app

Do you see the user's name? Or have you verified that it is the same uid?

**Comment by victoriahuang1** [comment] 2023-04-04 23:56
Closing due to inability to reproduce. Feel free to reopen if there is new information to help reproduce the issue.

**Closed by victoriahuang1** 2023-04-04 23:56 UTC
Labels: type: bug, status: can't reproduce
