### ISSUE TITLE
getDocumentFromData isn't defined for UserRecord

### ISSUE THREAD

**Issue by morad** [FlutterFlow/flutterflow-issues#577] opened 2023-03-05 08:29 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Flutterflow compiler is stating there is an error: The method 'getDocumentFromData' isn't defined for the type 'UserRecord'.
Which is not true, and it works on my local machine when I export the code. or on Autocomplete on Flutterflow editor.

### Expected Behavior

getDocumentFromData is defined, and no error should pop up.

### Steps To Reproduce

1. Create new Action
2. And use the following code:
Future<UsersRecord?> fetchUserDocByRef(DocumentReference? userDocID) async {
  // fetch from Users collection in firestore by userDocID and return the document
  if (userDocID == null) {
    return null;
  }
  final DocumentSnapshot doc = await userDocID.get();
  if (doc.exists) {
    return UsersRecord.getDocumentFromData(
        doc.data() as Map<String, dynamic>, doc.reference);
  }
  return null;
}

### Bug Report Code

Stack(   alignment: AlignmentDirectional(0, 0),   children: [     Transform.rotate(       angle: -0.7854,       child: Padding(         padding: EdgeInsetsDirectional.fromSTEB(5, 0, 0, 0),         child: Icon(           Icons.send_rounded,           color: Colors.white,           size: 24,         ),       ),     ).animateOnActionTrigger(       animationsMap['transformOnActionTriggerAnimation']!,     ),     Icon(       Icons.close_rounded,       color: Colors.white,       size: 24,     ).animateOnActionTrigger(       animationsMap['iconOnActionTriggerAnimation']!,     ),   ], )

### Context

Trying to compile, but won't work.

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web, Mac OS
- Browser name and version: Chrome
- Operating system and version affected:  MacOS Monterey
```

**Comment by hariprasadms** [comment] 2023-03-06 13:09
Hi @Pepino-GR - Please look at this issue. Thanks

**Comment by hariprasadms** [comment] 2023-03-07 11:11
This issue is not a bug. There is a way to achieve expected results in FF editor. Hence closing the issue.

**Closed by hariprasadms** 2023-03-07 11:11 UTC
Labels: closed: not a bug

**Comment by morad** [comment] 2023-03-09 06:22
Hey, 

I am using this in custom action, where it will get triggered when a user select a "friend" from a checkboxListTile. The action will retrieve the "Friend" User doc and pass it to chatPage widget which requires User Doc param.

![Screenshot 2023-03-09 at 9 17 17 AM](https://user-images.githubusercontent.com/66266/223937042-85ca575f-e218-46dc-8449-5fd7646575c7.png)

![Screenshot 2023-03-09 at 9 20 20 AM](https://user-images.githubusercontent.com/66266/223937192-32d7ea6b-2ca5-4e32-a410-7d4ad22c9c4d.png)

Nonetheless, I am able to compile this on my local IDE but for some reason the FF Editor sees it as an error.
