### ISSUE TITLE
Test Function in custom function broken

### ISSUE THREAD

**Issue by mattholdsme** [FlutterFlow/flutterflow-issues#1680] opened 2023-10-20 22:33 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When you run a test on the function to do manual inputs, we get an error stating it is something to do with firestore. After looking into this, it could be related to Firestore package being updated 48 hours ago. 

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/10339007/0fc08676-87bc-43df-93cb-1c33d3325ec0)

### Expected Behavior

The output of the above image should return 501 instead of an error

### Steps to Reproduce

1. create a new simple function with any type of input and make it have a return value
2. Run the function in test mode and click run after you enter your values manually

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Compiling with sound null safety lib/main.dart:1047:42: Error: Undefined name 'FieldValue'. currentUserReference?.update({'coins':FieldValue.increment(coinAmount)}

### Context

I am unable to test any new function so I am having to publish every time. I have not yet investigated if this is causing issues on my current builds yet after publishing.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/10339007/22cd8e49-bbb2-4a15-a354-d2b0ff40ea6a)

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: FlutterFlow
- Browser name and version: Chrome and edge
- Operating system and version affected: Windows 10
```

**Comment by wenkaifan0720** [comment] 2023-10-20 23:36
Hi @mattholdsme. Could you provide a bug report code? I tested with this project but can't reproduce the issue: https://app.flutterflow.io/project/flutterflow-issue-1680-ms97cy.

**Comment by wenkaifan0720** [comment] 2023-11-03 06:10
Hi, this should be fixed in our next update. Thanks.

**Closed by wenkaifan0720** 2023-11-03 06:10 UTC
Labels: closed: feature / enhancement request, type: feature / enhancement request
