### ISSUE TITLE
Passing data type from custom action fails compile

### ISSUE THREAD

**Issue by 978bobs** [FlutterFlow/flutterflow-issues#899] opened 2023-05-19 11:11 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

This was not present a week ago or so.  I have projects that worked and exported to github one example is from May 9, 2023.
[query_user_list_action.zip](https://github.com/FlutterFlow/flutterflow-issues/files/11516054/query_user_list_action.zip)

The result is the following error statement:  Custom Actions:  Unknown error compiling custom code. A common cause is a custom widget or action whose name in the code does not match the name provided in the editor.

Not sure if this is related to #621 but I believe not, based on the timeline.

### Expected Behavior

I expect to be able to use createUserMasterStruct() and pass a simple map from a custom action back as a Data Type as a List.  This would then update a local page state variable.  In this use-case I would then be able to generate a list view.

As additional background I am trying to make a Hive database.  The above mentioned project was working with SQFLITE and worked fine.  The code in question returns a <List<MasterDataStruct>> which is then used to show a listview in the UI. 

### Steps to Reproduce

1. starting from new project
2. create a data type userMaster where three fields are all of type String named userName, email, title.
3. Create custom action
4. no need to return, but this bug also occurs when trying to return the data type as well.
5. within the custom action code use createUserMasterStruct :  such as   var simplesend = createUserMasterStruct(
      userName: "defaultUser",
      email: "default@email.com",
      title: "defaultTitle");
 

6. print anything to console
print("hello world");
8. compile code

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Chcjl04xNrt9c+r6JKsJV+TsXQm41RY0kmMJ+SQsaN5PMC+wIZ/f7XFRuTde0S29Pe2Kkqzod+tXemvLlA/A4Gwydc5xq+pdQdT3KLXKmSraaCLiWeG5/DdJTGHbH1567pQhBIshsW14M2GWAGe6vEzftJK7bPm0dNP2hJZKK2SrDX1iXc2URm05KZDPz

### Context

I am trying to create a windows desktop application only - no Firestore no Supabase.  The application is designed and right now I'm trying to prove out the use of local database.  I had succeeded in making SQFLITE work.  It now fails due to this issue.  I am in the middle of trying to do the same with HIVE which is where I've been banging my head against a wall all week long.  This has led me to this issue and has stopped all activity on this project.  

This issue has affected me by stopping a commercial project in its tracks.  

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/15112106/5700e739-085a-4960-8dc5-563c70ca89b4)

### Environment

```markdown
- FlutterFlow version: 3.1 released May 18, 20223
- Platform: Windows and Web
- Browser name and version: Chrome Version 113.0.5672.93 (Official Build) (64-bit)
- Operating system and version affected: Windows 11 Pro version: 22H2 osbild: 22621.1702 Experience: Windows Feature Experience Pack 1000.22641.1000.0 on a Dell Optiplex 7460 AIO
```

**Comment by 978bobs** [comment] 2023-05-19 16:55
by the way doesn't matter if I 'exclude from compilation' for the custom action. same result.

**Comment by hariprasadms** [comment] 2023-05-21 08:36
Hi @978bobs - Thanks for submitting the issue. I have tested the above steps in a test project. It seems to be working fine and also data can print in the browser console.  Below is the action code, Is this looks same as you. 

<img width="617" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/bdc731cb-4e62-4368-956e-944b523f4215">

If you still experiencing the issue, can you setup a blank project with custom action code and share the project code please? 
If you there is no error any more. You can close the issue.

Thanks

**Comment by 978bobs** [comment] 2023-05-22 11:19
OK, I tried the code you presented in the screen shot and still get error.  Bug report and screen capture are presented.  You know it would be funny if you could point me to the documentation on proper use of structs in custom actions too please.  I can't find it.  So maybe I'm just flying blind?

I did notice that your default automatic flutterflow imports are different from mine.  I don't have the import '/backend/backend.dart'; line.  fyi

![Screenshot 5-22-2023 at 07 05 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/15112106/556f8a53-1ae6-48bd-bc55-3b664bcfe122)

BUGREPORT FOLLOWS: 

ITFXlsn1z4pNxeZE+s/xLcAwlWIwGUwbUOc7j9VEGAsjCePrP7MMZuPBN1NuYuqHeHxmI2ekjmEzw93GuOL2UfoDGEiYQL5+ybpXUxDvXkmmSqqlBZarOWgnGfJPIUCh5rW3oxN4APpZWXwX706IGN6uY3qCf9qOYwx5e6fDbOY=

**Comment by 978bobs** [comment] 2023-05-22 11:36
After a little more digging it seems that the import '/backend/backend.dart' is inserted when the application includes firestore.  Somehow I wonder if the new release (which removes the firestore requirement from data-types) somehow missed when an application gets created without firestore dependencies?

**Comment by 978bobs** [comment] 2023-05-22 11:54
Just viewed this other bug report. They are getting the same error I am getting. I wonder if these two are related?
They are trying to use Supabase and custom code.

https://github.com/FlutterFlow/flutterflow-issues/issues/906

**Comment by ggabrovski** [comment] 2023-05-22 14:11
Hi @978bobs, 
you can copy the imports form the boilerplate action code:

<img width="1376" alt="Screenshot 2023-05-22 at 16 59 27" src="https://github.com/FlutterFlow/flutterflow-issues/assets/24413349/787e90d7-7abb-4ab6-9349-b669b7d051fc">

I make the quick test and its working:

<img width="918" alt="Screenshot 2023-05-22 at 17 10 35" src="https://github.com/FlutterFlow/flutterflow-issues/assets/24413349/0886841b-b1e9-4878-bf29-38bf627dcabb">

Hope this will help you

**Comment by 978bobs** [comment] 2023-05-22 14:26
So if I'm using the same code as you and flutterflow is not compiling, how am I supposed to get to test?  

I am attaching the copy of the boilerplate code. It is not the same boilerplate that you have.  

Tell me something, when you start with a blank application, do you "Setup Firebase" or do you disable?  So if data types are not dependent on Firebase anymore why would you?  

By the way, it is unclear what your second image with the red arrow is supposed to indicate.  So no, it has not yet helped me.

Do let me know if th images I attached came through?

Thanks,
Bob
![Screenshot 5-22-2023 at 10 19 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/15112106/0be9b019-f7cf-4c05-a3e0-fa3a8410e194)
![Screenshot 5-22-2023 at 10 23 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/15112106/715f0021-2fc6-4d71-a056-f3e33a1f050c)

**Comment by ggabrovski** [comment] 2023-05-22 16:05
Hi @978bobs,
yes previously I have project with Firebase and it work. Now I have made second test without Firebase and debug icon show the error, but the project run successfully and I can see print in the browser console. As you can see below:

<img width="1383" alt="Screenshot 2023-05-22 at 18 57 10" src="https://github.com/FlutterFlow/flutterflow-issues/assets/24413349/b918ee8b-3675-4b3c-b476-3cf810453708">

<img width="1440" alt="Screenshot 2023-05-22 at 18 57 27" src="https://github.com/FlutterFlow/flutterflow-issues/assets/24413349/5b557a99-7fd3-427d-b01d-af43e4d9ea11">

I think this is bug and someone need to fix it.

**Comment by 978bobs** [comment] 2023-05-22 18:32
I was confused how you got the test to run.  I had to do the following to get the print to console like you did.
1) create and empty app with default blank page.
2) run build and get the test page in debug mode
3) leave running in debug.
4) create the custom action.  go to main and choose custom action for initial actions.
5) compile it and get the failed bug
6) return to the open debug tab and hit instant reload
7) inspect that page and find that yes the print to console had indeed worked.

Now for the bad news.  If I later close the debut window or let it expire, I cannot get back to see the debug view.  Why? because the bug failed message is blocking everything.  "Unknown error compiling custom code. A common cause is a custom widget or action whose name in the code does not match the name provided in the editor."


![failed_run](https://github.com/FlutterFlow/flutterflow-issues/assets/15112106/7e47d15d-1b0d-4169-843a-1ad19b82a45c)
![rantest](https://github.com/FlutterFlow/flutterflow-issues/assets/15112106/59549c24-af7c-4ffd-ae8b-90bc4ad8ef78)

**Comment by 978bobs** [comment] 2023-05-23 12:03
I have provided additional information, would love to hear the rationale for this being classified as 'not a bug'?

> If you still experiencing the issue, can you setup a blank project with custom action code and share the project bug report code please? If you there is no error any more. You can close the issue.
> 
> Thanks

**Comment by 978bobs** [comment] 2023-05-25 14:44
ok, I give up, but I will not close this topic.

**Comment by TizianoVecellio** [comment] 2023-05-26 21:42
I have the same issue. No custom code will compile no matter what I do. Not marketplace widgets, not even an empty boilerplate. Always an error. When I click "compile" the button flashes to red "unknown error".

**Comment by EmersonFJ** [comment] 2023-05-26 23:26
I have the same issue - I am not using Firebase and if I create a Custom Data type, all the sudden my custom widgets and custom actions do not compile / have an error as shown above; this appears to be a material bug prevent users who do not use Firebase from using the new Custom Data Type; I cannot find a work around at all

**Comment by EmersonFJ** [comment] 2023-05-26 23:28
> ok, I give up, but I will not close this topic.

Don’t give up and don’t close it; this is an issue for many people; see the FF community site; annoyingly, this is happening during a long weekend, which is best building time for those of us still with day jobs….

**Comment by idea-garage** [comment] 2023-05-27 05:23
I reported same issue below, and be said it may be bug but cannot reproduce at support side.
https://github.com/FlutterFlow/flutterflow-issues/issues/931

Creation NEW project and detect specific situation which causing error, then it would be helpful for support side.

**Comment by EmersonFJ** [comment] 2023-05-27 11:28
> I reported same issue below, and be said it may be bug but cannot reproduce at support side. #931
> 
> Creation NEW project and detect specific situation which causing error, then it would be helpful for support side.

See here for how to recreate one version of this problem ; note Firebase is not enabled; a custom data type and a custom action that is unrelated to the custom data type is all you need to create the error; in this video it shows tying the custom data into app state, for many others that have shared this that step isn’t always required;  : https://sos-videos.zefranck.com/gK2CqKxWCYZZ2z3G2gMQ

**Comment by 978bobs** [comment] 2023-05-27 20:59
I just went back and redid this to confirm for my own sanity.  If you build your app without firebase and then try to use data-type in the action it fails. If you build that same app with firebase it works.  To me the seeming only difference is in how the boilerplate is constructed in the custom action.  In the app with firebase you get this line:  import '/backend/backend.dart';  in the app without firebase this line is missing.

**Comment by EmersonFJ** [comment] 2023-05-27 22:04
> I just went back and redid this to confirm for my own sanity. If you build your app without firebase and then try to use data-type in the action it fails. If you build that same app with firebase it works. To me the seeming only difference is in how the boilerplate is constructed in the custom action. In the app with firebase you get this line: import '/backend/backend.dart'; in the app without firebase this line is missing.

Did you by chance (sorry away from computer for a day) see if you could build without firebase, have it fail, then connect Firebase and have it work? Or do you need to build with Firebase from the start?

**Comment by EmersonFJ** [comment] 2023-05-27 22:05
I see @agreaves is on the case - thank you Alex!

**Comment by agreaves** [comment] 2023-05-27 22:43
Hi @EmersonFJ, on the case indeed! Although it turns out @aemelyanovff has already fixed this one 😊. This should be fixed for everyone on our next deploy! Your analysis is correct that this issue occurs for projects that use Data Types but not Firestore, sorry about that! We'll likely hotfix this one relatively soon.

**Closed by agreaves** 2023-05-27 22:43 UTC
Labels: status: needs triage

**Comment by EmersonFJ** [comment] 2023-05-28 00:46
> Hi @EmersonFJ, on the case indeed! Although it turns out @aemelyanovff has already fixed this one 😊. This should be fixed for everyone on our next deploy! Your analysis is correct that this issue occurs for projects that use Data Types but not Firestore, sorry about that! We'll likely hotfix this one relatively soon.

Well sounds like @aemelyanovff is a rockstar then!
