### ISSUE TITLE
Clickable area isn't consistent

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#1966] opened 2023-12-06 00:35 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Clickable area isn't consistent

### Expected Behavior

When a user click in the row should be clickable

### Steps to Reproduce

1. Create a row
2. Add some widgets there
3. To the row add a custom dialog
4. Now the clickable area of the row isn't consistent

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40z/Lqx89Jpbxa1s+NKcBv9SM5KWF9bbsrm+17aDUsIuOtBqQLPPfeVFpuTbCjaVNceU2ZuGQfw/yMhYftMcI5AxSqfZxH/qh+ajr0e2iuSq7REoeSZmsnBexTfEia55+42BQkOtZ1Wmw42WGILu+XRXTDBOu/Zwh9f6PHaOI=

### Context

I want to show a dropdown account when the use click in the row

### Visual documentation

https://www.loom.com/share/3baea8e920ed4222a615c6d4b3de4158?sid=65b39a08-e603-4de3-a9a0-aef537d94693

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.O released December 1, 2023 - Flutter version is 3.13.7
- Platform: Web
- Browser name and version: Chrome Version 119.0.6045.161 (Official Build) (64-bit)
- Operating system and version affected: W11 23H2
```

**Comment by paulVu** [comment] 2023-12-13 02:22
I have the same issue in this week. Sometime all the button can't click in `run`.

**Comment by Franco98404** [comment] 2023-12-17 09:52
Let's hope that FF fixes it soon because the bug is very annoying

**Comment by hariprasadms** [comment] 2024-02-12 12:12
Hi, Thanks for raising the issue. As it doesn't appear to be widespread and lacks a blank project with reproducible steps, it may have been overlooked. Considering its age, it's possible it has been addressed in recent FlutterFlow updates. Therefore, the issue is being closed. However, if you believe the problem persists, please reopen the issue by providing a blank project with the reproduced issue and share the project bug report code. This will facilitate a thorough investigation and prompt resolution. Thank you.

**Closed** 2024-02-12 12:13 UTC
Labels: status: can't reproduce, needs a blank project with issue setup
