### ISSUE TITLE
Calendar swipe

### ISSUE THREAD

**Issue by blondie63** [FlutterFlow/flutterflow-issues#912] opened 2023-05-22 11:01 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Left & Right swipe DOES'NT works !!

### Expected Behavior

logically... have to works !!

### Steps to Reproduce

Create a page with a Calendar widget
run app and try to swipe left & right

Tested on web, iOS , Android

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wlsmAsI1Nobhe+KqJb/pvoCMvIjo2aJ0rk8IbGSs8GpT2PJkQevfRQFtUcMDmYAhIemD9oDgX/MqPvYbqUO4pAE6tUYh8waViSg7wWkihVanXPa63b39tHdFbGGq94baVkQhSJrdfSCAtw2abNeqWYAnfJ7qxOUg7HuaoXdeK2SrDX1iXc2URm05KZDPz

### Context

It's normally that user try to swipe!!!

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/1261851/8c996e41-5da8-4b7f-a73a-726e80154cd9

### Additional Info

I've documented this issue on your community 
https://community.flutterflow.io/c/discuss-and-get-help/calendar
and also sent from FF Ui

### Environment

```markdown
- FlutterFlow version: 3.1 May 20
- Platform: Web
- Browser name and version: Chrome 113.0.5672.126
- Operating system and version affected: MacOS Ventura 13.4
```

**Comment by agreaves** [comment] 2023-05-29 21:18
Hi @blondie63, I was not able to tell from the video what exactly the issue is with swiping. Could you explain a bit more what the issue seems to be?

**Comment by blondie63** [comment] 2023-05-29 21:25
Hi @agreaves , But you really don't understand ?????
If I swipe left and right with my finger or mouse you can see that the days of the month change correctly while the name of the month does NOT !!! While if one of the two icons < and > the name of the month changes !!! Are you part of the FF development team?

**Comment by agreaves** [comment] 2023-05-29 21:49
Hi @blondie63, friendly reminder to please remain respectful on our issue tracker, as we're here to help.

Thanks for clarifying, I do see the issue now, and this will be fixed upon our next release!

When you create an issue in the future, please add a complete description of the issue that fully describes the issue you're facing, even if it seem obvious. This helps our (sometimes tired 😅) devs identify and fix your issues faster. Thanks again for the bug report!

**Closed by agreaves** 2023-05-29 21:49 UTC
Labels: type: bug, status: confirmed

**Comment by blondie63** [comment] 2023-05-30 15:18
Hi @agreaves, Sorry but I didn't mean to be rude, it just seemed so obvious to me and then it was evening and maybe I was a little tired. Best regards
