### ISSUE TITLE
Unable to toggle legacy date picker is using Organisational Design System

### ISSUE THREAD

**Issue by TerenceStupple** [FlutterFlow/flutterflow-issues#205] opened 2022-12-09 07:39 UTC
## Expected behavior (required)
I expect to be able to go to Settings > Theme and toggle 'Use Legacy Date/Time Picker'

## Current behavior (required)
I can not toggle the Date/Time Picker as an Organisational Design System Theme is selected and the page is locked.

## To Reproduce (required)

1. Have a project that has a legacy date picker in it.
2. Have a project that uses an Organisational theme.
3. Click on Warning in primary nav.
4. Click on Date/Time Picker Toggle.

### Bug Report Code
N/A

## Context (required)
Wish to use new date picker but we are unable to.

## Screenshots / recordings
<img width="374" alt="image" src="https://user-images.githubusercontent.com/27389292/206649903-3288cd60-2218-427d-9e32-a552445d29ff.png">

<img width="539" alt="image" src="https://user-images.githubusercontent.com/27389292/206650000-39d9e834-204f-43fb-9d20-42aafb4f707c.png">

<img width="400" alt="image" src="https://user-images.githubusercontent.com/27389292/206650022-e12ac2f4-93f9-45cf-ab0d-aeed38fe53c6.png">

## Your environment
* Version of FlutterFlow used: v3.0 December9, 2022 - Flutter 3.3.4
* MacOS 13.0.1
* Chrome Version 108.0.5359.98 (Official Build) (arm64)

**Comment by Pepino-GR** [comment] 2022-12-09 17:21
I cannot reproduce this issue. @shelpert can you please try to reproduce?

**Comment by TerenceStupple** [comment] 2022-12-09 23:22
https://user-images.githubusercontent.com/27389292/206811048-5db37341-f4c5-4fa4-b43a-5e39b0a5609e.mov

**Comment by Pepino-GR** [comment] 2022-12-10 13:07
Hi TerenceStupple,

thanks for reporting.

**Comment by agreaves** [comment] 2022-12-28 04:59
Hi @TerenceStupple, thank you for the bug report! This will be fixed upon our next release! 🙂

**Closed by agreaves** 2022-12-28 04:59 UTC
Labels: status: confirmed
