### ISSUE TITLE
Team Function added in a branch doesn't merge to the main branch

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#1926] opened 2023-11-29 16:20 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Team Function added in a branch doesn't merge to the main branch

### Expected Behavior

Team Function added in a branch should be added to the main branch

### Steps to Reproduce

1. Create a branch
2. Add a team function
3. Use this team function in some place
4. Now merge to the main branch
5. No produces an error but nothing happens

The team action is not added and the widget where the team function is used and the team function disappear after refresh the page

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfkufl0It1mNte14SIKcJsgiYUNkMcTIMziNZ+exUbfaL1Bu0AOcnBblpoYMu4aVNcBmGLgkUDpvDRiIX+GvUoNU6CG7461cxybAvke2iuSq7REoeSZmsnBexTfEia55+42BQkOtZ1Wmw42WGILu+XRXTDBOu/Zwh9f6PHaOI=

### Context

I want to do some changes in a branch and merge it after to the main branch

### Visual documentation

https://www.loom.com/share/fd375aa3973c417992b4f90c718a3944

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.O released November 28, 2023 - Flutter version is 3.137
- Platform: Web
- Browser name and version: Chrome Version 119.0.6045.161 (Official Build) (64-bit)
- Operating system and version affected: W11 23H2
```

**Comment by Franco98404** [comment] 2023-11-29 16:27
An improvement after the merge is to redirect to the main branch or show a message to let the user decide if to go to the main branch or still work in the same branch. Now after the merge I still in the same branch and is little be confuse to me because I think that I am in the main branch

**Comment by Franco98404** [comment] 2023-12-08 17:02
> Hi @Franco98404 - Thanks for submitting the issue. Is this behaviour still happening for you? 

@hariprasadms I don't have a team account, so I can't verify but the video was recorded the last week

**Comment by hariprasadms** [comment] 2023-12-11 09:53
Thanks for confirmation @Franco98404 - This can be related to firebase _database user permission to perform merge action (This is something to do at FlutterFlow side) . I can reproduce the same behaviour for one of the user accounts but it is not from team. I can see below error. 

<img width="1091" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/144101ff-5ed8-4a2a-92ed-d7ab1f10e4e3">

Can you please share what error you see in browser console while performing merge actions.

**Comment by Franco98404** [comment] 2023-12-11 19:33
I no longer have an active account to test

**Comment by Franco98404** [comment] 2023-12-11 19:33
I no longer have an active account to test

**Comment by infocodiste** [comment] 2024-01-11 13:49
It seems like I'm encountering a problem while merging branches. When I merge another branch into the main one, it ends up overwriting all the changes from the other branch, and the main branch loses its modifications. Additionally, attempting to rebase with the main branch causes the other branch to adopt the characteristics of the main branch and loses its modifications. This is quite frustrating for me as a developer, especially after investing in the enterprise-level access. After spending two days carefully merging two branches, I'm unable to find a well-merged branch, forcing me to resort to manual project management by manually write within the main branch

**Comment by smian0** [comment] 2024-01-18 16:22
Hi flutterflow team, we are facing the exact same issue. Please address this issue since we are also a paying team customer and we expected this feature to work flawlessly.

**Comment by syg-eliseu** [comment] 2024-03-21 14:46
It appears that the Flutterflow team simply abandoned issue support.

**Comment by renandeves** [comment] 2024-05-21 16:48
Hi guys, our team is having exactly the same problem.
We've contacted FF support by email, sent lots of videos, proofs and haven't received anything conclusive.

**Comment by leighajarett** [comment] 2024-05-24 16:35
Hi there! We have tested this and are not able to reproduce. @renandeves can you share more details like bug report code / videos to this issue?

**Comment by msusviela** [comment] 2024-07-09 21:36
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Closed by msusviela** 2024-07-09 21:36 UTC
Labels: type: bug, waiting for user response, Branching, not in linear
