### ISSUE TITLE
Flutter version on Web different than Mac app

### ISSUE THREAD

**Issue by Nic61** [FlutterFlow/flutterflow-issues#2784] opened 2024-04-22 10:42 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Having a different flutter version on mac app renders it useless. It causes crashes in the UI and I can't deploy on stores.

### Expected Behavior

I would expect to have the same flutter version everywhere to have a consistent development experience.

### Steps to Reproduce

1. Open a web project and check flutter version
2. Open a mac app project and check flutter version

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

NA

### Context

Bugs in UI and actions and I can't deploy to stores from mac app.

### Visual documentation

![Screenshot 2024-04-22 at 12 38 36](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/549e7956-4559-4799-878c-1bfd01f7ab61/9c364cd9-f4c2-48ab-9794-ab86c665d49b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81NDllNzk1Ni00NTU5LTQ3OTktODc4Yy0xYmZkMDFmN2FiNjEvOWMzNjRjZDktZjRjMi00OGFiLTk3OTQtYWI4NmM2NjVkNDliIiwiaWF0IjoxNzEzNzk1NjYyLCJleHAiOjMzMjg0MzU1NjYyfQ.w5AkTQEtxEzAEjO8FI4GoYumAVH0uqOg-zWyQt4SKQE "=215x")

![Screenshot 2024-04-22 at 12 38 55](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/98259901-bffb-4ab4-bd44-af26916fa656/b55f1dc6-891c-44e6-a3bc-771ec8f5f7f0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85ODI1OTkwMS1iZmZiLTRhYjQtYmQ0NC1hZjI2OTE2ZmE2NTYvYjU1ZjFkYzYtODkxYy00NGU2LWEzYmMtNzcxZWM4ZjVmN2YwIiwiaWF0IjoxNzEzNzk1NjYyLCJleHAiOjMzMjg0MzU1NjYyfQ.tHjPMawaUpetRah5QTKQD5Pt9YSRlsPrP1aePvTIbN4 "=244x")

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version:
- Platform: web and mac
- Browser name and version: Google Chrome
- Operating system and version affected:
```

**Comment by rzambroni** [comment] 2024-04-22 14:47
Hey @Nic61, the Flutter version seems to be the same on all platforms. If you are referring to the FlutterFlow version rather, this is normal and should not be causing you any problems.

Thanks.

**Comment by Nic61** [comment] 2024-04-22 16:44
You're right. I misunderstood those.
I just want to point that I do have issues with the mac app. Specifically some UI bugs and the deploy issue (same as another issue request here on git)

**Comment by Nic61** [comment] 2024-04-22 16:44
Specifically this one: https://github.com/FlutterFlow/flutterflow-issues/issues/2758

**Comment by rzambroni** [comment] 2024-04-22 16:50
Ok, thanks. Will close this one as it is a duplicate of [#2758](https://github.com/FlutterFlow/flutterflow-issues/issues/2758) then. That issue will be triaged soon, please be aware of the updates there.

**Closed by rzambroni** 2024-04-22 16:50 UTC
Labels: status: not a bug
