### ISSUE TITLE
Reorderable listview anchor for reordering don't display on mobile device

### ISSUE THREAD

**Issue by vaital3000** [FlutterFlow/flutterflow-issues#1450] opened 2023-09-13 09:15 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I deploy web version of my project https://reorderable-list-view-bug-tc2x9n.flutterflow.app/

When I open page on desktop Chrome on mac, I see reorder anchors 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/15158048/12b10e66-74b5-488e-a682-99502388ae33)

But when I open this page on mobile device in chrome (Samsung Galaxy S23 Ultra), I don't see reorder ancors, but I can reorder items. (When I setup apk on this device, I get same behavior)
![telegram-cloud-photo-size-2-5190886590954721933-y](https://github.com/FlutterFlow/flutterflow-issues/assets/15158048/dd83565e-1553-4d93-8af7-b6f0ef655f2a)

### Expected Behavior

Page displayed same as on desktop.

### Steps to Reproduce

1. Create new Page
2. Add ListView widget
3. Enable reordering
4. Add items into ListView
5. Deploy project to web

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8khvHlsIZ2sdtJ7aryavlR/SMUKUR/RY0nktVxQgwgIYzwEoYUZeD4YRduYsyAenxiM2eIknsKzPzZvYfxUMJdZUisUY9q3btydzuXRlOlVr6LEpCgTnx7EplmGnKG0buNqwx9FMVqSEI/3DmXOOiQdD7vN5zMPG0wQuWXDIP5n1bjLBDkUiAyyiZecCfn

### Context

I can't use reordering in listview on mobile

### Visual documentation

![telegram-cloud-photo-size-2-5190826285318917126-y](https://github.com/FlutterFlow/flutterflow-issues/assets/15158048/344eef86-e177-4ab2-a482-a85f407f9d41)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/15158048/ac40bc83-a8ee-4dbd-97de-f9de3a779351)

### Environment

```markdown
- FlutterFlow version: v3.1 (released Sep 7, 2023
- Platform: Web, Android
- Browser name and version(works fine): Chrome(Mac OS) Version 116.0.5845.179 (Official Build) (arm64)
- Browser name and version(don't works): Chrome(Android) 116.0.5845.172
- Operating system and version affected: Android 13; SM-S918B Build/TP1A.220624.014
```

**Comment by zeymermontes** [comment] 2023-09-13 17:34
I think is part of the Behavior of the dependency. But can be changed with a parameter

**Comment by hariprasadms** [comment] 2023-09-13 19:58
Hi @vaital3000 - Thanks for submitting the issue. I tested it and was able to replicate web app link while accessing in mobile browser ( real device only but its works fine in browser mobile simulators ). It works fine in real devices and desktop browsers.

**Comment by victoriahuang1** [comment] 2023-09-18 20:18
Hi @vaital3000 , thanks for the report. This is actually the expected behavior. On mobile, the entire list item is draggable. On the other hand, on desktop, you need to drag the icon.

But I agree that it will be nice to have the ability to customize the UI. I will closing this as it is not a bug, but will put this in as a feature request :)

**Closed by victoriahuang1** 2023-09-18 20:18 UTC
Labels: type: bug, status: confirmed
