### ISSUE TITLE
Flutterflow languageselector does not have an 'action' option

### ISSUE THREAD

**Issue by adrfinance** [FlutterFlow/flutterflow-issues#4862] opened 2024-11-11 08:55 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

For some reason, the language selector widget does not have an 'action' option.

### Expected Behavior

I would like the widget to have an 'action' widget, thus allowing me to make an API call every time the user changes the language.

### Steps to Reproduce

1. Create new page
2. Add language selector widget with e.g. 2 languages
3. Try to add an action
4. Not possible since the 'action' option does not exist

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5TzMmBw412odtF+Kr9bcJR/SAXH1gjargzjuxhcw4aJurmP7QMPsj8ZXFLX/26TFZqeFqZrGcFps7MhuPpUsFcGxuub7o9wbluUwLgc2qyR8TSBaqKVXMlEd1mf0iA5quNviN+IuxYL3ACxWO6Nd68aDLrJL7yDVVMGfKYUZvDo1aCGQ/rLyBt4zEDLHWkE8YPZFDq+f6QspZl1eTjzw==

### Visual documentation

<img width="1152" alt="language selector options" src="https://github.com/user-attachments/assets/2e518ddd-b066-4588-bc5c-ebb649e514d9">

### Environment

```markdown
- FlutterFlow version: 5.0.8+
- Platform: Web
- Browser name and version: Chrome Version 130.0.6723.117 (Official Build) (64-bit)
- Operating system and version affected: Windows 11
```

### Additional Information

I am trying to make an API call every time the language is changed and this is not possible at the moment since there is no action option on the language selector widget

**Comment by Alezanello** [comment] 2024-11-11 13:35
Hello!

Thank you for your input!

This appears to be more of a feature request than a bug. Since this GitHub Issue Tracker is intended solely for reproducible bugs, I’ll be closing this ticket. However, I will create an internal ticket to add your request to the engineering team's backlog so they are aware of it.

Thank you for your understanding!

**Closed as not planned** 2024-11-11 13:35 UTC
Labels: closed: feature / enhancement request
