### ISSUE TITLE
UI failing to build

### ISSUE THREAD

**Issue by NWADEM** [FlutterFlow/flutterflow-issues#2063] opened 2023-12-26 20:05 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am building a ble app from a templated app from the Flutterflow marketplace. The UI recently started not displaying at all. I ran this app for a couple of months without running into this issue. I normally download the apk to a device for debugging since it depends on a bluetooth plugin that cannot be run in a browser, but I tried just to test the ui and got an error (a screenshot of which is attached).

### Expected Behavior

I expect the ui to load without issue as it did until today.

### Steps to Reproduce

1. Go to my project: https://app.flutterflow.io/project/ble-project-r8xyz2?tab=uiBuilder&page=SplashPage
2. Run it

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4glsn13ItIvsdA7arPKe9VuCUQJn4jRpc0sNobbxAjIoDoPJkUac7sQ1hpZ/GmYAlbKEWIpFo00NrPitjxGu4FMk+ZfJhJ+Kl+ZQ3MRnm/aoS6CLmJOHMlJ+JhGkeM3KSZgCZAWdJhLF4G3F+AefC8RT3BJZv7Zwh9f6PHaOI=

### Context

I am developing an application to control bluetooth devices for the company I develop at.

### Visual documentation

![Screenshot 2023-12-26 135524](https://github.com/FlutterFlow/flutterflow-issues/assets/143843313/b923ebd9-552f-4365-9070-cb5bfaaedd95)

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: Developed on Windows, application to be run on android
- Browser name and version: Chrome 120.0.6099.111
- Operating system and version affected: Windows OS build 120.0.6099.111, Android 13 (sdk 33)
```

**Comment by sbis04** [comment] 2023-12-27 06:20
Hey @NWADEM, the null issue is happening because certain values coming from the custom actions are not set initially (and are `null`), you can solve the issue by assigning a default value to the variables while using them. I identified there are two places from where the issue might be occurring:

1. `isEnabled` conditional on "Fetching bluetooth status..." Text widget
2. `aTSRadio` on the "PTX not found" button.

I'm closing this issue since it's not a bug. Please reach out to the support for further help regarding this.

**Closed** 2024-02-05 13:39 UTC
Labels: closed: not a bug
