### ISSUE TITLE
jProperty Overide: String property not properly set in Image

### ISSUE THREAD

**Issue by JohnCarterGonzalez** [FlutterFlow/flutterflow-issues#2984] opened 2024-05-24 19:19 UTC
### 

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

## Problem

There seems to be a bug with several of my image widgets that could be related to:

[https://community.flutterflow.io/ask-the-community/post/string-property-not-properly-set-bqtPVHI3MMOtlq6](https://community.flutterflow.io/ask-the-community/post/string-property-not-properly-set-bqtPVHI3MMOtlq6)

The image widgets show a **Property Override** error that, no matter the debugging, cannot be fixed.

### Expected Behavior

The expected behaviour is like the 'Course Hero Image' widget above it. The 'Course Thumbnail Image' image widget grabs the returned URL from Supabase and uses that for the Image Path with no error.

### Steps to Reproduce

It is not reproducible per se. The error showed up upon logging on about 2 days ago, and not matter the steps I take to fix it, will not go away.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Cz/Hlz4tgrsNc1rrMacBvvyQsKUg4RYIN0sFhexIYN5PRDYl3Z/ekUERVZOnhS2xXeWaJgWoW3NbNiuHpV/IFPQuuQKpbz7pcFj3LVkyVV4iIFJWgY2tAEeFPChXGy8K3kRFSWe5hc3xnwUyIAuu/aALANIDbCms4Dq/LZO4=

## Context

I have a form that uploads two media files to Supabase via the FlutterFlow **'Upload media to Supabase'** methods provided.

These image widgets that have their path set by the returned urls from Supabase. Half of them work correctly (on each page where this action is used) and show no error. The other half of them show a "Property Override String property not properly set in Image" error:

The first image widget labeled 'Course Hero Image' does not trigger the error. It is the widget labeled 'Course Thumbnail Image', yet the two are identical in set up the only difference is that the path for the 'Hero' widget grabs 'Uploaded File URL 1' and the 'Thumbnail' widgets is 'Uploaded File URL 2'.

## Debugging

I have removed the path variables from the affected widgets, the error persists. I have changed to the 'Image Type' from 'Network' to any other option and I have removed the widget entirely, the error still persists on the page it was originally reported from.

### Visual documentation

Affected Image Widget:

![Screenshot 2024-05-24 at 12 05 44 PM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/6e28ebbd-4f3e-494d-944a-a5435ea89ed6/ac9ac079-01cd-4117-91ca-e9a30add6731?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82ZTI4ZWJiZC00ZjNlLTQ5NGQtOTQ0YS1hNTQzNWVhODllZDYvYWM5YWMwNzktMDFjZC00MTE3LTkxY2EtZTlhMzBhZGQ2NzMxIiwiaWF0IjoxNzE2ODM0NDI5LCJleHAiOjMzMjg3Mzk0NDI5fQ.iZ4JhzrTz0xabfO3HvVbsusSxmPdVkpM27RzXeNEQJg "=1920x")

Upload to Supabase workflow:

![Screenshot 2024-05-24 at 12 13 26 PM](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/0fafd4da-5535-4529-9ba1-e3cf6031fbfc/23626d61-48d7-4db9-87ec-1b250f6af734?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wZmFmZDRkYS01NTM1LTQ1MjktOWJhMS1lM2NmNjAzMWZiZmMvMjM2MjZkNjEtNDhkNy00ZGI5LTg3ZWMtMWIyNTBmNmFmNzM0IiwiaWF0IjoxNzE2ODM0NDI5LCJleHAiOjMzMjg3Mzk0NDI5fQ.T996uZl9F95AxoFbYIRpnmLziIB7cFS_rF1lLJ0Xyvk "=1920x")

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1.53
- Platform: Web, MacOS Desktop
- Browser name and version: Chrome 124.0.6367.210
- Operating system and version affected: MacOS Sonoma 14.5
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] \~100% of the time
- [ ] \~50% of the time
- [ ] \~10% of the time
- [ ] \~1% of the time
- [ ] Very rarely or only encountered once

**Comment by msusviela** [comment] 2024-05-27 18:36
Hey @JohnCarterGonzalez, Thanks for your report, So sorry you are experiencing this issue. I was not able to reproduce this on a blank project, but it is replicable on yours. That's why I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. Thanks so much!

**Closed** 2024-05-27 18:36 UTC

**Comment by JohnCarterGonzalez** [comment] 2024-05-28 17:43
@msusviela thanks for your reply! I will reach out to the support email you sent me. Feel free to close the issue.
