### ISSUE TITLE
MissingPluginException(No implementation found for method requestPermissionExtend on channel com.fluttercandies/photo_manager)

### ISSUE THREAD

**Issue by PeterKarpinski** [FlutterFlow/flutterflow-issues#987] opened 2023-06-12 16:52 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Here's my custom action code:

`import 'package:wechat_assets_picker/wechat_assets_picker.dart';

// Set your action name, define your arguments and return parameter,
// and then add the boilerplate code using the button on the right!

Future selectImages(BuildContext context) async {
  final List<AssetEntity>? result = await AssetPicker.pickAssets(context);
  print(result);
  return result;
}`

After clicking button that triggers this action I get the following error:

`Uncaught (in promise) Error: MissingPluginException(No implementation found for method requestPermissionExtend on channel com.fluttercandies/photo_manager)`

### Expected Behavior

I expected to see the 'select images' modal.

### Steps to Reproduce

1.Add wechat_assets_picker: ^8.4.3 to custom action
2.Try to use AssetPicker.pickAssets(context); function

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXhsmB389OvuZE+Yf1bvlvoGQwFjMMbY0v0u0bFB43G4urBLMuPeDOR0NKTsuQTFA2eGaIklIHwNbQvfDpVPk6NU+Cf4980JVAcD3hWnyjRZ/TPaqee3EnBeJgBWrF5sHVkR1SD/ViSng51EOhNq3qNleeY8aSfxBlZ7vfcPo=

### Context

I am trying to upload multiple images to my API. First step would be to select them via wechat_assets_picker.

### Visual documentation

![Screenshot from 2023-06-12 18-43-15](https://github.com/FlutterFlow/flutterflow-issues/assets/63281010/2dc4cdec-f06d-4a1c-b8bb-ac40a5f89d0d)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected:  Ubuntu
```

**Comment by hariprasadms** [comment] 2023-06-18 17:42
Hi @PeterKarpinski - Thanks for submitting the issue. It appears that the issue is with the third-party package. I also don't see a sample project created with issue setup details. Without a blank project setup that clearly illustrates the issue, we are unable to consider this type of issue for investigation. 

Please update the issue with blank project details.

**Comment by wenkaifan0720** [comment] 2023-07-05 15:46
Hi @PeterKarpinski. The package you are trying to use doesn't support the web platform. If you want to use it, you'll need to test it locally with Android and iOS. 

Since this is not a bug on our end, I will close this issue.

**Closed by wenkaifan0720** 2023-07-05 15:46 UTC
Labels: closed: not a bug, status: not a bug
