### ISSUE TITLE
Translations get lost when copying / cutting objects

### ISSUE THREAD

**Issue by GiovanniBaldo** [FlutterFlow/flutterflow-issues#3563] opened 2024-08-06 16:07 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

after copying objects often translations are lost

### Expected Behavior

trasnlations should not get lost

### Steps to Reproduce

Create new project
Add languages to project: English , Italian , French
Set English as primary and display language
On main page, create a container in the main column, width infinite, height 200
Add a column in the container. 
Add some text to the column
Insert a value for every text with translations in the 3 languages
Trasforma the container widget into a component -> inside the component all the text are still translated (not always... )
In main column of main page add another container , widht infinite, height 200
Now copy the column containing the texts from the component created above and paste the column in the new container in the main page. translations in italian and trench are LOST! 

Notice this is not the only behavior where the translations get lost. it was just the easier to reproduce.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48z8jfz4pPxPVY0LrUb8Fr/TkRJmk7bYJF0+pHcxE8J5zKB+wAYvf7P1FWTL3iTG9YP1qjuD8y1vfqkvH9J/YBISecb6JnzqlfEALhRniiMqnSErqNfW1TP9FUCmrGy57UugldCO1eS0Zm72b3C/CtdB/AJ7K2OFUdI/+LKdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

<img width="907" alt="Screenshot 2024-08-06 alle 18 04 41" src="https://github.com/user-attachments/assets/6a1167fa-c1b0-4bb6-864a-4237c2179e31">

### Environment

```markdown
- FlutterFlow version: 4.1.79
- Platform: ios/android/web
- Browser name and version: i'm using ff app
- Operating system and version affected: macbook air m2 sonoma 14.5
```

### Additional Information

u can verify on project "translation-bug-uo5ztb"

**Comment by msusviela** [comment] 2024-08-06 17:54
Thanks @GiovanniBaldo. I'm closing this issue because it's a duplicate of this issues:<br>[https://github.com/FlutterFlow/flutterflow-issues/issues/2346](https://github.com/FlutterFlow/flutterflow-issues/issues/2346)

[https://github.com/FlutterFlow/flutterflow-issues/issues/3457](https://github.com/FlutterFlow/flutterflow-issues/issues/3457)

<br>The ENG team is already working on a fix for all this data loss regarding translations.<br><br>You can follow the original issue to keep updated.

Thanks for filling in!

**Closed as not planned** 2024-08-06 17:55 UTC
Labels: closed: duplicate
