### ISSUE TITLE
Setting multiple conditions about ChoiceChips to disable a button

### ISSUE THREAD

**Issue by crystal-estelstudio** [FlutterFlow/flutterflow-issues#1108] opened 2023-07-12 14:30 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

A grey screen occurs during run mode.

### Expected Behavior

The button should be disabled when ChoiceChips is less than 1 or more than 3.

### Steps to Reproduce

1. Create ChoiceChips
2. Create Button
3. Turn on "Button Disable Options"
4. Add Multiple Conditions
5. First Condition: ChoiceChips NumList < 1
6. Second Condition: ChoiceChips NumList > 3

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wyeflzItOpbxY+KrQdfpVtGAUMjs5R+Ye0O5ERis9f5CvOpYUec/6PhFVOfW/TQlAe2emp14K0euNueHXEPAnOSmWRaZMyJANFAHyfEGmSrGTF7ioWWskJ+lnCmKd4J6vvSYnWPhYdV47612QOOeXSXLAN5jGIkQ8Sq/LZO4=

### Context

We are trying to make sure user selects only 1, 2, or 3 choices in the ChoiceChips widget.

### Visual documentation

https://www.loom.com/share/7613d60705214abfa75acab46505e936?sid=f45adba2-5d8f-4331-99c3-5e1bfcaecd8f
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/138203516/6b763fdd-a607-42f9-9dd6-1ca840943ff0)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Chrome 114.0.5735.198
- Operating system and version affected: macOS Ventura 13.4.1
```

**Comment by kevintonb** [comment] 2023-07-14 09:09
Hey @crystal-estelstudio , thank you for sharing this issue. This looks more like an implementation error rather than a bug within Flutterflow. In order to get more context, can you please share more elaborate reproducible steps to recreate this issue? Feel free to also attach an empty blank project where the issue has been recreated! :)

**Comment by crystal-estelstudio** [comment] 2023-07-14 09:43
Hi @kevintonb , as requested, here are more elaborate reproducible steps to recreate this issue:

1. Create a ChoiceChips widget
2. Add a backend query and set Define Options to that backend query
3. Set Allow Multi Select to On
4. Add a button
5. Turn on "Button Disable Options"
6. Set to Combine Conditions
7. Set First (Single) Condition: ChoiceChips NumList < 1
8. Choose "OR"
9. Set Second (Single) Condition: ChoiceChips NumList > 3

Here is the link to an empty blank project where the issue has been recreated: https://app.flutterflow.io/project/sample-lrkgk7 (In this sample app, since I don't have a Firebase collection connected just like in our current project, I used a free API)

Note that when I remove the conditions, it does not have a grey screen. Only happens when #s 5-8 are there.

Thanks in advance for your help!

**Comment by katherineqian** [comment] 2023-09-30 20:08
Hi @crystal-estelstudio, I wanted to apologize for the extremely delayed response on this issue. I appreciate all of the details that you gave to help resolve the bug. I was not active on maintenance and I'm sorry that I let this fall through the cracks like this. I wanted to provide you with an ETA on when this would be addressed - it should likely be fixed on the second release from now, if not the next one. I will provide an update here if it turns out this isn't a bug, but based on the report, I believe I should be able to find a fix for this. I'm sorry again for the delay.

**Comment by hariprasadms** [comment] 2023-12-20 10:45
Since the issue is considerably old and there has been no follow-up, we assume that it has been resolved in the latest FF updates. Thanks

**Closed by hariprasadms** 2023-12-20 10:45 UTC
Labels: closed: fixed, Choice chips widget
