### ISSUE TITLE
LogOut Redirection code gets generated out of the Condition when the action is performed inside a condition branch

### ISSUE THREAD

**Issue by mehdidou99** [FlutterFlow/flutterflow-issues#1599] opened 2023-10-06 13:43 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I perform a LogOut action inside of a conditional action branch ; the "logout" part is generated at the correct place, but the last instruction (a redirection to the logged out page) is generated outside the condition branch and thus always happen, even when the condition is not met.

### Expected Behavior

The redirection only happens when the condition is met.

### Steps to Reproduce

1. Create a project with authentication
2. Create a LoggedIn page
3. Create an "On Load" action with a condition
4. Add a "LogOut" action to one of the branches
5. View code

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEels/l25RJpb0B17XicPowiQMwJ0QlUIInj+0bWRMhfarmELMiZffeXElLYteifVZAAFql8VEdw8nGjoaSOsACJk2aGoRDzoRXQTrKTn25aZiSO86KeXdRI+ZMCh2Z37uFpBZvNuxhcUVn1GeAevCdG3qCf9qOYwx5e6fDbOY=

### Context

I sometimes delete some accounts outside of the app. When that happens, the user is not automatically logged out, so there is a never ending loading when he goes to the Profile page (which is caused by a query to get the user document that never gets it because it is deleted)
So I added an On Load action to check if the document exists and logs out when it does not exist, avoiding this issue, but now the user is always redirected to my LoggedOut page every time he goes to the profile page.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/19557144/960ff351-bf91-4a33-af29-13770b6cf52a)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/19557144/4212ce51-a5cb-4eae-89a8-81d1737e758d)

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: Web
- Browser name and version: Chrome Version 116.0.5845.179
- Operating system and version affected: Ubuntu 22.04.3 LTS
```

**Comment by hariprasadms** [comment] 2023-10-09 14:22
Hi @mehdidou99 - Thanks for reporting the issue. As per above steps, I am not able to reproduce the issue. I can confirm that it is working as expected. In the given project, I was unable to find the page where you are facing issue. I would suggest reproduce the issue in a blank project and share project bug report code of the same. Once you have added required details. we can re investigate the issue. Thanks

**Comment by hariprasadms** [comment] 2023-10-10 14:56
Hi, Any any latest updates about required details? I presume you got the solution. If this is the case let me know I can close the issue. Thanks

**Closed** 2023-10-16 09:06 UTC
Labels: status: not a bug
