### ISSUE TITLE
 The custom widget code editor isn't compiling in a specific project.

### ISSUE THREAD

**Issue by sabatage3** [FlutterFlow/flutterflow-issues#1629] opened 2023-10-12 02:37 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When trying to compile even a sample widget, the compile button doesn't do anything. I tried repeating the process in another (older) project, and it worked just fine. I don't have any errors in my project, so I have no idea what configuration could possibly be causing the custom widget's compile button to stop working. Please, I need someone to access my project to see what's happening.

Custom functions and actions work just fine.

### Expected Behavior

The compile button should at least attempt to compile when pressed, but it doesn't do anything. I've already tried in multiple browsers.

### Steps to Reproduce

Since I just realized this only happens in a specific project of mine, I don't think it can be reproduced. I created a new project, and it works just fine, but when I cloned the project, it had the same issue.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Ck8nf34Z2xOFc+Kr2dvlVgiI5JUN/RYEWmO0bWQ0gJ5PND+x/esnRQFJuZ9OrdkFqJGH8oDkK0+zJm9z1NvUFGxKrb6pBzLVQczrdcH6mM4yXPajpQH9+GshWCUDH5MKG3B0lGNt1c0IY70+IO9+/ExfbQpe2IlUaRfGaMZLXvgfuQ0SLb3kNh1JWeC/v

### Context

I was attempting to create a custom toggle switch widget because the default one from FlutterFlow is not functioning correctly. It doesn't display the right colors when set to 'true,' and it's not reading a parameter from Firestore like other widgets on the page.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/15147720/677caadc-51dd-4a3a-b4c0-c37994b30d6e)

I get this error whenever I click on the compile button, and it simply doesn't respond.

### Additional Info

I have no errors in my project or in my custom widget code.

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: web
- Browser name and version: multiple browsers
- Operating system and version affected: windows and MacOs
```

**Comment by katherineqian** [comment] 2023-10-12 03:53
Hi @sabatage3, I've been investigating the same bug so can mark it as confirmed. It appears to be a problem related to the Flutter update that we just performed recently. As a temporary workaround to unblock you, can you try adding the import `intl: 0.18.0` in your Custom Action and pressing the green "Refresh code editor with pubspec dependencies" button?

**Comment by sabatage3** [comment] 2023-10-12 04:03
@katherineqian Thank you for your quick response. Unfortunately, that workaround didn't work for me. I encountered an error because I couldn't override FlutterFlow's default 'intl'. So the compile button still not responding

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/15147720/a69f1219-d596-4815-8bf0-ffaae36ff8fc)

**Comment by katherineqian** [comment] 2023-10-12 04:05
You should still be able to override the version that we provide if you click the green button, since that's just a warning -- but please let me know if you click it and that still doesn't fix the error.

**Comment by katherineqian** [comment] 2023-10-12 04:09
Update: Thanks for letting me know -- let me get back to you about a different fix. This had fixed the error on a different test case, but it appears that something else is still not working here.

**Comment by katherineqian** [comment] 2023-10-12 17:28
Hi @sabatage3, 

This is actually fixed in the next version that is about to be released to production. Although I could reproduce the error you're experiencing on the current live version, the button is fully functional and clickable on the next pre-release version. Please wait until the next version and everything should work again. In the meantime, selecting "Exclude from compilation"  would unblock you from running/testing/publishing your project. 

Please also reopen this issue if you continue to experience this issue after the next release. Thanks for reporting this.

**Closed by katherineqian** 2023-10-12 17:28 UTC
Labels: type: bug, status: confirmed

**Comment by sabatage3** [comment] 2023-10-14 01:12
@katherineqian Any idea when this new version of FlutterFlow is coming out? I need to deliver this project to my client in a couple of weeks :(

**Comment by katherineqian** [comment] 2023-10-15 03:38
Sorry, I actually don't know the exact day, but I know it is soon and I think it will be at the start of this coming week. You'll be able to tell from the dialog that appears when you hover over "FlutterFlow -- v4.x" at the top left of your screen. I hope that helps a little with understanding the status, I understand that it is frustrating.
