### ISSUE TITLE
Shared project not shown in preview-app

### ISSUE THREAD

**Issue by webwurm** [FlutterFlow/flutterflow-issues#1320] opened 2023-08-21 07:31 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I share my project with another ff-account (not a team-member!), it is shown in his account as "Team Project" in the ff-dashboard, but it does not appear in the FF Preview-App in the shared-projects-section.

I tried it with an existing and now with a complete new ff-user, and this happened in any case.

### Expected Behavior

The project should show up in the "Shared-with-me-projects"-section in the FF Preview-app.

### Steps to Reproduce

1. Settings > Collaboration > Invite User
2. Sign up/in as the new user (Team project is shown)
3. Install and sign in in FF Preview-app > Shared project: Project show also there be shown

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Wl8nl3891pbxH1rXuY+9VnjwWQ2Yha788msN+URA2GO/1OrYPX/ykP1FoXbSndkFifWCZqzkd0/DRm9z1GME6B0msfqZ6+bl6YQvgcGCnV8TSDai8fnZuGshQN0iByMGr3BR/Nu5pWXgj3FOYA+eXQnLXQYzuDTBMIcmkUafXrgfuQ0SLb3kNh1JWeC/v

### Context

I am trying to share the project in the preview-app with the customer. 

### Visual documentation

![Screenshot_20230821_102709](https://github.com/FlutterFlow/flutterflow-issues/assets/1053176/54ad50c1-5258-4499-a133-6c9eb55b388d)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: web
- Browser name and version: Edge
- Operating system and version affected: Windows 11; Android
```

**Comment by SameerShahzad99** [comment] 2023-09-06 18:13
@webwurm Thank you for sharing, i was able to reproduce this problem on my end

**Comment by wenkaifan0720** [comment] 2023-09-15 19:28
Hi @webwurm. Our preview app is outdated now and we are considering of replacing it. I will close this issue for now since we will not be fixing it.

**Closed by wenkaifan0720** 2023-09-15 19:28 UTC
Labels: type: bug, status: wontfix, status: confirmed, closed: feature / enhancement request
