### ISSUE TITLE
Generated code using a disposed context

### ISSUE THREAD

**Issue by siddharthadevops** [FlutterFlow/flutterflow-issues#814] opened 2023-04-26 10:25 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Generated FlutterFlow code is using a disposed context to get MediaQuery.of(context) height

### Expected Behavior

Generated FlutterFlow code must use the appropriate context

### Steps to Reproduce

1.- Create a BottomSheet page
2.- An action of this BottomSheet dismiss the page `(Navigator.pop) `and launch a new BottomSheet page

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESl/KA5YtgrsAC1YfyacdqhQMkQzM6bZI7ku1EdwEhfL7sE+0AfeLCbktLYtemY0FiIWGJjj8K0fzGvoXpGsc4KUytfIRqzZRXQQ/gWmG7RLKmEpewQXRAHf1hf3Ku37TQvyRdIthpW0Fl62eMe/CrG3qCf9qOYwx5e6fDbOY=

### Context

I'm trying to dismiss a BottomSheet and from this page, launch another BottomSheet, dismissing the previous

### Visual documentation

                           ```
 onTap: () async {
                                  Navigator.pop(context);
                                  await showModalBottomSheet(
                                    isScrollControlled: true,
                                    backgroundColor: Colors.transparent,
                                    barrierColor:
                                        FlutterFlowTheme.of(context).barriers,
                                    enableDrag: false,
                                    context: context,
                                    builder: (bottomSheetContext) {
                                      return Padding(
                                        padding:
                                            MediaQuery.of(bottomSheetContext)
                                                .viewInsets,
                                        child: Container(
                                          height: MediaQuery.of(context)
                                                  .size
                                                  .height *
                                              0.5,
                                          child: CreateNoteWidget(
                                            lessonIndex:
                                                widget.lessondocument!.index,
                                            lessonNumber: widget
                                                .lessondocument!.lessonNumber,
                                            sectionIndex: 0,
                                          ),
                                        ),
                                      );
                                    },
                                  ).then((value) => setState(() {}));
                                },
                                child: Text(
                                  FFLocalizations.of(context).getText(
                                    'km19ru40' /* New note */,
                                  ),
                                  textAlign: TextAlign.start,
```

### Additional Info

```
child: Container(
                                          height: MediaQuery.of(context)
```
 As you can see, in the second use of MediaQuery, instead of using bottomSheetContext it is using the context of the first bottom sheet, which was dismissed previously.

### Environment

```markdown
- FlutterFlow version: 3.7.10
- Platform: all platform
- Browser name and version:
- Operating system and version affected: Ios, android
```

**Comment by hariprasadms** [comment] 2023-04-28 11:32
Hi @siddharthadevops - The bottom-sheet dismiss and open new one, there are multiple ways to achieve this behaviour using action flow. I would suggest explore all possibilities. considering the current bottom sheet feature behaviour, I can say it is working as expected.

Any additional enhancements necessary around the present feature can be considered as a feature request rather than a bug. Please keep us updated on how things goes. **For the time being, I can mark this issue as not a bug and close it.**

**Closed** 2023-04-28 11:32 UTC
Labels: closed: not a bug

**Comment by siddharthadevops** [comment] 2023-04-28 14:18
As you can see in the generated code, you are using the right context in the Padding object, and a defunct one y the very next container.

```
 Padding(
padding:
MediaQuery.of(bottomSheetContext)
.viewInsets,
child: Container(
height: MediaQuery.of(context)
.size
.height *
0.5,
child: CreateNoteWidget(
```
