### ISSUE TITLE
Text Field Widget Unintentionally Expands To Max Lines

### ISSUE THREAD

**Issue by gentleVirus** [FlutterFlow/flutterflow-issues#2660] opened 2024-04-04 12:10 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The Text Field Widget expands to the max lines setting by default even though the min lines is set to 1 and there is no content.

### Expected Behavior

The Text Field Widget should only expand, up to the max lines settings, if there is enough content in it.

### Steps to Reproduce

1. Create a new page. 
3. Add a text field widget. 
3. Set max lines to 3 and min lines to 1.
4. Publish and view in web.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEejMrlvJNPj7xH+c/+c/lvrwMwHVgjbJ0vpe5+dwsjCePrELMcYsn4XFNDWOqHY1VMOU7+p3wGw+juv9nxUfEpE0ydf4c6ypNpUxDifHGXSoyyPc28PmpPO/pgClyby7S3qx1+NuhtWngQ1E6Tf9muY3qCf9qOYwx5e6fDbOY=

### Context

Worked perfectly fine like two or three days ago, than with the last update, the problem started.

The preview in FlutterFlow shows the widget as it should be.

Only tested this in Web and PWA.

This bug is visually very striking because text fields are much lager than they should be.

### Visual documentation

Bug in Web and PWA:
![textfieldBug](https://github.com/FlutterFlow/flutterflow-issues/assets/141834860/6a8d5a76-0de8-4828-9632-17273768e292)

Settings in FlutterFlow:
![textfieldSettings](https://github.com/FlutterFlow/flutterflow-issues/assets/141834860/a4e4c424-9b2c-44d9-81d6-e39108284820)

Preview in FutterFlow:
![textfieldFFView](https://github.com/FlutterFlow/flutterflow-issues/assets/141834860/f2d3dc74-3802-4097-bd85-5f7d04bd2652)

### Environment

```markdown
- FlutterFlow version: v.4.1
- Platform: Web/PWA
- Browser name and version: Chrome
- Operating system and version affected: Android/Windows
```

**Comment by rzambroni** [comment] 2024-04-04 13:50
Hi @gentleVirus, thanks for the report, our team is already aware of this issue as it is a duplicate of: [https://github.com/FlutterFlow/flutterflow-issues/issues/2625](https://github.com/FlutterFlow/flutterflow-issues/issues/2625). 

The good news is that is already fixed! 

I believe the fix will be available on today's release. 

feel free to re-file the issue if you continue to experience it after the next update.

**Closed** 2024-04-04 13:51 UTC
Labels: closed: duplicate
