### ISSUE TITLE
Test run publish run and does not work, coutless errors thrown.

### ISSUE THREAD

**Issue by dajana0** [FlutterFlow/flutterflow-issues#3469] opened 2024-07-24 10:44 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Testing and post-publishing of the application does not work. In the console, I see thousands of errors thrown over and over again:
```
Uncaught 
    at Object.v (https://app.flutterflow.io/main.dart.js:3955:19)
    at Object.ca8 (https://app.flutterflow.io/main.dart.js:6497:9)
    at cxk.lx (https://app.flutterflow.io/main.dart.js:182789:21)
    at cxk.dF (https://app.flutterflow.io/main.dart.js:182791:21)
    at Object.ndR (https://app.flutterflow.io/main.dart.js:141202:21)
    at hJA.$1 (https://app.flutterflow.io/main.dart.js:390877:16)
    at hSD.$1 (https://app.flutterflow.io/main.dart.js:186545:21)
```
![image](https://github.com/user-attachments/assets/3ae9f537-3d83-44c1-8c48-c3c97cecb469)

I created a new project that is completely clean. It has one page - HomePage with an image and AppBar to reproduce the behavior and the same errors keep appearing. I've had this error for over a month now and wonder if I should resign from your services because I cannot work and add new things to my application. 

### Expected Behavior

The app is not frozen and you can do anything in the app.

### Steps to Reproduce

1. Create a new project 
2. Run test mode
3. Open the console and see errors.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89gotsA+qryKvl6hQAkKUg4WLg7m9cbSg8cIuuvB+0Eeur+VGRCYOmcfVZ6PGeikkgJ+Pz4iYTtIfAECzubaINo/89cYRbLfHGlaZCoEauadH9QAftbf1zC5quN2BRACLZfck4Gw2z/cq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

[screen-capture.webm](https://github.com/user-attachments/assets/22442d47-2a97-4ccb-83ad-1832b6e7ab62)

### Environment

```markdown
- FlutterFlow version:  v4.1.75+ released July 23, 2024
- Flutter version: 3.22.2
- Platform: Web
- Browser name and version: Google Chrome Version 126.0.6478.128 (Official Build) (64-bit)
- Operating system and version affected: Windows
```

### Additional Information

I can't work, I can't release a new version of the app. I would make it a top priority because I am unable to do anything with the application.

**Comment by msusviela** [comment] 2024-07-24 11:20
Hi @dajana0. Thank you for filling in. So sorry you're experiencing this issue. Our team is already working on a fix for this. I'm closing this issue because it's a duplicate of this: [https://github.com/FlutterFlow/flutterflow-issues/issues/3270](https://github.com/FlutterFlow/flutterflow-issues/issues/3270)

You can follow the original issue there.

**Closed as not planned** 2024-07-24 11:23 UTC
Labels: closed: duplicate

**Comment by dajana0** [comment] 2024-07-24 11:27
@msusviela when do you expect to release the fix? I have duplicated the issue because the was no response on [#3270](https://github.com/FlutterFlow/flutterflow-issues/issues/3270 )

**Comment by leighajarett** [comment] 2024-07-26 20:29
@dajana0 can you please check and see if this is working for you now?
