### ISSUE TITLE
 Does not create page by AI

### ISSUE THREAD

**Issue by rlmuz** [FlutterFlow/flutterflow-issues#1305] opened 2023-08-18 16:04 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm trying to create a page with AI, it returns an error saying that my daily limit is over. I'm testing the paid plan, and I haven't created any pages via AI today

### Expected Behavior

I believe that in the paid plan the creation of pages by AI is unlimited

### Steps to Reproduce

1- I have an existing project, I want to create a new page using AI
2- I click on the AI generated Page icon
3- I describe my page in the prompt
4- The page is generated
5- click on insert page
6-I name the page
7- returns a message: "AI Gen page insert limit reached for today. Please try again tomorrow."

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

does not generate an error, it just does not insert the page

### Context

It does not generate an error code, it simply does not create the page.

### Visual documentation

<img width="692" alt="erro FlutterFlow" src="https://github.com/FlutterFlow/flutterflow-issues/assets/142610349/743e3fd6-f8e7-41f9-8b90-246c5dfa2d37">

### Environment

```markdown
- FlutterFlow version: 3.1 
- Platform: Web
- Browser name and version: Google ChromeVersão 115.0.5790.171 (Oficial Version) 64 bits
- Operating system and version affected: Windows 10 Home version 22H2
```

**Comment by SameerShahzad99** [comment] 2023-08-22 20:09
Thank you for reporting this bug, I was unable to reproduce this issue on my end ,but i can confirm that similar problem was faced by another user.

**Comment by ArinDavidsson** [comment] 2023-08-25 04:14
### The AI page generator not working
I have the exact same problem!! Or sometimes even before they have made the page I get an error saying:
'The page could not be generated properly. '

**Comment by sbis04** [comment] 2023-08-27 15:39
I think our current AI Page Gen limit is 5 generations/day and 3 inserts/day, if you exceed that then you would get the "limit reached" error.

And, the "the page could not be generated properly" error actually means that the output that was generated based on OpenAI wasn't parsable properly to a working FlutterFlow layout. Since we are dealing with AI which gives a non-deterministic output, this is expected in some cases, but we are constantly optimizing the AI-based generation to minimize it.

**Comment by ArinDavidsson** [comment] 2023-08-27 18:12
I changed the text that I was going give to something much simpler, it did make the page but as soon as I pressed save, it gave me an error saying: 'AI Gen page insert page reach limit for today. Please try again tomorrow.' The thing that is most annoying is that I still had 4/5 page generators left and when That page had been generated and it still disappeared (because of your app), I only had 3/5 page generators left. So not only did the page not get saved but also you took one of my 5 generators as I had used it or something!! smh. Please fix this error in your app.

**Comment by sbis04** [comment] 2023-09-23 00:06
Hi @rlmuz, thanks for reporting the issue! It should be fixed in the next update! 😊

**Closed** 2023-09-23 00:05 UTC
Labels: status: confirmed, status : project specific
