### ISSUE TITLE
ios Deployment: Step 6 script `Install pods` exited with status code 1 - update ios pod

### ISSUE THREAD

**Issue by MyTechAgent** [FlutterFlow/flutterflow-issues#2758] opened 2024-04-18 06:58 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

No longer deploying to apple store.

### Expected Behavior

Successful deployment message on deployment

### Steps to Reproduce

1. tried to update dependencies around google maps.
2. tried ipad app deployment, web and windows desktop app.
3. tried changing version codes
4. tried deploying a completely different project that is already published on ios and since it doesn't have google maps flutter ios it deploys fine.
5. Found apple has changed minimum requirements - [https://developers.google.com/maps/documentation/ios-sdk/release-notes](https://developers.google.com/maps/documentation/ios-sdk/release-notes)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hcmAx491ofpE1876dvlahjw5Jnl6a4EZlOxraCsofePrOpkAf8/7UFtUON/kTG9fMGCJknIX/Mr8uPDhCcIEAAWcGYhdybl1FhXdQmKXSqqkBb63b0B8RPJRGGLA4J2C3Ap5JtJfLl0swE2UF+qvbD7XCb70DlUnQuaeXdeK2SrDX1iXc2URm05KZDPz

### Context

i can no longer deploye to apple ios without having a mac. This is stopping me from testing the app as I use custom widgets and functions that are only ios compatible.

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/32baf14e-b56d-44c1-9b18-0090098e82c6/9e4e933f-269b-47e2-a6b1-42df77f3723c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zMmJhZjE0ZS1iNTZkLTQ0YzEtOWIxOC0wMDkwMDk4ZTgyYzYvOWU0ZTkzM2YtMjY5Yi00N2UyLWE2YjEtNDJkZjc3ZjM3MjNjIiwiaWF0IjoxNzEzNDI5NTI0LCJleHAiOjMzMjgzOTg5NTI0fQ.es4MZDIoRz4NvnK2W-ntTHXRU57_0eSCzCOGQVFLzYg)

Error:
\`Codemagic Deploy Output
Failed Step: Install pods

┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available! │
│ │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘

╔════════════════════════════════════════════════════════════════════════════╗
  ║ Welcome to Flutter! - [https://flutter.dev](https://flutter.dev) ║
  ║ ║
  ║ The Flutter tool uses Google Analytics to anonymously report feature usage ║
  ║ statistics and basic crash reports. This data is used to help improve ║
  ║ Flutter tools over time. ║
  ║ ║
  ║ Flutter tool analytics are not sent on the very first run. To disable ║
  ║ reporting, type 'flutter config --no-analytics'. To display the current ║
  ║ setting, type 'flutter config'. If you opt out of analytics, an opt-out ║
  ║ event will be sent, and then no further information will be sent by the ║
  ║ Flutter tool. ║
  ║ ║
  ║ By downloading the Flutter SDK, you agree to the Google Terms of Service. ║
  ║ The Google Privacy Policy describes how data is handled in this service. ║
  ║ ║
  ║ Moreover, Flutter includes the Dart SDK, which may send usage metrics and ║
  ║ crash reports to Google. ║
  ║ ║
  ║ Read about data we send with crash reports: ║
  ║ [https://flutter.dev/docs/reference/crash-reporting](https://flutter.dev/docs/reference/crash-reporting) ║
  ║ ║
  ║ See Google's privacy policy: ║
  ║ [https://policies.google.com/privacy](https://policies.google.com/privacy) ║
  ║ ║
  ║ To disable animations in this tool, use ║
  ║ 'flutter config --no-cli-animations'. ║
  ╚════════════════════════════════════════════════════════════════════════════╝

Resolving dependencies...

* \_fe_analyzer_shared 61.0.0 (67.0.0 available)
* \_flutterfire_internals 1.3.24 (1.3.30 available)
* analyzer 5.13.0 (6.4.1 available)
* archive 3.4.10
* args 2.5.0
* arkit_plugin 1.0.7
* async 2.11.0
* auto_size_text 3.0.0
* boolean_selector 2.1.1
* cached_network_image 3.3.1
* cached_network_image_platform_interface 4.0.0
* cached_network_image_web 1.1.1
* carousel_slider 4.2.1
* characters 1.3.0
* checked_yaml 2.0.3
* chewie 1.7.1 (1.8.1 available)
* cli_util 0.4.1
* clock 1.1.1
* cloud_firestore 4.15.7 (4.17.0 available)
* cloud_firestore_platform_interface 6.1.8 (6.2.0 available)
* cloud_firestore_web 3.10.7 (3.12.0 available)
* cloud_functions 4.6.7 (4.7.2 available)
* cloud_functions_platform_interface 5.5.18 (5.5.24 available)
* cloud_functions_web 4.7.1 (4.9.2 available)
* collection 1.18.0
* convert 3.1.1
* cross_file 0.3.3+8 (0.3.4+1 available)
* crypto 3.0.3
* csslib 1.0.0
* csv 5.0.1 (6.0.0 available)
* cupertino_icons 1.0.8
* dbus 0.7.10
* dropdown_button2 2.3.9
* easy_debounce 2.0.1 (2.0.3 available)
* equatable 2.0.5
* fake_async 1.3.1
* ffi 2.1.2
* file 7.0.0
* file_picker 6.1.1 (8.0.0+1 available)
* file_selector_linux 0.9.2+1
* file_selector_macos 0.9.3+3
* file_selector_platform_interface 2.6.2
* file_selector_windows 0.9.3+1
* firebase_auth 4.17.7 (4.19.2 available)
* firebase_auth_platform_interface 7.1.7 (7.2.3 available)
* firebase_auth_web 5.9.7 (5.11.2 available)
* firebase_core 2.26.0 (2.30.0 available)
* firebase_core_platform_interface 5.0.0
* firebase_core_web 2.11.5 (2.15.0 available)
* firebase_messaging 14.7.18 (14.8.2 available)
* firebase_messaging_platform_interface 4.5.26 (4.5.32 available)
* firebase_messaging_web 3.6.7 (3.8.2 available)
* firebase_performance 0.9.3+16 (0.9.4+2 available)
* firebase_performance_platform_interface 0.1.4+24 (0.1.4+30 available)
* firebase_performance_web 0.1.4+24 (0.1.6+2 available)
* firebase_storage 11.6.8 (11.7.2 available)
* firebase_storage_platform_interface 5.1.11 (5.1.17 available)
* firebase_storage_web 3.7.2 (3.9.2 available)
* fixnum 1.1.0
* flutter 0.0.0 from sdk flutter
* flutter_animate 4.1.1+1 (4.5.0 available)
* flutter_background_service 5.0.5
* flutter_background_service_android 6.2.2
* flutter_background_service_ios 5.0.0
* flutter_background_service_platform_interface 5.0.0
* flutter_cache_manager 3.3.1
* flutter_card_swiper 6.0.0 (7.0.0 available)
* flutter_google_places 0.4.0 from git [https://github.com/ShehanYjoz/flutter_google_places.git](https://github.com/ShehanYjoz/flutter_google_places.git) at 52ddef
* flutter_launcher_icons 0.13.1
* flutter_lints 3.0.0 (3.0.2 available)
* flutter_local_notifications 17.0.1
* flutter_local_notifications_linux 4.0.0+1
* flutter_local_notifications_platform_interface 7.0.0+1
* flutter_localizations 0.0.0 from sdk flutter
* flutter_native_splash 2.3.1 (2.4.0 available)
* flutter_plugin_android_lifecycle 2.0.17 (2.0.19 available)
* flutter_rating_bar 4.0.1
* flutter_secure_storage 8.0.0 (9.0.0 available)
* flutter_secure_storage_linux 1.2.0
* flutter_secure_storage_macos 3.0.1
* flutter_secure_storage_platform_interface 1.0.2
* flutter_secure_storage_web 1.1.2
* flutter_secure_storage_windows 2.1.1 (3.0.0 available)
* flutter_staggered_grid_view 0.7.0
* flutter_stripe 9.4.0 (10.1.1 available)
* flutter_stripe_web 4.4.0 (5.1.0 available)
* flutter_test 0.0.0 from sdk flutter
* flutter_web_plugins 0.0.0 from sdk flutter
* font_awesome_flutter 10.6.0 (10.7.0 available)
* freezed_annotation 2.4.1
* from_css_color 2.0.0
* geoflutterfire2 2.3.15
* geolocator 10.1.0 (11.0.0 available)
* geolocator_android 4.4.0 (4.5.4 available)
* geolocator_apple 2.3.2 (2.3.7 available)
* geolocator_platform_interface 4.2.0 (4.2.2 available)
* geolocator_web 2.2.0 (3.0.0 available)
* geolocator_windows 0.2.3
* glob 2.1.2
* go_router 12.1.3 (13.2.4 available)
* google_api_headers 2.0.3 (4.0.0 available)
* google_fonts 6.1.0 (6.2.1 available)
* google_generative_ai 0.1.0 (0.3.0 available)
* google_identity_services_web 0.2.2 (0.3.1+1 available)
* google_maps 6.3.0 (7.1.0 available)
* google_maps_flutter 2.5.3 (2.6.1 available)
* google_maps_flutter_android 2.7.0
* google_maps_flutter_ios 2.6.0
* google_maps_flutter_platform_interface 2.6.0
* google_maps_flutter_web 0.5.4+3 (0.5.6+2 available)
* google_maps_webservice 0.0.20-nullsafety.5 from git [https://github.com/ShehanYjoz/google_maps_webservice.git](https://github.com/ShehanYjoz/google_maps_webservice.git) at 1588c2
* google_sign_in 6.1.5 (6.2.1 available)
* google_sign_in_android 6.1.20 (6.1.23 available)
* google_sign_in_ios 5.6.4 (5.7.6 available)
* google_sign_in_platform_interface 2.4.2 (2.4.5 available)
* google_sign_in_web 0.12.1 (0.12.4 available)
* html 0.15.4
  ! http 1.2.0 (overridden) (1.2.1 available)
* http_parser 4.0.2
* image 4.1.7
* image_picker 1.0.4 (1.1.0 available)
* image_picker_android 0.8.8 (0.8.10 available)
* image_picker_for_web 3.0.1 (3.0.4 available)
* image_picker_ios 0.8.8+2 (0.8.10 available)
* image_picker_linux 0.2.1+1
* image_picker_macos 0.2.1+1
* image_picker_platform_interface 2.9.1 (2.10.0 available)
* image_picker_windows 0.2.1+1
* infinite_scroll_pagination 4.0.0
* intl 0.18.1 (0.19.0 available)
* iregexp 0.1.1 (0.1.2 available)
* js 0.6.7 (0.7.1 available)
* js_wrapping 0.7.4
* json_annotation 4.8.1
* json_path 0.6.2 (0.7.1 available)
* leak_tracker 10.0.0 (10.0.5 available)
* leak_tracker_flutter_testing 2.0.1 (3.0.5 available)
* leak_tracker_testing 2.0.1 (3.0.1 available)
* lints 3.0.0
* location 5.0.3 (6.0.1 available)
* location_platform_interface 3.1.2 (4.0.0 available)
* location_web 4.2.0 (5.0.1 available)
* logging 1.2.0
* lottie 2.7.0 (3.1.0 available)
* matcher 0.12.16+1
* material_color_utilities 0.8.0 (0.11.1 available)
* maybe_just_nothing 0.5.3
* meta 1.11.0 (1.14.0 available)
* mime 1.0.5
* mime_type 1.0.0
* nested 1.0.0
* octo_image 2.0.0
* package_config 2.1.0
* package_info_plus 4.2.0 (7.0.0 available)
* package_info_plus_platform_interface 2.0.1 (3.0.0 available)
* page_transition 2.1.0
* path 1.9.0
* path_provider 2.0.14 (2.1.3 available)
* path_provider_android 2.0.25 (2.2.4 available)
* path_provider_foundation 2.2.2 (2.3.2 available)
* path_provider_linux 2.1.11 (2.2.1 available)
* path_provider_platform_interface 2.0.6 (2.1.2 available)
* path_provider_windows 2.1.7 (2.2.1 available)
* percent_indicator 4.2.2 (4.2.3 available)
* petitparser 5.4.0 (6.0.2 available)
* photo_view 0.14.0 (0.15.0 available)
* pigeon 11.0.1 (18.0.0 available)
* platform 3.1.4
* plugin_platform_interface 2.1.8
  ! pointer_interceptor 0.10.1 (overridden)
* pointer_interceptor_ios 0.10.0+2
* pointer_interceptor_platform_interface 0.10.0+1
* pointer_interceptor_web 0.10.1+2 (0.10.2 available)
* pointycastle 3.8.0
* provider 6.0.5 (6.1.2 available)
* pub_semver 2.1.4
* quiver 3.2.1
* rfc_6901 0.1.1 (0.2.0 available)
* rxdart 0.27.7
* sanitize_html 2.1.0
* shared_preferences 2.2.2 (2.2.3 available)
* shared_preferences_android 2.2.1 (2.2.2 available)
* shared_preferences_foundation 2.3.4 (2.3.5 available)
* shared_preferences_linux 2.3.2
* shared_preferences_platform_interface 2.3.1 (2.3.2 available)
* shared_preferences_web 2.2.1 (2.3.0 available)
* shared_preferences_windows 2.3.2
* sign_in_with_apple 4.3.0 (6.1.0 available)
* sign_in_with_apple_platform_interface 1.0.0 (1.1.0 available)
* sign_in_with_apple_web 1.0.1 (2.1.0 available)
* sky_engine 0.0.99 from sdk flutter
* sliver_tools 0.2.12
* smooth_page_indicator 1.1.0
* source_span 1.10.0
* sprintf 7.0.0
* sqflite 2.2.6 (2.3.3 available)
* sqflite_common 2.5.4
* stack_trace 1.11.1
* stream_channel 2.1.2
* stream_transform 2.1.0
* string_scanner 1.2.0
* stripe_android 9.4.0 (10.1.1 available)
* stripe_ios 9.4.1 (10.1.0 available)
* stripe_js 3.2.0 (3.4.0 available)
* stripe_platform_interface 9.4.0 (10.1.1 available)
* synchronized 3.1.0 (3.1.0+1 available)
* term_glyph 1.2.1
* test_api 0.6.1 (0.7.1 available)
* timeago 3.2.2 (3.6.1 available)
* timezone 0.9.2
* typed_data 1.3.2
* universal_io 2.2.2
* url_launcher 6.2.5 (6.2.6 available)
* url_launcher_android 6.3.0 (6.3.1 available)
* url_launcher_ios 6.2.5
* url_launcher_linux 3.1.1
* url_launcher_macos 3.1.0
* url_launcher_platform_interface 2.3.2
* url_launcher_web 2.2.3 (2.3.1 available)
* url_launcher_windows 3.1.1
  ! uuid 4.4.0 (overridden)
* vector_math 2.1.4
* video_player 2.8.1 (2.8.6 available)
* video_player_android 2.4.10 (2.4.14 available)
* video_player_avfoundation 2.5.1 (2.5.7 available)
* video_player_platform_interface 6.2.1 (6.2.2 available)
* video_player_web 2.1.2 (2.3.0 available)
* vm_service 13.0.0 (14.2.1 available)
* wakelock_plus 1.1.4 (1.2.4 available)
* wakelock_plus_platform_interface 1.2.1
* watcher 1.1.0
* web 0.4.2 (0.5.1 available)
* webview_flutter 4.7.0
* webview_flutter_android 3.15.0 (3.16.0 available)
* webview_flutter_platform_interface 2.10.0
* webview_flutter_wkwebview 3.12.0 (3.13.0 available)
* webviewx_plus 0.5.0
* win32 5.4.0
* xdg_directories 1.0.4
* xml 6.3.0 (6.5.0 available)
* yaml 3.1.2
  Changed 238 dependencies!
  120 packages have newer versions incompatible with dependency constraints.
  Try `flutter pub outdated` for more information.
  Analyzing dependencies
  Pre-downloading: `FirebaseFirestore` from `https://github.com/invertase/firestore-ios-sdk-frameworks.git`, tag `10.22.0`
  cloud_firestore: Using Firebase SDK version '10.22.0' defined in 'firebase_core'
  cloud_functions: Using Firebase SDK version '10.22.0' defined in 'firebase_core'
  firebase_auth: Using Firebase SDK version '10.22.0' defined in 'firebase_core'
  firebase_core: Using Firebase SDK version '10.22.0' defined in 'firebase_core'
  firebase_messaging: Using Firebase SDK version '10.22.0' defined in 'firebase_core'
  firebase_performance: Using Firebase SDK version '10.22.0' defined in 'firebase_core'
  firebase_storage: Using Firebase SDK version '10.22.0' defined in 'firebase_core'
  Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org/`

CocoaPods 1.15.0 is available.
To update use: `gem install cocoapods`

For more information, see [https://blog.cocoapods.org](https://blog.cocoapods.org) and the CHANGELOG for this version at [https://github.com/CocoaPods/CocoaPods/releases/tag/1.15.0](https://github.com/CocoaPods/CocoaPods/releases/tag/1.15.0)

\[!\] CocoaPods could not find compatible versions for pod "google_maps_flutter_ios":
  In Podfile:
    google_maps_flutter_ios (from `.symlinks/plugins/google_maps_flutter_ios/ios`)

Specs satisfying the `google_maps_flutter_ios (from `.symlinks/plugins/google_maps_flutter_ios/ios`)` dependency were found, but they required a higher minimum deployment target.

Build failed :|
Step 6 script `Install pods` exited with status code 1\`

### Additional Info

I was previously able to deploy prior to the flutter update coming through.

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f624793c-a76e-402e-8763-8e686a5dd281/e082d712-f114-408a-9f84-8e6ceb5ba2fa?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mNjI0NzkzYy1hNzZlLTQwMmUtODc2My04ZTY4NmE1ZGQyODEvZTA4MmQ3MTItZjExNC00MDhhLTlmODQtOGU2Y2ViNWJhMmZhIiwiaWF0IjoxNzEzNDI5NTI0LCJleHAiOjMzMjgzOTg5NTI0fQ.h8k9D2CsV0IyiSm1joxy827CZLTM2bE03ihMSesrwtc)

### Environment

```markdown
- FlutterFlow version: 4.1.34+
- Platform: web, ipad, desktop
- Browser name and version: edge, chrome most recent version for both
- Operating system and version affected: windows
```

**Comment by DefiLable** [comment] 2024-04-19 07:16
Same issue for me

**Comment by MyTechAgent** [comment] 2024-04-19 08:06
Pretty sure it’s to do with the minimum requirements of Apple change and most dependencies having to be changed now due to it. I noticed a lot of dependency updates come through on pub. At the moment I can only suggest downloading VMware if you don’t have a Mac and get an iOS image to manually push through Xcode. Hopefully someone will jump on this in the short term :).

**Comment by ahnsunnyyoung** [comment] 2024-04-19 09:40
I had a same issue, and found this. https://community.flutterflow.io/troubleshooting/post/cannot-deploy-to-app-store---failed-step-install-pods-nWfLtDOotGM51JH

Try manually set version number. It resolved my problem!

**Comment by DefiLable** [comment] 2024-04-19 12:31
Hello everyone,

If you encounter deployment issues with your Flutter app, I have found a solution that worked for me which I'd like to share. This involves a few updates both on GitHub and in the iOS-specific files of your Flutter project.

Step 1: Deploy from GitHub

Ensure your latest code is pushed to GitHub and set for deployment. This ensures that all changes are correctly synced and ready for the next steps.

Step 2: Update the Podfile

Navigate to the iOS directory in your Flutter project and open the Podfile. You will need to update the platform version to ensure compatibility with newer iOS versions. Change the line:

ruby
Copy code
platform :ios, '13.0'
to

ruby
Copy code
platform :ios, '14.1'
Step 3: Modify the Xcode Project File

Next, go to the /ios/Runner.xcodeproj/project.pbxproj file. Here, you need to update the deployment target to match the Podfile update. Change all instances of:

plaintext
Copy code
IPHONEOS_DEPLOYMENT_TARGET = 13.0;
to

plaintext
Copy code
IPHONEOS_DEPLOYMENT_TARGET = 14.1;
This ensures that the iOS deployment target is consistent across your project settings, preventing potential conflicts during the build process.

After making these changes, try redeploying your app. This resolved the deployment issues in my case and might help you too. Let me know if you have any questions or need further assistance!

**Comment by DefiLable** [comment] 2024-04-19 12:31
Hello everyone,

If you encounter deployment issues with your Flutter app, I have found a solution that worked for me which I'd like to share. This involves a few updates both on GitHub and in the iOS-specific files of your Flutter project.

Step 1: Deploy from GitHub

Ensure your latest code is pushed to GitHub and set for deployment. This ensures that all changes are correctly synced and ready for the next steps.

Step 2: Update the Podfile

Navigate to the iOS directory in your Flutter project and open the Podfile. You will need to update the platform version to ensure compatibility with newer iOS versions. Change the line:

platform :ios, '13.0'
to


platform :ios, '14.1'

Step 3: Modify the Xcode Project File

Next, go to the /ios/Runner.xcodeproj/project.pbxproj file. Here, you need to update the deployment target to match the Podfile update. Change all instances of:


IPHONEOS_DEPLOYMENT_TARGET = 13.0;
to

IPHONEOS_DEPLOYMENT_TARGET = 14.1;

This ensures that the iOS deployment target is consistent across your project settings, preventing potential conflicts during the build process.

After making these changes, try redeploying your app. This resolved the deployment issues in my case and might help you too. Let me know if you have any questions or need further assistance!

**Comment by MyTechAgent** [comment] 2024-04-19 13:05
mate you are a genius thank you, I learned a new skill too, which I am sure I can leverage git more than I have been. Giving it a crack now, publishing now.

**Comment by MyTechAgent** [comment] 2024-04-19 13:30
spoke to soon. Seems like to merge the branches you need to be a team. Back to trying to spin up a vm to test this...

**Comment by DefiLable** [comment] 2024-04-19 14:46
yes sorry I didn't mentionned it but I already had a vm to signup as a team

**Comment by MyTechAgent** [comment] 2024-04-19 15:23
kk looks like codemagic.io is actually free. It allows you to connect straight to the git. I would advise trying this as it's the same process as FF. 

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/113911679/5464cb27-7aec-4654-be42-2a641a15517c)

**Comment by MyTechAgent** [comment] 2024-04-19 23:47
@DefiLable I just upgraded... did you merge than push to git and adjusted the pods ect, than deployed? Trying to figure out the workflow you used to get it to publish

**Comment by Nic61** [comment] 2024-04-22 10:36
It works from FF web but not from the Mac App. It seems they have different flutter versionings

**Comment by rzambroni** [comment] 2024-04-22 18:50
Hey everyone,  So sorry you are experiencing this issue. I can't replicate this on a blank project. Are you still experiencing it? given the nature of the issue I would encourage you to follow up with our support team so you can validate the configurations specific to your project with them. You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow.

**Comment by MyTechAgent** [comment] 2024-04-22 22:32
Morning,
I will try that as it’s happening across all my projects. Could be that the projects are no longer updating but I have confirmed it’s the pod file minimum requirements that is throwing it all out of whack. The new minimum is 14.1 and not sure if it’s all dependencies or just google maps. I have spent the last 4 days trying to work out workarounds. I will spin up a new project and copy everything across to see if that helps….
Kind Regards, 


Sent from Yahoo Mail for iPhone


On Tuesday, April 23, 2024, 4:51 AM, rzambroni ***@***.***> wrote:




Hey everyone, So sorry you are experiencing this issue. I can't replicate this on a blank project. Are you still experiencing it? given the nature of the issue I would encourage you to follow up with our support team so you can validate the configurations specific to your project with them. You can do that either by email: ***@***.*** or using the in-app chat inside of FlutterFlow.

**Comment by MyTechAgent** [comment] 2024-04-23 03:47
Hey All,

I have message the flutterflow team as above. Still struggling to see why this would be placed as project specific. If it was just me than yes but there is others having the same issue? Either way I will keep everyone up to date.

**Comment by MyTechAgent** [comment] 2024-04-24 13:17
So still no update on this but I managed to get GitHub linked up with codemagic. During this process I found out why it worked on a blank project and why it's only impacting particular users. The package google_maps_flutter_iOS will no longer deploy for anyone using 14.1 or below. This changes to apple's policy has changed some but not all dependencies. The only way I have found is to have a physical Mac, I change the pod files as stated above, install brew cocoapods files into the same folder as podfile, than configure Xcode (launch_page, permissions ect). After this code magic should accept it once you configure code magic. Unfortunately the workflow is not as fluent as FF but if you use a package that is impacted by this then it's the only way.. If you add your google maps into I bet you can reproduce the issue ;).

**Comment by rpock** [comment] 2024-04-24 15:26
I can confirm that there is a deployment target issue on iOS for google maps. Upgrading it to 14.0 solves the issue in my case.

<img width="708" alt="Bildschirmfoto 2024-04-24 um 17 21 57" src="https://github.com/FlutterFlow/flutterflow-issues/assets/63868258/7fcc752a-11f6-4388-aa7a-5144ba257ab7">

**Comment by ayjayem** [comment] 2024-04-29 01:50
I am experiencing the same issue. I tried upgrading the minimum deployment target to 14.1 as described, but this didn't solve the problem in my case. I've tried deploying from both the desktop agent and the web app.

**Comment by MyTechAgent** [comment] 2024-04-29 03:17
Make sure when you upgrade it, you use control + f to search for 13.0 and than use the replace all with 14.1. Once you get this sorted and working the first time you can than go to Xcode cloud.

**Comment by ayjayem** [comment] 2024-04-29 04:05
Appreciate it - did this, but with no luck directly through FF. Using codemagic.io after having updated from 13.0 to 14.1 is working for me though, so not blocked - but will be nice to see this resolved in FF soon hopefully.

**Comment by MyTechAgent** [comment] 2024-04-29 04:08
Ahh yes did the same thing but hit the limit so went to Xcode cloud with 25 build hours free each month. Tbh I think FF is burning a little at the moment with the major update. I wouldn't expect this to be solved anytime soon as most people don't get to the deployment stage. Going of this though I setup a GitHub automation to auto push to iOS store. Hope I am wrong but a Quick Look around will show that they will need to fix a fair few things to update the pods. Appple has thrown a grenade in the works with the policy update, they are also requiring additional privacy files to be uploaded that FF have advised they are working on

**Comment by ayjayem** [comment] 2024-04-29 04:31
Oof, challenging.

I spoke too soon as well - Codemagic build submitted successfully and processed just fine, but crashes in TestFlight.

I did notice though just now that the minimum deployment target is also listed in ios/Flutter/AppFrameworkInfo.plist, which I just corrected... hoping that along with the updates to the other references of the deployment target will remedy.

**Comment by ayjayem** [comment] 2024-04-29 22:48
Yeah sadly no luck. This issue is still outstanding for me -- really hope that the FlutterFlow team can address, as I'm completely blocked at the moment.

**Comment by MyTechAgent** [comment] 2024-04-30 00:11
Someone else may need to create a new git post to report this as I worry the FF team have no oversight of this as it's marked as project specific by the last contributor.. which may only show up as an impact to one user.. we need it to be marked as an incident if we want action on it. Otherwise just do workarounds. From how this was handled I ended up stopping payments to FF and went back to coding manually on top of the infrastructure FF already built. Don't see a point if I can't deploy from there :). ![image](https://github.com/FlutterFlow/flutterflow-issues/assets/113911679/27f12259-cbb8-4b74-b3fa-05b4ff3a102a)

**Comment by paramparim** [comment] 2024-05-03 13:20
Hello! I faced the same problem. It helped me to resubmit for publication with the same version number and build number for which this error occurred.

**Comment by rpock** [comment] 2024-05-14 07:00
What do you think about the following idea, to specify the deployment target for iOS in the advanced settings like the advanced settings for Android? 
 
 
<img width="290" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/63868258/8520a899-38a0-4405-bd97-2bf6198e6b24">

**Comment by ayjayem** [comment] 2024-05-14 13:37
This makes sense to me.

**Comment by leighajarett** [comment] 2024-05-15 21:44
Thanks for this feedback, I do think we need to add that as an option. We track features separately internally so I will close this issue - but this has been added to our backlog. Thanks!

**Closed** 2024-05-15 21:45 UTC
Labels: status: can't reproduce, needs technical triage

**Comment by DefiLable** [comment] 2024-05-15 21:48
Hi Leigha,
It is also blocking one of your major feature when using a Mac : testing on a simulated iPhone,
It would be great If you handle the problem !
Thank you !

**Comment by leighajarett** [comment] 2024-05-15 21:59
You can test on iOS simulator using local run 🙂

**Comment by DefiLable** [comment] 2024-05-15 22:03
I wish I could, but because it’s not installing pods I can only test on simulator after downloading the code, modifying the deployment target and then launch simulator but I can’t use local run with the simulator.
I can on an android simulated device but not on an iPhone simulated device…

**Comment by DefiLable** [comment] 2024-05-15 22:03
I have the same error when I try to local run

**Comment by leighajarett** [comment] 2024-05-15 22:28
Please reach out to our support team who can better advise support@flutterflow.io

**Comment by MyTechAgent** [comment] 2024-05-16 03:21
I will try and write a guide tonight on how to fix the issue in the workaround with pods. There is a couple of things you will need to do in order to get it to work. Keep in mind you will need a Mac.

**Comment by leighajarett** [comment] 2024-05-17 12:47
That sounds amazing, thank you!

**Comment by MyTechAgent** [comment] 2024-05-28 01:00
Hi All,

Sorry for the tutorial for the workaround taking a while. After I figured out the solution I ended up working on my MVP to try and catch up on all the lost time from this issue still being an issue. Please find attached the documentation. 
[Step-by-Step_Tutorial_Setting_Up_CodeMagic_or_Xcode_Cloud.docx](https://github.com/FlutterFlow/flutterflow-issues/files/15462677/Step-by-Step_Tutorial_Setting_Up_CodeMagic_or_Xcode_Cloud.docx)
