### ISSUE TITLE
Grey screen on dynamically generated children of a ListView/Row/Column if the children have DateTime in it

### ISSUE THREAD

**Issue by nadavgover** [FlutterFlow/flutterflow-issues#2062] opened 2023-12-26 16:22 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Grey screen on dynamically generated children of a ListView/Row/Column if the children have DateTime in it. On Android (but not on FlutterFlow's test mode), a grey screen is sometimes shown instead of the children themselves. I don't know why it's only sometimes, and sometimes only on part of the children and not all of them, usually the children that are not shown and needs scroll to be in the view.
I'm not 100% sure it's related to DateTime and I'm not sure why it's not consistent.

### Expected Behavior

All dynamically generated children are shown on Android (and all platforms).

### Steps to Reproduce

1. Create a new page
2. Create a list of DateTimes, by calling an api or mocking data (or however)
3. Display the DateTime in a Text widget and use DateTime Format of your choice
4. Run on test mode and check that it works
5. Build APK and run on an actual Android device and check if works (you may need to do this part several times because it's not consistent)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4okcrqw4xgrulc7aXqdvlahSQWH1N/U40rmMpBZzUYF5SuCLMqY8mnP1BuUsSqSnNLPmeMp14EpcruuODPDvEFAxGdQaZJ/6t2ag3dfDqRVpuTF7qoeHB5O8JXJhWCy4mvgSRCBPVeSGQW70y2OOSuThDZNO/vIUQ8Sq/LZO4=

### Context

A feature in my app that I can't implement

### Visual documentation

![WhatsApp Image 2023-12-26 at 18 20 41](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/1f5184a2-6302-481a-977a-dabd8e7c317e/b97146a0-5119-408f-bc22-85e027618fff?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xZjUxODRhMi02MzAyLTQ4MWEtOTc3YS1kYWJkOGU3YzMxN2UvYjk3MTQ2YTAtNTExOS00MDhmLWJjMjItODVlMDI3NjE4ZmZmIiwiaWF0IjoxNzA3MTQyNTI2LCJleHAiOjMzMjc3NzAyNTI2fQ.3GdFFtnFbIiLfXXXHeYGF3-0q6smxd6o9k5VHPet4ZY)

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: v4.0
- Platform: Android
- Browser name and version: Chrome
- Operating system and version affected: Android
```

**Comment by nadavgover** [comment] 2024-01-03 06:24
Still relevant

**Comment by nadavgover** [comment] 2024-01-20 18:25
Still relevant

**Comment by hariprasadms** [comment] 2024-02-12 11:52
Hi, Thanks for raising the issue. As it doesn't appear to be widespread and lacks a blank project with reproducible steps, it may have been overlooked. Considering its age, it's possible it has been addressed in recent FlutterFlow updates. Therefore, the issue is being closed. However, if you believe the problem persists, please reopen the issue by providing a blank project with the reproduced issue and share the project bug report code. This will facilitate a thorough investigation and prompt resolution. Thank you.

**Closed** 2024-02-12 11:53 UTC
Labels: status: can't reproduce, needs a blank project with issue setup
