### ISSUE TITLE
FlutterFlow showing blank screen on load

### ISSUE THREAD

**Issue by galenmyburgh** [FlutterFlow/flutterflow-issues#3298] opened 2024-07-02 09:48 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When app is build either in test debug mode or normal run mode it completes loading but just shows blank screen.
Even version that has been uploaded last week isn't working at link, also just shows blank page when you go to link.

### Expected Behavior

Web app is supposed to be running normally, actually open the app when in run or test mode, not just show empty screen with no errors.

### Steps to Reproduce

Link to FlutterFlow Project: https://app.flutterflow.io/project/d-e-v-tripleblue-app-01052024-qkqc9m
Link to deployed web app: dev.triple.blue
1. Ensure there are no errors in build.
2. Run / Test Run project
3. Arrive on blank screen after loading is completed

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT80lOfl3ItIn7wA15DUbsFFmjkXOVwjRYI7lexqEQ80G5uvE7QHduPVN1ptOcO4YWw+GkaYhmEJw8LSvobfCftcAE+BbLZywqVTWx/PRmGgaYiIEZe8fXBtGdlVCmq4yKSJsxVSGM5oXHs3wDuyfNmyfDbYNZT4DEYgRM+1KoP+n0qnLXnFKCYz2RYPGVuOEfljIVDq+f6QspZl1eTjzw==

### Visual documentation

![Uploading Screenshot 2024-07-02 at 11.42.18.png…]()

### Environment

```markdown
- FlutterFlow version: 4.1.65+
- Platform: Mac
- Browser name and version: Opera GX version 14.5
- Operating system and version affected: macOS Sonoma 14.5
```

**Comment by Alezanello** [comment] 2024-07-02 12:46
Hello!

Thank you for bringing this issue to our attention.

We have successfully reproduced the problem and will be forwarding it to our engineering team for further investigation and resolution.

We appreciate your patience and understanding.

Best regards,

Azanello

**Comment by Alezanello** [comment] 2024-07-02 14:41
Hello!<br><br>I'm back with an update after further review.<br><br>The issue appears to be related to the error shown by the `html_editor_enhanced` package, which has been deprecated with the latest versions of Flutter and Dart.<br><br>This issue is a duplicate of [#3290](https://github.com/FlutterFlow/flutterflow-issues/issues/3290).<br><br>Thank you for your understanding.<br>Best regards,<br>Azanello

**Closed as not planned by Alezanello** 2024-07-02 14:41 UTC
Labels: closed: duplicate
