### ISSUE TITLE
Bug Found with Package Dependencies in FlutterFlow Project

### ISSUE THREAD

**Issue by PjamaLama** [FlutterFlow/flutterflow-issues#3370] opened 2024-07-11 12:58 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Dear FlutterFlow Support Team,

I hope this email finds you well.

After numerous attempts to solve this issue, i have come to the conclusion that this might be an bug on your side. 

I am encountering a package dependency issue in my FlutterFlow project. Here are the steps leading to the error:

Downloaded the appflowy_editor package from [pub.dev](http://pub.dev/).
Installed the html_editor_enhanced package through the FlutterFlow marketplace.
Ran the project and encountered the dependency error.
Uninstalled the widget with the amplify dependency.
Attempted to run in debug mode, but the same dependency error persists.
Below is the error message for your reference:

Because appflowy_editor >=1.0.0-dev.2 depends on visibility_detector ^0.4.0+2 and html_editor_enhanced >=2.5.0 <2.6.0 depends on visibility_detector ^0.3.3, appflowy_editor >=1.0.0-dev.2 is incompatible with html_editor_enhanced >=2.5.0 <2.6.0.
And because html_editor_enhanced >=2.6.0 depends on flutter_keyboard_visibility ^6.0.0 and get_hired depends on appflowy_editor ^3.1.0, html_editor_enhanced >=2.5.0 requires flutter_keyboard_visibility ^6.0.0.
So, because get_hired depends on both flutter_keyboard_visibility ^5.4.0 and html_editor_enhanced ^2.5.1, version solving failed.

Here is my project link, you have my permission to view my project code

[Jobs near me (gethired.flutterflow.app)](https://gethired.flutterflow.app/)

Could you please assist in resolving this issue?

### Expected Behavior

There sould not be a dependecy error as I have deleted the custom widget that used that dependency. 

### Steps to Reproduce

Downloaded the appflowy_editor package from [pub.dev](http://pub.dev/).
Installed the html_editor_enhanced package through the FlutterFlow marketplace.
Ran the project and encountered the dependency error.
Uninstalled the widget with the amplify dependency.
Attempted to run in debug mode, but the same dependency error persists.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kkfHq2ItNseFJ7qrpbcIwnmU4C084TL03pu0bFEggGLbrBIYMafekP0hoZ+28SlZHKEWGgj8JpdrLkoTXG/JdAy+CfN1bwbh9WwqVZF+/aoSyBbWeVEB6L95RJ0/H0J6nnRFSJut1cVY67DqmGN+vcHPXH5/7Zwh9f6PHaOI=

### Visual documentation

![marketpoalce](https://github.com/FlutterFlow/flutterflow-issues/assets/38701964/df02ed5c-98df-49e3-b751-4e570370112a)
![asdfasdfasdf](https://github.com/FlutterFlow/flutterflow-issues/assets/38701964/b5c08278-f89a-49e3-9d5e-580ee03daa3c)
![Capture](https://github.com/FlutterFlow/flutterflow-issues/assets/38701964/e82e24e4-ed73-45dc-8068-b2b9cf0c7670)

### Environment

```markdown
- FlutterFlow version: v4.1.7
- Platform: Web and Desktop
- Browser name and version: Edge  126.0.2592.87 (Official build) (64-bit)
- Operating system and version affected: windows 10 home, v2 of my code is affected
```

**Comment by Alezanello** [comment] 2024-07-11 13:03
Hello!<br><br>The issue appears to be related to the error shown by the `html_editor_enhanced` package, which has been deprecated with the latest versions of Flutter and Dart.<br><br>This issue is a duplicate of [#3290](https://github.com/FlutterFlow/flutterflow-issues/issues/3290).

**Closed as not planned** 2024-07-16 12:18 UTC
Labels: waiting for user response
