### ISSUE TITLE
Can upload custom fonts

### ISSUE THREAD

**Issue by pnaa** [FlutterFlow/flutterflow-issues#2569] opened 2024-03-21 11:00 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The upload file widget keeps spinning and doesn't open the file browser

### Expected Behavior

select a font file and upload.

### Steps to Reproduce

Upload custom font from Theme menu

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48ysmAuJdPxOVA+KX2acdKnjwWH0c7RK87iet+Tg88KOvUB+x/evWkVFJVYMOmT1VIfUSmmXMGwaGKkfL9G/I3Bw2ZRaJEzqhbWDnyfEm7UZOBCamwWUFtL91WClSX056FgBJ4JuhpSloS2zmmNu6UZD/UJKL4IlFISq/LZO4=

### Context

upload custom font

### Visual documentation

<img width="742" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/28980882/6ea2273f-09eb-4f20-a97f-e4244fada120">

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: Mobile
- Browser name and version: Chrome latest
- Operating system and version affected: MacOs latest
```

**Comment by rzambroni** [comment] 2024-04-09 15:15
Hey @pnaa, Thanks for your report, So sorry you are experiencing this issue. I was not able to reproduce this on a blank project, but it is replicable on yours. That's why I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. 

I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. 

If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. 

Thanks so much!

**Closed** 2024-04-12 17:03 UTC
Labels: closed: not a bug, status : project specific
