### ISSUE TITLE
Unable to deploy to web (Sudden breakage)

### ISSUE THREAD

**Issue by ValetCEO** [FlutterFlow/flutterflow-issues#3032] opened 2024-05-31 18:54 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The project won't deploy to web. Everything was fine and I'd deployed about 30 mins earlier and everything was fine. Now I get a long list of issues when I attempt to deploy to web. Is this a FF bug ? URGENT: We're launching on Monday 
<img width="1680" alt="Screenshot 2024-05-31 at 19 52 43" src="https://github.com/FlutterFlow/flutterflow-issues/assets/155745989/9fbc7c24-05b8-44b9-a50e-31b4feffa5f3">

### Expected Behavior

Should deploy to web

### Steps to Reproduce

Deploy to web

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Clcrqw5VOsdhE7c+BbPowoDwWHG4jRYEn1usbGAk0N5POD+x/fMnBN1dUOPGjSglif1n8gnIX/MryvvLxVO5dAwydRbZi+IdySQvdRkCXb5ShPK63b3MmO8NhI2an16W7mxRSPrZYZVog3Tn2f9i+YAHqNO/7CzAZBuaeXdeK2SrDX1iXc2URm05KZDPz

### Context

Unable to publish. Launching on Monday P1 URGENT

### Visual documentation

<img width="1680" alt="Screenshot 2024-05-31 at 19 52 43" src="https://github.com/FlutterFlow/flutterflow-issues/assets/155745989/f21b0d77-b97f-4cc7-a6bd-5f62480d5e26">

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected:macOS Monterey 12.2.1
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by malbrecht0792** [comment] 2024-05-31 19:00
Getting this too. The new FF update breaks my project

**Comment by ValetCEO** [comment] 2024-05-31 19:03
Yep looks like a lot of people are experiencing it.

**Comment by pittmanluke** [comment] 2024-05-31 19:06
same here

**Comment by rzambroni** [comment] 2024-05-31 19:25
Hey everyone! yes, we confirmed there might be an issue with projects with nullable values on datastructs, i'm marking this as a duplicate since it was previously reported.  Thanks

**Closed by rzambroni** 2024-05-31 19:25 UTC
Labels: status: needs triage
