### ISSUE TITLE
Tutorial keeps returning despite 'Done'

### ISSUE THREAD

**Issue by unibum** [FlutterFlow/flutterflow-issues#2771] opened 2024-04-19 20:57 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In the first project, I started going through tutorial.. renamed project, gone back to tutorial , next next keys, then done.. closed project. reopen project, tutorial back at step 1..
tried opening in web, app, cant get rid of it..
Would be nice if tutorial can be dragged onto 2nd screen.. need to enlarge it to see whats being done and covers project screen.. annoying as heck shrinking, expanding etc..

### Expected Behavior

Tutorial stops appearing when done.

### Steps to Reproduce

In the first project, I started going through tutorial.. renamed project, gone back to tutorial , next next keys, then done.. closed project. reopen project, tutorial back at step 1..
tried opening in web, app, cant get rid of it..

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

NA

### Context

close tutorial so it never returns unless I want to reopen it on purpose (somehow, cant close it so cant see if I can thus reopen it on demand)

### Visual documentation

is the BAU tutorial window, no image needed

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: in various versions
- Platform: web and desktop
- Browser name and version: chrome
- Operating system and version affected: win 11
```

**Comment by rzambroni** [comment] 2024-04-22 19:14
Hey @unibum, thanks for your feedback.

Unfortunately, the tutorial project currently doesn't track completion. If you'd like to continue adding features to your work and prefer to avoid the tutorial popups, I recommend duplicating the project from your projects page. This will allow you to work on it without the tutorial interruptions.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/0d6cb8e4-0d2d-4df1-a008-c2ecd23c4c57/2ead12ee-e41f-40b4-b421-36b41e0ed6d1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wZDZjYjhlNC0wZDJkLTRkZjEtYTAwOC1jMmVjZDIzYzRjNTcvMmVhZDEyZWUtZTQxZi00MGI0LWI0MjEtMzZiNDFlMGVkNmQxIiwiaWF0IjoxNzEzODEzMjQyLCJleHAiOjMzMjg0MzczMjQyfQ.zi2Cah8OdTR6ricsAcvgIJKo1fexaiL7dh7Y7lfz-7U " alt="image.png" width="479" height="398" />

Your suggestion is a valuable potential improvement to the tutorial, and I will submit a feature request so our team can consider it. I’m closing this ticket since it’s intended for tracking FlutterFlow bugs,  your feature request will be tracked in our internal backlog.

Thanks a lot!

**Comment by unibum** [comment] 2024-04-22 19:23
Hi, thank you for this, but the issue is I click 'done' once clicked through tutorial and get the #12 (last one from memory).. and it keeps coming back at step 1 of 12.. i.e. click done, close app, reopen app and tutorial appears again on step 1.. that seems like a  bug to me, the 'done' isnt doing anything..

**Comment by rzambroni** [comment] 2024-04-22 21:01
I understand, but currently, by design, the "DONE" button is just dismissing the hint, not saving the progress you made. If you want to continue working from the tutorial project template please Duplicate the project, or consider creating a new project from scratch. <br><br>

**Closed** 2024-04-23 14:43 UTC
Labels: closed: feature / enhancement request
