### ISSUE TITLE
JSONPath Issue on dynamic children

### ISSUE THREAD

**Issue by jarrydc22** [FlutterFlow/flutterflow-issues#398] opened 2023-01-24 01:50 UTC
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

When using an API call result with dynamic children that have a timestamp parameter on the child component it should be possible to use JSON path to populate the timestamp field like it is with other data types.

## Current behavior (required)

When using an API call result with dynamic children that have a timestamp parameter on the child component it doesn't give an option to use JSON path to locate the specific timestamp field.

## To Reproduce (required)

1. Create a list view
2. Add child component that has a timestamp component parameter
3. Make a backend query API call
4. Use the API call result to generate dynamic children
5. On the child component set the timestamp component parameter using variable and choose the child item. This comes up with the JSON path options when it's another data type but shows no options when it's a timestamp and can't set from variable using the dynamic data passed.

### Bug Report Code (required, generate from Widget Tree)

ITESi8mAsI5grtdd16rQacd6hQIhNmY1bZMnktVxRR4cIZjnOoYcPePSX0NKTtOWdwt6eFGajkwx0P+MvoSWKPUCBE2df7pNk/UwKlCvHAM=

## Context (required)

I can't pass timestamp to dynamic children and limits the ability to use date and time based on user location, currently have to change api calls to do all the timestamp formatting on the server side and doesn't allow for any dynamic behaviors in the app around timezone/location etc.

## Screenshots / recordings

![image](https://user-images.githubusercontent.com/123430021/214196416-7dfcfc06-7a9e-443e-a683-a0ca230f4494.png)

## Your environment

* Version of FlutterFlow used: 3.3.4
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Edge Version 109.0.1518.61 (Official build) (64-bit)
* Operating system and version (desktop or mobile): Desktop

**Comment by victoriahuang1** [comment] 2023-01-25 23:20
Hi @organicnz , thanks for the report. It seems like the API is returning an integer timestamp, which is different than how FlutterFlow's timestamps are represented (`DateTime`). There is no current built-in FlutterFlow functionality to turn integer timestamps into `DateTime` objects. However, you can implement a custom function to do this for you!

You can add the custom function (with return type being `Timestamp`) below:
```
DateTime millisecondsToDateTime(int timestamp) {
  /// MODIFY CODE ONLY BELOW THIS LINE

  return DateTime.fromMicrosecondsSinceEpoch(timestamp);

  /// MODIFY CODE ONLY ABOVE THIS LINE
}
```

Then, you can use this custom function in to your dynamic children, passing the integer timestamp into it as an argument.

I can add a feature request for native conversion between integer and `DateTime` timestamps, but will be closing this ticket since it is not a bug.
Hope this helps!

**Closed by victoriahuang1** 2023-01-25 23:20 UTC
Labels: status: needs triage

**Comment by victoriahuang1** [comment] 2023-01-26 17:44
> It is still a bug as I can pass a datetime format through the api but I still can't set the jsonpath for a timestamp field.

Hi @jarrydc22 this is the expected behavior today ^.

But we agree that being able to set the data type for json path fields would be very useful, and it is something that has already been on our list of new features to support :)

**Comment by jarrydc22** [comment] 2023-01-27 05:30
So just to confirm the expected behaviour is not to be able to set a timestamp data type from a json path and therefore you can’t pass timestamp data from an api call? Or am I missing a way to pass a timestamp from an api call to a timestamp field in the UI.

**Comment by victoriahuang1** [comment] 2023-01-27 05:46
> So just to confirm the expected behaviour is not to be able to set a timestamp data type from a json path and therefore you can’t pass timestamp data from an api call?

Yes, this is correct.

> Or am I missing a way to pass a timestamp from an api call to a timestamp field in the UI.

There is a workaround for this though with custom functions. If you add the custom function that I provided above, you will be able to use it to convert the values from the API response and use them as `Timestamp` data type values.

**Comment by jarrydc22** [comment] 2023-01-27 06:28
Thanks Victoria. I'll take a look at the custom function and test it out.
________________________________
