### ISSUE TITLE
DataType Issue

### ISSUE THREAD

**Issue by kjoyceee** [FlutterFlow/flutterflow-issues#232] opened 2022-12-15 20:01 UTC
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
Able to select field from a datatype 

## Current behavior (required)
Does not give you option to select a field once you select 'data structure type' under available options.

**Comment by isegal** [comment] 2022-12-15 20:43
Seeing the same problem.

When DataType is passed as a `Component Parameter`, trying to access variables from it looks like this:

<img width="305" alt="image" src="https://user-images.githubusercontent.com/4561505/207962426-f6af3347-7c1c-4125-b662-9c56f4df39fd.png">

When it is a list item of `DataType`s (eg returned by a custom function and passed to `Generate Dynamic Children`), it will look like this:

<img width="408" alt="image" src="https://user-images.githubusercontent.com/4561505/207962830-0731754d-092a-4c7f-b9d4-a0b654d3a350.png">

**Comment by kjoyceee** [comment] 2022-12-15 21:26
I luckily have a 1.1.24 version on my Mac that I've reverted to for now to get by til fixed.

**Comment by agreaves** [comment] 2022-12-20 03:28
This is fixed now! It looks like #236 was a duplicate of this.

**Closed by agreaves** 2022-12-20 03:28 UTC
Labels: status: needs triage
