### ISSUE TITLE
No captura la localización del dispositivo al ejecutarse en modo test

### ISSUE THREAD

**Issue by Jamescom-Hak** [FlutterFlow/flutterflow-issues#3721] opened 2024-08-31 23:21 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Al Widget de google maps se le asigna la localización del dispositivo para que al cargarse muestre el centro del mapa, sin embargo, solo muestra el punto de coordenadas 0,0.  Al hacer la inspección a la página se muestra lo siguiente: Error querying user location: Location permissions are permanently denied, we cannot request permissions.

### Expected Behavior

El widget google maps debe capturar la localización del dispositivo y mostrarlo como punto central al cargar el mapa en el dispositivo.

### Steps to Reproduce

1. Crea una nueva página. 2. Carga Widget contenedor. 3. Asignación de ancho y alto, 100% y 70% respectivamente. 4. Carga de widget google maps. 5. Num Markers igual a single. 6. marker type igual a LatLng. 7. Marker LatLng igual a coordenadas de un punto en mi ciudad. 8. Marker Icon igual a Deafult. 9. Mrker color igual a blue. 10. Map Type igual a Roadmap. 11. Map Style igual a Standfard. 13. Initial map cdnter igual a Current Device Location. 14. Initial map Zoom igual a 14

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Padding(   padding: EdgeInsetsDirectional.fromSTEB(5, 0, 5, 0),   child: Builder(builder: (context) {     final _googleMapMarker =         regParkingEntradaDatosParkingsRecord?.ubicacionParks;     return FlutterFlowGoogleMap(       controller: _model.googleMapsController,       onCameraIdle: (latLng) =>           setState(() => _model.googleMapsCenter = latLng),       initialLocation: _model.googleMapsCenter ??=           LatLng(13.106061, -59.613158),       markers: [         if (_googleMapMarker != null)           FlutterFlowMarker(             _googleMapMarker.serialize(),             _googleMapMarker,           ),       ],       markerColor: GoogleMarkerColor.blue,       mapType: MapType.normal,       style: GoogleMapStyle.standard,       initialZoom: 14,       allowInteraction: true,       allowZoom: true,       showZoomControls: true,       showLocation: true,       showCompass: false,       showMapToolbar: false,       showTraffic: false,       centerMapOnMarkerTap: true,     );   }), )

### Visual documentation

![1  Captura de pantalla 2024-08-31 180250](https://github.com/user-attachments/assets/21677f90-e360-4fa9-9384-a7d1c0db97b9)
![2  Captura de pantalla 2024-08-31 180331](https://github.com/user-attachments/assets/010281a6-70f6-48d4-82be-c256b9e6da3b)
![3  Captura de pantalla 2024-08-31 180407](https://github.com/user-attachments/assets/b99fbba6-51e5-4216-94a8-bb8dade57289)
![4  Captura de pantalla 2024-08-31 180441](https://github.com/user-attachments/assets/67113204-5e96-41f8-af08-afae96946bdc)
![5  Captura de pantalla 2024-08-31 180515](https://github.com/user-attachments/assets/37df13c6-ff98-4314-b692-d3183eec1b97)
![6  Captura de pantalla 2024-08-31 180618](https://github.com/user-attachments/assets/bc92512b-e7f7-4fda-9029-0cb88482dd1f)

### Environment

```markdown
- FlutterFlow version: 4.185
- Platform: web y App Fluterflow para Windows 11
- Browser name and version: Edge Versión 128.0.2739.54 (Compilación oficial) (64 bits)
- Operating system and version affected: Windows 11
```

### Additional Information

Me impide seguir con el desarrollo de la App ya que no puedo hacer Test con datos reales

**Comment by Alezanello** [comment] 2024-09-02 12:29
Hello!

Thank you for bringing this issue to our attention, and we’re sorry for any inconvenience it may have caused. The good news is that this is a known issue, and our team has already added it to their backlog for a fix. This issue is a duplicate of [this ticket](https://github.com/FlutterFlow/flutterflow-issues/issues/3285), where you can find any future updates. I’ll go ahead and close this ticket as a duplicate.

Thanks again, and have a great day!

**Closed as not planned** 2024-09-02 12:29 UTC
Labels: closed: duplicate
