### ISSUE TITLE
Supabase Custom Schemas not supported using get Schema

### ISSUE THREAD

**Issue by PandasDeveloper** [FlutterFlow/flutterflow-issues#4870] opened 2024-11-12 09:45 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Using the Supabase integration in the FlutterFlow builder I enter in API URL and Anon Key and select 'Get Schema'.

The Supabase tables are pulled, however it is only pulling from the public Schema. (In which i would like to select app schema instead)

### Expected Behavior

Being able to select the Schema for get the tables for the associated Schema would be the expected behaviour.

### Steps to Reproduce

1. Enter Supabase Integration
2. Enter in API URL and Anon Key
3. Click get Schema

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfk8nf7ZNOseEA7q6JcvpshWQXNUccTYMvjuphcx4jG7byE5oMesnBQ0NKTcujT1ZYA1K0gmE0wvzXk+HfGsE6Gw2bRrk40JVAezrLVnOjVrKIDZOwPHMkLNxQGUiA1sOnvBVQAPpvS0If1zu1Nq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

![image](https://github.com/user-attachments/assets/99862ae7-032e-418d-93be-96a916271901)

### Environment

```markdown
- FlutterFlow version:  3.24.2
- Platform:Web
- Browser name and version: Chrome 107.0.5304.110
- Operating system and version affected:  macOS Monterey 12.2.1
```

**Comment by Alezanello** [comment] 2024-11-12 18:38
Hello!

Thank you for your input! This is currently the expected behavior. What you’re suggesting falls under a feature or enhancement request rather than a bug. As this GitHub Issue Tracker is intended for bug reports, I’ll be closing this issue. Rest assured, I will create an internal ticket and add it to the engineering team's backlog for consideration.

Thank you for understanding!

**Closed as not planned** 2024-11-12 18:38 UTC
Labels: closed: feature / enhancement request
