### ISSUE TITLE
Old Version

### ISSUE THREAD

**Issue by ricardocosta43** [FlutterFlow/flutterflow-issues#2090] opened 2024-01-02 16:36 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I was making changes to my project.
I asked a master member of my team to come in and do an export to github
After that, I entered the project again and the changes since 12/30/2023 were undone.
I need them again

If you compare the pull request for git and the version in flutterflow, some functions do not exist and the EventDetail screen is different

### Expected Behavior

Current version

### Steps to Reproduce

Not is possible

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40luflwItItbxE1s72ccJVgiY5JVN6bLgz19VraCosfZT2BLMcec/RVERoZO7gTAlmPU6jkWoW0dbJuOD9L/cCGxecRr5B/pF+Sgz/WjqtVLKXFJWgRnclFtNQfEiwy6aNvRJ+XdNZLk4R3U+XevKsZBbtJufPDlVNDq/LZO4=

### Context

I was two days late for work

### Visual documentation

compare to git

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: 4.0
- Platform: Web
- Browser name and version: Chrome 120.0.6099.129
- Operating system and version affected: masOS Sonoma
```

**Comment by hariprasadms** [comment] 2024-01-02 16:51
Hi @ricardocosta43 - Please include steps to reproduce the issue or provide a brief video explaining the problem you're experiencing. Without these details, it becomes challenging for us to investigate and address the issue effectively. Update Issue title which can reflect the issue details briefly. Thanks

**Comment by ricardocosta43** [comment] 2024-01-02 17:36
Good afternoon
Thanks for the feedback
After searching on a forum, I identified that flutterflow takes snapshots of the project. Then I was able to select a snapshot where my changes were saved
Unfortunately I can't make a video on how to reproduce the problem as it is intermittent and completely random.

What you can do internally is the following
1 - A master account as the owner of any blank project (this account needs to pay the maximum plan)
2 - a secondary account that DOES NOT PAY FOR FLUTERFLOW (this account must use the free version of flutterflow)
3 - Use the free account to make changes to the project
4 - From time to time log in with the master account to make concomitant changes
5 - You need two people using the same project at the same time with these example accounts that I told you

I believe you will see the problem happen
________________________________
De: Hari ***@***.***>
Enviado: terça-feira, 2 de janeiro de 2024 13:52
Para: FlutterFlow/flutterflow-issues ***@***.***>
Cc: ricardocosta43 ***@***.***>; Mention ***@***.***>
Assunto: Re: [FlutterFlow/flutterflow-issues] Old Version (Issue #2090)


Hi @ricardocosta43<https://github.com/ricardocosta43> - Please include steps to reproduce the issue or provide a brief video explaining the problem you're experiencing. Without these details, it becomes challenging for us to investigate and address the issue effectively. Update Issue title which can reflect the issue details briefly. Thanks

**Comment by takashiff** [comment] 2024-01-30 19:49
Hello @ricardocosta43, thank you for your bug report. Unfortunately, we do not allow realtime collaboration between accounts that are not a part of the same teams plan. The following dialog should appear when trying to work on the same project simultaneously: 
<img width="577" alt="Screenshot 2024-01-30 at 11 47 46 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/134453477/c3d00f69-a71e-42d5-9031-83fb2ae3e7d2">

If you don't mind providing further info so that we can find the root cause of this issue. was the above dialog not presented to you or the project owner while collaborating? Thanks

**Comment by hariprasadms** [comment] 2024-02-02 10:13
@ricardocosta43 - Are you still experiencing the issue ? If it is resolved, please close the issue. Thanks

**Comment by ricardocosta43** [comment] 2024-02-02 10:17
> Olá@ricardocosta43, obrigado pelo seu relatório de bug. Infelizmente, não permitimos a colaboração em tempo real entre contas que não fazem parte do mesmo plano de equipe. A seguinte caixa de diálogo deverá aparecer ao tentar trabalhar no mesmo projeto simultaneamente: <img alt="Captura de tela 30/01/2024 às 11h47min46s" width="577" src="https://private-user-images.githubusercontent.com/134453477/300942321-c3d00f69-a71e-42d5-9031-83fb2ae3e7d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NjkxODQsIm5iZiI6MTcwNjg2ODg4NCwicGF0aCI6Ii8xMzQ0NTM0NzcvMzAwOTQyMzIxLWMzZDAwZjY5LWE3MWUtNDJkNS05MDMxLTgzZmIyYWUzZTdkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQxMDE0NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZDUyZTkxMGMwODJjNWJkZDcyZTVmODc1Y2M1NmIwYmNmZTI3MzI5Yjk3N2UxZWU5MTM0MGM1MzIxYmU3M2JiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GsCVhUf59bWatOVpfC_IDCcZsC2sd9JpJAZVI3f4OZs">
> 
> Se você não se importar, forneça mais informações para que possamos encontrar a causa raiz do problema. a caixa de diálogo acima não foi apresentada a você ou ao proprietário do projeto durante a colaboração? Obrigado

@hariprasadms

Hello
Yes, the dialog box appears when we try to use the project simultaneously, but it does not justify the project going back to an old version (a week ago)

**Comment by takashiff** [comment] 2024-02-06 22:57
Hi @ricardocosta43, is any of your previous data saved within the project snapshots? In the future, please refrain from collaborating on the same project on a free plan, as it is disallowed and intentionally does not save any changes. Thanks

**Closed** 2024-03-23 14:40 UTC
