### ISSUE TITLE
Test Mode Debug Panel showing values as Null

### ISSUE THREAD

**Issue by GGLionCross** [FlutterFlow/flutterflow-issues#3183] opened 2024-06-19 21:50 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In Test Mode, a few property in my App State are showing as Null even though they should have values. Also, my action parameters to various components are showing as null as well.

### Expected Behavior

My onSubmit parameters which do have actions tied to them shouldn't show as Null.
Objects in my AppState that are 2 or more levels deep in Data Schema shouldn't show as Null.

### Steps to Reproduce

1. Run Test Mode
2. Observe Debug Panel
3. Confirm parameters and state values that are Null when they shouldn't be.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40lPHlz4xgoctF7arALMZvmik5KVh5aucn1tZ7aCosfZT2BLMcec/RVERpTsOhdH9UMEyagWoW3OiOvfLDUcYEKTicc65A+M5IUgHLWl6uRq6uFJWgdXEnL/xPfXbA07eN2R1AXdJ1SGQS2E+uJ9+Xfz3vHqWyPFUwDq/LZO4=

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/11065433/ae525e7a-08d4-4035-848c-1e8579ab902f)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/11065433/e4167dc3-7b27-4f10-aef7-a07686692bd3)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/11065433/cbb86bf8-8114-4ef8-a64d-f2b237019f0d)

### Environment

```markdown
- FlutterFlow v4.1.61+ released June 18, 2024
- Flutter version is 3.19.1
- Platform: Web
- Browser name and version: Brave v1.67.116 Chromium 126.0.6478.71
- Operating system and version affected: Windows 11
```

### Additional Information

How are you able to access my project? Do I need to share a link to it? It's associated with my email lioncrossdev@gmail.com

**Comment by mulyameubel** [comment] 2024-06-20 01:49
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/171655109/f76486d7-885d-4b41-93e3-9595c7503229)
stuck and not displaying data

**Comment by chetstriker** [comment] 2024-06-20 19:52
I'm having the same issue, I did a simple test to trigger the API call when I press a button:
The api call returns successful in the action flow editor response and shows a success alert box, I also see the call and expected results returned in the built in chrome debugger, however the flutterflow debugger still shows null and I'm guessing that's why my components that read off of it are failing.
Here is a photo from the debugger
<img width="1083" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/4873992/8961b961-e91c-4b58-97c7-9cdf46eca65c">
On the right side, I see my API call returning results which are inside the "apiResulttbd" action shown on the right.
However it stays as showing null.
Here is the action shown below, where it shows the API call and the action variable name associated that match with the call to my server shown as successfully returning the results in the debugger
<img width="586" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/4873992/36608972-8e05-4e54-aeca-7fe9f441ee11">

**Comment by manni-io** [comment] 2024-06-21 02:35
I have also been having this issue the last 24 hours with both app and page state

**Comment by msusviela** [comment] 2024-06-21 11:26
Hi. I was not able to reproduce the issue from a blank project. If anyone can provide the steps to reproduce the issue from a blank project, it'll be very helpful for us.<br><br>@GGLionCross what I found that could be related to the issue of that values being null, is that the textfields are processing the info as a string and not as a number:

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/b87e9036-092c-4b99-8406-868f5d423957/15bd55f1-ab83-4843-a5e6-a848be1b953a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iODdlOTAzNi0wOTJjLTRiOTktODQwNi04NjhmNWQ0MjM5NTcvMTViZDU1ZjEtYWI4My00ODQzLWE1ZTYtYTg0OGJlMWI5NTNhIiwiaWF0IjoxNzE4OTY5MjYyLCJleHAiOjMzMjg5NTI5MjYyfQ.scIrgmiGVI3C2X-M9HGi-03-HBVB1uEhWdlOfJEgRTA " alt="image.png" width="620" height="517" />

<br><br><br>That could be causing the issue (because you're trying to set a string in a field that only takes doubles). Can you try making that a type that matches the datatype fields (double)?<br><br>Let me know if this solved your issue

**Comment by GGLionCross** [comment] 2024-06-21 19:29
Here's a loom recording demonstrating the bug and workflow a little further:
https://www.loom.com/share/4c5273b04ca6464ab42a83c8787b52b1

Also, the top level values of my App State are shown, but for some reason, any defined data type of my property object are showing as Null in Test, even though it works correctly when building as a Run

**Comment by msusviela** [comment] 2024-07-16 13:18
The team is already working on this. Thanks for your reports!. I'm closing this issue since it's a duplicate of one in our internal backlog.

**Closed as not planned by msusviela** 2024-07-16 13:18 UTC
Labels: closed: duplicate
