### ISSUE TITLE
No Firebase project present in FlutterFlow project. Please set your Firebase project ID in Firebase settings

### ISSUE THREAD

**Issue by fernandofmn** [FlutterFlow/flutterflow-issues#3784] opened 2024-09-09 13:57 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm trying to change Firebase Project or regenerate config files and I have this mensage. The Firebase Project textfield is always readonly and I'm not able to change then.

Error: No Firebase project present in FlutterFlow project. Please set your Firebase project ID in Firebase settings.

![Captura de tela 2024-09-09 104812](https://github.com/user-attachments/assets/8eeddd0c-71e3-42d7-b643-5447f3e0b2c4)
![image](https://github.com/user-attachments/assets/d221e0e8-1829-4d63-afe2-2f7cdb4743cf)

### Expected Behavior

Change and regenerate firebase project
xxx

### Steps to Reproduce

regenerate config firebase or change firebase project

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4el8j6yItNobxG7ZSJbsBv9ScWHGYjbZI7m+5+GQwjIZj3OpoEduj+QHZVOMO/dFY3OlmI8HIzw/zUheOSF+49Piiqc5xbwpNIajzKUma5RbanDKiwRX8lBd9jGkuHzbSw2Qp7LvFoW1otw2eyIeiXUj/dQbrBDkU/GOSLDNnJj3y9HhzKXn0Jg1ZSfCvr

### Visual documentation

![image](https://github.com/user-attachments/assets/b02e1a8c-1b52-4466-8513-139ca2f8fff5)

xxxxxxxxxxxxxxxxxxxxx

### Environment

```markdown
- FlutterFlow version: latest version
- Platform: web and desktop
- Browser name and version: Chrome
- Operating system and version affected: Windows
```

**Comment by rzambroni** [comment] 2024-09-09 14:06
Hello,

Thank you for your report! Our team is already aware of the issue, and it has been assigned to the engineering team for a fix. We’ve noted your comment on the original ticket, and updates will be posted there. I’ll be marking this ticket as a duplicate of the following issue: [GitHub Issue #3744](https://github.com/FlutterFlow/flutterflow-issues/issues/3744).

Thank you for your understanding!

**Closed as not planned by rzambroni** 2024-09-09 14:06 UTC
Labels: closed: duplicate

**Comment by fernandofmn** [comment] 2024-09-09 14:33
Thanks @rzambroni. I'm very worried because I'm not able to run the code, and I'm codding and not testing.
