### ISSUE TITLE
App Does not Work on IOS

### ISSUE THREAD

**Issue by anywheresa** [FlutterFlow/flutterflow-issues#63] opened 2022-10-28 04:23 UTC
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
Display app properly on IOS devices.

## Current behavior (required)
App displays object out of alignment ie. two rows in a column. Bottom row will overlap top row.
Form field do not display/are hidden. Keyboard opens which means they are there but cannot be seen.

## To Reproduce (required)

1.Open app

## Context (required)

Cannot run the app on IOS. 

## Screenshots / recordings

Android Landing Page (What it should look like)
![Android Login](https://user-images.githubusercontent.com/56668789/198501683-1ae08b27-8934-4294-82c1-10b50a0632e9.jpg)
IOS Landing Page - PROBLEM
![IOS Landing](https://user-images.githubusercontent.com/56668789/198501781-d8df4748-5c6e-43fa-9700-837c37b0317c.png)
Android Login Page  (What it should look like)
![Android Login](https://user-images.githubusercontent.com/56668789/198501873-714b0fa2-9c95-4583-8760-ac3967d6d67d.jpg)
IOS Login Page with missing form - PROBLEM
![IOS Login](https://user-images.githubusercontent.com/56668789/198501934-028e8e8b-44ff-4963-8b20-cae498a71c42.png)

## Your environment

* **Bug Report Code:**
* Version of FlutterFlow used: Latest
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome
* Operating system and version (desktop or mobile):Win 10

**Comment by bulgariamitko** [comment] 2022-10-28 07:24
This issue tracker is intended for general bugs that are applicable to all users. Because this error appears to be specific to your project and the steps are not reproducible, this is classified as a support request and will be closed. Please use chat support or contact support [at] [flutterflow.io](http://flutterflow.io/) for further assistance.
If you do find a specific reason for the issues you are encountering in your project, please don’t hesitate to open a new bug report with the relevant steps to reproduce.
Thank you for your contribution!

**Comment by anywheresa** [comment] 2022-10-28 15:10
How is this specific to me? This is standard stuff. Surely if this is happening to me, it will be happening to everyone. Maybe no one has deployed in the last few days!

**Comment by wenkaifan0720** [comment] 2022-10-28 17:11
This does look problematic. Could you share with me the project (or just this page) so I can debug it more quickly?

**Comment by anywheresa** [comment] 2022-10-29 04:09
Thank you.
I see there are other developers that are also picking up the same issue, as reported on my forum post [here](https://community.flutterflow.io/c/bugs/app-does-not-work-on-ios?login_token=VAdAzDj1DwbmjXB9CcaHDW3cy79a5LRdhPPo)

My project is https://app.flutterflow.io/project/eclipse-connect-xzhqif
Thank you.

**Comment by wenkaifan0720** [comment] 2022-10-30 14:49
Hi. After some research, I think the problem is with the "Gotham" font that you used which is causing layout issues on iOS. See this link: https://stackoverflow.com/questions/52567063/flutter-layout-issue-in-ios-devices-messed-up-layout-in-ios-devices. 
After removing the "Gotham" font, the layout looks normal on iOS (running on an emulator, let me know if the issue is resolved on a real device). 
Unfortunately this issue may be caused by Flutter after a recent update and we will have to wait for a fix from their side. My suggestion at the moment would be to remove the "Gotham" font when you build for iOS. I am not sure what is causing other users' issues on the community forum. But I am going to try to ask them to create a ticket here.

**Comment by anywheresa** [comment] 2022-10-31 07:00
Great, thank you, good work, as it was not a Flutterflow issue! I changed fonts and it is working now. Do you perhaps know if other fonts are effected as well. I may be a good thing to inform the community as it seems there may be other fonts also causing an issue.

**Comment by wenkaifan0720** [comment] 2022-11-01 03:20
I wish I know the answer. I've tried a decent amount of fonts on the iOS emulator but haven't encountered this issue. I don't think there are many fonts that will cause this issue and there's also a good chance this issue will be fixed by the Flutter team. So I wouldn't worry too much.

**Closed** 2022-11-03 07:31 UTC
Labels: status: not a bug
