### ISSUE TITLE
Floating Nav Bar code change and below navbar transparency can't be change

### ISSUE THREAD

**Issue by jeanlouisliaud** [FlutterFlow/flutterflow-issues#972] opened 2023-06-05 18:55 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Until last Friday, I was using a floating navigation bar stuck to the bottom of the screen. After noticing transparency between the navigation bar and the bottom of an IOS phone, I set the elevation to 0, which fixed the problem: the bar was white and so was the space below it (c.f screenshot).

Since the new version of FlutterFlow last Friday, the code has changed (c.f screenshot) and the transparency can no longer be removed from FlutterFlow. 

For the record, I didn't use the default navigation bar because this is not possible to "always show navigation" on two page.

### Expected Behavior

The bottom of the navigation bar is no longer transparent, and I can set it to white.

### Steps to Reproduce

1. Create a page
2. Put Floating bottom navigation on the page
3. Run the result on IOS mobile device

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4skufl3ItOtbxG+Kr+bsBB/WYWOVAiRJJJscp/bxIgGIDzPOw+ZPWkbVtoQsPjS1VEeUSmmXIJpKHSvuD9LfFeIRStfKVyyJF2VgrxfGaRUZOBEarpdUBRO+FQCly03JjYhxFTIstYWloe3F+medm9bBHqJ5jFIndISq/LZO4=

### Context

I can't publish my app on the store bafore fix this issue.

### App before and after 02/06 Flutterflow new version
**Before**
![IMG_9773](https://github.com/FlutterFlow/flutterflow-issues/assets/115577193/e62ebb77-243c-4650-ab4b-27c0610db8e8)

**After**
![IMG_9774](https://github.com/FlutterFlow/flutterflow-issues/assets/115577193/fb4048bc-93f3-4095-91d4-435c7322df4c)

### Code before and after 02/06 Flutterflow new version
**Before**
![CleanShot 2023-06-05 at 17 46 16](https://github.com/FlutterFlow/flutterflow-issues/assets/115577193/22b91cfe-d633-448d-87c3-f11cab5f9510)

**After**
![CleanShot 2023-06-05 at 17 43 25@2x](https://github.com/FlutterFlow/flutterflow-issues/assets/115577193/f3885aa9-f3c2-41d6-bb45-be67a422bddd)

### Environment

```markdown
- FlutterFlow version: 3.7.12
- Platform: IOS
- Operating system and version affected: IOS
```

**Comment by jeanlouisliaud** [comment] 2023-06-06 15:10
Any update on this issue ? 😊

**Comment by jeanlouisliaud** [comment] 2023-06-07 08:31
Hi @bulgariamitko @katherineqian, how are you ? 

Any news on this issue ? We're stuck for production deployment

**Comment by bulgariamitko** [comment] 2023-06-07 11:26
@jeanlouisliaud FF team has to review this issue and fix it or deny it. I do not work for FF I can only confirm this issue which I did.

**Comment by jeanlouisliaud** [comment] 2023-06-08 07:11
Hi @katherineqian @hariprasadms, 

Any news on this issue ? Doest it come from FF new version ?

**Comment by SamyKhara** [comment] 2023-06-12 01:59
The bug seems to be resolved recently but only partially. The floating navbar gap has increased significantly for iOS.

**Comment by jeanlouisliaud** [comment] 2023-06-12 08:51
Hi @SamyKhara, the bug isn't resolved for me. I guess i will never have a response from FF dev team, i will update the code 
 manually.

**Comment by SamyKhara** [comment] 2023-06-12 16:07
@agreaves @bulgariamitko @katherineqian 
This bug is still happening, but on specific pages. It is happening on all pages that are not on Navbar. So if I have a page that I navigate to from Home, the floating bar has a huge transparency at the bottom.

**Comment by bulgariamitko** [comment] 2023-06-13 06:47
@SamyKhara ca you submit a screenshot?

**Comment by SamyKhara** [comment] 2023-06-13 14:44
Hi- as you can see in the two screenshots, the navbar transparency is dependent on whether the page is on Navbar or not.

![IMG_1880](https://github.com/FlutterFlow/flutterflow-issues/assets/21138564/fbbe12cf-816f-4d66-b902-71661cb67065)
![IMG_1883](https://github.com/FlutterFlow/flutterflow-issues/assets/21138564/64fb0787-1375-4e8d-83ff-6eb8a93dabf6)

**Comment by wenkaifan0720** [comment] 2023-06-14 14:18
Hi @jeanlouisliaud. Sorry for the delayed reply. The floating nav bar package has been pretty old by now, and things could go wrong with it. We added that two lines of code you mentioned to fix another bug related to floating nav bars. (could you check whether the keyboard shows up properly if you remove them). And we thought for the behavior you desired (non transparent below the nav bar), you could use the default nav bar. The always show nav bar on page thing is annoying, but is it a blocker?

**Comment by jeanlouisliaud** [comment] 2023-06-14 14:39
Hi @wenkaifan0720, thank you for the response. The keyboard show up properly. In my case, it's a blocker. I have data show on a map, and the same data show in list. Both are accessible from the same navbar item, a button on the screen make the switch between these views.

**Comment by wenkaifan0720** [comment] 2023-06-14 17:34
Hi @jeanlouisliaud. After reading the example for the floating nav bar package, I believe what FF has right now is the expected behavior. The nav bar is floating above the bottom edge of the screen. 

I still don't quite get the reason that you can't use the default nav bar. Could you elaborate?

**Comment by SamyKhara** [comment] 2023-06-17 21:19
@wenkaifan0720 - major issue with using Default Navbar- I cannot show Navbar on pages that are not on Navbar.

Floating Navbar is the only option, but the transparency issue is very recent. It is a simple issue-
The Safe Area below Navbar is transparent on pages that are not on Navbar and it is NOT transparent on pages that are ON navbar.

@bulgariamitko @agreaves Can we get a quick resolution on this, please? It has been impacting the App experience negatively since the change made earlier this month by the FF team.

**Comment by SamyKhara** [comment] 2023-06-19 17:47
Hi Team- I seem to have found an issue that is causing this. Pages on Navbar have Column widgets that extend to the bottom of the page. See below.

<img width="416" alt="Screenshot 2023-06-19 at 1 45 36 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/21138564/7a5976fd-a8e0-4d74-8150-94f37080b3fe">

Pages not on navbar have the Column widget extend only to the top of the Navbar. See below.

<img width="462" alt="Screenshot 2023-06-19 at 1 44 11 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/21138564/5fff5636-4ba4-4f76-8654-c93680c6ca15">

If the Engineering team can fix this issue, that will be superb as then we can add some bottom padding on the outermost widget layer.

**Comment by faxioman** [comment] 2023-08-24 10:13
From what I see, the default Flutter navbar is currently the only one that's truly usable. Unfortunately, though, it's not possible to display it on screens that are not directly linked to it.

**Comment by greyginter** [comment] 2023-08-25 04:56
Also facing this issue, the only workaround I can find is using a container the same color as the nav bar set at 5% height. Depending on your scroll behaviour, you may have to nest an existing scrolling column (if you have one) inside a new, non-scrolling column with the colored container below it.

**Comment by kium-one** [comment] 2023-09-24 19:37
Same issue here.
- Can't add nav bar to non-root pages if it's the default navBar
- Floating nar bar that's added on pages doesn't stay in place, it moves with the screen during navigation to another page.

**Comment by katherineqian** [comment] 2023-09-30 16:18
Hi all, I'm sorry for the extremely late response here. I was not active on maintenance and I'm sorry that this fell through the cracks.  From reading the thread, it sounded like the best fix for this moving forward would be to add the ability to remove pages from the default Flutter NavBar. However, this is actually difficult to support in the Flutter default `BottomNavigationBar` due to the way Flutter navigation works (though it is supported on the other Nav Bar styles). Let's say you have a `Home` page which correctly shows the Nav Bar and also is included on the Nav Bar. You click on a post and navigate to the `Posts` page, which you want to display the Nav Bar but not actually include as an icon on the Nav Bar. However, if you navigate to a page _without_ using the NavBar (by clicking on the post in this case), the new Posts page will be pushed to the top of your stack and it will actually cover the entire Home page including the `BottomNavigationBar`. There is a popular package for solving this problem called [persistent_bottom_nav_bar](https://pub.dev/packages/persistent_bottom_nav_bar) on pub.dev.

To provide more info on @wenkaifan0720's comment, the floating nav bar (see [package here](https://pub.dev/packages/floating_bottom_navigation_bar)) is designed to have that transparent space at the bottom, so if you wanted to hide that space, it would be a slightly non-standard usage of the package. It looks like the package itself has not well-maintained -- last update was 2 years ago -- and has some issues with iOS that have been reported on GitHub as well. I suspect the issues will continue to worsen in severity as Flutter continues to upgrade. We will likely need to make some changes to this widget itself to keep it updated. 

I wanted to offer that explanation as well as a suggestion for how to move forward. I understand it's difficult to integrate a custom nav package like `persistent_bottom_nav_bar` in FlutterFlow since it requires customization of the base structure of your app (even Scaffolds are declared for you in this package). So the best solution I would suggest here to fully control the look and feel of your NavBar appears to be to create your own NavBar component and show that on whatever page you want. See [this community post](https://community.flutterflow.io/widgets-and-design/post/can-i-display-navbar-on-every-page-of-the-app-mqqYHQ7deKY6LyK) for a suggestion about this method. 

I would suggest searching for NavBar on the new Marketplace: https://marketplace.flutterflow.io/search?query=navbar
There are already a few free pre-built NavBar options that creators have offered which would be a great starting point for customization if you decide to pursue the route of using your own component as the Nav Bar. 

I hope this explanation and the suggestions help. Closing the issue for now.

**Closed by katherineqian** 2023-09-30 16:18 UTC
Labels: type: bug, status: confirmed

**Comment by kium-one** [comment] 2023-09-30 16:37
Thank you Kathy for the elaborate response, much appreciated. It makes a lot of sense.Do you know if by any chance there’s a way to create a custom nav bar that doesn’t animate with the page on page changes (i.e. stays fixed at the bottom), or it’s only possible with the bigger revamp you mentioned or a very custom implementation on our end?On Sep 30, 2023, at 6:18 PM, Kathy Qian ***@***.***> wrote:﻿
Closed #972 as completed.

**Comment by katherineqian** [comment] 2023-09-30 16:50
Hi @kium-one, if the constraints are: 1) keep Nav Bar on screens which do not appear on the Nav Bar 2) do not float the Nav Bar (i.e. do not have space at the bottom, on all platforms) then yes, I believe the custom implementation would be the easiest solution to this issue. There have been other workarounds proposed to this issue -- I found [this video](https://www.youtube.com/watch?v=qj7jcuU2Z10) about it if you'd like to take a look, but the concern here is that alternative methods like keeping a separate stack of items on the page may impact performance negatively. I would personally go for the custom implementation if I were to build an app with a Nav Bar with these constraints, since there are several good components that have already been pre-built on the Marketplace and I would be able to have full control over the styling of the Nav Bar without having to depend on a package (as you can see, the previous floating nav bar package became less well-maintained over time).

**Comment by kium-one** [comment] 2023-09-30 18:44
Thank you for the links, that's really useful. These pre-built nav bars are simply elements within the page structure though, right? My issue is that when I navigate to a screen using "navigate to", then the animation (slide left) moves the nav bar as well, which is quite jarring.
I'm assuming the only solutions are the one in the video and being patient until FF updates it. For now I'd stick to patience :)

**Comment by katherineqian** [comment] 2023-10-01 21:05
That is a really good point about the UX being non-ideal if you use a component in this way. Let me give this another look and I'll come back and update here to see if I can provide a better resolution.
