### ISSUE TITLE
After FlutterFlow Update! Back End query - Ignore empty filter values is not working

### ISSUE THREAD

**Issue by Jensoulus** [FlutterFlow/flutterflow-issues#2043] opened 2023-12-21 16:41 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The ignore empty filter values is not working after FlutterFlow update. This was working before without a problem. Once the value was null it was ignored.

### Expected Behavior

Null/ Empty filter values get ignored

### Steps to Reproduce

Create new page
Query firestore collection with empty/null filter values
See that no elements are being found

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

not able to create

### Context

I have a list with a lot of items that should be able to be filtered. If no filter is set the list should contain all items. If a filter is set the list should only contain the items for the chosen filter

### Visual documentation

I am not sure how I should document this. But what I can say is that I got requested to create a huge index in firestore (because I have a lot of filters) but if I create this index I don't get results (makes sense because I have no data where all filters are applicable at the same time)

![Bildschirmfoto 2023-12-21 um 17 44 10](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/222fb571-3286-4d5f-8440-7bd7f11d6467/499b571b-8e89-4b07-b267-7ba1912b6594?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yMjJmYjU3MS0zMjg2LTRkNWYtODQ0MC03YmQ3ZjExZDY0NjcvNDk5YjU3MWItOGU4OS00YjA3LWIyNjctN2JhMTkxMmI2NTk0IiwiaWF0IjoxNzA3MTQxODQ2LCJleHAiOjMzMjc3NzAxODQ2fQ.THGzN6tRgw86YbvMFN3vruTk78yjjqVyrD2DUELCEPE)

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: 3.13.7
- Platform: iOS & Android
- Browser name and version:
- Operating system and version affected:
```

**Comment by agreaves** [comment] 2023-12-21 17:14
Hi @Jensoulus, thank you for the bug report. We do really need the Bug Report Code in order to reproduce and fix this issue, could you try generating it again? You may have turned off the clipboard permissions, that's the most common cause of it failing. If not, you could simply link the project and I could take a look (if you're able to tell me which backend query it is). Thanks!

**Comment by tothati90** [comment] 2023-12-21 17:31
i'm experiencing the same thing. if i turn on ignore empty filter values, the data doesn't show up. it worked fine before, i didn't change anything, but since the last update something is wrong

**Comment by Jensoulus** [comment] 2023-12-21 17:35
Hi @agreaves  ,
the project is bdr-touren-5ctcs9 and you can see this error on the page test. It just contains one query

**Comment by GuzSantos** [comment] 2023-12-21 19:28
I having similar situations from API call from Xano. suddenly all API calls are getting an error value or a null value after the update.

**Comment by agreaves** [comment] 2023-12-21 20:16
Hi @tothati90 and @Jensoulus, thanks for the info.

@Jensoulus in your case, the filter is set to check whether it is equal to `Null`. This is not the same as an empty string, which it what it checks for. This would have been the same before the update as well. Do you have a different example where this still happens.

@tothati90 do you know which field is not being ignored? Or rather, can you walk me through the issue you're experiencing. Before the update, was "Ignore Empty Fields" checked in your project and now it returns no data? Just wondering whether you're sure that it's the ignore empty fields part that's the issue.

**Comment by agreaves** [comment] 2023-12-21 20:17
@GuzSantos this sounds like a separate issue if you'd like to create a new issue for it!

**Comment by Jensoulus** [comment] 2023-12-21 20:21
@agreaves sure, I do have another example. The Events page contains a query on the list view. If you navigate to this page via the navbar no filters are set (filter values are null - except some values). It worked before the update that all the items of the collection are being returned. Now it is return nothing. In this case I am also using the null value to signalise the empty value - it is the same as on the test page. How else should I signalise an empty filter value for a Boolean for example?

Thanks for your fast reply!

**Comment by agreaves** [comment] 2023-12-21 20:35
I believe I've identified the issue! Once it runs through our test suite we'll deploy it right away.

@Jensoulus In general, values that are explicitly passed as `null` are ignored by default. In order to _not_ ignore them, you must explicitly mark "Filter on Null Values". Regardless, as I mentioned we'll have a fix soon!

**Comment by Jensoulus** [comment] 2023-12-21 20:40
@agreaves thank you very much!
I wish you a nice Christmas!

**Comment by agreaves** [comment] 2023-12-21 22:29
Hey folks, this should be fixed now! Please let me know if you continue to encounter this issue.

**Comment by GuzSantos** [comment] 2023-12-21 22:34
Hi @agreaves,

I found my issue, besides showing a null error ends up to be a datatype incompatibility. On the API call I bring a double number from the backend, but the API call after changes made to declare the Datatype was showing Integer and then the crash. 


I changed in the API call configuration to Double and solve the issue. However it created a new one. As I am forced now to declare the DataType as double, I can't use it in a Text field that requires a String, I get Data Type incompatibility errors.
![Screen Shot 2023-12-21 at 22 08 17](https://github.com/FlutterFlow/flutterflow-issues/assets/139913617/03cf2914-2f6a-41e2-900e-b782484dd409)

**Comment by Jensoulus** [comment] 2023-12-21 22:34
Yes it is working! Great how quickly you reacted! I will close this ticket

**Comment by GuzSantos** [comment] 2023-12-21 22:35
I know has nothing to do with this issue, just want to close the loop and make you guys aware that other issues are happening. Thanks anyway.

**Comment by agreaves** [comment] 2023-12-21 22:44
@GuzSantos that makes sense! One last question I have (while we're here) is where it says it's incompatible? Doubles should be able to be used as strings in general so it shouldn't normally be an issue. You can select "No Further Changes" or "Number Format" for example.

**Comment by GuzSantos** [comment] 2023-12-21 22:49
Hi @agreaves, Yes. As you can see from the print screen the number I get is 0.6666666 and I selected as Number Format to transform to Percentage and get 66,7%. And then got a message that a String field can't accept an Integer and crashes.

The only solution I could found was to build a Code Expression as showed below.

I take the double from the Json Call, multiply by 100 to get the percentage and parse to string with 1 decimal, adding the % string at the end.
![Screen Shot 2023-12-21 at 22 48 38](https://github.com/FlutterFlow/flutterflow-issues/assets/139913617/3ca87f55-75d6-4aef-b7b6-e6dbeed75f97)

I am also posting this issue on the community to see if anyone else has the same issue.

**Comment by agreaves** [comment] 2023-12-21 22:55
Hi @GuzSantos, got it. Could you generate a Bug Report Code on this exact widget (while the project is in the state where it's not working)? Then I'll be able to look at it directly and hopefully reproduce / fix.

If I need more info I'll reach out separately and leave the other good people in this issue alone 😅

**Comment by hariprasadms** [comment] 2024-02-16 13:30
Hi there, No additional details have been provided in the issue, and considering its age, we assume that the issue has been resolved in the latest FlutterFlow releases. Therefore, we are closing the issue. If you still believe you are experiencing the problem, please create a new issue with all the necessary details included. We appreciate you contibutions.

Thank you!

**Closed** 2024-02-16 13:30 UTC
Labels: status: needs information, waiting for user response
