### ISSUE TITLE
FlutterFlow Builder Crashes when duplicating a componant 

### ISSUE THREAD

**Issue by Dev-Muhammad-Junaid** [FlutterFlow/flutterflow-issues#2824] opened 2024-04-27 21:30 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The builder crashed unexpectedly, duplicating components adds a container that is not a part of the component.
When deleting the container, it stays there, crashing the entire builder.
Gray screen of Death. Seems a project-specific issue.

### Expected Behavior

.

### Steps to Reproduce

1. Duplicate my componant
2. Adds a container
3. Delete the container
4. Select the container widget
5. FF builders crashes

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4elMrqw5N1xd9G15PTbcFFoCoRNmY6U6xMiuxhYAw3IqLrPYoQYej+QHZVOMO/dFY3OlmI8HI1w6HOhvzLGvkXPiiWc4Rd1qVxEwvyWnmRV5SmDc+gbX96AehRChCHzbSzqyMnWfNsWHgS62GIG9yicB3UGY/7NjI/Hf2XNZD5nl6JLTLOXn0Jg1ZSfCvr

### Context

.

### Visual documentation

[https://github.com/FlutterFlow/flutterflow-issues/assets/65047962/cd0462fa-9115-40af-8e2f-bc1b8c8126f1](https://github.com/FlutterFlow/flutterflow-issues/assets/65047962/cd0462fa-9115-40af-8e2f-bc1b8c8126f1)

### Additional Info

.

### Environment

```markdown
- FlutterFlow version: 4.1.45+ (26 April,2024)
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: Mac
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] undefined\~100% of the time
- [ ] undefined\~50% of the time
- [ ] undefined\~10% of the time
- [ ] undefined\~1% of the time
- [ ] Very rarely or only encountered once

**Comment by Dev-Muhammad-Junaid** [comment] 2024-04-29 00:34
Okay Sure, I'll try to re-create the issue in a blank project and send an update

**Comment by Dev-Muhammad-Junaid** [comment] 2024-04-29 06:14
It seems to be project-specific. I also created other components and some follow the same issue.
What should be causing this. I replicated the same structure in another project but duplicating works fine

**Comment by rzambroni** [comment] 2024-04-29 14:41
Yep, its a bit hard to reproduce, if you happen to identify how to replicate this let me know and I'll take a look.

I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects.

Thanks!

**Closed by rzambroni** 2024-04-29 14:41 UTC
Labels: closed : project specific

**Comment by Dev-Muhammad-Junaid** [comment] 2024-05-05 13:49
https://github.com/FlutterFlow/flutterflow-issues/assets/65047962/a7f242c9-f7eb-4c02-9884-be2d363f4abb
