### ISSUE TITLE
RichTextSpan doesn't trigger actions

### ISSUE THREAD

**Issue by JuanxCursed** [FlutterFlow/flutterflow-issues#862] opened 2023-05-08 20:26 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When placing "links" into some words of the string, for instance:

By registering you do agree with our **_Privacy Policy_** and our **_Terms of Use_**.

To achieve that, we use RichText and RichTextSpan, in this case, both the Privacy Policy and Terms of Use have actions bound to it to launch a URL for a website.
These same actions placed into a Text Widget, Container, Row,...... works perfectly, but not into a RichTextSpan Widget.

This also is cause some other behaviors like, unable to download or push the code to debug (without any kind of message errors, just generic ones)

Therefore maybe this is related to:
https://github.com/FlutterFlow/flutterflow-issues/issues/575
https://github.com/FlutterFlow/flutterflow-issues/issues/496
https://github.com/FlutterFlow/flutterflow-issues/issues/684

### Expected Behavior

When a RichTextSpan is clicked the action should be triggered, or does not show any actions to bind if do not supports it.

### Steps to Reproduce

1. Create a new page
2. Add a RichText Widget 
3. Add a few RichTextSpan 
4. Get 2-3 RichTextSpan and add action 
5. In these actions try to launch a URL

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4glMmB389OxcRE17ruKe9aqykUOXo9bL00sNpETRIYCYjyO5YUaeP8XxNtZN/nTXNbKEWKgkYGzNbvivL1CvY3HE+rGaJG+Jd6TDrvXlK/aovSDs+KdnQlAe9hGFS40cKNvRJAOsheWUIl3V73Nd+8ZCrDQp/7Zwh9f6PHaOI=

### Context

I'm trying to create a register page that links to a webpage to provide the user with more details.

### Visual documentation
![image](https://user-images.githubusercontent.com/16026646/236932773-a1526136-f271-4e6b-8aeb-e4278a63c076.png)
![image](https://user-images.githubusercontent.com/16026646/236933472-a2b3edfd-c728-4b26-a543-20e19dd4931f.png)
![image](https://user-images.githubusercontent.com/16026646/236933155-85975fee-0464-45f0-b977-64b842dcffde.png)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Chrome Version 113.0.5672.63 (Official) 64 bits
- Operating system and version affected: Windows 11
```

**Comment by organicnz** [comment] 2023-05-16 11:54
Hi, @JuanxCursed. Thanks for adding this issue, Juan 🙂

I just reproduced this issue in beta and it looks like Launch URL actions work as expected 🙂

[Video](https://www.loom.com/share/7a8ea8de00fb4e1299421e36627f5797)

**Comment by wenkaifan0720** [comment] 2023-07-05 22:16
@JuanxCursed. I couldn't reproduce the issue as well. Is it still happening to you?

**Comment by wenkaifan0720** [comment] 2023-07-07 15:26
I'll close this issue for now. If it is still happening to you, please reopen this issue. Thank you.

**Closed by wenkaifan0720** 2023-07-07 15:26 UTC
Labels: status: can't reproduce, closed: other
