### ISSUE TITLE
Media Upload to Local & Snack Bar stopped working since refreshing page to new FlutterFlow version.

### ISSUE THREAD

**Issue by Kato-iOS** [FlutterFlow/flutterflow-issues#2349] opened 2024-02-16 08:38 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

No longer able to upload any media on local upload widget state and snack bar no longer display. It most likely is just a coincidence however I am facing this (or noticed at least) since the new FlutterFlow versions (refresh page was pushed).

### Expected Behavior

The expected behavior is to display the image which is uploaded to Local widget state as well as having the snack bar working ideally giving any type of feedback.

### Steps to Reproduce

1. Create new blank page;
2. Add button and image in the main column (without any modification/styling);
3. Add action to button (Upload Data -> Upload Save Media -> Upload Type: Local Upload (Widget State) -> Show Snack Bar -> Name: UploadedToLocalState)
4. Image change Image Type from Network to Uploaded File -> Upload File selected is from Widget State: Uploaded Local File);
5. Run (Nothing happens when you select the image).
6. PS: I also tried to create a Page State variable and update page state updating that variable and trying to display that in the image but had the same results.

![1](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/fecc9710-f12a-4557-8559-9e2160125e6f/2496a1d6-856f-47ca-a1d6-19f3814eba15?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mZWNjOTcxMC1mMTJhLTQ1NTctODU1OS05ZTIxNjAxMjVlNmYvMjQ5NmExZDYtODU2Zi00N2NhLWExZDYtMTlmMzgxNGViYTE1IiwiaWF0IjoxNzA4MDc1NTMwLCJleHAiOjMzMjc4NjM1NTMwfQ.orhur7kyJVabat2d6FgE3YDVh7Q1rPZk2D2cb7purtM)

![2](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/975c8146-380e-42b7-b559-e07a8d03d3a6/53d9af11-6dcd-42ba-8cbc-8baf28fbdd9c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85NzVjODE0Ni0zODBlLTQyYjctYjU1OS1lMDdhOGQwM2QzYTYvNTNkOWFmMTEtNmRjZC00MmJhLThjYmMtOGJhZjI4ZmJkZDljIiwiaWF0IjoxNzA4MDc1NTMwLCJleHAiOjMzMjc4NjM1NTMwfQ.2wsvQcZ3Gtg5OCuMfuNjQILtHOPzGRIXTTkxoL5f5F0)

![3](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/21f3b065-9493-4ec0-ac35-61f5de370d8d/86ec962a-3e7f-45de-a271-e03d67c19bbb?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yMWYzYjA2NS05NDkzLTRlYzAtYWMzNS02MWY1ZGUzNzBkOGQvODZlYzk2MmEtM2U3Zi00NWRlLWEyNzEtZTAzZDY3YzE5YmJiIiwiaWF0IjoxNzA4MDc1NTMwLCJleHAiOjMzMjc4NjM1NTMwfQ.rIuctI7Cjy0-jgF0IvRg_aYGhG3mIksnQXRn3CZELBs)

![4](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/0e9e9eb5-ed93-467d-ae70-75a04735dfa2/b332eeed-a0a7-40be-b646-290f1d2f54e1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wZTllOWViNS1lZDkzLTQ2N2QtYWU3MC03NWEwNDczNWRmYTIvYjMzMmVlZWQtYTBhNy00MGJlLWI2NDYtMjkwZjFkMmY1NGUxIiwiaWF0IjoxNzA4MDc1NTMwLCJleHAiOjMzMjc4NjM1NTMwfQ.GguUeqEFzL8FM7tnjjY5z_jqy5drgA0Ij0G5ucDnxRU)

[https://github.com/FlutterFlow/flutterflow-issues/assets/20778155/f1789c9b-e916-490f-b896-c1620a996448](https://github.com/FlutterFlow/flutterflow-issues/assets/20778155/f1789c9b-e916-490f-b896-c1620a996448)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4si87huIh2rtxE17qBYMdB/SMWQkAiU+coscp/bxIgGIDzPOw+ZPWkPxNCXuG6TwlceESmmnsG0NGNuOGTGMEqJTiBY65MyodcYBbxfEm5a5OBDLmwf0ZtO+dhG0ic38GzrhNTNth2W0IF12CQJfOAYALaQJDTImdISq/LZO4=

### Context

I'm trying to display an image from uploaded media (instead of asset or network).

### Visual documentation

![1](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/0a5a90c7-6418-4588-bf66-1879afa70575/50bdecf6-c67d-406f-a59a-bf4024b5c072?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wYTVhOTBjNy02NDE4LTQ1ODgtYmY2Ni0xODc5YWZhNzA1NzUvNTBiZGVjZjYtYzY3ZC00MDZmLWE1OWEtYmY0MDI0YjVjMDcyIiwiaWF0IjoxNzA4MDc1NTMwLCJleHAiOjMzMjc4NjM1NTMwfQ.r6_bq2xJbtST-kGR2DA7OTuxB9Xs4uGtrB__dGwjWwA)

![2](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/50019328-33aa-47f2-8dc5-5b2e759a21dd/3a56400d-fa1b-47b1-b7fc-271caffcf2d6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81MDAxOTMyOC0zM2FhLTQ3ZjItOGRjNS01YjJlNzU5YTIxZGQvM2E1NjQwMGQtZmExYi00N2IxLWI3ZmMtMjcxY2FmZmNmMmQ2IiwiaWF0IjoxNzA4MDc1NTMwLCJleHAiOjMzMjc4NjM1NTMwfQ.avkp6KlDgKpquUHQARrOCh59TiQ2xVzuJoqk4_FKmrk)

![3](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/c1a69a74-e90f-4c0c-a451-f1955d7191ea/716d77e7-0fa9-424c-94f4-069f448ef259?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jMWE2OWE3NC1lOTBmLTRjMGMtYTQ1MS1mMTk1NWQ3MTkxZWEvNzE2ZDc3ZTctMGZhOS00MjRjLTk0ZjQtMDY5ZjQ0OGVmMjU5IiwiaWF0IjoxNzA4MDc1NTMwLCJleHAiOjMzMjc4NjM1NTMwfQ.pFOd2HWeae20lIMz_cE6FDzum8LHU2GU2QLLHW-ZcwM)

![4](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/66dcb056-8de4-4c13-8760-2c8499339b06/6eba9d20-40e8-4745-bddd-a1928e1f3f6e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82NmRjYjA1Ni04ZGU0LTRjMTMtODc2MC0yYzg0OTkzMzliMDYvNmViYTlkMjAtNDBlOC00NzQ1LWJkZGQtYTE5MjhlMWYzZjZlIiwiaWF0IjoxNzA4MDc1NTMwLCJleHAiOjMzMjc4NjM1NTMwfQ.E-82WMYrZCBumKRnhIuIjMvgKnhsg76VsR2y4ldYcTw)

[https://github.com/FlutterFlow/flutterflow-issues/assets/20778155/33c3bff3-3730-4a2a-9213-c537936ed859](https://github.com/FlutterFlow/flutterflow-issues/assets/20778155/33c3bff3-3730-4a2a-9213-c537936ed859)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow v4.1 released February 15, 2024
- Flutter version is 3.13.7
- Platform: Run mobile ios and android
- Browser name and version: Chrome
- Operating system and version affected: I'm using windows, did not try on Mac.
```

**Comment by Kato-iOS** [comment] 2024-02-16 11:29
Update:
- Firebase upload stopped also working
- Now the full section Upload Type (Firebase or Local File) has been removed completely and no longer available.  

I'm not entirely sure if this is a new feature that they are trying to roll out or what else could it be. But it seem really strange that a feature just ups and disappear.

![1](https://github.com/FlutterFlow/flutterflow-issues/assets/20778155/b5535eb0-e643-4f9b-9e33-68117f38817f)

**Comment by hariprasadms** [comment] 2024-02-16 12:05
Hi @Kato-iOS - Thanks for submitting the issue. I have verified the steps you provided above. To use the uploaded file to a local file, below option should be used instead media source type as _camera or gallery_ . 

<img width="929" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/c9ec595c-9de4-4167-babb-d5a53e774d0f">

However, I've noticed a technical glitch in your configuration that allows selecting media and crashes the app on real devices. This issue needs investigation, and I'll mark it as a bug.

**Comment by Kato-iOS** [comment] 2024-02-16 13:56
Hi @hariprasadms and @takashiff,

Firstly, I want to thank you for reviewing my bug report. I've read your response, and in an effort to expedite resolving this issue, I've based my actions on the assumption that it's related to my project configuration and my ability to access or view different features (as suggested). However, it appears this is not the issue. To illustrate my point, I conducted a test by opening a new FlutterFlow account using a different browser, under a different email, without any cookies or connection to my original account, and I encountered the exact same issues (please see the attached pictures).

Additionally, concerning the feature I mentioned, it seems to be the same one that most premium or paid users have access to, as demonstrated in the videos posted by these YouTubers: [link](https://www.youtube.com/watch?v=8CIWXoOWBe8) and [link](https://www.youtube.com/watch?v=fXhF_9Ll3Fc&t=5s). I thought it would be helpful to share my findings.

I don't mean to come across as selfish, but the pressing question now is, how can I or any other user who creates a new account currently perform simple tasks like uploading media to local storage and Firestore, especially since this option was removed from the dashboard today?

Thank you in advance for your assistance.
Cheers,
Amato

![1](https://github.com/FlutterFlow/flutterflow-issues/assets/20778155/caad16b8-ac07-408b-acfe-d493db8a41bb)
![2](https://github.com/FlutterFlow/flutterflow-issues/assets/20778155/353f53e7-ca01-46e8-919a-c4fc14f29a22)
![2B](https://github.com/FlutterFlow/flutterflow-issues/assets/20778155/62f09ba1-3b6c-4baa-92fd-70e93937564f)
![3](https://github.com/FlutterFlow/flutterflow-issues/assets/20778155/a3dfdc3a-b239-4305-ba37-2c01884a2cb9)

**Comment by KevDev99** [comment] 2024-02-16 14:30
There must be a bug since FlutterFlow Version 4.1, after updated yesterday uploads are not working anymore:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/102754713/8363e76d-1a3b-4ed5-be1f-bb00af662fb7)


Checking Logs:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/102754713/40282ba3-c72d-4ad6-a4a6-b582c92fc6da)

**Comment by Kato-iOS** [comment] 2024-02-16 14:40
@KevDev99 I was literally just about to post the same mate :) !It refuses to connect from the get go! The thing is that it seems unlikely that they pushed the new version without any unit testing that would cover this. My best guess is either something was changed in some Meta Tags, or Some security feature was added or changed that crashes with CSP! The ideal case scenario here would be to revert to previous repo/build whilst fixing this. Let's wait to here from the team! 
Cheers mate!

![Screenshot 2024-02-16 183210](https://github.com/FlutterFlow/flutterflow-issues/assets/20778155/4c275b3f-1232-4900-baeb-59c3011e869d)

![Screenshot 2024-02-16 183339](https://github.com/FlutterFlow/flutterflow-issues/assets/20778155/53f16ca9-0584-4b0b-bc24-dc1074637a92)

**Comment by KevDev99** [comment] 2024-02-16 14:43
@Kato-iOS well at least i'm not alone haha :D yes, it is unbelievable that such standard components are not tested. somehow the problem has crept in very strangely... i will download the code and check directly from VSCode if i can see something further...

**Comment by KevDev99** [comment] 2024-02-16 15:35
its definitely an issue with the FlutterFlow Web Emulator. It works on all Platforms when compiling locally (Tested Web, Android, iOS)

**Comment by hariprasadms** [comment] 2024-02-16 15:54
Every everyone for additional details. The issue has been already marked as bug. We will look into shortly. Thanks

**Comment by Kato-iOS** [comment] 2024-02-16 15:56
@KevDev99 yes mate, I also tried to deploy on Testflight when I saw the issue with the JS and Tags and works there. It kind of defeat the purpose though :) I mean if you have to code and test separately also withtout knowing what will and will not display or throw errors. I wonder in in future they will add an option to link to LambdaTest as a failsafe for when the regular run and test don't work.  @hariprasadms great, all noted. Thank you in advance for the prompt resolution. Cheers guys

**Comment by cartworthy** [comment] 2024-02-16 19:17
I just want to chime in that my entire app functionality is built around users uploading photos. They all stopped working today and it resulted in hours of wasting time trying to debug an issue that is caused by this faulty update. I can not move forward until this is resolved.

I'm only commenting in hopes to raise this bug in the priority list — this is likely affecting many users. Thank you!

**Comment by KevDev99** [comment] 2024-02-16 19:25
just tested with the newest version and it works for me again. @hariprasadms thanks!

**Comment by KevDev99** [comment] 2024-02-16 19:26
> I just want to chime in that my entire app functionality is built around users uploading photos. They all stopped working today and it resulted in hours of wasting time trying to debug an issue that is caused by this faulty update. I can not move forward until this is resolved.
> 
> I'm only commenting in hopes to raise this bug in the priority list — this is likely affecting many users. Thank you!

@cartworthy they issue shouldn't be at the users directly. In my case it worked in the android and ios apps without any problems, the only issue was in the web emulator

**Comment by cartworthy** [comment] 2024-02-16 19:36
> just tested with the newest version and it works for me again. @hariprasadms thanks!

How do you get the newest version of the web emulator? I tried hitting the play button to build a new prototype, but the uploads still are not working on my end.

**Comment by cartworthy** [comment] 2024-02-16 19:38
I just realized Lotties also are not showing up at all with this update!

**Comment by KevDev99** [comment] 2024-02-16 19:47
Sorry my last information was wrong but its now clear that the issue is coming from the latest security updates which now all browser automatically install ( my private one had still an older browser version and therefore it worked until the browser got updated)

**Comment by KevDev99** [comment] 2024-02-16 19:48
> I just realized Lotties also are not showing up at all with this update!

have you compiled the project locally ?

**Comment by cartworthy** [comment] 2024-02-16 19:54
@KevDev99 

> > I just realized Lotties also are not showing up at all with this update!
> 
> have you compiled the project locally ? To check it on android / ios ?

No, but I tried deploying to the app store to test via TestFlight and that failed...I'm guessing it's related because I haven't changed anything on my app.

```
Error: ERROR: Asset validation failed (90186) Invalid Pre-Release Train. The train version '8.1.5' is closed for new build submissions

Error: ERROR: Asset validation failed (90062) This bundle is invalid. The value for key CFBundleShortVersionString [8.1.5] in the Info.plist file must contain a higher version than that of the previously approved version [8.1.5].
```

**Comment by cartworthy** [comment] 2024-02-16 22:41
> > I just realized Lotties also are not showing up at all with this update!
> 
> have you compiled the project locally ? To check it on android / ios ?

@KevDev99 No, but I just deployed it to TestFlight and everything works normally there. Still no Media Uploads or Lotties showing up on the web emulator though.

**Comment by Kato-iOS** [comment] 2024-02-17 07:20
Hi guys, the issue appears to be fixed. I will wait for the FlutterFlow Team to confirm before closing the issue as resolved. @agreaves , could you please confirm?

**Comment by agreaves** [comment] 2024-02-18 23:19
Hi @Kato-iOS, apologies for not updating! This issue was indeed fixed two days ago, glad to see it's working for you now!

Closing this issue accordingly.

**Closed by agreaves** 2024-02-18 23:19 UTC
Labels: status: confirmed, Bug

**Comment by Kato-iOS** [comment] 2024-02-19 07:00
HI @agreaves no worries, thanks appreciated the prompt resolution. Cheers mate
