### ISSUE TITLE
API Call Returns 200 (Success) but null body in FF, when Postman returns full JSON. 

### ISSUE THREAD

**Issue by jerico-johns** [FlutterFlow/flutterflow-issues#151] opened 2022-11-22 17:42 UTC
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
The GET response should return a JSON formatted table from Google Cloud Storage. (See Image for Postman response)
![Screen Shot 2022-11-22 at 9 36 31 AM](https://user-images.githubusercontent.com/76978523/203383009-7ea14fc6-2836-485f-900e-359e4c9c5e59.png)

## Current behavior (required)
The API call gives 'Status: 200 (Success)' but is null. (See image). Dropping the ?alt=media portion gives the object metadata succesfully. I believe this issue started after the v3.0 Flutterflow updates. 

![Screen Shot 2022-11-22 at 9 35 58 AM](https://user-images.githubusercontent.com/76978523/203382857-3f84f29f-02fb-486c-b02b-694692bf3a9f.png)

## To Reproduce (required)

1. in FF, Define a new API Call as 'GET https://storage.googleapis.com/storage/v1/b/pool-party-e4d98.appspot.com/o/firebasetable?alt=media' 
2. Test API Call 

### Bug Report Code

FutureBuilder<ApiCallResponse>(
  future: GetBigQueryCall.call(),
  builder: (context, snapshot) {
    // Customize what your widget looks like when it's loading.
    if (!snapshot.hasData) {
      return Center(
        child: SizedBox(
          width: 50,
          height: 50,
          child: CircularProgressIndicator(
            color: FlutterFlowTheme.of(context).primaryColor,
          ),
        ),
      );
    }
    final columnGetBigQueryResponse = snapshot.data!;
    return Builder(
      builder: (context) {
        final body = getJsonField(
          columnGetBigQueryResponse.jsonBody,
          r'''$''',
        ).toList();
        return Column(
          mainAxisSize: MainAxisSize.max,
          children: List.generate(body.length, (bodyIndex) {
            final bodyItem = body[bodyIndex];
            return StreamBuilder<List<SelectionsRecord>>(
              stream: querySelectionsRecord(
                queryBuilder: (selectionsRecord) =>
                    selectionsRecord.orderBy('game_id'),
              ),
              builder: (context, snapshot) {
                // Customize what your widget looks like when it's loading.
                if (!snapshot.hasData) {
                  return Center(
                    child: SizedBox(
                      width: 50,
                      height: 50,
                      child: CircularProgressIndicator(
                        color: FlutterFlowTheme.of(context).primaryColor,
                      ),
                    ),
                  );
                }
                List<SelectionsRecord> textSelectionsRecordList =
                    snapshot.data!;
                return Text(
                  getJsonField(
                    columnGetBigQueryResponse.jsonBody,
                    r'''$''',
                  ).toString(),
                  style: FlutterFlowTheme.of(context).bodyText1,
                );
              },
            );
          }),
        );
      },
    );
  },
)

## Context (required)

I am unable to load the necessary data from Google Cloud Storage for my app. 

## Your environment

* Version of FlutterFlow used: v3.0
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome 
* Operating system and version (desktop or mobile): MacOS Monterey (Version 12.6.1)

**Comment by hariprasadms** [comment] 2022-11-23 15:06
Hi, Looks like this is related to authentication issue. Have you add the authentication details in FF api call which is same as in postman?. What happens when hit the endpoint directly on a browser? Could you please confirm these details please.

**Comment by jerico-johns** [comment] 2022-11-28 18:49
The endpoint in Google Cloud Storage is public so no auth is required. You can see Postman is not using any auth. Hitting the endpoint in browser directly (pasting the request in as URL) works without issue. Feel free to try as this is a public object in GCS. 

![Screen Shot 2022-11-28 at 10 47 57 AM](https://user-images.githubusercontent.com/76978523/204356498-1a2bc129-5019-4d63-8ed5-4208ad89a306.png)

**Comment by jerico-johns** [comment] 2022-12-06 20:04
To update I believe this issue arose after the FlutterFlow v3.3.4 updates on November 18th, 2022. I was able to hit this API endpoint within FF with no issue before that update.

**Comment by Francabral11** [comment] 2023-01-19 07:14
Hi, I'm having the same problem when I use a variable as a parameter in the post method, it returns status 200 null

**Comment by pstatile** [comment] 2023-03-01 15:48
Same here...

**Comment by hariprasadms** [comment] 2023-03-12 23:07
Hello, Looks like this issue is specific endpoint return type. End point return formate is not as standard json formate instead it is in a sort of table formate. This is specific to firebase storage endpoint. This is not a bug. However, I can mark this as a feature request.

**Comment by agreaves** [comment] 2023-07-09 23:33
Hi @jerico-johns, thanks for this bug report! Just wanted to round out this older issue and provide more context.

The response for this (and likely other APIs mentioned here) is not a valid JSON response, so it's not being parsed in the same way as most responses. This means that the preview will not show up in the API test response because currently this only supports standard JSON bodies.

In the UI Builder however you have additional options. Instead of selecting `JSON Body` from the `API Response Options`, you can select `Raw Body Text` as seen below:

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/7757399/4e2652d1-ffd7-4a95-a7f9-c082f461ef03)

This allows you to use the raw API body as you please!

Closing this issue for now, but hope this helps!

**Closed by agreaves** 2023-07-09 23:33 UTC
Labels: type: feature request
