### ISSUE TITLE
API Response as DataType struggling with Dates

### ISSUE THREAD

**Issue by eavendano** [FlutterFlow/flutterflow-issues#2203] opened 2024-01-19 17:02 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I read about the new feature in an email you guys sent as an update. As soon as I tried to use it, I found that it does not work with dates. Here is the feature specified in the email:

![Captura de pantalla 2024-01-19 a la(s) 10 42 10](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/fb56d2f4-6428-44bb-a63c-0f45c606422e/47e55b80-beae-45f7-8427-89773e3299d5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mYjU2ZDJmNC02NDI4LTQ0YmItYTYzYy0wZjQ1YzYwNjQyMmUvNDdlNTViODAtYmVhZS00NWY3LTg0MjctODk3NzNlMzI5OWQ1IiwiaWF0IjoxNzA2OTY0MDY5LCJleHAiOjMzMjc3NTI0MDY5fQ.MapLgZLTWAjDO31gQrL72cgORVxdcDvK4eDVwgsTujU)

I have Supabase setup, and I'm using a Custom API Call to the backend; I get the most recent organization and was using JSON Path to update the App State's current organization. My Organization DataType has two fields defined as DateTime defined as `created_at` and `updated_at`. Now that I'm transitioning to Result as DataType, I'm getting the following error on my console:

```
Uncaught (in promise) Error: Expected a value of type 'DateTime?', but got one of type 'String'
```

### Expected Behavior

Seamless transition to a DataType in the API without DateTime issues.

### Steps to Reproduce

1. Define a datatype in Flutterflow that contains a DateTime field.
2. Define a 1:1 mapping table on Supabase.
3. Create an API Call for Supabase and use the Result as DataType Feature.
4. On the API call Action, you can use the following configuration:

![Captura de pantalla 2024-01-19 a la(s) 10 56 35](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/d6ef9dd8-0655-4af4-a349-ff6a2802f328/03be913e-3da5-4f10-970b-4c2a87446fa3?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kNmVmOWRkOC0wNjU1LTRhZjQtYTM0OS1mZjZhMjgwMmYzMjgvMDNiZTkxM2UtM2RhNS00ZjEwLTk3MGItNGMyYTg3NDQ2ZmEzIiwiaWF0IjoxNzA2OTY0MDY5LCJleHAiOjMzMjc3NTI0MDY5fQ.CqgxWDJQTcxkLgbKOvDlGnNjhh0PEguxJNP2LcTLol0)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4si/Lqw5FNoblE7rruY8J7/Sk6Nn44R40wscp/bxIgGIDzPOw+ZPWlSFhCQuLgT0FEJkSmmk0zptbskvOeE/ddCxCuGao9+LVucQvveEChe5OBBbmZOXZCEcFQIW7C0KbYrREmPulfSU4k61+mCtm8ShTcNb7GIndISq/LZO4=

### Context

Just remove the JSON Path usage but the new feature is struggling with DateTime

### Visual documentation

![Captura de pantalla 2024-01-19 a la(s) 10 58 57](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/daefe97c-0bc9-43e3-9f15-ba357feec140/1db5606f-42f3-4510-83ec-625a76785134?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kYWVmZTk3Yy0wYmM5LTQzZTMtOWYxNS1iYTM1N2ZlZWMxNDAvMWRiNTYwNmYtNDJmMy00NTEwLTgzZWMtNjI1YTc2Nzg1MTM0IiwiaWF0IjoxNzA2OTY0MDY5LCJleHAiOjMzMjc3NTI0MDY5fQ.ycB4DWUMbzrqeBtTvISqe1vdKYdg2oGhV7-cH7bMyvU)

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: v4.0 released January 15, 2024
- Platform: Mobile
- Browser name and version: Bave Versión 1.61.120 Chromium: 120.0.6099.234 (Build oficial) (arm64)
- Operating system and version affected: Mac OS Sonoma 14.2.1
FlutterFlow v4.0 released January 15, 2024
Flutter version is 3.13.7
```

**Comment by Franco98404** [comment] 2024-01-24 20:51
I have this error too

**Comment by VictorAndCo** [comment] 2024-01-30 16:43
Same issue here, with 3rd party API - "parse as datatype" doesn't work.

**Comment by eavendano** [comment] 2024-02-14 03:03
This issue should not be stale

**Comment by Franco98404** [comment] 2024-02-14 10:12
> This issue should not be stale

I agree but lately the FlutterFlow team has been taking a long time to fix the bugs

**Comment by eavendano** [comment] 2024-02-20 16:01
beep

**Comment by Night-coyote** [comment] 2024-02-23 02:20
It essential issue. It Doesn't allow to use automatic convertion api responce to data type if it has datetime fields

**Comment by diegoserranobst** [comment] 2024-03-11 11:57
flutterflow team plase give an answer. I have same issue. I ask to support and Steve not know what we are talking about.

**Comment by Franco98404** [comment] 2024-03-11 11:59
> flutterflow team plase give an answer. I have same issue. I ask to support and Steve not know what we are talking about.

I have the same problem with the support team with various bugs :c

**Comment by rwbrown2022** [comment] 2024-03-12 18:37
I am blocked by the same behavior with any non-primitive json objects including dateTime, Firebase document references and lists. I tried nested data types where each complex field is a data type containing one field of the desired type. The code now compiles but every complex type is set to null. I am trying to solve this with custom code with no luck so far.

**Comment by paulperez-dev** [comment] 2024-04-17 21:23
Hi @eavendano, I'm sorry for the delay in the response, we are trying to get up to speed with everything. I'm moving this to the ENG team so they can work on this! 

Thanks for your feedback!

**Comment by paulperez-dev** [comment] 2024-04-18 00:08
Hi @eavendano! This is not a bug. JSON responses don't have non-primitive data types such as datetime, firestore document ID, etc. It is all stored as a string.

The new feature defaults all non-primitive data types to string.

**Closed** 2024-04-18 00:13 UTC
Labels: status: confirmed, Bug

**Comment by constant-work** [comment] 2024-05-02 16:14
Perhaps I am missing something here, but what is the point of having a DateTime Data Type if it is not possible to pass a date or time to it from an API that returns JSON (eg. most APIs)?

It would seem to me a primary use case for using a Data Schema would be to manage API responses.

> Hi @eavendano! This is not a bug. JSON responses don't have non-primitive data types such as datetime, firestore document ID, etc. It is all stored as a string.
> 
> The new feature defaults all non-primitive data types to string.

**Comment by constant-work** [comment] 2024-05-02 17:08
My work around is to not use Data Types / Data Schemas for dates or times retrieved from JSON. Instead, if I want to populate a Text widget with a date from a JSON API response, I call a custom function which accepts a date string and returns a Flutter DateTime object. Since the Text widget is now working with a Flutter DateTime object returned by the custom function, all the options for manipulating the display of a date become available. I hope this helps someone else (and I hope FlutterFlow makes this a native feature!). Here is the custom function:

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/160641563/79c4164e-ee0a-4874-940c-48db7fd17b1d)

**Comment by eavendano** [comment] 2024-05-03 00:19
Hi! @constant-work! I think the point is not the workaround. To me it looks like false advertising regarding a feature that was announced with that exact functionality.

"You can parse your own data without using JSON Schema since JSON Schema is error prone." Quoting the email featuring the announcement. Now that the feature is live, all the persons following this thread had used JSON Schema without issues and the supposed feature doesn't support dates.

Now, I'm a Senior engineer and parsing dates is not that hard, yes there are formatting and cutover or time switching issues (looking at you US and the dumb daylight switch over), BUT as long as you can use a simple converter and use UTC on your formatting you should be good for most cases. If you use Epoch all you should consider is precision 8 or 13 digits after the dot. If you are using Julian formatting, you truly have an old enterprise system but dates should not be a problem.

Even then, the feature could allow you to specify a parsing function or something where you easily can shape your date into something comprehensive. Dates are simple strings and should not be an issue in my opinion.

**Comment by JLENF** [comment] 2024-05-19 02:06
@constant-work thank you!!

**Comment by arniigreat1** [comment] 2024-06-09 22:00
@constant-work thanks for this. 

@paulperez-dev I would argue timestamp is an issue as with what constant-work says. Shouldn't have timestamp as a datatype option if we can't even use it with JSON. 

In reality, with everyone's projects that becomes more complex, we will be needing to convert the date time every single time we import it into our databases and when we extract. Then it'll become more annoying once theirs more timezones and use cases

Sure, we can say it's not a problem, but the entire idea of FF is to make it easy and no code. And for someone with no coding experience, they won't be able to parse the string to datetime - given the entire idea of FF is to now give everyone the ability to build and be developers. And this dateTime should be an easy service imo

> Hi @eavendano! This is not a bug. JSON responses don't have non-primitive data types such as datetime, firestore document ID, etc. It is all stored as a string.
> 
> The new feature defaults all non-primitive data types to string.

**Comment by oliversl** [comment] 2024-07-04 21:56
Here is the function:

DateTime dateTime = DateTime.parse(dateString);
return dateTime;

**Comment by winwintangelo** [comment] 2024-07-08 19:26
Interesting that image URL in API response will be automatically converted to imagePATH object with no problem. 

The Date/Time object is the the most used fields in 90% API calls, not supported OOTB is lack of user empathy. 


> @constant-work thanks for this.
> 
> @paulperez-dev I would argue timestamp is an issue as with what constant-work says. Shouldn't have timestamp as a datatype option if we can't even use it with JSON.
> 
> In reality, with everyone's projects that becomes more complex, we will be needing to convert the date time every single time we import it into our databases and when we extract. Then it'll become more annoying once theirs more timezones and use cases
> 
> Sure, we can say it's not a problem, but the entire idea of FF is to make it easy and no code. And for someone with no coding experience, they won't be able to parse the string to datetime - given the entire idea of FF is to now give everyone the ability to build and be developers. And this dateTime should be an easy service imo
> 
> > Hi @eavendano! This is not a bug. JSON responses don't have non-primitive data types such as datetime, firestore document ID, etc. It is all stored as a string.
> > The new feature defaults all non-primitive data types to string.

**Comment by bgbraga** [comment] 2024-07-26 12:27
@paulperez-dev that issue should not be closed.
It is simple to solve. If the target field on Data Type is Date Time, try to convert the string in Date Time (you could specify the expected ISO format).

If the target field is not Date Time, keep it as String.

**Comment by Arkhemis** [comment] 2024-07-31 11:56
Same issue here. I set up the whole thing as DataType because it was easier and now I'm stuck with this problem. At least, let us the possibility to set up the DateTime format in the datatype field. It would automatically know which type of datetime to expect and convert it accordingly.

**Comment by blanc-k** [comment] 2024-09-06 07:19
Same issue, it's my first comment on FF github, and this problem is a real pain point as a no-code user.
@leighajarett : Hi could you please take a look, it's a quick win action for your customer's satisfaction. BR

**Comment by julienwir** [comment] 2024-09-09 09:45
Same here, I want to sort my api results by last update date. Found a bad but working solution >> get an INT field updated in the backend for each update >> this int is sorted in FF api results >> then I convert the 10 first items with a custom function to get dates as dates. 
But not working perfectly neither.
NEED IT TO BE FIXED please, it's the most important data when doing api calls.
Good luck to all of u!

**Comment by azalty** [comment] 2024-09-27 13:57
This should seriously be addressed ASAP.

Flutterflow relies way too much on Firebase. Go add true support for APIs.

**Comment by iainmcfall** [comment] 2024-10-11 07:10
Just came across this issue in my first project where I am using APIs to return data. This needs to be addressed. (It would also be awesome to be able to use FFs inbuilt date format e.g. Relative)

**Comment by NickTretiakov** [comment] 2024-10-19 15:06
Same here, spent like 4 hours on it until I suddenly found this thread...

**Comment by wgtrevillyan** [comment] 2024-10-22 06:09
Issue still present

**Comment by rdeputat** [comment] 2025-01-13 05:58
That looks so rude 😒  @leighajarett 

<img width="951" alt="image" src="https://github.com/user-attachments/assets/697fc175-93fc-41b7-90d8-f0b6c8cb9f04" />

**Comment by tiagosilveiransj** [comment] 2025-01-17 21:43
Issue still present

**Comment by mtruebe** [comment] 2025-02-28 16:53
This would save everybody a lot of time. Its a pretty easy feature to convert an integer being passed to a datetime variable. I would think this is a few lines of code for the flutterflow team. Its annoying have to manage this throughout the application. These little issues add up and cause performance degredations all over the place.

**Comment by squirrel-o** [comment] 2025-03-26 08:25
@paulperez-dev  @leighajarett could you look at this issue please? I'm having the same problem with our mySQL backend, and it's not feasible to have to add manual code to every single DateTime field in our BE. I specified the data type to expect, but it still doesn't get the DateTimes right. It's very much a bug that FF doesn't read JSON responses right

**Comment by alohacorey** [comment] 2025-03-26 17:37
Agree with everyone here. This needs fixed to parse DateTime properly from JSON.

**Comment by Ajris** [comment] 2025-03-29 12:48
Well, it is funny that they are just closing those issues without any info :)

**Comment by wemmick** [comment] 2025-05-06 05:51
One more request here - please fix this, guys!

**Comment by mtruebe** [comment] 2025-05-21 23:34
Please fix

**Comment by HugoCrd** [comment] 2025-06-20 11:43
This feature would really help, indeed.
