### ISSUE TITLE
The loop option for YouTube video player does not work. 

### ISSUE THREAD

**Issue by hughCar389** [FlutterFlow/flutterflow-issues#1121] opened 2023-07-14 16:41 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When the video ends it does not loop when the option is selected. 

### Expected Behavior

The video needs to loop when finished. 

### Steps to Reproduce

1)Add an app bar
2)add a list view then a container 
3)add YouTube video player to the container
2) select the loop video, show controls, show full screen controls, and pause on forward navigation 
3) Add a YouTube URL 
4)The video should have a width of 100 and Height of 42
5)Preview the app 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfkM/l7ZBgoctH176JKcJVvDgWH18cT7kRlOtxc0kgIozPPJkAOvfOTERDUu7iY3w2MWejkWoW097nheLhGsECaQeubaE5+at2VBXKRkOVSpC6FJWgYWt7I9pgBUPG4cONrRN+AM1tS3A83U+EA9mWfD3DN7rEIXo8Dq/LZO4=

### Context

The goal is for users to watch videos that only suggest Hughston Videos. If the app suggests inappropriate content then it negates the functionality of the app. 

### Visual documentation

![Capture](https://github.com/FlutterFlow/flutterflow-issues/assets/124802801/94a8c36d-009a-43cf-9e38-6cc2d41cfd60)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Chrome and 114.0.5735.199
- Operating system and version affected: Windows and 10
```

**Comment by SameerShahzad99** [comment] 2023-07-14 18:09
@hughCar389 Although this bug report was not with a blank project with an issue setup, Thank you so much for submitting it, I can reproduce this bug!

**Comment by aemelyanovff** [comment] 2023-07-14 18:41
Duplicate of https://github.com/FlutterFlow/flutterflow-issues/issues/1019

**Closed by aemelyanovff** 2023-07-14 18:41 UTC
Labels: type: bug, status: confirmed
