### ISSUE TITLE
Project Builds Failed.

### ISSUE THREAD

**Issue by Dev-Muhammad-Junaid** [FlutterFlow/flutterflow-issues#3081] opened 2024-06-07 22:21 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The project has no errors and it should run fine but it crashes due to package conflicts

### Expected Behavior

```
Seems to be related to Enums package conflicts.

70 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Launching lib/main.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...      
lib/create_activity_page/create_activity_page_widget.dart:779:38: Error: 'Category' is imported from both 'package:flutter/src/foundation/annotations.dart' and 'package:touch_pointz_life2024/backend/schema/enums/enums.dart'.
                              return Category.METime.name;
                                     ^^^^^^^^
lib/create_activity_page/create_activity_page_widget.dart:782:38: Error: 'Category' is imported from both 'package:flutter/src/foundation/annotations.dart' and 'package:touch_pointz_life2024/backend/schema/enums/enums.dart'.
                              return Category.LifeAdmin.name;
                                     ^^^^^^^^
lib/create_activity_page/create_activity_page_widget.dart:784:38: Error: 'Category' is imported from both 'package:flutter/src/foundation/annotations.dart' and 'package:touch_pointz_life2024/backend/schema/enums/enums.dart'.
                              return Category.KidsAdmin.name;
                                     ^^^^^^^^
lib/create_activity_page/create_activity_page_widget.dart:800:46: Error: 'Category' is imported from both 'package:flutter/src/foundation/annotations.dart' and 'package:touch_pointz_life2024/backend/schema/enums/enums.dart'.
                                      return Category.METime.name;
                                             ^^^^^^^^
lib/create_activity_page/create_activity_page_widget.dart:803:46: Error: 'Category' is imported from both 'package:flutter/src/foundation/annotations.dart' and 'package:touch_pointz_life2024/backend/schema/enums/enums.dart'.
                                      return Category.LifeAdmin.name;
                                             ^^^^^^^^
lib/create_activity_page/create_activity_page_widget.dart:805:46: Error: 'Category' is imported from both 'package:flutter/src/foundation/annotations.dart' and 'package:touch_pointz_life2024/backend/schema/enums/enums.dart'.
                                      return Category.KidsAdmin.name;
                                             ^^^^^^^^
Unhandled exception:
Unsupported operation: Unsupported invalid type InvalidType(<invalid>) (InvalidType). Encountered while compiling file:///tmp/ff_service_scratch/ReB16BoGPCynJ5VdyayZ/touch_pointz_life2024/lib/create_activity_page/create_activity_page_widget.dart, which contains the type: FunctionType(<invalid> Function()).
#0      ProgramCompiler._typeCompilationError (package:dev_compiler/src/kernel/compiler.dart:3678)
#1      ProgramCompiler._newEmitType (package:dev_compiler/src/kernel/compiler.dart:3471)
#2      ProgramCompiler._emitType (package:dev_compiler/src/kernel/compiler.dart:3379)
#3      ProgramCompiler.visitFunctionType (package:dev_compiler/src/kernel/compiler.dart:3731)
#4      ProgramCompiler._emitFunctionTagged (package:dev_compiler/src/kernel/compiler.dart:3307)
#5      ProgramCompiler.visitFunctionExpression (package:dev_compiler/src/kernel/compiler.dart:7573)
#6      FunctionExpression.accept (package:kernel/ast.dart:8606)
#7      ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:4611)
#8      ProgramCompiler._emitMethodCall (package:dev_compiler/src/kernel/compiler.dart:5773)
#9      ProgramCompiler.visitFunctionInvocation (package:dev_compiler/src/kernel/compiler.dart:5683)
#10     FunctionInvocation.accept (package:kernel/ast.dart:6063)
#11     ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:4611)
#12     ProgramCompiler._emitNamedExpression (package:dev_compiler/src/kernel/compiler.dart:6845)
#13     ProgramCompiler._emitArgumentList (package:dev_compiler/src/kernel/compiler.dart:6837)
#14     ProgramCompiler.visitStaticInvocation (package:dev_compiler/src/kernel/compiler.dart:6735)
#15     StaticInvocation.accept (package:kernel/ast.dart:6576)
#16     ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:4611)
#17     ProgramCompiler._emitArgumentList (package:dev_compiler/src/kernel/compiler.dart:6834)
#18     ProgramCompiler._emitMethodCall (package:dev_compiler/src/kernel/compiler.dart:5774)
#19     ProgramCompiler.visitInstanceInvocation (package:dev_compiler/src/kernel/compiler.dart:5688)
#20     InstanceInvocation.accept (package:kernel/ast.dart:5768)
#21     ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:4611)
#22     ProgramCompiler.visitAwaitExpression (package:dev_compiler/src/kernel/compiler.dart:7555)
#23     AwaitExpression.accept (package:kernel/ast.dart:8539)
#24     ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:4611)
#25     ProgramCompiler.visitExpressionStatement (package:dev_compiler/src/kernel/compiler.dart:4688)
#26     ExpressionStatement.accept (package:kernel/ast.dart:9142)
#27     ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:4520)
#28     MappedListIterable.elementAt (dart:_internal/iterable.dart:425)
#29     ListIterator.moveNext (dart:_internal/iterable.dart:354)
#30     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189)
#31     new _GrowableList.of (dart:core-patch/growable_array.dart:150)
#32     new List.of (dart:core-patch/array_patch.dart:39)
#33     SetBase.toList (dart:collection/set.dart:119)
#34     ProgramCompiler.visitBlock (package:dev_compiler/src/kernel/compiler.dart:4701)
#35     Block.accept (package:kernel/ast.dart:9195)
#36     ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:4520)
#37     ProgramCompiler._emitFunctionScopedBody (package:dev_compiler/src/kernel/compiler.dart:4553)
#38     ProgramCompiler._emitGeneratorFunctionExpression.emitGeneratorFn.<anonymous closure>.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:4129)
#39     ProgramCompiler._withLetScope (package:dev_compiler/src/kernel/compiler.dart:2829)
#40     ProgramCompiler._withCurrentFunction (package:dev_compiler/src/kernel/compiler.dart:4296)
#41     ProgramCompiler._emitGeneratorFunctionExpression.emitGeneratorFn.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:4128)
#42     ProgramCompiler._superDisallowed (package:dev_compiler/src/kernel/compiler.dart:4307)
#43     ProgramCompiler._emitGeneratorFunctionExpression.emitGeneratorFn (package:dev_compiler/src/kernel/compiler.dart:4123)
#44     ProgramCompiler._emitGeneratorFunctionExpression (package:dev_compiler/src/kernel/compiler.dart:4221)
#45     ProgramCompiler._emitGeneratorFunctionBody (package:dev_compiler/src/kernel/compiler.dart:4282)
#46     ProgramCompiler._emitFunction (package:dev_compiler/src/kernel/compiler.dart:4061)
#47     ProgramCompiler._emitArrowFunction (package:dev_compiler/src/kernel/compiler.dart:7578)
#48     ProgramCompiler.visitFunctionExpression (package:dev_compiler/src/kernel/compiler.dart:7571)
#49     FunctionExpression.accept (package:kernel/ast.dart:8606)
#50     ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:4611)
#51     ProgramCompiler._emitNamedExpression (package:dev_compiler/src/kernel/compiler.dart:6845)
#52     ProgramCompiler._emitArgumentList (package:dev_compiler/src/kernel/compiler.dart:6837)
#53     ProgramCompiler.visitConstructorInvocation (package:dev_compiler/src/kernel/compiler.dart:7059)
#54     ConstructorInvocation.accept (package:kernel/ast.dart:6660)
#55     ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:4611)
#56     ProgramCompiler._emitNamedExpression (package:dev_compiler/src/kernel/compiler.dart:6845)
#57     ProgramCompiler._emitArgumentList (package:dev_compiler/src/kernel/compiler.dart:6837)
#58     ProgramCompiler.visitConstructorInvocation (package:dev_compiler/src/kernel/compiler.dart:7059)
#59     ConstructorInvocation.accept (package:kernel/ast.dart:6660)
#60     ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:4611)
#61     ProgramCompiler._emitNamedExpression (package:dev_compiler/src/kernel/compiler.dart:6845)
#62     ProgramCompiler._emitArgumentList (package:dev_compiler/src/kernel/compiler.dart:6837)
#63     ProgramCompiler.visitConstructorInvocation (package:dev_compiler/src/kernel/compiler.dart:7059)
#64     ConstructorInvocation.accept (package:kernel/ast.dart:6660)
#65     ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:4611)
#66     MappedListIterable.elementAt (dart:_internal/iterable.dart:425)
#67     ListIterator.moveNext (dart:_internal/iterable.dart:354)
#68     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189)
#69     new _GrowableList.of (dart:core-patch/growable_array.dart:150)
#70     new List.of (dart:core-patch/array_patch.dart:39)
#71     SetBase.toList (dart:collection/set.dart:119)
#72     ProgramCompiler._visitExpressionList (package:dev_compiler/src/kernel/compiler.dart:4574)
#73     ProgramCompiler.visitListLiteral (package:dev_compiler/src/kernel/compiler.dart:7451)
#74     ListLiteral.accept (package:kernel/ast.dart:8160)
#75     ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:4611)
#76     ProgramCompiler._emitNamedExpression (package:dev_compiler/src/kernel/compiler.dart:6845)
#77     ProgramCompiler._emitArgumentList (package:dev_compiler/src/kernel/compiler.dart:6837)
#78     ProgramCompiler.visitConstructorInvocation (package:dev_compiler/src/kernel/compiler.dart:7059)
#79     ConstructorInvocation.accept (package:kernel/ast.dart:6660)
#80     ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:4611)
#81     ProgramCompiler._emitNamedExpression (package:dev_compiler/src/kernel/compiler.dart:6845)
#82     ProgramCompiler._emitArgumentList (package:dev_compiler/src/kernel/compiler.dart:6837)
#83     ProgramCompiler.visitConstructorInvocation (package:dev_compiler/src/kernel/compiler.dart:7059)
#84     ConstructorInvocation.accept (package:kernel/ast.dart:6660)
#85     ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:4611)
#86     ProgramCompiler._emitNamedExpression (package:dev_compiler/src/kernel/compiler.dart:6845)
#87     ProgramCompiler._emitArgumentList (package:dev_compiler/src/kernel/compiler.dart:6837)
#88     ProgramCompiler.visitConstructorInvocation (package:dev_compiler/src/kernel/compiler.dart:7059)
#89     ConstructorInvocation.accept (package:kernel/ast.dart:6660)
#90     ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:4611)
#91     ProgramCompiler._emitNamedExpression (package:dev_compiler/src/kernel/compiler.dart:6845)
#92     ProgramCompiler._emitArgumentList (package:dev_compiler/src/kernel/compiler.dart:6837)
#93     ProgramCompiler.visitConstructorInvocation (package:dev_compiler/src/kernel/compiler.dart:7059)
#94     ConstructorInvocation.accept (package:kernel/ast.dart:6660)
#95     ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:4611)
#96     ProgramCompiler._emitNamedExpression (package:dev_compiler/src/kernel/compiler.dart:6845)
#97     ProgramCompiler._emitArgumentList (package:dev_compiler/src/kernel/compiler.dart:6837)
#98     ProgramCompiler.visitConstructorInvocation (package:dev_compiler/src/kernel/compiler.dart:7059)
#99     ConstructorInvocation.accept (package:kernel/ast.dart:6660)
#100    ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:4611)
#101    ProgramCompiler.visitReturnStatement (package:dev_compiler/src/kernel/compiler.dart:5182)
#102    ReturnStatement.accept (package:kernel/ast.dart:10159)
#103    ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:4520)
#104    MappedListIterable.elementAt (dart:_internal/iterable.dart:425)
#105    ListIterator.moveNext (dart:_internal/iterable.dart:354)
#106    new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189)
#107    new _GrowableList.of (dart:core-patch/growable_array.dart:150)
#108    new List.of (dart:core-patch/array_patch.dart:39)
#109    SetBase.toList (dart:collection/set.dart:119)
#110    ProgramCompiler.visitBlock (package:dev_compiler/src/kernel/compiler.dart:4701)
#111    Block.accept (package:kernel/ast.dart:9195)
#112    ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:4520)
#113    ProgramCompiler._emitFunctionScopedBody (package:dev_compiler/src/kernel/compiler.dart:4553)
#114    ProgramCompiler._emitSyncFunctionBody.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:4259)
#115    ProgramCompiler._withLetScope (package:dev_compiler/src/kernel/compiler.dart:2829)
#116    ProgramCompiler._withCurrentFunction (package:dev_compiler/src/kernel/compiler.dart:4296)
#117    ProgramCompiler._emitSyncFunctionBody (package:dev_compiler/src/kernel/compiler.dart:4255)
#118    ProgramCompiler._emitFunction (package:dev_compiler/src/kernel/compiler.dart:4060)
#119    ProgramCompiler._emitMethodDeclaration.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:2392)
#120    ProgramCompiler._withMethodDeclarationContext (package:dev_compiler/src/kernel/compiler.dart:4323)
#121    ProgramCompiler._emitMethodDeclaration (package:dev_compiler/src/kernel/compiler.dart:2391)
#122    ProgramCompiler._emitClassMethods (package:dev_compiler/src/kernel/compiler.dart:2332)
#123    ProgramCompiler._emitClassDeclaration (package:dev_compiler/src/kernel/compiler.dart:932)
#124    ProgramCompiler._emitClass (package:dev_compiler/src/kernel/compiler.dart:846)
#125    List.forEach (dart:core-patch/growable_array.dart:416)
#126    ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:784)
#127    List.forEach (dart:core-patch/growable_array.dart:416)
#128    ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:505)
#129    IncrementalJavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:223)
the Dart compiler exited unexpectedly.
Waiting for connection from debug service on Web Server...         37.4s
Failed to compile application.
```

### Steps to Reproduce

1. Not sure how to reproduce this.
But the category names is the highlight that is causing conflicts with relevant enums.dart file.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ez8mB35VNtbxH1s/UbMdKoyQXNmYiU4E0lcJDcAwaNZ+vPLMMf+j+QHZVOMO/dFY3OlmI8T8fwM3Iuez1V8Y9PiiWfqI61c1yShaVXniXV5ikEZeRdHAkO5pUGEOHzbSzqyMnWfNsWHgS62GIG9yicB3UGY/7NjI/Hf2XNZD5nl6JLTLOXn0Jg1ZSfCvr

### Visual documentation

<img width="1076" alt="Screenshot 2024-06-08 at 3 16 45 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/65047962/25ed3dbc-868b-4c13-91a7-187c2818b18f">

### Environment

```markdown
-FlutterFlow v4.1.54+ released June 4, 2024
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: MACOS
```

### Additional Information

.

**Comment by paulperez-dev** [comment] 2024-06-08 23:10
Hi @Dev-Muhammad-Junaid! This error is because there is a `Category` class already defined in one of the imports. Try changing the name of your import and it should solve the build error. I'm closing this issue since this is not a bug.

**Closed as not planned** 2024-06-08 23:11 UTC
Labels: closed: not a bug
