### ISSUE TITLE
Enums are not correctly deserialized when being returned on an algolia search on iPhone and Android devices

### ISSUE THREAD

**Issue by QuinnGunter** [FlutterFlow/flutterflow-issues#3464] opened 2024-07-23 20:27 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

when creating a listview that shows the results of an algolia search if one of the fields is an enum it is not being deserialized and i believe it is being returned as a String causing a null value in the ui.

This is resolved on web. However is still an issue on iphone and android physical devices

### Expected Behavior

i expect to have the value properly valued as an enum on mobile devices as it is on web

### Steps to Reproduce

1. add a schema to firebase with a enum value in a field
2. add algolia to the project
3. add a listview that displays the results of an algolia search
4. add some variable that is set to the enum field of the algolia search with a default value i chose ERROR
5. **_run in test mode on android or ios_**
6. search for an item and see the value in the listview

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48lfLqw4VgoctF7r6Jc8Ewlj0vJl87U4E7jdYaZxU8J5zTP4YIP/v7ak5oO7ynT3NmJWGgrHEy/PfqifLDF8IqIRCuQYtxyqt2Wg/KJDuWVpCXEc2vfW1RHpthJlS/16ujmgp+VdJqdUY/22CQI96+dBXYHuP6Ino3IvmlKdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

| Functional on web/ run | issue on mobile test devices |
|--------|--------|
| https://github.com/user-attachments/assets/077ff2f5-016b-4325-abd1-bc6c580a4ab9 | https://github.com/user-attachments/assets/d5b4b25d-4d71-4164-9e29-b42a9599f01b | 

### Environment

```markdown
- FlutterFlow version: Version 4.1.75 (4.1.75)
- Platform: Local test or physical device
- Browser name and version: na
- Operating system and version affected:  macOS 14.5 (23F79)
```

### Additional Information

Same issue as here. Web and run modes work. However Ios and Android phones fail to display results. https://github.com/FlutterFlow/flutterflow-issues/issues/2756

**Comment by QuinnGunter** [comment] 2024-07-23 20:30
@mohn93 @fabiofcos if you are interested in following along

**Comment by Alezanello** [comment] 2024-07-24 12:13
Hello!

I tested it by creating a new event, and it shows up directly. However, when I try to search for it, there is an endless heart loader. This is very strange because no errors are showing in the console.

Do you have any logs from your side in Algolia regarding the search? Or have you tried using Algolia directly to search the documents?

Best regards,<br>Azanello

**Comment by QuinnGunter** [comment] 2024-07-24 13:44
Hi @Alezanello I do not have the logs regarding the search. When I search in Algolia with the same search the results are returned as expected. Even using the Run mode on this project will give me results instead of the infinite loader

**Comment by QuinnGunter** [comment] 2024-07-25 13:20
@Alezanello you'll find if you create an event with the "never" repeat option you will get the result to load when searched. Assuming that the search is unique to only the "never" repeat event.

**Comment by QuinnGunter** [comment] 2024-08-06 13:48
This issue is still present

**Comment by QuinnGunter** [comment] 2024-08-12 16:31
@Alezanello Any update on this? This is a major issue in my production application. Users can not use the search do to this.

**Comment by QuinnGunter** [comment] 2024-08-21 17:55
This is still an issue for me

**Comment by ryutosh** [comment] 2024-08-27 08:39
@Alezanello 
Still have problem in issue 3638 you closed as duplicate.

I tried to figure out the problem.
Then, knew "getDocumentFromData" causes run time error "ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'Fruits' is not a subtype of type 'String?".

`
SomeRecord.getDocumentFromData(
 {
  "favorite_fruit": Fruits.values.byName("orange"),  // Fruits is enums.
 },
 SomeRecord.collection.doc(docId)
`

**Comment by quillifyai** [comment] 2024-08-28 17:51
I have the same problem of the enum not deserializing correctly, but my use case is when I put it in a text widget in a generated list. From what I can tell in the code, it needs to look like this: 
extension FFEnumListExtensions<T extends Enum> on Iterable<T> {
  T? deserialize(String? value) => firstWhereOrNull((e) =>
      e.serialize() == value?.replaceAll("${T.toString()}.", "")); //Added the replaceAll
}

But I'll also note that while this method works in debug mode, it does not work in release mode

**Comment by ryutosh** [comment] 2024-09-06 04:58
@Alezanello 
With all due respect, what is your roadmap for this issue?
Sorry to ask such an intrusive question, but the suspension of the search function is fatal to the app.

I can't understand why it is labeled as “waiting for user response” even though other reports have been raised by other users.

**Comment by MortadhaFadhlaoui** [comment] 2024-09-23 16:40
A quick workaround :

>  'format': convertAlgoliaParam<Format>(
>             snapshot.data['format'],
>             ParamType.Enum,
>             false,
>           ),

 
###############################
> 'format': snapshot.data['format'],

**Comment by asifmasroor** [comment] 2024-11-02 07:32
I have the same issue and it's not resolving. @MortadhaFadhlaoui can you please explain where to update this code?

**Comment by QuinnGunter** [comment] 2024-11-12 16:07
I'd love to hear if there is any update here? Issue is still present and doesn't seem to be a priority to get fixed. This issue completely **blocks** the use of the integrated search with Algolia.

**Comment by asifmasroor** [comment] 2024-11-13 09:46
It seems like Flutterflow team is in sleep mode 📳

**Comment by asifmasroor** [comment] 2024-11-13 10:22
This issue was reported on July 24th. Almost 4 months have passed without any resolution. I don't understand how a CRITICAL bug like this can be ignored for so LONG. As @QuinnGunter stated, this is a MISSION-CRITICAL bug and without resolution, no app can stay live.

**Comment by quillifyai** [comment] 2024-11-14 14:01
I'm having the same persistent issue

**Comment by QuinnGunter** [comment] 2024-11-14 15:02
@leighajarett any word if this is something that is on the roadmap to be fixed? I appreciate any insight you can give on this.

**Comment by Alezanello** [comment] 2024-11-14 16:15
Hello everyone,

I sincerely apologize for the delay in my response. I missed track of this issue until today when I was alerted by the recent replies. I can confirm that this issue is occurring, and I will escalate it to the engineering team to work on a fix.

Thank you for your patience, and once again, I’m very sorry for the delay.

**Comment by QuinnGunter** [comment] 2024-11-14 16:30
Thank you so much for the update ❤️

**Comment by asifmasroor** [comment] 2024-11-17 06:10
@Alezanello Any timeline for the fix?

**Comment by asifmasroor** [comment] 2024-11-19 05:05
@victoriahuang1 Any updates?? This is EXTREMELY critical. At least acknowledge that you or anyone in your team is working on it?


> Hello everyone,
> 
> I sincerely apologize for the delay in my response. I missed track of this issue until today when I was alerted by the recent replies. I can confirm that this issue is occurring, and I will escalate it to the engineering team to work on a fix.
> 
> Thank you for your patience, and once again, I’m very sorry for the delay.

**Comment by QuinnGunter** [comment] 2024-12-03 21:07
Hello @victoriahuang1 , I want to keep the conversation going on this since we have seen it go stale several times. Is there any update if this will be fixes soon or any timeline on it? It is starting to feel frustrating that features in my app can't be released due to this issue that's been open since July.

**Closed as completed** 2024-12-11 17:23 UTC
Labels: status: confirmed, Bug

**Comment by QuinnGunter** [comment] 2024-12-12 15:53
Woooohooo! 🎉 🥳  This issue seems to be resolved on my side. While it took some back and forth I really appreciate the team, thank you!!

**Comment by asifmasroor** [comment] 2024-12-12 16:01
It is working now but only in release mode for me. In debug version, it is
Not working.

**Comment by kennette21** [comment] 2025-05-01 00:37
I am still experiencing this issue. Is anyone else?
