### ISSUE TITLE
iOS bug if I use a Bottom sheet

### ISSUE THREAD

**Issue by guillermo259** [FlutterFlow/flutterflow-issues#1042] opened 2023-06-24 20:57 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a bottom sheet loading an API in a dropdown when I select an Option and try to complete the form in iOS show me a gray screen in the bottom sheet.

### Expected Behavior

Select the option in the dropdown complete the form and send that data to the API

### Steps to Reproduce

Open the app in iOS 
select the first Demo 
try to add a product
complete the form
and show the bug

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4olsjfz4p2sdtE1s72ccBKjSQvJn57bY00mMpBZz0aIuPpDJl/PM/6P0tBZ+mmT2NUfVq2p14K0vTOi+PpG+4oPkmWf7Zb+ZFtVQviTTi7R8STF7qSeGtPL8RWN2bA4Z+JuQlAHMluc3Bm7WeuJu68ZBXtHrLQNWowSq/LZO4=

### Context

I cant upload my app to appstore because Apple show a bug

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/51971690/484d06b7-0efc-4a25-a4b0-f3e8c17e12b8

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Chrome 114.0.5735.134
- Operating system and version affected: iOS 16
```

**Comment by hariprasadms** [comment] 2023-07-03 10:51
Hi @guillermo259 - Thanks for posting the issue. I apologise for the delay in getting back to you. Could you please confirm, you still face the issue or found a solution ? Once you confirmed these details, I can look at the issue. Thanks

**Comment by guillermo259** [comment] 2023-07-03 10:57
I’m having the same issues I’m checking if is my client server. 

Desde Cpanel:

Uso Del Disco
1,66 GB / 10 GB (16,59%)
Uso De Archivos
27.797 / 250.000 (11,12%)
Subdominios
1 / 10 (10%)
Uso Del Disco MySQL®️
97,38 MB / 8,44 GB (1,13%)
Banda Ancha
2,32 GB / ∞
Uso De CPU
0 / 100 (0%)
Procesos Entrantes
0 / 20 (0%)
Uso De Memoria Física
0 bytes / 512 MB (0%)
IOPS
0 / 10.240 (0%)
Uso I/O
0 bytes/s / 10 MB/s (0%)
Número De Procesos
0 / 35 (0%)

I’m not sure if I’m using all the incoming processes and all the processes

**Comment by guillermo259** [comment] 2023-07-03 14:06
In debug and web run good with my server and my client server but if y do the deploy to iOS with my server works but with my client server only work in Android

**Comment by paulVu** [comment] 2023-08-04 13:37
I was fix my issue above, to handle null. and change list view to column. 
`import 'dart:convert';
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:timeago/timeago.dart' as timeago;
import '../../flutter_flow/lat_lng.dart';
import '../../flutter_flow/place.dart';
import '../../flutter_flow/uploaded_file.dart';
import '../../flutter_flow/custom_functions.dart';
import '/backend/backend.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '/backend/schema/structs/index.dart';
import '/auth/firebase_auth/auth_util.dart';

List<FriendStruct> sortFriendsByDate(List<FriendStruct> friends) {
  /// MODIFY CODE ONLY BELOW THIS LINE

  // sorts a list of "friends" objects by the "date" field in decreasing order
  // friends.sort((a, b) => b.date!.compareTo(a.date!));
  // return friends;
  // sorts a list of "friends" objects by the "date" field in decreasing order
  friends.sort((a, b) {
    if (a.date != null && b.date != null) {
      return b.date!.compareTo(a.date!);
    } else if (a.date == null && b.date == null) {
      return 0; // If both dates are null, consider them equal
    } else if (a.date == null) {
      return 1; // If "a" has a null date, it should come after "b"
    } else {
      return -1; // If "b" has a null date, it should come before "a"
    }
  });
  return friends;

  /// MODIFY CODE ONLY ABOVE THIS LINE
}`

**Comment by hariprasadms** [comment] 2023-09-21 19:02
Hi @takashiff - Sorry for being late responding on the issue. Considering the date you submitted the issue and the sub sequent latest FlutterFlow updates, I presume issue has been resolved for you. If the issue is still persists, please update the status we can start investigate the issue. 

Update below details.

1. Blank project with issue steps setup. Project bug report code of the same project ( Not the actual project bug code )
2. What is the Api end points type - Private or public ? If private, has it got proxy setup ? is it accessable through proxy?
3. If possible quick video showing the issue.

**Comment by hariprasadms** [comment] 2023-09-25 15:05
Hi, No recent activities on the issue. Hence close the issue.

**Closed** 2023-09-25 15:05 UTC
Labels: status: needs triage, status: needs information, needs a blank project with issue setup, waiting for user response
