### ISSUE TITLE
Signature Widget no longer working

### ISSUE THREAD

**Issue by Crashdown5** [FlutterFlow/flutterflow-issues#929] opened 2023-05-24 20:42 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Using the signature widget, even in a new blank empty app with only a HomePage, Column, and Signature with no other changes will result in an error during testing mode upon loading the page with the Signature widget.

### Expected Behavior

Expect signature widget to work normally when not using any special modifications

### Steps to Reproduce

1. Create New Empty Project.
2. Add Signature Widget
3. Test Preview

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4whcrl7Yp1rt8B15DtbcdFmioRMjp+R+cVm9VESis8I5TuBOxzZ8neUFtWXL3ndHx6IWaZjTo11vfqidnxC8c4HzOrfrpG1c1xExWXQkKVR5vWCJO/fW1SJ+xPfGKMyMHQnhV/JtNfc3AG1GGuOO+UVg3bQb63Dm0vMvG1JdeK2SrDX1iXc2URm05KZDPz

### Context

Originally trying to add a signature inside of a tabview and was running into this issue whenever the Signature widget was added in. Decided to test on a blank project with nothing else added in and receive the same error so it does not seem related to the other project.

### Visual documentation

![SignatureError](https://github.com/FlutterFlow/flutterflow-issues/assets/134552952/c434e9f2-4df6-4b0a-99bf-4b6c8724380d)
![WidgetTree](https://github.com/FlutterFlow/flutterflow-issues/assets/134552952/fcbb5b2a-84f5-4785-826c-9073aa178f44)

### Environment

```markdown
- FlutterFlow version: 3.1 (released May 23, 2023)
- Platform: Web
- Browser name and version: Tested on Edge(Chromium) 113.0.1774.50 and Firefox 113.0.1
- Operating system and version affected: Windows 10 22H2
```

**Comment by organicnz** [comment] 2023-05-25 14:40
Hi, @Crashdown5. Thanks for adding this issue, mate 🙂

I couldn't reproduce this issue on the Chrome browser. Are you able to reproduce it on Chrome by any chance? 🙂

Screenshot:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/4765090/fd6f84a4-81a0-486e-b73d-8a39fc17698f)

**Comment by Crashdown5** [comment] 2023-05-25 15:27
Hi @organicnz thanks for the reply, I just tried but I am apparently unable to login via Chrome using the Microsoft Authentication option as I used that since we use Microsoft in our company. See the below message. This is on a new Chrome install with nothing else in it. I just tried on Edge in a private session and I receive the same error, same with Firefox. 

I checked the Azure enterprise application, FlutterFlow, that was setup upon first login by FlutterFlow when first using that Microsoft login button. It is reporting in the logs there that it is successful on the Azure end without error.

I do not know if this issue would related to the Signature issue, I just tested it again in Edge as I am still logged in and got the same error.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/134552952/45a0a5b6-fa2b-4b80-9e42-713f46fd6e00)

**Comment by Crashdown5** [comment] 2023-05-25 15:45
To follow up on my last comment, there are no errors in Azure for the interactive login on my end. However there are failure logs that appear to originate on FlutterFlow's end about expired keys. See the screenshot below, I've blurred out what may be sensitive information. Oddly enough on my end I get a MFA request while on FF end its single factor showing in the logs. As the app is not something we created but FlutterFlow did, we cannot generate new keys as far as I am aware.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/134552952/55d32a3c-5d96-4005-a962-3882c6fc1e21)

**Comment by Crashdown5** [comment] 2023-05-25 20:17
Adding more information since I had some more time to test. To rule out authentication issues I reset my FF password, even though one was never setup, and logged in via Chrome. I tested the project with only a column and signature widget and I received the same error I sent in the first screenshot. Using the Preview mode works fine but testing mode does not.

**Comment by organicnz** [comment] 2023-05-26 08:20
@Crashdown5 thanks for testing and providing additional information. 

Yeah, I can confirm that it crashes on `Test mode` and works fine on `Run mode`. Looks like a bug.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/4765090/f5342af4-769b-4b3f-bbd2-322c3b765701)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/4765090/c5d13aad-a810-4a5d-ab80-233ae38bbb2a)

**Comment by victoriahuang1** [comment] 2023-06-01 17:12
Hi @Crashdown5 , thanks for the report. This issue will be fixed upon the next deploy.

**Closed by victoriahuang1** 2023-06-01 17:12 UTC
Labels: type: bug, status: confirmed
