### ISSUE TITLE
Can't copy paste into a drawer correctly

### ISSUE THREAD

**Issue by DanielEdrisian** [FlutterFlow/flutterflow-issues#401] opened 2023-01-24 08:37 UTC
## Expected behavior (required)

Be able to copy the contents of a drawer from one page and paste it into another

## Current behavior (required)

It copies the wrong items

## To Reproduce (required)
1. Create new page
2. Add drawer
3. Add stuff to drawer
4. Copy that stuff
5. Create another page
6. Add drawer
7. Paste into that drawer

### Bug Report Code (required, generate from Widget Tree)

N/A

## Context (required)

Can't copy paste

## Your environment

* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by bulgariamitko** [comment] 2023-01-24 08:58
I had hard time copy widgets in the drawer as well, but then I was able to, but there was something that you can't copy and paste everything. I will mark this as a bug, because the experience is not fluent.

**Comment by DanielEdrisian** [comment] 2023-01-24 23:52
Oh hi Dimitar! 🙂

**Comment by DanielEdrisian** [comment] 2023-01-24 23:52
Sounds good, thanks

**Comment by shelpert** [comment] 2023-04-11 17:43
@bulgariamitko @DanielEdrisian Is this still an issue? Can you give me some examples of what you are copy/pasting, it seems to work fine for me.

**Comment by bulgariamitko** [comment] 2023-04-13 06:45
@shelpert I don't know how FF works, but because I have several keyboards layouts and one of them is Cyrillic when I switch to my Cyrillic keyboard I am not able to do any shortcuts like copy and paste and I guess that is because when I click Control+C FF knows that this is the letter "C", but when I switch my keyboard it turns to the letter "Ц" it will be great if there is some visual saying that this command is not recognized or make it work for any keyboard layout in the word :)

**Comment by shelpert** [comment] 2023-04-14 19:46
Got it, that's a good point! I'll bring that up with the team :)

**Comment by shelpert** [comment] 2023-04-19 23:23
I'm gonna close this issue for now otherwise, since I can't reproduce the issue and I've added the keyboard layout issue to our internal list.

**Closed by shelpert** 2023-04-19 23:23 UTC
Labels: type: bug, status: confirmed
