### ISSUE TITLE
A VideoPlayer view disappears

### ISSUE THREAD

**Issue by nagoyan55** [FlutterFlow/flutterflow-issues#866] opened 2023-05-09 13:22 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After maximize and minimize a VideoPlayer widget, the widget disappears except its controllers.

### Expected Behavior

After controlled, it can be seen normally.

### Steps to Reproduce

1. Create New Page
2. Add a VideoPlayer widget
3. Maximize the widget by its controller button
4. Minimize the widget by its controller button

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfz/Hqx89goctH176JaOxVmWIUQz4cT5MnktVudw4sCKL2O4kQdvWlSFhVYOGiSlZUekSmmnkz+ejFj87qUfUpCAetR754walpED3yZH+QUZOBO6WCYEYnTO1VGG6XyrWvkCJTNrN2LEJg202DN/K8YHTqJr71ImdISq/LZO4=

### Context

In my project, the VideoPlayer widget is wrapped with a Container widget. But it doesn't matter with this problem. I can reproduce it with a naked VideoPlayer widget on new project.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/33846836/157eca35-a2ff-44aa-b48d-6bd7a06e9b82

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform:Web
- Browser name and version: Chrome 112.0.5615.135/112.0.5615.138, Safari 16.0
- Operating system and version affected: Windows, Android, IOS
```

**Comment by wenkaifan0720** [comment] 2023-07-07 20:15
I can confirm that this is an issue with the video player package that we depend on. Unfortunately this package hasn't been updated in a while and we probably will need to find an alternative. Because of the complexity of the matter, I can't give an ETA right now.

**Comment by rzambroni** [comment] 2024-04-25 21:05
Hey everyone! i was trying to re-validate this issue and seems to be fixed now, can you confirm if that's the case on your end as well? 

i'll close this issue for now but if you are still having problems with it please leave a comment and we can take another look.

Thanks!

**Closed by rzambroni** 2024-04-25 21:05 UTC
Labels: type: bug, status: confirmed, priority: low, not in linear
