### ISSUE TITLE
Set value List<String> into a Custom Function

### ISSUE THREAD

**Issue by bulgariamitko** [FlutterFlow/flutterflow-issues#21] opened 2022-09-29 11:45 UTC
## Expected behavior (required)
You can't click Confirm, because it says Available Options - List Contains Item. You should get "No further changes".

## Current behavior (required)
You can't click Confirm nothing is happening and the value is not saved.

## To Reproduce (required)
1. Create a Custom Function which has only one argument List<String> and it is returning the same List<String> value.
2. Create a Local State variable List<String> as well
3. Go to a Page - Click on a Text Widget and Click on Actions
4. Update Local State, Select the Local State that you just create, Set Value, From Variable
5. Choose the Custom Function you just created and then click on Confirm

## Context (required)
You can't use this when using Custom Function with an argument of a List<String>.

## Your environment

* Version of FlutterFlow used: 3.0.5
* Platform (e.g. Web, MacOS Desktop): Web 
* Browser name and version: Chrome 106
* Operating system and version (desktop or mobile): desktop

**Comment by agreaves** [comment] 2022-11-12 00:25
I have not been able to reproduce this issue even after following the steps, could you add a video or screenshot?

**Comment by bulgariamitko** [comment] 2022-12-11 11:21
More information you can get from here. This is the same issue. 
https://community.flutterflow.io/c/discuss-and-get-help/creating-an-article-page-with-multiple-headers-paragraphs#comment_wrapper_13550401

**Comment by agreaves** [comment] 2022-12-19 03:15
Hey! It looks like neither of those issues are related to this issue after all, so I'm going to close this issue as not reproducible (perhaps it's already fixed).

**Closed by agreaves** 2022-12-19 03:15 UTC
Labels: type: bug, status: needs information, priority: low
