### ISSUE TITLE
Hover Color Glitch On Text Field

### ISSUE THREAD

**Issue by BalramShah** [FlutterFlow/flutterflow-issues#5152] opened 2024-12-20 14:27 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Lets say my Scaffold color is light Blue and my text field fill color I set it to White. And I don't any color on hover but There is default hover color which I dont so to nullify it, i kept hover color as white(same as text field fill color). But now, while however its is flashing gray color and then turning white. Its looking very awkward glitched website/app.

### Expected Behavior

If we set text field fill color as white and also text field hover color as white then on hover we shouldn't see any change in color of the text field fill color. 

2nd case: Same If we set both text field fill color and text field hover color as no color, then while hovering there shouldn't be change in color.

### Steps to Reproduce

Create a Page
Set Page scaffold color as #dbe7f9
Add a text field
Add texfeild fill color as white
Add texfeild hover color as white
Run the program
Just mover the mouse over and outside the text field.
Gray color will appear like a glitching.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXl8j6yIhhsshE+pCBasBVpGYwGUAaU40V0t1ETRQbCIj4EIouPfT8SEhDUtCzaH9LfFGjnkQEw9b5vYX9KfJeA0mrRro6/qhcdRPPbDiiaZikDamRPUZ9J+ZVCX3Gy7bYqx54JvtuSWQs2FyqO+TJYz6Cf9qOYwx5e6fDbOY=

### Visual documentation

Its goes away in 0.1 sec and very difficult to capture its image.

### Environment

```markdown
FlutterFlow v5.0.0+ released December 13, 2024
Flutter version is 3.24.2
```

**Comment by BalramShah** [comment] 2024-12-20 14:53
https://github.com/user-attachments/assets/113609be-4ce0-4ac5-baf8-4beed39ce212

See, in preview video, also the recorder i used has mismatch pfs and its not able to capture that 0.01 sec odd looking glitch for every in and out movement of mouse coz on screen its happening for every movement of mouse, however it did capture 1 time at 04 sec of preview video. but its happing every time mouse moves in and moves out.

**Comment by paulperez-dev** [comment] 2024-12-20 20:11
Hi @BalramShah,

I believe this might be a duplicate of #4093. Could you please confirm?

**Comment by BalramShah** [comment] 2024-12-21 08:46
Looks like similar, however I have attached a video how that glitch is looking like and that glitch I faced still active on 20 December. And if its same issue, I guess its flutterflows accountability to decide from here onwards coz I am different user. 

Also if its same, I have no hopes of quick resolution as its reported 2 months plus back and since it takes such time, I cant remain open to discuss further in such lengthy matters.

Thank you for the attention.

**Comment by paulperez-dev** [comment] 2024-12-31 12:14
Hi @BalramShah,

I appreciate the effort you’ve put into this. After reviewing your report, it does appear to align with **#4093**. I completely understand your perspective and frustration regarding the time frame.

We’re closing this issue to consolidate efforts and avoid duplication, but I want to assure you that your video and feedback are valuable and will be linked internally to the original ticket. This helps provide more context, which can aid in resolving the issue.

I understand that long-standing issues can be discouraging, and I apologize for the delay. If there are any updates, we’ll make sure to communicate them through **#4093**.

Thank you again for your understanding and patience.

**Closed as not planned** 2024-12-31 12:14 UTC
Labels: closed: duplicate
