### ISSUE TITLE
Create document action is missing option "Add To Set"  in list type

### ISSUE THREAD

**Issue by benjaminathlan** [FlutterFlow/flutterflow-issues#584] opened 2023-03-08 16:18 UTC
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

<img width="998" alt="CleanShot 2023-03-08 at 15 54 51@2x" src="https://user-images.githubusercontent.com/173659/223762782-26b22e0e-042e-4dce-8101-24b4fbce5ee9.png">

Today it's not possible to add to set on document property list. 

I wanted to add document ref to a list from a "**create document action**" but I only have : 
- Add First Item
- Set Value

So I use a workaround (which is not good because it's costing anoter backend call) : 
Create a document, then update it

### Expected Behavior

Create document action and having the ability to "add to set" in List Ref property

### Steps To Reproduce

1. Create a document called "**_files_**" with a ImagePath property
2. Create a property (list) in this **_files_** document called **userList**  that reference _Users_
3. Create a button in a page for uploading
4. Open Actions
5. Action 1 : Upload media to firebase
6. Action 2 : Create **_files_** document with uploaded files (try to add the current user in **userList** property)
7. Action 3 : AS A WORKAROUND, I'm using upadte document to add userList into it

### Bug Report Code

IT4sz8jf5ZZIpbxK7aqNKflR/SMvJlg7U7gkscp/bxIgGIDzPOw+ZPWkYlhpXs+5dFV+e0SmmXMB/62MvtjlG8cFBzWtc745+s0BbjzveFiie5OBDs/pVHF7J+RQG3KD4J+jnxVSA7JYcXgC2Fyle9zKfBXZH4/4IndISq/LZO4=

### Context

Not blocking cause I found a workaround.

### Additional info

This it this update behavios
<img width="1084" alt="CleanShot 2023-03-08 at 15 54 59@2x" src="https://user-images.githubusercontent.com/173659/223768036-5f9b4c51-e897-4635-b669-effc77a8f115.png">

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: iOS, Android, Web
- Browser name and version: Chrome, ARC
- Operating system and version affected: Mac Silicon M1 (Ventura 13.0)
```

**Comment by aemelyanovff** [comment] 2023-03-10 20:43
@benjaminathlan This is by design. "Add to Set" only makes sense when updating an existing document. When you are creating a new document, there's nothing to add to. You can either specify one element of the new set (Add First Item) or the entire set (Set Value).

What would you expect "Add to Set" to do when creating a new document? What would it add to?

**Comment by aemelyanovff** [comment] 2023-03-16 13:48
Closing the issue. @benjaminathlan please feel free to reopen if you disagree.

**Closed by aemelyanovff** 2023-03-16 13:48 UTC
Labels: type: bug, status: confirmed
