### ISSUE TITLE
Callback parameter invalid value

### ISSUE THREAD

**Issue by ghost** [FlutterFlow/flutterflow-issues#3200] opened 2024-06-22 10:08 UTC
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When trying to use the callback parameter from an action parameter of a component there is an issue that the parameter is invalid.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/172298955/f0172dd7-e122-4332-aeb0-3c13d2f7a1c7)

### Expected Behavior

You should be able to normally use the callback parameter.

### Steps to Reproduce

1. Create a component that is used as a child inside a list
2. Add an action parameter to the component with its parameter with a string for example
3. Use the action "execute callback" with that component action parameter
4. In the main page where you are using the component try to use the passed string parameter from the callback to set a page state for example.
5. There is an issue that the string passed parameter is invalid with "?"

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/172298955/f0172dd7-e122-4332-aeb0-3c13d2f7a1c7)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gk8nqy4xOxeEA15CBbO9WmSoQG0g1bb00sNtuTQIdCYDuBIYiaeP7fldvZPWgTXNPKEWIhjk1+dLPjdjDA8A7E02sQLZJ1rhIFBaXUl+/aoSPDaigXkBQO+dYGWK936avgBNRKthYWmBm7173GuivEzXdGZ/4Zwh9f6PHaOI=

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/172298955/f0172dd7-e122-4332-aeb0-3c13d2f7a1c7)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.61 released June 21, 2024
Flutter version is 3.19.1
- Platform: MacOs Desktop App FlutterFlow
- Browser name and version: Chrome
- Operating system and version affected: MacOs
```

**Comment by paulperez-dev** [comment] 2024-06-24 19:07
Hi @marinoKhalas! This seems to be a duplicate of [https://github.com/FlutterFlow/flutterflow-issues/issues/2305](https://github.com/FlutterFlow/flutterflow-issues/issues/2305), which is in **beta** (to be released in the following days). I will be closing this issue.

**Comment by paulperez-dev** [comment] 2024-06-24 20:28
Hi @marinoKhalas! I can't find the issue in your project (it is also a very complicated project). Can you please confirm if you solved the issue? If not, please share a bug report code from a blank project so I can quickly triage the issue.

Thanks!

**Comment by paulperez-dev** [comment] 2024-07-03 19:10
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Closed as not planned by paulperez-dev** 2024-07-03 19:10 UTC
Labels: closed: other
